var QUIZ_DATA = [
  {
    tag: "AWS Organizations",
    q: "¿Qué habilita AWS Organizations que no existe al gestionar cuentas de AWS de forma completamente independiente?",
    options: [
      "Facturación consolidada, jerarquía de OUs con guardrails heredables (SCP/RCP/Declarative) y compartición de recursos entre cuentas",
      "Facturación consolidada únicamente: las políticas de seguridad se siguen aplicando cuenta por cuenta, sin ninguna herencia entre ellas",
      "Consolida todas las cuentas en una sola, de modo que deja de ser necesario mantener múltiples cuentas de AWS separadas",
      "Herencia automática de las políticas de IAM de la cuenta de management hacia las identidades de todas las cuentas miembro",
    ],
    correct: 0,
    explain: "Organizations permite estructurar cuentas en OUs jerárquicas, aplicar guardrails que se heredan automáticamente por OU (SCPs, RCPs, Declarative Policies, AI opt-out policies), facturación consolidada, y compartir recursos (vía RAM) o gestionar servicios de seguridad de forma centralizada. Lo que <strong>no</strong> hace es propagar políticas de identidad de IAM: cada cuenta sigue teniendo su propio IAM. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Control Tower",
    q: "¿Qué automatiza AWS Control Tower que AWS Organizations por sí solo no hace?",
    options: [
      "Nada adicional: es simplemente la consola web de AWS Organizations, con exactamente las mismas capacidades y otro nombre comercial",
      "Despliega una landing zone completa: OUs recomendadas, cuentas Log Archive y Audit, controles preconfigurados y Account Factory",
      "Solo la gestión de la facturación consolidada y de los presupuestos de las cuentas miembro de la organización",
      "Aplica SCPs a la cuenta de management, algo que AWS Organizations por sí solo no puede hacer en ningún caso",
    ],
    correct: 1,
    explain: "Control Tower se construye <strong>sobre</strong> Organizations, automatizando el despliegue de una landing zone completa: estructura de OUs, cuentas Log Archive y Audit ya creadas y configuradas, controles preventivos y detectivos ya activados, y Account Factory para que cada cuenta nueva nazca conforme. Ni Control Tower ni Organizations someten la cuenta de management a las SCP. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Controles de Control Tower",
    q: "En Control Tower, ¿qué diferencia a un control PREVENTIVO de uno DETECTIVO?",
    options: [
      "Ambos bloquean la acción; se diferencian solo en si se aplican a una OU o a una cuenta miembro concreta",
      "El detectivo bloquea la llamada de API y el preventivo se limita a registrarla en CloudTrail",
      "El preventivo impide que la acción no conforme ocurra, normalmente vía una SCP que deniega la API",
      "El preventivo solo puede aplicarse a nivel de OU y el detectivo solo a nivel de cuenta miembro",
    ],
    correct: 2,
    explain: "Preventivo = bloquea <strong>antes</strong> (ej. una SCP que deniega crear buckets S3 públicos). Detectivo = detecta <strong>después</strong> (ej. una Config Rule que marca como NON_COMPLIANT un bucket que ya quedó público por otro camino). Ambos tipos se aplican a OUs y cuentas; Control Tower los combina, y añade además controles <em>proactivos</em> que validan plantillas de CloudFormation antes del despliegue. <a href=\"https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AI services opt-out policies",
    q: "Tu organización maneja datos altamente confidenciales y quiere garantizar que NINGÚN servicio de IA/ML de AWS (como ciertas funciones de mejora de modelos) use esos datos para entrenamiento, en todas las cuentas de la organización. ¿Qué mecanismo de Organizations aplicas?",
    options: [
      "Una SCP que deniegue las acciones de todos los servicios de IA en las cuentas de la organización",
      "Una RCP aplicada al servicio Amazon Bedrock, que cubre el resto de servicios de IA por herencia",
      "Activar GuardDuty con protección de datos de IA en todas las cuentas de la organización",
      "Una AI services opt-out policy aplicada a la raíz de la organización, heredada por las cuentas",
    ],
    correct: 3,
    explain: "Las AI services opt-out policies son un tipo de política de organización dedicado (junto a SCP, RCP y Declarative Policies) pensado específicamente para controlar de forma centralizada y heredable si los servicios de IA de AWS pueden usar los datos de tus cuentas para entrenamiento/mejora de modelos. Denegar acciones con una SCP impediría <em>usar</em> el servicio, que es un objetivo distinto. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_ai-opt-out.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Delegated administrator",
    q: "¿Por qué se recomienda designar una cuenta 'delegated administrator' para servicios como GuardDuty, Security Hub o IAM Access Analyzer, en vez de gestionarlos desde la cuenta de management?",
    options: [
      "Reduce el uso diario de la cuenta de management y permite al equipo de seguridad operar desde una cuenta dedicada",
      "Es un requisito técnico: GuardDuty y Security Hub no pueden habilitarse desde la cuenta de management",
      "Duplica los hallazgos en las dos cuentas, lo que aporta redundancia en caso de que una de ellas se vea comprometida",
      "Solo está disponible en organizaciones gestionadas con Control Tower, no con AWS Organizations a secas",
    ],
    correct: 0,
    explain: "La buena práctica es minimizar el uso day-to-day de la cuenta de management (comprometerla comprometería potencialmente TODA la organización). Delegar la administración de servicios de seguridad a una cuenta dedicada (típicamente 'Audit' o 'Security Tooling') permite al equipo de seguridad operar con visibilidad de toda la organización sin tocar la cuenta de management: es una recomendación, no una imposición técnica. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_best-practices_mgmt-acct.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Root user & break-glass",
    q: "¿Qué es un procedimiento 'break-glass' en el contexto de gestión de la cuenta root?",
    options: [
      "Un proceso para eliminar de forma permanente el usuario root de todas las cuentas miembro",
      "Un proceso de emergencia documentado y auditado para usar el root cuando es imprescindible",
      "Una alarma de CloudWatch que avisa cada vez que alguien inicia sesión con el usuario root",
      "Una política que obliga a rotar la contraseña del usuario root cada noventa días en todas las cuentas",
    ],
    correct: 1,
    explain: "Break-glass describe el acceso de emergencia: las credenciales root no se usan <strong>nunca</strong> para operación diaria (con MFA hardware guardado de forma segura, a menudo con doble custodia), y solo se accede a través de un procedimiento documentado, auditado y con aprobación cuando surge una necesidad excepcional. La alarma de inicio de sesión root es un control detectivo complementario, no el procedimiento en sí. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/root-user-best-practices.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Root access management centralizado",
    q: "¿Qué capacidad de Organizations permite gestionar de forma centralizada las credenciales root de las cuentas MIEMBRO sin tener que hacer el proceso de recuperación de contraseña en cada una?",
    options: [
      "IAM Identity Center, que federa también las credenciales root de las cuentas miembro",
      "AWS Config, con una regla que detecta y elimina las credenciales root sin gestionar",
      "Centralized root access management, desde la cuenta de management de la organización",
      "Amazon Detective, que correlaciona el uso de credenciales root entre cuentas",
    ],
    correct: 2,
    explain: "Centralized root access management permite gestionar el acceso root de las cuentas miembro desde la cuenta de management, reduciendo drásticamente el riesgo de credenciales root sueltas y sin gestionar en decenas de cuentas. IAM Identity Center federa identidades <em>IAM</em>, nunca el usuario root; Config y Detective solo observan, no retiran credenciales. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Infrastructure as Code a escala",
    q: "¿Qué servicio de AWS permite desplegar el MISMO stack de CloudFormation (ej. una configuración base de seguridad) automáticamente en cientos de cuentas y regiones de una organización, de forma centralizada?",
    options: [
      "AWS Config Conformance Packs, que despliegan plantillas de CloudFormation en cada cuenta",
      "AWS Service Catalog, que impone el despliegue del producto en todas las cuentas de la OU",
      "AWS Resource Access Manager, compartiendo el stack con el resto de cuentas de la organización",
      "AWS CloudFormation StackSets, con despliegue automático a las cuentas nuevas de una OU",
    ],
    correct: 3,
    explain: "StackSets extiende CloudFormation para gestionar el mismo stack como una unidad a través de múltiples cuentas/regiones, con integración con AWS Organizations para desplegar <strong>automáticamente</strong> en cuentas que se unan a una OU en el futuro. Los conformance packs despliegan reglas de Config, no infraestructura arbitraria; Service Catalog ofrece productos en autoservicio, no despliegue impuesto. <a href=\"https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Validación de IaC",
    q: "¿Qué diferencia a CloudFormation Guard de cfn-lint?",
    options: [
      "cfn-lint valida sintaxis y buenas prácticas; Guard evalúa la plantilla contra reglas propias",
      "cfn-lint escribe reglas de política propias; Guard solo comprueba la sintaxis de la plantilla",
      "Guard valida plantillas en tiempo de despliegue; cfn-lint bloquea la llamada de API en runtime",
      "cfn-lint evalúa recursos ya desplegados; Guard sustituye a las SCP como guardrail en runtime",
    ],
    correct: 0,
    explain: "cfn-lint es un linter general (sintaxis, tipos de recursos válidos, mejores prácticas). CloudFormation Guard es un motor de <em>policy-as-code</em> donde tú escribes las reglas de negocio/seguridad que la plantilla debe cumplir. Ambos actúan sobre la plantilla en el pipeline de CI/CD (shift-left), nunca sobre recursos ya desplegados, y complementan —no sustituyen— los guardrails en runtime como SCP o Config. <a href=\"https://docs.aws.amazon.com/cfn-guard/latest/ug/what-is-guard.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Estrategia de tagging",
    q: "Más allá de la organización visual, ¿qué caso de uso de seguridad/gobierno habilita una estrategia de tagging consistente (ej. tag 'environment' o 'data-classification')?",
    options: [
      "Ninguno: los tags solo afectan a la presentación de recursos en la consola de AWS",
      "Habilita ABAC, conformance packs y SCPs condicionales que se aplican según el tag del recurso",
      "Solo alimentan Cost Explorer y los informes de facturación, sin efecto sobre el acceso",
      "Sustituyen a las políticas de IAM en aquellos recursos que llevan un tag de clasificación de datos",
    ],
    correct: 1,
    explain: "Una estrategia de tagging consistente es la base de <strong>ABAC</strong> (visto en el módulo de IAM), de conformance packs condicionales, y de la capacidad de responder rápido durante un incidente ('¿qué recursos son de producción?', '¿quién es el owner?'). Los tags no sustituyen a IAM: son un <em>insumo</em> de las condiciones de las políticas, que siguen siendo necesarias. <a href=\"https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Firewall Manager",
    q: "Tienes WAF, Security Groups y AWS Network Firewall desplegados de forma inconsistente en decenas de cuentas, y quieres aplicar y mantener una política de seguridad de red uniforme en todas ellas desde un único lugar. ¿Qué servicio usas?",
    options: [
      "AWS RAM, compartiendo las reglas de WAF y los security groups con el resto de cuentas",
      "AWS Config Rules, que detectan las desviaciones y las corrigen en cada cuenta miembro",
      "AWS Firewall Manager, que aplica y mantiene las políticas de red en todas las cuentas",
      "Amazon Inspector, que evalúa la exposición de red y ajusta los security groups afectados",
    ],
    correct: 2,
    explain: "Firewall Manager centraliza la gestión de políticas de seguridad de red y de aplicación (WAF, Shield Advanced, Security Groups, Network Firewall, Route 53 Resolver DNS Firewall) a nivel de organización, aplicándolas automáticamente incluso a recursos y cuentas <strong>nuevas</strong>. Config detecta y puede remediar, pero no distribuye políticas de WAF; Inspector evalúa vulnerabilidades y alcanzabilidad, no aplica configuración. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Compartir recursos entre cuentas",
    q: "Quieres compartir una VPC (subnets), un Transit Gateway, o una regla de Firewall Manager entre varias cuentas de tu organización SIN duplicar el recurso ni usar peering/AssumeRole para cada acceso. ¿Qué servicio usas?",
    options: [
      "AWS Config Aggregator, que expone los recursos de red del resto de cuentas de la organización",
      "AWS Service Catalog, que despliega una copia idéntica de la VPC en cada cuenta consumidora",
      "VPC peering entre las cuentas, replicando las subnets necesarias en cada una de ellas",
      "AWS Resource Access Manager (RAM), compartiendo el recurso con las cuentas de la organización",
    ],
    correct: 3,
    explain: "AWS RAM permite compartir recursos concretos (subnets de una VPC, Transit Gateways, License Manager configurations, reglas de Firewall Manager, etc.) directamente con otras cuentas de la organización o con cuentas externas específicas, evitando duplicación de infraestructura (modelo de <em>shared VPC</em>). El aggregator solo agrega datos de configuración; Service Catalog y el peering implican duplicar o interconectar, no compartir. <a href=\"https://docs.aws.amazon.com/ram/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Service Catalog",
    q: "¿Qué problema resuelve AWS Service Catalog en un contexto de gobierno multi-cuenta?",
    options: [
      "Ofrece a los equipos plantillas de infraestructura preaprobadas que despliegan en autoservicio",
      "Sustituye a CloudFormation como motor de despliegue de infraestructura en toda la organización",
      "Publica el catálogo de precios de AWS para estimar el coste de cada despliegue aprobado",
      "Distribuye exclusivamente software de terceros del AWS Marketplace a las cuentas miembro",
    ],
    correct: 0,
    explain: "Service Catalog permite empaquetar plantillas de IaC ya revisadas y aprobadas como 'productos' que los equipos despliegan en autoservicio, sin necesitar permisos amplios de creación de recursos: equilibrio entre velocidad de desarrollo y control centralizado. No sustituye a CloudFormation —se apoya en él— y admite productos propios, no solo software del Marketplace. <a href=\"https://docs.aws.amazon.com/servicecatalog/latest/adminguide/introduction.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Config aggregators",
    q: "¿Qué permite un AWS Config Aggregator?",
    options: [
      "Aplica el mismo conjunto de reglas de Config en todas las cuentas, como un conformance pack",
      "Consolida el estado de compliance de varias cuentas y regiones en una única vista",
      "Agrega los resultados de las reglas dentro de una sola cuenta, región por región",
      "Sustituye a Security Hub como consola central de hallazgos de seguridad multi-cuenta",
    ],
    correct: 1,
    explain: "Un Config Aggregator recopila datos de configuración y compliance de múltiples cuentas fuente (y regiones) en una cuenta agregadora, dando una vista consolidada de qué recursos son NON_COMPLIANT en toda la organización. <strong>Agregar no es desplegar</strong>: para aplicar las mismas reglas en todas partes hacen falta reglas u organización de conformance packs a nivel de organización. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Audit Manager vs AWS Artifact",
    q: "¿Cuál es la diferencia entre AWS Audit Manager y AWS Artifact?",
    options: [
      "Son el mismo servicio: Artifact es la consola y Audit Manager su API equivalente",
      "Artifact recopila evidencia de tu cuenta y Audit Manager entrega los certificados de AWS",
      "Audit Manager recopila evidencia de tu entorno; Artifact entrega los informes de AWS",
      "Ambos solo pueden usarse desde la cuenta de management y cubren únicamente us-east-1",
    ],
    correct: 2,
    explain: "Audit Manager automatiza la recolección continua de <strong>evidencia de tu propio entorno</strong> (config, logs, políticas) organizada según el framework que elijas (PCI-DSS, HIPAA…), para tus auditorías. AWS Artifact es la biblioteca de <strong>informes y certificaciones de AWS</strong> como proveedor (SOC, ISO, PCI) y donde se aceptan acuerdos como el BAA. La opción que invierte los dos roles es el error clásico. <a href=\"https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Well-Architected Tool",
    q: "¿Para qué se usa la AWS Well-Architected Tool en el contexto de gobierno de seguridad?",
    options: [
      "Desplegar automáticamente la infraestructura que corrige los riesgos detectados",
      "Evaluar exclusivamente cargas de trabajo de machine learning frente al lente específico de ML",
      "Calcular el coste mensual exacto de una carga de trabajo antes de desplegarla",
      "Evaluar una carga frente a las buenas prácticas de los seis pilares y priorizar riesgos",
    ],
    correct: 3,
    explain: "La Well-Architected Tool guía una revisión estructurada (normalmente vía workshop con el equipo) de una carga de trabajo contra las mejores prácticas de AWS en los seis pilares —incluido Security—, señalando riesgos altos/medios y generando un plan de remediación priorizado. Es una herramienta de <em>evaluación</em>: no despliega ni remedia nada por sí misma, y los lentes de ML son solo uno más entre muchos. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SCP vs RCP vs Declarative vs AI opt-out (repaso)",
    q: "Repaso de los 4 tipos de políticas de organización: ¿cuál es la única pensada específicamente para el uso de datos por servicios de IA/ML, y no para permisos ni configuración?",
    options: [
      "AI services opt-out policy: controla el uso de tus datos por los servicios de IA",
      "Resource Control Policy (RCP): fija el techo de acceso a los datos de tus recursos",
      "Service Control Policy (SCP): acota los permisos máximos de las identidades",
      "Declarative Policy: fuerza un estado de configuración duradero en EC2, VPC y EBS",
    ],
    correct: 0,
    explain: "SCP = techo de permisos de <em>identidad</em>. RCP = techo de acceso a los <em>recursos</em>, incluidos principals externos. Declarative Policy = fuerza un <em>estado de configuración</em>. AI services opt-out policy = el único tipo dedicado a controlar si los servicios de IA de AWS pueden usar tus datos para mejorar sus modelos. Los cuatro son políticas de organización, pero cada una resuelve un problema distinto. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Notificaciones de compliance",
    q: "Además de remediar automáticamente un recurso NON_COMPLIANT detectado por Config, ¿qué mecanismo se usa típicamente para notificar al equipo responsable (skill 6.3.1)?",
    options: [
      "Config no emite eventos: hay que consultar el estado de compliance por API cada día",
      "EventBridge captura el cambio de compliance y lo enruta a SNS o a un runbook de SSM",
      "Solo revisando manualmente el panel de Config en cada cuenta y región de la organización",
      "Únicamente abriendo un caso de AWS Support desde la cuenta de auditoría de la organización",
    ],
    correct: 1,
    explain: "El patrón estándar es: Config detecta el cambio de compliance &rarr; EventBridge captura el evento &rarr; se enruta a SNS para notificar humanos, y/o dispara un runbook de Systems Manager Automation para remediar. Es el mismo patrón de <strong>EventBridge como bus central</strong> que se repite en detección (Domain 1) y en respuesta a incidentes (Domain 2). <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/monitor-config-with-cloudwatchevents.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Landing zone existente vs nueva",
    q: "¿Puede Control Tower aplicarse a una organización de AWS que YA existe, con decenas de cuentas ya en uso, o solo sirve para organizaciones completamente nuevas?",
    options: [
      "Solo sirve para organizaciones nuevas: exige crear la organización desde la propia consola",
      "Exige migrar antes todas las cuentas existentes a la región en la que se despliega la landing zone",
      "Extiende la landing zone sobre una organización existente, incorporando cuentas poco a poco",
      "Solo admite cuentas sin recursos desplegados: las que ya tienen cargas deben recrearse",
    ],
    correct: 2,
    explain: "Aunque Control Tower nació pensado para nuevas implementaciones, soporta explícitamente el caso de <strong>landing zone existente</strong>: se puede desplegar sobre una organización ya en uso e ir incorporando (<em>enroll</em>) las cuentas actuales a la estructura de OUs y controles de forma incremental, sin un big-bang de migración ni recrear cuentas. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Declarative Policies: VPC Block Public Access",
    q: "El equipo de seguridad quiere garantizar que NINGUNA VPC de la organización, presente o futura, permita tráfico de entrada desde internet a través de un internet gateway, sin tener que auditar route tables o NACLs cuenta por cuenta, y con la posibilidad de revertir el cambio si algo se rompe. ¿Qué mecanismo es el más adecuado?",
    options: [
      "Editar manualmente las NACLs y las route tables de cada VPC existente en cada cuenta",
      "Una SCP que deniegue ec2:CreateInternetGateway en todas las cuentas de la organización",
      "Una Config Rule detectiva que marque las VPC expuestas y avise al equipo responsable",
      "Una Declarative Policy que active VPC Block Public Access a nivel de OU u organización",
    ],
    correct: 3,
    explain: "Las Declarative Policies cubren EC2/VPC/EBS a escala forzando un <strong>estado</strong> de configuración, no solo bloqueando llamadas de API como una SCP. VPC Block Public Access bloquea el ingress público vía internet gateway de forma centralizada, no destructiva y reversible, aplicándose también a VPCs futuras. Una SCP sobre ec2:CreateInternetGateway no cambia el estado de los IGW <em>ya existentes</em>. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Declarative Policies: proveedores de AMI permitidos",
    q: "Tras la publicación de investigaciones sobre el ataque 'whoAMI' (donde un atacante publica una AMI pública con un nombre que coincide con el patrón que busca código mal configurado), tu organización quiere restringir de forma centralizada qué propietarios de AMI pueden usarse para lanzar instancias EC2 en TODAS las cuentas, ocultando además cualquier AMI no conforme en consola y CLI. ¿Qué solución aplicas?",
    options: [
      "Una Declarative Policy de EC2 'Allowed AMIs' aplicada a toda la organización",
      "Una SCP con una condición sobre ec2:Owner replicada en la política de cada cuenta",
      "Una Config Rule detectiva que marque como no conformes las instancias ya lanzadas",
      "Un permission boundary de IAM en cada rol que pueda lanzar instancias EC2",
    ],
    correct: 0,
    explain: "'Allowed AMIs' es una de las configuraciones de EC2 soportadas por las Declarative Policies: define qué proveedores de AMI son válidos para toda la organización, bloqueando el lanzamiento y <strong>ocultando en consola y CLI</strong> cualquier AMI de un proveedor no permitido. Es preventivo y heredable; la Config Rule llega tarde y los boundaries hay que mantenerlos rol a rol. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Tag Policies: enforcement en IaC",
    q: "Detectas que varios equipos crean recursos vía CloudFormation, Terraform y Pulumi sin incluir el tag obligatorio 'cost-center', y quieres bloquear (o al menos advertir) esos despliegues ANTES de que el recurso se cree, sin implementar una validación distinta para cada herramienta de IaC. ¿Qué capacidad de Organizations usas?",
    options: [
      "CloudFormation Guard, configurado a mano en el pipeline de cada equipo y herramienta",
      "Una Tag Policy con claves obligatorias y el hook de validación en modo Warn o Fail",
      "Una SCP que deniegue la acción CreateTags cuando no se indique un valor para el tag",
      "Una Config Rule 'required-tags', que evalúa el recurso una vez ya ha sido creado",
    ],
    correct: 1,
    explain: "Las Tag Policies de Organizations permiten definir claves de tag obligatorias y aplicarlas directamente sobre despliegues de infraestructura como código (CloudFormation, Terraform y Pulumi) mediante un hook de validación con modo <strong>Warn</strong> (advierte pero permite) o <strong>Fail</strong> (bloquea el despliegue): gobierno de tagging <em>shift-left</em>, antes de crear el recurso, y sin una integración distinta por herramienta. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_tag-policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Tag Policies vs RCP",
    q: "Quieres impedir que cualquier identidad, incluida una con permisos amplios, pueda ELIMINAR o MODIFICAR el tag 'data-classification' de un recurso una vez asignado — no solo estandarizar qué valores son válidos para ese tag. ¿Qué mecanismo resuelve específicamente ese requisito?",
    options: [
      "Una Tag Policy, que además de estandarizar valores impide borrar los tags ya definidos en el recurso",
      "Una Declarative Policy de tagging aplicada a la OU en la que residen esos recursos",
      "Una RCP o SCP que deniegue tag:TagResource y tag:UntagResource salvo a principals autorizados",
      "Un Config Aggregator con alertas en tiempo real ante cualquier cambio de ese tag",
    ],
    correct: 2,
    explain: "Las Tag Policies <strong>estandarizan y reportan</strong> qué claves y valores son válidos (e incluso bloquean despliegues de IaC sin los tags requeridos), pero no son un mecanismo de control de permisos sobre la acción de etiquetar o desetiquetar. Para impedir que alguien borre o cambie un tag concreto hace falta una política de permisos (RCP o SCP) que deniegue esas acciones: son controles complementarios, no intercambiables. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Resource Control Policies: alcance de servicios soportados",
    q: "Tu equipo quiere usar una RCP para restringir el acceso externo a tablas de Amazon DynamoDB en todas las cuentas, igual que ya hacen con buckets S3. ¿Qué deberías verificar primero antes de asumir que funcionará igual?",
    options: [
      "Nada: las RCP cubren todas las acciones de todos los servicios, igual que las SCP",
      "Que Control Tower esté desplegado, ya que las RCP dependen de su landing zone",
      "Que la cuenta de management tenga MFA físico, requisito para activar las RCP",
      "Que DynamoDB figure entre los servicios que las RCP soportan en ese momento",
    ],
    correct: 3,
    explain: "A diferencia de las SCP (que actúan como techo de permisos sobre cualquier acción de IAM), las <strong>RCP solo cubren un conjunto específico de servicios</strong> que AWS ha ido ampliando desde su lanzamiento en noviembre de 2024. Antes de diseñar un control de perímetro de datos con RCP sobre un servicio concreto hay que confirmar que ya está soportado, o el control simplemente no tendrá efecto. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Config a nivel de organización",
    q: "Hasta hace poco, para desplegar centralizadamente una regla de Config nueva en toda la organización era necesario empaquetarla dentro de un conformance pack. ¿Qué capacidad reciente de AWS Config elimina esa necesidad?",
    options: [
      "Config despliega reglas individuales a nivel de organización, sin empaquetarlas",
      "Solo se logra replicando cada regla con CloudFormation StackSets en todas las cuentas",
      "El Config Aggregator despliega las reglas nuevas en las cuentas fuente automáticamente",
      "No es posible: desplegar a nivel de organización sigue exigiendo un conformance pack",
    ],
    correct: 0,
    explain: "AWS Config amplió la gestión a nivel de organización para incluir no solo conformance packs completos, sino también <strong>reglas individuales</strong>, simplificando el gobierno de compliance multi-cuenta cuando solo se necesita una regla puntual. Complementa (no sustituye) el uso de conformance packs para conjuntos grandes de reglas relacionadas, y no depende del aggregator, que solo consolida resultados. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Control Tower Landing Zone 4.0",
    q: "Tras migrar a la versión 4.0 de la landing zone de Control Tower, ¿qué cambio arquitectónico relevante ocurre respecto a cómo se agregaban antes los datos de compliance de AWS Config entre cuentas?",
    options: [
      "AWS Config desaparece de la landing zone y Security Hub asume la evaluación de compliance",
      "Los dos aggregators previos se sustituyen por un Service-Linked Config Aggregator (SLCA)",
      "La agregación central desaparece y el compliance se consulta cuenta por cuenta",
      "Hay que desplegar a mano un Config Aggregator adicional después de migrar la landing zone",
    ],
    correct: 1,
    explain: "La landing zone 4.0 introduce integraciones de servicio opcionales y <strong>recursos dedicados por servicio</strong> (Config y CloudTrail ya no comparten buckets S3 ni topics SNS), y migra la agregación de compliance a un Service-Linked Config Aggregator desplegado en la cuenta de integración de Config, retirando el aggregator de organización (en management) y el de cuenta (en Audit) usados antes. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Control Tower: biblioteca de controles",
    q: "Un responsable de compliance pregunta cómo ha evolucionado la cobertura de controles preconfigurados de Control Tower para poder mapearla contra sus requisitos regulatorios. ¿Qué afirmación es correcta sobre esa biblioteca de controles?",
    options: [
      "Se mantiene fija desde el lanzamiento del servicio, sin controles nuevos desde entonces",
      "Solo quedan controles preventivos: los detectivos se retiraron de la biblioteca en 2025",
      "Se ha ampliado con cientos de controles de Config, agrupables en conformance packs",
      "Está limitada a cincuenta controles por organización por una restricción del servicio",
    ],
    correct: 2,
    explain: "Control Tower ha seguido ampliando de forma sustancial su catálogo de controles basados en Config (cientos de controles nuevos incorporados en 2025), activables a nivel de cuenta o de organización y agrupables mediante conformance packs. Una organización que evaluó su cobertura hace un año probablemente esté dejando de aprovechar controles nuevos relevantes para su marco regulatorio. <a href=\"https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Control Tower: resolución automática de drift de SCP",
    q: "Un ingeniero modifica, fuera de la consola de Control Tower, una SCP administrada por el servicio: la adjunta también a otra OU distinta a la prevista. Antes esto quedaba marcado como 'drift' de gobernanza que requería intervención. ¿Qué mejora reciente de Control Tower afecta a este escenario?",
    options: [
      "Control Tower bloquea ahora cualquier cambio manual sobre las SCP que administra",
      "Solo un Config Aggregator personalizado puede detectar ese tipo de cambio de SCP",
      "El concepto de drift de gobernanza ha desaparecido por completo del servicio Control Tower",
      "Control Tower resuelve por sí solo ciertos drifts de SCP sin re-registrar la landing zone",
    ],
    correct: 3,
    explain: "Control Tower amplió en 2025 el manejo de drift de SCPs administradas: ciertos tipos de cambio (una SCP de un control quedando adjunta a otra OU o a una cuenta miembro por una acción fuera de la consola) ahora los <strong>resuelve automáticamente el propio servicio</strong>, en vez de quedar como drift persistente que bloquea operaciones de la landing zone hasta remediarlo a mano. El drift sigue existiendo como concepto. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/drift.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Centralized Root Access Management: sesiones con alcance de tarea",
    q: "Necesitas restaurar el acceso a un bucket S3 cuya política quedó mal configurada en una cuenta miembro — tarea que tradicionalmente exigía usar las credenciales root de esa cuenta. Con Centralized Root Access Management activo, ¿cómo se resuelve esto sin recuperar la contraseña root de la cuenta miembro?",
    options: [
      "Se invoca una sesión root con alcance de tarea sobre esa cuenta, sin credenciales",
      "Se lanza el flujo de recuperación de contraseña asociado al email root de esa cuenta",
      "Solo es posible si la cuenta miembro usa IAM Identity Center como fuente de identidad",
      "Hay que abrir un caso de soporte de pago con AWS para cada restauración de este tipo",
    ],
    correct: 0,
    explain: "Centralized Root Access Management (noviembre de 2024) permite invocar desde la cuenta de management o la delegated admin un conjunto acotado de acciones root <strong>con alcance de tarea</strong> (<code>sts:AssumeRoot</code>) sobre cuentas miembro, como restaurar el acceso a un bucket S3 o a una cola SQS, sin credenciales root de larga duración; además, las cuentas nuevas pueden nacer sin credenciales root utilizables. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Audit Manager: maintenance mode",
    q: "Estás diseñando la estrategia de recopilación continua de evidencia de compliance para una organización que va a incorporar cuentas NUEVAS a partir de mediados de 2026. Un compañero propone usar AWS Audit Manager en esas cuentas nuevas. ¿Qué deberías tener en cuenta?",
    options: [
      "Sigue siendo la opción recomendada, sin limitaciones para incorporar cuentas nuevas",
      "Audit Manager está en modo mantenimiento y no admite cuentas ni regiones nuevas",
      "Audit Manager se ha retirado y ha dejado de funcionar también en las cuentas actuales",
      "Audit Manager pasa a ser gratuito e ilimitado en todas las cuentas de la organización",
    ],
    correct: 1,
    explain: "AWS anunció que Audit Manager entra en <strong>modo mantenimiento</strong>: desde el 30 de abril de 2026 deja de poder configurarse en cuentas o regiones nuevas. Los clientes que ya lo tenían configurado antes de esa fecha siguen usándolo con normalidad (incluido crear nuevos assessments) en esa cuenta/región, pero sin nuevas funcionalidades ni soporte para nuevos frameworks o servicios. <a href=\"https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Service Catalog AppRegistry: maintenance mode",
    q: "Planeabas usar AWS Service Catalog AppRegistry para agrupar lógicamente recursos por aplicación y aplicar tags de forma consistente en cuentas que se crearán después de julio de 2026. ¿Qué deberías saber al respecto?",
    options: [
      "AppRegistry acaba de ampliar su disponibilidad a más regiones que nunca",
      "AppRegistry sustituye a AWS Config para el inventario de recursos por aplicación",
      "AppRegistry entra en modo mantenimiento; usa Resource Groups o Resource Explorer",
      "Todo AWS Service Catalog, no solo AppRegistry, deja de funcionar en esa fecha",
    ],
    correct: 2,
    explain: "AWS anunció que AppRegistry (el componente de Service Catalog para agrupar recursos por aplicación) pasa a <strong>modo mantenimiento</strong>, sin apertura a nuevos clientes desde el 30 de julio de 2026 ni nuevas funcionalidades o regiones. Los clientes existentes conservan el servicio, y para necesidades nuevas de agrupación y tagging AWS recomienda Resource Groups y Resource Explorer, sin coste adicional. <a href=\"https://docs.aws.amazon.com/servicecatalog/latest/adminguide/introduction.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Firewall Manager & Shield Advanced: Anti-DDoS managed rule group",
    q: "Gestionas políticas de AWS Firewall Manager que incluyen protección con Shield Advanced para cargas de trabajo detrás de ALB y CloudFront. AWS anunció un cambio en cómo Shield Advanced mitiga ataques de capa de aplicación (L7). ¿En qué consiste ese cambio?",
    options: [
      "El cambio afecta solo a AWS Network Firewall, no a Shield Advanced ni a Firewall Manager",
      "Shield Advanced deja de mitigar ataques de capa de aplicación y cubre solo capas 3 y 4",
      "AWS WAF se retira y Shield Advanced asume por completo el filtrado de peticiones HTTP",
      "Shield Advanced se apoya en el managed rule group 'Anti-DDoS' de AWS WAF para la capa 7",
    ],
    correct: 3,
    explain: "AWS anunció que Shield Advanced adopta el managed rule group <strong>Anti-DDoS</strong> de AWS WAF para reforzar la mitigación de ataques DDoS de capa de aplicación (inundaciones de peticiones HTTP), coherente con el modelo en el que Firewall Manager ya distribuye y mantiene de forma centralizada las políticas de WAF —incluidos los managed rule groups— junto a Shield Advanced en toda la organización. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Control Tower: soberanía digital (European Sovereign Cloud)",
    q: "Una empresa europea con requisitos estrictos de residencia de datos evalúa desplegar su landing zone en el nuevo AWS European Sovereign Cloud (disponibilidad general anunciada en enero de 2026, físicamente independiente de otras regiones de AWS). ¿Qué es correcto sobre el soporte de Control Tower en este contexto?",
    options: [
      "Control Tower está disponible allí e incorpora controles de residencia de datos",
      "Control Tower no está disponible allí: la landing zone debe gestionarse a mano",
      "El European Sovereign Cloud replica sus metadatos en las regiones estándar de AWS",
      "Solo es accesible vía Direct Connect y no soporta Organizations ni Control Tower",
    ],
    correct: 0,
    explain: "El AWS European Sovereign Cloud es una nube independiente, operada exclusivamente por residentes de la UE y físicamente separada del resto de regiones de AWS. Control Tower da soporte a este entorno incorporando gobernanza de residencia de datos (una agrupación dedicada de soberanía digital) y opciones como un <em>key store</em> externo para KMS, en línea con el Digital Sovereignty Pledge de AWS. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Well-Architected Tool: Review Templates",
    q: "El equipo de plataforma revisa decenas de cargas de trabajo con patrones de arquitectura muy similares (y, por tanto, las mismas respuestas a la mayoría de las mejores prácticas del pilar de seguridad) y quiere evitar rellenar manualmente las mismas respuestas en cada revisión nueva. ¿Qué funcionalidad de la Well-Architected Tool resuelve esto?",
    options: [
      "No es posible: cada revisión debe completarse manualmente desde cero en la Well-Architected Tool",
      "Review Templates: plantillas con respuestas prellenadas para nuevas cargas de trabajo",
      "Exportar las respuestas a una hoja de cálculo y copiarlas en cada revisión nueva",
      "Los lentes personalizados, disponibles solo para el pilar de optimización de costes",
    ],
    correct: 1,
    explain: "Review Templates permite predefinir respuestas comunes a las mejores prácticas del Well-Architected Framework —incluido el pilar de Security— o de un lente personalizado, y aplicarlas como punto de partida al crear nuevas cargas de trabajo con patrones repetidos. Reduce la duplicación de esfuerzo y estandariza el criterio de evaluación entre equipos. Los lentes personalizados, por cierto, no se limitan a ningún pilar. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Declarative Policies vs SCP: durabilidad",
    q: "Un compañero pregunta por qué el equipo de seguridad prefiere una Declarative Policy en vez de una SCP para forzar IMDSv2 en todas las instancias EC2 de la organización, si ambas son políticas de organización que se heredan por OU. ¿Cuál es la razón principal?",
    options: [
      "Las SCP solo pueden adjuntarse a cuentas individuales de la organización, nunca a una OU",
      "Las Declarative Policies tienen un coste por cuenta menor que el de las SCP",
      "La Declarative Policy fija un estado de configuración duradero, aunque cambien las APIs",
      "No hay diferencia práctica: ambas deniegan las mismas llamadas de API de EC2",
    ],
    correct: 2,
    explain: "Las Declarative Policies están pensadas para configuración duradera de un servicio ('set and forget'): definido el estado deseado (ej. IMDSv2 obligatorio), se mantiene automáticamente aunque el servicio añada nuevas APIs o funcionalidades relacionadas. Una SCP opera sobre <strong>permisos de API concretos</strong>: si aparece una nueva forma de llegar al resultado no deseado, hay que actualizarla a mano. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Config conformance packs: expansión regional",
    q: "Tu organización empieza a operar cargas de trabajo en regiones relativamente nuevas de AWS, como Asia Pacífico (Malasia) o Asia Pacífico (Nueva Zelanda), y planeas desplegar conformance packs de Config a nivel de organización en todas las cuentas y regiones. ¿Qué deberías verificar antes de asumir que funcionará igual que en regiones más antiguas como us-east-1?",
    options: [
      "Que Control Tower esté desplegado, único requisito para los conformance packs",
      "Nada: los conformance packs están disponibles en todas las regiones desde su lanzamiento",
      "Que la región coincida con la de la cuenta de management, única donde se evalúan",
      "Que la región de destino ya soporte conformance packs y su gestión de organización",
    ],
    correct: 3,
    explain: "AWS ha ido ampliando de forma incremental la disponibilidad regional tanto de los conformance packs de Config como de su gestión a nivel de organización, incorporando en 2025 regiones como Asia Pacífico (Malasia), (Nueva Zelanda), (Tailandia), (Taipéi) y México (Centro). Un supuesto de examen realista es <strong>verificar la disponibilidad regional</strong> de una funcionalidad de gobierno antes de asumir cobertura global uniforme. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Alcance de las SCP",
    q: "Estás desplegando Service Control Policies en una organización. ¿Qué DOS afirmaciones son correctas?",
    options: [
      "Una SCP no concede permisos: solo acota el máximo que pueden tener las identidades",
      "Una SCP puede conceder a un usuario permisos que su identity policy no le otorga",
      "Las SCP no se aplican a las identidades de la cuenta de management de la organización",
      "Las SCP también alcanzan a los principals externos que acceden a los recursos de la cuenta",
    ],
    correct: [0, 2],
    explain: "Dos clásicos del examen. Una SCP es un <strong>guardrail</strong>, nunca una concesión: el permiso efectivo es la intersección entre la SCP y las políticas de identidad. Y la <strong>cuenta de management no queda sujeta a las SCP</strong>, motivo por el que AWS recomienda no alojar cargas de trabajo en ella. La última opción describe lo que hacen las <strong>RCP</strong>, que sí alcanzan a identidades externas: justo el hueco que las SCP no cubren. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Controles de Control Tower",
    q: "Control Tower ofrece distintos tipos de control sobre la landing zone. ¿Qué DOS descripciones son correctas?",
    options: [
      "Los detectivos bloquean la acción antes de que llegue a ocurrir, igual que los preventivos",
      "Los preventivos se implementan con SCP e impiden que la acción llegue a ejecutarse",
      "Los preventivos solo pueden aplicarse a la cuenta de auditoría de la landing zone",
      "Los detectivos se implementan con reglas de Config y avisan de la desviación ya ocurrida",
    ],
    correct: [1, 3],
    explain: "La distinción <strong>preventivo vs detectivo</strong> es la que más se pregunta: los preventivos (SCP) <strong>impiden</strong>, los detectivos (Config) <strong>detectan</strong> lo que ya pasó — por eso la tercera opción se contradice a sí misma. Los preventivos se aplican a OUs y cuentas, no solo a la de auditoría. Control Tower añade además controles <em>proactivos</em>, que validan plantillas de CloudFormation antes del despliegue. <a href=\"https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Compliance multi-cuenta con Config",
    q: "Necesitas una visión única del cumplimiento de reglas de AWS Config en 90 cuentas y 4 Regiones. ¿Qué DOS elementos lo permiten?",
    options: [
      "Un aggregator de AWS Config que reúna los datos de todas las cuentas y regiones",
      "Un bucket S3 en cada cuenta del que descargar cada semana los informes de forma manual",
      "Activar Config solo en la cuenta de gestión, que hereda el estado de las demás",
      "Conformance packs de organización que apliquen el mismo conjunto de reglas en todas",
    ],
    correct: [0, 3],
    explain: "El <strong>aggregator</strong> resuelve la vista consolidada y los <strong>conformance packs</strong> a nivel de organización garantizan que todas las cuentas evalúan lo mismo. La descarga manual no escala a 90 cuentas y siempre llega tarde. Y Config es un servicio <strong>regional y por cuenta</strong>: la cuenta de gestión no hereda nada, hay que habilitarlo donde estén los recursos. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Protección del usuario root",
    q: "Estás endureciendo el usuario root de todas las cuentas de la organización. ¿Qué DOS medidas recomienda AWS?",
    options: [
      "Crear una access key de root en cada cuenta y guardarla en Secrets Manager",
      "Habilitar MFA en el usuario root y eliminar sus access keys si existen",
      "Usar la gestión centralizada de acceso root para retirar esas credenciales",
      "Usar el root a diario, ya que ninguna SCP puede llegar a bloquearlo nunca",
    ],
    correct: [1, 2],
    explain: "Lo básico es <strong>MFA y cero access keys</strong> en el root, y la <strong>gestión centralizada de acceso root</strong> permite retirar por completo esas credenciales de las cuentas miembro, dejando las tareas que exigen root para sesiones acotadas vía <code>sts:AssumeRoot</code>. Crear access keys de root es justo lo contrario de la recomendación. Y que las SCP no limiten al root de la management account es un motivo para <strong>no</strong> usarlo a diario, no para usarlo. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/root-user-best-practices.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Administrador delegado por servicio",
    q: "Vas a sacar la administración de GuardDuty, Security Hub y Macie fuera de la cuenta de gestión de la organización. ¿Qué es cierto del administrador delegado?",
    options: [
      "Debe ser la propia cuenta de gestión para poder ver todas las cuentas miembro",
      "Se designa por servicio, y puede ser una cuenta distinta para cada uno",
      "Solo puede designarse una única cuenta delegada para toda la organización",
      "Hereda de forma automática permisos de administrador sobre las demás cuentas",
    ],
    correct: 1,
    explain: "La delegación es <b>por servicio</b>: se registra una cuenta como administrador delegado de GuardDuty, otra —o la misma— de Security Hub, y así con cada servicio integrado con Organizations. Lo habitual es concentrarlos en una cuenta de seguridad, pero es una decisión, no una obligación. La cuenta de gestión es justo la que conviene dejar fuera, para reducir lo que puede pasar si se compromete. Y ser administrador delegado de un servicio de seguridad no otorga ningún permiso sobre los recursos de las cuentas miembro. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_integrate_services.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "La evidencia que aporta AWS",
    q: "Un auditor pide las certificaciones e informes de cumplimiento de la infraestructura sobre la que corre la carga del cliente. ¿De dónde salen y qué cubren?",
    options: [
      "De Security Hub, cuyo panel de estándares genera el informe de cumplimiento que el auditor necesita",
      "De AWS Artifact: cubren la mitad del proveedor, no la configuración del cliente",
      "De AWS Audit Manager, que produce las certificaciones de AWS junto con las evidencias de la cuenta",
      "De AWS Config, cuyo historial de conformidad sirve como acreditación ante el auditor externo",
    ],
    correct: 1,
    explain: "<b>Artifact</b> es el portal donde AWS publica sus informes de auditoría y certificaciones —SOC, ISO, PCI— y los acuerdos que a veces hay que aceptar. Lo importante para el examen es el <b>alcance</b>: acreditan la mitad de AWS en la responsabilidad compartida, y no dicen nada de cómo está configurada tu cuenta. Esa otra mitad la cubren Security Hub y Config evaluando tus recursos, y Audit Manager recogiendo la evidencia de tu configuración, pero ninguno de los tres emite las certificaciones del proveedor. <a href=\"https://docs.aws.amazon.com/artifact/latest/ug/what-is-aws-artifact.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["governance"] = QUIZ_DATA;
