var QUIZ_DATA = [
  {
    tag: "Envelope encryption",
    q: "Why does KMS use 'envelope encryption' (encrypting the data with a data key, and that data key with the CMK) instead of encrypting the data directly with the KMS key?",
    options: [
      "Because KMS's APIs have a very small payload size limit (4KB for symmetric keys)",
      "Because KMS keys can't encrypt data at all, only other keys",
      "Because it's exclusively a HIPAA compliance requirement",
      "Because it avoids paying for KMS API calls",
    ],
    correct: 0,
    explain: "KMS's direct Encrypt/Decrypt operations are limited to ~4KB of payload. To encrypt large objects, you generate a data key (GenerateDataKey), encrypt the data locally with that data key (no size limit), and send only the (small) data key to KMS to be encrypted/decrypted — hence 'envelope'.",
  },
  {
    tag: "Envelope encryption",
    q: "After using GenerateDataKey to encrypt a large file locally, what should the application do with the plaintext data key once encryption is finished?",
    options: [
      "Store it alongside the encrypted file to decrypt faster later",
      "Delete it from memory immediately",
      "Send it back to KMS so it can be stored securely",
      "Encrypt it with a second, different data key (double wrapping)",
    ],
    correct: 1,
    explain: "GenerateDataKey returns TWO versions: the plaintext data key (used once to encrypt, then discarded from memory) and the data key encrypted by the KMS key (that one is stored alongside the data). To decrypt, the encrypted data key is sent to KMS Decrypt, which returns the plaintext version again.",
  },
  {
    tag: "KMS key types",
    q: "What's the main difference between an AWS managed key (e.g. aws/s3) and a customer managed key (CMK) in KMS?",
    options: [
      "AWS managed keys are free and customer managed ones cost money; otherwise they're identical",
      "AWS managed keys support multi-Region and customer managed keys don't",
      "Only customer managed keys let you write custom key policies, enable rotation on your own schedule, disable them, or schedule their deletion",
      "AWS managed keys are asymmetric by default",
    ],
    correct: 2,
    explain: "AWS managed keys (prefix aws/) are created and managed automatically by AWS for a specific service, with mandatory annual rotation and no customizable key policy. Customer managed keys give you full control: your own key policy, optional configurable rotation, the ability to disable/delete them, and they're the only type that supports multi-Region keys.",
  },
  {
    tag: "KMS grants",
    q: "What is a KMS grant used for, instead of modifying the key policy directly?",
    options: [
      "A grant gives permanent permissions that replace the key policy",
      "A grant is just another name for an IAM policy attached to a role",
      "Grants only exist for asymmetric keys",
      "A grant lets you delegate temporary, programmatic permissions on a key (e.g. to an AWS service acting on your behalf) without editing the key policy, and it can be revoked individually without affecting other permissions",
    ],
    correct: 3,
    explain: "Grants are a more granular, dynamic delegation mechanism than the key policy: they're created/revoked programmatically (CreateGrant/RetireGrant/RevokeGrant), and they're ideal for letting an AWS service obtain temporary access to your key on your behalf (e.g. EBS encrypting a volume) without rewriting the key policy every time.",
  },
  {
    tag: "KMS multi-Region keys",
    q: "You have a primary Multi-Region KMS key in eu-west-1 replicated to us-east-1. An S3 object was encrypted using the us-east-1 replica. Can it be decrypted using the primary key in eu-west-1?",
    options: [
      "Yes: Multi-Region keys share the SAME underlying cryptographic material between the primary and its replicas, even though they have different Key IDs — anything encrypted with one replica can be decrypted with any other replica or the primary",
      "No, each replica is a completely independent key with different cryptographic material",
      "Only if both are in the same account but not the same Region",
      "It can only be decrypted by manually creating a third key that combines both",
    ],
    correct: 0,
    explain: "Unlike independently creating identical KMS keys in each region (which would have DIFFERENT cryptographic material), Multi-Region keys are replicas that share the same cryptographic material. This lets you encrypt in one region and decrypt in another without re-encrypting the data — critical for DR and global applications.",
  },
  {
    tag: "KMS vs CloudHSM",
    q: "A financial services company needs FIPS 140-2 Level 3, exclusive (single-tenant) control of the cryptographic hardware, and the ability to export key material if they migrate providers. Which service fits best?",
    options: [
      "AWS KMS with customer managed keys",
      "AWS CloudHSM: a dedicated, single-tenant HSM, full control of the key lifecycle, and it allows key export (unlike KMS)",
      "AWS Secrets Manager",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "KMS is multi-tenant (though with strong isolation guarantees) and NEVER allows exporting key material. CloudHSM gives you a dedicated (single-tenant) HSM, FIPS 140-2 Level 3, and full control including the ability to export keys — at the cost of managing the HSM infrastructure yourself (clusters, high availability).",
  },
  {
    tag: "Imported key material",
    q: "What limitation do KMS keys with IMPORTED key material (BYOK) have that AWS-generated keys don't?",
    options: [
      "They can't be used to encrypt data, only to sign",
      "They can only be used with S3, not with other services",
      "They don't support AWS-managed automatic annual rotation",
      "They can't have a custom key policy",
    ],
    correct: 2,
    explain: "When you import your own key material, AWS can't rotate it automatically for you (it doesn't know how to regenerate it). You can optionally set an expiration date for the material, and rotation becomes a manual process: create a new KMS key and import fresh material.",
  },
  {
    tag: "External Key Store (XKS)",
    q: "What does a KMS External Key Store (XKS) solve?",
    options: [
      "It lets you generate keys faster than standard KMS",
      "It replaces CloudHSM entirely",
      "It's simply an S3 bucket where copies of keys are stored",
      "It lets key material reside and be managed OUTSIDE AWS (in your own on-premises or third-party key manager), while AWS applications keep using the standard KMS API",
    ],
    correct: 3,
    explain: "XKS connects KMS to an external key manager (on-premises or third-party) through a proxy: the key material NEVER enters AWS, but AWS services integrated with KMS can keep using that key transparently. It's the option for maximum 'key sovereignty' while keeping native AWS integration.",
  },
  {
    tag: "S3 Object Lock",
    q: "What's the difference between Governance mode and Compliance mode in S3 Object Lock?",
    options: [
      "In Governance mode, users with the s3:BypassGovernanceRetention permission can delete/overwrite the object before the retention period expires; in Compliance mode, NO ONE can do that — not even the root account — until it expires",
      "They're synonyms, only the name changes depending on the region",
      "Compliance only applies to buckets with versioning disabled",
      "Governance is for public objects and Compliance for private ones",
    ],
    correct: 0,
    explain: "Both modes use WORM (Write Once Read Many), but Governance offers an escape hatch for users with specific elevated permissions, while Compliance is absolute: once the retention period is set, not even the root user can delete or modify the object until it expires. Compliance is used for strict regulatory requirements (e.g. SEC 17a-4).",
  },
  {
    tag: "Glacier Vault Lock",
    q: "What characterizes a Glacier Vault Lock policy once it is confirmed (locked)?",
    options: [
      "It can be freely edited at any time by the account administrator",
      "It becomes immutable: it can never be modified or deleted, ideal for meeting long-term data retention regulatory requirements",
      "It expires automatically after 90 days",
      "It only applies to objects smaller than 1MB",
    ],
    correct: 1,
    explain: "Vault Lock offers a 24-hour testing period to validate the policy before locking it; once locked, the policy is permanent and immutable — not even the account owner can change it, guaranteeing verifiable regulatory compliance.",
  },
  {
    tag: "Data integrity",
    q: "To verify that a software artifact (e.g. a downloaded binary) hasn't been altered in transit or tampered with by a third party, which AWS mechanism is most appropriate?",
    options: [
      "S3 Versioning alone",
      "MFA Delete on the bucket",
      "AWS Signer: digital code signing with centrally managed keys, verifiable by the receiver before executing the artifact",
      "AWS Backup",
    ],
    correct: 2,
    explain: "AWS Signer lets you digitally sign code (e.g. Lambda functions, container images, IoT firmware) so the receiver can cryptographically verify it hasn't been altered since creation — it covers integrity, not just confidentiality.",
  },
  {
    tag: "Lifecycle & retention",
    q: "You need objects in an S3 bucket to move automatically to Glacier Deep Archive after 180 days and be permanently deleted after 7 years, with no manual intervention. What mechanism do you use?",
    options: [
      "S3 Object Lock in Compliance mode with a 7-year retention period",
      "Cross-Region Replication",
      "AWS Backup with a daily plan",
      "S3 Lifecycle policies with transition rules (180 days → Deep Archive) and expiration rules (7 years → deletion)",
    ],
    correct: 3,
    explain: "S3 Lifecycle policies automate exactly this pattern: TRANSITION rules between storage classes based on age, and EXPIRATION rules for automatic deletion after a set period. Object Lock protects against premature deletion, but it doesn't move or delete objects on its own.",
  },
  {
    tag: "Backup & ransomware",
    q: "As protection against ransomware that encrypts or deletes your production data (including attempts to delete your backups), which AWS Backup feature is most relevant?",
    options: [
      "AWS Backup Vault Lock: makes backups immutable (WORM), preventing them from being deleted or modified even by a compromised administrator, for the configured retention period",
      "Encryption in transit for backups only",
      "Increasing backup frequency to hourly",
      "AWS Backup offers no specific protection against ransomware",
    ],
    correct: 0,
    explain: "AWS Backup Vault Lock applies the same WORM principle as S3 Object Lock, but at the level of an entire backup vault: once locked (especially in compliance mode), not even compromised administrator credentials can delete the backups before their retention period expires — a key mitigation against ransomware.",
  },
  {
    tag: "AWS DataSync vs Backup vs DLM",
    q: "Which statement correctly distinguishes AWS DataSync from AWS Backup?",
    options: [
      "They're the same service with different names",
      "DataSync is designed to MIGRATE/SYNCHRONIZE large volumes of data between on-premises and AWS (or between AWS storage services)",
      "DataSync only works with relational databases",
      "AWS Backup doesn't support EFS or FSx",
    ],
    correct: 1,
    explain: "DataSync moves/synchronizes data (ideal for migrations or recurring on-prem↔AWS transfers), while AWS Backup centralizes backup policies (retention, scheduling, cross-Region/cross-account copying) for EBS, RDS, DynamoDB, EFS, FSx, etc. Amazon Data Lifecycle Manager (DLM), in turn, automates EBS snapshots and AMIs specifically.",
  },
  {
    tag: "TLS in transit",
    q: "You want to force every client connecting to your Application Load Balancer to use TLS 1.2 or higher, rejecting outdated ciphers. What do you configure?",
    options: [
      "A Security Group rule that blocks port 80",
      "A bucket policy on S3",
      "A security policy (ELBSecurityPolicy) on the ALB's HTTPS listener, selecting a policy that requires TLS 1.2+",
      "A NACL on the ALB's subnet",
    ],
    correct: 2,
    explain: "Elastic Load Balancers (ALB/NLB) use predefined 'security policies' on the HTTPS/TLS listener that determine which TLS versions and cipher suites are accepted. Choosing a modern policy (e.g. ELBSecurityPolicy-TLS13-1-2-2021-06) enforces TLS 1.2+ and rejects connections using older protocols.",
  },
  {
    tag: "Private connectivity",
    q: "What's the main difference between AWS PrivateLink and VPC Peering for accessing a service in another VPC/account?",
    options: [
      "They're identical, only the marketing name changes",
      "PrivateLink only works between accounts in the same Organization",
      "VPC Peering is more secure than PrivateLink in all cases",
      "PrivateLink exposes the service as a one-directional endpoint (the consumer doesn't see the rest of the provider's VPC, and there's no CIDR range overlap to manage); VPC Peering connects the two full VPCs bidirectionally, potentially exposing the entire network",
    ],
    correct: 3,
    explain: "PrivateLink is ideal for exposing ONE specific service (e.g. a provider's SaaS) without giving full network visibility or worrying about CIDR overlap. VPC Peering connects two entire networks as if they were one — better suited for fully trusted relationships between your own VPCs.",
  },
  {
    tag: "Client VPN vs Verified Access",
    q: "How does AWS Verified Access differ from AWS Client VPN?",
    options: [
      "Client VPN establishes a traditional network tunnel (the user 'enters' the VPC)",
      "They're the same service; Verified Access is just the new name for Client VPN",
      "Verified Access only works with on-premises applications",
      "Client VPN doesn't support MFA",
    ],
    correct: 0,
    explain: "Client VPN is a classic remote-access model (full-tunnel or split-tunnel VPN). AWS Verified Access implements Zero Trust Network Access (ZTNA): it evaluates identity signals (IAM Identity Center) and device posture on every request at the application layer, without giving the user general network access.",
  },
  {
    tag: "Inter-resource encryption",
    q: "What is 'Nitro encryption' in the context of EC2 instances built on the Nitro System?",
    options: [
      "A separate service you have to enable and pay for separately",
      "Automatic encryption of instance memory and of traffic between Nitro instances within AWS infrastructure, with no client intervention or configuration",
      "It only encrypts attached EBS storage",
      "A type of KMS key exclusive to GPU instances",
    ],
    correct: 1,
    explain: "The Nitro System automatically encrypts data in transit BETWEEN Nitro instances within the same region (and the instance's local memory) as part of the underlying architecture, with no configuration required from the client — an exam point about 'inter-resource encryption in transit' that tends to surprise people because it requires no user action.",
  },
  {
    tag: "Secrets Manager",
    q: "What advantage does AWS Secrets Manager have over Systems Manager Parameter Store (SecureString) for RDS database credentials?",
    options: [
      "Parameter Store can't encrypt values, Secrets Manager can",
      "Secrets Manager is free and Parameter Store isn't",
      "Secrets Manager offers native AUTOMATIC ROTATION (with built-in Lambda functions for RDS, Redshift, DocumentDB) with no extra work",
      "Parameter Store doesn't support IAM-based access control",
    ],
    correct: 2,
    explain: "Both encrypt with KMS, but Secrets Manager has built-in automatic rotation out of the box for several database engines (it updates the credential AND applies it in the database in the same cycle). Parameter Store is cheaper for general configuration, but native automatic rotation is the main reason to choose Secrets Manager for database credentials.",
  },
  {
    tag: "Data masking",
    q: "You want any credit card number that mistakenly appears in your CloudWatch Logs to be automatically masked before an operator with normal permissions can see it. What mechanism do you use?",
    options: [
      "An IAM policy that denies reading logs",
      "Amazon Macie, because CloudWatch Logs doesn't support masking",
      "Encrypting the log group with KMS only",
      "A CloudWatch Logs data protection policy with sensitive data detectors (e.g. the 'Credit-Card-Number' data type) that masks the value in the view, leaving it visible only to principals with explicit 'unmask' permission",
    ],
    correct: 3,
    explain: "CloudWatch Logs data protection policies detect predefined or custom sensitive data types (cards, SSNs, AWS credentials, etc.) and automatically mask those values in queries/views — only principals with the logs:Unmask IAM permission see the real value. Amazon SNS has an equivalent 'message data protection' capability for messages.",
  },
  {
    tag: "ACM & certificates",
    q: "What's the key difference between a public certificate from AWS Certificate Manager (ACM) and one issued by AWS Private CA?",
    options: [
      "ACM's public certificates are free and publicly trusted (verified by a public CA, valid in any browser)",
      "There's no difference, both are free and publicly trusted",
      "AWS Private CA can't issue TLS certificates, only sign code",
      "Public ACM requires you to manage renewal yourself",
    ],
    correct: 0,
    explain: "ACM issues free public certificates with automatic renewal, valid for verifiable public domains (e.g. ELB, CloudFront). AWS Private CA creates your own private CA hierarchy to issue internal certificates (mTLS between microservices, IoT devices, IAM Roles Anywhere) that are only trusted where you distribute the root certificate.",
  },
  {
    tag: "Client-side vs server-side encryption",
    q: "In 'client-side' encryption of an S3 object, where does the data encryption happen?",
    options: [
      "On the S3 server side, before writing to disk",
      "On the client/application, BEFORE sending the data to S3",
      "In a KMS proxy managed by AWS",
      "It's identical to SSE-S3, only the name changes",
    ],
    correct: 1,
    explain: "In client-side encryption (using the AWS Encryption SDK or the S3 Encryption Client), encryption happens in the client application before the data travels to AWS — S3 never sees the plaintext. In server-side encryption (SSE-S3, SSE-KMS, SSE-C), S3 receives the data in the clear (over TLS) and encrypts it itself when writing to disk.",
  },
  {
    tag: "SSE-KMS vs SSE-C",
    q: "What characterizes SSE-C (Server-Side Encryption with Customer-Provided Keys) in S3, compared to SSE-KMS?",
    options: [
      "SSE-C doesn't require HTTPS",
      "SSE-C automatically uses KMS internally",
      "SSE-C is more secure because AWS never sees the key",
      "SSE-C is the default option if you don't configure anything",
    ],
    correct: 2,
    explain: "With SSE-C, you manage and send the AES-256 encryption key on every request; S3 uses it to encrypt/decrypt but NEVER stores it. Maximum control, but also maximum responsibility: if you lose that key, the object is unrecoverable, since not even AWS Support can help.",
  },
  {
    tag: "SageMaker AI / EMR / EKS",
    q: "In an Amazon EMR cluster processing sensitive data, which configuration specifically covers encryption of traffic BETWEEN cluster nodes (not just storage)?",
    options: [
      "Enabling SSE-S3 on the source data bucket",
      "Using a more restrictive Security Group only",
      "Enabling CloudTrail for the cluster",
      "EMR's in-transit encryption / inter-node encryption (TLS between cluster nodes, Spark shuffle, etc.), configurable in the cluster's Security Configuration",
    ],
    correct: 3,
    explain: "At-rest encryption (EBS, S3) protects storage, but internal traffic between nodes of a distributed cluster (EMR, EKS, SageMaker AI) requires explicit in-transit, inter-node encryption configuration, defined in the cluster's Security Configuration — exactly the kind of control that skill 5.1.3 added to the SCS-C03 exam.",
  },
  {
    tag: "KMS HMAC keys",
    q: "You need to generate and verify HMACs (message authentication codes) to guarantee the integrity and authenticity of messages between two systems, relying on a FIPS 140-2 validated HSM, without managing the cryptographic material yourself. What would you use?",
    options: [
      "A KMS HMAC key (KeyUsage GENERATE_VERIFY_MAC) with the GenerateMac and VerifyMac operations",
      "A standard symmetric KMS key with the Encrypt/Decrypt operations",
      "AWS Signer",
      "A secret in Secrets Manager with automatic rotation",
    ],
    correct: 0,
    explain: "HMAC KMS keys are a dedicated symmetric key type (KeyUsage GENERATE_VERIFY_MAC, conforming to RFC 2104) built specifically to generate (GenerateMac) and verify (VerifyMac) message authentication codes within KMS's security boundary; they cannot be used with Encrypt/Decrypt or GenerateDataKey.",
  },
  {
    tag: "KMS ECDH key agreement",
    q: "Two separate organizations want to establish a shared secret between their systems in order to later derive a symmetric session key, without transmitting any private key over the network. Which KMS operation enables this using asymmetric EC keys?",
    options: [
      "GenerateDataKeyPair",
      "DeriveSharedSecret, on an asymmetric NIST EC (or SM2) KMS key with KeyUsage KEY_AGREEMENT, using the ECDH (Elliptic Curve Diffie-Hellman) algorithm",
      "GenerateRandom",
      "Sign and Verify on an RSA key",
    ],
    correct: 1,
    explain: "DeriveSharedSecret uses the ECDH Cofactor primitive to derive a shared secret from your asymmetric KMS key (KeyUsage KEY_AGREEMENT) and the other party's SPKI/DER-encoded public key, within the FIPS 140-2 security boundary of KMS's HSM — without any private key ever leaving KMS or crossing the network.",
  },
  {
    tag: "S3 Bucket Keys",
    q: "A company encrypts millions of S3 objects with SSE-KMS and notices that the cost of KMS API calls (GenerateDataKey, Decrypt) is disproportionately high relative to storage. Which S3 option, enabled without any change to the client application, drastically reduces that cost?",
    options: [
      "Switching to SSE-S3",
      "Enabling S3 Transfer Acceleration",
      "Enabling S3 Bucket Keys: generates a short-lived bucket-level key from the KMS key and reuses it to encrypt multiple objects, reducing KMS calls by up to 99%",
      "Migrating to DSSE-KMS",
    ],
    correct: 2,
    explain: "With S3 Bucket Keys, S3 requests a bucket-level key from KMS just once (short-lived) and uses it to derive data keys for multiple objects locally, instead of calling KMS for every object — reducing KMS requests by up to 99% with no change to how the application uploads/downloads objects. It's not compatible with DSSE-KMS.",
  },
  {
    tag: "S3 DSSE-KMS",
    q: "A defense-sector customer needs to comply with CNSSP 15 / the Data-at-Rest Capability Package, which requires TWO independent layers of AES-256 encryption on objects stored in S3. Which S3 encryption method meets this requirement?",
    options: [
      "Standard SSE-KMS with S3 Bucket Keys enabled",
      "SSE-C",
      "Client-side encryption with the AWS Encryption SDK only",
      "DSSE-KMS (dual-layer server-side encryption)",
    ],
    correct: 3,
    explain: "DSSE-KMS encrypts the object twice, independently: one layer with a data key generated by KMS, and an additional layer with a key managed by S3, meeting dual-layer CNSA guidance for highly regulated workloads. It doesn't support S3 Bucket Keys and carries an extra per-GB cost compared to SSE-KMS.",
  },
  {
    tag: "AWS Payment Cryptography",
    q: "A fintech is migrating its payment card processing (PIN validation, cryptogram generation, key management aligned with payment industry standards) off on-premises HSMs. Which AWS service is purpose-built to replace those payment HSMs while meeting PCI PIN and PCI P2PE?",
    options: [
      "AWS Payment Cryptography: a managed service with PCI PTS-certified HSMs, purpose-built for payment industry cryptographic operations (card issuance, PIN validation, transaction processing)",
      "AWS KMS with customer managed keys",
      "Generic AWS CloudHSM",
      "AWS Secrets Manager",
    ],
    correct: 0,
    explain: "AWS Payment Cryptography is a managed service purpose-built for payment cryptographic operations (debit, credit, stored-value cards), using HSMs certified under PCI PTS, with PCI PIN and PCI P2PE compliance packages available via AWS Artifact — unlike CloudHSM or KMS, which are general-purpose and not built for the specific workflows of the payments industry.",
  },
  {
    tag: "Nitro Enclaves & KMS attestation",
    q: "An application processes highly sensitive data inside an AWS Nitro Enclave and needs KMS to decrypt data only for THAT specific enclave (identified by its image hash), not for any other process on the parent instance or any other enclave. What mechanism guarantees this?",
    options: [
      "A standard KMS grant with no additional conditions",
      "KMS cryptographic attestation",
      "The Nitro System's automatic memory encryption",
      "KMS Multi-Region keys",
    ],
    correct: 1,
    explain: "When calling Decrypt/DeriveSharedSecret/GenerateDataKey/GenerateDataKeyPair/GenerateRandom with an AttestationDocument signed by the Nitro hypervisor, KMS returns the result re-encrypted under the public key embedded in that document instead of in plaintext, and the kms:RecipientAttestation:ImageSha384 condition in the key policy lets you restrict access to enclaves whose image (PCR0) exactly matches the expected value.",
  },
  {
    tag: "ALB mutual TLS (mTLS)",
    q: "You need your Application Load Balancer to authenticate the CLIENT's identity (not just encrypt the channel) by verifying its X.509 certificate against a trusted CA, before forwarding the request to the target. What do you configure?",
    options: [
      "A TLS 1.3 security policy on the listener",
      "AWS WAF with a rate-based rule",
      "Mutual TLS (mTLS) on the ALB's HTTPS listener in 'verify' mode, with a Trust Store containing the CA bundle (third-party or AWS Private CA) and, optionally, revocation lists",
      "A Security Group that only allows the client's CIDR",
    ],
    correct: 2,
    explain: "The ALB supports mTLS in two modes: 'passthrough' (forwards the client's certificate chain to the target via HTTP headers, without validating it) and 'verify' (the ALB itself validates the client certificate against a Trust Store containing the CA bundle and CRLs). Verify mode is how the ALB offloads certificate-based client authentication.",
  },
  {
    tag: "Amazon Macie — automated discovery",
    q: "You want continuous, low-cost visibility into which S3 buckets across your organization might contain sensitive data, without manually defining and running a full scanning job against every bucket. Which Macie capability do you use?",
    options: [
      "A sensitive data discovery job scheduled against 100% of the objects in every bucket",
      "GuardDuty S3 Protection",
      "AWS Config rules only",
      "Automated sensitive data discovery",
    ],
    correct: 3,
    explain: "Macie offers two modes: 'automated sensitive data discovery' (continuous evaluation and representative sampling across accounts/buckets for broad, low-cost visibility, with an interactive data map and a sensitivity score per bucket) and 'sensitive data discovery jobs' (targeted, deeper analysis of specific buckets or objects, more expensive because it reviews more objects).",
  },
  {
    tag: "AWS Private CA — short-lived certificate mode",
    q: "A platform issues hundreds of thousands of very short-lived certificates (7 days or less) per month to authenticate ephemeral workloads, and the fixed monthly cost of a general-purpose mode CA is disproportionate. What option reduces the cost?",
    options: [
      "Using AWS Private CA in short-lived certificate mode",
      "Migrating to public ACM",
      "Disabling OCSP revocation checking",
      "Using CloudHSM to issue the certificates directly",
    ],
    correct: 0,
    explain: "AWS Private CA offers two modes: general-purpose (any validity period, higher fixed monthly cost per CA) and short-lived certificate mode (much lower fixed monthly cost, but issued certificates cannot exceed 7 days of validity) — ideal for ephemeral workload identities (containers, functions) that rotate certificates frequently.",
  },
  {
    tag: "Secrets Manager multi-Region",
    q: "An application with readers in two regions needs low-latency access to the same database secret in both, and when the credential is rotated in the primary region, the new value should propagate automatically without managing rotation separately in each region. Which Secrets Manager feature do you use?",
    options: [
      "S3 Cross-Region Replication applied to an exported copy of the secret",
      "Secrets Manager multi-Region secrets (ReplicateSecretToRegions)",
      "Manually creating identical, independent secrets in each region",
      "KMS Multi-Region keys, which also replicate the secret's value automatically",
    ],
    correct: 1,
    explain: "Secrets Manager lets you replicate a secret (encrypted value and metadata) to other regions with ReplicateSecretToRegions; if rotation is enabled on the primary secret, the new value propagates automatically to all replicas without managing them individually. Each replica is billed as a separate secret, and a replica can be promoted to a standalone secret if needed.",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "An on-premises workload (outside AWS) needs to obtain temporary IAM credentials to call the AWS API, without using long-term access keys stored on the server. An internal PKI already exists. Which solution fits?",
    options: [
      "IAM access keys rotated manually every 90 days",
      "AWS Client VPN",
      "IAM Roles Anywhere: register your CA (e.g. one issued by AWS Private CA, or your own PKI) as a trust anchor",
      "Amazon Cognito Identity Pools",
    ],
    correct: 2,
    explain: "IAM Roles Anywhere establishes trust between your existing PKI (registered as a trust anchor) and AWS: workloads outside AWS present an X.509 certificate issued by that CA to call CreateSession and obtain temporary session credentials for an IAM role via STS, removing the need for long-term access keys on on-premises systems.",
  },
  {
    tag: "EBS encryption by default",
    q: "You enable the account-level 'EBS encryption by default' setting in a region that already has unencrypted EBS volumes in use. What happens to those existing volumes?",
    options: [
      "They're automatically encrypted the next time they're attached to an instance",
      "They're automatically deleted for policy non-compliance",
      "They're automatically encrypted on the next scheduled snapshot",
      "They're unaffected: the setting only applies to volumes and snapshot copies created AFTER it's turned on",
    ],
    correct: 3,
    explain: "'EBS encryption by default' is a region-level setting that only affects volumes and snapshot copies created from that point forward. A volume or snapshot can only be encrypted at the moment of its creation — there's no way to retroactively encrypt an existing one without creating a new encrypted copy from it.",
  },
  {
    tag: "RDS encryption at rest",
    q: "You have a production RDS instance that was created WITHOUT encryption at rest (storage encryption disabled). How can you enable encryption without losing the data?",
    options: [
      "It's not possible to modify the encryption of an existing instance",
      "Modifying the instance directly with 'aws rds modify-db-instance --storage-encrypted'",
      "Enabling SSE-KMS on the instance",
      "Turning on 'EBS encryption by default' in the region",
    ],
    correct: 0,
    explain: "RDS encryption at rest can only be set at instance creation time (or when restoring from an encrypted snapshot) — there's no modify operation to encrypt an existing instance. The standard pattern is: snapshot → copy the snapshot with encryption enabled → restore an instance from the encrypted snapshot → cut over the application.",
  },
  {
    tag: "kms:ViaService",
    q: "You want a customer managed KMS key to be usable only by Amazon S3 (not by EBS, RDS, or a user calling the KMS API directly), even if those other principals hold general IAM permissions on the key. What condition do you add to the key policy?",
    options: [
      "aws:SourceIp",
      "kms:ViaService, set to s3.<region>.amazonaws.com, in the Condition of the statement that allows kms:Decrypt / kms:GenerateDataKey",
      "aws:PrincipalOrgID",
      "kms:GrantIsForAWSResource",
    ],
    correct: 1,
    explain: "kms:ViaService restricts use of a KMS key to requests originating from a specific AWS service (identified by its service principal, e.g. s3.eu-west-1.amazonaws.com), even if the calling principal has general IAM permissions on the key — it's how you say 'this key is only used through S3', blocking direct API use or use from other services.",
  },
  {
    tag: "RDS — master password managed by Secrets Manager",
    q: "You want to fully eliminate plaintext exposure of a new RDS database's master password during creation, and have AWS handle periodic rotation of that password without you writing a Lambda function. Which RDS option do you use?",
    options: [
      "Manually configure Secrets Manager and a rotation Lambda after creating the instance",
      "Use Parameter Store SecureString with a rotation policy",
      "Enable 'Manage master credentials in AWS Secrets Manager' when creating (or modifying) the instance",
      "Disable password authentication and use only IAM database authentication",
    ],
    correct: 2,
    explain: "Enabling 'Manage master credentials in AWS Secrets Manager' has RDS generate and store the master password directly in Secrets Manager (never shown in plaintext during creation) and manage its full lifecycle, including periodic automatic rotation, without you writing or deploying your own rotation Lambda.",
  },
  {
    tag: "S3 Object Lock — Legal Hold",
    q: "You need to preserve an S3 object indefinitely for an ongoing legal matter, without knowing how long it will last, and without relying on setting a specific retention date in Governance or Compliance mode. Which Object Lock mechanism do you use?",
    options: [
      "A retention period in Compliance mode with a far-future date (e.g. year 2099)",
      "Glacier Vault Lock",
      "S3 Versioning with MFA Delete",
      "Legal Hold: applies the same WORM protection as a retention period but with NO expiration date",
    ],
    correct: 3,
    explain: "A Legal Hold provides the same WORM protection as a retention period, but with no expiration date: it stays in effect until someone with the s3:PutObjectLegalHold permission explicitly removes it. An object can have a retention period, a legal hold, both, or neither — they're independent mechanisms.",
  },
  {
    tag: "KMS automatic rotation — scope",
    q: "You enable annual automatic rotation on a KMS key. For which of the following is that automatic rotation NOT available, requiring manual or on-demand rotation instead?",
    options: [
      "Asymmetric keys, HMAC keys, keys with imported key material (EXTERNAL origin), and keys in a custom key store (CloudHSM key store or External Key Store) — automatic rotation only applies to symmetric encryption keys with AWS-generated material",
      "Only for symmetric encryption keys generated by AWS (AWS_KMS origin)",
      "Only AWS managed keys (aws/s3, etc.)",
      "None: all KMS keys support automatic rotation",
    ],
    correct: 0,
    explain: "KMS automatic rotation is only available for symmetric encryption KMS keys with AWS-generated key material (AWS_KMS origin). It's not available for asymmetric keys, HMAC keys, keys with imported material, or keys in a custom key store — for those, the alternative is manual or on-demand rotation (RotateKeyOnDemand, also available for symmetric keys with imported material).",
  },
  {
    tag: "CloudTrail & KMS usage auditing",
    q: "You suspect a customer managed KMS key was used to decrypt data by an unauthorized principal. Where do you check who invoked the Decrypt operation on that key, when, and from which principal/role?",
    options: [
      "In the KMS key's key policy",
      "In AWS CloudTrail: every KMS API call (Decrypt, GenerateDataKey, Encrypt...) is logged as an event with the calling principal, the Key ID, the source, and the outcome of the call",
      "In Amazon Macie",
      "In AWS Config, which logs API invocations in real time",
    ],
    correct: 1,
    explain: "Every KMS API operation is logged as a CloudTrail event (enabled by default as a 'management event'), including the principal (user/role) that made the call, the timestamp, the affected Key ID, the source IP, and whether the call succeeded or was denied — the source of truth for auditing use of a KMS key.",
  },
  {
    tag: "Cross-account KMS key use",
    q: "A role in account B must decrypt objects encrypted with a customer managed KMS key living in account A. Which TWO conditions must hold?",
    options: [
      "The key policy in account A must allow access to the account B principal",
      "The identity policy of the role in account B must allow kms:Decrypt on that key",
      "The key must be an AWS managed key rather than a customer managed key",
      "Both accounts must be in the same Region and the same Organization",
    ],
    correct: [0, 1],
    explain: "As with cross-account role access, KMS requires <b>both ends</b>: key policy on the owner and identity policy on the consumer. Notably <b>AWS managed keys cannot be shared</b> across accounts — which is why the cross-account use case requires a customer managed key, the opposite of option C. Organizations isn't needed; Region does matter since keys are regional, but that is not what's missing here.",
  },
  {
    tag: "Envelope encryption",
    q: "Which TWO statements correctly describe envelope encryption as AWS KMS implements it?",
    options: [
      "Data is encrypted with a data key, and that data key is itself encrypted with the KMS key",
      "The plaintext data key is used in memory and then discarded",
      "Data travels to KMS to be encrypted there, regardless of size",
      "The KMS key leaves the service to encrypt data on the client",
    ],
    correct: [0, 1],
    explain: "Envelope encryption exists precisely so data does <b>not</b> travel to KMS: KMS encrypts the data key (a small, fast operation) and bulk encryption happens locally. KMS's direct <code>Encrypt</code> operation is capped at 4 KB, which rules out option C for real data. And a KMS key's cryptographic material <b>never leaves the service in plaintext</b>: that is its fundamental guarantee.",
  },
  {
    tag: "Immutable retention in S3",
    q: "A regulatory requirement demands certain S3 objects cannot be deleted for 7 years. Which TWO statements about S3 Object Lock are correct?",
    options: [
      "In compliance mode no user — including the account root — can delete the object before retention expires",
      "Object Lock requires versioning to be enabled on the bucket",
      "In governance mode nobody can override retention under any circumstances",
      "Object Lock can be turned on for existing objects with no prior bucket configuration",
    ],
    correct: [0, 1],
    explain: "<b>Compliance</b> is the truly immutable mode (not even root can bypass it) and Object Lock <b>depends on versioning</b>, since it protects specific versions. <b>Governance</b> mode does allow an override for anyone holding <code>s3:BypassGovernanceRetention</code> — that is exactly the difference between the modes and what tends to be tested. And Object Lock is enabled at the bucket level, not improvised onto existing objects in a bucket without it.",
  },
  {
    tag: "Secrets Manager rotation",
    q: "You want to automatically rotate an RDS database password stored in Secrets Manager. Which TWO elements are involved?",
    options: [
      "A rotation Lambda function with permission to change the credential in the database",
      "A rotation schedule defining how often the process runs",
      "An S3 bucket where Secrets Manager drops the previous password in plaintext",
      "An AWS Config rule that changes the password when it detects expiry",
    ],
    correct: [0, 1],
    explain: "Rotation relies on a <b>Lambda</b> (AWS ships templates for supported databases) and a <b>schedule</b>. Secrets Manager keeps secret versions with staging labels such as AWSCURRENT and AWSPREVIOUS inside the service itself, encrypted with KMS: it never writes plaintext credentials to a bucket. And Config <b>evaluates</b> configuration, it does not rotate credentials.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["data-protection"] = QUIZ_DATA;
