const QUIZ_DATA = [
  {
    tag: "Envelope encryption",
    q: "Why does KMS use 'envelope encryption' (encrypting the data with a data key, and that data key with the CMK) instead of encrypting the data directly with the KMS key?",
    options: [
      "Because KMS keys can't encrypt data at all, only other keys",
      "Because KMS's APIs have a very small payload size limit (4KB for symmetric keys); wrapping lets you encrypt data of any size locally and only send the (small) data key to KMS",
      "Because it's exclusively a HIPAA compliance requirement",
      "Because it avoids paying for KMS API calls",
    ],
    correct: 1,
    explain: "KMS's direct Encrypt/Decrypt operations are limited to ~4KB of payload. To encrypt large objects, you generate a data key (GenerateDataKey), encrypt the data locally with that data key (no size limit), and send only the (small) data key to KMS to be encrypted/decrypted — hence 'envelope'.",
  },
  {
    tag: "Envelope encryption",
    q: "After using GenerateDataKey to encrypt a large file locally, what should the application do with the plaintext data key once encryption is finished?",
    options: [
      "Store it alongside the encrypted file to decrypt faster later",
      "Send it back to KMS so it can be stored securely",
      "Delete it from memory immediately; only the ENCRYPTED version of the data key (the 'encrypted blob') is kept alongside the data",
      "Encrypt it with a second, different data key (double wrapping)",
    ],
    correct: 2,
    explain: "GenerateDataKey returns TWO versions: the plaintext data key (used once to encrypt, then discarded from memory) and the data key encrypted by the KMS key (that one is stored alongside the data). To decrypt, the encrypted data key is sent to KMS Decrypt, which returns the plaintext version again.",
  },
  {
    tag: "KMS key types",
    q: "What's the main difference between an AWS managed key (e.g. aws/s3) and a customer managed key (CMK) in KMS?",
    options: [
      "AWS managed keys are free and customer managed ones cost money; otherwise they're identical",
      "Only customer managed keys let you write custom key policies, enable rotation on your own schedule, disable them, or schedule their deletion",
      "AWS managed keys support multi-Region and customer managed keys don't",
      "AWS managed keys are asymmetric by default",
    ],
    correct: 1,
    explain: "AWS managed keys (prefix aws/) are created and managed automatically by AWS for a specific service, with mandatory annual rotation and no customizable key policy. Customer managed keys give you full control: your own key policy, optional configurable rotation, the ability to disable/delete them, and they're the only type that supports multi-Region keys.",
  },
  {
    tag: "KMS grants",
    q: "What is a KMS grant used for, instead of modifying the key policy directly?",
    options: [
      "A grant gives permanent permissions that replace the key policy",
      "A grant lets you delegate temporary, programmatic permissions on a key (e.g. to an AWS service acting on your behalf) without editing the key policy, and it can be revoked individually without affecting other permissions",
      "Grants only exist for asymmetric keys",
      "A grant is just another name for an IAM policy attached to a role",
    ],
    correct: 1,
    explain: "Grants are a more granular, dynamic delegation mechanism than the key policy: they're created/revoked programmatically (CreateGrant/RetireGrant/RevokeGrant), and they're ideal for letting an AWS service obtain temporary access to your key on your behalf (e.g. EBS encrypting a volume) without rewriting the key policy every time.",
  },
  {
    tag: "KMS multi-Region keys",
    q: "You have a primary Multi-Region KMS key in eu-west-1 replicated to us-east-1. An S3 object was encrypted using the us-east-1 replica. Can it be decrypted using the primary key in eu-west-1?",
    options: [
      "No, each replica is a completely independent key with different cryptographic material",
      "Yes: Multi-Region keys share the SAME underlying cryptographic material between the primary and its replicas, even though they have different Key IDs — anything encrypted with one replica can be decrypted with any other replica or the primary",
      "Only if both are in the same account but not the same Region",
      "It can only be decrypted by manually creating a third key that combines both",
    ],
    correct: 1,
    explain: "Unlike independently creating identical KMS keys in each region (which would have DIFFERENT cryptographic material), Multi-Region keys are replicas that share the same cryptographic material. This lets you encrypt in one region and decrypt in another without re-encrypting the data — critical for DR and global applications.",
  },
  {
    tag: "KMS vs CloudHSM",
    q: "A financial services company needs FIPS 140-2 Level 3, exclusive (single-tenant) control of the cryptographic hardware, and the ability to export key material if they migrate providers. Which service fits best?",
    options: [
      "AWS KMS with customer managed keys",
      "AWS CloudHSM: a dedicated, single-tenant HSM, full control of the key lifecycle, and it allows key export (unlike KMS)",
      "AWS Secrets Manager",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "KMS is multi-tenant (though with strong isolation guarantees) and NEVER allows exporting key material. CloudHSM gives you a dedicated (single-tenant) HSM, FIPS 140-2 Level 3, and full control including the ability to export keys — at the cost of managing the HSM infrastructure yourself (clusters, high availability).",
  },
  {
    tag: "Imported key material",
    q: "What limitation do KMS keys with IMPORTED key material (BYOK) have that AWS-generated keys don't?",
    options: [
      "They can't be used to encrypt data, only to sign",
      "They don't support AWS-managed automatic annual rotation; rotation, if desired, must be handled manually by re-importing new material",
      "They can only be used with S3, not with other services",
      "They can't have a custom key policy",
    ],
    correct: 1,
    explain: "When you import your own key material, AWS can't rotate it automatically for you (it doesn't know how to regenerate it). You can optionally set an expiration date for the material, and rotation becomes a manual process: create a new KMS key and import fresh material.",
  },
  {
    tag: "External Key Store (XKS)",
    q: "What does a KMS External Key Store (XKS) solve?",
    options: [
      "It lets you generate keys faster than standard KMS",
      "It lets key material reside and be managed OUTSIDE AWS (in your own on-premises or third-party key manager), while AWS applications keep using the standard KMS API",
      "It's simply an S3 bucket where copies of keys are stored",
      "It replaces CloudHSM entirely",
    ],
    correct: 1,
    explain: "XKS connects KMS to an external key manager (on-premises or third-party) through a proxy: the key material NEVER enters AWS, but AWS services integrated with KMS can keep using that key transparently. It's the option for maximum 'key sovereignty' while keeping native AWS integration.",
  },
  {
    tag: "S3 Object Lock",
    q: "What's the difference between Governance mode and Compliance mode in S3 Object Lock?",
    options: [
      "They're synonyms, only the name changes depending on the region",
      "In Governance mode, users with the s3:BypassGovernanceRetention permission can delete/overwrite the object before the retention period expires; in Compliance mode, NO ONE can do that — not even the root account — until it expires",
      "Compliance only applies to buckets with versioning disabled",
      "Governance is for public objects and Compliance for private ones",
    ],
    correct: 1,
    explain: "Both modes use WORM (Write Once Read Many), but Governance offers an escape hatch for users with specific elevated permissions, while Compliance is absolute: once the retention period is set, not even the root user can delete or modify the object until it expires. Compliance is used for strict regulatory requirements (e.g. SEC 17a-4).",
  },
  {
    tag: "Glacier Vault Lock",
    q: "What characterizes a Glacier Vault Lock policy once it is confirmed (locked)?",
    options: [
      "It can be freely edited at any time by the account administrator",
      "It becomes immutable: it can never be modified or deleted, ideal for meeting long-term data retention regulatory requirements",
      "It expires automatically after 90 days",
      "It only applies to objects smaller than 1MB",
    ],
    correct: 1,
    explain: "Vault Lock offers a 24-hour testing period to validate the policy before locking it; once locked, the policy is permanent and immutable — not even the account owner can change it, guaranteeing verifiable regulatory compliance.",
  },
  {
    tag: "Data integrity",
    q: "To verify that a software artifact (e.g. a downloaded binary) hasn't been altered in transit or tampered with by a third party, which AWS mechanism is most appropriate?",
    options: [
      "S3 Versioning alone",
      "AWS Signer: digital code signing with centrally managed keys, verifiable by the receiver before executing the artifact",
      "MFA Delete on the bucket",
      "AWS Backup",
    ],
    correct: 1,
    explain: "AWS Signer lets you digitally sign code (e.g. Lambda functions, container images, IoT firmware) so the receiver can cryptographically verify it hasn't been altered since creation — it covers integrity, not just confidentiality.",
  },
  {
    tag: "Lifecycle & retention",
    q: "You need objects in an S3 bucket to move automatically to Glacier Deep Archive after 180 days and be permanently deleted after 7 years, with no manual intervention. What mechanism do you use?",
    options: [
      "S3 Object Lock in Compliance mode with a 7-year retention period",
      "S3 Lifecycle policies with transition rules (180 days → Deep Archive) and expiration rules (7 years → deletion)",
      "AWS Backup with a daily plan",
      "Cross-Region Replication",
    ],
    correct: 1,
    explain: "S3 Lifecycle policies automate exactly this pattern: TRANSITION rules between storage classes based on age, and EXPIRATION rules for automatic deletion after a set period. Object Lock protects against premature deletion, but it doesn't move or delete objects on its own.",
  },
  {
    tag: "Backup & ransomware",
    q: "As protection against ransomware that encrypts or deletes your production data (including attempts to delete your backups), which AWS Backup feature is most relevant?",
    options: [
      "AWS Backup Vault Lock: makes backups immutable (WORM), preventing them from being deleted or modified even by a compromised administrator, for the configured retention period",
      "Encryption in transit for backups only",
      "Increasing backup frequency to hourly",
      "AWS Backup offers no specific protection against ransomware",
    ],
    correct: 0,
    explain: "AWS Backup Vault Lock applies the same WORM principle as S3 Object Lock, but at the level of an entire backup vault: once locked (especially in compliance mode), not even compromised administrator credentials can delete the backups before their retention period expires — a key mitigation against ransomware.",
  },
  {
    tag: "AWS DataSync vs Backup vs DLM",
    q: "Which statement correctly distinguishes AWS DataSync from AWS Backup?",
    options: [
      "They're the same service with different names",
      "DataSync is designed to MIGRATE/SYNCHRONIZE large volumes of data between on-premises and AWS (or between AWS storage services); AWS Backup is designed to create and manage centralized, scheduled BACKUP copies of AWS resources",
      "DataSync only works with relational databases",
      "AWS Backup doesn't support EFS or FSx",
    ],
    correct: 1,
    explain: "DataSync moves/synchronizes data (ideal for migrations or recurring on-prem↔AWS transfers), while AWS Backup centralizes backup policies (retention, scheduling, cross-Region/cross-account copying) for EBS, RDS, DynamoDB, EFS, FSx, etc. Amazon Data Lifecycle Manager (DLM), in turn, automates EBS snapshots and AMIs specifically.",
  },
  {
    tag: "TLS in transit",
    q: "You want to force every client connecting to your Application Load Balancer to use TLS 1.2 or higher, rejecting outdated ciphers. What do you configure?",
    options: [
      "A Security Group rule that blocks port 80",
      "A security policy (ELBSecurityPolicy) on the ALB's HTTPS listener, selecting a policy that requires TLS 1.2+",
      "A bucket policy on S3",
      "A NACL on the ALB's subnet",
    ],
    correct: 1,
    explain: "Elastic Load Balancers (ALB/NLB) use predefined 'security policies' on the HTTPS/TLS listener that determine which TLS versions and cipher suites are accepted. Choosing a modern policy (e.g. ELBSecurityPolicy-TLS13-1-2-2021-06) enforces TLS 1.2+ and rejects connections using older protocols.",
  },
  {
    tag: "Private connectivity",
    q: "What's the main difference between AWS PrivateLink and VPC Peering for accessing a service in another VPC/account?",
    options: [
      "They're identical, only the marketing name changes",
      "PrivateLink exposes the service as a one-directional endpoint (the consumer doesn't see the rest of the provider's VPC, and there's no CIDR range overlap to manage); VPC Peering connects the two full VPCs bidirectionally, potentially exposing the entire network",
      "VPC Peering is more secure than PrivateLink in all cases",
      "PrivateLink only works between accounts in the same Organization",
    ],
    correct: 1,
    explain: "PrivateLink is ideal for exposing ONE specific service (e.g. a provider's SaaS) without giving full network visibility or worrying about CIDR overlap. VPC Peering connects two entire networks as if they were one — better suited for fully trusted relationships between your own VPCs.",
  },
  {
    tag: "Client VPN vs Verified Access",
    q: "How does AWS Verified Access differ from AWS Client VPN?",
    options: [
      "They're the same service; Verified Access is just the new name for Client VPN",
      "Client VPN establishes a traditional network tunnel (the user 'enters' the VPC); Verified Access applies a Zero Trust model, evaluating identity + device posture on every request to a specific application, without exposing a full network tunnel",
      "Verified Access only works with on-premises applications",
      "Client VPN doesn't support MFA",
    ],
    correct: 1,
    explain: "Client VPN is a classic remote-access model (full-tunnel or split-tunnel VPN). AWS Verified Access implements Zero Trust Network Access (ZTNA): it evaluates identity signals (IAM Identity Center) and device posture on every request at the application layer, without giving the user general network access.",
  },
  {
    tag: "Inter-resource encryption",
    q: "What is 'Nitro encryption' in the context of EC2 instances built on the Nitro System?",
    options: [
      "A separate service you have to enable and pay for separately",
      "Automatic encryption of instance memory and of traffic between Nitro instances within AWS infrastructure, with no client intervention or configuration",
      "It only encrypts attached EBS storage",
      "A type of KMS key exclusive to GPU instances",
    ],
    correct: 1,
    explain: "The Nitro System automatically encrypts data in transit BETWEEN Nitro instances within the same region (and the instance's local memory) as part of the underlying architecture, with no configuration required from the client — an exam point about 'inter-resource encryption in transit' that tends to surprise people because it requires no user action.",
  },
  {
    tag: "Secrets Manager",
    q: "What advantage does AWS Secrets Manager have over Systems Manager Parameter Store (SecureString) for RDS database credentials?",
    options: [
      "Parameter Store can't encrypt values, Secrets Manager can",
      "Secrets Manager offers native AUTOMATIC ROTATION (with built-in Lambda functions for RDS, Redshift, DocumentDB) with no extra work; Parameter Store requires you to build the rotation logic yourself",
      "Secrets Manager is free and Parameter Store isn't",
      "Parameter Store doesn't support IAM-based access control",
    ],
    correct: 1,
    explain: "Both encrypt with KMS, but Secrets Manager has built-in automatic rotation out of the box for several database engines (it updates the credential AND applies it in the database in the same cycle). Parameter Store is cheaper for general configuration, but native automatic rotation is the main reason to choose Secrets Manager for database credentials.",
  },
  {
    tag: "Data masking",
    q: "You want any credit card number that mistakenly appears in your CloudWatch Logs to be automatically masked before an operator with normal permissions can see it. What mechanism do you use?",
    options: [
      "An IAM policy that denies reading logs",
      "A CloudWatch Logs data protection policy with sensitive data detectors (e.g. the 'Credit-Card-Number' data type) that masks the value in the view, leaving it visible only to principals with explicit 'unmask' permission",
      "Encrypting the log group with KMS only",
      "Amazon Macie, because CloudWatch Logs doesn't support masking",
    ],
    correct: 1,
    explain: "CloudWatch Logs data protection policies detect predefined or custom sensitive data types (cards, SSNs, AWS credentials, etc.) and automatically mask those values in queries/views — only principals with the logs:Unmask IAM permission see the real value. Amazon SNS has an equivalent 'message data protection' capability for messages.",
  },
  {
    tag: "ACM & certificates",
    q: "What's the key difference between a public certificate from AWS Certificate Manager (ACM) and one issued by AWS Private CA?",
    options: [
      "There's no difference, both are free and publicly trusted",
      "ACM's public certificates are free and publicly trusted (verified by a public CA, valid in any browser); AWS Private CA certificates are PRIVATELY trusted (valid only within your organization, where you distribute the root certificate) and cost per active CA",
      "AWS Private CA can't issue TLS certificates, only sign code",
      "Public ACM requires you to manage renewal yourself",
    ],
    correct: 1,
    explain: "ACM issues free public certificates with automatic renewal, valid for verifiable public domains (e.g. ELB, CloudFront). AWS Private CA creates your own private CA hierarchy to issue internal certificates (mTLS between microservices, IoT devices, IAM Roles Anywhere) that are only trusted where you distribute the root certificate.",
  },
  {
    tag: "Client-side vs server-side encryption",
    q: "In 'client-side' encryption of an S3 object, where does the data encryption happen?",
    options: [
      "On the S3 server side, before writing to disk",
      "On the client/application, BEFORE sending the data to S3 — S3 receives and stores only the already-encrypted object, never seeing the plaintext",
      "In a KMS proxy managed by AWS",
      "It's identical to SSE-S3, only the name changes",
    ],
    correct: 1,
    explain: "In client-side encryption (using the AWS Encryption SDK or the S3 Encryption Client), encryption happens in the client application before the data travels to AWS — S3 never sees the plaintext. In server-side encryption (SSE-S3, SSE-KMS, SSE-C), S3 receives the data in the clear (over TLS) and encrypts it itself when writing to disk.",
  },
  {
    tag: "SSE-KMS vs SSE-C",
    q: "What characterizes SSE-C (Server-Side Encryption with Customer-Provided Keys) in S3, compared to SSE-KMS?",
    options: [
      "SSE-C is more secure because AWS never sees the key; the client must send the encryption key on EVERY request (GET/PUT) over HTTPS, and AWS never stores it — if you lose the key, you lose the object forever",
      "SSE-C automatically uses KMS internally",
      "SSE-C doesn't require HTTPS",
      "SSE-C is the default option if you don't configure anything",
    ],
    correct: 0,
    explain: "With SSE-C, you manage and send the AES-256 encryption key on every request; S3 uses it to encrypt/decrypt but NEVER stores it. Maximum control, but also maximum responsibility: if you lose that key, the object is unrecoverable, since not even AWS Support can help.",
  },
  {
    tag: "SageMaker AI / EMR / EKS",
    q: "In an Amazon EMR cluster processing sensitive data, which configuration specifically covers encryption of traffic BETWEEN cluster nodes (not just storage)?",
    options: [
      "Enabling SSE-S3 on the source data bucket",
      "EMR's in-transit encryption / inter-node encryption (TLS between cluster nodes, Spark shuffle, etc.), configurable in the cluster's Security Configuration",
      "Enabling CloudTrail for the cluster",
      "Using a more restrictive Security Group only",
    ],
    correct: 1,
    explain: "At-rest encryption (EBS, S3) protects storage, but internal traffic between nodes of a distributed cluster (EMR, EKS, SageMaker AI) requires explicit in-transit, inter-node encryption configuration, defined in the cluster's Security Configuration — exactly the kind of control that skill 5.1.3 added to the SCS-C03 exam.",
  },
];
