// Question bank for the module: applications and data (SC-100, domain 4).
// Every explanation ends with a link to the official Microsoft Learn documentation.

var QUIZ_DATA = [
  {
    tag: "What Secure Score measures",
    q: "Management wants a single metric to track quarterly improvement in the Microsoft 365 configuration. What do you take, and what do you warn them about?",
    options: [
      "The percentage of compliant devices in Intune, which reflects the real state of the managed estate",
      "The number of incidents closed in the Defender portal, which drops as configuration improves",
      "Microsoft Secure Score, warning that it measures configuration improvement, not compliance with a standard",
      "The Defender for Cloud secure score, which aggregates the posture of every resource in the organisation",
    ],
    correct: 2,
    explain: "<b>Microsoft Secure Score</b>, in the Defender portal, is exactly that: tenant configuration — identity, email, apps, devices — with actions prioritised by impact and effort. The warning matters because it is the confusion the exam chases: it measures <em>improvement</em>, not <em>compliance</em>. The Defender for Cloud one measures cloud resources. Closed incidents measure operations. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Chasing a hundred per cent",
    q: "The team has set itself a target of reaching 100% on Microsoft Secure Score. Some actions require disabling features the business uses daily. What do you recommend?",
    options: [
      "Applying every action and finding business alternatives for the features that stop being available",
      "Implementing what brings real value and marking the rest as accepted risk or resolved by a third party",
      "Lowering the target to a round percentage the team can hit without having to argue with the business",
      "Replacing Secure Score with the regulatory compliance dashboard, which does have a reachable target",
    ],
    correct: 1,
    explain: "Secure Score is a <b>prioritisation</b> tool, not a grade to earn. Each action is weighed against risk and business impact, and the ones that do not apply are marked as <em>accepted risk</em> or <em>resolved through third party</em> — which is exactly what those states exist for: the number sits below 100% and the posture is correct. Chasing 100% by breaking the business is the blunt mistake. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Email or SaaS",
    q: "A phishing campaign using links that only turn malicious after delivery is getting past the current mail controls. Which capability addresses it?",
    options: [
      "Safe Links in Defender for Office 365, which rewrites and checks the destination at click time",
      "A Defender for Cloud Apps session policy over web access to the users' mailboxes",
      "A mail flow rule quarantining every external message that contains a link",
      "Training with phishing simulations aimed at the departments with the most recorded incidents",
    ],
    correct: 0,
    explain: "The detail in the stem is \"only turn malicious <em>after</em> delivery\": the link was harmless when the filter saw it. <b>Safe Links</b> rewrites it and re-checks the destination <b>at the moment of the click</b>, which is when the attack exists. Quarantining every external link breaks email. Training lowers the rate but checks no destinations. And Cloud Apps governs SaaS applications, not mail delivery. <a href=\"https://learn.microsoft.com/en-us/defender-office-365/safe-links-about\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Applications nobody approved",
    q: "Security suspects teams are uploading information to cloud storage services nobody has approved, and first wants to know which ones and at what volume. Where do you start?",
    options: [
      "By blocking every cloud storage service by category in the corporate web filtering",
      "An endpoint data loss prevention policy preventing copies to web services",
      "A survey of each team's manager about the tools they use day to day",
      "Cloud app discovery in Defender for Cloud Apps, over the traffic logs",
    ],
    correct: 3,
    explain: "Before deciding you have to <b>measure</b>, and the stem asks for exactly that: which ones and at what volume. <b>Cloud app discovery</b> in Defender for Cloud Apps analyses traffic logs, identifies the services in use, scores them by risk and shows volume and users — and from that comes what gets sanctioned and what gets blocked. Blocking by category without measuring cuts the legitimate too, and a survey misses whatever nobody declares. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The signal that hooks into the data",
    q: "The requirement says internal SharePoint documentation must only be openable from corporate machines with disk encryption. Which chain of pieces implements it?",
    options: [
      "A Purview retention policy over the sites, combined with permissions by security group",
      "An Intune compliance policy and conditional access requiring a compliant device",
      "A sensitivity label with encryption applied to every document in those sites",
      "A data loss prevention policy preventing downloads from unmanaged machines",
    ],
    correct: 1,
    explain: "Two pieces interlocking, in this order: <b>Intune</b> evaluates disk encryption through a compliance policy and marks the device compliant, and <b>conditional access</b> requires that signal for the SharePoint application. The label protects the file but does not condition on the device, DLP watches the data leaving and retention decides how long it is kept: none of the three looks at the machine's state. <a href=\"https://learn.microsoft.com/en-us/intune/intune-service/protect/device-compliance-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Without managing the device",
    q: "A partner company reaches Teams on their own laptops, which the organisation cannot administer. You want to stop them downloading files from shared channels. What do you design?",
    options: [
      "Requiring in conditional access that the device be Entra joined and marked compliant",
      "Enrolling those laptops in Intune with a restricted profile for Teams use only",
      "Conditional access app control with a session policy that blocks downloads",
      "Withdrawing access to the shared channels and publishing the files on your own external portal",
    ],
    correct: 2,
    explain: "\"We cannot administer the device\" rules out requiring compliance and rules out enrolling it. <b>Conditional access app control</b> puts the session behind a reverse proxy and applies a <b>session policy</b> that allows viewing and editing online but blocks the download: the data never lands on the unmanaged machine. Standing up a separate portal would work, but it rebuilds collaboration for a control that already exists. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Making the protection travel",
    q: "A contract is emailed to an external recipient and the worry is that they forward it on to third parties. Which Purview capability covers it?",
    options: [
      "A sensitivity label with encryption and usage rights that restrict forwarding",
      "A data loss prevention policy blocking the contract from being sent outside",
      "A seven-year retention policy over the mailbox the contract is sent from",
      "Information barriers between the department drafting the contract and the rest of the organisation",
    ],
    correct: 0,
    explain: "The restriction is about what happens <em>after the file has left</em>, and only a <b>sensitivity label with encryption</b> covers that: the usage rights travel inside the file itself and are evaluated when it is opened, wherever it is. <b>DLP</b> would block the send, which is not what is asked — the send is legitimate. Retention and information barriers answer different questions. <a href=\"https://learn.microsoft.com/en-us/purview/sensitivity-labels\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where the regulated data is",
    q: "A regulation requires knowing which SharePoint sites hold payment card numbers and preventing them from leaving by email. Which TWO Purview capabilities cover the requirement?",
    options: [
      "Sensitive information types, to discover and classify the data wherever it lives",
      "Information barriers between the teams working with payment data and the rest",
      "Insider risk management, to score the behaviour of whoever handles that data",
      "A data loss prevention policy with the email channel set to block",
    ],
    correct: [0, 3],
    explain: "Two verbs, two capabilities: <b>knowing where it is</b> is answered by <b>sensitive information types</b>, which recognise the card pattern with its checksum, and <b>stopping it leaving</b> by <b>DLP</b> on the email channel. Insider risk measures behaviour and information barriers separate communications: neither discovers the data nor blocks the channel. <a href=\"https://learn.microsoft.com/en-us/purview/sensitive-information-type-learn-about\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Copilot showing too much",
    q: "Piloting Copilot for Microsoft 365, several users receive summaries of other departments' documents. What is the cause and what do you do?",
    options: [
      "Copilot indexes the whole tenant with elevated permissions; its scope must be restricted to specific sites",
      "Copilot respects existing permissions: what surfaces is oversharing to fix at the source",
      "The model has memorised tenant content; the base model has to be retrained",
      "A Copilot-specific conditional access policy limiting which users can use it is missing",
    ],
    correct: 1,
    explain: "Copilot <b>creates no access</b>: it answers with what the user could already open. Documents from another department showing up means that user <em>already</em> had permission and nobody had noticed. It is fixed at the source — reviewing sites and \"anyone\" links, removing oversharing, labelling — not by fencing the assistant. And tenant data does not train the base models, so there is nothing memorised to retrain. <a href=\"https://learn.microsoft.com/en-us/copilot/microsoft-365/microsoft-365-copilot-privacy\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Auditing what was asked",
    q: "Compliance asks whether it is possible to know what a specific employee asked Copilot and what it answered, for an internal investigation. What do you answer?",
    options: [
      "That no record of the conversations remains, because they are processed without being stored in the tenant",
      "That only the interaction count per user remains, without the content of the conversation",
      "That the interactions are recorded in Purview Audit and support retention and eDiscovery",
      "That a specific diagnostic log has to be enabled first, with no retroactive effect",
    ],
    correct: 2,
    explain: "Copilot interactions are user activity in Microsoft 365 and land in <b>Purview Audit</b>, so they can be searched, put under <b>retention</b> and collected in <b>eDiscovery</b> like any other content. That is exactly the point the exam wants you to be able to state: the assistant is not a hole in data governance, it falls under the same tooling. <a href=\"https://learn.microsoft.com/en-us/purview/audit-solutions-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where to start with a portfolio",
    q: "An organisation with around two hundred internal applications wants to improve their security and asks where to start. What do you propose?",
    options: [
      "A penetration test on each application, beginning with the oldest ones in the catalogue",
      "Static analysis of every repository's code, prioritising afterwards by number of findings",
      "A WAF in front of all of them, to reduce risk while the deeper work is planned",
      "Inventorying and classifying by criticality and data handled, and prioritising effort on that basis",
    ],
    correct: 3,
    explain: "With two hundred applications the problem is not technical, it is <b>where to spend effort</b>: without knowing which are critical and what data they touch, any order is arbitrary. First the <b>inventory and classification</b>, and from that comes where penetration tests and analysis are worth it. A WAF on everything is a uniform patch over risks that are not uniform, and ordering by number of findings mistakes noise for risk. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What gets used without being registered",
    q: "The application inventory is maintained by hand by the architecture team, and both SaaS applications and published APIs are suspected to be missing from it. What do you add to the design?",
    options: [
      "Defender for Cloud Apps discovery for SaaS and Defender for APIs for what is published",
      "A mandatory registration process where each team declares its applications quarterly",
      "An Azure Policy rule blocking deployment of resources without the corresponding application tag",
      "A periodic port scan across the organisation's public address ranges",
    ],
    correct: 0,
    explain: "An inventory maintained by hand fails precisely on what is not declared. It is completed with <b>automatic discovery</b> per surface: <b>Defender for Cloud Apps</b> sees the SaaS actually in use from the traffic, and <b>Defender for APIs</b> inventories what is published in API Management. Quarterly declaration repeats the problem, the tag only covers what is deployed in Azure, and a port scan sees services, not applications. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "When threat modelling happens",
    q: "The team proposes threat modelling a critical application right before it goes to production, once everything is built. What do you point out?",
    options: [
      "That it is the right moment, because only then are the real implementation and its dependencies known",
      "That the moment does not matter as long as it is repeated for every major version of the application",
      "That it is a design activity: done on the diagram, producing requirements before building",
      "That it can be replaced by a penetration test, which finds the same problems once built",
    ],
    correct: 2,
    explain: "Threat modelling is a <b>design activity</b>: it is done on the data flow diagram and its output is <em>security requirements</em> that shape how the thing gets built. Doing it at the end turns every finding into an expensive redesign. And a penetration test does not replace it: that finds implementation defects, not architecture decisions that can no longer be changed. <a href=\"https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Classifying the threat",
    q: "Threat modelling an API surfaces that an authenticated client could call a method reserved for administrators by manipulating a parameter. Which STRIDE category is it and what mitigates it?",
    options: [
      "Tampering; mitigated by signing the request and checking its integrity on the server",
      "Elevation of privilege; mitigated by server-side authorization and input validation",
      "Information disclosure; mitigated by encrypting the response that method returns",
      "Spoofing; mitigated by requiring multifactor authentication to call the API",
    ],
    correct: 1,
    explain: "The client <em>is already authenticated</em> and manages to do something their role does not allow: that is <b>elevation of privilege</b>, and it is closed by checking <b>authorization on the server</b> — never trusting what the client sends — and validating input. <em>Tampering</em> breaks data integrity, disclosure exposes information they could already read, and spoofing is impersonation: not needed here, the identity is real. <a href=\"https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where to place the control",
    q: "You want to stop credentials embedded in code from reaching production. Where do you place the control for maximum effect?",
    options: [
      "In the IDE and in the pull request, so the secret never gets merged into the main branch",
      "In a weekly repository scan, notifying the author of each finding detected",
      "At runtime, with an alert when the application uses an unexpected credential",
      "In a manual code review before each production deployment, done by the security team",
    ],
    correct: 0,
    explain: "The <b>earlier</b> the control acts, the cheaper the fix and the smaller the exposure: a secret caught in the IDE is fixed before it ever exists in repository history, and one caught in the <b>pull request</b> never reaches the main branch. The weekly scan and the manual review arrive once the secret is written — and a merged secret has to be treated as compromised and rotated. <a href=\"https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-secret-scanning\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Vulnerable dependencies",
    q: "A scan reveals many applications carry old versions of libraries with known vulnerabilities. What does the lifecycle strategy add?",
    options: [
      "A WAF with rules specific to the vulnerabilities detected in each of those libraries",
      "Banning third-party libraries by policy in the portfolio's critical applications",
      "An annual dependency inventory, reviewed by architecture together with the owners",
      "Composition analysis in the pipeline, with automated updates of vulnerable dependencies",
    ],
    correct: 3,
    explain: "Dependencies change daily, so the control has to sit where things are built and be continuous: <b>composition analysis</b> in the pipeline that catches the vulnerable version and <b>automated updating</b> that opens the fix itself. A WAF mitigates some exploitation but does not fix the library. Banning third parties is not realistic. And an annual inventory runs far behind the rate at which vulnerabilities are published. <a href=\"https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-dependency-scanning\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The pipeline's credential",
    q: "The deployment pipeline authenticates to Azure with an app registration secret, stored as a secret variable in the continuous integration system. What do you propose?",
    options: [
      "Moving the secret to Key Vault and having the pipeline read it at startup, rotating every ninety days",
      "Workload identity federation, so there is no secret to store or rotate",
      "A certificate instead of the secret, with a long expiry so deployments are not interrupted",
      "Restricting by IP address the use of that app registration to the build agents",
    ],
    correct: 1,
    explain: "That is exactly the pattern the exam wants replaced. With <b>workload identity federation</b> the pipeline presents a token signed by its own provider and Entra ID exchanges it for access: there is <b>no secret</b> to store, rotate or steal. Reading it from Key Vault still needs a credential to reach Key Vault. The certificate is another secret. And IP filtering does not stop the credential being used from where it is supposed to be. <a href=\"https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Protecting the chain",
    q: "You want to stop a change reaching production without review, even from someone with write permission on the repository. What do you specify?",
    options: [
      "Removing write permission from everyone but the technical owners of each application",
      "An alert to the security team every time a change is pushed directly to the main branch",
      "Protected branches with mandatory review and production environments with prior approval",
      "A mandatory security scan in the pipeline that fails on any new finding",
    ],
    correct: 2,
    explain: "It is solved in the platform, not by removing permissions or watching afterwards: <b>protected branches</b> prevent direct pushes and require approval on the pull request, and <b>environments with approvals</b> hold the production deployment until somebody authorises it. The alert fires after the fact, removing permissions breaks daily work, and the scan looks at the content of the change, not at who approved it. <a href=\"https://learn.microsoft.com/en-us/azure/devops/pipelines/process/approvals\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Customer identities",
    q: "A new application will be used by end customers who sign themselves up, with social sign-in and password recovery. What do you specify?",
    options: [
      "Microsoft Entra External ID, which handles customer identities with self-service sign-up and social providers",
      "B2B invitations to the corporate tenant, one per customer who signs up for the application",
      "Users created in the corporate tenant through an automated sign-up process from the application",
      "The application's own authentication, with passwords stored hashed and salted in its database",
    ],
    correct: 0,
    explain: "<b>Customer or consumer</b> identities are their own case and have their own product: <b>Entra External ID</b>, with self-service sign-up, social providers, customisable flows and separation from the corporate directory. B2B is designed for partners, not for consumers at scale. Putting customers in the corporate tenant mixes two populations with different policies. And hand-writing authentication reintroduces a solved problem. <a href=\"https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Reaching the database without leaving",
    q: "An App Service application reaches an Azure SQL database and the requirement says that traffic must never cross the internet. What do you specify?",
    options: [
      "Firewall rules on the SQL server allowing only the App Service outbound addresses",
      "A service endpoint on the App Service subnet towards the Azure SQL service",
      "Virtual network integration on the App Service and a private endpoint on the SQL server",
      "A connection string forcing TLS 1.2 and verification of the server certificate",
    ],
    correct: 2,
    explain: "For the traffic <b>not to leave</b> you need both halves: <b>virtual network integration</b> puts the App Service outbound path inside your network, and the <b>private endpoint</b> gives SQL a private address within it. Firewall rules filter but the traffic still goes to the public address. A service endpoint keeps it on the Azure backbone but gives no private address. And TLS encrypts the path, it does not change it. <a href=\"https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "No secret for the application",
    q: "An Azure Function reads from a storage account and writes to Cosmos DB. Today it uses both services' keys in its configuration. What do you specify?",
    options: [
      "Moving both keys into Key Vault and referencing them from the function's configuration",
      "A managed identity for the function, with data roles over each service",
      "Rotating both keys through a monthly automation that updates the function's configuration",
      "An app registration with a certificate, shared by every function in the subscription",
    ],
    correct: 1,
    explain: "The exam's order of preference does not change: <b>managed identity</b> ahead of any secret. The function authenticates as itself against Entra ID and receives data roles scoped to each service: there is no key to store, rotate or leak. Key Vault improves the custody of a secret that could stop existing, and one identity shared across functions breaks least privilege and traceability. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Governing what is not a person",
    q: "An audit points out dozens of app registrations with broad permissions, no clear owner and no idea whether they are still in use. What do you add to the design?",
    options: [
      "Expiring every secret at thirty days so unused applications stop working by themselves",
      "A mandatory tag with the responsible team's name on every app registration",
      "An alert every time an app registration requests a new permission from the directory",
      "Workload identity governance: owner, access reviews and conditional access",
    ],
    correct: 3,
    explain: "Workload identities are governed like people's: an assigned <b>owner</b>, <b>access reviews</b> recertifying whether they are still needed and which permissions they keep, and <b>conditional access</b> to bound where they are used from. Expiring every secret at thirty days causes a cascading outage. The tag documents but does not recertify. And the alert covers what is new, not the dozens already there. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/identity-governance-applications-prepare\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "An API with no front door",
    q: "Each team publishes its APIs straight from its own App Service, with authentication solved differently in every one. What do you propose?",
    options: [
      "Documenting the authentication standard and checking in each pull request that every API implements it",
      "A WAF in front of each App Service, with the managed rule set for APIs enabled",
      "Publishing everything through API Management, validating the token at the gateway with a private backend",
      "A periodic penetration test on every published API, prioritised by service criticality",
    ],
    correct: 2,
    explain: "The problem is that <em>every API solves the same thing its own way</em>, and that is fixed by centralising the control at a gateway: <b>API Management</b> validates the Entra ID token, applies rate limiting and quotas, transforms the response and leaves the <b>backend on a private network</b>, reachable only from it. A documented standard depends on every team implementing it correctly, and a WAF filters requests but does not unify authorization. <a href=\"https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Abusing a public API",
    q: "A public query API is being scraped at scale by an authenticated client, exhausting the backend's capacity. Which control addresses it?",
    options: [
      "Rate limiting and quota policies per subscriber in API Management",
      "Revoking that client's access and blocking their source addresses at the firewall",
      "Automatically scaling the backend to absorb the volume that client generates",
      "A WAF with managed rules in front of the API, in prevention mode",
    ],
    correct: 0,
    explain: "The client is <b>authenticated and authorized</b>: this is not an attack a WAF recognises nor an origin worth blocking, it is <em>abusive use of the right they hold</em>. It is bounded with <b>rate limiting and quotas per subscriber</b> at the gateway, which is where the caller is known. Scaling the backend pays for the abuse. And revoking them handles one case without preventing the next. <a href=\"https://learn.microsoft.com/en-us/azure/api-management/api-management-sample-flexible-throttling\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Rolling out the WAF without breaking things",
    q: "A WAF is going in front of a high-traffic production application whose behaviour is poorly documented. How is it rolled out?",
    options: [
      "In prevention mode with the managed rule set, rolling back if user incidents appear",
      "In detection mode to measure false positives, tune with exclusions, and move to prevention afterwards",
      "In prevention mode but with critical rules only, adding the rest once things settle",
      "In detection mode permanently, so legitimate traffic is never at risk of being blocked",
    ],
    correct: 1,
    explain: "It is the same <em>measure, tune, enforce</em> pattern as in Azure Policy. <b>Detection mode</b> logs what it would block without blocking it, and from those logs you identify the false positives and write the <b>exclusions</b> and custom rules; only then do you move to <b>prevention</b>. Starting in prevention breaks production, and staying in detection forever means having a WAF that protects nothing. <a href=\"https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-tuning\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The WAF that gets bypassed",
    q: "With the WAF already in prevention on Application Gateway, a test shows requests arriving directly at the backend machines do not pass through it. What is missing?",
    options: [
      "Broadening the managed rule set so it also covers that kind of direct request",
      "Turning on WAF logging and shipping its events to Sentinel to detect the traffic going around it",
      "A second WAF, this time on Front Door, in front of the existing Application Gateway",
      "Having the backend machines accept traffic only from the Application Gateway subnet",
    ],
    correct: 3,
    explain: "A WAF only sees traffic that <b>goes through it</b>. If the backend accepts requests from any origin, passing through the WAF is optional for the attacker. It is closed in the network: a <b>security group</b> allowing only the Application Gateway subnet, and no public address on the machines. More rules or a second WAF are useless on a path that crosses neither, and logging detects after the fact. <a href=\"https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Before protecting, knowing",
    q: "An organisation wants to apply controls to the personal data it holds, but it is spread across Azure Storage, SQL databases and an on-premises file server. Where does it start?",
    options: [
      "By applying customer-managed key encryption across all three, to start from a common baseline",
      "By migrating all three sources into a single store on which one set of controls can be applied",
      "By scanning and classifying all three sources with Microsoft Purview, to know what exists and where",
      "By defining a common retention policy and applying it to the three data sources",
    ],
    correct: 2,
    explain: "You cannot protect what you do not know exists or where it lives: the first step is always <b>discovery and classification</b>. Purview's <b>data map</b> scans sources in Azure, in other clouds and on-premises, and classification recognises personal data through sensitive information types. Encryption and retention are controls <em>decided afterwards</em>, and migrating everything is a project that does not answer the question. <a href=\"https://learn.microsoft.com/en-us/purview/data-map-classification\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Precision in classification",
    q: "Classification is flagging many strings as customer numbers when they are not, and the data team is already suffering the noise. A master list of those numbers exists. What do you use?",
    options: [
      "Exact data match, checking against the master list rather than against a pattern",
      "A trainable classifier, fed with sample documents containing those numbers",
      "A custom sensitive information type with a stricter regular expression",
      "Lowering the confidence level required so only the clearest matches are flagged",
    ],
    correct: 0,
    explain: "When the <b>real list of values</b> exists, the answer is <b>exact data match</b>: it checks against an index of those specific values rather than a pattern, and false positives drop to practically zero. A stricter regular expression is still a pattern. A trainable classifier recognises <em>document types</em>, not values. And lowering the threshold changes the trade-off, not the precision. <a href=\"https://learn.microsoft.com/en-us/purview/sit-learn-about-exact-data-match-based-sits\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where to begin mitigating",
    q: "Defender for Cloud returns hundreds of recommendations about storage and databases. On what basis is the work ordered?",
    options: [
      "By recommendation severity, starting with every critical one on any resource",
      "By resources holding sensitive and exposed data, crossing classification with who can reach them",
      "By recommendation age, so none stays open indefinitely",
      "By owning team, splitting the total evenly so everyone makes progress at once",
    ],
    correct: 1,
    explain: "Prioritisation in this domain comes from crossing two axes: <b>sensitivity</b> — what classification says — and <b>exposure</b> — who can reach it. A store with regulated data reachable publicly comes before a critical on an empty test resource. Defender for Cloud supports this with sensitive data discovery and the attack paths ending at it. Severity, age and even splits order the list, not the risk. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/concept-data-security-posture\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The threat to the data",
    q: "A data risk analysis for an application identifies four scenarios. Which one is mitigated by immutable backups rather than by access controls?",
    options: [
      "That an employee with read permission downloads the full database",
      "That a leaked credential lets a third party query the data from outside the organisation",
      "That a developer reaches production data from a poorly isolated test environment",
      "That an attacker encrypts or deletes the data and demands payment to return it",
    ],
    correct: 3,
    explain: "The first three are <b>confidentiality</b> problems and are attacked with access, network and classification. The fourth is <b>availability and integrity</b>: against ransomware, no access control gives the data back once it is encrypted. What mitigates it is a copy the attacker cannot alter — <b>immutability</b>, locked retention, separate backup credentials — and having proved it by restoring. <a href=\"https://learn.microsoft.com/en-us/azure/storage/blobs/immutable-storage-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The three states of data",
    q: "A requirement says not even the cloud provider should be able to reach the data while the application processes it in memory. What covers it?",
    options: [
      "Customer-managed keys in Key Vault, with rotation and a log of every use of the key",
      "Infrastructure encryption, adding a second layer of encryption beneath the service's own",
      "Confidential computing, where data is only decrypted inside a processor enclave",
      "Encrypting the virtual machine's disk with a key held in Key Vault Managed HSM",
    ],
    correct: 2,
    explain: "The exam distinguishes three states and this is the third, the forgotten one: <b>in use</b>. No customer-managed key covers it, because the data has to be decrypted to be processed. <b>Confidential computing</b> decrypts it only inside a hardware-isolated <b>enclave</b>, out of reach of the hypervisor and the operator. The other three options protect data at rest, which was already solved here. <a href=\"https://learn.microsoft.com/en-us/azure/confidential-computing/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Being able to revoke the key",
    q: "A regulation requires the organisation to be able to render the data unreadable immediately and without depending on the provider. What do you specify?",
    options: [
      "Customer-managed keys, revoking the service's access to the key",
      "Soft delete and versioning on the storage where the data lives",
      "Infrastructure encryption over the data at rest, on top of the service's encryption",
      "A retention policy allowing the content to be deleted on request",
    ],
    correct: 0,
    explain: "Being able to <b>revoke</b> is what separates a customer key from the platform's: if the key lives in your <b>Key Vault</b> and you withdraw the service's access to it, the data stops being decryptable instantly and with no provider involvement. Infrastructure encryption adds a layer but is still platform-keyed. Soft delete and retention talk about keeping and removing, not about rendering unreadable. <a href=\"https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The corpus the AI reads",
    q: "An internal assistant answers by querying SharePoint documents. The worry is that it ends up exposing information to people who should not see it. What do you do first?",
    options: [
      "Limit the assistant to a small set of sites hand-picked by the platform team",
      "Log every assistant response to review afterwards the ones exposing sensitive data",
      "Encrypt with a customer-managed key the storage holding the documents it queries",
      "Classify and label the corpus, and fix the oversharing on the sites it queries",
    ],
    correct: 3,
    explain: "An assistant inherits the source's permissions: if the source is overshared, the assistant <b>spreads that oversharing faster</b>. The work is on the data — <b>classify, label and fix permissions</b> — not on the assistant. Hand-picking sites does not scale and leaves the problem untouched everywhere else. Logging detects afterwards. And encryption at rest does not change who holds read permission. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The data that leaves in the prompt",
    q: "Reviewing the design of a generative AI application, you see DLP covers email, Teams and endpoint, but nobody has looked at what users send in requests to the model. What do you point out?",
    options: [
      "That it does not apply, because the request travels over TLS to the organisation's own AI service",
      "That it is one more egress channel and must fall within the scope of classification and DLP",
      "That retention of the conversations is enough, allowing them to be reviewed if an incident arises",
      "That it is handled with a legal notice in the interface reminding users what not to type",
    ],
    correct: 1,
    explain: "The <em>prompt</em> is data <b>leaving the organisation towards a service</b>, exactly like an email attachment, and that is why it has to be in scope for classification and <b>DLP</b>. Travelling encrypted protects the transport, not the decision about what gets sent. Retention lets you look afterwards, once it has left. And a legal notice shifts responsibility to the user without implementing any control. <a href=\"https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Keeping it from the administrator",
    q: "A column of identification numbers must not be readable even by the Azure SQL database administrators. What do you specify?",
    options: [
      "Dynamic data masking on that column, with the unmask permission restricted",
      "Transparent data encryption with a customer-managed key held in Key Vault",
      "Always Encrypted, which encrypts on the client so the engine never sees the value in clear",
      "Row-level security preventing administrators from querying the rows holding that column",
    ],
    correct: 2,
    explain: "<b>Dynamic data masking</b> hides the value in the response, but the data is still in clear in the database and whoever holds the permission sees it. <b>Transparent data encryption</b> protects the files at rest, not the query. The only thing that leaves the value unreadable <em>to the engine and its administrators</em> is <b>Always Encrypted</b>: encryption and decryption happen on the client, with a key the database has no access to. <a href=\"https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Everyone sees their own",
    q: "An Azure SQL table holds data for every branch and each manager must only query their own, without duplicating the table or changing the application. What do you use?",
    options: [
      "Row-level security, with a predicate filtering by the identity running the query",
      "A view per branch, with permissions granted to each branch's group of managers",
      "Dynamic data masking on the branch column for unauthorised users",
      "Purview sensitivity labels applied to each branch's rows",
    ],
    correct: 0,
    explain: "<b>Row-level security</b> does exactly that: a predicate in the engine filters rows by who is running the query, transparently to the application, which keeps querying the same table. A view per branch works but means maintaining as many views as branches and changing the query. Masking hides columns, not rows. And labels classify, they do not filter. <a href=\"https://learn.microsoft.com/en-us/sql/relational-databases/security/row-level-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Revocable delegated access",
    q: "A vendor needs to upload files to a container for a few days. The team proposes a SAS signed with the account key. What do you point out?",
    options: [
      "That it is fine as long as the SAS is issued with a short expiry and write-only permissions",
      "That it cannot be revoked without rotating the account key: a user delegation SAS is better",
      "That the account key should be handed over directly and rotated when the work finishes",
      "That it should be reached over a private endpoint, which makes the SAS unnecessary",
    ],
    correct: 1,
    explain: "The problem with a SAS signed with the account key is <b>revocation</b>: cutting it short means rotating the key and taking down everything else that uses it. A <b>user delegation SAS</b> is signed with an Entra ID credential, inherits its permissions and is revoked by revoking that delegation, without touching the account. Handing over the key is worse. And a private endpoint decides how it is reached, not who may. <a href=\"https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Making it undeletable",
    q: "A sector regulation requires certain documentation to be kept for five years with no possibility of modifying or deleting it, not even by an administrator. Which TWO pieces does the design include?",
    options: [
      "A time-based immutability policy on the container, with the period locked",
      "A lifecycle rule moving the content to a cool access tier after thirty days",
      "Scoped data roles, so no identity holds delete permission over that container",
      "Versioning enabled on the account, to keep a copy of every modification of the content",
    ],
    correct: [0, 2],
    explain: "\"Not even by an administrator\" requires the block to sit in the <b>platform</b> rather than in permissions: a <b>time-based immutability policy</b> and, crucially, a <b>locked</b> one, which prevents deletion and overwriting for the period even for an owner. It is paired with <b>scoped roles</b>, because least privilege still applies. Lifecycle rules manage cost and versioning keeps copies, but neither prevents deletion. <a href=\"https://learn.microsoft.com/en-us/azure/storage/blobs/immutable-time-based-retention-policy-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detecting on storage",
    q: "On a storage account that is already hardened — no public access, private endpoint, no keys — you want to detect anomalous activity and malicious content uploaded by customers. What do you add?",
    options: [
      "Account diagnostic logging shipped to Sentinel, with analytics rules written by the SOC",
      "Defender CSPM, which evaluates the account's configuration and recommends what is left to harden",
      "Defender for Storage, with malware scanning on upload and anomalous access alerts",
      "An immutability policy on the containers where customers upload their files",
    ],
    correct: 2,
    explain: "The account is already well <b>configured</b>: what is missing is <b>detection</b>, and that is <b>Defender for Storage</b>, with malware scanning at upload time, alerts on access from anomalous identities or locations, and exfiltration detection. Defender CSPM looks at configuration, which is what is already solved. Logs in Sentinel mean writing those detections by hand. And immutability protects against deletion. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detecting on the database",
    q: "After an incident in the sector, management asks to be able to detect SQL injection attempts and anomalous access patterns across the Azure SQL databases. What is turned on?",
    options: [
      "Database auditing to a Log Analytics workspace, with one year of retention",
      "Row-level security and dynamic data masking over the tables holding customer data",
      "A WAF in prevention mode in front of the application that queries those databases",
      "Defender for Databases, which alerts on SQL injection and anomalous access",
    ],
    correct: 3,
    explain: "<b>Defender for Databases</b> is the detection plan for this service: it ships written detections for SQL injection, brute force and unusual access patterns, and adds vulnerability assessment of the database configuration. Auditing leaves the trail but does not alert on its own. The WAF filters at the application and misses whatever arrives by other paths. And row-level security controls access, it does not detect attacks. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-databases-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["apps-data"] = QUIZ_DATA;
