const QUIZ_DATA = [
  {
    tag: "Runbooks & OpsCenter",
    q: "¿Qué papel juega AWS Systems Manager OpsCenter en un plan de respuesta a incidentes?",
    options: [
      "Es un servicio de backup",
      "Centraliza 'OpsItems' (incidentes/problemas operativos) con contexto relacionado (recursos afectados, alarmas de CloudWatch, runbooks de Automation asociados), permitiendo investigar y ejecutar remediaciones desde un único lugar",
      "Sustituye a CloudTrail para auditoría",
      "Solo funciona con instancias EC2 Windows",
    ],
    correct: 1,
    explain: "OpsCenter agrega 'OpsItems' que representan incidentes u problemas operativos, enlazando automáticamente el contexto relevante (recursos, alarmas, runbooks de Systems Manager Automation ejecutables) — es la pieza de Systems Manager pensada para centralizar la investigación y ejecución de la respuesta, no solo el registro pasivo del incidente.",
  },
  {
    tag: "Preparación: minimizar blast radius",
    q: "Como parte de PREPARAR una cuenta para incidentes (antes de que ocurran), ¿qué práctica reduce el 'blast radius' si una carga de trabajo se ve comprometida?",
    options: [
      "Usar una única cuenta de AWS para todo, simplificando la gestión",
      "Segmentar cargas de trabajo en cuentas separadas (multi-account strategy), con permisos IAM de mínimo privilegio y sin credenciales de larga duración compartidas entre entornos",
      "Dar AdministratorAccess a todos los roles para agilizar la respuesta cuando ocurra un incidente",
      "Desactivar CloudTrail para reducir ruido",
    ],
    correct: 1,
    explain: "Minimizar el blast radius es una actividad de PREPARACIÓN (skill 2.1.2): separar cargas de trabajo en cuentas distintas, aplicar mínimo privilegio y evitar credenciales compartidas limita cuánto puede alcanzar un atacante si compromete un solo componente — mucho más barato hacerlo antes del incidente que durante.",
  },
  {
    tag: "Provisionar acceso de emergencia",
    q: "¿Por qué es importante tener PRE-PROVISIONADO (antes del incidente) el acceso que el equipo de respuesta necesitará durante una investigación?",
    options: [
      "No es importante, se puede crear el acceso necesario en el momento del incidente sin impacto",
      "Porque durante un incidente activo no quieres depender de flujos de aprobación IAM lentos ni de crear roles nuevos con prisa (riesgo de sobre-otorgar permisos); un rol de IR con permisos ya auditados y probados reduce tiempo de respuesta y errores",
      "Porque IAM no permite crear roles nuevos si GuardDuty está activo",
      "Solo aplica si usas IAM Identity Center",
    ],
    correct: 1,
    explain: "Skill 2.1.2 explícitamente menciona 'provisioning access' como parte de la preparación: un rol de IR con permisos de solo lectura amplios + acciones de contención específicas (aislar SG, crear snapshot), ya probado y auditado de antemano, evita improvisar permisos bajo presión durante el incidente — que es exactamente cuando más fácil es cometer un error de sobre-privilegio.",
  },
  {
    tag: "AWS Fault Injection Service",
    q: "¿Para qué se usa AWS Fault Injection Service (FIS) en el contexto de validar un plan de respuesta a incidentes?",
    options: [
      "Para desplegar parches de seguridad automáticamente",
      "Para ejecutar experimentos de chaos engineering CONTROLADOS (ej. simular la caída de una AZ, latencia de red, terminar instancias) y así probar si tus alarmas, runbooks y plan de respuesta realmente funcionan como se espera",
      "Para generar tráfico de ataque real contra producción sin control",
      "Es un servicio exclusivo de forense de malware",
    ],
    correct: 1,
    explain: "FIS permite diseñar y ejecutar experimentos de fallo controlados y con guardrails (stop conditions automáticas si algo se sale de lo esperado) para validar que la detección, alertado y los runbooks de respuesta funcionan de verdad — sin esperar a un incidente real para descubrir que la alarma nunca se disparó.",
  },
  {
    tag: "AWS Resilience Hub",
    q: "¿Qué evalúa AWS Resilience Hub?",
    options: [
      "El coste de una arquitectura",
      "La resiliencia de una aplicación frente a objetivos de recuperación definidos (RTO/RPO), identificando brechas en la arquitectura y recomendando mejoras, y puede orquestar experimentos de FIS para validarlo",
      "Solo el cumplimiento de PCI-DSS",
      "La latencia de red entre regiones",
    ],
    correct: 1,
    explain: "Resilience Hub evalúa una aplicación definida contra objetivos de RTO (tiempo de recuperación) y RPO (punto de recuperación/pérdida de datos aceptable), señala dónde la arquitectura actual no los cumpliría, y puede generar/ejecutar experimentos de FIS para validar la resiliencia real — complementario a FIS (FIS ejecuta el experimento, Resilience Hub define contra qué objetivo se mide).",
  },
  {
    tag: "Remediación automática",
    q: "Quieres que, en cuanto GuardDuty genere un finding de severidad alta sobre una instancia EC2 (ej. comunicación con un IP de minería de criptomonedas), se aísle automáticamente esa instancia sin esperar a que un humano actúe. ¿Qué arquitectura implementas?",
    options: [
      "Revisar los findings manualmente cada mañana",
      "Una regla de EventBridge que capture el finding de GuardDuty y dispare una función Lambda o un Step Functions state machine que cambie el Security Group de la instancia a uno de cuarentena (sin tráfico permitido salvo hacia la subnet forense)",
      "Desactivar la instancia manualmente vía consola cuando alguien lo note",
      "Configurar una SCP que bloquee GuardDuty",
    ],
    correct: 1,
    explain: "El patrón estándar de remediación automática (skill 2.1.4) es: finding de GuardDuty → EventBridge rule (filtra por severidad/tipo) → Lambda/Step Functions ejecuta la acción de contención (ej. modificar el Security Group a uno de cuarentena) — todo en segundos, sin esperar intervención humana para la contención inicial.",
  },
  {
    tag: "Automated Forensics Orchestrator",
    q: "¿Qué automatiza la solución de AWS 'Automated Forensics Orchestrator for Amazon EC2'?",
    options: [
      "El escaneo de vulnerabilidades continuo con Inspector",
      "Todo el flujo forense ante una instancia EC2 comprometida: aislamiento de red (SG de cuarentena), captura de snapshot EBS y memoria, etiquetado para cadena de custodia, y notificación al equipo de IR — sin intervención manual en cada paso",
      "La rotación de credenciales de IAM",
      "El despliegue de parches en toda la flota",
    ],
    correct: 1,
    explain: "Es una solución de AWS (basada en Step Functions + Lambda) que orquesta automáticamente el proceso forense completo ante una instancia comprometida: aislar la red, capturar evidencia (snapshots de disco y memoria), preservar la cadena de custodia con etiquetado/logging, y notificar — reduciendo el tiempo de contención de horas a minutos.",
  },
  {
    tag: "Contención de red",
    q: "¿Cuál es la forma más rápida y segura de aislar de la red una instancia EC2 comprometida SIN apagarla (preservando el estado de memoria para análisis forense)?",
    options: [
      "Terminar la instancia inmediatamente",
      "Cambiar su Security Group a uno de 'cuarentena' sin reglas de entrada/salida (o solo con salida hacia la subnet/herramientas forenses), manteniendo la instancia encendida para poder capturar memoria antes de cualquier otra acción",
      "Desconectar el cable de red físicamente",
      "Cambiar la contraseña del sistema operativo",
    ],
    correct: 1,
    explain: "Apagar o terminar la instancia destruye la memoria RAM (evidencia volátil valiosa). La práctica correcta es aislar a nivel de red (Security Group de cuarentena) manteniendo la instancia ENCENDIDA, para poder capturar un memory dump antes de proceder con el análisis y la eventual sustitución de la instancia.",
  },
  {
    tag: "Captura de evidencia forense",
    q: "Al capturar evidencia forense de una instancia EC2 comprometida para su posterior análisis, ¿qué DOS artefactos son más valiosos capturar antes de cualquier otra acción?",
    options: [
      "Solo los logs de CloudTrail de la cuenta",
      "Un snapshot del volumen EBS (estado del disco) y una captura de memoria (RAM) de la instancia — la memoria contiene evidencia volátil (procesos en ejecución, conexiones activas, claves en memoria) que se pierde al apagar la instancia",
      "Solo las métricas de CloudWatch de CPU",
      "El historial de facturación de la cuenta",
    ],
    correct: 1,
    explain: "El snapshot EBS preserva el estado del disco para análisis posterior sin alterar la instancia original. La captura de memoria (usando herramientas como el AVML de AWS o similares, vía Systems Manager) preserva evidencia volátil que desaparece en cuanto la instancia se apaga o reinicia — ambos artefactos son prioritarios en la fase de contención/captura.",
  },
  {
    tag: "SageMaker AI para forense",
    q: "El exam guide de SCS-C03 menciona explícitamente 'Amazon SageMaker AI notebooks' como ejemplo del skill 2.1.1 (runbooks de respuesta a incidentes). ¿Para qué se usarían en este contexto?",
    options: [
      "Para entrenar modelos de machine learning de producción",
      "Como entorno de análisis AISLADO y programático (notebooks Jupyter) para examinar artefactos forenses capturados (memory dumps, logs, snapshots montados), ejecutando scripts de análisis de forma repetible y documentada",
      "SageMaker no tiene ninguna relación con incident response, es un error del examen",
      "Para desplegar el sitio web de la empresa durante el incidente",
    ],
    correct: 1,
    explain: "Aunque SageMaker es conocido por ML, sus notebooks (entornos Jupyter gestionados y aislados) son útiles como banco de trabajo forense: analizar artefactos capturados con scripts en Python de forma reproducible, documentada, y en un entorno separado de la infraestructura de producción — un uso no obvio que el examen prueba precisamente porque sorprende.",
  },
  {
    tag: "Validar findings antes de actuar",
    q: "Recibes un finding de GuardDuty de severidad media sobre una instancia. Antes de ejecutar acciones de contención de gran impacto (ej. terminar la instancia), ¿qué deberías hacer primero según el skill 2.2.3?",
    options: [
      "Actuar inmediatamente sin verificar nada, la velocidad es lo único que importa",
      "Validar el finding: confirmar el alcance real y el impacto (¿qué recursos están realmente afectados?, ¿es un falso positivo conocido?, ¿hay corroboración en otras fuentes como VPC Flow Logs o CloudTrail?) antes de escalar a una respuesta de alto impacto",
      "Ignorar los findings de severidad media siempre",
      "Esperar 48 horas antes de revisar cualquier finding",
    ],
    correct: 1,
    explain: "El skill 2.2.3 (nuevo en SCS-C03) pide explícitamente validar findings para determinar el alcance e impacto reales antes de actuar — evita tanto la parálisis por sobre-análisis como la respuesta desproporcionada a un falso positivo, correlacionando el finding con otras fuentes (Flow Logs, CloudTrail, Detective) antes de una acción de alto impacto como terminar un recurso de producción.",
  },
  {
    tag: "Amazon Detective",
    q: "¿Qué resuelve Amazon Detective que GuardDuty y Security Hub por sí solos no resuelven bien?",
    options: [
      "Detective sustituye la necesidad de tener GuardDuty activado",
      "Detective construye automáticamente un GRAFO de comportamiento e interacciones entre recursos (IAM roles, instancias, IPs) a lo largo del tiempo, facilitando el análisis de causa raíz — responder '¿cómo llegó el atacante hasta aquí y qué más tocó?' en vez de solo '¿qué pasó en este evento puntual?'",
      "Detective es simplemente un dashboard de costes",
      "Detective solo analiza logs de RDS",
    ],
    correct: 1,
    explain: "GuardDuty y Security Hub te dicen QUÉ pasó (findings puntuales). Detective agrega automáticamente datos de CloudTrail, VPC Flow Logs y GuardDuty en un grafo navegable de relaciones entre entidades a lo largo del tiempo, permitiendo trazar la CADENA de eventos (root cause analysis) — 'este rol IAM comprometido a las 3:15 accedió después a estos 4 recursos y desde esta IP nueva'.",
  },
  {
    tag: "Amazon Detective",
    q: "¿Detective REEMPLAZA la necesidad de tener CloudTrail y VPC Flow Logs activados?",
    options: [
      "Sí, Detective genera sus propios logs independientes",
      "No: Detective CONSUME esos logs (CloudTrail, VPC Flow Logs, GuardDuty findings, y opcionalmente logs de EKS) para construir su grafo de comportamiento — si esas fuentes no están activas o Detective no está habilitado con suficiente antelación, el histórico disponible para investigar será limitado",
      "Detective solo funciona sin CloudTrail activado",
      "Detective sustituye completamente a Security Hub",
    ],
    correct: 1,
    explain: "Detective depende de que esas fuentes de log ya existan — no las sustituye, las CORRELACIONA. Además, Detective mantiene hasta 1 año de datos históricos para análisis retrospectivo, pero solo desde el momento en que se habilitó: es buena práctica activarlo de forma preventiva (parte de la preparación), no esperar al incidente para activarlo.",
  },
  {
    tag: "Recuperación",
    q: "Tras contener y erradicar un compromiso en una instancia EC2, ¿cuál es la práctica MÁS segura para recuperar el servicio?",
    options: [
      "Reiniciar la misma instancia comprometida y seguir usándola",
      "Sustituir la instancia por una nueva desplegada desde una AMI hardened conocida-buena (golden image), en vez de intentar 'limpiar' la instancia comprometida in-place — es prácticamente imposible garantizar que no queda ningún rastro de persistencia del atacante",
      "Restaurar únicamente las contraseñas de los usuarios locales",
      "Aplicar solo los parches pendientes sobre la instancia comprometida",
    ],
    correct: 1,
    explain: "El principio de recuperación tras un compromiso es 'no confíes en lo que pudo haber sido alterado': reconstruir desde una imagen limpia conocida (golden AMI, IaC) es mucho más fiable que intentar limpiar manualmente una instancia donde el atacante pudo haber dejado backdoors, tareas programadas o binarios modificados difíciles de detectar todos.",
  },
  {
    tag: "Restaurar desde backup",
    q: "Durante la fase de recuperación tras un incidente de ransomware que cifró datos en producción, ¿qué verificación es CRÍTICA hacer antes de restaurar desde un backup?",
    options: [
      "Ninguna, restaurar el backup más reciente disponible siempre es correcto",
      "Confirmar que el backup elegido es de ANTES de que ocurriera el compromiso (no un backup que ya contenga los datos cifrados o una puerta trasera persistida), usando backups inmutables (Vault Lock) como fuente de confianza",
      "Solo verificar el tamaño del backup",
      "Preguntar al atacante qué backup es seguro",
    ],
    correct: 1,
    explain: "Restaurar un backup posterior al compromiso puede reintroducir la misma vulnerabilidad o incluso datos ya cifrados/backdoors. Por eso los backups inmutables (AWS Backup Vault Lock, S3 Object Lock) son tan valorados: garantizan que existe al menos una versión anterior al ataque que no pudo ser alterada ni siquiera por el atacante con credenciales de administrador.",
  },
  {
    tag: "Correlación de logs multi-servicio",
    q: "Investigas un posible movimiento lateral de un atacante que comprometió credenciales IAM. ¿Qué combinación de fuentes te da la imagen más completa del alcance (skill 2.2.2)?",
    options: [
      "Solo revisar la factura de AWS del mes",
      "Correlacionar CloudTrail (qué acciones de API se hicieron con esas credenciales), VPC Flow Logs (a qué recursos de red se conectó), y los findings de GuardDuty/Detective (patrones ya marcados como anómalos) en la misma ventana de tiempo",
      "Solo mirar las alarmas de CloudWatch de CPU",
      "Solo el Cost Explorer",
    ],
    correct: 1,
    explain: "El movimiento lateral deja rastro en múltiples capas: CloudTrail muestra QUÉ hizo el atacante vía API, VPC Flow Logs muestra A QUÉ se conectó a nivel de red, y GuardDuty/Detective ya correlacionan patrones anómalos automáticamente. Cruzar las tres fuentes en la misma ventana temporal es lo que permite reconstruir el alcance real, en vez de mirar cada una de forma aislada.",
  },
  {
    tag: "Application Recovery Controller",
    q: "¿Para qué sirve Amazon Application Recovery Controller (ARC) en un escenario de incidente que afecta a una región completa?",
    options: [
      "Para escanear vulnerabilidades de aplicaciones",
      "Para orquestar y monitorizar el failover de una aplicación multi-región de forma segura y controlada (readiness checks + routing controls), evitando failovers manuales propensos a error durante una crisis",
      "Para gestionar certificados TLS",
      "Es un servicio de backup de bases de datos",
    ],
    correct: 1,
    explain: "ARC verifica continuamente que la infraestructura de la región de respaldo está realmente lista para recibir tráfico (readiness checks) y proporciona 'routing controls' seguros (con protección contra activaciones accidentales) para ejecutar el failover — pensado exactamente para el momento de máxima presión de un incidente de disponibilidad regional.",
  },
  {
    tag: "Cadena de custodia",
    q: "¿Por qué es importante etiquetar y documentar (timestamp, quién, qué acción) cada artefacto forense capturado durante un incidente (snapshots, memory dumps, logs exportados)?",
    options: [
      "Solo por organización visual, no tiene impacto real",
      "Para mantener la cadena de custodia: si el incidente termina en una acción legal/regulatoria, poder demostrar que la evidencia no fue alterada y quién tuvo acceso a ella en cada momento",
      "Porque AWS lo factura de forma distinta si está etiquetado",
      "No es relevante para el examen",
    ],
    correct: 1,
    explain: "La cadena de custodia (chain of custody) es un requisito frecuente en investigaciones que pueden derivar en acciones legales o reportes regulatorios: sin un registro claro de captura, acceso y manejo de cada artefacto forense, la evidencia puede perder validez. Soluciones como Automated Forensics Orchestrator automatizan este etiquetado desde el primer paso.",
  },
  {
    tag: "IR plan testing",
    q: "¿Cuál es la diferencia entre 'probar' un plan de respuesta a incidentes con un tabletop exercise y con AWS Fault Injection Service?",
    options: [
      "Son exactamente lo mismo",
      "Un tabletop exercise es una simulación DISCUTIDA verbalmente por el equipo (sin tocar sistemas reales) para validar el PROCESO y la comunicación; FIS ejecuta fallos TÉCNICOS reales y controlados contra la infraestructura para validar que las alarmas/runbooks automatizados realmente se disparan y funcionan",
      "FIS solo puede usarse una vez al año por límites de AWS",
      "Los tabletop exercises requieren interrumpir producción, FIS no",
    ],
    correct: 1,
    explain: "Ambos son formas válidas de 'test and validate' (skill 2.1.3) mencionadas en el exam guide, mutuamente complementarias: el tabletop valida que el EQUIPO sabe qué hacer y se comunica bien; FIS valida que la TECNOLOGÍA (alarmas, automatizaciones, runbooks ejecutables) responde de verdad como se diseñó, con guardrails para no causar un incidente real por accidente.",
  },
];
