var QUIZ_DATA = [
  {
    tag: "Runbooks & OpsCenter",
    q: "¿Qué papel juega AWS Systems Manager OpsCenter en un plan de respuesta a incidentes?",
    options: [
      "Centraliza OpsItems con su contexto —recursos, alarmas— y permite ejecutar runbooks de Automation",
      "Almacena copias de seguridad de instancias EC2 y bases de datos con políticas de retención centralizadas",
      "Sustituye a CloudTrail como registro de auditoría de las llamadas a la API durante el incidente",
      "Gestiona incidentes únicamente en instancias EC2 Windows registradas en Systems Manager Inventory",
    ],
    correct: 0,
    explain: "OpsCenter agrega 'OpsItems' que representan incidentes o problemas operativos, enlazando automáticamente el contexto relevante (recursos, alarmas de CloudWatch, runbooks de Systems Manager Automation ejecutables) — es la pieza de Systems Manager pensada para centralizar la investigación y la ejecución de la respuesta, no solo el registro pasivo del incidente. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/OpsCenter.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Preparación: minimizar blast radius",
    q: "Como parte de PREPARAR una cuenta para incidentes (antes de que ocurran), ¿qué práctica reduce el 'blast radius' si una carga de trabajo se ve comprometida?",
    options: [
      "Usar una única cuenta de AWS para todo, de modo que la auditoría y la respuesta a incidentes queden centralizadas",
      "Segmentar cargas en cuentas separadas, con mínimo privilegio y sin credenciales compartidas entre entornos",
      "Conceder AdministratorAccess a todos los roles para que la respuesta no se frene por falta de permisos",
      "Desactivar CloudTrail en las cuentas de desarrollo para que el ruido no oculte los eventos importantes",
    ],
    correct: 1,
    explain: "Minimizar el blast radius es una actividad de PREPARACIÓN (skill 2.1.2): separar cargas de trabajo en cuentas distintas, aplicar mínimo privilegio y evitar credenciales compartidas limita cuánto puede alcanzar un atacante si compromete un solo componente — mucho más barato hacerlo antes del incidente que durante. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/aws-security-incident-response-guide/preparation.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Provisionar acceso de emergencia",
    q: "¿Por qué es importante tener PRE-PROVISIONADO (antes del incidente) el acceso que el equipo de respuesta necesitará durante una investigación?",
    options: [
      "No es relevante: los permisos se pueden crear en caliente durante el incidente sin coste de tiempo",
      "Porque IAM bloquea la creación de roles nuevos mientras GuardDuty tenga findings activos sin resolver en la cuenta",
      "Evita depender de aprobaciones lentas y de improvisar permisos con prisa, que es cuando se sobre-otorga",
      "Solo aporta ventaja si la organización usa IAM Identity Center en lugar de usuarios IAM locales",
    ],
    correct: 2,
    explain: "El skill 2.1.2 menciona explícitamente 'provisioning access' como parte de la preparación: un rol de IR con permisos de solo lectura amplios más acciones de contención específicas (aislar un SG, crear un snapshot), ya probado y auditado de antemano, evita improvisar permisos bajo presión — que es exactamente cuando más fácil resulta cometer un error de sobre-privilegio. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/aws-security-incident-response-guide/prepare-processes.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Fault Injection Service",
    q: "¿Para qué se usa AWS Fault Injection Service (FIS) en el contexto de validar un plan de respuesta a incidentes?",
    options: [
      "Para desplegar parches de seguridad de forma automática sobre la flota tras detectar una vulnerabilidad",
      "Para analizar volcados de memoria y discos de instancias comprometidas en un entorno forense aislado",
      "Para lanzar tráfico de ataque real y sin límites contra producción y medir su capacidad de aguante",
      "Para ejecutar experimentos de fallo controlados y comprobar si alarmas y runbooks responden de verdad",
    ],
    correct: 3,
    explain: "FIS permite diseñar y ejecutar experimentos de fallo controlados y con guardrails (stop conditions automáticas si algo se sale de lo esperado) para validar que la detección, el alertado y los runbooks de respuesta funcionan de verdad — sin esperar a un incidente real para descubrir que la alarma nunca se disparó. <a href=\"https://docs.aws.amazon.com/fis/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Resilience Hub",
    q: "¿Qué evalúa AWS Resilience Hub?",
    options: [
      "La resiliencia de una aplicación frente a sus objetivos de RTO/RPO, con recomendaciones y experimentos FIS",
      "El coste mensual de una arquitectura y las oportunidades de ahorro con instancias reservadas o Savings Plans",
      "El cumplimiento de PCI-DSS de las cuentas, generando el informe de evidencias para el auditor",
      "La latencia de red entre regiones para decidir dónde desplegar la réplica de la aplicación",
    ],
    correct: 0,
    explain: "Resilience Hub evalúa una aplicación definida contra objetivos de RTO (tiempo de recuperación) y RPO (punto de recuperación o pérdida de datos aceptable), señala dónde la arquitectura actual no los cumpliría, y puede generar y ejecutar experimentos de FIS para validar la resiliencia real — complementario a FIS: FIS ejecuta el experimento, Resilience Hub define contra qué objetivo se mide. <a href=\"https://docs.aws.amazon.com/resilience-hub/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Remediación automática",
    q: "Quieres que, en cuanto GuardDuty genere un finding de severidad alta sobre una instancia EC2 (ej. comunicación con un IP de minería de criptomonedas), se aísle automáticamente esa instancia sin esperar a que un humano actúe. ¿Qué arquitectura implementas?",
    options: [
      "Un informe diario que agrupa los findings de la noche para que un analista los revise por la mañana",
      "Una regla de EventBridge sobre el finding que invoca Lambda o Step Functions y aplica un SG de cuarentena",
      "Una alarma de CloudWatch sobre la CPU de la instancia que avisa por SNS al equipo de guardia para que actúe",
      "Una SCP que impida a la instancia asumir roles nuevos hasta que un administrador la desbloquee",
    ],
    correct: 1,
    explain: "El patrón estándar de remediación automática (skill 2.1.4) es: finding de GuardDuty → regla de EventBridge que filtra por severidad o tipo → Lambda o Step Functions ejecuta la acción de contención (por ejemplo, cambiar el Security Group por uno de cuarentena), todo en segundos y sin esperar intervención humana para la contención inicial. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_eventbridge.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Automated Forensics Orchestrator",
    q: "¿Qué automatiza la solución de AWS 'Automated Forensics Orchestrator for Amazon EC2'?",
    options: [
      "El escaneo continuo de vulnerabilidades del sistema operativo y de los paquetes con Amazon Inspector",
      "La rotación periódica de las access keys de IAM y de los secretos guardados en Secrets Manager",
      "El flujo forense ante una EC2 comprometida: aislar, capturar disco y memoria y trazar la custodia",
      "El despliegue de parches en toda la flota con Patch Manager en cuanto se publica un boletín",
    ],
    correct: 2,
    explain: "Es una guidance de AWS (basada en Step Functions y Lambda) que orquesta automáticamente el proceso forense completo ante una instancia comprometida: aislar la red, capturar evidencia (snapshots de disco y volcado de memoria), preservar la cadena de custodia con etiquetado y logging, y notificar — reduciendo el tiempo de contención de horas a minutos. <a href=\"https://docs.aws.amazon.com/solutions/latest/automated-forensics-orchestrator-for-amazon-ec2/welcome.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Contención de red",
    q: "¿Cuál es la forma más rápida y segura de aislar de la red una instancia EC2 comprometida SIN apagarla (preservando el estado de memoria para análisis forense)?",
    options: [
      "Terminar la instancia de inmediato: cortar la comunicación con el atacante es siempre lo prioritario",
      "Cambiar la contraseña del sistema operativo y rotar las claves SSH de todos los usuarios locales",
      "Detener (stop) la instancia, ya que el estado de la RAM se conserva intacto en su volumen raíz de EBS",
      "Aplicarle un Security Group de cuarentena sin reglas, dejándola encendida para capturar la memoria",
    ],
    correct: 3,
    explain: "Apagar o terminar la instancia destruye la memoria RAM, que es evidencia volátil valiosa (un <code>stop</code> tampoco la preserva: la RAM no se vuelca al volumen raíz). La práctica correcta es aislar a nivel de red con un Security Group de cuarentena manteniendo la instancia ENCENDIDA, para poder capturar un volcado de memoria antes del análisis y de la eventual sustitución. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/compromised-ec2.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Captura de evidencia forense",
    q: "Al capturar evidencia forense de una instancia EC2 comprometida para su posterior análisis, ¿qué DOS artefactos son más valiosos capturar antes de cualquier otra acción?",
    options: [
      "Un snapshot del volumen EBS y un volcado de la memoria RAM, tomados antes de tocar nada más",
      "Los logs de CloudTrail de la cuenta y el historial de facturación del mes en el que ocurrió",
      "Las métricas de CPU y de red de CloudWatch durante la ventana en la que se detectó el finding",
      "El inventario de software de Systems Manager y la lista de parches pendientes de la instancia",
    ],
    correct: 0,
    explain: "El snapshot EBS preserva el estado del disco para el análisis posterior sin alterar la instancia original. El volcado de memoria (con herramientas como AVML, ejecutadas vía Systems Manager) preserva evidencia volátil que desaparece en cuanto la instancia se apaga o reinicia — ambos artefactos son prioritarios en la fase de contención y captura. <a href=\"https://docs.aws.amazon.com/ebs/latest/userguide/ebs-snapshots.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SageMaker AI para forense",
    q: "El exam guide de SCS-C03 menciona explícitamente 'Amazon SageMaker AI notebooks' como ejemplo del skill 2.1.1 (runbooks de respuesta a incidentes). ¿Para qué se usarían en este contexto?",
    options: [
      "Para entrenar modelos de machine learning de producción con los datos recuperados de la instancia",
      "Como banco de trabajo aislado y reproducible para analizar artefactos forenses con scripts en Python",
      "Para detectar el malware dentro del snapshot, sustituyendo a GuardDuty Malware Protection for EC2",
      "Para servir la aplicación afectada mientras se reconstruye la infraestructura desde la imagen dorada",
    ],
    correct: 1,
    explain: "Aunque SageMaker es conocido por ML, sus notebook instances (entornos Jupyter gestionados y aislados) son útiles como banco de trabajo forense: analizar artefactos capturados con scripts en Python de forma reproducible y documentada, en un entorno separado de la infraestructura de producción — un uso no obvio que el examen prueba precisamente porque sorprende. <a href=\"https://docs.aws.amazon.com/sagemaker/latest/dg/nbi.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Validar findings antes de actuar",
    q: "Recibes un finding de GuardDuty de severidad media sobre una instancia. Antes de ejecutar acciones de contención de gran impacto (ej. terminar la instancia), ¿qué deberías hacer primero según el skill 2.2.3?",
    options: [
      "Actuar de inmediato sobre el recurso: en respuesta a incidentes la velocidad prima sobre la certeza",
      "Descartar por norma los findings de severidad media, ya que rara vez implican actividad maliciosa",
      "Validar el alcance y el impacto reales, corroborando el finding con CloudTrail y VPC Flow Logs",
      "Suprimir el finding con una supresión y revisarlo en la reunión de seguridad de la semana siguiente",
    ],
    correct: 2,
    explain: "El skill 2.2.3 (nuevo en SCS-C03) pide explícitamente validar findings para determinar el alcance y el impacto reales antes de actuar — evita tanto la parálisis por sobre-análisis como la respuesta desproporcionada a un falso positivo, correlacionando el finding con otras fuentes (Flow Logs, CloudTrail, Detective) antes de una acción de alto impacto como terminar un recurso de producción. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_remediate.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Detective",
    q: "¿Qué resuelve Amazon Detective que GuardDuty y Security Hub por sí solos no resuelven bien?",
    options: [
      "Detective inspecciona el payload del tráfico, evitando tener que usar VPC Traffic Mirroring",
      "Detective evalúa la configuración de los recursos frente a controles de seguridad, igual que AWS Config",
      "Detective agrupa los findings por coste para priorizar los recursos más caros del entorno",
      "Detective construye un grafo de comportamiento entre entidades, base del análisis de causa raíz",
    ],
    correct: 3,
    explain: "GuardDuty y Security Hub te dicen QUÉ pasó (findings puntuales). Detective agrega automáticamente datos de CloudTrail, VPC Flow Logs y GuardDuty en un grafo navegable de relaciones entre entidades a lo largo del tiempo, permitiendo trazar la CADENA de eventos (root cause analysis): 'este rol IAM comprometido a las 3:15 accedió después a estos 4 recursos y desde esta IP nueva'. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/what-is-detective.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Detective",
    q: "¿Detective REEMPLAZA la necesidad de tener CloudTrail y VPC Flow Logs activados?",
    options: [
      "No: consume esos logs para construir su grafo, así que su histórico empieza cuando se habilita",
      "Sí: Detective genera sus propios logs independientes y no necesita ninguna fuente previa activa",
      "Detective solo puede habilitarse en cuentas con CloudTrail desactivado, para evitar duplicidades",
      "Detective sustituye a Security Hub como agregador central de los findings de todas las cuentas",
    ],
    correct: 0,
    explain: "Detective depende de que esas fuentes de log existan — no las sustituye, las CORRELACIONA (usa flujos propios y duplicados de CloudTrail y VPC Flow Logs, sin alterar tu configuración ni tu factura de esos servicios). Mantiene hasta 1 año de datos históricos, pero solo desde que se habilitó: conviene activarlo de forma preventiva, no esperar al incidente. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/detective-source-data-about.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Recuperación",
    q: "Tras contener y erradicar un compromiso en una instancia EC2, ¿cuál es la práctica MÁS segura para recuperar el servicio?",
    options: [
      "Reiniciar la instancia comprometida: el reinicio elimina los procesos maliciosos que viven en memoria",
      "Sustituirla por una instancia nueva desplegada desde una AMI hardened conocida-buena, sin limpiarla",
      "Restaurar las contraseñas locales y las claves SSH, que es por donde entró el atacante inicialmente",
      "Aplicar los parches pendientes sobre la instancia comprometida y devolverla al balanceador de carga",
    ],
    correct: 1,
    explain: "El principio de recuperación tras un compromiso es 'no confíes en lo que pudo haber sido alterado': reconstruir desde una imagen limpia conocida (golden AMI, IaC) es mucho más fiable que intentar limpiar a mano una instancia donde el atacante pudo dejar backdoors, tareas programadas o binarios modificados difíciles de detectar todos. La propia guía de GuardDuty recomienda terminar y reemplazar cuando no puedes garantizar la erradicación. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/compromised-ec2.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Restaurar desde backup",
    q: "Durante la fase de recuperación tras un incidente de ransomware que cifró datos en producción, ¿qué verificación es CRÍTICA hacer antes de restaurar desde un backup?",
    options: [
      "Ninguna: restaurar siempre el backup más reciente minimiza la pérdida de datos y acorta el RTO del servicio",
      "Comprobar que el tamaño del backup coincide con el del volumen original antes de restaurarlo",
      "Confirmar que el backup es anterior al compromiso, apoyándose en bóvedas inmutables como fuente fiable",
      "Restaurar sobre los mismos volúmenes y en la misma cuenta para acelerar la vuelta al servicio",
    ],
    correct: 2,
    explain: "Restaurar un backup posterior al compromiso puede reintroducir la misma vulnerabilidad, o incluso datos ya cifrados y backdoors persistidas. Por eso los backups inmutables (AWS Backup Vault Lock, S3 Object Lock) son tan valorados: garantizan que existe al menos una versión anterior al ataque que no pudo ser alterada ni siquiera por un atacante con credenciales de administrador. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Correlación de logs multi-servicio",
    q: "Investigas un posible movimiento lateral de un atacante que comprometió credenciales IAM. ¿Qué combinación de fuentes te da la imagen más completa del alcance (skill 2.2.2)?",
    options: [
      "Revisar la factura de AWS del mes y Cost Explorer para localizar el gasto anómalo del atacante",
      "Consultar el inventario de Systems Manager para ver qué software se instaló en las instancias",
      "Mirar las alarmas de CloudWatch de CPU y de red de las instancias durante la ventana del incidente detectado",
      "Cruzar CloudTrail, VPC Flow Logs y los findings de GuardDuty/Detective en la misma ventana temporal",
    ],
    correct: 3,
    explain: "El movimiento lateral deja rastro en varias capas: CloudTrail muestra QUÉ hizo el atacante vía API, VPC Flow Logs muestra A QUÉ se conectó a nivel de red, y GuardDuty/Detective ya correlacionan patrones anómalos automáticamente. Cruzar las tres fuentes en la misma ventana temporal es lo que permite reconstruir el alcance real, en vez de mirar cada una de forma aislada. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Application Recovery Controller",
    q: "¿Para qué sirve Amazon Application Recovery Controller (ARC) en un escenario de incidente que afecta a una región completa?",
    options: [
      "Para orquestar el failover multi-región con readiness checks y routing controls, evitando errores manuales",
      "Para escanear las aplicaciones en busca de vulnerabilidades antes de promocionarlas a producción",
      "Para emitir y renovar los certificados TLS de los endpoints de la aplicación en ambas regiones",
      "Para replicar de forma continua las bases de datos hacia la región secundaria como servicio de backup gestionado",
    ],
    correct: 0,
    explain: "ARC verifica continuamente que la infraestructura de la región de respaldo está realmente lista para recibir tráfico (readiness checks) y ofrece 'routing controls' seguros —interruptores on/off con protección frente a activaciones accidentales— para ejecutar el failover: pensado exactamente para el momento de máxima presión de un incidente de disponibilidad regional. <a href=\"https://docs.aws.amazon.com/r53recovery/latest/dg/what-is-route53-recovery.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cadena de custodia",
    q: "¿Por qué es importante etiquetar y documentar (timestamp, quién, qué acción) cada artefacto forense capturado durante un incidente (snapshots, memory dumps, logs exportados)?",
    options: [
      "Facilita el reparto de costes por proyecto, ya que las etiquetas se propagan a la factura detallada",
      "Para sostener la cadena de custodia: sin registro de captura y manejo la evidencia pierde validez",
      "Porque AWS aplica una tarifa reducida a los snapshots etiquetados como evidencia de un incidente",
      "Porque sin etiquetas Systems Manager no puede ejecutar runbooks de Automation sobre esos recursos",
    ],
    correct: 1,
    explain: "La cadena de custodia (chain of custody) es un requisito frecuente en investigaciones que pueden derivar en acciones legales o reportes regulatorios: sin un registro claro de captura, acceso y manejo de cada artefacto forense, la evidencia puede perder validez. Soluciones como Automated Forensics Orchestrator automatizan este etiquetado y su registro desde el primer paso. <a href=\"https://docs.aws.amazon.com/solutions/latest/automated-forensics-orchestrator-for-amazon-ec2/forensic-investigation-and-reporting-service.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IR plan testing",
    q: "¿Cuál es la diferencia entre 'probar' un plan de respuesta a incidentes con un tabletop exercise y con AWS Fault Injection Service?",
    options: [
      "Son equivalentes: ambos inyectan fallos técnicos reales y se diferencian solo en la herramienta usada",
      "FIS solo puede ejecutarse una vez al año por cuota del servicio; el tabletop no tiene ese límite",
      "El tabletop valida el proceso y la comunicación del equipo; FIS valida técnicamente alarmas y runbooks",
      "El tabletop exige interrumpir producción, mientras que FIS trabaja siempre sobre entornos aislados",
    ],
    correct: 2,
    explain: "Ambos son formas válidas de 'test and validate' (skill 2.1.3) mencionadas en el exam guide, mutuamente complementarias: el tabletop valida que el EQUIPO sabe qué hacer y se comunica bien; FIS valida que la TECNOLOGÍA (alarmas, automatizaciones, runbooks ejecutables) responde de verdad como se diseñó, con guardrails para no provocar un incidente real por accidente. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/aws-security-incident-response-guide/develop-and-test-incident-response-plan.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Security Incident Response",
    q: "Tu organización quiere reducir el tiempo entre la detección de un finding crítico de GuardDuty y el inicio de una investigación por parte de expertos, incluyendo acceso a un equipo de AWS con experiencia real en respuesta a incidentes, disponible 24/7. ¿Qué servicio de AWS, con disponibilidad general desde diciembre de 2024, está diseñado específicamente para esto?",
    options: [
      "AWS Trusted Advisor, que revisa la cuenta y recomienda buenas prácticas de seguridad y de coste",
      "Amazon Detective, que ayuda a investigar los findings pero no suma un equipo humano de AWS al caso",
      "AWS Systems Manager Incident Manager, que gestiona el proceso operativo y el escalado de guardias",
      "AWS Security Incident Response, con triage automático y acceso 24/7 al equipo de IR de AWS",
    ],
    correct: 3,
    explain: "Security IR (GA en diciembre de 2024) combina monitorización y triage automatizado de findings de GuardDuty y Security Hub, herramientas de investigación asistidas por IA, y acceso directo al CIRT de AWS 24/7. Detective ayuda a investigar pero no da acceso a un equipo humano de AWS; Incident Manager gestiona el proceso operativo pero ya no admite altas de clientes nuevos; Trusted Advisor solo da recomendaciones de buenas prácticas. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security IR: casos proactivos vs. reactivos",
    q: "Tras habilitar AWS Security Incident Response en tu organización, ¿en qué se diferencia un caso 'reactivo' de un caso proactivo (con el prefijo '[Proactive case]')?",
    options: [
      "El reactivo lo abre el propio cliente cuando sospecha un compromiso y pide ayuda al equipo de AWS",
      "No hay diferencia real: la consola usa ambos términos como sinónimos del mismo tipo de caso",
      "Los proactivos solo se generan para instancias EC2 con Windows y para cargas de trabajo en EKS",
      "Los reactivos no tienen coste, mientras que los proactivos se facturan por cada finding correlacionado",
    ],
    correct: 0,
    explain: "Security IR analiza el histórico de comportamiento de la cuenta, el tipo de finding y patrones de correlación entre cuentas para filtrar automáticamente el ruido; cuando concluye que hay una amenaza genuina abre un caso proactivo (prefijo '[Proactive case]') sin que el cliente tenga que detectarlo primero. Los casos reactivos son los que el propio cliente crea al sospechar un incidente. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/responding-to-an-aws-generated-case.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Retirada de Incident Manager: migrar a OpsCenter",
    q: "Estás diseñando el plan de respuesta a incidentes de una cuenta de AWS nueva en 2026 y valoras usar AWS Systems Manager Incident Manager para gestionar el ciclo de vida de los incidentes y el escalado del equipo. ¿Qué deberías tener en cuenta?",
    options: [
      "Es la opción que AWS recomienda hoy para cualquier cuenta nueva que arranque su plan de respuesta",
      "Desde noviembre de 2025 no admite clientes nuevos ni nuevas funcionalidades: AWS apunta a OpsCenter",
      "Ha sido renombrado como Amazon Detective, que absorbe la gestión del ciclo de vida del incidente",
      "Solo está disponible en us-east-1, así que obliga a centralizar allí toda la respuesta a incidentes",
    ],
    correct: 1,
    explain: "AWS anunció que, desde el 7 de noviembre de 2025, Incident Manager no admite nuevos clientes ni recibirá nuevas funcionalidades (los clientes existentes pueden seguir usándolo). Para una cuenta nueva, la guía oficial apunta a OpsCenter para centralizar OpsItems y a soluciones de partners de AWS para las capacidades de escalado y paging que antes cubría Incident Manager. <a href=\"https://docs.aws.amazon.com/incident-manager/latest/userguide/incident-manager-availability-change.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Detective: resúmenes de finding groups con IA generativa",
    q: "Un analista junior de SOC recibe un finding group complejo en Amazon Detective con docenas de findings y recursos relacionados, y le cuesta priorizar por dónde empezar. ¿Qué funcionalidad de Detective le da rápidamente, en lenguaje natural, un resumen de qué está pasando y su posible impacto?",
    options: [
      "Un chequeo de AWS Trusted Advisor sobre los recursos implicados en ese grupo de hallazgos",
      "Amazon Q Business, indexando los findings del grupo para poder preguntarle en lenguaje natural",
      "Finding group summary, que resume el grupo en lenguaje natural con IA generativa sobre Bedrock",
      "GuardDuty Malware Protection, que escanea los recursos citados y resume lo que ha encontrado",
    ],
    correct: 2,
    explain: "Finding group summary usa modelos de IA generativa alojados en Amazon Bedrock para analizar automáticamente las relaciones entre los findings y los recursos afectados de un finding group, y generar un resumen en lenguaje natural (qué inició la actividad, su posible impacto) que acelera drásticamente el triage inicial — disponible sin coste extra para cuentas con Detective habilitado. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/finding-group-summary.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Detective Investigations para IAM",
    q: "Quieres saber si un rol IAM concreto ha mostrado comportamiento anómalo (ej. 'impossible travel', uso desde IPs marcadas como maliciosas, tácticas de ataque conocidas) recientemente, y obtener un informe con los indicadores de compromiso (IoCs) y tácticas/técnicas (TTPs) detectados. ¿Qué funcionalidad de Amazon Detective usarías?",
    options: [
      "Cost Explorer, filtrando por el rol para ver si el gasto asociado se dispara de forma anómala",
      "AWS Config Rules aplicadas al rol, que evalúan si su política se desvía del estándar aprobado",
      "IAM Access Analyzer, que revisa qué principals externos podrían acceder al rol desde otra cuenta",
      "Detective investigations, que analiza el ARN con ML y threat intel y devuelve sus IoCs y TTPs",
    ],
    correct: 3,
    explain: "Detective investigations aplica machine learning y threat intelligence para analizar recursos IAM por su ARN y generar un informe con los indicadores de compromiso y las TTPs asociadas a comportamientos anómalos como el 'impossible travel' o el uso desde IPs marcadas — disponible desde la consola de Detective o su API, y complementa (no sustituye) a Access Analyzer, que se enfoca en accesos no deseados por diseño de políticas, no en comportamiento anómalo en el tiempo. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/detective-investigations.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Backup: bóveda lógicamente air-gapped",
    q: "Tu equipo de seguridad quiere una copia de backup que ni siquiera un atacante con credenciales de administrador root comprometidas dentro de la cuenta de la carga de trabajo pueda borrar o modificar. ¿Qué solución de AWS Backup cumple este requisito con mayor garantía?",
    options: [
      "Una logically air-gapped vault, cuyas copias viven fuera de la cuenta de la carga y son inmutables",
      "Snapshots de EBS programados con Data Lifecycle Manager y copiados a otra región de la misma cuenta",
      "Un bucket de S3 con versionado activado y una bucket policy que deniegue DeleteObject a los demás",
      "AWS Backup Vault Lock en modo governance, que impide borrar los recovery points de la bóveda",
    ],
    correct: 0,
    explain: "La logically air-gapped vault (GA en agosto de 2024) almacena las copias en una cuenta gestionada por AWS, fuera del alcance de la cuenta de carga de trabajo, bloqueadas e inmutables por defecto: ni siquiera el root puede borrarlas dentro del periodo de retención. El modo governance de Vault Lock (opción D) sí puede ser retirado por usuarios con permisos IAM suficientes, así que ofrece menos garantía frente a un atacante con privilegios de administrador. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/logicallyairgappedvault.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Backup: multi-party approval",
    q: "Un ataque de ransomware deja la cuenta de AWS de la carga de trabajo completamente inaccesible (las credenciales root fueron comprometidas y rotadas por el atacante). ¿Qué funcionalidad reciente de AWS Backup permite recuperar los backups almacenados en una logically air-gapped vault en este escenario extremo?",
    options: [
      "Restaurar con las credenciales root de la cuenta comprometida, ya rotadas, desde otra región",
      "Multi-party approval, que deja a cuentas aprobadas de la organización autorizar el acceso de restauración",
      "Abrir un caso de soporte en el plan Basic para que AWS devuelva el control de la cuenta afectada al cliente",
      "No hay recuperación posible: la bóveda queda inaccesible si su cuenta propietaria se compromete",
    ],
    correct: 1,
    explain: "Multi-party approval resuelve exactamente el escenario en el que la cuenta propietaria de los backups queda inaccesible: la petición de crear un <code>restore access backup vault</code> en una cuenta de recuperación pasa por una sesión de aprobación, y cuando el número exigido de miembros del equipo aprueba, se crea el punto de acceso para restaurar desde la bóveda air-gapped sin depender de la cuenta comprometida. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/multipartyapproval.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection para AWS Backup",
    q: "Antes de restaurar un backup de un volumen EBS tras un incidente de ransomware, quieres verificar de forma automatizada que ese backup concreto no contiene malware, e idealmente identificar cuál es el último backup 'limpio' conocido para minimizar la pérdida de datos. ¿Qué funcionalidad usarías?",
    options: [
      "Amazon Inspector, que escanea el contenido del recovery point en busca de firmas de malware conocidas",
      "AWS Config con un conformance pack que marque como no conforme cualquier backup infectado",
      "GuardDuty Malware Protection for AWS Backup, que escanea los backups e identifica el último limpio",
      "Amazon Macie, que inspecciona los metadatos del recovery point buscando indicios de cifrado",
    ],
    correct: 2,
    explain: "GuardDuty Malware Protection for AWS Backup extiende la detección de malware a los backups (snapshots de EBS, AMIs de EC2 y recovery points de S3): escanea automáticamente los backups nuevos sobre una copia de solo lectura, permite escaneos bajo demanda sobre backups existentes, y ayuda a verificar que un backup está limpio antes de restaurarlo. Funciona incluso si las fuentes de datos fundamentales de GuardDuty no están habilitadas. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection-backup.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Elastic Disaster Recovery: recovery points ante ransomware",
    q: "Usas AWS Elastic Disaster Recovery (DRS) para replicar continuamente tus servidores hacia AWS con un RPO de segundos. Durante la investigación descubres que el ransomware llevaba activo varias horas antes de cifrar los datos. ¿Cómo deberías recuperar el servicio con DRS?",
    options: [
      "Lanzar siempre la instancia de recuperación desde el punto de recuperación más reciente disponible",
      "Detener la replicación de DRS y esperar a que la actividad del ransomware cese por sí sola",
      "DRS solo conserva el último estado replicado, así que hay que recurrir en exclusiva a AWS Backup",
      "Lanzarla desde un punto de recuperación anterior al inicio de la actividad maliciosa detectada",
    ],
    correct: 3,
    explain: "AWS DRS mantiene múltiples point-in-time snapshots en el tiempo según su política PIT, no solo el más reciente, y permite lanzar la instancia de recuperación desde cualquiera de ellos. Ante un ransomware que llevaba tiempo activo antes de cifrar, usar el punto más reciente reintroduciría el compromiso: hay que elegir un punto anterior al inicio de la actividad maliciosa identificada durante la investigación. <a href=\"https://docs.aws.amazon.com/drs/latest/userguide/point-in-time.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudTrail Lake para investigación forense",
    q: "Necesitas investigar la actividad de una credencial comprometida a lo largo de varias cuentas de tu organización durante los últimos años, ejecutando consultas SQL complejas sobre eventos de API sin exportar y procesar manualmente archivos de log almacenados en S3. ¿Qué capacidad de CloudTrail usarías?",
    options: [
      "CloudTrail Lake, un almacén inmutable de eventos consultable con SQL y hasta 7 años de retención",
      "CloudTrail Insights, que detecta desviaciones en el volumen de llamadas pero no admite consultas SQL",
      "VPC Flow Logs enviados a un bucket de S3 y consultados con Athena particionando por cuenta y día",
      "AWS Config Aggregator, que reúne el histórico de configuración de los recursos de la organización",
    ],
    correct: 0,
    explain: "CloudTrail Lake almacena los eventos de forma inmutable con acceso de solo lectura, soporta consultas SQL (motor Trino) directamente desde la consola sobre event data stores, y admite retenciones configurables de hasta 7 años — ideal para investigaciones forenses que requieren correlacionar actividad histórica entre múltiples cuentas sin gestionar manualmente archivos de log en S3. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-lake.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "VPC Traffic Mirroring para forense de red",
    q: "Durante la investigación de una instancia EC2 comprometida, quieres capturar el CONTENIDO real de los paquetes de red (payloads), no solo metadatos de quién se conectó con quién, para analizarlo con una herramienta de inspección profunda de paquetes (DPI) fuera de banda. ¿Qué funcionalidad te permite esto?",
    options: [
      "VPC Flow Logs, cuyos registros incluyen el payload completo de cada paquete además de la cabecera",
      "VPC Traffic Mirroring, que copia el tráfico de la ENI, payload incluido, a un destino fuera de banda",
      "CloudTrail con eventos de datos activados, que registra el contenido de los paquetes TCP/IP salientes",
      "AWS Config con la grabación de tráfico de red activada sobre las interfaces de red de la instancia",
    ],
    correct: 1,
    explain: "VPC Flow Logs solo capturan metadatos (IPs origen y destino, puertos, bytes, acción) — NUNCA el contenido del paquete. VPC Traffic Mirroring actúa como un 'tap' de red virtual: copia el tráfico completo (payload incluido) desde la ENI de la instancia hacia appliances de seguridad fuera de banda, sin instalar agentes ni tocar la instancia origen — la herramienta correcta cuando el análisis exige ver el contenido real de la comunicación. <a href=\"https://docs.aws.amazon.com/vpc/latest/mirroring/what-is-traffic-mirroring.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cuenta forense dedicada",
    q: "Como parte de la preparación (2.1.2), tu organización crea una cuenta de AWS dedicada exclusivamente al análisis forense, separada de las cuentas de carga de trabajo. ¿Cuál es el flujo correcto para analizar en esa cuenta forense un volumen EBS de una instancia comprometida?",
    options: [
      "Entregar a la cuenta forense unas credenciales de administrador de la cuenta comprometida",
      "Mover la cuenta comprometida a la OU forense de la organización para analizarla desde dentro",
      "Compartir el snapshot y su KMS key, copiarlo re-cifrado en la forense y montarlo en solo lectura",
      "Montar el volumen original en otra instancia de la cuenta comprometida y analizarlo en caliente",
    ],
    correct: 2,
    explain: "El patrón estándar de forense multi-cuenta es: snapshot en la cuenta comprometida → compartir el snapshot y el acceso a la KMS key de origen (obligatorio: un snapshot cifrado con la clave gestionada por AWS no se puede compartir) → copiar y re-cifrar el snapshot con una key propia de la cuenta forense → crear un volumen y montarlo en modo solo lectura para preservar la integridad del artefacto durante el análisis. <a href=\"https://docs.aws.amazon.com/ebs/latest/userguide/ebs-modifying-snapshot-permissions.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Automated Forensics Orchestrator: soporte para EKS",
    q: "Tu organización ejecuta cargas de trabajo tanto en instancias EC2 como en clústeres de Amazon EKS sobre EC2. ¿La solución 'Automated Forensics Orchestrator' de AWS cubre ambos casos?",
    options: [
      "No: para EKS existe una solución distinta y sin relación con el orquestador forense de EC2",
      "Solo si todo se despliega en una única cuenta y región, porque no soporta entornos distribuidos",
      "Solo cubre instancias EC2 con Windows Server; para Linux y EKS hacen falta herramientas propias",
      "Sí: se llama 'for Amazon EC2 and EKS' y cubre ambos, en entornos multi-cuenta y multi-región",
    ],
    correct: 3,
    explain: "La guidance de AWS 'Automated Forensics Orchestrator for Amazon EC2 and EKS' (construida sobre Step Functions, Lambda y documentos de SSM) orquesta el mismo flujo forense —aislamiento del recurso, captura de memoria y disco, cadena de custodia— tanto para instancias EC2 como para clústeres EKS ejecutándose sobre EC2 y sus volúmenes asociados, con despliegues multi-cuenta y multi-región. <a href=\"https://docs.aws.amazon.com/solutions/latest/automated-forensics-orchestrator-for-amazon-ec2/architecture-overview.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Security Lake para investigación centralizada",
    q: "Quieres centralizar y normalizar en un único formato (para poder correlacionarlos fácilmente) los logs de CloudTrail, VPC Flow Logs, consultas DNS de Route 53 Resolver y los findings de Security Hub de docenas de cuentas, y luego analizarlos con Athena o herramientas de terceros durante una investigación. ¿Qué servicio de AWS está diseñado para esto?",
    options: [
      "Amazon Security Lake, que normaliza automáticamente esos orígenes al esquema abierto OCSF en Parquet",
      "AWS Config Aggregator, que centraliza el histórico de configuración pero no los logs de actividad de la API",
      "AWS Systems Manager Inventory, que recopila el software instalado en las instancias gestionadas",
      "Amazon Macie, que clasifica los datos sensibles de S3 y los agrega en un panel centralizado",
    ],
    correct: 0,
    explain: "Amazon Security Lake ingiere y normaliza automáticamente al esquema OCSF (formato Parquet) los logs de CloudTrail, VPC Flow Logs, las consultas de Route 53 Resolver y los findings de Security Hub, además de decenas de fuentes de partners, centralizándolos en un data lake consultable con Athena, QuickSight u otras herramientas — precisamente para simplificar la correlación entre fuentes heterogéneas durante una investigación. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/what-is-security-lake.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Backup Vault Lock: modo compliance",
    q: "Configuras un AWS Backup Vault Lock en modo COMPLIANCE con un periodo de gracia ('cooling-off') de 3 días. ¿Qué implica esto para la inmutabilidad de los backups en esa bóveda?",
    options: [
      "Es idéntico al modo governance: cualquier usuario con permisos IAM puede retirar el lock cuando quiera",
      "Durante ese periodo aún puedes retirar o modificar el lock; después ya nadie, ni AWS, puede alterarlo",
      "El modo compliance permite borrar recovery points sueltos aunque la bóveda siga estando bloqueada",
      "El periodo de gracia solo aplica a bóvedas cifradas con una clave KMS gestionada por el cliente",
    ],
    correct: 1,
    explain: "El modo compliance de Vault Lock incluye un periodo de gracia de al menos 72 horas durante el cual todavía se puede deshacer o modificar el lock; una vez expira, ni el usuario root de la cuenta ni AWS pueden eliminar o alterar la bóveda o su configuración hasta que finalice la retención de cada recovery point — a diferencia del modo governance, donde usuarios con permisos IAM suficientes pueden retirar el lock en cualquier momento. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/vault-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "EventBridge + Security IR: automatización de casos",
    q: "Quieres que, además del triage automático que hace AWS Security Incident Response sobre los findings de GuardDuty/Security Hub, tu propio pipeline de automatización (ej. una Step Functions state machine que notifica a tu SOC interno) se dispare en cuanto se abra o actualice un caso en Security IR. ¿Cómo lo consigues?",
    options: [
      "No es posible: Security IR es un servicio cerrado que solo se opera desde su propia consola",
      "Sondeando la consola de Security IR cada cinco minutos con un script propio que detecte los cambios",
      "Consumiendo en EventBridge los eventos de creación y actualización de casos que publica Security IR",
      "Únicamente a través de las llamadas telefónicas que el CIRT de AWS hace al contacto designado",
    ],
    correct: 2,
    explain: "Security IR publica en Amazon EventBridge todos los eventos del ciclo de vida de sus casos (creación, actualización), además de exponer consola y API — esto permite construir automatizaciones propias con Rules o Pipes (Step Functions que notifiquen al SOC interno, abrir un ticket en la herramienta ITSM de la empresa, etc.) que reaccionen en tiempo real, sin depender de sondeo manual. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/eventbridge.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Route 53 Resolver query logs en forense",
    q: "Durante una investigación forense sospechas que una instancia comprometida ha estado resolviendo periódicamente el dominio de un servidor de comando y control (C2). CloudTrail no registra este tipo de actividad porque no son llamadas a la API de AWS. ¿Qué fuente de datos deberías consultar (idealmente ya activada de antemano) para confirmar esta hipótesis?",
    options: [
      "AWS Config, que registra cada cambio de configuración de los recursos de red dentro de la VPC",
      "IAM Access Analyzer, que identifica los accesos externos concedidos por las políticas de la cuenta",
      "AWS Cost Explorer, filtrando por la instancia para detectar el tráfico saliente anómalo facturado",
      "Route 53 Resolver query logs, que registran las consultas DNS emitidas por los recursos de la VPC",
    ],
    correct: 3,
    explain: "Las resoluciones DNS no son llamadas a la API de AWS, así que CloudTrail no las registra. Los Route 53 Resolver query logs sí capturan las consultas DNS emitidas desde recursos de la VPC (dominio, tipo de registro, IP e instancia de origen, código de respuesta), siendo la fuente correcta para detectar comunicación periódica con dominios de C2 — por eso conviene tenerlos activados como parte de la preparación, igual que CloudTrail o VPC Flow Logs. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 Object Lock para evidencia exportada",
    q: "Tras exportar los memory dumps y snapshots analizados a un bucket de S3 como repositorio de evidencia a largo plazo (por un posible litigio), ¿qué combinación de características de S3 garantiza que esos objetos no puedan sobrescribirse ni eliminarse por NADIE, incluso si el periodo de retención configurado ya expiró pero el proceso judicial sigue abierto?",
    options: [
      "S3 Object Lock en modo compliance combinado con un Legal Hold, que no tiene fecha de caducidad",
      "El versionado de S3 por sí solo, que conserva cada versión anterior de los objetos sobrescritos",
      "El cifrado en servidor con SSE-KMS y una key policy que deniegue el borrado al resto de principals",
      "Una bucket policy que deniegue s3:DeleteObject a todos los principals salvo al rol de administrador",
    ],
    correct: 0,
    explain: "El modo compliance de S3 Object Lock impide que nadie (incluido el root) modifique o borre el objeto mientras dure el periodo de retención configurado. El Legal Hold es un mecanismo independiente y sin fecha de caducidad: sigue protegiendo el objeto aunque el periodo de retención ya haya expirado, hasta que alguien con permiso lo retire explícitamente — justo lo que se necesita cuando un litigio se alarga más de lo previsto. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Contención de una EC2 comprometida",
    q: "GuardDuty reporta que una instancia EC2 de producción está comunicándose con una IP de command-and-control. Debes contenerla preservando la evidencia para el análisis forense posterior. ¿Qué DOS acciones son las adecuadas?",
    options: [
      "Sustituir su security group por uno sin reglas de salida, aislándola sin apagarla",
      "Terminar la instancia de inmediato para cortar la comunicación con el servidor de mando y control",
      "Tomar snapshots de los volúmenes EBS y capturar la memoria antes de cualquier otra acción",
      "Reiniciar la instancia para limpiar de la memoria los procesos maliciosos en ejecución",
    ],
    correct: [0, 2],
    explain: "Aislar por red corta el canal sin destruir estado, y el <strong>snapshot de EBS más la captura de memoria</strong> preservan la evidencia. Terminar la instancia destruye a la vez el disco efímero y la memoria: se pierde el caso. Reiniciar es igual de dañino, porque la memoria es justo donde vive el malware sin fichero en disco. Regla del examen: contener no es destruir. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/compromised-ec2.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Credenciales de IAM expuestas",
    q: "Se descubre que una access key de un usuario IAM lleva días publicada en un repositorio público. ¿Qué DOS acciones deben tomarse primero?",
    options: [
      "Cambiar la contraseña de consola del usuario y dar el incidente por cerrado",
      "Desactivar o eliminar de inmediato la access key publicada en el repositorio",
      "Esperar a que la clave caduque sola, ya que las access keys de IAM rotan solas",
      "Revisar CloudTrail para saber qué se hizo con la clave y desde qué IPs",
    ],
    correct: [1, 3],
    explain: "Primero se corta el acceso (<strong>desactivar la clave</strong>) y después se determina el alcance (<strong>CloudTrail</strong>): sin saber qué hizo el atacante no se puede saber si dejó puertas traseras, como roles o usuarios nuevos. Cambiar la contraseña de consola no afecta a una access key, que es un credencial distinto. Y las access keys de IAM <strong>no caducan solas</strong>: viven hasta que alguien las desactiva. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Preparación del plan de respuesta",
    q: "El equipo de seguridad quiere poder responder a incidentes sin depender de que un administrador esté disponible para conceder permisos en mitad de la crisis. ¿Qué DOS medidas preparan ese escenario?",
    options: [
      "Crear de antemano un rol de respuesta a incidentes con un trust policy acotado",
      "Repartir las credenciales root de las cuentas entre los miembros del equipo de guardia",
      "Conceder AdministratorAccess permanente a todo el equipo de seguridad",
      "Documentar y automatizar los procedimientos como runbooks de Systems Manager",
    ],
    correct: [0, 3],
    explain: "Un <strong>rol preaprovisionado</strong> y unos <strong>runbooks automatizados</strong> permiten actuar rápido sin improvisar permisos ni pasos. Repartir credenciales root destruye la trazabilidad y es lo contrario de lo que recomienda AWS: el root se protege con MFA y se usa solo para tareas que lo exigen. Y AdministratorAccess permanente convierte al equipo de respuesta en el mayor riesgo de la cuenta. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cadena de custodia",
    q: "La evidencia recogida de un incidente podría acabar en un procedimiento legal. ¿Qué DOS prácticas protegen su validez?",
    options: [
      "Analizar directamente los volúmenes originales de la instancia afectada",
      "Guardar la evidencia en una cuenta forense con acceso restringido y registrado",
      "Calcular y conservar hashes de integridad de cada artefacto recogido",
      "Comprimir la evidencia y enviarla por correo al equipo legal externo de la empresa",
    ],
    correct: [1, 2],
    explain: "El <strong>aislamiento en una cuenta forense</strong> con acceso auditado y los <strong>hashes de integridad</strong> son lo que permite demostrar que la evidencia no se alteró. Trabajar sobre los volúmenes originales los modifica y arruina la cadena de custodia: se analiza siempre sobre copias. Y el correo no ofrece ni control de acceso ni prueba de integridad. <a href=\"https://docs.aws.amazon.com/solutions/latest/automated-forensics-orchestrator-for-amazon-ec2/forensic-investigation-and-reporting-service.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["incident-response"] = QUIZ_DATA;
