var QUIZ_DATA = [
  {
    tag: "Runbooks & OpsCenter",
    q: "¿Qué papel juega AWS Systems Manager OpsCenter en un plan de respuesta a incidentes?",
    options: [
      "Centraliza 'OpsItems' (incidentes/problemas operativos) con contexto relacionado (recursos afectados, alarmas de CloudWatch, runbooks de Automation asociados), permitiendo investigar y ejecutar remediaciones desde un único lugar",
      "Es un servicio de backup",
      "Sustituye a CloudTrail para auditoría",
      "Solo funciona con instancias EC2 Windows",
    ],
    correct: 0,
    explain: "OpsCenter agrega 'OpsItems' que representan incidentes u problemas operativos, enlazando automáticamente el contexto relevante (recursos, alarmas, runbooks de Systems Manager Automation ejecutables) — es la pieza de Systems Manager pensada para centralizar la investigación y ejecución de la respuesta, no solo el registro pasivo del incidente.",
  },
  {
    tag: "Preparación: minimizar blast radius",
    q: "Como parte de PREPARAR una cuenta para incidentes (antes de que ocurran), ¿qué práctica reduce el 'blast radius' si una carga de trabajo se ve comprometida?",
    options: [
      "Usar una única cuenta de AWS para todo, simplificando la gestión",
      "Segmentar cargas de trabajo en cuentas separadas (multi-account strategy), con permisos IAM de mínimo privilegio y sin credenciales de larga duración compartidas entre entornos",
      "Dar AdministratorAccess a todos los roles para agilizar la respuesta cuando ocurra un incidente",
      "Desactivar CloudTrail para reducir ruido",
    ],
    correct: 1,
    explain: "Minimizar el blast radius es una actividad de PREPARACIÓN (skill 2.1.2): separar cargas de trabajo en cuentas distintas, aplicar mínimo privilegio y evitar credenciales compartidas limita cuánto puede alcanzar un atacante si compromete un solo componente — mucho más barato hacerlo antes del incidente que durante.",
  },
  {
    tag: "Provisionar acceso de emergencia",
    q: "¿Por qué es importante tener PRE-PROVISIONADO (antes del incidente) el acceso que el equipo de respuesta necesitará durante una investigación?",
    options: [
      "No es importante, se puede crear el acceso necesario en el momento del incidente sin impacto",
      "Porque IAM no permite crear roles nuevos si GuardDuty está activo",
      "Porque durante un incidente activo no quieres depender de flujos de aprobación IAM lentos ni de crear roles nuevos con prisa (riesgo de sobre-otorgar permisos); un rol de IR con permisos ya auditados y probados reduce tiempo de respuesta y errores",
      "Solo aplica si usas IAM Identity Center",
    ],
    correct: 2,
    explain: "Skill 2.1.2 explícitamente menciona 'provisioning access' como parte de la preparación: un rol de IR con permisos de solo lectura amplios + acciones de contención específicas (aislar SG, crear snapshot), ya probado y auditado de antemano, evita improvisar permisos bajo presión durante el incidente — que es exactamente cuando más fácil es cometer un error de sobre-privilegio.",
  },
  {
    tag: "AWS Fault Injection Service",
    q: "¿Para qué se usa AWS Fault Injection Service (FIS) en el contexto de validar un plan de respuesta a incidentes?",
    options: [
      "Para desplegar parches de seguridad automáticamente",
      "Es un servicio exclusivo de forense de malware",
      "Para generar tráfico de ataque real contra producción sin control",
      "Para ejecutar experimentos de chaos engineering CONTROLADOS (ej. simular la caída de una AZ, latencia de red, terminar instancias) y así probar si tus alarmas, runbooks y plan de respuesta realmente funcionan como se espera",
    ],
    correct: 3,
    explain: "FIS permite diseñar y ejecutar experimentos de fallo controlados y con guardrails (stop conditions automáticas si algo se sale de lo esperado) para validar que la detección, alertado y los runbooks de respuesta funcionan de verdad — sin esperar a un incidente real para descubrir que la alarma nunca se disparó.",
  },
  {
    tag: "AWS Resilience Hub",
    q: "¿Qué evalúa AWS Resilience Hub?",
    options: [
      "La resiliencia de una aplicación frente a objetivos de recuperación definidos (RTO/RPO), identificando brechas en la arquitectura y recomendando mejoras, y puede orquestar experimentos de FIS para validarlo",
      "El coste de una arquitectura",
      "Solo el cumplimiento de PCI-DSS",
      "La latencia de red entre regiones",
    ],
    correct: 0,
    explain: "Resilience Hub evalúa una aplicación definida contra objetivos de RTO (tiempo de recuperación) y RPO (punto de recuperación/pérdida de datos aceptable), señala dónde la arquitectura actual no los cumpliría, y puede generar/ejecutar experimentos de FIS para validar la resiliencia real — complementario a FIS (FIS ejecuta el experimento, Resilience Hub define contra qué objetivo se mide).",
  },
  {
    tag: "Remediación automática",
    q: "Quieres que, en cuanto GuardDuty genere un finding de severidad alta sobre una instancia EC2 (ej. comunicación con un IP de minería de criptomonedas), se aísle automáticamente esa instancia sin esperar a que un humano actúe. ¿Qué arquitectura implementas?",
    options: [
      "Revisar los findings manualmente cada mañana",
      "Una regla de EventBridge que capture el finding de GuardDuty y dispare una función Lambda o un Step Functions state machine que cambie el Security Group de la instancia a uno de cuarentena (sin tráfico permitido salvo hacia la subnet forense)",
      "Desactivar la instancia manualmente vía consola cuando alguien lo note",
      "Configurar una SCP que bloquee GuardDuty",
    ],
    correct: 1,
    explain: "El patrón estándar de remediación automática (skill 2.1.4) es: finding de GuardDuty → EventBridge rule (filtra por severidad/tipo) → Lambda/Step Functions ejecuta la acción de contención (ej. modificar el Security Group a uno de cuarentena) — todo en segundos, sin esperar intervención humana para la contención inicial.",
  },
  {
    tag: "Automated Forensics Orchestrator",
    q: "¿Qué automatiza la solución de AWS 'Automated Forensics Orchestrator for Amazon EC2'?",
    options: [
      "El escaneo de vulnerabilidades continuo con Inspector",
      "La rotación de credenciales de IAM",
      "Todo el flujo forense ante una instancia EC2 comprometida: aislamiento de red (SG de cuarentena), captura de snapshot EBS y memoria, etiquetado para cadena de custodia, y notificación al equipo de IR — sin intervención manual en cada paso",
      "El despliegue de parches en toda la flota",
    ],
    correct: 2,
    explain: "Es una solución de AWS (basada en Step Functions + Lambda) que orquesta automáticamente el proceso forense completo ante una instancia comprometida: aislar la red, capturar evidencia (snapshots de disco y memoria), preservar la cadena de custodia con etiquetado/logging, y notificar — reduciendo el tiempo de contención de horas a minutos.",
  },
  {
    tag: "Contención de red",
    q: "¿Cuál es la forma más rápida y segura de aislar de la red una instancia EC2 comprometida SIN apagarla (preservando el estado de memoria para análisis forense)?",
    options: [
      "Terminar la instancia inmediatamente",
      "Cambiar la contraseña del sistema operativo",
      "Desconectar el cable de red físicamente",
      "Cambiar su Security Group a uno de 'cuarentena' sin reglas de entrada/salida (o solo con salida hacia la subnet/herramientas forenses), manteniendo la instancia encendida para poder capturar memoria antes de cualquier otra acción",
    ],
    correct: 3,
    explain: "Apagar o terminar la instancia destruye la memoria RAM (evidencia volátil valiosa). La práctica correcta es aislar a nivel de red (Security Group de cuarentena) manteniendo la instancia ENCENDIDA, para poder capturar un memory dump antes de proceder con el análisis y la eventual sustitución de la instancia.",
  },
  {
    tag: "Captura de evidencia forense",
    q: "Al capturar evidencia forense de una instancia EC2 comprometida para su posterior análisis, ¿qué DOS artefactos son más valiosos capturar antes de cualquier otra acción?",
    options: [
      "Un snapshot del volumen EBS (estado del disco) y una captura de memoria (RAM) de la instancia — la memoria contiene evidencia volátil (procesos en ejecución, conexiones activas, claves en memoria) que se pierde al apagar la instancia",
      "Solo los logs de CloudTrail de la cuenta",
      "Solo las métricas de CloudWatch de CPU",
      "El historial de facturación de la cuenta",
    ],
    correct: 0,
    explain: "El snapshot EBS preserva el estado del disco para análisis posterior sin alterar la instancia original. La captura de memoria (usando herramientas como el AVML de AWS o similares, vía Systems Manager) preserva evidencia volátil que desaparece en cuanto la instancia se apaga o reinicia — ambos artefactos son prioritarios en la fase de contención/captura.",
  },
  {
    tag: "SageMaker AI para forense",
    q: "El exam guide de SCS-C03 menciona explícitamente 'Amazon SageMaker AI notebooks' como ejemplo del skill 2.1.1 (runbooks de respuesta a incidentes). ¿Para qué se usarían en este contexto?",
    options: [
      "Para entrenar modelos de machine learning de producción",
      "Como entorno de análisis AISLADO y programático (notebooks Jupyter) para examinar artefactos forenses capturados (memory dumps, logs, snapshots montados), ejecutando scripts de análisis de forma repetible y documentada",
      "SageMaker no tiene ninguna relación con incident response, es un error del examen",
      "Para desplegar el sitio web de la empresa durante el incidente",
    ],
    correct: 1,
    explain: "Aunque SageMaker es conocido por ML, sus notebooks (entornos Jupyter gestionados y aislados) son útiles como banco de trabajo forense: analizar artefactos capturados con scripts en Python de forma reproducible, documentada, y en un entorno separado de la infraestructura de producción — un uso no obvio que el examen prueba precisamente porque sorprende.",
  },
  {
    tag: "Validar findings antes de actuar",
    q: "Recibes un finding de GuardDuty de severidad media sobre una instancia. Antes de ejecutar acciones de contención de gran impacto (ej. terminar la instancia), ¿qué deberías hacer primero según el skill 2.2.3?",
    options: [
      "Actuar inmediatamente sin verificar nada, la velocidad es lo único que importa",
      "Ignorar los findings de severidad media siempre",
      "Validar el finding: confirmar el alcance real y el impacto (¿qué recursos están realmente afectados?, ¿es un falso positivo conocido?, ¿hay corroboración en otras fuentes como VPC Flow Logs o CloudTrail?) antes de escalar a una respuesta de alto impacto",
      "Esperar 48 horas antes de revisar cualquier finding",
    ],
    correct: 2,
    explain: "El skill 2.2.3 (nuevo en SCS-C03) pide explícitamente validar findings para determinar el alcance e impacto reales antes de actuar — evita tanto la parálisis por sobre-análisis como la respuesta desproporcionada a un falso positivo, correlacionando el finding con otras fuentes (Flow Logs, CloudTrail, Detective) antes de una acción de alto impacto como terminar un recurso de producción.",
  },
  {
    tag: "Amazon Detective",
    q: "¿Qué resuelve Amazon Detective que GuardDuty y Security Hub por sí solos no resuelven bien?",
    options: [
      "Detective sustituye la necesidad de tener GuardDuty activado",
      "Detective solo analiza logs de RDS",
      "Detective es simplemente un dashboard de costes",
      "Detective construye automáticamente un GRAFO de comportamiento e interacciones entre recursos (IAM roles, instancias, IPs) a lo largo del tiempo, facilitando el análisis de causa raíz — responder '¿cómo llegó el atacante hasta aquí y qué más tocó?' en vez de solo '¿qué pasó en este evento puntual?'",
    ],
    correct: 3,
    explain: "GuardDuty y Security Hub te dicen QUÉ pasó (findings puntuales). Detective agrega automáticamente datos de CloudTrail, VPC Flow Logs y GuardDuty en un grafo navegable de relaciones entre entidades a lo largo del tiempo, permitiendo trazar la CADENA de eventos (root cause analysis) — 'este rol IAM comprometido a las 3:15 accedió después a estos 4 recursos y desde esta IP nueva'.",
  },
  {
    tag: "Amazon Detective",
    q: "¿Detective REEMPLAZA la necesidad de tener CloudTrail y VPC Flow Logs activados?",
    options: [
      "No: Detective CONSUME esos logs (CloudTrail, VPC Flow Logs, GuardDuty findings, y opcionalmente logs de EKS) para construir su grafo de comportamiento — si esas fuentes no están activas o Detective no está habilitado con suficiente antelación, el histórico disponible para investigar será limitado",
      "Sí, Detective genera sus propios logs independientes",
      "Detective solo funciona sin CloudTrail activado",
      "Detective sustituye completamente a Security Hub",
    ],
    correct: 0,
    explain: "Detective depende de que esas fuentes de log ya existan — no las sustituye, las CORRELACIONA. Además, Detective mantiene hasta 1 año de datos históricos para análisis retrospectivo, pero solo desde el momento en que se habilitó: es buena práctica activarlo de forma preventiva (parte de la preparación), no esperar al incidente para activarlo.",
  },
  {
    tag: "Recuperación",
    q: "Tras contener y erradicar un compromiso en una instancia EC2, ¿cuál es la práctica MÁS segura para recuperar el servicio?",
    options: [
      "Reiniciar la misma instancia comprometida y seguir usándola",
      "Sustituir la instancia por una nueva desplegada desde una AMI hardened conocida-buena (golden image), en vez de intentar 'limpiar' la instancia comprometida in-place — es prácticamente imposible garantizar que no queda ningún rastro de persistencia del atacante",
      "Restaurar únicamente las contraseñas de los usuarios locales",
      "Aplicar solo los parches pendientes sobre la instancia comprometida",
    ],
    correct: 1,
    explain: "El principio de recuperación tras un compromiso es 'no confíes en lo que pudo haber sido alterado': reconstruir desde una imagen limpia conocida (golden AMI, IaC) es mucho más fiable que intentar limpiar manualmente una instancia donde el atacante pudo haber dejado backdoors, tareas programadas o binarios modificados difíciles de detectar todos.",
  },
  {
    tag: "Restaurar desde backup",
    q: "Durante la fase de recuperación tras un incidente de ransomware que cifró datos en producción, ¿qué verificación es CRÍTICA hacer antes de restaurar desde un backup?",
    options: [
      "Ninguna, restaurar el backup más reciente disponible siempre es correcto",
      "Solo verificar el tamaño del backup",
      "Confirmar que el backup elegido es de ANTES de que ocurriera el compromiso (no un backup que ya contenga los datos cifrados o una puerta trasera persistida), usando backups inmutables (Vault Lock) como fuente de confianza",
      "Preguntar al atacante qué backup es seguro",
    ],
    correct: 2,
    explain: "Restaurar un backup posterior al compromiso puede reintroducir la misma vulnerabilidad o incluso datos ya cifrados/backdoors. Por eso los backups inmutables (AWS Backup Vault Lock, S3 Object Lock) son tan valorados: garantizan que existe al menos una versión anterior al ataque que no pudo ser alterada ni siquiera por el atacante con credenciales de administrador.",
  },
  {
    tag: "Correlación de logs multi-servicio",
    q: "Investigas un posible movimiento lateral de un atacante que comprometió credenciales IAM. ¿Qué combinación de fuentes te da la imagen más completa del alcance (skill 2.2.2)?",
    options: [
      "Solo revisar la factura de AWS del mes",
      "Solo el Cost Explorer",
      "Solo mirar las alarmas de CloudWatch de CPU",
      "Correlacionar CloudTrail (qué acciones de API se hicieron con esas credenciales), VPC Flow Logs (a qué recursos de red se conectó), y los findings de GuardDuty/Detective (patrones ya marcados como anómalos) en la misma ventana de tiempo",
    ],
    correct: 3,
    explain: "El movimiento lateral deja rastro en múltiples capas: CloudTrail muestra QUÉ hizo el atacante vía API, VPC Flow Logs muestra A QUÉ se conectó a nivel de red, y GuardDuty/Detective ya correlacionan patrones anómalos automáticamente. Cruzar las tres fuentes en la misma ventana temporal es lo que permite reconstruir el alcance real, en vez de mirar cada una de forma aislada.",
  },
  {
    tag: "Application Recovery Controller",
    q: "¿Para qué sirve Amazon Application Recovery Controller (ARC) en un escenario de incidente que afecta a una región completa?",
    options: [
      "Para orquestar y monitorizar el failover de una aplicación multi-región de forma segura y controlada (readiness checks + routing controls), evitando failovers manuales propensos a error durante una crisis",
      "Para escanear vulnerabilidades de aplicaciones",
      "Para gestionar certificados TLS",
      "Es un servicio de backup de bases de datos",
    ],
    correct: 0,
    explain: "ARC verifica continuamente que la infraestructura de la región de respaldo está realmente lista para recibir tráfico (readiness checks) y proporciona 'routing controls' seguros (con protección contra activaciones accidentales) para ejecutar el failover — pensado exactamente para el momento de máxima presión de un incidente de disponibilidad regional.",
  },
  {
    tag: "Cadena de custodia",
    q: "¿Por qué es importante etiquetar y documentar (timestamp, quién, qué acción) cada artefacto forense capturado durante un incidente (snapshots, memory dumps, logs exportados)?",
    options: [
      "Solo por organización visual, no tiene impacto real",
      "Para mantener la cadena de custodia: si el incidente termina en una acción legal/regulatoria, poder demostrar que la evidencia no fue alterada y quién tuvo acceso a ella en cada momento",
      "Porque AWS lo factura de forma distinta si está etiquetado",
      "No es relevante para el examen",
    ],
    correct: 1,
    explain: "La cadena de custodia (chain of custody) es un requisito frecuente en investigaciones que pueden derivar en acciones legales o reportes regulatorios: sin un registro claro de captura, acceso y manejo de cada artefacto forense, la evidencia puede perder validez. Soluciones como Automated Forensics Orchestrator automatizan este etiquetado desde el primer paso.",
  },
  {
    tag: "IR plan testing",
    q: "¿Cuál es la diferencia entre 'probar' un plan de respuesta a incidentes con un tabletop exercise y con AWS Fault Injection Service?",
    options: [
      "Son exactamente lo mismo",
      "FIS solo puede usarse una vez al año por límites de AWS",
      "Un tabletop exercise es una simulación DISCUTIDA verbalmente por el equipo (sin tocar sistemas reales) para validar el PROCESO y la comunicación; FIS ejecuta fallos TÉCNICOS reales y controlados contra la infraestructura para validar que las alarmas/runbooks automatizados realmente se disparan y funcionan",
      "Los tabletop exercises requieren interrumpir producción, FIS no",
    ],
    correct: 2,
    explain: "Ambos son formas válidas de 'test and validate' (skill 2.1.3) mencionadas en el exam guide, mutuamente complementarias: el tabletop valida que el EQUIPO sabe qué hacer y se comunica bien; FIS valida que la TECNOLOGÍA (alarmas, automatizaciones, runbooks ejecutables) responde de verdad como se diseñó, con guardrails para no causar un incidente real por accidente.",
  },
  {
    tag: "AWS Security Incident Response",
    q: "Tu organización quiere reducir el tiempo entre la detección de un finding crítico de GuardDuty y el inicio de una investigación por parte de expertos, incluyendo acceso a un equipo de AWS con experiencia real en respuesta a incidentes, disponible 24/7. ¿Qué servicio de AWS, con disponibilidad general desde diciembre de 2024, está diseñado específicamente para esto?",
    options: [
      "AWS Trusted Advisor",
      "Amazon Detective",
      "AWS Systems Manager Incident Manager",
      "AWS Security Incident Response (Security IR): monitoriza y triagea automáticamente los findings de GuardDuty (vía Security Hub), abre casos proactivos cuando confirma una amenaza real, y da acceso directo al AWS Customer Incident Response Team (CIRT) 24/7",
    ],
    correct: 3,
    explain: "Security IR (GA diciembre 2024) combina monitorización y triage automatizado de findings de GuardDuty/Security Hub, herramientas de investigación asistidas por IA, y acceso directo al CIRT de AWS 24/7. Detective ayuda a investigar pero no da acceso a un equipo humano de AWS; Incident Manager gestiona el proceso operativo pero ya no admite altas de clientes nuevos (retirado desde nov. 2025); Trusted Advisor solo da recomendaciones de buenas prácticas.",
  },
  {
    tag: "Security IR: casos proactivos vs. reactivos",
    q: "Tras habilitar AWS Security Incident Response en tu organización, ¿en qué se diferencia un caso 'reactivo' de un caso proactivo (con el prefijo '[Proactive case]')?",
    options: [
      "Un caso reactivo lo abre el propio cliente cuando necesita ayuda (ej. sospecha un compromiso); un caso proactivo lo abre AUTOMÁTICAMENTE el servicio cuando su proceso de triage —que filtra automáticamente más del 99% de los findings entrantes— determina que un finding de GuardDuty/Security Hub es un verdadero positivo que requiere atención",
      "No hay diferencia real, ambos términos son sinónimos en la consola",
      "Los casos proactivos solo se generan para instancias EC2 con Windows",
      "Los casos reactivos son gratuitos y los proactivos tienen coste adicional por finding",
    ],
    correct: 0,
    explain: "Security IR analiza el histórico de comportamiento de la cuenta, el tipo de finding y patrones de correlación entre cuentas para filtrar automáticamente el ruido; cuando concluye que hay una amenaza genuina abre un caso proactivo (prefijo '[Proactive case]') sin que el cliente tenga que detectarlo primero. Los casos reactivos son los que el propio cliente crea manualmente al sospechar un incidente.",
  },
  {
    tag: "Retirada de Incident Manager: migrar a OpsCenter",
    q: "Estás diseñando el plan de respuesta a incidentes de una cuenta de AWS nueva en 2026 y valoras usar AWS Systems Manager Incident Manager para gestionar el ciclo de vida de los incidentes y el escalado del equipo. ¿Qué deberías tener en cuenta?",
    options: [
      "Es la opción que AWS recomienda activamente para cualquier cuenta nueva",
      "Desde el 7 de noviembre de 2025, Incident Manager dejó de aceptar clientes nuevos y AWS no añadirá más funcionalidades al servicio; para cuentas nuevas, AWS recomienda usar Systems Manager OpsCenter para gestionar los problemas operativos, y soluciones de partners de AWS para el escalado y paging automatizado",
      "Incident Manager ha sido renombrado oficialmente a Amazon Detective",
      "Incident Manager solo está disponible en la región us-east-1",
    ],
    correct: 1,
    explain: "AWS anunció que, desde el 7 de noviembre de 2025, Incident Manager no admite nuevos clientes ni recibirá nuevas funcionalidades (los clientes existentes pueden seguir usándolo). Para una cuenta nueva en 2026, la guía oficial de AWS apunta a OpsCenter para centralizar OpsItems y a soluciones de partners para las capacidades de escalado/paging que antes cubría Incident Manager.",
  },
  {
    tag: "Detective: resúmenes de finding groups con IA generativa",
    q: "Un analista junior de SOC recibe un finding group complejo en Amazon Detective con docenas de findings y recursos relacionados, y le cuesta priorizar por dónde empezar. ¿Qué funcionalidad de Detective le da rápidamente, en lenguaje natural, un resumen de qué está pasando y su posible impacto?",
    options: [
      "Un chequeo de AWS Trusted Advisor",
      "Amazon Q Business, un producto sin relación con Detective",
      "Finding group summary: una capacidad de Detective basada en modelos de IA generativa alojados en Amazon Bedrock que analiza automáticamente el grupo de hallazgos y genera un título e insights en lenguaje natural, sin coste adicional si Detective ya está habilitado",
      "GuardDuty Malware Protection",
    ],
    correct: 2,
    explain: "Finding group summary usa modelos de IA generativa en Amazon Bedrock para analizar automáticamente las relaciones entre findings y recursos afectados de un finding group, y generar un resumen en lenguaje natural (qué inició la actividad, su posible impacto) que acelera drásticamente el triage inicial — disponible sin coste extra para cuentas con Detective habilitado.",
  },
  {
    tag: "Detective Investigations para IAM",
    q: "Quieres saber si un rol IAM concreto ha mostrado comportamiento anómalo (ej. 'impossible travel', uso desde IPs marcadas como maliciosas, tácticas de ataque conocidas) recientemente, y obtener un informe con los indicadores de compromiso (IoCs) y tácticas/técnicas (TTPs) detectados. ¿Qué funcionalidad de Amazon Detective usarías?",
    options: [
      "Cost Explorer, filtrando el gasto asociado al rol IAM",
      "AWS Config Rules aplicadas al rol IAM",
      "IAM Access Analyzer, usado de forma aislada",
      "Detective investigations: usa modelos de machine learning y threat intelligence para analizar un IAM user o role por su ARN y generar un informe de comportamiento anómalo (impossible travel, IPs marcadas, tácticas de ataque)",
    ],
    correct: 3,
    explain: "Detective investigations aplica machine learning y threat intelligence para analizar recursos IAM (por ARN) y generar un informe con los indicadores de compromiso y TTPs asociados a comportamientos anómalos como el 'impossible travel' o el uso desde IPs marcadas como maliciosas — disponible desde la consola de Detective o su API pública, y complementa (no sustituye) a Access Analyzer, que se enfoca en detectar accesos no deseados por diseño de políticas, no en comportamiento anómalo en tiempo.",
  },
  {
    tag: "AWS Backup: bóveda lógicamente air-gapped",
    q: "Tu equipo de seguridad quiere una copia de backup que ni siquiera un atacante con credenciales de administrador root comprometidas dentro de la cuenta de la carga de trabajo pueda borrar o modificar. ¿Qué solución de AWS Backup cumple este requisito con mayor garantía?",
    options: [
      "Una logically air-gapped vault de AWS Backup: almacena copias inmutables en una cuenta propiedad de AWS (fuera de tu cuenta de carga de trabajo), bloqueadas por defecto, con protección de borrado que ningún principal —ni siquiera el root de la cuenta propietaria— puede eludir dentro del periodo de retención",
      "Snapshots EBS estándar, sin ninguna configuración adicional",
      "Un bucket S3 estándar con versioning activado, sin Object Lock",
      "AWS Backup Vault Lock en modo governance",
    ],
    correct: 0,
    explain: "La logically air-gapped vault (GA agosto 2024) almacena las copias en una cuenta gestionada por AWS, fuera del alcance de la cuenta de carga de trabajo, bloqueadas e inmutables por defecto — ni siquiera el root puede borrarlas dentro del periodo de retención. El modo governance de Vault Lock (opción D) sí puede ser desbloqueado por usuarios con permisos IAM suficientes, por lo que ofrece menos garantía frente a un atacante con privilegios de administrador.",
  },
  {
    tag: "AWS Backup: multi-party approval",
    q: "Un ataque de ransomware deja la cuenta de AWS de la carga de trabajo completamente inaccesible (las credenciales root fueron comprometidas y rotadas por el atacante). ¿Qué funcionalidad reciente de AWS Backup permite recuperar los backups almacenados en una logically air-gapped vault en este escenario extremo?",
    options: [
      "Restaurar directamente usando las credenciales root comprometidas",
      "Multi-party approval para logically air-gapped vaults en AWS Organizations: permite autorizar el acceso y la restauración de backups a cuentas aprobadas incluso cuando la cuenta propietaria original quedó inaccesible por un evento accidental o malicioso, sin depender de esa cuenta",
      "Abrir un caso de soporte en el plan Basic de AWS Support",
      "No es posible recuperar los backups si la cuenta propietaria está comprometida",
    ],
    correct: 1,
    explain: "Multi-party approval (2025) resuelve exactamente el escenario en el que la cuenta propietaria original de los backups queda inaccesible: cuentas aprobadas previamente en la organización pueden autorizar y ejecutar la restauración desde la bóveda air-gapped sin depender de que la cuenta comprometida vuelva a estar operativa.",
  },
  {
    tag: "GuardDuty Malware Protection para AWS Backup",
    q: "Antes de restaurar un backup de un volumen EBS tras un incidente de ransomware, quieres verificar de forma automatizada que ese backup concreto no contiene malware, e idealmente identificar cuál es el último backup 'limpio' conocido para minimizar la pérdida de datos. ¿Qué funcionalidad usarías?",
    options: [
      "Amazon Inspector, escaneando el backup directamente",
      "AWS Config, con un conformance pack de malware",
      "Amazon GuardDuty Malware Protection for AWS Backup (GA noviembre 2025): escanea automáticamente los backups nuevos de EC2/EBS/S3, permite escaneos bajo demanda de backups existentes, verifica que un backup está limpio antes de restaurarlo, e identifica el último backup limpio conocido usando escaneo incremental sobre los datos que cambiaron",
      "Amazon Macie, escaneando los metadatos del backup",
    ],
    correct: 2,
    explain: "GuardDuty Malware Protection for AWS Backup extiende la detección de malware a los backups de EC2, EBS y S3: escanea automáticamente los backups nuevos, permite escaneos bajo demanda sobre backups existentes, verifica que estén limpios antes de una restauración, e identifica el último backup limpio conocido — usando escaneo incremental para no tener que re-escanear todo el histórico. Funciona incluso si las fuentes de datos fundamentales de GuardDuty no están habilitadas.",
  },
  {
    tag: "AWS Elastic Disaster Recovery: recovery points ante ransomware",
    q: "Usas AWS Elastic Disaster Recovery (DRS) para replicar continuamente tus servidores hacia AWS con un RPO de segundos. Durante la investigación descubres que el ransomware llevaba activo varias horas antes de cifrar los datos. ¿Cómo deberías recuperar el servicio con DRS?",
    options: [
      "Siempre lanzar la instancia de recuperación desde el punto de recuperación más reciente disponible",
      "Apagar DRS y esperar a que el ransomware se desactive por sí solo",
      "DRS solo permite recuperar el último estado replicado, así que hay que usar exclusivamente AWS Backup",
      "Lanzar la instancia de recuperación eligiendo un punto de recuperación (recovery point) ANTERIOR al inicio de la actividad maliciosa detectada, en vez del más reciente — DRS conserva múltiples puntos de recuperación en el tiempo (no solo el último) precisamente para permitir este tipo de recuperación selectiva",
    ],
    correct: 3,
    explain: "AWS DRS mantiene múltiples recovery points en el tiempo, no solo el más reciente, y permite lanzar la instancia de recuperación desde cualquiera de ellos. Ante un ransomware que ya llevaba tiempo activo antes de cifrar, usar el punto más reciente reintroduciría el compromiso; hay que elegir un punto anterior al inicio de la actividad maliciosa identificada durante la investigación.",
  },
  {
    tag: "CloudTrail Lake para investigación forense",
    q: "Necesitas investigar la actividad de una credencial comprometida a lo largo de varias cuentas de tu organización durante los últimos años, ejecutando consultas SQL complejas sobre eventos de API sin exportar y procesar manualmente archivos de log almacenados en S3. ¿Qué capacidad de CloudTrail usarías?",
    options: [
      "CloudTrail Lake: un almacén de eventos gestionado e inmutable (los eventos no pueden modificarse una vez capturados) que permite ejecutar consultas SQL directamente desde la consola (motor basado en Athena), con retención configurable de hasta 7 años",
      "CloudTrail Insights, exclusivamente",
      "VPC Flow Logs",
      "AWS Config Aggregator",
    ],
    correct: 0,
    explain: "CloudTrail Lake almacena los eventos de forma inmutable con acceso de solo lectura (no se pueden alterar), soporta consultas SQL directamente desde la consola con un motor basado en Amazon Athena, y admite retenciones configurables de hasta 7 años — ideal para investigaciones forenses que requieren correlacionar actividad histórica entre múltiples cuentas sin gestionar manualmente archivos de log.",
  },
  {
    tag: "VPC Traffic Mirroring para forense de red",
    q: "Durante la investigación de una instancia EC2 comprometida, quieres capturar el CONTENIDO real de los paquetes de red (payloads), no solo metadatos de quién se conectó con quién, para analizarlo con una herramienta de inspección profunda de paquetes (DPI) fuera de banda. ¿Qué funcionalidad te permite esto?",
    options: [
      "VPC Flow Logs, que ya incluyen el payload completo de cada paquete",
      "VPC Traffic Mirroring, que copia el tráfico de red (incluyendo payloads, no solo cabeceras) desde la interfaz de red (ENI) de la instancia hacia un destino de monitorización fuera de banda, sin necesidad de instalar ningún agente en la instancia",
      "AWS CloudTrail, que registra el contenido de los paquetes TCP/IP",
      "AWS Config, activando el grabado de tráfico de red",
    ],
    correct: 1,
    explain: "VPC Flow Logs solo capturan metadatos (IPs origen/destino, puertos, bytes, acción) — NUNCA el contenido del paquete. VPC Traffic Mirroring actúa como un 'tap' de red virtual: copia el tráfico completo (payload incluido) desde la ENI de la instancia hacia appliances de seguridad fuera de banda, sin tocar la instancia origen — la herramienta correcta cuando el análisis requiere ver el contenido real de la comunicación.",
  },
  {
    tag: "Cuenta forense dedicada",
    q: "Como parte de la preparación (2.1.2), tu organización crea una cuenta de AWS dedicada exclusivamente al análisis forense, separada de las cuentas de carga de trabajo. ¿Cuál es el flujo correcto para analizar en esa cuenta forense un volumen EBS de una instancia comprometida?",
    options: [
      "Dar a la cuenta forense credenciales de administrador de la cuenta comprometida",
      "Migrar la cuenta comprometida completa a la organización forense",
      "Crear un snapshot del volumen EBS en la cuenta comprometida, compartirlo con la cuenta forense (incluyendo permisos sobre la key de KMS si está cifrado), y en la cuenta forense copiar el snapshot re-cifrándolo con una key propia para crear un volumen que se monta en modo SOLO LECTURA para el análisis",
      "Analizar el volumen directamente sobre la instancia comprometida, sin copiarlo",
    ],
    correct: 2,
    explain: "El patrón estándar de forense multi-cuenta es: snapshot en la cuenta comprometida → compartir el snapshot (y el acceso a la KMS key origen) con la cuenta forense → copiar y re-cifrar el snapshot con una key propia de la cuenta forense → crear un volumen y montarlo en modo solo lectura para preservar la integridad del artefacto durante el análisis. Nunca se otorgan credenciales de administrador de la cuenta comprometida ni se analiza sobre la instancia original.",
  },
  {
    tag: "Automated Forensics Orchestrator: soporte para EKS",
    q: "Tu organización ejecuta cargas de trabajo tanto en instancias EC2 como en clústeres de Amazon EKS sobre EC2. ¿La solución 'Automated Forensics Orchestrator' de AWS cubre ambos casos?",
    options: [
      "No, existe una solución completamente distinta y no relacionada para EKS",
      "Solo puede desplegarse en una única cuenta y una única región",
      "Solo cubre instancias EC2 con Windows Server",
      "Sí: la solución se llama oficialmente 'Automated Forensics Orchestrator for Amazon EC2 and EKS', y extiende el mismo flujo (aislamiento, captura de memoria/disco, cadena de custodia) tanto a instancias EC2 como a clústeres EKS ejecutándose sobre EC2 y sus volúmenes asociados, en entornos multi-cuenta y multi-región",
    ],
    correct: 3,
    explain: "La guidance de AWS 'Automated Forensics Orchestrator for Amazon EC2 and EKS' (construida sobre Step Functions, Lambda y documentos de SSM) orquesta el mismo flujo forense —aislamiento del recurso, captura de memoria y disco, cadena de custodia— tanto para instancias EC2 como para clústeres EKS sobre EC2 y sus volúmenes asociados, soportando despliegues multi-cuenta y multi-región.",
  },
  {
    tag: "Amazon Security Lake para investigación centralizada",
    q: "Quieres centralizar y normalizar en un único formato (para poder correlacionarlos fácilmente) los logs de CloudTrail, VPC Flow Logs, consultas DNS de Route 53 Resolver y los findings de Security Hub de docenas de cuentas, y luego analizarlos con Athena o herramientas de terceros durante una investigación. ¿Qué servicio de AWS está diseñado para esto?",
    options: [
      "Amazon Security Lake, que centraliza y normaliza automáticamente estos datos al esquema abierto OCSF (Open Cybersecurity Schema Framework) en formato Parquet, facilitando la correlación y el threat hunting entre fuentes heterogéneas",
      "AWS Config Aggregator",
      "AWS Systems Manager Inventory",
      "Amazon Macie",
    ],
    correct: 0,
    explain: "Amazon Security Lake ingiere y normaliza automáticamente al esquema OCSF (formato Parquet) los logs de CloudTrail, VPC Flow Logs, consultas de Route 53 Resolver y los findings de Security Hub (además de más de 50 fuentes de partners), centralizándolos en un data lake que se puede consultar con Athena, QuickSight u otras herramientas — precisamente para simplificar la correlación entre fuentes heterogéneas durante una investigación.",
  },
  {
    tag: "AWS Backup Vault Lock: modo compliance",
    q: "Configuras un AWS Backup Vault Lock en modo COMPLIANCE con un periodo de gracia ('cooling-off') de 3 días. ¿Qué implica esto para la inmutabilidad de los backups en esa bóveda?",
    options: [
      "Es idéntico al modo governance: cualquier usuario con permisos IAM suficientes puede eliminar el lock en cualquier momento",
      "Durante el periodo de gracia todavía puedes eliminar o modificar la configuración del lock; una vez transcurrido ese periodo, la bóveda y su configuración se vuelven inmutables y NO pueden ser eliminadas ni alteradas por ningún usuario —ni siquiera el root ni el propio AWS— hasta que expire la retención de cada recovery point",
      "El modo compliance permite borrar recovery points individuales en cualquier momento, sin restricción",
      "El periodo de gracia solo aplica a bóvedas cifradas con una clave KMS gestionada por el cliente",
    ],
    correct: 1,
    explain: "El modo compliance de Vault Lock incluye un periodo de gracia durante el cual todavía se puede deshacer o modificar el lock; una vez expira ese periodo, ni siquiera el usuario root de la cuenta ni AWS pueden eliminar o alterar la bóveda o su configuración hasta que finalice la retención de cada recovery point — a diferencia del modo governance, donde usuarios con permisos IAM suficientes pueden retirar el lock en cualquier momento.",
  },
  {
    tag: "EventBridge + Security IR: automatización de casos",
    q: "Quieres que, además del triage automático que hace AWS Security Incident Response sobre los findings de GuardDuty/Security Hub, tu propio pipeline de automatización (ej. una Step Functions state machine que notifica a tu SOC interno) se dispare en cuanto se abra o actualice un caso en Security IR. ¿Cómo lo consigues?",
    options: [
      "No es posible integrar Security IR con flujos de automatización propios",
      "Sondeando (polling) la consola de Security IR cada 5 minutos con un script propio",
      "Consumiendo los eventos que AWS Security Incident Response publica en Amazon EventBridge (creación/actualización de casos) para construir flujos de automatización propios que se disparen sobre esos eventos, además de poder gestionar los casos vía consola o API",
      "Solo es posible mediante llamadas telefónicas directas del CIRT",
    ],
    correct: 2,
    explain: "Security IR publica eventos de sus casos (creación, actualización) en Amazon EventBridge, además de exponer consola y API — esto permite construir automatizaciones propias (ej. Step Functions que notifiquen al SOC interno, abran un ticket en la herramienta ITSM de la empresa, etc.) que reaccionen en tiempo real a la actividad del caso, sin depender de sondeo manual.",
  },
  {
    tag: "Route 53 Resolver query logs en forense",
    q: "Durante una investigación forense sospechas que una instancia comprometida ha estado resolviendo periódicamente el dominio de un servidor de comando y control (C2). CloudTrail no registra este tipo de actividad porque no son llamadas a la API de AWS. ¿Qué fuente de datos deberías consultar (idealmente ya activada de antemano) para confirmar esta hipótesis?",
    options: [
      "AWS Config",
      "IAM Access Analyzer",
      "AWS Cost Explorer",
      "Route 53 Resolver query logs, que registran las consultas DNS realizadas por los recursos dentro de tu VPC (dominio consultado, tipo de respuesta, IP de origen), permitiendo detectar patrones de resolución hacia dominios de C2 conocidos",
    ],
    correct: 3,
    explain: "Las resoluciones DNS no son llamadas a la API de AWS, así que CloudTrail no las registra. Route 53 Resolver query logs sí capturan cada consulta DNS emitida desde recursos de la VPC (dominio, tipo de registro, IP de origen, respuesta), siendo la fuente correcta para detectar comunicación periódica con dominios de C2 — por eso conviene tenerlos activados como parte de la preparación, igual que CloudTrail o VPC Flow Logs.",
  },
  {
    tag: "S3 Object Lock para evidencia exportada",
    q: "Tras exportar los memory dumps y snapshots analizados a un bucket de S3 como repositorio de evidencia a largo plazo (por un posible litigio), ¿qué combinación de características de S3 garantiza que esos objetos no puedan sobrescribirse ni eliminarse por NADIE, incluso si el periodo de retención configurado ya expiró pero el proceso judicial sigue abierto?",
    options: [
      "S3 Object Lock en modo COMPLIANCE combinado con un Legal Hold: el modo compliance impide que cualquier usuario (incluido el root) modifique o elimine el objeto durante el periodo de retención, y el Legal Hold añade una restricción independiente, sin fecha de expiración, hasta que se retire explícitamente",
      "Versioning de S3 por sí solo, sin ninguna otra configuración",
      "Server-Side Encryption con SSE-S3, sin ninguna otra configuración",
      "Una bucket policy que deniega DeleteObject a todos los principals excepto al administrador",
    ],
    correct: 0,
    explain: "El modo compliance de S3 Object Lock impide que cualquiera (incluido el root) modifique o borre el objeto mientras dure el periodo de retención configurado. El Legal Hold es un mecanismo independiente y sin fecha de caducidad: sigue protegiendo el objeto aunque el periodo de retención ya haya expirado, hasta que alguien con permiso lo retire explícitamente — justo lo que se necesita cuando un litigio se alarga más de lo previsto originalmente.",
  },
  {
    tag: "Contención de una EC2 comprometida",
    q: "GuardDuty reporta que una instancia EC2 de producción está comunicándose con una IP de command-and-control. Debes contenerla preservando la evidencia para el análisis forense posterior. ¿Qué DOS acciones son las adecuadas?",
    options: [
      "Sustituir su security group por uno sin reglas de salida, aislándola sin apagarla",
      "Tomar un snapshot de los volúmenes EBS y capturar la memoria antes de cualquier otra cosa",
      "Terminar la instancia de inmediato para cortar la comunicación",
      "Reiniciar la instancia para limpiar los procesos maliciosos en memoria",
    ],
    correct: [0, 1],
    explain: "Aislar por red corta el canal sin destruir estado, y el <b>snapshot de EBS más la captura de memoria</b> preservan la evidencia. Terminar la instancia destruye a la vez el disco efímero y la memoria: se pierde el caso. Reiniciar es igual de dañino, porque la memoria es justo donde vive el malware sin fichero en disco. Regla del examen: contener no es destruir.",
  },
  {
    tag: "Credenciales de IAM expuestas",
    q: "Se descubre que una access key de un usuario IAM lleva días publicada en un repositorio público. ¿Qué DOS acciones deben tomarse primero?",
    options: [
      "Desactivar o eliminar la access key comprometida inmediatamente",
      "Revisar CloudTrail para determinar qué se hizo con esa clave y desde dónde",
      "Cambiar la contraseña de consola del usuario y dar por cerrado el incidente",
      "Esperar a que la clave expire por sí sola, ya que las access keys caducan automáticamente",
    ],
    correct: [0, 1],
    explain: "Primero se corta el acceso (<b>desactivar la clave</b>) y después se determina el alcance (<b>CloudTrail</b>): sin saber qué hizo el atacante no se puede saber si dejó puertas traseras, como roles o usuarios nuevos. Cambiar la contraseña de consola no afecta a una access key, que es un credencial distinto. Y las access keys de IAM <b>no caducan solas</b>: viven hasta que alguien las desactiva.",
  },
  {
    tag: "Preparación del plan de respuesta",
    q: "El equipo de seguridad quiere poder responder a incidentes sin depender de que un administrador esté disponible para conceder permisos en mitad de la crisis. ¿Qué DOS medidas preparan ese escenario?",
    options: [
      "Crear de antemano un rol de respuesta a incidentes con los permisos necesarios y un trust policy acotado",
      "Documentar y automatizar los procedimientos como runbooks ejecutables en Systems Manager",
      "Repartir las credenciales root de las cuentas entre los miembros del equipo por si acaso",
      "Conceder AdministratorAccess permanente a todo el equipo de seguridad",
    ],
    correct: [0, 1],
    explain: "Un <b>rol preaprovisionado</b> y unos <b>runbooks automatizados</b> permiten actuar rápido sin improvisar permisos ni pasos. Repartir credenciales root destruye la trazabilidad y es lo contrario de lo que recomienda AWS: el root se protege con MFA y se usa solo para tareas que lo exigen. Y AdministratorAccess permanente convierte el equipo de respuesta en el mayor riesgo de la cuenta.",
  },
  {
    tag: "Cadena de custodia",
    q: "La evidencia recogida de un incidente podría acabar en un procedimiento legal. ¿Qué DOS prácticas protegen su validez?",
    options: [
      "Guardar la evidencia en una cuenta forense separada, con acceso restringido y registrado",
      "Calcular y conservar hashes de integridad de los artefactos recogidos",
      "Analizar directamente los volúmenes originales de la instancia afectada",
      "Comprimir la evidencia y enviarla por correo al equipo legal",
    ],
    correct: [0, 1],
    explain: "El <b>aislamiento en una cuenta forense</b> con acceso auditado y los <b>hashes de integridad</b> son lo que permite demostrar que la evidencia no se alteró. Trabajar sobre los volúmenes originales los modifica y arruina la cadena de custodia: se analiza siempre sobre copias. Y el correo no ofrece ni control de acceso ni prueba de integridad.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["incident-response"] = QUIZ_DATA;
