var QUIZ_DATA = [
  {
    tag: "GuardDuty",
    q: "¿Sobre qué fuentes de datos analiza Amazon GuardDuty el comportamiento para detectar amenazas, sin que tengas que activar logging manualmente en cada cuenta?",
    options: [
      "CloudTrail (gestión y datos), VPC Flow Logs y DNS logs, más EKS audit logs opcionales",
      "Únicamente los eventos de gestión de CloudTrail, ya que el resto de fuentes hay que habilitarlas aparte",
      "Las métricas de CloudWatch de cada recurso, que GuardDuty consulta mediante un rol de solo lectura",
      "Los logs de aplicación que tú publiques en un log group de CloudWatch designado para GuardDuty",
    ],
    correct: 0,
    explain: "GuardDuty es 'serverless' en el sentido de que consume internamente CloudTrail, VPC Flow Logs y DNS query logs (y opcionalmente EKS audit logs, runtime monitoring de EC2/ECS/EKS, RDS login activity, S3 data events) SIN que tú tengas que activarlos ni gestionarlos por separado — se activa el servicio y ya está analizando. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty vs Macie vs Config",
    q: "Necesitas descubrir automáticamente qué buckets S3 de tu cuenta contienen números de tarjetas de crédito o información personal identificable (PII), sin escribir tú las reglas de detección. ¿Qué servicio usas?",
    options: [
      "Amazon GuardDuty, que perfila el comportamiento de acceso a S3 y marca los buckets con datos sensibles",
      "Amazon Macie, que aplica identificadores de datos gestionados y ML para clasificar el contenido de S3",
      "AWS Config, cuyas reglas gestionadas inspeccionan el contenido de los objetos de cada bucket",
      "Amazon Inspector, que analiza los objetos de S3 igual que analiza las imágenes de contenedor",
    ],
    correct: 1,
    explain: "Macie está especializado en DESCUBRIMIENTO Y CLASIFICACIÓN de datos sensibles en S3 (PII, credenciales, financieros...) usando machine learning y patrones predefinidos (o personalizados). GuardDuty detecta comportamiento anómalo/amenazas, no clasifica contenido de datos. <a href=\"https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Security Hub",
    q: "¿Cuál es el rol principal de AWS Security Hub frente a GuardDuty, Macie e Inspector?",
    options: [
      "Sustituye a los tres: al activarlo puedes desactivar GuardDuty, Macie e Inspector sin perder cobertura",
      "Solo evalúa recursos EC2, por lo que los findings de S3 o IAM se consultan en cada servicio origen",
      "Agrega y normaliza findings de servicios AWS y de terceros, y ejecuta checks de compliance",
      "Reparte y factura el coste de los servicios de seguridad entre las cuentas de la organización",
    ],
    correct: 2,
    explain: "Security Hub es el AGREGADOR: centraliza findings de múltiples servicios de detección de AWS y de terceros en un solo lugar, y adicionalmente ejecuta sus propios controles de compliance frente a estándares de seguridad reconocidos (CIS AWS Foundations, PCI-DSS, AWS Foundational Security Best Practices). <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Automatización de evaluaciones",
    q: "Quieres que un conjunto de reglas de AWS Config (ej. 'todo bucket S3 debe tener cifrado activado') se aplique automáticamente a TODAS las cuentas de una OU en tu organización, de forma centralizada. ¿Qué usas?",
    options: [
      "Crear la misma Config Rule cuenta por cuenta y mantener las copias sincronizadas a mano",
      "Una SCP que deniegue s3:PutObject cuando el bucket no tenga cifrado activado",
      "Amazon Inspector, que evalúa la configuración de cifrado de cada bucket de la OU",
      "AWS Config Conformance Packs desplegados a nivel de organización sobre la OU",
    ],
    correct: 3,
    explain: "Los Conformance Packs empaquetan un conjunto de Config Rules (y acciones de remediación opcionales) como una única plantilla desplegable de forma centralizada a nivel de organización, evitando configurar regla por regla en cada cuenta — parte del skill 1.1.5 sobre automatizar evaluaciones regulares. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudTrail organizacional",
    q: "¿Qué ventaja tiene configurar un CloudTrail 'organization trail' desde la cuenta de gestión, frente a crear un trail independiente en cada cuenta miembro?",
    options: [
      "Se aplica a todas las cuentas, presentes y futuras, y no pueden desactivarlo",
      "Ninguna funcional: cambia el punto de creación, pero cobertura y coste son idénticos",
      "Registra solo eventos de datos; los de gestión siguen requiriendo un trail por cuenta",
      "Cubre solo la cuenta de gestión, y cada cuenta miembro necesita su propio trail",
    ],
    correct: 0,
    explain: "Un organization trail creado desde la cuenta de gestión (o un delegated administrator) se replica automáticamente a todas las cuentas miembro presentes Y futuras, sin que estas puedan desactivarlo, garantizando cobertura completa e inmutable — clave para el skill 1.2.2. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/creating-an-organizational-trail-in-the-console.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cuenta de logging dedicada",
    q: "¿Por qué la mejor práctica es enviar los logs de seguridad (CloudTrail, VPC Flow Logs...) a una CUENTA dedicada de logging, separada de las cuentas de carga de trabajo?",
    options: [
      "CloudTrail exige técnicamente una cuenta distinta para poder entregar a un bucket S3",
      "Aísla la evidencia del radio de acción de quien comprometa la carga de trabajo",
      "El almacenamiento en S3 se factura a mitad de precio cuando cruza el límite de cuenta",
      "Permite entregar los logs sin cifrar y evitar así el coste de las claves de KMS",
    ],
    correct: 1,
    explain: "Separar los logs en una cuenta dedicada (con acceso muy restringido, a menudo el 'Log Archive account' de Control Tower) es una defensa contra el escenario donde un atacante que compromete la cuenta de carga de trabajo intenta borrar o alterar la evidencia de sus acciones — los logs ya no están ahí para que los toque. <a href=\"https://docs.aws.amazon.com/prescriptive-guidance/latest/security-reference-architecture/log-archive.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Security Lake",
    q: "¿Qué problema resuelve específicamente Amazon Security Lake frente a simplemente centralizar logs en un bucket S3?",
    options: [
      "Ninguno relevante: es un bucket S3 gestionado con un nombre comercial distinto",
      "Reemplaza a CloudTrail como origen de los eventos de API de la organización",
      "Normaliza los logs al esquema abierto OCSF y los particiona sin ETL propio",
      "Solo ingiere findings de GuardDuty, por lo que el resto sigue yendo a un bucket propio",
    ],
    correct: 2,
    explain: "Security Lake automatiza la ingesta, normalización a OCSF, particionado (por fuente/región/fecha) y gestión del ciclo de vida de logs de seguridad de múltiples cuentas y fuentes (AWS y terceros integrados), eliminando el trabajo manual de ETL que necesitarías si solo centralizaras en un bucket S3 crudo. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/what-is-security-lake.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Athena vs CloudWatch Logs Insights",
    q: "¿Cuándo es más apropiado usar Amazon Athena en vez de CloudWatch Logs Insights para analizar logs de seguridad?",
    options: [
      "Nunca: ambos consultan los mismos datos y solo cambia la sintaxis de la consulta",
      "Athena solo puede consultar VPC Flow Logs; el resto de formatos requiere OpenSearch",
      "CloudWatch Logs Insights no permite filtrar, solo descargar el log group completo",
      "Athena para SQL ad-hoc sobre históricos en S3; Logs Insights para logs recientes",
    ],
    correct: 3,
    explain: "Athena consulta datos en S3 con SQL estándar (ideal para grandes volúmenes históricos, como los datos normalizados de Security Lake). CloudWatch Logs Insights usa su propio lenguaje de consulta optimizado para logs recientes ya ingeridos en CloudWatch Logs — más rápido para investigaciones inmediatas, menos apropiado para análisis histórico masivo. <a href=\"https://docs.aws.amazon.com/athena/latest/ug/when-should-i-use-ate.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Normalización y correlación",
    q: "¿Qué servicio de AWS se usa típicamente para construir dashboards de visualización y correlación de eventos de seguridad a partir de múltiples fuentes (Security Lake, OpenSearch, CloudWatch)?",
    options: [
      "Amazon Managed Grafana, con paneles sobre CloudWatch, OpenSearch y Athena",
      "AWS Config, cuyo panel de conformidad admite fuentes de datos externas como OpenSearch",
      "AWS Trusted Advisor, que construye paneles a partir de los checks de sus categorías",
      "Amazon Inspector, que expone sus hallazgos como paneles de correlación multi-fuente",
    ],
    correct: 0,
    explain: "Amazon Managed Grafana ofrece un servicio gestionado de Grafana para construir dashboards que correlacionen métricas y logs de múltiples fuentes de datos (CloudWatch, OpenSearch, Athena/Security Lake, Prometheus...) sin gestionar la infraestructura de Grafana tú mismo — skill 1.2.5. <a href=\"https://docs.aws.amazon.com/grafana/latest/userguide/what-is-Amazon-Managed-Service-Grafana.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "VPC Flow Logs",
    q: "¿Qué información capturan los VPC Flow Logs?",
    options: [
      "El contenido completo de cada paquete, incluida la carga útil de la conexión",
      "Metadatos de la conexión IP (5-tupla, bytes, ACCEPT/REJECT) por ENI o VPC",
      "Solo el tráfico HTTP y HTTPS, incluyendo la URL solicitada en cada petición",
      "Solo los intentos rechazados por security groups y network ACLs de la subred",
    ],
    correct: 1,
    explain: "VPC Flow Logs capturan METADATOS de las conexiones (5-tupla + bytes + acción), similar a un registro de llamadas telefónicas: quién llamó a quién, cuánto duró, pero NO el contenido de la conversación. Son la fuente principal para detectar escaneos de puertos, exfiltración de datos por volumen anómalo, o comunicación con IPs maliciosas. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Route 53 Resolver logs",
    q: "¿Qué visibilidad aportan específicamente los Route 53 Resolver query logs que los VPC Flow Logs no dan?",
    options: [
      "Ninguna: los VPC Flow Logs ya incluyen el nombre de dominio de cada conexión",
      "Solo registran los fallos de resolución (NXDOMAIN) que devuelve el resolver",
      "Registran la consulta DNS previa: qué dominio se pidió y quién preguntó",
      "Solo funcionan si el dominio consultado está registrado y alojado en Route 53",
    ],
    correct: 2,
    explain: "Mientras VPC Flow Logs ven la conexión IP resultante, los Resolver query logs ven la CONSULTA DNS previa — esencial para detectar malware que resuelve dominios de C2 conocidos, o exfiltración de datos codificados en subconsultas DNS (DNS tunneling), incluso antes de que se establezca la conexión IP. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Troubleshooting de logging",
    q: "Notas que CloudWatch Logs no está recibiendo logs de una instancia EC2 donde el agente CloudWatch (CloudWatch Agent) está instalado y corriendo. ¿Cuáles son las dos causas más probables a revisar primero?",
    options: [
      "El tipo de instancia EC2 y la versión del sistema operativo instalada",
      "El tamaño del volumen EBS raíz y el espacio libre disponible en disco",
      "La zona horaria del servidor y el desfase del reloj frente al NTP configurado",
      "El fichero de configuración del agente y los permisos del instance profile",
    ],
    correct: 3,
    explain: "Los dos culpables más comunes al depurar 'el agente corre pero no llegan logs' son: (1) un archivo de configuración del agente mal apuntado (rutas de log incorrectas, log group mal referenciado) y (2) permisos IAM insuficientes en el Instance Profile/execution role para escribir en CloudWatch Logs — exactamente el skill 1.3.2 de remediar 'CloudWatch Agent configuration' y 'missing logs'. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/troubleshooting-CloudWatch-Agent.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Troubleshooting de logging",
    q: "Un desarrollador reporta que las invocaciones de su función Lambda no generan logs en CloudWatch, aunque la función se ejecuta correctamente. ¿Cuál es la causa más probable a revisar primero?",
    options: [
      "Al execution role le faltan los permisos logs:CreateLogStream y PutLogEvents",
      "La función supera el límite de memoria y el runtime descarta el búfer de logs",
      "La función se despliega en una región donde CloudWatch Logs no está disponible",
      "El runtime elegido no emite a stdout y por eso Lambda no recoge su salida",
    ],
    correct: 0,
    explain: "Lambda necesita que su execution role tenga permisos explícitos para escribir en CloudWatch Logs (normalmente vía la managed policy AWSLambdaBasicExecutionRole). Si faltan, la función se ejecuta con normalidad (el fallo de logging no bloquea la ejecución) pero simplemente no aparece nada en CloudWatch — un caso clásico de troubleshooting del skill 1.3.1. <a href=\"https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon API Gateway logging",
    q: "¿Qué tipo de logging hay que activar explícitamente en Amazon API Gateway para capturar el cuerpo (body) de las peticiones y respuestas, útil para depurar problemas de autorización?",
    options: [
      "El execution logging por defecto ya incluye el body de petición y respuesta",
      "Data trace logging en el stage, que añade el detalle de request/response",
      "AWS X-Ray, que registra el body de cada traza sin configuración adicional",
      "El access logging del stage, cuyo formato incluye siempre el cuerpo completo",
    ],
    correct: 1,
    explain: "API Gateway distingue entre 'execution logging' (metadatos de la ejecución: errores, latencia) y 'data trace logging' (detalle completo de request/response, incluyendo headers y body). El data trace se activa aparte porque expone información potencialmente sensible en los logs — relevante para el skill 1.3.1 sobre analizar la configuración de logging de recursos. <a href=\"https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudFront logging",
    q: "¿Qué dos modalidades de logging ofrece Amazon CloudFront para analizar las peticiones que llegan a una distribución?",
    options: [
      "Un único tipo de log de acceso, entregado siempre a un bucket de S3 propio",
      "Solo logs en tiempo real hacia Kinesis, sin opción de entrega diferida",
      "Standard logs entregados a S3 con retraso y real-time logs a Kinesis",
      "Ninguno nativo: el registro de peticiones se obtiene únicamente desde AWS WAF",
    ],
    correct: 2,
    explain: "Standard logs (access logs) se entregan a un bucket S3 con cierto retraso y son gratuitos, ideales para análisis histórico/forense. Real-time logs se envían a Kinesis Data Streams en segundos, permitiendo alertar o reaccionar casi inmediatamente a patrones de tráfico — la elección depende de si necesitas velocidad (real-time) o análisis diferido barato (standard). <a href=\"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/logging.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Aggregar findings multi-cuenta",
    q: "Para tener una vista consolidada de los findings de GuardDuty y Security Hub de TODAS las cuentas de tu organización sin iniciar sesión en cada una, ¿qué patrón se usa?",
    options: [
      "Exportar los findings a CSV desde cada cuenta y consolidarlos en una hoja de cálculo",
      "Una SCP que obligue a cada cuenta miembro a replicar sus findings a la cuenta central",
      "No es posible: los findings solo se consultan desde la cuenta que los genera",
      "Designar una cuenta como delegated administrator de GuardDuty y de Security Hub",
    ],
    correct: 3,
    explain: "Tanto GuardDuty como Security Hub soportan el modelo de 'delegated administrator': una cuenta designada (normalmente la de seguridad/logging) ve y gestiona automáticamente los findings de todas las cuentas miembro de la Organization, sin necesidad de iniciar sesión en cada una individualmente. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_organizations.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Análisis de workloads",
    q: "Antes de diseñar una estrategia de monitorización para una nueva carga de trabajo, ¿qué debes analizar primero según el skill 1.1.1?",
    options: [
      "Los requisitos de monitorización: qué activos hay y qué eventos importan",
      "El coste mensual estimado, que determina por sí solo el nivel de detección aplicable",
      "El nombre y las etiquetas de la carga de trabajo, para agrupar después las alarmas",
      "El proveedor de CI/CD, que decide qué servicios de detección pueden habilitarse",
    ],
    correct: 0,
    explain: "El skill 1.1.1 (analizar workloads para determinar requisitos de monitorización) es la base antes de elegir herramientas: sin entender qué activos hay, qué eventos importan y qué SLA de detección se necesita, cualquier configuración de GuardDuty/Security Hub/alarmas será genérica en vez de ajustada al riesgo real de esa carga de trabajo. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_detect_investigate_events_app_service_logging.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Health checks",
    q: "En el contexto del skill 1.1.2 (diseñar estrategias de monitorización de workloads configurando health checks), ¿qué diferencia a un health check de Route 53 de una alarma de CloudWatch básica?",
    options: [
      "Son equivalentes: un health check es una alarma de CloudWatch con otro nombre",
      "El health check sondea activamente el endpoint desde varias ubicaciones globales",
      "Los health checks de Route 53 solo aceptan instancias EC2 como destino del sondeo",
      "CloudWatch no puede alarmar sobre la salud de un endpoint bajo ninguna métrica",
    ],
    correct: 1,
    explain: "Route 53 health checks hacen sondeos ACTIVOS periódicos a un endpoint desde ubicaciones distribuidas globalmente, útiles para decidir failover de DNS. Las alarmas de CloudWatch son PASIVAS: consumen métricas ya publicadas (por el recurso o por ti) y disparan una acción cuando cruzan un umbral — ambos son piezas de una estrategia de monitorización, con propósitos distintos. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/welcome-health-checks.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "OCSF",
    q: "¿Por qué Amazon Security Lake normaliza los logs al formato OCSF en vez de guardarlos en su formato original de cada servicio?",
    options: [
      "Lo exige la normativa de la SEC para los logs de seguridad almacenados en la nube",
      "OCSF comprime los eventos y reduce a la mitad el coste de almacenarlos en S3",
      "Para correlacionar fuentes distintas con un esquema común, sin parsers propios",
      "Athena solo puede consultar objetos de S3 escritos con el esquema OCSF",
    ],
    correct: 2,
    explain: "El valor de OCSF es la INTEROPERABILIDAD: un evento de autenticación de CloudTrail y uno de un firewall de terceros, ambos normalizados a OCSF, comparten la misma estructura de campos — permitiendo correlacionar 'inicio de sesión fallido' en ambas fuentes con una sola consulta, en vez de escribir lógica de parsing distinta para cada producto. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/open-cybersecurity-schema-framework.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "Un analista de seguridad revisa Security Hub y ve un finding de severidad CRÍTICA que GuardDuty nunca había emitido antes con ese nivel, titulado algo como 'AttackSequence:IAM/CompromisedCredentials'. El finding agrupa varios eventos individuales (descubrimiento de privilegios, manipulación de API, persistencia) ocurridos en un periodo de tiempo. ¿Qué característica de GuardDuty generó este finding?",
    options: [
      "GuardDuty Malware Protection, que escanea los volúmenes EBS de la instancia implicada",
      "AWS Config, que evalúa la configuración de los recursos citados en el finding",
      "Amazon Detective, que genera findings críticos propios sin depender de GuardDuty",
      "GuardDuty Extended Threat Detection, que correlaciona eventos en una attack sequence",
    ],
    correct: 3,
    explain: "GuardDuty Extended Threat Detection (GA diciembre 2024) analiza patrones a través de múltiples fuentes y periodos de tiempo para generar 'attack sequence findings' (prefijo AttackSequence:) que representan una cadena de pasos de un atacante (descubrimiento, movimiento, persistencia, exfiltración) como un único hallazgo de severidad CRÍTICA — un nivel que GuardDuty no usaba antes de esta función. Se diferencia de Detective, que ayuda a INVESTIGAR relaciones entre findings ya generados, no a generarlos. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-extended-threat-detection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for S3",
    q: "Una aplicación permite a usuarios externos subir archivos directamente a un bucket S3 antes de que un pipeline los procese. El equipo de seguridad quiere escanear automáticamente cada objeto nuevo en busca de malware ANTES de que el pipeline lo consuma, sin desplegar ni mantener su propia infraestructura de escaneo. ¿Qué solución nativa de AWS cumple este requisito?",
    options: [
      "GuardDuty Malware Protection for S3, que escanea los objetos nuevos",
      "Amazon Inspector, activando el escaneo de objetos sobre el bucket de destino",
      "Amazon Macie, con un job de clasificación programado sobre ese mismo bucket",
      "Cifrado SSE-KMS en el bucket, que rechaza los objetos con firma maliciosa",
    ],
    correct: 0,
    explain: "GuardDuty Malware Protection for S3 (GA junio 2024) escanea de forma gestionada y sin agentes los objetos nuevos subidos a buckets S3 seleccionados, disparándose ante el evento s3:ObjectCreated, y puede etiquetar el objeto o dispararte una remediación automática según se configure. Macie clasifica CONTENIDO sensible (PII), no detecta malware; Inspector evalúa vulnerabilidades de EC2/ECR/Lambda, no objetos S3; el cifrado no analiza el contenido del archivo. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/gdu-malware-protection-s3.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "¿Cómo escanea GuardDuty Malware Protection for EC2 (activado tras un finding de una instancia potencialmente comprometida) el disco de esa instancia en busca de malware, sin afectar al rendimiento de la instancia en producción?",
    options: [
      "Instala un agente en el sistema operativo y escanea el disco en caliente",
      "Toma un snapshot de los volúmenes EBS y lo escanea aislado, sin agente",
      "Reinicia la instancia en modo recuperación para escanear el disco offline",
      "Exige detener la instancia y desadjuntar los volúmenes antes de escanear",
    ],
    correct: 1,
    explain: "GuardDuty Malware Protection for EC2 es AGENTLESS: cuando se dispara (automáticamente tras ciertos findings o bajo demanda), toma un snapshot de los volúmenes EBS de la instancia/contenedor sospechoso y escanea ESE snapshot en una cuenta de escaneo gestionada por AWS, sin instalar nada en la instancia original ni afectar su disponibilidad o rendimiento, y sin necesidad de detenerla ni reiniciarla. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty RDS Protection",
    q: "Una empresa usa clústeres Aurora PostgreSQL. Quieren detectar intentos de fuerza bruta contra las credenciales de la base de datos y accesos desde patrones de login inusuales, sin modificar el motor de la base de datos ni degradar su rendimiento. ¿Qué función de GuardDuty resuelve esto?",
    options: [
      "GuardDuty Malware Protection for S3, aplicada a los backups del clúster Aurora",
      "Amazon Inspector, escaneando vulnerabilidades del motor Aurora PostgreSQL",
      "GuardDuty RDS Protection, que perfila la actividad de login con ML",
      "AWS Config, con una regla que verifica el cifrado en reposo del clúster",
    ],
    correct: 2,
    explain: "GuardDuty RDS Protection monitoriza y perfila la actividad de login de las bases de datos Aurora (MySQL y PostgreSQL compatible), RDS for PostgreSQL y Aurora PostgreSQL Limitless Database, sin necesidad de agentes ni cambios en el motor, generando findings de credenciales anómalas (login exitoso desde IP/patrón inusual, o pico de intentos fallidos indicativo de fuerza bruta) con contexto enriquecido sobre la base de datos afectada. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/rds-protection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Lambda Protection",
    q: "Un equipo sospecha que una función Lambda ha sido comprometida y está siendo usada para minar criptomonedas o comunicarse con un servidor de Comando y Control (C2), incluso en funciones que NO están configuradas dentro de una VPC. ¿Qué función de GuardDuty detecta este comportamiento?",
    options: [
      "AWS X-Ray, analizando las trazas salientes de cada invocación de la función",
      "Amazon Inspector, escaneando el código y las dependencias en busca de malware",
      "AWS Config, evaluando si la función está asociada a una VPC y a sus subredes",
      "GuardDuty Lambda Protection, que analiza la actividad de red de la función",
    ],
    correct: 3,
    explain: "GuardDuty Lambda Protection analiza los logs de actividad de red generados cada vez que se invoca una función Lambda de la cuenta —incluidas las funciones SIN configuración de VPC— para detectar tráfico saliente hacia infraestructura maliciosa conocida (C2, minería de criptomonedas), aplicando filtros inteligentes para cobrar solo por el subconjunto de esos logs de red relevante para la detección. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/lambda-protection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty EKS Runtime Monitoring",
    q: "Al activar GuardDuty EKS Runtime Monitoring en un clúster EKS, ¿cómo se despliega el agente de seguridad para obtener visibilidad a nivel de sistema operativo (ejecución de procesos, acceso a ficheros, conexiones de red) en cada nodo?",
    options: [
      "Como el add-on aws-guardduty-agent, un DaemonSet eBPF en cada nodo",
      "Como un contenedor sidecar que GuardDuty inyecta en cada pod del clúster",
      "Sin agente: basta con los audit logs de EKS que ya consume GuardDuty",
      "Como una Lambda que sondea periódicamente la API de Kubernetes del clúster",
    ],
    correct: 0,
    explain: "Para EKS, el agente de GuardDuty se distribuye como el EKS add-on 'aws-guardduty-agent' y se despliega como un DaemonSet (una instancia del agente por cada nodo compatible del clúster), construido sobre eBPF para obtener telemetría del kernel con bajo overhead. Esto contrasta con el despliegue en ECS Fargate, donde el agente se inyecta como sidecar container en cada task, porque Fargate no expone nodos persistentes donde correr un DaemonSet. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/how-runtime-monitoring-works-eks.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty ECS/Fargate Runtime Monitoring",
    q: "Una organización ejecuta la mayoría de sus cargas de trabajo en Amazon ECS sobre Fargate (sin gestionar instancias EC2 ni nodos). ¿Cómo despliega GuardDuty el agente de Runtime Monitoring en este caso, dado que Fargate no expone nodos persistentes donde correr un DaemonSet?",
    options: [
      "Runtime Monitoring no está disponible en Fargate, solo en ECS sobre EC2",
      "Como un contenedor sidecar aws-guardduty-agent- inyectado en cada task",
      "El cliente añade el agente a su propia imagen y lo declara en el Dockerfile",
      "Como una extensión del CloudWatch Agent dentro del contenedor de aplicación",
    ],
    correct: 1,
    explain: "A diferencia de EKS (DaemonSet por nodo), en ECS Fargate GuardDuty despliega el agente como un CONTENEDOR SIDECAR adicional dentro de cada task —visible como un contenedor con prefijo 'aws-guardduty-agent-'— inyectado automáticamente cuando se activa la gestión automatizada del agente (ECS_FARGATE_AGENT_MANAGEMENT) o mediante tags de inclusión en el clúster, sin necesidad de modificar las definiciones de tarea existentes. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/runtime-monitoring.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Hub: risk prioritization",
    q: "Desde finales de 2025, AWS reorganizó Security Hub: el servicio de checks de compliance que existía hasta entonces (CIS, PCI-DSS, AWS FSBP) pasó a llamarse 'Security Hub CSPM' y ahora es un subcomponente de un 'nuevo' Security Hub más amplio. ¿Qué capacidad adicional aporta este nuevo Security Hub sobre el Security Hub CSPM original?",
    options: [
      "Sustituye a GuardDuty e Inspector como origen de los findings",
      "Abandona ASFF y OCSF por un formato de finding propietario",
      "Correlación y priorización del riesgo casi en tiempo real",
      "Añade un panel de costes, sin cambios en la capa de detección",
    ],
    correct: 2,
    explain: "El nuevo Security Hub (GA general a finales de 2025) añade una capa de análisis de riesgo que correlaciona automáticamente señales de múltiples servicios (Security Hub CSPM, Inspector, GuardDuty, Macie) para producir 'exposure findings' — contexto de negocio sobre qué hallazgos combinados representan el mayor riesgo real (ej. exposición pública + vulnerabilidad crítica + datos sensibles), en vez de exigir que un analista correlacione manualmente miles de findings individuales de baja prioridad. Sigue necesitando que GuardDuty/Inspector estén activados como fuentes. <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudTrail network activity events",
    q: "Tu organización usa VPC endpoints (AWS PrivateLink) para que las cargas de trabajo accedan a servicios como S3 o KMS sin salir a Internet. Quieres auditar la actividad de API que atraviesa esos VPC endpoints, incluida la generada por servicios de AWS actuando en tu nombre, algo que el CloudTrail estándar (management/data events) no siempre refleja con el mismo detalle. ¿Qué función usas?",
    options: [
      "VPC Flow Logs, que ya registran qué operación de API atravesó el endpoint",
      "Amazon Detective, que reconstruye esas llamadas a partir del grafo de comportamiento",
      "GuardDuty, activando la fuente de datos de S3 sobre los buckets accedidos",
      "CloudTrail network activity events, un tipo de evento propio de los VPC endpoints",
    ],
    correct: 3,
    explain: "CloudTrail network activity events for VPC endpoints (GA febrero 2025) es un nuevo TIPO de evento, distinto de los management/data events tradicionales, que da visibilidad sobre la actividad de API que pasa a través de un VPC endpoint para los servicios soportados — incluyendo llamadas hechas por servicios de AWS en tu nombre. VPC Flow Logs solo ven metadatos de red (IP/puerto), no qué API se invocó. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-network-events-with-cloudtrail.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Route 53 DNS Firewall Advanced",
    q: "Un equipo de seguridad ha configurado Route 53 Resolver DNS Firewall con listas de dominios gestionadas (malware, botnets conocidos) pero sigue preocupado por malware que genera dominios aleatorios mediante un Domain Generation Algorithm (DGA) o que usa DNS tunneling para exfiltrar datos — técnicas diseñadas para evadir listas estáticas de dominios. ¿Qué capacidad de DNS Firewall aborda específicamente esta amenaza?",
    options: [
      "DNS Firewall Advanced, que inspecciona el patrón de la consulta DNS",
      "Subir el TTL de las respuestas para que el resolver cachee los dominios nuevos",
      "Activar DNSSEC en la zona alojada para validar el origen de las respuestas",
      "Redirigir las consultas a un resolver de terceros situado fuera de la VPC",
    ],
    correct: 0,
    explain: "Las reglas 'Foundational' de DNS Firewall bloquean contra listas de dominios conocidos (maliciosos, gestionadas por AWS o Recorded Future). DNS Firewall Advanced añade un tier de reglas que analiza el PATRÓN de la consulta (longitud, entropía, estructura) para detectar técnicas diseñadas precisamente para evadir listas estáticas, como DGA y DNS tunneling, permitiendo ajustar un 'confidence_threshold' en vez de depender solo de listas de dominios. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/firewall-advanced.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Detective finding groups",
    q: "Un analista tiene decenas de findings de GuardDuty de severidad baja/media aparentemente inconexos en Security Hub, y sospecha que varios pertenecen a la misma campaña de ataque pero no tiene tiempo de correlacionarlos manualmente. ¿Qué función de Amazon Detective le ayuda directamente con esto?",
    options: [
      "Detective genera nuevos findings de GuardDuty que sustituyen a los originales",
      "Finding groups, que agrupan con ML los findings que comparten entidades",
      "Detective reemplaza a Security Hub como panel de agregación de findings",
      "Detective analiza un finding cada vez y no dispone de agrupación automática",
    ],
    correct: 1,
    explain: "Los finding groups de Amazon Detective usan ML para identificar qué findings de GuardDuty (y también de Inspector) están relacionados por compartir entidades (mismo rol IAM, misma sesión, misma IP), agrupando señales de baja severidad que aisladas podrían ignorarse, pero que juntas muestran una campaña de ataque completa — e incluye resúmenes generados con IA generativa en lenguaje natural para acelerar la investigación. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/groups-about.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Macie automated sensitive data discovery",
    q: "Una cuenta tiene cientos de buckets S3 con petabytes de datos. El equipo quiere mantener visibilidad CONTINUA de qué buckets contienen datos sensibles sin pagar por escanear cada objeto completo de forma recurrente, algo que sería prohibitivamente caro. ¿Qué capacidad de Macie está diseñada específicamente para este caso?",
    options: [
      "Un discovery job programado a diario sobre el 100% de los objetos del inventario",
      "Amazon Inspector, aplicado al inventario de buckets S3 de la cuenta",
      "Automated sensitive data discovery, que muestrea objetos representativos",
      "GuardDuty S3 Protection, que clasifica el contenido de cada objeto nuevo",
    ],
    correct: 2,
    explain: "Automated sensitive data discovery es la capacidad de Macie que evalúa el inventario de S3 de forma continua (diaria) y aplica MUESTREO inteligente sobre un subconjunto representativo de objetos por bucket, en vez de escanear cada objeto — manteniendo visibilidad actualizada de qué buckets tienen datos sensibles a una fracción del coste de un job de clasificación exhaustivo. Los sensitive data discovery jobs tradicionales (puntuales o programados) siguen existiendo para análisis exhaustivo y dirigido cuando se necesita examinar el 100% de un alcance concreto. <a href=\"https://docs.aws.amazon.com/macie/latest/user/discovery-asdd.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Security Incident Response",
    q: "Una organización quiere que, cuando GuardDuty o Security Hub CSPM generen un finding crítico, se dispare automáticamente un flujo de triage, y tener acceso 24/7 a un equipo de respuesta a incidentes de AWS para colaborar en la contención, sin construir ellos mismos esa integración desde cero. ¿Qué servicio de AWS cubre este caso de uso?",
    options: [
      "AWS Trusted Advisor, con los checks de su categoría de seguridad",
      "AWS Config, con una remediación automática asociada a cada regla",
      "Amazon Detective, habilitando su modo de respuesta a incidentes 24/7",
      "AWS Security Incident Response, que triagea y escala al CIRT",
    ],
    correct: 3,
    explain: "AWS Security Incident Response (GA diciembre 2024) es un servicio dedicado que ingesta y triagea automáticamente findings de GuardDuty y de Security Hub CSPM (incluyendo integraciones de terceros vía Security Hub), ofrece herramientas de colaboración para la respuesta, puede tomar acciones de contención con tu permiso, y da acceso directo 24/7 al AWS Customer Incident Response Team — no es una funcionalidad de Trusted Advisor, Detective ni Config. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Lake rollup regions",
    q: "Una empresa opera en tres regiones de AWS y, por motivos de cumplimiento normativo, necesita que los datos de seguridad de Security Lake de cada región permanezcan también disponibles localmente, pero además quiere consolidar una copia de todas ellas en una única región para análisis centralizado. ¿Qué concepto de Security Lake permite esto?",
    options: [
      "Rollup regions: una región recibe copia de las contributing regions",
      "Security Lake solo admite una región activa por organización, sin copias",
      "Replicación cruzada de S3 configurada a mano al margen de Security Lake",
      "Un aggregator de AWS Config, reutilizado para consolidar esos mismos datos",
    ],
    correct: 0,
    explain: "Security Lake permite designar una o más rollup regions que reciben una COPIA de los datos de las contributing regions especificadas (los datos originales siguen existiendo en sus regiones/buckets de origen, cumpliendo requisitos de residencia de datos), dando además un único punto de integración para herramientas de análisis centralizadas — configurable vía consola o la API UpdateDataLake. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/manage-regions.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudWatch cross-account observability",
    q: "El equipo de seguridad quiere ver, desde una única cuenta central de monitorización, las métricas, logs de CloudWatch Logs y trazas de X-Ray generados en decenas de cuentas de carga de trabajo de la organización, SIN copiar ni duplicar esos datos entre cuentas. ¿Qué mecanismo de AWS permite esto?",
    options: [
      "Suscripciones de CloudWatch Logs que copian los log groups a la cuenta central",
      "CloudWatch cross-account observability mediante Observability Access Manager",
      "Amazon Security Lake, que ingiere y centraliza las métricas de CloudWatch",
      "Un organization trail de CloudTrail ampliado para incluir métricas y trazas",
    ],
    correct: 1,
    explain: "OAM (Observability Access Manager) es el servicio que sustenta CloudWatch cross-account observability: mediante 'sinks' (en la cuenta de monitorización) y 'links' (desde cada cuenta origen), permite que una cuenta central consulte y visualice métricas, logs y trazas de hasta 100.000 cuentas origen SIN mover ni copiar los datos — se consultan in situ, a diferencia de una solución basada en suscripciones de CloudWatch Logs, que sí replica los logs a otra cuenta. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Config aggregator",
    q: "Quieres tener, desde una única cuenta, una vista consolidada del estado de cumplimiento de las Config Rules y del inventario de recursos de TODAS las cuentas de tu AWS Organization y de todas sus regiones, sin necesariamente convertir esa cuenta en delegated administrator de Security Hub. ¿Qué recurso de AWS Config usas?",
    options: [
      "Un organization trail de CloudTrail entregado al bucket de esa cuenta",
      "Un conformance pack, que ya consolida la vista sin necesidad de aggregator",
      "Un AWS Config aggregator a nivel de organización en esa cuenta",
      "Amazon Security Lake, redirigiendo únicamente los datos de AWS Config",
    ],
    correct: 2,
    explain: "Un Config aggregator (en su variante de organización) es un recurso específico de AWS Config que recopila y consolida en una única cuenta el estado de configuración de recursos y el cumplimiento de Config Rules de todas las cuentas miembro y regiones habilitadas de la Organization — es un concepto independiente del delegated administrator de Security Hub/GuardDuty, aunque puedan coexistir en la misma cuenta de seguridad. Un conformance pack por sí solo despliega reglas, no agrega su visualización entre cuentas. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Hub vs Security Lake aggregation",
    q: "Un arquitecto de seguridad necesita explicar la diferencia entre 'Security Hub cross-region aggregation' y las 'rollup regions' de Amazon Security Lake, ya que ambas suenan a 'centralizar datos de varias regiones'. ¿Cuál es la distinción correcta?",
    options: [
      "Son el mismo mecanismo, solo renombrado según el servicio que lo implementa",
      "Ambas exigen tener Amazon Security Lake activado como prerrequisito técnico",
      "La de Security Hub opera dentro de una cuenta y la de Security Lake entre organizaciones",
      "Security Hub consolida findings; las rollup regions de Security Lake, logs OCSF",
    ],
    correct: 3,
    explain: "Aunque ambas resuelven 'quiero ver datos de varias regiones en un solo sitio', operan sobre capas distintas: Security Hub cross-region aggregation trabaja con FINDINGS (el resultado de la detección/evaluación) y los replica hacia una región agregadora designada para el panel de Security Hub; Security Lake rollup regions trabaja con LOGS crudos normalizados a OCSF y replica copias de esos logs hacia una región de destino para análisis. No son intercambiables ni dependen técnicamente la una de la otra. <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/finding-aggregation.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty a escala de organización",
    q: "Una empresa con 180 cuentas en AWS Organizations quiere que GuardDuty esté activo en todas, y que cualquier cuenta nueva quede protegida sin intervención manual. ¿Qué DOS pasos son necesarios?",
    options: [
      "Designar una cuenta como delegated administrator de GuardDuty desde la management account",
      "Crear en cada cuenta miembro un rol IAM que permita a GuardDuty leer CloudTrail y flow logs",
      "Activar auto-enable para que las cuentas nuevas de la organización se incorporen solas",
      "Habilitar GuardDuty cuenta por cuenta e invitarlas una a una desde la cuenta central",
    ],
    correct: [0, 2],
    explain: "GuardDuty se gobierna en Organizations con un <b>delegated administrator</b> y la opción de <b>auto-enable</b>, que incorpora las cuentas nuevas sin tocar nada. GuardDuty consume CloudTrail, VPC Flow Logs y DNS logs por su cuenta mediante un service-linked role: no hay que crear roles ni habilitar esos logs. El flujo de invitaciones manuales existe, pero es justo lo que se quiere evitar y no cubre las cuentas futuras. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/set-guardduty-auto-enable-preferences.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudTrail: eventos de datos",
    q: "Tras un incidente, el equipo descubre que CloudTrail no registró QUIÉN descargó objetos concretos de un bucket S3, aunque sí registró la creación del bucket. ¿Qué DOS afirmaciones explican y resuelven la situación?",
    options: [
      "CloudTrail no puede registrar acceso a objetos: solo el S3 server access logging lo hace",
      "Los management events registran operaciones sobre el bucket, no sobre objetos concretos",
      "Basta con ampliar la retención del trail para que los eventos aparezcan retroactivamente",
      "Hay que habilitar data events de S3 en el bucket y registrar lecturas como GetObject",
    ],
    correct: [1, 3],
    explain: "CloudTrail separa <b>management events</b> (plano de control: CreateBucket, PutBucketPolicy) de <b>data events</b> (plano de datos: GetObject, PutObject), y los data events están desactivados por defecto porque tienen coste y volumen altos. S3 server access logging es una alternativa, no la única vía. Y la retención nunca genera eventos que no se capturaron: lo que no se registró no existe. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cuenta de logging inmutable",
    q: "Auditoría exige que los logs de CloudTrail no puedan ser borrados ni alterados por un administrador de la cuenta que los genera, ni siquiera con credenciales root. ¿Qué DOS medidas lo consiguen?",
    options: [
      "Entregar los logs a un bucket de una cuenta de logging dedicada y separada",
      "Cifrar el bucket con SSE-S3 en lugar de SSE-KMS para impedir el borrado de objetos",
      "Activar el versionado del bucket y confiar en que nadie borre versiones anteriores",
      "Aplicar S3 Object Lock en modo compliance sobre el bucket de destino de los logs",
    ],
    correct: [0, 3],
    explain: "La separación de cuentas quita el poder al administrador de la cuenta origen, y <b>Object Lock en modo compliance</b> impide el borrado incluso a root durante el periodo de retención (el modo governance sí admite excepción con un permiso especial, por eso no vale aquí). El tipo de cifrado no cambia quién puede borrar. El versionado ayuda a recuperar, pero un administrador con permisos puede borrar versiones: confiar no es un control. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Hub multi-Región",
    q: "Una organización opera en 5 Regiones y quiere revisar todos los findings de Security Hub desde un único panel, en una sola cuenta y Región. ¿Qué DOS elementos hacen falta?",
    options: [
      "Replicar los findings con una función Lambda desplegada en cada Región",
      "Designar un delegated administrator de Security Hub en la organización",
      "Configurar una Región de agregación que consolide los findings de las demás",
      "Desactivar Security Hub en las Regiones secundarias para no duplicar findings",
    ],
    correct: [1, 2],
    explain: "Security Hub necesita <b>delegated administrator</b> para la vista multi-cuenta y <b>cross-Region aggregation</b> para la vista multi-Región; son dos ejes distintos y hacen falta los dos. La replicación con Lambda es reinventar una función nativa. Y desactivar Security Hub en las otras Regiones eliminaría precisamente los findings que se quieren ver: los controles se evalúan donde están los recursos. <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/finding-aggregation-enable.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Elegir la fuente de log",
    q: "Necesitas saber quién modificó la política de un bucket S3 y desde qué dirección IP lo hizo. ¿Qué fuente de log responde a esa pregunta?",
    options: [
      "Los VPC Flow Logs de la subred donde vive la aplicación que usa el bucket",
      "Los S3 server access logs del bucket, que registran cada petición recibida",
      "El evento de CloudTrail de la llamada PutBucketPolicy, con su sourceIPAddress",
      "Las métricas de CloudWatch del bucket durante la ventana del cambio",
    ],
    correct: 2,
    explain: "Cambiar una política de bucket es una llamada al <b>plano de control</b>, y eso vive en CloudTrail: el evento <code>PutBucketPolicy</code> trae identidad, hora y <code>sourceIPAddress</code>. Los server access logs y los data events de S3 registran acceso a <b>objetos</b>, no cambios de configuración. Los Flow Logs ven paquetes, no llamadas a la API, y las métricas cuentan pero no dicen quién. Saber qué pregunta responde cada fuente es la mitad del dominio de detección. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-concepts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Requisitos de retención",
    q: "Una carga de trabajo nueva procesa datos de tarjetas y está sujeta a PCI DSS. ¿Qué determina cuánto tiempo hay que conservar sus logs de seguridad?",
    options: [
      "El coste de almacenamiento en CloudWatch Logs, que crece con el volumen ingerido",
      "Los requisitos de cumplimiento de la carga y su ventana de investigación",
      "El periodo por defecto de CloudTrail, que conserva 90 días de eventos de gestión",
      "El tiempo que tarda GuardDuty en generar findings sobre los eventos ingeridos",
    ],
    correct: 1,
    explain: "La retención se deriva del <b>requisito</b>, no de la herramienta: el marco de cumplimiento fija un mínimo y la ventana de investigación realista suele pedir más. El coste es una consecuencia a optimizar después, no la entrada del diseño. Los 90 días del historial de eventos de CloudTrail son la vista de consola, no un límite del trail. Y GuardDuty analiza en continuo: su latencia no tiene relación con cuánto guardas. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Alerta sobre un cambio de configuración",
    q: "Quieres que salte un aviso en cuanto alguien desactive el cifrado por defecto de un bucket, sin depender de que un humano mire un panel. ¿Cómo lo montas?",
    options: [
      "Una alarma de CloudWatch sobre la métrica de peticiones PUT del bucket",
      "Un panel de CloudWatch con un widget que muestre la configuración del bucket",
      "Una consulta programada de Athena sobre los logs de acceso al servidor de S3",
      "Una regla de EventBridge sobre el evento de CloudTrail que publica en SNS",
    ],
    correct: 3,
    explain: "El patrón de detección casi reflejo en AWS es <b>CloudTrail → EventBridge → destino</b>: la regla casa el evento concreto y lo entrega a SNS, Lambda o Systems Manager en segundos. Una alarma sobre peticiones PUT mide volumen, no configuración. Un panel exige que alguien lo mire, que es justo lo que se quiere evitar. Y una consulta programada de Athena introduce el retardo de su propio horario, además de mirar la fuente equivocada. <a href=\"https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Estado deseado en la flota",
    q: "Debes garantizar que el agente de CloudWatch está instalado y con la misma configuración en todas las instancias EC2, incluidas las que se lancen la semana que viene. ¿Qué encaja mejor?",
    options: [
      "Systems Manager State Manager, que reaplica el estado deseado periódicamente",
      "Una regla de AWS Config que marque como no conformes las instancias sin el agente",
      "Un script de user data en la plantilla de lanzamiento del Auto Scaling group",
      "Systems Manager Run Command lanzado a mano al detectar instancias nuevas",
    ],
    correct: 0,
    explain: "<b>State Manager</b> declara un estado y lo <b>reaplica</b> según su horario, así que corrige tanto la instancia nueva como la que alguien tocó ayer. Una regla de Config detecta la desviación pero no la arregla por sí sola. El user data se ejecuta una única vez al arrancar y no repara nada después. Y Run Command a mano depende de que alguien se acuerde, que es la definición de control que no escala. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-state.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Logs de flujo en Transit Gateway",
    q: "Dos VPC se comunican a través de un Transit Gateway y necesitas ver el tráfico que el propio gateway descarta por sus tablas de rutas, no lo que ocurre dentro de cada VPC. ¿Qué activas?",
    options: [
      "VPC Flow Logs en las dos VPC, que ya cubren todo lo que atraviesa el gateway",
      "Transit gateway flow logs, que registran el tráfico en sus attachments",
      "Route 53 Resolver query logs sobre las dos VPC conectadas al gateway",
      "Los logs de acceso del Network Load Balancer situado delante del gateway",
    ],
    correct: 1,
    explain: "Los <b>transit gateway flow logs</b> son una fuente propia del gateway: registran cada flujo por attachment y tabla de rutas, incluido lo que se descarta porque no hay ruta. Los VPC Flow Logs solo ven las ENI dentro de la VPC, así que un paquete rechazado en el gateway nunca aparece ahí. Los logs de Resolver responden preguntas de DNS. Y el balanceador ni siquiera está en ese camino. <a href=\"https://docs.aws.amazon.com/vpc/latest/tgw/tgw-flow-logs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Consultas históricas de CloudTrail",
    q: "Seguridad necesita consultar con SQL siete años de eventos de CloudTrail sin montar ni mantener infraestructura de consulta propia. ¿Qué encaja?",
    options: [
      "Un trail que entregue a S3 y una tabla de Athena creada sobre ese prefijo",
      "CloudWatch Logs Insights sobre el grupo de logs al que entrega el trail",
      "Amazon OpenSearch Service con los eventos ingeridos por una función Lambda",
      "CloudTrail Lake, un almacén de datos de eventos consultable con SQL",
    ],
    correct: 3,
    explain: "<b>CloudTrail Lake</b> guarda los eventos en un event data store gestionado, con retención de hasta siete años y consultas SQL desde la propia consola: no hay bucket, ni catálogo, ni clúster que mantener. Athena sobre S3 resuelve lo mismo pero exige crear y particionar la tabla. Logs Insights no usa SQL y su retención se gestiona aparte. Y OpenSearch es precisamente la infraestructura que el enunciado descarta. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-lake.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Panel unificado de seguridad",
    q: "Quieres un panel único que combine métricas de CloudWatch, datos de OpenSearch y de Prometheus para el equipo de seguridad, con inicio de sesión federado desde IAM Identity Center. ¿Qué servicio?",
    options: [
      "Amazon Managed Grafana, que federa varias fuentes y usa Identity Center",
      "Un panel de CloudWatch, que ya muestra métricas y logs en la misma pantalla",
      "Security Hub, cuyo resumen agrega los findings de los servicios de seguridad",
      "Amazon Athena con una vista que una las tres fuentes en una sola consulta",
    ],
    correct: 0,
    explain: "<b>Amazon Managed Grafana</b> existe justo para eso: conecta varios orígenes —CloudWatch, OpenSearch, Prometheus, y de terceros— en un mismo panel y delega la autenticación en IAM Identity Center. Los paneles de CloudWatch se quedan en las fuentes de CloudWatch. Security Hub agrega findings de seguridad, no series temporales arbitrarias. Y Athena consulta datos en S3, no métricas de Prometheus. <a href=\"https://docs.aws.amazon.com/grafana/latest/userguide/what-is-Amazon-Managed-Service-Grafana.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Entrega de notificaciones",
    q: "La organización quiere que los avisos importantes de sus cuentas lleguen a un centro de notificaciones común en la consola y además al móvil del equipo de guardia, sin escribir código. ¿Qué servicio lo centraliza?",
    options: [
      "Un tema de SNS con suscripción SMS creado a mano en cada cuenta miembro",
      "AWS User Notifications, que centraliza los avisos de la consola",
      "Una función Lambda suscrita a EventBridge que llame a la API de mensajería",
      "Amazon EventBridge Scheduler, que reparte los eventos según su calendario",
    ],
    correct: 1,
    explain: "<b>AWS User Notifications</b> es la capa de entrega: se configuran reglas sobre eventos de EventBridge y se eligen destinos —el Notifications Center de la consola, correo, chat o móvil—, con vista consolidada para toda la organización y sin código. Un tema de SNS por cuenta funciona, pero hay que crearlo y mantenerlo en cada una. Lambda es escribir el código que el enunciado descarta. Y Scheduler dispara por horario, no por evento. <a href=\"https://docs.aws.amazon.com/notifications/latest/userguide/what-is-service.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Qué monitorizar antes de cómo",
    q: "Un equipo va a instrumentar una carga nueva y empieza activando todas las métricas y todos los logs disponibles, para no quedarse corto. ¿Qué corriges del enfoque?",
    options: [
      "Nada: en monitorización siempre es preferible recoger de más y filtrar después con consultas",
      "Que conviene empezar por las métricas y dejar los logs para una segunda fase, por coste",
      "Que los requisitos salen de lo que la carga necesita demostrar y detectar",
      "Que hay que activar solo lo que exija la norma de cumplimiento aplicable a esa carga",
    ],
    correct: 2,
    explain: "Analizar la carga para determinar <b>qué</b> monitorizar es un paso de diseño, no una opción. Se parte de las preguntas que hay que poder responder —quién accedió a este dato, se degradó este servicio, cambió alguien esta configuración— y de ahí salen las fuentes, la retención y las alarmas. Activarlo todo produce dos daños: la factura de ingesta crece sin límite y la señal útil queda enterrada bajo eventos que nadie mira. Dejar los logs para después ordena mal las prioridades, y limitarse a la norma cubre la auditoría pero no la operación. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
  {
    tag: "La alarma que nadie atiende",
    q: "Un equipo tiene 400 alarmas de CloudWatch y admite que ignora la mayoría de las notificaciones. Quieren reducir el ruido sin perder cobertura.",
    options: [
      "Revisar cada alarma contra una acción concreta y retirar la que no lleve a ninguna",
      "Subir los umbrales de todas las alarmas un 20% para que salten con menos frecuencia",
      "Agrupar todas las notificaciones en un único tema de SNS con resumen diario",
      "Aumentar el número de periodos de evaluación en todas las alarmas antes de disparar",
    ],
    correct: 0,
    explain: "Una alarma existe para provocar una <b>acción</b>. Si nadie sabe qué hacer cuando salta, no es una alarma: es una métrica, y su sitio es un panel. El criterio para podar es ese, no el umbral: por cada alarma, quién la recibe y qué hace. Subir umbrales a ciegas apaga también las que sí importaban. Un resumen diario convierte una señal de tiempo real en un informe. Y alargar los periodos de evaluación retrasa la detección sin arreglar que la alarma no lleve a ningún sitio. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
  {
    tag: "Umbral fijo o comportamiento",
    q: "El número de invocaciones de una función varía mucho entre día laborable y fin de semana. Un umbral fijo o dispara falsas alarmas el sábado o no detecta nada el martes. ¿Qué usas?",
    options: [
      "Dos alarmas distintas, una para días laborables y otra para fines de semana, con umbrales propios",
      "Una alarma sobre la media móvil de siete días, que suaviza la diferencia entre semana y fin de semana",
      "Una alarma compuesta que combine invocaciones con errores, para reducir los falsos positivos",
      "Detección de anomalías de CloudWatch, que aprende la banda esperada por hora y día y alerta al salirse de ella",
    ],
    correct: 3,
    explain: "La detección de anomalías construye un modelo del comportamiento <b>esperado</b> de la métrica según la hora y el día, y la alarma se define contra esa banda en lugar de contra un número fijo. Es exactamente el caso de una métrica con estacionalidad conocida. Dos alarmas con umbrales propios funcionan hasta que aparece un festivo o cambia el patrón, y hay que mantenerlas. La media móvil oculta precisamente el pico que quieres ver. Y una alarma compuesta reduce falsos positivos combinando señales, pero no resuelve que el umbral base sea inadecuado. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-anomaly-detection.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
  {
    tag: "Qué logs y con qué retención",
    q: "Una obligación exige poder reconstruir, hasta cinco años después, quién leyó un objeto concreto de S3. El equipo tiene CloudTrail activado con la configuración por defecto y retención de 90 días.",
    options: [
      "Basta con ampliar la retención del trail a cinco años: la lectura del objeto ya se registra por defecto",
      "Faltan las dos: habilitar data events de S3 y llevar el trail a S3 con cinco años",
      "Basta con habilitar los logs de acceso al servidor del bucket, que registran cada lectura con detalle suficiente",
      "Basta con activar Macie sobre el bucket, que inventaría los accesos al contenido sensible",
    ],
    correct: 1,
    explain: "Identificar las fuentes de log a partir del requisito exige mirar dos cosas: <b>qué</b> se registra y <b>cuánto</b> se guarda. CloudTrail registra por defecto solo <b>management events</b> —el plano de control: crear el bucket, cambiar su política—. Quién descargó un objeto concreto es un <b>data event</b>, está desactivado por defecto y hay que habilitarlo. Y la retención de 90 días del historial de eventos no cubre cinco años: hace falta que el trail entregue a S3, con su ciclo de vida. Los logs de acceso al servidor son best-effort y no sirven como registro de auditoría. Y Macie clasifica el dato, no registra los accesos. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/aws-security-incident-response-guide/logging-and-events.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
  {
    tag: "Dónde aterrizan los logs",
    q: "Diseñas la ingesta de logs de una organización con cuarenta cuentas. ¿Dónde entregas los trails y por qué?",
    options: [
      "En un bucket por cuenta, para que cada equipo conserve la propiedad de sus propios registros de auditoría",
      "En el bucket de la cuenta de gestión, que ya concentra la facturación y las políticas de la organización",
      "En una cuenta de logging dedicada y aislada, para que comprometer producción no dé acceso a los registros",
      "En un bucket replicado entre las cuarenta cuentas, para que cualquiera pueda consultar el histórico completo",
    ],
    correct: 2,
    explain: "El log es la evidencia de lo que hizo el atacante, así que el diseño asume que el atacante llegará a la cuenta que está atacando: si los registros viven ahí, los borra. Por eso se entregan a una <b>cuenta de logging dedicada</b>, sin cargas de trabajo, con acceso muy restringido y a ser posible con bloqueo de objetos. Un bucket por cuenta pone la evidencia al alcance de quien la generó. La cuenta de gestión es el objetivo de mayor valor de la organización y no debe alojar cargas. Y replicar a las cuarenta multiplica por cuarenta las oportunidades de borrado. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/logging-with-S3.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
  {
    tag: "Una bandeja para todas las cuentas",
    q: "Un equipo de plataforma quiere ver en un solo sitio los avisos operativos y de seguridad que AWS emite para las cuarenta cuentas de la organización, sin montar una integración por servicio.",
    options: [
      "AWS User Notifications a nivel de organización, que centraliza los avisos de todas",
      "Una regla de EventBridge por cuenta que reenvíe todos los eventos a un tema de SNS común",
      "Suscribirse manualmente a los boletines de cada servicio desde la consola de cada una de las cuentas",
      "Un panel de CloudWatch en la cuenta de gestión con widgets de cada servicio de las cuarenta cuentas",
    ],
    correct: 0,
    explain: "<b>User Notifications</b> es el servicio pensado para esto: agrega los avisos que AWS emite —eventos de estado, hallazgos, recordatorios de mantenimiento— en una bandeja unificada, con configuraciones a nivel de organización para no repetirlas cuenta por cuenta, y los reenvía a los canales que elijas. Cuarenta reglas de EventBridge hacen algo parecido a costa de construirlo y mantenerlo. Suscribirse a mano por consola no escala y se rompe con cada cuenta nueva. Y un panel de CloudWatch muestra métricas, no avisos. <a href=\"https://docs.aws.amazon.com/notifications/latest/userguide/what-is-service.html\" target=\"_blank\" rel=\"noopener\">AWS Docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["detection"] = QUIZ_DATA;
