// Question bank for the module: best practices and priorities (SC-100, domain 1).
// Every explanation ends with a link to the official Microsoft Learn documentation.

var QUIZ_DATA = [
  {
    tag: "Where the priority comes from",
    q: "A customer asks for a security strategy and hands over a report with eight hundred vulnerabilities. Where does the design start?",
    options: [
      "With the report's critical vulnerabilities, which are the ones an attacker would exploit first",
      "With an analysis of the most frequent threats in the customer's sector",
      "By identifying the critical business processes and the assets they depend on",
      "By comparing the current posture with that of similar organisations in size and sector",
    ],
    correct: 2,
    explain: "The strategy does not come from a catalogue of threats but from <b>what the business needs to keep running</b>. First the critical processes and their assets; then which threats put <em>those</em> assets at risk, and from that the priority of controls. Ordering by technical severity treats a critical in a test environment and a medium on the road to the billing system exactly the same. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Who sets the objective",
    q: "Designing the protection of a billing application, the security team proposes a nightly daily backup. What is missing before accepting that design?",
    options: [
      "Knowing the RPO and RTO the business accepts for that application",
      "Checking that the backup storage has customer-managed key encryption enabled",
      "Verifying the nightly window does not clash with other applications' batch processes",
      "Deciding how many backups are kept and for how long before being deleted",
    ],
    correct: 0,
    explain: "A daily backup means accepting the loss of up to <b>twenty-four hours</b> of billing, and that is not security's call: the <b>business</b> makes it with its <b>RPO</b>, just as it sets with the <b>RTO</b> how long it can be down. Without those two numbers the design is a guess. Encryption, window and retention are later decisions, and all of them depend on the first. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/disaster-recovery-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Backups that survive the attacker",
    q: "The backup design for a critical environment is being reworked on the assumption that the attacker will obtain administrator credentials. Which TWO measures does the design include?",
    options: [
      "Increasing backup frequency from daily to every four hours, to reduce data loss",
      "Immutable backups, with soft delete and deletion protected by multifactor authentication",
      "Encrypting the backups with a customer-managed key held in Key Vault",
      "Separation of duties: whoever administers the workload does not administer its backup vault",
    ],
    correct: [1, 3],
    explain: "The stem's premise is that the attacker <b>holds permissions</b>, and against that frequency and encryption do nothing: they could delete the backups anyway. What saves them is the platform <b>not allowing deletion</b> — immutability, soft delete, MFA-protected deletion — and the workload's credentials <b>not working</b> on the vault. Encryption protects confidentiality, which is not the risk here. <a href=\"https://learn.microsoft.com/en-us/azure/backup/backup-azure-security-feature\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Green backups that do not restore",
    q: "A customer shows a dashboard with twelve months of successful backups and not a single failure. What do you ask before accepting their recovery capability?",
    options: [
      "Whether the backups are replicated to a geographically distant second region",
      "Whether the backup vault has customer-managed key encryption enabled",
      "Whether the configured retention covers the period the sector regulation requires",
      "When the last restore was, and whether it met the committed RTO",
    ],
    correct: 3,
    explain: "A green backup only proves the process finished, not that the data is usable or that the business comes back in time. The question separating a real plan from a pretty dashboard is <b>when the last restore was</b> and whether it met the <b>RTO</b>. Replication, encryption and retention are good properties of a backup that may never have been tested. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/disaster-recovery-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where to start against ransomware",
    q: "Management asks for a ransomware plan and wants to know what gets tackled first, with budget for a single line of work this quarter. Which one do you choose?",
    options: [
      "Deploying EDR across the estate and enabling attack surface reduction on the clients",
      "Securing the ability to recover: immutable, isolated backups with a tested restore",
      "Hardening email, which is where most campaigns of this type get in",
      "Training the whole organisation with quarterly phishing simulation campaigns",
    ],
    correct: 1,
    explain: "Microsoft's order is <b>recover, limit the damage, make entry harder</b>, and it is deliberately counter-intuitive. Recovery goes first because it is the only thing that guarantees the business survives <em>even if prevention fails</em>, and it takes away the attacker's leverage. EDR, email and training are the next phases, not the first. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase1\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What turns an incident into a catastrophe",
    q: "With recovery already handled, the customer asks which line of work stops one compromised machine ending in the whole organisation being encrypted. Which is it?",
    options: [
      "Segmenting the network into more zones and filtering traffic between them with an internal firewall",
      "Shortening detection time with more analytics rules and extended SOC coverage hours",
      "Privileged access: PIM, dedicated workstations, LAPS and separated administration planes",
      "Increasing backup frequency so the restore point sits closer in time",
    ],
    correct: 2,
    explain: "What turns a compromised machine into an encrypted organisation is reaching <b>administrative credentials</b> from it. That is why the second phase is <b>privileged access</b>: time-bound activation in PIM, dedicated workstations, unique local passwords with LAPS, and separated planes. Segmentation helps, detection shortens the damage, and more backups do not limit the blast radius. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Patching without breaking",
    q: "The platform team wants to apply every security update the day it is published, across the whole server estate. What do you recommend?",
    options: [
      "Deployment rings with a pilot group and phases, plus a fast lane for what is actively exploited",
      "Applying them all immediately, since the risk of not patching always beats that of a regression",
      "Systematically delaying them thirty days so others find the regressions first",
      "Applying only the criticals immediately and leaving the rest for the quarterly maintenance window",
    ],
    correct: 0,
    explain: "A mature design does not choose between speed and stability: it combines them with <b>deployment rings</b> — pilot first, then production in phases — and a documented <b>fast lane</b> for vulnerabilities actually being exploited. Applying everything at once risks a global outage; always waiting thirty days leaves the urgent open; and pushing non-criticals to a quarter accumulates debt. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What cannot be patched",
    q: "An indispensable legacy system has a known vulnerability and the vendor will publish no fix. What does the design capture?",
    options: [
      "Accepting and documenting the risk, since no vendor fix is available",
      "Retiring the system immediately and replacing it with a supported alternative",
      "Applying a later version's update even though the vendor does not support it",
      "Compensating mitigation — isolation and filtering — with a planned retirement and its date",
    ],
    correct: 3,
    explain: "\"Indispensable\" rules out retiring it today and \"no fix\" rules out patching it, but simply accepting the risk is not a design. What is expected is <b>compensating mitigation</b> — segment, filter, restrict who reaches it, watch it closely — together with a <b>retirement plan with a date</b>, so the exception does not become permanent. Installing unsupported patches adds a different risk. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-posture-vulnerability-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Finding the gap",
    q: "A customer has bought security tools without a plan and wants to know which capabilities they are still missing. What do you use to answer?",
    options: [
      "The Microsoft Cloud Security Benchmark, checking control by control what is not met",
      "The cybersecurity reference architectures, to map capabilities and see the gaps",
      "The Cloud Adoption Framework, following its adoption journey from the strategy phase",
      "The Well-Architected Framework, reviewing each workload and its design trade-offs",
    ],
    correct: 1,
    explain: "The question is \"<em>which capabilities am I missing</em>\", and that is the map: the <b>MCRA</b> shows the set of security capabilities, how they fit together and what covers each one, so whatever stays blank is the gap. The <b>MCSB</b> measures whether what exists is well <em>configured</em>, which is a different question. CAF orders the adoption and Well-Architected reviews one workload. <a href=\"https://learn.microsoft.com/en-us/security/adoption/mcra\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Map or benchmark",
    q: "With the set of capabilities now defined, the customer asks for a list of concrete, measurable controls to know whether their cloud is well configured. What do you give them?",
    options: [
      "The cybersecurity reference architectures, which detail how the products integrate",
      "The Zero Trust adoption framework, with its three principles and six pillars",
      "The Microsoft Cloud Security Benchmark, which Defender for Cloud evaluates continuously",
      "The shared responsibility model, to delimit what the provider controls and what the customer does",
    ],
    correct: 2,
    explain: "Concrete, <b>measurable</b> controls is the definition of the <b>MCSB</b>: mapped to CIS and NIST, assigned by default in Defender for Cloud and evaluated automatically, including over connected AWS and GCP. The MCRA gives the capability map but not an evaluable list, Zero Trust gives principles, and the shared responsibility model splits who does what. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The access is already legitimate",
    q: "A salesperson who has handed in their resignation downloads the full customer portfolio they can legitimately reach through their role. What addresses this risk?",
    options: [
      "Requiring phishing-resistant MFA to reach the customer management system",
      "Withdrawing system access when the resignation is received, through an automated leaver process",
      "Insider risk management, which scores the employee's behaviour",
      "A conditional access policy limiting access to the organisation's offices",
    ],
    correct: 2,
    explain: "No access control stops it, because <b>the access is correct</b>: it is their job. What addresses this threat is looking at <b>behaviour</b> rather than permissions, and that is <b>insider risk management</b>, which combines signals — unusual download volume, resignation submitted, movement to personal storage — to raise a case. Hardening authentication or location answers an external threat. <a href=\"https://learn.microsoft.com/en-us/purview/insider-risk-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Coming in through the trusted door",
    q: "After a high-profile incident in which an attacker compromised a widely used library, management asks what the organisation does about that kind of attack. What does the design capture?",
    options: [
      "Composition analysis, provenance and signing, with governance of third-party access",
      "A WAF with managed rules in front of every application using third-party libraries",
      "Banning the use of open source libraries in the organisation's critical applications",
      "Increasing the frequency of vulnerability scanning on the machines where they run",
    ],
    correct: 0,
    explain: "The supply chain comes in through something you <b>already trust</b>, so the defence sits in the build: <b>composition analysis</b> to know what gets pulled in, <b>provenance and signing</b> to know the artefact is the one that was built, and governance of vendor and tooling access. Banning open source is not realistic, and the WAF and machine scanning act once the component is already inside. <a href=\"https://learn.microsoft.com/en-us/azure/security/develop/secure-supply-chain\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "AI is not an exception",
    q: "A team deploys an AI workload as a proof of concept and asks to sit outside the usual governance \"until we decide whether it goes ahead\". What do you answer?",
    options: [
      "That it is reasonable while it processes no production data, reviewing it when it does",
      "That the MCSB controls apply to it like any workload, plus its own on top",
      "That it can stay outside if deployed in an isolated subscription with no connection to the rest",
      "That a governance framework specific to AI is needed before any control can be applied",
    ],
    correct: 1,
    explain: "The classic design mistake is treating AI as an experiment outside governance. An AI workload is a workload: the <b>MCSB controls</b> apply — identity with no local keys, private endpoint, data protection, logging, posture — and <b>on top</b> come its own, like content filters and prompt shields. There is no need to wait for a new framework: the existing one already covers it. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Controls specific to AI",
    q: "Applying the MCSB to a generative AI workload, which control has no equivalent in a traditional workload and has to be added?",
    options: [
      "Entra ID authentication with managed identities instead of service keys",
      "A private endpoint with public access disabled on the resource hosting the model",
      "Shipping the service's traces to the SIEM to correlate with the rest of the signal",
      "Content filters and shields against direct and indirect prompt injection",
    ],
    correct: 3,
    explain: "The first three are benchmark controls that apply equally to an AI service and to a database. What is <b>specific</b> to AI is that content the model reads can end up directing what it does: <b>prompt injection</b>, which no identity or network measure covers and which is addressed with the service's own filters and shields. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The three principles",
    q: "You review a design where the internal network is treated as trusted and, once inside, services talk to each other without authenticating. Which Zero Trust principle is broken?",
    options: [
      "Assume breach: segment and verify assuming the intrusion has happened",
      "Verify explicitly: multifactor authentication is missing for those services' users",
      "Least privilege: the services hold more permissions than their function needs",
      "None: the model allows trusting the internal network if it is correctly segmented",
    ],
    correct: 0,
    explain: "Treating the internal network as a trust zone is precisely what <b>assume breach</b> denies: you design assuming somebody is already inside, which is why service-to-service traffic is authenticated and encrypted just like traffic from outside. Verify explicitly and least privilege are the other two principles and describe different defects. And the fourth option is the premise Zero Trust came to replace. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "How it gets adopted",
    q: "Management approves \"implementing Zero Trust\" and asks which product to buy and when it will be finished. What do you answer?",
    options: [
      "That it is implemented with Entra ID and conditional access, and is done once every application is covered",
      "That Microsoft Defender XDR is enough, applying the three principles across the estate's signal",
      "That it is a model adopted pillar by pillar and continuously, guided by the adoption framework",
      "That the organisation must migrate fully to the cloud first, since the model does not apply on-premises",
    ],
    correct: 2,
    explain: "Zero Trust is neither a product nor a project with an end date: it is a <b>model</b> adopted by <b>pillars</b> — identities, endpoints, applications, data, infrastructure and networks — and the <b>adoption framework</b> exists precisely to give the order, the milestones and how to measure progress. Conditional access and Defender XDR are important pieces, not the whole implementation. And the model applies to hybrid too. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/adopt/zero-trust-adoption-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Before giving AI to everyone",
    q: "An organisation wants to deploy Copilot for Microsoft 365 to the whole workforce next month. What comes first in the plan?",
    options: [
      "Training the workforce in responsible use of the assistant and publishing an acceptable use policy",
      "Classifying and labelling the content, and fixing the oversharing in SharePoint and OneDrive",
      "Agreeing with the business the list of approved use cases and the expected return of each",
      "Deploying to a pilot group and measuring answer quality before widening the scope",
    ],
    correct: 1,
    explain: "An assistant <b>inherits the source's permissions</b>: if the content is overshared, it spreads that faster and to more people. That is why the prerequisite work is <b>data governance</b> — classify, label and fix permissions — and everything else comes after. Training, use cases and a pilot are legitimate parts of the plan, but none stops somebody reading on day one what they should not. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The AI already in use",
    q: "Preparing the AI adoption strategy, you discover several teams already use unapproved AI tools with internal documents. What does the strategy capture?",
    options: [
      "Blocking every AI tool by category in web filtering until the plan is finished",
      "An internal communication reminding people that only approved tools may be used",
      "Accepting the existing use and auditing it once the adoption strategy is published",
      "Discovering the real usage with Defender for Cloud Apps, and deciding from that data",
    ],
    correct: 3,
    explain: "Unapproved AI is <b>shadow IT</b> and is handled the same way: first <b>discover</b> what is used and at what volume — Defender for Cloud Apps gives that from the traffic — and with that data decide what gets sanctioned, what gets replaced with a corporate alternative and what gets blocked. Blocking blind pushes usage into channels with no visibility, and a memo does not change behaviour on its own. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Organisation or workload",
    q: "A customer asks you to review whether one application's design balances security, reliability and cost well. Which framework do you apply?",
    options: [
      "The Cloud Adoption Framework, which covers the full cloud adoption journey",
      "The Microsoft Cloud Security Benchmark, which evaluates the workload's controls",
      "The Well-Architected Framework, which reviews a workload and makes its trade-offs explicit",
      "The cybersecurity reference architectures, which show how the capabilities fit together",
    ],
    correct: 2,
    explain: "\"One application\" and \"balances\" are the two tells for the <b>Well-Architected Framework</b>, which reviews a <b>workload</b> through its pillars and forces the <b>trade-offs</b> into the open: hardening security almost always costs money, performance or operational convenience. The <b>CAF</b> looks at the organisation and its adoption, MCSB measures configuration and MCRA maps capabilities. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The explicit trade-off",
    q: "In a Well-Architected review, the team proposes hardening a workload with controls that add latency and cost. What is expected of the architect?",
    options: [
      "Applying the controls anyway, because security takes priority over the other pillars",
      "Documenting the trade-off and taking it to the workload owner for decision",
      "Dropping any control that degrades performance and looking for alternatives with no impact",
      "Applying only the controls with no additional cost and leaving the rest for next year",
    ],
    correct: 1,
    explain: "Well-Architected does not say security always wins: it says the <b>trade-offs exist</b> and that a mature design <em>makes them explicit</em> rather than pretending they are not there. The architect measures the impact on latency and cost, sets it next to the risk being reduced, and takes the decision to whoever owns the workload. Applying regardless, dropping regardless, or filtering by cost are three ways of not deciding. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Every team doing its own thing",
    q: "In an organisation with forty teams deploying into Azure, each configures security to its own taste and the result is uneven. What do you recommend?",
    options: [
      "A best practice guide published by the security team, with a review before each deployment",
      "A monthly audit of the subscriptions with a deviation report for each team",
      "Mandatory Azure security training for every development team in the organisation",
      "Management groups with Azure Policy initiatives and landing zones for what is new",
    ],
    correct: 3,
    explain: "An uneven result across forty teams is not fixed by asking them to remember: it is fixed by putting the <b>guardrails in the platform</b>. <b>Azure Policy</b> initiatives assigned at <b>management groups</b> apply to every subscription, present and future, and <b>landing zones</b> make new things compliant from birth. The guide, the audit and the training all depend on each team complying. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Who is answerable for what",
    q: "After an incident, nobody knows who was supposed to configure an application's logging: neither the product team, nor platform, nor security takes responsibility. What is missing?",
    options: [
      "A responsibility model like the CAF's, with a workload owner and defined functions",
      "An Azure policy enabling diagnostic logging on every resource in the organisation",
      "A centralised Log Analytics workspace all teams send their logs to",
      "A clause in the incident management procedure naming a responsible person when each case opens",
    ],
    correct: 0,
    explain: "The defect is not technical but one of <b>governance</b>: there is nobody to hold accountable. The <b>CAF</b> defines security functions and a <b>workload owner</b>, so every decision has an owner before the incident. The policy and the workspace solve this specific case and leave the problem untouched, and naming somebody after it has happened is by definition too late. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/teams-roles\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Why the management group",
    q: "You want to guarantee that every Azure subscription, including ones created next year, has the Defender plans and centralised logging enabled. How is that assured?",
    options: [
      "A subscription onboarding procedure the platform team runs at each creation",
      "Azure Policy initiatives with DeployIfNotExists at the management group",
      "An infrastructure-as-code template each team uses when creating a new subscription",
      "A quarterly review of existing subscriptions, remediating the ones that do not comply",
    ],
    correct: 1,
    explain: "\"Including ones created next year\" is the tell for the <b>management group</b>: an assignment there reaches subscriptions that <em>do not yet exist</em>, and with <b>DeployIfNotExists</b> the configuration deploys itself rather than only being audited. The manual procedure and the template depend on somebody remembering, and a quarterly review remediates after the gap has been open for three months. <a href=\"https://learn.microsoft.com/en-us/azure/governance/management-groups/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What separates a landing zone",
    q: "Designing the landing zones, a team proposes putting the identity, connectivity and management subscriptions alongside the application ones to keep it simple. What do you point out?",
    options: [
      "That it is reasonable if they all sit under the same management group with the same policies",
      "That it is reasonable as long as each application has its own well-defined resource group",
      "Platform and workload are separated: different lifecycle, permissions and policies",
      "That it only matters once the organisation passes a certain number of active subscriptions",
    ],
    correct: 2,
    explain: "The reference design separates the <b>platform</b> subscriptions — identity, management, connectivity — from the <b>workload</b> ones because they have different lifecycles, owners and policy needs: whoever deploys an application must not be able to touch the hub network or the log store. Merging them trades that separation for convenience, and resource groups do not replace it. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "A gate at the end",
    q: "In one organisation, security reviews each application at a single gate before production, and the team complains it always arrives late and blocks releases. What do you propose?",
    options: [
      "Spreading automatic controls across the lifecycle, instead of a single gate",
      "Bringing the security review forward two weeks so there is time to fix what it finds",
      "Adding people to the security team so the final review is resolved faster",
      "Letting non-critical applications skip the review and reserving it for the critical ones",
    ],
    correct: 0,
    explain: "A gate at the end concentrates every finding at the most expensive moment to fix them, which is why it always blocks. <b>DevSecOps</b> spreads <b>automatic</b> controls across the lifecycle — modelling at design, scanning in the code and the pull request, dependencies at build, policy at deployment — so each problem is found where it is cheap. Moving or reinforcing the gate does not change its nature. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/devsecops-controls\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Making the control count",
    q: "The pipeline's security scan has been producing findings nobody acts on for months, and releases carry on regardless. Which process change fixes it?",
    options: [
      "Sending a weekly summary of open findings to each development team's manager",
      "Increasing the scan's sensitivity so no relevant finding slips through",
      "Having a finding above the agreed threshold break the build, with a documented exception",
      "Moving the findings into the team's issue tracker so they enter their planning",
    ],
    correct: 2,
    explain: "A warning that stops nothing becomes noise, and noise does not get read. What makes the control count is that a finding above the agreed threshold <b>breaks the build</b>, with a <b>documented exception path with an owner</b> for justified cases. More sensitivity produces more noise, and the weekly summary and the issue tracker still depend on somebody prioritising. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/devsecops-controls\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["best-practices"] = QUIZ_DATA;
