// Question bank for the module: best practices and priorities (SC-100, domain 1).
// Every explanation ends with a link to the official Microsoft Learn documentation.

var QUIZ_DATA = [
  {
    tag: "Where the priority comes from",
    q: "A customer asks for a security strategy and hands over a report with eight hundred vulnerabilities. Where does the design start?",
    options: [
      "With the report's critical vulnerabilities, which are the ones an attacker would exploit first",
      "With an analysis of the most frequent threats in the customer's sector",
      "By identifying the critical business processes and the assets they depend on",
      "By comparing the current posture with that of similar organisations in size and sector",
    ],
    correct: 2,
    explain: "The strategy does not come from a catalogue of threats but from <b>what the business needs to keep running</b>. First the critical processes and their assets; then which threats put <em>those</em> assets at risk, and from that the priority of controls. Ordering by technical severity treats a critical in a test environment and a medium on the road to the billing system exactly the same. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Who sets the objective",
    q: "Designing the protection of a billing application, the security team proposes a nightly daily backup. What is missing before accepting that design?",
    options: [
      "Knowing the RPO and RTO the business accepts for that application",
      "Checking that the backup storage has customer-managed key encryption enabled",
      "Verifying the nightly window does not clash with other applications' batch processes",
      "Deciding how many backups are kept and for how long before being deleted",
    ],
    correct: 0,
    explain: "A daily backup means accepting the loss of up to <b>twenty-four hours</b> of billing, and that is not security's call: the <b>business</b> makes it with its <b>RPO</b>, just as it sets with the <b>RTO</b> how long it can be down. Without those two numbers the design is a guess. Encryption, window and retention are later decisions, and all of them depend on the first. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Backups that survive the attacker",
    q: "The backup design for a critical environment is being reworked on the assumption that the attacker will obtain administrator credentials. Which TWO measures does the design include?",
    options: [
      "Increasing backup frequency from daily to every four hours, to reduce data loss",
      "Immutable backups, with soft delete and deletion protected by multifactor authentication",
      "Encrypting the backups with a customer-managed key held in Key Vault",
      "Separation of duties: whoever administers the workload does not administer its backup vault",
    ],
    correct: [1, 3],
    explain: "The stem's premise is that the attacker <b>holds permissions</b>, and against that frequency and encryption do nothing: they could delete the backups anyway. What saves them is the platform <b>not allowing deletion</b> — immutability, soft delete, MFA-protected deletion — and the workload's credentials <b>not working</b> on the vault. Encryption protects confidentiality, which is not the risk here. <a href=\"https://learn.microsoft.com/en-us/azure/backup/backup-azure-security-feature\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Green backups that do not restore",
    q: "A customer shows a dashboard with twelve months of successful backups and not a single failure. What do you ask before accepting their recovery capability?",
    options: [
      "Whether the backups are replicated to a geographically distant second region",
      "Whether the backup vault has customer-managed key encryption enabled",
      "Whether the configured retention covers the period the sector regulation requires",
      "When the last restore was, and whether it met the committed RTO",
    ],
    correct: 3,
    explain: "A green backup only proves the process finished, not that the data is usable or that the business comes back in time. The question separating a real plan from a pretty dashboard is <b>when the last restore was</b> and whether it met the <b>RTO</b>. Replication, encryption and retention are good properties of a backup that may never have been tested. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where to start against ransomware",
    q: "Management asks for a ransomware plan and wants to know what gets tackled first, with budget for a single line of work this quarter. Which one do you choose?",
    options: [
      "Deploying EDR across the estate and enabling attack surface reduction on the clients",
      "Securing the ability to recover: immutable, isolated backups with a tested restore",
      "Hardening email, which is where most campaigns of this type get in",
      "Training the whole organisation with quarterly phishing simulation campaigns",
    ],
    correct: 1,
    explain: "Microsoft's order is <b>recover, limit the damage, make entry harder</b>, and it is deliberately counter-intuitive. Recovery goes first because it is the only thing that guarantees the business survives <em>even if prevention fails</em>, and it takes away the attacker's leverage. EDR, email and training are the next phases, not the first. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase1\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What turns an incident into a catastrophe",
    q: "With recovery already handled, the customer asks which line of work stops one compromised machine ending in the whole organisation being encrypted. Which is it?",
    options: [
      "Segmenting the network into more zones and filtering traffic between them with an internal firewall",
      "Shortening detection time with more analytics rules and extended SOC coverage hours",
      "Privileged access: PIM, dedicated workstations, LAPS and separated administration planes",
      "Increasing backup frequency so the restore point sits closer in time",
    ],
    correct: 2,
    explain: "What turns a compromised machine into an encrypted organisation is reaching <b>administrative credentials</b> from it. That is why the second phase is <b>privileged access</b>: time-bound activation in PIM, dedicated workstations, unique local passwords with LAPS, and separated planes. Segmentation helps, detection shortens the damage, and more backups do not limit the blast radius. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Patching without breaking",
    q: "The platform team wants to apply every security update the day it is published, across the whole server estate. What do you recommend?",
    options: [
      "Deployment rings with a pilot group and phases, plus a fast lane for what is actively exploited",
      "Applying them all immediately, since the risk of not patching always beats that of a regression",
      "Systematically delaying them thirty days so others find the regressions first",
      "Applying only the criticals immediately and leaving the rest for the quarterly maintenance window",
    ],
    correct: 0,
    explain: "A mature design does not choose between speed and stability: it combines them with <b>deployment rings</b> — pilot first, then production in phases — and a documented <b>fast lane</b> for vulnerabilities actually being exploited. Applying everything at once risks a global outage; always waiting thirty days leaves the urgent open; and pushing non-criticals to a quarter accumulates debt. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What cannot be patched",
    q: "An indispensable legacy system has a known vulnerability and the vendor will publish no fix. What does the design capture?",
    options: [
      "Accepting and documenting the risk, since no vendor fix is available",
      "Retiring the system immediately and replacing it with a fully vendor-supported alternative product",
      "Applying a later version's update even though the vendor does not support it",
      "Compensating mitigation — isolation and filtering — with a planned retirement and its date",
    ],
    correct: 3,
    explain: "\"Indispensable\" rules out retiring it today and \"no fix\" rules out patching it, but simply accepting the risk is not a design. What is expected is <b>compensating mitigation</b> — segment, filter, restrict who reaches it, watch it closely — together with a <b>retirement plan with a date</b>, so the exception does not become permanent. Installing unsupported patches adds a different risk. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-posture-vulnerability-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Finding the gap",
    q: "A customer has bought security tools without a plan and wants to know which capabilities they are still missing. What do you use to answer?",
    options: [
      "The Microsoft Cloud Security Benchmark, checking control by control what is not met",
      "The cybersecurity reference architectures, to map capabilities and see the gaps",
      "The Cloud Adoption Framework, following its adoption journey from the strategy phase",
      "The Well-Architected Framework, reviewing each workload and its design trade-offs",
    ],
    correct: 1,
    explain: "The question is \"<em>which capabilities am I missing</em>\", and that is the map: the <b>MCRA</b> shows the set of security capabilities, how they fit together and what covers each one, so whatever stays blank is the gap. The <b>MCSB</b> measures whether what exists is well <em>configured</em>, which is a different question. CAF orders the adoption and Well-Architected reviews one workload. <a href=\"https://learn.microsoft.com/en-us/security/adoption/mcra\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Map or benchmark",
    q: "With the set of capabilities now defined, the customer asks for a list of concrete, measurable controls to know whether their cloud is well configured. What do you give them?",
    options: [
      "The cybersecurity reference architectures, which detail how the products integrate",
      "The Zero Trust adoption framework, with its three principles and six pillars",
      "The Microsoft Cloud Security Benchmark, which Defender for Cloud evaluates continuously",
      "The shared responsibility model, to delimit what the provider controls and what the customer does",
    ],
    correct: 2,
    explain: "Concrete, <b>measurable</b> controls is the definition of the <b>MCSB</b>: mapped to CIS and NIST, assigned by default in Defender for Cloud and evaluated automatically, including over connected AWS and GCP. The MCRA gives the capability map but not an evaluable list, Zero Trust gives principles, and the shared responsibility model splits who does what. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The access is already legitimate",
    q: "A salesperson who has handed in their resignation downloads the full customer portfolio they can legitimately reach through their role. What addresses this risk?",
    options: [
      "Requiring phishing-resistant MFA to reach the customer management system",
      "Withdrawing system access when the resignation is received, through an automated leaver process",
      "Insider risk management, which scores the employee's behaviour",
      "A conditional access policy limiting access to the organisation's offices",
    ],
    correct: 2,
    explain: "No access control stops it, because <b>the access is correct</b>: it is their job. What addresses this threat is looking at <b>behaviour</b> rather than permissions, and that is <b>insider risk management</b>, which combines signals — unusual download volume, resignation submitted, movement to personal storage — to raise a case. Hardening authentication or location answers an external threat. <a href=\"https://learn.microsoft.com/en-us/purview/insider-risk-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Coming in through the trusted door",
    q: "After a high-profile incident in which an attacker compromised a widely used library, management asks what the organisation does about that kind of attack. What does the design capture?",
    options: [
      "Composition analysis, provenance and signing, with governance of third-party access",
      "A WAF with managed rules in front of every application using third-party libraries",
      "Banning the use of open source libraries in the organisation's critical applications",
      "Increasing the frequency of vulnerability scanning on the machines where they run",
    ],
    correct: 0,
    explain: "The supply chain comes in through something you <b>already trust</b>, so the defence sits in the build: <b>composition analysis</b> to know what gets pulled in, <b>provenance and signing</b> to know the artefact is the one that was built, and governance of vendor and tooling access. Banning open source is not realistic, and the WAF and machine scanning act once the component is already inside. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/sfi/protect-software-supply-chain\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "AI is not an exception",
    q: "A team deploys an AI workload as a proof of concept and asks to sit outside the usual governance \"until we decide whether it goes ahead\". What do you answer?",
    options: [
      "That it is reasonable while it processes no production data, reviewing it when it does",
      "That the MCSB controls apply to it like any workload, plus its own on top",
      "That it can stay outside if deployed in an isolated subscription with no connection to the rest",
      "That a governance framework specific to AI is needed before any control can be applied",
    ],
    correct: 1,
    explain: "The classic design mistake is treating AI as an experiment outside governance. An AI workload is a workload: the <b>MCSB controls</b> apply — identity with no local keys, private endpoint, data protection, logging, posture — and <b>on top</b> come its own, like content filters and prompt shields. There is no need to wait for a new framework: the existing one already covers it. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Controls specific to AI",
    q: "Applying the MCSB to a generative AI workload, which control has no equivalent in a traditional workload and has to be added?",
    options: [
      "Entra ID authentication with managed identities instead of service keys",
      "A private endpoint with public access disabled on the resource hosting the model",
      "Shipping the service's traces to the SIEM to correlate with the rest of the signal",
      "Content filters and shields against direct and indirect prompt injection",
    ],
    correct: 3,
    explain: "The first three are benchmark controls that apply equally to an AI service and to a database. What is <b>specific</b> to AI is that content the model reads can end up directing what it does: <b>prompt injection</b>, which no identity or network measure covers and which is addressed with the service's own filters and shields. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The three principles",
    q: "You review a design where the internal network is treated as trusted and, once inside, services talk to each other without authenticating. Which Zero Trust principle is broken?",
    options: [
      "Assume breach: segment and verify assuming the intrusion has happened",
      "Verify explicitly: multifactor authentication is missing for those services' users",
      "Least privilege: the services hold more permissions than their function needs",
      "None: the model allows trusting the internal network if it is correctly segmented",
    ],
    correct: 0,
    explain: "Treating the internal network as a trust zone is precisely what <b>assume breach</b> denies: you design assuming somebody is already inside, which is why service-to-service traffic is authenticated and encrypted just like traffic from outside. Verify explicitly and least privilege are the other two principles and describe different defects. And the fourth option is the premise Zero Trust came to replace. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "How it gets adopted",
    q: "Management approves \"implementing Zero Trust\" and asks which product to buy and when it will be finished. What do you answer?",
    options: [
      "That it is implemented with Entra ID and conditional access, and is done once every application is covered",
      "That Microsoft Defender XDR is enough, applying the three principles across the estate's signal",
      "That it is a model adopted pillar by pillar and continuously, guided by the adoption framework",
      "That the organisation must migrate fully to the cloud first, since the model does not apply on-premises",
    ],
    correct: 2,
    explain: "Zero Trust is neither a product nor a project with an end date: it is a <b>model</b> adopted by <b>pillars</b> — identities, endpoints, applications, data, infrastructure and networks — and the <b>adoption framework</b> exists precisely to give the order, the milestones and how to measure progress. Conditional access and Defender XDR are important pieces, not the whole implementation. And the model applies to hybrid too. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/adopt/zero-trust-adoption-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Before giving AI to everyone",
    q: "An organisation wants to deploy Copilot for Microsoft 365 to the whole workforce next month. What comes first in the plan?",
    options: [
      "Training the workforce in responsible use of the assistant and publishing an acceptable use policy",
      "Classifying and labelling the content, and fixing the oversharing in SharePoint and OneDrive",
      "Agreeing with the business the list of approved use cases and the expected return of each",
      "Deploying to a pilot group and measuring answer quality before widening the scope",
    ],
    correct: 1,
    explain: "An assistant <b>inherits the source's permissions</b>: if the content is overshared, it spreads that faster and to more people. That is why the prerequisite work is <b>data governance</b> — classify, label and fix permissions — and everything else comes after. Training, use cases and a pilot are legitimate parts of the plan, but none stops somebody reading on day one what they should not. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The AI already in use",
    q: "Preparing the AI adoption strategy, you discover several teams already use unapproved AI tools with internal documents. What does the strategy capture?",
    options: [
      "Blocking every AI tool by category in web filtering until the plan is finished",
      "An internal communication reminding people that only approved tools may be used",
      "Accepting the existing use and auditing it once the adoption strategy is published",
      "Discovering the real usage with Defender for Cloud Apps, and deciding from that data",
    ],
    correct: 3,
    explain: "Unapproved AI is <b>shadow IT</b> and is handled the same way: first <b>discover</b> what is used and at what volume — Defender for Cloud Apps gives that from the traffic — and with that data decide what gets sanctioned, what gets replaced with a corporate alternative and what gets blocked. Blocking blind pushes usage into channels with no visibility, and a memo does not change behaviour on its own. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Organisation or workload",
    q: "A customer asks you to review whether one application's design balances security, reliability and cost well. Which framework do you apply?",
    options: [
      "The Cloud Adoption Framework, which covers the full cloud adoption journey",
      "The Microsoft Cloud Security Benchmark, which evaluates the workload's controls",
      "The Well-Architected Framework, which reviews a workload and makes its trade-offs explicit",
      "The cybersecurity reference architectures, which show how the capabilities fit together",
    ],
    correct: 2,
    explain: "\"One application\" and \"balances\" are the two tells for the <b>Well-Architected Framework</b>, which reviews a <b>workload</b> through its pillars and forces the <b>trade-offs</b> into the open: hardening security almost always costs money, performance or operational convenience. The <b>CAF</b> looks at the organisation and its adoption, MCSB measures configuration and MCRA maps capabilities. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The explicit trade-off",
    q: "In a Well-Architected review, the team proposes hardening a workload with controls that add latency and cost. What is expected of the architect?",
    options: [
      "Applying the controls anyway, because security takes priority over the other pillars",
      "Documenting the trade-off and taking it to the workload owner for decision",
      "Dropping any control that degrades performance and looking for alternatives with no impact",
      "Applying only the controls with no additional cost and leaving the rest for next year",
    ],
    correct: 1,
    explain: "Well-Architected does not say security always wins: it says the <b>trade-offs exist</b> and that a mature design <em>makes them explicit</em> rather than pretending they are not there. The architect measures the impact on latency and cost, sets it next to the risk being reduced, and takes the decision to whoever owns the workload. Applying regardless, dropping regardless, or filtering by cost are three ways of not deciding. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Every team doing its own thing",
    q: "In an organisation with forty teams deploying into Azure, each configures security to its own taste and the result is uneven. What do you recommend?",
    options: [
      "A best practice guide published by the security team, with a review before each deployment",
      "A monthly audit of the subscriptions with a deviation report for each team",
      "Mandatory Azure security training for every development team in the organisation",
      "Management groups with Azure Policy initiatives and landing zones for what is new",
    ],
    correct: 3,
    explain: "An uneven result across forty teams is not fixed by asking them to remember: it is fixed by putting the <b>guardrails in the platform</b>. <b>Azure Policy</b> initiatives assigned at <b>management groups</b> apply to every subscription, present and future, and <b>landing zones</b> make new things compliant from birth. The guide, the audit and the training all depend on each team complying. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Who is answerable for what",
    q: "After an incident, nobody knows who was supposed to configure an application's logging: neither the product team, nor platform, nor security takes responsibility. What is missing?",
    options: [
      "A responsibility model like the CAF's, with a workload owner and defined functions",
      "An Azure policy enabling diagnostic logging on every resource in the organisation",
      "A centralised Log Analytics workspace all teams send their logs to",
      "A clause in the incident management procedure naming a responsible person when each case opens",
    ],
    correct: 0,
    explain: "The defect is not technical but one of <b>governance</b>: there is nobody to hold accountable. The <b>CAF</b> defines security functions and a <b>workload owner</b>, so every decision has an owner before the incident. The policy and the workspace solve this specific case and leave the problem untouched, and naming somebody after it has happened is by definition too late. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/teams-roles\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Why the management group",
    q: "You want to guarantee that every Azure subscription, including ones created next year, has the Defender plans and centralised logging enabled. How is that assured?",
    options: [
      "A subscription onboarding procedure the platform team runs at each creation",
      "Azure Policy initiatives with DeployIfNotExists at the management group",
      "An infrastructure-as-code template each team uses when creating a new subscription",
      "A quarterly review of existing subscriptions, remediating the ones that do not comply",
    ],
    correct: 1,
    explain: "\"Including ones created next year\" is the tell for the <b>management group</b>: an assignment there reaches subscriptions that <em>do not yet exist</em>, and with <b>DeployIfNotExists</b> the configuration deploys itself rather than only being audited. The manual procedure and the template depend on somebody remembering, and a quarterly review remediates after the gap has been open for three months. <a href=\"https://learn.microsoft.com/en-us/azure/governance/management-groups/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What separates a landing zone",
    q: "Designing the landing zones, a team proposes putting the identity, connectivity and management subscriptions alongside the application ones to keep it simple. What do you point out?",
    options: [
      "That it is reasonable if they all sit under the same management group with the same policies",
      "That it is reasonable as long as each application has its own well-defined resource group",
      "Platform and workload are separated: different lifecycle, permissions and policies",
      "That it only matters once the organisation passes a certain number of active subscriptions",
    ],
    correct: 2,
    explain: "The reference design separates the <b>platform</b> subscriptions — identity, management, connectivity — from the <b>workload</b> ones because they have different lifecycles, owners and policy needs: whoever deploys an application must not be able to touch the hub network or the log store. Merging them trades that separation for convenience, and resource groups do not replace it. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "A gate at the end",
    q: "In one organisation, security reviews each application at a single gate before production, and the team complains it always arrives late and blocks releases. What do you propose?",
    options: [
      "Spreading automatic controls across the lifecycle, instead of a single gate",
      "Bringing the security review forward two weeks so there is time to fix what it finds",
      "Adding people to the security team so the final review is resolved faster",
      "Letting non-critical applications skip the review and reserving it for the critical ones",
    ],
    correct: 0,
    explain: "A gate at the end concentrates every finding at the most expensive moment to fix them, which is why it always blocks. <b>DevSecOps</b> spreads <b>automatic</b> controls across the lifecycle — modelling at design, scanning in the code and the pull request, dependencies at build, policy at deployment — so each problem is found where it is cheap. Moving or reinforcing the gate does not change its nature. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/develop/secure-devops-environments-zero-trust\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Making the control count",
    q: "The pipeline's security scan has been producing findings nobody acts on for months, and releases carry on regardless. Which process change fixes it?",
    options: [
      "Sending a weekly summary of the open findings to each development team's engineering manager",
      "Increasing the scan's sensitivity so no relevant finding slips through",
      "Having a finding above the agreed threshold break the build, with a documented exception",
      "Moving the findings into the team's issue tracker so they enter their planning",
    ],
    correct: 2,
    explain: "A warning that stops nothing becomes noise, and noise does not get read. What makes the control count is that a finding above the agreed threshold <b>breaks the build</b>, with a <b>documented exception path with an owner</b> for justified cases. More sensitivity produces more noise, and the weekly summary and the issue tracker still depend on somebody prioritising. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/develop/secure-devops-environments-zero-trust\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What gets protected first",
    q: "Leadership asks for a security strategy and the technical team proposes starting by hardening the systems with the most detected vulnerabilities. What do you correct?",
    options: [
      "Nothing: the vulnerability count is the objective measure of risk and orders the work well",
      "That the oldest systems should come first, as they tend to concentrate uncorrected defects",
      "That priority comes from business impact if the system fails or leaks, not from the defect count",
      "That the asset inventory must be completed first and only then should the order be decided",
    ],
    correct: 2,
    explain: "A resiliency strategy starts with the business, not the scanner. The first step is identifying the <b>critical processes</b> — the ones that cost money, reputation or lives when they stop — and the assets they depend on, and from there deciding where to invest. A system with forty vulnerabilities supporting nothing important comes after one with two that carries billing. Ordering by defect count or by age optimises a technical metric, not risk. And the inventory is a necessary step, but on its own it does not prioritise: criticality comes from the business. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Restoring is not recovering",
    q: "A customer has verified daily backups of every system and considers their continuity plan covered. In an exercise they take eleven days to get back into operation. What was missing from the design?",
    options: [
      "Testing full service recovery, with dependency order and times measured against the objective",
      "Increasing backup frequency, since a daily backup implies losing up to twenty-four hours of data",
      "Encrypting the backups with a customer key so restoration could be performed in any region",
      "Keeping the backups longer, so they could return to a point before the incident began",
    ],
    correct: 0,
    explain: "Having backups answers the recovery point objective — how much data I lose — but the exercise failed the recovery <b>time</b> objective: how long until I am operating again. And that depends on things a backup does not solve: what order systems come up in, whether identity is available before the applications that depend on it, whether there is capacity to restore into, whether anyone knows how to run the procedure. That is why the plan is <b>tested end to end</b> and timed against the declared objective. Backing up more often improves the other objective, not this one; encrypting and retaining longer do not change the time either. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The two ransomware priorities",
    q: "Leadership approves a limited ransomware budget and asks which two fronts to concentrate it on to cut risk most, per Microsoft's recommendations.",
    options: [
      "Next-generation antivirus on every machine and awareness training for the whole workforce",
      "Internal network segmentation and disk encryption on every machine in the estate",
      "Strengthened mail filtering and a mandatory monthly patch cycle on servers and clients",
      "Backups the attacker cannot destroy, and control of the privileged access that lets them spread",
    ],
    correct: 3,
    explain: "Microsoft organises ransomware work around two questions: <b>if I am encrypted, can I come back?</b> and <b>how far can the attacker reach?</b> The first is answered with backups protected from the administrator themselves — immutable, with soft delete, outside the scope of whoever administers production — and with tested recovery. The second by bounding the privileged access that turns one compromised machine into the whole domain. Antivirus, training, segmentation, filtering and patching are useful controls and come afterwards, but none of them decides whether you survive the attack once it happens. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase1\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The patch that cannot be applied",
    q: "A critical industrial system runs on an unsupported operating system version. The vendor certifies no later version and replacing it will take two years. What do you recommend meanwhile?",
    options: [
      "Apply the later version's updates even without vendor backing, since the risk of not patching is greater",
      "Compensating mitigation — isolate, filter and monitor closely — with a planned retirement and a date",
      "Accept and document the risk, since without a vendor update there is no control that can be applied",
      "Retire the system immediately and replace it with a supported alternative, even if production stops",
    ],
    correct: 1,
    explain: "When you cannot patch, the answer is neither to give up nor to break the system: it is to <b>compensate and set a date</b>. Compensating means reducing exposure with what you do control — segmenting the network so only those who should can reach it, filtering protocols, restricting accounts, increasing monitoring on that asset — and setting a date means the mitigation is temporary and there is an approved retirement plan, with budget and an owner. Applying unsupported updates can break the process and void the warranty. Accepting the risk with no controls is abdication. And stopping production today is disproportionate against a two-year plan. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Patching without stopping the service",
    q: "The operations team resists monthly patching because every cycle causes production incidents. Security insists the deadline is met. What design resolves the conflict?",
    options: [
      "Apply patches directly in production outside working hours, accepting the risk of an overnight incident",
      "Reduce patching to critical bulletins, leaving the rest for the system's annual maintenance window",
      "Deployment rings: a pilot group first, then the rest in phases, with automated scheduling and a way to roll back",
      "Delegate the patching decision to each owning team, who best understand each update's impact on their system",
    ],
    correct: 2,
    explain: "The conflict is real and has a known design solution: <b>deploy in rings</b>. A small, representative group receives updates first, the outcome is observed for a few days and only then do they advance to the next ring, until the estate is covered; scheduling and reporting come from the update tool and there is a way back if something breaks. That meets the deadline without betting all of production on one day. Patching at night does not reduce the risk, it moves it. Limiting to critical bulletins lets everything else accumulate. And delegating with no framework is how the current situation arose. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What the reference architecture is for",
    q: "An architect uses Microsoft's cybersecurity reference architectures as a design to implement verbatim, and proposes deploying every capability that appears in them.",
    options: [
      "Correct: the reference architectures describe the target state and deploying them fully guarantees coverage",
      "Correct provided it is phased, starting with the identity capabilities and finishing with the data ones",
      "Incorrect: the reference architectures only describe Microsoft products and are of no use in a multi-vendor estate",
      "Incorrect: they are a capability map for placing what you have and spotting gaps, not a shopping list to execute in full",
    ],
    correct: 3,
    explain: "Reference architectures are for <b>orientation</b>: they show which capabilities exist, how they relate and which product covers each, so you can lay what you already have on top and see where the gaps are, where things overlap and what is missing. Treating them as a shopping list leads to deploying capabilities with no requirement behind them, with their cost and operational load. The decision of what to implement comes from the customer's risk, not from the diagram. And it is not true that they only serve Microsoft estates: the capability map is just as useful for placing third-party tools and spotting overlap. <a href=\"https://learn.microsoft.com/en-us/security/adoption/mcra\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The risk that arrives through the supplier",
    q: "The customer has strengthened identity, endpoint and network, but has not looked at how third-party components reach production or what access their managed service providers hold.",
    options: [
      "That is the supply chain gap: verify artifact provenance and bound and monitor supplier access",
      "Not a relevant gap as long as identity and endpoint controls are properly implemented across the estate",
      "Covered by requiring each supplier to hold a current security certification and renewing it annually",
      "Covered by scanning every artifact with the endpoint antivirus before deploying it to production",
    ],
    correct: 0,
    explain: "The three vectors the syllabus names — insider, external and <b>supply chain</b> — need different controls, and the third is frequently forgotten because it does not arrive where the others watch. It has two faces: the <b>code and artifacts</b> arriving from outside, which demand verifying provenance and integrity, signing, and controlling what enters the build; and <b>supplier access</b>, which tends to be privileged, permanent and lightly monitored, and is bounded with time-limited access, approval and auditing. An annual certificate is not a technical control, and antivirus does not detect a legitimate dependency with a backdoor introduced upstream. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/sfi/protect-software-supply-chain\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Three vectors, three controls",
    q: "A customer proposes covering insider risk with the same tools used against external attackers: perimeter filtering, intrusion detection and malicious domain blocking.",
    options: [
      "Sufficient, because a malicious insider ends up using the same techniques as an external attacker",
      "Sufficient if the access logs of users with elevated permissions are additionally reviewed monthly",
      "Not sufficient: the insider is already inside legitimately, so the control watches behaviour",
      "Not sufficient: local administration rights must be removed from every user in the estate",
    ],
    correct: 2,
    explain: "The difference between vectors is the <b>starting point</b>. An external attacker has to get in, so you detect them trying: intrusion, stolen credentials, exploitation. The insider <b>is already inside</b> and uses access that belongs to them, so no perimeter control fires: what gives them away is not intrusion but the <b>pattern</b> — unusual volume, out-of-hours activity, coincidence with leaving the company — and that is insider risk management with DLP and classification. Reviewing logs by hand does not scale, and removing local administration is a good control but does not cover a user abusing what they have legitimately been granted. <a href=\"https://learn.microsoft.com/en-us/purview/insider-risk-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Adopting is not deploying",
    q: "A customer has spent eighteen months deploying Zero Trust controls and cannot get the business to perceive progress or approve further phases. The technical controls work well.",
    options: [
      "Accelerate the technical rollout to reach the target state sooner so the result finally becomes visible",
      "The non-technical part is missing: business scenarios, sponsorship, measurable objectives and communication",
      "Replace the framework with a simpler one, because Zero Trust is too broad for a mid-sized organisation",
      "Start again from identity, the pillar every other control in the model depends on",
    ],
    correct: 1,
    explain: "The Zero Trust adoption framework is explicit that the hard part is not technical. It structures the work into <b>business scenarios</b> — modernise quickly and securely, protect against ransomware, meet regulation — and into four phases repeated per scenario: define strategy with sponsorship, plan with measurable objectives, implement, and <b>govern</b> by communicating progress. When that is missing, the technical rollout advances but nobody outside the team understands what has been gained, which is why further phases are not approved. Accelerating more of the same does not change that perception, and neither is the framework excessive nor does the work need redoing. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/adopt/zero-trust-adoption-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Before switching AI on",
    q: "An organisation wants to adopt generative AI within six months. The security team asks what the first piece of work is, before choosing models or platforms.",
    options: [
      "Choose the platform and model, since every other security decision depends on that technical choice",
      "Define the content filters and prompt shields that will apply to every AI workload",
      "Train the workforce in responsible use, so the main risk — misuse through ignorance — is covered",
      "Get data governance in order: what exists, how it is classified and who can see it, because AI inherits it",
    ],
    correct: 3,
    explain: "Secure AI adoption starts <b>before the AI</b>, with the data. A generative tool that respects permissions creates no new exposure: it <b>reveals the exposure that was already there</b>, because it finds in seconds what previously had to be sought out. So the first job is data governance — discover, classify, label, fix open sharing and over-inherited permissions — and only then are platform, filters and training decided, which are necessary but do not substitute for the above. Starting with the technical choice is building on ground nobody has looked at. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The AI the workforce already uses",
    q: "Before approving any tool, the customer discovers a good part of the workforce already pastes work text into public AI services from the corporate browser. Where do you start?",
    options: [
      "Discover the real usage with the cloud app catalogue, and offer an approved alternative while governing the unapproved one",
      "Block every generative AI service domain at the proxy until an approved corporate tool exists",
      "Publish an internal policy forbidding the use of unapproved AI services and communicate it to the whole workforce",
      "Configure endpoint DLP to block any text pasting into the browser from company applications",
    ],
    correct: 0,
    explain: "This is the shadow AI pattern, and it is handled like any other unapproved usage: first <b>see</b> — cloud app discovery says which services are used, by whom and at what volume — then <b>offer</b> an approved alternative, because people use those tools to get work done and banning them with no substitute pushes usage onto personal phones, where you see nothing. With that in place you can govern: block the worst, allow the rest with DLP over sensitive content. Blocking outright with no alternative, publishing a policy with no controls, or blocking all pasting are answers that do not survive the first month. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/security-features\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What the landing zone solves once",
    q: "Each of the customer's teams creates its own subscriptions and configures network, identity, logging and policy by itself. No two look alike and auditing takes weeks.",
    options: [
      "Publish a written configuration guide and review every new subscription in the architecture meeting before approving it",
      "Audit all subscriptions quarterly with Azure Policy and raise tickets with each team for what fails",
      "Landing zones: the platform hands over the subscription already carrying network, identity, logging and inherited policy",
      "Create a single shared subscription for all teams, so there is only one configuration to maintain",
    ],
    correct: 2,
    explain: "The landing zone idea is that platform decisions are made <b>once</b> and delivered ready-made. The team receives a subscription that is born with its place in the management group hierarchy, its inherited policies, its connectivity, its roles and its log forwarding, so correct configuration does not depend on everyone repeating it properly. A written guide depends on being read and followed; auditing afterwards catches non-compliance once it is deployed and generates constant friction; and a single shared subscription removes the environment and permission separation you need. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Security that does not slow delivery",
    q: "On introducing security controls into the pipelines, development teams complain that every build takes forty minutes longer and many findings are not actionable.",
    options: [
      "Keep every control and accept the cost, because security justifies any impact on delivery time",
      "Tune where each control runs and at what threshold: fast, high-signal checks block; slow ones run apart",
      "Move every control out of the pipeline and run them once a week against the repository's main branch",
      "Leave every control in informational mode, so they never stop a build and do not bother the team",
    ],
    correct: 1,
    explain: "A control the team learns to ignore protects nothing, and that is the DevSecOps lesson the exam is after. The design is about <b>placing each control where it pays</b>: secret scanning and fast, high-signal checks at commit or pull request, where blocking is cheap and the finding is almost always real; heavy, noisy analysis in scheduled runs that feed the backlog without slowing anyone. And the blocking threshold is agreed, with documented exceptions. Accepting the cost outright burns the relationship, moving everything out loses the gate, and leaving everything informational is having no control at all. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/develop/secure-devops-environments-zero-trust\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Security against availability",
    q: "A security measure would clearly reduce intrusion risk, but introduces a single point of failure in a service with a continuous availability requirement. How is this resolved?",
    options: [
      "Security wins: intrusion risk outweighs an outage, and availability can be recovered afterwards",
      "Look for an alternative giving the same control without the single point; otherwise the business decides",
      "Availability wins: any measure that could cause an outage is ruled out by definition",
      "Implement it in passive mode, so it records what it would have blocked but never actually blocks",
    ],
    correct: 1,
    explain: "The Well-Architected pillars <b>compete with each other</b>, and the skill being measured is recognising the conflict and resolving it, not declaring that one always wins. The first move is to look for a design giving the control without the downside: make the component redundant, degrade gracefully, apply the control elsewhere. If none exists, the decision belongs to the <b>business</b>, taken with both risks on the table and in writing. Declaring a default winner — in either direction — is not architecture. And leaving it permanently passive pretends to a control that does not exist. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Two objectives, two designs",
    q: "A service declares a recovery point objective of five minutes and a recovery time objective of eight hours. The team asks what each number implies for the design.",
    options: [
      "Both are covered by one decision: backups every five minutes retained for eight hours in the vault",
      "The first requires a second active region and the second requires increasing existing backup retention",
      "Both refer to the same interval measured differently, so designing for the stricter one is enough",
      "The first requires near-continuous replication; the second allows an unhurried restore, independently",
    ],
    correct: 3,
    explain: "These are two different questions and confusing them produces designs that are either expensive or inadequate. The recovery <b>point</b> objective measures how much data I can lose, and five minutes forces near-continuous replication or very frequent backups. The recovery <b>time</b> objective measures how long I can take to be operating again, and eight hours is generous: it allows restoring and bringing systems up in order without a hot second region. Here the combination is strict on data and relaxed on time, and the design reflects that. Both being strict is a different case, and they are not always strict together. <a href=\"https://learn.microsoft.com/en-us/azure/backup/backup-azure-security-feature\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "From laptop to domain",
    q: "In an exercise, the attacker enters through an unprivileged user's laptop and controls the domain within four hours. Every system was patched and running antivirus.",
    options: [
      "The problem is the escalation path: privileged credentials reused and reachable from general-purpose machines",
      "The problem is the antivirus, which missed the initial payload and should be replaced with a detection and response solution",
      "The problem is network segmentation, and separating servers from user machines onto different networks is enough",
      "The problem is that the user opened the file, corrected with training and periodic phishing simulations",
    ],
    correct: 0,
    explain: "Everything being patched demonstrates exactly the point: modern ransomware does not escalate through vulnerabilities but through <b>credentials</b>. The attacker gets in where they can and hunts in memory and on disk for privileged credentials somebody used there, or local accounts with the same password everywhere, and hops along. That is why the countermeasures are the tiered model, dedicated administration workstations, distinct per-machine local passwords and time-bound privileged access. Antivirus and training reduce the likelihood of initial entry, not escalation; and segmenting helps, but does not stop a valid credential opening the door. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "High-level framework or technical benchmark",
    q: "A customer asks what the difference is between using the cybersecurity reference architectures and using Microsoft's cloud security benchmark, and when each applies.",
    options: [
      "They are the same thing under different names: one is the summarised version of the other for leadership presentations",
      "The architectures apply to Microsoft 365 and the benchmark applies to Azure, so you use them by product",
      "The architectures place capabilities and responsibilities; the benchmark gives testable controls over resources",
      "The benchmark replaces the architectures now that Defender for Cloud assigns it by default",
    ],
    correct: 2,
    explain: "They are used at <b>different moments in the design</b>. The reference architectures are a map: which capabilities exist, how they fit, who answers for each; they orient the conversation and reveal gaps. The <b>benchmark</b> descends to the concrete control: what a resource must satisfy, how it is checked and which controls in other standards it maps to, which is why Defender for Cloud evaluates it automatically. Neither replaces the other: first you decide which capabilities are needed, then you demand the technical control that realises them. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "An AI workload is still a workload",
    q: "The team asks whether an AI workload needs entirely new security controls or whether the same ones as the rest of the Azure estate apply.",
    options: [
      "It needs entirely new controls, because model risks have no equivalent in traditional workloads",
      "The same identity, network, encryption and logging controls apply, plus those specific to the model",
      "Only the model-specific controls apply, since the managed platform fully covers everything else",
      "The same controls apply and nothing more, because an AI service is a platform service like any other",
    ],
    correct: 1,
    explain: "The benchmark treats an AI workload as what it is: a <b>platform service</b> held to the same requirements as the others — identity instead of keys, a private endpoint, encryption with the appropriate key, logging and posture — and <b>additionally</b> the controls that only make sense here: content filters, defence against embedded instructions, governance of the data feeding the model and of what the model produces. You neither discard what you know nor ignore what is new: the two layers add up, and that is the answer the exam is after. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/security-features\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Filtering input and output",
    q: "A public-facing AI application applies content filters to what the user writes. A review asks whether that is enough to cover the inappropriate content risk.",
    options: [
      "Enough: filtering the input stops the model receiving anything that would lead it to generate inappropriate content",
      "Enough if the system message additionally instructs the model to refuse that kind of request explicitly",
      "Not enough: every response has to be logged and reviewed afterwards to catch what the filter let through",
      "Not enough: you filter both directions, because the model can generate inappropriate content from an innocuous prompt",
    ],
    correct: 3,
    explain: "Filtering only the input assumes all the risk comes from what the user asks, and it does not: a model can produce harmful, biased or confidential content from a perfectly normal prompt, or from content embedded in a document it is given to read. That is why Content Safety is applied in <b>both directions</b>, on the prompt and on the response, before the response reaches the user. The system message helps but is the layer the attack tries to go around, and reviewing logs afterwards detects what has already been published. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The three principles, one by one",
    q: "A design requires phishing-resistant MFA and a compliant device for all access, encrypts traffic and segments the network. The team claims it fully covers Zero Trust.",
    options: [
      "Least privilege is missing: the design says who gets in and from where, but not with how many permissions or for how long",
      "Nothing is missing: verifying identity and device and encrypting traffic covers all three principles of the model",
      "Explicit verification is missing, because network location is not being used as a signal in the access decision",
      "Assume breach is missing, because no detection and response solution has been deployed on the estate's servers",
    ],
    correct: 0,
    explain: "Walking the design against the <b>three principles</b> one by one is the exercise the exam asks for. Verify explicitly: covered, identity and device are evaluated on every access. Assume breach: partly covered, there is segmentation and encryption, which is damage containment. <b>Least privilege</b>: nowhere to be found — what the user can do once inside, with which role, permanent or temporary, reviewed by whom — and that is where the gap is. That is the pattern in these questions: the missing principle is usually the one about permissions, because entry controls are the first thing organisations implement. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Who answers for what",
    q: "At a customer, cloud security \"is handled by the platform team\" and nobody knows who decides on posture, who responds to incidents or who approves policy exceptions.",
    options: [
      "A minor problem: as long as the platform team holds the necessary permissions, the decisions get made anyway",
      "Resolved by creating a monthly security committee where everyone agrees the outstanding cloud decisions together",
      "A governance gap: the framework defines roles and responsibilities, and with no owner decisions go unmade",
      "Resolved by contracting a managed service to take on the complete security of the customer's cloud estate",
    ],
    correct: 2,
    explain: "The adoption framework is not only technical: it defines <b>roles and responsibilities</b> because a control with no owner is not operated. You have to name who governs posture and decides the acceptable risk level, who runs detection and responds to incidents, who administers the platform and who approves exceptions and with what expiry. Without that, recommendations stay open and exceptions become permanent. Trusting that decisions \"get made anyway\" is how this state is reached; a monthly committee with no assigned owners distributes blame rather than work; and outsourcing shifts execution, not the responsibility to decide. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/teams-roles\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Evaluating an existing strategy",
    q: "You are asked to evaluate the security strategy of a customer three years into the cloud. They have controls deployed, a trained team and budget. What criteria do you evaluate it against?",
    options: [
      "By comparing their tool inventory against other customers of the same sector and size, to spot what they lack",
      "Against the framework: sponsored strategy, governance with owners, controls aligned to risk, and measurement",
      "By measuring the secure score of their tenants and subscriptions, which summarises the state objectively and comparably",
      "By reviewing the number of incidents over the last twelve months, which indicates whether the deployed controls work",
    ],
    correct: 1,
    explain: "Evaluating a strategy is neither inventorying tools nor reading a number. The framework provides the structure: is there a written <b>strategy</b>, with sponsorship and business objectives behind it? Is there <b>governance</b>, with named owners and exceptions that expire? Do the <b>controls</b> answer this customer's real risk or whatever came in the catalogue? Is progress <b>measured</b> in a way leadership understands? Comparing against other customers ignores that the risk differs. The score is an input, not the evaluation. And counting incidents also measures luck and attacker activity. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The recommendation the customer can sustain",
    q: "A small customer, with two people in IT and no security team, asks for recommendations. The temptation is to propose the same design as for a large enterprise with its own operations centre.",
    options: [
      "Propose the same design, because risk does not depend on organisation size and good practice is universal",
      "Propose only free controls, since a small customer cannot absorb the cost of any additional licensing",
      "Propose the complete design and let the customer decide which parts to implement according to each year's budget",
      "Fit the recommendation to what that customer can operate: prefer managed, automatic capabilities",
    ],
    correct: 3,
    explain: "A recommendation the customer cannot operate does not reduce risk: it produces alerts nobody reads and controls that get switched off at the first incident. Recommending well means accounting for <b>operational capacity</b>, and for a small organisation that means leaning towards the managed and the automatic — detection that responds by itself, policies that remediate, secure defaults — rather than powerful tools that presume an operations centre. This is not lowering security, it is choosing the form that survives. Size is not irrelevant, price is not the criterion, and offloading the whole decision onto the customer is not advising. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Recommending in order",
    q: "You present twenty security recommendations to a customer who can take on five this year. They ask you to say which and why, not to hand them an unordered list to pick from.",
    options: [
      "The five that most reduce risk to their critical processes, saying which scenario each one closes",
      "The five cheapest to implement, maximising the number of recommendations closed with the available budget",
      "The five required by the industry standard that applies to them, leaving the rest until a new obligation arrives",
      "The five Defender for Cloud marks as critical, which is the order the tool itself already computes",
    ],
    correct: 0,
    explain: "The architect's value lies precisely in the <b>order and the justification</b>, not in the list. Prioritising well means crossing what the tool flags with what this customer cannot afford to happen, and explaining each recommendation in terms of <b>which scenario stops being possible</b> once implemented: that is what lets leadership decide and sustain the budget. Ordering by cost optimises the count of closed tasks. Sticking to the standard covers the audit, not the risk. And the tool's severity ignores asset criticality, which is exactly what the customer contributes and the tool does not know. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where the policy goes",
    q: "A policy is approved that must apply to every current subscription and to any created from now on. The team proposes assigning it subscription by subscription for fine-grained control.",
    options: [
      "Correct: assigning per subscription allows the policy's parameters to be adapted to each team's reality",
      "A mistake: assign it at the appropriate management group and let it inherit, future subscriptions included",
      "Correct provided there is a documented process obliging it to be assigned on every new subscription too",
      "A mistake: it must be assigned at the tenant root group, the only scope where inheritance works",
    ],
    correct: 1,
    explain: "This is the basis of landing zone governance: the management group hierarchy exists precisely for this: an assignment at a group <b>inherits</b> downwards and reaches subscriptions that do not yet exist, so the one created tomorrow is born compliant. Assigning one by one turns every new subscription into an opportunity to forget, which is how governance gaps appear. Documenting a manual process does not change that, it only distributes the blame. And the scope need not be the root: you choose the group covering exactly what the policy should reach, which might be production, a business unit or a region. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The same credential everywhere",
    q: "A single service principal with Contributor across every subscription serves the pipelines of all twelve teams. It is convenient to manage and has never caused problems.",
    options: [
      "Acceptable as long as the secret is held in the organisation's vault and rotated automatically every ninety days",
      "Acceptable if every use of that principal is audited and the deployment log is reviewed monthly with the teams",
      "Any compromised pipeline deploys into any subscription: one identity per team and environment, scoped to what it deploys",
      "Better replaced with a single managed identity, removing the secret while keeping the current management convenience",
    ],
    correct: 2,
    explain: "The problem is not the secret, it is the <b>scope</b>. One identity with Contributor everywhere means a failure in the least important pipeline — a compromised dependency, a branch anyone can open, a log leaking a variable — hands over the whole estate. The correct design separates by team and environment, with permissions scoped to what that pipeline actually deploys, and ideally with no secret at all, through workload identity federation. Vaulting and rotating the secret better, or auditing it, does not reduce what its holder achieves; and a single managed identity keeps exactly the same excessive scope. <a href=\"https://learn.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["best-practices"] = QUIZ_DATA;
