var QUIZ_DATA = [
  {
    tag: "Envelope encryption",
    q: "Why does KMS use 'envelope encryption' (encrypting the data with a data key, and that data key with the CMK) instead of encrypting the data directly with the KMS key?",
    options: [
      "Because the KMS Encrypt and Decrypt operations are limited to a 4 KB payload per call",
      "Because a KMS key can only encrypt other keys and takes no application data as input at all",
      "Because HIPAA requires health data to be encrypted under two chained, distinct keys",
      "Because KMS bills per encrypted byte and the data key cuts the billable volume sent",
    ],
    correct: 0,
    explain: "KMS's direct <code>Encrypt</code>/<code>Decrypt</code> operations are capped at ~4 KB of payload. To encrypt large objects you generate a data key (<code>GenerateDataKey</code>), encrypt the data locally with it (no size limit), and send only the small data key to KMS to be encrypted or decrypted — hence the 'envelope'. KMS bills per request, not per byte, and a KMS key can encrypt data, just very little of it. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Envelope encryption",
    q: "After using GenerateDataKey to encrypt a large file locally, what should the application do with the plaintext data key once encryption is finished?",
    options: [
      "Store it next to the encrypted file so you do not have to call KMS to decrypt",
      "Wipe it from memory as soon as encryption ends, keeping only its encrypted copy",
      "Send it back to KMS with ImportKeyMaterial so the service holds it for you",
      "Wrap it in a second, different data key to add one more layer of encryption",
    ],
    correct: 1,
    explain: "<code>GenerateDataKey</code> returns TWO versions: the plaintext data key (used once, then discarded from memory) and the data key encrypted under the KMS key, which is what you store alongside the data. To decrypt, you send the encrypted copy to <code>Decrypt</code>. Keeping the plaintext copy next to the file defeats the encryption entirely, and <code>ImportKeyMaterial</code> is for BYOK, not for escrowing data keys. <a href=\"https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS key types",
    q: "What's the main difference between an AWS managed key (e.g. aws/s3) and a customer managed key (CMK) in KMS?",
    options: [
      "AWS managed keys are free and customer managed ones cost money; otherwise identical",
      "AWS managed keys can be replicated as multi-Region keys and customer managed cannot",
      "Only customer managed keys allow a custom key policy, configurable rotation and deletion",
      "AWS managed keys are asymmetric by default, whereas customer managed keys are always symmetric",
    ],
    correct: 2,
    explain: "AWS managed keys (the <code>aws/</code> prefix) are created and run by AWS for one specific service: mandatory annual rotation, no editable key policy, and no way to disable them or share them across accounts. Customer managed keys give full control — your own key policy, configurable rotation, disable and scheduled deletion — and they are the only kind that supports multi-Region. Both kinds are symmetric by default. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS grants",
    q: "What is a KMS grant used for, instead of modifying the key policy directly?",
    options: [
      "It grants permanent permissions on the key that override whatever the key policy says",
      "It is simply another name for the identity policy that you attach to an IAM role or an IAM user",
      "It is the only valid mechanism to authorize operations on asymmetric and HMAC KMS keys",
      "Delegate temporary permissions on a key programmatically, revocable without editing the policy",
    ],
    correct: 3,
    explain: "Grants are a more granular, dynamic delegation mechanism than the key policy: they are created and retired through the API (<code>CreateGrant</code>, <code>RetireGrant</code>, <code>RevokeGrant</code>) and they are how an AWS service gets temporary access to your key on your behalf (EBS encrypting a volume, for example). They do not replace the key policy — it must allow <code>kms:CreateGrant</code> — and they are not limited to one key type. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/grants.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS multi-Region keys",
    q: "You have a primary Multi-Region KMS key in eu-west-1 replicated to us-east-1. An S3 object was encrypted using the us-east-1 replica. Can it be decrypted using the primary key in eu-west-1?",
    options: [
      "Yes: primary and replicas share the same key material, even though their Key IDs differ",
      "No: each replica is generated with its own key material, entirely independent of the primary",
      "Only if both keys belong to the same account and the object is copied with S3 Replication",
      "Only after creating a third key that combines the material of the primary and the replica",
    ],
    correct: 0,
    explain: "Creating 'identical' KMS keys independently in each Region produces DIFFERENT key material and incompatible ciphertexts. Multi-Region keys, by contrast, are replicas that share the same material: what one encrypts, any other can decrypt, with no re-encryption of the data. That is what makes DR scenarios and multi-Region active applications workable. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS vs CloudHSM",
    q: "A financial services company needs FIPS 140-2 Level 3, exclusive (single-tenant) control of the cryptographic hardware, and the ability to export key material if they migrate providers. Which service fits best?",
    options: [
      "AWS KMS with customer managed keys, which also lets you export the key material",
      "AWS CloudHSM, which gives a dedicated single-tenant HSM and allows key material export",
      "AWS Secrets Manager, which holds cryptographic material and rotates it automatically",
      "Amazon Macie, which classifies sensitive data and manages the keys protecting it",
    ],
    correct: 1,
    explain: "KMS is multi-tenant (with strong isolation guarantees) and NEVER allows key material to be exported: that is its fundamental guarantee. CloudHSM hands you a dedicated HSM cluster, FIPS 140-2 Level 3, with full lifecycle control and key export — in exchange for owning the cluster's operation (high availability, backups, crypto users). Macie classifies data; it does not manage keys. <a href=\"https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Imported key material",
    q: "What limitation do KMS keys with IMPORTED key material (BYOK) have that AWS-generated keys don't?",
    options: [
      "They cannot be used in data encryption operations, only to sign and verify signatures",
      "They can only be used with Amazon S3, not with the other KMS-integrated services",
      "They do not support AWS-managed annual automatic rotation: you rotate them manually",
      "They cannot have their own key policy: they inherit the account default policy",
    ],
    correct: 2,
    explain: "When you import your own material (origin <code>EXTERNAL</code>), AWS cannot regenerate it and therefore offers no annual automatic rotation. You can set an expiration date for the material and rotate on demand with <code>RotateKeyOnDemand</code> by importing fresh material, or create a new key. Otherwise the key behaves like any other: it encrypts data, integrates with services, and has its own key policy. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "External Key Store (XKS)",
    q: "What does a KMS External Key Store (XKS) solve?",
    options: [
      "That KMS generates and hands out keys faster by skipping FIPS validation of the HSM below",
      "It replaces CloudHSM by providing an HSM cluster fully managed by AWS for you",
      "Keeping backup copies of the material of your KMS keys in an encrypted S3 bucket",
      "That key material resides outside AWS, in your own key manager, while using the KMS API",
    ],
    correct: 3,
    explain: "XKS links KMS to an external key manager (on-premises or third-party) through an XKS proxy that you operate: the key material NEVER enters AWS and KMS can neither create nor see it, yet integrated services keep using the key through the standard API. It is the maximum-key-sovereignty option while keeping native AWS integration; it speeds nothing up and does not replace CloudHSM, which lives inside AWS. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/keystore-external.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 Object Lock",
    q: "What's the difference between Governance mode and Compliance mode in S3 Object Lock?",
    options: [
      "Governance allows an override with s3:BypassGovernanceRetention; Compliance allows none",
      "They are synonyms and the name shown depends only on the Region where the bucket is created",
      "Compliance can only be applied on buckets that have versioning explicitly disabled",
      "Governance protects publicly accessible objects and Compliance protects private ones",
    ],
    correct: 0,
    explain: "Both modes implement WORM (Write Once Read Many). <strong>Governance</strong> leaves an escape hatch for principals holding <code>s3:BypassGovernanceRetention</code>, handy for testing retention before committing. <strong>Compliance</strong> is absolute: once the retention period is set, not even the root user can delete the object or shorten the retention until it expires. That is the mode used for strict regulatory regimes such as SEC 17a-4. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Glacier Vault Lock",
    q: "What characterizes a Glacier Vault Lock policy once it is confirmed (locked)?",
    options: [
      "The account administrator can still go on editing it freely at any later point in time",
      "It becomes immutable: no principal, not even the root user, can modify or delete it",
      "It expires automatically after 90 days and must be confirmed again from scratch",
      "It only protects the vault archives whose size is below 1 MB once compressed",
    ],
    correct: 1,
    explain: "Vault Lock is applied in two steps: initiating it puts the policy 'in progress' for 24 hours so you can validate it, and confirming it (<code>CompleteVaultLock</code>) makes it permanent and immutable. Not even the account owner can alter it afterwards, which gives verifiable compliance control — Glacier's counterpart to S3 Object Lock's Compliance mode. <a href=\"https://docs.aws.amazon.com/amazonglacier/latest/dev/vault-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Data integrity",
    q: "To verify that a software artifact (e.g. a downloaded binary) hasn't been altered in transit or tampered with by a third party, which AWS mechanism is most appropriate?",
    options: [
      "S3 Versioning, which keeps each version so you can compare the binary with the prior one",
      "MFA Delete on the bucket, which demands a second factor before overwriting the binary",
      "AWS Signer, which digitally signs the code so that the receiver can verify its integrity",
      "AWS Backup, which hashes each copy and raises an alert when the binary has changed",
    ],
    correct: 2,
    explain: "AWS Signer digitally signs code — Lambda packages, container images in ECR, IoT firmware — managing the keys and the code-signing certificate for you. The receiver validates the signature before executing and detects any change made after publication. Versioning, MFA Delete and Backup protect the stored object from deletion or overwrite, but they attest neither authorship nor artifact integrity. <a href=\"https://docs.aws.amazon.com/signer/latest/developerguide/Welcome.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Lifecycle & retention",
    q: "You need objects in an S3 bucket to move automatically to Glacier Deep Archive after 180 days and be permanently deleted after 7 years, with no manual intervention. What mechanism do you use?",
    options: [
      "S3 Object Lock in Compliance mode, with the retention period set to seven full years",
      "Cross-Region Replication, naming Glacier Deep Archive as the destination storage class",
      "AWS Backup with a daily plan and a lifecycle rule keeping copies for seven years",
      "S3 Lifecycle, with a transition rule at 180 days and an expiration rule at 7 years",
    ],
    correct: 3,
    explain: "S3 Lifecycle rules automate exactly this pattern: <strong>transition</strong> actions that move objects between storage classes by age, and <strong>expiration</strong> actions that delete them after the retention period. Object Lock blocks early deletion but never moves or removes anything; replication copies objects to another bucket; AWS Backup manages backed-up resources, not the live objects in the bucket. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Backup & ransomware",
    q: "As protection against ransomware that encrypts or deletes your production data (including attempts to delete your backups), which AWS Backup feature is most relevant?",
    options: [
      "AWS Backup Vault Lock, which applies WORM to the vault and blocks early deletion",
      "Encryption in transit for the copies, so they cannot be intercepted while moving",
      "Raising the plan frequency to hourly copies to shrink the potential loss window",
      "Copying backups to another Region, since ransomware cannot cross Region boundaries",
    ],
    correct: 0,
    explain: "Backup Vault Lock brings the WORM principle to a whole vault: in compliance mode, once the grace period (at least 72 hours) elapses, neither root nor a compromised administrator can delete recovery points or shorten their retention. Encryption in transit does not stop a deletion, higher frequency only multiplies the copies an attacker can delete, and a cross-Region copy is still deletable with valid credentials. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/vault-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS DataSync vs Backup vs DLM",
    q: "Which statement correctly distinguishes AWS DataSync from AWS Backup?",
    options: [
      "They are the same transfer engine, with two commercial names and two consoles",
      "DataSync migrates and syncs data between systems; AWS Backup schedules and retains copies",
      "DataSync only supports relational databases; AWS Backup only supports file data",
      "AWS Backup supports neither EFS nor FSx; for those two file systems you have to use DataSync",
    ],
    correct: 1,
    explain: "DataSync moves and synchronizes data between NFS/SMB, object storage and AWS services: it is the migration and recurring on-premises↔AWS transfer tool. AWS Backup centralizes backup policy (scheduling, retention, cross-Region and cross-account copying) over EBS, RDS, DynamoDB, EFS, FSx and more. Amazon Data Lifecycle Manager (DLM) covers a different niche: EBS snapshots and AMIs. <a href=\"https://docs.aws.amazon.com/datasync/latest/userguide/what-is-datasync.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "TLS in transit",
    q: "You want to force every client connecting to your Application Load Balancer to use TLS 1.2 or higher, rejecting outdated ciphers. What do you configure?",
    options: [
      "A security group rule that blocks port 80 and only lets port 443 through to the ALB",
      "A bucket policy carrying the s3:TlsVersion condition applied over the ALB origin",
      "A security policy on the ALB HTTPS listener that requires TLS 1.2 as the minimum",
      "A NACL on the ALB subnet that drops packets negotiated with outdated cipher suites",
    ],
    correct: 2,
    explain: "ELB HTTPS/TLS listeners use predefined <em>security policies</em> that fix which TLS versions and cipher suites can be negotiated; choosing a modern one (say <code>ELBSecurityPolicy-TLS13-1-2-2021-06</code>) requires TLS 1.2 as a floor. Security groups and NACLs operate on ports and IPs: they can close port 80, but they cannot see the TLS version negotiated inside the connection. <a href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/describe-ssl-policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Private connectivity",
    q: "What's the main difference between AWS PrivateLink and VPC Peering for accessing a service in another VPC/account?",
    options: [
      "They are the same technology: PrivateLink is the current trade name of VPC peering",
      "PrivateLink only works between accounts that belong to the same AWS Organization or OU",
      "VPC peering is more secure because it encrypts traffic, which PrivateLink does not",
      "PrivateLink exposes a single service per endpoint; peering joins the two whole VPCs",
    ],
    correct: 3,
    explain: "PrivateLink publishes ONE specific service behind an endpoint: the consumer never sees the rest of the provider's VPC and CIDRs may overlap freely, which is what makes it right for SaaS and for cross-account services with no full trust relationship. VPC peering joins two entire networks bidirectionally, requires non-overlapping CIDRs, and potentially exposes everything reachable on the other side. <a href=\"https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Client VPN vs Verified Access",
    q: "How does AWS Verified Access differ from AWS Client VPN?",
    options: [
      "Client VPN opens a network tunnel and the user enters the VPC; Verified Access never does",
      "They are the same service: Verified Access is simply the new commercial name for Client VPN",
      "Verified Access only publishes on-premises applications, never applications in the VPC",
      "Client VPN supports neither MFA nor federation, which is why Verified Access replaces it",
    ],
    correct: 0,
    explain: "Client VPN is classic remote access: a tunnel comes up (full or split) and the client becomes one more node on the network. Verified Access implements Zero Trust Network Access: it evaluates trust-provider signals on EVERY HTTP request — identity via IAM Identity Center and device posture — and publishes the application without granting general network access. Client VPN does support SAML federation and MFA. <a href=\"https://docs.aws.amazon.com/verified-access/latest/ug/what-is-verified-access.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Inter-resource encryption",
    q: "What is 'Nitro encryption' in the context of EC2 instances built on the Nitro System?",
    options: [
      "A separate service you must enable in each Region and that bills per instance and hour",
      "Automatic encryption of traffic between Nitro instances and of memory, with no setup",
      "Encryption limited to attached EBS volumes, handled with the aws/ebs managed key",
      "A KMS key type reserved for GPU instances, used to encrypt their video memory",
    ],
    correct: 1,
    explain: "Nitro System hardware transparently encrypts traffic between supported instances with AES-256-GCM, provided they are in the same Region and the same VPC (or peered VPCs) and the traffic does not cross a load balancer or transit gateway. The keys exist only in the protected memory of the Nitro Cards. This is the 'inter-resource encryption in transit' exam point that surprises people because it needs no customer action. <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Secrets Manager",
    q: "What advantage does AWS Secrets Manager have over Systems Manager Parameter Store (SecureString) for RDS database credentials?",
    options: [
      "Parameter Store stores values in the clear, while Secrets Manager encrypts them with KMS",
      "Secrets Manager has no per-secret cost while Parameter Store bills for every parameter",
      "Secrets Manager rotates the credential automatically with Lambdas AWS already provides",
      "Parameter Store cannot control access with IAM policies, only through a VPC endpoint",
    ],
    correct: 2,
    explain: "Both encrypt with KMS and both are governed by IAM; the differentiator is <strong>rotation</strong>. Secrets Manager ships ready-made rotation Lambda functions for RDS, Aurora, Redshift and DocumentDB — and even managed rotation without a Lambda for some cases — which change the credential in the database and in the secret within the same cycle. Parameter Store is cheaper for configuration, but you write the rotation logic yourself. <a href=\"https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Data masking",
    q: "You want any credit card number that mistakenly appears in your CloudWatch Logs to be automatically masked before an operator with normal permissions can see it. What mechanism do you use?",
    options: [
      "An IAM policy that denies logs:GetLogEvents to every operator in the whole account",
      "Amazon Macie, which scans the log groups and replaces each sensitive value with asterisks",
      "Encrypting the log group with your own KMS key, which hides the value from readers",
      "A CloudWatch Logs data protection policy masking the value unless you hold logs:Unmask",
    ],
    correct: 3,
    explain: "CloudWatch Logs <em>data protection policies</em> detect managed sensitive data types (cards, SSNs, AWS credentials) or custom ones and mask them at every egress point — console, Logs Insights, metric filters, subscription filters — so only a principal holding <code>logs:Unmask</code> sees the real value. Encrypting with KMS protects the disk, not the view: anyone who can read the log group reads it decrypted. Amazon SNS offers an equivalent capability for messages. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/mask-sensitive-log-data.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "ACM & certificates",
    q: "What's the key difference between a public certificate from AWS Certificate Manager (ACM) and one issued by AWS Private CA?",
    options: [
      "ACM's are publicly trusted and free; Private CA's are trusted only inside your org",
      "There is no difference: both are free and any browser out on the market validates them",
      "AWS Private CA cannot issue TLS certificates, only sign code and device firmware",
      "Public ACM certificates have to be renewed and reinstalled by hand each time",
    ],
    correct: 0,
    explain: "ACM issues public certificates at no cost, with automatic renewal, for domains you can validate, consumable from ELB, CloudFront or API Gateway. AWS Private CA stands up your own private CA hierarchy — with a monthly cost per active CA — for internal certificates: mTLS between microservices, IoT devices, IAM Roles Anywhere. Those certificates are trusted only where you distribute the root certificate. <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Client-side vs server-side encryption",
    q: "In 'client-side' encryption of an S3 object, where does the data encryption happen?",
    options: [
      "On the S3 side, right before the object is written to the service's own disk",
      "In the client application, before the data leaves toward the S3 endpoint",
      "In an AWS-managed encryption proxy that sits in front of the S3 endpoint",
      "At the same point as SSE-S3: the only thing that changes is who owns the key",
    ],
    correct: 1,
    explain: "With client-side encryption (AWS Encryption SDK or the Amazon S3 Encryption Client) the object is encrypted in the application itself and S3 only ever receives ciphertext: the service plays no part in encrypting or decrypting and never sees plaintext. With server-side encryption (SSE-S3, SSE-KMS, DSSE-KMS, SSE-C) the object reaches S3 in the clear over TLS and S3 encrypts it as it writes to disk. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SSE-KMS vs SSE-C",
    q: "What characterizes SSE-C (Server-Side Encryption with Customer-Provided Keys) in S3, compared to SSE-KMS?",
    options: [
      "SSE-C allows plain HTTP requests because the key already travels encrypted in the header",
      "SSE-C internally wraps the key that you hand it with a KMS key managed by AWS",
      "S3 uses the AES-256 key you send on every request and never stores it anywhere",
      "SSE-C is the encryption applied by default to any new and unconfigured bucket",
    ],
    correct: 2,
    explain: "With SSE-C you own the AES-256 key and send it in headers on every PUT and every GET; S3 encrypts and decrypts with it but only keeps a randomly salted HMAC to validate later requests. That is why SSE-C mandates HTTPS, and why losing the key means losing the object. It never goes through KMS, and the default encryption for a new bucket is SSE-S3. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SageMaker AI / EMR / EKS",
    q: "In an Amazon EMR cluster processing sensitive data, which configuration specifically covers encryption of traffic BETWEEN cluster nodes (not just storage)?",
    options: [
      "Enabling SSE-S3 on the EMRFS bucket from which the cluster reads its input data",
      "Restricting the cluster security group so that only the nodes talk to each other",
      "Turning on CloudTrail data events on the cluster to record the internal traffic",
      "EMR in-transit encryption, defined in the cluster's security configuration",
    ],
    correct: 3,
    explain: "At-rest encryption (local EBS, EMRFS over S3) protects storage, but a distributed cluster's internal traffic — Spark shuffle, node-to-node RPC — is only encrypted if you enable <em>in-transit encryption</em> in the EMR security configuration, supplying PEM certificates or letting EMR manage them. A security group restricts who talks to whom, it does not encrypt; CloudTrail records API calls, not cluster traffic. <a href=\"https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-data-encryption-options.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS HMAC keys",
    q: "You need to generate and verify HMACs (message authentication codes) to guarantee the integrity and authenticity of messages between two systems, relying on a FIPS 140-2 validated HSM, without managing the cryptographic material yourself. What would you use?",
    options: [
      "A KMS HMAC key with KeyUsage GENERATE_VERIFY_MAC, via GenerateMac and VerifyMac",
      "A standard symmetric KMS key, encrypting the message with Encrypt and comparing outputs",
      "AWS Signer, which produces a signature of the message with its code-signing cert",
      "A rotated Secrets Manager secret, using its value as the HMAC key in the application",
    ],
    correct: 0,
    explain: "HMAC KMS keys are symmetric keys with <code>KeyUsage GENERATE_VERIFY_MAC</code>, conforming to RFC 2104, dedicated to <code>GenerateMac</code> and <code>VerifyMac</code> over messages of up to 4,096 bytes; they support neither Encrypt/Decrypt nor GenerateDataKey. Their advantage over a software HMAC is that the material is generated and used entirely inside KMS, subject to the key policy. Signer signs code artifacts, not arbitrary messages. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/hmac.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS ECDH key agreement",
    q: "Two separate organizations want to establish a shared secret between their systems in order to later derive a symmetric session key, without transmitting any private key over the network. Which KMS operation enables this using asymmetric EC keys?",
    options: [
      "GenerateDataKeyPair, which hands each party an EC key pair to share with the other",
      "DeriveSharedSecret on an EC KMS key with KeyUsage KEY_AGREEMENT, using ECDH",
      "GenerateRandom, whose random value both parties then use as the shared secret",
      "Sign and Verify on an RSA key, signing the secret one party sends to the other",
    ],
    correct: 1,
    explain: "<code>DeriveSharedSecret</code> applies the ECDH Cofactor primitive over your asymmetric NIST EC (or SM2) KMS key with <code>KeyUsage KEY_AGREEMENT</code> and the other party's public key: both sides end up with the same secret without any private key leaving KMS or crossing the network. Signing or encrypting a secret and sending it does put it in transit, and <code>GenerateRandom</code> produces a value nobody else can reproduce. <a href=\"https://docs.aws.amazon.com/kms/latest/APIReference/API_DeriveSharedSecret.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 Bucket Keys",
    q: "A company encrypts millions of S3 objects with SSE-KMS and notices that the cost of KMS API calls (GenerateDataKey, Decrypt) is disproportionately high relative to storage. Which S3 option, enabled without any change to the client application, drastically reduces that cost?",
    options: [
      "Switching the bucket to SSE-S3, which still calls KMS but with no per-request cost",
      "Enabling S3 Transfer Acceleration, which batches the encryption requests together",
      "Enabling S3 Bucket Keys, which reuses one bucket-level key for many objects",
      "Migrating the bucket to DSSE-KMS, whose two layers cut the calls to the KMS API",
    ],
    correct: 2,
    explain: "Without Bucket Keys, S3 asks KMS for a data key per object and per read. With S3 Bucket Keys it requests one short-lived bucket-level key and derives data keys for many objects locally, cutting KMS requests by up to 99% with no application change. DSSE-KMS pulls the other way (more operations and a higher per-GB cost) and is not compatible with Bucket Keys; Transfer Acceleration affects the network, not encryption. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 DSSE-KMS",
    q: "A defense-sector customer needs to comply with CNSSP 15 / the Data-at-Rest Capability Package, which requires TWO independent layers of AES-256 encryption on objects stored in S3. Which S3 encryption method meets this requirement?",
    options: [
      "SSE-KMS with S3 Bucket Keys, whose bucket key contributes the second AES-256 layer",
      "SSE-C, because the customer key and the S3 key form two independent layers",
      "Client-side encryption with the AWS Encryption SDK, which wraps the data key twice",
      "DSSE-KMS, which applies two independent layers of AES-256 on upload of the object",
    ],
    correct: 3,
    explain: "DSSE-KMS encrypts the object twice, independently: one layer under a KMS data key and another under a key managed by S3, which is what dual-layer guidance for highly regulated workloads demands. The S3 Bucket Key only derives data keys for a single layer, and wrapping a data key twice (client-side) is not the same as encrypting the data twice. DSSE-KMS does not support Bucket Keys and costs more per GB. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingDSSEncryption.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudHSM custom key store",
    q: "A financial institution requires its encryption key material to live in single-tenant HSMs under its exclusive control, but wants to keep using the native KMS integration with S3, EBS and RDS. Which design allows that?",
    options: [
      "A KMS custom key store backed by a CloudHSM cluster",
      "Plain CloudHSM, encrypting in the application before writing to each service",
      "A customer managed KMS key with automatic annual rotation enabled",
      "Importing key material generated in the on-premises HSM into KMS every 90 days",
    ],
    correct: 0,
    explain: "A <b>custom key store</b> keeps key material inside a CloudHSM cluster that is yours and single-tenant, while KMS remains the API: S3, EBS and RDS integrate exactly as before, and the application never needs to know where the key lives. Plain CloudHSM forces the application to do the crypto and loses every one of those integrations. An ordinary customer managed key lives in the shared KMS HSMs. And imported key material still resides in KMS: setting the origin to EXTERNAL decides who generates the key, not where it is held. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/keystore-cloudhsm.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Nitro Enclaves & KMS attestation",
    q: "An application processes highly sensitive data inside an AWS Nitro Enclave and needs KMS to decrypt data only for THAT specific enclave (identified by its image hash), not for any other process on the parent instance or any other enclave. What mechanism guarantees this?",
    options: [
      "A classic KMS grant given to the parent instance role, with no extra conditions",
      "KMS cryptographic attestation, with kms:RecipientAttestation in the key policy",
      "The Nitro System automatic memory encryption, which isolates enclave from parent",
      "A KMS Multi-Region key whose replica is deployed inside the isolated enclave",
    ],
    correct: 1,
    explain: "When you call <code>Decrypt</code>, <code>GenerateDataKey</code>, <code>GenerateDataKeyPair</code>, <code>GenerateRandom</code> or <code>DeriveSharedSecret</code> with an AttestationDocument signed by the Nitro hypervisor, KMS validates the enclave's measurements and returns the result encrypted under the document's public key rather than in plaintext. The <code>kms:RecipientAttestation:ImageSha384</code> condition (PCR0) in the key policy pins access to the expected image. A grant without conditions cannot tell enclaves apart. <a href=\"https://docs.aws.amazon.com/enclaves/latest/user/kms.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "ALB mutual TLS (mTLS)",
    q: "You need your Application Load Balancer to authenticate the CLIENT's identity (not just encrypt the channel) by verifying its X.509 certificate against a trusted CA, before forwarding the request to the target. What do you configure?",
    options: [
      "A TLS 1.3 security policy on the listener, which already demands a client cert",
      "AWS WAF with a rate-based rule that validates the certificate before forwarding",
      "mTLS in verify mode on the HTTPS listener, with a trust store holding the CA bundle",
      "A security group that only admits the CIDR range from which the client connects",
    ],
    correct: 2,
    explain: "The ALB offers two mTLS modes: <strong>passthrough</strong>, which forwards the client's certificate chain to the target in HTTP headers without validating it, and <strong>verify</strong>, where the ALB itself validates the certificate against a trust store holding the CA bundle (third-party or AWS Private CA) and, optionally, revocation lists. Verify is what offloads client authentication from the backend. A security policy fixes protocols and ciphers; it does not demand a client certificate. <a href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/mutual-authentication.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Macie — automated discovery",
    q: "You want continuous, low-cost visibility into which S3 buckets across your organization might contain sensitive data, without manually defining and running a full scanning job against every bucket. Which Macie capability do you use?",
    options: [
      "A sensitive data discovery job scheduled over 100% of the objects in each bucket",
      "GuardDuty S3 Protection, which classifies the content of each object by its data type",
      "AWS Config rules that evaluate the content of the objects, bucket by bucket",
      "Automated sensitive data discovery, which samples objects daily and scores buckets",
    ],
    correct: 3,
    explain: "Macie has two modes. <strong>Automated sensitive data discovery</strong> evaluates the bucket inventory of every account in the organization daily and analyzes a representative sample of objects, producing a data map and a per-bucket sensitivity score at low cost. <strong>Sensitive data discovery jobs</strong> are targeted, exhaustive analyses of specific buckets, and cost more because they inspect far more objects. GuardDuty analyzes activity, not content. <a href=\"https://docs.aws.amazon.com/macie/latest/user/discovery-asdd.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Private CA — short-lived certificate mode",
    q: "A platform issues hundreds of thousands of very short-lived certificates (7 days or less) per month to authenticate ephemeral workloads, and the fixed monthly cost of a general-purpose mode CA is disproportionate. What option reduces the cost?",
    options: [
      "AWS Private CA in short-lived certificate mode, capped at seven days of validity",
      "Migrating to public ACM, which issues free certificates for any ephemeral workload",
      "Disabling OCSP and CRLs on the CA, which is where the fixed monthly cost sits",
      "Issuing the certificates straight from CloudHSM, without using AWS Private CA",
    ],
    correct: 0,
    explain: "AWS Private CA has two <em>usage modes</em>: general-purpose (any validity period, higher fixed monthly cost) and short-lived certificate (much lower fixed cost, but no issued certificate may exceed 7 days). It fits ephemeral container and function identities, which rotate so fast they need no revocation mechanism at all. Public ACM does not issue internal certificates, and CloudHSM provides keys, not a managed CA hierarchy. <a href=\"https://docs.aws.amazon.com/privateca/latest/userguide/short-lived-certificates.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Secrets Manager multi-Region",
    q: "An application with readers in two regions needs low-latency access to the same database secret in both, and when the credential is rotated in the primary region, the new value should propagate automatically without managing rotation separately in each region. Which Secrets Manager feature do you use?",
    options: [
      "S3 Cross-Region Replication over an exported file that holds the secret value",
      "Secrets Manager multi-Region secrets, replicated with ReplicateSecretToRegions",
      "Creating an independent secret in each Region with the same name and same value",
      "A KMS Multi-Region key, which also replicates the secret value to the replicas",
    ],
    correct: 1,
    explain: "<code>ReplicateSecretToRegions</code> creates replicas linked to the primary secret: the encrypted value and the metadata (tags, resource policy) are replicated, and when rotation updates the primary the new value reaches every replica on its own. Each replica bills as a secret and can be promoted to standalone. A KMS Multi-Region key replicates key material, never the secret's contents. <a href=\"https://docs.aws.amazon.com/secretsmanager/latest/userguide/replicate-secrets.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "An on-premises workload (outside AWS) needs to obtain temporary IAM credentials to call the AWS API, without using long-term access keys stored on the server. An internal PKI already exists. Which solution fits?",
    options: [
      "IAM access keys kept on the server and rotated manually every ninety days",
      "AWS Client VPN, which hands out role credentials when the tunnel comes up",
      "IAM Roles Anywhere, registering your internal PKI's CA as a trust anchor",
      "Amazon Cognito Identity Pools, trading the X.509 certificate for credentials",
    ],
    correct: 2,
    explain: "IAM Roles Anywhere establishes trust between your existing PKI — registered as a <em>trust anchor</em> — and AWS: the workload presents an X.509 certificate issued by that CA, calls <code>CreateSession</code> and receives temporary IAM role credentials via STS, removing long-term access keys from the server. Client VPN provides network connectivity, not credentials; Cognito Identity Pools targets application end-user identities. <a href=\"https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "EBS encryption by default",
    q: "You enable the account-level 'EBS encryption by default' setting in a region that already has unencrypted EBS volumes in use. What happens to those existing volumes?",
    options: [
      "They are encrypted automatically the next time they get attached to an EC2 instance",
      "They get flagged as non-compliant and EC2 deletes them when the instance ends",
      "They get progressively encrypted as the volume's next snapshot is being created",
      "Nothing: the setting only reaches volumes and snapshot copies created afterwards",
    ],
    correct: 3,
    explain: "'EBS encryption by default' is a per-account, per-Region setting that only affects volumes and snapshot copies created from that point on; it never touches what already exists. A volume or snapshot can only be encrypted at creation time, so the route to encrypting an existing one is: snapshot → encrypted copy of that snapshot → create a new volume from the copy. <a href=\"https://docs.aws.amazon.com/ebs/latest/userguide/encryption-by-default.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "RDS encryption at rest",
    q: "You have a production RDS instance that was created WITHOUT encryption at rest (storage encryption disabled). How can you enable encryption without losing the data?",
    options: [
      "You cannot: you must copy the snapshot with encryption and restore a new instance",
      "With modify-db-instance and the --storage-encrypted flag on the live instance",
      "By enabling SSE-KMS on the instance from the encryption tab of the RDS console",
      "By turning on 'EBS encryption by default', which encrypts the existing storage",
    ],
    correct: 0,
    explain: "RDS encryption at rest is set only at instance creation or when restoring from an encrypted snapshot: there is no <code>modify</code> operation to turn it on later, and it can neither be disabled nor re-keyed afterwards. The standard pattern is snapshot → copy the snapshot with encryption enabled → restore from that copy → cut over, using DMS if you need to minimize the downtime window. <a href=\"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "kms:ViaService",
    q: "You want a customer managed KMS key to be usable only by Amazon S3 (not by EBS, RDS, or a user calling the KMS API directly), even if those other principals hold general IAM permissions on the key. What condition do you add to the key policy?",
    options: [
      "aws:SourceIp, restricting the key to the public IP address ranges used by S3",
      "kms:ViaService, set to s3.eu-west-1.amazonaws.com, on the usage statement",
      "aws:PrincipalOrgID, which narrows key usage down to the accounts in your org",
      "kms:GrantIsForAWSResource, which forces the call to arrive from an AWS service",
    ],
    correct: 1,
    explain: "<code>kms:ViaService</code> requires the request to reach KMS <em>through</em> a specific service, identified by its regional service principal (for example <code>s3.eu-west-1.amazonaws.com</code>): even if a role holds <code>kms:Decrypt</code> in its identity policy, a direct API call is denied. <code>kms:GrantIsForAWSResource</code> only constrains who may create grants, and <code>aws:PrincipalOrgID</code> narrows accounts, not services. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/conditions-kms.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "RDS — master password managed by Secrets Manager",
    q: "You want to fully eliminate plaintext exposure of a new RDS database's master password during creation, and have AWS handle periodic rotation of that password without you writing a Lambda function. Which RDS option do you use?",
    options: [
      "Creating the secret and the rotation Lambda by hand right after the instance exists",
      "Storing the password in a Parameter Store SecureString with a rotation policy",
      "Enabling 'Manage master credentials in AWS Secrets Manager' when creating it",
      "Disabling password authentication and relying only on IAM database authentication",
    ],
    correct: 2,
    explain: "With 'Manage master credentials in AWS Secrets Manager' it is RDS that generates the master password, stores it in Secrets Manager and rotates it regularly: it is never shown in plaintext during creation and you write or deploy no Lambda at all. You may optionally encrypt the secret with a customer managed key. IAM database authentication is a valid alternative for application connections, but the master user still has a password. <a href=\"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-secrets-manager.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 Object Lock — Legal Hold",
    q: "You need to preserve an S3 object indefinitely for an ongoing legal matter, without knowing how long it will last, and without relying on setting a specific retention date in Governance or Compliance mode. Which Object Lock mechanism do you use?",
    options: [
      "A retention period in Compliance mode with the expiry date set to year 2099",
      "Glacier Vault Lock, whose locked policy retains the object with no fixed term",
      "S3 Versioning with MFA Delete, which demands a second factor before deleting",
      "A Legal Hold, which applies that same WORM protection but with no expiration date",
    ],
    correct: 3,
    explain: "A Legal Hold gives the same WORM protection as a retention period but never expires: it stays in force until a principal holding <code>s3:PutObjectLegalHold</code> explicitly removes it, which is exactly what litigation of unknown duration calls for. An object can carry a retention period, a legal hold, both, or neither, because they are independent mechanisms. Setting Compliance until 2099 would be irreversible even if the case closes tomorrow. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "KMS automatic rotation — scope",
    q: "You enable annual automatic rotation on a KMS key. For which of the following is that automatic rotation NOT available, requiring manual or on-demand rotation instead?",
    options: [
      "Asymmetric keys, HMAC keys, imported key material, and custom key store keys",
      "Only the symmetric encryption keys whose material KMS itself generated for you",
      "Only AWS managed keys such as aws/s3 or aws/ebs, which already rotate alone",
      "None at all: any KMS key supports automatic rotation as soon as you turn it on",
    ],
    correct: 0,
    explain: "Automatic rotation exists only for symmetric encryption KMS keys with AWS-generated material (origin <code>AWS_KMS</code>). Left out are asymmetric keys, HMAC keys, keys with imported material (<code>EXTERNAL</code>) and keys in a custom key store (CloudHSM key store or XKS). For those the answer is manual rotation — create a new key and repoint the aliases — or, for imported material, <code>RotateKeyOnDemand</code>. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudTrail & KMS usage auditing",
    q: "You suspect a customer managed KMS key was used to decrypt data by an unauthorized principal. Where do you check who invoked the Decrypt operation on that key, when, and from which principal/role?",
    options: [
      "In the key's key policy, which lists the principals that have already used it",
      "In AWS CloudTrail, which logs every KMS call with its principal and Key ID",
      "In Amazon Macie, which inventories key usage over the sensitive data it finds",
      "In AWS Config, which records KMS API invocations in real time as they happen",
    ],
    correct: 1,
    explain: "Every KMS operation — including cryptographic ones such as <code>Decrypt</code> and <code>GenerateDataKey</code> — is logged as a CloudTrail management event carrying the calling principal, the timestamp, the Key ID, the source IP and whether the call succeeded or was denied; for cross-account access the event lands in both accounts. The key policy says who <em>may</em> use the key, not who did, and Config evaluates configuration, not invocations. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/logging-using-cloudtrail.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Cross-account KMS key use",
    q: "A role in account B must decrypt objects encrypted with a customer managed KMS key living in account A. Which TWO conditions must hold?",
    options: [
      "The key policy in account A must expressly authorize the account B principal",
      "The key must be an AWS managed key, the only kind that can be shared across accounts",
      "The identity policy of the role in account B must allow the kms:Decrypt action",
      "Both accounts must belong to the same Organization and sit in the same Region",
    ],
    correct: [0, 2],
    explain: "As with cross-account role access, KMS requires <strong>both ends</strong>: key policy on the owner and identity policy on the consumer; neither alone is enough. Notably <strong>AWS managed keys cannot be shared</strong> across accounts, which is why the cross-account use case requires a customer managed key — the opposite of option C. Organizations isn't needed; Region does matter since keys are regional, but that is not what's missing here. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Envelope encryption",
    q: "Which TWO statements correctly describe envelope encryption as AWS KMS implements it?",
    options: [
      "Data travels all the way to KMS to be encrypted there, regardless of its total size",
      "Data is encrypted with a data key, and that data key is encrypted with the KMS key",
      "The KMS key leaves the service in plaintext to encrypt the data on the client",
      "The plaintext data key is used in memory and discarded as soon as encryption ends",
    ],
    correct: [1, 3],
    explain: "Envelope encryption exists precisely so data does <strong>not</strong> travel to KMS: KMS encrypts the data key (a small, fast operation) and bulk encryption happens locally. The direct <code>Encrypt</code> operation is capped at 4 KB, which rules out option C for real data. And a KMS key's cryptographic material <strong>never leaves the service in plaintext</strong>: that is its fundamental guarantee. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Immutable retention in S3",
    q: "A regulatory requirement demands certain S3 objects cannot be deleted for 7 years. Which TWO statements about S3 Object Lock are correct?",
    options: [
      "In compliance mode no user, not even the account root, can delete the object",
      "In governance mode nobody can bypass retention under any foreseen circumstance",
      "Object Lock can be switched on for existing objects with no prior bucket setup",
      "Object Lock requires versioning to be enabled on the target bucket beforehand",
    ],
    correct: [0, 3],
    explain: "<strong>Compliance</strong> is the truly immutable mode (not even root can bypass it) and Object Lock <strong>depends on versioning</strong>, since it protects specific object versions. <strong>Governance</strong> mode does allow an override for anyone holding <code>s3:BypassGovernanceRetention</code> — that is exactly the difference between the modes and what tends to be tested. And Object Lock is enabled at the bucket level, not improvised onto objects in a bucket without it. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Secrets Manager rotation",
    q: "You want to automatically rotate an RDS database password stored in Secrets Manager. Which TWO elements are involved?",
    options: [
      "An S3 bucket where Secrets Manager deposits the previous password in plaintext",
      "A rotation Lambda with permission to change the credential inside the database",
      "A rotation schedule that defines how often the whole process is executed",
      "An AWS Config rule that changes the password once it detects it has expired",
    ],
    correct: [1, 2],
    explain: "Rotation relies on a <strong>Lambda</strong> (AWS ships templates for supported databases) and a <strong>schedule</strong> expressed with <code>cron()</code> or <code>rate()</code>. Secrets Manager keeps secret versions with staging labels such as AWSCURRENT and AWSPREVIOUS inside the service itself, encrypted with KMS: it never writes plaintext credentials to a bucket. And AWS Config <strong>evaluates</strong> configuration, it does not rotate credentials. <a href=\"https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Masking in SNS messages",
    q: "An SNS topic fans events out to several teams and the message body sometimes contains customer email addresses. You want unauthorized subscribers to receive them obfuscated, without changing the publisher. What do you apply?",
    options: [
      "A data protection policy on the topic, with a masking action",
      "Encryption at rest on the topic with a customer managed KMS key",
      "A subscription filter that drops messages containing personal data",
      "A CloudWatch Logs data protection policy on the publisher's log group",
    ],
    correct: 0,
    explain: "SNS <b>data protection policies</b> inspect the message body against managed data identifiers and apply an action — audit, de-identify or deny — per subscriber, so some receive the value and others do not. Encryption at rest protects the message while it waits, but the subscriber still receives it in the clear. A subscription filter decides which messages arrive, not which parts. And the CloudWatch Logs policy affects what is logged, not what is delivered. <a href=\"https://docs.aws.amazon.com/sns/latest/dg/message-data-protection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "EFS lifecycle management",
    q: "An EFS file system holds forensic evidence that is almost never read after the first week but must stay accessible for years. What reduces cost without moving it out of the file system?",
    options: [
      "An EFS lifecycle rule into Infrequent Access",
      "Copying it to S3 Glacier Deep Archive with a scheduled DataSync task",
      "An S3 lifecycle policy on the bucket that backs the EFS file system",
      "Lowering the file system's provisioned throughput to bursting mode",
    ],
    correct: 0,
    explain: "EFS has its own <b>lifecycle management</b>: after the configured number of days without access, a file drops to Infrequent Access or Archive, stays at the same path, reads the same way and costs considerably less. Copying to Glacier with DataSync moves it out of the file system, which the question rules out. EFS is not backed by an S3 bucket, so there is no S3 policy to apply. And throughput mode changes speed, not the price of storage. <a href=\"https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "FSx for Lustre backups",
    q: "A compute cluster uses Amazon FSx for Lustre with sensitive data and you need daily backups with a defined retention, encrypted, without stopping the file system. What do you use?",
    options: [
      "EBS snapshots of the volumes backing the file system",
      "The FSx automatic daily backups, with their window and retention",
      "A DataSync task replicating the contents to another file system",
      "Versioning on the S3 bucket linked by a data repository association",
    ],
    correct: 1,
    explain: "FSx for Lustre ships <b>automatic daily backups</b> with a configurable window and retention period, consistent with the file system and encrypted with the same key, without interrupting service. There are no EBS volumes to snapshot: the storage is not exposed that way. DataSync copies files but gives you neither a consistent recovery point nor a retention policy. And S3 versioning protects the objects in the linked repository, not the file system's metadata or state. <a href=\"https://docs.aws.amazon.com/fsx/latest/LustreGuide/using-backups-fsx.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "DataSync and encryption in transit",
    q: "You are copying 40 TB from an on-premises NAS to S3 and the requirement is that data travels encrypted end to end over the Direct Connect link. What is true of AWS DataSync?",
    options: [
      "You must build your own IPsec tunnel, because DataSync travels in the clear",
      "It encrypts in transit with TLS between agent and service, always",
      "Encryption in transit only applies when the destination bucket uses SSE-KMS",
      "It requires a site-to-site VPN on top of Direct Connect in order to encrypt",
    ],
    correct: 1,
    explain: "The DataSync agent always talks to the service over <b>TLS</b>, including the Direct Connect path through a VPC endpoint, so encryption in transit is neither optional nor something you configure. No IPsec tunnel or VPN is needed on top: that would encrypt twice. And destination encryption — SSE-S3 or SSE-KMS — is a decision about the data <em>at rest</em>, independent of how it travelled. <a href=\"https://docs.aws.amazon.com/datasync/latest/userguide/encryption-in-transit.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["data-protection"] = QUIZ_DATA;
