const QUIZ_DATA = [
  {
    tag: "Envelope encryption",
    q: "¿Por qué KMS usa 'envelope encryption' (cifrar los datos con una data key, y esa data key con la CMK) en vez de cifrar directamente los datos con la KMS key?",
    options: [
      "Porque las KMS keys no pueden cifrar datos en absoluto, solo otras claves",
      "Porque las API de KMS tienen un límite de tamaño de payload muy pequeño (4KB para simétricas); envolver permite cifrar datos de cualquier tamaño localmente y solo enviar la data key (pequeña) a KMS",
      "Porque es un requisito de cumplimiento de HIPAA exclusivamente",
      "Porque así se evita pagar por las llamadas a la API de KMS",
    ],
    correct: 1,
    explain: "Las operaciones Encrypt/Decrypt directas de KMS están limitadas a ~4KB de payload. Para cifrar objetos grandes, se genera una data key (GenerateDataKey), se cifran los datos localmente con esa data key (sin límite de tamaño), y solo la data key (pequeña) se envía a KMS para ser cifrada/descifrada — de ahí 'envelope' (sobre).",
  },
  {
    tag: "Envelope encryption",
    q: "Tras usar GenerateDataKey para cifrar un archivo grande localmente, ¿qué debe hacer la aplicación con la data key en texto plano una vez terminado el cifrado?",
    options: [
      "Guardarla junto al archivo cifrado para poder descifrar más rápido después",
      "Enviarla de vuelta a KMS para que la almacene de forma segura",
      "Eliminarla de memoria inmediatamente; solo se conserva la versión CIFRADA de la data key (el 'encrypted blob') junto a los datos",
      "Cifrarla con una segunda data key distinta (doble envuelta)",
    ],
    correct: 2,
    explain: "GenerateDataKey devuelve DOS versiones: la data key en texto plano (se usa una vez para cifrar y se descarta de memoria) y la data key cifrada por la KMS key (esa sí se guarda junto a los datos). Para descifrar, se manda la data key cifrada a KMS Decrypt, que devuelve la versión en texto plano.",
  },
  {
    tag: "Tipos de KMS keys",
    q: "¿Cuál es la diferencia principal entre una AWS managed key (ej. aws/s3) y una customer managed key (CMK) en KMS?",
    options: [
      "Las AWS managed keys son gratis y las customer managed cuestan; aparte de eso son idénticas",
      "Solo las customer managed keys permiten escribir key policies personalizadas, habilitar rotación en la fecha que quieras, deshabilitarlas o programar su eliminación",
      "Las AWS managed keys soportan multi-Region y las customer managed no",
      "Las AWS managed keys son asimétricas por defecto",
    ],
    correct: 1,
    explain: "Las AWS managed keys (prefijo aws/) las crea y gestiona AWS automáticamente para un servicio concreto, con rotación anual obligatoria y sin key policy personalizable. Las customer managed keys te dan control total: key policy propia, rotación opcional configurable, se pueden deshabilitar/eliminar, y son las únicas que soportan multi-Region keys.",
  },
  {
    tag: "KMS grants",
    q: "¿Para qué se usa un KMS grant en vez de modificar la key policy directamente?",
    options: [
      "Un grant da permisos permanentes que sustituyen a la key policy",
      "Un grant permite delegar permisos temporales y programáticos sobre una key (ej. a un servicio de AWS actuando en tu nombre) sin editar la key policy, y se puede revocar individualmente sin afectar a otros permisos",
      "Los grants solo existen para claves asimétricas",
      "Un grant es simplemente otro nombre para una IAM policy adjunta a un rol",
    ],
    correct: 1,
    explain: "Los grants son un mecanismo de delegación de permisos más granular y dinámico que la key policy: se crean/revocan programáticamente (CreateGrant/RetireGrant/RevokeGrant), son ideales para que un servicio de AWS obtenga acceso temporal a tu key en tu nombre (ej. EBS cifrando un volumen), sin tener que reescribir la key policy cada vez.",
  },
  {
    tag: "KMS multi-Region keys",
    q: "Tienes una Multi-Region KMS key primaria en eu-west-1 replicada como réplica en us-east-1. Un objeto S3 se cifró con la réplica en us-east-1. ¿Puede descifrarse usando la key primaria en eu-west-1?",
    options: [
      "No, cada réplica es una key completamente independiente con material criptográfico distinto",
      "Sí: las Multi-Region keys comparten el MISMO material criptográfico subyacente entre primaria y réplicas, aunque tengan Key IDs distintos — lo cifrado con una réplica se puede descifrar con cualquier otra réplica o la primaria",
      "Solo si ambas están en la misma cuenta pero no en la misma Region",
      "Solo puede descifrarse creando manualmente una tercera key que combine ambas",
    ],
    correct: 1,
    explain: "A diferencia de crear KMS keys idénticas de forma independiente en cada región (que tendrían material criptográfico DISTINTO), las Multi-Region keys son réplicas que comparten el mismo material criptográfico. Esto permite cifrar en una región y descifrar en otra sin re-cifrar los datos — clave para DR y aplicaciones globales.",
  },
  {
    tag: "KMS vs CloudHSM",
    q: "Una empresa de servicios financieros necesita FIPS 140-2 Level 3, control exclusivo (single-tenant) del hardware criptográfico, y la capacidad de exportar el material de claves si migran de proveedor. ¿Qué servicio encaja mejor?",
    options: [
      "AWS KMS con customer managed keys",
      "AWS CloudHSM: HSM dedicado y single-tenant, control total del ciclo de vida de las claves, y permite exportarlas (a diferencia de KMS)",
      "AWS Secrets Manager",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "KMS es multi-tenant (aunque con fuertes garantías de aislamiento) y NUNCA permite exportar el material de la clave. CloudHSM te da un HSM dedicado (single-tenant), FIPS 140-2 Level 3, y control total incluyendo la posibilidad de exportar claves — al coste de gestionar tú mismo la infraestructura HSM (clusters, alta disponibilidad).",
  },
  {
    tag: "Imported key material",
    q: "¿Qué limitación tienen las KMS keys con material de clave IMPORTADO (BYOK) que NO tienen las generadas por AWS?",
    options: [
      "No pueden usarse para cifrar datos, solo para firmar",
      "No soportan la rotación automática anual gestionada por AWS; la rotación, si se quiere, hay que gestionarla manualmente re-importando material nuevo",
      "Solo pueden usarse con S3, no con otros servicios",
      "No pueden tener key policy personalizada",
    ],
    correct: 1,
    explain: "Cuando importas tu propio material de clave, AWS no puede rotarlo automáticamente por ti (no conoce el proceso para generarlo de nuevo). Puedes opcionalmente configurar una fecha de expiración del material, y la rotación se convierte en un proceso manual: crear una nueva KMS key e importar material nuevo.",
  },
  {
    tag: "External Key Store (XKS)",
    q: "¿Qué resuelve un KMS External Key Store (XKS)?",
    options: [
      "Permite generar claves más rápido que el KMS estándar",
      "Permite que el material de clave resida y se gestione FUERA de AWS (en tu propio gestor de claves on-premises o de terceros), mientras las aplicaciones de AWS siguen usando la API estándar de KMS",
      "Es simplemente un bucket S3 donde se guardan copias de las claves",
      "Sustituye a CloudHSM completamente",
    ],
    correct: 1,
    explain: "XKS conecta KMS a un gestor de claves externo (on-premises o de un tercero) a través de un proxy: el material de clave NUNCA entra en AWS, pero los servicios de AWS integrados con KMS pueden seguir usando esa clave de forma transparente. Es la opción para 'soberanía de clave' máxima manteniendo la integración nativa con AWS.",
  },
  {
    tag: "S3 Object Lock",
    q: "¿Cuál es la diferencia entre el modo Governance y el modo Compliance en S3 Object Lock?",
    options: [
      "Son sinónimos, cambia solo el nombre según la región",
      "En modo Governance, usuarios con el permiso s3:BypassGovernanceRetention pueden eliminar/sobrescribir el objeto antes de que expire el retention period; en modo Compliance, NADIE puede hacerlo — ni siquiera la cuenta root — hasta que expire",
      "Compliance solo aplica a buckets con versioning deshabilitado",
      "Governance es para objetos públicos y Compliance para privados",
    ],
    correct: 1,
    explain: "Ambos modos usan WORM (Write Once Read Many), pero Governance permite una válvula de escape para usuarios con permisos elevados específicos, mientras que Compliance es absoluto: una vez fijado el retention period, ni el usuario root puede borrar o modificar el objeto hasta que expire. Compliance se usa para requisitos regulatorios estrictos (ej. SEC 17a-4).",
  },
  {
    tag: "Glacier Vault Lock",
    q: "¿Qué caracteriza a una política de Glacier Vault Lock una vez que se confirma (lock-policy)?",
    options: [
      "Puede editarse libremente en cualquier momento por el administrador de la cuenta",
      "Se vuelve inmutable: no puede modificarse ni eliminarse nunca, ideal para cumplir requisitos regulatorios de retención de datos a largo plazo",
      "Expira automáticamente a los 90 días",
      "Solo aplica a objetos menores de 1MB",
    ],
    correct: 1,
    explain: "Vault Lock permite un periodo de prueba de 24 horas para validar la política antes de bloquearla ('lock'); una vez bloqueada, la política es permanente e inmutable — ni siquiera el propietario de la cuenta puede cambiarla, garantizando cumplimiento normativo verificable.",
  },
  {
    tag: "Integridad de datos",
    q: "Para verificar que un artefacto de software (ej. un binario descargado) no ha sido alterado en tránsito ni manipulado por un tercero, ¿qué mecanismo de AWS es el más apropiado?",
    options: [
      "S3 Versioning únicamente",
      "AWS Signer: firma digital de código con claves gestionadas centralmente, verificable por el receptor antes de ejecutar el artefacto",
      "MFA Delete en el bucket",
      "AWS Backup",
    ],
    correct: 1,
    explain: "AWS Signer permite firmar digitalmente código (ej. funciones Lambda, imágenes de contenedor, firmware IoT) para que el receptor pueda verificar criptográficamente que no ha sido alterado desde su creación — cubre la integridad, no solo la confidencialidad.",
  },
  {
    tag: "Lifecycle & retención",
    q: "Necesitas que los objetos de un bucket S3 se muevan automáticamente a Glacier Deep Archive tras 180 días y se eliminen definitivamente tras 7 años, sin intervención manual. ¿Qué mecanismo usas?",
    options: [
      "S3 Object Lock en modo Compliance con retención de 7 años",
      "S3 Lifecycle policies con reglas de transición (180 días → Deep Archive) y expiración (7 años → eliminación)",
      "AWS Backup con un plan diario",
      "Cross-Region Replication",
    ],
    correct: 1,
    explain: "S3 Lifecycle policies automatizan exactamente este patrón: reglas de TRANSITION entre clases de almacenamiento por antigüedad, y reglas de EXPIRATION para eliminación automática tras un periodo. Object Lock protege contra borrado antes de tiempo, pero no mueve ni elimina objetos por sí solo.",
  },
  {
    tag: "Backup & ransomware",
    q: "Como protección contra ransomware que cifra o borra tus datos de producción (incluyendo intentos de eliminar los backups), ¿qué característica de AWS Backup es la más relevante?",
    options: [
      "AWS Backup Vault Lock: hace los backups inmutables (WORM), impidiendo que se eliminen o modifiquen incluso por un administrador comprometido, durante el periodo configurado",
      "Cifrado en tránsito de los backups únicamente",
      "Aumentar la frecuencia de backups a cada hora",
      "AWS Backup no ofrece ninguna protección específica contra ransomware",
    ],
    correct: 0,
    explain: "AWS Backup Vault Lock aplica el mismo principio WORM que S3 Object Lock, pero a nivel de vault de backups completo: una vez bloqueado (especialmente en modo compliance), ni siquiera credenciales de administrador comprometidas pueden eliminar los backups antes de que expire su retención — mitigación clave contra ransomware.",
  },
  {
    tag: "AWS DataSync vs Backup vs DLM",
    q: "¿Cuál de estas afirmaciones distingue correctamente AWS DataSync de AWS Backup?",
    options: [
      "Son el mismo servicio con nombres distintos",
      "DataSync está diseñado para MIGRAR/SINCRONIZAR grandes volúmenes de datos entre on-premises y AWS (o entre servicios de almacenamiento AWS); AWS Backup está diseñado para crear y gestionar copias de RESPALDO centralizadas y programadas de recursos AWS",
      "DataSync solo funciona con bases de datos relacionales",
      "AWS Backup no soporta EFS ni FSx",
    ],
    correct: 1,
    explain: "DataSync mueve/sincroniza datos (ideal para migraciones o transferencias recurrentes on-prem↔AWS), mientras que AWS Backup centraliza políticas de backup (retención, programación, copiado cross-Region/cross-account) para EBS, RDS, DynamoDB, EFS, FSx, etc. Amazon Data Lifecycle Manager (DLM), por su parte, automatiza específicamente snapshots de EBS y AMIs.",
  },
  {
    tag: "TLS en tránsito",
    q: "Quieres forzar que todos los clientes que se conecten a tu Application Load Balancer usen TLS 1.2 o superior, rechazando cifrados obsoletos. ¿Qué configuras?",
    options: [
      "Una Security Group rule que bloquee el puerto 80",
      "Una security policy (ELBSecurityPolicy) en el listener HTTPS del ALB, seleccionando una política que exija TLS 1.2+",
      "Una bucket policy en S3",
      "Una NACL en la subnet del ALB",
    ],
    correct: 1,
    explain: "Los Elastic Load Balancers (ALB/NLB) usan 'security policies' predefinidas en el listener HTTPS/TLS que determinan qué versiones de TLS y qué cipher suites se aceptan. Elegir una política moderna (ej. ELBSecurityPolicy-TLS13-1-2-2021-06) fuerza TLS 1.2+ y rechaza conexiones con protocolos antiguos.",
  },
  {
    tag: "Conectividad privada",
    q: "¿Cuál es la diferencia principal entre AWS PrivateLink y un VPC Peering para acceder a un servicio en otra VPC/cuenta?",
    options: [
      "Son idénticos, solo cambia el nombre comercial",
      "PrivateLink expone el servicio como un endpoint unidireccional (el consumidor no ve el resto de la VPC del proveedor, ni hay solapamiento de rangos CIDR a gestionar); VPC Peering conecta las dos VPCs completas bidireccionalmente, exponiendo potencialmente toda la red",
      "VPC Peering es más seguro que PrivateLink en todos los casos",
      "PrivateLink solo funciona entre cuentas de la misma Organization",
    ],
    correct: 1,
    explain: "PrivateLink es ideal para exponer UN servicio concreto (ej. un SaaS de un proveedor) sin dar visibilidad de red completa ni preocuparte por solapamiento de CIDRs. VPC Peering conecta dos redes completas como si fueran una — más apropiado para relaciones de confianza total entre VPCs propias.",
  },
  {
    tag: "Client VPN vs Verified Access",
    q: "¿En qué se diferencia AWS Verified Access de AWS Client VPN?",
    options: [
      "Son el mismo servicio, Verified Access es solo el nombre nuevo de Client VPN",
      "Client VPN establece un túnel de red tradicional (el usuario 'entra' a la VPC); Verified Access aplica un modelo Zero Trust evaluando identidad + postura del dispositivo en cada request a una aplicación específica, sin exponer un túnel de red completo",
      "Verified Access solo funciona con aplicaciones on-premises",
      "Client VPN no soporta MFA",
    ],
    correct: 1,
    explain: "Client VPN es un modelo de acceso remoto clásico (VPN de túnel completo o dividido). AWS Verified Access implementa Zero Trust Network Access (ZTNA): evalúa señales de identidad (IAM Identity Center) y de postura del dispositivo en cada solicitud a nivel de aplicación, sin dar al usuario acceso de red general.",
  },
  {
    tag: "Cifrado inter-recurso",
    q: "¿Qué es 'Nitro encryption' en el contexto de instancias EC2 basadas en el Nitro System?",
    options: [
      "Un servicio separado que hay que activar y pagar aparte",
      "Cifrado automático de la memoria de la instancia y del tráfico entre instancias Nitro dentro de la infraestructura de AWS, sin intervención ni configuración del cliente",
      "Solo cifra el almacenamiento EBS adjunto",
      "Un tipo de KMS key exclusivo para instancias GPU",
    ],
    correct: 1,
    explain: "El Nitro System cifra automáticamente los datos en tránsito ENTRE instancias Nitro dentro de la misma región (y la memoria local de la instancia) como parte de la arquitectura subyacente, sin que el cliente tenga que configurar nada — un punto de examen sobre 'inter-resource encryption in transit' que suele sorprender porque no requiere acción del usuario.",
  },
  {
    tag: "Secrets Manager",
    q: "¿Qué ventaja tiene AWS Secrets Manager sobre Systems Manager Parameter Store (SecureString) para credenciales de una base de datos RDS?",
    options: [
      "Parameter Store no puede cifrar valores, Secrets Manager sí",
      "Secrets Manager ofrece ROTACIÓN AUTOMÁTICA nativa (con funciones Lambda integradas para RDS, Redshift, DocumentDB) sin trabajo adicional; Parameter Store requiere que construyas tú la lógica de rotación",
      "Secrets Manager es gratuito y Parameter Store no",
      "Parameter Store no soporta control de acceso vía IAM",
    ],
    correct: 1,
    explain: "Ambos cifran con KMS, pero Secrets Manager tiene rotación automática integrada out-of-the-box para varios motores de base de datos (actualiza la credencial Y la aplica en la base de datos en el mismo ciclo). Parameter Store es más barato para configuración general, pero rotación automática nativa es la razón principal para elegir Secrets Manager con credenciales de bases de datos.",
  },
  {
    tag: "Data masking",
    q: "Quieres que cualquier número de tarjeta de crédito que aparezca por error en tus logs de CloudWatch Logs se enmascare automáticamente antes de que un operador con permisos normales pueda verlo. ¿Qué mecanismo usas?",
    options: [
      "Una IAM policy que deniegue leer logs",
      "Una CloudWatch Logs data protection policy con detectores de datos sensibles (ej. tipo de dato 'Credit-Card-Number') que enmascara el valor en la vista, dejándolo visible solo a principals con permiso explícito de 'unmask'",
      "Cifrar el log group con KMS únicamente",
      "Amazon Macie, porque CloudWatch Logs no soporta masking",
    ],
    correct: 1,
    explain: "Las CloudWatch Logs data protection policies detectan tipos de datos sensibles predefinidos (tarjetas, SSN, credenciales AWS, etc.) o personalizados, y enmascaran automáticamente esos valores en las consultas/vistas — solo principals con el permiso IAM logs:Unmask ven el valor real. Amazon SNS tiene una capacidad de 'message data protection' equivalente para mensajes.",
  },
  {
    tag: "ACM & certificados",
    q: "¿Cuál es la diferencia clave entre un certificado público de AWS Certificate Manager (ACM) y uno emitido por AWS Private CA?",
    options: [
      "No hay diferencia, ambos son gratuitos y de confianza pública",
      "Los certificados públicos de ACM son gratuitos y de confianza pública (verificados por una CA pública, válidos en cualquier navegador); los de AWS Private CA son de confianza PRIVADA (solo válidos dentro de tu organización, donde distribuyes tú el certificado raíz) y tienen coste por CA activa",
      "AWS Private CA no puede emitir certificados TLS, solo firmar código",
      "ACM público requiere gestionar tú mismo la renovación",
    ],
    correct: 1,
    explain: "ACM emite certificados públicos gratuitos con renovación automática, válidos para dominios públicos verificables (ej. ELB, CloudFront). AWS Private CA crea tu propia jerarquía de CA privada para emitir certificados internos (mTLS entre microservicios, dispositivos IoT, IAM Roles Anywhere) que solo son de confianza donde tú distribuyas el certificado raíz.",
  },
  {
    tag: "Client-side vs server-side encryption",
    q: "En cifrado 'client-side' de un objeto S3, ¿dónde ocurre el cifrado de los datos?",
    options: [
      "En el lado del servidor de S3, antes de escribir a disco",
      "En el cliente/aplicación, ANTES de enviar los datos a S3 — S3 recibe y almacena únicamente el objeto ya cifrado, sin ver nunca el texto plano",
      "En un proxy de KMS gestionado por AWS",
      "Es idéntico a SSE-S3, solo cambia el nombre",
    ],
    correct: 1,
    explain: "En cifrado client-side (usando el AWS Encryption SDK o el S3 Encryption Client), el cifrado ocurre en la aplicación del cliente antes de que el dato viaje a AWS — S3 nunca ve el texto plano. En server-side (SSE-S3, SSE-KMS, SSE-C), S3 recibe el dato en claro (por TLS) y lo cifra él mismo al escribirlo a disco.",
  },
  {
    tag: "SSE-KMS vs SSE-C",
    q: "¿Qué caracteriza a SSE-C (Server-Side Encryption with Customer-Provided Keys) en S3, frente a SSE-KMS?",
    options: [
      "SSE-C es más seguro porque AWS nunca ve la clave; el cliente debe enviar la clave de cifrado en CADA solicitud (GET/PUT) por HTTPS, y AWS no la almacena — si pierdes la clave, pierdes el objeto para siempre",
      "SSE-C usa automáticamente KMS internamente",
      "SSE-C no requiere HTTPS",
      "SSE-C es la opción por defecto si no configuras nada",
    ],
    correct: 0,
    explain: "Con SSE-C, tú gestionas y envías la clave de cifrado AES-256 en cada solicitud; S3 la usa para cifrar/descifrar pero NUNCA la almacena. Máximo control, pero también máxima responsabilidad: si pierdes esa clave, el objeto es irrecuperable, ya que ni siquiera AWS Support puede ayudarte.",
  },
  {
    tag: "SageMaker AI / EMR / EKS",
    q: "En un cluster de Amazon EMR que procesa datos sensibles, ¿qué configuración cubre específicamente el cifrado del tráfico ENTRE los nodos del cluster (no solo el almacenamiento)?",
    options: [
      "Habilitar SSE-S3 en el bucket de origen de los datos",
      "In-transit encryption / inter-node encryption de EMR (TLS entre nodos del cluster, shuffle de Spark, etc.), configurable en la Security Configuration del cluster",
      "Activar CloudTrail para el cluster",
      "Usar un Security Group más restrictivo únicamente",
    ],
    correct: 1,
    explain: "El cifrado at-rest (EBS, S3) protege el almacenamiento, pero el tráfico interno entre nodos de un cluster distribuido (EMR, EKS, SageMaker AI) requiere una configuración explícita de cifrado en tránsito inter-nodo, definida en la Security Configuration del cluster — exactamente el tipo de control que el skill 5.1.3 añadió al examen SCS-C03.",
  },
];
