const QUIZ_DATA = [
  {
    tag: "Envelope encryption",
    q: "¿Por qué KMS usa 'envelope encryption' (cifrar los datos con una data key, y esa data key con la CMK) en vez de cifrar directamente los datos con la KMS key?",
    options: [
      "Porque las KMS keys no pueden cifrar datos en absoluto, solo otras claves",
      "Porque las API de KMS tienen un límite de tamaño de payload muy pequeño (4KB para simétricas); envolver permite cifrar datos de cualquier tamaño localmente y solo enviar la data key (pequeña) a KMS",
      "Porque es un requisito de cumplimiento de HIPAA exclusivamente",
      "Porque así se evita pagar por las llamadas a la API de KMS",
    ],
    correct: 1,
    explain: "Las operaciones Encrypt/Decrypt directas de KMS están limitadas a ~4KB de payload. Para cifrar objetos grandes, se genera una data key (GenerateDataKey), se cifran los datos localmente con esa data key (sin límite de tamaño), y solo la data key (pequeña) se envía a KMS para ser cifrada/descifrada — de ahí 'envelope' (sobre).",
  },
  {
    tag: "Envelope encryption",
    q: "Tras usar GenerateDataKey para cifrar un archivo grande localmente, ¿qué debe hacer la aplicación con la data key en texto plano una vez terminado el cifrado?",
    options: [
      "Guardarla junto al archivo cifrado para poder descifrar más rápido después",
      "Enviarla de vuelta a KMS para que la almacene de forma segura",
      "Eliminarla de memoria inmediatamente; solo se conserva la versión CIFRADA de la data key (el 'encrypted blob') junto a los datos",
      "Cifrarla con una segunda data key distinta (doble envuelta)",
    ],
    correct: 2,
    explain: "GenerateDataKey devuelve DOS versiones: la data key en texto plano (se usa una vez para cifrar y se descarta de memoria) y la data key cifrada por la KMS key (esa sí se guarda junto a los datos). Para descifrar, se manda la data key cifrada a KMS Decrypt, que devuelve la versión en texto plano.",
  },
  {
    tag: "Tipos de KMS keys",
    q: "¿Cuál es la diferencia principal entre una AWS managed key (ej. aws/s3) y una customer managed key (CMK) en KMS?",
    options: [
      "Las AWS managed keys son gratis y las customer managed cuestan; aparte de eso son idénticas",
      "Solo las customer managed keys permiten escribir key policies personalizadas, habilitar rotación en la fecha que quieras, deshabilitarlas o programar su eliminación",
      "Las AWS managed keys soportan multi-Region y las customer managed no",
      "Las AWS managed keys son asimétricas por defecto",
    ],
    correct: 1,
    explain: "Las AWS managed keys (prefijo aws/) las crea y gestiona AWS automáticamente para un servicio concreto, con rotación anual obligatoria y sin key policy personalizable. Las customer managed keys te dan control total: key policy propia, rotación opcional configurable, se pueden deshabilitar/eliminar, y son las únicas que soportan multi-Region keys.",
  },
  {
    tag: "KMS grants",
    q: "¿Para qué se usa un KMS grant en vez de modificar la key policy directamente?",
    options: [
      "Un grant da permisos permanentes que sustituyen a la key policy",
      "Un grant permite delegar permisos temporales y programáticos sobre una key (ej. a un servicio de AWS actuando en tu nombre) sin editar la key policy, y se puede revocar individualmente sin afectar a otros permisos",
      "Los grants solo existen para claves asimétricas",
      "Un grant es simplemente otro nombre para una IAM policy adjunta a un rol",
    ],
    correct: 1,
    explain: "Los grants son un mecanismo de delegación de permisos más granular y dinámico que la key policy: se crean/revocan programáticamente (CreateGrant/RetireGrant/RevokeGrant), son ideales para que un servicio de AWS obtenga acceso temporal a tu key en tu nombre (ej. EBS cifrando un volumen), sin tener que reescribir la key policy cada vez.",
  },
  {
    tag: "KMS multi-Region keys",
    q: "Tienes una Multi-Region KMS key primaria en eu-west-1 replicada como réplica en us-east-1. Un objeto S3 se cifró con la réplica en us-east-1. ¿Puede descifrarse usando la key primaria en eu-west-1?",
    options: [
      "No, cada réplica es una key completamente independiente con material criptográfico distinto",
      "Sí: las Multi-Region keys comparten el MISMO material criptográfico subyacente entre primaria y réplicas, aunque tengan Key IDs distintos — lo cifrado con una réplica se puede descifrar con cualquier otra réplica o la primaria",
      "Solo si ambas están en la misma cuenta pero no en la misma Region",
      "Solo puede descifrarse creando manualmente una tercera key que combine ambas",
    ],
    correct: 1,
    explain: "A diferencia de crear KMS keys idénticas de forma independiente en cada región (que tendrían material criptográfico DISTINTO), las Multi-Region keys son réplicas que comparten el mismo material criptográfico. Esto permite cifrar en una región y descifrar en otra sin re-cifrar los datos — clave para DR y aplicaciones globales.",
  },
  {
    tag: "KMS vs CloudHSM",
    q: "Una empresa de servicios financieros necesita FIPS 140-2 Level 3, control exclusivo (single-tenant) del hardware criptográfico, y la capacidad de exportar el material de claves si migran de proveedor. ¿Qué servicio encaja mejor?",
    options: [
      "AWS KMS con customer managed keys",
      "AWS CloudHSM: HSM dedicado y single-tenant, control total del ciclo de vida de las claves, y permite exportarlas (a diferencia de KMS)",
      "AWS Secrets Manager",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "KMS es multi-tenant (aunque con fuertes garantías de aislamiento) y NUNCA permite exportar el material de la clave. CloudHSM te da un HSM dedicado (single-tenant), FIPS 140-2 Level 3, y control total incluyendo la posibilidad de exportar claves — al coste de gestionar tú mismo la infraestructura HSM (clusters, alta disponibilidad).",
  },
  {
    tag: "Imported key material",
    q: "¿Qué limitación tienen las KMS keys con material de clave IMPORTADO (BYOK) que NO tienen las generadas por AWS?",
    options: [
      "No pueden usarse para cifrar datos, solo para firmar",
      "No soportan la rotación automática anual gestionada por AWS; la rotación, si se quiere, hay que gestionarla manualmente re-importando material nuevo",
      "Solo pueden usarse con S3, no con otros servicios",
      "No pueden tener key policy personalizada",
    ],
    correct: 1,
    explain: "Cuando importas tu propio material de clave, AWS no puede rotarlo automáticamente por ti (no conoce el proceso para generarlo de nuevo). Puedes opcionalmente configurar una fecha de expiración del material, y la rotación se convierte en un proceso manual: crear una nueva KMS key e importar material nuevo.",
  },
  {
    tag: "External Key Store (XKS)",
    q: "¿Qué resuelve un KMS External Key Store (XKS)?",
    options: [
      "Permite generar claves más rápido que el KMS estándar",
      "Permite que el material de clave resida y se gestione FUERA de AWS (en tu propio gestor de claves on-premises o de terceros), mientras las aplicaciones de AWS siguen usando la API estándar de KMS",
      "Es simplemente un bucket S3 donde se guardan copias de las claves",
      "Sustituye a CloudHSM completamente",
    ],
    correct: 1,
    explain: "XKS conecta KMS a un gestor de claves externo (on-premises o de un tercero) a través de un proxy: el material de clave NUNCA entra en AWS, pero los servicios de AWS integrados con KMS pueden seguir usando esa clave de forma transparente. Es la opción para 'soberanía de clave' máxima manteniendo la integración nativa con AWS.",
  },
  {
    tag: "S3 Object Lock",
    q: "¿Cuál es la diferencia entre el modo Governance y el modo Compliance en S3 Object Lock?",
    options: [
      "Son sinónimos, cambia solo el nombre según la región",
      "En modo Governance, usuarios con el permiso s3:BypassGovernanceRetention pueden eliminar/sobrescribir el objeto antes de que expire el retention period; en modo Compliance, NADIE puede hacerlo — ni siquiera la cuenta root — hasta que expire",
      "Compliance solo aplica a buckets con versioning deshabilitado",
      "Governance es para objetos públicos y Compliance para privados",
    ],
    correct: 1,
    explain: "Ambos modos usan WORM (Write Once Read Many), pero Governance permite una válvula de escape para usuarios con permisos elevados específicos, mientras que Compliance es absoluto: una vez fijado el retention period, ni el usuario root puede borrar o modificar el objeto hasta que expire. Compliance se usa para requisitos regulatorios estrictos (ej. SEC 17a-4).",
  },
  {
    tag: "Glacier Vault Lock",
    q: "¿Qué caracteriza a una política de Glacier Vault Lock una vez que se confirma (lock-policy)?",
    options: [
      "Puede editarse libremente en cualquier momento por el administrador de la cuenta",
      "Se vuelve inmutable: no puede modificarse ni eliminarse nunca, ideal para cumplir requisitos regulatorios de retención de datos a largo plazo",
      "Expira automáticamente a los 90 días",
      "Solo aplica a objetos menores de 1MB",
    ],
    correct: 1,
    explain: "Vault Lock permite un periodo de prueba de 24 horas para validar la política antes de bloquearla ('lock'); una vez bloqueada, la política es permanente e inmutable — ni siquiera el propietario de la cuenta puede cambiarla, garantizando cumplimiento normativo verificable.",
  },
  {
    tag: "Integridad de datos",
    q: "Para verificar que un artefacto de software (ej. un binario descargado) no ha sido alterado en tránsito ni manipulado por un tercero, ¿qué mecanismo de AWS es el más apropiado?",
    options: [
      "S3 Versioning únicamente",
      "AWS Signer: firma digital de código con claves gestionadas centralmente, verificable por el receptor antes de ejecutar el artefacto",
      "MFA Delete en el bucket",
      "AWS Backup",
    ],
    correct: 1,
    explain: "AWS Signer permite firmar digitalmente código (ej. funciones Lambda, imágenes de contenedor, firmware IoT) para que el receptor pueda verificar criptográficamente que no ha sido alterado desde su creación — cubre la integridad, no solo la confidencialidad.",
  },
  {
    tag: "Lifecycle & retención",
    q: "Necesitas que los objetos de un bucket S3 se muevan automáticamente a Glacier Deep Archive tras 180 días y se eliminen definitivamente tras 7 años, sin intervención manual. ¿Qué mecanismo usas?",
    options: [
      "S3 Object Lock en modo Compliance con retención de 7 años",
      "S3 Lifecycle policies con reglas de transición (180 días → Deep Archive) y expiración (7 años → eliminación)",
      "AWS Backup con un plan diario",
      "Cross-Region Replication",
    ],
    correct: 1,
    explain: "S3 Lifecycle policies automatizan exactamente este patrón: reglas de TRANSITION entre clases de almacenamiento por antigüedad, y reglas de EXPIRATION para eliminación automática tras un periodo. Object Lock protege contra borrado antes de tiempo, pero no mueve ni elimina objetos por sí solo.",
  },
  {
    tag: "Backup & ransomware",
    q: "Como protección contra ransomware que cifra o borra tus datos de producción (incluyendo intentos de eliminar los backups), ¿qué característica de AWS Backup es la más relevante?",
    options: [
      "AWS Backup Vault Lock: hace los backups inmutables (WORM), impidiendo que se eliminen o modifiquen incluso por un administrador comprometido, durante el periodo configurado",
      "Cifrado en tránsito de los backups únicamente",
      "Aumentar la frecuencia de backups a cada hora",
      "AWS Backup no ofrece ninguna protección específica contra ransomware",
    ],
    correct: 0,
    explain: "AWS Backup Vault Lock aplica el mismo principio WORM que S3 Object Lock, pero a nivel de vault de backups completo: una vez bloqueado (especialmente en modo compliance), ni siquiera credenciales de administrador comprometidas pueden eliminar los backups antes de que expire su retención — mitigación clave contra ransomware.",
  },
  {
    tag: "AWS DataSync vs Backup vs DLM",
    q: "¿Cuál de estas afirmaciones distingue correctamente AWS DataSync de AWS Backup?",
    options: [
      "Son el mismo servicio con nombres distintos",
      "DataSync está diseñado para MIGRAR/SINCRONIZAR grandes volúmenes de datos entre on-premises y AWS (o entre servicios de almacenamiento AWS); AWS Backup está diseñado para crear y gestionar copias de RESPALDO centralizadas y programadas de recursos AWS",
      "DataSync solo funciona con bases de datos relacionales",
      "AWS Backup no soporta EFS ni FSx",
    ],
    correct: 1,
    explain: "DataSync mueve/sincroniza datos (ideal para migraciones o transferencias recurrentes on-prem↔AWS), mientras que AWS Backup centraliza políticas de backup (retención, programación, copiado cross-Region/cross-account) para EBS, RDS, DynamoDB, EFS, FSx, etc. Amazon Data Lifecycle Manager (DLM), por su parte, automatiza específicamente snapshots de EBS y AMIs.",
  },
  {
    tag: "TLS en tránsito",
    q: "Quieres forzar que todos los clientes que se conecten a tu Application Load Balancer usen TLS 1.2 o superior, rechazando cifrados obsoletos. ¿Qué configuras?",
    options: [
      "Una Security Group rule que bloquee el puerto 80",
      "Una security policy (ELBSecurityPolicy) en el listener HTTPS del ALB, seleccionando una política que exija TLS 1.2+",
      "Una bucket policy en S3",
      "Una NACL en la subnet del ALB",
    ],
    correct: 1,
    explain: "Los Elastic Load Balancers (ALB/NLB) usan 'security policies' predefinidas en el listener HTTPS/TLS que determinan qué versiones de TLS y qué cipher suites se aceptan. Elegir una política moderna (ej. ELBSecurityPolicy-TLS13-1-2-2021-06) fuerza TLS 1.2+ y rechaza conexiones con protocolos antiguos.",
  },
  {
    tag: "Conectividad privada",
    q: "¿Cuál es la diferencia principal entre AWS PrivateLink y un VPC Peering para acceder a un servicio en otra VPC/cuenta?",
    options: [
      "Son idénticos, solo cambia el nombre comercial",
      "PrivateLink expone el servicio como un endpoint unidireccional (el consumidor no ve el resto de la VPC del proveedor, ni hay solapamiento de rangos CIDR a gestionar); VPC Peering conecta las dos VPCs completas bidireccionalmente, exponiendo potencialmente toda la red",
      "VPC Peering es más seguro que PrivateLink en todos los casos",
      "PrivateLink solo funciona entre cuentas de la misma Organization",
    ],
    correct: 1,
    explain: "PrivateLink es ideal para exponer UN servicio concreto (ej. un SaaS de un proveedor) sin dar visibilidad de red completa ni preocuparte por solapamiento de CIDRs. VPC Peering conecta dos redes completas como si fueran una — más apropiado para relaciones de confianza total entre VPCs propias.",
  },
  {
    tag: "Client VPN vs Verified Access",
    q: "¿En qué se diferencia AWS Verified Access de AWS Client VPN?",
    options: [
      "Son el mismo servicio, Verified Access es solo el nombre nuevo de Client VPN",
      "Client VPN establece un túnel de red tradicional (el usuario 'entra' a la VPC); Verified Access aplica un modelo Zero Trust evaluando identidad + postura del dispositivo en cada request a una aplicación específica, sin exponer un túnel de red completo",
      "Verified Access solo funciona con aplicaciones on-premises",
      "Client VPN no soporta MFA",
    ],
    correct: 1,
    explain: "Client VPN es un modelo de acceso remoto clásico (VPN de túnel completo o dividido). AWS Verified Access implementa Zero Trust Network Access (ZTNA): evalúa señales de identidad (IAM Identity Center) y de postura del dispositivo en cada solicitud a nivel de aplicación, sin dar al usuario acceso de red general.",
  },
  {
    tag: "Cifrado inter-recurso",
    q: "¿Qué es 'Nitro encryption' en el contexto de instancias EC2 basadas en el Nitro System?",
    options: [
      "Un servicio separado que hay que activar y pagar aparte",
      "Cifrado automático de la memoria de la instancia y del tráfico entre instancias Nitro dentro de la infraestructura de AWS, sin intervención ni configuración del cliente",
      "Solo cifra el almacenamiento EBS adjunto",
      "Un tipo de KMS key exclusivo para instancias GPU",
    ],
    correct: 1,
    explain: "El Nitro System cifra automáticamente los datos en tránsito ENTRE instancias Nitro dentro de la misma región (y la memoria local de la instancia) como parte de la arquitectura subyacente, sin que el cliente tenga que configurar nada — un punto de examen sobre 'inter-resource encryption in transit' que suele sorprender porque no requiere acción del usuario.",
  },
  {
    tag: "Secrets Manager",
    q: "¿Qué ventaja tiene AWS Secrets Manager sobre Systems Manager Parameter Store (SecureString) para credenciales de una base de datos RDS?",
    options: [
      "Parameter Store no puede cifrar valores, Secrets Manager sí",
      "Secrets Manager ofrece ROTACIÓN AUTOMÁTICA nativa (con funciones Lambda integradas para RDS, Redshift, DocumentDB) sin trabajo adicional; Parameter Store requiere que construyas tú la lógica de rotación",
      "Secrets Manager es gratuito y Parameter Store no",
      "Parameter Store no soporta control de acceso vía IAM",
    ],
    correct: 1,
    explain: "Ambos cifran con KMS, pero Secrets Manager tiene rotación automática integrada out-of-the-box para varios motores de base de datos (actualiza la credencial Y la aplica en la base de datos en el mismo ciclo). Parameter Store es más barato para configuración general, pero rotación automática nativa es la razón principal para elegir Secrets Manager con credenciales de bases de datos.",
  },
  {
    tag: "Data masking",
    q: "Quieres que cualquier número de tarjeta de crédito que aparezca por error en tus logs de CloudWatch Logs se enmascare automáticamente antes de que un operador con permisos normales pueda verlo. ¿Qué mecanismo usas?",
    options: [
      "Una IAM policy que deniegue leer logs",
      "Una CloudWatch Logs data protection policy con detectores de datos sensibles (ej. tipo de dato 'Credit-Card-Number') que enmascara el valor en la vista, dejándolo visible solo a principals con permiso explícito de 'unmask'",
      "Cifrar el log group con KMS únicamente",
      "Amazon Macie, porque CloudWatch Logs no soporta masking",
    ],
    correct: 1,
    explain: "Las CloudWatch Logs data protection policies detectan tipos de datos sensibles predefinidos (tarjetas, SSN, credenciales AWS, etc.) o personalizados, y enmascaran automáticamente esos valores en las consultas/vistas — solo principals con el permiso IAM logs:Unmask ven el valor real. Amazon SNS tiene una capacidad de 'message data protection' equivalente para mensajes.",
  },
  {
    tag: "ACM & certificados",
    q: "¿Cuál es la diferencia clave entre un certificado público de AWS Certificate Manager (ACM) y uno emitido por AWS Private CA?",
    options: [
      "No hay diferencia, ambos son gratuitos y de confianza pública",
      "Los certificados públicos de ACM son gratuitos y de confianza pública (verificados por una CA pública, válidos en cualquier navegador); los de AWS Private CA son de confianza PRIVADA (solo válidos dentro de tu organización, donde distribuyes tú el certificado raíz) y tienen coste por CA activa",
      "AWS Private CA no puede emitir certificados TLS, solo firmar código",
      "ACM público requiere gestionar tú mismo la renovación",
    ],
    correct: 1,
    explain: "ACM emite certificados públicos gratuitos con renovación automática, válidos para dominios públicos verificables (ej. ELB, CloudFront). AWS Private CA crea tu propia jerarquía de CA privada para emitir certificados internos (mTLS entre microservicios, dispositivos IoT, IAM Roles Anywhere) que solo son de confianza donde tú distribuyas el certificado raíz.",
  },
  {
    tag: "Client-side vs server-side encryption",
    q: "En cifrado 'client-side' de un objeto S3, ¿dónde ocurre el cifrado de los datos?",
    options: [
      "En el lado del servidor de S3, antes de escribir a disco",
      "En el cliente/aplicación, ANTES de enviar los datos a S3 — S3 recibe y almacena únicamente el objeto ya cifrado, sin ver nunca el texto plano",
      "En un proxy de KMS gestionado por AWS",
      "Es idéntico a SSE-S3, solo cambia el nombre",
    ],
    correct: 1,
    explain: "En cifrado client-side (usando el AWS Encryption SDK o el S3 Encryption Client), el cifrado ocurre en la aplicación del cliente antes de que el dato viaje a AWS — S3 nunca ve el texto plano. En server-side (SSE-S3, SSE-KMS, SSE-C), S3 recibe el dato en claro (por TLS) y lo cifra él mismo al escribirlo a disco.",
  },
  {
    tag: "SSE-KMS vs SSE-C",
    q: "¿Qué caracteriza a SSE-C (Server-Side Encryption with Customer-Provided Keys) en S3, frente a SSE-KMS?",
    options: [
      "SSE-C es más seguro porque AWS nunca ve la clave; el cliente debe enviar la clave de cifrado en CADA solicitud (GET/PUT) por HTTPS, y AWS no la almacena — si pierdes la clave, pierdes el objeto para siempre",
      "SSE-C usa automáticamente KMS internamente",
      "SSE-C no requiere HTTPS",
      "SSE-C es la opción por defecto si no configuras nada",
    ],
    correct: 0,
    explain: "Con SSE-C, tú gestionas y envías la clave de cifrado AES-256 en cada solicitud; S3 la usa para cifrar/descifrar pero NUNCA la almacena. Máximo control, pero también máxima responsabilidad: si pierdes esa clave, el objeto es irrecuperable, ya que ni siquiera AWS Support puede ayudarte.",
  },
  {
    tag: "SageMaker AI / EMR / EKS",
    q: "En un cluster de Amazon EMR que procesa datos sensibles, ¿qué configuración cubre específicamente el cifrado del tráfico ENTRE los nodos del cluster (no solo el almacenamiento)?",
    options: [
      "Habilitar SSE-S3 en el bucket de origen de los datos",
      "In-transit encryption / inter-node encryption de EMR (TLS entre nodos del cluster, shuffle de Spark, etc.), configurable en la Security Configuration del cluster",
      "Activar CloudTrail para el cluster",
      "Usar un Security Group más restrictivo únicamente",
    ],
    correct: 1,
    explain: "El cifrado at-rest (EBS, S3) protege el almacenamiento, pero el tráfico interno entre nodos de un cluster distribuido (EMR, EKS, SageMaker AI) requiere una configuración explícita de cifrado en tránsito inter-nodo, definida en la Security Configuration del cluster — exactamente el tipo de control que el skill 5.1.3 añadió al examen SCS-C03.",
  },
  {
    tag: "KMS HMAC keys",
    q: "Necesitas generar y verificar HMACs (message authentication codes) para garantizar la integridad y autenticidad de mensajes entre dos sistemas, apoyándote en un HSM validado FIPS 140-2, sin gestionar tú mismo el material criptográfico. ¿Qué usarías?",
    options: [
      "Una KMS key simétrica estándar con las operaciones Encrypt/Decrypt",
      "Una KMS HMAC key (KeyUsage GENERATE_VERIFY_MAC) con las operaciones GenerateMac y VerifyMac",
      "AWS Signer",
      "Un secreto en Secrets Manager con rotación automática",
    ],
    correct: 1,
    explain: "Las HMAC KMS keys son un tipo de clave simétrica dedicado (KeyUsage GENERATE_VERIFY_MAC, conforme a RFC 2104) pensado exclusivamente para generar (GenerateMac) y verificar (VerifyMac) códigos de autenticación de mensajes dentro del límite de seguridad de KMS; no pueden usarse con Encrypt/Decrypt ni con GenerateDataKey.",
  },
  {
    tag: "KMS ECDH key agreement",
    q: "Dos organizaciones distintas quieren establecer un secreto compartido entre sus sistemas para derivar después una clave simétrica de sesión, sin transmitir ninguna clave privada por la red. ¿Qué operación de KMS permite esto usando claves asimétricas EC?",
    options: [
      "GenerateDataKeyPair",
      "DeriveSharedSecret, sobre una KMS key asimétrica NIST EC (o SM2) con KeyUsage KEY_AGREEMENT, usando el algoritmo ECDH (Elliptic Curve Diffie-Hellman)",
      "GenerateRandom",
      "Sign y Verify sobre una key RSA",
    ],
    correct: 1,
    explain: "DeriveSharedSecret usa el primitivo ECDH Cofactor para derivar un secreto compartido a partir de tu KMS key asimétrica (KeyUsage KEY_AGREEMENT) y la clave pública SPKI/DER de la otra parte, dentro del límite de seguridad FIPS 140-2 del HSM de KMS — sin que ninguna clave privada salga de KMS ni se transmita por la red.",
  },
  {
    tag: "S3 Bucket Keys",
    q: "Una empresa cifra millones de objetos S3 con SSE-KMS y observa que el coste de las llamadas a la API de KMS (GenerateDataKey, Decrypt) es desproporcionadamente alto frente al almacenamiento. ¿Qué opción de S3, activable sin cambios en la aplicación cliente, reduce drásticamente ese coste?",
    options: [
      "Cambiar a SSE-S3",
      "Habilitar S3 Bucket Keys: genera una clave de bucket de corta duración a partir de la KMS key y la reutiliza para cifrar múltiples objetos, reduciendo hasta un 99% las llamadas a KMS",
      "Habilitar S3 Transfer Acceleration",
      "Migrar a DSSE-KMS",
    ],
    correct: 1,
    explain: "Con S3 Bucket Keys, S3 solicita una clave a nivel de bucket a KMS una sola vez (de corta duración) y la usa para derivar las data keys de múltiples objetos localmente, en vez de llamar a KMS por cada objeto — reduce hasta un 99% las solicitudes a KMS sin cambiar cómo la aplicación sube/descarga objetos. No es compatible con DSSE-KMS.",
  },
  {
    tag: "S3 DSSE-KMS",
    q: "Un cliente del sector defensa necesita cumplir con CNSSP 15 / Data-at-Rest Capability Package, que exige DOS capas independientes de cifrado AES-256 sobre los objetos almacenados en S3. ¿Qué método de cifrado de S3 cumple este requisito?",
    options: [
      "SSE-KMS estándar con S3 Bucket Keys habilitado",
      "SSE-C",
      "DSSE-KMS (dual-layer server-side encryption): aplica dos capas independientes de cifrado AES-256 — una con una data key de KMS y otra con una clave adicional gestionada por S3",
      "Cifrado client-side con el AWS Encryption SDK únicamente",
    ],
    correct: 2,
    explain: "DSSE-KMS cifra el objeto dos veces de forma independiente: una capa con una data key generada por KMS y otra capa adicional con una clave gestionada por S3, cumpliendo guías CNSA de doble capa para cargas de trabajo altamente reguladas. No soporta S3 Bucket Keys y tiene un coste adicional por GB frente a SSE-KMS.",
  },
  {
    tag: "AWS Payment Cryptography",
    q: "Una fintech migra su procesamiento de tarjetas de pago (validación de PIN, generación de criptogramas, gestión de claves conforme a estándares de la industria de pagos) desde HSMs on-premises. ¿Qué servicio de AWS está diseñado específicamente para sustituir esos HSMs de pago, cumpliendo PCI PIN y PCI P2PE?",
    options: [
      "AWS CloudHSM genérico",
      "AWS KMS con customer managed keys",
      "AWS Payment Cryptography: servicio gestionado con HSMs certificados PCI PTS, diseñado para operaciones criptográficas de la industria de pagos (emisión de tarjetas, validación de PIN, procesamiento de transacciones)",
      "AWS Secrets Manager",
    ],
    correct: 2,
    explain: "AWS Payment Cryptography es un servicio gestionado específico para operaciones criptográficas de pagos (débito, crédito, tarjetas prepago), con HSMs certificados bajo PCI PTS y con paquetes de conformidad PCI PIN y PCI P2PE disponibles vía AWS Artifact — a diferencia de CloudHSM o KMS, que son de propósito general y no están diseñados para los flujos específicos de la industria de pagos.",
  },
  {
    tag: "Nitro Enclaves & atestación KMS",
    q: "Una aplicación procesa datos altamente sensibles dentro de un AWS Nitro Enclave y necesita que KMS solo descifre datos para ESE enclave concreto (identificado por el hash de su imagen), no para ningún otro proceso de la instancia padre ni de otro enclave. ¿Qué mecanismo lo garantiza?",
    options: [
      "Un KMS grant estándar sin condiciones adicionales",
      "El cifrado automático de memoria del Nitro System",
      "Atestación criptográfica de KMS: la llamada a Decrypt/GenerateDataKey incluye un documento de atestación firmado por el hipervisor Nitro, y la key policy usa la condición kms:RecipientAttestation:ImageSha384 para verificar el PCR0 (hash de la imagen) antes de re-cifrar la respuesta con la clave pública del enclave",
      "KMS Multi-Region keys",
    ],
    correct: 2,
    explain: "Al llamar a Decrypt/DeriveSharedSecret/GenerateDataKey/GenerateDataKeyPair/GenerateRandom con un AttestationDocument firmado por el hipervisor Nitro, KMS devuelve el resultado re-cifrado con la clave pública del propio documento en vez de en texto plano, y la condición kms:RecipientAttestation:ImageSha384 en la key policy permite restringir el acceso a enclaves cuya imagen (PCR0) coincida exactamente con la esperada.",
  },
  {
    tag: "ALB mutual TLS (mTLS)",
    q: "Necesitas que tu Application Load Balancer autentique la identidad del CLIENTE (no solo cifrar el canal) verificando su certificado X.509 contra una CA de confianza, antes de reenviar la solicitud al target. ¿Qué configuras?",
    options: [
      "Una security policy TLS 1.3 en el listener",
      "Mutual TLS (mTLS) en el listener HTTPS del ALB en modo 'verify', con un Trust Store que contenga el bundle de la CA (de un tercero o de AWS Private CA) y, opcionalmente, listas de revocación",
      "AWS WAF con una regla basada en tasa (rate-based rule)",
      "Un Security Group que solo permita el CIDR del cliente",
    ],
    correct: 1,
    explain: "El ALB soporta mTLS con dos modos: 'passthrough' (reenvía la cadena de certificados del cliente al target vía headers HTTP, sin validarla) y 'verify' (el propio ALB valida el certificado del cliente contra un Trust Store con el CA bundle y CRLs). Verify es la opción para que el ALB ofloadee la autenticación de cliente basada en certificado.",
  },
  {
    tag: "Amazon Macie — descubrimiento automatizado",
    q: "Quieres visibilidad continua y de bajo coste de qué buckets S3 de toda tu organización podrían contener datos sensibles, sin definir y ejecutar manualmente un job de escaneo completo sobre cada bucket. ¿Qué capacidad de Macie usas?",
    options: [
      "Un sensitive data discovery job programado sobre el 100% de los objetos de cada bucket",
      "Automated sensitive data discovery: Macie evalúa continuamente el inventario de buckets S3 y usa muestreo representativo de objetos para dar visibilidad amplia y una puntuación de sensibilidad por bucket, con menor coste que un escaneo completo",
      "AWS Config rules únicamente",
      "GuardDuty S3 Protection",
    ],
    correct: 1,
    explain: "Macie ofrece dos modos: 'automated sensitive data discovery' (evaluación continua y muestreo representativo entre cuentas/buckets para visibilidad amplia y de bajo coste, con un data map interactivo y sensitivity score por bucket) y 'sensitive data discovery jobs' (análisis dirigido y más exhaustivo sobre buckets u objetos concretos, más costoso porque revisa más objetos).",
  },
  {
    tag: "AWS Private CA — short-lived certificate mode",
    q: "Una plataforma emite cientos de miles de certificados de vida muy corta (7 días o menos) al mes para autenticar cargas de trabajo efímeras, y el coste mensual fijo de la CA en modo general-purpose resulta desproporcionado. ¿Qué opción reduce el coste?",
    options: [
      "Migrar a ACM público",
      "Usar AWS Private CA en modo short-lived certificate: coste fijo mensual de la CA mucho menor que el modo general-purpose, a cambio de que los certificados emitidos solo puedan tener una validez máxima de 7 días",
      "Desactivar la comprobación de revocación OCSP",
      "Usar CloudHSM para emitir los certificados directamente",
    ],
    correct: 1,
    explain: "AWS Private CA ofrece dos modos: general-purpose (cualquier periodo de validez, mayor coste fijo mensual por CA) y short-lived certificate mode (coste fijo mensual mucho menor, pero los certificados emitidos no pueden superar los 7 días de validez) — ideal para identidades efímeras de cargas de trabajo (contenedores, funciones) que rotan certificados con frecuencia.",
  },
  {
    tag: "Secrets Manager multi-Region",
    q: "Una aplicación con lectores en dos regiones necesita acceder al mismo secreto de base de datos con baja latencia en ambas, y que al rotar la credencial en la región primaria, el nuevo valor se propague automáticamente sin gestionar la rotación por separado en cada región. ¿Qué característica de Secrets Manager usas?",
    options: [
      "Cross-Region Replication de S3 aplicada a un export del secreto",
      "Multi-Region secrets de Secrets Manager (ReplicateSecretToRegions): crea réplicas sincronizadas en otras regiones; al rotar el secreto primario, el nuevo valor se propaga automáticamente a todas las réplicas",
      "Crear secretos idénticos de forma manual e independiente en cada región",
      "KMS Multi-Region keys, que replican también el valor del secreto automáticamente",
    ],
    correct: 1,
    explain: "Secrets Manager permite replicar un secreto (valor cifrado y metadatos) a otras regiones con ReplicateSecretToRegions; si la rotación está activada en el secreto primario, el nuevo valor se propaga automáticamente a todas las réplicas sin gestionarlas individualmente. Cada réplica se factura como un secreto independiente, y una réplica puede promocionarse a secreto independiente si hace falta.",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "Una carga de trabajo on-premises (fuera de AWS) necesita obtener credenciales temporales de IAM para llamar a la API de AWS, sin usar access keys de larga duración almacenadas en el servidor. Ya existe una PKI interna. ¿Qué solución encaja?",
    options: [
      "Access keys IAM rotadas manualmente cada 90 días",
      "IAM Roles Anywhere: registra tu CA (por ejemplo, una emitida por AWS Private CA o tu propia PKI) como trust anchor; el servidor presenta un certificado X.509 en una llamada CreateSession y recibe credenciales temporales vía STS, asumiendo un rol IAM",
      "AWS Client VPN",
      "Amazon Cognito Identity Pools",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere establece confianza entre tu PKI existente (registrada como trust anchor) y AWS: cargas de trabajo fuera de AWS presentan un certificado X.509 emitido por esa CA para llamar a CreateSession y obtener credenciales de sesión temporales de un rol IAM vía STS, eliminando la necesidad de access keys de larga duración en sistemas on-premises.",
  },
  {
    tag: "EBS encryption by default",
    q: "Habilitas la configuración de cuenta 'EBS encryption by default' en una región donde ya existen volúmenes EBS sin cifrar en uso. ¿Qué ocurre con esos volúmenes existentes?",
    options: [
      "Se cifran automáticamente la próxima vez que se adjuntan a una instancia",
      "No se ven afectados: la configuración solo aplica a los volúmenes y copias de snapshot creados DESPUÉS de activarla; los existentes permanecen sin cifrar y no pueden cifrarse retroactivamente sin crear un nuevo volumen o snapshot",
      "Se cifran automáticamente en el siguiente snapshot programado",
      "Se eliminan automáticamente por incumplimiento de política",
    ],
    correct: 1,
    explain: "'EBS encryption by default' es una configuración a nivel de región que solo afecta a los volúmenes y copias de snapshot creados a partir de ese momento. Un volumen o snapshot solo puede cifrarse en el momento de su creación — no existe forma de cifrar retroactivamente uno ya existente sin crear una copia cifrada nueva a partir de él.",
  },
  {
    tag: "RDS encryption at rest",
    q: "Tienes una instancia RDS de producción creada SIN cifrado en reposo (storage encryption deshabilitado). ¿Cómo puedes habilitar el cifrado sin perder los datos?",
    options: [
      "Modificando la instancia directamente con 'aws rds modify-db-instance --storage-encrypted'",
      "No es posible modificar el cifrado de una instancia existente: hay que crear un snapshot, copiar ese snapshot habilitando cifrado (con una KMS key), restaurar una nueva instancia a partir del snapshot cifrado, y redirigir la aplicación a la nueva instancia",
      "Habilitando SSE-KMS en la instancia",
      "Activando 'EBS encryption by default' en la región",
    ],
    correct: 1,
    explain: "El cifrado en reposo de RDS solo puede establecerse en el momento de creación de la instancia (o al restaurar desde un snapshot cifrado); no existe una operación de modify para cifrar una instancia existente. El patrón estándar es: snapshot → copiar snapshot con cifrado habilitado → restaurar instancia desde el snapshot cifrado → cutover de la aplicación.",
  },
  {
    tag: "kms:ViaService",
    q: "Quieres que una customer managed KMS key solo pueda ser usada por Amazon S3 (no por EBS, RDS, ni llamadas directas de un usuario a la API de KMS), incluso si esos otros principals tienen permisos IAM sobre la key. ¿Qué condición añades a la key policy?",
    options: [
      "aws:SourceIp",
      "kms:ViaService, con el valor s3.<region>.amazonaws.com, en el Condition de la statement que permite kms:Decrypt / kms:GenerateDataKey",
      "aws:PrincipalOrgID",
      "kms:GrantIsForAWSResource",
    ],
    correct: 1,
    explain: "kms:ViaService restringe el uso de una KMS key a solicitudes que provienen de un servicio de AWS específico (identificado por su principal de servicio, ej. s3.eu-west-1.amazonaws.com), incluso si el principal que hace la llamada tiene permisos IAM generales sobre la key — es la forma de decir 'esta key solo se usa a través de S3', bloqueando el uso directo vía API o desde otros servicios.",
  },
  {
    tag: "RDS — master password gestionado por Secrets Manager",
    q: "Quieres eliminar por completo la exposición en texto plano de la contraseña maestra de una nueva base de datos RDS durante su creación, y que AWS gestione la rotación periódica de esa contraseña sin que escribas tú una función Lambda. ¿Qué opción de RDS usas?",
    options: [
      "Configurar manualmente Secrets Manager y una Lambda de rotación después de crear la instancia",
      "Activar 'Manage master credentials in AWS Secrets Manager' al crear (o modificar) la instancia: RDS genera la contraseña, la almacena directamente en Secrets Manager (nunca la ves en claro) y gestiona la rotación automática (cada 7 días por defecto) sin Lambda propia",
      "Usar Parameter Store SecureString con una política de rotación",
      "Deshabilitar la autenticación con contraseña y usar solo IAM database authentication",
    ],
    correct: 1,
    explain: "Al habilitar 'Manage master credentials in AWS Secrets Manager', RDS genera y almacena la contraseña maestra directamente en Secrets Manager (nunca se muestra en claro durante la creación) y gestiona el ciclo de vida completo, incluida la rotación automática periódica, sin que tengas que escribir ni desplegar una función Lambda de rotación tú mismo.",
  },
  {
    tag: "S3 Object Lock — Legal Hold",
    q: "Necesitas preservar un objeto S3 indefinidamente por un litigio en curso, sin saber cuánto tiempo durará, y sin depender de fijar una fecha de retención concreta en modo Governance o Compliance. ¿Qué mecanismo de Object Lock usas?",
    options: [
      "Un retention period en modo Compliance con una fecha muy lejana en el futuro (ej. año 2099)",
      "Legal Hold: aplica la misma protección WORM que un retention period pero SIN fecha de expiración; permanece activo hasta que un principal con permisos explícitos lo retira, y es independiente del modo Governance/Compliance",
      "S3 Versioning con MFA Delete",
      "Glacier Vault Lock",
    ],
    correct: 1,
    explain: "Un Legal Hold ofrece la misma protección WORM que un retention period, pero sin fecha de expiración: permanece activo hasta que alguien con el permiso s3:PutObjectLegalHold lo retira explícitamente. Un objeto puede tener retention period, legal hold, ambos o ninguno — son mecanismos independientes entre sí.",
  },
  {
    tag: "Rotación automática de KMS — alcance",
    q: "Habilitas la rotación automática anual en una KMS key. ¿Para cuáles de las siguientes NO está disponible esa rotación automática, obligando a rotación manual o bajo demanda?",
    options: [
      "Solo para las claves simétricas de cifrado generadas por AWS (origen AWS_KMS)",
      "Claves asimétricas, claves HMAC, claves con material importado (origen EXTERNAL) y claves en un custom key store (CloudHSM key store o External Key Store) — la rotación automática solo aplica a claves simétricas de cifrado con material generado por AWS",
      "Únicamente las AWS managed keys (aws/s3, etc.)",
      "Ninguna: todas las KMS keys soportan rotación automática",
    ],
    correct: 1,
    explain: "La rotación automática de KMS solo está disponible para KMS keys simétricas de cifrado con material generado por AWS (origen AWS_KMS). No está disponible para claves asimétricas, claves HMAC, claves con material importado ni claves en un custom key store — para estas últimas, la alternativa es la rotación manual o bajo demanda (RotateKeyOnDemand, disponible también para claves simétricas con material importado).",
  },
  {
    tag: "CloudTrail & auditoría de uso de KMS",
    q: "Sospechas que una customer managed KMS key ha sido usada para descifrar datos por un principal no autorizado. ¿Dónde consultas quién invocó la operación Decrypt sobre esa key, cuándo, y desde qué principal/rol?",
    options: [
      "En la key policy de la KMS key",
      "En AWS CloudTrail: cada llamada a la API de KMS (Decrypt, GenerateDataKey, Encrypt...) queda registrada como evento con el principal invocador, el Key ID, el origen y el resultado de la llamada",
      "En Amazon Macie",
      "En AWS Config, que registra las invocaciones de API en tiempo real",
    ],
    correct: 1,
    explain: "Todas las operaciones de la API de KMS quedan registradas como eventos de CloudTrail (activado por defecto como 'management events'), incluyendo el principal (usuario/rol) que hizo la llamada, la hora, el Key ID afectado, la IP de origen y si la llamada tuvo éxito o fue denegada — la fuente de verdad para auditar el uso de una KMS key.",
  },
  {
    tag: "Uso cross-account de una KMS key",
    q: "Un rol de la cuenta B debe descifrar objetos cifrados con una KMS key gestionada por el cliente que vive en la cuenta A. ¿Qué DOS condiciones deben cumplirse?",
    options: [
      "La key policy de la clave en la cuenta A debe permitir el acceso al principal de la cuenta B",
      "La política de identidad del rol en la cuenta B debe permitir kms:Decrypt sobre esa clave",
      "La clave debe ser una AWS managed key en lugar de una customer managed key",
      "Ambas cuentas deben estar en la misma Región y en la misma Organization",
    ],
    correct: [0, 1],
    explain: "Igual que en el acceso cross-account a roles, KMS exige <b>las dos puntas</b>: key policy en el propietario e identity policy en el consumidor. Precisamente las <b>AWS managed keys no se pueden compartir</b> entre cuentas — por eso el caso de uso cross-account obliga a una customer managed key, justo lo contrario de la opción C. Y no hace falta Organizations; la Región sí importa porque las claves son regionales, pero eso no es lo que falta aquí.",
  },
  {
    tag: "Envelope encryption",
    q: "¿Qué DOS afirmaciones describen correctamente el envelope encryption tal y como lo implementa AWS KMS?",
    options: [
      "Los datos se cifran con una data key, y esa data key se cifra a su vez con la KMS key",
      "La data key en claro se usa en memoria y se descarta; solo se almacena su versión cifrada junto al dato",
      "Los datos viajan a KMS para ser cifrados allí, sin importar su tamaño",
      "La KMS key sale del servicio para cifrar los datos en el cliente",
    ],
    correct: [0, 1],
    explain: "El envelope encryption existe justamente para <b>no</b> mandar los datos a KMS: KMS cifra la data key (operación pequeña y rápida) y el cifrado masivo ocurre localmente. La operación directa <code>Encrypt</code> de KMS está limitada a 4 KB, lo que descarta la opción C para datos reales. Y el material criptográfico de una KMS key <b>nunca sale sin cifrar</b> del servicio: es su garantía fundamental.",
  },
  {
    tag: "Retención inmutable en S3",
    q: "Un requisito regulatorio exige que ciertos objetos de S3 no puedan borrarse durante 7 años. ¿Qué DOS afirmaciones sobre S3 Object Lock son correctas?",
    options: [
      "En modo compliance, ningún usuario — incluido el root de la cuenta — puede borrar el objeto antes de que expire la retención",
      "Object Lock requiere que el versionado esté habilitado en el bucket",
      "En modo governance nadie puede sobrescribir la retención bajo ninguna circunstancia",
      "Object Lock puede activarse sobre objetos ya existentes sin ninguna configuración previa del bucket",
    ],
    correct: [0, 1],
    explain: "<b>Compliance</b> es el modo verdaderamente inmutable (ni root puede saltárselo) y Object Lock <b>depende del versionado</b>, porque protege versiones concretas. El modo <b>governance</b> sí admite excepción para quien tenga el permiso <code>s3:BypassGovernanceRetention</code> — esa es justo la diferencia entre los dos modos y lo que suele preguntarse. Y Object Lock se habilita a nivel de bucket, no se improvisa sobre objetos existentes en un bucket que no lo tiene.",
  },
  {
    tag: "Rotación en Secrets Manager",
    q: "Quieres rotar automáticamente la contraseña de una base de datos RDS almacenada en Secrets Manager. ¿Qué DOS elementos intervienen?",
    options: [
      "Una función Lambda de rotación con permiso para cambiar la credencial en la base de datos",
      "Una programación de rotación que define cada cuánto se ejecuta el proceso",
      "Un bucket S3 donde Secrets Manager deposita la contraseña anterior en texto plano",
      "Una regla de AWS Config que cambie la contraseña cuando detecte que ha caducado",
    ],
    correct: [0, 1],
    explain: "La rotación se apoya en una <b>Lambda</b> (AWS provee plantillas para las bases de datos soportadas) y una <b>programación</b>. Secrets Manager mantiene las versiones del secreto con etiquetas como AWSCURRENT y AWSPREVIOUS dentro del propio servicio y cifradas con KMS: jamás escribe credenciales en claro en un bucket. Y Config <b>evalúa</b> configuración, no rota credenciales.",
  },
];
