const QUIZ_DATA = [
  {
    tag: "AWS Organizations",
    q: "¿Qué habilita AWS Organizations que no existe al gestionar cuentas de AWS de forma completamente independiente?",
    options: [
      "Facturación consolidada, jerarquía de OUs para aplicar guardrails (SCP/RCP/Declarative Policies) por grupo de cuentas, y compartición de recursos entre cuentas de la organización",
      "Solo la facturación consolidada, sin ningún otro beneficio",
      "Organizations sustituye la necesidad de tener múltiples cuentas de AWS",
      "Solo funciona con un máximo de 5 cuentas",
    ],
    correct: 0,
    explain: "Organizations permite estructurar cuentas en OUs (Organizational Units) jerárquicas, aplicar guardrails que se heredan automáticamente por OU (SCPs, RCPs, Declarative Policies, AI opt-out policies), facturación consolidada, y compartir recursos (vía RAM) o gestionar servicios de seguridad de forma centralizada entre todas las cuentas.",
  },
  {
    tag: "AWS Control Tower",
    q: "¿Qué automatiza AWS Control Tower que AWS Organizations por sí solo no hace?",
    options: [
      "Nada adicional, son el mismo servicio con nombres distintos",
      "Despliega una 'landing zone' completa con estructura de OUs recomendada, cuentas base (Log Archive, Audit/Security Tooling) ya configuradas, guardrails preventivos Y detectivos preconfigurados, y un Account Factory para aprovisionar cuentas nuevas ya conformes desde el primer minuto",
      "Control Tower solo gestiona facturación",
      "Solo puede usarse en cuentas completamente nuevas, nunca en organizaciones existentes",
    ],
    correct: 1,
    explain: "Control Tower se construye SOBRE Organizations, automatizando el despliegue de una landing zone completa: estructura de OUs, cuentas Log Archive y Audit ya creadas y configuradas, guardrails (controls) preventivos y detectivos ya activados, y Account Factory para que cada cuenta nueva nazca ya conforme a la política — soporta tanto entornos nuevos como 'landing zone existente' (extender Organizations ya en uso).",
  },
  {
    tag: "Controles de Control Tower",
    q: "En Control Tower, ¿qué diferencia a un control PREVENTIVO de uno DETECTIVO?",
    options: [
      "Son sinónimos exactos",
      "Un control preventivo IMPIDE que la acción no conforme ocurra (implementado normalmente como una SCP que bloquea la API); un control detectivo IDENTIFICA recursos que ya están en un estado no conforme (implementado como una Config Rule) para poder remediarlos después",
      "Los controles detectivos son siempre más estrictos que los preventivos",
      "Solo los controles preventivos pueden aplicarse a nivel de OU",
    ],
    correct: 1,
    explain: "Preventivo = bloquea ANTES (ej. una SCP que deniega crear buckets S3 públicos). Detectivo = detecta DESPUÉS (ej. una Config Rule que marca como NON_COMPLIANT un bucket que ya quedó público por algún otro camino). Control Tower combina ambos tipos para cubrir tanto la prevención como los casos donde la prevención no fue suficiente.",
  },
  {
    tag: "AI services opt-out policies",
    q: "Tu organización maneja datos altamente confidenciales y quiere garantizar que NINGÚN servicio de IA/ML de AWS (como ciertas funciones de mejora de modelos) use esos datos para entrenamiento, en todas las cuentas de la organización. ¿Qué mecanismo de Organizations aplicas?",
    options: [
      "Una SCP genérica que bloquee todos los servicios de IA",
      "Una AI services opt-out policy: un tipo de política de organización específico para controlar de forma centralizada si los servicios de IA de AWS pueden usar el contenido de tus cuentas para mejorar sus modelos",
      "Activar GuardDuty en modo estricto",
      "Una RCP sobre el servicio Bedrock únicamente",
    ],
    correct: 1,
    explain: "Las AI services opt-out policies son un tipo de política de organización dedicado (junto a SCP, RCP y Declarative Policies) pensado específicamente para controlar de forma centralizada y heredable si los servicios de IA de AWS pueden usar los datos de tus cuentas para entrenamiento/mejora de modelos — más preciso y mantenible que intentar replicar ese control con una SCP genérica.",
  },
  {
    tag: "Delegated administrator",
    q: "¿Por qué se recomienda designar una cuenta 'delegated administrator' para servicios como GuardDuty, Security Hub o IAM Access Analyzer, en vez de gestionarlos desde la cuenta de management?",
    options: [
      "Es obligatorio técnicamente, no hay alternativa",
      "Reduce el uso operativo de la cuenta de management (que debería reservarse casi exclusivamente para tareas de Organizations en sí) y sigue el principio de mínimo privilegio: el equipo de seguridad opera desde una cuenta dedicada, sin necesitar las credenciales más sensibles de toda la organización",
      "La cuenta de management no puede tener GuardDuty activado nunca",
      "Delegated administrator solo aplica a Control Tower",
    ],
    correct: 1,
    explain: "La buena práctica es minimizar el uso day-to-day de la cuenta de management (comprometerla comprometería potencialmente TODA la organización). Delegar la administración de servicios de seguridad a una cuenta dedicada (típicamente la de 'Audit' o 'Security Tooling') permite al equipo de seguridad operar con visibilidad de toda la organización sin tocar la cuenta de management en el día a día.",
  },
  {
    tag: "Root user & break-glass",
    q: "¿Qué es un procedimiento 'break-glass' en el contexto de gestión de la cuenta root?",
    options: [
      "Un procedimiento para eliminar permanentemente la cuenta root",
      "Un proceso documentado y controlado de EMERGENCIA para acceder a la cuenta root (credenciales normalmente guardadas de forma segura y no usadas nunca) cuando es estrictamente necesario, con MFA físico y aprobación/auditoría reforzada",
      "Una alarma de CloudWatch que se dispara al iniciar sesión con root",
      "Solo aplica a la cuenta de management, nunca a cuentas miembro",
    ],
    correct: 1,
    explain: "Break-glass describe el acceso de emergencia: las credenciales root normalmente no se usan NUNCA para operación diaria (con MFA hardware guardado de forma segura, a menudo con doble custodia), y solo se accede a través de un procedimiento documentado, auditado y con aprobación cuando surge una necesidad genuinamente excepcional (ej. recuperar el control de una cuenta comprometida).",
  },
  {
    tag: "Root access management centralizado",
    q: "¿Qué capacidad de Organizations permite gestionar de forma centralizada las credenciales root de las cuentas MIEMBRO sin tener que hacer el proceso de recuperación de contraseña en cada una?",
    options: [
      "IAM Identity Center por sí solo",
      "Centralized root access management: permite a la cuenta de management invocar de forma centralizada un conjunto acotado de acciones privilegiadas de root en cuentas miembro, y eliminar de forma efectiva la necesidad de credenciales root utilizables en esas cuentas",
      "AWS Config",
      "Amazon Detective",
    ],
    correct: 1,
    explain: "Esta capacidad (parte del skill 6.1.5) permite gestionar el acceso root de las cuentas miembro desde la cuenta de management de forma centralizada, reduciendo drásticamente el riesgo de credenciales root sueltas y sin gestionar en decenas de cuentas — combinable con MFA obligatorio a nivel de organización.",
  },
  {
    tag: "Infrastructure as Code a escala",
    q: "¿Qué servicio de AWS permite desplegar el MISMO stack de CloudFormation (ej. una configuración base de seguridad) automáticamente en cientos de cuentas y regiones de una organización, de forma centralizada?",
    options: [
      "AWS Config Conformance Packs únicamente",
      "AWS CloudFormation StackSets: define el stack una vez y lo despliega/actualiza/elimina de forma centralizada en todas las cuentas y regiones objetivo (incluso automáticamente en cuentas NUEVAS si se integra con Organizations)",
      "Amazon Q Developer",
      "AWS Service Catalog exclusivamente",
    ],
    correct: 1,
    explain: "StackSets extiende CloudFormation para gestionar el mismo stack como una unidad a través de múltiples cuentas/regiones, con la opción de integrarse con AWS Organizations para desplegar AUTOMÁTICAMENTE en cuentas que se unan a una OU en el futuro — clave para el skill 6.2.1 sobre despliegue consistente a escala.",
  },
  {
    tag: "Validación de IaC",
    q: "¿Qué diferencia a CloudFormation Guard de cfn-lint?",
    options: [
      "Son exactamente lo mismo con nombres distintos",
      "cfn-lint valida SINTAXIS y buenas prácticas generales de una plantilla CloudFormation; CloudFormation Guard evalúa la plantilla contra REGLAS DE POLICY personalizadas que tú defines (ej. 'todo bucket S3 debe tener cifrado'), permitiendo bloquear despliegues no conformes en el pipeline antes de aplicarlos",
      "CloudFormation Guard solo funciona con Terraform",
      "cfn-lint reemplaza la necesidad de tener SCPs",
    ],
    correct: 1,
    explain: "cfn-lint es un linter general (sintaxis, tipos de recursos válidos, mejores prácticas). CloudFormation Guard es un motor de políticas como código (policy-as-code) donde TÚ escribes las reglas de negocio/seguridad específicas que la plantilla debe cumplir — ambos se integran en el pipeline de CI/CD para detectar problemas antes del despliegue (shift-left), complementando (no sustituyendo) los guardrails en runtime como SCP/Config.",
  },
  {
    tag: "Estrategia de tagging",
    q: "Más allá de la organización visual, ¿qué caso de uso de seguridad/gobierno habilita una estrategia de tagging consistente (ej. tag 'environment' o 'data-classification')?",
    options: [
      "Ninguno, los tags son solo cosméticos",
      "Permite escribir políticas ABAC (acceso basado en atributos), Conformance Packs y SCPs condicionales que se aplican automáticamente según el tag del recurso (ej. 'solo cifrado obligatorio en recursos con data-classification=confidential'), y facilita atribuir costes/responsables durante una investigación",
      "Los tags solo sirven para Cost Explorer, sin relación con seguridad",
      "Los tags sustituyen la necesidad de usar IAM",
    ],
    correct: 1,
    explain: "Una estrategia de tagging consistente es la base de ABAC (visto en el módulo de IAM), de conformance packs condicionales, y de la capacidad de responder rápido durante un incidente ('¿qué recursos son de producción?', '¿quién es el owner de este recurso?') — el skill 6.2.2 lo trata como un pilar de gobierno, no solo de FinOps.",
  },
  {
    tag: "AWS Firewall Manager",
    q: "Tienes WAF, Security Groups y AWS Network Firewall desplegados de forma inconsistente en decenas de cuentas, y quieres aplicar y mantener una política de seguridad de red uniforme en todas ellas desde un único lugar. ¿Qué servicio usas?",
    options: [
      "AWS Firewall Manager: aplica y mantiene automáticamente políticas de WAF, Shield Advanced, Security Groups y Network Firewall a través de todas las cuentas y recursos de la organización, incluso los que se creen en el futuro",
      "AWS Config Rules únicamente",
      "AWS RAM",
      "Amazon Inspector",
    ],
    correct: 0,
    explain: "Firewall Manager centraliza la gestión de políticas de seguridad de red y de aplicación (WAF, Shield Advanced, Security Groups, Network Firewall, Route 53 Resolver DNS Firewall) a nivel de organización, aplicándolas automáticamente incluso a recursos y cuentas NUEVAS — exactamente el skill 6.2.3 de 'desplegar y forzar políticas desde una fuente central'.",
  },
  {
    tag: "Compartir recursos entre cuentas",
    q: "Quieres compartir una VPC (subnets), un Transit Gateway, o una regla de Firewall Manager entre varias cuentas de tu organización SIN duplicar el recurso ni usar peering/AssumeRole para cada acceso. ¿Qué servicio usas?",
    options: [
      "AWS Resource Access Manager (RAM): comparte recursos de AWS directamente entre cuentas de la organización (o cuentas externas específicas), de forma nativa y sin duplicar el recurso",
      "AWS Service Catalog",
      "Amazon Macie",
      "AWS Config Aggregator",
    ],
    correct: 0,
    explain: "AWS RAM permite compartir recursos concretos (subnets de una VPC, Transit Gateways, License Manager configurations, reglas de Firewall Manager, etc.) directamente con otras cuentas de la Organization o con cuentas externas específicas, evitando duplicación de infraestructura y simplificando el modelo de red compartida (shared VPC).",
  },
  {
    tag: "AWS Service Catalog",
    q: "¿Qué problema resuelve AWS Service Catalog en un contexto de gobierno multi-cuenta?",
    options: [
      "Permite a los equipos autoservirse plantillas de infraestructura PRE-APROBADAS por el equipo de seguridad/plataforma (ej. 'VPC estándar', 'bucket S3 conforme'), evitando que desplieguen recursos fuera de los estándares sin bloquear su autonomía por completo",
      "Sustituye completamente a CloudFormation",
      "Es un catálogo de precios de servicios de AWS",
      "Solo funciona para software de terceros del Marketplace",
    ],
    correct: 0,
    explain: "Service Catalog permite empaquetar plantillas de IaC ya revisadas y aprobadas como 'productos' que los equipos pueden desplegar de forma autoservicio, sin necesitar permisos amplios de creación de recursos — equilibrio entre velocidad de los equipos de desarrollo y control centralizado del equipo de plataforma/seguridad.",
  },
  {
    tag: "AWS Config aggregators",
    q: "¿Qué permite un AWS Config Aggregator?",
    options: [
      "Consolidar el estado de compliance de reglas de Config de MÚLTIPLES cuentas y regiones en una única vista, sin tener que iniciar sesión en cada cuenta individualmente",
      "Es lo mismo que un Conformance Pack",
      "Aggregators solo funcionan dentro de una única cuenta",
      "Sustituye a Security Hub completamente",
    ],
    correct: 0,
    explain: "Un Config Aggregator recopila datos de configuración y compliance de múltiples cuentas fuente (y regiones) en una cuenta agregadora, dando una vista consolidada de qué recursos son NON_COMPLIANT en toda la organización — se puede combinar con auto-remediación vía Config Remediation Actions o notificaciones (skill 6.3.1).",
  },
  {
    tag: "AWS Audit Manager vs AWS Artifact",
    q: "¿Cuál es la diferencia entre AWS Audit Manager y AWS Artifact?",
    options: [
      "Son el mismo servicio",
      "Audit Manager RECOPILA continuamente evidencia de TU propia cuenta (configuración, logs) mapeada contra un framework de compliance (ej. PCI-DSS, HIPAA) para preparar TUS auditorías; AWS Artifact te da acceso a los INFORMES DE COMPLIANCE de AWS mismo (SOC 2, ISO 27001) y a la aceptación de acuerdos como el BAA",
      "AWS Artifact recopila evidencia de tu cuenta, Audit Manager da certificados de AWS",
      "Ambos solo aplican a la cuenta de management",
    ],
    correct: 1,
    explain: "Audit Manager automatiza la recolección continua de EVIDENCIA de TU entorno (config, logs, políticas) organizada según el framework que elijas, para facilitar tus propias auditorías. AWS Artifact es la biblioteca de INFORMES Y CERTIFICACIONES de AWS como proveedor (SOC, ISO, PCI) que demuestran que la infraestructura subyacente de AWS cumple esos estándares — evidencia distinta, para propósitos distintos pero complementarios.",
  },
  {
    tag: "AWS Well-Architected Tool",
    q: "¿Para qué se usa la AWS Well-Architected Tool en el contexto de gobierno de seguridad?",
    options: [
      "Para desplegar infraestructura automáticamente",
      "Para evaluar una carga de trabajo frente a las mejores prácticas de los 6 pilares del Well-Architected Framework (incluido el pilar de Security), identificando riesgos y generando un plan de mejora priorizado",
      "Para calcular el coste exacto de una carga de trabajo",
      "Es exclusivo para cargas de trabajo de machine learning",
    ],
    correct: 1,
    explain: "La Well-Architected Tool guía una revisión estructurada (normalmente vía workshop con el equipo) de una carga de trabajo contra las mejores prácticas de AWS en los 6 pilares (incluyendo Security), señalando riesgos altos/medios y generando un plan de remediación priorizado — parte del skill 6.3.3 de 'evaluar arquitectura para compliance con best practices'.",
  },
  {
    tag: "SCP vs RCP vs Declarative vs AI opt-out (repaso)",
    q: "Repaso de los 4 tipos de políticas de organización: ¿cuál es la única pensada específicamente para el uso de datos por servicios de IA/ML, y no para permisos ni configuración?",
    options: [
      "Service Control Policy (SCP)",
      "Resource Control Policy (RCP)",
      "AI services opt-out policy",
      "Declarative Policy",
    ],
    correct: 2,
    explain: "SCP = techo de permisos de identidad. RCP = quién puede acceder a los recursos. Declarative Policy = fuerza un estado de configuración concreto. AI services opt-out policy = el único tipo dedicado específicamente a controlar si los servicios de IA de AWS pueden usar tus datos para mejorar sus modelos — los 4 son 'políticas de organización' pero cada una resuelve un problema distinto.",
  },
  {
    tag: "Notificaciones de compliance",
    q: "Además de remediar automáticamente un recurso NON_COMPLIANT detectado por Config, ¿qué mecanismo se usa típicamente para notificar al equipo responsable (skill 6.3.1)?",
    options: [
      "Config no soporta ningún tipo de notificación",
      "EventBridge captura el cambio de estado de compliance de Config y lo enruta a SNS (email/Slack vía integración) o dispara directamente una remediación automática vía Systems Manager Automation",
      "Solo se puede notificar revisando la consola manualmente cada día",
      "Únicamente vía AWS Support tickets",
    ],
    correct: 1,
    explain: "El patrón estándar es: Config detecta el cambio de compliance → EventBridge captura el evento → se enruta a SNS para notificar humanos, y/o dispara un Systems Manager Automation runbook para remediar automáticamente — el mismo patrón de EventBridge-como-bus-central que se repite en detección (Domain 1) e IR (Domain 2).",
  },
  {
    tag: "Landing zone existente vs nueva",
    q: "¿Puede Control Tower aplicarse a una organización de AWS que YA existe, con decenas de cuentas ya en uso, o solo sirve para organizaciones completamente nuevas?",
    options: [
      "Solo sirve para organizaciones completamente nuevas, sin cuentas previas",
      "Control Tower soporta extender una landing zone sobre una Organization YA EXISTENTE, incorporando gradualmente las cuentas actuales a la estructura de OUs y guardrails, sin necesidad de empezar desde cero",
      "Requiere migrar todas las cuentas a otra región primero",
      "Solo funciona si todas las cuentas están vacías",
    ],
    correct: 1,
    explain: "Aunque Control Tower nació pensado para nuevas implementaciones, soporta explícitamente el caso de 'landing zone existente': se puede desplegar sobre una Organization ya en uso e ir incorporando cuentas existentes a la estructura de OUs y guardrails de forma incremental, sin un big-bang de migración — relevante porque en el mundo real casi nadie empieza de cero.",
  },
];
