var QUIZ_DATA = [
  {
    tag: "AWS Organizations",
    q: "¿Qué habilita AWS Organizations que no existe al gestionar cuentas de AWS de forma completamente independiente?",
    options: [
      "Facturación consolidada, jerarquía de OUs para aplicar guardrails (SCP/RCP/Declarative Policies) por grupo de cuentas, y compartición de recursos entre cuentas de la organización",
      "Solo la facturación consolidada, sin ningún otro beneficio",
      "Organizations sustituye la necesidad de tener múltiples cuentas de AWS",
      "Solo funciona con un máximo de 5 cuentas",
    ],
    correct: 0,
    explain: "Organizations permite estructurar cuentas en OUs (Organizational Units) jerárquicas, aplicar guardrails que se heredan automáticamente por OU (SCPs, RCPs, Declarative Policies, AI opt-out policies), facturación consolidada, y compartir recursos (vía RAM) o gestionar servicios de seguridad de forma centralizada entre todas las cuentas.",
  },
  {
    tag: "AWS Control Tower",
    q: "¿Qué automatiza AWS Control Tower que AWS Organizations por sí solo no hace?",
    options: [
      "Nada adicional, son el mismo servicio con nombres distintos",
      "Despliega una 'landing zone' completa con estructura de OUs recomendada, cuentas base (Log Archive, Audit/Security Tooling) ya configuradas, guardrails preventivos Y detectivos preconfigurados, y un Account Factory para aprovisionar cuentas nuevas ya conformes desde el primer minuto",
      "Control Tower solo gestiona facturación",
      "Solo puede usarse en cuentas completamente nuevas, nunca en organizaciones existentes",
    ],
    correct: 1,
    explain: "Control Tower se construye SOBRE Organizations, automatizando el despliegue de una landing zone completa: estructura de OUs, cuentas Log Archive y Audit ya creadas y configuradas, guardrails (controls) preventivos y detectivos ya activados, y Account Factory para que cada cuenta nueva nazca ya conforme a la política — soporta tanto entornos nuevos como 'landing zone existente' (extender Organizations ya en uso).",
  },
  {
    tag: "Controles de Control Tower",
    q: "En Control Tower, ¿qué diferencia a un control PREVENTIVO de uno DETECTIVO?",
    options: [
      "Son sinónimos exactos",
      "Los controles detectivos son siempre más estrictos que los preventivos",
      "Un control preventivo IMPIDE que la acción no conforme ocurra (implementado normalmente como una SCP que bloquea la API); un control detectivo IDENTIFICA recursos que ya están en un estado no conforme (implementado como una Config Rule) para poder remediarlos después",
      "Solo los controles preventivos pueden aplicarse a nivel de OU",
    ],
    correct: 2,
    explain: "Preventivo = bloquea ANTES (ej. una SCP que deniega crear buckets S3 públicos). Detectivo = detecta DESPUÉS (ej. una Config Rule que marca como NON_COMPLIANT un bucket que ya quedó público por algún otro camino). Control Tower combina ambos tipos para cubrir tanto la prevención como los casos donde la prevención no fue suficiente.",
  },
  {
    tag: "AI services opt-out policies",
    q: "Tu organización maneja datos altamente confidenciales y quiere garantizar que NINGÚN servicio de IA/ML de AWS (como ciertas funciones de mejora de modelos) use esos datos para entrenamiento, en todas las cuentas de la organización. ¿Qué mecanismo de Organizations aplicas?",
    options: [
      "Una SCP genérica que bloquee todos los servicios de IA",
      "Una RCP sobre el servicio Bedrock únicamente",
      "Activar GuardDuty en modo estricto",
      "Una AI services opt-out policy: un tipo de política de organización específico para controlar de forma centralizada si los servicios de IA de AWS pueden usar el contenido de tus cuentas para mejorar sus modelos",
    ],
    correct: 3,
    explain: "Las AI services opt-out policies son un tipo de política de organización dedicado (junto a SCP, RCP y Declarative Policies) pensado específicamente para controlar de forma centralizada y heredable si los servicios de IA de AWS pueden usar los datos de tus cuentas para entrenamiento/mejora de modelos — más preciso y mantenible que intentar replicar ese control con una SCP genérica.",
  },
  {
    tag: "Delegated administrator",
    q: "¿Por qué se recomienda designar una cuenta 'delegated administrator' para servicios como GuardDuty, Security Hub o IAM Access Analyzer, en vez de gestionarlos desde la cuenta de management?",
    options: [
      "Reduce el uso operativo de la cuenta de management (que debería reservarse casi exclusivamente para tareas de Organizations en sí) y sigue el principio de mínimo privilegio: el equipo de seguridad opera desde una cuenta dedicada, sin necesitar las credenciales más sensibles de toda la organización",
      "Es obligatorio técnicamente, no hay alternativa",
      "La cuenta de management no puede tener GuardDuty activado nunca",
      "Delegated administrator solo aplica a Control Tower",
    ],
    correct: 0,
    explain: "La buena práctica es minimizar el uso day-to-day de la cuenta de management (comprometerla comprometería potencialmente TODA la organización). Delegar la administración de servicios de seguridad a una cuenta dedicada (típicamente la de 'Audit' o 'Security Tooling') permite al equipo de seguridad operar con visibilidad de toda la organización sin tocar la cuenta de management en el día a día.",
  },
  {
    tag: "Root user & break-glass",
    q: "¿Qué es un procedimiento 'break-glass' en el contexto de gestión de la cuenta root?",
    options: [
      "Un procedimiento para eliminar permanentemente la cuenta root",
      "Un proceso documentado y controlado de EMERGENCIA para acceder a la cuenta root (credenciales normalmente guardadas de forma segura y no usadas nunca) cuando es estrictamente necesario, con MFA físico y aprobación/auditoría reforzada",
      "Una alarma de CloudWatch que se dispara al iniciar sesión con root",
      "Solo aplica a la cuenta de management, nunca a cuentas miembro",
    ],
    correct: 1,
    explain: "Break-glass describe el acceso de emergencia: las credenciales root normalmente no se usan NUNCA para operación diaria (con MFA hardware guardado de forma segura, a menudo con doble custodia), y solo se accede a través de un procedimiento documentado, auditado y con aprobación cuando surge una necesidad genuinamente excepcional (ej. recuperar el control de una cuenta comprometida).",
  },
  {
    tag: "Root access management centralizado",
    q: "¿Qué capacidad de Organizations permite gestionar de forma centralizada las credenciales root de las cuentas MIEMBRO sin tener que hacer el proceso de recuperación de contraseña en cada una?",
    options: [
      "IAM Identity Center por sí solo",
      "AWS Config",
      "Centralized root access management: permite a la cuenta de management invocar de forma centralizada un conjunto acotado de acciones privilegiadas de root en cuentas miembro, y eliminar de forma efectiva la necesidad de credenciales root utilizables en esas cuentas",
      "Amazon Detective",
    ],
    correct: 2,
    explain: "Esta capacidad (parte del skill 6.1.5) permite gestionar el acceso root de las cuentas miembro desde la cuenta de management de forma centralizada, reduciendo drásticamente el riesgo de credenciales root sueltas y sin gestionar en decenas de cuentas — combinable con MFA obligatorio a nivel de organización.",
  },
  {
    tag: "Infrastructure as Code a escala",
    q: "¿Qué servicio de AWS permite desplegar el MISMO stack de CloudFormation (ej. una configuración base de seguridad) automáticamente en cientos de cuentas y regiones de una organización, de forma centralizada?",
    options: [
      "AWS Config Conformance Packs únicamente",
      "AWS Service Catalog exclusivamente",
      "Amazon Q Developer",
      "AWS CloudFormation StackSets: define el stack una vez y lo despliega/actualiza/elimina de forma centralizada en todas las cuentas y regiones objetivo (incluso automáticamente en cuentas NUEVAS si se integra con Organizations)",
    ],
    correct: 3,
    explain: "StackSets extiende CloudFormation para gestionar el mismo stack como una unidad a través de múltiples cuentas/regiones, con la opción de integrarse con AWS Organizations para desplegar AUTOMÁTICAMENTE en cuentas que se unan a una OU en el futuro — clave para el skill 6.2.1 sobre despliegue consistente a escala.",
  },
  {
    tag: "Validación de IaC",
    q: "¿Qué diferencia a CloudFormation Guard de cfn-lint?",
    options: [
      "cfn-lint valida SINTAXIS y buenas prácticas generales de una plantilla CloudFormation; CloudFormation Guard evalúa la plantilla contra REGLAS DE POLICY personalizadas que tú defines (ej. 'todo bucket S3 debe tener cifrado'), permitiendo bloquear despliegues no conformes en el pipeline antes de aplicarlos",
      "Son exactamente lo mismo con nombres distintos",
      "CloudFormation Guard solo funciona con Terraform",
      "cfn-lint reemplaza la necesidad de tener SCPs",
    ],
    correct: 0,
    explain: "cfn-lint es un linter general (sintaxis, tipos de recursos válidos, mejores prácticas). CloudFormation Guard es un motor de políticas como código (policy-as-code) donde TÚ escribes las reglas de negocio/seguridad específicas que la plantilla debe cumplir — ambos se integran en el pipeline de CI/CD para detectar problemas antes del despliegue (shift-left), complementando (no sustituyendo) los guardrails en runtime como SCP/Config.",
  },
  {
    tag: "Estrategia de tagging",
    q: "Más allá de la organización visual, ¿qué caso de uso de seguridad/gobierno habilita una estrategia de tagging consistente (ej. tag 'environment' o 'data-classification')?",
    options: [
      "Ninguno, los tags son solo cosméticos",
      "Permite escribir políticas ABAC (acceso basado en atributos), Conformance Packs y SCPs condicionales que se aplican automáticamente según el tag del recurso (ej. 'solo cifrado obligatorio en recursos con data-classification=confidential'), y facilita atribuir costes/responsables durante una investigación",
      "Los tags solo sirven para Cost Explorer, sin relación con seguridad",
      "Los tags sustituyen la necesidad de usar IAM",
    ],
    correct: 1,
    explain: "Una estrategia de tagging consistente es la base de ABAC (visto en el módulo de IAM), de conformance packs condicionales, y de la capacidad de responder rápido durante un incidente ('¿qué recursos son de producción?', '¿quién es el owner de este recurso?') — el skill 6.2.2 lo trata como un pilar de gobierno, no solo de FinOps.",
  },
  {
    tag: "AWS Firewall Manager",
    q: "Tienes WAF, Security Groups y AWS Network Firewall desplegados de forma inconsistente en decenas de cuentas, y quieres aplicar y mantener una política de seguridad de red uniforme en todas ellas desde un único lugar. ¿Qué servicio usas?",
    options: [
      "AWS RAM",
      "AWS Config Rules únicamente",
      "AWS Firewall Manager: aplica y mantiene automáticamente políticas de WAF, Shield Advanced, Security Groups y Network Firewall a través de todas las cuentas y recursos de la organización, incluso los que se creen en el futuro",
      "Amazon Inspector",
    ],
    correct: 2,
    explain: "Firewall Manager centraliza la gestión de políticas de seguridad de red y de aplicación (WAF, Shield Advanced, Security Groups, Network Firewall, Route 53 Resolver DNS Firewall) a nivel de organización, aplicándolas automáticamente incluso a recursos y cuentas NUEVAS — exactamente el skill 6.2.3 de 'desplegar y forzar políticas desde una fuente central'.",
  },
  {
    tag: "Compartir recursos entre cuentas",
    q: "Quieres compartir una VPC (subnets), un Transit Gateway, o una regla de Firewall Manager entre varias cuentas de tu organización SIN duplicar el recurso ni usar peering/AssumeRole para cada acceso. ¿Qué servicio usas?",
    options: [
      "AWS Config Aggregator",
      "AWS Service Catalog",
      "Amazon Macie",
      "AWS Resource Access Manager (RAM): comparte recursos de AWS directamente entre cuentas de la organización (o cuentas externas específicas), de forma nativa y sin duplicar el recurso",
    ],
    correct: 3,
    explain: "AWS RAM permite compartir recursos concretos (subnets de una VPC, Transit Gateways, License Manager configurations, reglas de Firewall Manager, etc.) directamente con otras cuentas de la Organization o con cuentas externas específicas, evitando duplicación de infraestructura y simplificando el modelo de red compartida (shared VPC).",
  },
  {
    tag: "AWS Service Catalog",
    q: "¿Qué problema resuelve AWS Service Catalog en un contexto de gobierno multi-cuenta?",
    options: [
      "Permite a los equipos autoservirse plantillas de infraestructura PRE-APROBADAS por el equipo de seguridad/plataforma (ej. 'VPC estándar', 'bucket S3 conforme'), evitando que desplieguen recursos fuera de los estándares sin bloquear su autonomía por completo",
      "Sustituye completamente a CloudFormation",
      "Es un catálogo de precios de servicios de AWS",
      "Solo funciona para software de terceros del Marketplace",
    ],
    correct: 0,
    explain: "Service Catalog permite empaquetar plantillas de IaC ya revisadas y aprobadas como 'productos' que los equipos pueden desplegar de forma autoservicio, sin necesitar permisos amplios de creación de recursos — equilibrio entre velocidad de los equipos de desarrollo y control centralizado del equipo de plataforma/seguridad.",
  },
  {
    tag: "AWS Config aggregators",
    q: "¿Qué permite un AWS Config Aggregator?",
    options: [
      "Es lo mismo que un Conformance Pack",
      "Consolidar el estado de compliance de reglas de Config de MÚLTIPLES cuentas y regiones en una única vista, sin tener que iniciar sesión en cada cuenta individualmente",
      "Aggregators solo funcionan dentro de una única cuenta",
      "Sustituye a Security Hub completamente",
    ],
    correct: 1,
    explain: "Un Config Aggregator recopila datos de configuración y compliance de múltiples cuentas fuente (y regiones) en una cuenta agregadora, dando una vista consolidada de qué recursos son NON_COMPLIANT en toda la organización — se puede combinar con auto-remediación vía Config Remediation Actions o notificaciones (skill 6.3.1).",
  },
  {
    tag: "AWS Audit Manager vs AWS Artifact",
    q: "¿Cuál es la diferencia entre AWS Audit Manager y AWS Artifact?",
    options: [
      "Son el mismo servicio",
      "AWS Artifact recopila evidencia de tu cuenta, Audit Manager da certificados de AWS",
      "Audit Manager RECOPILA continuamente evidencia de TU propia cuenta (configuración, logs) mapeada contra un framework de compliance (ej. PCI-DSS, HIPAA) para preparar TUS auditorías; AWS Artifact te da acceso a los INFORMES DE COMPLIANCE de AWS mismo (SOC 2, ISO 27001) y a la aceptación de acuerdos como el BAA",
      "Ambos solo aplican a la cuenta de management",
    ],
    correct: 2,
    explain: "Audit Manager automatiza la recolección continua de EVIDENCIA de TU entorno (config, logs, políticas) organizada según el framework que elijas, para facilitar tus propias auditorías. AWS Artifact es la biblioteca de INFORMES Y CERTIFICACIONES de AWS como proveedor (SOC, ISO, PCI) que demuestran que la infraestructura subyacente de AWS cumple esos estándares — evidencia distinta, para propósitos distintos pero complementarios.",
  },
  {
    tag: "AWS Well-Architected Tool",
    q: "¿Para qué se usa la AWS Well-Architected Tool en el contexto de gobierno de seguridad?",
    options: [
      "Para desplegar infraestructura automáticamente",
      "Es exclusivo para cargas de trabajo de machine learning",
      "Para calcular el coste exacto de una carga de trabajo",
      "Para evaluar una carga de trabajo frente a las mejores prácticas de los 6 pilares del Well-Architected Framework (incluido el pilar de Security), identificando riesgos y generando un plan de mejora priorizado",
    ],
    correct: 3,
    explain: "La Well-Architected Tool guía una revisión estructurada (normalmente vía workshop con el equipo) de una carga de trabajo contra las mejores prácticas de AWS en los 6 pilares (incluyendo Security), señalando riesgos altos/medios y generando un plan de remediación priorizado — parte del skill 6.3.3 de 'evaluar arquitectura para compliance con best practices'.",
  },
  {
    tag: "SCP vs RCP vs Declarative vs AI opt-out (repaso)",
    q: "Repaso de los 4 tipos de políticas de organización: ¿cuál es la única pensada específicamente para el uso de datos por servicios de IA/ML, y no para permisos ni configuración?",
    options: [
      "AI services opt-out policy",
      "Resource Control Policy (RCP)",
      "Service Control Policy (SCP)",
      "Declarative Policy",
    ],
    correct: 0,
    explain: "SCP = techo de permisos de identidad. RCP = quién puede acceder a los recursos. Declarative Policy = fuerza un estado de configuración concreto. AI services opt-out policy = el único tipo dedicado específicamente a controlar si los servicios de IA de AWS pueden usar tus datos para mejorar sus modelos — los 4 son 'políticas de organización' pero cada una resuelve un problema distinto.",
  },
  {
    tag: "Notificaciones de compliance",
    q: "Además de remediar automáticamente un recurso NON_COMPLIANT detectado por Config, ¿qué mecanismo se usa típicamente para notificar al equipo responsable (skill 6.3.1)?",
    options: [
      "Config no soporta ningún tipo de notificación",
      "EventBridge captura el cambio de estado de compliance de Config y lo enruta a SNS (email/Slack vía integración) o dispara directamente una remediación automática vía Systems Manager Automation",
      "Solo se puede notificar revisando la consola manualmente cada día",
      "Únicamente vía AWS Support tickets",
    ],
    correct: 1,
    explain: "El patrón estándar es: Config detecta el cambio de compliance → EventBridge captura el evento → se enruta a SNS para notificar humanos, y/o dispara un Systems Manager Automation runbook para remediar automáticamente — el mismo patrón de EventBridge-como-bus-central que se repite en detección (Domain 1) e IR (Domain 2).",
  },
  {
    tag: "Landing zone existente vs nueva",
    q: "¿Puede Control Tower aplicarse a una organización de AWS que YA existe, con decenas de cuentas ya en uso, o solo sirve para organizaciones completamente nuevas?",
    options: [
      "Solo sirve para organizaciones completamente nuevas, sin cuentas previas",
      "Requiere migrar todas las cuentas a otra región primero",
      "Control Tower soporta extender una landing zone sobre una Organization YA EXISTENTE, incorporando gradualmente las cuentas actuales a la estructura de OUs y guardrails, sin necesidad de empezar desde cero",
      "Solo funciona si todas las cuentas están vacías",
    ],
    correct: 2,
    explain: "Aunque Control Tower nació pensado para nuevas implementaciones, soporta explícitamente el caso de 'landing zone existente': se puede desplegar sobre una Organization ya en uso e ir incorporando cuentas existentes a la estructura de OUs y guardrails de forma incremental, sin un big-bang de migración — relevante porque en el mundo real casi nadie empieza de cero.",
  },
  {
    tag: "Declarative Policies: VPC Block Public Access",
    q: "El equipo de seguridad quiere garantizar que NINGUNA VPC de la organización, presente o futura, permita tráfico de entrada desde internet a través de un internet gateway, sin tener que auditar route tables o NACLs cuenta por cuenta, y con la posibilidad de revertir el cambio si algo se rompe. ¿Qué mecanismo es el más adecuado?",
    options: [
      "Modificar manualmente las NACLs de cada VPC existente",
      "Una SCP que deniegue ec2:CreateInternetGateway en toda la organización",
      "Una Config Rule detectiva combinada con remediación manual",
      "Una Declarative Policy que active VPC Block Public Access (bloqueo de ingress vía internet gateway) a nivel de OU/organización: fuerza ese estado deseado en todas las VPC actuales y futuras sin mutar los recursos existentes y de forma reversible",
    ],
    correct: 3,
    explain: "Las Declarative Policies cubren EC2/VPC/EBS a escala forzando un ESTADO de configuración (no solo bloqueando llamadas de API como una SCP). VPC Block Public Access es un caso de uso explícito: bloquea el ingress público vía internet gateway de forma centralizada, no destructiva y reversible, aplicándose automáticamente también a VPCs futuras — a diferencia de una SCP, que solo impide la llamada de API pero no cambia el estado de recursos ya existentes.",
  },
  {
    tag: "Declarative Policies: proveedores de AMI permitidos",
    q: "Tras la publicación de investigaciones sobre el ataque 'whoAMI' (donde un atacante publica una AMI pública con un nombre que coincide con el patrón que busca código mal configurado), tu organización quiere restringir de forma centralizada qué propietarios de AMI pueden usarse para lanzar instancias EC2 en TODAS las cuentas, ocultando además cualquier AMI no conforme en consola y CLI. ¿Qué solución aplicas?",
    options: [
      "Una Declarative Policy de EC2 para 'Allowed AMIs': define los proveedores de AMI permitidos a nivel de OU/organización, bloqueando el lanzamiento de instancias con AMIs no conformes y ocultándolas de la consola y la CLI",
      "Una SCP con una condición sobre ec2:Owner en cada política de cada cuenta",
      "Una Config Rule detectiva que marque como NON_COMPLIANT las instancias ya lanzadas",
      "Un permission boundary de IAM aplicado a cada rol de lanzamiento de instancias",
    ],
    correct: 0,
    explain: "La Declarative Policy de 'Allowed AMIs' es una de las configuraciones de EC2 soportadas por este tipo de política: permite definir qué proveedores de AMI son válidos para toda la organización, bloqueando el lanzamiento (y ocultando en consola/CLI) cualquier AMI que no proceda de un proveedor permitido — mitigación directa y preventiva frente a ataques de suplantación de AMIs públicas como whoAMI, más robusta que una SCP condicional que hay que mantener manualmente.",
  },
  {
    tag: "Tag Policies: enforcement en IaC",
    q: "Detectas que varios equipos crean recursos vía CloudFormation, Terraform y Pulumi sin incluir el tag obligatorio 'cost-center', y quieres bloquear (o al menos advertir) esos despliegues ANTES de que el recurso se cree, sin implementar una validación distinta para cada herramienta de IaC. ¿Qué capacidad de Organizations usas?",
    options: [
      "CloudFormation Guard configurado manualmente en cada pipeline de cada equipo",
      "AWS Organizations Tag Policies con 'required tag keys' y el hook de validación de cumplimiento de tagging, configurable en modo Warn o Fail, aplicado de forma centralizada a despliegues de CloudFormation, Terraform y Pulumi",
      "Una SCP que deniegue cualquier acción CreateTags que no incluya un valor",
      "Una Config Rule 'required-tags', que solo detecta el problema después de creado el recurso",
    ],
    correct: 1,
    explain: "Desde noviembre de 2025, las Tag Policies de Organizations permiten definir claves de tag obligatorias y aplicarlas directamente sobre despliegues de infraestructura como código (CloudFormation, Terraform y Pulumi) mediante un hook de validación con modo Warn (advierte pero permite) o Fail (bloquea el despliegue) — gobierno de tagging 'shift-left', antes de que el recurso llegue a crearse, en vez de detectarlo después con Config.",
  },
  {
    tag: "Tag Policies vs RCP",
    q: "Quieres impedir que cualquier identidad, incluida una con permisos amplios, pueda ELIMINAR o MODIFICAR el tag 'data-classification' de un recurso una vez asignado — no solo estandarizar qué valores son válidos para ese tag. ¿Qué mecanismo resuelve específicamente ese requisito?",
    options: [
      "Una Tag Policy, porque estandariza automáticamente el uso de cualquier tag en toda la organización",
      "Solo es posible activando GuardDuty en modo de protección de tags",
      "Una Resource Control Policy (o SCP) que restrinja las acciones tag:TagResource / tag:UntagResource sobre el recurso salvo para principals autorizados: las Tag Policies definen y reportan qué claves/valores son válidos, pero por sí solas NO bloquean la acción de modificar o quitar un tag",
      "Un AWS Config Aggregator con alertas en tiempo real",
    ],
    correct: 2,
    explain: "Las Tag Policies estandarizan y validan tags (incluyendo, desde 2025, el bloqueo de despliegues de IaC sin los tags requeridos), pero no son un mecanismo de control de permisos sobre la acción de etiquetar/desetiquetar en sí. Para impedir que alguien elimine o cambie un tag concreto hace falta una política de permisos (RCP o SCP) que deniegue explícitamente tag:UntagResource/tag:TagResource salvo condiciones concretas — son controles complementarios, no intercambiables.",
  },
  {
    tag: "Resource Control Policies: alcance de servicios soportados",
    q: "Tu equipo quiere usar una RCP para restringir el acceso externo a tablas de Amazon DynamoDB en todas las cuentas, igual que ya hacen con buckets S3. ¿Qué deberías verificar primero antes de asumir que funcionará igual?",
    options: [
      "Nada: las RCP cubren automáticamente todas las acciones de todos los servicios de AWS desde su lanzamiento, igual que las SCP",
      "Que Control Tower esté desplegado en la organización",
      "Que la cuenta de management tenga MFA físico obligatorio",
      "Que el servicio (en este caso DynamoDB) esté entre los soportados por RCP en ese momento: a diferencia de las SCP, que aplican de forma universal a cualquier acción de IAM, las RCP solo protegen un conjunto de servicios que AWS amplía de forma incremental (inicialmente S3, STS, KMS, Secrets Manager y SQS, con incorporaciones posteriores como ECR, OpenSearch Serverless, Cognito, CloudWatch Logs y DynamoDB)",
    ],
    correct: 3,
    explain: "A diferencia de las SCP (que actúan como techo de permisos sobre cualquier acción de IAM en la organización), las RCP solo cubren un conjunto específico de servicios que AWS ha ido ampliando progresivamente desde su lanzamiento en noviembre de 2024. Antes de diseñar un control de perímetro de datos con RCP sobre un servicio concreto hay que confirmar que ese servicio ya está soportado, o el control simplemente no tendrá efecto.",
  },
  {
    tag: "AWS Config a nivel de organización",
    q: "Hasta hace poco, para desplegar centralizadamente una regla de Config nueva en toda la organización era necesario empaquetarla dentro de un conformance pack. ¿Qué capacidad reciente de AWS Config elimina esa necesidad?",
    options: [
      "AWS Config ahora permite gestionar y desplegar reglas de Config INDIVIDUALES (no solo conformance packs completos) directamente a nivel de organización, simplificando la gobernanza de compliance sin obligar a agrupar cada regla en un pack",
      "Solo es posible logrando el mismo efecto con CloudFormation StackSets",
      "El Config Aggregator hace esto automáticamente sin ninguna acción adicional",
      "No es posible; siempre se requiere un conformance pack para desplegar a nivel de organización",
    ],
    correct: 0,
    explain: "AWS Config amplió la gestión a nivel de organización para incluir no solo conformance packs completos sino también reglas de Config individuales, simplificando el gobierno de compliance multi-cuenta cuando solo se necesita una regla puntual en vez de un paquete entero — complementa (no sustituye) el uso de conformance packs para conjuntos más grandes de reglas relacionadas.",
  },
  {
    tag: "Control Tower Landing Zone 4.0",
    q: "Tras migrar a la versión 4.0 de la landing zone de Control Tower, ¿qué cambio arquitectónico relevante ocurre respecto a cómo se agregaban antes los datos de compliance de AWS Config entre cuentas?",
    options: [
      "Se elimina AWS Config por completo de la landing zone, sustituido íntegramente por Security Hub",
      "El aggregator de organización en la cuenta de management y el aggregator de cuenta en la cuenta Audit se sustituyen por un Service-Linked Config Aggregator (SLCA) desplegado en la cuenta de integración de Config, además de pasar a usar recursos dedicados (buckets S3 y topics SNS) por servicio en lugar de recursos compartidos entre Config y CloudTrail",
      "Los datos de Config dejan de agregarse centralmente y hay que consultarlos cuenta por cuenta",
      "Es obligatorio desplegar manualmente un Config Aggregator adicional con Terraform tras la migración",
    ],
    correct: 1,
    explain: "La landing zone 4.0 de Control Tower introduce integraciones de servicio opcionales y recursos dedicados por servicio (Config y CloudTrail ya no comparten buckets/topics), y migra la agregación de compliance a un Service-Linked Config Aggregator desplegado en la cuenta de integración de Config, retirando los aggregators de organización (en management) y de cuenta (en Audit) usados anteriormente.",
  },
  {
    tag: "Control Tower: biblioteca de controles",
    q: "Un responsable de compliance pregunta cómo ha evolucionado la cobertura de controles preconfigurados de Control Tower para poder mapearla contra sus requisitos regulatorios. ¿Qué afirmación es correcta sobre esa biblioteca de controles?",
    options: [
      "Se ha mantenido fija desde el lanzamiento del servicio, sin nuevas incorporaciones desde entonces",
      "Solo existen controles preventivos; los detectivos fueron retirados en 2025",
      "Control Tower ha ampliado significativamente su biblioteca de controles basados en AWS Config (cientos de controles nuevos añadidos en 2025), permitiendo activarlos por cuenta o por organización y agruparlos en conformance packs para escalar la gobernanza multi-cuenta",
      "El número de controles disponibles nunca puede superar los 50 por limitación técnica del servicio",
    ],
    correct: 2,
    explain: "Control Tower ha seguido ampliando de forma sustancial su catálogo de controles basados en Config (cientos de controles nuevos incorporados en 2025), pudiendo activarse a nivel de cuenta o de organización y agruparse mediante conformance packs — una organización que evaluó su cobertura hace un año probablemente esté dejando de aprovechar controles nuevos relevantes para su marco de compliance.",
  },
  {
    tag: "Control Tower: resolución automática de drift de SCP",
    q: "Un ingeniero modifica, fuera de la consola de Control Tower, una SCP administrada por el servicio: la adjunta también a otra OU distinta a la prevista. Antes esto quedaba marcado como 'drift' de gobernanza que requería intervención. ¿Qué mejora reciente de Control Tower afecta a este escenario?",
    options: [
      "Control Tower ahora bloquea de forma absoluta cualquier cambio manual sobre SCPs administradas, sin excepción",
      "Solo un Config Aggregator personalizado puede detectar este tipo de cambios",
      "El concepto de drift ha sido eliminado por completo del servicio",
      "Control Tower ahora resuelve automáticamente ciertos tipos de drift de gobernanza sobre SCPs administradas (por ejemplo, quedar adjuntas también a otra OU o a una cuenta miembro fuera de la consola), sin que eso quede marcado como drift persistente que exija una re-registración manual de la landing zone",
    ],
    correct: 3,
    explain: "Control Tower amplió en 2025 el manejo de drift de SCPs administradas: ciertos tipos de cambio de gobernanza (una SCP de un control quedando adjunta a una OU distinta, o a una cuenta miembro, por una acción fuera de la consola) ahora se resuelven automáticamente por el propio servicio en vez de quedar como drift persistente que bloquea operaciones de la landing zone hasta remediarse manualmente.",
  },
  {
    tag: "Centralized Root Access Management: sesiones con alcance de tarea",
    q: "Necesitas restaurar el acceso a un bucket S3 cuya política quedó mal configurada en una cuenta miembro — tarea que tradicionalmente exigía usar las credenciales root de esa cuenta. Con Centralized Root Access Management activo, ¿cómo se resuelve esto sin recuperar la contraseña root de la cuenta miembro?",
    options: [
      "Se invoca, desde la cuenta de management o la delegated admin, una sesión de root con ALCANCE DE TAREA (task-scoped root session) sobre la cuenta miembro, limitada a esa acción privilegiada concreta y sin generar credenciales root de larga duración; además, las cuentas nuevas de la organización pueden crearse sin credenciales root utilizables desde el principio",
      "Es obligatorio usar el flujo de 'olvidé mi contraseña' asociado al email root de esa cuenta miembro",
      "Solo es posible si la cuenta miembro tiene IAM Identity Center configurado como fuente de identidad",
      "Se requiere abrir un ticket de soporte de pago con AWS para cada restauración",
    ],
    correct: 0,
    explain: "Centralized Root Access Management (lanzado en noviembre de 2024) permite invocar desde la cuenta de management un conjunto acotado de acciones root con alcance de tarea sobre cuentas miembro (como restaurar el acceso a un bucket S3 o una cola SQS), sin necesitar credenciales root de larga duración en la cuenta miembro — y las cuentas nuevas de la organización pueden nacer directamente sin credenciales root utilizables.",
  },
  {
    tag: "AWS Audit Manager: maintenance mode",
    q: "Estás diseñando la estrategia de recopilación continua de evidencia de compliance para una organización que va a incorporar cuentas NUEVAS a partir de mediados de 2026. Un compañero propone usar AWS Audit Manager en esas cuentas nuevas. ¿Qué deberías tener en cuenta?",
    options: [
      "Audit Manager sigue siendo la opción recomendada sin ninguna limitación para cuentas nuevas",
      "AWS anunció que Audit Manager pasa a modo de mantenimiento: a partir del 30 de abril de 2026 no se puede configurar en cuentas nuevas (las cuentas/regiones ya configuradas antes de esa fecha pueden seguir usándolo y creando assessments), por lo que para cuentas nuevas conviene evaluar un enfoque o herramienta distinta",
      "Audit Manager fue eliminado por completo de AWS y ya no funciona en ninguna cuenta existente",
      "Audit Manager pasa a ser gratuito e ilimitado para todas las cuentas a partir de esa fecha",
    ],
    correct: 1,
    explain: "AWS anunció que Audit Manager entra en modo mantenimiento: desde el 30 de abril de 2026 deja de poder configurarse en cuentas o regiones nuevas, aunque los clientes que ya lo tenían configurado antes de esa fecha pueden seguir usándolo con normalidad (incluyendo crear nuevos assessments) en esa cuenta/región concreta, sin recibir nuevas funcionalidades ni soporte para nuevos frameworks o servicios.",
  },
  {
    tag: "AWS Service Catalog AppRegistry: maintenance mode",
    q: "Planeabas usar AWS Service Catalog AppRegistry para agrupar lógicamente recursos por aplicación y aplicar tags de forma consistente en cuentas que se crearán después de julio de 2026. ¿Qué deberías saber al respecto?",
    options: [
      "AppRegistry ha ampliado recientemente su disponibilidad a más regiones que nunca",
      "AppRegistry sustituye por completo a AWS Config a partir de esa fecha",
      "AWS Service Catalog AppRegistry pasa a modo de mantenimiento y deja de estar disponible para clientes nuevos a partir del 30 de julio de 2026 (sin nuevas funcionalidades ni expansión regional); como alternativas sin coste adicional para agrupar y taguear recursos pueden usarse AWS Resource Groups y AWS Resource Explorer",
      "Es obligatorio migrar todo AWS Service Catalog (no solo AppRegistry) antes de esa fecha o dejará de funcionar",
    ],
    correct: 2,
    explain: "AWS anunció que AppRegistry (el componente de Service Catalog para agrupar recursos por aplicación) pasa a modo mantenimiento, sin apertura a nuevos clientes desde el 30 de julio de 2026 ni nuevas funcionalidades o regiones; los clientes existentes mantienen el servicio, y para necesidades nuevas de agrupación/tagging de recursos AWS recomienda AWS Resource Groups y AWS Resource Explorer, sin coste adicional.",
  },
  {
    tag: "Firewall Manager & Shield Advanced: Anti-DDoS managed rule group",
    q: "Gestionas políticas de AWS Firewall Manager que incluyen protección con Shield Advanced para cargas de trabajo detrás de ALB y CloudFront. AWS anunció un cambio en cómo Shield Advanced mitiga ataques de capa de aplicación (L7). ¿En qué consiste ese cambio?",
    options: [
      "Este cambio solo afecta a AWS Network Firewall, no a Shield Advanced ni a Firewall Manager",
      "Shield Advanced deja de soportar la mitigación de ataques de capa de aplicación por completo",
      "AWS WAF se elimina y se sustituye íntegramente por Shield Advanced",
      "Shield Advanced ahora se apoya en el managed rule group 'Anti-DDoS' de AWS WAF para mitigar ataques de capa de aplicación (como inundaciones de peticiones HTTP), integrándose con las políticas de Firewall Manager que ya distribuyen reglas de WAF de forma centralizada",
    ],
    correct: 3,
    explain: "AWS anunció que Shield Advanced adopta el managed rule group 'Anti-DDoS' de AWS WAF para reforzar la mitigación de ataques DDoS de capa de aplicación, coherente con el modelo en el que Firewall Manager ya distribuye y mantiene de forma centralizada las políticas de WAF (incluidos managed rule groups) junto a Shield Advanced en toda la organización.",
  },
  {
    tag: "Control Tower: soberanía digital (European Sovereign Cloud)",
    q: "Una empresa europea con requisitos estrictos de residencia de datos evalúa desplegar su landing zone en el nuevo AWS European Sovereign Cloud (disponibilidad general anunciada en enero de 2026, físicamente independiente de otras regiones de AWS). ¿Qué es correcto sobre el soporte de Control Tower en este contexto?",
    options: [
      "Control Tower está disponible en el AWS European Sovereign Cloud e incorpora controles de residencia de datos como parte del 'Digital Sovereignty Pledge' de AWS, incluyendo una agrupación dedicada de soberanía digital y la opción de usar un key store externo para AWS KMS",
      "Control Tower no está disponible en el European Sovereign Cloud; toda la landing zone debe gestionarse manualmente",
      "El European Sovereign Cloud comparte automáticamente todos los datos y metadatos con las regiones estándar de AWS fuera de la UE",
      "Solo es accesible mediante una conexión Direct Connect exclusiva, sin soporte de Control Tower ni de Organizations",
    ],
    correct: 0,
    explain: "El AWS European Sovereign Cloud es una nube independiente, operada exclusivamente por residentes de la UE y físicamente separada de otras regiones de AWS. Control Tower da soporte a este entorno incorporando gobernanza de residencia de datos (agrupación dedicada de soberanía digital) y opciones como un key store externo para KMS, en línea con el Digital Sovereignty Pledge de AWS.",
  },
  {
    tag: "AWS Well-Architected Tool: Review Templates",
    q: "El equipo de plataforma revisa decenas de cargas de trabajo con patrones de arquitectura muy similares (y, por tanto, las mismas respuestas a la mayoría de las mejores prácticas del pilar de seguridad) y quiere evitar rellenar manualmente las mismas respuestas en cada revisión nueva. ¿Qué funcionalidad de la Well-Architected Tool resuelve esto?",
    options: [
      "No es posible; cada revisión debe completarse manualmente desde cero sin excepción",
      "Review Templates: permite crear plantillas con respuestas prellenadas para las mejores prácticas del Well-Architected Framework (o de un lente personalizado) y aplicarlas como punto de partida al definir nuevas cargas de trabajo, reduciendo la duplicación de esfuerzo y estandarizando respuestas comunes entre equipos",
      "Solo se puede lograr exportando las respuestas a una hoja de cálculo y copiándolas manualmente en cada nueva revisión",
      "Es una funcionalidad exclusiva del pilar de optimización de costes, no aplicable al pilar de seguridad",
    ],
    correct: 1,
    explain: "Review Templates permite predefinir respuestas comunes a las mejores prácticas del Well-Architected Framework (incluido el pilar de Security) o de un lente personalizado, y aplicarlas como punto de partida al crear nuevas cargas de trabajo con patrones repetidos, evitando reintroducir manualmente las mismas respuestas y estandarizando el criterio de evaluación entre equipos y cargas de trabajo.",
  },
  {
    tag: "Declarative Policies vs SCP: durabilidad",
    q: "Un compañero pregunta por qué el equipo de seguridad prefiere una Declarative Policy en vez de una SCP para forzar IMDSv2 en todas las instancias EC2 de la organización, si ambas son políticas de organización que se heredan por OU. ¿Cuál es la razón principal?",
    options: [
      "Las SCP no pueden aplicarse a nivel de OU, solo a nivel de cuenta individual",
      "Las Declarative Policies tienen un coste adicional menor que las SCP",
      "Una Declarative Policy fuerza un ESTADO de configuración deseado de forma duradera ('configúralo una vez'): ese estado se mantiene automáticamente incluso cuando el servicio añade nuevas APIs o funcionalidades relacionadas, mientras que una SCP solo deniega llamadas de API concretas y hay que mantenerla actualizada manualmente a medida que aparecen nuevas formas de conseguir el mismo resultado no deseado",
      "No existe ninguna diferencia práctica relevante entre ambos tipos de política",
    ],
    correct: 2,
    explain: "Las Declarative Policies están pensadas para configuración duradera de un servicio ('set and forget'): una vez definida la configuración deseada (ej. IMDSv2 obligatorio), se mantiene automáticamente aunque el servicio añada nuevas APIs o funcionalidades relacionadas. Una SCP, en cambio, opera a nivel de permisos de API concretos: si aparece una nueva forma de conseguir el resultado no deseado (una API nueva, un parámetro nuevo), hay que actualizar la SCP manualmente para seguir cubriéndola.",
  },
  {
    tag: "AWS Config conformance packs: expansión regional",
    q: "Tu organización empieza a operar cargas de trabajo en regiones relativamente nuevas de AWS, como Asia Pacífico (Malasia) o Asia Pacífico (Nueva Zelanda), y planeas desplegar conformance packs de Config a nivel de organización en todas las cuentas y regiones. ¿Qué deberías verificar antes de asumir que funcionará igual que en regiones más antiguas como us-east-1?",
    options: [
      "La gestión a nivel de organización de conformance packs depende únicamente de si Control Tower está desplegado, no de la región",
      "Los conformance packs están disponibles automáticamente en todas las regiones desde el lanzamiento del servicio, sin excepciones",
      "Los conformance packs solo funcionan en la región donde reside la cuenta de management de la organización",
      "Los conformance packs de AWS Config y su gestión a nivel de organización tienen disponibilidad por región, que AWS ha ampliado de forma progresiva (incorporando en 2025 regiones como Asia Pacífico Malasia, Nueva Zelanda, Tailandia, Taipéi y México Central); conviene confirmar que la región de destino ya soporta la funcionalidad antes de desplegar",
    ],
    correct: 3,
    explain: "AWS ha ido ampliando de forma incremental la disponibilidad regional tanto de los conformance packs de Config como de su gestión a nivel de organización, incorporando en 2025 regiones como Asia Pacífico (Malasia), Asia Pacífico (Nueva Zelanda), Asia Pacífico (Tailandia), Asia Pacífico (Taipéi) y México (Centro) — un supuesto de examen realista es verificar la disponibilidad regional de una funcionalidad de gobierno antes de asumir cobertura global uniforme.",
  },
  {
    tag: "Alcance de las SCP",
    q: "Estás desplegando Service Control Policies en una organización. ¿Qué DOS afirmaciones son correctas?",
    options: [
      "Una SCP no concede permisos: solo acota el máximo que las identidades de la cuenta pueden llegar a tener",
      "Las SCP no se aplican a la management account de la organización",
      "Una SCP puede conceder permisos a un usuario que no los tiene en su identity policy",
      "Las SCP se aplican también a los principals externos que acceden a tus recursos",
    ],
    correct: [0, 1],
    explain: "Dos clásicos del examen. Una SCP es un <b>guardrail</b>, nunca una concesión: el permiso efectivo es la intersección entre la SCP y las políticas de identidad. Y la <b>management account no queda sujeta a las SCP</b>, motivo por el que AWS recomienda no alojar cargas de trabajo en ella. La opción D describe lo que hacen las <b>RCP</b>, que sí alcanzan a identidades externas: es justo el hueco que las SCP no cubren.",
  },
  {
    tag: "Controles de Control Tower",
    q: "Control Tower ofrece distintos tipos de control sobre la landing zone. ¿Qué DOS descripciones son correctas?",
    options: [
      "Los controles preventivos se implementan con SCPs e impiden que la acción llegue a ejecutarse",
      "Los controles detectivos se implementan con reglas de AWS Config y avisan cuando algo ya se ha desviado",
      "Los controles detectivos bloquean la acción antes de que ocurra, igual que los preventivos",
      "Los controles preventivos solo pueden aplicarse a la cuenta de auditoría",
    ],
    correct: [0, 1],
    explain: "La distinción <b>preventivo vs detectivo</b> es la que más se pregunta: los preventivos (SCP) <b>impiden</b>, los detectivos (Config) <b>detectan</b> lo que ya pasó. Por eso la opción C se contradice a sí misma. Los preventivos se aplican a OUs y cuentas, no solo a la de auditoría. Control Tower añade además controles <i>proactivos</i>, que validan plantillas de CloudFormation antes del despliegue.",
  },
  {
    tag: "Compliance multi-cuenta con Config",
    q: "Necesitas una visión única del cumplimiento de reglas de AWS Config en 90 cuentas y 4 Regiones. ¿Qué DOS elementos lo permiten?",
    options: [
      "Un aggregator de AWS Config que reúna los datos de todas las cuentas y Regiones",
      "Conformance packs desplegados en la organización para aplicar el mismo conjunto de reglas en todas partes",
      "Un bucket S3 en cada cuenta desde el que descargar informes manualmente cada semana",
      "Activar Config solo en la cuenta de gestión, que hereda automáticamente el estado de las demás",
    ],
    correct: [0, 1],
    explain: "El <b>aggregator</b> resuelve la vista consolidada y los <b>conformance packs</b> a nivel de organización garantizan que todas evalúan lo mismo. La descarga manual no escala a 90 cuentas y siempre llega tarde. Y Config es un servicio <b>regional y por cuenta</b>: la cuenta de gestión no hereda nada, hay que habilitarlo donde estén los recursos.",
  },
  {
    tag: "Protección del usuario root",
    q: "Estás endureciendo el usuario root de todas las cuentas de la organización. ¿Qué DOS medidas recomienda AWS?",
    options: [
      "Habilitar MFA en el root y eliminar sus access keys si existen",
      "Usar la gestión centralizada de acceso root para retirar las credenciales root de las cuentas miembro",
      "Crear una access key de root en cada cuenta y guardarla en Secrets Manager para automatizar tareas",
      "Usar el root para las tareas administrativas diarias, ya que nunca queda bloqueado por una SCP",
    ],
    correct: [0, 1],
    explain: "Lo básico es <b>MFA y cero access keys</b> en el root, y la <b>gestión centralizada de acceso root</b> permite retirar por completo esas credenciales de las cuentas miembro, dejando las tareas que exigen root para sesiones acotadas vía <code>sts:AssumeRoot</code>. Crear access keys de root es exactamente lo contrario de la recomendación. Y aunque es cierto que las SCP no limitan al root de la management account, eso es un motivo para <b>no</b> usarlo a diario, no para usarlo.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["governance"] = QUIZ_DATA;
