var QUIZ_DATA = [
  {
    tag: "Security Groups vs NACLs",
    q: "¿Cuál es la diferencia MÁS importante entre un Security Group y una Network ACL en cuanto a su comportamiento?",
    options: [
      "El Security Group es a nivel de subnet y la NACL a nivel de instancia",
      "El Security Group es STATEFUL (el tráfico de retorno se permite automáticamente) y solo admite reglas Allow; la NACL es STATELESS (hay que permitir explícitamente ida Y vuelta) y admite reglas Allow y Deny evaluadas en orden numérico",
      "Ambos son idénticos, solo cambia dónde se configuran en la consola",
      "La NACL solo filtra tráfico HTTP/HTTPS",
    ],
    correct: 1,
    explain: "Security Group = stateful, a nivel de ENI/instancia, solo Allow (todo lo no permitido se deniega implícitamente). NACL = stateless, a nivel de subnet, con reglas numeradas evaluadas en orden que pueden ser Allow o Deny — por eso hay que abrir el tráfico de retorno (puertos efímeros) explícitamente.",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "Detectas tráfico malicioso repetido desde una IP concreta y quieres bloquearla de inmediato a nivel de red, sin depender de que ninguna instancia tenga una regla que lo permita. ¿Qué mecanismo usas?",
    options: [
      "Una regla Deny en la Network ACL de la subnet (los Security Groups no pueden denegar explícitamente una IP)",
      "Añadir la IP a un Security Group con Deny",
      "Modificar el route table de la subnet",
      "Activar GuardDuty",
    ],
    correct: 0,
    explain: "Los Security Groups NO tienen reglas Deny — solo puedes especificar qué se permite. Para bloquear explícitamente una IP concreta a nivel de red (independientemente de qué Security Group tenga cada instancia), necesitas una regla Deny en la NACL de la subnet, evaluada antes de que el tráfico llegue a la instancia.",
  },
  {
    tag: "AWS WAF",
    q: "¿Qué tipo de ataque está diseñado para detectar y bloquear un 'rate-based rule' en AWS WAF?",
    options: [
      "Inyección SQL únicamente",
      "Un volumen anómalamente alto de requests desde la misma IP (o clave de agregación) en una ventana de tiempo — por ejemplo, fuerza bruta de login o scraping agresivo",
      "Ataques que ya pasaron por CloudFront",
      "Solo tráfico UDP",
    ],
    correct: 1,
    explain: "Las rate-based rules de WAF cuentan requests por clave de agregación (IP de origen por defecto, o una combinación custom) en ventanas deslizantes de 5 o 10 minutos, y bloquean automáticamente cuando se supera el umbral — ideal contra fuerza bruta, credential stuffing o scraping, complementario a las reglas de firma (SQLi, XSS del OWASP Top 10).",
  },
  {
    tag: "Shield Advanced",
    q: "¿Qué añade AWS Shield Advanced sobre la protección DDoS estándar (Shield Standard) que viene gratis con todas las cuentas?",
    options: [
      "Nada, Shield Standard ya cubre todos los casos",
      "Protección avanzada contra ataques de capa 3/4 y 7 más sofisticados, acceso al DDoS Response Team (DRT), reembolso de costes por picos de escalado durante un ataque, y visibilidad/métricas detalladas — de pago, por cuenta o por recurso",
      "Solo protege Route 53, no CloudFront ni ALB",
      "Shield Advanced sustituye a WAF completamente",
    ],
    correct: 1,
    explain: "Shield Standard (gratis, automático) cubre los ataques DDoS más comunes de capa 3/4. Shield Advanced añade protección ampliada, el DDoS Response Team disponible 24/7, cost protection (créditos si escalas por un ataque), y se integra con WAF para mitigación de capa 7 — recomendado para cargas críticas con SLA de disponibilidad.",
  },
  {
    tag: "Edge security",
    q: "Quieres bloquear el acceso a tu aplicación distribuida vía CloudFront desde todos los países excepto España y Portugal. ¿Qué mecanismo usas?",
    options: [
      "Un Security Group con reglas por país",
      "CloudFront Geo Restriction (allowlist de países) o una regla de geo-match en AWS WAF asociada a la distribución",
      "Una NACL con rangos CIDR por país",
      "Route 53 Resolver DNS Firewall",
    ],
    correct: 1,
    explain: "CloudFront Geo Restriction permite allowlist/blocklist de países directamente en la distribución. Alternativamente, una regla de geo-match en WAF (asociada a CloudFront) ofrece lo mismo con más flexibilidad para combinarlo con otras condiciones (rate limiting, fingerprinting).",
  },
  {
    tag: "S3 CORS",
    q: "Tu SPA en https://app.midominio.com necesita hacer peticiones fetch() directamente a un bucket S3 para subir archivos, y el navegador las bloquea con un error de CORS. ¿Qué configuras?",
    options: [
      "Una bucket policy que permita el Principal '*'",
      "Una configuración CORS en el bucket S3 que permita explícitamente el origen https://app.midominio.com y los métodos/headers necesarios",
      "Desactivar HTTPS en el bucket",
      "Un Security Group en el bucket",
    ],
    correct: 1,
    explain: "CORS (Cross-Origin Resource Sharing) es una restricción del NAVEGADOR, no de AWS. S3 soporta una configuración CORS propia (AllowedOrigins, AllowedMethods, AllowedHeaders) que le dice al navegador que ese origen concreto tiene permiso para hacer peticiones cross-origin al bucket — independiente de la bucket policy o los permisos IAM.",
  },
  {
    tag: "Hardened AMIs",
    q: "¿Qué servicio de AWS está diseñado específicamente para construir, mantener y validar AMIs (o imágenes de contenedor) hardened de forma automatizada y repetible?",
    options: [
      "AWS Config",
      "EC2 Image Builder: pipeline automatizado que aplica hardening (ej. CIS benchmarks), instala parches y ejecuta tests de validación antes de publicar la AMI",
      "AWS Backup",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "EC2 Image Builder automatiza el pipeline completo: parte de una imagen base, aplica componentes de hardening/configuración, instala actualizaciones, ejecuta tests, y publica la AMI (o imagen de contenedor) resultante — eliminando el proceso manual y garantizando reproducibilidad entre versiones.",
  },
  {
    tag: "Instance profiles vs roles",
    q: "¿Qué relación hay entre un 'Instance Profile' de EC2 y un IAM Role?",
    options: [
      "Son sinónimos exactos, se puede usar cualquiera de los dos términos indistintamente en la API",
      "El Instance Profile es el CONTENEDOR que asocia un IAM Role a una instancia EC2 — es lo que realmente se adjunta a la instancia (la consola lo oculta creándolo automáticamente al 'asignar un rol')",
      "Un Instance Profile puede contener múltiples IAM Roles simultáneamente",
      "El Instance Profile sustituye a la necesidad de tener un IAM Role",
    ],
    correct: 1,
    explain: "Técnicamente no adjuntas un IAM Role directamente a una instancia EC2: adjuntas un Instance Profile, que a su vez referencia UN único IAM Role. La consola de AWS oculta esta distinción creando el Instance Profile automáticamente, pero la CLI/API la expone (aws iam create-instance-profile + add-role-to-instance-profile).",
  },
  {
    tag: "Amazon Inspector",
    q: "¿Qué tipos de recursos puede escanear Amazon Inspector en busca de vulnerabilidades conocidas (CVEs)?",
    options: [
      "Solo instancias EC2",
      "Instancias EC2, imágenes de contenedor en Amazon ECR, y funciones Lambda (código y capas) — de forma continua, no solo bajo demanda",
      "Solo bases de datos RDS",
      "Solo buckets S3",
    ],
    correct: 1,
    explain: "Amazon Inspector escanea de forma continua y automática EC2 (paquetes de SO y vulnerabilidades de red), imágenes de contenedor en ECR (al hacer push y periódicamente), y funciones Lambda (dependencias en el código). GuardDuty, en cambio, monitoriza el RUNTIME (comportamiento anómalo en tiempo real), no vulnerabilidades estáticas conocidas.",
  },
  {
    tag: "Patch management",
    q: "¿Qué componente de Systems Manager automatiza la aplicación de parches de seguridad del sistema operativo en una flota de instancias EC2, según una ventana de mantenimiento programada?",
    options: [
      "Systems Manager Session Manager",
      "Systems Manager Patch Manager, típicamente orquestado con Maintenance Windows",
      "Systems Manager Parameter Store",
      "AWS Config",
    ],
    correct: 1,
    explain: "Patch Manager automatiza el escaneo y la aplicación de parches (SO y algunas aplicaciones) según baselines de aprobación configurables, ejecutado dentro de Maintenance Windows para controlar cuándo ocurre el impacto — clave para el skill 3.2.4 de 'desplegar parches de forma automatizada y con validación continua'.",
  },
  {
    tag: "Acceso administrativo seguro",
    q: "Quieres dar a los ingenieros acceso de shell a instancias EC2 en subnets privadas sin abrir el puerto 22, sin gestionar claves SSH, y con toda la sesión auditada en CloudTrail. ¿Qué usas?",
    options: [
      "EC2 Instance Connect con IP pública",
      "AWS Systems Manager Session Manager: crea un túnel a través del agente SSM, sin necesidad de puerto 22 abierto, bastion host, ni claves SSH, y registra cada comando ejecutado",
      "Un bastion host tradicional con NAT Gateway",
      "Desactivar el Security Group temporalmente",
    ],
    correct: 1,
    explain: "Session Manager establece la sesión a través del agente SSM saliente (HTTPS), sin necesidad de abrir puertos entrantes, bastion hosts, ni distribuir claves SSH — y todos los comandos quedan auditados (CloudTrail + logs opcionales a S3/CloudWatch). EC2 Instance Connect es la alternativa para SSH efímero pero SÍ requiere el puerto 22 accesible (aunque sea vía un rango controlado).",
  },
  {
    tag: "Seguridad en el pipeline",
    q: "¿Qué herramienta de AWS está diseñada para analizar código fuente y detectar vulnerabilidades de seguridad (ej. inyección, secretos hardcodeados) DENTRO del pipeline de CI/CD, antes de desplegar?",
    options: [
      "Amazon GuardDuty",
      "Amazon CodeGuru Security (y Amazon Q Developer para sugerencias/remediación asistida)",
      "AWS Config",
      "Amazon Detective",
    ],
    correct: 1,
    explain: "CodeGuru Security analiza estáticamente el código fuente en busca de vulnerabilidades (similar a un SAST — Static Application Security Testing) y secretos hardcodeados, integrable en el pipeline de CI/CD. Amazon Q Developer complementa con sugerencias de remediación asistidas por IA. GuardDuty y Detective operan sobre la cuenta en ejecución, no sobre el código fuente.",
  },
  {
    tag: "Guardrails para GenAI",
    q: "Estás construyendo una aplicación con un LLM que responde a usuarios finales, y necesitas protegerla contra prompt injection y fuga de datos sensibles en las respuestas. ¿Qué marco de referencia se menciona explícitamente en el exam guide de SCS-C03 para este tipo de protecciones?",
    options: [
      "PCI-DSS",
      "OWASP Top 10 for LLM Applications",
      "CIS Benchmarks estándar",
      "NIST 800-53 exclusivamente",
    ],
    correct: 1,
    explain: "El OWASP Top 10 for LLM Applications cataloga riesgos específicos de aplicaciones con modelos de lenguaje (prompt injection, fuga de datos sensibles, envenenamiento de entrenamiento, etc.) — un skill nuevo explícito en SCS-C03 (3.2.7), reflejando la adopción de GenAI en cargas de trabajo de producción.",
  },
  {
    tag: "Conectividad híbrida",
    q: "¿Qué diferencia a AWS Direct Connect de un AWS Site-to-Site VPN?",
    options: [
      "Son idénticos en rendimiento y coste",
      "Direct Connect es una conexión de red dedicada y privada (vía un partner o directamente) que NO atraviesa la Internet pública, con ancho de banda predecible; Site-to-Site VPN cifra el tráfico pero sigue viajando sobre Internet",
      "Site-to-Site VPN requiere hardware físico en tu datacenter mientras que Direct Connect no",
      "Direct Connect no puede combinarse con VPN",
    ],
    correct: 1,
    explain: "Direct Connect establece una conexión física dedicada entre tu datacenter y AWS (vía un DX location/partner), evitando la Internet pública — mejor latencia/consistencia, sin cifrado nativo (se añade con MACsec o una VPN sobre DX). Site-to-Site VPN crea un túnel IPsec cifrado sobre Internet, más rápido de desplegar pero con rendimiento menos predecible.",
  },
  {
    tag: "MACsec",
    q: "¿Para qué se usa MACsec (802.1AE) en el contexto de AWS Direct Connect?",
    options: [
      "Para acelerar la velocidad de la conexión",
      "Para cifrar el tráfico a nivel de capa 2 (Ethernet) en conexiones Direct Connect dedicadas de alta velocidad, ya que Direct Connect por sí solo no cifra el tráfico",
      "Para reemplazar completamente a Direct Connect",
      "Es un protocolo exclusivo de Site-to-Site VPN",
    ],
    correct: 1,
    explain: "Direct Connect no cifra el tráfico de forma nativa (es una conexión privada, pero no cifrada). MACsec añade cifrado a nivel de enlace (capa 2) en conexiones dedicadas de 10/100 Gbps, cumpliendo requisitos donde la confidencialidad del tráfico es obligatoria incluso sobre una conexión ya privada.",
  },
  {
    tag: "Verified Access en híbrido",
    q: "Tu empresa tiene aplicaciones internas que deben ser accesibles tanto para empleados en la oficina (red on-premises) como en remoto, sin exponerlas a Internet ni depender de una VPN de red completa. ¿Qué solución encaja con el skill 3.3.3?",
    options: [
      "AWS Site-to-Site VPN únicamente",
      "AWS Verified Access: evalúa identidad (IAM Identity Center) y postura del dispositivo en cada request, dando acceso a nivel de aplicación sin exponer un túnel de red completo entre on-premises y AWS",
      "Convertir todas las apps en públicas con WAF delante",
      "AWS Direct Connect por sí solo",
    ],
    correct: 1,
    explain: "Verified Access implementa Zero Trust Network Access (ZTNA): en vez de conectar redes completas (como VPN o Direct Connect), evalúa cada solicitud a una aplicación específica según identidad y postura del dispositivo, funcionando igual de bien para usuarios en la oficina que en remoto sin exponer la app a Internet.",
  },
  {
    tag: "Segmentación de red",
    q: "En el diseño de una VPC, ¿qué término describe el tráfico ENTRE cargas de trabajo dentro del mismo entorno (ej. entre microservicios en distintas subnets privadas), a diferencia del tráfico que entra/sale del perímetro?",
    options: [
      "Tráfico north/south",
      "Tráfico east/west",
      "Tráfico de tránsito (transit)",
      "Tráfico de peering",
    ],
    correct: 1,
    explain: "North/south es el tráfico que cruza el perímetro (cliente de Internet ↔ tu VPC). East/west es el tráfico interno entre cargas de trabajo (microservicio A ↔ microservicio B). Aislar y filtrar el tráfico east/west (con SGs específicos por capa, subnets aisladas, Network Firewall interno) reduce el blast radius si un componente se ve comprometido — un principio central del skill 3.3.4.",
  },
  {
    tag: "AWS Network Firewall",
    q: "¿En qué se diferencia AWS Network Firewall de un Security Group o una NACL?",
    options: [
      "Es exactamente lo mismo con otro nombre comercial",
      "Network Firewall es un firewall con estado a nivel de VPC/subnet que soporta inspección de capa 3-7 (incluyendo reglas basadas en dominio y firmas tipo IDS/IPS con Suricata), más avanzado que el filtrado de 5-tupla de SG/NACL",
      "Solo puede desplegarse en subnets públicas",
      "No soporta reglas basadas en dominio (FQDN)",
    ],
    correct: 1,
    explain: "SG y NACL filtran por IP/puerto/protocolo (5-tupla). AWS Network Firewall añade inspección profunda de paquetes (deep packet inspection), reglas de dominio (permitir solo salida a *.midominio.com), y reglas de firma compatibles con el formato Suricata (IDS/IPS) — pensado para tráfico de tránsito entre subnets o hacia Internet a través de un Gateway/Transit Gateway.",
  },
  {
    tag: "Detección de accesos innecesarios",
    q: "¿Qué herramienta te dice si existe una ruta de red alcanzable no intencionada entre dos recursos (ej. una instancia en subnet privada accesible desde Internet por una mala configuración en cadena de SG/NACL/route table)?",
    options: [
      "AWS Config Rules únicamente",
      "Amazon Inspector Network Reachability (o VPC Network Access Analyzer) — analiza toda la cadena de configuración de red para detectar rutas de acceso no intencionadas",
      "Amazon Macie",
      "AWS Trusted Advisor exclusivamente",
    ],
    correct: 1,
    explain: "Estas herramientas modelan toda la configuración de red (SGs, NACLs, route tables, peering, IGW/NAT) para determinar si existe una ruta alcanzable entre un origen y un destino que no debería existir — mucho más fiable que revisar manualmente cada componente por separado, exactamente el skill 3.3.5.",
  },
  {
    tag: "OCSF",
    q: "¿Qué es el Open Cybersecurity Schema Framework (OCSF) en el contexto de integraciones de seguridad con AWS?",
    options: [
      "Un servicio de AWS de pago para almacenar logs",
      "Un esquema de datos ABIERTO y estandarizado para normalizar eventos de seguridad de distintas fuentes (AWS y terceros), facilitando la correlación sin transformar cada formato propietario manualmente",
      "Un protocolo de cifrado",
      "El sucesor de CloudTrail",
    ],
    correct: 1,
    explain: "OCSF es un estándar abierto (impulsado por AWS y otros) para representar eventos de seguridad de forma consistente entre productos y proveedores distintos. Amazon Security Lake lo usa como formato nativo, facilitando integrar fuentes de terceros sin escribir un parser distinto para cada una — parte del skill 3.1.4 sobre integraciones edge.",
  },
  {
    tag: "WAF Fraud Control – ATP",
    q: "Tu equipo de seguridad detecta un aumento de intentos de login con credenciales robadas (credential stuffing) contra el endpoint de login de tu aplicación, servido detrás de CloudFront. Los atacantes usan pares email/contraseña filtrados en otras brechas, y muchos aciertan porque los usuarios reutilizan contraseñas. ¿Qué componente de AWS WAF Fraud Control resuelve específicamente este caso de uso?",
    options: [
      "AWS WAF Bot Control, para bloquear bots conocidos",
      "Account Takeover Prevention (ATP): compara los pares de credenciales enviados en el login contra una base de datos de credenciales filtradas actualizada regularmente, y detecta patrones anómalos de inicio de sesión (fuerza bruta, credential stuffing) en la página de login concreta",
      "Una rate-based rule genérica sin más configuración",
      "Account Creation Fraud Prevention (ACFP), diseñado para páginas de registro",
    ],
    correct: 1,
    explain: "ATP protege específicamente páginas de login: inspecciona las credenciales enviadas y las compara contra una base de datos de credenciales comprometidas conocidas (actualizada continuamente), además de aplicar heurísticas de comportamiento anómalo. ACFP (opción D) es el componente hermano para páginas de REGISTRO/creación de cuentas, no de login — no resuelve credential stuffing en un login existente.",
  },
  {
    tag: "WAF Fraud Control – ACFP",
    q: "Una aplicación con registro público sufre oleadas de creación de cuentas falsas generadas por bots, usadas después para fraude de promociones (abuso de cupones de bienvenida). ¿Qué protección de AWS WAF está diseñada para este escenario?",
    options: [
      "Account Creation Fraud Prevention (ACFP), que monitoriza continuamente las peticiones al endpoint de registro/sign-up y bloquea automáticamente solicitudes sospechosas según identificadores de la petición y análisis de comportamiento",
      "Account Takeover Prevention (ATP), pensado para el endpoint de login",
      "CloudFront Geo Restriction",
      "Shield Advanced, mitigación de capa 3/4",
    ],
    correct: 0,
    explain: "ACFP protege específicamente páginas de creación de cuentas: analiza patrones de comportamiento y señales de la petición (huella del dispositivo, uso repetido de identificadores) para bloquear el fraude de registro masivo, distinto del abuso de login (ATP) o de la mitigación DDoS de red (Shield).",
  },
  {
    tag: "WAF CAPTCHA vs Challenge",
    q: "Quieres frenar un bot sencillo que hace scraping del catálogo de productos sin degradar la experiencia de los usuarios reales (no quieres pedirles que resuelvan un puzle visible). ¿Qué acción de regla de AWS WAF es la más adecuada?",
    options: [
      "CAPTCHA, que siempre pide resolver un puzle visible al usuario",
      "Challenge: ejecuta una verificación silenciosa en segundo plano (confirma que el cliente es un navegador real) sin interacción visible del usuario, y solo si falla se puede escalar a bloqueo o CAPTCHA",
      "Block directo de todas las IPs sospechosas sin verificación",
      "Count, que no bloquea nada, solo registra métricas",
    ],
    correct: 1,
    explain: "Challenge realiza una comprobación silenciosa (basada en un token cifrado, cookie aws-waf-token) que verifica que el cliente ejecuta JavaScript como un navegador real, sin pedir nada al usuario — ideal para filtrar bots simples sin fricción. CAPTCHA exige resolver un puzle visible, más intrusivo, reservado para amenazas más persistentes.",
  },
  {
    tag: "WAF Bot Control",
    q: "Necesitas distinguir entre bots 'buenos' conocidos (como los crawlers de motores de búsqueda legítimos) y bots maliciosos/no categorizados en tu aplicación web, incluyendo la capacidad de definir protecciones contra bots dirigidos específicamente a tu negocio (ej. bots de scalping de inventario). ¿Qué managed rule group de AWS WAF encaja?",
    options: [
      "AWS Managed Rules — Core rule set (CRS), pensado para OWASP Top 10",
      "AWS WAF Bot Control, con su modalidad Targeted (Targeted Bot Control) para bots sofisticados y personalizados por dominio de negocio, además de categorizar tráfico de bots conocidos (buenos/verificados) frente a no categorizados",
      "Shield Advanced Anti-DDoS managed rule group",
      "Amazon Inspector",
    ],
    correct: 1,
    explain: "Bot Control clasifica el tráfico automatizado (buscadores verificados, monitores, bots maliciosos) y su capa 'Targeted' usa machine learning y fingerprinting específico de dominio para detectar bots sofisticados diseñados a medida contra tu aplicación (scalping, scraping avanzado) — más granular que las reglas genéricas de firma del CRS.",
  },
  {
    tag: "Shield Advanced + Anti-DDoS rule group",
    q: "Tu organización usa Shield Advanced sobre una distribución de CloudFront con AWS WAF. Tras la adopción del nuevo AWS WAF Anti-DDoS managed rule group como protección de capa de aplicación por defecto de Shield Advanced, ¿qué cambia respecto a la facturación durante un ataque DDoS de capa 7 activamente mitigado?",
    options: [
      "Se te cobra el doble durante la mitigación activa por el uso adicional de recursos",
      "Las solicitudes bloqueadas por la mitigación DDoS activa se excluyen de tu recuento mensual de solicitudes (WAF, Anti-DDoS managed rule group y Shield Advanced), evitando que el tráfico de ataque infle la factura",
      "No hay ningún cambio en la facturación, se cobra igual que el tráfico legítimo",
      "Shield Advanced deja de facturar por completo mientras dure cualquier ataque",
    ],
    correct: 1,
    explain: "El nuevo Anti-DDoS managed rule group (que sustituye a la protección de capa 7 anterior con menos WCU) excluye del recuento de solicitudes facturables el tráfico bloqueado durante una mitigación DDoS activa — así el volumen del ataque no se traduce en un coste desproporcionado para el cliente.",
  },
  {
    tag: "Network Firewall TLS Inspection",
    q: "Necesitas que AWS Network Firewall inspeccione el contenido de las conexiones HTTPS salientes de tu VPC (no solo el SNI) para aplicar reglas de firma tipo IDS/IPS sobre el tráfico descifrado. ¿Qué debes configurar?",
    options: [
      "Nada adicional: Network Firewall inspecciona el payload cifrado de HTTPS de forma nativa sin configuración",
      "Una TLS Inspection Configuration: Network Firewall descifra el tráfico con un certificado que administra, lo inspecciona en claro, y lo vuelve a cifrar antes de reenviarlo — configurable para tráfico de entrada (ingress) y/o de salida (egress)",
      "Activar únicamente reglas de dominio (FQDN), que no requieren descifrado",
      "Sustituir Network Firewall por AWS WAF, que sí inspecciona TLS de forma nativa",
    ],
    correct: 1,
    explain: "Por defecto, un firewall con estado solo puede inspeccionar metadatos de TLS (como el SNI) porque el payload va cifrado. Para inspección profunda de HTTPS, Network Firewall soporta una TLS Inspection Configuration que actúa como proxy TLS: descifra con certificados gestionados (propios o vía ACM/KMS), aplica las reglas de firma/dominio sobre el tráfico en claro, y re-cifra antes de enviarlo al destino — disponible tanto para inspección de entrada como de salida.",
  },
  {
    tag: "Inspector Code Security",
    q: "Tu equipo de desarrollo quiere detectar vulnerabilidades de seguridad (y configuraciones erróneas de Infrastructure as Code) directamente en los pull requests de GitHub, antes de fusionar el código, sin depender solo de un escaneo posterior en producción. ¿Qué capacidad de Amazon Inspector cubre esto?",
    options: [
      "Inspector Network Reachability, que analiza rutas de red",
      "Amazon Inspector Code Security: se integra nativamente con repositorios de GitHub y GitLab para escanear código fuente, dependencias e IaC en cada push/pull request o en el pipeline de CI/CD, mostrando los hallazgos tanto en la consola de Inspector como en la propia plataforma de control de versiones",
      "Amazon Inspector solo puede escanear imágenes ya publicadas en ECR, nunca código fuente",
      "Amazon CodeGuru Reviewer, que sustituyó a Inspector en 2025",
    ],
    correct: 1,
    explain: "Con el lanzamiento de Inspector Code Security (2025), Inspector amplía su alcance más allá de EC2/ECR/Lambda hacia el código fuente: integración nativa con GitHub y GitLab para analizar vulnerabilidades, dependencias e IaC en el momento del commit/PR o en CI/CD, con feedback directo en la plataforma de control de versiones — complementando (no sustituyendo) a CodeGuru Security.",
  },
  {
    tag: "Inspector organization-wide management",
    q: "Como administrador delegado de seguridad en AWS Organizations, quieres habilitar y configurar de forma centralizada qué tipos de escaneo de Amazon Inspector (por ejemplo, Lambda Code Scanning o Code Security) se aplican automáticamente en todas las cuentas de ciertas unidades organizativas (OUs), sin tener que configurarlo cuenta por cuenta. ¿Qué mecanismo usas?",
    options: [
      "Un Service Control Policy (SCP) que bloquee la desactivación de Inspector",
      "Gestión de Amazon Inspector a través de políticas de AWS Organizations: permite configurar y aplicar de forma centralizada los tipos de escaneo (incluyendo Lambda Code Scanning y Code Security) en todas las cuentas, OUs seleccionadas, o cuentas individuales de la organización",
      "AWS Config conformance packs únicamente",
      "Tienes que activarlo manualmente en cada cuenta miembro, no existe gestión centralizada",
    ],
    correct: 1,
    explain: "Amazon Inspector añadió soporte para gestión centralizada mediante políticas de AWS Organizations, permitiendo a un administrador delegado definir qué escaneos (Lambda, EC2, ECR, Code Security) se activan por defecto en toda la organización o en OUs concretas, eliminando la necesidad de habilitarlo cuenta por cuenta.",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "GuardDuty genera múltiples findings de baja severidad aparentemente inconexos sobre una instancia EC2 y una tarea ECS relacionada (acceso inusual a credenciales, luego una conexión de red sospechosa poco después). ¿Qué capacidad de GuardDuty está diseñada para correlacionar esta secuencia y elevarla a un único hallazgo crítico de 'ataque en curso'?",
    options: [
      "Extended Threat Detection: correlaciona múltiples señales y eventos a lo largo del tiempo (entre EC2, ECS, EKS, S3, IAM, etc.) para identificar secuencias de ataque multietapa, generando un finding de severidad crítica cuando detecta un patrón de compromiso en progreso",
      "GuardDuty Malware Protection, que solo escanea volúmenes EBS",
      "Amazon Detective, que sustituye a GuardDuty",
      "AWS Config Rules",
    ],
    correct: 0,
    explain: "Extended Threat Detection (ampliado a EC2 y ECS) usa modelos de correlación para conectar hallazgos individuales de bajo riesgo distribuidos en el tiempo y en distintos recursos, identificando secuencias que en conjunto indican un ataque activo multietapa — reduciendo el ruido de alertas aisladas y priorizando lo que realmente importa investigar.",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "GuardDuty detecta actividad sospechosa en una instancia EC2 (por ejemplo, comunicación con un dominio de mando y control conocido). ¿Qué hace GuardDuty Malware Protection for EC2 automáticamente a partir de ahí, y qué impacto tiene sobre la instancia en ejecución?",
    options: [
      "Termina la instancia inmediatamente para contener la amenaza",
      "Realiza un escaneo agentless de los volúmenes EBS adjuntos (a partir de un snapshot) en busca de malware conocido, SIN necesidad de instalar un agente y SIN impacto en el rendimiento de la instancia en ejecución",
      "Requiere instalar el agente de Inspector en la instancia antes de poder escanear nada",
      "Solo funciona si la instancia está detenida (stopped)",
    ],
    correct: 1,
    explain: "Malware Protection for EC2 se activa automáticamente cuando GuardDuty detecta un hallazgo sospechoso, y escanea los volúmenes EBS asociados a partir de un snapshot (proceso agentless) para buscar malware conocido — sin instalar nada en la instancia ni afectar a su rendimiento o disponibilidad mientras se ejecuta el análisis.",
  },
  {
    tag: "VPC Route Server",
    q: "Tienes appliances de red virtuales de terceros (firewalls NVA) desplegados en tu VPC que necesitan anunciar dinámicamente rutas hacia las tablas de rutas de las subnets, sin mantener scripts personalizados ni una red overlay para sincronizar los cambios. ¿Qué servicio de AWS resuelve esto de forma nativa?",
    options: [
      "AWS Transit Gateway exclusivamente",
      "Amazon VPC Route Server: permite que los NVA anuncien rutas vía BGP, y actualiza dinámicamente las tablas de rutas de las subnets e Internet Gateway asociadas, eliminando la necesidad de scripts personalizados o redes overlay",
      "AWS Network Firewall, que gestiona rutas automáticamente",
      "Route 53 Resolver",
    ],
    correct: 1,
    explain: "VPC Route Server (GA abril 2025) introduce enrutamiento dinámico nativo dentro de una VPC: los NVA anuncian rutas por BGP al Route Server, que a su vez actualiza automáticamente las tablas de rutas de las subnets e Internet Gateway suscritas — antes había que resolver esto con automatización custom (Lambda + API de route tables) o topologías overlay complejas.",
  },
  {
    tag: "Verified Access non-HTTP(S)",
    q: "Además de aplicaciones web internas, tu equipo necesita dar acceso Zero Trust (evaluando identidad y postura del dispositivo) a bases de datos y a sesiones SSH/RDP hacia instancias EC2, sin desplegar una VPN de red completa. ¿Qué capacidad reciente de AWS Verified Access permite esto?",
    options: [
      "Verified Access solo soporta tráfico HTTP(S); para SSH/RDP hay que usar Site-to-Site VPN",
      "Soporte de Verified Access para protocolos no HTTP(S) (TCP genérico, incluyendo SSH y RDP): extiende las mismas políticas de acceso basadas en identidad y postura del dispositivo a recursos como bases de datos, repositorios git o instancias EC2 por SSH/RDP",
      "Hay que migrar esas cargas a AWS Client VPN, que es el único servicio con soporte SSH/RDP",
      "Solo es posible mediante un Direct Connect dedicado",
    ],
    correct: 1,
    explain: "Desde su disponibilidad general (GA, febrero 2025), Verified Access extiende el modelo Zero Trust más allá de HTTP(S) a protocolos TCP genéricos como SSH y RDP, permitiendo centralizar políticas de acceso (identidad + postura del dispositivo) para bases de datos, repositorios de código o acceso administrativo a EC2 — sin gestionar credenciales SSH ni exponer un túnel de red completo.",
  },
  {
    tag: "Security Group Referencing (Transit Gateway)",
    q: "Tienes dos VPCs conectadas a través de AWS Transit Gateway (no peering directo) y quieres permitir tráfico entre instancias de una VPC y otra referenciando directamente el Security Group de origen en la regla de entrada del Security Group de destino (en vez de usar rangos CIDR). ¿Es esto posible?",
    options: [
      "No, el referenciado de Security Groups entre VPCs solo funciona con VPC Peering directo, nunca a través de Transit Gateway",
      "Sí: AWS anunció disponibilidad general de Security Group Referencing sobre Transit Gateway, permitiendo especificar security groups de otras VPCs conectadas vía TGW como origen/destino en las reglas, sin depender de rangos CIDR estáticos",
      "Solo es posible si ambas VPCs están en la misma cuenta de AWS",
      "Solo funciona para tráfico UDP",
    ],
    correct: 1,
    explain: "Antes de esta capacidad (GA septiembre 2024), el referenciado cruzado de Security Groups solo estaba soportado en VPC Peering; el tráfico a través de Transit Gateway obligaba a usar rangos CIDR (más frágiles y difíciles de mantener a escala). Ahora también se puede referenciar el SG de una VPC remota conectada vía TGW, simplificando la segmentación este-oeste en topologías hub-and-spoke.",
  },
  {
    tag: "ECR Image Signing",
    q: "Quieres garantizar que solo se puedan desplegar en tu clúster imágenes de contenedor que efectivamente provienen de tu pipeline de CI/CD autorizado, protegiendo la cadena de suministro de software frente a imágenes manipuladas o no verificadas. ¿Qué capacidad de Amazon ECR ayuda a esto?",
    options: [
      "ECR pull-through cache, que solo sirve para cachear imágenes de registros públicos",
      "ECR managed image signing, integrado con AWS Signer: firma automáticamente las imágenes al hacer push a ECR, permitiendo verificar la firma (procedencia) antes del despliegue, como parte de la seguridad de la cadena de suministro de software",
      "Activar el escaneo mejorado de vulnerabilidades (enhanced scanning) — eso ya garantiza la procedencia",
      "Es una funcionalidad exclusiva de Docker Hub, no de ECR",
    ],
    correct: 1,
    explain: "ECR managed image signing usa AWS Signer para firmar automáticamente cada imagen en el push, generando una firma verificable de procedencia. Combinado con validación de firma en el despliegue (ej. en el clúster), evita ejecutar imágenes manipuladas o de origen desconocido — el escaneo de vulnerabilidades (enhanced scanning) es un control distinto y complementario, no garantiza procedencia.",
  },
  {
    tag: "Declarative Policies (IMDSv2)",
    q: "Quieres garantizar, a nivel de toda la organización de AWS Organizations, que NINGUNA instancia EC2 nueva pueda desplegarse con IMDSv1 habilitado (mitigando el vector SSRF), de forma que la configuración se mantenga aplicada incluso si se añaden cuentas nuevas o AWS introduce nuevas APIs de EC2. ¿Qué mecanismo usas, a diferencia de una SCP tradicional?",
    options: [
      "Una Service Control Policy (SCP) que deniegue la acción RunInstances si no se especifica IMDSv2",
      "Una Declarative Policy de AWS Organizations para EC2: define el estado deseado (IMDSv2 obligatorio) de forma centralizada desde la cuenta de gestión o un delegado, y AWS mantiene esa configuración de forma persistente sin necesidad de reescribir la política ante nuevas APIs o cuentas",
      "AWS Config con remediación automática, que revierte la instancia después de creada",
      "Etiquetar todas las instancias como 'IMDSv2-only' manualmente",
    ],
    correct: 1,
    explain: "Las Declarative Policies (GA diciembre 2024) son un tipo de política de Organizations distinto de las SCP: en vez de denegar acciones de la API, declaran el ESTADO deseado de una configuración (ej. 'IMDSv2 requerido' para EC2) y AWS se encarga de que ese estado se mantenga de forma centralizada y resiliente a cambios futuros del servicio — más robusto que mantener una SCP compleja o depender de remediación reactiva post-creación.",
  },
  {
    tag: "VPC Lattice Auth Policies",
    q: "Estás diseñando una malla de microservicios que cruza varias VPCs y cuentas de AWS, y quieres controlar qué servicio concreto puede invocar qué otro servicio y con qué método HTTP, usando identidad (SigV4/IAM) en vez de solo direcciones IP — de forma independiente a los Security Groups que gestiona el equipo de red. ¿Qué mecanismo de VPC Lattice aplica?",
    options: [
      "Los Network ACLs de cada VPC, que ya controlan esto por IP",
      "Auth Policies de VPC Lattice: documentos de política estilo IAM adjuntos a nivel de service network o de servicio individual, que autorizan (o deniegan) el acceso de un principal concreto a rutas/métodos específicos — complementarios, no sustitutos, de los Security Groups",
      "AWS Verified Access, que sustituye a VPC Lattice para este caso",
      "Una NAT Gateway compartida entre cuentas",
    ],
    correct: 1,
    explain: "VPC Lattice introduce autorización basada en identidad (auth policies tipo IAM) a nivel de service network o de servicio individual, permitiendo definir qué principal (rol/servicio) puede invocar qué operación — separando la responsabilidad de 'qué servicio puede llamar a cuál' (equipo de aplicaciones) de 'qué IP puede llegar a la red' (equipo de red/Security Groups). Para que la autorización tenga éxito, tanto la auth policy de Lattice como la política de identidad de IAM deben permitir explícitamente el acceso.",
  },
  {
    tag: "Route 53 Resolver DNS Firewall Advanced",
    q: "Sospechas que un host comprometido dentro de tu VPC está usando un Domain Generation Algorithm (DGA) para generar nombres de dominio pseudoaleatorios y comunicarse con infraestructura de mando y control (C2), evadiendo las listas de bloqueo de dominios estáticas. ¿Qué servicio de AWS detecta este patrón específico en tiempo real?",
    options: [
      "Route 53 Resolver DNS Firewall (la versión estándar, basada solo en listas de dominios)",
      "Route 53 Resolver DNS Firewall Advanced: analiza en tiempo real anomalías en los nombres de dominio consultados desde tus VPCs para detectar y bloquear patrones asociados a DGA (incluyendo variantes basadas en diccionario) y DNS tunneling, que las listas estáticas de dominios no pueden cubrir",
      "AWS Network Firewall con reglas de dominio (FQDN) únicamente",
      "Amazon GuardDuty, que bloquea el tráfico automáticamente",
    ],
    correct: 1,
    explain: "DNS Firewall Advanced (lanzado en 2024, con protección adicional contra DGA basado en diccionario añadida en 2025) va más allá del filtrado por listas estáticas de dominios: analiza en tiempo real las características de los nombres de dominio consultados para identificar los patrones típicos de DGA y DNS tunneling, amenazas diseñadas precisamente para evadir bloqueos basados en listas conocidas. GuardDuty puede DETECTAR y generar findings sobre actividad DNS sospechosa, pero no bloquea el tráfico DNS por sí mismo — eso corresponde a DNS Firewall.",
  },
  {
    tag: "PrivateLink endpoint policies",
    q: "Tu equipo ha creado un interface VPC endpoint hacia Amazon S3 para que las instancias en una subnet privada puedan acceder a S3 sin salir a Internet. Quieres asegurarte de que, a través de ESE endpoint concreto, solo se pueda acceder a un bucket específico, independientemente de los permisos IAM que tenga cada rol. ¿Qué mecanismo usas?",
    options: [
      "Modificar el Security Group del endpoint para filtrar por nombre de bucket",
      "Una Endpoint Policy: una política de recursos (en lenguaje IAM, con elemento Principal) adjunta al VPC endpoint que restringe qué acciones y qué recursos son accesibles A TRAVÉS de ese endpoint concreto — actúa como un control adicional, no sustituye a las políticas de IAM ni a la bucket policy",
      "Una NACL en la subnet donde vive el endpoint",
      "No es posible, todo endpoint da acceso completo al servicio",
    ],
    correct: 1,
    explain: "El Security Group de un interface endpoint solo controla acceso a nivel de red (qué puede conectar al ENI del endpoint, por IP/puerto) — no entiende de buckets S3. La Endpoint Policy es un resource policy en formato IAM que se adjunta al endpoint y limita explícitamente qué principals pueden realizar qué acciones sobre qué recursos usando ESE endpoint concreto, funcionando como una capa adicional de control junto con (no en sustitución de) las políticas de identidad IAM y la bucket policy del recurso.",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "Estás diseñando los controles de red de una VPC. ¿Qué DOS afirmaciones sobre security groups y network ACLs son correctas?",
    options: [
      "Los security groups son stateful: el tráfico de vuelta se permite automáticamente aunque no haya regla de salida",
      "Las network ACLs son stateless y admiten reglas de Deny explícitas, evaluadas por número de regla",
      "Los security groups permiten reglas de Deny explícitas para bloquear IPs concretas",
      "Las network ACLs se aplican a la interfaz de red de la instancia, no a la subred",
    ],
    correct: [0, 1],
    explain: "Es la comparación más preguntada del dominio. Los <b>SG son stateful</b> (solo permiten, y la vuelta es automática) y se aplican a la ENI; las <b>NACL son stateless</b> (permiten y deniegan, se evalúan en orden numérico y hay que abrir la vuelta explícitamente, típicamente los puertos efímeros) y se aplican a la subred. Por eso, para bloquear una IP concreta la herramienta es la NACL, no el security group.",
  },
  {
    tag: "Protección de una aplicación web pública",
    q: "Una aplicación web tras CloudFront sufre inyección SQL y un ataque volumétrico de capa 3/4. ¿Qué DOS servicios abordan directamente estas amenazas?",
    options: [
      "AWS WAF con los managed rule groups adecuados, para la inyección SQL",
      "AWS Shield, para la mitigación del ataque volumétrico de capa 3/4",
      "Amazon Inspector, que bloquea las peticiones maliciosas en tiempo real",
      "AWS Config, que impide que lleguen peticiones con payloads sospechosos",
    ],
    correct: [0, 1],
    explain: "<b>WAF</b> inspecciona en capa 7 y frena SQLi/XSS con reglas gestionadas; <b>Shield</b> mitiga DDoS volumétrico en capa 3/4 (Standard viene incluido, Advanced añade protección y respuesta gestionada). Inspector evalúa <i>vulnerabilidades</i> de instancias, contenedores y Lambda: no filtra tráfico. Config evalúa la <i>configuración</i> de recursos: tampoco está en el camino de la petición. Distinguir quién está en línea del tráfico y quién no es clave.",
  },
  {
    tag: "Acceso administrativo sin SSH expuesto",
    q: "Seguridad prohíbe abrir el puerto 22 a internet y quiere eliminar los bastion hosts, pero los operadores necesitan acceso de shell a instancias EC2 en subredes privadas. ¿Qué DOS elementos permiten esto?",
    options: [
      "AWS Systems Manager Session Manager, que abre la sesión sin puertos de entrada",
      "El SSM Agent instalado en la instancia y un instance profile con permisos para Systems Manager",
      "Una regla de security group que permita el puerto 22 desde el rango de IPs corporativo",
      "Una Elastic IP en cada instancia para que Systems Manager pueda alcanzarla",
    ],
    correct: [0, 1],
    explain: "<b>Session Manager</b> funciona con una conexión <i>saliente</i> del agente hacia el servicio, así que no requiere puertos de entrada, ni IP pública, ni bastion — y además registra la sesión en CloudTrail/S3/CloudWatch. Necesita las dos piezas: <b>agente</b> y <b>permisos vía instance profile</b>. Abrir el 22, aunque sea a un rango corporativo, es justo lo que se quiere eliminar, y la Elastic IP expondría la instancia en vez de protegerla.",
  },
  {
    tag: "Imágenes base endurecidas",
    q: "La empresa quiere garantizar que todas las instancias EC2 arrancan desde imágenes endurecidas y parcheadas. ¿Qué DOS servicios encajan en esa cadena?",
    options: [
      "EC2 Image Builder, para construir y versionar AMIs endurecidas de forma repetible",
      "Amazon Inspector, para detectar vulnerabilidades conocidas en las imágenes y las instancias",
      "AWS Shield Advanced, para validar que la AMI no contiene malware",
      "Amazon Macie, para escanear el sistema operativo de la AMI en busca de CVEs",
    ],
    correct: [0, 1],
    explain: "<b>Image Builder</b> automatiza la construcción, el endurecimiento y el versionado de AMIs, e <b>Inspector</b> las evalúa contra CVEs conocidos de forma continua. Shield es exclusivamente anti-DDoS. Y Macie descubre y clasifica <b>datos sensibles en S3</b> — no analiza sistemas operativos: confundir Macie con un escáner de vulnerabilidades es un distractor recurrente.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["infrastructure-security"] = QUIZ_DATA;
