const QUIZ_DATA = [
  {
    tag: "Security Groups vs NACLs",
    q: "¿Cuál es la diferencia MÁS importante entre un Security Group y una Network ACL en cuanto a su comportamiento?",
    options: [
      "El Security Group es a nivel de subnet y la NACL a nivel de instancia",
      "El Security Group es STATEFUL (el tráfico de retorno se permite automáticamente) y solo admite reglas Allow; la NACL es STATELESS (hay que permitir explícitamente ida Y vuelta) y admite reglas Allow y Deny evaluadas en orden numérico",
      "Ambos son idénticos, solo cambia dónde se configuran en la consola",
      "La NACL solo filtra tráfico HTTP/HTTPS",
    ],
    correct: 1,
    explain: "Security Group = stateful, a nivel de ENI/instancia, solo Allow (todo lo no permitido se deniega implícitamente). NACL = stateless, a nivel de subnet, con reglas numeradas evaluadas en orden que pueden ser Allow o Deny — por eso hay que abrir el tráfico de retorno (puertos efímeros) explícitamente.",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "Detectas tráfico malicioso repetido desde una IP concreta y quieres bloquearla de inmediato a nivel de red, sin depender de que ninguna instancia tenga una regla que lo permita. ¿Qué mecanismo usas?",
    options: [
      "Una regla Deny en la Network ACL de la subnet (los Security Groups no pueden denegar explícitamente una IP)",
      "Añadir la IP a un Security Group con Deny",
      "Modificar el route table de la subnet",
      "Activar GuardDuty",
    ],
    correct: 0,
    explain: "Los Security Groups NO tienen reglas Deny — solo puedes especificar qué se permite. Para bloquear explícitamente una IP concreta a nivel de red (independientemente de qué Security Group tenga cada instancia), necesitas una regla Deny en la NACL de la subnet, evaluada antes de que el tráfico llegue a la instancia.",
  },
  {
    tag: "AWS WAF",
    q: "¿Qué tipo de ataque está diseñado para detectar y bloquear un 'rate-based rule' en AWS WAF?",
    options: [
      "Inyección SQL únicamente",
      "Un volumen anómalamente alto de requests desde la misma IP (o clave de agregación) en una ventana de tiempo — por ejemplo, fuerza bruta de login o scraping agresivo",
      "Ataques que ya pasaron por CloudFront",
      "Solo tráfico UDP",
    ],
    correct: 1,
    explain: "Las rate-based rules de WAF cuentan requests por clave de agregación (IP de origen por defecto, o una combinación custom) en ventanas deslizantes de 5 o 10 minutos, y bloquean automáticamente cuando se supera el umbral — ideal contra fuerza bruta, credential stuffing o scraping, complementario a las reglas de firma (SQLi, XSS del OWASP Top 10).",
  },
  {
    tag: "Shield Advanced",
    q: "¿Qué añade AWS Shield Advanced sobre la protección DDoS estándar (Shield Standard) que viene gratis con todas las cuentas?",
    options: [
      "Nada, Shield Standard ya cubre todos los casos",
      "Protección avanzada contra ataques de capa 3/4 y 7 más sofisticados, acceso al DDoS Response Team (DRT), reembolso de costes por picos de escalado durante un ataque, y visibilidad/métricas detalladas — de pago, por cuenta o por recurso",
      "Solo protege Route 53, no CloudFront ni ALB",
      "Shield Advanced sustituye a WAF completamente",
    ],
    correct: 1,
    explain: "Shield Standard (gratis, automático) cubre los ataques DDoS más comunes de capa 3/4. Shield Advanced añade protección ampliada, el DDoS Response Team disponible 24/7, cost protection (créditos si escalas por un ataque), y se integra con WAF para mitigación de capa 7 — recomendado para cargas críticas con SLA de disponibilidad.",
  },
  {
    tag: "Edge security",
    q: "Quieres bloquear el acceso a tu aplicación distribuida vía CloudFront desde todos los países excepto España y Portugal. ¿Qué mecanismo usas?",
    options: [
      "Un Security Group con reglas por país",
      "CloudFront Geo Restriction (allowlist de países) o una regla de geo-match en AWS WAF asociada a la distribución",
      "Una NACL con rangos CIDR por país",
      "Route 53 Resolver DNS Firewall",
    ],
    correct: 1,
    explain: "CloudFront Geo Restriction permite allowlist/blocklist de países directamente en la distribución. Alternativamente, una regla de geo-match en WAF (asociada a CloudFront) ofrece lo mismo con más flexibilidad para combinarlo con otras condiciones (rate limiting, fingerprinting).",
  },
  {
    tag: "S3 CORS",
    q: "Tu SPA en https://app.midominio.com necesita hacer peticiones fetch() directamente a un bucket S3 para subir archivos, y el navegador las bloquea con un error de CORS. ¿Qué configuras?",
    options: [
      "Una bucket policy que permita el Principal '*'",
      "Una configuración CORS en el bucket S3 que permita explícitamente el origen https://app.midominio.com y los métodos/headers necesarios",
      "Desactivar HTTPS en el bucket",
      "Un Security Group en el bucket",
    ],
    correct: 1,
    explain: "CORS (Cross-Origin Resource Sharing) es una restricción del NAVEGADOR, no de AWS. S3 soporta una configuración CORS propia (AllowedOrigins, AllowedMethods, AllowedHeaders) que le dice al navegador que ese origen concreto tiene permiso para hacer peticiones cross-origin al bucket — independiente de la bucket policy o los permisos IAM.",
  },
  {
    tag: "Hardened AMIs",
    q: "¿Qué servicio de AWS está diseñado específicamente para construir, mantener y validar AMIs (o imágenes de contenedor) hardened de forma automatizada y repetible?",
    options: [
      "AWS Config",
      "EC2 Image Builder: pipeline automatizado que aplica hardening (ej. CIS benchmarks), instala parches y ejecuta tests de validación antes de publicar la AMI",
      "AWS Backup",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "EC2 Image Builder automatiza el pipeline completo: parte de una imagen base, aplica componentes de hardening/configuración, instala actualizaciones, ejecuta tests, y publica la AMI (o imagen de contenedor) resultante — eliminando el proceso manual y garantizando reproducibilidad entre versiones.",
  },
  {
    tag: "Instance profiles vs roles",
    q: "¿Qué relación hay entre un 'Instance Profile' de EC2 y un IAM Role?",
    options: [
      "Son sinónimos exactos, se puede usar cualquiera de los dos términos indistintamente en la API",
      "El Instance Profile es el CONTENEDOR que asocia un IAM Role a una instancia EC2 — es lo que realmente se adjunta a la instancia (la consola lo oculta creándolo automáticamente al 'asignar un rol')",
      "Un Instance Profile puede contener múltiples IAM Roles simultáneamente",
      "El Instance Profile sustituye a la necesidad de tener un IAM Role",
    ],
    correct: 1,
    explain: "Técnicamente no adjuntas un IAM Role directamente a una instancia EC2: adjuntas un Instance Profile, que a su vez referencia UN único IAM Role. La consola de AWS oculta esta distinción creando el Instance Profile automáticamente, pero la CLI/API la expone (aws iam create-instance-profile + add-role-to-instance-profile).",
  },
  {
    tag: "Amazon Inspector",
    q: "¿Qué tipos de recursos puede escanear Amazon Inspector en busca de vulnerabilidades conocidas (CVEs)?",
    options: [
      "Solo instancias EC2",
      "Instancias EC2, imágenes de contenedor en Amazon ECR, y funciones Lambda (código y capas) — de forma continua, no solo bajo demanda",
      "Solo bases de datos RDS",
      "Solo buckets S3",
    ],
    correct: 1,
    explain: "Amazon Inspector escanea de forma continua y automática EC2 (paquetes de SO y vulnerabilidades de red), imágenes de contenedor en ECR (al hacer push y periódicamente), y funciones Lambda (dependencias en el código). GuardDuty, en cambio, monitoriza el RUNTIME (comportamiento anómalo en tiempo real), no vulnerabilidades estáticas conocidas.",
  },
  {
    tag: "Patch management",
    q: "¿Qué componente de Systems Manager automatiza la aplicación de parches de seguridad del sistema operativo en una flota de instancias EC2, según una ventana de mantenimiento programada?",
    options: [
      "Systems Manager Session Manager",
      "Systems Manager Patch Manager, típicamente orquestado con Maintenance Windows",
      "Systems Manager Parameter Store",
      "AWS Config",
    ],
    correct: 1,
    explain: "Patch Manager automatiza el escaneo y la aplicación de parches (SO y algunas aplicaciones) según baselines de aprobación configurables, ejecutado dentro de Maintenance Windows para controlar cuándo ocurre el impacto — clave para el skill 3.2.4 de 'desplegar parches de forma automatizada y con validación continua'.",
  },
  {
    tag: "Acceso administrativo seguro",
    q: "Quieres dar a los ingenieros acceso de shell a instancias EC2 en subnets privadas sin abrir el puerto 22, sin gestionar claves SSH, y con toda la sesión auditada en CloudTrail. ¿Qué usas?",
    options: [
      "EC2 Instance Connect con IP pública",
      "AWS Systems Manager Session Manager: crea un túnel a través del agente SSM, sin necesidad de puerto 22 abierto, bastion host, ni claves SSH, y registra cada comando ejecutado",
      "Un bastion host tradicional con NAT Gateway",
      "Desactivar el Security Group temporalmente",
    ],
    correct: 1,
    explain: "Session Manager establece la sesión a través del agente SSM saliente (HTTPS), sin necesidad de abrir puertos entrantes, bastion hosts, ni distribuir claves SSH — y todos los comandos quedan auditados (CloudTrail + logs opcionales a S3/CloudWatch). EC2 Instance Connect es la alternativa para SSH efímero pero SÍ requiere el puerto 22 accesible (aunque sea vía un rango controlado).",
  },
  {
    tag: "Seguridad en el pipeline",
    q: "¿Qué herramienta de AWS está diseñada para analizar código fuente y detectar vulnerabilidades de seguridad (ej. inyección, secretos hardcodeados) DENTRO del pipeline de CI/CD, antes de desplegar?",
    options: [
      "Amazon GuardDuty",
      "Amazon CodeGuru Security (y Amazon Q Developer para sugerencias/remediación asistida)",
      "AWS Config",
      "Amazon Detective",
    ],
    correct: 1,
    explain: "CodeGuru Security analiza estáticamente el código fuente en busca de vulnerabilidades (similar a un SAST — Static Application Security Testing) y secretos hardcodeados, integrable en el pipeline de CI/CD. Amazon Q Developer complementa con sugerencias de remediación asistidas por IA. GuardDuty y Detective operan sobre la cuenta en ejecución, no sobre el código fuente.",
  },
  {
    tag: "Guardrails para GenAI",
    q: "Estás construyendo una aplicación con un LLM que responde a usuarios finales, y necesitas protegerla contra prompt injection y fuga de datos sensibles en las respuestas. ¿Qué marco de referencia se menciona explícitamente en el exam guide de SCS-C03 para este tipo de protecciones?",
    options: [
      "PCI-DSS",
      "OWASP Top 10 for LLM Applications",
      "CIS Benchmarks estándar",
      "NIST 800-53 exclusivamente",
    ],
    correct: 1,
    explain: "El OWASP Top 10 for LLM Applications cataloga riesgos específicos de aplicaciones con modelos de lenguaje (prompt injection, fuga de datos sensibles, envenenamiento de entrenamiento, etc.) — un skill nuevo explícito en SCS-C03 (3.2.7), reflejando la adopción de GenAI en cargas de trabajo de producción.",
  },
  {
    tag: "Conectividad híbrida",
    q: "¿Qué diferencia a AWS Direct Connect de un AWS Site-to-Site VPN?",
    options: [
      "Son idénticos en rendimiento y coste",
      "Direct Connect es una conexión de red dedicada y privada (vía un partner o directamente) que NO atraviesa la Internet pública, con ancho de banda predecible; Site-to-Site VPN cifra el tráfico pero sigue viajando sobre Internet",
      "Site-to-Site VPN requiere hardware físico en tu datacenter mientras que Direct Connect no",
      "Direct Connect no puede combinarse con VPN",
    ],
    correct: 1,
    explain: "Direct Connect establece una conexión física dedicada entre tu datacenter y AWS (vía un DX location/partner), evitando la Internet pública — mejor latencia/consistencia, sin cifrado nativo (se añade con MACsec o una VPN sobre DX). Site-to-Site VPN crea un túnel IPsec cifrado sobre Internet, más rápido de desplegar pero con rendimiento menos predecible.",
  },
  {
    tag: "MACsec",
    q: "¿Para qué se usa MACsec (802.1AE) en el contexto de AWS Direct Connect?",
    options: [
      "Para acelerar la velocidad de la conexión",
      "Para cifrar el tráfico a nivel de capa 2 (Ethernet) en conexiones Direct Connect dedicadas de alta velocidad, ya que Direct Connect por sí solo no cifra el tráfico",
      "Para reemplazar completamente a Direct Connect",
      "Es un protocolo exclusivo de Site-to-Site VPN",
    ],
    correct: 1,
    explain: "Direct Connect no cifra el tráfico de forma nativa (es una conexión privada, pero no cifrada). MACsec añade cifrado a nivel de enlace (capa 2) en conexiones dedicadas de 10/100 Gbps, cumpliendo requisitos donde la confidencialidad del tráfico es obligatoria incluso sobre una conexión ya privada.",
  },
  {
    tag: "Verified Access en híbrido",
    q: "Tu empresa tiene aplicaciones internas que deben ser accesibles tanto para empleados en la oficina (red on-premises) como en remoto, sin exponerlas a Internet ni depender de una VPN de red completa. ¿Qué solución encaja con el skill 3.3.3?",
    options: [
      "AWS Site-to-Site VPN únicamente",
      "AWS Verified Access: evalúa identidad (IAM Identity Center) y postura del dispositivo en cada request, dando acceso a nivel de aplicación sin exponer un túnel de red completo entre on-premises y AWS",
      "Convertir todas las apps en públicas con WAF delante",
      "AWS Direct Connect por sí solo",
    ],
    correct: 1,
    explain: "Verified Access implementa Zero Trust Network Access (ZTNA): en vez de conectar redes completas (como VPN o Direct Connect), evalúa cada solicitud a una aplicación específica según identidad y postura del dispositivo, funcionando igual de bien para usuarios en la oficina que en remoto sin exponer la app a Internet.",
  },
  {
    tag: "Segmentación de red",
    q: "En el diseño de una VPC, ¿qué término describe el tráfico ENTRE cargas de trabajo dentro del mismo entorno (ej. entre microservicios en distintas subnets privadas), a diferencia del tráfico que entra/sale del perímetro?",
    options: [
      "Tráfico north/south",
      "Tráfico east/west",
      "Tráfico de tránsito (transit)",
      "Tráfico de peering",
    ],
    correct: 1,
    explain: "North/south es el tráfico que cruza el perímetro (cliente de Internet ↔ tu VPC). East/west es el tráfico interno entre cargas de trabajo (microservicio A ↔ microservicio B). Aislar y filtrar el tráfico east/west (con SGs específicos por capa, subnets aisladas, Network Firewall interno) reduce el blast radius si un componente se ve comprometido — un principio central del skill 3.3.4.",
  },
  {
    tag: "AWS Network Firewall",
    q: "¿En qué se diferencia AWS Network Firewall de un Security Group o una NACL?",
    options: [
      "Es exactamente lo mismo con otro nombre comercial",
      "Network Firewall es un firewall con estado a nivel de VPC/subnet que soporta inspección de capa 3-7 (incluyendo reglas basadas en dominio y firmas tipo IDS/IPS con Suricata), más avanzado que el filtrado de 5-tupla de SG/NACL",
      "Solo puede desplegarse en subnets públicas",
      "No soporta reglas basadas en dominio (FQDN)",
    ],
    correct: 1,
    explain: "SG y NACL filtran por IP/puerto/protocolo (5-tupla). AWS Network Firewall añade inspección profunda de paquetes (deep packet inspection), reglas de dominio (permitir solo salida a *.midominio.com), y reglas de firma compatibles con el formato Suricata (IDS/IPS) — pensado para tráfico de tránsito entre subnets o hacia Internet a través de un Gateway/Transit Gateway.",
  },
  {
    tag: "Detección de accesos innecesarios",
    q: "¿Qué herramienta te dice si existe una ruta de red alcanzable no intencionada entre dos recursos (ej. una instancia en subnet privada accesible desde Internet por una mala configuración en cadena de SG/NACL/route table)?",
    options: [
      "AWS Config Rules únicamente",
      "Amazon Inspector Network Reachability (o VPC Network Access Analyzer) — analiza toda la cadena de configuración de red para detectar rutas de acceso no intencionadas",
      "Amazon Macie",
      "AWS Trusted Advisor exclusivamente",
    ],
    correct: 1,
    explain: "Estas herramientas modelan toda la configuración de red (SGs, NACLs, route tables, peering, IGW/NAT) para determinar si existe una ruta alcanzable entre un origen y un destino que no debería existir — mucho más fiable que revisar manualmente cada componente por separado, exactamente el skill 3.3.5.",
  },
  {
    tag: "OCSF",
    q: "¿Qué es el Open Cybersecurity Schema Framework (OCSF) en el contexto de integraciones de seguridad con AWS?",
    options: [
      "Un servicio de AWS de pago para almacenar logs",
      "Un esquema de datos ABIERTO y estandarizado para normalizar eventos de seguridad de distintas fuentes (AWS y terceros), facilitando la correlación sin transformar cada formato propietario manualmente",
      "Un protocolo de cifrado",
      "El sucesor de CloudTrail",
    ],
    correct: 1,
    explain: "OCSF es un estándar abierto (impulsado por AWS y otros) para representar eventos de seguridad de forma consistente entre productos y proveedores distintos. Amazon Security Lake lo usa como formato nativo, facilitando integrar fuentes de terceros sin escribir un parser distinto para cada una — parte del skill 3.1.4 sobre integraciones edge.",
  },
];
