var QUIZ_DATA = [
  {
    tag: "Security Groups vs NACLs",
    q: "¿Cuál es la diferencia MÁS importante entre un Security Group y una Network ACL en cuanto a su comportamiento?",
    options: [
      "El security group es stateful: el retorno se permite solo y sus reglas son siempre de tipo Allow",
      "El security group se aplica a la subred completa y la network ACL a la interfaz de red de cada instancia",
      "Ambos son stateless y evalúan sus reglas por número hasta encontrar la primera coincidencia",
      "La network ACL es stateful y es el security group el que obliga a abrir los puertos efímeros",
    ],
    correct: 0,
    explain: "<strong>Security group</strong>: stateful, a nivel de ENI, solo reglas Allow (lo no permitido se deniega de forma implícita). <strong>Network ACL</strong>: stateless, a nivel de subred, con reglas numeradas que pueden ser Allow o Deny — por eso hay que abrir explícitamente el tráfico de retorno hacia los puertos efímeros. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "Detectas tráfico malicioso repetido desde una IP concreta y quieres bloquearla de inmediato a nivel de red, sin depender de que ninguna instancia tenga una regla que lo permita. ¿Qué mecanismo usas?",
    options: [
      "Crear en el security group una regla Deny de máxima prioridad para esa IP de origen",
      "Una regla Deny en la network ACL de la subred, evaluada antes de llegar a la instancia",
      "Quitar la ruta hacia esa IP en la tabla de rutas de la subred para descartar el tráfico",
      "Activar GuardDuty, que bloquea de forma automática las IP con reputación maliciosa",
    ],
    correct: 1,
    explain: "Los security groups <strong>no tienen reglas Deny</strong>: solo describen lo que se permite. Para bloquear una IP concreta con independencia de qué security group tenga cada instancia, la herramienta es una regla Deny en la NACL de la subred, con un número de regla más bajo que cualquier Allow que la afecte. GuardDuty <em>detecta</em>, pero no bloquea tráfico. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS WAF",
    q: "¿Qué tipo de ataque está diseñado para detectar y bloquear un 'rate-based rule' en AWS WAF?",
    options: [
      "La inyección SQL, comparando cada petición contra las firmas del OWASP Top 10",
      "Los ataques que CloudFront ya ha dejado pasar hasta el origen de la distribución",
      "Un volumen anómalo de peticiones desde una misma clave de agregación",
      "El tráfico UDP volumétrico dirigido contra la capa 3/4 del recurso protegido",
    ],
    correct: 2,
    explain: "Una rate-based rule cuenta peticiones por clave de agregación (la IP de origen por defecto, o una combinación propia) dentro de una ventana de evaluación de 60 a 600 segundos, y aplica la acción al superar el umbral. Sirve contra fuerza bruta, credential stuffing y scraping; las firmas de SQLi o XSS son trabajo de las reglas gestionadas. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Shield Advanced",
    q: "¿Qué añade AWS Shield Advanced sobre la protección DDoS estándar (Shield Standard) que viene gratis con todas las cuentas?",
    options: [
      "Nada relevante: Shield Standard ya incluye el equipo de respuesta y la protección de costes",
      "Sustituye a AWS WAF, porque integra sus reglas gestionadas dentro de la propia suscripción",
      "Amplía la protección a Route 53 y Global Accelerator, pero no a CloudFront ni a los ALB",
      "Mitigación L3/4 y L7 avanzada, equipo de respuesta (SRT), protección de costes y métricas",
    ],
    correct: 3,
    explain: "Shield Standard es gratuito y automático, y cubre los ataques de capa 3/4 más comunes. Shield Advanced es de pago y añade mitigación avanzada, acceso al <strong>Shield Response Team</strong>, <em>cost protection</em> (créditos si el ataque te obliga a escalar), métricas y diagnóstico detallados, e integración con WAF para la capa 7. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/ddos-advanced-summary.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Edge security",
    q: "Quieres bloquear el acceso a tu aplicación distribuida vía CloudFront desde todos los países excepto España y Portugal. ¿Qué mecanismo usas?",
    options: [
      "CloudFront Geo Restriction con lista de permitidos, o una regla geo-match en AWS WAF",
      "Un security group asociado a la distribución con reglas de entrada por país de origen",
      "Una network ACL en la subred de la distribución con los rangos CIDR de cada país",
      "Route 53 Resolver DNS Firewall, filtrando las consultas DNS por país de la petición",
    ],
    correct: 0,
    explain: "Geo Restriction se configura en la propia distribución y admite lista de permitidos o de bloqueados por país. La alternativa es una regla <code>geo-match</code> en un web ACL de WAF, que permite combinar el país con otras condiciones (rate limiting, rutas concretas). Una distribución de CloudFront no vive en una subred, así que ni los security groups ni las NACL la protegen. <a href=\"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/georestrictions.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 CORS",
    q: "Tu SPA en https://app.midominio.com necesita hacer peticiones fetch() directamente a un bucket S3 para subir archivos, y el navegador las bloquea con un error de CORS. ¿Qué configuras?",
    options: [
      "Una bucket policy que permita el Principal '*' sobre las acciones de subida de objetos",
      "Una configuración CORS en el bucket con ese origen y los métodos y cabeceras permitidos",
      "Un VPC endpoint de tipo gateway hacia S3, para que la petición no salga a la red pública",
      "Un security group asociado al bucket que permita la IP pública del navegador cliente",
    ],
    correct: 1,
    explain: "CORS es una restricción del <strong>navegador</strong>, no de la autorización de AWS: la petición se rechaza en el cliente aunque IAM la permita. S3 tiene su propia configuración CORS (<code>AllowedOrigins</code>, <code>AllowedMethods</code>, <code>AllowedHeaders</code>) con la que el bucket declara qué orígenes pueden llamarlo. Abrir la bucket policy no arregla nada y los buckets no tienen security groups. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Hardened AMIs",
    q: "¿Qué servicio de AWS está diseñado específicamente para construir, mantener y validar AMIs (o imágenes de contenedor) hardened de forma automatizada y repetible?",
    options: [
      "AWS Config, que evalúa la configuración de la AMI y la corrige antes de publicarla",
      "AWS Backup, que versiona la AMI base y aplica los parches en cada copia programada",
      "EC2 Image Builder, con pipelines que aplican hardening, parchean y validan la imagen",
      "Amazon Macie, que analiza el sistema de ficheros de la AMI en busca de CVE conocidos",
    ],
    correct: 2,
    explain: "EC2 Image Builder automatiza el pipeline entero: parte de una imagen base, encadena componentes de hardening (por ejemplo, los benchmarks CIS), instala actualizaciones, ejecuta pruebas de validación y publica la AMI o imagen de contenedor versionada. Config audita configuración de recursos, Backup gestiona copias y Macie clasifica datos sensibles en S3. <a href=\"https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Instance profiles vs roles",
    q: "¿Qué relación hay entre un 'Instance Profile' de EC2 y un IAM Role?",
    options: [
      "Son sinónimos exactos: la API de IAM acepta ambos términos de forma indistinta",
      "El instance profile sustituye al rol y lleva adjuntas sus propias políticas de permisos",
      "Un instance profile puede contener varios roles y la instancia elige uno al arrancar",
      "El instance profile es el contenedor que asocia un único rol de IAM a la instancia",
    ],
    correct: 3,
    explain: "A una instancia EC2 no se le adjunta un rol directamente: se le adjunta un <strong>instance profile</strong>, que referencia exactamente <em>un</em> rol de IAM. La consola oculta la distinción creando el profile con el mismo nombre que el rol, pero la CLI la expone (<code>create-instance-profile</code> + <code>add-role-to-instance-profile</code>). Un rol sí puede estar en varios profiles. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Inspector",
    q: "¿Qué tipos de recursos puede escanear Amazon Inspector en busca de vulnerabilidades conocidas (CVEs)?",
    options: [
      "Instancias EC2, imágenes de contenedor en Amazon ECR y funciones Lambda con sus capas",
      "Solo instancias EC2, y únicamente si tienen instalado el agente de CloudWatch Logs",
      "Bases de datos RDS y clústeres de Aurora, buscando parches del motor aún sin aplicar",
      "Buckets de S3, clasificando además los objetos que contienen datos personales sensibles",
    ],
    correct: 0,
    explain: "Inspector escanea de forma continua EC2 (paquetes del sistema operativo y alcanzabilidad de red), imágenes de ECR (al hacer push y de forma periódica) y funciones Lambda (dependencias del código y capas). Escanear datos en S3 es trabajo de Macie, y GuardDuty vigila el <em>comportamiento</em> en ejecución, no las vulnerabilidades conocidas. <a href=\"https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Patch management",
    q: "¿Qué componente de Systems Manager automatiza la aplicación de parches de seguridad del sistema operativo en una flota de instancias EC2, según una ventana de mantenimiento programada?",
    options: [
      "Session Manager, que abre una sesión en cada nodo y ejecuta el instalador de parches",
      "Patch Manager, orquestado con maintenance windows o con una patch policy",
      "Parameter Store, que guarda la lista de parches aprobados para cada grupo de nodos",
      "AWS Config, cuya remediación automática instala los parches que faltan en el nodo",
    ],
    correct: 1,
    explain: "Patch Manager escanea e instala parches según <strong>patch baselines</strong> con reglas de aprobación (por antigüedad, severidad o listas explícitas), y se ejecuta dentro de maintenance windows —o mediante una patch policy sobre toda la organización— para controlar cuándo se produce el impacto. Parameter Store guarda configuración y Config audita, ninguno parchea. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Acceso administrativo seguro",
    q: "Quieres dar a los ingenieros acceso de shell a instancias EC2 en subnets privadas sin abrir el puerto 22, sin gestionar claves SSH, y con toda la sesión auditada en CloudTrail. ¿Qué usas?",
    options: [
      "EC2 Instance Connect sobre una IP pública, con el puerto 22 abierto al rango de AWS",
      "Un bastion host en la subred pública, alcanzable a través de una NAT Gateway",
      "AWS Systems Manager Session Manager, con el agente SSM y un instance profile",
      "Desactivar temporalmente el security group mientras dura la sesión de mantenimiento",
    ],
    correct: 2,
    explain: "Session Manager establece la sesión a través de la conexión <strong>saliente</strong> del agente SSM por HTTPS: no hace falta abrir puertos de entrada, ni IP pública, ni bastion, ni distribuir claves. La actividad queda en CloudTrail y el registro de la sesión puede enviarse a S3 o CloudWatch Logs. EC2 Instance Connect sigue necesitando el puerto 22 alcanzable. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Seguridad en el pipeline",
    q: "Un equipo quiere impedir que lleguen a producción credenciales incrustadas en el código y dependencias con CVE conocidos. Exige que el fallo se detecte lo antes posible en el ciclo, no como un hallazgo sobre la instancia ya desplegada. ¿Qué control encaja con ese requisito?",
    options: [
      "GuardDuty Runtime Monitoring en la instancia, que avisa cuando la credencial se usa",
      "Escaneo de código y dependencias en el pipeline, que corta el build antes de publicar",
      "Amazon Inspector sobre la imagen ya subida a ECR, que informa después de cada push",
      "Una regla de AWS Config que marca el recurso como no conforme tras desplegarlo",
    ],
    correct: 1,
    explain: "La clave del enunciado es <strong>cuándo</strong> se detecta, no con qué servicio. Las otras tres opciones son controles reales y útiles, pero todos actúan <em>después</em>: GuardDuty observa la instancia en ejecución, Inspector escanea la imagen cuando ya está publicada en ECR y Config evalúa el recurso una vez desplegado. Solo el análisis dentro del pipeline impide que el artefacto llegue a publicarse. Amazon Inspector cubre hoy esa fase con Code Security, integrable en CI/CD y en los pull requests. <a href=\"https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Guardrails para GenAI",
    q: "Estás construyendo una aplicación con un LLM que responde a usuarios finales, y necesitas protegerla contra prompt injection y fuga de datos sensibles en las respuestas. ¿Qué marco de referencia se menciona explícitamente en el exam guide de SCS-C03 para este tipo de protecciones?",
    options: [
      "OWASP Top 10 for LLM Applications, catálogo de riesgos propios de aplicaciones con LLM",
      "PCI DSS, que define los controles de protección del dato de tarjeta en la aplicación",
      "Los CIS Benchmarks, que endurecen la configuración del sistema operativo anfitrión",
      "NIST SP 800-53, con los controles de seguridad federales para sistemas de información",
    ],
    correct: 0,
    explain: "El <strong>OWASP Top 10 for LLM Applications</strong> cataloga los riesgos específicos de las aplicaciones basadas en modelos de lenguaje: prompt injection, fuga de información sensible, envenenamiento de datos, consumo ilimitado, etc. Es un skill nuevo y explícito de SCS-C03 (3.2.7). En AWS, el control que lo implementa son las Guardrails de Amazon Bedrock. <a href=\"https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-prompt-attack.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Conectividad híbrida",
    q: "¿Qué diferencia a AWS Direct Connect de un AWS Site-to-Site VPN?",
    options: [
      "Son equivalentes en rendimiento y coste; solo cambia el proveedor que los suministra",
      "Direct Connect es un enlace privado dedicado que no cruza Internet; la VPN sí lo hace",
      "La Site-to-Site VPN exige hardware propio en el centro de datos y Direct Connect no",
      "Direct Connect no puede combinarse con una VPN sobre la misma conexión física",
    ],
    correct: 1,
    explain: "Direct Connect es un enlace físico dedicado entre tu red y AWS a través de una ubicación DX o un partner: evita Internet y ofrece ancho de banda y latencia predecibles, pero <strong>no cifra por sí solo</strong>. Site-to-Site VPN monta un túnel IPsec cifrado sobre Internet, rápido de desplegar pero con rendimiento variable. Se combinan a menudo: VPN IPsec por encima de DX. <a href=\"https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "MACsec",
    q: "¿Para qué se usa MACsec (802.1AE) en el contexto de AWS Direct Connect?",
    options: [
      "Para acelerar la conexión agrupando varios enlaces físicos dentro de un mismo LAG",
      "Para reemplazar a Direct Connect por un túnel cifrado que viaja sobre Internet",
      "Para cifrar en capa 2 el enlace dedicado de Direct Connect, que de por sí no cifra",
      "Para cifrar los túneles de Site-to-Site VPN, donde es el protocolo por defecto",
    ],
    correct: 2,
    explain: "Direct Connect es una conexión privada, pero <strong>no cifrada</strong>. MACsec (IEEE 802.1AE) añade confidencialidad, integridad y autenticidad de origen a nivel de enlace en conexiones dedicadas de 10, 100 y 400 Gbps, mediante un par CKN/CAK provisionado en tu equipo de borde. Cubre el requisito de cifrar en tránsito sin montar una VPN por encima. <a href=\"https://docs.aws.amazon.com/directconnect/latest/UserGuide/MACsec.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Verified Access en híbrido",
    q: "Tu empresa tiene aplicaciones internas que deben ser accesibles tanto para empleados en la oficina (red on-premises) como en remoto, sin exponerlas a Internet ni depender de una VPN de red completa. ¿Qué solución encaja con el skill 3.3.3?",
    options: [
      "AWS Site-to-Site VPN, que conecta la red de la oficina con la VPC de las aplicaciones",
      "AWS Direct Connect, que da acceso privado a la aplicación desde cualquier ubicación",
      "Publicar las aplicaciones en Internet con AWS WAF y Shield Advanced por delante",
      "AWS Verified Access, que evalúa identidad y postura del dispositivo en cada petición",
    ],
    correct: 3,
    explain: "Verified Access implementa <strong>ZTNA</strong>: en lugar de unir redes enteras, autoriza cada petición a una aplicación concreta según la identidad (IAM Identity Center o un IdP externo) y las señales de postura del dispositivo. Funciona igual dentro de la oficina que en remoto y no expone la aplicación a Internet. VPN y Direct Connect conectan <em>redes</em>, no aplicaciones. <a href=\"https://docs.aws.amazon.com/verified-access/latest/ug/what-is-verified-access.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Segmentación de red",
    q: "En el diseño de una VPC, ¿qué término describe el tráfico ENTRE cargas de trabajo dentro del mismo entorno (ej. entre microservicios en distintas subnets privadas), a diferencia del tráfico que entra/sale del perímetro?",
    options: [
      "Tráfico east/west, el que fluye entre cargas de trabajo dentro del mismo entorno",
      "Tráfico north/south, el que atraviesa el perímetro entre Internet y la VPC",
      "Tráfico de tránsito, el que un Transit Gateway reenvía entre VPC de distintas cuentas",
      "Tráfico de peering, el que cruza una conexión de emparejamiento entre dos VPC",
    ],
    correct: 0,
    explain: "<strong>North/south</strong> es el tráfico que cruza el perímetro (cliente de Internet ↔ VPC); <strong>east/west</strong> es el interno entre componentes. Segmentar y filtrar el east/west —security groups por capa, subredes aisladas, Network Firewall o VPC Lattice— reduce el radio de impacto cuando un componente cae, que es justo el objetivo del skill 3.3.4. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_network_protection_layered.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Network Firewall",
    q: "¿En qué se diferencia AWS Network Firewall de un Security Group o una NACL?",
    options: [
      "Es el mismo motor de filtrado que los security groups, expuesto con otro nombre comercial",
      "Es un firewall gestionado con inspección L3-L7, reglas de dominio y firmas Suricata",
      "Solo puede desplegarse en subredes públicas, justo delante del Internet Gateway",
      "Filtra por 5-tupla igual que una NACL, pero además mantiene el estado de la conexión",
    ],
    correct: 1,
    explain: "Los security groups y las NACL filtran por 5-tupla (IP, puerto, protocolo). Network Firewall es un servicio gestionado que se despliega en subredes propias de inspección y añade inspección profunda de paquetes, reglas de dominio/SNI y reglas con formato <strong>Suricata</strong> (IDS/IPS), pensado para el tráfico de salida o de tránsito entre VPC. <a href=\"https://docs.aws.amazon.com/network-firewall/latest/developerguide/what-is-aws-network-firewall.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Detección de accesos innecesarios",
    q: "¿Qué herramienta te dice si existe una ruta de red alcanzable no intencionada entre dos recursos (ej. una instancia en subnet privada accesible desde Internet por una mala configuración en cadena de SG/NACL/route table)?",
    options: [
      "AWS Config, con reglas gestionadas que detectan los puertos abiertos a Internet",
      "Amazon Macie, que descubre qué recursos resultan alcanzables desde fuera de la cuenta",
      "Network Access Analyzer, o el análisis de alcanzabilidad de red de Inspector",
      "AWS Trusted Advisor, con su comprobación de puertos de seguridad expuestos",
    ],
    correct: 2,
    explain: "Estas herramientas <strong>modelan</strong> la configuración de red completa —security groups, NACL, tablas de rutas, peering, IGW y NAT— y calculan si existe una ruta alcanzable entre origen y destino. Es mucho más fiable que revisar cada componente por separado: el fallo suele estar en la <em>combinación</em>, no en una regla aislada. Es el skill 3.3.5. <a href=\"https://docs.aws.amazon.com/vpc/latest/network-access-analyzer/what-is-network-access-analyzer.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "OCSF",
    q: "¿Qué es el Open Cybersecurity Schema Framework (OCSF) en el contexto de integraciones de seguridad con AWS?",
    options: [
      "Un servicio gestionado de AWS para almacenar y consultar logs de seguridad",
      "El sucesor de CloudTrail para el registro de llamadas a la API de AWS",
      "Un protocolo de cifrado en tránsito para enviar eventos entre cuentas",
      "Un esquema abierto que normaliza eventos de seguridad de fuentes distintas",
    ],
    correct: 3,
    explain: "OCSF es un estándar <strong>abierto</strong> impulsado por AWS y otros fabricantes para representar eventos de seguridad con un esquema común. Amazon Security Lake lo usa como formato nativo: convierte automáticamente los logs de los servicios de AWS y exige a las fuentes personalizadas que entreguen ya en OCSF, de modo que correlacionar no obligue a escribir un parser por producto. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/open-cybersecurity-schema-framework.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "WAF Fraud Control – ATP",
    q: "Tu equipo de seguridad detecta un aumento de intentos de login con credenciales robadas (credential stuffing) contra el endpoint de login de tu aplicación, servido detrás de CloudFront. Los atacantes usan pares email/contraseña filtrados en otras brechas, y muchos aciertan porque los usuarios reutilizan contraseñas. ¿Qué componente de AWS WAF Fraud Control resuelve específicamente este caso de uso?",
    options: [
      "Account Takeover Prevention (ATP), que coteja las credenciales con las ya filtradas",
      "AWS WAF Bot Control, que categoriza y bloquea los bots conocidos por su firma",
      "Una rate-based rule por IP, que corta al superarse el umbral de peticiones",
      "Account Creation Fraud Prevention (ACFP), pensado para el endpoint de alta de cuenta",
    ],
    correct: 0,
    explain: "ATP protege el endpoint de <strong>inicio de sesión</strong>: inspecciona el par email/contraseña enviado y lo compara contra una base de credenciales comprometidas que AWS actualiza de forma continua, y además vigila las tasas de éxito y fallo por IP y por sesión de cliente. ACFP es el componente hermano, pero para páginas de <em>registro</em>, no de login. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-atp.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "WAF Fraud Control – ACFP",
    q: "Una aplicación con registro público sufre oleadas de creación de cuentas falsas generadas por bots, usadas después para fraude de promociones (abuso de cupones de bienvenida). ¿Qué protección de AWS WAF está diseñada para este escenario?",
    options: [
      "Account Takeover Prevention (ATP), que protege el endpoint de inicio de sesión",
      "Account Creation Fraud Prevention (ACFP), que vigila el endpoint de registro",
      "CloudFront Geo Restriction, bloqueando los países desde los que llega el fraude",
      "Shield Advanced, cuya mitigación de capa 3/4 descarta las oleadas automatizadas",
    ],
    correct: 1,
    explain: "ACFP vigila de forma continua las peticiones al endpoint de alta de cuenta: valida el dominio del correo, contrasta las credenciales contra la base de credenciales filtradas, revisa teléfono y dirección, y aplica análisis de comportamiento para frenar el registro masivo automatizado. ATP cubre el login; Shield mitiga DDoS de red, no fraude de aplicación. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-acfp.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "WAF CAPTCHA vs Challenge",
    q: "Quieres frenar un bot sencillo que hace scraping del catálogo de productos sin degradar la experiencia de los usuarios reales (no quieres pedirles que resuelvan un puzle visible). ¿Qué acción de regla de AWS WAF es la más adecuada?",
    options: [
      "CAPTCHA, que exige al usuario resolver un puzle visible antes de dejarle continuar",
      "Block sobre todas las IP sospechosas, sin ninguna verificación previa del cliente",
      "Challenge, que verifica en segundo plano que el cliente es un navegador real",
      "Count, que etiqueta la petición y la deja pasar sin aplicar ninguna otra acción",
    ],
    correct: 2,
    explain: "Challenge ejecuta una verificación <strong>silenciosa</strong> en el cliente (JavaScript más un token en la cookie <code>aws-waf-token</code>) para comprobar que hay un navegador real detrás, sin pedirle nada al usuario: ideal contra bots simples y sin fricción. CAPTCHA exige resolver un puzle visible y se reserva para amenazas más persistentes; Count solo cuenta. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "WAF Bot Control",
    q: "Necesitas distinguir entre bots 'buenos' conocidos (como los crawlers de motores de búsqueda legítimos) y bots maliciosos/no categorizados en tu aplicación web, incluyendo la capacidad de definir protecciones contra bots dirigidos específicamente a tu negocio (ej. bots de scalping de inventario). ¿Qué managed rule group de AWS WAF encaja?",
    options: [
      "AWS Managed Rules Core rule set (CRS), centrado en los riesgos del OWASP Top 10",
      "Amazon Inspector, que identifica los bots a partir de las CVE de la aplicación",
      "El Anti-DDoS managed rule group, pensado para las oleadas volumétricas de capa 7",
      "AWS WAF Bot Control, cuyo nivel Targeted añade fingerprinting y heurística",
    ],
    correct: 3,
    explain: "Bot Control clasifica el tráfico automatizado y verifica a los bots que se identifican (buscadores, monitores). Su nivel <strong>Common</strong> cubre los bots que se declaran; el nivel <strong>Targeted</strong> añade interrogación del navegador, fingerprinting y heurística de comportamiento para los bots sofisticados hechos a medida contra tu negocio, como el scalping de inventario. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-bot-control.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Shield Advanced + Anti-DDoS rule group",
    q: "Tu organización usa Shield Advanced sobre una distribución de CloudFront con AWS WAF. Tras la adopción del nuevo AWS WAF Anti-DDoS managed rule group como protección de capa de aplicación por defecto de Shield Advanced, ¿qué cambia respecto a la facturación durante un ataque DDoS de capa 7 activamente mitigado?",
    options: [
      "Las peticiones bloqueadas durante la mitigación activa no cuentan en la factura",
      "Se factura el doble mientras dura la mitigación, por el consumo extra de recursos",
      "No cambia nada: el tráfico de ataque se factura igual que el tráfico legítimo",
      "Shield Advanced deja de facturar por completo mientras el ataque siga activo",
    ],
    correct: 0,
    explain: "El Anti-DDoS managed rule group sustituye a la protección de capa 7 anterior con menos WCU y, durante una mitigación DDoS activa, las peticiones bloqueadas quedan <strong>excluidas del recuento mensual</strong> de solicitudes de WAF, del propio rule group y de Shield Advanced. Así el volumen del ataque no se traduce en un coste desproporcionado para el cliente. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-anti-ddos.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Network Firewall TLS Inspection",
    q: "Necesitas que AWS Network Firewall inspeccione el contenido de las conexiones HTTPS salientes de tu VPC (no solo el SNI) para aplicar reglas de firma tipo IDS/IPS sobre el tráfico descifrado. ¿Qué debes configurar?",
    options: [
      "Nada: Network Firewall inspecciona el payload cifrado de forma nativa y sin configurar",
      "Una TLS inspection configuration, que descifra, inspecciona y vuelve a cifrar",
      "Solo reglas de dominio (FQDN), que leen el SNI sin necesidad de descifrar nada",
      "Sustituirlo por AWS WAF, que sí inspecciona el contenido cifrado de extremo a extremo",
    ],
    correct: 1,
    explain: "Un firewall con estado solo ve metadatos del handshake (como el SNI) mientras el payload viaja cifrado. La <strong>TLS inspection configuration</strong> actúa de proxy: descifra con certificados de ACM, aplica las reglas de firma y de dominio sobre el tráfico en claro, y vuelve a cifrar hacia el destino. Sirve tanto para inspección de entrada como de salida. <a href=\"https://docs.aws.amazon.com/network-firewall/latest/developerguide/tls-inspection-configurations.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Inspector Code Security",
    q: "Tu equipo de desarrollo quiere detectar vulnerabilidades de seguridad (y configuraciones erróneas de Infrastructure as Code) directamente en los pull requests de GitHub, antes de fusionar el código, sin depender solo de un escaneo posterior en producción. ¿Qué capacidad de Amazon Inspector cubre esto?",
    options: [
      "Inspector Network Reachability, que analiza las rutas de red hacia el recurso",
      "Ninguna: Inspector solo escanea imágenes ya publicadas en ECR, nunca código fuente",
      "Amazon Inspector Code Security, integrado con GitHub y GitLab sobre cada PR",
      "Amazon CodeGuru Reviewer, que sustituyó a Inspector para el análisis de código",
    ],
    correct: 2,
    explain: "Inspector Code Security amplía el alcance del servicio más allá de EC2, ECR y Lambda hasta el <strong>repositorio</strong>: se conecta a GitHub o GitLab, analiza vulnerabilidades del código, dependencias y plantillas de IaC, y devuelve los hallazgos en el propio pull request o en el pipeline de CI/CD, antes de que la vulnerabilidad llegue a producción. <a href=\"https://docs.aws.amazon.com/inspector/latest/user/code-security-assessments-connect-github.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Inspector organization-wide management",
    q: "Como administrador delegado de seguridad en AWS Organizations, quieres habilitar y configurar de forma centralizada qué tipos de escaneo de Amazon Inspector (por ejemplo, Lambda Code Scanning o Code Security) se aplican automáticamente en todas las cuentas de ciertas unidades organizativas (OUs), sin tener que configurarlo cuenta por cuenta. ¿Qué mecanismo usas?",
    options: [
      "Una SCP que deniegue las llamadas a la API capaces de desactivar Inspector",
      "Ninguno: hay que activarlo cuenta por cuenta, Inspector no admite gestión central",
      "Un conformance pack de AWS Config desplegado sobre cada unidad organizativa",
      "Una política de Amazon Inspector de AWS Organizations aplicada sobre las OU",
    ],
    correct: 3,
    explain: "Las <strong>políticas de Amazon Inspector</strong> son un tipo de política de gestión de AWS Organizations: declaran qué escaneos (EC2, ECR, Lambda estándar y de código, Code Security) quedan activados en la raíz, en OU concretas o en cuentas sueltas, y las cuentas nuevas heredan la política al unirse. Una SCP solo puede denegar acciones, nunca activar una configuración. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_inspector.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "GuardDuty genera múltiples findings de baja severidad aparentemente inconexos sobre una instancia EC2 y una tarea ECS relacionada (acceso inusual a credenciales, luego una conexión de red sospechosa poco después). ¿Qué capacidad de GuardDuty está diseñada para correlacionar esta secuencia y elevarla a un único hallazgo crítico de 'ataque en curso'?",
    options: [
      "Extended Threat Detection, que correlaciona señales y genera un attack sequence",
      "Malware Protection for EC2, que escanea los volúmenes EBS de la instancia afectada",
      "Amazon Detective, que sustituye a GuardDuty en las cuentas con Security Hub activo",
      "Las reglas de AWS Config, que agregan los cambios de configuración de cada recurso",
    ],
    correct: 0,
    explain: "Extended Threat Detection correlaciona señales —actividad de API y findings previos— repartidas en el tiempo y entre recursos (EC2, ECS, EKS, S3, credenciales de IAM) y emite un finding de tipo <strong>attack sequence</strong>, siempre de severidad crítica, cuando el conjunto describe un ataque multietapa en curso. Va activado por defecto y sin coste adicional. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-extended-threat-detection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "GuardDuty detecta actividad sospechosa en una instancia EC2 (por ejemplo, comunicación con un dominio de mando y control conocido). ¿Qué hace GuardDuty Malware Protection for EC2 automáticamente a partir de ahí, y qué impacto tiene sobre la instancia en ejecución?",
    options: [
      "Termina la instancia de inmediato para contener la amenaza antes de analizarla",
      "Escanea sin agente los volúmenes EBS desde un snapshot, sin afectar al servicio",
      "Exige instalar antes el agente de Amazon Inspector en la instancia comprometida",
      "Solo puede escanear la instancia después de detenerla, en estado <code>stopped</code>",
    ],
    correct: 1,
    explain: "El <em>GuardDuty-initiated malware scan</em> arranca solo cuando un finding señala a la instancia: toma un snapshot de los volúmenes EBS adjuntos y lo analiza en busca de malware conocido de forma <strong>agentless</strong>, sin instalar nada en el sistema operativo y sin impacto en el rendimiento ni en la disponibilidad. GuardDuty detecta y avisa; contener es una decisión tuya. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "VPC Route Server",
    q: "Tienes appliances de red virtuales de terceros (firewalls NVA) desplegados en tu VPC que necesitan anunciar dinámicamente rutas hacia las tablas de rutas de las subnets, sin mantener scripts personalizados ni una red overlay para sincronizar los cambios. ¿Qué servicio de AWS resuelve esto de forma nativa?",
    options: [
      "AWS Transit Gateway, que propaga por BGP las rutas hacia las subredes de la VPC",
      "AWS Network Firewall, que reescribe las tablas de rutas al desplegar sus endpoints",
      "Amazon VPC Route Server, que recibe rutas por BGP y actualiza las tablas",
      "Route 53 Resolver, que resuelve por DNS el siguiente salto de cada appliance",
    ],
    correct: 2,
    explain: "VPC Route Server lleva el enrutamiento dinámico <strong>dentro</strong> de la VPC: los NVA establecen sesiones BGP contra los endpoints del route server y las rutas anunciadas se propagan automáticamente a las tablas de rutas de las subredes e Internet Gateway asociadas. Antes esto obligaba a automatizarlo con Lambda o a montar una overlay. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/route-server-how-it-works.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Verified Access non-HTTP(S)",
    q: "Además de aplicaciones web internas, tu equipo necesita dar acceso Zero Trust (evaluando identidad y postura del dispositivo) a bases de datos y a sesiones SSH/RDP hacia instancias EC2, sin desplegar una VPN de red completa. ¿Qué capacidad reciente de AWS Verified Access permite esto?",
    options: [
      "Ninguna: Verified Access solo admite HTTP(S), y para SSH o RDP hace falta una VPN",
      "Solo es viable sobre un Direct Connect dedicado que tenga MACsec habilitado",
      "Migrar esas cargas a AWS Client VPN, el único servicio con soporte de SSH y RDP",
      "El soporte de Verified Access para protocolos TCP no HTTP(S), como SSH y RDP",
    ],
    correct: 3,
    explain: "Verified Access admite endpoints TCP genéricos además de los HTTP(S): con el <em>Connectivity Client</em>, el usuario alcanza bases de datos, sesiones SSH o RDP aplicando la misma política de identidad y postura del dispositivo, sin abrir un túnel de red completo ni distribuir claves. Extiende el modelo Zero Trust a la administración de EC2. <a href=\"https://docs.aws.amazon.com/verified-access/latest/ug/verified-access-endpoints.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Group Referencing (Transit Gateway)",
    q: "Tienes dos VPCs conectadas a través de AWS Transit Gateway (no peering directo) y quieres permitir tráfico entre instancias de una VPC y otra referenciando directamente el Security Group de origen en la regla de entrada del Security Group de destino (en vez de usar rangos CIDR). ¿Es esto posible?",
    options: [
      "Sí: se pueden referenciar security groups entre VPC unidas al mismo transit gateway",
      "No: referenciar security groups entre VPC solo funciona con VPC peering directo",
      "Solo si ambas VPC pertenecen a la misma cuenta de AWS y a la misma zona de disponibilidad",
      "Solo para tráfico UDP; el tráfico TCP sigue exigiendo rangos CIDR estáticos",
    ],
    correct: 0,
    explain: "Con el <em>security group referencing support</em> activado en el transit gateway o en el attachment, una regla de <strong>entrada</strong> puede citar un security group de otra VPC adjunta al mismo TGW, en lugar de rangos CIDR frágiles de mantener. Ojo a los límites: solo reglas de entrada, y no funciona a través de peering entre transit gateways. <a href=\"https://docs.aws.amazon.com/vpc/latest/tgw/tgw-sg-updates.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "ECR Image Signing",
    q: "Quieres garantizar que solo se puedan desplegar en tu clúster imágenes de contenedor que efectivamente provienen de tu pipeline de CI/CD autorizado, protegiendo la cadena de suministro de software frente a imágenes manipuladas o no verificadas. ¿Qué capacidad de Amazon ECR ayuda a esto?",
    options: [
      "La pull-through cache de ECR, que replica y verifica las imágenes de registros públicos",
      "El managed image signing de ECR, que firma con AWS Signer en cada push",
      "El enhanced scanning de ECR, cuyo informe de CVE acredita también la procedencia",
      "Ninguna: la firma de imágenes es exclusiva de Docker Hub y del proyecto Notary",
    ],
    correct: 1,
    explain: "El <strong>managed image signing</strong> de ECR genera automáticamente una firma con AWS Signer al hacer push, y se gobierna como configuración del registro sin instalar herramientas en el cliente. Verificando esa firma en el despliegue evitas ejecutar imágenes manipuladas. El escaneo de vulnerabilidades es un control distinto: dice si hay CVE, no de dónde viene la imagen. <a href=\"https://docs.aws.amazon.com/AmazonECR/latest/userguide/managed-signing.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Declarative Policies (IMDSv2)",
    q: "Quieres garantizar, a nivel de toda la organización de AWS Organizations, que NINGUNA instancia EC2 nueva pueda desplegarse con IMDSv1 habilitado (mitigando el vector SSRF), de forma que la configuración se mantenga aplicada incluso si se añaden cuentas nuevas o AWS introduce nuevas APIs de EC2. ¿Qué mecanismo usas, a diferencia de una SCP tradicional?",
    options: [
      "Una SCP que deniegue la acción RunInstances cuando no se exige IMDSv2 en la petición",
      "Una regla de AWS Config con remediación que corrige la instancia una vez ya creada",
      "Una declarative policy de EC2 en AWS Organizations, aplicada en el plano de control",
      "Etiquetar las instancias como IMDSv2-only y auditar esas etiquetas cada semana",
    ],
    correct: 2,
    explain: "Las <strong>declarative policies</strong> son un tipo de política de Organizations distinto de las SCP: en vez de denegar acciones concretas de la API, declaran el <em>estado deseado</em> de un servicio —para EC2, atributos como <code>http_tokens</code> y <code>http_tokens_enforced</code>— y el propio plano de control del servicio lo mantiene, también cuando aparecen APIs o cuentas nuevas. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "VPC Lattice Auth Policies",
    q: "Estás diseñando una malla de microservicios que cruza varias VPCs y cuentas de AWS, y quieres controlar qué servicio concreto puede invocar qué otro servicio y con qué método HTTP, usando identidad (SigV4/IAM) en vez de solo direcciones IP — de forma independiente a los Security Groups que gestiona el equipo de red. ¿Qué mecanismo de VPC Lattice aplica?",
    options: [
      "Las network ACL de cada VPC, que ya filtran por IP de origen y puerto de destino",
      "Una NAT Gateway compartida que centraliza y autoriza las llamadas entre cuentas",
      "AWS Verified Access, que autoriza las llamadas entre los servicios de la malla",
      "Las auth policies de VPC Lattice, políticas IAM sobre la red o el servicio",
    ],
    correct: 3,
    explain: "Una auth policy es un documento con sintaxis IAM que se adjunta a la <strong>service network</strong> (autorización gruesa, del equipo de red) o a un <strong>servicio</strong> concreto (autorización fina, del equipo dueño del servicio), y decide qué principal puede invocar qué acción y ruta. Para que la llamada pase, la auth policy y la política de identidad deben permitirla las dos. <a href=\"https://docs.aws.amazon.com/vpc-lattice/latest/ug/auth-policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Route 53 Resolver DNS Firewall Advanced",
    q: "Sospechas que un host comprometido dentro de tu VPC está usando un Domain Generation Algorithm (DGA) para generar nombres de dominio pseudoaleatorios y comunicarse con infraestructura de mando y control (C2), evadiendo las listas de bloqueo de dominios estáticas. ¿Qué servicio de AWS detecta este patrón específico en tiempo real?",
    options: [
      "DNS Firewall Advanced, que detecta patrones de DGA y de tunneling sobre DNS",
      "Route 53 Resolver DNS Firewall estándar, basado en listas de dominios conocidos",
      "AWS Network Firewall con reglas de dominio (FQDN) sobre el tráfico de salida",
      "Amazon GuardDuty, que bloquea las consultas DNS hacia dominios de C2 conocidos",
    ],
    correct: 0,
    explain: "DNS Firewall Advanced no depende de listas: inspecciona firmas de amenaza en la propia consulta —longitud y forma del nombre, frecuencia y tamaño de las peticiones y respuestas— para identificar <strong>DGA</strong> y <strong>DNS tunneling</strong>, que existen precisamente para esquivar los bloqueos por lista. GuardDuty genera findings sobre actividad DNS sospechosa, pero quien bloquea es DNS Firewall. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/firewall-advanced.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "PrivateLink endpoint policies",
    q: "Tu equipo ha creado un interface VPC endpoint hacia Amazon S3 para que las instancias en una subnet privada puedan acceder a S3 sin salir a Internet. Quieres asegurarte de que, a través de ESE endpoint concreto, solo se pueda acceder a un bucket específico, independientemente de los permisos IAM que tenga cada rol. ¿Qué mecanismo usas?",
    options: [
      "Modificar el security group del endpoint para que filtre por el nombre del bucket destino",
      "Una endpoint policy, política de recursos que acota el acceso a través del endpoint",
      "Una network ACL en la subred del endpoint que restrinja los prefijos de red de S3",
      "Ninguno: cualquier endpoint concede acceso completo al servicio que representa",
    ],
    correct: 1,
    explain: "El security group de un interface endpoint solo controla <em>quién llega al ENI</em> por IP y puerto: no entiende de buckets. La <strong>endpoint policy</strong> es una política de recursos en sintaxis IAM (con elemento <code>Principal</code>) adjunta al endpoint que limita qué principales, acciones y recursos son accesibles por esa vía. No sustituye a las políticas de identidad ni a la bucket policy: se suma. <a href=\"https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-access.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "Estás diseñando los controles de red de una VPC. ¿Qué DOS afirmaciones sobre security groups y network ACLs son correctas?",
    options: [
      "Los security groups son stateful: el retorno se permite aunque no haya regla de salida",
      "Los security groups admiten reglas Deny explícitas para bloquear una IP de origen concreta",
      "Las network ACL son stateless y admiten reglas Deny evaluadas por número de regla",
      "Las network ACL se aplican a la interfaz de red de la instancia, y no a la subred",
    ],
    correct: [0, 2],
    explain: "Es la comparación más preguntada del dominio. Los <strong>security groups son stateful</strong> (solo permiten, y la vuelta es automática) y se aplican a la ENI; las <strong>NACL son stateless</strong> (permiten y deniegan, se evalúan en orden numérico y hay que abrir la vuelta explícitamente, típicamente los puertos efímeros) y se aplican a la subred. Por eso, para bloquear una IP concreta la herramienta es la NACL. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Protección de una aplicación web pública",
    q: "Una aplicación web tras CloudFront sufre inyección SQL y un ataque volumétrico de capa 3/4. ¿Qué DOS servicios abordan directamente estas amenazas?",
    options: [
      "Amazon Inspector, que bloquea en tiempo real las peticiones con payload malicioso",
      "AWS WAF con los managed rule groups adecuados, para frenar la inyección SQL",
      "AWS Config, que impide que las peticiones sospechosas lleguen hasta el origen",
      "AWS Shield, que mitiga el ataque volumétrico de capa 3/4 contra la distribución",
    ],
    correct: [1, 3],
    explain: "<strong>WAF</strong> inspecciona en capa 7 y frena SQLi o XSS con reglas gestionadas; <strong>Shield</strong> mitiga el DDoS volumétrico de capa 3/4 (Standard viene incluido, Advanced añade mitigación y respuesta gestionada). Inspector evalúa <em>vulnerabilidades</em> de instancias, contenedores y Lambda, y Config evalúa la <em>configuración</em> de los recursos: ninguno está en el camino de la petición. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Acceso administrativo sin SSH expuesto",
    q: "Seguridad prohíbe abrir el puerto 22 a internet y quiere eliminar los bastion hosts, pero los operadores necesitan acceso de shell a instancias EC2 en subredes privadas. ¿Qué DOS elementos permiten esto?",
    options: [
      "AWS Systems Manager Session Manager, que abre la sesión sin puertos de entrada",
      "Una regla de security group que permita el puerto 22 solo desde el rango corporativo",
      "Una Elastic IP en cada instancia para que Systems Manager pueda alcanzarla",
      "El agente SSM en la instancia y un instance profile con permisos de Systems Manager",
    ],
    correct: [0, 3],
    explain: "<strong>Session Manager</strong> trabaja con una conexión <em>saliente</em> del agente hacia el servicio, así que no requiere puertos de entrada, ni IP pública, ni bastion, y además registra la sesión en CloudTrail, S3 o CloudWatch Logs. Necesita las dos piezas: <strong>agente</strong> y <strong>permisos vía instance profile</strong>. Abrir el 22 a un rango corporativo es justo lo que se quiere eliminar. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Imágenes base endurecidas",
    q: "La empresa quiere garantizar que todas las instancias EC2 arrancan desde imágenes endurecidas y parcheadas. ¿Qué DOS servicios encajan en esa cadena?",
    options: [
      "AWS Shield Advanced, para comprobar que la AMI no contiene malware antes de usarla",
      "EC2 Image Builder, para construir y versionar AMIs endurecidas de forma repetible",
      "Amazon Inspector, para detectar CVE conocidos en las imágenes y en las instancias",
      "Amazon Macie, para escanear el sistema operativo de la AMI en busca de CVE conocidos",
    ],
    correct: [1, 2],
    explain: "<strong>Image Builder</strong> automatiza la construcción, el endurecimiento y el versionado de las AMIs, e <strong>Inspector</strong> las evalúa de forma continua contra CVE conocidos. Shield es exclusivamente anti-DDoS, y Macie descubre y clasifica <strong>datos sensibles en S3</strong>: no analiza sistemas operativos. Confundir Macie con un escáner de vulnerabilidades es un distractor recurrente. <a href=\"https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["infrastructure-security"] = QUIZ_DATA;
