const QUIZ_DATA = [
  {
    tag: "Policy evaluation",
    q: "A user has an identity policy that allows s3:GetObject on a bucket, but the bucket has a bucket policy with an explicit Deny for that same user. What happens?",
    options: [
      "Access is allowed because the identity policy takes priority",
      "Access is denied: an explicit Deny in any applicable policy always wins",
      "AWS only evaluates the identity policy if the resource belongs to the same account",
      "The outcome depends on which policy was created most recently",
    ],
    correct: 1,
    explain: "IAM's evaluation order is: explicit Deny &gt; explicit Allow &gt; default Deny. An explicit Deny in ANY applicable policy (identity, resource, SCP, RCP, boundary, session policy) overrides any Allow, no matter where it lives.",
  },
  {
    tag: "SCP vs RCP",
    q: "What is the key difference between a Service Control Policy (SCP) and a Resource Control Policy (RCP) in AWS Organizations?",
    options: [
      "There's no difference, they're synonyms for the same mechanism",
      "SCPs only apply to the management account",
      "SCPs limit what the account's identities can do; RCPs limit who can access the resources, including external/anonymous identities",
      "RCPs completely replace SCPs as of 2023",
    ],
    correct: 2,
    explain: "SCPs are guardrails that cap the maximum permission available to principals WITHIN the organization. RCPs (newer) cap access to the RESOURCES themselves, including external principals, closing gaps SCPs don't cover because SCPs don't apply to identities outside the organization.",
  },
  {
    tag: "Permission boundaries",
    q: "A developer has a permission boundary that only allows actions on S3 and DynamoDB. Their identity-based policy grants AdministratorAccess. What can they actually do?",
    options: [
      "Everything, because AdministratorAccess always wins",
      "Only S3 and DynamoDB actions: the permission boundary acts as the maximum ceiling, the intersection with the identity policy",
      "Nothing, because the boundary and the policy conflict and everything is denied",
      "It depends on the order in which the policies were attached",
    ],
    correct: 1,
    explain: "The permission boundary does NOT grant permissions on its own: it defines the maximum set of permissions an identity-based policy can grant. The effective permission is the INTERSECTION between the identity policy and the boundary.",
  },
  {
    tag: "STS",
    q: "A mobile app authenticates users against Google (an OIDC provider) and needs temporary AWS credentials to access an S3 bucket directly from the phone. Which STS API is appropriate?",
    options: [
      "sts:GetSessionToken",
      "sts:AssumeRoleWithWebIdentity (or better, via Amazon Cognito Identity Pools)",
      "sts:AssumeRoleWithSAML",
      "sts:GetFederationToken",
    ],
    correct: 1,
    explain: "AssumeRoleWithWebIdentity exchanges an OIDC token (Google, Facebook, Amazon, or any OIDC-compatible IdP) for temporary credentials. In production, AWS recommends using Cognito Identity Pools on top, which manages the exchange more securely without exposing secrets in the app.",
  },
  {
    tag: "SAML federation",
    q: "A company uses on-premises Active Directory Federation Services (ADFS) and wants to give its employees access to the AWS console without creating IAM users. Which mechanism is the most appropriate?",
    options: [
      "IAM Roles Anywhere",
      "AssumeRoleWithSAML combined with a SAML 2.0 IdP configured in IAM",
      "Individual access keys managed by AD",
      "AWS IAM Identity Center in standalone mode with no external IdP",
    ],
    correct: 1,
    explain: "AssumeRoleWithSAML lets you federate identities from a SAML 2.0 IdP (ADFS, Okta, Azure AD/Entra ID) directly against an IAM Role, without needing individual IAM users. IAM Identity Center is also valid and is the modern option AWS recommends for multi-account setups, but it still needs to connect that same SAML IdP as its identity source.",
  },
  {
    tag: "IAM Identity Center",
    q: "What is the main difference between a traditional cross-account IAM Role and an IAM Identity Center Permission Set?",
    options: [
      "There's no technical difference, IAM Identity Center is just a visual interface over roles",
      "Permission Sets only work with root users",
      "A Permission Set is defined once and IAM Identity Center automatically provisions the corresponding IAM Roles in each assigned member account",
      "Permission Sets don't support AWS managed policies, only inline",
    ],
    correct: 2,
    explain: "IAM Identity Center (the successor to AWS SSO) centralizes management: you define a Permission Set once, and the service automatically provisions/syncs the necessary IAM Roles in each account of the assigned organization, avoiding manual role management account by account.",
  },
  {
    tag: "IAM Access Analyzer",
    q: "What type of finding does IAM Access Analyzer generate when it detects that an IAM role hasn't been used in the last 90 days?",
    options: [
      "External access finding",
      "Unused access finding (part of the 'unused access' analysis, available since 2023)",
      "Policy validation finding",
      "Access Analyzer doesn't analyze usage, only static policies",
    ],
    correct: 1,
    explain: "Access Analyzer has three capabilities: (1) External access findings — detects resources accessible from outside your zone of trust; (2) Unused access findings — identifies roles, permissions, and access keys with no recent use; (3) Policy validation — validates syntax and best practices in policies as you write them.",
  },
  {
    tag: "ABAC",
    q: "In an attribute-based access control (ABAC) strategy with IAM, which condition would typically be used in a policy to allow a user to only tag/access resources that match their own department?",
    options: [
      "\"Condition\": {\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/department}\"}}",
      "\"Condition\": {\"IpAddress\": {\"aws:SourceIp\": \"10.0.0.0/16\"}}",
      "\"Condition\": {\"Bool\": {\"aws:MultiFactorAuthPresent\": \"true\"}}",
      "\"Condition\": {\"DateLessThan\": {\"aws:CurrentTime\": \"2026-01-01T00:00:00Z\"}}",

    ],
    correct: 0,
    explain: "ABAC compares tags on the principal with tags on the resource using policy variables like aws:PrincipalTag/key and aws:ResourceTag/key, enabling access rules that scale without rewriting policies for every new resource.",
  },
  {
    tag: "Confused deputy",
    q: "An AWS service (e.g. CloudTrail) assumes a role in your account on behalf of another AWS customer and, by mistake, accesses data in your account that it shouldn't. Which policy condition prevents this 'confused deputy problem'?",
    options: [
      "aws:MultiFactorAuthPresent",
      "aws:SourceIp",
      "aws:SourceArn and/or aws:SourceAccount in the role's trust policy",
      "aws:RequestedRegion",
    ],
    correct: 2,
    explain: "To prevent an AWS service from being 'tricked' into acting on behalf of an unauthorized third party, you add a condition to the trust policy with aws:SourceArn (or aws:SourceAccount) restricting which specific resource/account can invoke the AssumeRole via that service.",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "A company has on-premises servers (outside AWS) that need temporary AWS credentials without using long-lived access keys. Which service is designed exactly for this case?",
    options: [
      "AWS Systems Manager Hybrid Activations only",
      "IAM Roles Anywhere: uses X.509 certificates issued by a private CA and exchanges them for temporary credentials via STS",
      "IAM Identity Center with an on-premises connector",
      "Cognito Identity Pools",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere lets workloads outside AWS (on-prem servers, other clouds) obtain temporary IAM credentials by presenting an X.509 certificate signed by a trusted CA registered with IAM, eliminating the need for static access keys outside AWS.",
  },
  {
    tag: "Root user",
    q: "AWS introduced 'Centralized Root Access Management' in Organizations. What does this capability allow you to do?",
    options: [
      "Completely eliminate the need to have a root user in every account",
      "Centrally manage member accounts' root credentials and apply privileged root actions without needing to recover passwords account by account",
      "Turn root into an IAM role that any user can assume",
      "Replace MFA in the management account",
    ],
    correct: 1,
    explain: "This Organizations capability (launched in 2023-2024) lets you centrally manage and restrict member accounts' root credentials, and invoke a scoped set of privileged root tasks without having to go through the password-recovery process individually in each account.",
  },
  {
    tag: "MFA",
    q: "Which condition key is used in an IAM policy to require that an API call was made with an MFA-authenticated session?",
    options: [
      "aws:MultiFactorAuthPresent: true",
      "aws:MFA-Required: true",
      "iam:MFAEnabled: true",
      "sts:MfaAuthenticated: true",
    ],
    correct: 0,
    explain: "The standard condition is aws:MultiFactorAuthPresent. A well-tested best practice is combining it with aws:MultiFactorAuthAge to also cap the maximum age of the MFA session.",
  },
  {
    tag: "Resource-based policies",
    q: "Which of these statements about resource-based policies is correct?",
    options: [
      "Only IAM Roles can have resource-based policies",
      "They allow granting access to a principal from ANOTHER AWS account without that principal needing to assume a role in your account",
      "They can never be combined with conditions",
      "They always replace identity-based policies",
    ],
    correct: 1,
    explain: "Resources like S3 buckets, KMS keys, SQS queues, SNS topics, or Lambda functions support resource-based policies, which can directly specify an external Principal (from another account) without that principal needing to assume a role — cross-account access is granted directly on the resource.",
  },
  {
    tag: "Credential report vs Access Advisor",
    q: "What is the difference between the IAM Credential Report and IAM Access Advisor?",
    options: [
      "They're the same report with different names",
      "The Credential Report lists the credential status (passwords, access keys, MFA) of every user; Access Advisor shows which services/actions a principal has actually used and when it last used them",
      "Access Advisor only works at the root account level",
      "The Credential Report requires GuardDuty to be enabled",
    ],
    correct: 1,
    explain: "The Credential Report (generated at the account level, CSV) audits the credential status of every IAM user. Access Advisor (the 'Access Advisor' tab of a user/role) shows the history of accessed services — key for applying least privilege by removing unused permissions.",
  },
  {
    tag: "Cross-account trust policy",
    q: "Which element is mandatory in the trust policy (assume role policy document) of an IAM Role to allow an external account to assume it?",
    options: [
      "A Principal referencing the ARN or ID of the external account, with Action sts:AssumeRole",
      "A bucket policy linked to the role",
      "A specific SCP in the external account",
      "Nothing else: by default any account can assume any role",
    ],
    correct: 0,
    explain: "The role's trust policy must include a Principal with the ARN of the authorized external account/role and Action: sts:AssumeRole. In addition, the assuming account needs its own identity policy allowing it to call sts:AssumeRole on that ARN — BOTH sides (trust + source permission) are required.",
  },
  {
    tag: "Data perimeter",
    q: "In AWS's 'data perimeter' concept, what combination of controls is typically used to ensure data NEVER leaves the organization, even with stolen valid credentials?",
    options: [
      "Only KMS encryption",
      "Only restrictive Security Groups",
      "Organization-wide SCPs/RCPs + aws:PrincipalOrgID / aws:ResourceOrgID conditions + VPC endpoint policies",
      "Only rotating access keys every 90 days",
    ],
    correct: 2,
    explain: "The data perimeter combines 3 types of perimeters: identity (who can access? — SCPs/RCPs with aws:PrincipalOrgID), resource (which resources are trusted? — aws:ResourceOrgID) and network (from where? — VPC endpoint policies + aws:SourceVpce), so that not even valid, compromised credentials can exfiltrate data outside the perimeter.",
  },
  {
    tag: "Session policies",
    q: "When you call sts:AssumeRole passing an additional --policy parameter (session policy), how does this affect the effective permissions of the resulting session?",
    options: [
      "The session policy completely replaces the role's identity policy",
      "The session policy expands the role's permissions beyond what it already had",
      "The session policy acts as an additional filter: the effective permissions are the intersection between the role's permissions and the session policy",
      "Session policies only apply to users, not roles",
    ],
    correct: 2,
    explain: "Just like a permission boundary, a session policy NEVER expands permissions — it can only narrow (intersect) the permissions the assumed role already has. It's useful for issuing more restricted temporary credentials from a broad role.",
  },
  {
    tag: "Declarative policies",
    q: "AWS Organizations introduced 'Declarative Policies'. How do they differ from SCPs?",
    options: [
      "They're identical to SCPs, only the name changes",
      "Declarative Policies centrally set the desired configuration of certain service attributes (e.g. blocking IMDSv1, forcing public access block on EC2/VPC) across the entire organization, instead of just allowing/denying API actions",
      "Declarative Policies only work in the management account",
      "They completely replace Config Rules",
    ],
    correct: 1,
    explain: "Unlike SCPs (which deny/allow API calls), Declarative Policies (2024+) establish and maintain a desired configuration state at the organization level for specific attributes of certain services (e.g. requiring IMDSv2, blocking public access to snapshots), guaranteeing that no account can drift from that configuration.",
  },
  {
    tag: "Policy evaluation with VPC endpoints",
    q: "Which condition key restricts access to an S3 bucket exclusively to requests that pass through a specific VPC endpoint?",
    options: [
      "aws:SourceIp",
      "aws:SourceVpce",
      "aws:VpcSourceIp",
      "s3:VpcEndpointId",
    ],
    correct: 1,
    explain: "aws:SourceVpce in a bucket policy (or any compatible resource policy) restricts access to requests traveling through a specific VPC endpoint, a key 'network perimeter' control to prevent data exfiltration outside the VPC.",
  },
  {
    tag: "Inline vs managed policies",
    q: "What is the main disadvantage of using inline policies instead of managed policies?",
    options: [
      "Inline policies don't support conditions",
      "Inline policies can't be reused across multiple users/roles/groups and are harder to audit and version centrally",
      "Inline policies have a smaller size limit than managed policies",
      "Inline policies can't deny, only allow",
    ],
    correct: 1,
    explain: "An inline policy lives embedded in a single identity (user, group, or role) and cannot be attached to other identities or versioned independently, making it harder to reuse, centrally audit, and manage at scale compared to a customer managed policy.",
  },
  {
    tag: "Amazon Cognito",
    q: "Your web application has its own end-user sign-up/login system, and after authenticating, users need to upload files directly to an S3 bucket using temporary AWS credentials. Which combination of Cognito components would you use?",
    options: [
      "Just a Cognito User Pool, which already issues AWS credentials directly",
      "A Cognito User Pool for login (issues JWTs) + a Cognito Identity Pool that exchanges that JWT for temporary AWS credentials",
      "IAM Identity Center, because Cognito doesn't support users external to the organization",
      "AssumeRoleWithSAML pointed directly at the User Pool",
    ],
    correct: 1,
    explain: "The User Pool manages identity and login (returns JSON Web Tokens), but does NOT grant AWS credentials by itself. The Identity Pool is what exchanges that already-authenticated token for temporary AWS credentials (via STS internally), enabling direct, secure access to services like S3.",
  },
  {
    tag: "S3 presigned URLs",
    q: "What happens to an S3 presigned URL if, before it expires, the s3:GetObject permission of the user who generated it is revoked?",
    options: [
      "The URL keeps working until its lifetime expires, because the credentials were 'frozen' at signing time",
      "The URL stops working immediately: each use is still evaluated against the signer's current IAM permissions",
      "The URL automatically becomes invalid in under 1 minute",
      "It's not possible to revoke permissions for a presigned URL once generated",
    ],
    correct: 1,
    explain: "A presigned URL is not an independent credential: it's a signature that delegates, for a time window, the signer's current permission. If that permission is revoked (the policy is removed, the role is disabled, etc.) before the URL expires, access is also denied, because IAM is still evaluated on every request.",
  },
  {
    tag: "AWS Directory Service",
    q: "A company has an on-premises Active Directory it wants to keep using as its identity source, without migrating data or replicating the directory inside AWS. Which AWS Directory Service option fits?",
    options: [
      "AWS Managed Microsoft AD",
      "Simple AD",
      "AD Connector: acts as a proxy/redirector to the existing on-premises AD, without storing or replicating directory data in AWS",
      "Amazon Cognito User Pools",
    ],
    correct: 2,
    explain: "AD Connector is a simple directory proxy: it redirects authentication requests to the existing on-premises Active Directory without copying or syncing data. AWS Managed Microsoft AD, in contrast, DOES create a real, managed directory inside AWS (useful if you need trusts or a native cloud AD).",
  },
  {
    tag: "Amazon Verified Permissions",
    q: "Your team is building a multi-tenant SaaS application and needs to decide, on every request, whether the authenticated user can view a specific document based on their role and tenant. Which AWS service is specifically designed for this?",
    options: [
      "IAM Access Analyzer",
      "Amazon Verified Permissions, using Cedar-language policies queried via the IsAuthorized API",
      "AWS Config Rules",
      "A Service Control Policy (SCP) per tenant",
    ],
    correct: 1,
    explain: "Amazon Verified Permissions is a managed authorization engine based on the Cedar language, built for authorization logic INSIDE your own applications (who can view/edit which business resource), not for AWS API permissions. The app queries IsAuthorized on every request instead of hardcoding permission rules.",
  },
  {
    tag: "IAM paths",
    q: "What is the 'path' (e.g. /division_abc/subdivision_xyz/) of an IAM User or Role mainly used for?",
    options: [
      "Defines the region where the identity lives",
      "It's the S3 bucket path where that identity's logs are stored",
      "Groups/organizes identities by prefix within the ARN, allowing you to write administration policies that only allow managing identities under a specific path",
      "Determines the evaluation order of attached policies",
    ],
    correct: 2,
    explain: "The path is part of the ARN (arn:aws:iam::account:role/PATH/name) and is used to organize identities by team/project, allowing you to delegate administration with permissions scoped to a specific path — an authorization mechanism explicitly listed in the exam guide alongside resource policies and trust policies.",
  },
  {
    tag: "Policy Simulator vs Access Analyzer",
    q: "You want to check, before deploying it, whether a specific IAM policy would allow a role to delete a particular S3 bucket — without executing the real action or leaving a trace in CloudTrail. Which tool would you use?",
    options: [
      "IAM Access Analyzer (external access findings)",
      "IAM Policy Simulator (aws iam simulate-principal-policy)",
      "AWS Config conformance packs",
      "GuardDuty",
    ],
    correct: 1,
    explain: "IAM Policy Simulator answers exactly 'would this policy allow this specific action?' without executing anything real. Access Analyzer, in contrast, audits the access posture that ALREADY EXISTS in the account (external access, unused permissions) — they're complementary but answer different questions.",
  },
];
