var QUIZ_DATA = [
  {
    tag: "Policy evaluation",
    q: "A user has an identity policy that allows s3:GetObject on a bucket, but the bucket has a bucket policy with an explicit Deny for that same user. What happens?",
    options: [
      "Access is denied: an explicit Deny in any applicable policy always wins",
      "Access is allowed because the identity policy takes priority",
      "AWS only evaluates the identity policy if the resource belongs to the same account",
      "The outcome depends on which policy was created most recently",
    ],
    correct: 0,
    explain: "IAM's evaluation order is: explicit Deny &gt; explicit Allow &gt; default Deny. An explicit Deny in ANY applicable policy (identity, resource, SCP, RCP, boundary, session policy) overrides any Allow, no matter where it lives.",
  },
  {
    tag: "SCP vs RCP",
    q: "What is the key difference between a Service Control Policy (SCP) and a Resource Control Policy (RCP) in AWS Organizations?",
    options: [
      "There's no difference, they're synonyms for the same mechanism",
      "SCPs limit what the account's identities can do; RCPs limit who can access the resources, including external/anonymous identities",
      "SCPs only apply to the management account",
      "RCPs completely replace SCPs as of 2023",
    ],
    correct: 1,
    explain: "SCPs are guardrails that cap the maximum permission available to principals WITHIN the organization. RCPs (newer) cap access to the RESOURCES themselves, including external principals, closing gaps SCPs don't cover because SCPs don't apply to identities outside the organization.",
  },
  {
    tag: "Permission boundaries",
    q: "A developer has a permission boundary that only allows actions on S3 and DynamoDB. Their identity-based policy grants AdministratorAccess. What can they actually do?",
    options: [
      "Everything, because AdministratorAccess always wins",
      "Nothing, because the boundary and the policy conflict and everything is denied",
      "Only S3 and DynamoDB actions: the permission boundary acts as the maximum ceiling, the intersection with the identity policy",
      "It depends on the order in which the policies were attached",
    ],
    correct: 2,
    explain: "The permission boundary does NOT grant permissions on its own: it defines the maximum set of permissions an identity-based policy can grant. The effective permission is the INTERSECTION between the identity policy and the boundary.",
  },
  {
    tag: "STS",
    q: "A mobile app authenticates users against Google (an OIDC provider) and needs temporary AWS credentials to access an S3 bucket directly from the phone. Which STS API is appropriate?",
    options: [
      "sts:GetSessionToken",
      "sts:GetFederationToken",
      "sts:AssumeRoleWithSAML",
      "sts:AssumeRoleWithWebIdentity (or better, via Amazon Cognito Identity Pools)",
    ],
    correct: 3,
    explain: "AssumeRoleWithWebIdentity exchanges an OIDC token (Google, Facebook, Amazon, or any OIDC-compatible IdP) for temporary credentials. In production, AWS recommends using Cognito Identity Pools on top, which manages the exchange more securely without exposing secrets in the app.",
  },
  {
    tag: "SAML federation",
    q: "A company uses on-premises Active Directory Federation Services (ADFS) and wants to give its employees access to the AWS console without creating IAM users. Which mechanism is the most appropriate?",
    options: [
      "AssumeRoleWithSAML combined with a SAML 2.0 IdP configured in IAM",
      "IAM Roles Anywhere",
      "Individual access keys managed by AD",
      "AWS IAM Identity Center in standalone mode with no external IdP",
    ],
    correct: 0,
    explain: "AssumeRoleWithSAML lets you federate identities from a SAML 2.0 IdP (ADFS, Okta, Azure AD/Entra ID) directly against an IAM Role, without needing individual IAM users. IAM Identity Center is also valid and is the modern option AWS recommends for multi-account setups, but it still needs to connect that same SAML IdP as its identity source.",
  },
  {
    tag: "IAM Identity Center",
    q: "What is the main difference between a traditional cross-account IAM Role and an IAM Identity Center Permission Set?",
    options: [
      "There's no technical difference, IAM Identity Center is just a visual interface over roles",
      "A Permission Set is defined once and IAM Identity Center automatically provisions the corresponding IAM Roles in each assigned member account",
      "Permission Sets only work with root users",
      "Permission Sets don't support AWS managed policies, only inline",
    ],
    correct: 1,
    explain: "IAM Identity Center (the successor to AWS SSO) centralizes management: you define a Permission Set once, and the service automatically provisions/syncs the necessary IAM Roles in each account of the assigned organization, avoiding manual role management account by account.",
  },
  {
    tag: "IAM Access Analyzer",
    q: "What type of finding does IAM Access Analyzer generate when it detects that an IAM role hasn't been used in the last 90 days?",
    options: [
      "External access finding",
      "Policy validation finding",
      "Unused access finding (part of the 'unused access' analysis, available since 2023)",
      "Access Analyzer doesn't analyze usage, only static policies",
    ],
    correct: 2,
    explain: "Access Analyzer has three capabilities: (1) External access findings — detects resources accessible from outside your zone of trust; (2) Unused access findings — identifies roles, permissions, and access keys with no recent use; (3) Policy validation — validates syntax and best practices in policies as you write them.",
  },
  {
    tag: "ABAC",
    q: "In an attribute-based access control (ABAC) strategy with IAM, which condition would typically be used in a policy to allow a user to only tag/access resources that match their own department?",
    options: [
      "\"Condition\": {\"DateLessThan\": {\"aws:CurrentTime\": \"2026-01-01T00:00:00Z\"}}",
      "\"Condition\": {\"IpAddress\": {\"aws:SourceIp\": \"10.0.0.0/16\"}}",
      "\"Condition\": {\"Bool\": {\"aws:MultiFactorAuthPresent\": \"true\"}}",
      "\"Condition\": {\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/department}\"}}",
    ],
    correct: 3,
    explain: "ABAC compares tags on the principal with tags on the resource using policy variables like aws:PrincipalTag/key and aws:ResourceTag/key, enabling access rules that scale without rewriting policies for every new resource.",
  },
  {
    tag: "Confused deputy",
    q: "An AWS service (e.g. CloudTrail) assumes a role in your account on behalf of another AWS customer and, by mistake, accesses data in your account that it shouldn't. Which policy condition prevents this 'confused deputy problem'?",
    options: [
      "aws:SourceArn and/or aws:SourceAccount in the role's trust policy",
      "aws:SourceIp",
      "aws:MultiFactorAuthPresent",
      "aws:RequestedRegion",
    ],
    correct: 0,
    explain: "To prevent an AWS service from being 'tricked' into acting on behalf of an unauthorized third party, you add a condition to the trust policy with aws:SourceArn (or aws:SourceAccount) restricting which specific resource/account can invoke the AssumeRole via that service.",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "A company has on-premises servers (outside AWS) that need temporary AWS credentials without using long-lived access keys. Which service is designed exactly for this case?",
    options: [
      "AWS Systems Manager Hybrid Activations only",
      "IAM Roles Anywhere: uses X.509 certificates issued by a private CA and exchanges them for temporary credentials via STS",
      "IAM Identity Center with an on-premises connector",
      "Cognito Identity Pools",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere lets workloads outside AWS (on-prem servers, other clouds) obtain temporary IAM credentials by presenting an X.509 certificate signed by a trusted CA registered with IAM, eliminating the need for static access keys outside AWS.",
  },
  {
    tag: "Root user",
    q: "AWS introduced 'Centralized Root Access Management' in Organizations. What does this capability allow you to do?",
    options: [
      "Completely eliminate the need to have a root user in every account",
      "Turn root into an IAM role that any user can assume",
      "Centrally manage member accounts' root credentials and apply privileged root actions without needing to recover passwords account by account",
      "Replace MFA in the management account",
    ],
    correct: 2,
    explain: "This Organizations capability (launched in 2023-2024) lets you centrally manage and restrict member accounts' root credentials, and invoke a scoped set of privileged root tasks without having to go through the password-recovery process individually in each account.",
  },
  {
    tag: "MFA",
    q: "Which condition key is used in an IAM policy to require that an API call was made with an MFA-authenticated session?",
    options: [
      "sts:MfaAuthenticated: true",
      "aws:MFA-Required: true",
      "iam:MFAEnabled: true",
      "aws:MultiFactorAuthPresent: true",
    ],
    correct: 3,
    explain: "The standard condition is aws:MultiFactorAuthPresent. A well-tested best practice is combining it with aws:MultiFactorAuthAge to also cap the maximum age of the MFA session.",
  },
  {
    tag: "Resource-based policies",
    q: "Which of these statements about resource-based policies is correct?",
    options: [
      "They allow granting access to a principal from ANOTHER AWS account without that principal needing to assume a role in your account",
      "Only IAM Roles can have resource-based policies",
      "They can never be combined with conditions",
      "They always replace identity-based policies",
    ],
    correct: 0,
    explain: "Resources like S3 buckets, KMS keys, SQS queues, SNS topics, or Lambda functions support resource-based policies, which can directly specify an external Principal (from another account) without that principal needing to assume a role — cross-account access is granted directly on the resource.",
  },
  {
    tag: "Credential report vs Access Advisor",
    q: "What is the difference between the IAM Credential Report and IAM Access Advisor?",
    options: [
      "They're the same report with different names",
      "The Credential Report lists the credential status (passwords, access keys, MFA) of every user; Access Advisor shows which services/actions a principal has actually used and when it last used them",
      "Access Advisor only works at the root account level",
      "The Credential Report requires GuardDuty to be enabled",
    ],
    correct: 1,
    explain: "The Credential Report (generated at the account level, CSV) audits the credential status of every IAM user. Access Advisor (the 'Access Advisor' tab of a user/role) shows the history of accessed services — key for applying least privilege by removing unused permissions.",
  },
  {
    tag: "Cross-account trust policy",
    q: "Which element is mandatory in the trust policy (assume role policy document) of an IAM Role to allow an external account to assume it?",
    options: [
      "A specific SCP in the external account",
      "A bucket policy linked to the role",
      "A Principal referencing the ARN or ID of the external account, with Action sts:AssumeRole",
      "Nothing else: by default any account can assume any role",
    ],
    correct: 2,
    explain: "The role's trust policy must include a Principal with the ARN of the authorized external account/role and Action: sts:AssumeRole. In addition, the assuming account needs its own identity policy allowing it to call sts:AssumeRole on that ARN — BOTH sides (trust + source permission) are required.",
  },
  {
    tag: "Data perimeter",
    q: "In AWS's 'data perimeter' concept, what combination of controls is typically used to ensure data NEVER leaves the organization, even with stolen valid credentials?",
    options: [
      "Only KMS encryption",
      "Only restrictive Security Groups",
      "Only rotating access keys every 90 days",
      "Organization-wide SCPs/RCPs + aws:PrincipalOrgID / aws:ResourceOrgID conditions + VPC endpoint policies",
    ],
    correct: 3,
    explain: "The data perimeter combines 3 types of perimeters: identity (who can access? — SCPs/RCPs with aws:PrincipalOrgID), resource (which resources are trusted? — aws:ResourceOrgID) and network (from where? — VPC endpoint policies + aws:SourceVpce), so that not even valid, compromised credentials can exfiltrate data outside the perimeter.",
  },
  {
    tag: "Session policies",
    q: "When you call sts:AssumeRole passing an additional --policy parameter (session policy), how does this affect the effective permissions of the resulting session?",
    options: [
      "The session policy acts as an additional filter: the effective permissions are the intersection between the role's permissions and the session policy",
      "The session policy expands the role's permissions beyond what it already had",
      "The session policy completely replaces the role's identity policy",
      "Session policies only apply to users, not roles",
    ],
    correct: 0,
    explain: "Just like a permission boundary, a session policy NEVER expands permissions — it can only narrow (intersect) the permissions the assumed role already has. It's useful for issuing more restricted temporary credentials from a broad role.",
  },
  {
    tag: "Declarative policies",
    q: "AWS Organizations introduced 'Declarative Policies'. How do they differ from SCPs?",
    options: [
      "They're identical to SCPs, only the name changes",
      "Declarative Policies centrally set the desired configuration of certain service attributes (e.g. blocking IMDSv1, forcing public access block on EC2/VPC) across the entire organization, instead of just allowing/denying API actions",
      "Declarative Policies only work in the management account",
      "They completely replace Config Rules",
    ],
    correct: 1,
    explain: "Unlike SCPs (which deny/allow API calls), Declarative Policies (2024+) establish and maintain a desired configuration state at the organization level for specific attributes of certain services (e.g. requiring IMDSv2, blocking public access to snapshots), guaranteeing that no account can drift from that configuration.",
  },
  {
    tag: "Policy evaluation with VPC endpoints",
    q: "Which condition key restricts access to an S3 bucket exclusively to requests that pass through a specific VPC endpoint?",
    options: [
      "aws:SourceIp",
      "aws:VpcSourceIp",
      "aws:SourceVpce",
      "s3:VpcEndpointId",
    ],
    correct: 2,
    explain: "aws:SourceVpce in a bucket policy (or any compatible resource policy) restricts access to requests traveling through a specific VPC endpoint, a key 'network perimeter' control to prevent data exfiltration outside the VPC.",
  },
  {
    tag: "Inline vs managed policies",
    q: "What is the main disadvantage of using inline policies instead of managed policies?",
    options: [
      "Inline policies don't support conditions",
      "Inline policies can't deny, only allow",
      "Inline policies have a smaller size limit than managed policies",
      "Inline policies can't be reused across multiple users/roles/groups and are harder to audit and version centrally",
    ],
    correct: 3,
    explain: "An inline policy lives embedded in a single identity (user, group, or role) and cannot be attached to other identities or versioned independently, making it harder to reuse, centrally audit, and manage at scale compared to a customer managed policy.",
  },
  {
    tag: "Amazon Cognito",
    q: "Your web application has its own end-user sign-up/login system, and after authenticating, users need to upload files directly to an S3 bucket using temporary AWS credentials. Which combination of Cognito components would you use?",
    options: [
      "A Cognito User Pool for login (issues JWTs) + a Cognito Identity Pool that exchanges that JWT for temporary AWS credentials",
      "Just a Cognito User Pool, which already issues AWS credentials directly",
      "IAM Identity Center, because Cognito doesn't support users external to the organization",
      "AssumeRoleWithSAML pointed directly at the User Pool",
    ],
    correct: 0,
    explain: "The User Pool manages identity and login (returns JSON Web Tokens), but does NOT grant AWS credentials by itself. The Identity Pool is what exchanges that already-authenticated token for temporary AWS credentials (via STS internally), enabling direct, secure access to services like S3.",
  },
  {
    tag: "S3 presigned URLs",
    q: "What happens to an S3 presigned URL if, before it expires, the s3:GetObject permission of the user who generated it is revoked?",
    options: [
      "The URL keeps working until its lifetime expires, because the credentials were 'frozen' at signing time",
      "The URL stops working immediately: each use is still evaluated against the signer's current IAM permissions",
      "The URL automatically becomes invalid in under 1 minute",
      "It's not possible to revoke permissions for a presigned URL once generated",
    ],
    correct: 1,
    explain: "A presigned URL is not an independent credential: it's a signature that delegates, for a time window, the signer's current permission. If that permission is revoked (the policy is removed, the role is disabled, etc.) before the URL expires, access is also denied, because IAM is still evaluated on every request.",
  },
  {
    tag: "AWS Directory Service",
    q: "A company has an on-premises Active Directory it wants to keep using as its identity source, without migrating data or replicating the directory inside AWS. Which AWS Directory Service option fits?",
    options: [
      "AWS Managed Microsoft AD",
      "Simple AD",
      "AD Connector: acts as a proxy/redirector to the existing on-premises AD, without storing or replicating directory data in AWS",
      "Amazon Cognito User Pools",
    ],
    correct: 2,
    explain: "AD Connector is a simple directory proxy: it redirects authentication requests to the existing on-premises Active Directory without copying or syncing data. AWS Managed Microsoft AD, in contrast, DOES create a real, managed directory inside AWS (useful if you need trusts or a native cloud AD).",
  },
  {
    tag: "Amazon Verified Permissions",
    q: "Your team is building a multi-tenant SaaS application and needs to decide, on every request, whether the authenticated user can view a specific document based on their role and tenant. Which AWS service is specifically designed for this?",
    options: [
      "IAM Access Analyzer",
      "A Service Control Policy (SCP) per tenant",
      "AWS Config Rules",
      "Amazon Verified Permissions, using Cedar-language policies queried via the IsAuthorized API",
    ],
    correct: 3,
    explain: "Amazon Verified Permissions is a managed authorization engine based on the Cedar language, built for authorization logic INSIDE your own applications (who can view/edit which business resource), not for AWS API permissions. The app queries IsAuthorized on every request instead of hardcoding permission rules.",
  },
  {
    tag: "IAM paths",
    q: "What is the 'path' (e.g. /division_abc/subdivision_xyz/) of an IAM User or Role mainly used for?",
    options: [
      "Groups/organizes identities by prefix within the ARN, allowing you to write administration policies that only allow managing identities under a specific path",
      "It's the S3 bucket path where that identity's logs are stored",
      "Defines the region where the identity lives",
      "Determines the evaluation order of attached policies",
    ],
    correct: 0,
    explain: "The path is part of the ARN (arn:aws:iam::account:role/PATH/name) and is used to organize identities by team/project, allowing you to delegate administration with permissions scoped to a specific path — an authorization mechanism explicitly listed in the exam guide alongside resource policies and trust policies.",
  },
  {
    tag: "Policy Simulator vs Access Analyzer",
    q: "You want to check, before deploying it, whether a specific IAM policy would allow a role to delete a particular S3 bucket — without executing the real action or leaving a trace in CloudTrail. Which tool would you use?",
    options: [
      "IAM Access Analyzer (external access findings)",
      "IAM Policy Simulator (aws iam simulate-principal-policy)",
      "AWS Config conformance packs",
      "GuardDuty",
    ],
    correct: 1,
    explain: "IAM Policy Simulator answers exactly 'would this policy allow this specific action?' without executing anything real. Access Analyzer, in contrast, audits the access posture that ALREADY EXISTS in the account (external access, unused permissions) — they're complementary but answer different questions.",
  },
  {
    tag: "Access Analyzer – Internal access",
    q: "Your AWS Organizations org has dozens of accounts. You want to know, taking into account the combined effect of identity policies, SCPs, and RCPs, which roles and users INSIDE your own organization could end up accessing a critical S3 bucket in another account — external access isn't the concern here. Which IAM Access Analyzer capability, launched in 2025, answers exactly this?",
    options: [
      "External access findings from an account-scoped analyzer",
      "Unused access findings",
      "Internal access findings: a new analyzer type that uses automated reasoning to jointly evaluate identity policies, SCPs, and RCPs and show which principals in the organization can access S3, DynamoDB, or RDS resources",
      "The IAM Credential Report",
    ],
    correct: 2,
    explain: "In June 2025 AWS launched Internal Access Findings in IAM Access Analyzer: it uses automated reasoning (the same Zelkova technology that validates policies) to jointly evaluate identity-based policies, SCPs, and RCPs and generate findings on which identities INSIDE the organization have access to S3, DynamoDB, or RDS — complementing external access findings, which only look at access from outside the account/organization.",
  },
  {
    tag: "STS AssumeRoot",
    q: "A member account of the organization has Centralized Root Access Management enabled and its root credentials have been deleted. An administrator in the management account needs to temporarily unlock a corrupted S3 bucket policy in that member account, a task only root can perform. What is required to accomplish this?",
    options: [
      "Call a normal sts:AssumeRole; any role with AdministratorAccess can do the same thing root can",
      "Use sts:AssumeRoleWithSAML pointing at the corporate IdP",
      "Recover the member account's root password through the standard 'forgot password' flow",
      "Call sts:AssumeRoot from the management account (or a delegated administrator), mandatorily specifying an AWS managed TaskPolicy that scopes the session to that specific task — an unrestricted root session can never be obtained",
    ],
    correct: 3,
    explain: "sts:AssumeRoot can only be invoked from the Organization's management account (or an IAM delegated administrator), never with root credentials, and requires specifying an AWS managed TaskPolicy (e.g. for unlocking S3 policies or resolving KMS key issues) that scopes exactly what that temporary root session — capped at 15 minutes — can do. It never grants an 'unrestricted' root session.",
  },
  {
    tag: "Access Analyzer – Custom policy checks",
    q: "Your platform team wants to block, in the CI/CD pipeline, any pull request that adds a specific dangerous permission (e.g. iam:CreateAccessKey) to an IAM policy, BEFORE it gets deployed. Which IAM Access Analyzer API fits this automated control?",
    options: [
      "CheckAccessNotGranted: verifies that a candidate policy does NOT grant a set of critical permissions you specify, ideal for CI/CD gates",
      "list-findings-v2",
      "GetGeneratedPolicy",
      "simulate-principal-policy",
    ],
    correct: 0,
    explain: "CheckAccessNotGranted (part of Access Analyzer's custom policy checks, built on automated reasoning) lets you declare a list of critical actions/permissions that should never be granted and check a candidate policy against that list before deployment. Its sibling, CheckNoNewAccess, compares a new policy against a reference policy to ensure no additional access is introduced when it's updated.",
  },
  {
    tag: "aws:CalledVia",
    q: "You want to allow a user to run queries in Amazon Athena that internally call S3 and AWS Glue on their behalf, but prevent that same user from calling those S3/Glue actions directly outside the context of Athena. Which IAM condition key is designed exactly for this scenario?",
    options: [
      "aws:SourceArn",
      "aws:CalledVia, which holds the ordered list of AWS services that made the call on behalf of the principal, letting you require that certain actions only be executed 'via' a specific service",
      "aws:ViaAWSService alone, with no further nuance",
      "aws:PrincipalServiceName",
    ],
    correct: 1,
    explain: "aws:CalledVia captures the chain of AWS services that forwarded the request on the principal's behalf (e.g. Athena calling S3/Glue). With a StringEquals condition on aws:CalledVia you can require that certain actions (e.g. s3:GetObject on a specific bucket) are only allowed when invoked via athena.amazonaws.com, denying the user's direct call to those same actions.",
  },
  {
    tag: "SCP – full IAM policy language (2025)",
    q: "Until recently, SCPs only supported a limited subset of the IAM policy language. After the September 2025 AWS Organizations update, what new syntax capability became available in SCPs?",
    options: [
      "SCPs became able to grant permissions on their own, just like an identity-based policy",
      "SCPs became able to apply to accounts outside the organization",
      "Support for the full IAM policy language in SCPs: conditions, individual resource ARNs, the NotAction element combined with Allow, wildcards at the start/middle of the Action element, and NotResource",
      "SCPs completely replaced RCPs",
    ],
    correct: 2,
    explain: "Since September 2025, AWS Organizations supports the full IAM policy language in SCPs: conditions, specific resource ARNs, NotAction in Allow statements, wildcards in the middle of Action, and the NotResource element — matching the expressiveness of a regular IAM managed policy. This does NOT change the nature of SCPs: they remain purely guardrails that cap (never grant) permissions.",
  },
  {
    tag: "IAM Identity Center – Trusted Identity Propagation",
    q: "A corporate analyst, authenticated in IAM Identity Center, queries data in Amazon Athena/Redshift through Amazon QuickSight. The company wants the access logs for the underlying data in S3/Lake Formation to show the analyst's real corporate identity (not a generic service role), and wants data access permissions evaluated against their actual attributes/groups. Which IAM Identity Center mechanism enables this?",
    options: [
      "Traditional Permission Sets assigned directly to the analyst",
      "Session policies applied to QuickSight's service role",
      "Classic AssumeRoleWithSAML",
      "Trusted Identity Propagation (TIP): propagates the authenticated user's identity context across the chain of AWS services, so that permissions and audit logs reflect the real person, not a shared role",
    ],
    correct: 3,
    explain: "Trusted Identity Propagation adds the Identity Center user's identity context to an IAM Role when one service (QuickSight, Athena, Redshift, EMR, OpenSearch, SageMaker Unified Studio...) calls another on their behalf. This means data access permissions and CloudTrail records reflect the user's actual corporate identity instead of a shared service role, without needing to create an IAM role per person.",
  },
  {
    tag: "Multi-party approval",
    q: "The security team wants to ensure that no single person, acting alone, can restore/share data from a logically air-gapped AWS Backup vault in a ransomware recovery scenario — multiple authorized people must approve the operation before it executes. Which AWS governance capability, launched in 2025, is designed for this?",
    options: [
      "Multi-party approval (MPA): requires AWS Organizations and IAM Identity Center to be enabled, and an 'approval team' made up of multiple people to vote before critical operations — like sharing a backup from an air-gapped vault — execute",
      "An SCP with a Deny conditioned on aws:MultiFactorAuthPresent",
      "Permission boundaries combined with Access Analyzer",
      "AWS Config conformance packs with automatic remediation",
    ],
    correct: 0,
    explain: "Multi-party approval (MPA) requires AWS Organizations and IAM Identity Center. It lets you create approval teams whose members vote (with OTP verification since 2026) before a sensitive operation runs; its first integration was with AWS Backup for logically air-gapped vaults, allowing backups to be shared/restored from a potentially compromised account only with distributed approval, so no single person can do it unilaterally.",
  },
  {
    tag: "Declarative Policies – EC2/VPC/AMI attributes",
    q: "You want to guarantee, for the ENTIRE organization and in a way that no account can drift from even with local AdministratorAccess, that no EC2 instance can use IMDSv1 and that no VPC can reach the internet through an Internet Gateway except for explicit exceptions. Which AWS Organizations mechanism enforces exactly this type of control?",
    options: [
      "An SCP with a Deny on ec2:RunInstances unless a specific tag is included",
      "Declarative Policies: they fix specific attributes such as 'IMDSv2 enforcement' and 'VPC Block Public Access' as the desired configuration state at the organization/OU level, maintaining it even as new accounts are created or new APIs appear",
      "AWS Config managed rules with automatic remediation via SSM",
      "Resource Control Policies (RCP) on the EC2 service",
    ],
    correct: 1,
    explain: "Declarative Policies (launched in late 2024) cover, among others, EC2/VPC attributes such as 'VPC Block Public Access', 'Image (AMI) Block Public Access', and 'IMDSv2 enforcement'. Unlike an SCP (which denies API calls), a Declarative Policy fixes a desired configuration state that is automatically maintained even as new accounts appear or the service gains new features — it is not an allow/deny mechanism for actions.",
  },
  {
    tag: "RCP – management account exemption",
    q: "A company deploys an RCP at the organization root to restrict S3 bucket access to identities inside the organization only. An engineer, authenticated as an IAM user in the Organization's MANAGEMENT account, accesses a bucket in a member account without any issue, even though that bucket should theoretically be blocked from external sources by that RCP. Why?",
    options: [
      "It's a misconfiguration: RCPs must always apply to the management account too",
      "The user has MFA enabled, which automatically exempts them from any RCP",
      "By design, RCPs do NOT affect requests made by identities from the organization's management account — they only restrict resources in member accounts",
      "RCPs only apply to calls made from outside the bucket's region",
    ],
    correct: 2,
    explain: "A key (and counterintuitive, hence frequently tested) quirk of RCPs is that they do NOT apply to requests made by principals from the Organization's management account, even if the resource lives in a member account within the policy's scope. It's analogous to why the management account shouldn't be used for day-to-day operations: it escapes this type of organizational guardrail.",
  },
  {
    tag: "IAM Roles Anywhere – ABAC with certificates",
    q: "A company uses IAM Roles Anywhere to issue credentials to on-premises servers, and wants the assumed role to automatically carry a session tag with the server's name, extracted from the X.509 certificate itself used to authenticate, so it can apply ABAC policies without managing tags manually. Is this possible, and how?",
    options: [
      "It's not possible; session tags can only be added manually when invoking CreateSession",
      "No, IAM Roles Anywhere doesn't support any kind of session tagging",
      "Yes, but only if the certificate is issued by public AWS Certificate Manager, never by a private CA",
      "Yes: IAM Roles Anywhere can automatically map the Relative Distinguished Names (RDNs) from the Subject (and fields from the Issuer) of the X.509 certificate to session PrincipalTags, enabling ABAC policies based on certificate attributes",
    ],
    correct: 3,
    explain: "IAM Roles Anywhere can automatically map fields from the Subject (RDNs like CN, OU) and the Issuer of the presented X.509 certificate to the resulting session's PrincipalTag. This enables building ABAC policies (e.g. 'this server can only access resources with the same OU tag as its certificate') without having to manually manage tags for every session.",
  },
  {
    tag: "Verified Permissions – BatchIsAuthorized",
    q: "Your SaaS application needs to render a list of 25 documents and decide, for each one, whether the current user can view it and whether they can edit it — up to 50 authorization decisions for a single page load. Making 50 individual IsAuthorized calls would add too much latency. What does Amazon Verified Permissions offer for this case?",
    options: [
      "BatchIsAuthorized: evaluates up to 30 authorization decisions for the same principal or resource in a single API call, reducing latency compared to individual calls",
      "There's no alternative; you must call IsAuthorized 50 times sequentially",
      "You must export the Cedar policies and evaluate them locally on the client",
      "It's only possible using AWS Lambda@Edge to cache the decisions",
    ],
    correct: 0,
    explain: "Amazon Verified Permissions supports BatchIsAuthorized, which groups up to 30 authorization decisions into a single call for a given principal or resource — very useful for rendering interfaces (lists, tables) where you need to decide at once which actions are allowed on multiple items, avoiding the network cost of repeated individual calls.",
  },
  {
    tag: "Mandatory permission boundary on role creation",
    q: "You want to let developers create their own IAM Roles (iam:CreateRole) but guarantee they can NEVER create a role without a specific permission boundary attached to it — closing the door on self-granting admin permissions via a new boundary-less role. Which policy mechanism enforces exactly this restriction?",
    options: [
      "An SCP with a blanket Deny on iam:CreateRole",
      "A condition in the developer's identity policy using the iam:PermissionsBoundary key, requiring that any iam:CreateRole/iam:PutRolePermissionsBoundary specify the exact ARN of the allowed boundary",
      "A permission boundary can't be made mandatory; it depends on the developer's goodwill",
      "An IAM resource-based policy",
    ],
    correct: 1,
    explain: "The iam:PermissionsBoundary condition key (used with StringEquals against the ARN of the allowed boundary) can be added to the identity policy that grants a developer iam:CreateRole and iam:PutRolePermissionsBoundary, denying the operation unless exactly that boundary is attached. It's AWS's standard pattern for delegating role creation without enabling privilege escalation.",
  },
  {
    tag: "STS – role chaining and session duration",
    q: "A user assumes Role A (a 12-hour session) and, using those temporary credentials, tries to assume Role B (role chaining), also requesting --duration-seconds pointing to 12 hours. What happens to the maximum duration of the resulting Role B session?",
    options: [
      "The Role B session can also last up to 12 hours with no additional restriction",
      "Role chaining is prohibited by AWS STS and the second AssumeRole call will always fail",
      "When role chaining is used (temporary credentials from one role to assume another role), the maximum duration of the new session is capped at 1 hour, regardless of the MaxSessionDuration configured on Role B",
      "The duration depends solely on whether the user has MFA enabled",
    ],
    correct: 2,
    explain: "AWS STS explicitly caps role chaining: if you use the temporary credentials resulting from an AssumeRole to call AssumeRole again on another role, the maximum duration of that second session is capped at 1 hour, regardless of the MaxSessionDuration configured on the target role. This is a heavily tested detail because it contradicts the expectation that duration always follows the role's configuration.",
  },
  {
    tag: "RCP – aws:PrincipalOrgID vs aws:ResourceOrgID",
    q: "When designing 'data perimeter' guardrails with RCPs, what is the practical difference between conditioning an RCP on aws:PrincipalOrgID versus on aws:ResourceOrgID?",
    options: [
      "They're fully interchangeable synonyms",
      "aws:PrincipalOrgID no longer exists as of 2025, replaced by aws:SourceOrgID",
      "aws:ResourceOrgID can only be used in SCPs, never in RCPs",
      "aws:PrincipalOrgID checks which organization the calling IDENTITY belongs to (identity perimeter); aws:ResourceOrgID compares the PRINCIPAL's organization against the resource's own organization, useful for allowing cross-account access only within the same organization without listing every account",
    ],
    correct: 3,
    explain: "aws:PrincipalOrgID is the classic identity-perimeter key: it compares the calling principal's Organization ID against a fixed value. aws:ResourceOrgID (a variable, typically compared as '${aws:ResourceOrgID}' or implicitly in RCPs) lets you express 'only allow access if the principal belongs to the SAME organization as the resource itself' — a pattern widely used in RCPs to block access from outside the organization without maintaining account lists.",
  },
  {
    tag: "Access Analyzer – policy generation",
    q: "A team has been running an IAM role with the AdministratorAccess managed policy 'temporarily' for 6 months, and now wants to generate a least-privilege policy based on what that role has ACTUALLY used according to its CloudTrail activity, instead of writing one by hand from scratch. Which IAM Access Analyzer feature solves this directly?",
    options: [
      "Policy generation based on access activity: Access Analyzer analyzes the role's CloudTrail events and proposes a least-privilege IAM policy covering the services and actions actually used",
      "External access findings",
      "Unused access findings, which automatically generates the replacement policy",
      "IAM Credential Report",
    ],
    correct: 0,
    explain: "IAM Access Analyzer can generate a candidate policy by analyzing real activity recorded in CloudTrail (over a configurable period, up to 90 days) for a given role or user, proposing the services and actions actually used as a starting point for a least-privilege policy — far more precise than starting from scratch or relying only on service-level Access Advisor.",
  },
  {
    tag: "Verified Permissions – policy templates",
    q: "Your multi-tenant SaaS application has the same authorization pattern repeated for hundreds of tenants ('the owner can edit their own resource'), and you want to avoid duplicating the same Cedar policy hundreds of times in the policy store, one per tenant. Which Amazon Verified Permissions feature is designed exactly for this?",
    options: [
      "Create a separate policy store per tenant and sync them manually",
      "Policy templates: define a single Cedar policy template with placeholders (?principal, ?resource) that is then instantiated as 'template-linked policies' with concrete values per tenant, without duplicating the logic",
      "Use only static policies with no variables, one for every possible user/resource combination",
      "It's not possible; Cedar doesn't support policy parameterization",
    ],
    correct: 1,
    explain: "Verified Permissions policy templates let you declare a single Cedar template with placeholders (?principal and/or ?resource) and then create multiple 'template-linked policies' that instantiate that template with concrete IDs, avoiding the need to maintain hundreds of nearly identical copies of the same policy — key for multi-tenant SaaS at scale.",
  },
  {
    tag: "aws:PrincipalOrgID vs aws:PrincipalOrgPaths",
    q: "An organization has an OU named 'Sandbox' under the root, and wants an RCP that allows access to an S3 bucket only to identities that specifically belong to that OU (and its sub-OUs), not the entire organization in general. Which condition key is appropriate?",
    options: [
      "aws:PrincipalOrgID, pointing to the ID of the entire organization",
      "aws:PrincipalAccount, manually listing every account in the OU",
      "aws:PrincipalOrgPaths, which lets you compare the full hierarchical OU path the principal belongs to (organization/root OU/intermediate OU/...), allowing you to scope to a specific branch of the OU tree",
      "aws:ResourceOrgID",
    ],
    correct: 2,
    explain: "aws:PrincipalOrgID only identifies the whole organization (o-xxxxxxxxxx), without distinguishing OUs. To scope to a specific branch of the hierarchical tree (e.g. just the Sandbox OU and anything under it), you use aws:PrincipalOrgPaths, which contains the principal's full OU-ID path and supports prefix matching — far more precise than maintaining account lists.",
  },
  {
    tag: "Root user – AssumeRoot task policies",
    q: "When a management-account administrator calls sts:AssumeRoot to perform a root task in a member account, what exactly determines what that temporary root session can do?",
    options: [
      "Nothing limits it: any session obtained via AssumeRoot has full, unrestricted root privileges, just like the traditional root user",
      "An SCP with an explicit Allow on root:*",
      "The permission boundary that had been attached to the root user before its credentials were deleted",
      "A mandatory AWS managed TaskPolicy (e.g. for unlocking S3 policies, resolving KMS issues, or managing root configuration itself) that scopes the session exclusively to that specific task, never to generic root privileges",
    ],
    correct: 3,
    explain: "Unlike traditional root (which has no limits), sts:AssumeRoot requires specifying one of a bounded set of AWS managed TaskPolicies (designed for specific tasks that legitimately require root, such as unlocking a bucket policy that locked itself out). There is no 'unrestricted root' option via AssumeRoot — by design it's always a minimally scoped root session for one specific task.",
  },
  {
    tag: "Unused access analyzer – tracking period",
    q: "When configuring an unused access analyzer in IAM Access Analyzer, what does the 'tracking period' parameter control?",
    options: [
      "The time window (configurable, with preset options of 30/60/90 days or a custom value) during which actual permission usage is monitored; 'unused' findings are only generated for permissions/identities that already existed for the ENTIRE window",
      "The time Access Analyzer takes to generate the first finding, always fixed at 24 hours",
      "The time it takes for an unused role to be automatically deleted",
      "How often the KMS key used by Access Analyzer is rotated",
    ],
    correct: 0,
    explain: "The tracking period defines how long Access Analyzer observes actual permission usage before considering something 'unused' (default 90 days, configurable). A key exam detail: only identities and permissions that already existed for the ENTIRE period are evaluated — a role created 10 days ago with a 90-day tracking period will not yet generate an unused-access finding due to insufficient age.",
  },
  {
    tag: "RCP – supported services",
    q: "A security team wants to use an RCP to centrally restrict access to the organization's managed NoSQL database tables, requiring that only identities inside the organization itself can read them, even if some identity or resource policy accidentally exposes them externally. Following RCP support expansions through 2026, which service allows enforcing this directly via RCP?",
    options: [
      "Amazon RDS, supported by RCP since the initial 2024 launch",
      "Amazon DynamoDB, added to the set of RCP-supported services in a 2026 expansion, alongside S3, STS, KMS, SQS, Secrets Manager, ECR, OpenSearch Serverless, Cognito, and CloudWatch Logs",
      "Amazon Redshift, supported since the initial launch",
      "No database service supports RCPs; only object storage services",
    ],
    correct: 1,
    explain: "RCPs launched in November 2024 covering S3, STS, KMS, SQS, and Secrets Manager, and AWS has progressively expanded the list: ECR and OpenSearch Serverless (2025), and later Cognito, CloudWatch Logs, and Amazon DynamoDB. The exam may test this evolving list; the key concept is that RCPs only apply to services explicitly supported at any given time, not the entire AWS catalog.",
  },
  {
    tag: "Data perimeter – SCP vs RCP trap",
    q: "An organization configures an SCP that denies any s3:GetObject action unless the principal belongs to the organization (using aws:PrincipalOrgID). Yet an external third party manages to read an object from an organization S3 bucket because the bucket has a bucket policy granting them explicit Allow access. Why didn't the SCP prevent this?",
    options: [
      "The SCP has a syntax error",
      "S3 doesn't support SCPs of any kind",
      "SCPs only restrict what IDENTITIES belonging to the organization can do; they don't apply to external principals who arrive directly via the resource's own resource-based policy — exactly the gap RCPs are designed to close",
      "SCPs only apply to calls made from the console, not from the API",
    ],
    correct: 2,
    explain: "This is the canonical example of why RCPs exist: an SCP caps what identities INSIDE your organization can do, but an external principal (outside the organization) accessing via a bucket policy with an explicit Allow never 'passes through' that SCP, because SCPs aren't evaluated against principals outside the organization. Closing that gap requires an RCP, which CAN require that access to a resource — no matter who it comes from — satisfy a condition like aws:PrincipalOrgID.",
  },
  {
    tag: "SCP – multi-level evaluation across the OU tree",
    q: "An account hangs off OU-Production, which in turn hangs off the organization root. The root has an SCP that allows s3:*, OU-Production has an SCP that explicitly denies s3:DeleteBucket, and the account itself has no additional SCPs. Can s3:DeleteBucket be executed in that account?",
    options: [
      "Yes, because the root's SCP allows s3:* and takes priority for being higher in the hierarchy",
      "OU-level SCPs never take effect if the account has no SCP of its own",
      "It depends on which SCP was attached most recently",
      "No: for an action to be allowed, ALL SCPs along the full path from the root to the account (root → intermediate OUs → account) must allow it; an explicit Deny at any level of the tree blocks the action regardless of what other levels say",
    ],
    correct: 3,
    explain: "SCPs are evaluated cumulatively along the ENTIRE hierarchical path from the organization root down to the account (passing through every intermediate OU). The effective permission is the intersection of what's allowed at each level, and an explicit Deny anywhere along the path (here, OU-Production) blocks the action for the account, regardless of a higher level (the root) allowing it.",
  },
  {
    tag: "Cross-account access",
    q: "An application in account A must assume a role in account B. Which TWO elements are indispensable?",
    options: [
      "A trust policy on the account B role authorizing the account A principal to assume it",
      "An sts:AssumeRole permission in the account A principal's identity policy",
      "Both accounts belonging to the same AWS Organization",
      "VPC peering between the accounts so STS can route the request",
    ],
    correct: [0, 1],
    explain: "Cross-account access requires <b>both ends</b>: the resource (the role) must trust the caller, and the caller must be permitted to call. It is the classic case where an Allow on one side alone is not enough. Organizations isn't required — cross-account works between unrelated accounts — nor is network connectivity, because STS is a public service endpoint, not something living in your VPC.",
  },
  {
    tag: "Sources of an explicit Deny",
    q: "A user gets AccessDenied despite an identity policy allowing the action. In which TWO places could the blocking Deny live?",
    options: [
      "In a Service Control Policy attached to the OU or the account",
      "In the resource-based policy of the resource being accessed",
      "In the IAM console, which blocks actions flagged as dangerous",
      "In the CloudTrail history, which revokes permissions used improperly",
    ],
    correct: [0, 1],
    explain: "An explicit Deny in <b>any</b> applicable policy always wins: identity policy, resource policy, SCP, RCP, permission boundary or session policy. Here the two real candidates are the SCP and the resource policy. The IAM console doesn't block actions on its own, and CloudTrail is an audit log: it <b>observes</b>, it never revokes. Confusing a logging service with an enforcement one is a classic distractor.",
  },
  {
    tag: "Data perimeter",
    q: "You want your S3 buckets accessible only by identities from your own organization and only from your network. Which TWO condition keys would you use?",
    options: [
      "aws:PrincipalOrgID, to require the caller to belong to your organization",
      "aws:SourceVpce, to require the request to arrive through your VPC endpoint",
      "aws:RequestedRegion, to limit access to a specific Region",
      "aws:CurrentTime, to allow access only during business hours",
    ],
    correct: [0, 1],
    explain: "A data perimeter is built on two axes: <b>who</b> (identity perimeter, via aws:PrincipalOrgID) and <b>from where</b> (network perimeter, via aws:SourceVpce or aws:SourceIp). The other two condition keys are real and valid, but they scope Region and time of day: they answer neither the identity nor the network question posed here.",
  },
  {
    tag: "Permission boundaries",
    q: "You will let developers create their own roles without being able to escalate privileges. Which TWO statements about permission boundaries are correct?",
    options: [
      "A permission boundary grants nothing by itself: it caps what an identity policy can grant",
      "You can require, via a condition in the developer's policy, that every role they create carries a specific boundary",
      "The permission boundary replaces the identity policy: attaching the boundary is enough",
      "Permission boundaries apply to resources, just like bucket policies",
    ],
    correct: [0, 1],
    explain: "Effective permission is the <b>intersection</b> of the identity policy and the boundary, so the boundary alone grants nothing and doesn't replace the policy. The <code>iam:PermissionsBoundary</code> condition is precisely the mechanism for delegating role creation without allowing escalation. And boundaries attach to <b>identities</b> (users and roles), not to resources.",
  },
  {
    tag: "Federation with IAM Identity Center",
    q: "A company with 3,000 employees in a corporate IdP wants to grant access to 60 AWS accounts without creating IAM users. Which TWO statements describe the right approach?",
    options: [
      "IAM Identity Center federates with the IdP and assigns permission sets to groups across the organization's accounts",
      "Users receive temporary credentials via STS, not long-lived access keys",
      "You must create one IAM user per employee in each account and sync it with the IdP",
      "Each employee should share a common access key to simplify management",
    ],
    correct: [0, 1],
    explain: "<b>Identity Center</b> with <b>permission sets</b> assigned to groups is the recommended pattern at scale, and federation always issues <b>temporary STS credentials</b>. Creating 3,000 users across 60 accounts is exactly the problem federation removes (180,000 identities to maintain). Sharing one key between people destroys attribution: it is never the answer.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["iam"] = QUIZ_DATA;
