var QUIZ_DATA = [
  {
    tag: "Security Groups vs NACLs",
    q: "What is the MOST important behavioral difference between a Security Group and a Network ACL?",
    options: [
      "The Security Group is STATEFUL (return traffic is allowed automatically) and only supports Allow rules",
      "The Security Group operates at the subnet level and the NACL at the instance level",
      "Both are identical, only where they're configured in the console differs",
      "The NACL only filters HTTP/HTTPS traffic",
    ],
    correct: 0,
    explain: "Security Group = stateful, at the ENI/instance level, Allow only (anything not permitted is implicitly denied). NACL = stateless, at the subnet level, with numbered rules evaluated in order that can be Allow or Deny — that's why you have to explicitly open return traffic (ephemeral ports).",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "You detect repeated malicious traffic from a specific IP and want to block it immediately at the network level, without relying on any instance's rules to allow it. What mechanism do you use?",
    options: [
      "Add the IP to a Security Group with Deny",
      "A Deny rule in the subnet's Network ACL (Security Groups can't explicitly deny an IP)",
      "Modify the subnet's route table",
      "Enable GuardDuty",
    ],
    correct: 1,
    explain: "Security Groups do NOT have Deny rules — you can only specify what's allowed. To explicitly block a specific IP at the network level (regardless of which Security Group each instance has), you need a Deny rule in the subnet's NACL, evaluated before traffic reaches the instance.",
  },
  {
    tag: "AWS WAF",
    q: "What type of attack is a 'rate-based rule' in AWS WAF designed to detect and block?",
    options: [
      "SQL injection only",
      "Attacks that already passed through CloudFront",
      "An anomalously high volume of requests from the same IP (or aggregation key) within a time window",
      "UDP traffic only",
    ],
    correct: 2,
    explain: "WAF rate-based rules count requests by aggregation key (source IP by default, or a custom combination) in sliding 5- or 10-minute windows, and block automatically once the threshold is exceeded — ideal against brute force, credential stuffing, or scraping, complementary to signature rules (SQLi, XSS from the OWASP Top 10).",
  },
  {
    tag: "Shield Advanced",
    q: "What does AWS Shield Advanced add on top of the standard DDoS protection (Shield Standard) that comes free with every account?",
    options: [
      "Nothing, Shield Standard already covers all cases",
      "Shield Advanced completely replaces WAF",
      "It only protects Route 53, not CloudFront or ALB",
      "Advanced protection against more sophisticated layer 3/4 and layer 7 attacks, access to the DDoS Response Team (DRT), cost reimbursement for scaling spikes during an attack, and detailed visibility/metrics — paid, per account or per resource",
    ],
    correct: 3,
    explain: "Shield Standard (free, automatic) covers the most common layer 3/4 DDoS attacks. Shield Advanced adds extended protection, the DDoS Response Team available 24/7, cost protection (credits if you scale due to an attack), and integrates with WAF for layer 7 mitigation — recommended for critical workloads with an availability SLA.",
  },
  {
    tag: "Edge security",
    q: "You want to block access to your CloudFront-distributed application from every country except Spain and Portugal. What mechanism do you use?",
    options: [
      "CloudFront Geo Restriction (country allowlist) or a geo-match rule in AWS WAF associated with the distribution",
      "A Security Group with per-country rules",
      "A NACL with per-country CIDR ranges",
      "Route 53 Resolver DNS Firewall",
    ],
    correct: 0,
    explain: "CloudFront Geo Restriction allows an allowlist/blocklist of countries directly on the distribution. Alternatively, a geo-match rule in WAF (associated with CloudFront) offers the same capability with more flexibility to combine it with other conditions (rate limiting, fingerprinting).",
  },
  {
    tag: "S3 CORS",
    q: "Your SPA at https://app.mydomain.com needs to make fetch() requests directly to an S3 bucket to upload files, and the browser blocks them with a CORS error. What do you configure?",
    options: [
      "A bucket policy that allows the Principal '*'",
      "A CORS configuration on the S3 bucket that explicitly allows the origin https://app.mydomain.com and the necessary methods/headers",
      "Disable HTTPS on the bucket",
      "A Security Group on the bucket",
    ],
    correct: 1,
    explain: "CORS (Cross-Origin Resource Sharing) is a BROWSER restriction, not an AWS one. S3 supports its own CORS configuration (AllowedOrigins, AllowedMethods, AllowedHeaders) that tells the browser that a given origin is permitted to make cross-origin requests to the bucket — independent of the bucket policy or IAM permissions.",
  },
  {
    tag: "Hardened AMIs",
    q: "Which AWS service is specifically designed to build, maintain, and validate hardened AMIs (or container images) in an automated, repeatable way?",
    options: [
      "AWS Config",
      "AWS Backup",
      "EC2 Image Builder: an automated pipeline that applies hardening (e.g. CIS benchmarks), installs patches, and runs validation tests before publishing the AMI",
      "Amazon Macie",
    ],
    correct: 2,
    explain: "EC2 Image Builder automates the entire pipeline: starting from a base image, applying hardening/configuration components, installing updates, running tests, and publishing the resulting AMI (or container image) — eliminating the manual process and guaranteeing reproducibility between versions.",
  },
  {
    tag: "Instance profiles vs roles",
    q: "What is the relationship between an EC2 'Instance Profile' and an IAM Role?",
    options: [
      "They are exact synonyms; either term can be used interchangeably in the API",
      "The Instance Profile removes the need for an IAM Role",
      "An Instance Profile can contain multiple IAM Roles simultaneously",
      "The Instance Profile is the CONTAINER that associates an IAM Role with an EC2 instance",
    ],
    correct: 3,
    explain: "Technically, you don't attach an IAM Role directly to an EC2 instance: you attach an Instance Profile, which in turn references a SINGLE IAM Role. The AWS console hides this distinction by creating the Instance Profile automatically, but the CLI/API exposes it (aws iam create-instance-profile + add-role-to-instance-profile).",
  },
  {
    tag: "Amazon Inspector",
    q: "What types of resources can Amazon Inspector scan for known vulnerabilities (CVEs)?",
    options: [
      "EC2 instances, container images in Amazon ECR, and Lambda functions (code and layers)",
      "EC2 instances only",
      "RDS databases only",
      "S3 buckets only",
    ],
    correct: 0,
    explain: "Amazon Inspector continuously and automatically scans EC2 (OS packages and network vulnerabilities), container images in ECR (on push and periodically), and Lambda functions (dependencies in the code). GuardDuty, by contrast, monitors RUNTIME behavior (real-time anomalous activity), not known static vulnerabilities.",
  },
  {
    tag: "Patch management",
    q: "Which Systems Manager component automates applying OS security patches across a fleet of EC2 instances, according to a scheduled maintenance window?",
    options: [
      "Systems Manager Session Manager",
      "Systems Manager Patch Manager, typically orchestrated with Maintenance Windows",
      "Systems Manager Parameter Store",
      "AWS Config",
    ],
    correct: 1,
    explain: "Patch Manager automates scanning and applying patches (OS and some applications) according to configurable approval baselines, run within Maintenance Windows to control when the impact occurs — key to skill 3.2.4, 'deploy patches in an automated way with continuous validation.'",
  },
  {
    tag: "Secure administrative access",
    q: "You want to give engineers shell access to EC2 instances in private subnets without opening port 22, without managing SSH keys, and with the entire session audited in CloudTrail. What do you use?",
    options: [
      "EC2 Instance Connect with a public IP",
      "A traditional bastion host with a NAT Gateway",
      "AWS Systems Manager Session Manager",
      "Temporarily disable the Security Group",
    ],
    correct: 2,
    explain: "Session Manager establishes the session through the outbound SSM agent (HTTPS), with no need to open inbound ports, bastion hosts, or distribute SSH keys — and every command is audited (CloudTrail + optional logs to S3/CloudWatch). EC2 Instance Connect is the alternative for ephemeral SSH but DOES require port 22 to be reachable (even if restricted to a controlled range).",
  },
  {
    tag: "Pipeline security",
    q: "Which AWS tool is designed to analyze source code and detect security vulnerabilities (e.g. injection, hardcoded secrets) WITHIN the CI/CD pipeline, before deployment?",
    options: [
      "Amazon GuardDuty",
      "Amazon Detective",
      "AWS Config",
      "Amazon CodeGuru Security (with Amazon Q Developer for AI-assisted suggestions/remediation)",
    ],
    correct: 3,
    explain: "CodeGuru Security statically analyzes source code for vulnerabilities (similar to SAST — Static Application Security Testing) and hardcoded secrets, and can be integrated into the CI/CD pipeline. Amazon Q Developer complements it with AI-assisted remediation suggestions. GuardDuty and Detective operate on the running account, not on source code.",
  },
  {
    tag: "GenAI guardrails",
    q: "You're building an application with an LLM that responds to end users, and you need to protect it against prompt injection and leakage of sensitive data in the responses. Which framework is explicitly mentioned in the SCS-C03 exam guide for this type of protection?",
    options: [
      "OWASP Top 10 for LLM Applications",
      "PCI-DSS",
      "Standard CIS Benchmarks",
      "NIST 800-53 exclusively",
    ],
    correct: 0,
    explain: "The OWASP Top 10 for LLM Applications catalogs risks specific to applications built on language models (prompt injection, leakage of sensitive data, training data poisoning, etc.) — an explicit new skill in SCS-C03 (3.2.7), reflecting the adoption of GenAI in production workloads.",
  },
  {
    tag: "Hybrid connectivity",
    q: "What differentiates AWS Direct Connect from an AWS Site-to-Site VPN?",
    options: [
      "They are identical in performance and cost",
      "Direct Connect is a dedicated, private network connection (via a partner or directly) that does NOT cross the public Internet, with predictable bandwidth; Site-to-Site VPN encrypts traffic but it still travels over the Internet",
      "Site-to-Site VPN requires physical hardware in your datacenter while Direct Connect does not",
      "Direct Connect cannot be combined with VPN",
    ],
    correct: 1,
    explain: "Direct Connect establishes a dedicated physical connection between your datacenter and AWS (via a DX location/partner), avoiding the public Internet — better latency/consistency, with no native encryption (added via MACsec or a VPN over DX). Site-to-Site VPN creates an encrypted IPsec tunnel over the Internet, faster to deploy but with less predictable performance.",
  },
  {
    tag: "MACsec",
    q: "What is MACsec (802.1AE) used for in the context of AWS Direct Connect?",
    options: [
      "To speed up the connection",
      "To completely replace Direct Connect",
      "To encrypt traffic at layer 2 (Ethernet) on high-speed dedicated Direct Connect connections, since Direct Connect by itself doesn't encrypt traffic",
      "It is a protocol exclusive to Site-to-Site VPN",
    ],
    correct: 2,
    explain: "Direct Connect doesn't natively encrypt traffic (it's a private connection, but not an encrypted one). MACsec adds link-layer (layer 2) encryption on dedicated 10/100 Gbps connections, meeting requirements where traffic confidentiality is mandatory even over an already-private connection.",
  },
  {
    tag: "Verified Access in hybrid setups",
    q: "Your company has internal applications that must be accessible both to employees in the office (on-premises network) and remotely, without exposing them to the Internet or relying on a full-network VPN. Which solution fits skill 3.3.3?",
    options: [
      "AWS Site-to-Site VPN alone",
      "AWS Direct Connect by itself",
      "Make all the apps public with WAF in front",
      "AWS Verified Access: evaluates identity (IAM Identity Center) and device posture on every request, granting application-level access without exposing a full network tunnel between on-premises and AWS",
    ],
    correct: 3,
    explain: "Verified Access implements Zero Trust Network Access (ZTNA): instead of connecting entire networks (like VPN or Direct Connect), it evaluates each request to a specific application based on identity and device posture, working equally well for office and remote users without exposing the app to the Internet.",
  },
  {
    tag: "Network segmentation",
    q: "In VPC design, what term describes traffic BETWEEN workloads within the same environment (e.g. between microservices in different private subnets), as opposed to traffic entering/leaving the perimeter?",
    options: [
      "East/west traffic",
      "North/south traffic",
      "Transit traffic",
      "Peering traffic",
    ],
    correct: 0,
    explain: "North/south is traffic that crosses the perimeter (Internet client ↔ your VPC). East/west is internal traffic between workloads (microservice A ↔ microservice B). Isolating and filtering east/west traffic (with layer-specific SGs, isolated subnets, internal Network Firewall) reduces the blast radius if a component is compromised — a core principle of skill 3.3.4.",
  },
  {
    tag: "AWS Network Firewall",
    q: "How does AWS Network Firewall differ from a Security Group or a NACL?",
    options: [
      "It's exactly the same thing under a different commercial name",
      "Network Firewall is a stateful firewall at the VPC/subnet level that supports layer 3-7 inspection (including domain-based rules and IDS/IPS-style signatures with Suricata), more advanced than the 5-tuple filtering of SG/NACL",
      "It can only be deployed in public subnets",
      "It doesn't support domain-based (FQDN) rules",
    ],
    correct: 1,
    explain: "SG and NACL filter by IP/port/protocol (5-tuple). AWS Network Firewall adds deep packet inspection, domain rules (allow outbound only to *.mydomain.com), and Suricata-compatible signature rules (IDS/IPS) — designed for transit traffic between subnets or out to the Internet through a Gateway/Transit Gateway.",
  },
  {
    tag: "Detecting unnecessary access",
    q: "Which tool tells you whether an unintended reachable network path exists between two resources (e.g. an instance in a private subnet reachable from the Internet due to a misconfiguration chained across SG/NACL/route table)?",
    options: [
      "AWS Config Rules alone",
      "Amazon Macie",
      "Amazon Inspector Network Reachability (or VPC Network Access Analyzer)",
      "AWS Trusted Advisor exclusively",
    ],
    correct: 2,
    explain: "These tools model the entire network configuration (SGs, NACLs, route tables, peering, IGW/NAT) to determine whether a reachable path exists between a source and a destination that shouldn't exist — far more reliable than manually reviewing each component separately, exactly skill 3.3.5.",
  },
  {
    tag: "OCSF",
    q: "What is the Open Cybersecurity Schema Framework (OCSF) in the context of security integrations with AWS?",
    options: [
      "A paid AWS service for storing logs",
      "The successor to CloudTrail",
      "An encryption protocol",
      "An OPEN, standardized data schema for normalizing security events from different sources (AWS and third parties), enabling correlation without manually transforming each proprietary format",
    ],
    correct: 3,
    explain: "OCSF is an open standard (driven by AWS and others) for representing security events consistently across different products and vendors. Amazon Security Lake uses it as its native format, making it easier to integrate third-party sources without writing a separate parser for each one — part of skill 3.1.4 on edge integrations.",
  },
  {
    tag: "WAF Fraud Control – ATP",
    q: "Your security team detects a spike in login attempts using stolen credentials (credential stuffing) against your application's login endpoint, served behind CloudFront. Attackers are using email/password pairs leaked in other breaches, and many succeed because users reuse passwords. Which AWS WAF Fraud Control component specifically addresses this use case?",
    options: [
      "Account Takeover Prevention (ATP)",
      "AWS WAF Bot Control, to block known bots",
      "A generic rate-based rule with no further configuration",
      "Account Creation Fraud Prevention (ACFP), designed for registration pages",
    ],
    correct: 0,
    explain: "ATP specifically protects login pages: it inspects the submitted credentials and compares them against a database of known compromised credentials (updated continuously), in addition to applying anomalous-behavior heuristics. ACFP (option D) is the sibling component for account REGISTRATION/creation pages, not login — it does not address credential stuffing against an existing login.",
  },
  {
    tag: "WAF Fraud Control – ACFP",
    q: "An application with public registration suffers waves of fake accounts created by bots, later used for promo abuse (welcome-coupon fraud). Which AWS WAF protection is designed for this scenario?",
    options: [
      "Account Takeover Prevention (ATP), designed for the login endpoint",
      "Account Creation Fraud Prevention (ACFP), which continuously monitors requests to the registration/sign-up endpoint and automatically blocks suspicious requests based on request identifiers and behavioral analysis",
      "CloudFront Geo Restriction",
      "Shield Advanced, layer 3/4 mitigation",
    ],
    correct: 1,
    explain: "ACFP specifically protects account-creation pages: it analyzes behavioral patterns and request signals (device fingerprint, repeated reuse of identifiers) to block mass registration fraud, distinct from login abuse (ATP) or network-layer DDoS mitigation (Shield).",
  },
  {
    tag: "WAF CAPTCHA vs Challenge",
    q: "You want to slow down a simple bot scraping your product catalog without degrading the experience of real users (you don't want to make them solve a visible puzzle). Which AWS WAF rule action is most appropriate?",
    options: [
      "CAPTCHA, which always asks the user to solve a visible puzzle",
      "Directly block all suspicious IPs with no verification",
      "Challenge: runs a silent background check (confirms the client is a real browser) with no visible interaction from the user, and only escalates to block or CAPTCHA if it fails",
      "Count, which blocks nothing and only records metrics",
    ],
    correct: 2,
    explain: "Challenge performs a silent check (based on an encrypted token, the aws-waf-token cookie) that verifies the client executes JavaScript like a real browser, without asking the user anything — ideal for filtering out simple bots with no friction. CAPTCHA requires solving a visible puzzle, more intrusive, reserved for more persistent threats.",
  },
  {
    tag: "WAF Bot Control",
    q: "You need to distinguish between known 'good' bots (like legitimate search engine crawlers) and malicious/uncategorized bots on your web application, including the ability to define protections against bots specifically targeting your business (e.g. inventory scalping bots). Which AWS WAF managed rule group fits?",
    options: [
      "AWS Managed Rules — Core rule set (CRS), designed for the OWASP Top 10",
      "Amazon Inspector",
      "Shield Advanced Anti-DDoS managed rule group",
      "AWS WAF Bot Control, with its Targeted mode (Targeted Bot Control) for sophisticated bots customized per business domain, in addition to categorizing known bot traffic (good/verified) versus uncategorized",
    ],
    correct: 3,
    explain: "Bot Control classifies automated traffic (verified search engines, monitors, malicious bots), and its 'Targeted' tier uses machine learning and domain-specific fingerprinting to detect sophisticated bots purpose-built against your application (scalping, advanced scraping) — more granular than the CRS's generic signature rules.",
  },
  {
    tag: "Shield Advanced + Anti-DDoS rule group",
    q: "Your organization uses Shield Advanced on a CloudFront distribution with AWS WAF. After the adoption of the new AWS WAF Anti-DDoS managed rule group as Shield Advanced's default application-layer protection, what changes about billing during an actively mitigated layer 7 DDoS attack?",
    options: [
      "Requests blocked by active DDoS mitigation are excluded from your monthly request count (WAF, Anti-DDoS managed rule group, and Shield Advanced), preventing attack traffic from inflating the bill",
      "You're charged double during active mitigation for the additional resource usage",
      "There's no change in billing; it's charged the same as legitimate traffic",
      "Shield Advanced stops billing entirely for the duration of any attack",
    ],
    correct: 0,
    explain: "The new Anti-DDoS managed rule group (which replaces the previous layer-7 protection while using fewer WCUs) excludes traffic blocked during an active DDoS mitigation from the billable request count — so the volume of the attack doesn't translate into a disproportionate cost for the customer.",
  },
  {
    tag: "Network Firewall TLS Inspection",
    q: "You need AWS Network Firewall to inspect the content of outbound HTTPS connections from your VPC (not just the SNI) in order to apply IDS/IPS-style signature rules against the decrypted traffic. What do you need to configure?",
    options: [
      "Nothing extra: Network Firewall natively inspects the encrypted HTTPS payload with no configuration",
      "A TLS Inspection Configuration",
      "Enable only domain-based (FQDN) rules, which don't require decryption",
      "Replace Network Firewall with AWS WAF, which does natively inspect TLS",
    ],
    correct: 1,
    explain: "By default, a stateful firewall can only inspect TLS metadata (like the SNI) because the payload is encrypted. For deep HTTPS inspection, Network Firewall supports a TLS Inspection Configuration that acts as a TLS proxy: it decrypts with managed certificates (self-managed or via ACM/KMS), applies signature/domain rules to the plaintext traffic, and re-encrypts before sending it to the destination — available for both ingress and egress inspection.",
  },
  {
    tag: "Inspector Code Security",
    q: "Your development team wants to detect security vulnerabilities (and Infrastructure as Code misconfigurations) directly in GitHub pull requests, before code is merged, without relying solely on a later scan in production. Which Amazon Inspector capability covers this?",
    options: [
      "Inspector Network Reachability, which analyzes network paths",
      "Amazon Inspector can only scan images already published to ECR, never source code",
      "Amazon Inspector Code Security",
      "Amazon CodeGuru Reviewer, which replaced Inspector in 2025",
    ],
    correct: 2,
    explain: "With the launch of Inspector Code Security (2025), Inspector extends its scope beyond EC2/ECR/Lambda into source code: native integration with GitHub and GitLab to analyze vulnerabilities, dependencies, and IaC at commit/PR time or in CI/CD, with direct feedback in the source control platform — complementing (not replacing) CodeGuru Security.",
  },
  {
    tag: "Inspector organization-wide management",
    q: "As the delegated security administrator in AWS Organizations, you want to centrally enable and configure which Amazon Inspector scan types (for example, Lambda Code Scanning or Code Security) are automatically applied across all accounts in certain organizational units (OUs), without configuring it account by account. What mechanism do you use?",
    options: [
      "A Service Control Policy (SCP) that blocks disabling Inspector",
      "You have to enable it manually in each member account; there is no centralized management",
      "AWS Config conformance packs alone",
      "Amazon Inspector management through AWS Organizations policies",
    ],
    correct: 3,
    explain: "Amazon Inspector added support for centralized management via AWS Organizations policies, letting a delegated administrator define which scans (Lambda, EC2, ECR, Code Security) are enabled by default across the whole organization or in specific OUs, removing the need to enable it account by account.",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "GuardDuty generates multiple, seemingly unrelated low-severity findings about an EC2 instance and a related ECS task (unusual credential access, then a suspicious network connection shortly after). Which GuardDuty capability is designed to correlate this sequence and elevate it into a single critical 'attack in progress' finding?",
    options: [
      "Extended Threat Detection: correlates multiple signals and events over time (across EC2, ECS, EKS, S3, IAM, etc.) to identify multi-stage attack sequences, generating a critical-severity finding when it detects a pattern of an in-progress compromise",
      "GuardDuty Malware Protection, which only scans EBS volumes",
      "Amazon Detective, which replaces GuardDuty",
      "AWS Config Rules",
    ],
    correct: 0,
    explain: "Extended Threat Detection (expanded to EC2 and ECS) uses correlation models to connect individual low-risk findings spread over time and across different resources, identifying sequences that together indicate an active multi-stage attack — reducing alert noise and prioritizing what actually matters to investigate.",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "GuardDuty detects suspicious activity on an EC2 instance (for example, communication with a known command-and-control domain). What does GuardDuty Malware Protection for EC2 automatically do from there, and what impact does it have on the running instance?",
    options: [
      "It immediately terminates the instance to contain the threat",
      "It performs an agentless scan of the attached EBS volumes (from a snapshot) for known malware, with NO need to install an agent and NO impact on the running instance's performance",
      "It requires installing the Inspector agent on the instance before it can scan anything",
      "It only works if the instance is stopped",
    ],
    correct: 1,
    explain: "Malware Protection for EC2 is triggered automatically when GuardDuty detects a suspicious finding, and it scans the associated EBS volumes from a snapshot (an agentless process) to look for known malware — without installing anything on the instance or affecting its performance or availability while the scan runs.",
  },
  {
    tag: "VPC Route Server",
    q: "You have third-party virtual network appliances (NVA firewalls) deployed in your VPC that need to dynamically advertise routes into the subnets' route tables, without maintaining custom scripts or an overlay network to sync the changes. Which AWS service natively solves this?",
    options: [
      "AWS Transit Gateway exclusively",
      "AWS Network Firewall, which manages routes automatically",
      "Amazon VPC Route Server: lets NVAs advertise routes via BGP, and dynamically updates the route tables of the associated subnets and Internet Gateway, removing the need for custom scripts or overlay networks",
      "Route 53 Resolver",
    ],
    correct: 2,
    explain: "VPC Route Server (GA April 2025) introduces native dynamic routing inside a VPC: NVAs advertise routes over BGP to the Route Server, which in turn automatically updates the route tables of subscribed subnets and Internet Gateways — previously this required custom automation (Lambda + route table APIs) or complex overlay topologies.",
  },
  {
    tag: "Verified Access non-HTTP(S)",
    q: "Beyond internal web applications, your team needs to grant Zero Trust access (evaluating identity and device posture) to databases and to SSH/RDP sessions on EC2 instances, without deploying a full-network VPN. Which recent AWS Verified Access capability enables this?",
    options: [
      "Verified Access only supports HTTP(S) traffic; SSH/RDP requires Site-to-Site VPN",
      "It's only possible via a dedicated Direct Connect",
      "Those workloads must move to AWS Client VPN, the only service with SSH/RDP support",
      "Verified Access support for non-HTTP(S) protocols (generic TCP, including SSH and RDP)",
    ],
    correct: 3,
    explain: "Since its general availability (GA, February 2025), Verified Access extends the Zero Trust model beyond HTTP(S) to generic TCP protocols like SSH and RDP, letting you centralize access policies (identity + device posture) for databases, code repositories, or administrative access to EC2 — without managing SSH credentials or exposing a full network tunnel.",
  },
  {
    tag: "Security Group Referencing (Transit Gateway)",
    q: "You have two VPCs connected via AWS Transit Gateway (not direct peering), and you want to allow traffic between instances in one VPC and the other by directly referencing the source Security Group in the inbound rule of the destination Security Group (instead of using CIDR ranges). Is this possible?",
    options: [
      "Yes: AWS announced general availability of Security Group Referencing over Transit Gateway, allowing you to specify security groups from other VPCs connected via TGW as source/destination in rules, without relying on static CIDR ranges",
      "No, Security Group referencing across VPCs only works with direct VPC Peering, never over Transit Gateway",
      "Only if both VPCs are in the same AWS account",
      "It only works for UDP traffic",
    ],
    correct: 0,
    explain: "Before this capability (GA September 2024), cross-VPC Security Group referencing was only supported over VPC Peering; traffic through Transit Gateway forced you to use CIDR ranges (more fragile and harder to maintain at scale). Now you can also reference the Security Group of a remote VPC connected via TGW, simplifying east-west segmentation in hub-and-spoke topologies.",
  },
  {
    tag: "ECR Image Signing",
    q: "You want to guarantee that only container images that genuinely came from your authorized CI/CD pipeline can be deployed to your cluster, protecting the software supply chain against tampered or unverified images. Which Amazon ECR capability helps with this?",
    options: [
      "ECR pull-through cache, which only caches images from public registries",
      "ECR managed image signing, integrated with AWS Signer",
      "Enabling enhanced vulnerability scanning — that already guarantees provenance",
      "It's a feature exclusive to Docker Hub, not ECR",
    ],
    correct: 1,
    explain: "ECR managed image signing uses AWS Signer to automatically sign each image on push, generating a verifiable proof of provenance. Combined with signature validation at deploy time (e.g. in the cluster), it prevents running tampered or unknown-origin images — vulnerability scanning (enhanced scanning) is a distinct, complementary control that does not guarantee provenance.",
  },
  {
    tag: "Declarative Policies (IMDSv2)",
    q: "You want to guarantee, across your entire AWS Organizations organization, that NO new EC2 instance can be launched with IMDSv1 enabled (mitigating the SSRF vector), so that the configuration stays enforced even as new accounts are added or AWS introduces new EC2 APIs. What mechanism do you use, as opposed to a traditional SCP?",
    options: [
      "A Service Control Policy (SCP) that denies the RunInstances action unless IMDSv2 is specified",
      "AWS Config with automatic remediation, which reverts the instance after it's created",
      "An AWS Organizations Declarative Policy for EC2",
      "Manually tagging every instance as 'IMDSv2-only'",
    ],
    correct: 2,
    explain: "Declarative Policies (GA December 2024) are an Organizations policy type distinct from SCPs: instead of denying API actions, they declare the desired STATE of a configuration (e.g. 'IMDSv2 required' for EC2), and AWS ensures that state is maintained centrally and resiliently against future service changes — more robust than maintaining a complex SCP or relying on reactive post-creation remediation.",
  },
  {
    tag: "VPC Lattice Auth Policies",
    q: "You're designing a microservices mesh spanning multiple AWS VPCs and accounts, and you want to control which specific service can invoke which other service and with which HTTP method, using identity (SigV4/IAM) rather than just IP addresses — independently of the Security Groups managed by the network team. Which VPC Lattice mechanism applies?",
    options: [
      "Each VPC's Network ACLs, which already control this by IP",
      "A NAT Gateway shared across accounts",
      "AWS Verified Access, which replaces VPC Lattice for this case",
      "VPC Lattice Auth Policies: IAM-style policy documents attached at the service network or individual service level, which authorize (or deny) a specific principal's access to particular routes/methods — complementary to, not a replacement for, Security Groups",
    ],
    correct: 3,
    explain: "VPC Lattice introduces identity-based authorization (IAM-style auth policies) at the service network or individual service level, letting you define which principal (role/service) can invoke which operation — separating 'which service can call which' (application team) from 'which IP can reach the network' (network/Security Group team). For authorization to succeed, both the Lattice auth policy and the IAM identity policy must explicitly allow access.",
  },
  {
    tag: "Route 53 Resolver DNS Firewall Advanced",
    q: "You suspect a compromised host inside your VPC is using a Domain Generation Algorithm (DGA) to generate pseudo-random domain names and communicate with command-and-control (C2) infrastructure, evading static domain blocklists. Which AWS service detects this specific pattern in real time?",
    options: [
      "Route 53 Resolver DNS Firewall Advanced",
      "Route 53 Resolver DNS Firewall (the standard tier, based only on domain lists)",
      "AWS Network Firewall with domain (FQDN) rules only",
      "Amazon GuardDuty, which automatically blocks the traffic",
    ],
    correct: 0,
    explain: "DNS Firewall Advanced (launched in 2024, with additional dictionary-based DGA protection added in 2025) goes beyond static domain-list filtering: it analyzes the characteristics of queried domain names in real time to identify the typical patterns of DGA and DNS tunneling, threats specifically designed to evade known-list-based blocking. GuardDuty can DETECT and generate findings about suspicious DNS activity, but it does not block DNS traffic itself — that's DNS Firewall's job.",
  },
  {
    tag: "PrivateLink endpoint policies",
    q: "Your team created an interface VPC endpoint to Amazon S3 so instances in a private subnet can reach S3 without going out to the Internet. You want to ensure that, through THAT specific endpoint, only one particular bucket can be accessed, regardless of the IAM permissions each role has. What mechanism do you use?",
    options: [
      "Modify the endpoint's Security Group to filter by bucket name",
      "An Endpoint Policy: a resource policy (in IAM language, with a Principal element) attached to the VPC endpoint that restricts which actions and which resources are accessible THROUGH that specific endpoint — an additional control layer, not a replacement for IAM policies or the bucket policy",
      "A NACL in the subnet where the endpoint lives",
      "It's not possible; every endpoint grants full access to the service",
    ],
    correct: 1,
    explain: "An interface endpoint's Security Group only controls network-level access (what can connect to the endpoint's ENI, by IP/port) — it has no concept of S3 buckets. The Endpoint Policy is an IAM-format resource policy attached to the endpoint that explicitly limits which principals can perform which actions on which resources using THAT specific endpoint, acting as an additional layer of control alongside (not instead of) IAM identity policies and the resource's bucket policy.",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "You are designing a VPC's network controls. Which TWO statements about security groups and network ACLs are correct?",
    options: [
      "Security groups are stateful: return traffic is automatically allowed even with no outbound rule",
      "Network ACLs are stateless and support explicit Deny rules, evaluated by rule number",
      "Security groups support explicit Deny rules to block specific IPs",
      "Network ACLs apply to the instance's network interface, not to the subnet",
    ],
    correct: [0, 1],
    explain: "This is the domain's most-asked comparison. <b>SGs are stateful</b> (allow-only, return traffic automatic) and attach to the ENI; <b>NACLs are stateless</b> (allow and deny, evaluated in rule-number order, and return traffic must be opened explicitly, typically the ephemeral ports) and attach to the subnet. That's why blocking a specific IP is a NACL job, not a security group one.",
  },
  {
    tag: "Protecting a public web app",
    q: "A web application behind CloudFront is hit by SQL injection and a volumetric layer 3/4 attack. Which TWO services directly address these threats?",
    options: [
      "AWS WAF with the appropriate managed rule groups, for the SQL injection",
      "AWS Shield, for mitigating the volumetric layer 3/4 attack",
      "Amazon Inspector, which blocks malicious requests in real time",
      "AWS Config, which prevents requests with suspicious payloads from arriving",
    ],
    correct: [0, 1],
    explain: "<b>WAF</b> inspects at layer 7 and stops SQLi/XSS with managed rules; <b>Shield</b> mitigates volumetric DDoS at layers 3/4 (Standard is included, Advanced adds protection and managed response). Inspector assesses <i>vulnerabilities</i> in instances, containers and Lambda: it doesn't filter traffic. Config evaluates resource <i>configuration</i>: also not in the request path. Telling apart what sits inline with traffic and what doesn't is key.",
  },
  {
    tag: "Admin access without exposed SSH",
    q: "Security forbids opening port 22 to the internet and wants to eliminate bastion hosts, but operators need shell access to EC2 instances in private subnets. Which TWO enable this?",
    options: [
      "AWS Systems Manager Session Manager, which opens the session with no inbound ports",
      "The SSM Agent installed on the instance and an instance profile with Systems Manager permissions",
      "A security group rule allowing port 22 from the corporate IP range",
      "An Elastic IP on each instance so Systems Manager can reach it",
    ],
    correct: [0, 1],
    explain: "<b>Session Manager</b> works over an <i>outbound</i> connection from the agent to the service, so it needs no inbound ports, no public IP and no bastion — and it logs the session to CloudTrail/S3/CloudWatch. It needs both pieces: the <b>agent</b> and <b>permissions via an instance profile</b>. Opening port 22, even to a corporate range, is exactly what's being eliminated, and an Elastic IP would expose the instance rather than protect it.",
  },
  {
    tag: "Hardened base images",
    q: "The company wants every EC2 instance to boot from hardened, patched images. Which TWO services fit that chain?",
    options: [
      "EC2 Image Builder, to build and version hardened AMIs repeatably",
      "Amazon Inspector, to detect known vulnerabilities in the images and instances",
      "AWS Shield Advanced, to validate that the AMI contains no malware",
      "Amazon Macie, to scan the AMI's operating system for CVEs",
    ],
    correct: [0, 1],
    explain: "<b>Image Builder</b> automates building, hardening and versioning AMIs, and <b>Inspector</b> continuously assesses them against known CVEs. Shield is purely anti-DDoS. Macie discovers and classifies <b>sensitive data in S3</b> — it doesn't analyze operating systems: mistaking Macie for a vulnerability scanner is a recurring distractor.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["infrastructure-security"] = QUIZ_DATA;
