const QUIZ_DATA = [
  {
    tag: "Security Groups vs NACLs",
    q: "What is the MOST important behavioral difference between a Security Group and a Network ACL?",
    options: [
      "The Security Group operates at the subnet level and the NACL at the instance level",
      "The Security Group is STATEFUL (return traffic is allowed automatically) and only supports Allow rules; the NACL is STATELESS (both directions must be explicitly allowed) and supports Allow and Deny rules evaluated in numeric order",
      "Both are identical, only where they're configured in the console differs",
      "The NACL only filters HTTP/HTTPS traffic",
    ],
    correct: 1,
    explain: "Security Group = stateful, at the ENI/instance level, Allow only (anything not permitted is implicitly denied). NACL = stateless, at the subnet level, with numbered rules evaluated in order that can be Allow or Deny — that's why you have to explicitly open return traffic (ephemeral ports).",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "You detect repeated malicious traffic from a specific IP and want to block it immediately at the network level, without relying on any instance's rules to allow it. What mechanism do you use?",
    options: [
      "A Deny rule in the subnet's Network ACL (Security Groups can't explicitly deny an IP)",
      "Add the IP to a Security Group with Deny",
      "Modify the subnet's route table",
      "Enable GuardDuty",
    ],
    correct: 0,
    explain: "Security Groups do NOT have Deny rules — you can only specify what's allowed. To explicitly block a specific IP at the network level (regardless of which Security Group each instance has), you need a Deny rule in the subnet's NACL, evaluated before traffic reaches the instance.",
  },
  {
    tag: "AWS WAF",
    q: "What type of attack is a 'rate-based rule' in AWS WAF designed to detect and block?",
    options: [
      "SQL injection only",
      "An anomalously high volume of requests from the same IP (or aggregation key) within a time window — for example, login brute-forcing or aggressive scraping",
      "Attacks that already passed through CloudFront",
      "UDP traffic only",
    ],
    correct: 1,
    explain: "WAF rate-based rules count requests by aggregation key (source IP by default, or a custom combination) in sliding 5- or 10-minute windows, and block automatically once the threshold is exceeded — ideal against brute force, credential stuffing, or scraping, complementary to signature rules (SQLi, XSS from the OWASP Top 10).",
  },
  {
    tag: "Shield Advanced",
    q: "What does AWS Shield Advanced add on top of the standard DDoS protection (Shield Standard) that comes free with every account?",
    options: [
      "Nothing, Shield Standard already covers all cases",
      "Advanced protection against more sophisticated layer 3/4 and layer 7 attacks, access to the DDoS Response Team (DRT), cost reimbursement for scaling spikes during an attack, and detailed visibility/metrics — paid, per account or per resource",
      "It only protects Route 53, not CloudFront or ALB",
      "Shield Advanced completely replaces WAF",
    ],
    correct: 1,
    explain: "Shield Standard (free, automatic) covers the most common layer 3/4 DDoS attacks. Shield Advanced adds extended protection, the DDoS Response Team available 24/7, cost protection (credits if you scale due to an attack), and integrates with WAF for layer 7 mitigation — recommended for critical workloads with an availability SLA.",
  },
  {
    tag: "Edge security",
    q: "You want to block access to your CloudFront-distributed application from every country except Spain and Portugal. What mechanism do you use?",
    options: [
      "A Security Group with per-country rules",
      "CloudFront Geo Restriction (country allowlist) or a geo-match rule in AWS WAF associated with the distribution",
      "A NACL with per-country CIDR ranges",
      "Route 53 Resolver DNS Firewall",
    ],
    correct: 1,
    explain: "CloudFront Geo Restriction allows an allowlist/blocklist of countries directly on the distribution. Alternatively, a geo-match rule in WAF (associated with CloudFront) offers the same capability with more flexibility to combine it with other conditions (rate limiting, fingerprinting).",
  },
  {
    tag: "S3 CORS",
    q: "Your SPA at https://app.mydomain.com needs to make fetch() requests directly to an S3 bucket to upload files, and the browser blocks them with a CORS error. What do you configure?",
    options: [
      "A bucket policy that allows the Principal '*'",
      "A CORS configuration on the S3 bucket that explicitly allows the origin https://app.mydomain.com and the necessary methods/headers",
      "Disable HTTPS on the bucket",
      "A Security Group on the bucket",
    ],
    correct: 1,
    explain: "CORS (Cross-Origin Resource Sharing) is a BROWSER restriction, not an AWS one. S3 supports its own CORS configuration (AllowedOrigins, AllowedMethods, AllowedHeaders) that tells the browser that a given origin is permitted to make cross-origin requests to the bucket — independent of the bucket policy or IAM permissions.",
  },
  {
    tag: "Hardened AMIs",
    q: "Which AWS service is specifically designed to build, maintain, and validate hardened AMIs (or container images) in an automated, repeatable way?",
    options: [
      "AWS Config",
      "EC2 Image Builder: an automated pipeline that applies hardening (e.g. CIS benchmarks), installs patches, and runs validation tests before publishing the AMI",
      "AWS Backup",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "EC2 Image Builder automates the entire pipeline: starting from a base image, applying hardening/configuration components, installing updates, running tests, and publishing the resulting AMI (or container image) — eliminating the manual process and guaranteeing reproducibility between versions.",
  },
  {
    tag: "Instance profiles vs roles",
    q: "What is the relationship between an EC2 'Instance Profile' and an IAM Role?",
    options: [
      "They are exact synonyms; either term can be used interchangeably in the API",
      "The Instance Profile is the CONTAINER that associates an IAM Role with an EC2 instance — it's what actually gets attached to the instance (the console hides this by creating it automatically when you 'assign a role')",
      "An Instance Profile can contain multiple IAM Roles simultaneously",
      "The Instance Profile removes the need for an IAM Role",
    ],
    correct: 1,
    explain: "Technically, you don't attach an IAM Role directly to an EC2 instance: you attach an Instance Profile, which in turn references a SINGLE IAM Role. The AWS console hides this distinction by creating the Instance Profile automatically, but the CLI/API exposes it (aws iam create-instance-profile + add-role-to-instance-profile).",
  },
  {
    tag: "Amazon Inspector",
    q: "What types of resources can Amazon Inspector scan for known vulnerabilities (CVEs)?",
    options: [
      "EC2 instances only",
      "EC2 instances, container images in Amazon ECR, and Lambda functions (code and layers) — continuously, not just on demand",
      "RDS databases only",
      "S3 buckets only",
    ],
    correct: 1,
    explain: "Amazon Inspector continuously and automatically scans EC2 (OS packages and network vulnerabilities), container images in ECR (on push and periodically), and Lambda functions (dependencies in the code). GuardDuty, by contrast, monitors RUNTIME behavior (real-time anomalous activity), not known static vulnerabilities.",
  },
  {
    tag: "Patch management",
    q: "Which Systems Manager component automates applying OS security patches across a fleet of EC2 instances, according to a scheduled maintenance window?",
    options: [
      "Systems Manager Session Manager",
      "Systems Manager Patch Manager, typically orchestrated with Maintenance Windows",
      "Systems Manager Parameter Store",
      "AWS Config",
    ],
    correct: 1,
    explain: "Patch Manager automates scanning and applying patches (OS and some applications) according to configurable approval baselines, run within Maintenance Windows to control when the impact occurs — key to skill 3.2.4, 'deploy patches in an automated way with continuous validation.'",
  },
  {
    tag: "Secure administrative access",
    q: "You want to give engineers shell access to EC2 instances in private subnets without opening port 22, without managing SSH keys, and with the entire session audited in CloudTrail. What do you use?",
    options: [
      "EC2 Instance Connect with a public IP",
      "AWS Systems Manager Session Manager: creates a tunnel through the SSM agent, with no need for an open port 22, a bastion host, or SSH keys, and logs every command executed",
      "A traditional bastion host with a NAT Gateway",
      "Temporarily disable the Security Group",
    ],
    correct: 1,
    explain: "Session Manager establishes the session through the outbound SSM agent (HTTPS), with no need to open inbound ports, bastion hosts, or distribute SSH keys — and every command is audited (CloudTrail + optional logs to S3/CloudWatch). EC2 Instance Connect is the alternative for ephemeral SSH but DOES require port 22 to be reachable (even if restricted to a controlled range).",
  },
  {
    tag: "Pipeline security",
    q: "Which AWS tool is designed to analyze source code and detect security vulnerabilities (e.g. injection, hardcoded secrets) WITHIN the CI/CD pipeline, before deployment?",
    options: [
      "Amazon GuardDuty",
      "Amazon CodeGuru Security (with Amazon Q Developer for AI-assisted suggestions/remediation)",
      "AWS Config",
      "Amazon Detective",
    ],
    correct: 1,
    explain: "CodeGuru Security statically analyzes source code for vulnerabilities (similar to SAST — Static Application Security Testing) and hardcoded secrets, and can be integrated into the CI/CD pipeline. Amazon Q Developer complements it with AI-assisted remediation suggestions. GuardDuty and Detective operate on the running account, not on source code.",
  },
  {
    tag: "GenAI guardrails",
    q: "You're building an application with an LLM that responds to end users, and you need to protect it against prompt injection and leakage of sensitive data in the responses. Which framework is explicitly mentioned in the SCS-C03 exam guide for this type of protection?",
    options: [
      "PCI-DSS",
      "OWASP Top 10 for LLM Applications",
      "Standard CIS Benchmarks",
      "NIST 800-53 exclusively",
    ],
    correct: 1,
    explain: "The OWASP Top 10 for LLM Applications catalogs risks specific to applications built on language models (prompt injection, leakage of sensitive data, training data poisoning, etc.) — an explicit new skill in SCS-C03 (3.2.7), reflecting the adoption of GenAI in production workloads.",
  },
  {
    tag: "Hybrid connectivity",
    q: "What differentiates AWS Direct Connect from an AWS Site-to-Site VPN?",
    options: [
      "They are identical in performance and cost",
      "Direct Connect is a dedicated, private network connection (via a partner or directly) that does NOT cross the public Internet, with predictable bandwidth; Site-to-Site VPN encrypts traffic but it still travels over the Internet",
      "Site-to-Site VPN requires physical hardware in your datacenter while Direct Connect does not",
      "Direct Connect cannot be combined with VPN",
    ],
    correct: 1,
    explain: "Direct Connect establishes a dedicated physical connection between your datacenter and AWS (via a DX location/partner), avoiding the public Internet — better latency/consistency, with no native encryption (added via MACsec or a VPN over DX). Site-to-Site VPN creates an encrypted IPsec tunnel over the Internet, faster to deploy but with less predictable performance.",
  },
  {
    tag: "MACsec",
    q: "What is MACsec (802.1AE) used for in the context of AWS Direct Connect?",
    options: [
      "To speed up the connection",
      "To encrypt traffic at layer 2 (Ethernet) on high-speed dedicated Direct Connect connections, since Direct Connect by itself doesn't encrypt traffic",
      "To completely replace Direct Connect",
      "It is a protocol exclusive to Site-to-Site VPN",
    ],
    correct: 1,
    explain: "Direct Connect doesn't natively encrypt traffic (it's a private connection, but not an encrypted one). MACsec adds link-layer (layer 2) encryption on dedicated 10/100 Gbps connections, meeting requirements where traffic confidentiality is mandatory even over an already-private connection.",
  },
  {
    tag: "Verified Access in hybrid setups",
    q: "Your company has internal applications that must be accessible both to employees in the office (on-premises network) and remotely, without exposing them to the Internet or relying on a full-network VPN. Which solution fits skill 3.3.3?",
    options: [
      "AWS Site-to-Site VPN alone",
      "AWS Verified Access: evaluates identity (IAM Identity Center) and device posture on every request, granting application-level access without exposing a full network tunnel between on-premises and AWS",
      "Make all the apps public with WAF in front",
      "AWS Direct Connect by itself",
    ],
    correct: 1,
    explain: "Verified Access implements Zero Trust Network Access (ZTNA): instead of connecting entire networks (like VPN or Direct Connect), it evaluates each request to a specific application based on identity and device posture, working equally well for office and remote users without exposing the app to the Internet.",
  },
  {
    tag: "Network segmentation",
    q: "In VPC design, what term describes traffic BETWEEN workloads within the same environment (e.g. between microservices in different private subnets), as opposed to traffic entering/leaving the perimeter?",
    options: [
      "North/south traffic",
      "East/west traffic",
      "Transit traffic",
      "Peering traffic",
    ],
    correct: 1,
    explain: "North/south is traffic that crosses the perimeter (Internet client ↔ your VPC). East/west is internal traffic between workloads (microservice A ↔ microservice B). Isolating and filtering east/west traffic (with layer-specific SGs, isolated subnets, internal Network Firewall) reduces the blast radius if a component is compromised — a core principle of skill 3.3.4.",
  },
  {
    tag: "AWS Network Firewall",
    q: "How does AWS Network Firewall differ from a Security Group or a NACL?",
    options: [
      "It's exactly the same thing under a different commercial name",
      "Network Firewall is a stateful firewall at the VPC/subnet level that supports layer 3-7 inspection (including domain-based rules and IDS/IPS-style signatures with Suricata), more advanced than the 5-tuple filtering of SG/NACL",
      "It can only be deployed in public subnets",
      "It doesn't support domain-based (FQDN) rules",
    ],
    correct: 1,
    explain: "SG and NACL filter by IP/port/protocol (5-tuple). AWS Network Firewall adds deep packet inspection, domain rules (allow outbound only to *.mydomain.com), and Suricata-compatible signature rules (IDS/IPS) — designed for transit traffic between subnets or out to the Internet through a Gateway/Transit Gateway.",
  },
  {
    tag: "Detecting unnecessary access",
    q: "Which tool tells you whether an unintended reachable network path exists between two resources (e.g. an instance in a private subnet reachable from the Internet due to a misconfiguration chained across SG/NACL/route table)?",
    options: [
      "AWS Config Rules alone",
      "Amazon Inspector Network Reachability (or VPC Network Access Analyzer) — analyzes the entire network configuration chain to detect unintended access paths",
      "Amazon Macie",
      "AWS Trusted Advisor exclusively",
    ],
    correct: 1,
    explain: "These tools model the entire network configuration (SGs, NACLs, route tables, peering, IGW/NAT) to determine whether a reachable path exists between a source and a destination that shouldn't exist — far more reliable than manually reviewing each component separately, exactly skill 3.3.5.",
  },
  {
    tag: "OCSF",
    q: "What is the Open Cybersecurity Schema Framework (OCSF) in the context of security integrations with AWS?",
    options: [
      "A paid AWS service for storing logs",
      "An OPEN, standardized data schema for normalizing security events from different sources (AWS and third parties), enabling correlation without manually transforming each proprietary format",
      "An encryption protocol",
      "The successor to CloudTrail",
    ],
    correct: 1,
    explain: "OCSF is an open standard (driven by AWS and others) for representing security events consistently across different products and vendors. Amazon Security Lake uses it as its native format, making it easier to integrate third-party sources without writing a separate parser for each one — part of skill 3.1.4 on edge integrations.",
  },
];
