var QUIZ_DATA = [
  {
    tag: "Security Groups vs NACLs",
    q: "What is the MOST important behavioral difference between a Security Group and a Network ACL?",
    options: [
      "The security group is stateful: return traffic is allowed, and its rules are Allow-only",
      "The security group applies to the whole subnet and the network ACL to each instance's ENI",
      "Both are stateless and evaluate their rules by number until the first match is found",
      "The network ACL is stateful, and it is the security group that must open ephemeral ports",
    ],
    correct: 0,
    explain: "<strong>Security group</strong>: stateful, at the ENI level, Allow rules only (anything not permitted is implicitly denied). <strong>Network ACL</strong>: stateless, at the subnet level, with numbered rules that can be Allow or Deny — which is why you must explicitly open return traffic on the ephemeral ports. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "You detect repeated malicious traffic from a specific IP and want to block it immediately at the network level, without relying on any instance's rules to allow it. What mechanism do you use?",
    options: [
      "Add a top-priority Deny rule for that source IP to the relevant security group",
      "A Deny rule in the subnet's network ACL, evaluated before traffic reaches the instance",
      "Remove the route toward that IP from the subnet's route table so the traffic is dropped",
      "Enable GuardDuty, which automatically blocks IPs with a malicious reputation",
    ],
    correct: 1,
    explain: "Security groups have <strong>no Deny rules</strong>: they only describe what is allowed. To block a specific IP regardless of which security group each instance carries, the tool is a Deny rule in the subnet's NACL, with a rule number lower than any Allow that would match it. GuardDuty <em>detects</em>, but it does not block traffic. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS WAF",
    q: "What type of attack is a 'rate-based rule' in AWS WAF designed to detect and block?",
    options: [
      "SQL injection, by matching every request against the OWASP Top 10 signatures",
      "Attacks that CloudFront has already let through to the distribution's origin",
      "An anomalous volume of requests from a single aggregation key",
      "Volumetric UDP traffic aimed at layer 3/4 of the protected resource",
    ],
    correct: 2,
    explain: "A rate-based rule counts requests per aggregation key (source IP by default, or a custom combination) inside an evaluation window of 60 to 600 seconds, and applies its action once the limit is exceeded. It targets brute force, credential stuffing and scraping; SQLi and XSS signatures are the job of managed rule groups. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Shield Advanced",
    q: "What does AWS Shield Advanced add on top of the standard DDoS protection (Shield Standard) that comes free with every account?",
    options: [
      "Nothing meaningful: Shield Standard already includes the response team and cost protection",
      "It replaces AWS WAF, since it folds the managed rule groups into the subscription itself",
      "It extends protection to Route 53 and Global Accelerator, but not to CloudFront or ALBs",
      "Advanced L3/4 and L7 mitigation, the response team (SRT), cost protection and metrics",
    ],
    correct: 3,
    explain: "Shield Standard is free and automatic, covering the most common layer 3/4 attacks. Shield Advanced is paid and adds advanced mitigation, access to the <strong>Shield Response Team</strong>, <em>cost protection</em> (credits when an attack forces you to scale), detailed metrics and diagnostics, and integration with WAF for layer 7. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/ddos-advanced-summary.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Edge security",
    q: "You want to block access to your CloudFront-distributed application from every country except Spain and Portugal. What mechanism do you use?",
    options: [
      "CloudFront Geo Restriction with a country allowlist, or a geo-match rule in AWS WAF",
      "A security group attached to the distribution with inbound rules per source country",
      "A network ACL on the distribution's subnet holding the CIDR ranges of each country",
      "Route 53 Resolver DNS Firewall, filtering DNS queries by the country of the request",
    ],
    correct: 0,
    explain: "Geo Restriction is configured on the distribution itself and accepts a country allowlist or blocklist. The alternative is a <code>geo-match</code> rule in a WAF web ACL, which lets you combine country with other conditions (rate limiting, specific paths). A CloudFront distribution does not live in a subnet, so neither security groups nor NACLs protect it. <a href=\"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/georestrictions.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 CORS",
    q: "Your SPA at https://app.mydomain.com needs to make fetch() requests directly to an S3 bucket to upload files, and the browser blocks them with a CORS error. What do you configure?",
    options: [
      "A bucket policy that allows the Principal '*' for all of the object upload actions",
      "A CORS configuration on the bucket with that origin and the allowed methods and headers",
      "A gateway VPC endpoint to S3, so that the request never leaves toward the public network",
      "A security group attached to the bucket allowing the client browser's public IP",
    ],
    correct: 1,
    explain: "CORS is a <strong>browser</strong> restriction, not an AWS authorization one: the request is rejected client-side even when IAM allows it. S3 has its own CORS configuration (<code>AllowedOrigins</code>, <code>AllowedMethods</code>, <code>AllowedHeaders</code>) with which the bucket declares which origins may call it. Opening the bucket policy fixes nothing, and buckets have no security groups. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Hardened AMIs",
    q: "Which AWS service is specifically designed to build, maintain, and validate hardened AMIs (or container images) in an automated, repeatable way?",
    options: [
      "AWS Config, which evaluates the AMI's configuration and fixes it before publication",
      "AWS Backup, which versions the base AMI and applies patches on every scheduled copy",
      "EC2 Image Builder, with pipelines that harden, patch and validate the image",
      "Amazon Macie, which analyzes the AMI's file system looking for known CVEs",
    ],
    correct: 2,
    explain: "EC2 Image Builder automates the whole pipeline: it starts from a base image, chains hardening components (CIS benchmarks, for example), installs updates, runs validation tests, and publishes the versioned AMI or container image. Config audits resource configuration, Backup handles copies, and Macie classifies sensitive data in S3. <a href=\"https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Instance profiles vs roles",
    q: "What is the relationship between an EC2 'Instance Profile' and an IAM Role?",
    options: [
      "They are exact synonyms: the IAM API accepts either term interchangeably",
      "The instance profile replaces the role and carries its own attached permission policies",
      "An instance profile can hold several roles and the instance picks one at boot time",
      "The instance profile is the container that binds a single IAM role to the instance",
    ],
    correct: 3,
    explain: "You never attach a role directly to an EC2 instance: you attach an <strong>instance profile</strong>, which references exactly <em>one</em> IAM role. The console hides this by creating the profile with the same name as the role, but the CLI exposes it (<code>create-instance-profile</code> + <code>add-role-to-instance-profile</code>). One role can sit in many profiles. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Inspector",
    q: "What types of resources can Amazon Inspector scan for known vulnerabilities (CVEs)?",
    options: [
      "EC2 instances, container images in Amazon ECR, and Lambda functions with their layers",
      "EC2 instances only, and only where the CloudWatch Logs agent has been installed",
      "RDS databases and Aurora clusters, looking for engine patches not yet applied",
      "S3 buckets, and additionally classifying the objects that hold sensitive personal data",
    ],
    correct: 0,
    explain: "Inspector continuously scans EC2 (operating-system packages and network reachability), ECR images (on push and periodically), and Lambda functions (code dependencies and layers). Scanning data in S3 is Macie's job, and GuardDuty watches runtime <em>behavior</em> rather than known vulnerabilities. <a href=\"https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Patch management",
    q: "Which Systems Manager component automates applying OS security patches across a fleet of EC2 instances, according to a scheduled maintenance window?",
    options: [
      "Session Manager, which opens a session on each node and runs the patch installer",
      "Patch Manager, orchestrated with maintenance windows or with a patch policy",
      "Parameter Store, which holds the list of approved patches for each group of nodes",
      "AWS Config, whose automatic remediation installs the patches missing on the node",
    ],
    correct: 1,
    explain: "Patch Manager scans and installs patches according to <strong>patch baselines</strong> with approval rules (by age, severity or explicit lists), and runs inside maintenance windows — or through an organization-wide patch policy — so you control when the impact happens. Parameter Store stores configuration and Config audits; neither patches anything. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Secure administrative access",
    q: "You want to give engineers shell access to EC2 instances in private subnets without opening port 22, without managing SSH keys, and with the entire session audited in CloudTrail. What do you use?",
    options: [
      "EC2 Instance Connect over a public IP, with port 22 open to the AWS service range",
      "A bastion host in the public subnet, reachable through a NAT Gateway",
      "AWS Systems Manager Session Manager, with the SSM agent and an instance profile",
      "Temporarily disabling the security group for the duration of the maintenance session",
    ],
    correct: 2,
    explain: "Session Manager builds the session over the SSM agent's <strong>outbound</strong> HTTPS connection: no inbound ports, no public IP, no bastion, and no key distribution. Activity lands in CloudTrail and the session log can be shipped to S3 or CloudWatch Logs. EC2 Instance Connect still needs port 22 to be reachable. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Pipeline security",
    q: "Which AWS tool is designed to analyze source code and detect security vulnerabilities (e.g. injection, hardcoded secrets) WITHIN the CI/CD pipeline, before deployment?",
    options: [
      "Amazon GuardDuty, which analyzes the repository's code on every commit in the pipeline",
      "Amazon Detective, which reconstructs the code flow to pinpoint the vulnerability",
      "AWS Config, with managed rules that evaluate the code before each deployment",
      "CodeGuru Security, static analysis (SAST) that plugs into the CI/CD pipeline",
    ],
    correct: 3,
    explain: "The control that belongs here is <strong>static code analysis</strong> (SAST) plus secret detection, running in the pipeline before deployment. That was CodeGuru Security's role; AWS retired it in November 2025 and its capabilities now live in <strong>Amazon Inspector Code Security</strong> and Amazon Q Developer. GuardDuty and Detective observe the running account, not the code. <a href=\"https://docs.aws.amazon.com/inspector/latest/user/scanning-cicd.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GenAI guardrails",
    q: "You're building an application with an LLM that responds to end users, and you need to protect it against prompt injection and leakage of sensitive data in the responses. Which framework is explicitly mentioned in the SCS-C03 exam guide for this type of protection?",
    options: [
      "OWASP Top 10 for LLM Applications, a catalog of risks specific to LLM-based apps",
      "PCI DSS, which defines the controls protecting cardholder data in the application",
      "The CIS Benchmarks, which harden the configuration of the underlying operating system",
      "NIST SP 800-53, the federal security control catalog for information systems",
    ],
    correct: 0,
    explain: "The <strong>OWASP Top 10 for LLM Applications</strong> catalogs risks specific to language-model applications: prompt injection, sensitive information disclosure, data poisoning, unbounded consumption, and so on. It is a new, explicit SCS-C03 skill (3.2.7). On AWS, the control that implements it is Amazon Bedrock Guardrails. <a href=\"https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-prompt-attack.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Hybrid connectivity",
    q: "What differentiates AWS Direct Connect from an AWS Site-to-Site VPN?",
    options: [
      "They are equivalent in performance and cost; only the supplying provider changes",
      "Direct Connect is a dedicated private link that never crosses the Internet; the VPN does",
      "Site-to-Site VPN demands your own hardware in the datacenter and Direct Connect does not",
      "Direct Connect cannot be combined with a VPN riding over the same physical connection",
    ],
    correct: 1,
    explain: "Direct Connect is a dedicated physical link between your network and AWS through a DX location or partner: it avoids the Internet and offers predictable bandwidth and latency, but it does <strong>not encrypt on its own</strong>. Site-to-Site VPN builds an encrypted IPsec tunnel over the Internet, quick to deploy but with variable performance. They are often combined: IPsec VPN over DX. <a href=\"https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "MACsec",
    q: "What is MACsec (802.1AE) used for in the context of AWS Direct Connect?",
    options: [
      "To speed up the connection by bundling several physical links into a single LAG",
      "To replace Direct Connect with an encrypted tunnel that travels over the Internet",
      "To encrypt the dedicated Direct Connect link at layer 2, which is otherwise clear",
      "To encrypt the Site-to-Site VPN tunnels, where it is the default tunnel protocol",
    ],
    correct: 2,
    explain: "Direct Connect is a private connection, but <strong>not an encrypted one</strong>. MACsec (IEEE 802.1AE) adds confidentiality, integrity and origin authenticity at the link layer on dedicated 10, 100 and 400 Gbps connections, using a CKN/CAK pair provisioned on your edge device. It satisfies encryption-in-transit requirements without layering a VPN on top. <a href=\"https://docs.aws.amazon.com/directconnect/latest/UserGuide/MACsec.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Verified Access in hybrid setups",
    q: "Your company has internal applications that must be accessible both to employees in the office (on-premises network) and remotely, without exposing them to the Internet or relying on a full-network VPN. Which solution fits skill 3.3.3?",
    options: [
      "AWS Site-to-Site VPN, which connects the office network with the applications' VPC",
      "AWS Direct Connect, which grants private access to the application from any location",
      "Publishing the applications on the Internet with AWS WAF and Shield Advanced in front",
      "AWS Verified Access, which evaluates identity and device posture on every request",
    ],
    correct: 3,
    explain: "Verified Access implements <strong>ZTNA</strong>: instead of joining whole networks, it authorizes each request to a specific application based on identity (IAM Identity Center or an external IdP) and device posture signals. It works the same in the office as remotely and never exposes the application to the Internet. VPN and Direct Connect connect <em>networks</em>, not applications. <a href=\"https://docs.aws.amazon.com/verified-access/latest/ug/what-is-verified-access.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Network segmentation",
    q: "In VPC design, what term describes traffic BETWEEN workloads within the same environment (e.g. between microservices in different private subnets), as opposed to traffic entering/leaving the perimeter?",
    options: [
      "East/west traffic, the traffic flowing between workloads inside the same environment",
      "North/south traffic, the traffic crossing the perimeter between the Internet and the VPC",
      "Transit traffic, what a Transit Gateway forwards between VPCs in different accounts",
      "Peering traffic, what crosses a peering connection established between two VPCs",
    ],
    correct: 0,
    explain: "<strong>North/south</strong> is traffic crossing the perimeter (Internet client ↔ VPC); <strong>east/west</strong> is the internal traffic between components. Segmenting and filtering east/west — per-tier security groups, isolated subnets, Network Firewall or VPC Lattice — shrinks the blast radius when one component falls, which is exactly the point of skill 3.3.4. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_network_protection_layered.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Network Firewall",
    q: "How does AWS Network Firewall differ from a Security Group or a NACL?",
    options: [
      "It is the same filtering engine as security groups, offered under a different product name",
      "It is a managed firewall with L3-L7 inspection, domain rules and Suricata signatures",
      "It can only be deployed in public subnets, sitting right in front of the Internet Gateway",
      "It filters by 5-tuple just like a NACL, but additionally keeps connection state",
    ],
    correct: 1,
    explain: "Security groups and NACLs filter by 5-tuple (IP, port, protocol). Network Firewall is a managed service deployed in its own inspection subnets that adds deep packet inspection, domain/SNI rules, and rules in <strong>Suricata</strong> format (IDS/IPS), aimed at egress traffic or transit traffic between VPCs. <a href=\"https://docs.aws.amazon.com/network-firewall/latest/developerguide/what-is-aws-network-firewall.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Detecting unnecessary access",
    q: "Which tool tells you whether an unintended reachable network path exists between two resources (e.g. an instance in a private subnet reachable from the Internet due to a misconfiguration chained across SG/NACL/route table)?",
    options: [
      "AWS Config, with managed rules that flag ports left open to the public Internet",
      "Amazon Macie, which discovers which resources turn out to be reachable from outside",
      "Network Access Analyzer, or the network reachability analysis in Inspector",
      "AWS Trusted Advisor, through its check for exposed security-sensitive ports",
    ],
    correct: 2,
    explain: "These tools <strong>model</strong> the full network configuration — security groups, NACLs, route tables, peering, IGW and NAT — and compute whether a reachable path exists between a source and a destination. That is far more reliable than reviewing each component separately: the flaw usually lives in the <em>combination</em>, not in one isolated rule. This is skill 3.3.5. <a href=\"https://docs.aws.amazon.com/vpc/latest/network-access-analyzer/what-is-network-access-analyzer.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "OCSF",
    q: "What is the Open Cybersecurity Schema Framework (OCSF) in the context of security integrations with AWS?",
    options: [
      "A managed AWS service for storing and querying security log data",
      "The successor to CloudTrail for recording calls to the AWS API",
      "An in-transit encryption protocol for shipping events between accounts",
      "An open schema that normalizes security events from different sources",
    ],
    correct: 3,
    explain: "OCSF is an <strong>open</strong> standard driven by AWS and other vendors for representing security events in a common schema. Amazon Security Lake uses it as its native format: it automatically converts logs from AWS services and requires custom sources to deliver in OCSF already, so correlation does not mean writing one parser per product. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/open-cybersecurity-schema-framework.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "WAF Fraud Control – ATP",
    q: "Your security team detects a spike in login attempts using stolen credentials (credential stuffing) against your application's login endpoint, served behind CloudFront. Attackers are using email/password pairs leaked in other breaches, and many succeed because users reuse passwords. Which AWS WAF Fraud Control component specifically addresses this use case?",
    options: [
      "Account Takeover Prevention (ATP), which checks credentials against leaked ones",
      "AWS WAF Bot Control, which categorizes and blocks bots known by their signature",
      "An IP-based rate-based rule, which cuts in once the request threshold is passed",
      "Account Creation Fraud Prevention (ACFP), meant for the account sign-up endpoint",
    ],
    correct: 0,
    explain: "ATP protects the <strong>login</strong> endpoint: it inspects the submitted email/password pair and compares it against a stolen-credential database that AWS refreshes continuously, and it also tracks success and failure rates per IP and per client session. ACFP is the sibling component, but for <em>registration</em> pages, not login. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-atp.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "WAF Fraud Control – ACFP",
    q: "An application with public registration suffers waves of fake accounts created by bots, later used for promo abuse (welcome-coupon fraud). Which AWS WAF protection is designed for this scenario?",
    options: [
      "Account Takeover Prevention (ATP), which protects the sign-in endpoint",
      "Account Creation Fraud Prevention (ACFP), which watches the registration endpoint",
      "CloudFront Geo Restriction, blocking the countries the fraudulent traffic comes from",
      "Shield Advanced, whose layer 3/4 mitigation discards the automated waves",
    ],
    correct: 1,
    explain: "ACFP continuously watches requests to the account-creation endpoint: it validates the email domain, checks credentials against the leaked-credential database, reviews phone and address fields, and applies behavioral analysis to stop bulk automated sign-ups. ATP covers login; Shield mitigates network DDoS, not application fraud. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-acfp.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "WAF CAPTCHA vs Challenge",
    q: "You want to slow down a simple bot scraping your product catalog without degrading the experience of real users (you don't want to make them solve a visible puzzle). Which AWS WAF rule action is most appropriate?",
    options: [
      "CAPTCHA, which asks the user to solve a visible puzzle before letting them continue",
      "Block on every suspicious IP, with no prior verification of the client at all",
      "Challenge, which verifies in the background that the client is a real browser",
      "Count, which labels the request and lets it through without any further action",
    ],
    correct: 2,
    explain: "Challenge runs a <strong>silent</strong> verification in the client (JavaScript plus a token in the <code>aws-waf-token</code> cookie) to confirm a real browser is behind the request, asking the user for nothing: ideal against simple bots and frictionless. CAPTCHA demands a visible puzzle and is reserved for more persistent threats; Count only counts. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "WAF Bot Control",
    q: "You need to distinguish between known 'good' bots (like legitimate search engine crawlers) and malicious/uncategorized bots on your web application, including the ability to define protections against bots specifically targeting your business (e.g. inventory scalping bots). Which AWS WAF managed rule group fits?",
    options: [
      "AWS Managed Rules Core rule set (CRS), focused on the OWASP Top 10 risk categories",
      "Amazon Inspector, which identifies bots from the CVEs found in the application",
      "The Anti-DDoS managed rule group, meant for volumetric layer 7 request floods",
      "AWS WAF Bot Control, whose Targeted level adds fingerprinting and heuristics",
    ],
    correct: 3,
    explain: "Bot Control classifies automated traffic and verifies bots that self-identify (search engines, monitors). Its <strong>Common</strong> level covers bots that declare themselves; the <strong>Targeted</strong> level adds browser interrogation, fingerprinting and behavioral heuristics for the sophisticated bots built specifically against your business, such as inventory scalping. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-bot-control.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Shield Advanced + Anti-DDoS rule group",
    q: "Your organization uses Shield Advanced on a CloudFront distribution with AWS WAF. After the adoption of the new AWS WAF Anti-DDoS managed rule group as Shield Advanced's default application-layer protection, what changes about billing during an actively mitigated layer 7 DDoS attack?",
    options: [
      "Requests blocked during active mitigation do not count toward your bill",
      "You are charged double while mitigation lasts, for the extra resource consumption",
      "Nothing changes: attack traffic is billed exactly like legitimate traffic is",
      "Shield Advanced stops billing entirely for as long as the attack remains active",
    ],
    correct: 0,
    explain: "The Anti-DDoS managed rule group replaces the earlier layer 7 protection at lower WCU cost and, during an active DDoS mitigation, blocked requests are <strong>excluded from the monthly request count</strong> for WAF, for the rule group itself, and for Shield Advanced. The attack's volume therefore does not turn into a disproportionate bill. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-anti-ddos.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Network Firewall TLS Inspection",
    q: "You need AWS Network Firewall to inspect the content of outbound HTTPS connections from your VPC (not just the SNI) in order to apply IDS/IPS-style signature rules against the decrypted traffic. What do you need to configure?",
    options: [
      "Nothing: Network Firewall inspects the encrypted payload natively, with no configuration",
      "A TLS inspection configuration, which decrypts, inspects and re-encrypts",
      "Domain (FQDN) rules only, which read the SNI without needing to decrypt anything",
      "Replace it with AWS WAF, which does inspect encrypted content end to end",
    ],
    correct: 1,
    explain: "A stateful firewall only sees handshake metadata (such as the SNI) while the payload travels encrypted. The <strong>TLS inspection configuration</strong> acts as a proxy: it decrypts using ACM certificates, applies the signature and domain rules to the cleartext, and re-encrypts toward the destination. It works for both inbound and outbound inspection. <a href=\"https://docs.aws.amazon.com/network-firewall/latest/developerguide/tls-inspection-configurations.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Inspector Code Security",
    q: "Your development team wants to detect security vulnerabilities (and Infrastructure as Code misconfigurations) directly in GitHub pull requests, before code is merged, without relying solely on a later scan in production. Which Amazon Inspector capability covers this?",
    options: [
      "Inspector Network Reachability, which analyzes the network paths toward the resource",
      "None: Inspector only scans images already published to ECR, never the source code",
      "Amazon Inspector Code Security, integrated with GitHub and GitLab on each PR",
      "Amazon CodeGuru Reviewer, which replaced Inspector for source code analysis",
    ],
    correct: 2,
    explain: "Inspector Code Security widens the service's reach beyond EC2, ECR and Lambda into the <strong>repository</strong>: it connects to GitHub or GitLab, analyzes code vulnerabilities, dependencies and IaC templates, and returns findings in the pull request itself or in the CI/CD pipeline, before the vulnerability ever reaches production. <a href=\"https://docs.aws.amazon.com/inspector/latest/user/code-security-assessments-connect-github.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Inspector organization-wide management",
    q: "As the delegated security administrator in AWS Organizations, you want to centrally enable and configure which Amazon Inspector scan types (for example, Lambda Code Scanning or Code Security) are automatically applied across all accounts in certain organizational units (OUs), without configuring it account by account. What mechanism do you use?",
    options: [
      "An SCP that denies the API calls capable of disabling Inspector in a member account",
      "None: you enable it account by account, Inspector has no central management",
      "An AWS Config conformance pack deployed onto each organizational unit",
      "An Amazon Inspector policy in AWS Organizations, applied to the OUs",
    ],
    correct: 3,
    explain: "<strong>Amazon Inspector policies</strong> are a type of AWS Organizations management policy: they declare which scans (EC2, ECR, Lambda standard and code, Code Security) are enabled at the root, on specific OUs, or on individual accounts, and new accounts inherit the policy when they join. An SCP can only deny actions, never turn a configuration on. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_inspector.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "GuardDuty generates multiple, seemingly unrelated low-severity findings about an EC2 instance and a related ECS task (unusual credential access, then a suspicious network connection shortly after). Which GuardDuty capability is designed to correlate this sequence and elevate it into a single critical 'attack in progress' finding?",
    options: [
      "Extended Threat Detection, which correlates signals into an attack sequence finding",
      "Malware Protection for EC2, which only scans the EBS volumes of the affected instance",
      "Amazon Detective, which replaces GuardDuty in accounts that have Security Hub on",
      "AWS Config rules, which aggregate the configuration changes of each resource",
    ],
    correct: 0,
    explain: "Extended Threat Detection correlates signals — API activity and earlier findings — spread across time and across resources (EC2, ECS, EKS, S3, IAM credentials) and emits an <strong>attack sequence</strong> finding, always of critical severity, when the whole set describes a multi-stage attack in progress. It is on by default and carries no extra cost. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-extended-threat-detection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "GuardDuty detects suspicious activity on an EC2 instance (for example, communication with a known command-and-control domain). What does GuardDuty Malware Protection for EC2 automatically do from there, and what impact does it have on the running instance?",
    options: [
      "It terminates the instance immediately to contain the threat before any analysis",
      "It scans the EBS volumes agentlessly from a snapshot, without affecting the service",
      "It first requires the Amazon Inspector agent to be installed on the compromised host",
      "It can only scan the instance after stopping it, in the <code>stopped</code> state",
    ],
    correct: 1,
    explain: "The <em>GuardDuty-initiated malware scan</em> starts on its own when a finding points at the instance: it snapshots the attached EBS volumes and analyzes them for known malware <strong>agentlessly</strong>, installing nothing in the operating system and with no impact on performance or availability. GuardDuty detects and alerts; containment remains your decision. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "VPC Route Server",
    q: "You have third-party virtual network appliances (NVA firewalls) deployed in your VPC that need to dynamically advertise routes into the subnets' route tables, without maintaining custom scripts or an overlay network to sync the changes. Which AWS service natively solves this?",
    options: [
      "AWS Transit Gateway, which propagates routes by BGP into the VPC's subnets",
      "AWS Network Firewall, which rewrites the route tables when its endpoints deploy",
      "Amazon VPC Route Server, which takes BGP routes and updates the tables",
      "Route 53 Resolver, which resolves each appliance's next hop through DNS",
    ],
    correct: 2,
    explain: "VPC Route Server brings dynamic routing <strong>inside</strong> the VPC: NVAs establish BGP sessions against the route server endpoints, and the advertised routes propagate automatically into the route tables of the associated subnets and Internet Gateway. Previously this meant automating it with Lambda or building an overlay. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/route-server-how-it-works.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Verified Access non-HTTP(S)",
    q: "Beyond internal web applications, your team needs to grant Zero Trust access (evaluating identity and device posture) to databases and to SSH/RDP sessions on EC2 instances, without deploying a full-network VPN. Which recent AWS Verified Access capability enables this?",
    options: [
      "None: Verified Access only supports HTTP(S), and SSH or RDP still require a VPN",
      "It is only viable over a dedicated Direct Connect that has MACsec enabled",
      "Moving those workloads to AWS Client VPN, the only service supporting SSH and RDP",
      "Verified Access support for non-HTTP(S) TCP protocols, such as SSH and RDP",
    ],
    correct: 3,
    explain: "Verified Access supports generic TCP endpoints alongside HTTP(S) ones: with the <em>Connectivity Client</em>, a user reaches databases, SSH or RDP sessions under the same identity and device-posture policy, without opening a full network tunnel or handing out keys. It extends the Zero Trust model to EC2 administration. <a href=\"https://docs.aws.amazon.com/verified-access/latest/ug/verified-access-endpoints.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Group Referencing (Transit Gateway)",
    q: "You have two VPCs connected via AWS Transit Gateway (not direct peering), and you want to allow traffic between instances in one VPC and the other by directly referencing the source Security Group in the inbound rule of the destination Security Group (instead of using CIDR ranges). Is this possible?",
    options: [
      "Yes: security groups can be referenced across VPCs on the same transit gateway",
      "No: referencing security groups across VPCs only works with direct VPC peering",
      "Only if both VPCs belong to the same AWS account and the same availability zone",
      "Only for UDP traffic; TCP traffic still requires static CIDR ranges in the rule",
    ],
    correct: 0,
    explain: "With <em>security group referencing support</em> enabled on the transit gateway or on the attachment, an <strong>inbound</strong> rule can name a security group from another VPC attached to the same TGW instead of brittle CIDR ranges. Mind the limits: inbound rules only, and it does not work across transit gateway peering. <a href=\"https://docs.aws.amazon.com/vpc/latest/tgw/tgw-sg-updates.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "ECR Image Signing",
    q: "You want to guarantee that only container images that genuinely came from your authorized CI/CD pipeline can be deployed to your cluster, protecting the software supply chain against tampered or unverified images. Which Amazon ECR capability helps with this?",
    options: [
      "ECR pull-through cache, which replicates and verifies images from public registries",
      "ECR managed image signing, which signs with AWS Signer on every push",
      "ECR enhanced scanning, whose CVE report also attests to the image's provenance",
      "None: image signing belongs exclusively to Docker Hub and the Notary project",
    ],
    correct: 1,
    explain: "ECR <strong>managed image signing</strong> automatically generates an AWS Signer signature on push and is governed as a registry configuration, with no client-side tooling to install. Verifying that signature at deploy time keeps tampered images out. Vulnerability scanning is a different control: it tells you whether CVEs exist, not where the image came from. <a href=\"https://docs.aws.amazon.com/AmazonECR/latest/userguide/managed-signing.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Declarative Policies (IMDSv2)",
    q: "You want to guarantee, across your entire AWS Organizations organization, that NO new EC2 instance can be launched with IMDSv1 enabled (mitigating the SSRF vector), so that the configuration stays enforced even as new accounts are added or AWS introduces new EC2 APIs. What mechanism do you use, as opposed to a traditional SCP?",
    options: [
      "An SCP that denies the RunInstances action whenever IMDSv2 is not required in the call",
      "An AWS Config rule with remediation that fixes the instance once it has been created",
      "An EC2 declarative policy in AWS Organizations, enforced in the control plane",
      "Tagging instances as IMDSv2-only and auditing those tags on a weekly basis",
    ],
    correct: 2,
    explain: "<strong>Declarative policies</strong> are an Organizations policy type distinct from SCPs: instead of denying specific API actions, they declare a service's <em>desired state</em> — for EC2, attributes such as <code>http_tokens</code> and <code>http_tokens_enforced</code> — and the service's own control plane keeps it that way, including when new APIs or new accounts appear. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "VPC Lattice Auth Policies",
    q: "You're designing a microservices mesh spanning multiple AWS VPCs and accounts, and you want to control which specific service can invoke which other service and with which HTTP method, using identity (SigV4/IAM) rather than just IP addresses — independently of the Security Groups managed by the network team. Which VPC Lattice mechanism applies?",
    options: [
      "Each VPC's network ACLs, which already filter by source IP and destination port",
      "A shared NAT Gateway that centralizes and authorizes cross-account service calls",
      "AWS Verified Access, which authorizes the calls between services in the mesh",
      "VPC Lattice auth policies, IAM policies on the network or the service",
    ],
    correct: 3,
    explain: "An auth policy is an IAM-syntax document attached to the <strong>service network</strong> (coarse authorization, owned by the network team) or to an individual <strong>service</strong> (fine-grained, owned by the service team), deciding which principal may invoke which action and route. For the call to succeed, both the auth policy and the identity policy must allow it. <a href=\"https://docs.aws.amazon.com/vpc-lattice/latest/ug/auth-policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Route 53 Resolver DNS Firewall Advanced",
    q: "You suspect a compromised host inside your VPC is using a Domain Generation Algorithm (DGA) to generate pseudo-random domain names and communicate with command-and-control (C2) infrastructure, evading static domain blocklists. Which AWS service detects this specific pattern in real time?",
    options: [
      "DNS Firewall Advanced, which detects DGA patterns and DNS tunneling in real time",
      "Route 53 Resolver DNS Firewall standard tier, based only on lists of known domains",
      "AWS Network Firewall with domain (FQDN) rules applied to outbound traffic",
      "Amazon GuardDuty, which blocks the DNS queries aimed at known C2 domains",
    ],
    correct: 0,
    explain: "DNS Firewall Advanced does not depend on lists: it inspects threat signatures in the query itself — name length and shape, frequency and size of requests and responses — to identify <strong>DGA</strong> and <strong>DNS tunneling</strong>, which exist precisely to dodge list-based blocking. GuardDuty raises findings on suspicious DNS activity, but DNS Firewall is what blocks. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/firewall-advanced.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "PrivateLink endpoint policies",
    q: "Your team created an interface VPC endpoint to Amazon S3 so instances in a private subnet can reach S3 without going out to the Internet. You want to ensure that, through THAT specific endpoint, only one particular bucket can be accessed, regardless of the IAM permissions each role has. What mechanism do you use?",
    options: [
      "Modify the endpoint's security group so that it filters by the destination bucket name",
      "An endpoint policy, a resource policy that scopes access made through the endpoint",
      "A network ACL on the endpoint's subnet restricting the S3 network prefixes",
      "None: every endpoint grants full access to the whole service that it fronts",
    ],
    correct: 1,
    explain: "An interface endpoint's security group only controls <em>who reaches the ENI</em> by IP and port: it knows nothing about buckets. The <strong>endpoint policy</strong> is an IAM-syntax resource policy (with a <code>Principal</code> element) attached to the endpoint that limits which principals, actions and resources are reachable that way. It does not replace identity policies or the bucket policy: it adds to them. <a href=\"https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-access.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Groups vs NACLs",
    q: "You are designing a VPC's network controls. Which TWO statements about security groups and network ACLs are correct?",
    options: [
      "Security groups are stateful: return traffic is allowed with no outbound rule needed",
      "Security groups support explicit Deny rules that block one specific source IP address",
      "Network ACLs are stateless and support explicit Deny rules, evaluated by rule number",
      "Network ACLs apply to the instance's network interface, and not to the subnet",
    ],
    correct: [0, 2],
    explain: "This is the most-asked comparison in the domain. <strong>Security groups are stateful</strong> (Allow only, with the return path automatic) and apply to the ENI; <strong>NACLs are stateless</strong> (Allow and Deny, evaluated in numeric order, with the return path — usually ephemeral ports — opened explicitly) and apply to the subnet. That is why blocking a specific IP is a NACL job. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Protecting a public web app",
    q: "A web application behind CloudFront is hit by SQL injection and a volumetric layer 3/4 attack. Which TWO services directly address these threats?",
    options: [
      "Amazon Inspector, which blocks requests carrying a malicious payload in real time",
      "AWS WAF with the appropriate managed rule groups, to stop the SQL injection",
      "AWS Config, which stops suspicious requests from ever reaching the origin",
      "AWS Shield, which mitigates the volumetric layer 3/4 attack on the distribution",
    ],
    correct: [1, 3],
    explain: "<strong>WAF</strong> inspects at layer 7 and stops SQLi or XSS with managed rules; <strong>Shield</strong> mitigates volumetric layer 3/4 DDoS (Standard is included, Advanced adds mitigation and managed response). Inspector evaluates <em>vulnerabilities</em> in instances, containers and Lambda, and Config evaluates resource <em>configuration</em>: neither sits in the request path. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Admin access without exposed SSH",
    q: "Security forbids opening port 22 to the internet and wants to eliminate bastion hosts, but operators need shell access to EC2 instances in private subnets. Which TWO enable this?",
    options: [
      "AWS Systems Manager Session Manager, which opens the session with no inbound ports",
      "A security group rule that permits port 22 only from the corporate IP address range",
      "An Elastic IP on each instance so that Systems Manager is able to reach it",
      "The SSM agent on the instance plus an instance profile with Systems Manager rights",
    ],
    correct: [0, 3],
    explain: "<strong>Session Manager</strong> works over an <em>outbound</em> connection from the agent to the service, so it needs no inbound ports, no public IP and no bastion, and it logs the session to CloudTrail, S3 or CloudWatch Logs. It needs both pieces: the <strong>agent</strong> and <strong>permissions via the instance profile</strong>. Opening port 22 to a corporate range is exactly what is being eliminated. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Hardened base images",
    q: "The company wants every EC2 instance to boot from hardened, patched images. Which TWO services fit that chain?",
    options: [
      "AWS Shield Advanced, to verify that the AMI carries no malware before it is used",
      "EC2 Image Builder, to build and version hardened AMIs in a repeatable way",
      "Amazon Inspector, to detect known CVEs in the images and in the instances",
      "Amazon Macie, to scan the AMI's operating system looking for known CVEs",
    ],
    correct: [1, 2],
    explain: "<strong>Image Builder</strong> automates building, hardening and versioning the AMIs, and <strong>Inspector</strong> evaluates them continuously against known CVEs. Shield is purely anti-DDoS, and Macie discovers and classifies <strong>sensitive data in S3</strong>: it does not analyze operating systems. Mistaking Macie for a vulnerability scanner is a recurring distractor. <a href=\"https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["infrastructure-security"] = QUIZ_DATA;
