var QUIZ_DATA = [
  {
    tag: "Policy evaluation",
    q: "A user has an identity policy that allows s3:GetObject on a bucket, but the bucket has a bucket policy with an explicit Deny for that same user. What happens?",
    options: [
      "Access is denied: an explicit Deny in any applicable policy overrides every Allow",
      "Access is allowed: the user's identity policy takes priority over the bucket's",
      "Access is allowed: the bucket policy is only evaluated if the bucket is external",
      "It is resolved by whichever of the two policies was created or edited most recently",
    ],
    correct: 0,
    explain: "IAM's evaluation order is: explicit Deny &gt; explicit Allow &gt; default Deny. An explicit Deny in ANY applicable policy (identity, resource, SCP, RCP, boundary, session policy) overrides any Allow, no matter where it lives. A resource owned by the same account still has its resource policy evaluated. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SCP vs RCP",
    q: "What is the key difference between a Service Control Policy (SCP) and a Resource Control Policy (RCP) in AWS Organizations?",
    options: [
      "SCPs cap access to resources and RCPs cap what the identities can do",
      "SCPs cap what the identities in the organization's accounts can do",
      "SCPs only apply to the management account and RCPs to member accounts",
      "RCPs replaced SCPs, so new SCPs can no longer be created",
    ],
    correct: 1,
    explain: "SCPs are guardrails that cap the maximum permission available to principals WITHIN the organization. RCPs cap access to the RESOURCES themselves, including external principals, closing gaps SCPs don't cover because SCPs don't apply to identities outside the organization. Inverting that relationship is the classic mistake. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Permission boundaries",
    q: "A developer has a permission boundary that only allows actions on S3 and DynamoDB. Their identity-based policy grants AdministratorAccess. What can they actually do?",
    options: [
      "Everything: AdministratorAccess takes precedence over any permission boundary",
      "Nothing: the boundary and the identity policy conflict, so access is denied",
      "Only S3 and DynamoDB actions: the effective permission is the intersection",
      "Everything except S3 and DynamoDB: the boundary excludes what it lists",
    ],
    correct: 2,
    explain: "The permission boundary does NOT grant permissions on its own: it defines the maximum set of permissions an identity-based policy can grant. The effective permission is the INTERSECTION of the identity policy and the boundary — never the union, never the difference. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "STS",
    q: "A mobile app authenticates users against Google (an OIDC provider) and needs temporary AWS credentials to access an S3 bucket directly from the phone. Which STS API is appropriate?",
    options: [
      "sts:GetSessionToken, which returns temporary credentials to the calling IAM user",
      "sts:GetFederationToken, which federates from long-lived IAM user credentials",
      "sts:AssumeRoleWithSAML, which trades a SAML assertion from the IdP for a role",
      "sts:AssumeRoleWithWebIdentity, which trades the provider's token for a role",
    ],
    correct: 3,
    explain: "AssumeRoleWithWebIdentity exchanges an OIDC token (Google, Facebook, Amazon, or any compatible IdP) for temporary role credentials. GetSessionToken and GetFederationToken both start from long-lived IAM credentials, which is exactly what you must not ship inside a mobile app. In production AWS recommends Cognito Identity Pools on top. <a href=\"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SAML federation",
    q: "A company uses on-premises Active Directory Federation Services (ADFS) and wants to give its employees access to the AWS console without creating IAM users. Which mechanism is the most appropriate?",
    options: [
      "AssumeRoleWithSAML against a SAML 2.0 IdP registered as a provider in IAM",
      "IAM Roles Anywhere, registering the ADFS certificate as a trusted anchor CA",
      "Long-lived access keys generated from AD and handed out to each employee",
      "IAM Identity Center in standalone mode, using its internal directory as source",
    ],
    correct: 0,
    explain: "AssumeRoleWithSAML federates identities from a SAML 2.0 IdP (ADFS, Okta, Entra ID) straight into an IAM Role, with no individual IAM users. IAM Roles Anywhere solves a different problem (workloads, not people), and standalone Identity Center deliberately ignores the corporate directory the company already runs. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM Identity Center",
    q: "What is the main difference between a traditional cross-account IAM Role and an IAM Identity Center Permission Set?",
    options: [
      "None: a permission set is just a console view over roles that already exist",
      "A permission set is defined once and provisioned as a role in each account",
      "A permission set is assigned to the root user of each assigned member account",
      "A permission set only accepts inline policies, never AWS managed policies",
    ],
    correct: 1,
    explain: "IAM Identity Center centralizes management: you define a permission set once and the service provisions and keeps in sync the IAM roles it needs in every assigned account, so you never manage roles account by account. It accepts AWS managed, customer managed and inline policies, and is never assigned to the root user. <a href=\"https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM Access Analyzer",
    q: "What type of finding does IAM Access Analyzer generate when it detects that an IAM role hasn't been used in the last 90 days?",
    options: [
      "External access finding, because the role is reachable from outside the account",
      "Policy validation finding, because the role's policy breaks a recommended practice",
      "Unused access finding, which flags roles and permissions idle in the period",
      "None: Access Analyzer only inspects static policies, never real usage data",
    ],
    correct: 2,
    explain: "Access Analyzer has three distinct capabilities: external access findings (resources reachable from outside your zone of trust), unused access findings (roles, permissions and access keys with no recent use) and policy validation (syntax and best practices as you write). Idle age is squarely the second one's job. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "ABAC",
    q: "In an attribute-based access control (ABAC) strategy with IAM, which condition would typically be used in a policy to allow a user to only tag/access resources that match their own department?",
    options: [
      "\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:PrincipalTag/costcenter}\"}",
      "\"StringEquals\": {\"aws:ResourceTag/department\": \"${aws:ResourceTag/owner}\"}",
      "\"StringNotEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/team}\"}",
      "\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/department}\"}",
    ],
    correct: 3,
    explain: "ABAC compares a tag on the PRINCIPAL with the same tag on the RESOURCE using policy variables (<code>aws:PrincipalTag/key</code> against <code>${aws:ResourceTag/key}</code>), so the rule scales without rewriting the policy for every new resource. Comparing two tags from the same side, or negating the match, breaks the pattern. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_attribute-based-access-control.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Confused deputy",
    q: "An AWS service (e.g. CloudTrail) assumes a role in your account on behalf of another AWS customer and, by mistake, accesses data in your account that it shouldn't. Which policy condition prevents this 'confused deputy problem'?",
    options: [
      "aws:SourceArn or aws:SourceAccount in the service role's trust policy",
      "aws:SourceIp in the trust policy, limiting the IPs the service calls from",
      "aws:MultiFactorAuthPresent, requiring MFA from the service assuming the role",
      "aws:RequestedRegion, pinning the role to the Region where the resource lives",
    ],
    correct: 0,
    explain: "To stop an AWS service from being 'tricked' into acting for an unauthorized third party, add a trust policy condition on aws:SourceArn (or aws:SourceAccount) restricting which specific resource or account can trigger that AssumeRole. An AWS service does not call from your IP range and never presents MFA, so those conditions simply don't apply. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "A company has on-premises servers (outside AWS) that need temporary AWS credentials without using long-lived access keys. Which service is designed exactly for this case?",
    options: [
      "AWS Systems Manager Hybrid Activations, which registers the server as a node",
      "IAM Roles Anywhere, which trades an X.509 certificate for STS credentials",
      "IAM Identity Center, deploying its directory connector on the on-prem server",
      "Cognito Identity Pools, which issues credentials to external identities",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere lets workloads outside AWS obtain temporary credentials by presenting an X.509 certificate signed by a CA registered with IAM. Hybrid Activations is about managing the server with SSM, not about issuing arbitrary IAM credentials, and Cognito targets an application's end-user identities. <a href=\"https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Root user",
    q: "AWS introduced 'Centralized Root Access Management' in Organizations. What does this capability allow you to do?",
    options: [
      "Delete the root user of each member account, which stops existing altogether",
      "Turn each account's root into an IAM role that administrators can assume",
      "Centrally manage and remove the root credentials of member accounts",
      "Replace MFA on the management account with approval by several administrators",
    ],
    correct: 2,
    explain: "The capability centrally manages member accounts' root credentials — removing password, access keys and MFA, and preventing their recovery — and lets you invoke a bounded set of privileged tasks without going through password recovery account by account. The root user still exists as an identity: what disappears are its long-term credentials. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-enable-root-access.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "MFA",
    q: "Which condition key is used in an IAM policy to require that an API call was made with an MFA-authenticated session?",
    options: [
      "sts:MfaAuthenticated, which the temporary session exposes after validating MFA",
      "aws:MFARequired, which demands a second factor before the policy is evaluated",
      "iam:MFAEnabled, which reports whether the user has an MFA device registered",
      "aws:MultiFactorAuthPresent, which reports whether the session used MFA",
    ],
    correct: 3,
    explain: "The standard global key is <code>aws:MultiFactorAuthPresent</code>, of type Bool. The other three do not exist as IAM condition keys: they are plausible inventions mixing service prefixes with real concepts. A heavily tested best practice is pairing it with <code>aws:MultiFactorAuthAge</code> to cap the age of the MFA session. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Resource-based policies",
    q: "Which of these statements about resource-based policies is correct?",
    options: [
      "They can name a Principal from another account and grant it access directly",
      "Only IAM Roles support resource-based policies, no other AWS service does",
      "They do not accept a Condition element, only Effect, Principal, Action, Resource",
      "They replace identity-based policies: where one exists, IAM ignores the rest",
    ],
    correct: 0,
    explain: "S3 buckets, KMS keys, SQS queues, SNS topics and Lambda functions all support resource-based policies, which carry a <code>Principal</code> element and can name an identity in another account directly, with no role assumption in yours. They accept conditions like any JSON policy and are evaluated alongside identity policies, not instead of them. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Credential report vs Access Advisor",
    q: "What is the difference between the IAM Credential Report and IAM Access Advisor?",
    options: [
      "They are the same report: the Credential Report is Access Advisor as a CSV file",
      "The Credential Report audits passwords, access keys and MFA per IAM user",
      "Access Advisor only works on the root user, not on IAM users or IAM roles",
      "The Credential Report needs GuardDuty enabled before it can be generated",
    ],
    correct: 1,
    explain: "The Credential Report is an account-level CSV auditing the STATE of every IAM user's credentials (password age, access keys, MFA). Access Advisor shows the HISTORY of services a user or role has actually reached, and is the tool for trimming unused permissions. Neither depends on GuardDuty, and neither is limited to root. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_last-accessed.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Cross-account trust policy",
    q: "Which element is mandatory in the trust policy (assume role policy document) of an IAM Role to allow an external account to assume it?",
    options: [
      "An SCP in the external account explicitly authorizing the call to the role",
      "A bucket policy attached to the role listing the external account as Principal",
      "A Principal naming the external account or role, plus sts:AssumeRole",
      "Nothing: by default any AWS account can already assume any role",
    ],
    correct: 2,
    explain: "The role's trust policy must include a <code>Principal</code> with the ARN of the authorized external account or role and <code>Action: sts:AssumeRole</code>. The caller also needs its own identity policy allowing sts:AssumeRole on that ARN: BOTH ends are required. Roles have no bucket policy, and without a trust policy nobody outside can assume them. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Data perimeter",
    q: "In AWS's 'data perimeter' concept, what combination of controls is typically used to ensure data NEVER leaves the organization, even with stolen valid credentials?",
    options: [
      "KMS encryption on every object, so the data always leaves in encrypted form",
      "Restrictive Security Groups blocking all outbound traffic from the whole VPC",
      "Rotating access keys every 90 days plus a strict account password policy",
      "SCPs and RCPs using aws:PrincipalOrgID, plus VPC endpoint policies",
    ],
    correct: 3,
    explain: "The data perimeter combines three perimeters: identity (who is calling? SCPs/RCPs with aws:PrincipalOrgID), resource (is it a trusted resource? aws:ResourceOrgID) and network (from where? VPC endpoint policies with aws:SourceVpce). Encryption protects data at rest but a valid credential still decrypts it, and Security Groups cannot see the calling identity. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/building-a-data-perimeter-on-aws/building-a-data-perimeter-on-aws.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Session policies",
    q: "When you call sts:AssumeRole passing an additional --policy parameter (session policy), how does this affect the effective permissions of the resulting session?",
    options: [
      "It narrows the role's permissions: the result is the intersection of both",
      "It widens the role's permissions with whatever the session policy declares",
      "It replaces the role's own identity policy for the whole temporary session",
      "It has no effect: session policies only apply to federated users, not roles",
    ],
    correct: 0,
    explain: "Just like a permission boundary, a session policy NEVER widens permissions: it can only narrow, by intersection, what the assumed role already has. It is the mechanism for handing out more restricted temporary credentials from a broad role, and can be passed to AssumeRole, AssumeRoleWithSAML and AssumeRoleWithWebIdentity alike. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Declarative policies",
    q: "AWS Organizations introduced 'Declarative Policies'. How do they differ from SCPs?",
    options: [
      "They are SCPs renamed: the mechanism and the policy syntax are exactly the same",
      "They pin the desired configuration of service attributes across the organization",
      "They can only be attached to the management account, never to an OU or account",
      "They replace AWS Config entirely: they evaluate compliance rules and remediate drift",
    ],
    correct: 1,
    explain: "Unlike SCPs, which allow or deny API calls, declarative policies establish and maintain a desired configuration state at the organization or OU level for specific attributes of certain services (requiring IMDSv2, blocking public AMIs). They are enforced in the service's control plane and hold even as the service adds new APIs. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Policy evaluation with VPC endpoints",
    q: "Which condition key restricts access to an S3 bucket exclusively to requests that pass through a specific VPC endpoint?",
    options: [
      "aws:SourceIp, which compares the public source IP of the request",
      "aws:VpcSourceIp, which compares the private IP assigned inside the VPC",
      "aws:SourceVpce, which compares the ID of the VPC endpoint used",
      "s3:VpcEndpointId, which compares the endpoint declared on the bucket",
    ],
    correct: 2,
    explain: "<code>aws:SourceVpce</code> in a bucket policy (or any compatible resource policy) restricts access to requests travelling through a specific VPC endpoint: it is the core network-perimeter control. aws:SourceIp compares addresses, not endpoints, and the other two keys do not exist. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Inline vs managed policies",
    q: "What is the main disadvantage of using inline policies instead of managed policies?",
    options: [
      "Inline policies do not accept the Condition element in their statements",
      "Inline policies can only allow actions, they can never deny them",
      "Inline policies cannot be attached to roles, only to users and groups",
      "Inline policies cannot be reused or versioned in a central place",
    ],
    correct: 3,
    explain: "An inline policy lives embedded in a single identity (user, group or role): it cannot be attached elsewhere and has no versions to roll back to, which makes it harder to reuse, audit and manage at scale than a customer managed policy. In expressiveness they are identical: conditions, Deny and any identity type all work. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Cognito",
    q: "Your web application has its own end-user sign-up/login system, and after authenticating, users need to upload files directly to an S3 bucket using temporary AWS credentials. Which combination of Cognito components would you use?",
    options: [
      "A User Pool issues the JWT; an Identity Pool trades it for credentials",
      "Just a User Pool, which already returns temporary AWS credentials directly",
      "Just an Identity Pool, which handles user sign-up and user login",
      "A User Pool federated with AssumeRoleWithSAML against the bucket",
    ],
    correct: 0,
    explain: "The User Pool handles identity and login and returns JSON Web Tokens, but does NOT hand out AWS credentials. The Identity Pool is what exchanges that authenticated token for temporary STS credentials tied to a role, enabling direct access to S3. Confusing the two components is the most common exam mistake. <a href=\"https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 presigned URLs",
    q: "What happens to an S3 presigned URL if, before it expires, the s3:GetObject permission of the user who generated it is revoked?",
    options: [
      "It keeps working: the signature froze the permissions held when it was created",
      "It stops working: every use is evaluated against the current permissions",
      "It stops working, but only after a propagation delay of about one minute",
      "It keeps working: a presigned URL can never be revoked once it is issued",
    ],
    correct: 1,
    explain: "A presigned URL is not a standalone credential: it is a signature delegating, for a time window, the signer's CURRENT permission. If that permission goes away before the URL expires, the request is denied, because IAM is evaluated again on every access. The expiry time is a ceiling, not a guarantee of access. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Directory Service",
    q: "A company has an on-premises Active Directory it wants to keep using as its identity source, without migrating data or replicating the directory inside AWS. Which AWS Directory Service option fits?",
    options: [
      "AWS Managed Microsoft AD, which creates a managed directory inside AWS",
      "Simple AD, a Samba-compatible directory that runs inside your own VPC",
      "AD Connector, a proxy that redirects authentication to the on-prem AD",
      "Cognito User Pools, which imports the AD users from an exported CSV file",
    ],
    correct: 2,
    explain: "AD Connector is a plain directory proxy: it redirects authentication requests to the existing on-premises Active Directory without copying or syncing data. Managed Microsoft AD and Simple AD do create a directory inside AWS, which is precisely what the scenario rules out, and Cognito targets application end users, not employees with AD. <a href=\"https://docs.aws.amazon.com/directoryservice/latest/admin-guide/directory_ad_connector.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Verified Permissions",
    q: "Your team is building a multi-tenant SaaS application and needs to decide, on every request, whether the authenticated user can view a specific document based on their role and tenant. Which AWS service is specifically designed for this?",
    options: [
      "IAM Access Analyzer, evaluating the application's own policies on each request",
      "One Service Control Policy per tenant, denying access to other tenants' documents",
      "AWS Config Rules, evaluating the compliance of every document in the tenant",
      "Amazon Verified Permissions, with Cedar policies queried via IsAuthorized",
    ],
    correct: 3,
    explain: "Amazon Verified Permissions is a managed authorization engine built on the Cedar language, designed for authorization logic INSIDE your own applications (who may view or edit which business object), not for permissions on the AWS API. SCPs and Config act on AWS resources and have no visibility into a tenant's documents. <a href=\"https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/what-is-avp.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM paths",
    q: "What is the 'path' (e.g. /division_abc/subdivision_xyz/) of an IAM User or Role mainly used for?",
    options: [
      "It groups identities by prefix in the ARN and lets you delegate their admin",
      "It points to the path inside the S3 bucket where that identity's logs are kept",
      "It defines the AWS Region in which that IAM identity is created and lives",
      "It fixes the order in which the policies attached to the identity get evaluated",
    ],
    correct: 0,
    explain: "The path is part of the ARN (<code>arn:aws:iam::account:role/PATH/name</code>) and organizes identities by team or project, so an administration policy with a wildcard on that path delegates management of just that branch. IAM is a global service with no Region, and policy order never affects evaluation. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Policy Simulator vs Access Analyzer",
    q: "You want to check, before deploying it, whether a specific IAM policy would allow a role to delete a particular S3 bucket — without executing the real action or leaving a trace in CloudTrail. Which tool would you use?",
    options: [
      "IAM Access Analyzer, reviewing the external access findings for that bucket",
      "IAM Policy Simulator, running simulate-principal-policy on that action",
      "AWS Config conformance packs, evaluating the policy against the rule set",
      "Amazon GuardDuty, which detects deletion attempts against that bucket",
    ],
    correct: 1,
    explain: "The Policy Simulator answers exactly 'would this policy allow this action on this resource?' without sending the real request. Access Analyzer audits the access posture that ALREADY exists, Config evaluates deployed configuration and GuardDuty detects suspicious activity after the fact: none of them answers a hypothetical, pre-deployment question. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_testing-policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Access Analyzer – Internal access",
    q: "Your AWS Organizations org has dozens of accounts. You want to know, taking into account the combined effect of identity policies, SCPs, and RCPs, which roles and users INSIDE your own organization could end up accessing a critical S3 bucket in another account — external access isn't the concern here. Which IAM Access Analyzer capability, launched in 2025, answers exactly this?",
    options: [
      "External access findings from an analyzer scoped to one single member account",
      "Unused access findings covering the roles in all member accounts",
      "Internal access findings, which evaluate policies, SCPs and RCPs together",
      "The IAM Credential Report consolidated across all member accounts",
    ],
    correct: 2,
    explain: "Internal access findings use automated reasoning to evaluate identity-based policies, SCPs and RCPs TOGETHER, and show which identities in the organization can reach S3, DynamoDB or RDS resources. External access findings only look at access from outside the zone of trust, and unused access findings talk about idle permissions, not about who can reach what. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "STS AssumeRoot",
    q: "A member account of the organization has Centralized Root Access Management enabled and its root credentials have been deleted. An administrator in the management account needs to temporarily unlock a corrupted S3 bucket policy in that member account, a task only root can perform. What is required to accomplish this?",
    options: [
      "sts:AssumeRole on a role with AdministratorAccess, equivalent to being root",
      "sts:AssumeRoleWithSAML against the corporate IdP using the administrators group",
      "Recovering the member account's root password through the standard flow",
      "sts:AssumeRoot from the management account, naming an AWS TaskPolicy",
    ],
    correct: 3,
    explain: "sts:AssumeRoot can only be called with credentials from the management account or an IAM delegated administrator, never with root credentials, and it requires naming an AWS managed TaskPolicy that scopes the session to that one task. AdministratorAccess does not cover root-reserved actions, and password recovery is exactly what this capability removes. <a href=\"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoot.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Access Analyzer – Custom policy checks",
    q: "Your platform team wants to block, in the CI/CD pipeline, any pull request that adds a specific dangerous permission (e.g. iam:CreateAccessKey) to an IAM policy, BEFORE it gets deployed. Which IAM Access Analyzer API fits this automated control?",
    options: [
      "CheckAccessNotGranted, which verifies the policy grants none of those actions",
      "ListFindingsV2, which enumerates every open finding of the account's analyzer",
      "GetGeneratedPolicy, which retrieves the policy generated from CloudTrail",
      "SimulatePrincipalPolicy, which simulates the action against a given principal",
    ],
    correct: 0,
    explain: "CheckAccessNotGranted, one of the automated-reasoning custom policy checks, takes a candidate policy plus a list of critical actions and returns PASS or FAIL: the natural CI/CD gate. Its sibling CheckNoNewAccess compares a new policy against a reference one. SimulatePrincipalPolicy needs the principal to already exist, so it cannot vet an undeployed policy. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-custom-policy-checks.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "aws:CalledVia",
    q: "You want to allow a user to run queries in Amazon Athena that internally call S3 and AWS Glue on their behalf, but prevent that same user from calling those S3/Glue actions directly outside the context of Athena. Which IAM condition key is designed exactly for this scenario?",
    options: [
      "aws:SourceArn, which identifies the resource that triggered the call by the service",
      "aws:CalledVia, which lists the services that called on the principal's behalf",
      "aws:ViaAWSService, which reports whether any AWS service made the call",
      "aws:PrincipalServiceName, which identifies the calling service principal",
    ],
    correct: 1,
    explain: "<code>aws:CalledVia</code> holds the ordered chain of AWS services that forwarded the request on the principal's behalf, so a StringEquals on <code>athena.amazonaws.com</code> lets you allow s3:GetObject only when it comes from Athena and deny the direct call. aws:ViaAWSService is a boolean and cannot say WHICH service, and aws:SourceArn belongs in trust policies against the confused deputy. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SCP – full IAM policy language (2025)",
    q: "Until recently, SCPs only supported a limited subset of the IAM policy language. After the September 2025 AWS Organizations update, what new syntax capability became available in SCPs?",
    options: [
      "SCPs became able to grant permissions like an identity-based policy",
      "SCPs became applicable to principals outside the organization too",
      "SCPs gained support for the full IAM policy language syntax",
      "SCPs began to be evaluated before any identity-based policy",
    ],
    correct: 2,
    explain: "SCPs now accept the full IAM policy language: conditions, specific resource ARNs, NotAction inside Allow statements, wildcards in the middle of an Action, and the NotResource element. That matches the expressiveness of a managed policy, but it does NOT change their nature: they remain guardrails that cap, never grant, and only apply to identities in the organization. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_syntax.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM Identity Center – Trusted Identity Propagation",
    q: "A corporate analyst, authenticated in IAM Identity Center, queries data in Amazon Athena/Redshift through Amazon QuickSight. The company wants the access logs for the underlying data in S3/Lake Formation to show the analyst's real corporate identity (not a generic service role), and wants data access permissions evaluated against their actual attributes/groups. Which IAM Identity Center mechanism enables this?",
    options: [
      "Permission sets assigned directly to the analyst in every data account",
      "Session policies applied to the service role that QuickSight uses",
      "Classic AssumeRoleWithSAML against the company's corporate IdP",
      "Trusted Identity Propagation, which carries the identity context",
    ],
    correct: 3,
    explain: "Trusted Identity Propagation adds the Identity Center user's identity context to the IAM role when one service calls another on their behalf (QuickSight, Athena, Redshift, EMR, OpenSearch, SageMaker Unified Studio). Data permissions and CloudTrail records then reflect the real corporate identity instead of a shared service role, with no IAM role per person. <a href=\"https://docs.aws.amazon.com/singlesignon/latest/userguide/trustedidentitypropagation-overview.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Multi-party approval",
    q: "The security team wants to ensure that no single person, acting alone, can restore/share data from a logically air-gapped AWS Backup vault in a ransomware recovery scenario — multiple authorized people must approve the operation before it executes. Which AWS governance capability, launched in 2025, is designed for this?",
    options: [
      "Multi-party approval, with teams that vote before the operation executes",
      "An SCP denying the operation unless aws:MultiFactorAuthPresent is true",
      "Permission boundaries combined with IAM Access Analyzer findings",
      "AWS Config conformance packs with automatic remediation via Systems Manager",
    ],
    correct: 0,
    explain: "Multi-party approval is an AWS Organizations capability that requires IAM Identity Center: you define approval teams with an M-of-N threshold and the protected operation waits until the votes are in. Its first integration was AWS Backup for logically air-gapped vaults. Requiring MFA is still one person, and Config remediates configuration rather than authorizing one-off operations. <a href=\"https://docs.aws.amazon.com/mpa/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Declarative Policies – EC2/VPC/AMI attributes",
    q: "You want to guarantee, for the ENTIRE organization and in a way that no account can drift from even with local AdministratorAccess, that no EC2 instance can use IMDSv1 and that no VPC can reach the internet through an Internet Gateway except for explicit exceptions. Which AWS Organizations mechanism enforces exactly this type of control?",
    options: [
      "An SCP denying ec2:RunInstances when a specific tag is missing",
      "Declarative policies, which pin IMDSv2 and VPC Block Public Access",
      "AWS Config managed rules with automatic remediation via Systems Manager",
      "An RCP on EC2 requiring aws:PrincipalOrgID on every single call",
    ],
    correct: 1,
    explain: "Declarative policies cover EC2 and VPC attributes such as 'VPC Block Public Access', 'Image (AMI) Block Public Access' and 'IMDSv2 enforcement'. Unlike an SCP, which denies specific API calls, they pin a desired configuration state in the control plane that survives new accounts and new APIs. Config detects and remediates after the fact; it does not prevent the drift. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "RCP – management account exemption",
    q: "A company deploys an RCP at the organization root to restrict S3 bucket access to identities inside the organization only. An engineer, authenticated as an IAM user in the Organization's MANAGEMENT account, accesses a bucket in a member account without any issue, even though that bucket should theoretically be blocked from external sources by that RCP. Why?",
    options: [
      "It is a mistake: the RCP should also be attached to the management account",
      "The user has MFA enabled, which exempts them from the organization's RCPs",
      "RCPs do not apply to identities in the organization's management account",
      "RCPs only apply to calls made from outside the bucket's own Region",
    ],
    correct: 2,
    explain: "A key RCP quirk — counterintuitive, and therefore heavily tested — is that they do NOT apply to requests made by principals in the organization's management account, even when the resource lives in a member account within the policy's scope. It is one more reason not to run day-to-day work from the management account: it escapes this class of guardrail. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IAM Roles Anywhere – ABAC with certificates",
    q: "A company uses IAM Roles Anywhere to issue credentials to on-premises servers, and wants the assumed role to automatically carry a session tag with the server's name, extracted from the X.509 certificate itself used to authenticate, so it can apply ABAC policies without managing tags manually. Is this possible, and how?",
    options: [
      "No: session tags can only be added by hand when calling CreateSession",
      "No: IAM Roles Anywhere supports no form of session tagging at all",
      "Yes, but only with certificates issued by public ACM, never by a private CA",
      "Yes: Subject and Issuer RDNs are mapped to session PrincipalTags",
    ],
    correct: 3,
    explain: "IAM Roles Anywhere applies attribute mapping rules that automatically turn the Relative Distinguished Names of the presented certificate's Subject (CN, OU...) and Issuer into PrincipalTags on the resulting session. That lets you write ABAC policies such as 'this server may only reach resources tagged with the same OU as its certificate' with no manual tag management. <a href=\"https://docs.aws.amazon.com/rolesanywhere/latest/userguide/attribute-mapping.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Verified Permissions – BatchIsAuthorized",
    q: "Your SaaS application needs to render a list of 25 documents and decide, for each one, whether the current user can view it and whether they can edit it — up to 50 authorization decisions for a single page load. Making 50 individual IsAuthorized calls would add too much latency. What does Amazon Verified Permissions offer for this case?",
    options: [
      "BatchIsAuthorized, which groups up to 30 decisions into a single call",
      "Nothing: you must call IsAuthorized once for each pending decision",
      "Exporting the Cedar policies and evaluating them client-side via the SDK",
      "Caching the decisions in Lambda@Edge in front of the application",
    ],
    correct: 0,
    explain: "BatchIsAuthorized groups up to 30 authorization decisions for one principal or resource into a single call, which is exactly the shape of a list or table where you must decide at once which actions to render. Evaluating Cedar on the client moves the decision to an untrusted place, and edge caching solves neither the first load nor invalidation. <a href=\"https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_BatchIsAuthorized.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Mandatory permission boundary on role creation",
    q: "You want to let developers create their own IAM Roles (iam:CreateRole) but guarantee they can NEVER create a role without a specific permission boundary attached to it — closing the door on self-granting admin permissions via a new boundary-less role. Which policy mechanism enforces exactly this restriction?",
    options: [
      "An SCP denying iam:CreateRole to every identity in the whole account",
      "An iam:PermissionsBoundary condition in the developer's own policy",
      "It cannot be enforced: attaching the boundary is up to whoever creates the role",
      "A resource-based policy attached to the permission boundary itself",
    ],
    correct: 1,
    explain: "The <code>iam:PermissionsBoundary</code> condition key, with StringEquals against the allowed boundary's ARN, is added to the policy granting the developer iam:CreateRole and iam:PutRolePermissionsBoundary: if the call does not attach exactly that boundary, it is denied. This is AWS's standard pattern for delegating role creation without opening a privilege-escalation path. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "STS – role chaining and session duration",
    q: "A user assumes Role A (a 12-hour session) and, using those temporary credentials, tries to assume Role B (role chaining), also requesting --duration-seconds pointing to 12 hours. What happens to the maximum duration of the resulting Role B session?",
    options: [
      "It can last up to 12 hours, just like the Role A session",
      "It fails: STS forbids chaining roles from temporary credentials",
      "It is capped at 1 hour, whatever MaxSessionDuration Role B has",
      "It depends on whether the original user authenticated with MFA",
    ],
    correct: 2,
    explain: "AWS STS explicitly caps role chaining: if you use the temporary credentials from one AssumeRole to call AssumeRole again, the resulting session lasts at most 1 hour, regardless of the MaxSessionDuration configured on the target role — asking for more returns an error. It is a heavily tested detail because it contradicts the expectation that the role's setting wins. <a href=\"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "RCP – aws:PrincipalOrgID vs aws:ResourceOrgID",
    q: "When designing 'data perimeter' guardrails with RCPs, what is the practical difference between conditioning an RCP on aws:PrincipalOrgID versus on aws:ResourceOrgID?",
    options: [
      "They are synonyms: both of them return the organization ID of the resource",
      "aws:PrincipalOrgID is deprecated and replaced by aws:SourceOrgID",
      "aws:ResourceOrgID can only be used in SCPs, never inside an RCP",
      "aws:PrincipalOrgID looks at the organization of the calling identity",
    ],
    correct: 3,
    explain: "aws:PrincipalOrgID is the IDENTITY-perimeter key: it compares the calling principal's organization against a fixed value. aws:ResourceOrgID describes the organization the RESOURCE belongs to, and lets an RCP express 'only if the caller belongs to the same organization as the resource', with no account lists to maintain. Both are current and complementary. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Access Analyzer – policy generation",
    q: "A team has been running an IAM role with the AdministratorAccess managed policy 'temporarily' for 6 months, and now wants to generate a least-privilege policy based on what that role has ACTUALLY used according to its CloudTrail activity, instead of writing one by hand from scratch. Which IAM Access Analyzer feature solves this directly?",
    options: [
      "Policy generation based on the role's recorded CloudTrail activity",
      "The external access findings of the analyzer created in that account",
      "The unused access findings, which write the replacement policy",
      "The IAM Credential Report, which lists the permissions exercised",
    ],
    correct: 0,
    explain: "Access Analyzer policy generation reviews a role or user's CloudTrail events over a window of up to 90 days and proposes a policy containing the services and actions actually used, as a least-privilege starting point. Unused access findings point at what is superfluous but write no policy, and the Credential Report only reports credential state. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-policy-generation.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Verified Permissions – policy templates",
    q: "Your multi-tenant SaaS application has the same authorization pattern repeated for hundreds of tenants ('the owner can edit their own resource'), and you want to avoid duplicating the same Cedar policy hundreds of times in the policy store, one per tenant. Which Amazon Verified Permissions feature is designed exactly for this?",
    options: [
      "Creating a separate policy store per tenant and keeping them in sync",
      "Policy templates instantiated as template-linked policies per tenant",
      "Writing one static policy for each concrete user and resource pair",
      "It is not possible: the Cedar language cannot parameterize policies",
    ],
    correct: 1,
    explain: "A policy template declares a single Cedar policy with <code>?principal</code> and <code>?resource</code> placeholders, and each template-linked policy instantiates it with concrete IDs: the logic lives in one place and updating it propagates to every instance. A policy store per tenant multiplies the management surface, and one policy per pair does not scale. <a href=\"https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/policy-templates.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "aws:PrincipalOrgID vs aws:PrincipalOrgPaths",
    q: "An organization has an OU named 'Sandbox' under the root, and wants an RCP that allows access to an S3 bucket only to identities that specifically belong to that OU (and its sub-OUs), not the entire organization in general. Which condition key is appropriate?",
    options: [
      "aws:PrincipalOrgID, compared against the whole organization's ID",
      "aws:PrincipalAccount, listing the OU's accounts by hand",
      "aws:PrincipalOrgPaths, which compares the principal's OU path",
      "aws:ResourceOrgID, pointing at the OU where the bucket lives",
    ],
    correct: 2,
    explain: "aws:PrincipalOrgID only identifies the whole organization (o-xxxxxxxxxx) and cannot distinguish OUs. To scope to one branch of the tree you use aws:PrincipalOrgPaths, which holds the principal's full OU-ID path and supports prefix matching, covering the OU and everything beneath it. Listing accounts by hand works until somebody creates the next one. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Root user – AssumeRoot task policies",
    q: "When a management-account administrator calls sts:AssumeRoot to perform a root task in a member account, what exactly determines what that temporary root session can do?",
    options: [
      "Nothing: an AssumeRoot session carries unrestricted root privileges",
      "An SCP with an explicit Allow on the root:* action in that account",
      "The permission boundary root had before its keys were deleted",
      "An AWS managed TaskPolicy that scopes the session to that task",
    ],
    correct: 3,
    explain: "Unlike traditional root, which has no limits, sts:AssumeRoot requires naming one of the AWS managed TaskPolicies, designed for specific tasks that legitimately need root (unlocking a bucket policy, fixing a KMS key policy, managing root's own credentials). There is no unrestricted-root option: by design it is always a minimally scoped session. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user-privileged-task.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Unused access analyzer – tracking period",
    q: "When configuring an unused access analyzer in IAM Access Analyzer, what does the 'tracking period' parameter control?",
    options: [
      "The window over which real usage of each permission is observed",
      "How long the analyzer takes to produce its very first finding",
      "The deadline after which an unused role is deleted automatically",
      "How often the KMS key that encrypts the findings gets rotated",
    ],
    correct: 0,
    explain: "The tracking period defines how many days (1 to 365, 90 by default) Access Analyzer observes real usage before calling something 'unused'. Key exam detail: only identities and permissions that existed for the ENTIRE period are evaluated, so a role created 10 days ago under a 90-day tracking period yields no finding yet. Access Analyzer never deletes roles by itself. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-create-unused.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "RCP – supported services",
    q: "A security team wants to use an RCP to centrally restrict access to the organization's managed NoSQL database tables, requiring that only identities inside the organization itself can read them, even if some identity or resource policy accidentally exposes them externally. Following RCP support expansions through 2026, which service allows enforcing this directly via RCP?",
    options: [
      "Amazon RDS, supported by RCPs ever since their 2024 launch",
      "Amazon DynamoDB, added to the services that RCPs support",
      "Amazon Redshift, supported by RCPs since their first release",
      "None: RCPs only cover object storage in Amazon S3 buckets",
    ],
    correct: 1,
    explain: "RCPs launched in November 2024 covering S3, STS, KMS, SQS and Secrets Manager, and AWS has progressively expanded the list with ECR, OpenSearch Serverless, Cognito, CloudWatch Logs and Amazon DynamoDB. Beyond the specific list, the conceptual point is that an RCP only bites on the services explicitly supported at the time, not on the whole catalogue. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Data perimeter – SCP vs RCP trap",
    q: "An organization configures an SCP that denies any s3:GetObject action unless the principal belongs to the organization (using aws:PrincipalOrgID). Yet an external third party manages to read an object from an organization S3 bucket because the bucket has a bucket policy granting them explicit Allow access. Why didn't the SCP prevent this?",
    options: [
      "The SCP has a syntax error inside its Condition block element",
      "S3 does not allow an SCP to restrict its object read actions at all",
      "SCPs only restrict the identities that belong to the organization",
      "SCPs are only evaluated for calls made from the AWS console",
    ],
    correct: 2,
    explain: "This is the canonical reason RCPs exist: an SCP caps what identities INSIDE your organization can do, but an external principal arriving via a bucket policy never passes through that SCP, because SCPs are not evaluated against principals outside the organization. Closing the gap requires an RCP, which constrains the resource no matter who calls. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SCP – multi-level evaluation across the OU tree",
    q: "An account hangs off OU-Production, which in turn hangs off the organization root. The root has an SCP that allows s3:*, OU-Production has an SCP that explicitly denies s3:DeleteBucket, and the account itself has no additional SCPs. Can s3:DeleteBucket be executed in that account?",
    options: [
      "Yes: the root SCP allows s3:* and wins for sitting higher up the tree",
      "Yes: an OU-level SCP has no effect if the account has no SCP of its own",
      "Yes: among conflicting SCPs only the most recently attached one counts",
      "No: an explicit Deny at any level of the path blocks the action",
    ],
    correct: 3,
    explain: "SCPs are evaluated cumulatively along the ENTIRE path from the organization root down to the account, through every intermediate OU: the effective permission is the intersection of what each level allows, and an explicit Deny anywhere blocks the action regardless of the levels above. How recently a policy was attached never affects evaluation. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_evaluation.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Cross-account access",
    q: "An application in account A must assume a role in account B. Which TWO elements are indispensable?",
    options: [
      "A trust policy on the account B role authorizing the principal in A",
      "Both accounts belonging to one and the same organization in AWS Organizations",
      "An sts:AssumeRole permission in the identity policy of the principal in A",
      "A VPC peering between the accounts so that STS can route the request",
    ],
    correct: [0, 2],
    explain: "Cross-account access requires <b>both ends</b>: the resource (the role) must trust the caller, and the caller must be permitted to call. It is the classic case where an Allow on one side alone is not enough. Organizations isn't required — cross-account works between unrelated accounts — nor is network connectivity, because STS is a public service endpoint, not something living in your VPC. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Sources of an explicit Deny",
    q: "A user gets AccessDenied despite an identity policy allowing the action. In which TWO places could the blocking Deny live?",
    options: [
      "In the IAM console, which blocks the actions flagged as dangerous",
      "In a Service Control Policy attached to the OU or to the account",
      "In the CloudTrail history, which revokes permissions used improperly",
      "In the resource-based policy of the resource being accessed",
    ],
    correct: [1, 3],
    explain: "An explicit Deny in <b>any</b> applicable policy always wins: identity policy, resource policy, SCP, RCP, permission boundary or session policy. Here the two real candidates are the SCP and the resource policy. The IAM console doesn't block actions on its own, and CloudTrail is an audit log: it <b>observes</b>, it never revokes. Confusing a logging service with an enforcement one is a classic distractor. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Data perimeter",
    q: "You want your S3 buckets accessible only by identities from your own organization and only from your network. Which TWO condition keys would you use?",
    options: [
      "aws:PrincipalOrgID, to require the caller to belong to your organization",
      "aws:RequestedRegion, to limit access to one single AWS Region of your choice",
      "aws:CurrentTime, to allow access only within working hours on weekdays",
      "aws:SourceVpce, to require the request to arrive through your VPC endpoint",
    ],
    correct: [0, 3],
    explain: "A data perimeter is built on two axes: <b>who</b> (identity perimeter, via aws:PrincipalOrgID) and <b>from where</b> (network perimeter, via aws:SourceVpce or aws:SourceIp). The other two condition keys are real and valid, but they scope Region and time of day: they answer neither the identity nor the network question posed here. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/building-a-data-perimeter-on-aws/building-a-data-perimeter-on-aws.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Permission boundaries",
    q: "You will let developers create their own roles without being able to escalate privileges. Which TWO statements about permission boundaries are correct?",
    options: [
      "The boundary replaces the identity policy: attaching the boundary is enough",
      "A boundary grants nothing by itself: it caps what a policy can grant",
      "You can require by condition that every role created carries a given boundary",
      "Boundaries are attached to the resources, just like the bucket policies of S3",
    ],
    correct: [1, 2],
    explain: "Effective permission is the <b>intersection</b> of the identity policy and the boundary, so the boundary alone grants nothing and doesn't replace the policy. The <code>iam:PermissionsBoundary</code> condition is precisely the mechanism for delegating role creation without allowing escalation. And boundaries attach to <b>identities</b> (users and roles), not to resources. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Federation with IAM Identity Center",
    q: "A company with 3,000 employees in a corporate IdP wants to grant access to 60 AWS accounts without creating IAM users. Which TWO statements describe the right approach?",
    options: [
      "You must create one IAM user per employee in each of the 60 AWS accounts",
      "All employees should share one common access key so management gets simpler",
      "Identity Center federates with the IdP and assigns permission sets by group",
      "Users receive temporary STS credentials, not long-lived access keys",
    ],
    correct: [2, 3],
    explain: "<b>Identity Center</b> with <b>permission sets</b> assigned to groups is the recommended pattern at scale, and federation always issues <b>temporary STS credentials</b>. Creating 3,000 users across 60 accounts is exactly the problem federation removes (180,000 identities to maintain). Sharing one key between people destroys attribution: it is never the answer. <a href=\"https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Active Directory and access to AWS",
    q: "A company with on-premises Active Directory wants employees to sign in to AWS with corporate credentials and, on top of that, wants its Windows applications on EC2 to join a domain managed inside AWS. Which combination fits?",
    options: [
      "Creating one IAM user per employee and syncing them with a script against AD",
      "AWS Managed Microsoft AD as the directory, federated into IAM Identity Center",
      "Amazon Cognito with a user pool replicating the domain accounts",
      "AD Connector as the directory and one IAM role per group in the local domain",
    ],
    correct: 1,
    explain: "The two requirements pull in different directions and only one option covers both. For console access <b>AD Connector</b> would do, proxying authentication to the on-premises AD without storing anything in AWS; but <em>domain-joining instances</em> needs a real directory inside AWS, and that is <b>AWS Managed Microsoft AD</b>, which also plugs into IAM Identity Center as an identity source and can trust the corporate domain. Hand-synced IAM users are duplicated credentials. And Cognito is built for your application's identities, not your employees. <a href=\"https://docs.aws.amazon.com/directoryservice/latest/admin-guide/directory_microsoft_ad.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["iam"] = QUIZ_DATA;
