// Question bank for the module: security operations, identity and compliance (SC-100, domain 2).
// Every explanation ends with a link to the official Microsoft Learn documentation.

var QUIZ_DATA = [
  {
    tag: "XDR versus SIEM",
    q: "A customer on Microsoft 365 E5 wants the SOC to see, correlated, attacks that start in an email, continue on the laptop and end in an Entra ID account. The whole estate is Microsoft and there are no plans to ingest other sources. What do you recommend?",
    options: [
      "Deploy Microsoft Sentinel and ingest the Defender for Office 365, Defender for Endpoint and Entra ID connectors",
      "Use Microsoft Defender XDR, which already correlates those signals into a single incident",
      "Export each product's alerts to shared storage and correlate them with your own queries",
      "Deploy Sentinel alongside Defender XDR and work incidents in both portals",
    ],
    correct: 1,
    explain: "Defender XDR <b>already</b> correlates identity, endpoint, email and Microsoft cloud apps into assembled incidents, with nothing to connect and no ingestion cost. Adding Sentinel here means paying to rebuild by hand what comes finished. A SIEM earns its place when a foreign source appears — a third-party firewall, another cloud, a line-of-business application — or when long retention is required; none of that is in the scenario. And working in two portals is exactly what the unified portal removes. <a href=\"https://learn.microsoft.com/en-us/unified-secops-platform/overview-unified-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "When the SIEM earns its place",
    q: "The same organization now brings in third-party network appliances, an in-house line-of-business application and AWS subscriptions, and needs all of it correlated with what Defender XDR already sees, with two years of retention. What does the design add?",
    options: [
      "Extend the Defender XDR licences so it can ingest the new sources",
      "A second tenant dedicated to the sources that are not Microsoft",
      "Analytics rules in Defender for Cloud Apps over the firewall records",
      "Microsoft Sentinel, with Defender XDR connected as one of its sources",
    ],
    correct: 3,
    explain: "Defender XDR only sees its own sensors: arbitrary sources cannot be added to it by licensing. <b>Sentinel</b> is the piece that ingests foreign telemetry, and the reference pattern is to connect Defender XDR into Sentinel so the SOC keeps one incident queue covering both. A second tenant fragments identity without solving correlation, and Defender for Cloud Apps governs SaaS — it is not a SIEM. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Auditing user activity",
    q: "Legal needs to answer, up to a year back, who accessed a specific mailbox and who exported data from Microsoft 365. Which capability meets that requirement?",
    options: [
      "Microsoft Purview Audit, at the tier with extended retention",
      "Entra ID sign-in logs exported to Log Analytics",
      "Defender for Office 365 alerts about suspicious mailbox access",
      "A Sentinel playbook that records every access in a custom table",
    ],
    correct: 0,
    explain: "The question is about <b>activity</b>, not detection: who did what to which object. That lives in <b>Purview Audit</b>, whose higher tier extends retention and adds high-value events such as mailbox access. Sign-in logs say who got in, not what they touched afterwards. Alerts cover the suspicious, not the complete history. And a playbook cannot record what already happened. <a href=\"https://learn.microsoft.com/en-us/purview/audit-solutions-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Ingestion cost",
    q: "Sentinel costs have risen sharply because of network flow records and verbose proxy logs, which make up most of the volume and almost never trigger an alert, though regulation requires keeping them. Which design solves both?",
    options: [
      "Reduce retention across the whole workspace to the minimum regulation might allow",
      "Move them to a cheaper table tier and keep in analytics what feeds rules",
      "Stop ingesting them and keep them only on the appliance that produces them",
      "Create one workspace per source to spread the cost across subscriptions",
    ],
    correct: 1,
    explain: "SIEM cost is governed by deciding <b>which data needs analytics capability</b> and which only needs to be stored and queryable. Auxiliary table tiers and long-term storage exist for this: you keep what regulation demands at a fraction of the price and reserve the expensive tier for what feeds detections. Cutting retention globally collides with the regulation, dropping ingestion breaks investigation, and multiplying workspaces splits the bill without reducing it. <a href=\"https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Governing servers outside Azure",
    q: "A customer has 400 servers spread across their data centre and a third-party cloud. They want the same configuration policies applied to them as to their Azure machines, and to see them in Defender for Cloud. What is indispensable in the design?",
    options: [
      "A site-to-site VPN tunnel between the data centre and the Azure virtual network",
      "Migrate those servers to Azure so they fall under the same control plane",
      "A dedicated Log Analytics workspace in each of the environments",
      "Azure Arc, which projects those servers into the Azure control plane",
    ],
    correct: 3,
    explain: "<b>Azure Arc</b> is the piece that turns an outside server into an Azure resource for governance purposes: from then on Azure Policy, Machine Configuration and Defender for Servers apply to it exactly as to a native machine. A VPN provides network connectivity, which is a different problem. Migrating contradicts the scenario. And a workspace carries logs but does not let you govern the server's configuration. <a href=\"https://learn.microsoft.com/en-us/azure/azure-arc/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Posture in other clouds",
    q: "The same customer also wants the security recommendations for their AWS accounts and GCP projects in the same place as the Azure ones, without installing anything on those workloads. What do you recommend?",
    options: [
      "The Defender for Cloud multicloud connectors, which read configuration without agents",
      "Deploy the Azure Monitor agent on every AWS and GCP instance",
      "Export AWS and GCP configuration to Sentinel and write custom analytics rules",
      "Replicate the critical workloads into Azure so Defender for Cloud can assess them",
    ],
    correct: 0,
    explain: "The <b>multicloud connectors</b> in Defender for Cloud authenticate against AWS and GCP and assess their configuration from outside, with no agent on the workloads, which is precisely the constraint. Deploying agents contradicts it. Sentinel correlates events; it does not produce posture recommendations. And replicating workloads so you can look at them is not an architectural answer. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/multicloud\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Automation rule or playbook",
    q: "The SOC wants Sentinel incidents of one specific type, almost always false positives, to close themselves with a comment and without spending on Logic Apps runs. Which mechanism fits?",
    options: [
      "A playbook that evaluates the incident and calls the Sentinel API to close it",
      "Disable the analytics rule that generates those incidents",
      "A suppression rule in Defender XDR on the originating alert",
      "A Sentinel automation rule with the condition and the closing action",
    ],
    correct: 3,
    explain: "<b>Automation rules</b> are native to Sentinel and do exactly this — filter on a condition and close, tag, assign or change severity — without invoking a Logic App, which is the cost constraint. A playbook would do the job but bills per run. Disabling the rule blinds the detection entirely. And suppressing in Defender XDR acts earlier, on a signal you still want. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/automate-incident-handling-with-automation-rules\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Acting outside Sentinel",
    q: "Now they want a high-severity incident to automatically open a ticket in the corporate ITSM and post to a Teams channel. What does the design add?",
    options: [
      "An automation rule, which can invoke external systems on its own",
      "A continuous export of the incident to the ITSM's storage",
      "A playbook built on Logic Apps, triggered from an automation rule",
      "An ITSM data connector in Sentinel",
    ],
    correct: 2,
    explain: "When the action leaves <b>Sentinel</b>, you need a <b>playbook</b>: a Logic App with hundreds of connectors, usually triggered from an automation rule that filters on severity. Rules on their own act within the incident. An export moves data but does not create the ticket. And a data connector brings information from the ITSM into Sentinel, which is the opposite direction. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/automate-responses-with-playbooks\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Hunting versus detection",
    q: "Leadership asks for the ability to proactively look for attacker activity that no rule has detected yet. Which statement describes what must be designed?",
    options: [
      "Increase the number of active analytics rules to cover many more known techniques",
      "Automate the response so that incidents get closed much faster",
      "Lower the alert severity threshold so that less activity slips through",
      "Threat hunting: queries over historical data starting from a hypothesis",
    ],
    correct: 3,
    explain: "By definition, what no rule detects will not be found by adding rules: it is found by <b>hunting</b> — forming a hypothesis about how an attacker would behave and looking for it in data you already hold. That is why hunting depends on <em>retention</em> and query access rather than on the detection catalogue. Lowering thresholds only adds noise, and automating response speeds up what is already detected. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/hunting\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detection coverage",
    q: "You are asked to show the security committee which attack techniques the organization would not notice today. How do you frame it?",
    options: [
      "From the number of alerts the SOC closes each month and its mean time to respond",
      "Map the active rules against the techniques in the MITRE ATT&CK matrix",
      "From the tenant's current Microsoft Secure Score",
      "From the result of the last external penetration test",
    ],
    correct: 1,
    explain: "Detection coverage is measured against a <b>catalogue of techniques</b>, and the standard is MITRE ATT&CK: active rules are mapped onto the matrix and whatever stays blank is the gap. Alert volume measures activity, not coverage. Secure Score measures configuration posture. And a penetration test gives a point-in-time sample of what one team achieved, not the full map. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/mitre-coverage\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The ATT&CK matrix for OT",
    q: "The coverage analysis includes the manufacturing plant, with PLCs and industrial control systems. Which MITRE ATT&CK matrix applies to that part?",
    options: [
      "ICS, specific to industrial control systems",
      "Enterprise, which already covers any operating system in the environment",
      "Mobile, because of the operator terminals on the plant floor",
      "Enterprise again, restricted to the initial access techniques",
    ],
    correct: 0,
    explain: "MITRE publishes <b>three matrices</b> and they are not interchangeable: Enterprise for IT, Mobile for iOS and Android, and <b>ICS</b> for industrial control systems, with techniques that do not exist in IT — manipulating PLC logic, inhibiting a safety function. In a plant scenario the ICS matrix is the one that applies, and it is the one that goes with Defender for IoT. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/mitre-coverage\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Phases of the response workflow",
    q: "Reviewing a customer's incident response plan, you see detection and containment are well defined, but it does not say who decides to disconnect a production system or how that is communicated to the business. What is missing from the design?",
    options: [
      "The definition of decision-making roles and the incident communication plan",
      "More analytics rules covering the scenarios specific to the production environment",
      "A playbook that automatically isolates any system raising a high alert",
      "A second Sentinel workspace dedicated exclusively to the production environment",
    ],
    correct: 0,
    explain: "An incident response plan is not only technology: what fails in real scenarios is <b>who has the authority</b> to make a business decision under pressure and <b>how it is communicated</b> upwards and outwards. Without that, containment stalls while somebody hunts for an approver. More rules do not help anyone decide, isolating production automatically can cause more damage than the incident, and an extra workspace is an unrelated platform decision. <a href=\"https://learn.microsoft.com/en-us/security/operations/incident-response-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Identity for an AI agent",
    q: "A team deploys an AI agent that queries SharePoint and raises tickets on its own, with no person behind each run. Security requires being able to audit what the agent did and to limit what it can reach. What do you propose?",
    options: [
      "Give the agent its own identity with Microsoft Entra Agent ID and apply conditional access to it",
      "Run it with the credentials of the user who invoked it, so it inherits their permissions",
      "Register an application with a shared secret stored in the service configuration",
      "Create a service user with a long password and exclude it from conditional access policies",
    ],
    correct: 0,
    explain: "An agent acting on its own is a principal, and as such it needs an <b>identity of its own</b>. <b>Entra Agent ID</b> provides one with a lifecycle, an owner and an audit trail, and because it is a first-class identity, <b>conditional access</b> policies apply to it, which is what bounds where it can reach and under what conditions. Inheriting the user's identity hands it all of their permissions and makes it impossible to tell in the log who acted. A shared secret is a credential nobody rotates. And excluding it from conditional access removes the very control being asked for. <a href=\"https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-agent-id\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "An agent's blast radius",
    q: "After giving several agents their own identities, leadership asks what would happen if one of them were compromised. What lets you answer that?",
    options: [
      "The Entra ID sign-in log filtered by those agent identities",
      "A quarterly access review over the registered owners of each of the agents",
      "Blast radius analysis for agent identities in Defender XDR",
      "The tenant's Secure Score once all the agents have been registered",
    ],
    correct: 2,
    explain: "The question is not what the agent has done but <b>how far it would reach</b> if someone controlled it, and that is answered by analysing its effective scope: which resources it accesses and what it could reach from there. That is blast radius analysis over agent identities in <b>Defender XDR</b>. Sign-in logs are history, not potential reach. An access review confirms whether the agent should exist. And Secure Score measures tenant configuration. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-365-defender\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Agent lifecycle",
    q: "A team deploys several AI agents that query business data. Security wants to be able to answer, at any moment, who is responsible for each agent, what it accesses and whether it is still needed. Which part of the design covers that?",
    options: [
      "Keeping a sheet in an internal repository with the owner and the declared purpose of every deployed agent",
      "Registering each agent with Entra Agent ID, with an owner, and subjecting it to access reviews like any identity",
      "Tagging the Azure resources hosting the agents with the name of the team that deployed them and their cost centre",
      "Reviewing the application audit logs monthly to work out which agent accessed which piece of data",
    ],
    correct: 1,
    explain: "All three questions — who is accountable, what it accesses, whether it is still needed — are exactly what <b>identity governance</b> answers, and that is why the agent has to be a directory identity rather than a row in a sheet. With <b>Entra Agent ID</b> it inherits an owner, an access record and <b>access reviews</b>. The sheet and the resource tags enforce nothing. And inferring it from logs is forensics, not governance. <a href=\"https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-agent-id\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "An agent's permissions",
    q: "An AI agent needs to read from an Azure Storage container and write to a queue. The team proposes giving it Contributor over the subscription \"so we don't have to adjust it every time\". What do you recommend?",
    options: [
      "Accept it while the agent is in testing and review the granted permissions before it moves to production",
      "Replace the role with a storage account access key held in Key Vault and rotated on a schedule",
      "Assign it only the data roles over the specific container and queue it needs",
      "Keep Contributor and offset it with a conditional access policy restricting where it connects from",
    ],
    correct: 2,
    explain: "An agent is just another principal and <b>least privilege</b> applies to it as it does to a person: data roles scoped to the container and the queue, not Contributor over the subscription. \"It's in testing\" is how excessive permissions become permanent. The access key reintroduces a secret to guard, when the identity already avoids having one. And conditional access bounds <em>where from</em>, not <em>what it can do</em>: a compromised agent connecting from the right place would still be an administrator. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "SaaS on an unmanaged device",
    q: "Access to a SaaS application is allowed from personal devices, but documents must not be downloadable onto them. The application has no feature that prevents it. What solves this?",
    options: [
      "A conditional access policy that blocks sign-in from non-compliant devices",
      "Publishing the application through Microsoft Entra Private Access",
      "A Purview data loss prevention policy on the personal endpoint",
      "Conditional access app control with a session policy",
    ],
    correct: 3,
    explain: "When the session must be allowed but <b>constrained</b>, the piece is conditional access app control: traffic is routed through <b>Defender for Cloud Apps</b> as a reverse proxy and a session policy blocks the download while still allowing viewing and editing in the browser. Blocking sign-in breaks the requirement to allow access. Endpoint DLP needs to manage a device that is personal. And Private Access publishes internal resources; it does not govern a third-party SaaS. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/what-is-defender-for-cloud-apps\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Three layers of access",
    q: "Reviewing an access design for internal applications, you see it only defines who may authenticate and with what MFA. Which two layers are missing for it to be complete?",
    options: [
      "The network layer, how the request arrives, and the application layer, what can be done inside",
      "More authentication methods and a second identity provider configured as a fallback",
      "A complete user inventory and a properly documented joiner and leaver process",
      "Encryption of data at rest and periodic rotation of the application's keys",
    ],
    correct: 0,
    explain: "A complete access design has three layers: <b>identity</b> (who, and under what conditions), <b>network</b> (how the request arrives: Private Access for internal, private endpoints for PaaS) and <b>application</b> (what can be done inside, with session policies). The scenario covers only the first. More authentication methods reinforce that same layer. An inventory is identity governance. And encryption protects data at rest, which is a different axis. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Hybrid authentication and resilience",
    q: "A customer uses pass-through authentication against their AD DS. A prolonged data centre outage left everyone unable to sign in to Microsoft 365 as well. They want to avoid that without giving up local validation day to day. What do you recommend?",
    options: [
      "Add more authentication agents spread across the same data centre",
      "Move to federation with AD FS and publish a second node in the cloud",
      "Shorten token lifetimes so they get renewed against the cloud",
      "Enable password hash synchronization as a fallback method",
    ],
    correct: 3,
    explain: "With PTA and with federation, authentication depends on the on-premises environment answering: if it goes down, nobody signs in to the cloud either. <b>Password hash synchronization</b> as a fallback lets Entra ID validate on its own when on-premises is unavailable, without changing the primary method. More agents in the same data centre do not cover the loss of that data centre. AD FS deepens the dependency. And shortening tokens makes it worse: it forces more authentication against the thing that is down. <a href=\"https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-phs\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detecting leaked credentials",
    q: "Security wants Entra ID to raise an alert when an employee's password shows up in a public breach. The customer authenticates today with pure federation and does not synchronize hashes. What is required?",
    options: [
      "Enable password hash synchronization, even though authentication stays federated",
      "Buy Microsoft Defender for Identity for every domain controller in the forest",
      "Turn on Entra ID smart lockout in the tenant and tune its thresholds",
      "Publish a conditional access policy based on sign-in risk",
    ],
    correct: 0,
    explain: "Entra ID can only compare a leaked password against your user's if it holds their <b>synchronized hash</b>; with pure federation it does not, and that detection simply does not work, even though authentication keeps happening against AD FS. Defender for Identity watches the on-premises AD DS, not public breaches. Smart lockout stops brute force. And a risk policy <em>consumes</em> the signal that is not being produced yet. <a href=\"https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Access for a partner company",
    q: "A partner company needs access to an internal application. You do not want to manage their passwords or their joiners and leavers, and the same conditional access as for your own staff must apply. Which design fits?",
    options: [
      "Create users in your own tenant and synchronize them from the partner's directory",
      "Invite them as B2B users, governed with cross-tenant access settings",
      "Publish the application on the internet with its own authentication and an allow list",
      "Establish a forest trust between the two AD DS environments",
    ],
    correct: 1,
    explain: "<b>B2B</b> is exactly this: the partner signs in with their home identity — their company handles joiners, leavers and passwords — while existing as a guest in your tenant, so your conditional access applies to them. <b>Cross-tenant access settings</b> are the governance piece: which tenants, which users, and whether you accept the MFA they already performed at home. Creating your own users takes on the lifecycle you wanted to avoid, publishing with separate authentication creates a silo, and a forest trust is disproportionate. <a href=\"https://learn.microsoft.com/en-us/entra/external-id/what-is-b2b\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Proving an attribute without storing it",
    q: "A service needs to confirm that whoever requests access holds a specific qualification, without storing their personal data and without depending on the directory of the issuing body. What fits?",
    options: [
      "An application that queries the issuing body's directory over an API",
      "An Entra ID dynamic group based on a custom attribute",
      "A B2B flow with manual review of the documentation provided",
      "Verifiable credentials with Microsoft Entra Verified ID",
    ],
    correct: 3,
    explain: "<b>Verifiable credentials</b> solve exactly this case: the issuer signs a credential, the person holds and presents it, and the verifier checks the signature <b>without contacting</b> the issuer or storing the data. Querying an API creates the dependency the scenario rules out. A dynamic group requires the attribute to already live in your directory. And manual review neither scales nor avoids storing the documentation. <a href=\"https://learn.microsoft.com/en-us/entra/verified-id/decentralized-identifier-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Immediate session revocation",
    q: "After disabling a compromised account, the user kept reaching Exchange Online for nearly an hour with the token they already held. What fixes that?",
    options: [
      "Reduce access token lifetime to a few minutes across the whole tenant",
      "Continuous access evaluation, which applies revocation almost immediately",
      "A conditional access policy that requires MFA on every request",
      "A Sentinel playbook that closes sessions whenever an account is disabled",
    ],
    correct: 1,
    explain: "An access token stays valid until it expires even after the account is disabled. <b>Continuous access evaluation</b> fixes this by having the resource and the identity provider talk to each other: on a critical event — account disabled, password changed, risk raised — the session is cut almost at once. Shortening tokens tenant-wide narrows the window at the cost of far more latency and load. Requiring MFA does not invalidate an already issued token. And a playbook arrives afterwards, with the delay of its own run. <a href=\"https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-continuous-access-evaluation\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "User risk or sign-in risk",
    q: "Two different responses are wanted: if Entra ID believes an account is compromised, force a secure password change; if only this particular sign-in looks anomalous, require MFA. How is that designed?",
    options: [
      "Two policies: one on user risk and one on sign-in risk",
      "A single risk policy with the threshold in the middle and MFA as the grant control",
      "One policy based on network location and another based on device state",
      "Sentinel analytics rules triggering different playbooks depending on the alert type",
    ],
    correct: 0,
    explain: "Entra ID Protection calculates <b>two distinct risks</b>: <em>user</em> risk — the likelihood the identity is compromised — and <em>sign-in</em> risk — how anomalous this particular request is. They map to two conditional access policies and to two different remediations: secure password change for the first, MFA for the second. A single policy cannot give different answers. Location and device are other signals. And taking it to the SIEM adds delay to something the engine resolves inline. <a href=\"https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Protecting one specific operation",
    q: "Modifying the conditional access policies themselves should require strong, recent authentication, even though the administrator's session has been open since the morning. What achieves that?",
    options: [
      "Lower the session lifetime for all administrators to one hour",
      "Require MFA for administrators in the general conditional access policy",
      "Protected actions, which tie an authentication requirement to that operation",
      "A PIM rule requiring justification when activating the administrator role",
    ],
    correct: 2,
    explain: "<b>Protected actions</b> attach an authentication requirement to <em>specific</em> high-impact operations, so the requirement is evaluated when they are performed and not only at sign-in. Lowering session lifetime inconveniences everyone all day to cover one case. The general MFA was already satisfied in the morning. And PIM controls role activation, not each operation performed while it is active. <a href=\"https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/protected-actions-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Phishing-resistant MFA",
    q: "After a phishing campaign defeated push-notification MFA, administrators should only be able to authenticate with phishing-resistant methods. What do you apply?",
    options: [
      "Disable every other authentication method across the whole tenant",
      "An authentication strength in the conditional access policy for those roles",
      "Increase how often MFA is prompted for administrative accounts",
      "Targeted training and a phishing simulation campaign for that group",
    ],
    correct: 1,
    explain: "<b>Authentication strength</b> lets you require specific methods — FIDO2, Windows Hello for Business, certificate-based — instead of plain 'MFA', applied through conditional access to just the roles that need it. Disabling methods tenant-wide affects users who do not need it and usually breaks scenarios. Prompting more often repeats a method already proven vulnerable. And training lowers likelihood without closing the vector. <a href=\"https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-strengths\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Validating the design against Zero Trust",
    q: "You review a conditional access deployment that requires MFA for all users on all applications, with no further conditions and no exclusions. What is the most important observation?",
    options: [
      "Device and risk signals are missing, and so is an excluded emergency account",
      "It should apply only to critical applications to reduce user friction",
      "Push-notification MFA should be replaced with codes sent by text message",
      "An equivalent policy is needed in each of the Azure subscriptions",
    ],
    correct: 0,
    explain: "Zero Trust requires <b>verifying explicitly with every available signal</b>: user and application alone are not enough — <em>device</em> state and <em>risk</em> are missing. And there is a serious operational flaw: without <b>excluded emergency accounts</b>, a mistake in a policy can lock out every administrator at once, with no way back in to fix it. Narrowing scope works against the principle. SMS is weaker, not stronger. And policies are tenant-wide, not per subscription. <a href=\"https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-emergency-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Verify explicitly",
    q: "Reviewing a customer's access design you find that, once the user has done MFA when signing in for the day, the session is good for every application until they log off, administration portals included. Which Zero Trust principle is broken and what fixes it?",
    options: [
      "Assume breach; fixed by segmenting the internal network into smaller zones",
      "Verify explicitly; fixed by evaluating every request and requiring recent authentication on what is critical",
      "Least privilege; fixed by reducing the roles permanently assigned to those users",
      "Verify explicitly; fixed by extending password expiry so passwords change less often",
    ],
    correct: 1,
    explain: "<b>Verify explicitly</b> means evaluating <em>every</em> request against the signals of the moment, not trusting an authentication from hours ago. It is fixed with sign-in frequency, <b>CAE</b> and, for critical operations, recent strong authentication. Assume breach and least privilege are the other two principles and describe different problems. And the fourth option names the right principle with a measure that has nothing to do with it. <a href=\"https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-continuous-access-evaluation\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Validating before enforcing",
    q: "Before enforcing a new set of conditional access policies in a 20,000-user tenant, the customer wants to know who they would block without blocking anyone yet. What do you do?",
    options: [
      "Apply them to a pilot group of a hundred users and wait for whatever the service desk reports",
      "Apply them during a quiet period and roll them back if calls to the service desk go up",
      "Deploy them in report-only mode and analyse the impact with the What If tool and the sign-in logs",
      "Simulate them by writing KQL queries over the last month of historical sign-in logs",
    ],
    correct: 2,
    explain: "<b>Report-only mode</b> evaluates the policy on every real sign-in and records the outcome <em>without applying it</em>: that is precisely \"knowing who it would block without blocking\". <b>What If</b> checks specific cases before you even publish it. The pilot already blocks a hundred people. Apply-and-roll-back blocks everyone. And rebuilding it by hand in KQL approximates with queries what the platform computes exactly. <a href=\"https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-report-only\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Local administrator password",
    q: "In a domain with 3,000 machines, all of them share the same local administrator password. What do you specify to cut the lateral movement that enables?",
    options: [
      "Disable the local administrator account entirely on every machine",
      "A group policy setting a different password per department",
      "Rename the local administrator account to make it harder to find",
      "Windows LAPS, which manages and rotates a unique password per machine",
    ],
    correct: 3,
    explain: "A shared local password turns the compromise of one machine into the compromise of all 3,000: it is the basis of lateral movement with pass-the-hash. <b>Windows LAPS</b> manages a <b>different password per machine</b>, rotates it and stores it in the directory with controlled access. Disabling the account breaks recovery when a machine loses contact with the domain. Grouping by department reduces the blast radius without removing it. And renaming is obscurity, not control. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Removing the secret rather than storing it",
    q: "An application on Azure App Service keeps the connection string to an Azure SQL database in its configuration. You are asked to reduce credential risk with the least maintenance. What do you recommend?",
    options: [
      "Move the string to Azure Key Vault and reference it from the configuration",
      "Encrypt the application configuration with a customer-managed key",
      "Use a managed identity for the application to authenticate against SQL",
      "Rotate the password every 30 days through a scheduled automation",
    ],
    correct: 2,
    explain: "The order of preference is to <b>remove the secret</b> before storing it better: with a <b>managed identity</b> the application obtains an Entra ID token for SQL and there is no password to store, rotate or leak, and no credential to maintain. Key Vault is the right answer when the secret cannot disappear, but here it can. Encrypting the configuration protects the store, not the use. And rotating every 30 days keeps the problem and adds work. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Exclusive custody of the key",
    q: "A regulatory requirement demands that key material reside in a single-tenant module under the customer's exclusive control, with FIPS 140-3 Level 3 certification. Which service qualifies?",
    options: [
      "Azure Key Vault Standard tier with software-protected keys",
      "Infrastructure encryption enabled on the storage account",
      "Customer-managed keys stored in Key Vault Premium",
      "Azure Key Vault Managed HSM",
    ],
    correct: 3,
    explain: "<b>Managed HSM</b> is the single-tenant offering: the module belongs to the customer and Microsoft has no access to the key material, with the certification the requirement names. Key Vault Standard protects in software. Premium uses HSMs but <em>shared</em> ones, which fails the single-tenant requirement. And infrastructure encryption adds a second layer over the data without saying anything about where the key lives. <a href=\"https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Separating control planes",
    q: "At one customer, the same account administers Entra ID, the Azure subscriptions, and signs in over RDP to application servers. Which enterprise access model principle is being broken, and how is it fixed?",
    options: [
      "Plane separation: distinct accounts for identity, management and workload",
      "Credential rotation: it is enough to change that account's password every thirty days",
      "Least privilege: it is enough to strip the permissions it has not used in ninety days",
      "Network segmentation: it is enough to isolate those servers in a separate subnet",
    ],
    correct: 0,
    explain: "The enterprise access model separates the <b>control, management and data planes</b>, and forbids an identity from a higher plane being exposed on a lower one. Using the same account to sign in to a server leaves its credentials on a less trusted machine, and from there you reach Entra ID. Rotating the password does not stop it sitting in memory for the duration of the session. Trimming unused permissions leaves the structural problem in place. And network segmentation does not stop the credential travelling. <a href=\"https://learn.microsoft.com/en-us/security/privileged-access-workstations/privileged-access-access-model\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "PIM versus access reviews",
    q: "A customer already has every privileged role in PIM, with activation capped at eight hours and approval required. The audit points out that people are still eligible for roles they stopped needing more than a year ago. What is missing?",
    options: [
      "Cutting the activation window from eight hours down to one to limit exposure",
      "Requiring phishing-resistant MFA at the moment any role is activated",
      "Periodic access reviews that recertify who should remain eligible",
      "Turning those eligible roles into permanent assignments so they can be audited better",
    ],
    correct: 2,
    explain: "PIM answers <b>how long</b> a role is active; it does not answer <b>whether that person should be able to activate it at all</b>. That second question belongs to <b>access reviews</b>: someone recertifies eligibility periodically and whatever is not confirmed is removed. Shortening the window or hardening activation improves an axis that is already solved. And going back to permanent assignments moves in the opposite direction. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/access-reviews-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Temporary access for external staff",
    q: "An external vendor needs access to a set of applications for three-month projects, with business-owner approval and automatic removal when the project ends. Which capability covers this?",
    options: [
      "A security group whose membership the support team maintains by hand",
      "Entitlement management access packages, with request, approval and expiry",
      "PIM eligible roles assigned one by one to each person at the external vendor",
      "A Conditional Access policy configured to expire after ninety days",
    ],
    correct: 1,
    explain: "<b>Entitlement management</b> bundles resources — applications, groups, sites — into an access package with a request, approval and <b>expiry</b> policy, and serves both employees and external users, who can request it from their own tenant. The manual group is exactly the work you are trying to remove. PIM is built for privileged roles, not for portfolios of business applications. And a Conditional Access policy neither grants nor removes access: it conditions it. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Attacks against AD DS",
    q: "During an assessment you find a service account with an SPN whose password is weak and has not changed in years. Which attack does this enable, and what fixes it at the root?",
    options: [
      "DCSync; fixed by auditing who holds directory replication permissions",
      "Golden Ticket; fixed by rotating the krbtgt account password twice",
      "Kerberoasting; fixed by migrating to group managed service accounts",
      "Pass-the-hash; fixed by enabling Credential Guard on every workstation",
    ],
    correct: 2,
    explain: "Any authenticated user can request a service ticket for an account with an SPN and crack its password offline: that is <b>kerberoasting</b>, and what closes it at the root is the password no longer being human, using <b>group managed service accounts</b>, which generate it long and rotate it themselves. DCSync abuses replication permissions. Golden Ticket starts from a krbtgt compromise. And pass-the-hash replays credentials held in memory. <a href=\"https://learn.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/group-managed-service-accounts-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detecting the attack inside the domain",
    q: "Beyond hardening AD DS, the customer wants to detect the moment someone attempts DCSync or enumerates the domain through reconnaissance. What do you deploy?",
    options: [
      "Advanced audit policies shipping the security events into Sentinel",
      "A monthly review of privileged group membership",
      "Defender for Endpoint on the domain member servers",
      "Microsoft Defender for Identity on the domain controllers",
    ],
    correct: 3,
    explain: "<b>Defender for Identity</b> installs on the domain controllers and is built for exactly these techniques: DCSync, Golden Ticket, kerberoasting, reconnaissance and lateral movement, with the detections already written. Dumping raw events into Sentinel means writing and maintaining those detections from scratch. Defender for Endpoint protects the server, not the directory protocol. And a monthly review arrives late and only sees membership. <a href=\"https://learn.microsoft.com/en-us/defender-for-identity/what-is\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Unused permissions across clouds",
    q: "An organisation with workloads in Azure, AWS and GCP wants to identify which identities hold permissions they never use, and trim them down to actual usage. What do you recommend?",
    options: [
      "The regulatory compliance dashboard in Microsoft Defender for Cloud",
      "Entra ID access reviews over the groups belonging to each cloud",
      "Microsoft Entra Permissions Management",
      "Azure Policy with initiatives assigned to every subscription and project",
    ],
    correct: 2,
    explain: "This is cloud infrastructure entitlement management, and the Microsoft piece is <b>Permissions Management</b>: it compares <em>granted</em> against <em>used</em> permissions across the three clouds, computes the excess and lets you trim to real usage. Defender for Cloud gives you posture over <em>resources</em>, not over permissions. Access reviews recertify membership without knowing what is used. And Azure Policy governs configuration. <a href=\"https://learn.microsoft.com/en-us/entra/permissions-management/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Trimming the granted permission",
    q: "Permissions Management shows that an AWS role used by a data team has a very high permission creep index. The team is afraid trimming it will break their nightly processes. How do you plan the trim?",
    options: [
      "Remove the role and grant it back only when somebody complains that something stopped working",
      "Leave it as it is and offset it with an alert every time the role performs a privileged action",
      "Generate the role right-sized to observed historical usage and apply it after the observation period",
      "Replace the role with long-lived credentials specific to each of the nightly processes",
    ],
    correct: 2,
    explain: "The value of <b>Permissions Management</b> is not the number: it is that it knows <em>what has actually been used</em> and can propose a role right-sized to that usage. The team's fear is answered with an observation window long enough for the nightly processes to run, not by giving up on the trim. Removing and waiting for complaints is manufacturing the incident. The alert detects after the fact. And long-lived credentials make the problem worse rather than solving it. <a href=\"https://learn.microsoft.com/en-us/entra/permissions-management/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Administering the tenant",
    q: "Which TWO measures are essential when designing administration of an Entra ID tenant so it does not become a single point of failure?",
    options: [
      "Emergency access accounts excluded from Conditional Access and alerted on when used",
      "Administrative roles granted through time-bound activation in PIM",
      "A second standby tenant with the same users synchronised into it",
      "Administrator passwords of at least twenty characters, rotated monthly",
    ],
    correct: [0, 1],
    explain: "The two that hold the design up are <b>emergency access accounts</b> — excluded from the policies so a Conditional Access mistake cannot lock everyone out, and watched with an alert because their use is always exceptional — and roles obtained through <b>time-bound activation in PIM</b> instead of being permanent. A standby tenant doubles the attack surface without solving anything, and password length is irrelevant against a stolen token or a badly written policy. <a href=\"https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-emergency-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where administration happens",
    q: "Domain administrators work from their everyday laptops, with email and web browsing on them. The account is in PIM and requires MFA. Which risk is still uncovered?",
    options: [
      "That the password is brute-forced against the domain controller",
      "That the machine the admin works from is compromised and the session is captured",
      "That the PIM role activation is not written to the audit logs",
      "That the MFA can be replayed from a different geographic location",
    ],
    correct: 1,
    explain: "PIM and MFA protect the <b>account</b>, but the session opens on a machine that also reads email and browses the web. If that machine falls, the attacker does not need the password: they inherit the already-authenticated session. That is why the design calls for a dedicated, hardened <b>privileged access workstation</b>. Brute force is stopped by lockout and MFA. Activation is logged. And MFA replay is covered by Conditional Access. <a href=\"https://learn.microsoft.com/en-us/security/privileged-access-workstations/privileged-access-devices\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Remote access to the servers",
    q: "The administrators already work from dedicated hardened workstations, but they reach the virtual machines over RDP published to the internet with a public IP per server. What do you recommend?",
    options: [
      "Restrict the RDP port to the offices' public IP addresses using network security groups",
      "Azure Bastion, with Entra ID and conditional access in front and no public IP on the machines",
      "Just-in-time access to the management ports in Defender for Cloud, keeping the public IP",
      "A site-to-site VPN between the offices and the virtual network, keeping published RDP as a fallback",
    ],
    correct: 1,
    explain: "The dedicated workstation solves <em>which machine</em> administration happens from; what is left is <em>how you get there</em>. <b>Azure Bastion</b> removes the public IP from the machine and puts the session behind Entra ID and conditional access, which is where the identity decisions already live. IP filtering still exposes the port and trusts the network as a perimeter. Just-in-time access shrinks the window but keeps the exposure. And keeping published RDP \"as a fallback\" preserves exactly the path you were closing. <a href=\"https://learn.microsoft.com/en-us/azure/bastion/bastion-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "From requirement to control",
    q: "A customer must comply with a regulation that requires a certain category of data to be encrypted at rest and requires them to demonstrate it to an auditor periodically. Which design answers both halves of the requirement?",
    options: [
      "An Azure Policy assignment with a Deny effect over unencrypted resources",
      "The Defender for Cloud regulatory compliance dashboard as the only measure",
      "A manual quarterly report produced by the platform team",
      "Azure Policy to enforce the encryption and Defender for Cloud to evidence it",
    ],
    correct: 3,
    explain: "These are <b>two distinct obligations</b>: enforce and demonstrate. <b>Azure Policy</b> enforces — it blocks or remediates the non-compliant resource — and the Defender for Cloud <b>regulatory compliance</b> dashboard evidences, mapping real state against the standard's controls continuously and exportably. Either one on its own answers half the question. And the manual report is neither repeatable nor verifiable. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/regulatory-compliance-dashboard\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The whole framework or the obligation",
    q: "A customer has to comply with an extensive regulatory framework in Azure and asks for the least possible operational effort. The team proposes writing a policy from scratch for every control. What do you recommend?",
    options: [
      "Assign the built-in initiative for that framework and write policies only for the controls it does not cover",
      "Write the policies from scratch so they reflect the exact language of the applicable regulatory framework",
      "Start from the Microsoft Cloud Security Benchmark and consider the framework covered once it is at a hundred per cent",
      "Document the controls in a procedure and verify them with a manual quarterly review of the environment",
    ],
    correct: 0,
    explain: "\"Least operational effort\" is the tell: Azure Policy ships <b>built-in initiatives</b> for the common frameworks and Defender for Cloud surfaces them in the regulatory compliance dashboard. You assign what already exists and write only the difference. Writing everything duplicates finished work and has to be maintained. MCSB is a good baseline but is not equivalent to a specific framework. And a procedure with a manual review is neither a technical control nor repeatable evidence. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/samples/built-in-initiatives\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Enforce and evidence",
    q: "A regulatory obligation requires that no storage be publicly accessible and that compliance be demonstrable to an external auditor every quarter. Which TWO pieces does the design include?",
    options: [
      "A Sentinel alert every time a storage account is created in any subscription",
      "An Azure Policy assignment with a Deny effect on public access, assigned at the management group",
      "An automation rule that assigns storage incidents to the platform team",
      "The Defender for Cloud regulatory compliance dashboard, which is where the per-control evidence comes from",
    ],
    correct: [1, 3],
    explain: "The obligation has two halves: <b>prevent</b> and <b>demonstrate</b>. The first is <b>Azure Policy</b> with <code>Deny</code> at the right scope — the management group, not subscription by subscription; the second is the <b>regulatory compliance</b> dashboard, which shows real state control by control and can be exported for the auditor. The alert warns about the creation but neither prevents nor evidences it, and the automation rule only routes incidents. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Rollout order for a policy",
    q: "You need to enforce a security configuration in a subscription that already holds hundreds of deployed resources, many of them non-compliant, without breaking deployments in flight. How do you plan it?",
    options: [
      "Assign the policy with a Deny effect and fix afterwards whatever stops working",
      "Apply DeployIfNotExists directly against every non-compliant resource",
      "Audit first to measure, remediate what exists, and apply Deny last",
      "Exclude the current resources from scope and apply Deny only to new ones",
    ],
    correct: 2,
    explain: "A <code>Deny</code> up front fixes nothing that already exists — it only blocks what is new — and usually breaks legitimate deployments. The sequence the exam expects is <b>Audit</b> to measure the real scope, <b>remediation</b> of what exists, and <b>Deny</b> last so the drift cannot come back. Going straight to DeployIfNotExists over hundreds of resources changes production without measuring. And excluding what exists makes the non-compliance permanent. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Purview for regulated data",
    q: "A regulation requires knowing where a certain category of personal data lives in Microsoft 365, preventing it from leaving by email, and retaining it for seven years. Which TWO Microsoft Purview capabilities cover the requirement?",
    options: [
      "Classification with sensitivity labels to discover and mark the data",
      "Information barriers to separate communication between departments",
      "Insider risk management to score each employee's behaviour",
      "Data loss prevention to stop it leaving through risky channels",
    ],
    correct: [0, 3],
    explain: "The requirement carries two verbs: <b>know where it is</b> and <b>stop it leaving</b>. The first is classification with sensitivity labels; the second is <b>data loss prevention</b>. The seven-year retention is handled by data lifecycle management, which is not among the options. Insider risk measures behaviour and information barriers separate communications: neither one discovers the data nor blocks it leaving. <a href=\"https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Score or compliance",
    q: "The steering committee asks for a report showing, control by control, the degree of compliance with ISO 27001 in Azure and also in the connected AWS accounts. What do you take to the meeting?",
    options: [
      "The trend of the Microsoft Secure Score over the last six months",
      "The detection coverage report against the MITRE ATT&CK matrices",
      "The summary of incidents closed by the SOC in the Defender XDR portal",
      "The Defender for Cloud regulatory compliance dashboard with ISO 27001 added",
    ],
    correct: 3,
    explain: "The Defender for Cloud <b>regulatory compliance</b> dashboard maps the real state of resources against a standard's controls — MCSB by default, plus whatever you add, ISO 27001 included — and also covers connected AWS and GCP accounts. <b>Secure Score</b> measures relative posture improvement, not compliance with a regulation: that is the confusion the question is fishing for. Incidents and detection coverage measure operations, not compliance. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/regulatory-compliance-dashboard\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["operations-identity"] = QUIZ_DATA;
