const QUIZ_DATA = [
  {
    tag: "Evaluación de políticas",
    q: "Un usuario tiene una política de identidad que permite s3:GetObject sobre un bucket, pero el bucket tiene una bucket policy con un Deny explícito para ese mismo usuario. ¿Qué ocurre?",
    options: [
      "Se le permite el acceso porque la política de identidad tiene prioridad",
      "Se le deniega el acceso: un Deny explícito en cualquier política aplicable siempre gana",
      "AWS evalúa solo la política de identidad si el recurso es propio de la cuenta",
      "El resultado depende de cuál política se creó más recientemente",
    ],
    correct: 1,
    explain: "El orden de evaluación de IAM es: Deny explícito &gt; Allow explícito &gt; Deny por defecto. Un Deny explícito en CUALQUIER política que aplique (identidad, recurso, SCP, RCP, boundary, session policy) anula cualquier Allow, sin importar dónde esté.",
  },
  {
    tag: "SCP vs RCP",
    q: "¿Cuál es la diferencia clave entre una Service Control Policy (SCP) y una Resource Control Policy (RCP) en AWS Organizations?",
    options: [
      "No hay diferencia, son sinónimos del mismo mecanismo",
      "Las SCP solo aplican a la cuenta de gestión (management account)",
      "Las SCP limitan lo que las identidades de la cuenta pueden hacer; las RCP limitan quién puede acceder a los recursos, incluidas identidades externas/anónimas",
      "Las RCP sustituyen completamente a las SCP desde 2023",
    ],
    correct: 2,
    explain: "Las SCP son guardrails que acotan el máximo permiso disponible para principals DENTRO de la organización. Las RCP (más recientes) acotan el acceso a los RECURSOS en sí, incluyendo principals externos, cerrando huecos que las SCP no cubren porque las SCP no aplican a identidades fuera de la organización.",
  },
  {
    tag: "Permission boundaries",
    q: "Un desarrollador tiene un permission boundary que solo permite acciones sobre S3 y DynamoDB. Su identity-based policy le concede AdministratorAccess. ¿Qué puede hacer realmente?",
    options: [
      "Todo, porque AdministratorAccess siempre gana",
      "Solo acciones S3 y DynamoDB: el permission boundary actúa como techo máximo, la intersección con la identity policy",
      "Nada, porque el boundary y la policy entran en conflicto y se deniega todo",
      "Depende del orden en que se adjuntaron las políticas",
    ],
    correct: 1,
    explain: "El permission boundary NO otorga permisos por sí mismo: define el máximo conjunto de permisos que una identity-based policy puede conceder. El permiso efectivo es la INTERSECCIÓN entre la identity policy y el boundary.",
  },
  {
    tag: "STS",
    q: "Una aplicación móvil autentica usuarios contra Google (proveedor OIDC) y necesita credenciales temporales de AWS para acceder a un bucket S3 de forma directa desde el móvil. ¿Qué API de STS es la adecuada?",
    options: [
      "sts:GetSessionToken",
      "sts:AssumeRoleWithWebIdentity (o mejor, vía Amazon Cognito Identity Pools)",
      "sts:AssumeRoleWithSAML",
      "sts:GetFederationToken",
    ],
    correct: 1,
    explain: "AssumeRoleWithWebIdentity intercambia un token OIDC (Google, Facebook, Amazon, o cualquier IdP compatible con OIDC) por credenciales temporales. En producción, AWS recomienda usar Cognito Identity Pools por encima, que gestiona el intercambio de forma más segura sin exponer secretos de la app.",
  },
  {
    tag: "Federación SAML",
    q: "Una empresa usa Active Directory Federation Services (ADFS) on-premises y quiere dar acceso a la consola de AWS a sus empleados sin crear usuarios IAM. ¿Qué mecanismo es el más apropiado?",
    options: [
      "IAM Roles Anywhere",
      "AssumeRoleWithSAML combinado con un IdP SAML 2.0 configurado en IAM",
      "Access keys individuales gestionadas por AD",
      "AWS IAM Identity Center en modo standalone sin IdP externo",
    ],
    correct: 1,
    explain: "AssumeRoleWithSAML permite federar identidades desde un IdP SAML 2.0 (ADFS, Okta, Azure AD/Entra ID) directamente contra un IAM Role, sin necesidad de usuarios IAM individuales. IAM Identity Center también es válido y es la opción moderna recomendada por AWS para multi-cuenta, pero igualmente necesita conectar ese mismo IdP SAML como fuente de identidad.",
  },
  {
    tag: "IAM Identity Center",
    q: "¿Cuál es la diferencia principal entre un IAM Role tradicional cross-account y un Permission Set de IAM Identity Center?",
    options: [
      "No hay diferencia técnica, IAM Identity Center es solo una interfaz visual sobre roles",
      "Los Permission Sets solo funcionan con usuarios root",
      "Un Permission Set se define una vez y IAM Identity Center provisiona automáticamente los IAM Roles correspondientes en cada cuenta miembro asignada",
      "Los Permission Sets no soportan políticas gestionadas por AWS, solo inline",
    ],
    correct: 2,
    explain: "IAM Identity Center (sucesor de AWS SSO) centraliza la gestión: defines un Permission Set una vez y el servicio provisiona/sincroniza automáticamente los IAM Roles necesarios en cada cuenta de la organización asignada, evitando gestionar roles manualmente cuenta por cuenta.",
  },
  {
    tag: "IAM Access Analyzer",
    q: "¿Qué tipo de hallazgo genera IAM Access Analyzer cuando detecta que un rol IAM no se ha usado en los últimos 90 días?",
    options: [
      "External access finding",
      "Unused access finding (parte del análisis de 'unused access', disponible desde 2023)",
      "Policy validation finding",
      "Access Analyzer no analiza el uso, solo políticas estáticas",
    ],
    correct: 1,
    explain: "Access Analyzer tiene tres capacidades: (1) External access findings — detecta recursos accesibles desde fuera de tu zona de confianza; (2) Unused access findings — identifica roles, permisos y access keys sin uso reciente; (3) Policy validation — valida sintaxis y buenas prácticas de políticas mientras las escribes.",
  },
  {
    tag: "ABAC",
    q: "En una estrategia de control de acceso basado en atributos (ABAC) con IAM, ¿qué condición se usaría típicamente en una política para permitir que un usuario solo pueda etiquetar/acceder a recursos que coincidan con su propio departamento?",
    options: [
      "\"Condition\": {\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/department}\"}}",
      "\"Condition\": {\"IpAddress\": {\"aws:SourceIp\": \"10.0.0.0/16\"}}",
      "\"Condition\": {\"Bool\": {\"aws:MultiFactorAuthPresent\": \"true\"}}",
      "\"Condition\": {\"DateLessThan\": {\"aws:CurrentTime\": \"2026-01-01T00:00:00Z\"}}",

    ],
    correct: 0,
    explain: "ABAC compara etiquetas (tags) del principal con etiquetas del recurso usando variables de política como aws:PrincipalTag/clave y aws:ResourceTag/clave, permitiendo reglas de acceso que escalan sin reescribir políticas para cada nuevo recurso.",
  },
  {
    tag: "Confused deputy",
    q: "Un servicio de AWS (ej. CloudTrail) asume un rol en tu cuenta en nombre de otro cliente de AWS y por error accede a datos de tu cuenta que no le corresponden. ¿Qué condición de política previene este 'confused deputy problem'?",
    options: [
      "aws:MultiFactorAuthPresent",
      "aws:SourceIp",
      "aws:SourceArn y/o aws:SourceAccount en la trust policy del rol",
      "aws:RequestedRegion",
    ],
    correct: 2,
    explain: "Para evitar que un servicio de AWS sea 'engañado' para actuar en nombre de un tercero no autorizado, se añade a la trust policy una condición con aws:SourceArn (o aws:SourceAccount) que restringe qué recurso/cuenta específica puede invocar el AssumeRole vía ese servicio.",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "Una empresa tiene servidores on-premises (fuera de AWS) que necesitan credenciales temporales de AWS sin usar access keys de larga duración. ¿Qué servicio está diseñado exactamente para este caso?",
    options: [
      "AWS Systems Manager Hybrid Activations únicamente",
      "IAM Roles Anywhere: usa certificados X.509 emitidos por una CA privada para intercambiarlos por credenciales temporales vía STS",
      "IAM Identity Center con conector on-premises",
      "Cognito Identity Pools",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere permite a cargas de trabajo fuera de AWS (servidores on-prem, otros clouds) obtener credenciales temporales de IAM presentando un certificado X.509 firmado por una CA de confianza registrada en IAM, eliminando la necesidad de access keys estáticas fuera de AWS.",
  },
  {
    tag: "Root user",
    q: "AWS introdujo 'Centralized Root Access Management' en Organizations. ¿Qué permite hacer esta capacidad?",
    options: [
      "Eliminar por completo la necesidad de tener usuario root en cada cuenta",
      "Gestionar de forma centralizada las credenciales root de las cuentas miembro y aplicar acciones privilegiadas de root sin necesidad de recuperar contraseñas cuenta por cuenta",
      "Convertir el root en un rol IAM asumible por cualquier usuario",
      "Sustituir MFA en la cuenta de gestión",
    ],
    correct: 1,
    explain: "Esta capacidad de Organizations (lanzada en 2023-2024) permite gestionar y restringir de forma centralizada las credenciales root de las cuentas miembro, e invocar un conjunto acotado de tareas privilegiadas de root sin tener que hacer el proceso de recuperación de contraseña individualmente en cada cuenta.",
  },
  {
    tag: "MFA",
    q: "¿Qué clave de condición se usa en una política IAM para exigir que una API call se haya realizado con una sesión autenticada por MFA?",
    options: [
      "aws:MultiFactorAuthPresent: true",
      "aws:MFA-Required: true",
      "iam:MFAEnabled: true",
      "sts:MfaAuthenticated: true",
    ],
    correct: 0,
    explain: "La condición estándar es aws:MultiFactorAuthPresent. Es una buena práctica muy preguntada en el examen combinarla con aws:MultiFactorAuthAge para limitar además la antigüedad máxima de la sesión MFA.",
  },
  {
    tag: "Resource-based policies",
    q: "¿Cuál de estas afirmaciones sobre políticas basadas en recursos (resource-based policies) es correcta?",
    options: [
      "Solo IAM Roles pueden tener resource-based policies",
      "Permiten conceder acceso a un principal de OTRA cuenta AWS sin necesidad de que ese principal asuma un rol en tu cuenta",
      "No pueden combinarse nunca con condiciones",
      "Sustituyen siempre a las identity-based policies",
    ],
    correct: 1,
    explain: "Recursos como buckets S3, KMS keys, colas SQS, topics SNS o Lambda functions soportan resource-based policies, que pueden especificar directamente un Principal externo (de otra cuenta) sin que ese principal necesite asumir un rol — el acceso cross-account se concede directamente en el recurso.",
  },
  {
    tag: "Credential report vs Access Advisor",
    q: "¿Cuál es la diferencia entre el IAM Credential Report y el IAM Access Advisor?",
    options: [
      "Son el mismo informe con nombres distintos",
      "El Credential Report lista el estado de credenciales (passwords, access keys, MFA) de todos los usuarios; Access Advisor muestra qué servicios/acciones ha usado realmente un principal y cuándo por última vez",
      "Access Advisor solo funciona a nivel de cuenta root",
      "El Credential Report requiere GuardDuty habilitado",
    ],
    correct: 1,
    explain: "El Credential Report (generado a nivel de cuenta, CSV) audita el estado de credenciales de todos los usuarios IAM. Access Advisor (pestaña 'Access Advisor' de un usuario/rol) muestra el histórico de servicios accedidos — clave para aplicar el principio de mínimo privilegio eliminando permisos no usados.",
  },
  {
    tag: "Cross-account trust policy",
    q: "¿Qué elemento es obligatorio en la trust policy (assume role policy document) de un IAM Role para permitir que una cuenta externa lo asuma?",
    options: [
      "Un Principal que referencie el ARN o ID de la cuenta externa, con Action sts:AssumeRole",
      "Un bucket policy vinculado al rol",
      "Una SCP específica en la cuenta externa",
      "Nada adicional: por defecto cualquier cuenta puede asumir cualquier rol",
    ],
    correct: 0,
    explain: "La trust policy del rol debe incluir un Principal con el ARN de la cuenta/rol externo autorizado y Action: sts:AssumeRole. Además, la cuenta que asume necesita su propia identity policy que le permita hacer sts:AssumeRole sobre ese ARN — se requieren AMBOS lados (trust + permiso de origen).",
  },
  {
    tag: "Data perimeter",
    q: "En el concepto de 'data perimeter' de AWS, ¿qué combinación de controles se usa típicamente para asegurar que los datos NUNCA salgan de la organización, incluso con credenciales válidas robadas?",
    options: [
      "Solo cifrado con KMS",
      "Solo Security Groups restrictivos",
      "SCPs/RCPs a nivel de organización + condiciones aws:PrincipalOrgID / aws:ResourceOrgID + VPC endpoint policies",
      "Solo rotación de access keys cada 90 días",
    ],
    correct: 2,
    explain: "El data perimeter combina 3 tipos de perímetros: identidad (¿quién puede acceder? — SCPs/RCPs con aws:PrincipalOrgID), recurso (¿qué recursos son de confianza? — aws:ResourceOrgID) y red (¿desde dónde? — VPC endpoint policies + aws:SourceVpce), de forma que ni siquiera credenciales válidas comprometidas puedan exfiltrar datos fuera del perímetro.",
  },
  {
    tag: "Session policies",
    q: "Cuando llamas a sts:AssumeRole pasando un parámetro --policy adicional (session policy), ¿cómo afecta esto a los permisos efectivos de la sesión resultante?",
    options: [
      "La session policy sustituye completamente a la identity policy del rol",
      "La session policy amplía los permisos del rol más allá de lo que ya tenía",
      "La session policy actúa como filtro adicional: los permisos efectivos son la intersección entre los permisos del rol y la session policy",
      "Las session policies solo aplican a usuarios, no a roles",
    ],
    correct: 2,
    explain: "Igual que un permission boundary, una session policy NUNCA amplía permisos — solo puede acotar (intersección) los permisos que ya tiene el rol asumido. Es útil para dar credenciales temporales más restringidas a partir de un rol amplio.",
  },
  {
    tag: "Declarative policies",
    q: "AWS Organizations introdujo 'Declarative Policies'. ¿En qué se diferencian de las SCP?",
    options: [
      "Son idénticas a las SCP, solo cambia el nombre",
      "Las Declarative Policies fijan de forma centralizada la configuración deseada de ciertos atributos de servicio (ej. bloquear IMDSv1, forzar bloqueo de acceso público en EC2/VPC) en toda la organización, en vez de solo permitir/denegar acciones de API",
      "Las Declarative Policies solo funcionan en la cuenta de gestión",
      "Sustituyen a Config Rules completamente",
    ],
    correct: 1,
    explain: "A diferencia de las SCP (que deniegan/permiten llamadas a API), las Declarative Policies (2024+) establecen y mantienen un estado de configuración deseado a nivel de organización para atributos específicos de ciertos servicios (p. ej. exigir IMDSv2, bloquear acceso público a snapshots), garantizando que ninguna cuenta pueda desviarse de esa configuración.",
  },
  {
    tag: "Policy evaluation con VPC endpoints",
    q: "¿Qué clave de condición permite restringir el acceso a un bucket S3 exclusivamente a peticiones que pasen por un VPC endpoint específico?",
    options: [
      "aws:SourceIp",
      "aws:SourceVpce",
      "aws:VpcSourceIp",
      "s3:VpcEndpointId",
    ],
    correct: 1,
    explain: "aws:SourceVpce en una bucket policy (o cualquier resource policy compatible) restringe el acceso a peticiones que viajen a través de un VPC endpoint concreto, un control clave del 'network perimeter' para evitar exfiltración de datos hacia fuera de la VPC.",
  },
  {
    tag: "Inline vs managed policies",
    q: "¿Cuál es la principal desventaja de usar políticas inline en lugar de políticas gestionadas (managed policies)?",
    options: [
      "Las políticas inline no soportan condiciones",
      "Las políticas inline no se pueden reutilizar entre múltiples usuarios/roles/grupos y son más difíciles de auditar y versionar de forma centralizada",
      "Las políticas inline tienen un límite de tamaño menor que las gestionadas",
      "Las políticas inline no pueden denegar, solo permitir",
    ],
    correct: 1,
    explain: "Una política inline vive embebida en una única identidad (usuario, grupo o rol) y no se puede adjuntar a otras identidades ni versionar de forma independiente, dificultando su reutilización, auditoría centralizada y gestión a escala frente a una customer managed policy.",
  },
  {
    tag: "Amazon Cognito",
    q: "Tu aplicación web tiene su propio sistema de registro/login de usuarios finales, y tras autenticarse necesitan subir archivos directamente a un bucket S3 con credenciales temporales de AWS. ¿Qué combinación de componentes de Cognito usarías?",
    options: [
      "Solo un Cognito User Pool, que ya emite credenciales de AWS directamente",
      "Un Cognito User Pool para el login (emite JWT) + un Cognito Identity Pool que cambia ese JWT por credenciales temporales de AWS",
      "IAM Identity Center, porque Cognito no soporta usuarios externos a la organización",
      "AssumeRoleWithSAML apuntando directamente al User Pool",
    ],
    correct: 1,
    explain: "El User Pool gestiona identidad y login (devuelve JSON Web Tokens), pero NO da credenciales de AWS por sí solo. El Identity Pool es el que intercambia ese token ya autenticado por credenciales temporales de AWS (vía STS internamente), permitiendo acceso directo y seguro a servicios como S3.",
  },
  {
    tag: "S3 presigned URLs",
    q: "¿Qué ocurre con un S3 presigned URL si, antes de que expire, se revoca el permiso s3:GetObject del usuario que la generó?",
    options: [
      "La URL sigue funcionando igual hasta que expire su tiempo de vida, porque las credenciales se 'congelaron' en el momento de la firma",
      "La URL deja de funcionar de inmediato: cada uso se sigue evaluando contra los permisos IAM vigentes del firmante",
      "La URL se invalida automáticamente en menos de 1 minuto",
      "No es posible revocar permisos de un presigned URL una vez generado",
    ],
    correct: 1,
    explain: "Un presigned URL no es una credencial independiente: es una firma que delega, durante una ventana de tiempo, el permiso vigente del firmante. Si ese permiso se revoca (se le quita la policy, se desactiva el rol, etc.) antes de que expire la URL, el acceso también se deniega, porque IAM se sigue evaluando en cada petición.",
  },
  {
    tag: "AWS Directory Service",
    q: "Una empresa tiene un Active Directory on-premises que quiere seguir usando como fuente de identidad, sin migrar datos ni replicar el directorio dentro de AWS. ¿Qué opción de AWS Directory Service encaja?",
    options: [
      "AWS Managed Microsoft AD",
      "Simple AD",
      "AD Connector: actúa como proxy/redirector hacia el AD on-premises existente, sin almacenar ni replicar datos de directorio en AWS",
      "Amazon Cognito User Pools",
    ],
    correct: 2,
    explain: "AD Connector es un simple proxy de directorio: redirige las solicitudes de autenticación al Active Directory on-premises existente sin copiar ni sincronizar datos. AWS Managed Microsoft AD, en cambio, SÍ crea un directorio real y gestionado dentro de AWS (útil si necesitas trusts o un AD nativo en la nube).",
  },
  {
    tag: "Amazon Verified Permissions",
    q: "Tu equipo está construyendo una aplicación SaaS multi-tenant y necesita decidir, en cada request, si el usuario autenticado puede ver un documento concreto según su rol y el tenant al que pertenece. ¿Qué servicio de AWS está diseñado específicamente para esto?",
    options: [
      "IAM Access Analyzer",
      "Amazon Verified Permissions, usando políticas en lenguaje Cedar consultadas vía la API IsAuthorized",
      "AWS Config Rules",
      "Una Service Control Policy (SCP) por tenant",
    ],
    correct: 1,
    explain: "Amazon Verified Permissions es un motor de autorización gestionado, basado en el lenguaje Cedar, pensado para lógica de autorización DENTRO de aplicaciones propias (quién puede ver/editar qué recurso de negocio), no para permisos sobre la API de AWS. La app consulta IsAuthorized en cada request en vez de hardcodear reglas de permisos.",
  },
  {
    tag: "IAM paths",
    q: "¿Para qué se usa principalmente el 'path' (ej. /division_abc/subdivision_xyz/) de un IAM User o Role?",
    options: [
      "Define la región donde vive la identidad",
      "Es la ruta del bucket S3 donde se almacenan los logs de esa identidad",
      "Agrupa/organiza identidades por prefijo dentro del ARN, permitiendo escribir políticas de administración que solo permitan gestionar identidades bajo un path concreto",
      "Determina el orden de evaluación de las políticas adjuntas",
    ],
    correct: 2,
    explain: "El path es parte del ARN (arn:aws:iam::cuenta:role/PATH/nombre) y sirve para organizar identidades por equipo/proyecto, permitiendo delegar administración con permisos acotados a un path concreto — un mecanismo de autorización explícitamente listado en el exam guide junto a resource policies y trust policies.",
  },
  {
    tag: "Policy Simulator vs Access Analyzer",
    q: "Quieres comprobar, antes de desplegarla, si una política IAM concreta permitiría a un rol borrar un bucket S3 específico — sin ejecutar la acción real ni dejar rastro en CloudTrail. ¿Qué herramienta usarías?",
    options: [
      "IAM Access Analyzer (external access findings)",
      "IAM Policy Simulator (aws iam simulate-principal-policy)",
      "AWS Config conformance packs",
      "GuardDuty",
    ],
    correct: 1,
    explain: "IAM Policy Simulator responde exactamente 'esta política, ¿permitiría esta acción concreta?' sin ejecutar nada real. Access Analyzer, en cambio, audita la postura de acceso YA EXISTENTE en la cuenta (acceso externo, permisos no usados) — son complementarios pero responden preguntas distintas.",
  },
  {
    tag: "Access Analyzer – Internal access",
    q: "Tu organización en AWS Organizations tiene decenas de cuentas. Quieres saber, teniendo en cuenta el efecto combinado de las políticas de identidad, las SCPs y las RCPs, qué roles y usuarios DENTRO de tu propia organización pueden llegar a acceder a un bucket S3 crítico de otra cuenta — no te interesa el acceso externo. ¿Qué capacidad de IAM Access Analyzer, lanzada en 2025, responde exactamente a esto?",
    options: [
      "External access findings de un analyzer con scope de cuenta",
      "Internal access findings: un nuevo tipo de analyzer que usa razonamiento automatizado para evaluar conjuntamente políticas de identidad, SCPs y RCPs y mostrar qué principals de la organización pueden acceder a recursos S3, DynamoDB o RDS",
      "Unused access findings",
      "El IAM Credential Report",
    ],
    correct: 1,
    explain: "En junio de 2025 AWS lanzó los Internal Access Findings en IAM Access Analyzer: usan razonamiento automatizado (la misma tecnología Zelkova que valida políticas) para evaluar conjuntamente identity-based policies, SCPs y RCPs y generar hallazgos de qué identidades DENTRO de la organización tienen acceso a S3, DynamoDB o RDS, complementando los external access findings (que solo miran acceso desde fuera de la cuenta/organización).",
  },
  {
    tag: "STS AssumeRoot",
    q: "Una cuenta miembro de la organización tiene habilitado Centralized Root Access Management y sus credenciales root han sido eliminadas. Un administrador de la cuenta de gestión necesita desbloquear temporalmente una bucket policy de S3 corrupta en esa cuenta miembro, una tarea que solo root puede ejecutar. ¿Qué es obligatorio para lograrlo?",
    options: [
      "Llamar a sts:AssumeRole normal; cualquier rol con AdministratorAccess puede hacerlo igual que root",
      "Llamar a sts:AssumeRoot desde la cuenta de gestión (o un delegated administrator), especificando obligatoriamente una TaskPolicy administrada por AWS que acota la sesión a esa tarea concreta — nunca se puede obtener una sesión root sin restricciones",
      "Recuperar la contraseña root de la cuenta miembro mediante el flujo estándar de 'forgot password'",
      "Usar sts:AssumeRoleWithSAML apuntando al IdP corporativo",
    ],
    correct: 1,
    explain: "sts:AssumeRoot solo puede invocarse desde la cuenta de gestión de la Organization (o un delegated administrator de IAM), nunca con credenciales root, y exige indicar una TaskPolicy administrada por AWS (por ejemplo para desbloquear políticas de S3 o resolver problemas de claves KMS) que acota exactamente qué puede hacer esa sesión root temporal de máximo 15 minutos — jamás concede un root 'sin restricciones'.",
  },
  {
    tag: "Access Analyzer – Custom policy checks",
    q: "Tu equipo de plataforma quiere bloquear en el pipeline de CI/CD cualquier pull request que añada un permiso peligroso concreto (por ejemplo iam:CreateAccessKey) a una política IAM, ANTES de que se despliegue. ¿Qué API de IAM Access Analyzer encaja para este control automatizado?",
    options: [
      "list-findings-v2",
      "CheckAccessNotGranted: verifica que una política candidata NO conceda un conjunto de permisos críticos que tú especifiques, ideal para gates de CI/CD",
      "GetGeneratedPolicy",
      "simulate-principal-policy",
    ],
    correct: 1,
    explain: "CheckAccessNotGranted (parte de los custom policy checks de Access Analyzer, basados en razonamiento automatizado) te permite declarar una lista de acciones/permisos críticos que nunca deben concederse y comprobar una política candidata contra esa lista antes del despliegue. Su hermana CheckNoNewAccess compara una política nueva contra una de referencia para asegurar que no se introduce acceso adicional al actualizarla.",
  },
  {
    tag: "aws:CalledVia",
    q: "Quieres permitir que un usuario ejecute consultas en Amazon Athena que internamente llaman a S3 y a AWS Glue en su nombre, pero impedir que ese mismo usuario llame directamente a esas acciones de S3/Glue fuera del contexto de Athena. ¿Qué clave de condición IAM está diseñada exactamente para este escenario?",
    options: [
      "aws:SourceArn",
      "aws:CalledVia, que contiene la lista ordenada de servicios de AWS que hicieron la llamada en nombre del principal, permitiendo exigir que ciertas acciones solo se ejecuten 'a través de' un servicio concreto",
      "aws:ViaAWSService únicamente, sin más matices",
      "aws:PrincipalServiceName",
    ],
    correct: 1,
    explain: "aws:CalledVia captura la cadena de servicios de AWS que reenviaron la solicitud en nombre del principal (por ejemplo, Athena llamando a S3/Glue). Con una condición StringEquals sobre aws:CalledVia puedes exigir que ciertas acciones (ej. s3:GetObject sobre un bucket concreto) solo se permitan cuando se invocan a través de athena.amazonaws.com, denegando la llamada directa del usuario a esas mismas acciones.",
  },
  {
    tag: "SCP – lenguaje IAM completo (2025)",
    q: "Hasta hace poco, las SCPs solo soportaban un subconjunto limitado del lenguaje de políticas IAM. Tras la actualización de AWS Organizations de septiembre de 2025, ¿qué nueva capacidad de sintaxis pasó a estar disponible en las SCPs?",
    options: [
      "Las SCPs pasaron a poder otorgar permisos por sí mismas, igual que una identity-based policy",
      "Soporte para el lenguaje completo de políticas IAM en SCPs: condiciones, ARNs de recurso individuales, el elemento NotAction combinado con Allow, wildcards al inicio/medio del elemento Action y NotResource",
      "Las SCPs pasaron a poder aplicarse a cuentas fuera de la organización",
      "Las SCPs sustituyeron por completo a las RCPs",
    ],
    correct: 1,
    explain: "Desde septiembre de 2025, AWS Organizations soporta el lenguaje completo de políticas IAM en las SCPs: condiciones, ARNs de recurso específicos, NotAction en statements Allow, wildcards en posiciones intermedias del Action y el elemento NotResource — igualando la expresividad de una managed policy IAM normal. Esto NO cambia la naturaleza de las SCPs: siguen siendo únicamente guardrails que acotan (nunca otorgan) permisos.",
  },
  {
    tag: "IAM Identity Center – Trusted Identity Propagation",
    q: "Un analista corporativo, autenticado en IAM Identity Center, consulta datos en Amazon Athena/Redshift a través de Amazon QuickSight. La empresa quiere que los logs de acceso a los datos subyacentes en S3/Lake Formation muestren la identidad corporativa real del analista (no un rol de servicio genérico), y que los permisos de acceso a los datos se evalúen según sus atributos/grupos reales. ¿Qué mecanismo de IAM Identity Center habilita esto?",
    options: [
      "Permission Sets tradicionales asignados directamente al analista",
      "Trusted Identity Propagation (TIP): propaga el contexto de identidad del usuario autenticado a través de la cadena de servicios de AWS, de modo que los permisos y los logs de auditoría reflejan a la persona real, no un rol compartido",
      "AssumeRoleWithSAML clásico",
      "Session policies aplicadas al rol de servicio de QuickSight",
    ],
    correct: 1,
    explain: "Trusted Identity Propagation añade el contexto de identidad del usuario de Identity Center a un IAM Role cuando un servicio (QuickSight, Athena, Redshift, EMR, OpenSearch, SageMaker Unified Studio...) llama a otro en su nombre. Así, los permisos de acceso a datos y los registros en CloudTrail reflejan la identidad corporativa real del usuario en lugar de un rol de servicio compartido, sin necesidad de crear un rol IAM por persona.",
  },
  {
    tag: "Multi-party approval",
    q: "El equipo de seguridad quiere que ninguna persona, por sí sola, pueda restaurar/compartir datos de un vault de AWS Backup lógicamente aislado (logically air-gapped) en un escenario de recuperación ante ransomware — se exige que varias personas autorizadas aprueben la operación antes de ejecutarla. ¿Qué capacidad de gobernanza de AWS, lanzada en 2025, está diseñada para esto?",
    options: [
      "Una SCP con Deny condicionado a aws:MultiFactorAuthPresent",
      "Multi-party approval (MPA): requiere que AWS Organizations e IAM Identity Center estén habilitados, y que un 'equipo de aprobación' formado por varias personas vote antes de ejecutar operaciones críticas como compartir un backup de un vault air-gapped",
      "Permission boundaries combinados con Access Analyzer",
      "AWS Config conformance packs con remediación automática",
    ],
    correct: 1,
    explain: "Multi-party approval (MPA) requiere AWS Organizations e IAM Identity Center. Permite crear equipos de aprobación cuyos miembros votan (con verificación OTP desde 2026) antes de que se ejecute una operación sensible; su primera integración fue con AWS Backup para vaults lógicamente aislados, permitiendo compartir/restaurar backups desde una cuenta potencialmente comprometida solo con aprobación distribuida, sin que una sola persona pueda hacerlo unilateralmente.",
  },
  {
    tag: "Declarative Policies – atributos EC2/VPC/AMI",
    q: "Quieres garantizar, para TODA la organización y de forma que ninguna cuenta pueda desviarse aunque tenga AdministratorAccess local, que ninguna instancia EC2 pueda usar IMDSv1 y que ninguna VPC pueda comunicarse con internet a través de un Internet Gateway salvo excepciones explícitas. ¿Qué mecanismo de AWS Organizations aplica exactamente este tipo de control?",
    options: [
      "Una SCP con Deny sobre ec2:RunInstances si no incluye una etiqueta concreta",
      "Declarative Policies: fijan atributos concretos como 'IMDSv2 enforcement' y 'VPC Block Public Access' como estado de configuración deseado a nivel de organización/OU, manteniéndolo incluso si se lanzan nuevas cuentas o aparecen nuevas APIs",
      "AWS Config managed rules con remediación automática vía SSM",
      "Resource Control Policies (RCP) sobre el servicio EC2",
    ],
    correct: 1,
    explain: "Declarative Policies (lanzadas a finales de 2024) cubren, entre otros, atributos de EC2/VPC como 'VPC Block Public Access', 'Image (AMI) Block Public Access' e 'IMDSv2 enforcement'. A diferencia de una SCP (que deniega llamadas de API), una Declarative Policy fija un estado de configuración deseado que se mantiene automáticamente incluso ante cuentas nuevas o funcionalidades nuevas del servicio — no es un mecanismo allow/deny de acciones.",
  },
  {
    tag: "RCP – exención de la cuenta de gestión",
    q: "Una empresa despliega una RCP a nivel de la raíz de la organización para restringir el acceso a buckets S3 solo a identidades dentro de la organización. Un ingeniero, autenticado como usuario IAM en la cuenta de GESTIÓN (management account) de la Organization, accede sin problema a un bucket de una cuenta miembro que en teoría debería estar bloqueado por esa RCP para orígenes externos. ¿A qué se debe esto?",
    options: [
      "Es un error de configuración: las RCPs siempre deben aplicar también a la cuenta de gestión",
      "Las RCPs, por diseño, NO afectan a las solicitudes realizadas por identidades de la cuenta de gestión de la organización — solo restringen recursos en cuentas miembro",
      "El usuario tiene MFA activo, lo que le exime automáticamente de cualquier RCP",
      "Las RCPs solo aplican a llamadas realizadas desde fuera de la región del bucket",
    ],
    correct: 1,
    explain: "Una particularidad clave de las RCPs (muy preguntada porque es contraintuitiva) es que NO se aplican a las solicitudes hechas por principals de la cuenta de gestión de la Organization, incluso si el recurso vive en una cuenta miembro dentro del scope de la política. Es un caso análogo a por qué la cuenta de gestión no debería usarse para operaciones del día a día: escapa a las restricciones de guardrails organizacionales de este tipo.",
  },
  {
    tag: "IAM Roles Anywhere – ABAC con certificados",
    q: "Una empresa usa IAM Roles Anywhere para dar credenciales a servidores on-premises, y quiere que el rol asumido lleve automáticamente un tag de sesión con el nombre del servidor, extraído del propio certificado X.509 usado para autenticarse, para poder aplicar políticas ABAC sin gestionar tags manualmente. ¿Es esto posible, y cómo?",
    options: [
      "No es posible; los tags de sesión solo pueden añadirse manualmente al invocar CreateSession",
      "Sí: IAM Roles Anywhere puede mapear automáticamente los Relative Distinguished Names (RDNs) del Subject (y campos del Issuer) del certificado X.509 a PrincipalTags de la sesión, permitiendo políticas ABAC basadas en atributos del certificado",
      "Sí, pero solo si el certificado se emite desde AWS Certificate Manager público, nunca desde una CA privada",
      "No, IAM Roles Anywhere no soporta ningún tipo de tagging de sesión",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere puede mapear automáticamente campos del Subject (RDNs como CN, OU) y del Issuer del certificado X.509 presentado a PrincipalTag de la sesión resultante. Esto permite construir políticas ABAC (por ejemplo, 'este servidor solo puede acceder a recursos con el mismo tag OU que su certificado') sin tener que gestionar manualmente los tags de cada sesión.",
  },
  {
    tag: "Verified Permissions – BatchIsAuthorized",
    q: "Tu aplicación SaaS necesita renderizar una lista de 25 documentos y decidir, para cada uno, si el usuario actual puede verlo y si puede editarlo — es decir, hasta 50 decisiones de autorización para una sola carga de página. Hacer 50 llamadas individuales a IsAuthorized añadiría demasiada latencia. ¿Qué ofrece Amazon Verified Permissions para este caso?",
    options: [
      "No hay alternativa; hay que llamar a IsAuthorized 50 veces de forma secuencial",
      "BatchIsAuthorized: permite evaluar hasta 30 decisiones de autorización para un mismo principal o recurso en una sola llamada a la API, reduciendo la latencia frente a llamadas individuales",
      "Hay que exportar las políticas Cedar y evaluarlas localmente en el cliente",
      "Solo es posible si se usa AWS Lambda@Edge para cachear las decisiones",
    ],
    correct: 1,
    explain: "Amazon Verified Permissions soporta BatchIsAuthorized, que agrupa hasta 30 decisiones de autorización en una sola llamada para un principal o recurso dado, muy útil para renderizar interfaces (listas, tablas) donde hace falta decidir de golpe qué acciones están permitidas sobre múltiples elementos, evitando el coste de red de llamadas individuales repetidas.",
  },
  {
    tag: "Permission boundary obligatorio al crear roles",
    q: "Quieres permitir que los desarrolladores creen sus propios IAM Roles (iam:CreateRole) pero garantizar que NUNCA puedan crear un rol sin que lleve adjunto un permission boundary concreto — cerrando la puerta a que se autoconcedan permisos de administrador vía un rol nuevo sin boundary. ¿Qué mecanismo de política aplica exactamente esta restricción?",
    options: [
      "Una SCP con Deny total sobre iam:CreateRole",
      "Una condición en la identity policy del desarrollador usando la clave iam:PermissionsBoundary, exigiendo que cualquier iam:CreateRole/iam:PutRolePermissionsBoundary especifique el ARN exacto del boundary permitido",
      "Un permission boundary no puede exigirse de forma obligatoria; depende de la buena voluntad del desarrollador",
      "Una resource-based policy en IAM",
    ],
    correct: 1,
    explain: "La condición de clave iam:PermissionsBoundary (usada con StringEquals sobre el ARN del boundary permitido) se puede añadir a la identity policy que da a un desarrollador iam:CreateRole y iam:PutRolePermissionsBoundary, denegando la operación si no se adjunta exactamente ese boundary. Es el patrón estándar de AWS para delegar la creación de roles sin habilitar escalada de privilegios.",
  },
  {
    tag: "STS – role chaining y duración de sesión",
    q: "Un usuario asume el Rol A (sesión de 12 horas) y, usando esas credenciales temporales, intenta asumir el Rol B (role chaining) también con --duration-seconds apuntando a 12 horas. ¿Qué ocurre con la duración máxima de la sesión resultante del Rol B?",
    options: [
      "La sesión del Rol B también puede durar hasta 12 horas sin restricción adicional",
      "Cuando se usa role chaining (credenciales temporales de un rol para asumir otro rol), la duración máxima de la nueva sesión se limita a 1 hora, independientemente del MaxSessionDuration configurado en el Rol B",
      "El role chaining está prohibido por AWS STS y la segunda llamada a AssumeRole fallará siempre",
      "La duración depende únicamente de si el usuario tiene MFA activo",
    ],
    correct: 1,
    explain: "AWS STS limita explícitamente el role chaining: si usas las credenciales temporales resultantes de un AssumeRole para llamar de nuevo a AssumeRole sobre otro rol, la duración máxima de esa segunda sesión se limita a 1 hora, sin importar el MaxSessionDuration configurado en el rol de destino. Es un detalle muy preguntado porque contradice la expectativa de que la duración siempre sigue la configuración del rol.",
  },
  {
    tag: "RCP – aws:PrincipalOrgID vs aws:ResourceOrgID",
    q: "Al diseñar guardrails de 'data perimeter' con RCPs, ¿cuál es la diferencia práctica entre condicionar una RCP con aws:PrincipalOrgID y condicionarla con aws:ResourceOrgID?",
    options: [
      "Son sinónimos completamente intercambiables",
      "aws:PrincipalOrgID comprueba a qué organización pertenece la IDENTIDAD que hace la llamada (perímetro de identidad); aws:ResourceOrgID compara la organización del PRINCIPAL con la del propio recurso, útil para permitir acceso cross-account solo dentro de la misma organización sin necesitar listar cada cuenta",
      "aws:ResourceOrgID solo puede usarse en SCPs, nunca en RCPs",
      "aws:PrincipalOrgID ya no existe desde 2025, fue reemplazada por aws:SourceOrgID",
    ],
    correct: 1,
    explain: "aws:PrincipalOrgID es la clave clásica del perímetro de identidad: compara la Organization ID del principal que llama contra un valor fijo. aws:ResourceOrgID (variable, se compara normalmente como '${aws:ResourceOrgID}' o de forma implícita en RCPs) permite expresar 'solo permite acceso si el principal pertenece a la MISMA organización que el propio recurso', un patrón muy usado en RCPs para bloquear el acceso desde fuera de la organización sin necesidad de mantener listas de cuentas.",
  },
  {
    tag: "Access Analyzer – generación de políticas",
    q: "Un equipo lleva 6 meses operando un rol IAM con la política gestionada AdministratorAccess 'temporalmente', y ahora quiere generar una política de mínimo privilegio basada en lo que ese rol REALMENTE ha usado según su actividad registrada en CloudTrail, en vez de escribirla a mano desde cero. ¿Qué funcionalidad de IAM Access Analyzer resuelve esto directamente?",
    options: [
      "External access findings",
      "La generación de políticas basada en actividad de acceso (policy generation): Access Analyzer analiza los eventos de CloudTrail del rol y propone una política IAM de mínimo privilegio con los servicios y acciones realmente utilizados",
      "Unused access findings, que genera automáticamente la política sustituta",
      "IAM Credential Report",
    ],
    correct: 1,
    explain: "IAM Access Analyzer puede generar una política candidata analizando la actividad real registrada en CloudTrail (por un periodo configurable, hasta 90 días) para un rol o usuario dado, proponiendo los servicios y acciones efectivamente usados como punto de partida para una política de mínimo privilegio — mucho más preciso que empezar desde cero o depender solo de Access Advisor a nivel de servicio.",
  },
  {
    tag: "Verified Permissions – policy templates",
    q: "Tu aplicación SaaS multi-tenant tiene el mismo patrón de autorización repetido para cientos de tenants ('el propietario puede editar su propio recurso'), y quieres evitar duplicar la misma política Cedar cientos de veces en el policy store, una por tenant. ¿Qué característica de Amazon Verified Permissions está pensada exactamente para esto?",
    options: [
      "Policy templates: definen una plantilla de política Cedar con placeholders (?principal, ?resource) que luego se instancia como 'template-linked policies' con valores concretos por tenant, sin duplicar la lógica",
      "Crear un policy store distinto por cada tenant y sincronizarlos manualmente",
      "Usar únicamente políticas estáticas sin variables, una por cada combinación posible de usuario/recurso",
      "No es posible; Cedar no soporta parametrización de políticas",
    ],
    correct: 0,
    explain: "Los policy templates de Verified Permissions permiten declarar una única plantilla Cedar con placeholders (?principal y/o ?resource) y luego crear múltiples 'template-linked policies' que instancian esa plantilla con IDs concretos, evitando mantener cientos de copias casi idénticas de la misma política — clave para SaaS multi-tenant a escala.",
  },
  {
    tag: "aws:PrincipalOrgID vs aws:PrincipalOrgPaths",
    q: "Una organización tiene una OU llamada 'Sandbox' bajo la raíz, y quiere una RCP que permita el acceso a un bucket S3 solo a identidades que pertenezcan específicamente a esa OU (y sus sub-OUs), no a toda la organización en general. ¿Qué clave de condición es la adecuada?",
    options: [
      "aws:PrincipalOrgID, apuntando al ID de la organización completa",
      "aws:PrincipalOrgPaths, que permite comparar la ruta jerárquica completa de OUs a la que pertenece el principal (organización/OU raíz/OU intermedia/...), permitiendo acotar a una rama concreta del árbol de OUs",
      "aws:PrincipalAccount, listando manualmente cada cuenta de la OU",
      "aws:ResourceOrgID",
    ],
    correct: 1,
    explain: "aws:PrincipalOrgID solo identifica la organización completa (o-xxxxxxxxxx), sin distinguir OUs. Para acotar a una rama concreta del árbol jerárquico (por ejemplo, solo la OU Sandbox y lo que cuelgue de ella) se usa aws:PrincipalOrgPaths, que contiene la ruta completa de IDs de OU del principal y admite comparación por prefijo — mucho más preciso que mantener listas de cuentas.",
  },
  {
    tag: "Root user – Task policies de AssumeRoot",
    q: "Cuando un administrador de la cuenta de gestión llama a sts:AssumeRoot para realizar una tarea root en una cuenta miembro, ¿qué determina exactamente qué puede hacer esa sesión root temporal?",
    options: [
      "Nada la limita: cualquier sesión obtenida vía AssumeRoot tiene privilegios root completos e irrestrictos, igual que el usuario root tradicional",
      "Una TaskPolicy administrada por AWS obligatoria (por ejemplo, para desbloquear políticas de S3, resolver problemas de KMS, o gestionar la propia configuración de root) que acota la sesión exclusivamente a esa tarea concreta, nunca a privilegios root genéricos",
      "El permission boundary que tuviera adjunto el usuario root antes de eliminar sus credenciales",
      "Una SCP con Allow explícito sobre root:*",
    ],
    correct: 1,
    explain: "A diferencia del root tradicional (que no tiene límites), sts:AssumeRoot exige indicar una de un conjunto acotado de TaskPolicy administradas por AWS (diseñadas para tareas específicas que legítimamente requieren root, como desbloquear una bucket policy que se bloqueó a sí misma). No existe una opción de 'root sin restricciones' vía AssumeRoot — es, por diseño, siempre una sesión root de alcance mínimo para una tarea concreta.",
  },
  {
    tag: "Unused access analyzer – tracking period",
    q: "Al configurar un unused access analyzer en IAM Access Analyzer, ¿qué controla el parámetro de 'tracking period' (periodo de seguimiento)?",
    options: [
      "El tiempo que Access Analyzer tarda en generar el primer hallazgo, siempre fijo en 24 horas",
      "La ventana de tiempo (configurable, con opciones predefinidas de 30/60/90 días o un valor personalizado) durante la cual se monitoriza el uso real de permisos; solo se generan hallazgos de 'no usado' para permisos/identidades que ya existían durante TODA esa ventana",
      "El tiempo que tarda en eliminarse automáticamente un rol no usado",
      "La frecuencia con la que se rota la clave KMS usada por Access Analyzer",
    ],
    correct: 1,
    explain: "El tracking period define durante cuánto tiempo Access Analyzer observa el uso real de permisos antes de considerar algo 'no usado' (por defecto 90 días, configurable). Un detalle clave del examen: solo se evalúan identidades y permisos que ya existían durante TODO ese periodo — un rol creado hace 10 días con un tracking period de 90 no generará todavía un finding de acceso no usado por antigüedad insuficiente.",
  },
  {
    tag: "RCP – servicios soportados",
    q: "Un equipo de seguridad quiere usar una RCP para restringir centralmente el acceso a las tablas de una base de datos NoSQL gestionada de la organización, exigiendo que solo identidades dentro de la propia organización puedan leerlas, incluso si alguna política de identidad o de recurso las expone accidentalmente hacia fuera. Tras las ampliaciones de soporte de RCP hasta 2026, ¿qué servicio permite aplicar esto directamente vía RCP?",
    options: [
      "Amazon RDS, soportado por RCP desde el lanzamiento inicial en 2024",
      "Amazon DynamoDB, incorporado al conjunto de servicios soportados por RCP en una ampliación de 2026, junto con S3, STS, KMS, SQS, Secrets Manager, ECR, OpenSearch Serverless, Cognito y CloudWatch Logs",
      "Amazon Redshift, soportado desde el lanzamiento inicial",
      "Ningún servicio de bases de datos soporta RCPs; solo servicios de almacenamiento de objetos",
    ],
    correct: 1,
    explain: "Las RCPs se lanzaron en noviembre de 2024 cubriendo S3, STS, KMS, SQS y Secrets Manager, y AWS ha ido ampliando la lista progresivamente: ECR y OpenSearch Serverless (2025), y más adelante Cognito, CloudWatch Logs y Amazon DynamoDB. El examen puede preguntar sobre esta lista en evolución; lo clave conceptualmente es que las RCPs solo aplican a los servicios explícitamente soportados en cada momento, no a todo el catálogo de AWS.",
  },
  {
    tag: "Data perimeter – trampa SCP vs RCP",
    q: "Una organización configura una SCP que deniega cualquier acción s3:GetObject salvo que el principal pertenezca a la organización (usando aws:PrincipalOrgID). Sin embargo, un tercero externo consigue leer un objeto de un bucket S3 de la organización porque el bucket tiene una bucket policy que le concede acceso explícito con un Allow. ¿Por qué la SCP no evitó esto?",
    options: [
      "La SCP tiene un error de sintaxis",
      "Las SCP solo restringen lo que pueden hacer las IDENTIDADES de la organización; no se aplican a principals externos que llegan directamente vía una resource-based policy del propio recurso, que es exactamente el hueco que las RCP están diseñadas para cerrar",
      "S3 no soporta SCPs de ningún tipo",
      "Las SCP solo aplican a llamadas hechas desde la consola, no desde la API",
    ],
    correct: 1,
    explain: "Este es el ejemplo canónico de por qué existen las RCP: una SCP acota lo que las identidades DENTRO de tu organización pueden hacer, pero un principal externo (fuera de la organización) que accede vía una bucket policy con Allow explícito nunca 'pasa por' esa SCP, porque las SCP no se evalúan sobre principals ajenos a la organización. Para cerrar ese hueco hace falta una RCP, que sí puede exigir que el acceso a un recurso —venga de quien venga— cumpla una condición como aws:PrincipalOrgID.",
  },
  {
    tag: "SCP – evaluación multi-nivel en el árbol de OUs",
    q: "Una cuenta cuelga de OU-Producción, que a su vez cuelga de la raíz de la organización. La raíz tiene una SCP que permite s3:*, OU-Producción tiene una SCP que deniega explícitamente s3:DeleteBucket, y la propia cuenta no tiene SCPs adicionales. ¿Se puede ejecutar s3:DeleteBucket en esa cuenta?",
    options: [
      "Sí, porque la SCP de la raíz permite s3:* y tiene prioridad por estar más arriba en la jerarquía",
      "No: para que una acción se permita, TODAS las SCPs en el camino completo desde la raíz hasta la cuenta (raíz → OUs intermedias → cuenta) deben permitirla; un Deny explícito en cualquier nivel del árbol bloquea la acción sin importar qué digan los demás niveles",
      "Depende de qué SCP se adjuntó más recientemente",
      "Las SCPs de nivel OU nunca tienen efecto si la cuenta no tiene su propia SCP",
    ],
    correct: 1,
    explain: "Las SCPs se evalúan de forma acumulativa a lo largo de TODO el camino jerárquico desde la raíz de la organización hasta la cuenta (pasando por cada OU intermedia). El permiso efectivo es la intersección de lo permitido en cada nivel, y un Deny explícito en cualquier punto del camino (en este caso, OU-Producción) bloquea la acción para la cuenta, sin importar que un nivel superior (la raíz) la permitiera.",
  },
  {
    tag: "Acceso cross-account",
    q: "Una aplicación en la cuenta A debe asumir un rol de la cuenta B. ¿Qué DOS elementos son imprescindibles para que funcione?",
    options: [
      "Un trust policy en el rol de la cuenta B que autorice al principal de la cuenta A a asumirlo",
      "Un permiso sts:AssumeRole en la política de identidad del principal de la cuenta A",
      "Que ambas cuentas pertenezcan a la misma AWS Organization",
      "Una VPC peering entre las dos cuentas para que STS pueda enrutar la petición",
    ],
    correct: [0, 1],
    explain: "El acceso cross-account exige <b>las dos puntas</b>: el recurso (el rol) debe confiar en quien llama, y quien llama debe tener permiso para llamar. Es el caso clásico en que un Allow en un solo lado no basta. No hace falta Organizations — el cross-account funciona entre cuentas sin relación — ni conectividad de red, porque STS es un endpoint público del servicio, no algo que viva en tu VPC.",
  },
  {
    tag: "Orígenes de un Deny explícito",
    q: "Un usuario recibe AccessDenied pese a tener una identity policy con Allow para la acción. ¿En qué DOS sitios puede estar el Deny que lo bloquea?",
    options: [
      "En una Service Control Policy aplicada a la OU o a la cuenta",
      "En la resource-based policy del recurso al que intenta acceder",
      "En la consola de IAM, que bloquea acciones marcadas como peligrosas",
      "En el historial de CloudTrail, que revoca permisos usados indebidamente",
    ],
    correct: [0, 1],
    explain: "Un Deny explícito en <b>cualquier</b> política aplicable gana siempre: identity policy, resource policy, SCP, RCP, permission boundary o session policy. Aquí los dos candidatos reales son la SCP y la política del recurso. La consola de IAM no bloquea acciones por su cuenta, y CloudTrail es un registro de auditoría: <b>observa</b>, nunca revoca. Confundir un servicio de registro con uno de control es un distractor típico.",
  },
  {
    tag: "Data perimeter",
    q: "Quieres garantizar que tus buckets S3 solo sean accesibles por identidades de tu propia organización y únicamente desde tu red. ¿Qué DOS condition keys aplicarías?",
    options: [
      "aws:PrincipalOrgID, para exigir que quien llama pertenezca a tu organización",
      "aws:SourceVpce, para exigir que la petición llegue por tu VPC endpoint",
      "aws:RequestedRegion, para limitar el acceso a una Región concreta",
      "aws:CurrentTime, para permitir el acceso solo en horario laboral",
    ],
    correct: [0, 1],
    explain: "Un data perimeter se construye sobre dos ejes: <b>quién</b> (identity perimeter, con aws:PrincipalOrgID) y <b>desde dónde</b> (network perimeter, con aws:SourceVpce o aws:SourceIp). Las otras dos condition keys existen y son válidas, pero acotan Región y horario: no responden a la pregunta de identidad ni de red que plantea el enunciado.",
  },
  {
    tag: "Permission boundaries",
    q: "Vas a permitir que los desarrolladores creen sus propios roles sin que puedan escalar privilegios. ¿Qué DOS afirmaciones sobre permission boundaries son correctas?",
    options: [
      "Un permission boundary no concede permisos por sí mismo: define el máximo que una identity policy puede otorgar",
      "Se puede exigir, mediante una condición en la política del desarrollador, que todo rol que cree lleve un boundary concreto",
      "El permission boundary sustituye a la identity policy: basta con adjuntar el boundary",
      "Los permission boundaries se aplican a recursos, igual que las bucket policies",
    ],
    correct: [0, 1],
    explain: "El permiso efectivo es la <b>intersección</b> entre la identity policy y el boundary, así que el boundary por sí solo no concede nada y no sustituye a la política. La condición <code>iam:PermissionsBoundary</code> es justo el mecanismo con el que se delega la creación de roles sin permitir escalada. Y los boundaries se adjuntan a <b>identidades</b> (usuarios y roles), no a recursos.",
  },
  {
    tag: "Federación con IAM Identity Center",
    q: "Una empresa con 3.000 empleados en un IdP corporativo quiere dar acceso a 60 cuentas de AWS sin crear usuarios IAM. ¿Qué DOS afirmaciones describen el enfoque correcto?",
    options: [
      "IAM Identity Center federa con el IdP y asigna permission sets a grupos sobre las cuentas de la organización",
      "Los usuarios reciben credenciales temporales vía STS, no claves de acceso de larga duración",
      "Hay que crear un usuario IAM por empleado en cada cuenta y sincronizarlo con el IdP",
      "Cada empleado debe compartir una access key común para simplificar la gestión",
    ],
    correct: [0, 1],
    explain: "<b>Identity Center</b> con <b>permission sets</b> asignados a grupos es el patrón recomendado a escala, y la federación entrega siempre <b>credenciales temporales de STS</b>. Crear 3.000 usuarios en 60 cuentas es exactamente el problema que la federación elimina (180.000 identidades que mantener). Y compartir una clave entre personas destruye la atribución: nunca es la respuesta.",
  },
];
