var QUIZ_DATA = [
  {
    tag: "Evaluación de políticas",
    q: "Un usuario tiene una política de identidad que permite s3:GetObject sobre un bucket, pero el bucket tiene una bucket policy con un Deny explícito para ese mismo usuario. ¿Qué ocurre?",
    options: [
      "Se deniega: un Deny explícito en cualquier política aplicable anula todo Allow",
      "Se permite el acceso: la política de identidad del usuario prevalece sobre la del bucket",
      "Se permite: la bucket policy solo se evalúa si el bucket pertenece a otra cuenta",
      "Se resuelve según cuál de las dos políticas se creó o modificó más recientemente",
    ],
    correct: 0,
    explain: "El orden de evaluación de IAM es: Deny explícito &gt; Allow explícito &gt; Deny por defecto. Un Deny explícito en CUALQUIER política que aplique (identidad, recurso, SCP, RCP, boundary, session policy) anula cualquier Allow, sin importar dónde esté. Que el recurso sea de la propia cuenta no exime de evaluar su resource policy. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SCP vs RCP",
    q: "¿Cuál es la diferencia clave entre una Service Control Policy (SCP) y una Resource Control Policy (RCP) en AWS Organizations?",
    options: [
      "Las SCP acotan el acceso a los recursos y las RCP acotan a las identidades",
      "Las SCP acotan lo que pueden hacer las identidades de la organización",
      "Las SCP solo aplican a la cuenta de gestión y las RCP a las cuentas miembro",
      "Las RCP reemplazaron a las SCP y ya no se pueden crear SCP nuevas",
    ],
    correct: 1,
    explain: "Las SCP son guardrails que acotan el máximo permiso disponible para principals DENTRO de la organización. Las RCP acotan el acceso a los RECURSOS en sí, incluyendo principals externos, cerrando huecos que las SCP no cubren porque las SCP no aplican a identidades fuera de la organización. Invertir esa relación es el error clásico. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Permission boundaries",
    q: "Un desarrollador tiene un permission boundary que solo permite acciones sobre S3 y DynamoDB. Su identity-based policy le concede AdministratorAccess. ¿Qué puede hacer realmente?",
    options: [
      "Todo: AdministratorAccess prevalece sobre cualquier permission boundary",
      "Nada: el boundary y la identity policy entran en conflicto y se deniega",
      "Solo acciones de S3 y DynamoDB: el permiso efectivo es la intersección",
      "Todo salvo S3 y DynamoDB: el boundary excluye lo que enumera",
    ],
    correct: 2,
    explain: "El permission boundary NO otorga permisos por sí mismo: define el máximo conjunto de permisos que una identity-based policy puede conceder. El permiso efectivo es la INTERSECCIÓN entre la identity policy y el boundary, nunca la unión ni la diferencia. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "STS",
    q: "Una aplicación móvil autentica usuarios contra Google (proveedor OIDC) y necesita credenciales temporales de AWS para acceder a un bucket S3 de forma directa desde el móvil. ¿Qué API de STS es la adecuada?",
    options: [
      "sts:GetSessionToken, que devuelve credenciales temporales al usuario IAM que llama",
      "sts:GetFederationToken, que federa a partir de credenciales IAM de larga duración",
      "sts:AssumeRoleWithSAML, que intercambia una aserción SAML del IdP por un rol",
      "sts:AssumeRoleWithWebIdentity, que intercambia el token del proveedor por un rol",
    ],
    correct: 3,
    explain: "AssumeRoleWithWebIdentity intercambia un token OIDC (Google, Facebook, Amazon o cualquier IdP compatible) por credenciales temporales de un rol. GetSessionToken y GetFederationToken parten de credenciales IAM de larga duración, que es justo lo que no queremos incrustar en un móvil. En producción AWS recomienda Cognito Identity Pools por encima. <a href=\"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Federación SAML",
    q: "Una empresa usa Active Directory Federation Services (ADFS) on-premises y quiere dar acceso a la consola de AWS a sus empleados sin crear usuarios IAM. ¿Qué mecanismo es el más apropiado?",
    options: [
      "AssumeRoleWithSAML contra un IdP SAML 2.0 registrado como proveedor en IAM",
      "IAM Roles Anywhere, registrando el certificado de ADFS como CA de confianza",
      "Access keys de larga duración generadas por AD y repartidas a cada empleado",
      "IAM Identity Center en modo standalone, con su directorio interno como fuente",
    ],
    correct: 0,
    explain: "AssumeRoleWithSAML permite federar identidades desde un IdP SAML 2.0 (ADFS, Okta, Entra ID) directamente contra un IAM Role, sin usuarios IAM individuales. IAM Roles Anywhere resuelve otro problema (cargas de trabajo, no personas) y el modo standalone de Identity Center ignora precisamente el directorio que la empresa ya tiene. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM Identity Center",
    q: "¿Cuál es la diferencia principal entre un IAM Role tradicional cross-account y un Permission Set de IAM Identity Center?",
    options: [
      "Ninguna: un permission set es solo una vista de consola sobre roles ya creados",
      "El permission set se define una vez y se provisiona como rol en cada cuenta",
      "El permission set se asigna al usuario root de cada cuenta miembro asignada",
      "El permission set solo admite políticas inline, nunca gestionadas por AWS",
    ],
    correct: 1,
    explain: "IAM Identity Center centraliza la gestión: defines un Permission Set una vez y el servicio provisiona y sincroniza automáticamente los IAM Roles necesarios en cada cuenta asignada, evitando gestionar roles cuenta por cuenta. Admite políticas gestionadas por AWS, gestionadas por el cliente e inline, y nunca se asigna al usuario root. <a href=\"https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM Access Analyzer",
    q: "¿Qué tipo de hallazgo genera IAM Access Analyzer cuando detecta que un rol IAM no se ha usado en los últimos 90 días?",
    options: [
      "External access finding, porque el rol es accesible desde fuera de la cuenta",
      "Policy validation finding, porque la política del rol incumple una buena práctica",
      "Unused access finding, que señala roles y permisos sin uso en el periodo",
      "Ninguno: Access Analyzer solo analiza políticas estáticas, nunca el uso real",
    ],
    correct: 2,
    explain: "Access Analyzer tiene tres capacidades distintas: external access findings (recursos accesibles desde fuera de tu zona de confianza), unused access findings (roles, permisos y access keys sin uso reciente) y policy validation (sintaxis y buenas prácticas mientras escribes). La antigüedad sin uso es exactamente el dominio de la segunda. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "ABAC",
    q: "En una estrategia de control de acceso basado en atributos (ABAC) con IAM, ¿qué condición se usaría típicamente en una política para permitir que un usuario solo pueda etiquetar/acceder a recursos que coincidan con su propio departamento?",
    options: [
      "\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:PrincipalTag/costcenter}\"}",
      "\"StringEquals\": {\"aws:ResourceTag/department\": \"${aws:ResourceTag/owner}\"}",
      "\"StringNotEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/team}\"}",
      "\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/department}\"}",
    ],
    correct: 3,
    explain: "ABAC compara una etiqueta del PRINCIPAL con la misma etiqueta del RECURSO usando variables de política (<code>aws:PrincipalTag/clave</code> frente a <code>${aws:ResourceTag/clave}</code>), y así la regla escala sin reescribir la política por cada recurso nuevo. Comparar dos tags del mismo lado, o negar la comparación, rompe el patrón. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_attribute-based-access-control.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Confused deputy",
    q: "Un servicio de AWS (ej. CloudTrail) asume un rol en tu cuenta en nombre de otro cliente de AWS y por error accede a datos de tu cuenta que no le corresponden. ¿Qué condición de política previene este 'confused deputy problem'?",
    options: [
      "aws:SourceArn o aws:SourceAccount en la trust policy del rol de servicio",
      "aws:SourceIp en la trust policy, limitando las IP desde las que llama el servicio",
      "aws:MultiFactorAuthPresent, exigiendo MFA al servicio que asume el rol",
      "aws:RequestedRegion, limitando el rol a la Región donde vive el recurso afectado",
    ],
    correct: 0,
    explain: "Para evitar que un servicio de AWS sea 'engañado' y actúe en nombre de un tercero no autorizado, se añade a la trust policy una condición con aws:SourceArn (o aws:SourceAccount) que restringe qué recurso o cuenta concreta puede provocar ese AssumeRole. Un servicio de AWS no llega desde una IP tuya ni presenta MFA, así que esas condiciones no aplican. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "Una empresa tiene servidores on-premises (fuera de AWS) que necesitan credenciales temporales de AWS sin usar access keys de larga duración. ¿Qué servicio está diseñado exactamente para este caso?",
    options: [
      "AWS Systems Manager Hybrid Activations, que registra el servidor como nodo gestionado",
      "IAM Roles Anywhere, que cambia un certificado X.509 por credenciales de STS",
      "IAM Identity Center, desplegando su conector de directorio en el servidor",
      "Cognito Identity Pools, que emite credenciales a identidades externas",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere permite a cargas de trabajo fuera de AWS obtener credenciales temporales presentando un certificado X.509 firmado por una CA registrada en IAM. Hybrid Activations sirve para gestionar el servidor con SSM, no para dar credenciales arbitrarias de IAM, y Cognito está pensado para identidades de usuarios finales de una aplicación. <a href=\"https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Root user",
    q: "AWS introdujo 'Centralized Root Access Management' en Organizations. ¿Qué permite hacer esta capacidad?",
    options: [
      "Eliminar el usuario root de cada cuenta miembro, que deja de existir del todo",
      "Convertir el root de cada cuenta en un rol IAM asumible por los administradores",
      "Gestionar y eliminar centralmente las credenciales root de las cuentas miembro",
      "Sustituir el MFA de la cuenta de gestión por aprobación de varios administradores",
    ],
    correct: 2,
    explain: "Esta capacidad permite gestionar de forma centralizada las credenciales root de las cuentas miembro —eliminar contraseña, access keys y MFA, e impedir su recuperación— e invocar un conjunto acotado de tareas privilegiadas sin recuperar la contraseña cuenta por cuenta. El usuario root sigue existiendo como identidad: lo que desaparece son sus credenciales de larga duración. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-enable-root-access.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "MFA",
    q: "¿Qué clave de condición se usa en una política IAM para exigir que una API call se haya realizado con una sesión autenticada por MFA?",
    options: [
      "sts:MfaAuthenticated, que la sesión temporal expone tras validar el MFA",
      "aws:MFARequired, que exige un segundo factor antes de evaluar la política",
      "iam:MFAEnabled, que indica si el usuario tiene un dispositivo MFA registrado",
      "aws:MultiFactorAuthPresent, que indica si la sesión se autenticó con MFA",
    ],
    correct: 3,
    explain: "La clave global estándar es <code>aws:MultiFactorAuthPresent</code>, de tipo Bool. Las otras tres no existen como condition keys de IAM: son inventos plausibles que mezclan nombres de servicio con conceptos reales. Una buena práctica muy preguntada es combinarla con <code>aws:MultiFactorAuthAge</code> para limitar la antigüedad de la sesión MFA. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Resource-based policies",
    q: "¿Cuál de estas afirmaciones sobre políticas basadas en recursos (resource-based policies) es correcta?",
    options: [
      "Permiten nombrar un Principal de otra cuenta y concederle acceso directamente",
      "Solo los IAM Roles admiten políticas basadas en recursos, ningún otro servicio",
      "No admiten el elemento Condition, solo Effect, Principal, Action y Resource",
      "Sustituyen a las políticas de identidad: si existen, IAM ignora a las demás",
    ],
    correct: 0,
    explain: "Buckets S3, claves KMS, colas SQS, topics SNS o funciones Lambda soportan resource-based policies, que incluyen un elemento <code>Principal</code> y pueden nombrar directamente una identidad de otra cuenta, sin que esta asuma un rol en la tuya. Admiten condiciones como cualquier política JSON y se evalúan junto a las de identidad, no en su lugar. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Credential report vs Access Advisor",
    q: "¿Cuál es la diferencia entre el IAM Credential Report y el IAM Access Advisor?",
    options: [
      "Son el mismo informe: el Credential Report es la versión CSV de Access Advisor",
      "El Credential Report audita contraseñas, access keys y MFA de cada usuario",
      "Access Advisor solo funciona sobre el usuario root, no sobre usuarios ni roles",
      "El Credential Report necesita GuardDuty habilitado para poder generarse",
    ],
    correct: 1,
    explain: "El Credential Report es un CSV a nivel de cuenta que audita el ESTADO de las credenciales de todos los usuarios IAM (antigüedad de contraseña, access keys, MFA). Access Advisor muestra el HISTÓRICO de servicios accedidos por un usuario o rol, y es la herramienta para recortar permisos no usados. No dependen de GuardDuty ni se limitan al root. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_last-accessed.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cross-account trust policy",
    q: "¿Qué elemento es obligatorio en la trust policy (assume role policy document) de un IAM Role para permitir que una cuenta externa lo asuma?",
    options: [
      "Una SCP en la cuenta externa que autorice explícitamente la llamada al rol",
      "Una bucket policy asociada al rol que liste la cuenta externa como Principal",
      "Un Principal con la cuenta o rol externo y la acción sts:AssumeRole",
      "Nada: por defecto cualquier cuenta de AWS puede asumir cualquier rol",
    ],
    correct: 2,
    explain: "La trust policy del rol debe incluir un <code>Principal</code> con el ARN de la cuenta o rol externo autorizado y <code>Action: sts:AssumeRole</code>. Además, quien asume necesita en su propia identity policy el permiso de llamar a sts:AssumeRole sobre ese ARN: hacen falta AMBOS lados. Los roles no tienen bucket policies, y sin trust policy nadie externo puede asumirlos. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Data perimeter",
    q: "En el concepto de 'data perimeter' de AWS, ¿qué combinación de controles se usa típicamente para asegurar que los datos NUNCA salgan de la organización, incluso con credenciales válidas robadas?",
    options: [
      "Cifrado con KMS de todos los objetos, para que el dato salga siempre cifrado",
      "Security Groups restrictivos que bloqueen todo el tráfico saliente de la VPC",
      "Rotación de access keys cada 90 días y una política de contraseñas estricta",
      "SCP y RCP con aws:PrincipalOrgID, junto a políticas de VPC endpoint",
    ],
    correct: 3,
    explain: "El data perimeter combina tres perímetros: identidad (¿quién accede? SCP/RCP con aws:PrincipalOrgID), recurso (¿es un recurso de confianza? aws:ResourceOrgID) y red (¿desde dónde? VPC endpoint policies con aws:SourceVpce). El cifrado protege el dato en reposo pero no impide que una credencial válida lo descifre; los Security Groups no ven la identidad que llama. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/building-a-data-perimeter-on-aws/building-a-data-perimeter-on-aws.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Session policies",
    q: "Cuando llamas a sts:AssumeRole pasando un parámetro --policy adicional (session policy), ¿cómo afecta esto a los permisos efectivos de la sesión resultante?",
    options: [
      "Acota los permisos del rol: el resultado es la intersección de ambos",
      "Amplía los permisos del rol con lo que declare la session policy",
      "Sustituye a la política del rol durante toda la sesión temporal",
      "No tiene efecto: las session policies solo aplican a usuarios federados",
    ],
    correct: 0,
    explain: "Igual que un permission boundary, una session policy NUNCA amplía permisos: solo puede acotar por intersección los que ya tiene el rol asumido. Es el mecanismo para entregar credenciales temporales más restringidas a partir de un rol amplio, y se puede pasar tanto en AssumeRole como en AssumeRoleWithSAML o AssumeRoleWithWebIdentity. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Declarative policies",
    q: "AWS Organizations introdujo 'Declarative Policies'. ¿En qué se diferencian de las SCP?",
    options: [
      "Son las SCP renombradas: el mecanismo y la sintaxis son exactamente los mismos",
      "Fijan la configuración deseada de atributos de servicio en toda la organización",
      "Solo pueden adjuntarse a la cuenta de gestión, nunca a una OU o cuenta miembro",
      "Sustituyen a AWS Config: evalúan reglas de cumplimiento y remedian desviaciones",
    ],
    correct: 1,
    explain: "A diferencia de las SCP, que permiten o deniegan llamadas a la API, las Declarative Policies establecen y mantienen un estado de configuración deseado a nivel de organización u OU para atributos concretos de ciertos servicios (por ejemplo exigir IMDSv2 o bloquear el acceso público a AMIs). Se aplican en el plano de control del servicio y se mantienen aunque el servicio añada APIs nuevas. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Policy evaluation con VPC endpoints",
    q: "¿Qué clave de condición permite restringir el acceso a un bucket S3 exclusivamente a peticiones que pasen por un VPC endpoint específico?",
    options: [
      "aws:SourceIp, que compara la IP pública de origen de la petición",
      "aws:VpcSourceIp, que compara la IP privada asignada dentro de la VPC",
      "aws:SourceVpce, que compara el ID del VPC endpoint utilizado",
      "s3:VpcEndpointId, que compara el endpoint declarado en el bucket",
    ],
    correct: 2,
    explain: "<code>aws:SourceVpce</code> en una bucket policy (o cualquier resource policy compatible) restringe el acceso a las peticiones que viajan por un VPC endpoint concreto: es el control central del perímetro de red. aws:SourceIp mira direcciones, no endpoints, y las otras dos claves no existen. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Inline vs managed policies",
    q: "¿Cuál es la principal desventaja de usar políticas inline en lugar de políticas gestionadas (managed policies)?",
    options: [
      "Las políticas inline no admiten el elemento Condition en sus statements",
      "Las políticas inline solo pueden permitir acciones, nunca denegarlas",
      "Las políticas inline no pueden adjuntarse a roles, solo a usuarios y grupos",
      "Las políticas inline no se reutilizan ni se versionan de forma centralizada",
    ],
    correct: 3,
    explain: "Una política inline vive embebida en una única identidad (usuario, grupo o rol): no se puede adjuntar a otras identidades ni tiene versiones que revertir, lo que dificulta reutilizarla, auditarla y gestionarla a escala frente a una customer managed policy. En expresividad son idénticas: admiten Condition, Deny y cualquier tipo de identidad. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Cognito",
    q: "Tu aplicación web tiene su propio sistema de registro/login de usuarios finales, y tras autenticarse necesitan subir archivos directamente a un bucket S3 con credenciales temporales de AWS. ¿Qué combinación de componentes de Cognito usarías?",
    options: [
      "Un User Pool emite el JWT; un Identity Pool lo cambia por credenciales",
      "Solo un User Pool, que ya devuelve credenciales temporales de AWS",
      "Solo un Identity Pool, que gestiona el registro y el login de usuarios",
      "Un User Pool federado con AssumeRoleWithSAML contra el bucket destino",
    ],
    correct: 0,
    explain: "El User Pool gestiona identidad y login y devuelve JSON Web Tokens, pero NO entrega credenciales de AWS. El Identity Pool es quien intercambia ese token ya autenticado por credenciales temporales de STS asociadas a un rol, permitiendo el acceso directo a S3. Confundir ambos componentes es el error más habitual del examen. <a href=\"https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 presigned URLs",
    q: "¿Qué ocurre con un S3 presigned URL si, antes de que expire, se revoca el permiso s3:GetObject del usuario que la generó?",
    options: [
      "Sigue funcionando: la firma congela los permisos vigentes al generarla",
      "Deja de funcionar: cada uso se evalúa contra los permisos actuales",
      "Deja de funcionar, pero solo tras un retardo de propagación de 1 minuto",
      "Sigue funcionando: una URL prefirmada no se puede revocar nunca",
    ],
    correct: 1,
    explain: "Un presigned URL no es una credencial independiente: es una firma que delega, durante una ventana de tiempo, el permiso VIGENTE del firmante. Si ese permiso desaparece antes de que la URL expire, la petición se deniega, porque IAM se evalúa de nuevo en cada acceso. La caducidad de la URL es un techo, no una garantía de acceso. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Directory Service",
    q: "Una empresa tiene un Active Directory on-premises que quiere seguir usando como fuente de identidad, sin migrar datos ni replicar el directorio dentro de AWS. ¿Qué opción de AWS Directory Service encaja?",
    options: [
      "AWS Managed Microsoft AD, que crea un directorio gestionado dentro de AWS",
      "Simple AD, un directorio compatible con Samba que vive en tu propia VPC",
      "AD Connector, un proxy que redirige la autenticación al AD on-premises",
      "Cognito User Pools, que importa los usuarios del AD mediante un fichero CSV",
    ],
    correct: 2,
    explain: "AD Connector es un simple proxy de directorio: redirige las solicitudes de autenticación al Active Directory on-premises existente sin copiar ni sincronizar datos. Managed Microsoft AD y Simple AD sí crean un directorio dentro de AWS, que es justo lo que el enunciado descarta, y Cognito está pensado para usuarios finales de aplicaciones, no para empleados con AD. <a href=\"https://docs.aws.amazon.com/directoryservice/latest/admin-guide/directory_ad_connector.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Verified Permissions",
    q: "Tu equipo está construyendo una aplicación SaaS multi-tenant y necesita decidir, en cada request, si el usuario autenticado puede ver un documento concreto según su rol y el tenant al que pertenece. ¿Qué servicio de AWS está diseñado específicamente para esto?",
    options: [
      "IAM Access Analyzer, evaluando las políticas de la propia aplicación en cada request",
      "Una SCP por tenant que deniegue el acceso a los documentos de los demás",
      "AWS Config Rules, que evalúa la conformidad de cada documento del tenant",
      "Amazon Verified Permissions, con políticas Cedar consultadas vía IsAuthorized",
    ],
    correct: 3,
    explain: "Amazon Verified Permissions es un motor de autorización gestionado basado en el lenguaje Cedar, pensado para la lógica de autorización DENTRO de tus aplicaciones (quién puede ver o editar qué objeto de negocio), no para permisos sobre la API de AWS. Las SCP y Config operan sobre recursos de AWS y no tienen visibilidad de los documentos de un tenant. <a href=\"https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/what-is-avp.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM paths",
    q: "¿Para qué se usa principalmente el 'path' (ej. /division_abc/subdivision_xyz/) de un IAM User o Role?",
    options: [
      "Agrupa identidades por prefijo en el ARN y permite delegar su administración",
      "Indica la ruta dentro del bucket de S3 donde se guardan los logs de esa identidad",
      "Define la Región de AWS en la que se crea y vive esa identidad de IAM",
      "Fija el orden en que se evalúan las políticas adjuntas a la identidad",
    ],
    correct: 0,
    explain: "El path forma parte del ARN (<code>arn:aws:iam::cuenta:role/PATH/nombre</code>) y sirve para organizar identidades por equipo o proyecto, de modo que una política de administración con comodín sobre ese path delegue la gestión solo de esa rama. IAM es un servicio global, sin Región, y el orden de las políticas nunca influye en la evaluación. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Policy Simulator vs Access Analyzer",
    q: "Quieres comprobar, antes de desplegarla, si una política IAM concreta permitiría a un rol borrar un bucket S3 específico — sin ejecutar la acción real ni dejar rastro en CloudTrail. ¿Qué herramienta usarías?",
    options: [
      "IAM Access Analyzer, revisando los external access findings del bucket",
      "IAM Policy Simulator, con simulate-principal-policy sobre esa acción",
      "AWS Config conformance packs, evaluando la política contra las reglas",
      "Amazon GuardDuty, que detecta los intentos de borrado sobre el bucket",
    ],
    correct: 1,
    explain: "El Policy Simulator responde exactamente a '¿esta política permitiría esta acción concreta sobre este recurso?' sin enviar la petición real. Access Analyzer audita la postura de acceso YA EXISTENTE, Config evalúa configuración desplegada y GuardDuty detecta actividad sospechosa a posteriori: ninguno responde una pregunta hipotética previa al despliegue. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_testing-policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Access Analyzer – Internal access",
    q: "Tu organización en AWS Organizations tiene decenas de cuentas. Quieres saber, teniendo en cuenta el efecto combinado de las políticas de identidad, las SCPs y las RCPs, qué roles y usuarios DENTRO de tu propia organización pueden llegar a acceder a un bucket S3 crítico de otra cuenta — no te interesa el acceso externo. ¿Qué capacidad de IAM Access Analyzer, lanzada en 2025, responde exactamente a esto?",
    options: [
      "External access findings de un analyzer con alcance de una sola cuenta",
      "Unused access findings sobre los roles de todas las cuentas",
      "Internal access findings, que evalúan a la vez políticas, SCP y RCP",
      "El IAM Credential Report consolidado de todas las cuentas miembro",
    ],
    correct: 2,
    explain: "Los internal access findings usan razonamiento automatizado para evaluar CONJUNTAMENTE identity-based policies, SCPs y RCPs y mostrar qué identidades de la organización pueden acceder a recursos de S3, DynamoDB o RDS. Los external access findings solo miran acceso desde fuera de la zona de confianza, y los unused access findings hablan de permisos sin usar, no de quién puede llegar. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "STS AssumeRoot",
    q: "Una cuenta miembro de la organización tiene habilitado Centralized Root Access Management y sus credenciales root han sido eliminadas. Un administrador de la cuenta de gestión necesita desbloquear temporalmente una bucket policy de S3 corrupta en esa cuenta miembro, una tarea que solo root puede ejecutar. ¿Qué es obligatorio para lograrlo?",
    options: [
      "sts:AssumeRole sobre un rol con AdministratorAccess, equivalente a root",
      "sts:AssumeRoleWithSAML contra el IdP corporativo con el grupo de administradores",
      "Recuperar la contraseña root de la cuenta miembro por el flujo estándar",
      "sts:AssumeRoot desde la cuenta de gestión, indicando una TaskPolicy de AWS",
    ],
    correct: 3,
    explain: "sts:AssumeRoot solo puede invocarse con credenciales de la cuenta de gestión o de un delegated administrator de IAM, nunca con credenciales root, y exige indicar una TaskPolicy gestionada por AWS que acota la sesión a esa tarea concreta. AdministratorAccess no cubre las acciones reservadas al root, y el flujo de recuperación de contraseña es justo lo que esta capacidad elimina. <a href=\"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoot.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Access Analyzer – Custom policy checks",
    q: "Tu equipo de plataforma quiere bloquear en el pipeline de CI/CD cualquier pull request que añada un permiso peligroso concreto (por ejemplo iam:CreateAccessKey) a una política IAM, ANTES de que se despliegue. ¿Qué API de IAM Access Analyzer encaja para este control automatizado?",
    options: [
      "CheckAccessNotGranted, que comprueba que la política no concede esos permisos",
      "ListFindingsV2, que enumera todos los hallazgos abiertos del analyzer de la cuenta",
      "GetGeneratedPolicy, que recupera la política generada desde CloudTrail",
      "SimulatePrincipalPolicy, que simula la acción contra el principal indicado",
    ],
    correct: 0,
    explain: "CheckAccessNotGranted, uno de los custom policy checks basados en razonamiento automatizado, recibe una política candidata y una lista de acciones críticas y devuelve PASS o FAIL: es el gate natural de CI/CD. Su hermana CheckNoNewAccess compara la política nueva contra una de referencia. SimulatePrincipalPolicy exige que el principal ya exista en la cuenta, no sirve para una política aún sin desplegar. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-custom-policy-checks.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "aws:CalledVia",
    q: "Quieres permitir que un usuario ejecute consultas en Amazon Athena que internamente llaman a S3 y a AWS Glue en su nombre, pero impedir que ese mismo usuario llame directamente a esas acciones de S3/Glue fuera del contexto de Athena. ¿Qué clave de condición IAM está diseñada exactamente para este escenario?",
    options: [
      "aws:SourceArn, que identifica el recurso que originó la llamada del servicio",
      "aws:CalledVia, que lista los servicios que llamaron en nombre del principal",
      "aws:ViaAWSService, que indica si la llamada la hizo un servicio cualquiera",
      "aws:PrincipalServiceName, que identifica al service principal que llama",
    ],
    correct: 1,
    explain: "<code>aws:CalledVia</code> contiene la cadena ordenada de servicios de AWS que reenviaron la petición en nombre del principal, así que con un StringEquals sobre <code>athena.amazonaws.com</code> puedes permitir s3:GetObject solo cuando venga de Athena y denegar la llamada directa. aws:ViaAWSService es booleana y no distingue QUÉ servicio, y aws:SourceArn se usa en trust policies contra el confused deputy. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SCP – lenguaje IAM completo (2025)",
    q: "Hasta hace poco, las SCPs solo soportaban un subconjunto limitado del lenguaje de políticas IAM. Tras la actualización de AWS Organizations de septiembre de 2025, ¿qué nueva capacidad de sintaxis pasó a estar disponible en las SCPs?",
    options: [
      "Las SCP pasaron a poder conceder permisos, como una política de identidad",
      "Las SCP pasaron a aplicarse también a principals de fuera de la organización",
      "Las SCP pasaron a soportar el lenguaje completo de políticas de IAM",
      "Las SCP pasaron a evaluarse antes que las políticas de identidad",
    ],
    correct: 2,
    explain: "Las SCP admiten ya el lenguaje completo de políticas IAM: condiciones, ARNs de recurso concretos, NotAction en statements Allow, comodines en posiciones intermedias del Action y el elemento NotResource. Esto iguala su expresividad a la de una managed policy, pero NO cambia su naturaleza: siguen siendo guardrails que acotan, nunca conceden, y solo aplican a identidades de la organización. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_syntax.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM Identity Center – Trusted Identity Propagation",
    q: "Un analista corporativo, autenticado en IAM Identity Center, consulta datos en Amazon Athena/Redshift a través de Amazon QuickSight. La empresa quiere que los logs de acceso a los datos subyacentes en S3/Lake Formation muestren la identidad corporativa real del analista (no un rol de servicio genérico), y que los permisos de acceso a los datos se evalúen según sus atributos/grupos reales. ¿Qué mecanismo de IAM Identity Center habilita esto?",
    options: [
      "Permission sets asignados directamente al analista en cada cuenta de datos",
      "Session policies aplicadas al rol de servicio que usa QuickSight",
      "AssumeRoleWithSAML clásico contra el IdP corporativo de la empresa",
      "Trusted Identity Propagation, que propaga el contexto de identidad",
    ],
    correct: 3,
    explain: "Trusted Identity Propagation añade el contexto de identidad del usuario de Identity Center al rol IAM cuando un servicio llama a otro en su nombre (QuickSight, Athena, Redshift, EMR, OpenSearch, SageMaker Unified Studio). Así los permisos de datos y los registros de CloudTrail reflejan la identidad corporativa real en vez de un rol de servicio compartido, sin crear un rol por persona. <a href=\"https://docs.aws.amazon.com/singlesignon/latest/userguide/trustedidentitypropagation-overview.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Multi-party approval",
    q: "El equipo de seguridad quiere que ninguna persona, por sí sola, pueda restaurar/compartir datos de un vault de AWS Backup lógicamente aislado (logically air-gapped) en un escenario de recuperación ante ransomware — se exige que varias personas autorizadas aprueben la operación antes de ejecutarla. ¿Qué capacidad de gobernanza de AWS, lanzada en 2025, está diseñada para esto?",
    options: [
      "Multi-party approval, con equipos que votan antes de ejecutar la operación",
      "Una SCP que deniegue la operación salvo con aws:MultiFactorAuthPresent",
      "Permission boundaries combinados con los hallazgos de Access Analyzer",
      "AWS Config conformance packs con remediación automática vía Systems Manager",
    ],
    correct: 0,
    explain: "Multi-party approval es una capacidad de AWS Organizations que requiere IAM Identity Center: defines equipos de aprobación con un umbral M de N y la operación protegida no se ejecuta hasta reunir los votos. Su primera integración fue AWS Backup para vaults lógicamente aislados. Exigir MFA sigue siendo una sola persona, y Config remedia configuración, no autoriza operaciones puntuales. <a href=\"https://docs.aws.amazon.com/mpa/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Declarative Policies – atributos EC2/VPC/AMI",
    q: "Quieres garantizar, para TODA la organización y de forma que ninguna cuenta pueda desviarse aunque tenga AdministratorAccess local, que ninguna instancia EC2 pueda usar IMDSv1 y que ninguna VPC pueda comunicarse con internet a través de un Internet Gateway salvo excepciones explícitas. ¿Qué mecanismo de AWS Organizations aplica exactamente este tipo de control?",
    options: [
      "Una SCP que deniegue ec2:RunInstances si falta una etiqueta concreta",
      "Declarative policies, que fijan IMDSv2 y VPC Block Public Access",
      "AWS Config managed rules con remediación automática vía Systems Manager",
      "Una RCP sobre EC2 que exija aws:PrincipalOrgID en cada llamada",
    ],
    correct: 1,
    explain: "Las declarative policies cubren atributos de EC2 y VPC como 'VPC Block Public Access', 'Image (AMI) Block Public Access' e 'IMDSv2 enforcement'. A diferencia de una SCP, que deniega llamadas concretas a la API, fijan un estado de configuración deseado en el plano de control que se mantiene aunque aparezcan cuentas o APIs nuevas. Config detecta y remedia a posteriori, no impide la desviación. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "RCP – exención de la cuenta de gestión",
    q: "Una empresa despliega una RCP a nivel de la raíz de la organización para restringir el acceso a buckets S3 solo a identidades dentro de la organización. Un ingeniero, autenticado como usuario IAM en la cuenta de GESTIÓN (management account) de la Organization, accede sin problema a un bucket de una cuenta miembro que en teoría debería estar bloqueado por esa RCP para orígenes externos. ¿A qué se debe esto?",
    options: [
      "Es un error: la RCP debía adjuntarse también a la cuenta de gestión",
      "El usuario tiene MFA activo, lo que le exime de las RCP de la organización",
      "Las RCP no se aplican a las identidades de la cuenta de gestión",
      "Las RCP solo se aplican a llamadas hechas desde fuera de la Región",
    ],
    correct: 2,
    explain: "Una particularidad clave de las RCP, contraintuitiva y muy preguntada, es que NO se aplican a las solicitudes hechas por principals de la cuenta de gestión de la organización, aunque el recurso viva en una cuenta miembro dentro del alcance de la política. Es otro motivo para no usar la cuenta de gestión en el día a día: escapa a este tipo de guardrails. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM Roles Anywhere – ABAC con certificados",
    q: "Una empresa usa IAM Roles Anywhere para dar credenciales a servidores on-premises, y quiere que el rol asumido lleve automáticamente un tag de sesión con el nombre del servidor, extraído del propio certificado X.509 usado para autenticarse, para poder aplicar políticas ABAC sin gestionar tags manualmente. ¿Es esto posible, y cómo?",
    options: [
      "No: los tags de sesión solo se añaden a mano al invocar CreateSession",
      "No: IAM Roles Anywhere no admite ningún tipo de etiquetado de sesión",
      "Sí, pero solo con certificados emitidos por ACM público, nunca por una CA privada",
      "Sí: los RDN del Subject y del Issuer se mapean a PrincipalTag de sesión",
    ],
    correct: 3,
    explain: "IAM Roles Anywhere aplica reglas de attribute mapping que convierten automáticamente los Relative Distinguished Names del Subject (CN, OU...) y del Issuer del certificado presentado en PrincipalTag de la sesión resultante. Con eso puedes escribir políticas ABAC del tipo 'este servidor solo accede a recursos con la misma OU que su certificado' sin gestionar tags a mano. <a href=\"https://docs.aws.amazon.com/rolesanywhere/latest/userguide/attribute-mapping.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Verified Permissions – BatchIsAuthorized",
    q: "Tu aplicación SaaS necesita renderizar una lista de 25 documentos y decidir, para cada uno, si el usuario actual puede verlo y si puede editarlo — es decir, hasta 50 decisiones de autorización para una sola carga de página. Hacer 50 llamadas individuales a IsAuthorized añadiría demasiada latencia. ¿Qué ofrece Amazon Verified Permissions para este caso?",
    options: [
      "BatchIsAuthorized, que agrupa hasta 30 decisiones en una sola llamada",
      "Nada: hay que llamar a IsAuthorized una vez por cada decisión pendiente",
      "Exportar las políticas Cedar y evaluarlas en el cliente con el SDK",
      "Cachear las decisiones en Lambda@Edge por delante de la aplicación",
    ],
    correct: 0,
    explain: "BatchIsAuthorized agrupa hasta 30 decisiones de autorización para un mismo principal o recurso en una sola llamada, que es justo el patrón de una lista o tabla donde hay que decidir de golpe qué acciones se muestran. Evaluar Cedar en el cliente traslada la decisión a un lugar no confiable, y cachear en el borde no resuelve la primera carga ni la invalidación. <a href=\"https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_BatchIsAuthorized.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Permission boundary obligatorio al crear roles",
    q: "Quieres permitir que los desarrolladores creen sus propios IAM Roles (iam:CreateRole) pero garantizar que NUNCA puedan crear un rol sin que lleve adjunto un permission boundary concreto — cerrando la puerta a que se autoconcedan permisos de administrador vía un rol nuevo sin boundary. ¿Qué mecanismo de política aplica exactamente esta restricción?",
    options: [
      "Una SCP que deniegue iam:CreateRole a todas las identidades de la cuenta",
      "Una condición iam:PermissionsBoundary en la política del desarrollador",
      "No se puede exigir: adjuntar el boundary depende de quien crea el rol",
      "Una política basada en recursos adjunta al propio permission boundary",
    ],
    correct: 1,
    explain: "La clave de condición <code>iam:PermissionsBoundary</code>, con StringEquals contra el ARN del boundary permitido, se añade a la política que concede al desarrollador iam:CreateRole y iam:PutRolePermissionsBoundary: si la llamada no adjunta exactamente ese boundary, se deniega. Es el patrón estándar de AWS para delegar la creación de roles sin abrir la puerta a la escalada de privilegios. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "STS – role chaining y duración de sesión",
    q: "Un usuario asume el Rol A (sesión de 12 horas) y, usando esas credenciales temporales, intenta asumir el Rol B (role chaining) también con --duration-seconds apuntando a 12 horas. ¿Qué ocurre con la duración máxima de la sesión resultante del Rol B?",
    options: [
      "Puede durar hasta 12 horas, igual que la sesión del Rol A",
      "Falla: STS prohíbe encadenar roles partiendo de credenciales temporales",
      "Se limita a 1 hora, sin importar el MaxSessionDuration del Rol B",
      "Depende de si el usuario original se autenticó con MFA al inicio",
    ],
    correct: 2,
    explain: "AWS STS limita explícitamente el role chaining: si usas las credenciales temporales de un AssumeRole para llamar de nuevo a AssumeRole, la sesión resultante dura como máximo 1 hora, sin importar el MaxSessionDuration configurado en el rol de destino. Pedir más provoca un error. Es un detalle muy preguntado porque contradice la expectativa de que manda la configuración del rol. <a href=\"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "RCP – aws:PrincipalOrgID vs aws:ResourceOrgID",
    q: "Al diseñar guardrails de 'data perimeter' con RCPs, ¿cuál es la diferencia práctica entre condicionar una RCP con aws:PrincipalOrgID y condicionarla con aws:ResourceOrgID?",
    options: [
      "Son sinónimos: las dos devuelven el ID de la organización del recurso",
      "aws:PrincipalOrgID quedó obsoleta y la sustituye aws:SourceOrgID",
      "aws:ResourceOrgID solo puede usarse en SCP, nunca en una RCP",
      "aws:PrincipalOrgID mira la organización de la identidad que llama",
    ],
    correct: 3,
    explain: "aws:PrincipalOrgID es la clave del perímetro de IDENTIDAD: compara la organización del principal que llama contra un valor fijo. aws:ResourceOrgID describe la organización a la que pertenece el RECURSO, y permite expresar en una RCP 'solo si quien llama pertenece a la misma organización que el recurso', sin mantener listas de cuentas. Ambas siguen vigentes y son complementarias. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Access Analyzer – generación de políticas",
    q: "Un equipo lleva 6 meses operando un rol IAM con la política gestionada AdministratorAccess 'temporalmente', y ahora quiere generar una política de mínimo privilegio basada en lo que ese rol REALMENTE ha usado según su actividad registrada en CloudTrail, en vez de escribirla a mano desde cero. ¿Qué funcionalidad de IAM Access Analyzer resuelve esto directamente?",
    options: [
      "La generación de políticas a partir de la actividad de CloudTrail",
      "Los external access findings del analyzer creado en esa misma cuenta",
      "Los unused access findings, que generan la política sustituta",
      "El IAM Credential Report, que lista los permisos ya ejercidos",
    ],
    correct: 0,
    explain: "La policy generation de Access Analyzer analiza los eventos de CloudTrail de un rol o usuario durante un periodo de hasta 90 días y propone una política con los servicios y acciones realmente usados, como punto de partida de mínimo privilegio. Los unused access findings señalan lo que sobra pero no escriben la política, y el Credential Report solo mira el estado de las credenciales. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-policy-generation.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Verified Permissions – policy templates",
    q: "Tu aplicación SaaS multi-tenant tiene el mismo patrón de autorización repetido para cientos de tenants ('el propietario puede editar su propio recurso'), y quieres evitar duplicar la misma política Cedar cientos de veces en el policy store, una por tenant. ¿Qué característica de Amazon Verified Permissions está pensada exactamente para esto?",
    options: [
      "Crear un policy store independiente por tenant y sincronizarlos entre sí",
      "Policy templates instanciados como template-linked policies por tenant",
      "Escribir una política estática por cada par concreto de usuario y recurso",
      "No es posible: el lenguaje Cedar no admite parametrizar sus políticas",
    ],
    correct: 1,
    explain: "Un policy template declara una única política Cedar con placeholders <code>?principal</code> y <code>?resource</code>, y cada template-linked policy la instancia con IDs concretos: la lógica vive en un solo sitio y actualizarla se propaga a todas las instancias. Un policy store por tenant multiplica la superficie de gestión, y escribir una política por par no escala. <a href=\"https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/policy-templates.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "aws:PrincipalOrgID vs aws:PrincipalOrgPaths",
    q: "Una organización tiene una OU llamada 'Sandbox' bajo la raíz, y quiere una RCP que permita el acceso a un bucket S3 solo a identidades que pertenezcan específicamente a esa OU (y sus sub-OUs), no a toda la organización en general. ¿Qué clave de condición es la adecuada?",
    options: [
      "aws:PrincipalOrgID, comparado con el ID de la organización completa",
      "aws:PrincipalAccount, enumerando a mano las cuentas de esa OU",
      "aws:PrincipalOrgPaths, que compara la ruta de OU del principal",
      "aws:ResourceOrgID, apuntando a la OU donde vive el bucket",
    ],
    correct: 2,
    explain: "aws:PrincipalOrgID solo identifica la organización entera (o-xxxxxxxxxx) y no distingue OUs. Para acotar a una rama del árbol se usa aws:PrincipalOrgPaths, que contiene la ruta completa de IDs de OU del principal y admite comparación por prefijo, cubriendo así la OU y sus descendientes. Enumerar cuentas a mano funciona hasta que alguien crea la siguiente. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Root user – Task policies de AssumeRoot",
    q: "Cuando un administrador de la cuenta de gestión llama a sts:AssumeRoot para realizar una tarea root en una cuenta miembro, ¿qué determina exactamente qué puede hacer esa sesión root temporal?",
    options: [
      "Nada: la sesión de AssumeRoot tiene privilegios root sin restricción",
      "Una SCP con un Allow explícito sobre la acción root:* en esa cuenta",
      "El permission boundary que tuviera el root antes de borrar sus claves",
      "Una TaskPolicy gestionada por AWS que acota la sesión a esa tarea",
    ],
    correct: 3,
    explain: "A diferencia del root tradicional, que no tiene límites, sts:AssumeRoot exige indicar una de las TaskPolicy gestionadas por AWS, diseñadas para tareas concretas que legítimamente requieren root (desbloquear una bucket policy, resolver una política de clave KMS, gestionar las credenciales del propio root). No existe una opción de root irrestricto: por diseño es siempre una sesión de alcance mínimo. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user-privileged-task.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Unused access analyzer – tracking period",
    q: "Al configurar un unused access analyzer en IAM Access Analyzer, ¿qué controla el parámetro de 'tracking period' (periodo de seguimiento)?",
    options: [
      "La ventana durante la que se observa el uso real de cada permiso",
      "El tiempo que tarda el analyzer en generar su primer hallazgo",
      "El plazo tras el cual se elimina automáticamente un rol sin uso",
      "La frecuencia con la que rota la clave KMS que cifra los hallazgos",
    ],
    correct: 0,
    explain: "El tracking period define durante cuántos días (de 1 a 365, 90 por defecto) Access Analyzer observa el uso real antes de considerar algo 'no usado'. Detalle clave del examen: solo se evalúan identidades y permisos que ya existían durante TODO ese periodo, así que un rol creado hace 10 días con tracking de 90 aún no genera hallazgo. Access Analyzer nunca borra roles por su cuenta. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-create-unused.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "RCP – servicios soportados",
    q: "Un equipo de seguridad quiere usar una RCP para restringir centralmente el acceso a las tablas de una base de datos NoSQL gestionada de la organización, exigiendo que solo identidades dentro de la propia organización puedan leerlas, incluso si alguna política de identidad o de recurso las expone accidentalmente hacia fuera. Tras las ampliaciones de soporte de RCP hasta 2026, ¿qué servicio permite aplicar esto directamente vía RCP?",
    options: [
      "Amazon RDS, soportado por las RCP desde su lanzamiento en 2024",
      "Amazon DynamoDB, incorporado a los servicios que admiten RCP",
      "Amazon Redshift, soportado por las RCP desde su lanzamiento",
      "Ninguno: las RCP solo cubren almacenamiento de objetos en S3",
    ],
    correct: 1,
    explain: "Las RCP se lanzaron en noviembre de 2024 cubriendo S3, STS, KMS, SQS y Secrets Manager, y AWS ha ido ampliando la lista con ECR, OpenSearch Serverless, Cognito, CloudWatch Logs y Amazon DynamoDB. Lo conceptualmente clave, más allá de la lista concreta, es que una RCP solo surte efecto sobre los servicios explícitamente soportados en cada momento, no sobre todo el catálogo. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Data perimeter – trampa SCP vs RCP",
    q: "Una organización configura una SCP que deniega cualquier acción s3:GetObject salvo que el principal pertenezca a la organización (usando aws:PrincipalOrgID). Sin embargo, un tercero externo consigue leer un objeto de un bucket S3 de la organización porque el bucket tiene una bucket policy que le concede acceso explícito con un Allow. ¿Por qué la SCP no evitó esto?",
    options: [
      "La SCP tiene un error de sintaxis en su bloque Condition",
      "S3 no admite que una SCP restrinja sus acciones de lectura de objetos",
      "Las SCP solo restringen a las identidades de la organización",
      "Las SCP solo se evalúan en llamadas hechas desde la consola",
    ],
    correct: 2,
    explain: "Es el ejemplo canónico de por qué existen las RCP: una SCP acota lo que pueden hacer las identidades DENTRO de tu organización, pero un principal externo que accede vía bucket policy nunca pasa por esa SCP, porque no se evalúa sobre principals ajenos a la organización. Cerrar ese hueco exige una RCP, que sí impone condiciones al recurso venga quien venga. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SCP – evaluación multi-nivel en el árbol de OUs",
    q: "Una cuenta cuelga de OU-Producción, que a su vez cuelga de la raíz de la organización. La raíz tiene una SCP que permite s3:*, OU-Producción tiene una SCP que deniega explícitamente s3:DeleteBucket, y la propia cuenta no tiene SCPs adicionales. ¿Se puede ejecutar s3:DeleteBucket en esa cuenta?",
    options: [
      "Sí: la SCP de la raíz permite s3:* y prevalece por estar más arriba",
      "Sí: las SCP de una OU no surten efecto si la cuenta no tiene SCP propia",
      "Sí: de las SCP en conflicto solo cuenta la adjuntada más recientemente",
      "No: un Deny en cualquier nivel del camino bloquea la acción",
    ],
    correct: 3,
    explain: "Las SCP se evalúan de forma acumulativa a lo largo de TODO el camino desde la raíz hasta la cuenta, pasando por cada OU intermedia: el permiso efectivo es la intersección de lo permitido en cada nivel, y un Deny explícito en cualquier punto bloquea la acción sin importar lo que digan los niveles superiores. La antigüedad de una política nunca influye en la evaluación. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_evaluation.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Acceso cross-account",
    q: "Una aplicación en la cuenta A debe asumir un rol de la cuenta B. ¿Qué DOS elementos son imprescindibles para que funcione?",
    options: [
      "Una trust policy en el rol de la cuenta B que autorice al principal de A",
      "Que ambas cuentas pertenezcan a la misma organización de AWS Organizations",
      "Un permiso sts:AssumeRole en la política de identidad del principal de A",
      "Un VPC peering entre las cuentas para que STS enrute la petición",
    ],
    correct: [0, 2],
    explain: "El acceso cross-account exige <b>las dos puntas</b>: el recurso (el rol) debe confiar en quien llama, y quien llama debe tener permiso para llamar. Es el caso clásico en que un Allow en un solo lado no basta. No hace falta Organizations — el cross-account funciona entre cuentas sin relación — ni conectividad de red, porque STS es un endpoint público del servicio, no algo que viva en tu VPC. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Orígenes de un Deny explícito",
    q: "Un usuario recibe AccessDenied pese a tener una identity policy con Allow para la acción. ¿En qué DOS sitios puede estar el Deny que lo bloquea?",
    options: [
      "En la consola de IAM, que bloquea las acciones peligrosas",
      "En una Service Control Policy aplicada a la OU o a la cuenta",
      "En el historial de CloudTrail, que revoca permisos mal usados",
      "En la política basada en recursos del recurso al que accede",
    ],
    correct: [1, 3],
    explain: "Un Deny explícito en <b>cualquier</b> política aplicable gana siempre: identity policy, resource policy, SCP, RCP, permission boundary o session policy. Aquí los dos candidatos reales son la SCP y la política del recurso. La consola de IAM no bloquea acciones por su cuenta, y CloudTrail es un registro de auditoría: <b>observa</b>, nunca revoca. Confundir un servicio de registro con uno de control es un distractor típico. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Data perimeter",
    q: "Quieres garantizar que tus buckets S3 solo sean accesibles por identidades de tu propia organización y únicamente desde tu red. ¿Qué DOS condition keys aplicarías?",
    options: [
      "aws:PrincipalOrgID, para exigir que quien llama sea de tu organización",
      "aws:RequestedRegion, para limitar el acceso a una sola Región de AWS",
      "aws:CurrentTime, para permitir el acceso solo dentro del horario laboral",
      "aws:SourceVpce, para exigir que la petición llegue por tu VPC endpoint",
    ],
    correct: [0, 3],
    explain: "Un data perimeter se construye sobre dos ejes: <b>quién</b> (identity perimeter, con aws:PrincipalOrgID) y <b>desde dónde</b> (network perimeter, con aws:SourceVpce o aws:SourceIp). Las otras dos condition keys existen y son válidas, pero acotan Región y horario: no responden a la pregunta de identidad ni de red que plantea el enunciado. <a href=\"https://docs.aws.amazon.com/whitepapers/latest/building-a-data-perimeter-on-aws/building-a-data-perimeter-on-aws.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Permission boundaries",
    q: "Vas a permitir que los desarrolladores creen sus propios roles sin que puedan escalar privilegios. ¿Qué DOS afirmaciones sobre permission boundaries son correctas?",
    options: [
      "El boundary sustituye a la identity policy: basta con adjuntar el boundary",
      "Un permission boundary no concede permisos: acota lo que otra puede dar",
      "Se puede exigir por condición que todo rol creado lleve un boundary concreto",
      "Los boundaries se adjuntan a los recursos, igual que las bucket policies de S3",
    ],
    correct: [1, 2],
    explain: "El permiso efectivo es la <b>intersección</b> entre la identity policy y el boundary, así que el boundary por sí solo no concede nada y no sustituye a la política. La condición <code>iam:PermissionsBoundary</code> es justo el mecanismo con el que se delega la creación de roles sin permitir escalada. Y los boundaries se adjuntan a <b>identidades</b> (usuarios y roles), no a recursos. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Federación con IAM Identity Center",
    q: "Una empresa con 3.000 empleados en un IdP corporativo quiere dar acceso a 60 cuentas de AWS sin crear usuarios IAM. ¿Qué DOS afirmaciones describen el enfoque correcto?",
    options: [
      "Hay que crear un usuario IAM por empleado en cada una de las 60 cuentas",
      "Todos los empleados comparten una access key común para simplificar la gestión",
      "IAM Identity Center federa con el IdP y asigna permission sets a grupos",
      "Los usuarios reciben credenciales temporales de STS, no access keys fijas",
    ],
    correct: [2, 3],
    explain: "<b>Identity Center</b> con <b>permission sets</b> asignados a grupos es el patrón recomendado a escala, y la federación entrega siempre <b>credenciales temporales de STS</b>. Crear 3.000 usuarios en 60 cuentas es exactamente el problema que la federación elimina (180.000 identidades que mantener). Y compartir una clave entre personas destruye la atribución: nunca es la respuesta. <a href=\"https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Active Directory y acceso a AWS",
    q: "Una empresa con Active Directory on-premises quiere que sus empleados entren en AWS con las credenciales corporativas y, además, que sus aplicaciones Windows en EC2 se unan a un dominio gestionado dentro de AWS. ¿Qué combinación encaja?",
    options: [
      "Crear un usuario IAM por empleado y sincronizarlo con un script contra el AD",
      "AWS Managed Microsoft AD como directorio, federado en IAM Identity Center",
      "Amazon Cognito con un grupo de usuarios que replique las cuentas del dominio",
      "AD Connector como directorio y un rol IAM por cada grupo del dominio local",
    ],
    correct: 1,
    explain: "Los dos requisitos tiran en direcciones distintas y solo uno los cubre a la vez. Para la consola bastaría <b>AD Connector</b>, que reenvía la autenticación al AD local sin guardar nada en AWS; pero <em>unir instancias a un dominio</em> exige un directorio real en AWS, y eso es <b>AWS Managed Microsoft AD</b>, que además se conecta a IAM Identity Center como origen de identidad y puede establecer una relación de confianza con el dominio corporativo. Los usuarios IAM sincronizados a mano son credenciales duplicadas. Y Cognito está pensado para las identidades de tu aplicación, no para los empleados. <a href=\"https://docs.aws.amazon.com/directoryservice/latest/admin-guide/directory_microsoft_ad.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["iam"] = QUIZ_DATA;
