const QUIZ_DATA = [
  {
    tag: "Evaluación de políticas",
    q: "Un usuario tiene una política de identidad que permite s3:GetObject sobre un bucket, pero el bucket tiene una bucket policy con un Deny explícito para ese mismo usuario. ¿Qué ocurre?",
    options: [
      "Se le permite el acceso porque la política de identidad tiene prioridad",
      "Se le deniega el acceso: un Deny explícito en cualquier política aplicable siempre gana",
      "AWS evalúa solo la política de identidad si el recurso es propio de la cuenta",
      "El resultado depende de cuál política se creó más recientemente",
    ],
    correct: 1,
    explain: "El orden de evaluación de IAM es: Deny explícito &gt; Allow explícito &gt; Deny por defecto. Un Deny explícito en CUALQUIER política que aplique (identidad, recurso, SCP, RCP, boundary, session policy) anula cualquier Allow, sin importar dónde esté.",
  },
  {
    tag: "SCP vs RCP",
    q: "¿Cuál es la diferencia clave entre una Service Control Policy (SCP) y una Resource Control Policy (RCP) en AWS Organizations?",
    options: [
      "No hay diferencia, son sinónimos del mismo mecanismo",
      "Las SCP solo aplican a la cuenta de gestión (management account)",
      "Las SCP limitan lo que las identidades de la cuenta pueden hacer; las RCP limitan quién puede acceder a los recursos, incluidas identidades externas/anónimas",
      "Las RCP sustituyen completamente a las SCP desde 2023",
    ],
    correct: 2,
    explain: "Las SCP son guardrails que acotan el máximo permiso disponible para principals DENTRO de la organización. Las RCP (más recientes) acotan el acceso a los RECURSOS en sí, incluyendo principals externos, cerrando huecos que las SCP no cubren porque las SCP no aplican a identidades fuera de la organización.",
  },
  {
    tag: "Permission boundaries",
    q: "Un desarrollador tiene un permission boundary que solo permite acciones sobre S3 y DynamoDB. Su identity-based policy le concede AdministratorAccess. ¿Qué puede hacer realmente?",
    options: [
      "Todo, porque AdministratorAccess siempre gana",
      "Solo acciones S3 y DynamoDB: el permission boundary actúa como techo máximo, la intersección con la identity policy",
      "Nada, porque el boundary y la policy entran en conflicto y se deniega todo",
      "Depende del orden en que se adjuntaron las políticas",
    ],
    correct: 1,
    explain: "El permission boundary NO otorga permisos por sí mismo: define el máximo conjunto de permisos que una identity-based policy puede conceder. El permiso efectivo es la INTERSECCIÓN entre la identity policy y el boundary.",
  },
  {
    tag: "STS",
    q: "Una aplicación móvil autentica usuarios contra Google (proveedor OIDC) y necesita credenciales temporales de AWS para acceder a un bucket S3 de forma directa desde el móvil. ¿Qué API de STS es la adecuada?",
    options: [
      "sts:GetSessionToken",
      "sts:AssumeRoleWithWebIdentity (o mejor, vía Amazon Cognito Identity Pools)",
      "sts:AssumeRoleWithSAML",
      "sts:GetFederationToken",
    ],
    correct: 1,
    explain: "AssumeRoleWithWebIdentity intercambia un token OIDC (Google, Facebook, Amazon, o cualquier IdP compatible con OIDC) por credenciales temporales. En producción, AWS recomienda usar Cognito Identity Pools por encima, que gestiona el intercambio de forma más segura sin exponer secretos de la app.",
  },
  {
    tag: "Federación SAML",
    q: "Una empresa usa Active Directory Federation Services (ADFS) on-premises y quiere dar acceso a la consola de AWS a sus empleados sin crear usuarios IAM. ¿Qué mecanismo es el más apropiado?",
    options: [
      "IAM Roles Anywhere",
      "AssumeRoleWithSAML combinado con un IdP SAML 2.0 configurado en IAM",
      "Access keys individuales gestionadas por AD",
      "AWS IAM Identity Center en modo standalone sin IdP externo",
    ],
    correct: 1,
    explain: "AssumeRoleWithSAML permite federar identidades desde un IdP SAML 2.0 (ADFS, Okta, Azure AD/Entra ID) directamente contra un IAM Role, sin necesidad de usuarios IAM individuales. IAM Identity Center también es válido y es la opción moderna recomendada por AWS para multi-cuenta, pero igualmente necesita conectar ese mismo IdP SAML como fuente de identidad.",
  },
  {
    tag: "IAM Identity Center",
    q: "¿Cuál es la diferencia principal entre un IAM Role tradicional cross-account y un Permission Set de IAM Identity Center?",
    options: [
      "No hay diferencia técnica, IAM Identity Center es solo una interfaz visual sobre roles",
      "Los Permission Sets solo funcionan con usuarios root",
      "Un Permission Set se define una vez y IAM Identity Center provisiona automáticamente los IAM Roles correspondientes en cada cuenta miembro asignada",
      "Los Permission Sets no soportan políticas gestionadas por AWS, solo inline",
    ],
    correct: 2,
    explain: "IAM Identity Center (sucesor de AWS SSO) centraliza la gestión: defines un Permission Set una vez y el servicio provisiona/sincroniza automáticamente los IAM Roles necesarios en cada cuenta de la organización asignada, evitando gestionar roles manualmente cuenta por cuenta.",
  },
  {
    tag: "IAM Access Analyzer",
    q: "¿Qué tipo de hallazgo genera IAM Access Analyzer cuando detecta que un rol IAM no se ha usado en los últimos 90 días?",
    options: [
      "External access finding",
      "Unused access finding (parte del análisis de 'unused access', disponible desde 2023)",
      "Policy validation finding",
      "Access Analyzer no analiza el uso, solo políticas estáticas",
    ],
    correct: 1,
    explain: "Access Analyzer tiene tres capacidades: (1) External access findings — detecta recursos accesibles desde fuera de tu zona de confianza; (2) Unused access findings — identifica roles, permisos y access keys sin uso reciente; (3) Policy validation — valida sintaxis y buenas prácticas de políticas mientras las escribes.",
  },
  {
    tag: "ABAC",
    q: "En una estrategia de control de acceso basado en atributos (ABAC) con IAM, ¿qué condición se usaría típicamente en una política para permitir que un usuario solo pueda etiquetar/acceder a recursos que coincidan con su propio departamento?",
    options: [
      "\"Condition\": {\"StringEquals\": {\"aws:PrincipalTag/department\": \"${aws:ResourceTag/department}\"}}",
      "\"Condition\": {\"IpAddress\": {\"aws:SourceIp\": \"10.0.0.0/16\"}}",
      "\"Condition\": {\"Bool\": {\"aws:MultiFactorAuthPresent\": \"true\"}}",
      "\"Condition\": {\"DateLessThan\": {\"aws:CurrentTime\": \"2026-01-01T00:00:00Z\"}}",

    ],
    correct: 0,
    explain: "ABAC compara etiquetas (tags) del principal con etiquetas del recurso usando variables de política como aws:PrincipalTag/clave y aws:ResourceTag/clave, permitiendo reglas de acceso que escalan sin reescribir políticas para cada nuevo recurso.",
  },
  {
    tag: "Confused deputy",
    q: "Un servicio de AWS (ej. CloudTrail) asume un rol en tu cuenta en nombre de otro cliente de AWS y por error accede a datos de tu cuenta que no le corresponden. ¿Qué condición de política previene este 'confused deputy problem'?",
    options: [
      "aws:MultiFactorAuthPresent",
      "aws:SourceIp",
      "aws:SourceArn y/o aws:SourceAccount en la trust policy del rol",
      "aws:RequestedRegion",
    ],
    correct: 2,
    explain: "Para evitar que un servicio de AWS sea 'engañado' para actuar en nombre de un tercero no autorizado, se añade a la trust policy una condición con aws:SourceArn (o aws:SourceAccount) que restringe qué recurso/cuenta específica puede invocar el AssumeRole vía ese servicio.",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "Una empresa tiene servidores on-premises (fuera de AWS) que necesitan credenciales temporales de AWS sin usar access keys de larga duración. ¿Qué servicio está diseñado exactamente para este caso?",
    options: [
      "AWS Systems Manager Hybrid Activations únicamente",
      "IAM Roles Anywhere: usa certificados X.509 emitidos por una CA privada para intercambiarlos por credenciales temporales vía STS",
      "IAM Identity Center con conector on-premises",
      "Cognito Identity Pools",
    ],
    correct: 1,
    explain: "IAM Roles Anywhere permite a cargas de trabajo fuera de AWS (servidores on-prem, otros clouds) obtener credenciales temporales de IAM presentando un certificado X.509 firmado por una CA de confianza registrada en IAM, eliminando la necesidad de access keys estáticas fuera de AWS.",
  },
  {
    tag: "Root user",
    q: "AWS introdujo 'Centralized Root Access Management' en Organizations. ¿Qué permite hacer esta capacidad?",
    options: [
      "Eliminar por completo la necesidad de tener usuario root en cada cuenta",
      "Gestionar de forma centralizada las credenciales root de las cuentas miembro y aplicar acciones privilegiadas de root sin necesidad de recuperar contraseñas cuenta por cuenta",
      "Convertir el root en un rol IAM asumible por cualquier usuario",
      "Sustituir MFA en la cuenta de gestión",
    ],
    correct: 1,
    explain: "Esta capacidad de Organizations (lanzada en 2023-2024) permite gestionar y restringir de forma centralizada las credenciales root de las cuentas miembro, e invocar un conjunto acotado de tareas privilegiadas de root sin tener que hacer el proceso de recuperación de contraseña individualmente en cada cuenta.",
  },
  {
    tag: "MFA",
    q: "¿Qué clave de condición se usa en una política IAM para exigir que una API call se haya realizado con una sesión autenticada por MFA?",
    options: [
      "aws:MultiFactorAuthPresent: true",
      "aws:MFA-Required: true",
      "iam:MFAEnabled: true",
      "sts:MfaAuthenticated: true",
    ],
    correct: 0,
    explain: "La condición estándar es aws:MultiFactorAuthPresent. Es una buena práctica muy preguntada en el examen combinarla con aws:MultiFactorAuthAge para limitar además la antigüedad máxima de la sesión MFA.",
  },
  {
    tag: "Resource-based policies",
    q: "¿Cuál de estas afirmaciones sobre políticas basadas en recursos (resource-based policies) es correcta?",
    options: [
      "Solo IAM Roles pueden tener resource-based policies",
      "Permiten conceder acceso a un principal de OTRA cuenta AWS sin necesidad de que ese principal asuma un rol en tu cuenta",
      "No pueden combinarse nunca con condiciones",
      "Sustituyen siempre a las identity-based policies",
    ],
    correct: 1,
    explain: "Recursos como buckets S3, KMS keys, colas SQS, topics SNS o Lambda functions soportan resource-based policies, que pueden especificar directamente un Principal externo (de otra cuenta) sin que ese principal necesite asumir un rol — el acceso cross-account se concede directamente en el recurso.",
  },
  {
    tag: "Credential report vs Access Advisor",
    q: "¿Cuál es la diferencia entre el IAM Credential Report y el IAM Access Advisor?",
    options: [
      "Son el mismo informe con nombres distintos",
      "El Credential Report lista el estado de credenciales (passwords, access keys, MFA) de todos los usuarios; Access Advisor muestra qué servicios/acciones ha usado realmente un principal y cuándo por última vez",
      "Access Advisor solo funciona a nivel de cuenta root",
      "El Credential Report requiere GuardDuty habilitado",
    ],
    correct: 1,
    explain: "El Credential Report (generado a nivel de cuenta, CSV) audita el estado de credenciales de todos los usuarios IAM. Access Advisor (pestaña 'Access Advisor' de un usuario/rol) muestra el histórico de servicios accedidos — clave para aplicar el principio de mínimo privilegio eliminando permisos no usados.",
  },
  {
    tag: "Cross-account trust policy",
    q: "¿Qué elemento es obligatorio en la trust policy (assume role policy document) de un IAM Role para permitir que una cuenta externa lo asuma?",
    options: [
      "Un Principal que referencie el ARN o ID de la cuenta externa, con Action sts:AssumeRole",
      "Un bucket policy vinculado al rol",
      "Una SCP específica en la cuenta externa",
      "Nada adicional: por defecto cualquier cuenta puede asumir cualquier rol",
    ],
    correct: 0,
    explain: "La trust policy del rol debe incluir un Principal con el ARN de la cuenta/rol externo autorizado y Action: sts:AssumeRole. Además, la cuenta que asume necesita su propia identity policy que le permita hacer sts:AssumeRole sobre ese ARN — se requieren AMBOS lados (trust + permiso de origen).",
  },
  {
    tag: "Data perimeter",
    q: "En el concepto de 'data perimeter' de AWS, ¿qué combinación de controles se usa típicamente para asegurar que los datos NUNCA salgan de la organización, incluso con credenciales válidas robadas?",
    options: [
      "Solo cifrado con KMS",
      "Solo Security Groups restrictivos",
      "SCPs/RCPs a nivel de organización + condiciones aws:PrincipalOrgID / aws:ResourceOrgID + VPC endpoint policies",
      "Solo rotación de access keys cada 90 días",
    ],
    correct: 2,
    explain: "El data perimeter combina 3 tipos de perímetros: identidad (¿quién puede acceder? — SCPs/RCPs con aws:PrincipalOrgID), recurso (¿qué recursos son de confianza? — aws:ResourceOrgID) y red (¿desde dónde? — VPC endpoint policies + aws:SourceVpce), de forma que ni siquiera credenciales válidas comprometidas puedan exfiltrar datos fuera del perímetro.",
  },
  {
    tag: "Session policies",
    q: "Cuando llamas a sts:AssumeRole pasando un parámetro --policy adicional (session policy), ¿cómo afecta esto a los permisos efectivos de la sesión resultante?",
    options: [
      "La session policy sustituye completamente a la identity policy del rol",
      "La session policy amplía los permisos del rol más allá de lo que ya tenía",
      "La session policy actúa como filtro adicional: los permisos efectivos son la intersección entre los permisos del rol y la session policy",
      "Las session policies solo aplican a usuarios, no a roles",
    ],
    correct: 2,
    explain: "Igual que un permission boundary, una session policy NUNCA amplía permisos — solo puede acotar (intersección) los permisos que ya tiene el rol asumido. Es útil para dar credenciales temporales más restringidas a partir de un rol amplio.",
  },
  {
    tag: "Declarative policies",
    q: "AWS Organizations introdujo 'Declarative Policies'. ¿En qué se diferencian de las SCP?",
    options: [
      "Son idénticas a las SCP, solo cambia el nombre",
      "Las Declarative Policies fijan de forma centralizada la configuración deseada de ciertos atributos de servicio (ej. bloquear IMDSv1, forzar bloqueo de acceso público en EC2/VPC) en toda la organización, en vez de solo permitir/denegar acciones de API",
      "Las Declarative Policies solo funcionan en la cuenta de gestión",
      "Sustituyen a Config Rules completamente",
    ],
    correct: 1,
    explain: "A diferencia de las SCP (que deniegan/permiten llamadas a API), las Declarative Policies (2024+) establecen y mantienen un estado de configuración deseado a nivel de organización para atributos específicos de ciertos servicios (p. ej. exigir IMDSv2, bloquear acceso público a snapshots), garantizando que ninguna cuenta pueda desviarse de esa configuración.",
  },
  {
    tag: "Policy evaluation con VPC endpoints",
    q: "¿Qué clave de condición permite restringir el acceso a un bucket S3 exclusivamente a peticiones que pasen por un VPC endpoint específico?",
    options: [
      "aws:SourceIp",
      "aws:SourceVpce",
      "aws:VpcSourceIp",
      "s3:VpcEndpointId",
    ],
    correct: 1,
    explain: "aws:SourceVpce en una bucket policy (o cualquier resource policy compatible) restringe el acceso a peticiones que viajen a través de un VPC endpoint concreto, un control clave del 'network perimeter' para evitar exfiltración de datos hacia fuera de la VPC.",
  },
  {
    tag: "Inline vs managed policies",
    q: "¿Cuál es la principal desventaja de usar políticas inline en lugar de políticas gestionadas (managed policies)?",
    options: [
      "Las políticas inline no soportan condiciones",
      "Las políticas inline no se pueden reutilizar entre múltiples usuarios/roles/grupos y son más difíciles de auditar y versionar de forma centralizada",
      "Las políticas inline tienen un límite de tamaño menor que las gestionadas",
      "Las políticas inline no pueden denegar, solo permitir",
    ],
    correct: 1,
    explain: "Una política inline vive embebida en una única identidad (usuario, grupo o rol) y no se puede adjuntar a otras identidades ni versionar de forma independiente, dificultando su reutilización, auditoría centralizada y gestión a escala frente a una customer managed policy.",
  },
];
