var QUIZ_DATA = [
  {
    tag: "Runbooks & OpsCenter",
    q: "What role does AWS Systems Manager OpsCenter play in an incident response plan?",
    options: [
      "It centralizes OpsItems with their context — resources, alarms — and runs Automation runbooks",
      "It stores backups of EC2 instances and databases under centrally managed retention policies",
      "It replaces CloudTrail as the audit record of every API call made during the incident response",
      "It manages incidents only for Windows EC2 instances registered in Systems Manager Inventory",
    ],
    correct: 0,
    explain: "OpsCenter aggregates 'OpsItems' that represent operational incidents or problems, automatically linking in the relevant context (resources, CloudWatch alarms, executable Systems Manager Automation runbooks) — it's the Systems Manager piece designed to centralize investigation and execution of the response, not just passive incident logging. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/OpsCenter.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Preparation: minimizing blast radius",
    q: "As part of PREPARING an account for incidents (before they happen), which practice reduces the 'blast radius' if a workload is compromised?",
    options: [
      "Using a single AWS account for everything, so that auditing and incident response stay centralized",
      "Segmenting workloads into separate accounts, with least privilege and no shared credentials",
      "Granting AdministratorAccess to every role so the response is never slowed down by missing permissions",
      "Disabling CloudTrail in the development accounts so the noise doesn't bury the important events",
    ],
    correct: 1,
    explain: "Minimizing blast radius is a PREPARATION activity (skill 2.1.2): separating workloads into distinct accounts, applying least privilege, and avoiding shared credentials limits how far an attacker can get if they compromise a single component — much cheaper to do before the incident than during it. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_securely_operate_multi_accounts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Provisioning emergency access",
    q: "Why is it important to PRE-PROVISION (before the incident) the access the response team will need during an investigation?",
    options: [
      "It isn't relevant: the permissions can be created on the fly during the incident at no cost in time",
      "Because IAM blocks the creation of new roles while GuardDuty has active unresolved findings in the account",
      "It avoids depending on slow approvals and on rushing permissions, which is when over-granting happens",
      "It only pays off if the organization uses IAM Identity Center instead of local IAM users",
    ],
    correct: 2,
    explain: "Skill 2.1.2 explicitly mentions 'provisioning access' as part of preparation: an IR role with broad read-only permissions plus specific containment actions (isolate an SG, create a snapshot), already tested and audited beforehand, avoids improvising permissions under pressure — exactly when it's easiest to make an over-privilege mistake. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_incident_response_pre_provision_access.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Fault Injection Service",
    q: "What is AWS Fault Injection Service (FIS) used for in the context of validating an incident response plan?",
    options: [
      "To automatically deploy security patches across the fleet once a vulnerability has been detected",
      "To analyze memory dumps and disks from compromised instances inside an isolated forensic environment",
      "To fire real, unbounded attack traffic at production in order to measure how much load it withstands",
      "To run controlled failure experiments and check whether alarms and runbooks really do respond",
    ],
    correct: 3,
    explain: "FIS lets you design and run controlled failure experiments with guardrails (automatic stop conditions if something goes outside expected bounds) to validate that detection, alerting, and response runbooks genuinely work — instead of waiting for a real incident to discover the alarm never fired. <a href=\"https://docs.aws.amazon.com/fis/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Resilience Hub",
    q: "What does AWS Resilience Hub assess?",
    options: [
      "An application's resilience against its RTO/RPO objectives, with recommendations and FIS experiments",
      "The monthly cost of an architecture and the savings available through reserved instances or Savings Plans",
      "The PCI-DSS compliance of the accounts, producing the evidence report an auditor would ask for",
      "Network latency between regions, so you can decide where to deploy the application replica",
    ],
    correct: 0,
    explain: "Resilience Hub evaluates a defined application against RTO (recovery time objective) and RPO (recovery point, i.e. acceptable data loss) targets, flags where the current architecture would fall short, and can generate and run FIS experiments to validate real resilience — complementary to FIS: FIS runs the experiment, Resilience Hub defines the target it's measured against. <a href=\"https://docs.aws.amazon.com/resilience-hub/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Automated remediation",
    q: "You want a high-severity GuardDuty finding on an EC2 instance (e.g. communication with a cryptocurrency mining IP) to trigger automatic isolation of that instance without waiting for a human to act. What architecture do you implement?",
    options: [
      "A daily report that groups the overnight findings so an analyst can review them in the morning",
      "An EventBridge rule on the finding that invokes Lambda or Step Functions and applies a quarantine SG",
      "A CloudWatch alarm on the instance's CPU that pages the on-call team over SNS so a human can act on it",
      "An SCP that stops the instance from assuming new roles until an administrator unblocks it",
    ],
    correct: 1,
    explain: "The standard automated remediation pattern (skill 2.1.4) is: GuardDuty finding → EventBridge rule filtering by severity or type → Lambda or Step Functions executes the containment action (for example, swapping the Security Group for a quarantine one), all within seconds and without waiting on human intervention for initial containment. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_eventbridge.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Automated Forensics Orchestrator",
    q: "What does the AWS 'Automated Forensics Orchestrator for Amazon EC2' solution automate?",
    options: [
      "Continuous vulnerability scanning of the operating system and its installed packages with Amazon Inspector",
      "Periodic rotation of the IAM access keys and of the secrets stored in AWS Secrets Manager",
      "The forensic workflow for a compromised EC2: isolate it, capture disk and memory, track custody",
      "Patch deployment across the whole fleet with Patch Manager as soon as a bulletin is published",
    ],
    correct: 2,
    explain: "It's AWS guidance (built on Step Functions and Lambda) that automatically orchestrates the full forensic process for a compromised instance: isolating the network, capturing evidence (disk snapshots and a memory dump), preserving chain of custody through tagging and logging, and sending notifications — cutting containment time from hours to minutes. <a href=\"https://docs.aws.amazon.com/solutions/latest/automated-forensics-orchestrator-for-amazon-ec2/welcome.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Network containment",
    q: "What's the fastest and safest way to isolate a compromised EC2 instance from the network WITHOUT powering it off (preserving memory state for forensic analysis)?",
    options: [
      "Terminate the instance immediately: cutting off the attacker's channel always comes first",
      "Change the operating system password and rotate the SSH keys of every local user account",
      "Stop the instance, since the state of its RAM is preserved intact inside the root EBS volume itself",
      "Apply a quarantine Security Group with no rules, leaving it running so memory can be captured",
    ],
    correct: 3,
    explain: "Powering off or terminating the instance destroys RAM, which is valuable volatile evidence (a <code>stop</code> doesn't preserve it either: RAM is not flushed to the root volume). The correct practice is to isolate at the network level with a quarantine Security Group while keeping the instance POWERED ON, so a memory dump can be taken before analysis and eventual replacement. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/compromised-ec2.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Capturing forensic evidence",
    q: "When capturing forensic evidence from a compromised EC2 instance for later analysis, which TWO artifacts are most valuable to capture before any other action?",
    options: [
      "A snapshot of the EBS volume and a dump of the instance's RAM, taken before touching anything else",
      "The account's CloudTrail logs and the detailed billing history for the month the incident happened",
      "The CloudWatch CPU and network metrics for the window in which the finding was detected",
      "The Systems Manager software inventory and the list of patches still pending on the instance",
    ],
    correct: 0,
    explain: "The EBS snapshot preserves disk state for later analysis without altering the original instance. The memory dump (using tools such as AVML, run through Systems Manager) preserves volatile evidence that disappears the moment the instance is powered off or restarted — both artifacts are top priority during the containment and capture phase. <a href=\"https://docs.aws.amazon.com/ebs/latest/userguide/ebs-snapshots.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SageMaker AI for forensics",
    q: "The SCS-C03 exam guide explicitly mentions 'Amazon SageMaker AI notebooks' as an example under skill 2.1.1 (incident response runbooks). What would they be used for in this context?",
    options: [
      "To train production machine learning models on the data recovered from the compromised instance",
      "As an isolated, reproducible workbench for analyzing forensic artifacts with Python scripts",
      "To detect malware inside the snapshot, taking the place of GuardDuty Malware Protection for EC2",
      "To serve the affected application while the infrastructure is rebuilt from the golden image",
    ],
    correct: 1,
    explain: "Although SageMaker is best known for ML, its notebook instances (managed, isolated Jupyter environments) are useful as a forensic workbench: analyzing captured artifacts with Python scripts in a reproducible, documented way, in an environment separate from production infrastructure — a non-obvious use the exam tests precisely because it's surprising. <a href=\"https://docs.aws.amazon.com/sagemaker/latest/dg/nbi.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Validating findings before acting",
    q: "You receive a medium-severity GuardDuty finding on an instance. Before executing high-impact containment actions (e.g. terminating the instance), what should you do first per skill 2.2.3?",
    options: [
      "Act on the resource immediately: in incident response, speed matters more than certainty does",
      "Discard medium-severity findings as a rule, since they rarely correspond to malicious activity",
      "Validate the real scope and impact, corroborating the finding with CloudTrail and VPC Flow Logs",
      "Silence the finding with a suppression rule and review it at next week's security review meeting",
    ],
    correct: 2,
    explain: "Skill 2.2.3 (new in SCS-C03) explicitly calls for validating findings to determine actual scope and impact before acting — avoiding both analysis paralysis and a disproportionate response to a false positive, by correlating the finding with other sources (Flow Logs, CloudTrail, Detective) before a high-impact action such as terminating a production resource. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_remediate.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Detective",
    q: "What does Amazon Detective solve that GuardDuty and Security Hub alone don't solve well?",
    options: [
      "Detective inspects traffic payloads, removing the need to set up VPC Traffic Mirroring",
      "Detective evaluates resource configuration against security controls, much as AWS Config does",
      "Detective groups findings by cost so you can prioritize the most expensive resources first",
      "Detective builds a behavior graph between entities, the basis for root cause analysis",
    ],
    correct: 3,
    explain: "GuardDuty and Security Hub tell you WHAT happened (point-in-time findings). Detective automatically aggregates CloudTrail, VPC Flow Logs, and GuardDuty data into a navigable graph of relationships between entities over time, letting you trace the CHAIN of events (root cause analysis): 'this IAM role, compromised at 3:15, then accessed these 4 resources from this new IP.' <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/what-is-detective.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Detective",
    q: "Does Detective REPLACE the need to have CloudTrail and VPC Flow Logs enabled?",
    options: [
      "No: it consumes those logs to build its graph, so its history starts when you enable it",
      "Yes: Detective generates its own independent logs and needs no pre-existing source enabled",
      "Detective can only be enabled in accounts with CloudTrail turned off, to avoid duplicate data",
      "Detective takes over from Security Hub as the central aggregator of findings for all accounts",
    ],
    correct: 0,
    explain: "Detective depends on those log sources existing — it doesn't replace them, it CORRELATES them (it uses independent, duplicate streams of CloudTrail and VPC Flow Logs, without changing your configuration or your bill for those services). It retains up to 1 year of history, but only from the moment it was enabled: turn it on proactively rather than waiting for the incident. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/detective-source-data-about.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Recovery",
    q: "After containing and eradicating a compromise on an EC2 instance, what is the SAFEST practice for restoring service?",
    options: [
      "Reboot the compromised instance, since a reboot clears out the malicious processes living in memory",
      "Replace it with a new instance deployed from a known-good hardened AMI, rather than cleaning it",
      "Restore the local passwords and SSH keys, which is how the attacker got in there in the first place",
      "Apply the pending patches to the compromised instance and put it back behind the load balancer",
    ],
    correct: 1,
    explain: "The recovery principle after a compromise is 'don't trust what could have been tampered with': rebuilding from a known-clean image (golden AMI, IaC) is far more reliable than hand-cleaning an instance where the attacker may have left backdoors, scheduled tasks, or modified binaries that are hard to find exhaustively. GuardDuty's own guidance recommends terminating and replacing when eradication can't be guaranteed. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/compromised-ec2.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Restoring from backup",
    q: "During the recovery phase after a ransomware incident that encrypted production data, what verification is CRITICAL before restoring from a backup?",
    options: [
      "None: always restoring the most recent backup minimizes data loss and shortens the overall service RTO",
      "Checking that the backup's size matches that of the original volume before restoring it",
      "Confirming the backup predates the compromise, leaning on immutable vaults as the trusted source",
      "Restoring onto the same volumes and in the same account, to get back to service faster",
    ],
    correct: 2,
    explain: "Restoring a backup taken after the compromise can reintroduce the same vulnerability, or even already-encrypted data and persisted backdoors. That's why immutable backups (AWS Backup Vault Lock, S3 Object Lock) are so valued: they guarantee at least one version predating the attack exists that couldn't be altered even by an attacker with administrator credentials. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Multi-service log correlation",
    q: "You're investigating possible lateral movement by an attacker who compromised IAM credentials. What combination of sources gives you the most complete picture of the scope (skill 2.2.2)?",
    options: [
      "Review the month's AWS bill and Cost Explorer to locate the attacker's anomalous spending",
      "Query the Systems Manager inventory to see what software was installed on the instances",
      "Look at the CloudWatch CPU and network alarms for the instances during the detected incident window",
      "Cross-reference CloudTrail, VPC Flow Logs, and GuardDuty/Detective findings in the same time window",
    ],
    correct: 3,
    explain: "Lateral movement leaves traces across several layers: CloudTrail shows WHAT the attacker did via API, VPC Flow Logs show WHAT they connected to at the network level, and GuardDuty/Detective already correlate anomalous patterns automatically. Cross-referencing all three within the same time window is what lets you reconstruct the real scope, instead of looking at each in isolation. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Application Recovery Controller",
    q: "What is Amazon Application Recovery Controller (ARC) used for in an incident scenario affecting an entire region?",
    options: [
      "To orchestrate multi-region failover with readiness checks and routing controls, not manual steps",
      "To scan applications for vulnerabilities before they are promoted into the production environment",
      "To issue and renew the TLS certificates for the application's endpoints in both regions",
      "To continuously replicate the databases into the secondary region as a managed backup service",
    ],
    correct: 0,
    explain: "ARC continuously verifies that the standby region's infrastructure is genuinely ready to receive traffic (readiness checks) and provides safe 'routing controls' — on/off switches with protection against accidental activation — to execute failover: built for exactly the moment of maximum pressure during a regional availability incident. <a href=\"https://docs.aws.amazon.com/r53recovery/latest/dg/what-is-route53-recovery.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Chain of custody",
    q: "Why is it important to tag and document (timestamp, who, what action) each forensic artifact captured during an incident (snapshots, memory dumps, exported logs)?",
    options: [
      "It makes per-project cost allocation easier, since tags propagate into the detailed billing report",
      "To sustain the chain of custody: with no record of capture and handling, evidence loses validity",
      "Because AWS applies a reduced rate to snapshots tagged as evidence belonging to an incident",
      "Because without tags Systems Manager cannot run Automation runbooks against those resources",
    ],
    correct: 1,
    explain: "Chain of custody is a frequent requirement in investigations that may lead to legal action or regulatory reporting: without a clear record of capture, access, and handling for each forensic artifact, the evidence can lose validity. Solutions like Automated Forensics Orchestrator automate that tagging and its logging from the very first step. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_incident_response_prepare_forensic.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IR plan testing",
    q: "What is the difference between 'testing' an incident response plan with a tabletop exercise versus with AWS Fault Injection Service?",
    options: [
      "They are equivalent: both inject real technical failures and differ only in the tooling that is used",
      "FIS can only be run once a year because of a service quota; the tabletop has no such limit",
      "The tabletop validates the team's process and communication; FIS validates alarms and runbooks",
      "The tabletop requires interrupting production, whereas FIS always works on isolated environments",
    ],
    correct: 2,
    explain: "Both are valid, mutually complementary forms of 'test and validate' (skill 2.1.3) mentioned in the exam guide: the tabletop validates that the TEAM knows what to do and communicates well; FIS validates that the TECHNOLOGY (alarms, automations, executable runbooks) genuinely responds as designed, with guardrails so it doesn't cause a real incident by accident. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_incident_response_run_game_days.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Security Incident Response",
    q: "Your organization wants to reduce the time between detecting a critical GuardDuty finding and starting an expert-led investigation, including access to an AWS team with real incident response experience, available 24/7. Which AWS service, generally available since December 2024, is specifically designed for this?",
    options: [
      "AWS Trusted Advisor, which reviews the account and recommends security and cost best practices",
      "Amazon Detective, which helps you investigate findings but adds no human AWS team to the case",
      "AWS Systems Manager Incident Manager, which handles the operational process and on-call escalation",
      "AWS Security Incident Response, with automated triage and 24/7 access to the AWS IR team",
    ],
    correct: 3,
    explain: "Security IR (GA December 2024) combines automated monitoring and triage of GuardDuty and Security Hub findings, AI-assisted investigation tools, and direct 24/7 access to the AWS CIRT. Detective helps investigate but doesn't provide access to a human AWS team; Incident Manager manages the operational process but no longer accepts new customers; Trusted Advisor only provides best-practice recommendations. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security IR: proactive vs. reactive cases",
    q: "After enabling AWS Security Incident Response in your organization, what distinguishes a 'reactive' case from a proactive case (prefixed '[Proactive case]')?",
    options: [
      "The reactive one is opened by the customer when they suspect a compromise and ask AWS for help",
      "There's no real difference: the console uses both terms as synonyms for the same kind of case",
      "Proactive ones are only generated for Windows EC2 instances and for workloads running on EKS",
      "Reactive ones carry no cost, whereas proactive ones are billed per correlated finding they include",
    ],
    correct: 0,
    explain: "Security IR analyzes the account's historical behavior baseline, the finding type, and cross-account correlation patterns to automatically filter out noise; when it concludes there's a genuine threat, it opens a proactive case (prefixed '[Proactive case]') without the customer having to spot it first. Reactive cases are the ones the customer creates when they suspect an incident. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/responding-to-an-aws-generated-case.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Incident Manager retirement: migrate to OpsCenter",
    q: "You're designing the incident response plan for a new AWS account in 2026 and are considering AWS Systems Manager Incident Manager to manage the incident lifecycle and team escalation. What should you keep in mind?",
    options: [
      "It's the option AWS recommends today for any new account that is starting out with its response plan",
      "Since November 2025 it accepts no new customers and gets no new features: AWS points to OpsCenter",
      "It has been renamed Amazon Detective, which absorbs management of the incident lifecycle",
      "It's only available in us-east-1, so it forces you to centralize all incident response there",
    ],
    correct: 1,
    explain: "AWS announced that, as of November 7, 2025, Incident Manager no longer accepts new customers and will receive no new features (existing customers can keep using it). For a new account, official guidance points to OpsCenter to centralize OpsItems, and to AWS Partner Network solutions for the escalation and paging capabilities Incident Manager previously covered. <a href=\"https://docs.aws.amazon.com/incident-manager/latest/userguide/incident-manager-availability-change.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Detective: GenAI finding group summaries",
    q: "A junior SOC analyst receives a complex finding group in Amazon Detective with dozens of findings and related resources, and struggles to prioritize where to start. Which Detective capability quickly gives them a natural-language summary of what's happening and its possible impact?",
    options: [
      "An AWS Trusted Advisor check run against the resources involved in that group of findings",
      "Amazon Q Business, indexing the group's findings so you can ask about them in natural language",
      "Finding group summary, which summarizes the group in plain language using GenAI on Bedrock",
      "GuardDuty Malware Protection, which scans the named resources and summarizes what it finds",
    ],
    correct: 2,
    explain: "Finding group summary uses generative AI models hosted on Amazon Bedrock to automatically analyze the relationships between the findings and affected resources in a finding group, producing a natural-language summary (what triggered the activity, its potential impact) that dramatically speeds up initial triage — available at no extra cost for accounts with Detective enabled. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/finding-group-summary.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Detective Investigations for IAM",
    q: "You want to know whether a specific IAM role has shown anomalous behavior recently (e.g. 'impossible travel', usage from IP addresses flagged as malicious, known attack tactics), and get a report listing the indicators of compromise (IoCs) and tactics/techniques (TTPs) detected. Which Amazon Detective capability would you use?",
    options: [
      "Cost Explorer, filtering by the role to see whether its associated spend has spiked anomalously",
      "AWS Config Rules applied to the role, evaluating whether its policy drifts from the approved standard",
      "IAM Access Analyzer, which reviews which external principals could assume the role from another account",
      "Detective investigations, which analyzes the ARN with ML and threat intel and returns IoCs and TTPs",
    ],
    correct: 3,
    explain: "Detective investigations applies machine learning and threat intelligence to analyze IAM resources by ARN and produce a report of the indicators of compromise and TTPs associated with anomalous behavior such as 'impossible travel' or usage from flagged IPs — available from the Detective console or its API, and it complements (not replaces) Access Analyzer, which focuses on unintended access from policy design rather than anomalous behavior over time. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/investigations-about.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Backup: logically air-gapped vault",
    q: "Your security team wants a backup copy that not even an attacker with compromised root administrator credentials inside the workload account can delete or modify. Which AWS Backup solution meets this requirement with the strongest guarantee?",
    options: [
      "A logically air-gapped vault, whose copies live outside the workload account and are immutable",
      "EBS snapshots scheduled with Data Lifecycle Manager and copied to another region of the same account",
      "An S3 bucket with versioning enabled and a bucket policy denying DeleteObject to everyone else",
      "AWS Backup Vault Lock in governance mode, which prevents deletion of the vault's recovery points",
    ],
    correct: 0,
    explain: "The logically air-gapped vault (GA August 2024) stores copies in an AWS-managed account, outside the reach of the workload account, locked and immutable by default: not even root can delete them within the retention period. Vault Lock's governance mode (option D) CAN be removed by users with sufficient IAM permissions, so it offers a weaker guarantee against an attacker with administrator privileges. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/logicallyairgappedvault.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Backup: multi-party approval",
    q: "A ransomware attack leaves the workload's AWS account completely inaccessible (root credentials were compromised and rotated by the attacker). Which recent AWS Backup capability lets you recover the backups stored in a logically air-gapped vault in this extreme scenario?",
    options: [
      "Restoring with the compromised account's root credentials, already rotated, from another region",
      "Multi-party approval, which lets approved accounts in the organization authorize restore access",
      "Opening a support case on the Basic plan so AWS hands control of the affected account back to you",
      "There is no recovery path: the vault becomes unreachable if its owning account is compromised",
    ],
    correct: 1,
    explain: "Multi-party approval addresses exactly the scenario where the backup-owning account becomes inaccessible: the request to create a <code>restore access backup vault</code> in a recovery account goes through an approval session, and once the required number of team members approves, the access point is created so you can restore from the air-gapped vault without depending on the compromised account. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/multipartyapproval.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for AWS Backup",
    q: "Before restoring an EBS volume backup after a ransomware incident, you want to automatically verify that specific backup contains no malware, and ideally identify the last known 'clean' backup to minimize data loss. Which capability would you use?",
    options: [
      "Amazon Inspector, which scans the recovery point's contents looking for known malware signatures",
      "AWS Config with a conformance pack that marks any infected backup as non-compliant",
      "GuardDuty Malware Protection for AWS Backup, which scans backups and finds the last clean one",
      "Amazon Macie, which inspects the recovery point's metadata for signs of encryption",
    ],
    correct: 2,
    explain: "GuardDuty Malware Protection for AWS Backup extends malware detection to backups (EBS snapshots, EC2 AMIs, and S3 recovery points): it automatically scans new backups against a read-only copy, allows on-demand scans of existing ones, and helps verify a backup is clean before you restore it. It works even if GuardDuty's foundational data sources aren't enabled. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection-backup.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Elastic Disaster Recovery: recovery points and ransomware",
    q: "You use AWS Elastic Disaster Recovery (DRS) to continuously replicate your servers to AWS with a seconds-level RPO. During the investigation you discover the ransomware had been active for several hours before encrypting the data. How should you recover the service with DRS?",
    options: [
      "Always launch the recovery instance from the most recent recovery point that is available",
      "Stop DRS replication and wait for the ransomware's activity to die down on its own",
      "DRS only keeps the last replicated state, so you have to fall back on AWS Backup exclusively",
      "Launch it from a recovery point that predates the start of the detected malicious activity",
    ],
    correct: 3,
    explain: "AWS DRS keeps multiple point-in-time snapshots over time under its PIT policy, not just the most recent one, and lets you launch the recovery instance from any of them. Facing ransomware that had been active for a while before encrypting, the most recent point would reintroduce the compromise: pick a point that predates the start of the malicious activity identified during the investigation. <a href=\"https://docs.aws.amazon.com/drs/latest/userguide/point-in-time.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudTrail Lake for forensic investigation",
    q: "You need to investigate the activity of a compromised credential across several of your organization's accounts over the last several years, running complex SQL queries against API events without manually exporting and processing log files stored in S3. Which CloudTrail capability would you use?",
    options: [
      "CloudTrail Lake, an immutable event store queried with SQL and retention of up to 7 years",
      "CloudTrail Insights, which spots deviations in call volume but doesn't support SQL queries",
      "VPC Flow Logs delivered to an S3 bucket and queried with Athena, partitioned by account and day",
      "AWS Config Aggregator, which gathers the configuration history of the organization's resources",
    ],
    correct: 0,
    explain: "CloudTrail Lake stores events immutably with read-only access, supports SQL queries (Trino engine) directly from the console against event data stores, and supports configurable retention of up to 7 years — ideal for forensic investigations that need to correlate historical activity across multiple accounts without manually managing log files in S3. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-lake.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "VPC Traffic Mirroring for network forensics",
    q: "While investigating a compromised EC2 instance, you want to capture the actual CONTENT of the network packets (payloads), not just metadata about who connected to whom, so you can analyze it with an out-of-band deep packet inspection (DPI) tool. What capability gives you this?",
    options: [
      "VPC Flow Logs, whose records include the full payload of every packet as well as the header",
      "VPC Traffic Mirroring, which copies ENI traffic, payload included, to an out-of-band destination",
      "CloudTrail with data events enabled, which records the content of every outbound TCP/IP packet sent",
      "AWS Config with network traffic recording enabled on the instance's network interfaces",
    ],
    correct: 1,
    explain: "VPC Flow Logs only capture metadata (source and destination IPs, ports, bytes, action) — NEVER the packet content. VPC Traffic Mirroring acts as a virtual network tap: it copies the full traffic (payload included) from the instance's ENI to out-of-band security appliances, with no agent and without touching the source instance — the right tool when the analysis needs the actual content of the communication. <a href=\"https://docs.aws.amazon.com/vpc/latest/mirroring/what-is-traffic-mirroring.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Dedicated forensic account",
    q: "As part of preparation (2.1.2), your organization creates an AWS account dedicated solely to forensic analysis, separate from workload accounts. What's the correct flow for analyzing an EBS volume from a compromised instance in that forensic account?",
    options: [
      "Hand the forensic account a set of administrator credentials for the compromised account",
      "Move the compromised account into the organization's forensic OU and analyze it in place from inside",
      "Share the snapshot and its KMS key, copy it re-encrypted into the forensic account, mount read-only",
      "Mount the original volume on another instance of the compromised account and analyze it live",
    ],
    correct: 2,
    explain: "The standard multi-account forensics pattern is: snapshot in the compromised account → share the snapshot and access to the source KMS key (mandatory: a snapshot encrypted with the AWS managed key cannot be shared) → copy and re-encrypt the snapshot with a key owned by the forensic account → create a volume and mount it read-only, preserving the artifact's integrity during analysis. <a href=\"https://docs.aws.amazon.com/ebs/latest/userguide/ebs-modifying-snapshot-permissions.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Automated Forensics Orchestrator: EKS support",
    q: "Your organization runs workloads on both EC2 instances and Amazon EKS clusters on EC2. Does AWS's 'Automated Forensics Orchestrator' solution cover both cases?",
    options: [
      "No: for EKS there's a separate solution, unrelated to the EC2 forensics orchestrator",
      "Only if everything is deployed in a single account and region, as it has no distributed support",
      "It only covers EC2 instances running Windows Server; Linux and EKS need your own tooling",
      "Yes: it's named 'for Amazon EC2 and EKS' and covers both, across accounts and regions",
    ],
    correct: 3,
    explain: "The AWS guidance 'Automated Forensics Orchestrator for Amazon EC2 and EKS' (built on Step Functions, Lambda, and SSM documents) orchestrates the same forensic workflow — resource isolation, memory and disk capture, chain of custody — for both EC2 instances and EKS clusters running on EC2 and their attached volumes, with multi-account and multi-region deployments. <a href=\"https://docs.aws.amazon.com/solutions/latest/automated-forensics-orchestrator-for-amazon-ec2/architecture-overview.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Security Lake for centralized investigation",
    q: "You want to centralize and normalize CloudTrail logs, VPC Flow Logs, Route 53 Resolver DNS queries, and Security Hub findings from dozens of accounts into a single format (so they can be correlated easily), and then analyze them with Athena or third-party tools during an investigation. Which AWS service is designed for this?",
    options: [
      "Amazon Security Lake, which normalizes those sources into the open OCSF schema in Parquet format",
      "AWS Config Aggregator, which centralizes configuration history but not the activity logs of the API",
      "AWS Systems Manager Inventory, which collects the software installed across managed instances",
      "Amazon Macie, which classifies sensitive data in S3 and aggregates it into a central dashboard",
    ],
    correct: 0,
    explain: "Amazon Security Lake automatically ingests and normalizes CloudTrail logs, VPC Flow Logs, Route 53 Resolver query logs, and Security Hub findings — plus dozens of partner sources — into the OCSF schema (Parquet format), centralizing them into a data lake queryable with Athena, QuickSight, or other tools, specifically to simplify correlation across heterogeneous sources during an investigation. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/what-is-security-lake.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Backup Vault Lock: compliance mode",
    q: "You configure an AWS Backup Vault Lock in COMPLIANCE mode with a 3-day 'cooling-off' grace period. What does this mean for the immutability of the backups in that vault?",
    options: [
      "It's identical to governance mode: any user with sufficient IAM permissions can remove the lock at will",
      "During that period you can still remove or modify the lock; afterwards nobody, not even AWS, can",
      "Compliance mode allows deleting individual recovery points even while the vault stays locked",
      "The grace period only applies to vaults that are encrypted with a customer-managed KMS key",
    ],
    correct: 1,
    explain: "Vault Lock's compliance mode includes a grace period of at least 72 hours during which the lock can still be undone or modified; once it expires, neither the account's root user nor AWS can delete or alter the vault or its configuration until every recovery point's retention ends — unlike governance mode, where users with sufficient IAM permissions can remove the lock at any time. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/vault-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "EventBridge + Security IR: case automation",
    q: "In addition to the automatic triage AWS Security Incident Response performs on GuardDuty/Security Hub findings, you want your own automation pipeline (e.g. a Step Functions state machine that notifies your internal SOC) to trigger as soon as a Security IR case is opened or updated. How do you achieve this?",
    options: [
      "It isn't possible: Security IR is a closed service operated only from its own console",
      "By polling the Security IR console every five minutes with a custom script that spots the changes",
      "By consuming in EventBridge the case creation and update events that Security IR publishes",
      "Only through the phone calls the AWS CIRT places to the designated security contact",
    ],
    correct: 2,
    explain: "Security IR publishes every case lifecycle event (creation, update) to Amazon EventBridge, in addition to exposing a console and API — this lets you build your own automations with Rules or Pipes (Step Functions notifying the internal SOC, opening a ticket in the company's ITSM tool, and so on) that react in real time, without relying on manual polling. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/eventbridge.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Route 53 Resolver query logs in forensics",
    q: "During a forensic investigation you suspect a compromised instance has been periodically resolving the domain of a command-and-control (C2) server. CloudTrail doesn't log this kind of activity because it isn't an AWS API call. Which data source should you consult (ideally already enabled beforehand) to confirm this hypothesis?",
    options: [
      "AWS Config, which records every configuration change to the network resources inside the VPC",
      "IAM Access Analyzer, which identifies external access granted by the account's own policies",
      "AWS Cost Explorer, filtered by the instance to spot the anomalous outbound traffic being billed",
      "Route 53 Resolver query logs, which record the DNS queries issued by resources in the VPC",
    ],
    correct: 3,
    explain: "DNS resolutions aren't AWS API calls, so CloudTrail doesn't log them. Route 53 Resolver query logs do capture the DNS queries issued from VPC resources (domain, record type, source IP and instance, response code), making them the right source for detecting periodic communication with C2 domains — which is why it's worth enabling them as part of preparation, just like CloudTrail or VPC Flow Logs. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "S3 Object Lock for exported evidence",
    q: "After exporting analyzed memory dumps and snapshots to an S3 bucket as a long-term evidence repository (for possible litigation), which combination of S3 features guarantees those objects can't be overwritten or deleted by ANYONE, even if the configured retention period has already expired but the legal proceeding is still open?",
    options: [
      "S3 Object Lock in compliance mode combined with a Legal Hold, which carries no expiration date",
      "S3 versioning on its own, which retains every previous version of the objects that get overwritten",
      "Server-side encryption with SSE-KMS and a key policy denying deletion to all other principals",
      "A bucket policy denying s3:DeleteObject to every principal except the administrator role",
    ],
    correct: 0,
    explain: "S3 Object Lock's compliance mode prevents anyone (including root) from modifying or deleting the object for as long as the configured retention period lasts. Legal Hold is an independent mechanism with no expiration date: it keeps protecting the object even after retention has expired, until someone with permission explicitly removes it — exactly what's needed when litigation drags on longer than expected. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Containing a compromised EC2",
    q: "GuardDuty reports that a production EC2 instance is talking to a command-and-control IP. You must contain it while preserving evidence for later forensics. Which TWO actions are appropriate?",
    options: [
      "Replace its security group with one that has no outbound rules, isolating it without powering it off",
      "Terminate the instance immediately in order to cut off communication with the command-and-control server",
      "Take EBS volume snapshots and capture memory before taking any other action on the instance",
      "Reboot the instance to clear the running malicious processes out of its memory for good",
    ],
    correct: [0, 2],
    explain: "Network isolation cuts the channel without destroying state, and the <strong>EBS snapshot plus memory capture</strong> preserve the evidence. Terminating destroys ephemeral disk and memory at once: the case is gone. Rebooting is just as damaging, because memory is exactly where fileless malware lives. Exam rule: contain is not destroy. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/compromised-ec2.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Exposed IAM credentials",
    q: "An IAM user's access key is found to have been public in a repository for days. Which TWO actions come first?",
    options: [
      "Change the user's console password and consider the incident closed",
      "Disable or delete the access key published in the repository right away",
      "Wait for the key to expire on its own, since IAM access keys rotate automatically",
      "Review CloudTrail to see what was done with the key and from which IPs",
    ],
    correct: [1, 3],
    explain: "First cut off access (<strong>disable the key</strong>), then establish scope (<strong>CloudTrail</strong>): without knowing what the attacker did you cannot know whether they left backdoors such as new roles or users. Changing the console password does nothing to an access key, which is a separate credential. And IAM access keys <strong>never expire on their own</strong>: they live until someone disables them. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Preparing the response plan",
    q: "The security team wants to respond to incidents without depending on an administrator being available to grant permissions mid-crisis. Which TWO measures prepare for this?",
    options: [
      "Pre-create an incident response role with a tightly scoped trust policy",
      "Distribute the accounts' root credentials among the members of the on-call team",
      "Grant the entire security team permanent AdministratorAccess in every account",
      "Document and automate the procedures as Systems Manager runbooks",
    ],
    correct: [0, 3],
    explain: "A <strong>pre-provisioned role</strong> and <strong>automated runbooks</strong> allow fast action without improvising permissions or steps. Sharing root credentials destroys traceability and is the opposite of AWS guidance: root is protected with MFA and used only for tasks that require it. Permanent AdministratorAccess turns the response team into the account's biggest risk. <a href=\"https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Chain of custody",
    q: "Evidence collected from an incident may end up in legal proceedings. Which TWO practices protect its validity?",
    options: [
      "Analyze the affected instance's original volumes directly, in place",
      "Store the evidence in a forensics account with restricted, logged access",
      "Compute and retain integrity hashes of every artifact collected",
      "Compress the evidence and email it over to the company's external legal team",
    ],
    correct: [1, 2],
    explain: "<strong>Isolation in a forensics account</strong> with audited access and <strong>integrity hashes</strong> are what let you prove the evidence wasn't altered. Working on the original volumes modifies them and ruins the chain of custody: always analyze copies. Email provides neither access control nor proof of integrity. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_incident_response_prepare_forensic.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["incident-response"] = QUIZ_DATA;
