const QUIZ_DATA = [
  {
    tag: "Runbooks & OpsCenter",
    q: "What role does AWS Systems Manager OpsCenter play in an incident response plan?",
    options: [
      "It's a backup service",
      "It centralizes 'OpsItems' (operational incidents/problems) with related context (affected resources, CloudWatch alarms, associated Automation runbooks), letting you investigate and execute remediations from a single place",
      "It replaces CloudTrail for auditing",
      "It only works with Windows EC2 instances",
    ],
    correct: 1,
    explain: "OpsCenter aggregates 'OpsItems' that represent operational incidents or problems, automatically linking in the relevant context (resources, alarms, executable Systems Manager Automation runbooks) — it's the Systems Manager piece designed to centralize investigation and execution of the response, not just passive incident logging.",
  },
  {
    tag: "Preparation: minimizing blast radius",
    q: "As part of PREPARING an account for incidents (before they happen), which practice reduces the 'blast radius' if a workload is compromised?",
    options: [
      "Using a single AWS account for everything to simplify management",
      "Segmenting workloads into separate accounts (multi-account strategy), with least-privilege IAM permissions and no long-lived credentials shared across environments",
      "Granting AdministratorAccess to every role to speed up the response when an incident occurs",
      "Disabling CloudTrail to reduce noise",
    ],
    correct: 1,
    explain: "Minimizing blast radius is a PREPARATION activity (skill 2.1.2): separating workloads into distinct accounts, applying least privilege, and avoiding shared credentials limits how far an attacker can get if they compromise a single component — much cheaper to do before the incident than during it.",
  },
  {
    tag: "Provisioning emergency access",
    q: "Why is it important to PRE-PROVISION (before the incident) the access the response team will need during an investigation?",
    options: [
      "It isn't important — the necessary access can be created on the fly during the incident with no impact",
      "Because during an active incident you don't want to depend on slow IAM approval workflows or rush-create new roles (risking over-granting permissions); an IR role with permissions already audited and tested reduces response time and errors",
      "Because IAM doesn't allow creating new roles while GuardDuty is enabled",
      "It only applies if you use IAM Identity Center",
    ],
    correct: 1,
    explain: "Skill 2.1.2 explicitly mentions 'provisioning access' as part of preparation: an IR role with broad read-only permissions plus specific containment actions (isolate an SG, create a snapshot), already tested and audited beforehand, avoids improvising permissions under pressure during the incident — exactly when it's easiest to make an over-privilege mistake.",
  },
  {
    tag: "AWS Fault Injection Service",
    q: "What is AWS Fault Injection Service (FIS) used for in the context of validating an incident response plan?",
    options: [
      "To automatically deploy security patches",
      "To run CONTROLLED chaos engineering experiments (e.g. simulating an AZ outage, network latency, terminating instances) to test whether your alarms, runbooks, and response plan actually work as expected",
      "To generate real, uncontrolled attack traffic against production",
      "It's a service exclusively for malware forensics",
    ],
    correct: 1,
    explain: "FIS lets you design and run controlled failure experiments with guardrails (automatic stop conditions if something goes outside expected bounds) to validate that detection, alerting, and response runbooks genuinely work — instead of waiting for a real incident to discover the alarm never fired.",
  },
  {
    tag: "AWS Resilience Hub",
    q: "What does AWS Resilience Hub assess?",
    options: [
      "The cost of an architecture",
      "An application's resilience against defined recovery objectives (RTO/RPO), identifying architectural gaps and recommending improvements, and it can orchestrate FIS experiments to validate it",
      "Only PCI-DSS compliance",
      "Network latency between regions",
    ],
    correct: 1,
    explain: "Resilience Hub evaluates a defined application against RTO (recovery time objective) and RPO (recovery point/acceptable data loss objective), flags where the current architecture would fall short, and can generate/run FIS experiments to validate real resilience — complementary to FIS (FIS runs the experiment, Resilience Hub defines the target it's measured against).",
  },
  {
    tag: "Automated remediation",
    q: "You want a high-severity GuardDuty finding on an EC2 instance (e.g. communication with a cryptocurrency mining IP) to trigger automatic isolation of that instance without waiting for a human to act. What architecture do you implement?",
    options: [
      "Review findings manually every morning",
      "An EventBridge rule that captures the GuardDuty finding and triggers a Lambda function or a Step Functions state machine that switches the instance's Security Group to a quarantine one (no traffic allowed except toward the forensics subnet)",
      "Manually disable the instance via the console when someone notices",
      "Configure an SCP that blocks GuardDuty",
    ],
    correct: 1,
    explain: "The standard automated remediation pattern (skill 2.1.4) is: GuardDuty finding → EventBridge rule (filters by severity/type) → Lambda/Step Functions executes the containment action (e.g. switching the Security Group to a quarantine one) — all within seconds, without waiting on human intervention for initial containment.",
  },
  {
    tag: "Automated Forensics Orchestrator",
    q: "What does the AWS 'Automated Forensics Orchestrator for Amazon EC2' solution automate?",
    options: [
      "Continuous vulnerability scanning with Inspector",
      "The entire forensics workflow for a compromised EC2 instance: network isolation (quarantine SG), EBS snapshot and memory capture, tagging for chain of custody, and notifying the IR team — without manual intervention at each step",
      "IAM credential rotation",
      "Patch deployment across the whole fleet",
    ],
    correct: 1,
    explain: "It's an AWS solution (built on Step Functions + Lambda) that automatically orchestrates the full forensic process for a compromised instance: isolating the network, capturing evidence (disk and memory snapshots), preserving chain of custody through tagging/logging, and sending notifications — cutting containment time from hours to minutes.",
  },
  {
    tag: "Network containment",
    q: "What's the fastest and safest way to isolate a compromised EC2 instance from the network WITHOUT powering it off (preserving memory state for forensic analysis)?",
    options: [
      "Terminate the instance immediately",
      "Switch its Security Group to a 'quarantine' one with no inbound/outbound rules (or only outbound toward forensics tools/subnet), keeping the instance powered on so memory can be captured before any other action",
      "Physically disconnect the network cable",
      "Change the operating system password",
    ],
    correct: 1,
    explain: "Powering off or terminating the instance destroys RAM memory (valuable volatile evidence). The correct practice is to isolate at the network level (quarantine Security Group) while keeping the instance POWERED ON, so a memory dump can be captured before proceeding with analysis and eventually replacing the instance.",
  },
  {
    tag: "Capturing forensic evidence",
    q: "When capturing forensic evidence from a compromised EC2 instance for later analysis, which TWO artifacts are most valuable to capture before any other action?",
    options: [
      "Only the account's CloudTrail logs",
      "A snapshot of the EBS volume (disk state) and a memory (RAM) capture of the instance — memory contains volatile evidence (running processes, active connections, in-memory keys) that's lost once the instance is powered off",
      "Only CloudWatch CPU metrics",
      "The account's billing history",
    ],
    correct: 1,
    explain: "The EBS snapshot preserves disk state for later analysis without altering the original instance. The memory capture (using tools like AWS's AVML or similar, via Systems Manager) preserves volatile evidence that disappears the moment the instance is powered off or restarted — both artifacts are top priority during the containment/capture phase.",
  },
  {
    tag: "SageMaker AI for forensics",
    q: "The SCS-C03 exam guide explicitly mentions 'Amazon SageMaker AI notebooks' as an example under skill 2.1.1 (incident response runbooks). What would they be used for in this context?",
    options: [
      "To train production machine learning models",
      "As an ISOLATED, programmatic analysis environment (Jupyter notebooks) for examining captured forensic artifacts (memory dumps, logs, mounted snapshots), running analysis scripts in a repeatable, documented way",
      "SageMaker has no relation to incident response — it's an error in the exam",
      "To deploy the company website during the incident",
    ],
    correct: 1,
    explain: "Although SageMaker is best known for ML, its notebooks (managed, isolated Jupyter environments) are useful as a forensic workbench: analyzing captured artifacts with Python scripts in a reproducible, documented way, in an environment separate from production infrastructure — a non-obvious use that the exam tests precisely because it's surprising.",
  },
  {
    tag: "Validating findings before acting",
    q: "You receive a medium-severity GuardDuty finding on an instance. Before executing high-impact containment actions (e.g. terminating the instance), what should you do first per skill 2.2.3?",
    options: [
      "Act immediately without verifying anything — speed is all that matters",
      "Validate the finding: confirm the actual scope and impact (which resources are really affected? is it a known false positive? is there corroboration from other sources like VPC Flow Logs or CloudTrail?) before escalating to a high-impact response",
      "Always ignore medium-severity findings",
      "Wait 48 hours before reviewing any finding",
    ],
    correct: 1,
    explain: "Skill 2.2.3 (new in SCS-C03) explicitly calls for validating findings to determine actual scope and impact before acting — avoiding both analysis-paralysis and a disproportionate response to a false positive, by correlating the finding with other sources (Flow Logs, CloudTrail, Detective) before a high-impact action like terminating a production resource.",
  },
  {
    tag: "Amazon Detective",
    q: "What does Amazon Detective solve that GuardDuty and Security Hub alone don't solve well?",
    options: [
      "Detective removes the need to have GuardDuty enabled",
      "Detective automatically builds a GRAPH of behavior and interactions between resources (IAM roles, instances, IPs) over time, making root cause analysis easier — answering 'how did the attacker get here and what else did they touch?' instead of just 'what happened in this single event?'",
      "Detective is simply a cost dashboard",
      "Detective only analyzes RDS logs",
    ],
    correct: 1,
    explain: "GuardDuty and Security Hub tell you WHAT happened (point-in-time findings). Detective automatically aggregates CloudTrail, VPC Flow Logs, and GuardDuty data into a navigable graph of relationships between entities over time, letting you trace the CHAIN of events (root cause analysis) — 'this IAM role, compromised at 3:15, then accessed these 4 resources from this new IP.'",
  },
  {
    tag: "Amazon Detective",
    q: "Does Detective REPLACE the need to have CloudTrail and VPC Flow Logs enabled?",
    options: [
      "Yes, Detective generates its own independent logs",
      "No: Detective CONSUMES those logs (CloudTrail, VPC Flow Logs, GuardDuty findings, and optionally EKS logs) to build its behavior graph — if those sources aren't active, or Detective wasn't enabled far enough in advance, the historical data available for investigation will be limited",
      "Detective only works without CloudTrail enabled",
      "Detective completely replaces Security Hub",
    ],
    correct: 1,
    explain: "Detective depends on those log sources already existing — it doesn't replace them, it CORRELATES them. It also retains up to 1 year of historical data for retrospective analysis, but only from the moment it was enabled: it's good practice to turn it on proactively (as part of preparation), not wait for the incident to enable it.",
  },
  {
    tag: "Recovery",
    q: "After containing and eradicating a compromise on an EC2 instance, what is the SAFEST practice for restoring service?",
    options: [
      "Reboot the same compromised instance and keep using it",
      "Replace the instance with a new one deployed from a known-good hardened AMI (golden image), rather than trying to 'clean' the compromised instance in-place — it's practically impossible to guarantee no trace of attacker persistence remains",
      "Restore only local user passwords",
      "Apply only pending patches to the compromised instance",
    ],
    correct: 1,
    explain: "The recovery principle after a compromise is 'don't trust what could have been tampered with': rebuilding from a known-clean image (golden AMI, IaC) is far more reliable than trying to manually clean an instance where the attacker may have left backdoors, scheduled tasks, or modified binaries that are hard to detect completely.",
  },
  {
    tag: "Restoring from backup",
    q: "During the recovery phase after a ransomware incident that encrypted production data, what verification is CRITICAL before restoring from a backup?",
    options: [
      "None — restoring the most recent available backup is always correct",
      "Confirming that the chosen backup predates the compromise (not a backup that already contains encrypted data or a persisted backdoor), using immutable backups (Vault Lock) as the trusted source",
      "Only checking the backup's size",
      "Asking the attacker which backup is safe",
    ],
    correct: 1,
    explain: "Restoring a backup taken after the compromise can reintroduce the same vulnerability or even already-encrypted data/backdoors. That's why immutable backups (AWS Backup Vault Lock, S3 Object Lock) are so valued: they guarantee at least one version predating the attack exists that couldn't be altered even by an attacker with administrator credentials.",
  },
  {
    tag: "Multi-service log correlation",
    q: "You're investigating possible lateral movement by an attacker who compromised IAM credentials. What combination of sources gives you the most complete picture of the scope (skill 2.2.2)?",
    options: [
      "Only review the month's AWS bill",
      "Correlate CloudTrail (which API actions were performed with those credentials), VPC Flow Logs (what network resources it connected to), and GuardDuty/Detective findings (patterns already flagged as anomalous) within the same time window",
      "Only look at CloudWatch CPU alarms",
      "Only Cost Explorer",
    ],
    correct: 1,
    explain: "Lateral movement leaves traces across multiple layers: CloudTrail shows WHAT the attacker did via API, VPC Flow Logs show WHAT they connected to at the network level, and GuardDuty/Detective already correlate anomalous patterns automatically. Cross-referencing all three sources within the same time window is what lets you reconstruct the real scope, instead of looking at each in isolation.",
  },
  {
    tag: "Application Recovery Controller",
    q: "What is Amazon Application Recovery Controller (ARC) used for in an incident scenario affecting an entire region?",
    options: [
      "To scan applications for vulnerabilities",
      "To orchestrate and monitor the failover of a multi-region application safely and in a controlled way (readiness checks + routing controls), avoiding error-prone manual failovers during a crisis",
      "To manage TLS certificates",
      "It's a database backup service",
    ],
    correct: 1,
    explain: "ARC continuously verifies that the backup region's infrastructure is genuinely ready to receive traffic (readiness checks) and provides safe 'routing controls' (with protection against accidental activation) to execute failover — built for exactly the moment of maximum pressure during a regional availability incident.",
  },
  {
    tag: "Chain of custody",
    q: "Why is it important to tag and document (timestamp, who, what action) each forensic artifact captured during an incident (snapshots, memory dumps, exported logs)?",
    options: [
      "Just for visual organization — it has no real impact",
      "To maintain chain of custody: if the incident ends up in a legal/regulatory action, you can demonstrate the evidence wasn't altered and who had access to it at each point in time",
      "Because AWS bills differently if it's tagged",
      "It's not relevant to the exam",
    ],
    correct: 1,
    explain: "Chain of custody is a frequent requirement in investigations that may lead to legal action or regulatory reporting: without a clear record of capture, access, and handling for each forensic artifact, the evidence can lose validity. Solutions like Automated Forensics Orchestrator automate this tagging from the very first step.",
  },
  {
    tag: "IR plan testing",
    q: "What is the difference between 'testing' an incident response plan with a tabletop exercise versus with AWS Fault Injection Service?",
    options: [
      "They're exactly the same thing",
      "A tabletop exercise is a simulation talked through verbally by the team (without touching real systems) to validate PROCESS and communication; FIS runs real, controlled TECHNICAL failures against the infrastructure to validate that automated alarms/runbooks actually trigger and work",
      "FIS can only be used once a year due to AWS limits",
      "Tabletop exercises require interrupting production, FIS doesn't",
    ],
    correct: 1,
    explain: "Both are valid, mutually complementary forms of 'test and validate' (skill 2.1.3) mentioned in the exam guide: the tabletop validates that the TEAM knows what to do and communicates well; FIS validates that the TECHNOLOGY (alarms, automations, executable runbooks) genuinely responds as designed, with guardrails to avoid accidentally causing a real incident.",
  },
  {
    tag: "AWS Security Incident Response",
    q: "Your organization wants to reduce the time between detecting a critical GuardDuty finding and starting an expert-led investigation, including access to an AWS team with real incident response experience, available 24/7. Which AWS service, generally available since December 2024, is specifically designed for this?",
    options: [
      "AWS Trusted Advisor",
      "AWS Security Incident Response (Security IR): automatically monitors and triages GuardDuty findings (via Security Hub), opens proactive cases when it confirms a genuine threat, and gives direct 24/7 access to the AWS Customer Incident Response Team (CIRT)",
      "AWS Systems Manager Incident Manager",
      "Amazon Detective",
    ],
    correct: 1,
    explain: "Security IR (GA December 2024) combines automated monitoring and triage of GuardDuty/Security Hub findings, AI-assisted investigation tools, and direct 24/7 access to the AWS CIRT. Detective helps investigate but doesn't provide access to a human AWS team; Incident Manager manages the operational process but no longer accepts new customers (retired for new sign-ups since Nov 2025); Trusted Advisor only provides best-practice recommendations.",
  },
  {
    tag: "Security IR: proactive vs. reactive cases",
    q: "After enabling AWS Security Incident Response in your organization, what distinguishes a 'reactive' case from a proactive case (prefixed '[Proactive case]')?",
    options: [
      "There's no real difference — both terms are synonyms in the console",
      "A reactive case is opened by the customer themselves when they need help (e.g. they suspect a compromise); a proactive case is opened AUTOMATICALLY by the service when its triage process — which automatically filters out more than 99% of incoming findings — determines that a GuardDuty/Security Hub finding is a true positive requiring attention",
      "Proactive cases are only generated for Windows EC2 instances",
      "Reactive cases are free and proactive cases carry an extra per-finding cost",
    ],
    correct: 1,
    explain: "Security IR analyzes the account's historical behavior baseline, the finding type, and cross-account correlation patterns to automatically filter out noise; when it concludes there's a genuine threat, it opens a proactive case (prefixed '[Proactive case]') without the customer having to spot it first. Reactive cases are the ones the customer manually creates when they suspect an incident.",
  },
  {
    tag: "Incident Manager retirement: migrate to OpsCenter",
    q: "You're designing the incident response plan for a new AWS account in 2026 and are considering AWS Systems Manager Incident Manager to manage the incident lifecycle and team escalation. What should you keep in mind?",
    options: [
      "It's the option AWS actively recommends for any new account",
      "As of November 7, 2025, Incident Manager stopped accepting new customers and AWS will not add further capabilities to the service (existing customers can keep using it); for new accounts, AWS recommends using Systems Manager OpsCenter to manage operational issues, and AWS Partner Network solutions for the automated escalation/paging capabilities Incident Manager used to cover",
      "Incident Manager has been officially renamed to Amazon Detective",
      "Incident Manager is only available in the us-east-1 region",
    ],
    correct: 1,
    explain: "AWS announced that, as of November 7, 2025, Incident Manager no longer accepts new customers and will receive no new features (existing customers are unaffected). For a new account in 2026, official AWS guidance points to OpsCenter to centralize OpsItems, and to partner solutions for the escalation/paging capabilities Incident Manager previously covered.",
  },
  {
    tag: "Detective: GenAI finding group summaries",
    q: "A junior SOC analyst receives a complex finding group in Amazon Detective with dozens of findings and related resources, and struggles to prioritize where to start. Which Detective capability quickly gives them a natural-language summary of what's happening and its possible impact?",
    options: [
      "An AWS Trusted Advisor check",
      "Finding group summary: a Detective capability powered by generative AI models hosted on Amazon Bedrock that automatically analyzes the finding group and produces a plain-language title and insights, at no extra cost when Detective is already enabled",
      "Amazon Q Business, a product unrelated to Detective",
      "GuardDuty Malware Protection",
    ],
    correct: 1,
    explain: "Finding group summary uses generative AI models on Amazon Bedrock to automatically analyze the relationships between the findings and affected resources in a finding group, producing a natural-language summary (what triggered the activity, its potential impact) that dramatically speeds up initial triage — available at no extra cost for accounts with Detective enabled.",
  },
  {
    tag: "Detective Investigations for IAM",
    q: "You want to know whether a specific IAM role has shown anomalous behavior recently (e.g. 'impossible travel', usage from IP addresses flagged as malicious, known attack tactics), and get a report listing the indicators of compromise (IoCs) and tactics/techniques (TTPs) detected. Which Amazon Detective capability would you use?",
    options: [
      "Detective investigations: uses machine learning models and threat intelligence to analyze an IAM user or role by its ARN and generate a report of anomalous behavior (impossible travel, flagged IPs, attack tactics)",
      "AWS Config Rules applied to the IAM role",
      "IAM Access Analyzer, used in isolation",
      "Cost Explorer, filtering spend associated with the IAM role",
    ],
    correct: 0,
    explain: "Detective investigations applies machine learning and threat intelligence to analyze IAM resources (by ARN) and produce a report of the indicators of compromise and TTPs associated with anomalous behavior such as 'impossible travel' or usage from flagged IPs — available from the Detective console or its public API, and complements (not replaces) Access Analyzer, which focuses on detecting unintended access from policy design rather than anomalous behavior over time.",
  },
  {
    tag: "AWS Backup: logically air-gapped vault",
    q: "Your security team wants a backup copy that not even an attacker with compromised root administrator credentials inside the workload account can delete or modify. Which AWS Backup solution meets this requirement with the strongest guarantee?",
    options: [
      "Standard EBS snapshots, with no additional configuration",
      "An AWS Backup logically air-gapped vault: it stores immutable copies in an AWS-owned account (outside your workload account), locked by default, with deletion protection that no principal — not even the owning account's root user — can bypass within the retention period",
      "A standard S3 bucket with versioning enabled, without Object Lock",
      "AWS Backup Vault Lock in governance mode",
    ],
    correct: 1,
    explain: "The logically air-gapped vault (GA August 2024) stores copies in an AWS-managed account, outside the reach of the workload account, locked and immutable by default — not even root can delete them within the retention period. Vault Lock's governance mode (option D) CAN be unlocked by users with sufficient IAM permissions, so it offers a weaker guarantee against an attacker with administrator privileges.",
  },
  {
    tag: "AWS Backup: multi-party approval",
    q: "A ransomware attack leaves the workload's AWS account completely inaccessible (root credentials were compromised and rotated by the attacker). Which recent AWS Backup capability lets you recover the backups stored in a logically air-gapped vault in this extreme scenario?",
    options: [
      "Restore directly using the compromised root credentials",
      "Multi-party approval for logically air-gapped vaults in AWS Organizations: it lets approved accounts authorize access to and restoration of backups even when the original owning account became inaccessible due to an accidental or malicious event, without depending on that account",
      "Open a support case on the Basic AWS Support plan",
      "It's not possible to recover the backups if the owning account is compromised",
    ],
    correct: 1,
    explain: "Multi-party approval (2025) addresses exactly this scenario, where the original backup-owning account becomes inaccessible: previously approved accounts within the organization can authorize and carry out restoration from the air-gapped vault without depending on the compromised account becoming operational again.",
  },
  {
    tag: "GuardDuty Malware Protection for AWS Backup",
    q: "Before restoring an EBS volume backup after a ransomware incident, you want to automatically verify that specific backup contains no malware, and ideally identify the last known 'clean' backup to minimize data loss. Which capability would you use?",
    options: [
      "Amazon Inspector, scanning the backup directly",
      "Amazon GuardDuty Malware Protection for AWS Backup (GA November 2025): automatically scans new EC2/EBS/S3 backups, allows on-demand scans of existing backups, verifies a backup is clean before restoring it, and identifies the last known clean backup using incremental scanning of only the data that changed",
      "AWS Config, with a malware conformance pack",
      "Amazon Macie, scanning the backup's metadata",
    ],
    correct: 1,
    explain: "GuardDuty Malware Protection for AWS Backup extends malware detection to EC2, EBS, and S3 backups: it automatically scans new backups, allows on-demand scans of existing ones, verifies backups are clean before a restore, and identifies the last known clean backup — using incremental scanning so it doesn't need to rescan the entire history. It works even if GuardDuty's foundational data sources aren't enabled.",
  },
  {
    tag: "AWS Elastic Disaster Recovery: recovery points and ransomware",
    q: "You use AWS Elastic Disaster Recovery (DRS) to continuously replicate your servers to AWS with a seconds-level RPO. During the investigation you discover the ransomware had been active for several hours before encrypting the data. How should you recover the service with DRS?",
    options: [
      "Always launch the recovery instance from the most recent available recovery point",
      "Launch the recovery instance choosing a recovery point that PREDATES the start of the detected malicious activity, instead of the most recent one — DRS retains multiple recovery points over time (not just the latest) precisely to enable this kind of selective recovery",
      "DRS only lets you recover the last replicated state, so you must use AWS Backup exclusively instead",
      "Turn off DRS and wait for the ransomware to deactivate on its own",
    ],
    correct: 1,
    explain: "AWS DRS keeps multiple recovery points over time, not just the most recent one, and lets you launch the recovery instance from any of them. Facing ransomware that had already been active for a while before encrypting data, using the most recent point would reintroduce the compromise; you need to pick a point that predates the start of the malicious activity identified during the investigation.",
  },
  {
    tag: "CloudTrail Lake for forensic investigation",
    q: "You need to investigate the activity of a compromised credential across several of your organization's accounts over the last several years, running complex SQL queries against API events without manually exporting and processing log files stored in S3. Which CloudTrail capability would you use?",
    options: [
      "CloudTrail Insights, exclusively",
      "CloudTrail Lake: a managed, immutable event store (events can't be modified once captured) that lets you run SQL queries directly from the console (Athena-based query engine), with configurable retention of up to 7 years",
      "VPC Flow Logs",
      "AWS Config Aggregator",
    ],
    correct: 1,
    explain: "CloudTrail Lake stores events immutably with read-only access (they can't be altered), supports running SQL queries directly from the console using an Amazon Athena-based engine, and supports configurable retention of up to 7 years — ideal for forensic investigations that need to correlate historical activity across multiple accounts without manually managing log files.",
  },
  {
    tag: "VPC Traffic Mirroring for network forensics",
    q: "While investigating a compromised EC2 instance, you want to capture the actual CONTENT of the network packets (payloads), not just metadata about who connected to whom, so you can analyze it with an out-of-band deep packet inspection (DPI) tool. What capability gives you this?",
    options: [
      "VPC Flow Logs, which already include the full payload of every packet",
      "VPC Traffic Mirroring, which copies network traffic (including payloads, not just headers) from the instance's network interface (ENI) to an out-of-band monitoring destination, without needing to install any agent on the instance",
      "AWS CloudTrail, which logs the content of TCP/IP packets",
      "AWS Config, by enabling network traffic recording",
    ],
    correct: 1,
    explain: "VPC Flow Logs only capture metadata (source/destination IPs, ports, bytes, action) — NEVER the packet content. VPC Traffic Mirroring acts as a virtual network tap: it copies the full traffic (payload included) from the instance's ENI to out-of-band security appliances, without touching the source instance — the right tool when the analysis needs to see the actual content of the communication.",
  },
  {
    tag: "Dedicated forensic account",
    q: "As part of preparation (2.1.2), your organization creates an AWS account dedicated solely to forensic analysis, separate from workload accounts. What's the correct flow for analyzing an EBS volume from a compromised instance in that forensic account?",
    options: [
      "Give the forensic account administrator credentials for the compromised account",
      "Create a snapshot of the EBS volume in the compromised account, share it with the forensic account (including permissions on the KMS key if it's encrypted), and in the forensic account copy the snapshot — re-encrypting it with a key of its own — to create a volume that's mounted READ-ONLY for analysis",
      "Migrate the entire compromised account into the forensic organization",
      "Analyze the volume directly on the compromised instance, without copying it",
    ],
    correct: 1,
    explain: "The standard multi-account forensics pattern is: snapshot in the compromised account → share the snapshot (and access to the source KMS key) with the forensic account → copy and re-encrypt the snapshot with a key owned by the forensic account → create a volume and mount it read-only, preserving the artifact's integrity during analysis. Administrator credentials for the compromised account are never granted, and analysis never happens on the original instance.",
  },
  {
    tag: "Automated Forensics Orchestrator: EKS support",
    q: "Your organization runs workloads on both EC2 instances and Amazon EKS clusters on EC2. Does AWS's 'Automated Forensics Orchestrator' solution cover both cases?",
    options: [
      "No, a completely separate, unrelated solution exists for EKS",
      "Yes: the solution is officially named 'Automated Forensics Orchestrator for Amazon EC2 and EKS', and extends the same workflow (isolation, memory/disk capture, chain of custody) to both EC2 instances and EKS clusters running on EC2 and their attached volumes, across multi-account and multi-region environments",
      "It only covers EC2 instances running Windows Server",
      "It can only be deployed in a single account and a single region",
    ],
    correct: 1,
    explain: "The AWS guidance 'Automated Forensics Orchestrator for Amazon EC2 and EKS' (built on Step Functions, Lambda, and SSM documents) orchestrates the same forensic workflow — resource isolation, memory and disk capture, chain of custody — for both EC2 instances and EKS clusters running on EC2 and their attached volumes, supporting multi-account and multi-region deployments.",
  },
  {
    tag: "Amazon Security Lake for centralized investigation",
    q: "You want to centralize and normalize CloudTrail logs, VPC Flow Logs, Route 53 Resolver DNS queries, and Security Hub findings from dozens of accounts into a single format (so they can be correlated easily), and then analyze them with Athena or third-party tools during an investigation. Which AWS service is designed for this?",
    options: [
      "AWS Config Aggregator",
      "Amazon Security Lake, which automatically centralizes and normalizes this data into the open OCSF (Open Cybersecurity Schema Framework) schema in Parquet format, making correlation and threat hunting across heterogeneous sources easier",
      "AWS Systems Manager Inventory",
      "Amazon Macie",
    ],
    correct: 1,
    explain: "Amazon Security Lake automatically ingests and normalizes CloudTrail logs, VPC Flow Logs, Route 53 Resolver query logs, and Security Hub findings (plus data from 50+ partner sources) into the OCSF schema (Parquet format), centralizing them into a data lake that can be queried with Athena, QuickSight, or other tools — specifically to simplify correlation across heterogeneous sources during an investigation.",
  },
  {
    tag: "AWS Backup Vault Lock: compliance mode",
    q: "You configure an AWS Backup Vault Lock in COMPLIANCE mode with a 3-day 'cooling-off' grace period. What does this mean for the immutability of the backups in that vault?",
    options: [
      "It's identical to governance mode: any user with sufficient IAM permissions can remove the lock at any time",
      "During the grace period you can still remove or modify the lock configuration; once that period elapses, the vault and its configuration become immutable and CANNOT be deleted or altered by any user — not even root or AWS itself — until every recovery point's retention period expires",
      "Compliance mode allows deleting individual recovery points at any time, without restriction",
      "The grace period only applies to vaults encrypted with a customer-managed KMS key",
    ],
    correct: 1,
    explain: "Vault Lock's compliance mode includes a grace period during which the lock can still be undone or modified; once that period expires, not even the account's root user or AWS can delete or alter the vault or its configuration until every recovery point's retention period ends — unlike governance mode, where users with sufficient IAM permissions can remove the lock at any time.",
  },
  {
    tag: "EventBridge + Security IR: case automation",
    q: "In addition to the automatic triage AWS Security Incident Response performs on GuardDuty/Security Hub findings, you want your own automation pipeline (e.g. a Step Functions state machine that notifies your internal SOC) to trigger as soon as a Security IR case is opened or updated. How do you achieve this?",
    options: [
      "It's not possible to integrate Security IR with your own automation flows",
      "By consuming the events AWS Security Incident Response publishes to Amazon EventBridge (case creation/update) to build your own automation flows that trigger on those events, in addition to managing cases via console or API",
      "By polling the Security IR console every 5 minutes with a custom script",
      "Only through direct phone calls from the CIRT",
    ],
    correct: 1,
    explain: "Security IR publishes case events (creation, update) to Amazon EventBridge, in addition to exposing a console and API — this lets you build your own automations (e.g. Step Functions notifying your internal SOC, opening a ticket in your ITSM tool, etc.) that react in real time to case activity, without relying on manual polling.",
  },
  {
    tag: "Route 53 Resolver query logs in forensics",
    q: "During a forensic investigation you suspect a compromised instance has been periodically resolving the domain of a command-and-control (C2) server. CloudTrail doesn't log this kind of activity because it isn't an AWS API call. Which data source should you consult (ideally already enabled beforehand) to confirm this hypothesis?",
    options: [
      "AWS Config",
      "Route 53 Resolver query logs, which record the DNS queries made by resources inside your VPC (domain queried, response type, source IP), letting you detect patterns of resolution toward known C2 domains",
      "AWS Cost Explorer",
      "IAM Access Analyzer",
    ],
    correct: 1,
    explain: "DNS resolutions aren't AWS API calls, so CloudTrail doesn't log them. Route 53 Resolver query logs do capture every DNS query issued from VPC resources (domain, record type, source IP, response), making them the right source for detecting periodic communication with C2 domains — which is why it's worth enabling them proactively as part of preparation, just like CloudTrail or VPC Flow Logs.",
  },
  {
    tag: "S3 Object Lock for exported evidence",
    q: "After exporting analyzed memory dumps and snapshots to an S3 bucket as a long-term evidence repository (for possible litigation), which combination of S3 features guarantees those objects can't be overwritten or deleted by ANYONE, even if the configured retention period has already expired but the legal proceeding is still open?",
    options: [
      "S3 versioning alone, with no other configuration",
      "S3 Object Lock in COMPLIANCE mode combined with a Legal Hold: compliance mode prevents any user (including root) from modifying or deleting the object during the retention period, and the Legal Hold adds an independent restriction with no expiration date until it's explicitly removed",
      "Server-Side Encryption with SSE-S3, with no other configuration",
      "A bucket policy that denies DeleteObject to every principal except the administrator",
    ],
    correct: 1,
    explain: "S3 Object Lock's compliance mode prevents anyone (including root) from modifying or deleting the object for as long as the configured retention period lasts. Legal Hold is an independent mechanism with no expiration date: it keeps protecting the object even after the retention period has already expired, until someone with permission explicitly removes it — exactly what's needed when litigation drags on longer than originally expected.",
  },
];
