const QUIZ_DATA = [
  {
    tag: "Runbooks & OpsCenter",
    q: "What role does AWS Systems Manager OpsCenter play in an incident response plan?",
    options: [
      "It's a backup service",
      "It centralizes 'OpsItems' (operational incidents/problems) with related context (affected resources, CloudWatch alarms, associated Automation runbooks), letting you investigate and execute remediations from a single place",
      "It replaces CloudTrail for auditing",
      "It only works with Windows EC2 instances",
    ],
    correct: 1,
    explain: "OpsCenter aggregates 'OpsItems' that represent operational incidents or problems, automatically linking in the relevant context (resources, alarms, executable Systems Manager Automation runbooks) — it's the Systems Manager piece designed to centralize investigation and execution of the response, not just passive incident logging.",
  },
  {
    tag: "Preparation: minimizing blast radius",
    q: "As part of PREPARING an account for incidents (before they happen), which practice reduces the 'blast radius' if a workload is compromised?",
    options: [
      "Using a single AWS account for everything to simplify management",
      "Segmenting workloads into separate accounts (multi-account strategy), with least-privilege IAM permissions and no long-lived credentials shared across environments",
      "Granting AdministratorAccess to every role to speed up the response when an incident occurs",
      "Disabling CloudTrail to reduce noise",
    ],
    correct: 1,
    explain: "Minimizing blast radius is a PREPARATION activity (skill 2.1.2): separating workloads into distinct accounts, applying least privilege, and avoiding shared credentials limits how far an attacker can get if they compromise a single component — much cheaper to do before the incident than during it.",
  },
  {
    tag: "Provisioning emergency access",
    q: "Why is it important to PRE-PROVISION (before the incident) the access the response team will need during an investigation?",
    options: [
      "It isn't important — the necessary access can be created on the fly during the incident with no impact",
      "Because during an active incident you don't want to depend on slow IAM approval workflows or rush-create new roles (risking over-granting permissions); an IR role with permissions already audited and tested reduces response time and errors",
      "Because IAM doesn't allow creating new roles while GuardDuty is enabled",
      "It only applies if you use IAM Identity Center",
    ],
    correct: 1,
    explain: "Skill 2.1.2 explicitly mentions 'provisioning access' as part of preparation: an IR role with broad read-only permissions plus specific containment actions (isolate an SG, create a snapshot), already tested and audited beforehand, avoids improvising permissions under pressure during the incident — exactly when it's easiest to make an over-privilege mistake.",
  },
  {
    tag: "AWS Fault Injection Service",
    q: "What is AWS Fault Injection Service (FIS) used for in the context of validating an incident response plan?",
    options: [
      "To automatically deploy security patches",
      "To run CONTROLLED chaos engineering experiments (e.g. simulating an AZ outage, network latency, terminating instances) to test whether your alarms, runbooks, and response plan actually work as expected",
      "To generate real, uncontrolled attack traffic against production",
      "It's a service exclusively for malware forensics",
    ],
    correct: 1,
    explain: "FIS lets you design and run controlled failure experiments with guardrails (automatic stop conditions if something goes outside expected bounds) to validate that detection, alerting, and response runbooks genuinely work — instead of waiting for a real incident to discover the alarm never fired.",
  },
  {
    tag: "AWS Resilience Hub",
    q: "What does AWS Resilience Hub assess?",
    options: [
      "The cost of an architecture",
      "An application's resilience against defined recovery objectives (RTO/RPO), identifying architectural gaps and recommending improvements, and it can orchestrate FIS experiments to validate it",
      "Only PCI-DSS compliance",
      "Network latency between regions",
    ],
    correct: 1,
    explain: "Resilience Hub evaluates a defined application against RTO (recovery time objective) and RPO (recovery point/acceptable data loss objective), flags where the current architecture would fall short, and can generate/run FIS experiments to validate real resilience — complementary to FIS (FIS runs the experiment, Resilience Hub defines the target it's measured against).",
  },
  {
    tag: "Automated remediation",
    q: "You want a high-severity GuardDuty finding on an EC2 instance (e.g. communication with a cryptocurrency mining IP) to trigger automatic isolation of that instance without waiting for a human to act. What architecture do you implement?",
    options: [
      "Review findings manually every morning",
      "An EventBridge rule that captures the GuardDuty finding and triggers a Lambda function or a Step Functions state machine that switches the instance's Security Group to a quarantine one (no traffic allowed except toward the forensics subnet)",
      "Manually disable the instance via the console when someone notices",
      "Configure an SCP that blocks GuardDuty",
    ],
    correct: 1,
    explain: "The standard automated remediation pattern (skill 2.1.4) is: GuardDuty finding → EventBridge rule (filters by severity/type) → Lambda/Step Functions executes the containment action (e.g. switching the Security Group to a quarantine one) — all within seconds, without waiting on human intervention for initial containment.",
  },
  {
    tag: "Automated Forensics Orchestrator",
    q: "What does the AWS 'Automated Forensics Orchestrator for Amazon EC2' solution automate?",
    options: [
      "Continuous vulnerability scanning with Inspector",
      "The entire forensics workflow for a compromised EC2 instance: network isolation (quarantine SG), EBS snapshot and memory capture, tagging for chain of custody, and notifying the IR team — without manual intervention at each step",
      "IAM credential rotation",
      "Patch deployment across the whole fleet",
    ],
    correct: 1,
    explain: "It's an AWS solution (built on Step Functions + Lambda) that automatically orchestrates the full forensic process for a compromised instance: isolating the network, capturing evidence (disk and memory snapshots), preserving chain of custody through tagging/logging, and sending notifications — cutting containment time from hours to minutes.",
  },
  {
    tag: "Network containment",
    q: "What's the fastest and safest way to isolate a compromised EC2 instance from the network WITHOUT powering it off (preserving memory state for forensic analysis)?",
    options: [
      "Terminate the instance immediately",
      "Switch its Security Group to a 'quarantine' one with no inbound/outbound rules (or only outbound toward forensics tools/subnet), keeping the instance powered on so memory can be captured before any other action",
      "Physically disconnect the network cable",
      "Change the operating system password",
    ],
    correct: 1,
    explain: "Powering off or terminating the instance destroys RAM memory (valuable volatile evidence). The correct practice is to isolate at the network level (quarantine Security Group) while keeping the instance POWERED ON, so a memory dump can be captured before proceeding with analysis and eventually replacing the instance.",
  },
  {
    tag: "Capturing forensic evidence",
    q: "When capturing forensic evidence from a compromised EC2 instance for later analysis, which TWO artifacts are most valuable to capture before any other action?",
    options: [
      "Only the account's CloudTrail logs",
      "A snapshot of the EBS volume (disk state) and a memory (RAM) capture of the instance — memory contains volatile evidence (running processes, active connections, in-memory keys) that's lost once the instance is powered off",
      "Only CloudWatch CPU metrics",
      "The account's billing history",
    ],
    correct: 1,
    explain: "The EBS snapshot preserves disk state for later analysis without altering the original instance. The memory capture (using tools like AWS's AVML or similar, via Systems Manager) preserves volatile evidence that disappears the moment the instance is powered off or restarted — both artifacts are top priority during the containment/capture phase.",
  },
  {
    tag: "SageMaker AI for forensics",
    q: "The SCS-C03 exam guide explicitly mentions 'Amazon SageMaker AI notebooks' as an example under skill 2.1.1 (incident response runbooks). What would they be used for in this context?",
    options: [
      "To train production machine learning models",
      "As an ISOLATED, programmatic analysis environment (Jupyter notebooks) for examining captured forensic artifacts (memory dumps, logs, mounted snapshots), running analysis scripts in a repeatable, documented way",
      "SageMaker has no relation to incident response — it's an error in the exam",
      "To deploy the company website during the incident",
    ],
    correct: 1,
    explain: "Although SageMaker is best known for ML, its notebooks (managed, isolated Jupyter environments) are useful as a forensic workbench: analyzing captured artifacts with Python scripts in a reproducible, documented way, in an environment separate from production infrastructure — a non-obvious use that the exam tests precisely because it's surprising.",
  },
  {
    tag: "Validating findings before acting",
    q: "You receive a medium-severity GuardDuty finding on an instance. Before executing high-impact containment actions (e.g. terminating the instance), what should you do first per skill 2.2.3?",
    options: [
      "Act immediately without verifying anything — speed is all that matters",
      "Validate the finding: confirm the actual scope and impact (which resources are really affected? is it a known false positive? is there corroboration from other sources like VPC Flow Logs or CloudTrail?) before escalating to a high-impact response",
      "Always ignore medium-severity findings",
      "Wait 48 hours before reviewing any finding",
    ],
    correct: 1,
    explain: "Skill 2.2.3 (new in SCS-C03) explicitly calls for validating findings to determine actual scope and impact before acting — avoiding both analysis-paralysis and a disproportionate response to a false positive, by correlating the finding with other sources (Flow Logs, CloudTrail, Detective) before a high-impact action like terminating a production resource.",
  },
  {
    tag: "Amazon Detective",
    q: "What does Amazon Detective solve that GuardDuty and Security Hub alone don't solve well?",
    options: [
      "Detective removes the need to have GuardDuty enabled",
      "Detective automatically builds a GRAPH of behavior and interactions between resources (IAM roles, instances, IPs) over time, making root cause analysis easier — answering 'how did the attacker get here and what else did they touch?' instead of just 'what happened in this single event?'",
      "Detective is simply a cost dashboard",
      "Detective only analyzes RDS logs",
    ],
    correct: 1,
    explain: "GuardDuty and Security Hub tell you WHAT happened (point-in-time findings). Detective automatically aggregates CloudTrail, VPC Flow Logs, and GuardDuty data into a navigable graph of relationships between entities over time, letting you trace the CHAIN of events (root cause analysis) — 'this IAM role, compromised at 3:15, then accessed these 4 resources from this new IP.'",
  },
  {
    tag: "Amazon Detective",
    q: "Does Detective REPLACE the need to have CloudTrail and VPC Flow Logs enabled?",
    options: [
      "Yes, Detective generates its own independent logs",
      "No: Detective CONSUMES those logs (CloudTrail, VPC Flow Logs, GuardDuty findings, and optionally EKS logs) to build its behavior graph — if those sources aren't active, or Detective wasn't enabled far enough in advance, the historical data available for investigation will be limited",
      "Detective only works without CloudTrail enabled",
      "Detective completely replaces Security Hub",
    ],
    correct: 1,
    explain: "Detective depends on those log sources already existing — it doesn't replace them, it CORRELATES them. It also retains up to 1 year of historical data for retrospective analysis, but only from the moment it was enabled: it's good practice to turn it on proactively (as part of preparation), not wait for the incident to enable it.",
  },
  {
    tag: "Recovery",
    q: "After containing and eradicating a compromise on an EC2 instance, what is the SAFEST practice for restoring service?",
    options: [
      "Reboot the same compromised instance and keep using it",
      "Replace the instance with a new one deployed from a known-good hardened AMI (golden image), rather than trying to 'clean' the compromised instance in-place — it's practically impossible to guarantee no trace of attacker persistence remains",
      "Restore only local user passwords",
      "Apply only pending patches to the compromised instance",
    ],
    correct: 1,
    explain: "The recovery principle after a compromise is 'don't trust what could have been tampered with': rebuilding from a known-clean image (golden AMI, IaC) is far more reliable than trying to manually clean an instance where the attacker may have left backdoors, scheduled tasks, or modified binaries that are hard to detect completely.",
  },
  {
    tag: "Restoring from backup",
    q: "During the recovery phase after a ransomware incident that encrypted production data, what verification is CRITICAL before restoring from a backup?",
    options: [
      "None — restoring the most recent available backup is always correct",
      "Confirming that the chosen backup predates the compromise (not a backup that already contains encrypted data or a persisted backdoor), using immutable backups (Vault Lock) as the trusted source",
      "Only checking the backup's size",
      "Asking the attacker which backup is safe",
    ],
    correct: 1,
    explain: "Restoring a backup taken after the compromise can reintroduce the same vulnerability or even already-encrypted data/backdoors. That's why immutable backups (AWS Backup Vault Lock, S3 Object Lock) are so valued: they guarantee at least one version predating the attack exists that couldn't be altered even by an attacker with administrator credentials.",
  },
  {
    tag: "Multi-service log correlation",
    q: "You're investigating possible lateral movement by an attacker who compromised IAM credentials. What combination of sources gives you the most complete picture of the scope (skill 2.2.2)?",
    options: [
      "Only review the month's AWS bill",
      "Correlate CloudTrail (which API actions were performed with those credentials), VPC Flow Logs (what network resources it connected to), and GuardDuty/Detective findings (patterns already flagged as anomalous) within the same time window",
      "Only look at CloudWatch CPU alarms",
      "Only Cost Explorer",
    ],
    correct: 1,
    explain: "Lateral movement leaves traces across multiple layers: CloudTrail shows WHAT the attacker did via API, VPC Flow Logs show WHAT they connected to at the network level, and GuardDuty/Detective already correlate anomalous patterns automatically. Cross-referencing all three sources within the same time window is what lets you reconstruct the real scope, instead of looking at each in isolation.",
  },
  {
    tag: "Application Recovery Controller",
    q: "What is Amazon Application Recovery Controller (ARC) used for in an incident scenario affecting an entire region?",
    options: [
      "To scan applications for vulnerabilities",
      "To orchestrate and monitor the failover of a multi-region application safely and in a controlled way (readiness checks + routing controls), avoiding error-prone manual failovers during a crisis",
      "To manage TLS certificates",
      "It's a database backup service",
    ],
    correct: 1,
    explain: "ARC continuously verifies that the backup region's infrastructure is genuinely ready to receive traffic (readiness checks) and provides safe 'routing controls' (with protection against accidental activation) to execute failover — built for exactly the moment of maximum pressure during a regional availability incident.",
  },
  {
    tag: "Chain of custody",
    q: "Why is it important to tag and document (timestamp, who, what action) each forensic artifact captured during an incident (snapshots, memory dumps, exported logs)?",
    options: [
      "Just for visual organization — it has no real impact",
      "To maintain chain of custody: if the incident ends up in a legal/regulatory action, you can demonstrate the evidence wasn't altered and who had access to it at each point in time",
      "Because AWS bills differently if it's tagged",
      "It's not relevant to the exam",
    ],
    correct: 1,
    explain: "Chain of custody is a frequent requirement in investigations that may lead to legal action or regulatory reporting: without a clear record of capture, access, and handling for each forensic artifact, the evidence can lose validity. Solutions like Automated Forensics Orchestrator automate this tagging from the very first step.",
  },
  {
    tag: "IR plan testing",
    q: "What is the difference between 'testing' an incident response plan with a tabletop exercise versus with AWS Fault Injection Service?",
    options: [
      "They're exactly the same thing",
      "A tabletop exercise is a simulation talked through verbally by the team (without touching real systems) to validate PROCESS and communication; FIS runs real, controlled TECHNICAL failures against the infrastructure to validate that automated alarms/runbooks actually trigger and work",
      "FIS can only be used once a year due to AWS limits",
      "Tabletop exercises require interrupting production, FIS doesn't",
    ],
    correct: 1,
    explain: "Both are valid, mutually complementary forms of 'test and validate' (skill 2.1.3) mentioned in the exam guide: the tabletop validates that the TEAM knows what to do and communicates well; FIS validates that the TECHNOLOGY (alarms, automations, executable runbooks) genuinely responds as designed, with guardrails to avoid accidentally causing a real incident.",
  },
];
