var QUIZ_DATA = [
  {
    tag: "AWS Organizations",
    q: "What does AWS Organizations enable that doesn't exist when managing AWS accounts completely independently?",
    options: [
      "Consolidated billing, an OU hierarchy with inheritable guardrails (SCP/RCP/Declarative), and cross-account resource sharing",
      "Consolidated billing only: security policies still have to be applied account by account, with no inheritance between any of them",
      "It merges all accounts into a single one, so keeping several separate AWS accounts is no longer necessary at all",
      "Automatic inheritance of the management account's IAM policies by the identities in every member account",
    ],
    correct: 0,
    explain: "Organizations lets you structure accounts into hierarchical OUs, apply guardrails that are automatically inherited per OU (SCPs, RCPs, Declarative Policies, AI opt-out policies), consolidate billing, and share resources (via RAM) or manage security services centrally. What it does <strong>not</strong> do is propagate IAM identity policies: each account still has its own IAM. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Control Tower",
    q: "What does AWS Control Tower automate that AWS Organizations alone does not?",
    options: [
      "Nothing extra: it is simply the AWS Organizations web console, with exactly the same capabilities under another name",
      "It deploys a full landing zone: recommended OUs, Log Archive and Audit accounts, controls, and Account Factory",
      "Only the management of consolidated billing and of the spending budgets of the organization's member accounts",
      "It applies SCPs to the management account, something that AWS Organizations on its own can never do",
    ],
    correct: 1,
    explain: "Control Tower is built <strong>on top of</strong> Organizations, automating the deployment of a complete landing zone: OU structure, Log Archive and Audit accounts already created and configured, preventive and detective controls already enabled, and Account Factory so each new account is born compliant. Neither service subjects the management account to SCPs. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Control Tower controls",
    q: "In Control Tower, what's the difference between a PREVENTIVE control and a DETECTIVE control?",
    options: [
      "Both block the action; they differ only in whether they apply to an OU or to a specific member account",
      "The detective control blocks the API call and the preventive one merely records it in CloudTrail",
      "A preventive control stops the non-compliant action, usually via an SCP that denies the API call",
      "Preventive controls apply only at the OU level and detective ones only at the member account level",
    ],
    correct: 2,
    explain: "Preventive = blocks <strong>before</strong> (e.g. an SCP that denies creating public S3 buckets). Detective = detects <strong>after</strong> (e.g. a Config Rule that flags a bucket that became public through some other path). Both types apply to OUs and accounts; Control Tower combines them, and also adds <em>proactive</em> controls that validate CloudFormation templates before deployment. <a href=\"https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AI services opt-out policies",
    q: "Your organization handles highly confidential data and wants to guarantee that NO AWS AI/ML service (such as certain model-improvement features) uses that data for training, across all accounts in the organization. Which Organizations mechanism do you apply?",
    options: [
      "An SCP that denies the actions of every AI service across the organization's accounts",
      "An RCP scoped to Amazon Bedrock, which covers the remaining AI services by inheritance",
      "Enabling GuardDuty with AI data protection across all accounts in the organization",
      "An AI services opt-out policy attached to the organization root, inherited below",
    ],
    correct: 3,
    explain: "AI services opt-out policies are a dedicated type of organization policy (alongside SCP, RCP, and Declarative Policies) built specifically to centrally and heritably control whether AWS AI services can use data from your accounts for training or improving models. Denying actions with an SCP would stop you <em>using</em> the service, which is a different goal. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_ai-opt-out.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Delegated administrator",
    q: "Why is it recommended to designate a 'delegated administrator' account for services like GuardDuty, Security Hub, or IAM Access Analyzer, instead of managing them from the management account?",
    options: [
      "It reduces daily use of the management account and lets the security team work from a dedicated account",
      "It is a technical requirement: GuardDuty and Security Hub cannot be enabled from the management account",
      "It duplicates findings in the two accounts, which adds redundancy in case one of them is ever compromised",
      "It is only available in organizations managed with Control Tower, not with plain AWS Organizations",
    ],
    correct: 0,
    explain: "Best practice is to minimize day-to-day use of the management account (compromising it would potentially compromise the ENTIRE organization). Delegating administration of security services to a dedicated account (typically 'Audit' or 'Security Tooling') lets the security team operate with organization-wide visibility without touching the management account — it is a recommendation, not a technical constraint. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_best-practices_mgmt-acct.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Root user & break-glass",
    q: "What is a 'break-glass' procedure in the context of root account management?",
    options: [
      "A procedure for permanently deleting the root user from all of the member accounts",
      "A documented, audited emergency process for using root when it is unavoidable",
      "A CloudWatch alarm that fires every time someone signs in with the root user",
      "A policy that forces the root user password to be rotated every ninety days in every account",
    ],
    correct: 1,
    explain: "Break-glass describes emergency access: root credentials are <strong>never</strong> used for daily operations (with hardware MFA stored securely, often under dual custody), and access only happens through a documented, audited, approved procedure when a genuinely exceptional need arises. The root sign-in alarm is a complementary detective control, not the procedure itself. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/root-user-best-practices.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Centralized root access management",
    q: "Which Organizations capability lets you centrally manage the root credentials of MEMBER accounts without going through the password-recovery process on each one?",
    options: [
      "IAM Identity Center, which federates the member accounts' root credentials as well",
      "AWS Config, with a rule that detects and deletes unmanaged root credentials",
      "Centralized root access management, from the organization's management account",
      "Amazon Detective, which correlates root credential usage across accounts",
    ],
    correct: 2,
    explain: "Centralized root access management lets you manage member accounts' root access from the management account, drastically reducing the risk of unmanaged, loose root credentials across dozens of accounts. IAM Identity Center federates <em>IAM</em> identities, never the root user; Config and Detective only observe, they do not remove credentials. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Infrastructure as Code at scale",
    q: "Which AWS service lets you deploy the SAME CloudFormation stack (e.g. a baseline security configuration) automatically across hundreds of accounts and regions in an organization, centrally?",
    options: [
      "AWS Config Conformance Packs, which deploy CloudFormation templates into each account",
      "AWS Service Catalog, which forces the product to be deployed in every account of the OU",
      "AWS Resource Access Manager, sharing the stack with the rest of the organization's accounts",
      "AWS CloudFormation StackSets, with automatic deployment to new accounts in an OU",
    ],
    correct: 3,
    explain: "StackSets extends CloudFormation to manage the same stack as a single unit across multiple accounts and regions, integrating with AWS Organizations to deploy <strong>automatically</strong> to accounts that join an OU in the future. Conformance packs deploy Config rules, not arbitrary infrastructure; Service Catalog offers self-service products, not enforced deployment. <a href=\"https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "IaC validation",
    q: "What's the difference between CloudFormation Guard and cfn-lint?",
    options: [
      "cfn-lint validates syntax and best practices; Guard checks it against your own rules",
      "cfn-lint is where you write your own policy rules; Guard only checks the template syntax",
      "Guard validates templates at deploy time; cfn-lint blocks the API call at runtime",
      "cfn-lint evaluates already-deployed resources; Guard replaces SCPs as a runtime guardrail",
    ],
    correct: 0,
    explain: "cfn-lint is a general linter (syntax, valid resource types, best practices). CloudFormation Guard is a <em>policy-as-code</em> engine where you write the specific business/security rules the template must satisfy. Both act on the template inside the CI/CD pipeline (shift-left), never on already-deployed resources, and they complement — not replace — runtime guardrails like SCP or Config. <a href=\"https://docs.aws.amazon.com/cfn-guard/latest/ug/what-is-guard.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Tagging strategy",
    q: "Beyond visual organization, what security/governance use case does a consistent tagging strategy (e.g. an 'environment' or 'data-classification' tag) enable?",
    options: [
      "None: tags only affect how resources are presented in the AWS console view",
      "It enables ABAC, conformance packs, and conditional SCPs driven by the resource's tag",
      "They only feed Cost Explorer and billing reports, with no effect on access",
      "They replace the IAM policies on those resources that carry a data-classification tag",
    ],
    correct: 1,
    explain: "A consistent tagging strategy is the foundation for <strong>ABAC</strong> (covered in the IAM module), for conditional conformance packs, and for responding quickly during an incident ('which resources are production?', 'who owns this?'). Tags do not replace IAM: they are an <em>input</em> to policy conditions, which are still required. <a href=\"https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Firewall Manager",
    q: "You have WAF, Security Groups, and AWS Network Firewall deployed inconsistently across dozens of accounts, and you want to apply and maintain a uniform network security policy across all of them from a single place. Which service do you use?",
    options: [
      "AWS RAM, sharing the WAF rules and the security groups with the other accounts",
      "AWS Config Rules, which detect the deviations and fix them in each member account",
      "AWS Firewall Manager, which applies and maintains network policies across all accounts",
      "Amazon Inspector, which assesses network exposure and adjusts the affected security groups",
    ],
    correct: 2,
    explain: "Firewall Manager centralizes the management of network and application security policies (WAF, Shield Advanced, Security Groups, Network Firewall, Route 53 Resolver DNS Firewall) at the organization level, applying them automatically even to <strong>new</strong> resources and accounts. Config detects and can remediate but does not distribute WAF policies; Inspector assesses vulnerabilities and reachability, it does not enforce configuration. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Sharing resources across accounts",
    q: "You want to share a VPC (subnets), a Transit Gateway, or a Firewall Manager rule among several accounts in your organization WITHOUT duplicating the resource or using peering/AssumeRole for every access. Which service do you use?",
    options: [
      "AWS Config Aggregator, which exposes the network resources of the other accounts",
      "AWS Service Catalog, which deploys an identical copy of the VPC into each consuming account",
      "VPC peering between the accounts, replicating the needed subnets in each one of them",
      "AWS Resource Access Manager (RAM), sharing the resource with the organization's accounts",
    ],
    correct: 3,
    explain: "AWS RAM lets you share specific resources (VPC subnets, Transit Gateways, License Manager configurations, Firewall Manager rules, etc.) directly with other accounts in the organization or with specific external accounts, avoiding infrastructure duplication (the <em>shared VPC</em> model). The aggregator only aggregates configuration data; Service Catalog and peering duplicate or interconnect rather than share. <a href=\"https://docs.aws.amazon.com/ram/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Service Catalog",
    q: "What problem does AWS Service Catalog solve in a multi-account governance context?",
    options: [
      "It gives teams pre-approved infrastructure templates they deploy in self-service",
      "It replaces CloudFormation as the infrastructure deployment engine across the organization",
      "It publishes the AWS price list so each approved deployment can be costed in advance",
      "It distributes only third-party AWS Marketplace software to the member accounts",
    ],
    correct: 0,
    explain: "Service Catalog lets you package already-reviewed and approved IaC templates as 'products' that teams deploy self-service, without needing broad resource-creation permissions: a balance between development velocity and centralized control. It does not replace CloudFormation — it builds on it — and it supports your own products, not just Marketplace software. <a href=\"https://docs.aws.amazon.com/servicecatalog/latest/adminguide/introduction.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Config aggregators",
    q: "What does an AWS Config Aggregator enable?",
    options: [
      "It applies the same set of Config rules in every account, like a conformance pack",
      "Consolidating the compliance state of several accounts and regions into one view",
      "It aggregates rule results inside a single account, one region at a time",
      "It replaces Security Hub as the central multi-account security findings console",
    ],
    correct: 1,
    explain: "A Config Aggregator collects configuration and compliance data from multiple source accounts (and regions) into an aggregator account, giving a consolidated view of which resources are NON_COMPLIANT across the organization. <strong>Aggregating is not deploying</strong>: applying the same rules everywhere needs organization-level rules or conformance packs. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Audit Manager vs AWS Artifact",
    q: "What's the difference between AWS Audit Manager and AWS Artifact?",
    options: [
      "They are the same service: Artifact is the console and Audit Manager its equivalent API",
      "Artifact collects evidence from your account and Audit Manager issues AWS certifications",
      "Audit Manager collects evidence from your environment; Artifact delivers AWS's reports",
      "Both can only be used from the management account and cover us-east-1 exclusively",
    ],
    correct: 2,
    explain: "Audit Manager automates continuous collection of <strong>evidence from your own environment</strong> (config, logs, policies) organized against the framework you choose (PCI-DSS, HIPAA…), for your own audits. AWS Artifact is the library of <strong>AWS's own reports and certifications</strong> as a provider (SOC, ISO, PCI) and where agreements like the BAA are accepted. The option that swaps the two roles is the classic trap. <a href=\"https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Well-Architected Tool",
    q: "What is the AWS Well-Architected Tool used for in a security governance context?",
    options: [
      "Automatically deploying the infrastructure that remediates the risks it detects",
      "Assessing machine learning workloads exclusively, against the dedicated ML lens",
      "Calculating the exact monthly cost of a workload before it is deployed",
      "Assessing a workload against the six pillars' best practices and ranking risks",
    ],
    correct: 3,
    explain: "The Well-Architected Tool guides a structured review (typically a workshop with the team) of a workload against AWS best practices across the six pillars — including Security — flagging high/medium risks and generating a prioritized remediation plan. It is an <em>assessment</em> tool: it neither deploys nor remediates anything, and the ML lens is only one lens among many. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SCP vs RCP vs Declarative vs AI opt-out (recap)",
    q: "Recap of the 4 types of organization policy: which one is specifically built for AI/ML services' use of data, rather than permissions or configuration?",
    options: [
      "AI services opt-out policy: controls AI services' use of your data",
      "Resource Control Policy (RCP): caps access to the data in your resources",
      "Service Control Policy (SCP): caps the maximum permissions of identities",
      "Declarative Policy: enforces a durable configuration state on EC2 and VPC",
    ],
    correct: 0,
    explain: "SCP = ceiling on <em>identity</em> permissions. RCP = ceiling on access to your <em>resources</em>, including external principals. Declarative Policy = enforces a <em>configuration state</em>. AI services opt-out policy = the only type dedicated to controlling whether AWS AI services can use your data to improve their models. All four are organization policies, but each solves a different problem. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Compliance notifications",
    q: "Besides automatically remediating a NON_COMPLIANT resource detected by Config, what mechanism is typically used to notify the responsible team (skill 6.3.1)?",
    options: [
      "Config emits no events: you must query the compliance state through the API daily",
      "EventBridge captures the compliance change and routes it to SNS or an SSM runbook",
      "Only by manually reviewing the Config dashboard in each account and each region",
      "Only by opening an AWS Support case from the organization's audit account",
    ],
    correct: 1,
    explain: "The standard pattern is: Config detects the compliance change &rarr; EventBridge captures the event &rarr; it is routed to SNS to notify humans, and/or triggers a Systems Manager Automation runbook to remediate. It is the same <strong>EventBridge-as-central-bus</strong> pattern that recurs in detection (Domain 1) and incident response (Domain 2). <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/monitor-config-with-cloudwatchevents.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Existing vs new landing zone",
    q: "Can Control Tower be applied to an AWS organization that ALREADY EXISTS, with dozens of accounts already in use, or does it only work for brand-new organizations?",
    options: [
      "It only works for brand-new organizations: it requires creating the organization itself",
      "It requires migrating every existing account first to the region where the landing zone runs",
      "It extends the landing zone over an existing organization, enrolling accounts gradually",
      "It only accepts accounts with no deployed resources: those with workloads must be recreated",
    ],
    correct: 2,
    explain: "Although Control Tower was originally designed with new implementations in mind, it explicitly supports the <strong>existing landing zone</strong> scenario: it can be deployed over an organization already in use and existing accounts can be <em>enrolled</em> into the OU and control structure incrementally, with no big-bang migration and no need to recreate accounts. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Declarative Policies: VPC Block Public Access",
    q: "The security team wants to guarantee that NO VPC in the organization, present or future, allows inbound traffic from the internet through an internet gateway, without auditing route tables or NACLs account by account, and with the ability to roll the change back if something breaks. Which mechanism is the best fit?",
    options: [
      "Manually editing the NACLs and route tables of every existing VPC in every account",
      "An SCP that denies ec2:CreateInternetGateway across all accounts in the organization",
      "A detective Config Rule that flags exposed VPCs and notifies the responsible team",
      "A Declarative Policy enabling VPC Block Public Access at the OU or org level",
    ],
    correct: 3,
    explain: "Declarative Policies cover EC2/VPC/EBS at scale by enforcing a configuration <strong>state</strong>, not just blocking API calls the way an SCP does. VPC Block Public Access blocks public ingress via internet gateway centrally, non-destructively, and reversibly, and applies to future VPCs too. An SCP on ec2:CreateInternetGateway does nothing about the internet gateways that <em>already exist</em>. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Declarative Policies: allowed AMI providers",
    q: "After research on the 'whoAMI' attack was published (where an attacker publishes a public AMI with a name matching the pattern that misconfigured code searches for), your organization wants to centrally restrict which AMI owners can be used to launch EC2 instances across ALL accounts, and also hide any non-compliant AMI from the console and CLI. Which solution do you apply?",
    options: [
      "An EC2 'Allowed AMIs' Declarative Policy applied across the whole organization",
      "An SCP with a condition on ec2:Owner replicated in every single account's policy",
      "A detective Config Rule that flags the already-launched instances as non-compliant",
      "An IAM permission boundary on every role able to launch EC2 instances",
    ],
    correct: 0,
    explain: "'Allowed AMIs' is one of the EC2 configurations supported by Declarative Policies: it defines which AMI providers are valid for the whole organization, blocking launches and <strong>hiding from console and CLI</strong> any AMI from a non-approved provider. It is preventive and inherited; the Config Rule arrives too late and permission boundaries must be maintained role by role. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Tag Policies: IaC enforcement",
    q: "You find that several teams create resources via CloudFormation, Terraform, and Pulumi without including the mandatory 'cost-center' tag, and you want to block (or at least warn on) those deployments BEFORE the resource is created, without building a separate validation for each IaC tool. Which Organizations capability do you use?",
    options: [
      "CloudFormation Guard, wired by hand into each team's pipeline and each IaC tool",
      "A Tag Policy with required keys and the validation hook in Warn or Fail mode",
      "An SCP that denies the CreateTags action when no value is supplied for the tag",
      "A 'required-tags' Config Rule, which evaluates the resource once it already exists",
    ],
    correct: 1,
    explain: "Organizations Tag Policies let you define required tag keys and enforce them directly on infrastructure-as-code deployments (CloudFormation, Terraform, and Pulumi) via a validation hook in <strong>Warn</strong> mode (warns but allows) or <strong>Fail</strong> mode (blocks the deployment): shift-left tagging governance, before the resource is created, with no per-tool integration to build. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_tag-policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Tag Policies vs RCP",
    q: "You want to prevent any identity, including one with broad permissions, from DELETING or MODIFYING the 'data-classification' tag on a resource once it has been assigned — not just standardize which values are valid for that tag. Which mechanism specifically addresses this requirement?",
    options: [
      "A Tag Policy, which besides standardizing values stops any of the defined tags being deleted",
      "A Declarative Policy for tagging applied to the OU that contains those resources",
      "An RCP or SCP denying tag:TagResource and tag:UntagResource except to authorized principals",
      "A Config Aggregator with real-time alerting on any change made to that tag key",
    ],
    correct: 2,
    explain: "Tag Policies <strong>standardize and report</strong> which keys and values are valid (and can even block IaC deployments missing required tags), but they are not a permissions-control mechanism over the tag/untag action itself. To stop someone removing or changing a specific tag you need a permissions policy (RCP or SCP) that denies those actions: complementary controls, not interchangeable ones. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Resource Control Policies: supported-service scope",
    q: "Your team wants to use an RCP to restrict external access to Amazon DynamoDB tables across all accounts, the same way they already do for S3 buckets. What should you verify first before assuming it will work the same way?",
    options: [
      "Nothing: RCPs cover every action of every AWS service, exactly like SCPs do",
      "That Control Tower is deployed, since RCPs depend on its landing zone",
      "That the management account enforces hardware MFA, required to enable RCPs",
      "That DynamoDB is among the services RCPs support at that point in time",
    ],
    correct: 3,
    explain: "Unlike SCPs (which act as a ceiling on permissions for any IAM action), <strong>RCPs only cover a specific set of services</strong> that AWS has progressively expanded since their November 2024 launch. Before designing a data-perimeter control with an RCP over a given service, confirm that service is already supported — otherwise the control simply has no effect. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Config at the organization level",
    q: "Until recently, deploying a new Config rule centrally across the whole organization required packaging it inside a conformance pack. Which recent AWS Config capability removes that requirement?",
    options: [
      "Config deploys individual rules at the organization level, with no packaging",
      "It is only achievable by replicating each rule with CloudFormation StackSets",
      "The Config Aggregator deploys the new rules into the source accounts automatically",
      "It is not possible: organization-level deployment still requires a conformance pack",
    ],
    correct: 0,
    explain: "AWS Config expanded organization-level management to include not just entire conformance packs but also <strong>individual rules</strong>, simplifying multi-account compliance governance when you only need a single rule. It complements (doesn't replace) conformance packs for large sets of related rules, and does not depend on the aggregator, which only consolidates results. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Control Tower Landing Zone 4.0",
    q: "After migrating to Control Tower landing zone version 4.0, what relevant architectural change happens to how AWS Config compliance data used to be aggregated across accounts?",
    options: [
      "AWS Config disappears from the landing zone and Security Hub takes over compliance",
      "The two previous aggregators are replaced by a Service-Linked Config Aggregator (SLCA)",
      "Central aggregation goes away and compliance has to be queried account by account",
      "An extra Config Aggregator has to be deployed by hand after migrating the landing zone",
    ],
    correct: 1,
    explain: "Landing zone 4.0 introduces optional service integrations and <strong>dedicated per-service resources</strong> (Config and CloudTrail no longer share S3 buckets or SNS topics), and migrates compliance aggregation to a Service-Linked Config Aggregator deployed in the Config integration account, retiring the organization aggregator (in management) and the account aggregator (in Audit) used before. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Control Tower: control library",
    q: "A compliance lead asks how Control Tower's preconfigured control coverage has evolved, in order to map it against their regulatory requirements. Which statement about that control library is correct?",
    options: [
      "It has stayed fixed since the service launched, with no new controls added since then",
      "Only preventive controls remain: the detective ones were retired from the library in 2025",
      "It has grown by hundreds of Config-based controls, groupable into conformance packs",
      "It is capped at fifty controls per organization by a restriction of the service itself",
    ],
    correct: 2,
    explain: "Control Tower has continued substantially expanding its catalog of Config-based controls (hundreds of new controls added in 2025), enableable at the account or organization level and groupable via conformance packs. An organization that assessed its coverage a year ago is likely missing newer controls relevant to its regulatory framework. <a href=\"https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Control Tower: automatic SCP drift resolution",
    q: "An engineer modifies, outside the Control Tower console, an SCP managed by the service: it ends up attached to a different OU than intended. This used to be flagged as governance 'drift' requiring intervention. Which recent Control Tower improvement affects this scenario?",
    options: [
      "Control Tower now blocks any manual change to the SCPs that it manages, with no exception",
      "Only a custom Config Aggregator can detect that kind of change to a managed SCP",
      "The concept of governance drift has disappeared entirely from the Control Tower service",
      "Control Tower resolves certain SCP drifts itself, with no landing zone re-registration",
    ],
    correct: 3,
    explain: "In 2025 Control Tower expanded how it handles drift on managed SCPs: certain governance changes (a control's SCP ending up attached to a different OU, or to a member account, through an action outside the console) are now <strong>resolved automatically by the service itself</strong> instead of being left as persistent drift that blocks landing-zone operations until manually remediated. Drift still exists as a concept. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/drift.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Centralized Root Access Management: task-scoped sessions",
    q: "You need to restore access to an S3 bucket whose policy was misconfigured in a member account — a task that traditionally required that account's root credentials. With Centralized Root Access Management enabled, how is this done without recovering the member account's root password?",
    options: [
      "You invoke a task-scoped root session on that account, with no credentials",
      "You start the password recovery flow tied to that account's root email address",
      "It is only possible if the member account uses IAM Identity Center as identity source",
      "A paid AWS Support case has to be opened for every restoration of this kind",
    ],
    correct: 0,
    explain: "Centralized Root Access Management (November 2024) lets you invoke, from the management account or the delegated admin, a limited set of <strong>task-scoped</strong> root actions (<code>sts:AssumeRoot</code>) on member accounts — such as restoring access to an S3 bucket or an SQS queue — without long-lived root credentials; new accounts can also be created without usable root credentials. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Audit Manager: maintenance mode",
    q: "You're designing the continuous compliance-evidence collection strategy for an organization that will onboard NEW accounts starting mid-2026. A colleague suggests using AWS Audit Manager on those new accounts. What should you keep in mind?",
    options: [
      "It is still the recommended option, with no limitations for onboarding new accounts",
      "Audit Manager is in maintenance mode and accepts no new accounts or regions",
      "Audit Manager has been retired and has stopped working in existing accounts too",
      "Audit Manager becomes free and unlimited across all accounts in the organization",
    ],
    correct: 1,
    explain: "AWS announced that Audit Manager is moving to <strong>maintenance mode</strong>: as of April 30, 2026 it can no longer be set up in new accounts or regions. Customers who already had it configured before that date keep using it normally (including creating new assessments) in that specific account/region, but without new features or support for new frameworks or services. <a href=\"https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Service Catalog AppRegistry: maintenance mode",
    q: "You were planning to use AWS Service Catalog AppRegistry to logically group resources by application and apply tags consistently in accounts that will be created after July 2026. What should you know about this?",
    options: [
      "AppRegistry has just expanded its availability to more regions than ever before",
      "AppRegistry replaces AWS Config for per-application inventory of resources",
      "AppRegistry enters maintenance mode; use Resource Groups or Resource Explorer",
      "All of AWS Service Catalog, not just AppRegistry, stops working on that date",
    ],
    correct: 2,
    explain: "AWS announced that AppRegistry (the Service Catalog component for grouping resources by application) is moving to <strong>maintenance mode</strong>, closed to new customers as of July 30, 2026, with no new features or regions. Existing customers keep the service, and for new grouping and tagging needs AWS recommends Resource Groups and Resource Explorer, at no additional cost. <a href=\"https://docs.aws.amazon.com/servicecatalog/latest/adminguide/introduction.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Firewall Manager & Shield Advanced: Anti-DDoS managed rule group",
    q: "You manage AWS Firewall Manager policies that include Shield Advanced protection for workloads behind ALB and CloudFront. AWS announced a change in how Shield Advanced mitigates application-layer (L7) attacks. What does that change involve?",
    options: [
      "The change affects only AWS Network Firewall, not Shield Advanced or Firewall Manager",
      "Shield Advanced stops mitigating application-layer attacks and covers only layers 3 and 4",
      "AWS WAF is retired and Shield Advanced fully takes over HTTP request filtering",
      "Shield Advanced relies on the AWS WAF 'Anti-DDoS' managed rule group for layer 7",
    ],
    correct: 3,
    explain: "AWS announced that Shield Advanced adopts the AWS WAF <strong>Anti-DDoS</strong> managed rule group to strengthen mitigation of application-layer DDoS attacks (HTTP request floods), consistent with the model where Firewall Manager already centrally distributes and maintains WAF policies — managed rule groups included — alongside Shield Advanced across the organization. <a href=\"https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Control Tower: digital sovereignty (European Sovereign Cloud)",
    q: "A European company with strict data-residency requirements is evaluating deploying its landing zone in the new AWS European Sovereign Cloud (general availability announced January 2026, physically independent from other AWS regions). What's correct about Control Tower's support in this context?",
    options: [
      "Control Tower is available there and includes data-residency controls",
      "Control Tower is not available there: the landing zone must be run by hand",
      "The European Sovereign Cloud replicates its metadata into AWS standard regions",
      "It is reachable only over Direct Connect, with no Organizations or Control Tower",
    ],
    correct: 0,
    explain: "The AWS European Sovereign Cloud is an independent cloud, operated exclusively by EU residents and physically separate from other AWS regions. Control Tower supports this environment with data-residency governance (a dedicated digital sovereignty grouping) and options such as an external <em>key store</em> for KMS, in line with AWS's Digital Sovereignty Pledge. <a href=\"https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Well-Architected Tool: Review Templates",
    q: "The platform team reviews dozens of workloads with very similar architecture patterns (and therefore the same answers to most Security-pillar best practices) and wants to avoid manually re-filling the same answers on every new review. Which Well-Architected Tool capability solves this?",
    options: [
      "It is not possible: every review must be completed manually from scratch in the tool",
      "Review Templates: templates with pre-filled answers for new workloads",
      "Exporting the answers to a spreadsheet and copying them into each new review",
      "Custom lenses, which are available only for the cost optimization pillar",
    ],
    correct: 1,
    explain: "Review Templates let you pre-define common answers to Well-Architected Framework best practices — including the Security pillar — or to a custom lens, and apply them as a starting point when creating new workloads with repeating patterns. It cuts duplicated effort and standardizes the evaluation criteria across teams. Custom lenses, incidentally, are not limited to any one pillar. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Declarative Policies vs SCP: durability",
    q: "A colleague asks why the security team prefers a Declarative Policy over an SCP to enforce IMDSv2 on all EC2 instances across the organization, given that both are organization policies inherited by OU. What's the main reason?",
    options: [
      "SCPs can only be attached to individual accounts of the organization, never to an OU",
      "Declarative Policies have a lower per-account cost than SCPs across the organization",
      "A Declarative Policy enforces a durable configuration state even as APIs change",
      "There is no practical difference: both of them deny exactly the same EC2 API calls",
    ],
    correct: 2,
    explain: "Declarative Policies are designed for durable, 'set and forget' service configuration: once the desired state is defined (e.g. mandatory IMDSv2), it is automatically maintained even as the service adds new APIs or related features. An SCP operates on <strong>specific API permissions</strong>: if a new path to the undesired outcome appears, the SCP must be updated by hand. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_declarative_policies.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Config conformance packs: regional expansion",
    q: "Your organization starts running workloads in relatively new AWS regions, such as Asia Pacific (Malaysia) or Asia Pacific (New Zealand), and you plan to deploy Config conformance packs at the organization level across all accounts and regions. What should you verify before assuming it will work the same as in older regions like us-east-1?",
    options: [
      "That Control Tower is deployed, the only requirement for conformance packs",
      "Nothing: conformance packs have been available in every region since launch",
      "That the region matches the management account's, the only one where rules run",
      "That the target region already supports conformance packs and org management",
    ],
    correct: 3,
    explain: "AWS has been incrementally expanding the regional availability of both Config conformance packs and their organization-level management, adding regions such as Asia Pacific (Malaysia), (New Zealand), (Thailand), (Taipei), and Mexico (Central) in 2025. A realistic exam scenario is <strong>verifying regional availability</strong> of a governance feature before assuming uniform global coverage. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "SCP scope",
    q: "You are rolling out Service Control Policies across an organization. Which TWO statements are correct?",
    options: [
      "An SCP grants nothing: it only caps the maximum permissions identities can have",
      "An SCP can grant a user the permissions that their identity policy does not give them",
      "SCPs do not apply to the identities in the organization's management account",
      "SCPs also reach the external principals that access the account's resources",
    ],
    correct: [0, 2],
    explain: "Two exam classics. An SCP is a <strong>guardrail</strong>, never a grant: effective permission is the intersection of the SCP and the identity policies. And the <strong>management account is not subject to SCPs</strong>, which is why AWS advises against running workloads in it. The last option describes what <strong>RCPs</strong> do, since they do reach external identities: precisely the gap SCPs leave open. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Control Tower controls",
    q: "Control Tower offers different control types across the landing zone. Which TWO descriptions are correct?",
    options: [
      "Detective controls block the action before it ever happens, just like the preventive ones",
      "Preventive controls are implemented with SCPs and stop the action from executing",
      "Preventive controls can only be applied to the audit account of the landing zone",
      "Detective controls are implemented with Config rules and flag drift after the fact",
    ],
    correct: [1, 3],
    explain: "The <strong>preventive vs detective</strong> distinction is the most-tested one: preventive controls (SCP) <strong>stop</strong> the action, detective controls (Config) <strong>find</strong> what already happened — which is why the third option contradicts itself. Preventive controls apply to OUs and accounts, not only the audit account. Control Tower also adds <em>proactive</em> controls, which validate CloudFormation templates before deployment. <a href=\"https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Multi-account compliance with Config",
    q: "You need a single view of AWS Config rule compliance across 90 accounts and 4 Regions. Which TWO enable this?",
    options: [
      "An AWS Config aggregator collecting data from all accounts and Regions",
      "An S3 bucket in each account from which to download reports manually every week",
      "Enabling Config only in the management account, which inherits the others' state",
      "Organization-level conformance packs applying the same rule set everywhere",
    ],
    correct: [0, 3],
    explain: "The <strong>aggregator</strong> delivers the consolidated view and organization-level <strong>conformance packs</strong> ensure every account evaluates the same rules. Manual downloads don't scale to 90 accounts and are always stale. And Config is a <strong>regional, per-account</strong> service: the management account inherits nothing, it must be enabled where the resources are. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Protecting the root user",
    q: "You are hardening the root user across every account in the organization. Which TWO does AWS recommend?",
    options: [
      "Create a root access key in each account and store it in Secrets Manager",
      "Enable MFA on the root user and delete its access keys if any exist",
      "Use centralized root access management to remove those root credentials",
      "Use root for daily administrative work, since no SCP can ever block it",
    ],
    correct: [1, 2],
    explain: "The basics are <strong>MFA and no access keys</strong> on root, and <strong>centralized root access management</strong> lets you remove those credentials from member accounts entirely, leaving root-only tasks to scoped sessions via <code>sts:AssumeRoot</code>. Creating root access keys is the exact opposite of the guidance. And the fact that SCPs don't restrict the management account's root is a reason <strong>not</strong> to use it daily, not a reason to use it. <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/root-user-best-practices.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Delegated administrator per service",
    q: "You are moving administration of GuardDuty, Security Hub and Macie out of the organization's management account. What is true of the delegated administrator?",
    options: [
      "It must be the management account itself in order to see all member accounts",
      "It is designated per service, and can be a different account for each one",
      "Only one delegated account can be designated for the whole organization",
      "It automatically inherits administrator permissions over the other accounts",
    ],
    correct: 1,
    explain: "Delegation is <b>per service</b>: you register one account as delegated administrator for GuardDuty, another — or the same one — for Security Hub, and so on for every service integrated with Organizations. Concentrating them in a security account is the common choice, but it is a choice, not a requirement. The management account is precisely the one worth keeping out, to limit what a compromise of it would reach. And being delegated administrator of a security service grants no permission over member account resources. <a href=\"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_integrate_services.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["governance"] = QUIZ_DATA;
