const QUIZ_DATA = [
  {
    tag: "AWS Organizations",
    q: "What does AWS Organizations enable that doesn't exist when managing AWS accounts completely independently?",
    options: [
      "Consolidated billing, an OU hierarchy for applying guardrails (SCP/RCP/Declarative Policies) by account group, and resource sharing between accounts in the organization",
      "Only consolidated billing, with no other benefit",
      "Organizations replaces the need to have multiple AWS accounts",
      "It only works with a maximum of 5 accounts",
    ],
    correct: 0,
    explain: "Organizations lets you structure accounts into hierarchical OUs (Organizational Units), apply guardrails that are automatically inherited per OU (SCPs, RCPs, Declarative Policies, AI opt-out policies), consolidate billing, and share resources (via RAM) or manage security services centrally across all accounts.",
  },
  {
    tag: "AWS Control Tower",
    q: "What does AWS Control Tower automate that AWS Organizations alone does not?",
    options: [
      "Nothing extra, they're the same service with different names",
      "It deploys a complete 'landing zone' with a recommended OU structure, base accounts (Log Archive, Audit/Security Tooling) already configured, preconfigured preventive AND detective guardrails, and an Account Factory to provision new accounts already compliant from minute one",
      "Control Tower only manages billing",
      "It can only be used on completely new accounts, never on existing organizations",
    ],
    correct: 1,
    explain: "Control Tower is built ON TOP of Organizations, automating the deployment of a complete landing zone: OU structure, Log Archive and Audit accounts already created and configured, preventive and detective guardrails (controls) already enabled, and Account Factory so each new account is born already compliant with policy — it supports both new environments and 'existing landing zone' scenarios (extending an Organizations setup already in use).",
  },
  {
    tag: "Control Tower controls",
    q: "In Control Tower, what's the difference between a PREVENTIVE control and a DETECTIVE control?",
    options: [
      "They're exact synonyms",
      "A preventive control PREVENTS the non-compliant action from happening (typically implemented as an SCP that blocks the API call); a detective control IDENTIFIES resources that are already in a non-compliant state (implemented as a Config Rule) so they can be remediated afterward",
      "Detective controls are always stricter than preventive ones",
      "Only preventive controls can be applied at the OU level",
    ],
    correct: 1,
    explain: "Preventive = blocks BEFORE (e.g. an SCP that denies creating public S3 buckets). Detective = detects AFTER (e.g. a Config Rule that flags as NON_COMPLIANT a bucket that became public through some other path). Control Tower combines both types to cover prevention as well as the cases where prevention wasn't enough.",
  },
  {
    tag: "AI services opt-out policies",
    q: "Your organization handles highly confidential data and wants to guarantee that NO AWS AI/ML service (such as certain model-improvement features) uses that data for training, across all accounts in the organization. Which Organizations mechanism do you apply?",
    options: [
      "A generic SCP that blocks all AI services",
      "An AI services opt-out policy: a specific type of organization policy for centrally controlling whether AWS AI services can use content from your accounts to improve their models",
      "Enable GuardDuty in strict mode",
      "An RCP scoped to the Bedrock service only",
    ],
    correct: 1,
    explain: "AI services opt-out policies are a dedicated type of organization policy (alongside SCP, RCP, and Declarative Policies) built specifically to centrally and heritably control whether AWS AI services can use data from your accounts for training/improving models — more precise and maintainable than trying to replicate that control with a generic SCP.",
  },
  {
    tag: "Delegated administrator",
    q: "Why is it recommended to designate a 'delegated administrator' account for services like GuardDuty, Security Hub, or IAM Access Analyzer, instead of managing them from the management account?",
    options: [
      "It's technically mandatory, there's no alternative",
      "It reduces operational use of the management account (which should be reserved almost exclusively for Organizations tasks themselves) and follows the principle of least privilege: the security team operates from a dedicated account, without needing the most sensitive credentials in the entire organization",
      "The management account can never have GuardDuty enabled",
      "Delegated administrator only applies to Control Tower",
    ],
    correct: 1,
    explain: "Best practice is to minimize day-to-day use of the management account (compromising it would potentially compromise the ENTIRE organization). Delegating administration of security services to a dedicated account (typically 'Audit' or 'Security Tooling') lets the security team operate with organization-wide visibility without touching the management account day to day.",
  },
  {
    tag: "Root user & break-glass",
    q: "What is a 'break-glass' procedure in the context of root account management?",
    options: [
      "A procedure to permanently delete the root account",
      "A documented and controlled EMERGENCY process for accessing the root account (credentials normally stored securely and never used) when strictly necessary, with physical MFA and reinforced approval/auditing",
      "A CloudWatch alarm that triggers when someone logs in as root",
      "It only applies to the management account, never to member accounts",
    ],
    correct: 1,
    explain: "Break-glass describes emergency access: root credentials are normally NEVER used for daily operations (with hardware MFA stored securely, often under dual custody), and access only happens through a documented, audited procedure with approval when a genuinely exceptional need arises (e.g. regaining control of a compromised account).",
  },
  {
    tag: "Centralized root access management",
    q: "Which Organizations capability lets you centrally manage the root credentials of MEMBER accounts without going through the password-recovery process on each one?",
    options: [
      "IAM Identity Center alone",
      "Centralized root access management: it lets the management account centrally invoke a limited set of privileged root actions in member accounts, effectively removing the need for usable root credentials in those accounts",
      "AWS Config",
      "Amazon Detective",
    ],
    correct: 1,
    explain: "This capability (part of skill 6.1.5) lets you manage member accounts' root access from the management account centrally, drastically reducing the risk of unmanaged, loose root credentials across dozens of accounts — combinable with mandatory MFA at the organization level.",
  },
  {
    tag: "Infrastructure as Code at scale",
    q: "Which AWS service lets you deploy the SAME CloudFormation stack (e.g. a baseline security configuration) automatically across hundreds of accounts and regions in an organization, centrally?",
    options: [
      "AWS Config Conformance Packs only",
      "AWS CloudFormation StackSets: define the stack once and deploy/update/delete it centrally across all target accounts and regions (even automatically in NEW accounts if integrated with Organizations)",
      "Amazon Q Developer",
      "AWS Service Catalog exclusively",
    ],
    correct: 1,
    explain: "StackSets extends CloudFormation to manage the same stack as a single unit across multiple accounts/regions, with the option to integrate with AWS Organizations to deploy AUTOMATICALLY to accounts that join an OU in the future — key for skill 6.2.1 on consistent deployment at scale.",
  },
  {
    tag: "IaC validation",
    q: "What's the difference between CloudFormation Guard and cfn-lint?",
    options: [
      "They're exactly the same thing with different names",
      "cfn-lint validates SYNTAX and general best practices of a CloudFormation template; CloudFormation Guard evaluates the template against CUSTOM POLICY RULES that you define (e.g. 'every S3 bucket must have encryption'), letting you block non-compliant deployments in the pipeline before applying them",
      "CloudFormation Guard only works with Terraform",
      "cfn-lint replaces the need for SCPs",
    ],
    correct: 1,
    explain: "cfn-lint is a general linter (syntax, valid resource types, best practices). CloudFormation Guard is a policy-as-code engine where YOU write the specific business/security rules the template must satisfy — both integrate into the CI/CD pipeline to catch problems before deployment (shift-left), complementing (not replacing) runtime guardrails like SCP/Config.",
  },
  {
    tag: "Tagging strategy",
    q: "Beyond visual organization, what security/governance use case does a consistent tagging strategy (e.g. an 'environment' or 'data-classification' tag) enable?",
    options: [
      "None, tags are purely cosmetic",
      "It enables ABAC (attribute-based access control) policies, Conformance Packs, and conditional SCPs that apply automatically based on a resource's tag (e.g. 'encryption mandatory only on resources with data-classification=confidential'), and makes it easier to attribute cost/ownership during an investigation",
      "Tags only matter for Cost Explorer, unrelated to security",
      "Tags replace the need to use IAM",
    ],
    correct: 1,
    explain: "A consistent tagging strategy is the foundation for ABAC (covered in the IAM module), conditional conformance packs, and the ability to respond quickly during an incident ('which resources are production?', 'who owns this resource?') — skill 6.2.2 treats it as a governance pillar, not just FinOps.",
  },
  {
    tag: "AWS Firewall Manager",
    q: "You have WAF, Security Groups, and AWS Network Firewall deployed inconsistently across dozens of accounts, and you want to apply and maintain a uniform network security policy across all of them from a single place. Which service do you use?",
    options: [
      "AWS Firewall Manager: automatically applies and maintains WAF, Shield Advanced, Security Groups, and Network Firewall policies across all accounts and resources in the organization, even ones created in the future",
      "AWS Config Rules only",
      "AWS RAM",
      "Amazon Inspector",
    ],
    correct: 0,
    explain: "Firewall Manager centralizes the management of network and application security policies (WAF, Shield Advanced, Security Groups, Network Firewall, Route 53 Resolver DNS Firewall) at the organization level, applying them automatically even to NEW resources and accounts — exactly skill 6.2.3, 'deploy and enforce policies from a central source.'",
  },
  {
    tag: "Sharing resources across accounts",
    q: "You want to share a VPC (subnets), a Transit Gateway, or a Firewall Manager rule among several accounts in your organization WITHOUT duplicating the resource or using peering/AssumeRole for every access. Which service do you use?",
    options: [
      "AWS Resource Access Manager (RAM): shares AWS resources directly between accounts in the organization (or specific external accounts), natively and without duplicating the resource",
      "AWS Service Catalog",
      "Amazon Macie",
      "AWS Config Aggregator",
    ],
    correct: 0,
    explain: "AWS RAM lets you share specific resources (VPC subnets, Transit Gateways, License Manager configurations, Firewall Manager rules, etc.) directly with other accounts in the Organization or with specific external accounts, avoiding infrastructure duplication and simplifying the shared-network model (shared VPC).",
  },
  {
    tag: "AWS Service Catalog",
    q: "What problem does AWS Service Catalog solve in a multi-account governance context?",
    options: [
      "It lets teams self-serve infrastructure templates PRE-APPROVED by the security/platform team (e.g. 'standard VPC', 'compliant S3 bucket'), preventing them from deploying resources outside the standards without completely blocking their autonomy",
      "It completely replaces CloudFormation",
      "It's a catalog of AWS service pricing",
      "It only works for third-party Marketplace software",
    ],
    correct: 0,
    explain: "Service Catalog lets you package already-reviewed and approved IaC templates as 'products' that teams can deploy self-service, without needing broad resource-creation permissions — a balance between development team velocity and centralized control from the platform/security team.",
  },
  {
    tag: "AWS Config aggregators",
    q: "What does an AWS Config Aggregator enable?",
    options: [
      "Consolidating the compliance state of Config rules from MULTIPLE accounts and regions into a single view, without having to log into each account individually",
      "It's the same thing as a Conformance Pack",
      "Aggregators only work within a single account",
      "It completely replaces Security Hub",
    ],
    correct: 0,
    explain: "A Config Aggregator collects configuration and compliance data from multiple source accounts (and regions) into an aggregator account, giving a consolidated view of which resources are NON_COMPLIANT across the organization — it can be combined with auto-remediation via Config Remediation Actions or notifications (skill 6.3.1).",
  },
  {
    tag: "AWS Audit Manager vs AWS Artifact",
    q: "What's the difference between AWS Audit Manager and AWS Artifact?",
    options: [
      "They're the same service",
      "Audit Manager continuously COLLECTS evidence from YOUR OWN account (configuration, logs) mapped against a compliance framework (e.g. PCI-DSS, HIPAA) to prepare YOUR audits; AWS Artifact gives you access to AWS's OWN COMPLIANCE REPORTS (SOC 2, ISO 27001) and to accepting agreements like the BAA",
      "AWS Artifact collects evidence from your account, Audit Manager issues AWS certifications",
      "Both only apply to the management account",
    ],
    correct: 1,
    explain: "Audit Manager automates continuous collection of EVIDENCE from your own environment (config, logs, policies) organized against the framework you choose, to facilitate your own audits. AWS Artifact is the library of AWS's OWN REPORTS AND CERTIFICATIONS as a provider (SOC, ISO, PCI) demonstrating that AWS's underlying infrastructure meets those standards — different evidence, for different but complementary purposes.",
  },
  {
    tag: "AWS Well-Architected Tool",
    q: "What is the AWS Well-Architected Tool used for in a security governance context?",
    options: [
      "To automatically deploy infrastructure",
      "To evaluate a workload against the best practices of the Well-Architected Framework's 6 pillars (including the Security pillar), identifying risks and generating a prioritized improvement plan",
      "To calculate the exact cost of a workload",
      "It's exclusively for machine learning workloads",
    ],
    correct: 1,
    explain: "The Well-Architected Tool guides a structured review (typically via a workshop with the team) of a workload against AWS best practices across the 6 pillars (including Security), flagging high/medium risks and generating a prioritized remediation plan — part of skill 6.3.3, 'evaluate architecture for compliance with best practices.'",
  },
  {
    tag: "SCP vs RCP vs Declarative vs AI opt-out (recap)",
    q: "Recap of the 4 types of organization policy: which one is specifically built for AI/ML services' use of data, rather than permissions or configuration?",
    options: [
      "Service Control Policy (SCP)",
      "Resource Control Policy (RCP)",
      "AI services opt-out policy",
      "Declarative Policy",
    ],
    correct: 2,
    explain: "SCP = ceiling on identity permissions. RCP = who can access resources. Declarative Policy = forces a specific configuration state. AI services opt-out policy = the only type dedicated specifically to controlling whether AWS AI services can use your data to improve their models — all 4 are 'organization policies' but each one solves a different problem.",
  },
  {
    tag: "Compliance notifications",
    q: "Besides automatically remediating a NON_COMPLIANT resource detected by Config, what mechanism is typically used to notify the responsible team (skill 6.3.1)?",
    options: [
      "Config doesn't support any kind of notification",
      "EventBridge captures Config's compliance state-change event and routes it to SNS (email/Slack via integration) or directly triggers automated remediation via Systems Manager Automation",
      "The only way to notify is by manually checking the console every day",
      "Only via AWS Support tickets",
    ],
    correct: 1,
    explain: "The standard pattern is: Config detects the compliance change → EventBridge captures the event → it's routed to SNS to notify humans, and/or triggers a Systems Manager Automation runbook to remediate automatically — the same EventBridge-as-central-bus pattern that recurs in detection (Domain 1) and IR (Domain 2).",
  },
  {
    tag: "Existing vs new landing zone",
    q: "Can Control Tower be applied to an AWS organization that ALREADY EXISTS, with dozens of accounts already in use, or does it only work for brand-new organizations?",
    options: [
      "It only works for brand-new organizations, with no prior accounts",
      "Control Tower supports extending a landing zone over an ALREADY EXISTING Organization, gradually bringing current accounts into the OU and guardrail structure, with no need to start from scratch",
      "It requires migrating all accounts to another region first",
      "It only works if all accounts are empty",
    ],
    correct: 1,
    explain: "Although Control Tower was originally designed with new implementations in mind, it explicitly supports the 'existing landing zone' scenario: it can be deployed over an Organization already in use and existing accounts can be incrementally brought into the OU and guardrail structure, without a big-bang migration — relevant because in the real world almost nobody starts from zero.",
  },
];
