var QUIZ_DATA = [
  {
    tag: "AWS Organizations",
    q: "What does AWS Organizations enable that doesn't exist when managing AWS accounts completely independently?",
    options: [
      "Consolidated billing, an OU hierarchy for applying guardrails (SCP/RCP/Declarative Policies) by account group, and resource sharing between accounts in the organization",
      "Only consolidated billing, with no other benefit",
      "Organizations replaces the need to have multiple AWS accounts",
      "It only works with a maximum of 5 accounts",
    ],
    correct: 0,
    explain: "Organizations lets you structure accounts into hierarchical OUs (Organizational Units), apply guardrails that are automatically inherited per OU (SCPs, RCPs, Declarative Policies, AI opt-out policies), consolidate billing, and share resources (via RAM) or manage security services centrally across all accounts.",
  },
  {
    tag: "AWS Control Tower",
    q: "What does AWS Control Tower automate that AWS Organizations alone does not?",
    options: [
      "Nothing extra, they're the same service with different names",
      "It deploys a complete 'landing zone' with a recommended OU structure, base accounts (Log Archive, Audit/Security Tooling) already configured, preconfigured preventive AND detective guardrails, and an Account Factory to provision new accounts already compliant from minute one",
      "Control Tower only manages billing",
      "It can only be used on completely new accounts, never on existing organizations",
    ],
    correct: 1,
    explain: "Control Tower is built ON TOP of Organizations, automating the deployment of a complete landing zone: OU structure, Log Archive and Audit accounts already created and configured, preventive and detective guardrails (controls) already enabled, and Account Factory so each new account is born already compliant with policy — it supports both new environments and 'existing landing zone' scenarios (extending an Organizations setup already in use).",
  },
  {
    tag: "Control Tower controls",
    q: "In Control Tower, what's the difference between a PREVENTIVE control and a DETECTIVE control?",
    options: [
      "They're exact synonyms",
      "Detective controls are always stricter than preventive ones",
      "A preventive control PREVENTS the non-compliant action from happening (typically implemented as an SCP that blocks the API call); a detective control IDENTIFIES resources that are already in a non-compliant state (implemented as a Config Rule) so they can be remediated afterward",
      "Only preventive controls can be applied at the OU level",
    ],
    correct: 2,
    explain: "Preventive = blocks BEFORE (e.g. an SCP that denies creating public S3 buckets). Detective = detects AFTER (e.g. a Config Rule that flags as NON_COMPLIANT a bucket that became public through some other path). Control Tower combines both types to cover prevention as well as the cases where prevention wasn't enough.",
  },
  {
    tag: "AI services opt-out policies",
    q: "Your organization handles highly confidential data and wants to guarantee that NO AWS AI/ML service (such as certain model-improvement features) uses that data for training, across all accounts in the organization. Which Organizations mechanism do you apply?",
    options: [
      "A generic SCP that blocks all AI services",
      "An RCP scoped to the Bedrock service only",
      "Enable GuardDuty in strict mode",
      "An AI services opt-out policy: a specific type of organization policy for centrally controlling whether AWS AI services can use content from your accounts to improve their models",
    ],
    correct: 3,
    explain: "AI services opt-out policies are a dedicated type of organization policy (alongside SCP, RCP, and Declarative Policies) built specifically to centrally and heritably control whether AWS AI services can use data from your accounts for training/improving models — more precise and maintainable than trying to replicate that control with a generic SCP.",
  },
  {
    tag: "Delegated administrator",
    q: "Why is it recommended to designate a 'delegated administrator' account for services like GuardDuty, Security Hub, or IAM Access Analyzer, instead of managing them from the management account?",
    options: [
      "It reduces operational use of the management account (which should be reserved almost exclusively for Organizations tasks themselves) and follows the principle of least privilege: the security team operates from a dedicated account, without needing the most sensitive credentials in the entire organization",
      "It's technically mandatory, there's no alternative",
      "The management account can never have GuardDuty enabled",
      "Delegated administrator only applies to Control Tower",
    ],
    correct: 0,
    explain: "Best practice is to minimize day-to-day use of the management account (compromising it would potentially compromise the ENTIRE organization). Delegating administration of security services to a dedicated account (typically 'Audit' or 'Security Tooling') lets the security team operate with organization-wide visibility without touching the management account day to day.",
  },
  {
    tag: "Root user & break-glass",
    q: "What is a 'break-glass' procedure in the context of root account management?",
    options: [
      "A procedure to permanently delete the root account",
      "A documented and controlled EMERGENCY process for accessing the root account (credentials normally stored securely and never used) when strictly necessary, with physical MFA and reinforced approval/auditing",
      "A CloudWatch alarm that triggers when someone logs in as root",
      "It only applies to the management account, never to member accounts",
    ],
    correct: 1,
    explain: "Break-glass describes emergency access: root credentials are normally NEVER used for daily operations (with hardware MFA stored securely, often under dual custody), and access only happens through a documented, audited procedure with approval when a genuinely exceptional need arises (e.g. regaining control of a compromised account).",
  },
  {
    tag: "Centralized root access management",
    q: "Which Organizations capability lets you centrally manage the root credentials of MEMBER accounts without going through the password-recovery process on each one?",
    options: [
      "IAM Identity Center alone",
      "AWS Config",
      "Centralized root access management: it lets the management account centrally invoke a limited set of privileged root actions in member accounts, effectively removing the need for usable root credentials in those accounts",
      "Amazon Detective",
    ],
    correct: 2,
    explain: "This capability (part of skill 6.1.5) lets you manage member accounts' root access from the management account centrally, drastically reducing the risk of unmanaged, loose root credentials across dozens of accounts — combinable with mandatory MFA at the organization level.",
  },
  {
    tag: "Infrastructure as Code at scale",
    q: "Which AWS service lets you deploy the SAME CloudFormation stack (e.g. a baseline security configuration) automatically across hundreds of accounts and regions in an organization, centrally?",
    options: [
      "AWS Config Conformance Packs only",
      "AWS Service Catalog exclusively",
      "Amazon Q Developer",
      "AWS CloudFormation StackSets: define the stack once and deploy/update/delete it centrally across all target accounts and regions (even automatically in NEW accounts if integrated with Organizations)",
    ],
    correct: 3,
    explain: "StackSets extends CloudFormation to manage the same stack as a single unit across multiple accounts/regions, with the option to integrate with AWS Organizations to deploy AUTOMATICALLY to accounts that join an OU in the future — key for skill 6.2.1 on consistent deployment at scale.",
  },
  {
    tag: "IaC validation",
    q: "What's the difference between CloudFormation Guard and cfn-lint?",
    options: [
      "cfn-lint validates SYNTAX and general best practices of a CloudFormation template; CloudFormation Guard evaluates the template against CUSTOM POLICY RULES that you define (e.g. 'every S3 bucket must have encryption'), letting you block non-compliant deployments in the pipeline before applying them",
      "They're exactly the same thing with different names",
      "CloudFormation Guard only works with Terraform",
      "cfn-lint replaces the need for SCPs",
    ],
    correct: 0,
    explain: "cfn-lint is a general linter (syntax, valid resource types, best practices). CloudFormation Guard is a policy-as-code engine where YOU write the specific business/security rules the template must satisfy — both integrate into the CI/CD pipeline to catch problems before deployment (shift-left), complementing (not replacing) runtime guardrails like SCP/Config.",
  },
  {
    tag: "Tagging strategy",
    q: "Beyond visual organization, what security/governance use case does a consistent tagging strategy (e.g. an 'environment' or 'data-classification' tag) enable?",
    options: [
      "None, tags are purely cosmetic",
      "It enables ABAC (attribute-based access control) policies, Conformance Packs, and conditional SCPs that apply automatically based on a resource's tag (e.g. 'encryption mandatory only on resources with data-classification=confidential'), and makes it easier to attribute cost/ownership during an investigation",
      "Tags only matter for Cost Explorer, unrelated to security",
      "Tags replace the need to use IAM",
    ],
    correct: 1,
    explain: "A consistent tagging strategy is the foundation for ABAC (covered in the IAM module), conditional conformance packs, and the ability to respond quickly during an incident ('which resources are production?', 'who owns this resource?') — skill 6.2.2 treats it as a governance pillar, not just FinOps.",
  },
  {
    tag: "AWS Firewall Manager",
    q: "You have WAF, Security Groups, and AWS Network Firewall deployed inconsistently across dozens of accounts, and you want to apply and maintain a uniform network security policy across all of them from a single place. Which service do you use?",
    options: [
      "AWS RAM",
      "AWS Config Rules only",
      "AWS Firewall Manager: automatically applies and maintains WAF, Shield Advanced, Security Groups, and Network Firewall policies across all accounts and resources in the organization, even ones created in the future",
      "Amazon Inspector",
    ],
    correct: 2,
    explain: "Firewall Manager centralizes the management of network and application security policies (WAF, Shield Advanced, Security Groups, Network Firewall, Route 53 Resolver DNS Firewall) at the organization level, applying them automatically even to NEW resources and accounts — exactly skill 6.2.3, 'deploy and enforce policies from a central source.'",
  },
  {
    tag: "Sharing resources across accounts",
    q: "You want to share a VPC (subnets), a Transit Gateway, or a Firewall Manager rule among several accounts in your organization WITHOUT duplicating the resource or using peering/AssumeRole for every access. Which service do you use?",
    options: [
      "AWS Config Aggregator",
      "AWS Service Catalog",
      "Amazon Macie",
      "AWS Resource Access Manager (RAM): shares AWS resources directly between accounts in the organization (or specific external accounts), natively and without duplicating the resource",
    ],
    correct: 3,
    explain: "AWS RAM lets you share specific resources (VPC subnets, Transit Gateways, License Manager configurations, Firewall Manager rules, etc.) directly with other accounts in the Organization or with specific external accounts, avoiding infrastructure duplication and simplifying the shared-network model (shared VPC).",
  },
  {
    tag: "AWS Service Catalog",
    q: "What problem does AWS Service Catalog solve in a multi-account governance context?",
    options: [
      "It lets teams self-serve infrastructure templates PRE-APPROVED by the security/platform team (e.g. 'standard VPC', 'compliant S3 bucket'), preventing them from deploying resources outside the standards without completely blocking their autonomy",
      "It completely replaces CloudFormation",
      "It's a catalog of AWS service pricing",
      "It only works for third-party Marketplace software",
    ],
    correct: 0,
    explain: "Service Catalog lets you package already-reviewed and approved IaC templates as 'products' that teams can deploy self-service, without needing broad resource-creation permissions — a balance between development team velocity and centralized control from the platform/security team.",
  },
  {
    tag: "AWS Config aggregators",
    q: "What does an AWS Config Aggregator enable?",
    options: [
      "It's the same thing as a Conformance Pack",
      "Consolidating the compliance state of Config rules from MULTIPLE accounts and regions into a single view, without having to log into each account individually",
      "Aggregators only work within a single account",
      "It completely replaces Security Hub",
    ],
    correct: 1,
    explain: "A Config Aggregator collects configuration and compliance data from multiple source accounts (and regions) into an aggregator account, giving a consolidated view of which resources are NON_COMPLIANT across the organization — it can be combined with auto-remediation via Config Remediation Actions or notifications (skill 6.3.1).",
  },
  {
    tag: "AWS Audit Manager vs AWS Artifact",
    q: "What's the difference between AWS Audit Manager and AWS Artifact?",
    options: [
      "They're the same service",
      "AWS Artifact collects evidence from your account, Audit Manager issues AWS certifications",
      "Audit Manager continuously COLLECTS evidence from YOUR OWN account (configuration, logs) mapped against a compliance framework (e.g. PCI-DSS, HIPAA) to prepare YOUR audits; AWS Artifact gives you access to AWS's OWN COMPLIANCE REPORTS (SOC 2, ISO 27001) and to accepting agreements like the BAA",
      "Both only apply to the management account",
    ],
    correct: 2,
    explain: "Audit Manager automates continuous collection of EVIDENCE from your own environment (config, logs, policies) organized against the framework you choose, to facilitate your own audits. AWS Artifact is the library of AWS's OWN REPORTS AND CERTIFICATIONS as a provider (SOC, ISO, PCI) demonstrating that AWS's underlying infrastructure meets those standards — different evidence, for different but complementary purposes.",
  },
  {
    tag: "AWS Well-Architected Tool",
    q: "What is the AWS Well-Architected Tool used for in a security governance context?",
    options: [
      "To automatically deploy infrastructure",
      "It's exclusively for machine learning workloads",
      "To calculate the exact cost of a workload",
      "To evaluate a workload against the best practices of the Well-Architected Framework's 6 pillars (including the Security pillar), identifying risks and generating a prioritized improvement plan",
    ],
    correct: 3,
    explain: "The Well-Architected Tool guides a structured review (typically via a workshop with the team) of a workload against AWS best practices across the 6 pillars (including Security), flagging high/medium risks and generating a prioritized remediation plan — part of skill 6.3.3, 'evaluate architecture for compliance with best practices.'",
  },
  {
    tag: "SCP vs RCP vs Declarative vs AI opt-out (recap)",
    q: "Recap of the 4 types of organization policy: which one is specifically built for AI/ML services' use of data, rather than permissions or configuration?",
    options: [
      "AI services opt-out policy",
      "Resource Control Policy (RCP)",
      "Service Control Policy (SCP)",
      "Declarative Policy",
    ],
    correct: 0,
    explain: "SCP = ceiling on identity permissions. RCP = who can access resources. Declarative Policy = forces a specific configuration state. AI services opt-out policy = the only type dedicated specifically to controlling whether AWS AI services can use your data to improve their models — all 4 are 'organization policies' but each one solves a different problem.",
  },
  {
    tag: "Compliance notifications",
    q: "Besides automatically remediating a NON_COMPLIANT resource detected by Config, what mechanism is typically used to notify the responsible team (skill 6.3.1)?",
    options: [
      "Config doesn't support any kind of notification",
      "EventBridge captures Config's compliance state-change event and routes it to SNS (email/Slack via integration) or directly triggers automated remediation via Systems Manager Automation",
      "The only way to notify is by manually checking the console every day",
      "Only via AWS Support tickets",
    ],
    correct: 1,
    explain: "The standard pattern is: Config detects the compliance change → EventBridge captures the event → it's routed to SNS to notify humans, and/or triggers a Systems Manager Automation runbook to remediate automatically — the same EventBridge-as-central-bus pattern that recurs in detection (Domain 1) and IR (Domain 2).",
  },
  {
    tag: "Existing vs new landing zone",
    q: "Can Control Tower be applied to an AWS organization that ALREADY EXISTS, with dozens of accounts already in use, or does it only work for brand-new organizations?",
    options: [
      "It only works for brand-new organizations, with no prior accounts",
      "It requires migrating all accounts to another region first",
      "Control Tower supports extending a landing zone over an ALREADY EXISTING Organization, gradually bringing current accounts into the OU and guardrail structure, with no need to start from scratch",
      "It only works if all accounts are empty",
    ],
    correct: 2,
    explain: "Although Control Tower was originally designed with new implementations in mind, it explicitly supports the 'existing landing zone' scenario: it can be deployed over an Organization already in use and existing accounts can be incrementally brought into the OU and guardrail structure, without a big-bang migration — relevant because in the real world almost nobody starts from zero.",
  },
  {
    tag: "Declarative Policies: VPC Block Public Access",
    q: "The security team wants to guarantee that NO VPC in the organization, present or future, allows inbound traffic from the internet through an internet gateway, without auditing route tables or NACLs account by account, and with the ability to roll the change back if something breaks. Which mechanism is the best fit?",
    options: [
      "Manually editing the NACLs of every existing VPC",
      "An SCP that denies ec2:CreateInternetGateway across the whole organization",
      "A detective Config Rule combined with manual remediation",
      "A Declarative Policy that enables VPC Block Public Access (blocking ingress via internet gateway) at the OU/organization level: it forces that desired state on all current and future VPCs without mutating existing resources, and it's reversible",
    ],
    correct: 3,
    explain: "Declarative Policies cover EC2/VPC/EBS at scale by enforcing a configuration STATE (not just blocking API calls the way an SCP does). VPC Block Public Access is an explicit use case: it blocks public ingress via internet gateway centrally, non-destructively, and reversibly, and automatically applies to future VPCs too — unlike an SCP, which only blocks the API call but doesn't change the state of resources that already exist.",
  },
  {
    tag: "Declarative Policies: allowed AMI providers",
    q: "After research on the 'whoAMI' attack was published (where an attacker publishes a public AMI with a name matching the pattern that misconfigured code searches for), your organization wants to centrally restrict which AMI owners can be used to launch EC2 instances across ALL accounts, and also hide any non-compliant AMI from the console and CLI. Which solution do you apply?",
    options: [
      "An EC2 Declarative Policy for 'Allowed AMIs': it defines the permitted AMI providers at the OU/organization level, blocking instance launches with non-compliant AMIs and hiding them from the console and CLI",
      "An SCP with a condition on ec2:Owner replicated in every account's policy",
      "A detective Config Rule that flags already-launched instances as NON_COMPLIANT",
      "An IAM permission boundary applied to every instance-launching role",
    ],
    correct: 0,
    explain: "The 'Allowed AMIs' Declarative Policy is one of the EC2 configurations this policy type supports: it lets you define which AMI providers are valid for the whole organization, blocking launches (and hiding from console/CLI) any AMI that doesn't come from an approved provider — a direct, preventive mitigation against public-AMI impersonation attacks like whoAMI, more robust than a conditional SCP that has to be maintained manually.",
  },
  {
    tag: "Tag Policies: IaC enforcement",
    q: "You find that several teams create resources via CloudFormation, Terraform, and Pulumi without including the mandatory 'cost-center' tag, and you want to block (or at least warn on) those deployments BEFORE the resource is created, without building a separate validation for each IaC tool. Which Organizations capability do you use?",
    options: [
      "CloudFormation Guard configured manually in each team's pipeline",
      "AWS Organizations Tag Policies with 'required tag keys' and the tagging compliance validation hook, configurable in Warn or Fail mode, applied centrally to CloudFormation, Terraform, and Pulumi deployments",
      "An SCP that denies any CreateTags action that doesn't include a value",
      "A 'required-tags' Config Rule, which only detects the problem after the resource has already been created",
    ],
    correct: 1,
    explain: "As of November 2025, Organizations Tag Policies let you define required tag keys and enforce them directly on infrastructure-as-code deployments (CloudFormation, Terraform, and Pulumi) via a validation hook with Warn (warns but allows) or Fail (blocks the deployment) mode — shift-left tagging governance, before the resource is ever created, instead of catching it afterward with Config.",
  },
  {
    tag: "Tag Policies vs RCP",
    q: "You want to prevent any identity, including one with broad permissions, from DELETING or MODIFYING the 'data-classification' tag on a resource once it has been assigned — not just standardize which values are valid for that tag. Which mechanism specifically addresses this requirement?",
    options: [
      "A Tag Policy, because it automatically standardizes the use of any tag across the organization",
      "This is only possible by enabling GuardDuty in tag-protection mode",
      "A Resource Control Policy (or SCP) that restricts the tag:TagResource / tag:UntagResource actions on the resource except for authorized principals: Tag Policies define and report which keys/values are valid, but on their own they do NOT block the action of modifying or removing a tag",
      "An AWS Config Aggregator with real-time alerting",
    ],
    correct: 2,
    explain: "Tag Policies standardize and validate tags (and, since 2025, can even block IaC deployments missing required tags), but on their own they are not a permissions-control mechanism over the tag/untag action itself. To stop someone from removing or changing a specific tag you need a permissions policy (RCP or SCP) that explicitly denies tag:UntagResource/tag:TagResource except under specific conditions — complementary controls, not interchangeable ones.",
  },
  {
    tag: "Resource Control Policies: supported-service scope",
    q: "Your team wants to use an RCP to restrict external access to Amazon DynamoDB tables across all accounts, the same way they already do for S3 buckets. What should you verify first before assuming it will work the same way?",
    options: [
      "Nothing — RCPs automatically cover every action of every AWS service from the moment they launched, just like SCPs",
      "That Control Tower is deployed in the organization",
      "That the management account has hardware MFA enforced",
      "That the service (DynamoDB, in this case) is among those currently supported by RCPs: unlike SCPs, which apply universally to any IAM action, RCPs only protect a specific set of services that AWS expands incrementally (initially S3, STS, KMS, Secrets Manager, and SQS, with later additions such as ECR, OpenSearch Serverless, Cognito, CloudWatch Logs, and DynamoDB)",
    ],
    correct: 3,
    explain: "Unlike SCPs (which act as a ceiling on permissions for any IAM action across the organization), RCPs only cover a specific set of services that AWS has progressively expanded since their November 2024 launch. Before designing a data-perimeter control with an RCP over a given service, you need to confirm that service is already supported — otherwise the control simply has no effect.",
  },
  {
    tag: "AWS Config at the organization level",
    q: "Until recently, deploying a new Config rule centrally across the whole organization required packaging it inside a conformance pack. Which recent AWS Config capability removes that requirement?",
    options: [
      "AWS Config now lets you manage and deploy INDIVIDUAL Config rules (not just entire conformance packs) directly at the organization level, simplifying compliance governance without forcing every rule into a pack",
      "This is only achievable by replicating the same effect with CloudFormation StackSets",
      "The Config Aggregator does this automatically with no additional action needed",
      "It's not possible; a conformance pack is always required to deploy at the organization level",
    ],
    correct: 0,
    explain: "AWS Config expanded organization-level management to include not just entire conformance packs but also individual Config rules, simplifying multi-account compliance governance when you only need a single rule rather than a whole package — it complements (doesn't replace) conformance packs for larger sets of related rules.",
  },
  {
    tag: "Control Tower Landing Zone 4.0",
    q: "After migrating to Control Tower landing zone version 4.0, what relevant architectural change happens to how AWS Config compliance data used to be aggregated across accounts?",
    options: [
      "AWS Config is removed entirely from the landing zone and fully replaced by Security Hub",
      "The organization aggregator in the management account and the account aggregator in the Audit account are replaced by a Service-Linked Config Aggregator (SLCA) deployed in the Config integration account, alongside a move to dedicated per-service resources (S3 buckets and SNS topics) instead of resources shared between Config and CloudTrail",
      "Config data is no longer aggregated centrally, and it must be queried account by account",
      "A separate Config Aggregator must be deployed manually with Terraform after the migration",
    ],
    correct: 1,
    explain: "Control Tower's landing zone 4.0 introduces optional service integrations and dedicated per-service resources (Config and CloudTrail no longer share buckets/topics), and migrates compliance aggregation to a Service-Linked Config Aggregator deployed in the Config integration account, retiring the previously used organization aggregator (in management) and account aggregator (in Audit).",
  },
  {
    tag: "Control Tower: control library",
    q: "A compliance lead asks how Control Tower's preconfigured control coverage has evolved, in order to map it against their regulatory requirements. Which statement about that control library is correct?",
    options: [
      "It has stayed fixed since the service launched, with no new additions since then",
      "Only preventive controls exist; detective controls were retired in 2025",
      "Control Tower has significantly expanded its library of AWS Config–based controls (hundreds of new controls added in 2025), which can be enabled per account or per organization and grouped into conformance packs to scale multi-account governance",
      "The number of available controls can never exceed 50 due to a technical limitation of the service",
    ],
    correct: 2,
    explain: "Control Tower has continued substantially expanding its catalog of Config-based controls (hundreds of new controls added in 2025), which can be enabled at the account or organization level and grouped via conformance packs — an organization that assessed its coverage a year ago is likely missing out on newer controls relevant to its compliance framework.",
  },
  {
    tag: "Control Tower: automatic SCP drift resolution",
    q: "An engineer modifies, outside the Control Tower console, an SCP managed by the service: it ends up attached to a different OU than intended. This used to be flagged as governance 'drift' requiring intervention. Which recent Control Tower improvement affects this scenario?",
    options: [
      "Control Tower now absolutely blocks any manual change to managed SCPs, with no exceptions",
      "Only a custom Config Aggregator can detect this kind of change",
      "The concept of drift has been removed from the service entirely",
      "Control Tower now automatically resolves certain types of governance drift on managed SCPs (for example, ending up attached to a different OU or to a member account outside the console), without it being flagged as persistent drift that requires a manual landing-zone re-registration",
    ],
    correct: 3,
    explain: "In 2025 Control Tower expanded how it handles drift on managed SCPs: certain types of governance change (a control's SCP ending up attached to a different OU, or to a member account, through an action outside the console) are now resolved automatically by the service itself instead of being left as persistent drift that blocks landing-zone operations until manually remediated.",
  },
  {
    tag: "Centralized Root Access Management: task-scoped sessions",
    q: "You need to restore access to an S3 bucket whose policy was misconfigured in a member account — a task that traditionally required that account's root credentials. With Centralized Root Access Management enabled, how is this done without recovering the member account's root password?",
    options: [
      "You invoke, from the management account or the delegated admin, a TASK-SCOPED root session on the member account, limited to that specific privileged action, without generating long-lived root credentials; in addition, new accounts in the organization can be created without usable root credentials from the start",
      "You must use the 'forgot my password' flow tied to that member account's root email",
      "It's only possible if the member account has IAM Identity Center configured as its identity source",
      "A paid AWS Support ticket is required for every such restoration",
    ],
    correct: 0,
    explain: "Centralized Root Access Management (launched November 2024) lets you invoke, from the management account, a limited set of task-scoped root actions on member accounts (such as restoring access to an S3 bucket or an SQS queue), without needing long-lived root credentials in the member account — and new accounts in the organization can be created without usable root credentials in the first place.",
  },
  {
    tag: "AWS Audit Manager: maintenance mode",
    q: "You're designing the continuous compliance-evidence collection strategy for an organization that will onboard NEW accounts starting mid-2026. A colleague suggests using AWS Audit Manager on those new accounts. What should you keep in mind?",
    options: [
      "Audit Manager remains the recommended option with no limitations for new accounts",
      "AWS announced that Audit Manager is moving to maintenance mode: starting April 30, 2026, it can no longer be set up in new accounts (accounts/regions already configured before that date can keep using it and creating new assessments), so for new accounts you should evaluate a different approach or tool",
      "Audit Manager has been fully removed from AWS and no longer works in any existing account",
      "Audit Manager becomes free and unlimited for all accounts starting on that date",
    ],
    correct: 1,
    explain: "AWS announced that Audit Manager is moving to maintenance mode: as of April 30, 2026, it can no longer be set up in new accounts or regions, although customers who already had it configured before that date can continue using it normally (including creating new assessments) in that specific account/region, without receiving new features or support for new frameworks or services.",
  },
  {
    tag: "AWS Service Catalog AppRegistry: maintenance mode",
    q: "You were planning to use AWS Service Catalog AppRegistry to logically group resources by application and apply tags consistently in accounts that will be created after July 2026. What should you know about this?",
    options: [
      "AppRegistry has recently expanded to more regions than ever",
      "AppRegistry fully replaces AWS Config starting on that date",
      "AWS Service Catalog AppRegistry is moving to maintenance mode and will no longer be available to new customers starting July 30, 2026 (no new features or regional expansion); as no-additional-cost alternatives for grouping and tagging resources, you can use AWS Resource Groups and AWS Resource Explorer",
      "All of AWS Service Catalog (not just AppRegistry) must be migrated away before that date or it will stop working",
    ],
    correct: 2,
    explain: "AWS announced that AppRegistry (the Service Catalog component for grouping resources by application) is moving to maintenance mode, closed to new customers as of July 30, 2026, with no new features or regions; existing customers keep the service, and for new resource-grouping/tagging needs AWS recommends AWS Resource Groups and AWS Resource Explorer, at no additional cost.",
  },
  {
    tag: "Firewall Manager & Shield Advanced: Anti-DDoS managed rule group",
    q: "You manage AWS Firewall Manager policies that include Shield Advanced protection for workloads behind ALB and CloudFront. AWS announced a change in how Shield Advanced mitigates application-layer (L7) attacks. What does that change involve?",
    options: [
      "This change only affects AWS Network Firewall, not Shield Advanced or Firewall Manager",
      "Shield Advanced stops supporting application-layer attack mitigation entirely",
      "AWS WAF is removed and fully replaced by Shield Advanced",
      "Shield Advanced now relies on the AWS WAF 'Anti-DDoS' managed rule group to mitigate application-layer attacks (such as HTTP request floods), integrating with the Firewall Manager policies that already centrally distribute WAF rules",
    ],
    correct: 3,
    explain: "AWS announced that Shield Advanced adopts the AWS WAF 'Anti-DDoS' managed rule group to strengthen mitigation of application-layer DDoS attacks, consistent with the model where Firewall Manager already centrally distributes and maintains WAF policies (including managed rule groups) alongside Shield Advanced across the organization.",
  },
  {
    tag: "Control Tower: digital sovereignty (European Sovereign Cloud)",
    q: "A European company with strict data-residency requirements is evaluating deploying its landing zone in the new AWS European Sovereign Cloud (general availability announced January 2026, physically independent from other AWS regions). What's correct about Control Tower's support in this context?",
    options: [
      "Control Tower is available in the AWS European Sovereign Cloud and incorporates data-residency governance as part of AWS's Digital Sovereignty Pledge, including a dedicated digital sovereignty grouping and the option to use an external key store for AWS KMS",
      "Control Tower is not available in the European Sovereign Cloud; the entire landing zone must be managed manually",
      "The European Sovereign Cloud automatically shares all data and metadata with AWS's standard regions outside the EU",
      "It's only reachable via an exclusive Direct Connect connection, with no Control Tower or Organizations support",
    ],
    correct: 0,
    explain: "The AWS European Sovereign Cloud is an independent cloud, operated exclusively by EU residents and physically separate from other AWS regions. Control Tower supports this environment with data-residency governance (a dedicated digital sovereignty grouping) and options like an external key store for KMS, in line with AWS's Digital Sovereignty Pledge.",
  },
  {
    tag: "AWS Well-Architected Tool: Review Templates",
    q: "The platform team reviews dozens of workloads with very similar architecture patterns (and therefore the same answers to most Security-pillar best practices) and wants to avoid manually re-filling the same answers on every new review. Which Well-Architected Tool capability solves this?",
    options: [
      "It's not possible; every review must be completed manually from scratch with no exceptions",
      "Review Templates: it lets you create templates with pre-filled answers for Well-Architected Framework best practices (or a custom lens) and apply them as a starting point when defining new workloads, reducing duplicated effort and standardizing common answers across teams",
      "It can only be achieved by exporting answers to a spreadsheet and manually copying them into each new review",
      "It's a capability exclusive to the cost-optimization pillar, not applicable to the security pillar",
    ],
    correct: 1,
    explain: "Review Templates let you pre-define common answers to Well-Architected Framework best practices (including the Security pillar) or a custom lens, and apply them as a starting point when creating new workloads with repeating patterns, avoiding re-entering the same answers manually and standardizing the evaluation criteria across teams and workloads.",
  },
  {
    tag: "Declarative Policies vs SCP: durability",
    q: "A colleague asks why the security team prefers a Declarative Policy over an SCP to enforce IMDSv2 on all EC2 instances across the organization, given that both are organization policies inherited by OU. What's the main reason?",
    options: [
      "SCPs cannot be applied at the OU level, only at the individual account level",
      "Declarative Policies have a lower additional cost than SCPs",
      "A Declarative Policy durably enforces a desired configuration STATE ('set it once'): that state is automatically maintained even as the service adds new APIs or related features, whereas an SCP only denies specific API calls and must be manually kept up to date as new ways of achieving the same undesired outcome appear",
      "There's no practically relevant difference between the two policy types",
    ],
    correct: 2,
    explain: "Declarative Policies are designed for durable, 'set and forget' service configuration: once the desired configuration is defined (e.g. mandatory IMDSv2), it is automatically maintained even as the service adds new APIs or related features. An SCP, by contrast, operates at the level of specific API permissions: if a new way of achieving the undesired outcome appears (a new API, a new parameter), the SCP has to be manually updated to keep covering it.",
  },
  {
    tag: "AWS Config conformance packs: regional expansion",
    q: "Your organization starts running workloads in relatively new AWS regions, such as Asia Pacific (Malaysia) or Asia Pacific (New Zealand), and you plan to deploy Config conformance packs at the organization level across all accounts and regions. What should you verify before assuming it will work the same as in older regions like us-east-1?",
    options: [
      "Organization-level management of conformance packs depends solely on whether Control Tower is deployed, not on the region",
      "Conformance packs have been automatically available in every region since the service launched, with no exceptions",
      "Conformance packs only work in the region where the organization's management account resides",
      "AWS Config conformance packs and their organization-level management have per-region availability, which AWS has progressively expanded (adding regions such as Asia Pacific Malaysia, New Zealand, Thailand, Taipei, and Mexico Central in 2025); you should confirm the target region already supports the feature before deploying",
    ],
    correct: 3,
    explain: "AWS has been incrementally expanding the regional availability of both Config conformance packs and their organization-level management, adding regions such as Asia Pacific (Malaysia), Asia Pacific (New Zealand), Asia Pacific (Thailand), Asia Pacific (Taipei), and Mexico (Central) in 2025 — a realistic exam scenario is verifying a governance feature's regional availability before assuming uniform global coverage.",
  },
  {
    tag: "SCP scope",
    q: "You are rolling out Service Control Policies across an organization. Which TWO statements are correct?",
    options: [
      "An SCP grants nothing: it only caps the maximum permissions the account's identities can have",
      "SCPs do not apply to the organization's management account",
      "An SCP can grant permissions to a user who lacks them in their identity policy",
      "SCPs also apply to external principals accessing your resources",
    ],
    correct: [0, 1],
    explain: "Two exam classics. An SCP is a <b>guardrail</b>, never a grant: effective permission is the intersection of the SCP and the identity policies. And the <b>management account is not subject to SCPs</b>, which is why AWS advises against running workloads in it. Option D describes what <b>RCPs</b> do, since they do reach external identities: that is precisely the gap SCPs leave open.",
  },
  {
    tag: "Control Tower controls",
    q: "Control Tower offers different control types across the landing zone. Which TWO descriptions are correct?",
    options: [
      "Preventive controls are implemented with SCPs and stop the action from executing",
      "Detective controls are implemented with AWS Config rules and flag drift after the fact",
      "Detective controls block the action before it happens, just like preventive ones",
      "Preventive controls can only be applied to the audit account",
    ],
    correct: [0, 1],
    explain: "The <b>preventive vs detective</b> distinction is the most-tested one: preventive controls (SCP) <b>stop</b> the action, detective controls (Config) <b>find</b> what already happened. That is why option C contradicts itself. Preventive controls apply to OUs and accounts, not only the audit account. Control Tower also adds <i>proactive</i> controls, which validate CloudFormation templates before deployment.",
  },
  {
    tag: "Multi-account compliance with Config",
    q: "You need a single view of AWS Config rule compliance across 90 accounts and 4 Regions. Which TWO enable this?",
    options: [
      "An AWS Config aggregator collecting data from all accounts and Regions",
      "Conformance packs deployed across the organization to apply the same rule set everywhere",
      "An S3 bucket in each account from which to download reports manually every week",
      "Enabling Config only in the management account, which automatically inherits the others' state",
    ],
    correct: [0, 1],
    explain: "The <b>aggregator</b> delivers the consolidated view and organization-level <b>conformance packs</b> ensure everyone evaluates the same rules. Manual downloads don't scale to 90 accounts and are always stale. And Config is a <b>regional, per-account</b> service: the management account inherits nothing, it must be enabled where the resources are.",
  },
  {
    tag: "Protecting the root user",
    q: "You are hardening the root user across every account in the organization. Which TWO does AWS recommend?",
    options: [
      "Enable MFA on root and delete its access keys if any exist",
      "Use centralized root access management to remove root credentials from member accounts",
      "Create a root access key in each account and store it in Secrets Manager to automate tasks",
      "Use root for daily administrative work, since it is never blocked by an SCP",
    ],
    correct: [0, 1],
    explain: "The basics are <b>MFA and no access keys</b> on root, and <b>centralized root access management</b> lets you remove those credentials from member accounts entirely, leaving root-only tasks to scoped sessions via <code>sts:AssumeRoot</code>. Creating root access keys is the exact opposite of the guidance. And while it is true SCPs don't restrict the management account's root, that is a reason <b>not</b> to use it daily, not a reason to use it.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["governance"] = QUIZ_DATA;
