// Banco de preguntas del módulo: soluciones de seguridad para infraestructura (SC-100, dominio 3).
// Cada explicación termina en el enlace a la documentación oficial de Microsoft Learn.

var QUIZ_DATA = [
  {
    tag: "CSPM frente a CWPP",
    q: "Un cliente acaba de conectar sus suscripciones a Defender for Cloud y ve una lista larga de recomendaciones, pero ninguna alerta. Pregunta por qué el producto «no detecta nada». ¿Qué le explicas?",
    options: [
      "Que las alertas tardan hasta 30 días en aparecer mientras el servicio aprende el comportamiento normal del entorno",
      "Que la capa gratuita da postura; para detectar hace falta activar los planes de protección de cargas",
      "Que hay que instalar el agente de Azure Monitor en cada recurso antes de que se genere ninguna alerta de seguridad",
      "Que las recomendaciones y las alertas son lo mismo y las recomendaciones ya son las alertas del servicio",
    ],
    correct: 1,
    explain: "Defender for Cloud son dos cosas: la <b>postura</b> (CSPM), que viene activada y evalúa la configuración contra el MCSB devolviendo recomendaciones, y la <b>protección de cargas</b> (CWPP), que son los planes de pago por tipo de recurso y es lo que genera alertas. Sin plan activo no hay detección, por bien configurado que esté todo. Y una recomendación dice qué <em>podría</em> pasar; una alerta dice qué <em>está</em> pasando. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/concept-cloud-security-posture-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La línea base de la nube",
    q: "La dirección pide una línea base de seguridad común para Azure y para las cuentas de AWS conectadas, con el mínimo esfuerzo operativo. ¿Qué propones?",
    options: [
      "El Microsoft Cloud Security Benchmark, que ya viene asignado y también evalúa AWS y GCP",
      "Escribir una iniciativa propia de Azure Policy que recoja los controles que la organización considera obligatorios",
      "Adoptar CIS como estándar y traducir cada uno de sus controles a definiciones de política escritas a mano",
      "Exportar las recomendaciones a un cuaderno y revisarlas cada trimestre con los equipos de plataforma",
    ],
    correct: 0,
    explain: "El <b>MCSB</b> es exactamente eso: la línea base que Microsoft considera común a cualquier nube, ya asignada por defecto en Defender for Cloud y aplicada también a las cuentas de <b>AWS y GCP</b> conectadas. «Mínimo esfuerzo operativo» descarta escribirla. Una iniciativa propia o CIS traducido a mano son trabajo que ya está hecho, y hay que mantenerlo. El cuaderno trimestral no es un control. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué mide cada puntuación",
    q: "El responsable de seguridad quiere una métrica que le diga cuánto ha mejorado la configuración del tenant en identidad, correo y dispositivos gestionados. ¿Cuál es?",
    options: [
      "El secure score de Defender for Cloud, que agrega el estado de todos los recursos de las suscripciones",
      "El porcentaje de cumplimiento del MCSB en el panel de cumplimiento normativo de Defender for Cloud",
      "El número de recomendaciones abiertas por severidad en el inventario de recursos de Defender for Cloud",
      "Microsoft Secure Score, en el portal de Defender",
    ],
    correct: 3,
    explain: "Son dos puntuaciones distintas con nombres casi iguales. <b>Microsoft Secure Score</b>, en el portal de Defender, mide la configuración del <b>tenant</b>: identidad, correo, aplicaciones y dispositivos. El <b>secure score de Defender for Cloud</b> mide la configuración de los <b>recursos</b> de Azure, AWS y GCP. El enunciado nombra identidad, correo y dispositivos, así que es la primera. Y el cumplimiento del MCSB mide conformidad con un estándar, no mejora. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Puntuación o conformidad",
    q: "Un auditor externo pide evidencia del grado de cumplimiento de PCI DSS en las suscripciones de Azure. El equipo propone enseñarle la evolución del secure score. ¿Qué recomiendas?",
    options: [
      "Enseñar el secure score acompañado de la lista de recomendaciones abiertas ordenadas por severidad",
      "Exportar el inventario de recursos y anotar a mano qué control de PCI DSS cubre cada uno de ellos",
      "Añadir PCI DSS como estándar y llevar el panel de cumplimiento normativo, control a control",
      "Enseñar el secure score, ya que un valor alto implica que se cumplen los controles de PCI DSS",
    ],
    correct: 2,
    explain: "El secure score es una métrica de <b>mejora relativa</b> de la postura: no está mapeado a los controles de ninguna norma y no responde «¿cumplimos el requisito 8.3?». El <b>panel de cumplimiento normativo</b> sí: se le añade PCI DSS como estándar y muestra, control a control, qué se cumple y qué no, con evidencia exportable. Anotarlo a mano no es repetible ni verificable. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/regulatory-compliance-dashboard\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Conector o Arc",
    q: "Un cliente tiene suscripciones de Azure, dos cuentas de AWS y cuarenta servidores en su propio centro de datos, y quiere postura de seguridad unificada sobre todo ello. ¿Qué DOS piezas incluye el diseño?",
    options: [
      "El conector de AWS de Defender for Cloud, que evalúa la configuración de la cuenta sin agentes",
      "Un espacio de trabajo de Log Analytics por cada uno de los tres entornos, con su regla de recopilación",
      "Azure Arc sobre los servidores del centro de datos, para que existan como recursos de Azure",
      "Una suscripción de Azure independiente por entorno, con su propio grupo de administración",
    ],
    correct: [0, 2],
    explain: "Son dos huecos distintos y cada uno tiene su pieza. La cuenta de AWS entra con el <b>conector multinube</b>, que lee su configuración <em>sin instalar nada</em>. Los servidores del centro de datos entran con <b>Azure Arc</b>, que los proyecta al plano de control de Azure para poder aplicarles Policy y los planes de Defender. Los workspaces son una decisión de registro, no de postura, y las suscripciones extra no aportan visibilidad. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-multicloud-security-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Postura sin agentes",
    q: "El equipo de AWS acepta conectar sus cuentas a Defender for Cloud, pero pone una condición: no se instala software de Microsoft en sus instancias. ¿Qué se puede ofrecer aun así?",
    options: [
      "Nada útil: sin agente en las instancias, el conector no llega a ver la configuración de la cuenta",
      "La postura completa de la cuenta, porque el conector lee la configuración por API sin agentes",
      "Solo el inventario de recursos, sin recomendaciones ni evaluación contra el MCSB",
      "Solo las alertas de la capa de red, que se obtienen de los registros de flujo de la nube de origen",
    ],
    correct: 1,
    explain: "La parte de <b>postura es agentless</b>: el conector asume un rol en la cuenta y lee la configuración por API, de modo que el MCSB se evalúa entero y las recomendaciones aparecen sin tocar una sola instancia. Lo que sí requiere despliegue son algunos planes de protección de cargas, y eso es una segunda conversación. Decir que sin agente no hay nada es descartar justo lo que el conector aporta. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-multicloud-security-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué plan cubre el riesgo",
    q: "Los administradores necesitan RDP y SSH contra un grupo de máquinas virtuales, pero seguridad no acepta que los puertos estén abiertos de forma permanente. ¿Qué plan y qué capacidad?",
    options: [
      "Defender for Servers P1, con Defender for Endpoint desplegado en cada una de las máquinas del grupo",
      "Defender for Resource Manager, que vigila las operaciones sospechosas del plano de control de Azure",
      "Defender for Servers P2, con acceso just-in-time a los puertos de administración",
      "Defender CSPM, que recomienda cerrar los puertos de administración expuestos a internet",
    ],
    correct: 2,
    explain: "El <b>acceso just-in-time</b> abre el puerto solo para la IP que lo pide, durante el tiempo aprobado, y lo vuelve a cerrar: es exactamente el requisito, y vive en <b>Defender for Servers P2</b>. P1 aporta EDR, que es otra cosa. Defender for Resource Manager mira el plano de control, no los puertos. Y Defender CSPM <em>recomienda</em> cerrarlos, pero no da el mecanismo para abrirlos cuando hace falta. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/just-in-time-access-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Elegir plan por el riesgo descrito",
    q: "Una aplicación permite a clientes externos subir ficheros a una cuenta de almacenamiento. El riesgo que preocupa es que suban contenido malicioso. ¿Qué se activa?",
    options: [
      "Defender for Storage, con el análisis de malware en la subida",
      "Defender for App Service, que detecta la ejecución de código sospechoso en la aplicación web",
      "Defender CSPM, para que recomiende deshabilitar el acceso público de la cuenta de almacenamiento",
      "Defender for Servers P2, con la supervisión de integridad de archivos sobre el sistema de ficheros",
    ],
    correct: 0,
    explain: "El riesgo está en <em>lo que se sube</em>, y eso lo cubre <b>Defender for Storage</b>, que analiza el objeto en el momento de la subida y alerta —o permite bloquear— si es malicioso. Defender for App Service mira la aplicación, no el contenido almacenado. Deshabilitar el acceso público es buena postura pero no examina ficheros. Y la integridad de archivos vigila cambios en un sistema de ficheros de servidor, no subidas de clientes. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué habilita Arc",
    q: "Se quiere exigir y auditar una configuración concreta del sistema operativo en servidores Linux que viven en el centro de datos del cliente, con las mismas herramientas que en Azure. ¿Qué lo hace posible?",
    options: [
      "Una directiva de grupo equivalente aplicada desde el Active Directory local de la organización",
      "Un script de configuración ejecutado por la herramienta de despliegue que ya usa el equipo de sistemas",
      "Defender for Servers P1, que despliega Defender for Endpoint sobre esos servidores Linux",
      "Azure Arc, que los proyecta como recursos y habilita Azure Policy con Machine Configuration",
    ],
    correct: 3,
    explain: "<b>Azure Arc</b> es lo que hace que un servidor de fuera exista como <em>recurso de Azure</em>; a partir de ahí se le aplica <b>Azure Policy</b> con <b>Machine Configuration</b>, que audita y corrige la configuración del sistema operativo igual que en una máquina de Azure. La directiva de grupo no llega a Linux. El script no deja evidencia auditable. Y Defender for Servers da EDR, no configuración. <a href=\"https://learn.microsoft.com/en-us/azure/azure-arc/servers/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Arc no es un conector de logs",
    q: "Tras conectar con Arc los servidores del centro de datos, el SOC pregunta por qué sus eventos de seguridad no aparecen en Sentinel. ¿Qué falta?",
    options: [
      "Volver a registrar los servidores en Arc, esta vez desde la suscripción donde vive el espacio de trabajo",
      "Desplegar el agente de Azure Monitor con su regla de recopilación de datos y conectar el origen en Sentinel",
      "Activar Defender CSPM en la suscripción, que es lo que reenvía los eventos de los recursos conectados",
      "Asignar una iniciativa de Azure Policy de auditoría sobre el grupo de administración que contiene los servidores",
    ],
    correct: 1,
    explain: "Arc <b>gobierna</b> el recurso; no transporta sus registros. Para que los eventos lleguen al SIEM hace falta el <b>agente de Azure Monitor</b> —que Arc puede desplegar como extensión— con su <b>regla de recopilación</b>, y el origen conectado en Sentinel. Son dos decisiones distintas, y un enunciado que pide gobernar <em>y</em> correlacionar necesita las dos. <a href=\"https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que no sabías que tenías",
    q: "Tras una fusión, el cliente sospecha que hay dominios y servidores web publicados a su nombre que ningún equipo reclama. Quiere el inventario de lo que un atacante vería desde internet. ¿Qué usas?",
    options: [
      "El inventario de recursos de Defender for Cloud, filtrado por los recursos con dirección IP pública",
      "Un análisis de vulnerabilidades sin agente sobre todas las máquinas de las suscripciones conectadas",
      "Microsoft Defender EASM, partiendo de semillas como los dominios y los rangos de la organización",
      "Los registros de flujo de la red virtual, buscando conexiones entrantes desde direcciones desconocidas",
    ],
    correct: 2,
    explain: "El valor de <b>Defender EASM</b> está justo en lo que no está en tus suscripciones: parte de <b>semillas</b> —dominios, rangos, nombres de organización— y descubre de forma recursiva hosts, subdominios, certificados y páginas que te pertenecen, los conozcas o no. Defender for Cloud solo ve lo que le has conectado, que es exactamente lo que aquí falta. Y los registros de flujo ven tráfico, no inventario. <a href=\"https://learn.microsoft.com/en-us/azure/external-attack-surface-management/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dentro o fuera",
    q: "Al presentar el diseño, alguien propone sustituir Defender EASM por Defender for Cloud «porque ya da postura y sale más barato». ¿Qué respondes?",
    options: [
      "Que es razonable, porque Defender for Cloud también descubre activos externos desde las semillas que se le indiquen",
      "Que miran cosas distintas: Defender for Cloud ve lo conectado, EASM ve lo publicado aunque no lo conozcas",
      "Que es razonable siempre que se active Defender CSPM, que amplía el descubrimiento a los activos de internet",
      "Que solo tiene sentido si además se contrata un servicio externo de pruebas de intrusión periódicas",
    ],
    correct: 1,
    explain: "Es la distinción de la tarea: Defender for Cloud da una vista <b>desde dentro</b> —lo que hay en las suscripciones y cuentas conectadas— y EASM una vista <b>desde fuera</b>, la del atacante, incluido el subdominio de una campaña olvidada o el entorno de pruebas que quedó publicado. Nada de lo que no esté conectado aparece en Defender for Cloud, y ese es justo el problema que el cliente describe. <a href=\"https://learn.microsoft.com/en-us/azure/external-attack-surface-management/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Priorizar de verdad",
    q: "El equipo arrastra miles de recomendaciones abiertas y las va cerrando por severidad, sin que la exposición baje. ¿Qué cambio de proceso propones?",
    options: [
      "Cerrar primero las que afecten a más recursos, para que el número total baje más deprisa",
      "Repartir las recomendaciones entre los equipos propietarios y fijar un objetivo mensual de cierre",
      "Trabajar las rutas de ataque hacia activos críticos y arreglar sus puntos de estrangulamiento",
      "Subir el umbral de severidad para que solo entren en la lista las recomendaciones críticas",
    ],
    correct: 2,
    explain: "Diez críticas en máquinas aisladas importan menos que una media en el camino hacia un controlador de dominio. <b>Security Exposure Management</b> encadena activos y debilidades en <b>rutas de ataque</b>, y señala los puntos donde varias rutas se cruzan: arreglar uno corta muchas a la vez. Contar recursos afectados, repartir la lista o subir el umbral cambian el número, no la exposición. <a href=\"https://learn.microsoft.com/en-us/security-exposure-management/work-attack-paths-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué es crítico para el negocio",
    q: "Las rutas de ataque que salen no coinciden con lo que el negocio considera importante: aparecen entornos de pruebas y no el sistema de facturación. ¿Qué falta configurar?",
    options: [
      "La clasificación de activos críticos, para que la priorización pese el impacto en el negocio",
      "Más conectores de datos, para que el gráfico incluya orígenes que hoy no se están leyendo",
      "Una iniciativa de seguridad específica para el entorno de producción, con su propia métrica de progreso",
      "Etiquetas de recurso en Azure con el nombre del sistema y del equipo propietario de cada carga",
    ],
    correct: 0,
    explain: "El motor sabe qué está expuesto y qué es alcanzable, pero no sabe <em>qué te importa</em> hasta que se lo dices. La <b>gestión de activos críticos</b> es donde se marca —con clasificaciones integradas o propias— qué recursos son críticos para el negocio, y a partir de ahí las rutas y la priorización se ordenan por impacto real. Las etiquetas de Azure documentan, pero no alimentan esa priorización. <a href=\"https://learn.microsoft.com/en-us/security-exposure-management/critical-asset-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Servidores de varias plataformas",
    q: "El parque de servidores mezcla Windows Server, varias distribuciones de Linux y máquinas en AWS. Seguridad quiere detección y respuesta uniforme en todos. ¿Qué propones?",
    options: [
      "Un producto de EDR distinto por plataforma, elegido por el equipo que administra cada una de ellas",
      "Defender for Servers, que lleva Defender for Endpoint a Windows y Linux, en Azure, Arc y AWS",
      "Reglas de análisis en Sentinel sobre los registros del sistema operativo que cada servidor ya genera",
      "Directivas de grupo de endurecimiento en Windows y guías de bastionado revisadas a mano en Linux",
    ],
    correct: 1,
    explain: "<b>Defender for Servers</b> despliega <b>Defender for Endpoint</b> sobre Windows y Linux, y alcanza tanto las máquinas de Azure como las conectadas con Arc y las de AWS y GCP a través de sus conectores: eso es lo que da la uniformidad que pide el enunciado. Un EDR por plataforma multiplica consolas. Los registros en Sentinel dan detección, pero no respuesta en el equipo. Y el endurecimiento previene, no detecta. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-defender-for-servers-select-plan\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Credenciales en el servidor",
    q: "Una aplicación en una máquina virtual guarda en un fichero de configuración la cadena de conexión a una base de datos de Azure. ¿Qué se especifica en el diseño?",
    options: [
      "Cifrar el disco de la máquina con una clave gestionada por el cliente, para proteger ese fichero",
      "Restringir los permisos del fichero al usuario de servicio y auditar quién lo lee con la directiva de auditoría",
      "Rotar la contraseña cada treinta días mediante una automatización que reescriba el fichero de configuración",
      "Usar una identidad administrada de la máquina y quitar la credencial del fichero",
    ],
    correct: 3,
    explain: "El orden de preferencia del examen: <b>identidad administrada</b> primero, secreto en Key Vault después, y secreto en la configuración nunca. Si la aplicación se autentica con la identidad de la máquina, no hay credencial que proteger, cifrar ni rotar. Las otras tres opciones custodian mejor un secreto cuya existencia era el problema. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dispositivo personal, dato corporativo",
    q: "Los comerciales leen el correo corporativo en sus móviles personales. La empresa no puede administrar esos dispositivos, pero necesita impedir que el dato salga a aplicaciones personales. ¿Qué diseñas?",
    options: [
      "Inscribir los dispositivos en Intune con una directiva de cumplimiento ligera, solo para el correo",
      "Bloquear el acceso desde dispositivos no conformes con una política de acceso condicional",
      "Directivas de protección de aplicaciones, que acotan el dato dentro de la aplicación gestionada",
      "Publicar el correo a través de un escritorio virtual al que se conecten desde el móvil personal",
    ],
    correct: 2,
    explain: "«No podemos administrar el dispositivo» descarta la inscripción y descarta también condicionar por cumplimiento, que necesita un dispositivo gestionado. Las <b>directivas de protección de aplicaciones</b> (MAM) protegen el dato <em>dentro</em> de la aplicación —cifrado, sin copiar y pegar a aplicaciones personales, sin guardar en local— sin tocar el resto del móvil. El escritorio virtual resuelve, pero es una infraestructura entera para un problema que ya tiene respuesta. <a href=\"https://learn.microsoft.com/en-us/intune/intune-service/apps/app-protection-policy\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El estado del equipo como señal",
    q: "Se quiere que solo entren a las aplicaciones los equipos corporativos con el cifrado de disco activo y el antivirus al día. ¿Cómo se articula?",
    options: [
      "Una directiva de cumplimiento en Intune y una política de acceso condicional que exija dispositivo conforme",
      "Una regla de Azure Policy sobre los equipos, que impida el acceso a los que no cumplan los requisitos",
      "Una lista de direcciones IP de las oficinas como ubicación de confianza en el acceso condicional",
      "Una revisión mensual del inventario de equipos, retirando el acceso a los que no cumplan",
    ],
    correct: 0,
    explain: "Son dos piezas encajadas: <b>Intune</b> evalúa el equipo contra una <b>directiva de cumplimiento</b> y marca el resultado en la identidad del dispositivo; el <b>acceso condicional</b> consume esa señal con el control «requerir que el dispositivo sea conforme». Azure Policy gobierna recursos de Azure, no equipos cliente. La IP dice dónde está el equipo, no cómo está. Y la revisión mensual llega tarde. <a href=\"https://learn.microsoft.com/en-us/intune/intune-service/protect/device-compliance-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Identidad de un dispositivo IoT",
    q: "Un fabricante va a desplegar cien mil sensores que enviarán telemetría a Azure. El plan actual es incluir la misma clave compartida en la imagen del firmware. ¿Qué recomiendas?",
    options: [
      "Mantener la clave compartida pero rotarla cada seis meses mediante una actualización de firmware masiva",
      "Identidad por dispositivo con certificado X.509 o TPM, provisionada con el Device Provisioning Service",
      "Una clave distinta por lote de fabricación, de forma que el compromiso afecte solo a ese lote de sensores",
      "Cifrar el firmware para que la clave compartida no pueda extraerse del dispositivo con facilidad",
    ],
    correct: 1,
    explain: "Una clave compartida por cien mil dispositivos es un único punto de fallo: quien extraiga una suplanta a todos, y no hay forma de <b>revocar uno solo</b>. El diseño correcto es una <b>identidad por dispositivo</b> —certificado X.509 o clave en TPM— aprovisionada de forma automática con el <b>Device Provisioning Service</b>. Rotar, agrupar por lotes o cifrar el firmware reducen la escala del problema pero no lo cambian. <a href=\"https://learn.microsoft.com/en-us/azure/iot-dps/about-iot-dps\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "IoT de oficina",
    q: "El inventario de la red corporativa deja fuera cámaras, impresoras y controladores de sala, que nadie sabe si están parcheados. No admiten agente. ¿Qué recomiendas?",
    options: [
      "Un análisis de vulnerabilidades autenticado contra cada uno de esos dispositivos, con credencial de administrador",
      "Segmentarlos en una red aislada y darlos por cubiertos, ya que no acceden a datos corporativos",
      "El descubrimiento de Enterprise IoT, que usa los sensores de Defender for Endpoint ya desplegados",
      "Un sensor de red OT de Defender for IoT conectado a un puerto espejo del conmutador principal",
    ],
    correct: 2,
    explain: "Para el <b>IoT de empresa</b> —cámaras, impresoras, dispositivos de sala en la red corporativa— el descubrimiento va con <b>Enterprise IoT</b>, que aprovecha los equipos con Defender for Endpoint ya desplegados como sensores, sin instalar nada en el dispositivo. El sensor OT es la respuesta de la <em>red industrial</em>, no de la ofimática. Segmentar ayuda, pero no da inventario ni vulnerabilidades. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/eiot-defender-for-endpoint\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Visibilidad en planta",
    q: "Una fábrica quiere detectar amenazas en su red de control industrial. La condición es firme: no se instala software en los PLC ni se interrumpe la producción. ¿Qué propones?",
    options: [
      "Defender for Endpoint en las estaciones de ingeniería, como punto de observación de la red industrial",
      "Un análisis activo de la red industrial en la ventana de mantenimiento programada de cada mes",
      "Llevar los registros del historiador y del SCADA a Sentinel y escribir reglas de análisis propias",
      "Un sensor de red de Defender for IoT en modo pasivo, sobre un puerto espejo",
    ],
    correct: 3,
    explain: "En OT no se instala nada y no se sondea: un análisis activo puede tumbar un PLC. <b>Defender for IoT</b> trabaja con un <b>sensor pasivo</b> en un puerto espejo, que entiende los protocolos industriales y de ahí saca inventario, vulnerabilidades y anomalías <em>sin emitir un solo paquete</em>. Las estaciones de ingeniería son un punto ciego parcial, y los registros del SCADA no ven el tráfico entre dispositivos. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La matriz que toca",
    q: "El SOC va a medir su cobertura de detección sobre el entorno industrial que acaba de incorporar. ¿Contra qué matriz de MITRE ATT&CK se evalúa?",
    options: [
      "Contra la matriz ICS, que recoge las técnicas propias de los sistemas de control industrial",
      "Contra la matriz Enterprise, que es la de referencia y cubre cualquier entorno de una organización",
      "Contra la matriz Mobile, por los terminales que los operarios usan en la planta de producción",
      "Contra las tres a la vez, promediando el porcentaje de cobertura que resulte de cada una de ellas",
    ],
    correct: 0,
    explain: "ATT&CK tiene tres matrices y no son intercambiables: <b>Enterprise</b> para sistemas y nube corporativos, <b>Mobile</b> para iOS y Android, e <b>ICS</b> para sistemas de control industrial, con técnicas que solo existen ahí. Un entorno OT se evalúa contra <b>ICS</b>. Promediar las tres mezcla marcos que miden universos distintos y no dice nada útil sobre la brecha real. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Aplicar una línea base",
    q: "Se quiere una línea base de endurecimiento del sistema operativo, aplicada y auditada de forma continua, sobre servidores de Azure y sobre otros conectados con Arc. ¿Con qué?",
    options: [
      "Con una imagen dorada endurecida, redesplegando las máquinas que se desvíen de la configuración",
      "Con Azure Policy y Machine Configuration, que audita y corrige la configuración dentro del servidor",
      "Con las líneas base de seguridad de Intune, asignadas al grupo de dispositivos de los servidores",
      "Con una regla de análisis en Sentinel que alerte cuando cambie un ajuste crítico del sistema operativo",
    ],
    correct: 1,
    explain: "<b>Machine Configuration</b> es la extensión de Azure Policy que mira <em>dentro</em> del sistema operativo: audita la configuración contra una línea base y, si se le permite, la corrige, tanto en máquinas de Azure como en las conectadas con <b>Arc</b>. La imagen dorada fija el punto de partida pero no vigila la desviación. Intune es para clientes. Y una alerta detecta el cambio, no lo impide. <a href=\"https://learn.microsoft.com/en-us/azure/governance/machine-configuration/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Orden de aplicación",
    q: "La línea base nueva de servidores se va a aplicar sobre un parque de ochocientas máquinas heredadas, muchas de ellas con la configuración antigua. ¿Cómo se despliega?",
    options: [
      "En modo de corrección desde el primer día, para que el parque converja cuanto antes a la línea base",
      "Solo sobre las máquinas nuevas, dejando las heredadas con su configuración hasta que se retiren",
      "En modo auditoría para medir la desviación real, remediar por lotes y exigir después",
      "Con una excepción permanente para las máquinas heredadas, documentada como riesgo aceptado",
    ],
    correct: 2,
    explain: "Es el mismo patrón que en gobierno: <b>auditar</b> para conocer el alcance real, <b>remediar</b> por lotes con ventana de cambio, y <b>exigir</b> al final para que la desviación no vuelva. Corregir de golpe ochocientas máquinas heredadas es cómo se rompe producción. Aplicarla solo a lo nuevo o aceptar el riesgo para siempre dejan el parque partido en dos indefinidamente. <a href=\"https://learn.microsoft.com/en-us/azure/governance/machine-configuration/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Contraseña local repetida",
    q: "Un ejercicio de intrusión demuestra que, desde un portátil comprometido, se llega a cualquier otro del parque reutilizando el hash del administrador local. ¿Qué lo corta?",
    options: [
      "Renombrar la cuenta de administrador local en todos los equipos para dificultar su localización",
      "Windows LAPS, con una contraseña distinta por equipo, rotada sola y custodiada en Entra ID",
      "Una directiva de grupo que fije una contraseña larga y distinta para cada departamento de la empresa",
      "Deshabilitar la cuenta de administrador local en todos los equipos del parque de forma permanente",
    ],
    correct: 1,
    explain: "El problema es que la credencial <b>es la misma</b> en todas partes. <b>Windows LAPS</b> la hace única por equipo, la rota sin intervención y guarda la copia en <b>Entra ID</b> o AD DS con lectura acotada y auditada: un equipo comprometido deja de abrir los demás. Renombrar no impide reutilizar el hash. Una contraseña por departamento sigue siendo compartida. Y deshabilitarla deja sin salida al equipo que pierde el dominio. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dónde se guarda la contraseña",
    q: "Al evaluar Windows LAPS para un parque de equipos unidos solo a Entra ID, el equipo pregunta dónde queda la contraseña y quién puede leerla. ¿Qué respondes?",
    options: [
      "Queda cifrada en el propio equipo, y se recupera arrancando en modo de recuperación con una clave maestra",
      "Queda en un almacén de Key Vault por equipo, con una política de acceso por cada administrador del parque",
      "Queda en el objeto de dispositivo de Entra ID, y su lectura se concede por rol y se audita",
      "Queda en un fichero cifrado del recurso compartido de administración, con permisos NTFS restringidos",
    ],
    correct: 2,
    explain: "LAPS respalda la contraseña en el <b>objeto de dispositivo</b> —en <b>Entra ID</b> para equipos unidos a Entra, o en el objeto de equipo de AD DS en un dominio—, la lectura se concede con un rol y cada recuperación <b>queda auditada</b>. Ese rastro es la mitad del valor del control: no solo hay una contraseña distinta por equipo, sino constancia de quién la pidió y cuándo. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Línea base de SaaS",
    q: "La organización usa una veintena de aplicaciones SaaS de terceros y quiere evaluar de forma continua si están configuradas de forma segura. ¿Qué herramienta cubre esa superficie?",
    options: [
      "Azure Policy, con una iniciativa que recoja los ajustes esperados de cada una de las aplicaciones",
      "El panel de cumplimiento normativo de Defender for Cloud, añadiendo el estándar que aplique al sector",
      "El secure score de Defender for Cloud, que cubre los recursos y las aplicaciones conectadas al tenant",
      "La gestión de postura de SaaS de Defender for Cloud Apps",
    ],
    correct: 3,
    explain: "Cada superficie tiene su herramienta y confundirlas es el error típico de esta tarea. IaaS y PaaS: Defender for Cloud y Azure Policy. <b>SaaS de terceros</b>: la <b>gestión de postura de SaaS</b> de <b>Defender for Cloud Apps</b>, que se conecta a la aplicación y evalúa su configuración. Azure Policy no llega a un SaaS ajeno, y el secure score de Defender for Cloud mide recursos de nube, no la configuración de esas aplicaciones. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/security-saas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dónde se fija la línea base de PaaS",
    q: "Se quiere que ningún servicio PaaS nuevo se despliegue con acceso público habilitado, en todas las suscripciones presentes y futuras. ¿Cómo se especifica?",
    options: [
      "Una iniciativa de Azure Policy asignada al grupo de administración, con efecto Deny",
      "Una recomendación de Defender for Cloud asignada a los propietarios de cada suscripción, con fecha límite",
      "Una regla de gobierno que notifique al equipo responsable cada vez que aparezca un recurso público",
      "Una plantilla de infraestructura como código revisada, que el equipo de plataforma publique como estándar",
    ],
    correct: 0,
    explain: "«Presentes y futuras» apunta al <b>grupo de administración</b>, que es donde una asignación alcanza a las suscripciones que aún no existen, y «que no se despliegue» apunta a <b>Deny</b>, que es el control preventivo. Las recomendaciones y las reglas de gobierno de Defender for Cloud avisan y hacen seguimiento, pero no impiden. Y una plantilla estándar solo cubre a quien la use. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La plataforma IoT",
    q: "Al revisar una carga de trabajo IoT, ves que el IoT Hub acepta conexiones desde internet y que todos los dispositivos usan la misma política de acceso compartida del hub. ¿Qué priorizas?",
    options: [
      "Rotar la clave de la política compartida y establecer un calendario de rotación trimestral",
      "Activar el registro de diagnóstico del hub y llevarlo a Sentinel para detectar conexiones anómalas",
      "Credencial por dispositivo con permiso mínimo, y endpoint privado para el hub",
      "Cifrar la telemetría en la aplicación antes de enviarla, además del cifrado en tránsito del protocolo",
    ],
    correct: 2,
    explain: "Son los dos defectos estructurales del diseño y van juntos: una <b>credencial por dispositivo</b> con permiso mínimo —para poder revocar uno sin tocar el resto— y un <b>endpoint privado</b> para que el hub deje de estar publicado. Rotar la clave común mantiene el punto único de fallo. El registro detecta después. Y el cifrado extremo a extremo protege el dato, pero no arregla quién puede conectarse. <a href=\"https://learn.microsoft.com/en-us/azure/iot/iot-overview-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Revocar un dispositivo",
    q: "Se detecta que un lote de dispositivos ha sido manipulado físicamente y hay que cortarles el acceso a la plataforma sin afectar al resto del despliegue. ¿Qué lo hace posible?",
    options: [
      "Bloquear en el cortafuegos las direcciones IP desde las que se conectan esos dispositivos manipulados",
      "Deshabilitar o revocar la identidad individual de cada uno de los dispositivos afectados",
      "Rotar la clave compartida del hub y redistribuirla al resto del parque mediante una actualización",
      "Cambiar el punto de conexión de la plataforma y actualizar solo los dispositivos que siguen siendo de confianza",
    ],
    correct: 1,
    explain: "Aquí se cobra la decisión de diseño anterior: con <b>identidad individual</b>, revocar es deshabilitar esos registros de dispositivo y nada más se entera. Con clave compartida habría que rotarla y redistribuirla a todo el parque, que es la opción tres y explica por qué la clave común es mala idea. La IP cambia. Y mover el punto de conexión es rehacer el despliegue entero. <a href=\"https://learn.microsoft.com/en-us/azure/iot/iot-overview-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Global o regional",
    q: "Una aplicación web se sirve desde tres regiones, con conmutación entre ellas, y necesita filtrado de capa de aplicación en el borde. ¿Qué eliges?",
    options: [
      "Application Gateway con WAF en cada región, y resolución DNS ponderada por la latencia del cliente",
      "Azure Firewall Premium con inspección de TLS delante de los servidores de la aplicación web",
      "Azure Front Door con WAF, que es global y enruta al origen sano más cercano",
      "Un grupo de seguridad de red por subred, con reglas que permitan solo los puertos 80 y 443",
    ],
    correct: 2,
    explain: "Los dos servicios llevan WAF y la diferencia es el alcance: <b>Front Door</b> es <b>global</b> —entra cuando hay varias regiones, latencia mundial o conmutación—, y <b>Application Gateway</b> es <b>regional</b>, dentro de la red virtual, para cuando el tráfico no debe salir de ella. Azure Firewall filtra red y protocolo, no peticiones HTTP. Y un grupo de seguridad de red abre puertos: no mira el contenido. <a href=\"https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/afds-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Saltarse el borde",
    q: "Se despliega Front Door con WAF delante de una aplicación en App Service. Una prueba demuestra que el atacante llega al App Service por su dirección pública y esquiva el WAF. ¿Qué falta?",
    options: [
      "Restringir el origen para que solo acepte tráfico del servicio de borde, por enlace privado o filtrado",
      "Activar el modo de prevención en el WAF, que hasta ahora estaba trabajando solo en modo de detección",
      "Añadir Azure DDoS Protection sobre la red virtual donde está publicada la aplicación web",
      "Ampliar el conjunto de reglas gestionadas del WAF para que cubra también el tráfico que llega directo",
    ],
    correct: 0,
    explain: "Un WAF solo protege el tráfico que <b>pasa por él</b>. Si el origen sigue aceptando peticiones de cualquiera, el borde es opcional para el atacante. Lo que cierra el hueco es <b>bloquear el origen</b>: enlace privado desde Front Door, o filtrado que solo acepte tráfico del servicio de borde. Cambiar el modo o las reglas mejora un WAF que en este camino ni siquiera se atraviesa. <a href=\"https://learn.microsoft.com/en-us/azure/frontdoor/origin-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Control en cada fase",
    q: "Un cliente quiere impedir que lleguen a producción contenedores privilegiados y contenedores con vulnerabilidades críticas conocidas. ¿Qué DOS controles incluye el diseño?",
    options: [
      "Detección en tiempo de ejecución en los nodos, con las alertas de Defender for Containers",
      "Análisis de vulnerabilidades de las imágenes en el registro y en el pipeline de construcción",
      "Control de admisión en el clúster con Azure Policy para Kubernetes, que rechace lo no conforme",
      "Directivas de red entre pods, para que un contenedor comprometido no alcance a los demás",
    ],
    correct: [1, 2],
    explain: "El enunciado dice <em>«impedir que lleguen»</em>, así que los dos controles son preventivos y actúan en fases distintas: el <b>análisis de la imagen</b> encuentra la vulnerabilidad antes de publicarla, y el <b>control de admisión</b> rechaza en el propio clúster el manifiesto que pide privilegios. La detección en ejecución y las directivas de red son buenas piezas del diseño, pero actúan cuando el contenedor ya está dentro. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/policy-for-kubernetes\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Secretos en el contenedor",
    q: "Una aplicación en contenedor necesita la cadena de conexión de una base de datos. El equipo la pasa hoy como variable de entorno en el manifiesto, que vive en el repositorio. ¿Qué propones?",
    options: [
      "Mover la variable a un secreto de Kubernetes, que el clúster almacena aparte del manifiesto",
      "Cifrar el manifiesto en el repositorio y descifrarlo en el pipeline en el momento del despliegue",
      "Inyectar la variable desde el sistema de integración continua, para que no quede escrita en el repositorio",
      "Autenticar con identidad de carga de trabajo, sin secreto que pasar",
    ],
    correct: 3,
    explain: "Igual que en las máquinas: lo mejor es que <b>no haya secreto</b>. Con <b>identidad de carga de trabajo</b> el pod obtiene un token federado de Entra ID y accede a la base de datos sin credencial almacenada en ninguna parte. Las otras tres mejoran <em>dónde</em> se guarda el secreto —y el secreto de Kubernetes va codificado, no cifrado, por defecto—, pero el secreto sigue existiendo. <a href=\"https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Quién entra al clúster",
    q: "En un clúster de AKS, los desarrolladores comparten un fichero kubeconfig con credenciales de administrador del clúster. Se quiere acceso por persona, revocable y auditable. ¿Qué diseñas?",
    options: [
      "Un kubeconfig por persona, generado con su propio certificado de cliente y renovado cada trimestre",
      "Integración con Entra ID y Azure RBAC para Kubernetes, con roles por espacio de nombres",
      "Un servidor intermedio desde el que los desarrolladores ejecuten los comandos contra el clúster",
      "Roles y vinculaciones de RBAC de Kubernetes asociados a cuentas de servicio del propio clúster",
    ],
    correct: 1,
    explain: "La <b>integración con Entra ID</b> hace que el acceso al servidor de API use la identidad de la persona, con lo que le aplican MFA, acceso condicional y PIM, y queda registrado; <b>Azure RBAC para Kubernetes</b> permite además asignar roles por ámbito desde Azure. Los certificados por persona y las cuentas de servicio del clúster son credenciales fuera del directorio: ni revocación central ni señales de riesgo. <a href=\"https://learn.microsoft.com/en-us/azure/aks/concepts-identity\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Exponer el plano de control",
    q: "El servidor de API de un clúster de AKS de producción responde en internet. El equipo argumenta que está protegido porque exige autenticación con Entra ID. ¿Qué recomiendas?",
    options: [
      "Dejarlo así, ya que exigir Entra ID con MFA es suficiente para proteger el servidor de API",
      "Publicar el servidor de API detrás de un WAF con reglas gestionadas para las llamadas a la API",
      "Clúster privado, o rangos de IP autorizados si el acceso desde fuera es imprescindible",
      "Rotar las credenciales del clúster cada treinta días y auditar los accesos al servidor de API",
    ],
    correct: 2,
    explain: "La autenticación es necesaria pero no es la única capa: un plano de control publicado sigue siendo alcanzable por cualquiera, y con eso llega la enumeración y cualquier fallo del propio servidor. Se cierra con un <b>clúster privado</b> —el servidor de API solo tiene endpoint interno— o, si hace falta administrarlo desde fuera, con <b>rangos de IP autorizados</b>. Un WAF entiende HTTP de aplicación, no la API de Kubernetes. <a href=\"https://learn.microsoft.com/en-us/azure/aks/private-clusters\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Acceso al servicio de IA",
    q: "Una aplicación interna consume un modelo de Azure OpenAI usando la clave del recurso, guardada en la configuración de la aplicación. ¿Qué especificas en el diseño?",
    options: [
      "Deshabilitar la autenticación por clave y usar Entra ID con la identidad administrada de la aplicación",
      "Guardar la clave en Key Vault y leerla al arrancar la aplicación, con rotación cada noventa días",
      "Restringir por dirección IP el acceso al recurso, de modo que la clave solo sirva desde la aplicación",
      "Rotar la clave del recurso cada vez que alguien del equipo de desarrollo cambie de proyecto",
    ],
    correct: 0,
    explain: "Un servicio de IA es un recurso de Azure más y le aplica el mismo orden de preferencia: <b>identidad administrada y Entra ID</b> por delante de cualquier clave, y desactivar la autenticación local para que la clave deje de ser una vía. Key Vault y la rotación custodian mejor un secreto que puede dejar de existir. El filtrado por IP acota desde dónde, pero la clave sigue siendo un dato que se filtra. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/security-features\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El riesgo propio de la IA",
    q: "Un asistente interno responde preguntas leyendo documentos que suben los usuarios. Preocupa que un documento contenga instrucciones que redirijan el comportamiento del modelo. ¿Qué lo aborda?",
    options: [
      "Un endpoint privado para el recurso de IA y acceso público deshabilitado en el servicio",
      "Claves gestionadas por el cliente sobre el almacenamiento donde se guardan los documentos subidos",
      "Una política de acceso condicional que exija dispositivo conforme para usar el asistente",
      "Filtros de contenido y escudos de prompt frente a la inyección directa e indirecta",
    ],
    correct: 3,
    explain: "Lo que describe el enunciado es <b>inyección indirecta de instrucciones</b>: el contenido que el modelo lee acaba dirigiendo lo que hace. Ninguna medida de red, de cifrado o de identidad lo evita, porque el atacante no necesita acceso: le basta con que su documento se lea. Se aborda con los <b>filtros de contenido y los escudos de prompt</b> del propio servicio, y acotando lo que el modelo puede hacer con la identidad que se le da. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Endpoint privado o de servicio",
    q: "El requisito dice que una cuenta de almacenamiento solo debe ser accesible desde la red virtual de la aplicación. El equipo propone un endpoint de servicio. ¿Qué señalas?",
    options: [
      "Que el endpoint de servicio sirve, siempre que además se abra un grupo de seguridad de red hacia el servicio de almacenamiento",
      "Que el endpoint de servicio no da dirección privada al recurso: hace falta endpoint privado y acceso público deshabilitado",
      "Que el endpoint de servicio sirve, porque el tráfico deja de salir a internet y viaja por la red de Azure",
      "Que ninguno de los dos cumple el requisito y hay que mover el dato a un servidor de ficheros propio",
    ],
    correct: 1,
    explain: "El <b>endpoint de servicio</b> mantiene el tráfico dentro de la red troncal de Azure y permite filtrar por red virtual, pero el recurso <em>sigue teniendo una dirección pública</em>. El <b>endpoint privado</b> le da una dirección <b>privada</b> dentro de tu red y, con el acceso público deshabilitado, deja de ser alcanzable desde fuera. Cuando el requisito dice «solo desde la red virtual», es endpoint privado. <a href=\"https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Reglas que no envejecen",
    q: "Los grupos de seguridad de red de un entorno tienen cientos de reglas con direcciones IP fijas, y cada despliegue obliga a revisarlas. ¿Qué cambio propones?",
    options: [
      "Consolidar las reglas en un único grupo de seguridad de red aplicado a todas las subredes del entorno",
      "Sustituir los grupos de seguridad de red por reglas de Azure Firewall centralizadas en el hub",
      "Grupos de seguridad de aplicación, para que las reglas hablen de roles y no de direcciones",
      "Reservar direcciones IP estáticas para cada carga de trabajo, de modo que las reglas dejen de cambiar",
    ],
    correct: 2,
    explain: "Los <b>grupos de seguridad de aplicación</b> agrupan interfaces por función —<em>web</em>, <em>aplicación</em>, <em>base de datos</em>— y las reglas se escriben entre esos grupos: una máquina nueva hereda su política por pertenecer al grupo, sin tocar ninguna regla. Consolidar en un solo grupo empeora la legibilidad, el cortafuegos del hub no sustituye al filtrado entre subredes, y fijar direcciones perpetúa el problema. <a href=\"https://learn.microsoft.com/en-us/azure/virtual-network/application-security-groups\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La política sigue al usuario",
    q: "Con el trabajo híbrido, la navegación de los portátiles ya no pasa por el proxy del centro de datos y el filtrado web se aplica solo en la oficina. ¿Qué propones?",
    options: [
      "Microsoft Entra Internet Access, con filtrado web y acceso condicional aplicados esté donde esté el usuario",
      "Retornar todo el tráfico de internet al centro de datos por la VPN, para que vuelva a pasar por el proxy",
      "Un proxy local instalado en cada portátil, con la lista de categorías bloqueadas distribuida por Intune",
      "Reglas de Azure Firewall Premium sobre la red virtual, aplicadas al tráfico de salida de los usuarios",
    ],
    correct: 0,
    explain: "<b>Entra Internet Access</b> es la pasarela web segura de la familia SSE: el cliente reenvía la navegación al servicio de Microsoft, donde se aplica el <b>filtrado web</b> y —lo que lo separa de un proxy clásico— el mismo <b>acceso condicional</b> que gobierna las aplicaciones, con la identidad y el estado del dispositivo como señales. La política deja de depender de por dónde va el tráfico. Retornarlo todo a la sede es justo lo que se quiere evitar. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-internet-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Filtrado por identidad",
    q: "Se quiere permitir a un grupo concreto el acceso a una categoría de sitios que está bloqueada para el resto de la organización. ¿Qué lo hace posible en el diseño de SSE?",
    options: [
      "Una excepción por dirección IP de origen, aplicada al rango desde el que trabaja ese grupo de usuarios",
      "Un segundo perfil de reenvío de tráfico, asignado a los dispositivos que utilizan las personas de ese grupo",
      "Una directiva de filtrado asignada por grupo, ya que la decisión se toma sobre la identidad del usuario",
      "Una regla de aplicación en Azure Firewall Premium que permita esos nombres de dominio completos",
    ],
    correct: 2,
    explain: "Que la pasarela conozca <b>quién</b> navega es la diferencia de fondo frente a un proxy de red: la directiva se asigna por <b>usuario o grupo</b> del directorio y viaja con la persona, sin importar el dispositivo ni la red. La excepción por IP vuelve a atar la política al lugar. Y Azure Firewall filtra tráfico de la red virtual, no la navegación del portátil que está en casa. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-internet-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Un token robado fuera de la red",
    q: "Tras un robo de tokens, se busca que un token de sesión no sirva si la petición no llega a través de la infraestructura corporativa, sin depender de listas de direcciones IP. ¿Qué se usa?",
    options: [
      "Una ubicación con nombre en el acceso condicional que agrupe los rangos públicos de todas las sedes",
      "La condición de red conforme en el acceso condicional, con el perfil de tráfico de Microsoft",
      "Frecuencia de inicio de sesión reducida a una hora para todas las aplicaciones del tenant",
      "Restricciones de tenant v2 sobre los dispositivos gestionados del parque corporativo",
    ],
    correct: 1,
    explain: "La condición de <b>red conforme</b> exige que la petición llegue por el servicio de acceso seguro global; el marcador no se puede reproducir desde fuera, así que un token exfiltrado no vale en otra red. Es más fuerte que una <b>ubicación con nombre</b> por IP, que se falsifica con cualquier salida por la red corporativa. La frecuencia de inicio acorta la ventana pero no la cierra, y las restricciones de tenant resuelven otro problema. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-compliant-network\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Iniciar sesión en otro tenant",
    q: "Se detecta que empleados suben documentos corporativos a cuentas de Microsoft 365 de otras organizaciones desde el portátil de empresa. ¿Qué control lo impide?",
    options: [
      "Una política de prevención de pérdida de datos de Purview sobre los canales de red de esos equipos",
      "Bloquear los dominios de terceros en el filtrado web de Entra Internet Access para toda la organización",
      "Configuración de acceso entre tenants, restringiendo qué organizaciones externas pueden invitar usuarios",
      "Restricciones de tenant v2, que impiden iniciar sesión en tenants ajenos desde el dispositivo corporativo",
    ],
    correct: 3,
    explain: "Las <b>restricciones de tenant v2</b> hacen justo eso: desde un dispositivo o una red gestionada, solo se puede iniciar sesión en los tenants que la organización permite, de modo que la cuenta ajena deja de ser una salida. La configuración de acceso entre tenants gobierna la colaboración <em>entrante y saliente de tu propio tenant</em>, no el inicio de sesión en otro. Y bloquear el dominio de Microsoft 365 rompería también el uso legítimo. <a href=\"https://learn.microsoft.com/en-us/entra/external-id/tenant-restrictions-v2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Sustituir la VPN",
    q: "Los proveedores externos acceden hoy por VPN a una aplicación interna, y una vez dentro alcanzan toda la red. Se quiere acotarlo a esa sola aplicación. ¿Qué propones?",
    options: [
      "Microsoft Entra Private Access, publicando la aplicación con su propia política de acceso condicional",
      "Mantener la VPN y segmentar la red interna para que el rango de los proveedores solo llegue a esa aplicación",
      "Publicar la aplicación en internet con autenticación de Entra ID y una restricción por dirección IP de origen",
      "Un escritorio virtual por proveedor, desde el que se acceda a la aplicación interna dentro de la red",
    ],
    correct: 0,
    explain: "<b>Entra Private Access</b> concede acceso <b>a una aplicación</b>, no a una red: un conector instalado junto a ella abre la conexión hacia fuera, no se publica nada, y cada aplicación es un recurso con su propia política de acceso condicional evaluada en cada sesión. Segmentar la VPN mejora el radio pero sigue dando red y sigue publicando el concentrador. Publicar la aplicación la expone a internet. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué se publica hacia fuera",
    q: "Al comparar Entra Private Access con la VPN existente, la dirección pregunta qué mejora en concreto. ¿Qué DOS afirmaciones son correctas?",
    options: [
      "Que cifra el tráfico entre el cliente y la aplicación, cosa que la VPN actual no hace en todos los casos",
      "Que reduce la latencia porque el tráfico deja de atravesar la infraestructura de la organización",
      "Que no hay concentrador publicado: el conector abre la conexión hacia el servicio desde dentro",
      "Que cada aplicación se evalúa con acceso condicional en cada sesión, y no solo al montar el túnel",
    ],
    correct: [2, 3],
    explain: "Las dos que sostienen el argumento de confianza cero: <b>no se publica nada</b> —el conector inicia la conexión de dentro hacia fuera, así que no hay concentrador expuesto que atacar— y la decisión se toma <b>por aplicación y en cada sesión</b> con acceso condicional, en vez de una sola vez al establecer el túnel. El cifrado también lo hace una VPN, y la latencia depende del despliegue: ninguna de las dos es la diferencia de seguridad. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["infrastructure"] = QUIZ_DATA;
