var QUIZ_DATA = [
  {
    tag: "Envelope encryption",
    q: "¿Por qué KMS usa 'envelope encryption' (cifrar los datos con una data key, y esa data key con la CMK) en vez de cifrar directamente los datos con la KMS key?",
    options: [
      "Porque las operaciones Encrypt y Decrypt de KMS están limitadas a 4 KB de payload por llamada",
      "Porque una KMS key solo puede cifrar otras claves: no admite datos de aplicación como entrada",
      "Porque HIPAA obliga a que los datos de salud se cifren con dos claves distintas encadenadas",
      "Porque KMS factura por cada byte cifrado y la data key reduce el volumen facturable enviado",
    ],
    correct: 0,
    explain: "Las operaciones <code>Encrypt</code>/<code>Decrypt</code> directas de KMS están limitadas a ~4 KB de payload. Para cifrar objetos grandes se genera una data key (<code>GenerateDataKey</code>), se cifran los datos localmente con ella (sin límite de tamaño) y solo la data key —pequeña— viaja a KMS para cifrarse o descifrarse: de ahí el 'sobre'. El coste de KMS es por petición, no por byte, y una KMS key sí puede cifrar datos, simplemente muy pocos. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Envelope encryption",
    q: "Tras usar GenerateDataKey para cifrar un archivo grande localmente, ¿qué debe hacer la aplicación con la data key en texto plano una vez terminado el cifrado?",
    options: [
      "Guardarla junto al archivo cifrado, para no tener que llamar a KMS al descifrarlo",
      "Borrarla de memoria en cuanto termina el cifrado, conservando solo su versión cifrada",
      "Devolverla a KMS con ImportKeyMaterial para que el servicio la custodie por ti",
      "Envolverla en una segunda data key distinta, para añadir una capa extra de cifrado",
    ],
    correct: 1,
    explain: "<code>GenerateDataKey</code> devuelve DOS versiones: la data key en texto plano (se usa una vez y se descarta de memoria) y la data key cifrada por la KMS key, que sí se guarda junto a los datos. Para descifrar se manda la copia cifrada a <code>Decrypt</code>. Guardar la copia en claro junto al archivo anula por completo el cifrado, y <code>ImportKeyMaterial</code> sirve para BYOK, no para custodiar data keys. <a href=\"https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Tipos de KMS keys",
    q: "¿Cuál es la diferencia principal entre una AWS managed key (ej. aws/s3) y una customer managed key (CMK) en KMS?",
    options: [
      "Las AWS managed keys son gratuitas y las customer managed cuestan; por lo demás son idénticas",
      "Las AWS managed keys se pueden replicar como multi-Region keys y las customer managed no",
      "Solo las customer managed keys admiten key policy propia, rotación configurable y borrado programado",
      "Las AWS managed keys son asimétricas por defecto, mientras que las customer managed son siempre simétricas",
    ],
    correct: 2,
    explain: "Las AWS managed keys (prefijo <code>aws/</code>) las crea y gestiona AWS para un servicio concreto: rotación anual obligatoria, key policy no editable y sin posibilidad de deshabilitarlas ni compartirlas entre cuentas. Las customer managed keys dan control total —key policy propia, rotación configurable, deshabilitación y eliminación programada— y son las únicas que soportan multi-Region. Ambos tipos son simétricos por defecto. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "KMS grants",
    q: "¿Para qué se usa un KMS grant en vez de modificar la key policy directamente?",
    options: [
      "Conceder permisos permanentes sobre la key que prevalecen sobre lo que diga la key policy",
      "Es simplemente otro nombre para la política de identidad que se adjunta a un rol o a un usuario de IAM",
      "Es el único mecanismo válido para autorizar operaciones sobre KMS keys asimétricas y HMAC",
      "Delegar permisos temporales sobre una key de forma programática, revocables sin tocar la key policy",
    ],
    correct: 3,
    explain: "Los grants son un mecanismo de delegación más granular y dinámico que la key policy: se crean y retiran por API (<code>CreateGrant</code>, <code>RetireGrant</code>, <code>RevokeGrant</code>) y son la vía por la que un servicio de AWS obtiene acceso temporal a tu key en tu nombre (por ejemplo EBS al cifrar un volumen). No sustituyen a la key policy —de hecho necesitan que esta permita <code>kms:CreateGrant</code>— ni están limitados a un tipo de clave. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/grants.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "KMS multi-Region keys",
    q: "Tienes una Multi-Region KMS key primaria en eu-west-1 replicada como réplica en us-east-1. Un objeto S3 se cifró con la réplica en us-east-1. ¿Puede descifrarse usando la key primaria en eu-west-1?",
    options: [
      "Sí: primaria y réplicas comparten el mismo material criptográfico, aunque tengan Key IDs distintos",
      "No: cada réplica se genera con su propio material criptográfico, totalmente independiente de la primaria",
      "Solo si ambas claves pertenecen a la misma cuenta y el objeto se copia con S3 Replication",
      "Solo tras crear una tercera key que combine el material de la primaria y el de la réplica",
    ],
    correct: 0,
    explain: "Crear KMS keys 'iguales' de forma independiente en cada Región produce material criptográfico DISTINTO y ciphertexts incompatibles. Las Multi-Region keys, en cambio, son réplicas que comparten el mismo material: lo cifrado con una se descifra con cualquier otra, sin re-cifrar los datos. Es la base de los escenarios de DR y de aplicaciones activas en varias Regiones. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "KMS vs CloudHSM",
    q: "Una empresa de servicios financieros necesita FIPS 140-2 Level 3, control exclusivo (single-tenant) del hardware criptográfico, y la capacidad de exportar el material de claves si migran de proveedor. ¿Qué servicio encaja mejor?",
    options: [
      "AWS KMS con customer managed keys, que también permite exportar el material de la clave",
      "AWS CloudHSM, que ofrece HSM dedicado single-tenant y permite exportar el material de clave",
      "AWS Secrets Manager, que custodia material criptográfico y lo rota de forma automática",
      "Amazon Macie, que clasifica los datos sensibles y gestiona las claves que los protegen",
    ],
    correct: 1,
    explain: "KMS es multi-tenant (con fuertes garantías de aislamiento) y NUNCA permite exportar el material de una clave: es su garantía fundamental. CloudHSM entrega un cluster de HSM dedicado, FIPS 140-2 Level 3, con control total del ciclo de vida y exportación de claves, a cambio de que la operación del cluster (alta disponibilidad, backups, usuarios criptográficos) sea tuya. Macie clasifica datos, no gestiona claves. <a href=\"https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Imported key material",
    q: "¿Qué limitación tienen las KMS keys con material de clave IMPORTADO (BYOK) que NO tienen las generadas por AWS?",
    options: [
      "No pueden usarse en operaciones de cifrado de datos, únicamente para firmar y verificar firmas",
      "Solo se pueden usar con Amazon S3, no con el resto de servicios integrados con KMS",
      "No admiten la rotación automática anual gestionada por AWS: hay que rotarlas manualmente",
      "No admiten key policy propia: heredan siempre la política por defecto de la cuenta",
    ],
    correct: 2,
    explain: "Al importar tu propio material (origen <code>EXTERNAL</code>), AWS no puede regenerarlo y por tanto no ofrece rotación automática anual. Puedes fijar una fecha de expiración del material y rotar bajo demanda con <code>RotateKeyOnDemand</code> importando material nuevo, o crear una key nueva. Fuera de eso, la key se comporta como cualquier otra: cifra datos, se integra con los servicios y tiene su propia key policy. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "External Key Store (XKS)",
    q: "¿Qué resuelve un KMS External Key Store (XKS)?",
    options: [
      "Que KMS genere y entregue claves más deprisa al saltarse la validación FIPS del HSM subyacente",
      "Sustituye a CloudHSM aportando un cluster de HSM gestionado por completo por AWS",
      "Guardar copias de respaldo del material de las KMS keys en un bucket S3 cifrado",
      "Que el material de clave resida fuera de AWS, en tu gestor de claves, usando la API de KMS",
    ],
    correct: 3,
    explain: "XKS conecta KMS con un gestor de claves externo (on-premises o de un tercero) a través de un XKS proxy que tú operas: el material de clave NUNCA entra en AWS y KMS no puede crearlo ni verlo, pero los servicios integrados siguen usando la clave con la API estándar. Es la opción de máxima soberanía de clave manteniendo la integración nativa; no acelera nada ni reemplaza a CloudHSM, que sí vive dentro de AWS. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/keystore-external.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 Object Lock",
    q: "¿Cuál es la diferencia entre el modo Governance y el modo Compliance en S3 Object Lock?",
    options: [
      "Governance admite excepción con s3:BypassGovernanceRetention; Compliance no admite ninguna",
      "Son sinónimos y el nombre que aparece depende únicamente de la Región en la que se cree el bucket",
      "Compliance solo puede aplicarse en buckets que tengan el versionado deshabilitado",
      "Governance protege los objetos de acceso público y Compliance los objetos privados",
    ],
    correct: 0,
    explain: "Ambos modos implementan WORM (Write Once Read Many). <strong>Governance</strong> deja una válvula de escape para principals con el permiso <code>s3:BypassGovernanceRetention</code>, útil para probar retenciones antes de comprometerse. <strong>Compliance</strong> es absoluto: fijado el retention period, ni el usuario root puede borrar ni acortar la retención hasta que expire. Se usa para requisitos regulatorios estrictos como SEC 17a-4. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Glacier Vault Lock",
    q: "¿Qué caracteriza a una política de Glacier Vault Lock una vez que se confirma (lock-policy)?",
    options: [
      "El administrador de la cuenta puede seguir editándola libremente en cualquier momento posterior",
      "Se vuelve inmutable: ya no puede modificarse ni eliminarse por ningún principal, ni root",
      "Caduca automáticamente a los 90 días y hay que volver a confirmarla desde cero",
      "Solo protege los archivos del vault cuyo tamaño sea inferior a 1 MB comprimidos",
    ],
    correct: 1,
    explain: "Vault Lock se aplica en dos pasos: al iniciarlo la política queda 'in progress' durante 24 horas para que la valides, y si la confirmas (<code>CompleteVaultLock</code>) pasa a ser permanente e inmutable. Ni el propietario de la cuenta puede alterarla después, lo que da un control de cumplimiento verificable —el equivalente en Glacier al modo Compliance de S3 Object Lock. <a href=\"https://docs.aws.amazon.com/amazonglacier/latest/dev/vault-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Integridad de datos",
    q: "Para verificar que un artefacto de software (ej. un binario descargado) no ha sido alterado en tránsito ni manipulado por un tercero, ¿qué mecanismo de AWS es el más apropiado?",
    options: [
      "S3 Versioning, que conserva cada versión y permite comparar el binario con la anterior",
      "MFA Delete en el bucket, que exige un segundo factor antes de sobrescribir el binario",
      "AWS Signer, que firma digitalmente el código para que el receptor verifique su integridad",
      "AWS Backup, que calcula el hash de cada copia y alerta cuando el binario ha cambiado",
    ],
    correct: 2,
    explain: "AWS Signer firma digitalmente código —paquetes de Lambda, imágenes de contenedor en ECR, firmware IoT— gestionando por ti las claves y el certificado de code signing. El receptor valida la firma antes de ejecutar y detecta cualquier alteración posterior a la publicación. Versioning, MFA Delete y Backup protegen el objeto almacenado frente a borrado o sobrescritura, pero no acreditan la autoría ni la integridad del artefacto. <a href=\"https://docs.aws.amazon.com/signer/latest/developerguide/Welcome.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Lifecycle & retención",
    q: "Necesitas que los objetos de un bucket S3 se muevan automáticamente a Glacier Deep Archive tras 180 días y se eliminen definitivamente tras 7 años, sin intervención manual. ¿Qué mecanismo usas?",
    options: [
      "S3 Object Lock en modo Compliance, con un periodo de retención fijado en siete años",
      "Cross-Region Replication, indicando Glacier Deep Archive como clase de almacenamiento destino",
      "AWS Backup con un plan diario y una regla de ciclo de vida de siete años de retención",
      "S3 Lifecycle, con una regla de transición a los 180 días y una de expiración a los 7 años",
    ],
    correct: 3,
    explain: "Las S3 Lifecycle rules automatizan exactamente este patrón: acciones de <strong>transition</strong> entre clases de almacenamiento según la antigüedad del objeto y acciones de <strong>expiration</strong> que lo eliminan pasado el plazo. Object Lock impide borrar antes de tiempo pero no mueve ni elimina nada; la replicación copia objetos a otro bucket; AWS Backup gestiona recursos respaldados, no los objetos vivos del bucket. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Backup & ransomware",
    q: "Como protección contra ransomware que cifra o borra tus datos de producción (incluyendo intentos de eliminar los backups), ¿qué característica de AWS Backup es la más relevante?",
    options: [
      "AWS Backup Vault Lock, que aplica WORM al vault e impide borrar copias antes de tiempo",
      "El cifrado en tránsito de las copias, que impide interceptarlas mientras se transfieren",
      "Aumentar la frecuencia del plan a copias horarias para reducir la ventana de pérdida",
      "Copiar los backups a otra Región, ya que el ransomware no puede cruzar fronteras regionales",
    ],
    correct: 0,
    explain: "Backup Vault Lock lleva el principio WORM al vault completo: en modo compliance, transcurrido el periodo de gracia (mínimo 72 horas) ni el root ni un administrador comprometido pueden borrar los recovery points ni acortar su retención. El cifrado en tránsito no impide un borrado, más frecuencia solo multiplica las copias que el atacante puede borrar, y una copia cross-Region sigue siendo borrable con credenciales válidas. <a href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/vault-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS DataSync vs Backup vs DLM",
    q: "¿Cuál de estas afirmaciones distingue correctamente AWS DataSync de AWS Backup?",
    options: [
      "Son el mismo motor de transferencia, con dos nombres comerciales y dos consolas",
      "DataSync migra y sincroniza datos entre sistemas; AWS Backup programa y retiene copias",
      "DataSync solo admite bases de datos relacionales; AWS Backup solo admite ficheros",
      "AWS Backup no admite EFS ni FSx; para esos dos sistemas de archivos hay que usar DataSync",
    ],
    correct: 1,
    explain: "DataSync mueve y sincroniza datos entre NFS/SMB, almacenamiento de objetos y servicios de AWS: es la herramienta de migración y de transferencias recurrentes on-premises↔AWS. AWS Backup centraliza políticas de copia (programación, retención, copia cross-Region y cross-account) sobre EBS, RDS, DynamoDB, EFS, FSx y más. Amazon Data Lifecycle Manager (DLM) cubre un nicho distinto: snapshots de EBS y AMIs. <a href=\"https://docs.aws.amazon.com/datasync/latest/userguide/what-is-datasync.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "TLS en tránsito",
    q: "Quieres forzar que todos los clientes que se conecten a tu Application Load Balancer usen TLS 1.2 o superior, rechazando cifrados obsoletos. ¿Qué configuras?",
    options: [
      "Una regla del security group que bloquee el puerto 80 y solo deje pasar el 443",
      "Una bucket policy con la condición s3:TlsVersion aplicada sobre el origen del ALB",
      "Una security policy en el listener HTTPS del ALB que exija TLS 1.2 como versión mínima",
      "Una NACL en la subnet del ALB que descarte los paquetes negociados con cifrados obsoletos",
    ],
    correct: 2,
    explain: "Los listeners HTTPS/TLS de ELB usan <em>security policies</em> predefinidas que fijan qué versiones de TLS y qué cipher suites se negocian; elegir una moderna (por ejemplo <code>ELBSecurityPolicy-TLS13-1-2-2021-06</code>) exige TLS 1.2 como mínimo. Security groups y NACLs trabajan a nivel de puerto e IP: pueden cerrar el 80, pero no ven la versión de TLS negociada dentro de la conexión. <a href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/describe-ssl-policies.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Conectividad privada",
    q: "¿Cuál es la diferencia principal entre AWS PrivateLink y un VPC Peering para acceder a un servicio en otra VPC/cuenta?",
    options: [
      "Son la misma tecnología: PrivateLink es el nombre comercial del VPC peering actual",
      "PrivateLink solo funciona entre cuentas que pertenezcan a la misma AWS Organization o a la misma OU",
      "El VPC peering es más seguro porque cifra el tráfico, cosa que PrivateLink no hace",
      "PrivateLink expone un único servicio por endpoint; el peering conecta las dos VPC enteras",
    ],
    correct: 3,
    explain: "PrivateLink publica UN servicio concreto detrás de un endpoint: el consumidor no ve el resto de la VPC del proveedor y los CIDR pueden solaparse sin problema, lo que lo hace ideal para SaaS y para exponer servicios entre cuentas sin relación de confianza total. El VPC peering une dos redes completas de forma bidireccional, exige CIDR sin solape y expone potencialmente todo lo alcanzable en el otro lado. <a href=\"https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Client VPN vs Verified Access",
    q: "¿En qué se diferencia AWS Verified Access de AWS Client VPN?",
    options: [
      "Client VPN abre un túnel de red y el usuario entra en la VPC; Verified Access nunca lo hace",
      "Son el mismo servicio: Verified Access es simplemente el nombre comercial nuevo de AWS Client VPN",
      "Verified Access solo publica aplicaciones on-premises, nunca aplicaciones en la VPC",
      "Client VPN no admite MFA ni federación, y por eso se sustituye por Verified Access",
    ],
    correct: 0,
    explain: "Client VPN es acceso remoto clásico: se levanta un túnel (full o split) y el cliente pasa a ser un nodo más de la red. Verified Access implementa Zero Trust Network Access: evalúa en CADA petición HTTP las señales del trust provider —identidad vía IAM Identity Center y postura del dispositivo— y publica la aplicación sin conceder acceso de red general. Client VPN sí admite federación SAML y MFA. <a href=\"https://docs.aws.amazon.com/verified-access/latest/ug/what-is-verified-access.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Cifrado inter-recurso",
    q: "¿Qué es 'Nitro encryption' en el contexto de instancias EC2 basadas en el Nitro System?",
    options: [
      "Un servicio aparte que hay que activar en cada Región y que se factura por instancia y por hora",
      "Cifrado automático del tráfico entre instancias Nitro y de la memoria, sin configurar nada",
      "Cifrado exclusivo de los volúmenes EBS adjuntos, gestionado con la clave aws/ebs",
      "Un tipo de KMS key reservado a instancias con GPU para cifrar la memoria de vídeo",
    ],
    correct: 1,
    explain: "El hardware del Nitro System cifra de forma transparente el tráfico entre instancias soportadas con AES-256-GCM, siempre que estén en la misma Región y en la misma VPC (o VPC emparejadas) y el tráfico no atraviese un balanceador o un transit gateway. Las claves solo existen en la memoria protegida de las Nitro Cards. Es el punto de examen de 'inter-resource encryption in transit' que sorprende porque no requiere acción del cliente. <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Secrets Manager",
    q: "¿Qué ventaja tiene AWS Secrets Manager sobre Systems Manager Parameter Store (SecureString) para credenciales de una base de datos RDS?",
    options: [
      "Parameter Store guarda los valores en claro, mientras que Secrets Manager los cifra con KMS",
      "Secrets Manager no tiene coste por secreto y Parameter Store se factura por parámetro",
      "Secrets Manager rota la credencial automáticamente con Lambdas ya provistas por AWS",
      "Parameter Store no permite controlar el acceso con políticas IAM, solo por endpoint de VPC",
    ],
    correct: 2,
    explain: "Los dos cifran con KMS y los dos se controlan con IAM; el diferencial es la <strong>rotación</strong>. Secrets Manager trae funciones Lambda de rotación listas para RDS, Aurora, Redshift y DocumentDB —e incluso rotación gestionada sin Lambda para algunos casos— que cambian la credencial en la base de datos y en el secreto en el mismo ciclo. Parameter Store es más barato para configuración, pero la lógica de rotación la escribes tú. <a href=\"https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Data masking",
    q: "Quieres que cualquier número de tarjeta de crédito que aparezca por error en tus logs de CloudWatch Logs se enmascare automáticamente antes de que un operador con permisos normales pueda verlo. ¿Qué mecanismo usas?",
    options: [
      "Una política IAM que deniegue logs:GetLogEvents a todos los operadores de la cuenta",
      "Amazon Macie, que analiza los log groups y sustituye cada dato sensible que encuentra por asteriscos",
      "Cifrar el log group con una KMS key propia, que oculta el dato a quien lo consulta",
      "Una data protection policy de CloudWatch Logs que enmascare el dato salvo con logs:Unmask",
    ],
    correct: 3,
    explain: "Las <em>data protection policies</em> de CloudWatch Logs detectan tipos de datos sensibles gestionados (tarjetas, SSN, credenciales de AWS) o personalizados y los enmascaran en todos los puntos de salida —consola, Logs Insights, metric filters, subscription filters—; solo quien tenga <code>logs:Unmask</code> ve el valor real. Cifrar con KMS protege el disco, no la vista: quien puede leer el log group lo ve descifrado. Amazon SNS ofrece una capacidad equivalente para mensajes. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/mask-sensitive-log-data.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "ACM & certificados",
    q: "¿Cuál es la diferencia clave entre un certificado público de AWS Certificate Manager (ACM) y uno emitido por AWS Private CA?",
    options: [
      "Los de ACM son de confianza pública y gratuitos; los de Private CA, de confianza interna",
      "No hay diferencia: los dos son gratuitos y los valida cualquier navegador que haya en el mercado",
      "AWS Private CA no puede emitir certificados TLS, únicamente firmar código y firmware",
      "Los certificados públicos de ACM hay que renovarlos e instalarlos de nuevo a mano",
    ],
    correct: 0,
    explain: "ACM emite certificados públicos sin coste, con renovación automática, para dominios que puedas validar y consumibles desde ELB, CloudFront o API Gateway. AWS Private CA levanta tu propia jerarquía de CA privada —con coste mensual por CA activa— para certificados internos: mTLS entre microservicios, dispositivos IoT o IAM Roles Anywhere. Esos certificados solo son de confianza allí donde tú distribuyas el certificado raíz. <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Client-side vs server-side encryption",
    q: "En cifrado 'client-side' de un objeto S3, ¿dónde ocurre el cifrado de los datos?",
    options: [
      "En el lado de S3, justo antes de escribir el objeto en el disco del propio servicio",
      "En la aplicación cliente, antes de que los datos salgan hacia el endpoint de S3",
      "En un proxy de cifrado gestionado por AWS que se sitúa delante del endpoint de S3",
      "En el mismo punto que en SSE-S3: lo único que cambia es quién posee la clave",
    ],
    correct: 1,
    explain: "Con cifrado client-side (AWS Encryption SDK o Amazon S3 Encryption Client) el objeto se cifra en la propia aplicación y S3 recibe únicamente ciphertext: el servicio no participa en el cifrado ni en el descifrado y nunca ve el texto plano. En server-side (SSE-S3, SSE-KMS, DSSE-KMS, SSE-C) el objeto llega a S3 en claro sobre TLS y es S3 quien lo cifra al escribirlo en disco. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SSE-KMS vs SSE-C",
    q: "¿Qué caracteriza a SSE-C (Server-Side Encryption with Customer-Provided Keys) en S3, frente a SSE-KMS?",
    options: [
      "SSE-C admite peticiones por HTTP porque la clave ya viaja cifrada en la cabecera",
      "SSE-C envuelve por dentro la clave que le entregas con una KMS key gestionada por AWS",
      "S3 usa la clave AES-256 que envías en cada petición y jamás la llega a almacenar",
      "SSE-C es el cifrado que se aplica por defecto a un bucket nuevo sin configurar",
    ],
    correct: 2,
    explain: "Con SSE-C tú gestionas la clave AES-256 y la envías en cabeceras en cada PUT y cada GET; S3 cifra y descifra con ella pero solo guarda un HMAC salteado para validar peticiones futuras. Por eso SSE-C exige HTTPS obligatoriamente y por eso perder la clave significa perder el objeto. No pasa por KMS, y el cifrado por defecto de un bucket nuevo es SSE-S3. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "SageMaker AI / EMR / EKS",
    q: "En un cluster de Amazon EMR que procesa datos sensibles, ¿qué configuración cubre específicamente el cifrado del tráfico ENTRE los nodos del cluster (no solo el almacenamiento)?",
    options: [
      "Habilitar SSE-S3 en el bucket de EMRFS del que el cluster lee los datos de entrada",
      "Restringir el security group del cluster para que solo los nodos hablen entre ellos",
      "Activar CloudTrail data events sobre el cluster para registrar el tráfico interno",
      "La in-transit encryption de EMR, definida en la security configuration del cluster",
    ],
    correct: 3,
    explain: "El cifrado at-rest (EBS local, EMRFS sobre S3) protege el almacenamiento, pero el tráfico interno de un cluster distribuido —shuffle de Spark, RPC entre nodos— solo se cifra si activas la <em>in-transit encryption</em> en la security configuration de EMR, aportando certificados PEM o dejando que EMR los gestione. Un security group restringe quién habla con quién, no cifra; CloudTrail registra llamadas de API, no el tráfico del cluster. <a href=\"https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-data-encryption-options.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "KMS HMAC keys",
    q: "Necesitas generar y verificar HMACs (message authentication codes) para garantizar la integridad y autenticidad de mensajes entre dos sistemas, apoyándote en un HSM validado FIPS 140-2, sin gestionar tú mismo el material criptográfico. ¿Qué usarías?",
    options: [
      "Una KMS key HMAC con KeyUsage GENERATE_VERIFY_MAC, vía GenerateMac y VerifyMac",
      "Una KMS key simétrica de cifrado, cifrando el mensaje con Encrypt y comparando salidas",
      "AWS Signer, que produce una firma del mensaje con su certificado de code signing",
      "Un secreto rotado de Secrets Manager, usando su valor como clave HMAC en la aplicación",
    ],
    correct: 0,
    explain: "Las HMAC KMS keys son claves simétricas con <code>KeyUsage GENERATE_VERIFY_MAC</code>, conformes a RFC 2104, dedicadas a <code>GenerateMac</code> y <code>VerifyMac</code> sobre mensajes de hasta 4.096 bytes; no admiten Encrypt/Decrypt ni GenerateDataKey. La ventaja sobre un HMAC en software es que el material se genera y se usa íntegramente dentro de KMS, sujeto a la key policy. Signer firma artefactos de código, no mensajes arbitrarios. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/hmac.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "KMS ECDH key agreement",
    q: "Dos organizaciones distintas quieren establecer un secreto compartido entre sus sistemas para derivar después una clave simétrica de sesión, sin transmitir ninguna clave privada por la red. ¿Qué operación de KMS permite esto usando claves asimétricas EC?",
    options: [
      "GenerateDataKeyPair, que entrega a cada parte un par de claves EC para compartir",
      "DeriveSharedSecret sobre una KMS key EC con KeyUsage KEY_AGREEMENT, usando ECDH",
      "GenerateRandom, cuyo valor aleatorio ambas partes usan como secreto compartido",
      "Sign y Verify sobre una key RSA, firmando el secreto que una parte envía a la otra",
    ],
    correct: 1,
    explain: "<code>DeriveSharedSecret</code> aplica el primitivo ECDH Cofactor sobre tu KMS key asimétrica NIST EC (o SM2) con <code>KeyUsage KEY_AGREEMENT</code> y la clave pública de la otra parte: ambas partes obtienen el mismo secreto sin que ninguna clave privada salga de KMS ni viaje por la red. Firmar o cifrar un secreto y enviarlo sí lo pone en tránsito, y <code>GenerateRandom</code> produce un valor que nadie más puede reproducir. <a href=\"https://docs.aws.amazon.com/kms/latest/APIReference/API_DeriveSharedSecret.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 Bucket Keys",
    q: "Una empresa cifra millones de objetos S3 con SSE-KMS y observa que el coste de las llamadas a la API de KMS (GenerateDataKey, Decrypt) es desproporcionadamente alto frente al almacenamiento. ¿Qué opción de S3, activable sin cambios en la aplicación cliente, reduce drásticamente ese coste?",
    options: [
      "Cambiar el bucket a SSE-S3, que sigue llamando a KMS pero sin coste por petición",
      "Habilitar S3 Transfer Acceleration, que agrupa las peticiones de cifrado en lote",
      "Habilitar S3 Bucket Keys, que reutiliza una clave de bucket para muchos objetos",
      "Migrar el bucket a DSSE-KMS, cuyas dos capas reducen las llamadas a la API de KMS",
    ],
    correct: 2,
    explain: "Sin Bucket Keys, S3 pide a KMS una data key por cada objeto y por cada lectura. Con S3 Bucket Keys pide una clave de bucket de vida corta y deriva localmente las data keys de muchos objetos, reduciendo hasta un 99% las peticiones a KMS sin tocar la aplicación. DSSE-KMS va en la dirección contraria (más operaciones y coste por GB) y no es compatible con Bucket Keys; Transfer Acceleration afecta a la red, no al cifrado. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 DSSE-KMS",
    q: "Un cliente del sector defensa necesita cumplir con CNSSP 15 / Data-at-Rest Capability Package, que exige DOS capas independientes de cifrado AES-256 sobre los objetos almacenados en S3. ¿Qué método de cifrado de S3 cumple este requisito?",
    options: [
      "SSE-KMS con S3 Bucket Keys, cuya clave de bucket aporta la segunda capa de cifrado AES-256",
      "SSE-C, porque la clave del cliente y la de S3 forman dos capas independientes",
      "Cifrado client-side con el AWS Encryption SDK, que envuelve la data key dos veces",
      "DSSE-KMS, que aplica dos capas independientes de cifrado AES-256 al subir el objeto",
    ],
    correct: 3,
    explain: "DSSE-KMS cifra el objeto dos veces de forma independiente: una capa con una data key de KMS y otra con una clave gestionada por S3, que es lo que exigen las guías de doble capa para cargas altamente reguladas. La clave de bucket de S3 Bucket Keys solo deriva data keys de una única capa, y envolver una data key dos veces (client-side) no equivale a cifrar dos veces el dato. DSSE-KMS no admite Bucket Keys y cuesta más por GB. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingDSSEncryption.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Custom key store con CloudHSM",
    q: "Una entidad financiera exige que el material de sus claves de cifrado viva en HSM de un solo inquilino bajo su control exclusivo, pero quiere seguir usando la integración nativa de KMS con S3, EBS y RDS. ¿Qué diseño lo permite?",
    options: [
      "Un custom key store de KMS respaldado por un clúster de CloudHSM",
      "CloudHSM a secas, cifrando en la aplicación antes de escribir en cada servicio",
      "Una KMS key gestionada por el cliente con la rotación automática anual activada",
      "Importar a KMS el material de clave generado en el HSM on-premises cada 90 días",
    ],
    correct: 0,
    explain: "Un <b>custom key store</b> mantiene el material de clave dentro de un clúster de CloudHSM que es tuyo y de un solo inquilino, mientras KMS sigue siendo la API: S3, EBS y RDS se integran exactamente igual que antes, sin que la aplicación sepa dónde está la clave. CloudHSM a secas obliga a cifrar en la aplicación y pierde todas esas integraciones. Una customer managed key normal vive en los HSM compartidos de KMS. Y el material importado sigue residiendo en KMS: cambiar el origen a EXTERNAL decide quién genera la clave, no dónde se custodia. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/keystore-cloudhsm.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Nitro Enclaves & atestación KMS",
    q: "Una aplicación procesa datos altamente sensibles dentro de un AWS Nitro Enclave y necesita que KMS solo descifre datos para ESE enclave concreto (identificado por el hash de su imagen), no para ningún otro proceso de la instancia padre ni de otro enclave. ¿Qué mecanismo lo garantiza?",
    options: [
      "Un KMS grant clásico concedido al rol de la instancia padre, sin condiciones extra",
      "La atestación criptográfica de KMS, con kms:RecipientAttestation en la key policy",
      "El cifrado automático de memoria del Nitro System, que aísla al enclave del padre",
      "Una KMS Multi-Region key, cuya réplica se despliega dentro del enclave aislado",
    ],
    correct: 1,
    explain: "Al llamar a <code>Decrypt</code>, <code>GenerateDataKey</code>, <code>GenerateDataKeyPair</code>, <code>GenerateRandom</code> o <code>DeriveSharedSecret</code> con un AttestationDocument firmado por el hipervisor Nitro, KMS valida las medidas del enclave y devuelve el resultado cifrado con la clave pública del documento, no en claro. La condición <code>kms:RecipientAttestation:ImageSha384</code> (PCR0) en la key policy restringe el acceso a la imagen esperada. Un grant sin condiciones no distingue enclaves. <a href=\"https://docs.aws.amazon.com/enclaves/latest/user/kms.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "ALB mutual TLS (mTLS)",
    q: "Necesitas que tu Application Load Balancer autentique la identidad del CLIENTE (no solo cifrar el canal) verificando su certificado X.509 contra una CA de confianza, antes de reenviar la solicitud al target. ¿Qué configuras?",
    options: [
      "Una security policy TLS 1.3 en el listener, que ya exige certificado de cliente",
      "AWS WAF con una regla rate-based que valide el certificado antes de reenviarlo",
      "mTLS en modo verify sobre el listener HTTPS, con un trust store que contenga la CA",
      "Un security group que solo admita el rango CIDR desde el que conecta el cliente",
    ],
    correct: 2,
    explain: "El ALB ofrece dos modos de mTLS: <strong>passthrough</strong>, que reenvía la cadena del cliente al target en cabeceras HTTP sin validarla, y <strong>verify</strong>, en el que el propio ALB valida el certificado contra un trust store con el CA bundle (de un tercero o de AWS Private CA) y, opcionalmente, listas de revocación. Verify es lo que descarga la autenticación de cliente del backend. Una security policy fija protocolos y ciphers, no exige certificado de cliente. <a href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/mutual-authentication.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Amazon Macie — descubrimiento automatizado",
    q: "Quieres visibilidad continua y de bajo coste de qué buckets S3 de toda tu organización podrían contener datos sensibles, sin definir y ejecutar manualmente un job de escaneo completo sobre cada bucket. ¿Qué capacidad de Macie usas?",
    options: [
      "Un sensitive data discovery job programado sobre el 100% de los objetos de cada bucket",
      "GuardDuty S3 Protection, que clasifica el contenido de cada objeto según su tipo",
      "Reglas de AWS Config que evalúan el contenido de los objetos bucket por bucket",
      "Automated sensitive data discovery, que muestrea objetos a diario y puntúa el bucket",
    ],
    correct: 3,
    explain: "Macie tiene dos modos. <strong>Automated sensitive data discovery</strong> evalúa a diario el inventario de buckets de todas las cuentas de la organización y analiza una muestra representativa de objetos, produciendo un data map y un sensitivity score por bucket a bajo coste. Los <strong>sensitive data discovery jobs</strong> son análisis dirigidos y exhaustivos sobre buckets concretos, más caros porque revisan muchos más objetos. GuardDuty analiza actividad, no contenido. <a href=\"https://docs.aws.amazon.com/macie/latest/user/discovery-asdd.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "AWS Private CA — short-lived certificate mode",
    q: "Una plataforma emite cientos de miles de certificados de vida muy corta (7 días o menos) al mes para autenticar cargas de trabajo efímeras, y el coste mensual fijo de la CA en modo general-purpose resulta desproporcionado. ¿Qué opción reduce el coste?",
    options: [
      "AWS Private CA en modo short-lived certificate, con validez máxima de siete días",
      "Migrar a ACM público, que emite gratis certificados para cargas de trabajo efímeras",
      "Desactivar OCSP y las CRL de la CA, que es donde se concentra el coste fijo mensual",
      "Emitir los certificados directamente desde CloudHSM, sin pasar por AWS Private CA",
    ],
    correct: 0,
    explain: "AWS Private CA ofrece dos <em>usage modes</em>: general-purpose (cualquier periodo de validez, coste fijo mensual mayor) y short-lived certificate (coste fijo mucho menor, pero ningún certificado emitido puede superar 7 días). Encaja con identidades efímeras de contenedores y funciones, que rotan tan rápido que ni siquiera necesitan revocación. ACM público no emite certificados internos, y CloudHSM aporta claves, no una jerarquía de CA gestionada. <a href=\"https://docs.aws.amazon.com/privateca/latest/userguide/short-lived-certificates.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Secrets Manager multi-Region",
    q: "Una aplicación con lectores en dos regiones necesita acceder al mismo secreto de base de datos con baja latencia en ambas, y que al rotar la credencial en la región primaria, el nuevo valor se propague automáticamente sin gestionar la rotación por separado en cada región. ¿Qué característica de Secrets Manager usas?",
    options: [
      "Cross-Region Replication de S3 sobre un fichero exportado con el valor del secreto",
      "Multi-Region secrets de Secrets Manager, replicados con ReplicateSecretToRegions",
      "Crear en cada Región un secreto independiente con el mismo nombre y el mismo valor",
      "Una KMS Multi-Region key, que replica también el valor del secreto a las réplicas",
    ],
    correct: 1,
    explain: "<code>ReplicateSecretToRegions</code> crea réplicas enlazadas al secreto primario: se replican el valor cifrado y los metadatos (tags, política de recursos), y cuando la rotación actualiza el primario el nuevo valor llega solo a todas las réplicas. Cada réplica se factura como un secreto y puede promocionarse a independiente. Una KMS Multi-Region key replica material de clave, nunca el contenido del secreto. <a href=\"https://docs.aws.amazon.com/secretsmanager/latest/userguide/replicate-secrets.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "IAM Roles Anywhere",
    q: "Una carga de trabajo on-premises (fuera de AWS) necesita obtener credenciales temporales de IAM para llamar a la API de AWS, sin usar access keys de larga duración almacenadas en el servidor. Ya existe una PKI interna. ¿Qué solución encaja?",
    options: [
      "Access keys de IAM guardadas en el servidor y rotadas manualmente cada 90 días",
      "AWS Client VPN, que entrega credenciales del rol al establecerse el túnel",
      "IAM Roles Anywhere, registrando la CA de tu PKI interna como un trust anchor",
      "Amazon Cognito Identity Pools, canjeando el certificado X.509 por credenciales",
    ],
    correct: 2,
    explain: "IAM Roles Anywhere establece confianza entre tu PKI existente —registrada como <em>trust anchor</em>— y AWS: la carga de trabajo presenta un certificado X.509 emitido por esa CA, llama a <code>CreateSession</code> y recibe credenciales temporales de un rol IAM vía STS, eliminando las access keys de larga duración del servidor. Client VPN da conectividad de red, no credenciales; Cognito Identity Pools está pensado para identidades de usuarios de aplicaciones. <a href=\"https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "EBS encryption by default",
    q: "Habilitas la configuración de cuenta 'EBS encryption by default' en una región donde ya existen volúmenes EBS sin cifrar en uso. ¿Qué ocurre con esos volúmenes existentes?",
    options: [
      "Se cifran automáticamente la próxima vez que se adjuntan a una instancia EC2",
      "Se marcan como no conformes y EC2 los elimina al terminar la instancia asociada",
      "Se van cifrando de forma progresiva a medida que se crea el siguiente snapshot del volumen",
      "Nada: el ajuste solo alcanza a los volúmenes y copias de snapshot creados después",
    ],
    correct: 3,
    explain: "'EBS encryption by default' es un ajuste por cuenta y Región que solo afecta a los volúmenes y a las copias de snapshot creados a partir de ese momento; no toca lo existente. Un volumen o un snapshot solo puede cifrarse en el instante de su creación, así que la vía para cifrar uno existente es: snapshot → copia del snapshot con cifrado → crear un volumen nuevo desde esa copia. <a href=\"https://docs.aws.amazon.com/ebs/latest/userguide/encryption-by-default.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "RDS encryption at rest",
    q: "Tienes una instancia RDS de producción creada SIN cifrado en reposo (storage encryption deshabilitado). ¿Cómo puedes habilitar el cifrado sin perder los datos?",
    options: [
      "No se puede: hay que copiar el snapshot cifrándolo y restaurar una instancia nueva",
      "Con modify-db-instance y el parámetro --storage-encrypted sobre la instancia viva",
      "Habilitando SSE-KMS en la instancia desde la pestaña de cifrado de la consola RDS",
      "Activando 'EBS encryption by default', que cifra el almacenamiento ya existente",
    ],
    correct: 0,
    explain: "El cifrado en reposo de RDS solo se establece al crear la instancia o al restaurar desde un snapshot cifrado: no existe una operación <code>modify</code> que lo active después, ni se puede desactivar ni cambiar la clave más tarde. El patrón estándar es snapshot → copiar el snapshot con cifrado habilitado → restaurar desde esa copia → cutover, usando DMS si necesitas minimizar la ventana de indisponibilidad. <a href=\"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "kms:ViaService",
    q: "Quieres que una customer managed KMS key solo pueda ser usada por Amazon S3 (no por EBS, RDS, ni llamadas directas de un usuario a la API de KMS), incluso si esos otros principals tienen permisos IAM sobre la key. ¿Qué condición añades a la key policy?",
    options: [
      "aws:SourceIp, restringiendo la key a los rangos de direcciones públicas de S3",
      "kms:ViaService, con el valor s3.eu-west-1.amazonaws.com, en la statement de uso",
      "aws:PrincipalOrgID, que acota el uso de la key a las cuentas de tu organización",
      "kms:GrantIsForAWSResource, que obliga a que la llamada llegue desde un servicio",
    ],
    correct: 1,
    explain: "<code>kms:ViaService</code> exige que la petición llegue a KMS <em>a través de</em> un servicio concreto, identificado por su principal de servicio regional (por ejemplo <code>s3.eu-west-1.amazonaws.com</code>): aunque un rol tenga <code>kms:Decrypt</code> en su política de identidad, una llamada directa a la API queda denegada. <code>kms:GrantIsForAWSResource</code> solo limita quién puede crear grants, y <code>aws:PrincipalOrgID</code> acota cuentas, no servicios. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/conditions-kms.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "RDS — master password gestionado por Secrets Manager",
    q: "Quieres eliminar por completo la exposición en texto plano de la contraseña maestra de una nueva base de datos RDS durante su creación, y que AWS gestione la rotación periódica de esa contraseña sin que escribas tú una función Lambda. ¿Qué opción de RDS usas?",
    options: [
      "Crear el secreto y la Lambda de rotación a mano justo después de crear la instancia",
      "Guardar la contraseña en Parameter Store SecureString con una política de rotación",
      "Activar 'Manage master credentials in AWS Secrets Manager' al crear la instancia",
      "Desactivar la autenticación por contraseña y usar solo IAM database authentication",
    ],
    correct: 2,
    explain: "Con 'Manage master credentials in AWS Secrets Manager' es RDS quien genera la contraseña maestra, la guarda en Secrets Manager y la rota periódicamente: nunca se muestra en claro durante la creación y no escribes ni despliegas ninguna Lambda. Opcionalmente puedes cifrar el secreto con una customer managed key. IAM database authentication es una alternativa válida para las conexiones de aplicación, pero el usuario maestro sigue teniendo contraseña. <a href=\"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-secrets-manager.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "S3 Object Lock — Legal Hold",
    q: "Necesitas preservar un objeto S3 indefinidamente por un litigio en curso, sin saber cuánto tiempo durará, y sin depender de fijar una fecha de retención concreta en modo Governance o Compliance. ¿Qué mecanismo de Object Lock usas?",
    options: [
      "Un retention period en modo Compliance fijando la fecha de expiración en 2099",
      "Glacier Vault Lock, cuya política bloqueada retiene el objeto sin plazo fijo",
      "S3 Versioning con MFA Delete, que exige un segundo factor para poder borrar",
      "Un Legal Hold, que aplica la misma protección WORM pero sin fecha de expiración",
    ],
    correct: 3,
    explain: "Un Legal Hold da la misma protección WORM que un retention period pero no caduca: sigue activo hasta que un principal con <code>s3:PutObjectLegalHold</code> lo retira explícitamente, que es justo lo que pide un litigio de duración desconocida. Un objeto puede tener retention period, legal hold, ambos o ninguno, porque son mecanismos independientes. Fijar Compliance hasta 2099 sería irreversible aunque el litigio se cierre mañana. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Rotación automática de KMS — alcance",
    q: "Habilitas la rotación automática anual en una KMS key. ¿Para cuáles de las siguientes NO está disponible esa rotación automática, obligando a rotación manual o bajo demanda?",
    options: [
      "Claves asimétricas, HMAC, con material importado y las de custom key stores",
      "Solo las claves simétricas de cifrado con material generado por el propio KMS",
      "Únicamente las AWS managed keys, del tipo aws/s3 o aws/ebs, que ya rotan solas",
      "Ninguna: cualquier KMS key admite rotación automática en cuanto la habilitas",
    ],
    correct: 0,
    explain: "La rotación automática solo existe para KMS keys simétricas de cifrado con material generado por AWS (origen <code>AWS_KMS</code>). Quedan fuera las asimétricas, las HMAC, las de material importado (<code>EXTERNAL</code>) y las alojadas en un custom key store (CloudHSM key store o XKS). Para esas, la salida es la rotación manual —crear una key nueva y repuntar los alias— o, en el caso del material importado, <code>RotateKeyOnDemand</code>. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "CloudTrail & auditoría de uso de KMS",
    q: "Sospechas que una customer managed KMS key ha sido usada para descifrar datos por un principal no autorizado. ¿Dónde consultas quién invocó la operación Decrypt sobre esa key, cuándo, y desde qué principal/rol?",
    options: [
      "En la key policy de la clave, donde figuran los principals que la han utilizado",
      "En AWS CloudTrail, que registra cada llamada a KMS con su principal y Key ID",
      "En Amazon Macie, que inventaría el uso de las claves sobre los datos sensibles",
      "En AWS Config, que registra en tiempo real las invocaciones de la API de KMS",
    ],
    correct: 1,
    explain: "Todas las operaciones de KMS —incluidas las criptográficas como <code>Decrypt</code> y <code>GenerateDataKey</code>— se registran como management events de CloudTrail, con el principal invocador, la marca de tiempo, el Key ID, la IP de origen y si la llamada tuvo éxito o fue denegada; en accesos cross-account el evento aparece en ambas cuentas. La key policy dice quién <em>puede</em> usar la clave, no quién la usó, y Config evalúa configuración, no invocaciones. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/logging-using-cloudtrail.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Uso cross-account de una KMS key",
    q: "Un rol de la cuenta B debe descifrar objetos cifrados con una KMS key gestionada por el cliente que vive en la cuenta A. ¿Qué DOS condiciones deben cumplirse?",
    options: [
      "La key policy en la cuenta A debe autorizar expresamente al principal de la cuenta B",
      "La clave debe ser una AWS managed key, la única que se puede compartir entre cuentas",
      "La política de identidad del rol en la cuenta B debe permitir la acción kms:Decrypt",
      "Ambas cuentas deben pertenecer a la misma Organization y estar en la misma Región",
    ],
    correct: [0, 2],
    explain: "Igual que en el acceso cross-account a roles, KMS exige <strong>las dos puntas</strong>: key policy en el propietario e identity policy en el consumidor; ninguna de las dos basta por sí sola. Precisamente las <strong>AWS managed keys no se pueden compartir</strong> entre cuentas, así que el caso de uso obliga a una customer managed key —justo lo contrario de la opción C. Organizations no hace falta; la Región importa porque las claves son regionales, pero no es lo que falta aquí. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Envelope encryption",
    q: "¿Qué DOS afirmaciones describen correctamente el envelope encryption tal y como lo implementa AWS KMS?",
    options: [
      "Los datos viajan hasta KMS para cifrarse allí, con independencia de su tamaño total",
      "Los datos se cifran con una data key, y esa data key se cifra con la KMS key",
      "La KMS key sale del servicio en claro para cifrar los datos en el cliente",
      "La data key en claro se usa en memoria y se descarta en cuanto acaba el cifrado",
    ],
    correct: [1, 3],
    explain: "El envelope encryption existe justamente para <strong>no</strong> mandar los datos a KMS: KMS cifra la data key (operación pequeña y rápida) y el cifrado masivo ocurre localmente. La operación directa <code>Encrypt</code> está limitada a 4 KB, lo que descarta la opción C para datos reales. Y el material criptográfico de una KMS key <strong>nunca sale sin cifrar</strong> del servicio: es su garantía fundamental. <a href=\"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Retención inmutable en S3",
    q: "Un requisito regulatorio exige que ciertos objetos de S3 no puedan borrarse durante 7 años. ¿Qué DOS afirmaciones sobre S3 Object Lock son correctas?",
    options: [
      "En modo compliance ningún usuario, ni el root de la cuenta, puede borrar el objeto",
      "En modo governance nadie puede saltarse la retención bajo ningún supuesto previsto",
      "Object Lock se activa sobre objetos ya existentes sin configurar antes el bucket",
      "Object Lock exige que el versionado esté habilitado en el bucket de destino",
    ],
    correct: [0, 3],
    explain: "<strong>Compliance</strong> es el modo verdaderamente inmutable (ni root puede saltárselo) y Object Lock <strong>depende del versionado</strong>, porque protege versiones concretas de objeto. El modo <strong>governance</strong> sí admite excepción para quien tenga <code>s3:BypassGovernanceRetention</code> — esa es justo la diferencia entre los dos modos y lo que suele preguntarse. Y Object Lock se habilita a nivel de bucket, no se improvisa sobre objetos de un bucket que no lo tiene. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Rotación en Secrets Manager",
    q: "Quieres rotar automáticamente la contraseña de una base de datos RDS almacenada en Secrets Manager. ¿Qué DOS elementos intervienen?",
    options: [
      "Un bucket de S3 donde Secrets Manager deposita la contraseña anterior en texto plano",
      "Una Lambda de rotación con permiso para cambiar la credencial en la base de datos",
      "Una programación de rotación que define cada cuánto tiempo se ejecuta el proceso",
      "Una regla de AWS Config que cambia la contraseña al detectar que ya ha caducado",
    ],
    correct: [1, 2],
    explain: "La rotación se apoya en una <strong>Lambda</strong> (AWS provee plantillas para las bases de datos soportadas) y una <strong>programación</strong> expresada con <code>cron()</code> o <code>rate()</code>. Secrets Manager mantiene las versiones del secreto con etiquetas como AWSCURRENT y AWSPREVIOUS dentro del propio servicio y cifradas con KMS: jamás escribe credenciales en claro en un bucket. Y AWS Config <strong>evalúa</strong> configuración, no rota credenciales. <a href=\"https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Enmascarado en mensajes de SNS",
    q: "Un tema de SNS reparte eventos a varios equipos y el cuerpo del mensaje incluye a veces correos electrónicos de clientes. Quieres que los suscriptores no autorizados los reciban ofuscados, sin cambiar el publicador. ¿Qué aplicas?",
    options: [
      "Una política de protección de datos del tema, con una acción de enmascarado",
      "Cifrado en reposo del tema con una KMS key gestionada por el cliente",
      "Un filtro de suscripción que descarte los mensajes con datos personales",
      "Una política de protección de datos del grupo de CloudWatch Logs del publicador",
    ],
    correct: 0,
    explain: "Las <b>data protection policies</b> de SNS inspeccionan el cuerpo del mensaje contra identificadores de datos gestionados y aplican una acción —auditar, ofuscar o bloquear— por suscriptor, de modo que unos reciben el dato y otros no. El cifrado en reposo protege el mensaje mientras espera, pero el suscriptor lo recibe en claro igual. Un filtro de suscripción decide qué mensajes llegan, no qué partes. Y la política de CloudWatch Logs afecta a lo que se registra, no a lo que se entrega. <a href=\"https://docs.aws.amazon.com/sns/latest/dg/message-data-protection.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Ciclo de vida en EFS",
    q: "Un sistema de archivos EFS guarda evidencias forenses que casi nunca se leen pasada la primera semana, pero que deben conservarse accesibles durante años. ¿Qué reduce el coste sin sacarlas del sistema de archivos?",
    options: [
      "Una regla de ciclo de vida de EFS hacia Infrequent Access",
      "Copiarlas a S3 Glacier Deep Archive con una tarea programada de DataSync",
      "Una política de ciclo de vida de S3 sobre el bucket que respalda el EFS",
      "Reducir el rendimiento provisionado del sistema de archivos a modo ráfaga",
    ],
    correct: 0,
    explain: "EFS tiene <b>gestión del ciclo de vida</b> propia: pasado el número de días configurado sin acceso, el fichero baja a Infrequent Access o a Archive y sigue estando en la misma ruta, se lee igual y cuesta bastante menos. Copiar a Glacier con DataSync los saca del sistema de archivos, que es lo que el enunciado excluye. EFS no está respaldado por un bucket de S3, así que no hay política de S3 que aplicar. Y el modo de rendimiento cambia la velocidad, no el precio del almacenamiento. <a href=\"https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "Copias de FSx for Lustre",
    q: "Un clúster de cómputo usa Amazon FSx for Lustre con datos sensibles y necesitas copias diarias con retención definida, cifradas, sin detener el sistema de archivos. ¿Qué usas?",
    options: [
      "Snapshots de EBS de los volúmenes que respaldan el sistema de archivos",
      "Las copias automáticas diarias de FSx, con su ventana y su retención",
      "Una tarea de DataSync que replique el contenido a otro sistema de archivos",
      "El versionado del bucket S3 vinculado por data repository association",
    ],
    correct: 1,
    explain: "FSx for Lustre trae <b>copias automáticas diarias</b> con ventana y periodo de retención configurables, coherentes con el sistema de archivos y cifradas con la misma clave, sin interrumpir el servicio. No hay volúmenes de EBS que fotografiar: el almacenamiento no se expone así. DataSync copia ficheros, pero no da un punto de recuperación consistente ni una política de retención. Y el versionado de S3 protege los objetos del repositorio vinculado, no los metadatos ni el estado del sistema de archivos. <a href=\"https://docs.aws.amazon.com/fsx/latest/LustreGuide/using-backups-fsx.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
  {
    tag: "DataSync y cifrado en tránsito",
    q: "Vas a copiar 40 TB desde un NAS on-premises a S3 y el requisito es que los datos viajen cifrados de extremo a extremo por la conexión de Direct Connect. ¿Qué es cierto de AWS DataSync?",
    options: [
      "Hay que montar un túnel IPsec propio, porque DataSync viaja en claro",
      "Cifra en tránsito con TLS entre el agente y el servicio, siempre",
      "El cifrado en tránsito solo se activa si el destino es un bucket con SSE-KMS",
      "Requiere una VPN de sitio a sitio además de Direct Connect para cifrar",
    ],
    correct: 1,
    explain: "El agente de DataSync habla con el servicio siempre por <b>TLS</b>, incluida la ruta por Direct Connect a través de un VPC endpoint, así que el cifrado en tránsito no es opcional ni hay que configurarlo. No hace falta ni túnel IPsec ni VPN encima: eso sería cifrar dos veces. Y el cifrado del destino —SSE-S3 o SSE-KMS— es una decisión sobre el dato <em>en reposo</em>, independiente de cómo viajó. <a href=\"https://docs.aws.amazon.com/datasync/latest/userguide/encryption-in-transit.html\" target=\"_blank\" rel=\"noopener\">Doc AWS ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["data-protection"] = QUIZ_DATA;
