// Banco de preguntas del módulo: operaciones de seguridad, identidad y cumplimiento (SC-100, dominio 2).
// Cada explicación termina en el enlace a la documentación oficial de Microsoft Learn.

var QUIZ_DATA = [
  {
    tag: "XDR frente a SIEM",
    q: "Un cliente con Microsoft 365 E5 quiere que el SOC vea correlacionados los ataques que empiezan en un correo, siguen en el portátil y acaban en una cuenta de Entra ID. Todo el estado es de Microsoft y no hay planes de ingerir otros orígenes. ¿Qué recomiendas?",
    options: [
      "Desplegar Microsoft Sentinel e ingerir los conectores de Defender for Office 365, Defender for Endpoint y Entra ID",
      "Usar Microsoft Defender XDR, que ya correlaciona esas señales en un único incidente",
      "Exportar las alertas de cada producto a un almacenamiento común y correlacionarlas con consultas propias",
      "Desplegar Sentinel y además Defender XDR, y trabajar los incidentes en los dos portales",
    ],
    correct: 1,
    explain: "Defender XDR <b>ya</b> correlaciona identidad, endpoint, correo y aplicaciones de Microsoft en incidentes montados, sin conectar nada y sin coste de ingesta. Meter Sentinel aquí es pagar por reconstruir a mano lo que viene hecho. El SIEM se justifica cuando entra un origen ajeno —un firewall de terceros, otra nube, una aplicación propia— o cuando hace falta retención larga; nada de eso aparece en el enunciado. Y trabajar en dos portales a la vez es justo lo que resuelve el portal unificado. <a href=\"https://learn.microsoft.com/en-us/unified-secops/overview-unified-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cuándo entra el SIEM",
    q: "La misma organización incorpora ahora appliances de red de un tercero, una aplicación de negocio propia y suscripciones en AWS, y necesita correlacionar todo eso con lo que ya ve Defender XDR, con dos años de retención. ¿Qué añade el diseño?",
    options: [
      "Ampliar las licencias de Defender XDR para que ingiera los orígenes nuevos",
      "Un segundo tenant dedicado a los orígenes que no son de Microsoft",
      "Reglas de análisis en Defender for Cloud Apps sobre los registros del firewall",
      "Microsoft Sentinel, con Defender XDR conectado como uno de sus orígenes",
    ],
    correct: 3,
    explain: "Defender XDR solo ve sus propios sensores: no se le pueden añadir orígenes arbitrarios por licencia. <b>Sentinel</b> es la pieza que ingiere lo ajeno, y el patrón de referencia es conectar Defender XDR a Sentinel para que el SOC tenga una sola cola de incidentes con las dos cosas. Un segundo tenant fragmenta la identidad sin resolver la correlación, y Defender for Cloud Apps gobierna SaaS, no es un SIEM. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Auditoría de actividad de usuario",
    q: "Legal pide poder responder, hasta un año atrás, quién accedió a un buzón concreto y quién exportó datos desde Microsoft 365. ¿Qué capacidad cubre ese requisito?",
    options: [
      "Microsoft Purview Audit, en su nivel con retención ampliada",
      "Los registros de inicio de sesión de Entra ID exportados a Log Analytics",
      "Las alertas de Defender for Office 365 sobre acceso sospechoso a buzones",
      "Un playbook de Sentinel que registre cada acceso en una tabla propia",
    ],
    correct: 0,
    explain: "La pregunta es de <b>actividad</b>, no de detección: quién hizo qué sobre qué objeto. Eso vive en <b>Purview Audit</b>, cuyo nivel superior amplía la retención y añade eventos de alto valor como el acceso a buzones. Los registros de inicio de sesión dicen quién entró, no qué tocó después. Las alertas cubren lo sospechoso, no el histórico completo. Y un playbook no puede registrar lo que ya ocurrió. <a href=\"https://learn.microsoft.com/en-us/purview/audit-solutions-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Coste de ingesta",
    q: "El coste de Sentinel se ha disparado por los registros de flujo de red y los verbosos del proxy, que ocupan la mayor parte del volumen y casi nunca disparan una alerta, aunque hay que conservarlos por normativa. ¿Qué diseño resuelve las dos cosas?",
    options: [
      "Reducir la retención de todo el workspace al mínimo que la normativa llegue a permitir",
      "Llevarlos a un nivel de tabla más barato y dejar en análisis lo que alimenta reglas",
      "Dejar de ingerirlos y conservarlos únicamente en el appliance que los genera",
      "Crear un workspace por origen para repartir el coste entre varias suscripciones",
    ],
    correct: 1,
    explain: "El coste de un SIEM se gobierna decidiendo <b>qué dato necesita capacidad de análisis</b> y cuál solo necesita estar guardado y ser consultable. Los niveles de tabla auxiliares y el almacenamiento a largo plazo existen para eso: se conserva lo que la norma exige a una fracción del precio y se reserva el nivel caro para lo que alimenta detecciones. Bajar la retención global choca con la normativa, dejar de ingerir rompe la investigación, y multiplicar workspaces reparte la factura sin reducirla. <a href=\"https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Gobernar servidores fuera de Azure",
    q: "Un cliente tiene 400 servidores repartidos entre su centro de datos y una nube de terceros. Quiere aplicarles las mismas políticas de configuración que a sus máquinas de Azure y verlos en Defender for Cloud. ¿Qué es imprescindible en el diseño?",
    options: [
      "Un túnel VPN de sitio a sitio entre el centro de datos y la red virtual de Azure",
      "Migrar esos servidores a Azure para que queden bajo el mismo plano de control",
      "Un workspace de Log Analytics dedicado en cada uno de los entornos",
      "Azure Arc, que proyecta esos servidores al plano de control de Azure",
    ],
    correct: 3,
    explain: "<b>Azure Arc</b> es la pieza que convierte un servidor de fuera en un recurso de Azure a efectos de gobierno: a partir de ahí le aplican Azure Policy, Machine Configuration y Defender for Servers igual que a una máquina nativa. La VPN da conectividad de red, que es otro problema. Migrar contradice el enunciado. Y un workspace lleva los logs, pero no permite gobernar la configuración del servidor. <a href=\"https://learn.microsoft.com/en-us/azure/azure-arc/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Postura en otras nubes",
    q: "El mismo cliente quiere además ver las recomendaciones de seguridad de sus cuentas de AWS y sus proyectos de GCP en el mismo sitio que las de Azure, sin instalar nada en esas cargas. ¿Qué recomiendas?",
    options: [
      "Los conectores multinube de Defender for Cloud, que leen la configuración sin agentes",
      "Desplegar el agente de Azure Monitor en cada una de las instancias de AWS y de GCP",
      "Exportar la configuración de AWS y GCP a Sentinel y escribir reglas de análisis propias",
      "Replicar las cargas críticas en Azure para poder evaluarlas con Defender for Cloud",
    ],
    correct: 0,
    explain: "Los <b>conectores multinube</b> de Defender for Cloud se autentican contra AWS y GCP y evalúan su configuración desde fuera, sin agente en las cargas, que es exactamente la restricción del enunciado. Desplegar agentes la contradice. Sentinel correlaciona eventos, no produce recomendaciones de postura. Y replicar cargas para poder mirarlas no es una respuesta de arquitectura. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-multicloud-security-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Reglas de automatización o playbook",
    q: "El SOC quiere que los incidentes de Sentinel de un tipo concreto, que casi siempre son falso positivo, se cierren solos con un comentario y sin gastar en ejecuciones de Logic Apps. ¿Qué mecanismo encaja?",
    options: [
      "Un playbook que evalúe el incidente y llame a la API de Sentinel para cerrarlo",
      "Una regla de supresión en Defender XDR sobre la alerta de origen",
      "Desactivar la regla de análisis que genera esos incidentes",
      "Una regla de automatización de Sentinel con la condición y la acción de cierre",
    ],
    correct: 3,
    explain: "Las <b>reglas de automatización</b> son nativas de Sentinel y hacen exactamente esto —filtrar por condición y cerrar, etiquetar, asignar o cambiar la severidad— sin invocar una Logic App, que es la restricción de coste del enunciado. Un playbook haría el trabajo pero pagando por cada ejecución. Desactivar la regla ciega la detección por completo. Y suprimir en Defender XDR actúa antes, sobre una señal que sí se quiere seguir teniendo. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/automate-incident-handling-with-automation-rules\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Actuar fuera de Sentinel",
    q: "Ahora quieren que un incidente de severidad alta abra automáticamente un ticket en el ITSM corporativo y avise a un canal de Teams. ¿Qué añade el diseño?",
    options: [
      "Una regla de automatización, que puede invocar sistemas externos por sí sola",
      "Una exportación continua del incidente al almacenamiento del ITSM",
      "Un playbook basado en Logic Apps, disparado por una regla de automatización",
      "Un conector de datos del ITSM en Sentinel",
    ],
    correct: 2,
    explain: "Cuando la acción sale <b>fuera</b> de Sentinel hace falta un <b>playbook</b>: es una Logic App con cientos de conectores, y lo habitual es dispararlo desde una regla de automatización que filtre por severidad. Las reglas por sí solas actúan dentro del incidente. Una exportación mueve datos pero no crea el ticket. Y un conector de datos trae información del ITSM hacia Sentinel, que es la dirección contraria. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/automation/automate-responses-with-playbooks\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Caza frente a detección",
    q: "La dirección pide capacidad para buscar de forma proactiva actividad de atacante que ninguna regla haya detectado todavía. ¿Qué describe correctamente lo que hay que diseñar?",
    options: [
      "Aumentar el número de reglas de análisis activas para cubrir muchas más técnicas conocidas",
      "Automatizar la respuesta para que los incidentes se cierren mucho más rápido",
      "Bajar el umbral de severidad de las alertas para que se escape menos actividad",
      "Caza de amenazas: consultas sobre datos históricos a partir de una hipótesis",
    ],
    correct: 3,
    explain: "Por definición, lo que ninguna regla detecta no se encuentra con más reglas: se encuentra <b>cazando</b>, es decir, formulando una hipótesis sobre cómo se comportaría un atacante y buscándola en los datos que ya están. De ahí que la caza dependa de la <em>retención</em> y del acceso a consultas, no del catálogo de detecciones. Bajar umbrales solo aumenta el ruido, y automatizar la respuesta acelera lo que ya se detecta. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/hunting\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cobertura de detección",
    q: "Te piden demostrar ante el comité de seguridad de qué técnicas de ataque la organización no se enteraría hoy. ¿Cómo lo planteas?",
    options: [
      "Con el número de alertas que el SOC cierra cada mes y su tiempo medio de respuesta",
      "Cruzando las reglas activas contra las técnicas de la matriz MITRE ATT&CK",
      "Con la puntuación de Microsoft Secure Score que tiene el tenant ahora mismo",
      "Con el resultado de la última prueba de intrusión externa contratada",
    ],
    correct: 1,
    explain: "La cobertura de detección se mide contra un <b>catálogo de técnicas</b>, y el estándar es MITRE ATT&CK: se mapean las reglas activas sobre la matriz y lo que queda en blanco es la brecha. El volumen de alertas mide actividad, no cobertura. Secure Score mide postura de configuración. Y una prueba de intrusión da una muestra puntual de lo que un equipo concreto consiguió, no el mapa completo. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/mitre-coverage\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Matriz de ATT&CK para OT",
    q: "El alcance del análisis de cobertura incluye la planta de fabricación, con PLC y sistemas de control industrial. ¿Qué matriz de MITRE ATT&CK aplica a esa parte?",
    options: [
      "ICS, específica de sistemas de control industrial",
      "Enterprise, que ya cubre cualquier sistema operativo del entorno",
      "Mobile, por los terminales de operario en planta",
      "La misma Enterprise, restringida a las técnicas de acceso inicial",
    ],
    correct: 0,
    explain: "MITRE publica <b>tres matrices</b> y no son intercambiables: Enterprise para TI, Mobile para iOS y Android, e <b>ICS</b> para sistemas de control industrial, con técnicas que no existen en TI —manipular la lógica de un PLC, inhibir una función de seguridad—. En un escenario de planta, la matriz ICS es la que corresponde, y es la que acompaña a Defender for IoT. <a href=\"https://learn.microsoft.com/en-us/azure/sentinel/mitre-coverage\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Fases del flujo de respuesta",
    q: "Al revisar el plan de respuesta a incidentes de un cliente, ves que define muy bien la detección y la contención, pero no dice quién decide desconectar un sistema de producción ni cómo se comunica a negocio. ¿Qué falta en el diseño?",
    options: [
      "La definición de roles de decisión y el plan de comunicación del incidente",
      "Más reglas de análisis que cubran los escenarios propios del entorno de producción",
      "Un playbook que aísle de forma automática cualquier sistema con una alerta alta",
      "Un segundo workspace de Sentinel dedicado en exclusiva al entorno de producción",
    ],
    correct: 0,
    explain: "Un plan de respuesta no es solo tecnología: la parte que se falla en los escenarios reales es <b>quién tiene autoridad</b> para tomar una decisión de negocio bajo presión y <b>cómo se informa</b> hacia arriba y hacia fuera. Sin eso, la contención se retrasa mientras se busca a alguien que la autorice. Más reglas no ayudan a decidir, aislar producción automáticamente puede causar más daño que el incidente, y un workspace extra es una decisión de plataforma sin relación. <a href=\"https://learn.microsoft.com/en-us/security/operations/incident-response-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Identidad para un agente de IA",
    q: "Un equipo despliega un agente de IA que consulta SharePoint y abre incidencias por su cuenta, sin que haya una persona detrás en cada ejecución. Seguridad exige poder auditar qué hizo el agente y limitar a qué llega. ¿Qué diseño propones?",
    options: [
      "Darle al agente una identidad propia con Microsoft Entra Agent ID y aplicarle acceso condicional",
      "Ejecutarlo con las credenciales del usuario que lo invocó, para heredar sus permisos",
      "Registrar una aplicación con un secreto compartido guardado en la configuración del servicio",
      "Crear un usuario de servicio con contraseña larga y excluirlo de las políticas de acceso condicional",
    ],
    correct: 0,
    explain: "Un agente que actúa solo es un principal, y como tal necesita <b>identidad propia</b>. <b>Entra Agent ID</b> se la da con ciclo de vida, propietario y rastro de auditoría, y al ser una identidad de primera clase le aplican las políticas de <b>acceso condicional</b>, que es lo que acota a qué llega y bajo qué condiciones. Heredar la identidad del usuario le regala todos sus permisos y hace imposible distinguir en el log quién actuó. Un secreto compartido es una credencial que nadie rota. Y excluir del acceso condicional es quitar justo el control que se pide. <a href=\"https://learn.microsoft.com/en-us/entra/agent-id/what-is-microsoft-entra-agent-id\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Radio de impacto de un agente",
    q: "Tras dar identidad propia a varios agentes, dirección pregunta qué pasaría si uno de ellos quedara comprometido. ¿Qué permite responder a eso?",
    options: [
      "El registro de inicios de sesión de Entra ID filtrado por esas identidades de agente",
      "Un access review trimestral sobre los propietarios registrados de cada uno de los agentes",
      "El análisis de radio de impacto de las identidades de agente en Defender XDR",
      "La puntuación de Secure Score del tenant una vez registrados todos los agentes",
    ],
    correct: 2,
    explain: "La pregunta no es qué ha hecho el agente sino <b>hasta dónde llegaría</b> si alguien lo controlara, y eso se responde analizando su alcance efectivo: a qué recursos accede y qué podría alcanzar desde ahí. Es el análisis de radio de impacto sobre identidades de agente en <b>Defender XDR</b>. Los inicios de sesión son historia, no alcance potencial. Un access review confirma si el agente debe existir. Y Secure Score mide configuración del tenant. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-365-defender\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Ciclo de vida del agente",
    q: "Un equipo despliega varios agentes de IA que consultan datos de negocio. Seguridad pide poder responder, en cualquier momento, quién es responsable de cada agente, a qué accede y si sigue haciendo falta. ¿Qué parte del diseño lo cubre?",
    options: [
      "Guardar en un repositorio interno una hoja con el propietario y el propósito declarado de cada agente desplegado",
      "Registrar cada agente con Entra Agent ID, con propietario, y someterlo a access reviews como a cualquier identidad",
      "Etiquetar los recursos de Azure que hospedan los agentes con el nombre del equipo que los ha desplegado y su centro de coste",
      "Revisar mensualmente los registros de auditoría de las aplicaciones para deducir qué agente ha accedido a qué dato",
    ],
    correct: 1,
    explain: "Las tres preguntas —quién responde, a qué accede, si sigue haciendo falta— son exactamente las que resuelve el <b>gobierno de identidades</b>, y por eso el agente tiene que ser una identidad de directorio y no una entrada en una hoja. Con <b>Entra Agent ID</b> hereda propietario, registro de acceso y <b>access reviews</b>. La hoja y las etiquetas de recurso no se aplican a nada. Y deducirlo de los logs es forense, no gobierno. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/agent-id-governance-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Permisos de un agente",
    q: "Un agente de IA necesita leer un contenedor de Azure Storage y escribir en una cola. El equipo propone darle el rol Colaborador sobre la suscripción «para no tener que ajustarlo cada vez». ¿Qué recomiendas?",
    options: [
      "Aceptarlo mientras el agente esté en pruebas y revisar los permisos concedidos antes del paso a producción",
      "Sustituir el rol por una clave de acceso de la cuenta de almacenamiento guardada en Key Vault y rotada",
      "Asignarle solo los roles de datos sobre el contenedor y la cola concretos que necesita",
      "Mantener Colaborador y compensarlo con una política de acceso condicional que restrinja desde dónde se conecta",
    ],
    correct: 2,
    explain: "Un agente es un principal más y le aplica el <b>mínimo privilegio</b> igual que a una persona: roles de datos acotados al contenedor y la cola, no Colaborador sobre la suscripción. «Está en pruebas» es como se consolidan los permisos excesivos. La clave de acceso reintroduce un secreto que hay que custodiar, cuando la identidad ya evita tenerlo. Y el acceso condicional acota <em>desde dónde</em>, no <em>qué puede hacer</em>: un agente comprometido desde el sitio correcto seguiría siendo administrador. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "SaaS en equipo no gestionado",
    q: "Se permite el acceso a una aplicación SaaS desde equipos personales, pero no se puede permitir que se descarguen documentos en ellos. La aplicación no tiene ninguna función que lo impida. ¿Qué lo resuelve?",
    options: [
      "Una política de acceso condicional que bloquee el inicio de sesión desde equipos no conformes",
      "Publicar la aplicación a través de Microsoft Entra Private Access",
      "Una política de prevención de pérdida de datos de Purview sobre el endpoint personal",
      "Control de aplicaciones de acceso condicional con política de sesión",
    ],
    correct: 3,
    explain: "Cuando la sesión debe permitirse pero <b>limitarse</b>, la pieza es el control de aplicaciones de acceso condicional: el tráfico pasa por <b>Defender for Cloud Apps</b> como proxy inverso y una política de sesión bloquea la descarga dejando ver y editar en línea. Bloquear el inicio de sesión incumple el requisito de permitir el acceso. La DLP de endpoint necesita gestionar un equipo que es personal. Y Private Access publica recursos internos, no gobierna una SaaS de terceros. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/what-is-defender-for-cloud-apps\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Tres capas de acceso",
    q: "Al revisar un diseño de acceso a aplicaciones internas, ves que solo define quién puede autenticarse y con qué MFA. ¿Qué dos capas faltan para que sea completo?",
    options: [
      "La capa de red, por dónde llega, y la de aplicación, qué se hace dentro",
      "Más métodos de autenticación y un segundo proveedor de identidad configurado como respaldo",
      "Un inventario completo de usuarios y un proceso de alta y baja debidamente documentado",
      "Cifrado en reposo de los datos y rotación periódica de las claves de la aplicación",
    ],
    correct: 0,
    explain: "Un diseño de acceso completo tiene tres capas: <b>identidad</b> (quién y bajo qué condiciones), <b>red</b> (por dónde llega: Private Access para lo interno, endpoints privados para PaaS) y <b>aplicación</b> (qué puede hacer dentro, con políticas de sesión). El enunciado solo cubre la primera. Añadir más métodos de autenticación refuerza esa misma capa. El inventario es gobierno de identidad. Y el cifrado protege el dato en reposo, que es otro eje. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Autenticación híbrida y resiliencia",
    q: "Un cliente usa pass-through authentication contra su AD DS. Un corte prolongado en el centro de datos dejó a todos sin poder entrar tampoco en Microsoft 365. Quieren evitarlo sin renunciar a la validación local en el día a día. ¿Qué recomiendas?",
    options: [
      "Añadir más agentes de autenticación repartidos en el mismo centro de datos",
      "Migrar a federación con AD FS y publicar un segundo nodo en la nube",
      "Reducir la duración de los tokens para que se renueven contra la nube",
      "Activar la sincronización de hash de contraseñas como método de respaldo",
    ],
    correct: 3,
    explain: "Con PTA y con federación, la autenticación depende de que el entorno local responda: si cae, no se entra tampoco en la nube. La <b>sincronización de hash de contraseñas</b> como respaldo permite que Entra ID valide por su cuenta cuando el local no está, sin cambiar el método principal. Más agentes en el mismo centro de datos no cubren la caída del centro de datos. AD FS agrava la dependencia. Y acortar tokens empeora el problema: obliga a autenticar más a menudo contra lo que está caído. <a href=\"https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-phs\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detección de credenciales filtradas",
    q: "Seguridad quiere que Entra ID avise cuando la contraseña de un empleado aparezca en una filtración pública. El cliente autentica hoy con federación pura y no sincroniza hashes. ¿Qué hace falta?",
    options: [
      "Habilitar la sincronización de hash de contraseñas, aunque siga autenticando federado",
      "Comprar Microsoft Defender for Identity para todos los controladores de dominio del bosque",
      "Activar el bloqueo inteligente de Entra ID en el tenant y ajustar sus umbrales",
      "Publicar una política de acceso condicional basada en el riesgo de inicio de sesión",
    ],
    correct: 0,
    explain: "Entra ID solo puede comparar una contraseña filtrada con la de tu usuario si tiene su <b>hash sincronizado</b>; con federación pura no lo tiene y esa detección no funciona, aunque la autenticación siga haciéndose contra AD FS. Defender for Identity vigila el AD DS local, no las filtraciones públicas. El bloqueo inteligente frena fuerza bruta. Y una política de riesgo <em>consume</em> la señal que aquí todavía no se está generando. <a href=\"https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Acceso de una empresa colaboradora",
    q: "Una empresa colaboradora necesita acceder a una aplicación interna. No se quieren gestionar sus contraseñas ni sus altas y bajas, y debe aplicárseles el mismo acceso condicional que al personal propio. ¿Qué diseño encaja?",
    options: [
      "Crear usuarios en el tenant propio y sincronizarlos desde el directorio del colaborador",
      "Invitarlos como usuarios B2B, gobernados con cross-tenant access settings",
      "Publicar la aplicación en internet con autenticación propia y una lista de permitidos",
      "Establecer una confianza de bosque entre los dos entornos de AD DS",
    ],
    correct: 1,
    explain: "<b>B2B</b> es exactamente esto: el socio entra con su identidad de origen —su empresa gestiona sus altas, bajas y contraseñas— y en tu tenant existe como invitado, de modo que le aplican tus políticas de acceso condicional. Los <b>cross-tenant access settings</b> son la pieza de gobierno: qué tenants, qué usuarios y si aceptas la MFA que ya hicieron en el suyo. Crear usuarios propios es asumir el ciclo de vida que se quiere evitar, publicar con autenticación propia crea un silo, y una confianza de bosque es desproporcionada. <a href=\"https://learn.microsoft.com/en-us/entra/external-id/what-is-b2b\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Probar un atributo sin almacenarlo",
    q: "Un servicio necesita comprobar que quien solicita acceso posee una titulación concreta, sin guardar sus datos personales ni depender del directorio de la entidad que la emitió. ¿Qué encaja?",
    options: [
      "Una aplicación que consulte por API el directorio de la entidad emisora",
      "Un grupo dinámico de Entra ID basado en un atributo personalizado",
      "Un flujo B2B con revisión manual de la documentación aportada",
      "Credenciales verificables con Microsoft Entra Verified ID",
    ],
    correct: 3,
    explain: "Las <b>credenciales verificables</b> resuelven justo este caso: la entidad emite una credencial firmada, la persona la custodia y la presenta, y el verificador comprueba la firma <b>sin consultar</b> al emisor ni almacenar los datos. Consultar por API crea la dependencia que el enunciado descarta. Un grupo dinámico exige que el atributo ya viva en tu directorio. Y la revisión manual no escala ni evita guardar la documentación. <a href=\"https://learn.microsoft.com/en-us/entra/verified-id/decentralized-identifier-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Revocación inmediata de sesión",
    q: "Al deshabilitar una cuenta comprometida, el usuario siguió accediendo a Exchange Online cerca de una hora con el token que ya tenía. ¿Qué corrige eso?",
    options: [
      "Reducir la vida de los tokens de acceso a unos pocos minutos en todo el tenant",
      "Continuous access evaluation, que aplica la revocación casi al momento",
      "Una política de acceso condicional que exija MFA en cada petición",
      "Un playbook de Sentinel que cierre las sesiones cada vez que se deshabilite una cuenta",
    ],
    correct: 1,
    explain: "Un token de acceso es válido hasta que caduca aunque la cuenta ya esté deshabilitada. <b>Continuous access evaluation</b> resuelve esto haciendo que el recurso y el proveedor de identidad hablen: ante un evento crítico —cuenta deshabilitada, contraseña cambiada, riesgo elevado— la sesión se corta casi al instante. Acortar tokens en todo el tenant reduce la ventana a costa de mucha más latencia y carga. Exigir MFA no invalida un token ya emitido. Y un playbook llega después, con el retardo de su propia ejecución. <a href=\"https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-continuous-access-evaluation\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Riesgo de usuario o de inicio de sesión",
    q: "Se quieren dos respuestas distintas: si Entra ID cree que una cuenta está comprometida, forzar un cambio de contraseña seguro; si solo el inicio de sesión concreto parece anómalo, pedir MFA. ¿Cómo se diseña?",
    options: [
      "Dos políticas: una por riesgo de usuario y otra por riesgo de sesión",
      "Una única política de riesgo con el umbral en medio y MFA como control de concesión",
      "Una política basada en la ubicación de red y otra basada en el estado del dispositivo",
      "Reglas de análisis en Sentinel que disparen playbooks distintos según el tipo de alerta",
    ],
    correct: 0,
    explain: "Entra ID Protection calcula <b>dos riesgos distintos</b>: el de <em>usuario</em> —probabilidad de que la identidad esté comprometida— y el de <em>inicio de sesión</em> —lo anómala que es esta petición concreta—. Se corresponden con dos políticas de acceso condicional y con dos remediaciones diferentes: cambio de contraseña seguro para el primero, MFA para el segundo. Una sola política no puede dar respuestas distintas. La ubicación y el dispositivo son otras señales. Y llevarlo al SIEM añade retardo a algo que el motor resuelve en línea. <a href=\"https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Proteger una operación concreta",
    q: "Se quiere que modificar las propias políticas de acceso condicional exija una autenticación fuerte y reciente, aunque el administrador ya tenga la sesión abierta desde por la mañana. ¿Qué lo consigue?",
    options: [
      "Bajar la duración de la sesión de todos los administradores a una hora",
      "Exigir MFA a los administradores en la política general de acceso condicional",
      "Protected actions, que ligan un requisito de autenticación a esa operación",
      "Una regla de PIM que exija justificación al activar el rol de administrador",
    ],
    correct: 2,
    explain: "Las <b>protected actions</b> asocian un requisito de autenticación a <em>operaciones concretas</em> de alto impacto, de modo que la exigencia se evalúa en el momento de ejecutarlas y no solo al iniciar sesión. Bajar la duración de sesión molesta a todo el mundo todo el día para cubrir un caso puntual. La MFA general ya se cumplió por la mañana. Y PIM controla la activación del rol, no cada operación que se hace mientras está activo. <a href=\"https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/protected-actions-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "MFA resistente a phishing",
    q: "Tras una campaña de phishing que superó la MFA por notificación, se quiere que los administradores solo puedan autenticarse con métodos resistentes a phishing. ¿Qué se aplica?",
    options: [
      "Desactivar el resto de métodos de autenticación para todo el tenant",
      "Una fuerza de autenticación en la política de acceso condicional de esos roles",
      "Aumentar la frecuencia con la que se pide MFA a las cuentas administrativas",
      "Formación específica y una campaña de simulación de phishing para ese grupo",
    ],
    correct: 1,
    explain: "La <b>fuerza de autenticación</b> permite exigir métodos concretos —FIDO2, Windows Hello for Business, certificado— en lugar de «MFA» a secas, y se aplica en la política de acceso condicional solo a los roles que lo necesitan. Desactivar métodos en todo el tenant afecta a usuarios que no lo requieren y suele romper escenarios. Pedir MFA más a menudo repite un método que ya se demostró vulnerable. Y la formación reduce la probabilidad, no cierra el vector. <a href=\"https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-strengths\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Validar el diseño contra Zero Trust",
    q: "Revisas un despliegue de acceso condicional que exige MFA a todos los usuarios para todas las aplicaciones, sin más condiciones ni exclusiones. ¿Cuál es la observación más importante?",
    options: [
      "Que faltan señales de dispositivo y de riesgo, y una cuenta de emergencia excluida",
      "Que debería aplicarse solo a las aplicaciones críticas para reducir la fricción del usuario",
      "Que la MFA por notificación debería sustituirse por códigos enviados en mensajes de texto",
      "Que hace falta una política equivalente definida en cada una de las suscripciones de Azure",
    ],
    correct: 0,
    explain: "Zero Trust exige <b>verificar explícitamente con todas las señales disponibles</b>: usuario y aplicación solos no bastan, faltan el estado del <em>dispositivo</em> y el <em>riesgo</em>. Y hay un fallo operativo grave: sin <b>cuentas de emergencia excluidas</b>, un error en una política puede dejar fuera a todos los administradores a la vez, sin forma de entrar a corregirlo. Reducir el alcance va contra el principio. Los SMS son más débiles, no más fuertes. Y las políticas son del tenant, no por suscripción. <a href=\"https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-emergency-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Verificación explícita",
    q: "Al revisar el diseño de acceso de un cliente encuentras que, una vez el usuario ha hecho MFA al entrar por la mañana, la sesión vale todo el día para cualquier aplicación, incluidas las de administración. ¿Qué principio de Zero Trust se incumple y qué lo corrige?",
    options: [
      "Asumir la brecha; se corrige segmentando la red interna en zonas más pequeñas",
      "Verificar explícitamente; se corrige evaluando cada petición y exigiendo autenticación reciente en lo crítico",
      "Mínimo privilegio; se corrige reduciendo los roles asignados de forma permanente a esos usuarios",
      "Verificar explícitamente; se corrige alargando la caducidad de la contraseña para reducir los cambios",
    ],
    correct: 1,
    explain: "<b>Verificar explícitamente</b> significa evaluar <em>cada</em> petición contra las señales del momento, no confiar en una autenticación de hace horas. Se corrige con frecuencia de inicio de sesión, <b>CAE</b> y, para las operaciones críticas, autenticación reciente y fuerte. Asumir la brecha y el mínimo privilegio son los otros dos principios y describen otros problemas. Y la cuarta opción invoca el principio correcto con una medida que no tiene nada que ver. <a href=\"https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-continuous-access-evaluation\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Validar antes de aplicar",
    q: "Antes de aplicar un conjunto nuevo de políticas de acceso condicional en un tenant de 20.000 usuarios, el cliente quiere saber a quién bloquearían sin bloquear a nadie todavía. ¿Qué haces?",
    options: [
      "Aplicarlas a un grupo piloto de cien usuarios y esperar a las incidencias que reporte el servicio de soporte",
      "Aplicarlas en horario de baja actividad y revertirlas si aumentan las llamadas al servicio de soporte",
      "Desplegarlas en modo solo informe y analizar el impacto con la herramienta What If y los registros de inicio de sesión",
      "Simularlas escribiendo consultas KQL sobre los registros de inicio de sesión históricos del último mes",
    ],
    correct: 2,
    explain: "El <b>modo solo informe</b> evalúa la política en cada inicio de sesión real y registra el resultado <em>sin aplicarlo</em>: es exactamente «saber a quién bloquearía sin bloquear». Con <b>What If</b> se comprueban casos concretos antes incluso de publicarla. El piloto ya bloquea a cien personas. Aplicar y revertir bloquea a todas. Y reconstruirlo a mano en KQL es aproximar con consultas lo que la plataforma calcula exacto. <a href=\"https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-report-only\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Contraseña de administrador local",
    q: "En un dominio con 3.000 equipos, todos comparten la misma contraseña de administrador local. ¿Qué se especifica para cortar el movimiento lateral que eso permite?",
    options: [
      "Deshabilitar por completo la cuenta de administrador local en todos los equipos",
      "Una directiva de grupo que fije una contraseña distinta por departamento",
      "Renombrar la cuenta de administrador local para dificultar su localización",
      "Windows LAPS, que gestiona y rota una contraseña única por equipo",
    ],
    correct: 3,
    explain: "Una contraseña local compartida convierte el compromiso de un equipo en el compromiso de los 3.000: es la base del movimiento lateral con pass-the-hash. <b>Windows LAPS</b> gestiona una contraseña <b>distinta por equipo</b>, la rota y la almacena en el directorio con acceso controlado. Deshabilitar la cuenta rompe la recuperación cuando un equipo pierde la conexión con el dominio. Agrupar por departamento reduce el alcance pero no lo elimina. Y renombrar es oscuridad, no control. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Eliminar el secreto en vez de custodiarlo",
    q: "Una aplicación en Azure App Service guarda en su configuración la cadena de conexión a una base de datos SQL. Se pide reducir el riesgo de credenciales con el menor mantenimiento posible. ¿Qué recomiendas?",
    options: [
      "Mover la cadena a Azure Key Vault y referenciarla desde la configuración",
      "Cifrar la configuración de la aplicación con una clave gestionada por el cliente",
      "Usar una identidad administrada de la aplicación para autenticarse contra SQL",
      "Rotar la contraseña cada 30 días mediante una automatización programada",
    ],
    correct: 2,
    explain: "El orden de preferencia es <b>eliminar el secreto</b> antes que custodiarlo mejor: con una <b>identidad administrada</b> la aplicación obtiene un token de Entra ID contra SQL y no hay contraseña que guardar, rotar ni filtrar, y no hay credencial que mantener. Key Vault es la respuesta correcta cuando el secreto no puede desaparecer, pero aquí sí puede. Cifrar la configuración protege el almacén, no el uso. Y rotar cada 30 días conserva el problema y añade trabajo. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Custodia exclusiva de la clave",
    q: "Un requisito regulatorio obliga a que el material de clave resida en un módulo de un solo inquilino bajo control exclusivo del cliente, con certificación FIPS 140-3 nivel 3. ¿Qué servicio cumple?",
    options: [
      "Azure Key Vault en nivel Standard con claves protegidas por software",
      "Cifrado de infraestructura activado en la cuenta de almacenamiento",
      "Claves gestionadas por el cliente almacenadas en Key Vault Premium",
      "Azure Key Vault Managed HSM",
    ],
    correct: 3,
    explain: "<b>Managed HSM</b> es la oferta de un solo inquilino: el módulo es del cliente y Microsoft no tiene acceso al material de clave, con la certificación que pide el enunciado. Key Vault Standard protege por software. Premium usa HSM pero <em>compartidos</em>, lo que incumple el requisito de inquilino único. Y el cifrado de infraestructura añade una segunda capa sobre el dato, sin decir nada sobre dónde vive la clave. <a href=\"https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Separar planos de control",
    q: "En un cliente, la misma cuenta administra Entra ID, las suscripciones de Azure y entra por RDP en servidores de aplicación. ¿Qué principio del enterprise access model se está incumpliendo y cómo se corrige?",
    options: [
      "La separación de planos: cuentas distintas para identidad, gestión y carga de trabajo",
      "La rotación de credenciales: basta con cambiar la contraseña de esa cuenta cada treinta días",
      "El mínimo privilegio: basta con retirarle los permisos que no haya usado en noventa días",
      "La segmentación de red: basta con aislar esos servidores en una subred independiente",
    ],
    correct: 0,
    explain: "El enterprise access model separa los <b>planos de control, gestión y datos</b>, y prohíbe que una identidad de un plano superior se exponga en uno inferior. Al usar la misma cuenta para entrar en un servidor, sus credenciales quedan en un equipo de menor confianza y desde ahí se llega a Entra ID. Rotar la contraseña no impide que quede en memoria durante la sesión. Recortar permisos no usados deja el problema estructural. Y la segmentación de red no evita que la credencial viaje. <a href=\"https://learn.microsoft.com/en-us/security/privileged-access-workstations/privileged-access-access-model\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "PIM frente a access reviews",
    q: "Un cliente ya tiene todos los roles privilegiados en PIM, con activación limitada a ocho horas y aprobación. La auditoría señala que hay personas elegibles para roles que dejaron de necesitar hace más de un año. ¿Qué falta?",
    options: [
      "Reducir la ventana de activación de ocho horas a una para limitar la exposición",
      "Exigir MFA resistente a phishing en el momento de activar cualquier rol",
      "Access reviews periódicas que recertifiquen quién debe seguir siendo elegible",
      "Convertir esos roles elegibles en asignaciones permanentes para poder auditarlos mejor",
    ],
    correct: 2,
    explain: "PIM responde a <b>cuánto tiempo</b> está activo un rol; no responde a <b>si esa persona debería poder activarlo</b>. Esa segunda pregunta es la de las <b>access reviews</b>: alguien recertifica periódicamente la elegibilidad y lo que no se confirma se retira. Acortar la ventana o endurecer la activación mejora un eje que ya está resuelto. Y volver a asignaciones permanentes va en la dirección contraria. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/access-reviews-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Acceso temporal para externos",
    q: "Un proveedor externo necesita acceso a un conjunto de aplicaciones durante proyectos de tres meses, con aprobación de un responsable de negocio y retirada automática al terminar. ¿Qué capacidad lo cubre?",
    options: [
      "Un grupo de seguridad con la pertenencia gestionada a mano por el equipo de soporte",
      "Paquetes de acceso de entitlement management, con solicitud, aprobación y caducidad",
      "Roles elegibles en PIM asignados uno a uno a cada persona del proveedor externo",
      "Una política de acceso condicional configurada para caducar a los noventa días",
    ],
    correct: 1,
    explain: "El <b>entitlement management</b> empaqueta recursos —aplicaciones, grupos, sitios— en un paquete de acceso con política de solicitud, aprobación y <b>caducidad</b>, y sirve tanto para personal propio como para externos, que pueden solicitarlo desde su propio tenant. El grupo manual es el trabajo que se quiere eliminar. PIM está pensado para roles privilegiados, no para carteras de aplicaciones de negocio. Y una política de acceso condicional no concede ni retira acceso: lo condiciona. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Ataques contra AD DS",
    q: "Durante una evaluación se descubre que una cuenta de servicio con SPN tiene una contraseña débil que no ha cambiado en años. ¿Qué ataque habilita y qué lo corrige de raíz?",
    options: [
      "DCSync; se corrige auditando quién tiene permisos de replicación en el dominio",
      "Golden Ticket; se corrige rotando dos veces la contraseña de la cuenta krbtgt",
      "Kerberoasting; se corrige migrando a cuentas de servicio administradas de grupo",
      "Pass-the-hash; se corrige habilitando Credential Guard en todas las estaciones",
    ],
    correct: 2,
    explain: "Cualquier usuario autenticado puede pedir un ticket de servicio para una cuenta con SPN y romper su contraseña sin conexión: eso es <b>kerberoasting</b>, y lo que lo cierra de raíz es que la contraseña deje de ser humana, con <b>cuentas de servicio administradas de grupo</b>, que la generan larga y la rotan solas. DCSync explota permisos de replicación. Golden Ticket parte del compromiso de krbtgt. Y pass-the-hash reutiliza credenciales en memoria. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/group-managed-service-accounts/group-managed-service-accounts/group-managed-service-accounts-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detectar el ataque en el dominio",
    q: "Además de endurecer AD DS, se quiere detectar en cuanto alguien intente DCSync o enumere el dominio con reconocimiento. ¿Qué se despliega?",
    options: [
      "Directivas de auditoría avanzadas enviando los eventos de seguridad a Sentinel",
      "Un análisis mensual de pertenencia a los grupos privilegiados",
      "Defender for Endpoint en los servidores miembro del dominio",
      "Microsoft Defender for Identity sobre los controladores de dominio",
    ],
    correct: 3,
    explain: "<b>Defender for Identity</b> se instala en los controladores de dominio y está construido para exactamente estas técnicas: DCSync, Golden Ticket, kerberoasting, reconocimiento y movimiento lateral, con detecciones ya escritas. Volcar eventos crudos a Sentinel obliga a escribir y mantener esas detecciones desde cero. Defender for Endpoint protege el servidor, no el protocolo de directorio. Y una revisión mensual llega tarde y solo ve pertenencia. <a href=\"https://learn.microsoft.com/en-us/defender-for-identity/what-is\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Permisos sin usar en varias nubes",
    q: "Una organización con cargas en Azure, AWS y GCP quiere identificar qué identidades tienen permisos concedidos que no utilizan, y recortarlos al uso real. ¿Qué recomiendas?",
    options: [
      "El panel de cumplimiento normativo de Microsoft Defender for Cloud",
      "Access reviews de Entra ID sobre los grupos que dan acceso a cada una de las tres nubes",
      "Las capacidades CIEM del plan Defender CSPM en Defender for Cloud",
      "Azure Policy con iniciativas asignadas a cada suscripción de Azure y a cada proyecto de GCP",
    ],
    correct: 2,
    explain: "Esto es <b>gestión de permisos de infraestructura en la nube</b> (CIEM), y hoy vive dentro de <b>Defender for Cloud</b>, en el plan <b>Defender CSPM</b>: analiza la configuración y el uso real de las identidades en Azure, AWS y GCP y devuelve recomendaciones sobre identidades inactivas y permisos excesivos. Ojo con el producto anterior: <em>Microsoft Entra Permissions Management</em> hacía justo esto, pero Microsoft lo retiró el 1 de noviembre de 2025 y dirigió a los clientes a Defender CSPM. El panel de cumplimiento evidencia conformidad con una norma. Las access reviews recertifican pertenencia, sin saber qué se usa. Y Azure Policy gobierna configuración de recursos, no permisos de identidades. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/permissions-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Recortar el permiso concedido",
    q: "Las recomendaciones CIEM de Defender for Cloud señalan un rol de AWS, usado por un equipo de datos, con permisos muy por encima de lo que utiliza. El equipo teme que recortarlo rompa sus procesos nocturnos. ¿Cómo se plantea el recorte?",
    options: [
      "Retirar el rol y volver a concederlo solo cuando alguien reclame que algo ha dejado de funcionar",
      "Dejarlo como está y compensarlo con una alerta cada vez que el rol ejecute una acción privilegiada",
      "Ajustar el rol al uso observado, con un periodo de observación que cubra el ciclo nocturno completo",
      "Sustituir el rol por credenciales de larga duración específicas para cada uno de los procesos nocturnos",
    ],
    correct: 2,
    explain: "El valor de CIEM no es la etiqueta de riesgo: es que sabe <em>qué se ha usado realmente</em>, y con eso se puede escribir un rol ajustado a ese uso. El miedo del equipo se responde alargando la <b>ventana de observación</b> hasta que hayan entrado los procesos nocturnos, no renunciando al recorte. Retirar y esperar quejas es provocar la incidencia. La alerta detecta después de que ocurra. Y las credenciales de larga duración cambian un permiso excesivo por un secreto permanente: empeoran el problema. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/permissions-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Administración del tenant",
    q: "¿Qué DOS medidas son imprescindibles al diseñar la administración de un tenant de Entra ID para que no se convierta en un punto único de fallo?",
    options: [
      "Cuentas de emergencia excluidas del acceso condicional y con alerta si se usan",
      "Roles administrativos concedidos mediante activación temporal en PIM",
      "Un segundo tenant de respaldo con los mismos usuarios sincronizados",
      "Contraseñas de administrador de al menos veinte caracteres, rotadas cada mes",
    ],
    correct: [0, 1],
    explain: "Las dos que sostienen el diseño son las <b>cuentas de emergencia</b> —excluidas de las políticas para que un error de acceso condicional no deje a todos fuera, y vigiladas con alerta porque su uso siempre es excepcional— y que los roles se obtengan por <b>activación temporal en PIM</b> en vez de ser permanentes. Un tenant de respaldo duplica la superficie sin resolver nada, y la longitud de la contraseña es irrelevante frente a un token robado o una política mal escrita. <a href=\"https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-emergency-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Desde dónde se administra",
    q: "Los administradores de dominio trabajan desde sus portátiles habituales, con correo y navegación. La cuenta está en PIM y exige MFA. ¿Qué riesgo queda sin cubrir?",
    options: [
      "Que la contraseña sea adivinada por fuerza bruta contra el controlador de dominio",
      "Que el equipo desde el que se administra esté comprometido y capture la sesión",
      "Que la activación del rol en PIM no quede registrada en los logs de auditoría",
      "Que la MFA se pueda repetir desde otra ubicación geográfica distinta",
    ],
    correct: 1,
    explain: "PIM y MFA protegen la <b>cuenta</b>, pero la sesión se abre en un equipo que además lee correo y navega. Si ese equipo cae, el atacante no necesita la contraseña: hereda la sesión ya autenticada. Por eso el diseño exige una <b>estación de acceso privilegiado</b> dedicada y endurecida. La fuerza bruta la frenan el bloqueo y la MFA. La activación sí se registra. Y la reutilización de MFA la cubre el acceso condicional. <a href=\"https://learn.microsoft.com/en-us/security/privileged-access-workstations/privileged-access-devices\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Acceso remoto a los servidores",
    q: "Los administradores ya trabajan desde estaciones dedicadas y endurecidas, pero llegan a las máquinas virtuales por RDP publicado en internet con una IP pública por servidor. ¿Qué recomiendas?",
    options: [
      "Restringir el puerto RDP a las direcciones IP públicas de las oficinas mediante grupos de seguridad de red",
      "Azure Bastion, con Entra ID y acceso condicional delante y sin IP pública en las máquinas",
      "Acceso just-in-time a los puertos de administración en Defender for Cloud, manteniendo la IP pública",
      "Una VPN de sitio a sitio entre las oficinas y la red virtual, dejando el RDP publicado como respaldo",
    ],
    correct: 1,
    explain: "La estación dedicada resuelve <em>desde qué equipo</em> se administra; falta resolver <em>cómo se llega</em>. <b>Azure Bastion</b> quita la IP pública de la máquina y pone la sesión detrás de Entra ID y del acceso condicional, que es donde ya viven las decisiones de identidad. Filtrar por IP sigue exponiendo el puerto y confía en la red como perímetro. El acceso just-in-time reduce la ventana pero mantiene la exposición. Y dejar el RDP publicado «de respaldo» conserva justo el camino que se quería cerrar. <a href=\"https://learn.microsoft.com/en-us/azure/bastion/bastion-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Del requisito al control",
    q: "Un cliente debe cumplir una norma que obliga a cifrar cierta categoría de datos en reposo y a demostrarlo periódicamente ante un auditor. ¿Qué diseño responde a las dos partes del requisito?",
    options: [
      "Una política de Azure Policy con efecto Deny sobre los recursos sin cifrar",
      "El panel de cumplimiento normativo de Defender for Cloud como única medida",
      "Un informe manual trimestral elaborado por el equipo de plataforma",
      "Azure Policy para exigir el cifrado y Defender for Cloud para evidenciarlo",
    ],
    correct: 3,
    explain: "Son <b>dos obligaciones distintas</b>: implementar y demostrar. <b>Azure Policy</b> implementa —impide o corrige el recurso no conforme— y el panel de <b>cumplimiento normativo</b> de Defender for Cloud evidencia, mapeando el estado real contra los controles del estándar de forma continua y exportable. Cada una por separado deja media respuesta. Y el informe manual no es repetible ni verificable. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/regulatory-compliance-dashboard\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El marco entero o la obligación",
    q: "Un cliente tiene que cumplir un marco normativo extenso en Azure y pide el mínimo esfuerzo operativo posible. El equipo propone escribir desde cero las políticas de cada control. ¿Qué recomiendas?",
    options: [
      "Asignar la iniciativa integrada de ese marco y escribir solo las políticas de los controles que no cubra",
      "Escribir las políticas desde cero para que reflejen con exactitud el lenguaje del marco normativo aplicable",
      "Empezar por el Microsoft Cloud Security Benchmark y considerar el marco cubierto una vez esté al cien por cien",
      "Documentar los controles en un procedimiento y verificarlos con una revisión manual trimestral del entorno",
    ],
    correct: 0,
    explain: "«Mínimo esfuerzo operativo» es la pista: Azure Policy trae <b>iniciativas integradas</b> para los marcos habituales y Defender for Cloud las expone en el panel de cumplimiento normativo. Se asigna lo que ya existe y se escribe solo la diferencia. Escribirlo todo duplica un trabajo hecho y hay que mantenerlo. El MCSB es una buena base pero no es equivalente a un marco concreto. Y el procedimiento con revisión manual no es un control técnico ni evidencia repetible. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/samples/built-in-initiatives\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Implementar y evidenciar",
    q: "Una obligación normativa exige que ningún almacenamiento sea accesible públicamente y que se pueda demostrar el cumplimiento ante un auditor externo cada trimestre. ¿Qué DOS piezas incluye el diseño?",
    options: [
      "Una alerta de Sentinel cada vez que se cree una cuenta de almacenamiento en cualquier suscripción",
      "Una política de Azure con efecto Deny sobre el acceso público, asignada al grupo de administración",
      "Una regla de automatización que asigne al equipo de plataforma los incidentes de almacenamiento",
      "El panel de cumplimiento normativo de Defender for Cloud, del que sale la evidencia por control",
    ],
    correct: [1, 3],
    explain: "La obligación tiene dos mitades: <b>impedir</b> y <b>demostrar</b>. La primera es <b>Azure Policy</b> con <code>Deny</code> en el ámbito correcto —el grupo de administración, no suscripción a suscripción—; la segunda es el <b>panel de cumplimiento normativo</b>, que muestra control a control el estado real y se puede exportar para el auditor. La alerta avisa de la creación pero no la impide ni la evidencia, y la regla de automatización solo reparte incidentes. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Orden de despliegue de una política",
    q: "Se quiere exigir una configuración de seguridad en una suscripción que ya tiene cientos de recursos desplegados, muchos de ellos no conformes, sin interrumpir los despliegues en curso. ¿Cómo se plantea?",
    options: [
      "Asignar la política con efecto Deny y corregir después lo que deje de funcionar",
      "Aplicar DeployIfNotExists directamente sobre todos los recursos no conformes",
      "Auditar primero para medir, remediar lo existente y aplicar Deny al final",
      "Excluir los recursos actuales del ámbito y aplicar Deny solo a los nuevos",
    ],
    correct: 2,
    explain: "Un <code>Deny</code> de entrada no arregla nada de lo que ya existe —solo bloquea lo nuevo— y suele romper despliegues legítimos. La secuencia que espera el examen es <b>Audit</b> para medir el alcance real, <b>remediación</b> de lo existente y <b>Deny</b> al final para que la desviación no vuelva. Ir directamente a DeployIfNotExists sobre cientos de recursos cambia producción sin medir. Y excluir lo existente deja el incumplimiento permanente. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Purview para el dato regulado",
    q: "Una norma exige saber dónde reside cierta categoría de dato personal en Microsoft 365, impedir que salga por correo y conservarlo siete años. ¿Qué DOS capacidades de Microsoft Purview cubren el requisito?",
    options: [
      "Clasificación con etiquetas de confidencialidad para descubrir y marcar el dato",
      "Barreras de información para separar la comunicación entre departamentos",
      "Gestión de riesgo interno para puntuar el comportamiento de cada empleado",
      "Prevención de pérdida de datos para impedir la salida por los canales de riesgo",
    ],
    correct: [0, 3],
    explain: "El requisito tiene dos verbos: <b>saber dónde está</b> y <b>evitar que salga</b>. Lo primero es clasificación con etiquetas de confidencialidad; lo segundo, <b>prevención de pérdida de datos</b>. La retención de siete años la resuelve la gestión del ciclo de vida, que no está entre las opciones. El riesgo interno mide comportamiento y las barreras de información separan comunicaciones: ninguna de las dos descubre ni bloquea la salida del dato. <a href=\"https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Puntuación o conformidad",
    q: "El comité pide un informe que muestre, control a control, el grado de conformidad con ISO 27001 en Azure y también en las suscripciones de AWS conectadas. ¿Qué se lleva a la reunión?",
    options: [
      "La evolución de la puntuación de Microsoft Secure Score en los últimos seis meses",
      "El informe de cobertura de detección sobre las matrices de MITRE ATT&CK",
      "El resumen de incidentes cerrados por el SOC en el portal de Defender XDR",
      "El panel de cumplimiento normativo de Defender for Cloud con ISO 27001 añadido",
    ],
    correct: 3,
    explain: "El <b>panel de cumplimiento normativo</b> de Defender for Cloud mapea el estado real de los recursos contra los controles de un estándar —MCSB por defecto, y los que añadas, incluido ISO 27001— y cubre también las suscripciones de AWS y GCP conectadas. <b>Secure Score</b> mide mejora relativa de la postura, no conformidad con una norma: es la confusión que busca la pregunta. Los incidentes y la cobertura de detección miden operación, no cumplimiento. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/regulatory-compliance-dashboard\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["operations-identity"] = QUIZ_DATA;
