const QUIZ_DATA = [
  {
    tag: "GuardDuty",
    q: "What data sources does Amazon GuardDuty analyze for behavior to detect threats, without you having to manually enable logging in each account?",
    options: [
      "Only CloudTrail",
      "CloudTrail (management and data events), VPC Flow Logs, DNS logs, and optionally EKS audit logs and runtime monitoring — GuardDuty consumes these sources internally without you having to enable or separately pay for them",
      "Only CloudWatch metrics",
      "Only application logs that you send it manually",
    ],
    correct: 1,
    explain: "GuardDuty is 'serverless' in the sense that it internally consumes CloudTrail, VPC Flow Logs, and DNS query logs (and optionally EKS audit logs, EC2/ECS/EKS runtime monitoring, RDS login activity, S3 data events) WITHOUT you having to enable or separately manage them — you turn on the service and it's already analyzing.",
  },
  {
    tag: "GuardDuty vs Macie vs Config",
    q: "You need to automatically discover which S3 buckets in your account contain credit card numbers or personally identifiable information (PII), without writing the detection rules yourself. Which service do you use?",
    options: [
      "Amazon GuardDuty",
      "Amazon Macie: uses machine learning and managed patterns to automatically discover and classify sensitive data in S3",
      "AWS Config",
      "Amazon Inspector",
    ],
    correct: 1,
    explain: "Macie specializes in DISCOVERING AND CLASSIFYING sensitive data in S3 (PII, credentials, financial data...) using machine learning and predefined (or custom) patterns. GuardDuty detects anomalous behavior/threats — it doesn't classify data content.",
  },
  {
    tag: "AWS Security Hub",
    q: "What is AWS Security Hub's main role relative to GuardDuty, Macie, and Inspector?",
    options: [
      "It replaces all three, making it unnecessary to have them enabled",
      "It aggregates and normalizes findings from GuardDuty, Macie, Inspector, and others (including third-party products) into a centralized dashboard, and also runs its own compliance checks against standards (CIS, PCI-DSS, AWS FSBP)",
      "It only works with EC2 resources",
      "It's a security billing service",
    ],
    correct: 1,
    explain: "Security Hub is the AGGREGATOR: it centralizes findings from multiple AWS and third-party detection services in one place, and additionally runs its own compliance controls against recognized security standards (CIS AWS Foundations, PCI-DSS, AWS Foundational Security Best Practices).",
  },
  {
    tag: "Automating evaluations",
    q: "You want a set of AWS Config rules (e.g., 'every S3 bucket must have encryption enabled') to apply automatically to ALL accounts in an OU in your organization, centrally. What do you use?",
    options: [
      "Individual Config Rules in each account, replicated manually",
      "AWS Config Conformance Packs deployed at the organization level — a package of rules + remediations deployed centrally to all accounts in an OU",
      "Amazon Inspector",
      "An SCP with the same effect",
    ],
    correct: 1,
    explain: "Conformance Packs bundle a set of Config Rules (and optional remediation actions) as a single template that can be deployed centrally at the organization level, avoiding rule-by-rule configuration in each account — part of skill 1.1.5 on automating regular evaluations.",
  },
  {
    tag: "Organizational CloudTrail",
    q: "What advantage does configuring a CloudTrail 'organization trail' from the management account have over creating an independent trail in each member account?",
    options: [
      "None, the cost and coverage are identical",
      "The organization trail applies automatically to ALL accounts (current and future) in the organization, cannot be disabled or modified by member accounts, and centralizes logs in a single S3 bucket",
      "The organization trail doesn't record management events, only data events",
      "You can only have one organization trail active in the entire management account",
    ],
    correct: 1,
    explain: "An organization trail created from the management account (or a delegated administrator) is automatically replicated to all current AND future member accounts, without them being able to disable it, guaranteeing complete and immutable coverage — key for skill 1.2.2.",
  },
  {
    tag: "Dedicated logging account",
    q: "Why is it best practice to send security logs (CloudTrail, VPC Flow Logs...) to a dedicated logging ACCOUNT, separate from workload accounts?",
    options: [
      "It's a mandatory technical requirement of CloudTrail",
      "It isolates the logs from a possible compromise of the workload account: if an attacker compromises the production account, they can't reach or alter the logs (which already live in a different account with minimal, distinct permissions)",
      "It cuts storage costs in half",
      "It lets you avoid using KMS",
    ],
    correct: 1,
    explain: "Separating logs into a dedicated account (with very restricted access, often the 'Log Archive account' in Control Tower) defends against the scenario where an attacker who compromises the workload account tries to delete or alter the evidence of their actions — the logs are no longer there for them to touch.",
  },
  {
    tag: "Amazon Security Lake",
    q: "What problem does Amazon Security Lake specifically solve compared to simply centralizing logs in an S3 bucket?",
    options: [
      "None, it's just an S3 bucket with a different name",
      "It automatically normalizes logs from multiple AWS sources (and compatible third parties) to the open OCSF schema, organizing them into a partitioned data lake optimized for querying, without you having to write ETL transformations",
      "It completely replaces CloudTrail",
      "It only accepts logs from GuardDuty",
    ],
    correct: 1,
    explain: "Security Lake automates ingestion, normalization to OCSF, partitioning (by source/region/date), and lifecycle management of security logs from multiple accounts and sources (AWS and integrated third parties), eliminating the manual ETL work you'd need if you just centralized into a raw S3 bucket.",
  },
  {
    tag: "Athena vs CloudWatch Logs Insights",
    q: "When is it more appropriate to use Amazon Athena instead of CloudWatch Logs Insights to analyze security logs?",
    options: [
      "Never, they're interchangeable in all cases",
      "Athena is better for ad-hoc SQL queries over large volumes of historical data stored in S3 (e.g., a Security Lake data lake); CloudWatch Logs Insights is better for quick queries over recent logs already in a CloudWatch log group",
      "CloudWatch Logs Insights doesn't support any kind of filtering",
      "Athena can only query VPC Flow Logs",
    ],
    correct: 1,
    explain: "Athena queries data in S3 with standard SQL (ideal for large historical volumes, like Security Lake's normalized data). CloudWatch Logs Insights uses its own query language optimized for recent logs already ingested into CloudWatch Logs — faster for immediate investigations, less suited to massive historical analysis.",
  },
  {
    tag: "Normalization and correlation",
    q: "Which AWS service is typically used to build visualization and correlation dashboards for security events from multiple sources (Security Lake, OpenSearch, CloudWatch)?",
    options: [
      "Amazon Managed Grafana",
      "AWS Config",
      "AWS Trusted Advisor",
      "Amazon Inspector",
    ],
    correct: 0,
    explain: "Amazon Managed Grafana offers a managed Grafana service for building dashboards that correlate metrics and logs from multiple data sources (CloudWatch, OpenSearch, Athena/Security Lake, Prometheus...) without managing the Grafana infrastructure yourself — skill 1.2.5.",
  },
  {
    tag: "VPC Flow Logs",
    q: "What information do VPC Flow Logs capture?",
    options: [
      "The complete content (payload) of every network packet",
      "IP connection metadata (source, destination, ports, protocol, bytes, ACCEPT/REJECT action) at the ENI, subnet, or VPC level — NOT the traffic's content/payload",
      "Only HTTP/HTTPS traffic",
      "Only connection attempts blocked by Security Groups",
    ],
    correct: 1,
    explain: "VPC Flow Logs capture connection METADATA (5-tuple + bytes + action), similar to a phone call log: who called whom, how long it lasted, but NOT the content of the conversation. They're the primary source for detecting port scans, data exfiltration via anomalous volume, or communication with malicious IPs.",
  },
  {
    tag: "Route 53 Resolver logs",
    q: "What visibility do Route 53 Resolver query logs specifically provide that VPC Flow Logs don't?",
    options: [
      "None, they're redundant",
      "They capture DNS queries made from resources inside the VPC (which domain was resolved, the response, who asked) — key for detecting communication with C2 (Command & Control) domains or DNS-tunneling exfiltration techniques",
      "They only record DNS resolution failures",
      "They only work if Route 53 is used as the domain registrar",
    ],
    correct: 1,
    explain: "While VPC Flow Logs see the resulting IP connection, Resolver query logs see the DNS QUERY that came before it — essential for detecting malware resolving known C2 domains, or data exfiltration encoded in DNS subqueries (DNS tunneling), even before the IP connection is established.",
  },
  {
    tag: "Logging troubleshooting",
    q: "You notice CloudWatch Logs isn't receiving logs from an EC2 instance where the CloudWatch Agent is installed and running. What are the two most likely causes to check first?",
    options: [
      "The EC2 instance type chosen and the operating system version",
      "The agent's configuration file (which logs/paths it's configured to send) and the Instance Profile's IAM permissions (missing the logs:PutLogEvents permission or similar)",
      "The server's time zone",
      "The size of the EBS volume",
    ],
    correct: 1,
    explain: "The two most common culprits when debugging 'the agent is running but no logs arrive' are: (1) an agent configuration file pointed at the wrong place (incorrect log paths, misreferenced log group), and (2) insufficient IAM permissions on the Instance Profile/execution role to write to CloudWatch Logs — exactly skill 1.3.2 on remediating 'CloudWatch Agent configuration' and 'missing logs'.",
  },
  {
    tag: "Logging troubleshooting",
    q: "A developer reports that invocations of their Lambda function aren't generating logs in CloudWatch, even though the function executes successfully. What's the most likely cause to check first?",
    options: [
      "The Lambda function exceeds the memory limit",
      "The Lambda function's execution role doesn't have the logs:CreateLogStream / logs:PutLogEvents permission (part of the AWSLambdaBasicExecutionRole managed policy)",
      "The region where the function is deployed",
      "The Lambda runtime used",
    ],
    correct: 1,
    explain: "Lambda needs its execution role to have explicit permissions to write to CloudWatch Logs (normally via the AWSLambdaBasicExecutionRole managed policy). If they're missing, the function executes normally (the logging failure doesn't block execution) but simply nothing shows up in CloudWatch — a classic troubleshooting case for skill 1.3.1.",
  },
  {
    tag: "Amazon API Gateway logging",
    q: "What type of logging must be explicitly enabled in Amazon API Gateway to capture the body of requests and responses, useful for debugging authorization issues?",
    options: [
      "Default execution logging always includes it already",
      "Data trace logging (at the stage level), which in addition to standard execution logs records the request/response detail — it must be explicitly enabled because it can expose sensitive data",
      "AWS X-Ray automatically, with no configuration",
      "It's not possible to capture the body under any circumstances",
    ],
    correct: 1,
    explain: "API Gateway distinguishes between 'execution logging' (execution metadata: errors, latency) and 'data trace logging' (full request/response detail, including headers and body). Data trace is enabled separately because it exposes potentially sensitive information in the logs — relevant to skill 1.3.1 on analyzing resource logging configuration.",
  },
  {
    tag: "CloudFront logging",
    q: "What two logging modes does Amazon CloudFront offer for analyzing the requests reaching a distribution?",
    options: [
      "Only one type of log, with no options",
      "Standard logging (access logs delivered to S3 with some delay) and Real-time logs (sent to Kinesis Data Streams with a latency of seconds, for near-real-time alerting)",
      "Only real-time logs, with no option for delayed logs",
      "CloudFront doesn't support native logging, you have to use a separate WAF",
    ],
    correct: 1,
    explain: "Standard logs (access logs) are delivered to an S3 bucket with some delay and are free, ideal for historical/forensic analysis. Real-time logs are sent to Kinesis Data Streams within seconds, allowing you to alert on or react to traffic patterns almost immediately — the choice depends on whether you need speed (real-time) or cheap deferred analysis (standard).",
  },
  {
    tag: "Aggregating findings across accounts",
    q: "To get a consolidated view of GuardDuty and Security Hub findings from ALL accounts in your organization without logging into each one, what pattern is used?",
    options: [
      "Manually copying findings into a spreadsheet",
      "Designating an account as the 'delegated administrator' for GuardDuty and Security Hub, which automatically aggregates findings from all member accounts of the organization into a single dashboard",
      "It's not possible to consolidate findings across accounts",
      "Using SCPs to force consolidation",
    ],
    correct: 1,
    explain: "Both GuardDuty and Security Hub support the 'delegated administrator' model: a designated account (typically the security/logging account) automatically sees and manages findings from all member accounts in the Organization, without needing to log into each one individually.",
  },
  {
    tag: "Workload analysis",
    q: "Before designing a monitoring strategy for a new workload, what should you analyze first according to skill 1.1.1?",
    options: [
      "Only the workload's estimated monthly cost",
      "The workload's monitoring requirements: what assets exist, which events are critical to detect, what alert-latency level is needed, and what compliance applies",
      "The name that will be given to the workload",
      "The CI/CD provider that will be used",
    ],
    correct: 1,
    explain: "Skill 1.1.1 (analyzing workloads to determine monitoring requirements) is the foundation before choosing tools: without understanding what assets exist, which events matter, and what detection SLA is needed, any GuardDuty/Security Hub/alarm configuration will be generic instead of tailored to that workload's actual risk.",
  },
  {
    tag: "Health checks",
    q: "In the context of skill 1.1.2 (designing workload monitoring strategies by configuring health checks), what distinguishes a Route 53 health check from a basic CloudWatch alarm?",
    options: [
      "They're exactly the same",
      "A Route 53 health check actively verifies an endpoint's availability from multiple global locations (and can trigger DNS failover), while a CloudWatch alarm passively reacts to metrics that the resource itself is already publishing",
      "Route 53 health checks only work with EC2 instances",
      "CloudWatch can't alarm on an endpoint's health",
    ],
    correct: 1,
    explain: "Route 53 health checks perform periodic ACTIVE probes against an endpoint from globally distributed locations, useful for deciding DNS failover. CloudWatch alarms are PASSIVE: they consume metrics already published (by the resource or by you) and trigger an action when they cross a threshold — both are pieces of a monitoring strategy, serving different purposes.",
  },
  {
    tag: "OCSF",
    q: "Why does Amazon Security Lake normalize logs to the OCSF format instead of storing them in each service's original format?",
    options: [
      "Due to an SEC legal requirement",
      "So that analysis tools and third-party SIEMs can query and correlate events from completely different sources (CloudTrail, GuardDuty, third-party firewalls...) using a common schema, without writing a separate parser for each proprietary format",
      "OCSF automatically cuts log size in half",
      "It's a technical requirement of S3 in order to query with Athena",
    ],
    correct: 1,
    explain: "The value of OCSF is INTEROPERABILITY: an authentication event from CloudTrail and one from a third-party firewall, both normalized to OCSF, share the same field structure — allowing you to correlate a 'failed login' across both sources with a single query, instead of writing separate parsing logic for each product.",
  },
];
