const QUIZ_DATA = [
  {
    tag: "GuardDuty",
    q: "What data sources does Amazon GuardDuty analyze for behavior to detect threats, without you having to manually enable logging in each account?",
    options: [
      "Only CloudTrail",
      "CloudTrail (management and data events), VPC Flow Logs, DNS logs, and optionally EKS audit logs and runtime monitoring — GuardDuty consumes these sources internally without you having to enable or separately pay for them",
      "Only CloudWatch metrics",
      "Only application logs that you send it manually",
    ],
    correct: 1,
    explain: "GuardDuty is 'serverless' in the sense that it internally consumes CloudTrail, VPC Flow Logs, and DNS query logs (and optionally EKS audit logs, EC2/ECS/EKS runtime monitoring, RDS login activity, S3 data events) WITHOUT you having to enable or separately manage them — you turn on the service and it's already analyzing.",
  },
  {
    tag: "GuardDuty vs Macie vs Config",
    q: "You need to automatically discover which S3 buckets in your account contain credit card numbers or personally identifiable information (PII), without writing the detection rules yourself. Which service do you use?",
    options: [
      "Amazon GuardDuty",
      "Amazon Macie: uses machine learning and managed patterns to automatically discover and classify sensitive data in S3",
      "AWS Config",
      "Amazon Inspector",
    ],
    correct: 1,
    explain: "Macie specializes in DISCOVERING AND CLASSIFYING sensitive data in S3 (PII, credentials, financial data...) using machine learning and predefined (or custom) patterns. GuardDuty detects anomalous behavior/threats — it doesn't classify data content.",
  },
  {
    tag: "AWS Security Hub",
    q: "What is AWS Security Hub's main role relative to GuardDuty, Macie, and Inspector?",
    options: [
      "It replaces all three, making it unnecessary to have them enabled",
      "It aggregates and normalizes findings from GuardDuty, Macie, Inspector, and others (including third-party products) into a centralized dashboard, and also runs its own compliance checks against standards (CIS, PCI-DSS, AWS FSBP)",
      "It only works with EC2 resources",
      "It's a security billing service",
    ],
    correct: 1,
    explain: "Security Hub is the AGGREGATOR: it centralizes findings from multiple AWS and third-party detection services in one place, and additionally runs its own compliance controls against recognized security standards (CIS AWS Foundations, PCI-DSS, AWS Foundational Security Best Practices).",
  },
  {
    tag: "Automating evaluations",
    q: "You want a set of AWS Config rules (e.g., 'every S3 bucket must have encryption enabled') to apply automatically to ALL accounts in an OU in your organization, centrally. What do you use?",
    options: [
      "Individual Config Rules in each account, replicated manually",
      "AWS Config Conformance Packs deployed at the organization level — a package of rules + remediations deployed centrally to all accounts in an OU",
      "Amazon Inspector",
      "An SCP with the same effect",
    ],
    correct: 1,
    explain: "Conformance Packs bundle a set of Config Rules (and optional remediation actions) as a single template that can be deployed centrally at the organization level, avoiding rule-by-rule configuration in each account — part of skill 1.1.5 on automating regular evaluations.",
  },
  {
    tag: "Organizational CloudTrail",
    q: "What advantage does configuring a CloudTrail 'organization trail' from the management account have over creating an independent trail in each member account?",
    options: [
      "None, the cost and coverage are identical",
      "The organization trail applies automatically to ALL accounts (current and future) in the organization, cannot be disabled or modified by member accounts, and centralizes logs in a single S3 bucket",
      "The organization trail doesn't record management events, only data events",
      "You can only have one organization trail active in the entire management account",
    ],
    correct: 1,
    explain: "An organization trail created from the management account (or a delegated administrator) is automatically replicated to all current AND future member accounts, without them being able to disable it, guaranteeing complete and immutable coverage — key for skill 1.2.2.",
  },
  {
    tag: "Dedicated logging account",
    q: "Why is it best practice to send security logs (CloudTrail, VPC Flow Logs...) to a dedicated logging ACCOUNT, separate from workload accounts?",
    options: [
      "It's a mandatory technical requirement of CloudTrail",
      "It isolates the logs from a possible compromise of the workload account: if an attacker compromises the production account, they can't reach or alter the logs (which already live in a different account with minimal, distinct permissions)",
      "It cuts storage costs in half",
      "It lets you avoid using KMS",
    ],
    correct: 1,
    explain: "Separating logs into a dedicated account (with very restricted access, often the 'Log Archive account' in Control Tower) defends against the scenario where an attacker who compromises the workload account tries to delete or alter the evidence of their actions — the logs are no longer there for them to touch.",
  },
  {
    tag: "Amazon Security Lake",
    q: "What problem does Amazon Security Lake specifically solve compared to simply centralizing logs in an S3 bucket?",
    options: [
      "None, it's just an S3 bucket with a different name",
      "It automatically normalizes logs from multiple AWS sources (and compatible third parties) to the open OCSF schema, organizing them into a partitioned data lake optimized for querying, without you having to write ETL transformations",
      "It completely replaces CloudTrail",
      "It only accepts logs from GuardDuty",
    ],
    correct: 1,
    explain: "Security Lake automates ingestion, normalization to OCSF, partitioning (by source/region/date), and lifecycle management of security logs from multiple accounts and sources (AWS and integrated third parties), eliminating the manual ETL work you'd need if you just centralized into a raw S3 bucket.",
  },
  {
    tag: "Athena vs CloudWatch Logs Insights",
    q: "When is it more appropriate to use Amazon Athena instead of CloudWatch Logs Insights to analyze security logs?",
    options: [
      "Never, they're interchangeable in all cases",
      "Athena is better for ad-hoc SQL queries over large volumes of historical data stored in S3 (e.g., a Security Lake data lake); CloudWatch Logs Insights is better for quick queries over recent logs already in a CloudWatch log group",
      "CloudWatch Logs Insights doesn't support any kind of filtering",
      "Athena can only query VPC Flow Logs",
    ],
    correct: 1,
    explain: "Athena queries data in S3 with standard SQL (ideal for large historical volumes, like Security Lake's normalized data). CloudWatch Logs Insights uses its own query language optimized for recent logs already ingested into CloudWatch Logs — faster for immediate investigations, less suited to massive historical analysis.",
  },
  {
    tag: "Normalization and correlation",
    q: "Which AWS service is typically used to build visualization and correlation dashboards for security events from multiple sources (Security Lake, OpenSearch, CloudWatch)?",
    options: [
      "Amazon Managed Grafana",
      "AWS Config",
      "AWS Trusted Advisor",
      "Amazon Inspector",
    ],
    correct: 0,
    explain: "Amazon Managed Grafana offers a managed Grafana service for building dashboards that correlate metrics and logs from multiple data sources (CloudWatch, OpenSearch, Athena/Security Lake, Prometheus...) without managing the Grafana infrastructure yourself — skill 1.2.5.",
  },
  {
    tag: "VPC Flow Logs",
    q: "What information do VPC Flow Logs capture?",
    options: [
      "The complete content (payload) of every network packet",
      "IP connection metadata (source, destination, ports, protocol, bytes, ACCEPT/REJECT action) at the ENI, subnet, or VPC level — NOT the traffic's content/payload",
      "Only HTTP/HTTPS traffic",
      "Only connection attempts blocked by Security Groups",
    ],
    correct: 1,
    explain: "VPC Flow Logs capture connection METADATA (5-tuple + bytes + action), similar to a phone call log: who called whom, how long it lasted, but NOT the content of the conversation. They're the primary source for detecting port scans, data exfiltration via anomalous volume, or communication with malicious IPs.",
  },
  {
    tag: "Route 53 Resolver logs",
    q: "What visibility do Route 53 Resolver query logs specifically provide that VPC Flow Logs don't?",
    options: [
      "None, they're redundant",
      "They capture DNS queries made from resources inside the VPC (which domain was resolved, the response, who asked) — key for detecting communication with C2 (Command & Control) domains or DNS-tunneling exfiltration techniques",
      "They only record DNS resolution failures",
      "They only work if Route 53 is used as the domain registrar",
    ],
    correct: 1,
    explain: "While VPC Flow Logs see the resulting IP connection, Resolver query logs see the DNS QUERY that came before it — essential for detecting malware resolving known C2 domains, or data exfiltration encoded in DNS subqueries (DNS tunneling), even before the IP connection is established.",
  },
  {
    tag: "Logging troubleshooting",
    q: "You notice CloudWatch Logs isn't receiving logs from an EC2 instance where the CloudWatch Agent is installed and running. What are the two most likely causes to check first?",
    options: [
      "The EC2 instance type chosen and the operating system version",
      "The agent's configuration file (which logs/paths it's configured to send) and the Instance Profile's IAM permissions (missing the logs:PutLogEvents permission or similar)",
      "The server's time zone",
      "The size of the EBS volume",
    ],
    correct: 1,
    explain: "The two most common culprits when debugging 'the agent is running but no logs arrive' are: (1) an agent configuration file pointed at the wrong place (incorrect log paths, misreferenced log group), and (2) insufficient IAM permissions on the Instance Profile/execution role to write to CloudWatch Logs — exactly skill 1.3.2 on remediating 'CloudWatch Agent configuration' and 'missing logs'.",
  },
  {
    tag: "Logging troubleshooting",
    q: "A developer reports that invocations of their Lambda function aren't generating logs in CloudWatch, even though the function executes successfully. What's the most likely cause to check first?",
    options: [
      "The Lambda function exceeds the memory limit",
      "The Lambda function's execution role doesn't have the logs:CreateLogStream / logs:PutLogEvents permission (part of the AWSLambdaBasicExecutionRole managed policy)",
      "The region where the function is deployed",
      "The Lambda runtime used",
    ],
    correct: 1,
    explain: "Lambda needs its execution role to have explicit permissions to write to CloudWatch Logs (normally via the AWSLambdaBasicExecutionRole managed policy). If they're missing, the function executes normally (the logging failure doesn't block execution) but simply nothing shows up in CloudWatch — a classic troubleshooting case for skill 1.3.1.",
  },
  {
    tag: "Amazon API Gateway logging",
    q: "What type of logging must be explicitly enabled in Amazon API Gateway to capture the body of requests and responses, useful for debugging authorization issues?",
    options: [
      "Default execution logging always includes it already",
      "Data trace logging (at the stage level), which in addition to standard execution logs records the request/response detail — it must be explicitly enabled because it can expose sensitive data",
      "AWS X-Ray automatically, with no configuration",
      "It's not possible to capture the body under any circumstances",
    ],
    correct: 1,
    explain: "API Gateway distinguishes between 'execution logging' (execution metadata: errors, latency) and 'data trace logging' (full request/response detail, including headers and body). Data trace is enabled separately because it exposes potentially sensitive information in the logs — relevant to skill 1.3.1 on analyzing resource logging configuration.",
  },
  {
    tag: "CloudFront logging",
    q: "What two logging modes does Amazon CloudFront offer for analyzing the requests reaching a distribution?",
    options: [
      "Only one type of log, with no options",
      "Standard logging (access logs delivered to S3 with some delay) and Real-time logs (sent to Kinesis Data Streams with a latency of seconds, for near-real-time alerting)",
      "Only real-time logs, with no option for delayed logs",
      "CloudFront doesn't support native logging, you have to use a separate WAF",
    ],
    correct: 1,
    explain: "Standard logs (access logs) are delivered to an S3 bucket with some delay and are free, ideal for historical/forensic analysis. Real-time logs are sent to Kinesis Data Streams within seconds, allowing you to alert on or react to traffic patterns almost immediately — the choice depends on whether you need speed (real-time) or cheap deferred analysis (standard).",
  },
  {
    tag: "Aggregating findings across accounts",
    q: "To get a consolidated view of GuardDuty and Security Hub findings from ALL accounts in your organization without logging into each one, what pattern is used?",
    options: [
      "Manually copying findings into a spreadsheet",
      "Designating an account as the 'delegated administrator' for GuardDuty and Security Hub, which automatically aggregates findings from all member accounts of the organization into a single dashboard",
      "It's not possible to consolidate findings across accounts",
      "Using SCPs to force consolidation",
    ],
    correct: 1,
    explain: "Both GuardDuty and Security Hub support the 'delegated administrator' model: a designated account (typically the security/logging account) automatically sees and manages findings from all member accounts in the Organization, without needing to log into each one individually.",
  },
  {
    tag: "Workload analysis",
    q: "Before designing a monitoring strategy for a new workload, what should you analyze first according to skill 1.1.1?",
    options: [
      "Only the workload's estimated monthly cost",
      "The workload's monitoring requirements: what assets exist, which events are critical to detect, what alert-latency level is needed, and what compliance applies",
      "The name that will be given to the workload",
      "The CI/CD provider that will be used",
    ],
    correct: 1,
    explain: "Skill 1.1.1 (analyzing workloads to determine monitoring requirements) is the foundation before choosing tools: without understanding what assets exist, which events matter, and what detection SLA is needed, any GuardDuty/Security Hub/alarm configuration will be generic instead of tailored to that workload's actual risk.",
  },
  {
    tag: "Health checks",
    q: "In the context of skill 1.1.2 (designing workload monitoring strategies by configuring health checks), what distinguishes a Route 53 health check from a basic CloudWatch alarm?",
    options: [
      "They're exactly the same",
      "A Route 53 health check actively verifies an endpoint's availability from multiple global locations (and can trigger DNS failover), while a CloudWatch alarm passively reacts to metrics that the resource itself is already publishing",
      "Route 53 health checks only work with EC2 instances",
      "CloudWatch can't alarm on an endpoint's health",
    ],
    correct: 1,
    explain: "Route 53 health checks perform periodic ACTIVE probes against an endpoint from globally distributed locations, useful for deciding DNS failover. CloudWatch alarms are PASSIVE: they consume metrics already published (by the resource or by you) and trigger an action when they cross a threshold — both are pieces of a monitoring strategy, serving different purposes.",
  },
  {
    tag: "OCSF",
    q: "Why does Amazon Security Lake normalize logs to the OCSF format instead of storing them in each service's original format?",
    options: [
      "Due to an SEC legal requirement",
      "So that analysis tools and third-party SIEMs can query and correlate events from completely different sources (CloudTrail, GuardDuty, third-party firewalls...) using a common schema, without writing a separate parser for each proprietary format",
      "OCSF automatically cuts log size in half",
      "It's a technical requirement of S3 in order to query with Athena",
    ],
    correct: 1,
    explain: "The value of OCSF is INTEROPERABILITY: an authentication event from CloudTrail and one from a third-party firewall, both normalized to OCSF, share the same field structure — allowing you to correlate a 'failed login' across both sources with a single query, instead of writing separate parsing logic for each product.",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "A security analyst reviews Security Hub and sees a CRITICAL severity finding that GuardDuty had never issued at that level before, titled something like 'AttackSequence:IAM/CompromisedCredentials'. The finding groups together several individual events (privilege discovery, API manipulation, persistence) that occurred over a period of time. What GuardDuty feature generated this finding?",
    options: [
      "GuardDuty Malware Protection, which scans EBS volumes for malware",
      "GuardDuty Extended Threat Detection, which uses AI/ML to correlate multiple individual low/medium severity findings into a single critical-severity attack sequence, mapped to MITRE ATT&CK tactics",
      "Amazon Detective, which automatically generates findings without needing GuardDuty",
      "AWS Config, which evaluates the configuration state of the resources involved",
    ],
    correct: 1,
    explain: "GuardDuty Extended Threat Detection (GA December 2024) analyzes patterns across multiple data sources and time periods to generate 'attack sequence findings' (AttackSequence: prefix) that represent a chain of steps taken by an attacker (discovery, movement, persistence, exfiltration) as a single CRITICAL-severity finding — a level GuardDuty never used before this feature. It differs from Detective, which helps you INVESTIGATE relationships between findings that already exist, not generate them.",
  },
  {
    tag: "GuardDuty Malware Protection for S3",
    q: "An application lets external users upload files directly to an S3 bucket before a pipeline processes them. The security team wants to automatically scan every new object for malware BEFORE the pipeline consumes it, without deploying or maintaining their own scanning infrastructure. Which native AWS solution meets this requirement?",
    options: [
      "Enable Amazon Inspector on the S3 bucket",
      "GuardDuty Malware Protection for S3: automatically scans newly uploaded objects in configured buckets using AWS-managed and third-party scanning engines, and generates a finding or tags the object if malware is detected",
      "Configure Macie with a classification job on the bucket",
      "Enable SSE-KMS encryption on the bucket, which automatically blocks malicious files",
    ],
    correct: 1,
    explain: "GuardDuty Malware Protection for S3 (GA June 2024) is a fully managed, agentless service that scans newly uploaded objects in selected S3 buckets, triggered by the s3:ObjectCreated event, and can tag the object or trigger automated remediation depending on configuration. Macie classifies sensitive CONTENT (PII) — it doesn't detect malware; Inspector evaluates EC2/ECR/Lambda vulnerabilities, not S3 objects; encryption doesn't analyze the file's content.",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "How does GuardDuty Malware Protection for EC2 (triggered after a finding on a potentially compromised instance) scan that instance's disk for malware without affecting the running production instance's performance?",
    options: [
      "It installs an agent inside the running instance's operating system and scans live",
      "It reboots the instance into recovery mode to scan the disk offline",
      "It takes a snapshot of the EBS volumes attached to the suspicious instance and scans that snapshot in isolation, agentlessly, without touching the original running instance",
      "It requires stopping the instance before any volume can be scanned",
    ],
    correct: 2,
    explain: "GuardDuty Malware Protection for EC2 is AGENTLESS: when triggered (automatically after certain findings, or on demand), it takes a snapshot of the EBS volumes on the suspicious instance/container and scans THAT snapshot in an AWS-managed scanning account, without installing anything on the original instance or affecting its availability or performance, and without needing to stop or reboot it.",
  },
  {
    tag: "GuardDuty RDS Protection",
    q: "A company runs Aurora PostgreSQL clusters. They want to detect brute-force attempts against database credentials and access from unusual login patterns, without modifying the database engine or degrading its performance. Which GuardDuty feature addresses this?",
    options: [
      "GuardDuty Malware Protection for S3",
      "GuardDuty RDS Protection: profiles and monitors login activity (successes and failures) on Aurora/RDS databases using ML models, generating findings such as CredentialAccess:RDS/AnomalousBehavior.SuccessfulLogin or .FailedLogin, without requiring any database changes",
      "Amazon Inspector, scanning the Aurora engine for vulnerabilities",
      "AWS Config, evaluating whether encryption at rest is enabled",
    ],
    correct: 1,
    explain: "GuardDuty RDS Protection monitors and profiles login activity for Aurora databases (MySQL- and PostgreSQL-compatible), RDS for PostgreSQL, and Aurora PostgreSQL Limitless Database, without requiring agents or engine changes, generating anomalous-credential findings (successful login from an unusual IP/pattern, or a spike in failed attempts indicative of brute forcing) with rich context about the affected database.",
  },
  {
    tag: "GuardDuty Lambda Protection",
    q: "A team suspects a Lambda function has been compromised and is being used to mine cryptocurrency or communicate with a Command and Control (C2) server, even in functions that are NOT configured inside a VPC. Which GuardDuty feature detects this behavior?",
    options: [
      "AWS X-Ray, by analyzing invocation traces",
      "GuardDuty Lambda Protection, which monitors the network activity logs generated by ALL Lambda functions in the account (whether or not they're configured with VPC networking) to detect communication with known malicious IPs/domains or cryptocurrency-mining patterns",
      "AWS Config, evaluating the function's network configuration",
      "Amazon Inspector, scanning the function's code for malware",
    ],
    correct: 1,
    explain: "GuardDuty Lambda Protection analyzes the network activity logs generated every time an account's Lambda function is invoked — including functions WITHOUT VPC configuration — to detect outbound traffic to known malicious infrastructure (C2, cryptocurrency mining), applying smart filters so you're only charged for the subset of that network log data relevant to detection.",
  },
  {
    tag: "GuardDuty EKS Runtime Monitoring",
    q: "When you enable GuardDuty EKS Runtime Monitoring on an EKS cluster, how is the security agent deployed to gain OS-level visibility (process execution, file access, network connections) on each node?",
    options: [
      "As a Lambda function that runs periodically against the Kubernetes API",
      "As a sidecar container injected into each pod",
      "No agent is required — it only analyzes EKS audit logs",
      "As the 'aws-guardduty-agent' EKS add-on, deployed as an eBPF-based DaemonSet that runs on every supported node in the cluster",
    ],
    correct: 3,
    explain: "For EKS, the GuardDuty agent is distributed as the 'aws-guardduty-agent' EKS add-on and deployed as a DaemonSet (one instance of the agent per supported node in the cluster), built on eBPF to get kernel-level telemetry with low overhead. This contrasts with the ECS Fargate deployment, where the agent is injected as a sidecar container into each task, because Fargate exposes no persistent nodes to run a DaemonSet on.",
  },
  {
    tag: "GuardDuty ECS/Fargate Runtime Monitoring",
    q: "An organization runs most of its workloads on Amazon ECS on Fargate (with no EC2 instances or nodes to manage). How does GuardDuty deploy the Runtime Monitoring agent in this case, given that Fargate exposes no persistent nodes to run a DaemonSet on?",
    options: [
      "Runtime Monitoring isn't possible on Fargate, only on ECS on EC2",
      "GuardDuty automatically injects a sidecar container (prefixed 'aws-guardduty-agent-') into every Fargate ECS task when automated agent management is enabled, without you having to manually modify task definitions",
      "The customer must build their own container image with the agent manually included in every Dockerfile",
      "It's deployed as an extension of the CloudWatch Agent inside the application's own container",
    ],
    correct: 1,
    explain: "Unlike EKS (a DaemonSet per node), on ECS Fargate GuardDuty deploys the agent as an additional SIDECAR CONTAINER inside each task — visible as a container prefixed 'aws-guardduty-agent-' — automatically injected when automated agent management (ECS_FARGATE_AGENT_MANAGEMENT) is enabled, or via inclusion tags on the cluster, with no need to modify existing task definitions.",
  },
  {
    tag: "Security Hub: risk prioritization",
    q: "In late 2025, AWS reorganized Security Hub: the compliance-checking service that had existed until then (CIS, PCI-DSS, AWS FSBP) was renamed 'Security Hub CSPM' and is now a sub-component of a broader 'new' Security Hub. What additional capability does this new Security Hub add on top of the original Security Hub CSPM?",
    options: [
      "It removes the need to have GuardDuty or Inspector enabled",
      "Near real-time risk correlation and prioritization: it automatically combines findings from Security Hub CSPM (configuration), Inspector (vulnerabilities), and GuardDuty (threats) to generate 'exposure findings' that identify, for example, a publicly exposed resource with a critical vulnerability and access to sensitive data",
      "It removes the use of ASFF/OCSF as the finding format",
      "It only adds a security cost dashboard, with no functional changes",
    ],
    correct: 1,
    explain: "The new Security Hub (general GA in late 2025) adds a risk analysis layer that automatically correlates signals from multiple services (Security Hub CSPM, Inspector, GuardDuty, Macie) to produce 'exposure findings' — business context on which combined findings represent the greatest real risk (e.g., public exposure + critical vulnerability + sensitive data), instead of requiring an analyst to manually correlate thousands of individual low-priority findings. It still needs GuardDuty/Inspector enabled as sources.",
  },
  {
    tag: "CloudTrail network activity events",
    q: "Your organization uses VPC endpoints (AWS PrivateLink) so workloads can reach services like S3 or KMS without going out to the internet. You want to audit API activity that crosses those VPC endpoints, including activity generated by AWS services acting on your behalf, something standard CloudTrail (management/data events) doesn't always capture with the same level of detail. Which feature do you use?",
    options: [
      "VPC Flow Logs, which already capture the detail of the API that was invoked",
      "Amazon Detective, which automatically reconstructs those calls",
      "CloudTrail network activity events for VPC endpoints: an opt-in event class that records API activity (control plane and data plane) crossing a VPC endpoint for supported services (e.g., S3, EC2, KMS, Secrets Manager), including activity generated by AWS services acting on your behalf",
      "GuardDuty, by enabling the S3 data source",
    ],
    correct: 2,
    explain: "CloudTrail network activity events for VPC endpoints (GA February 2025) is a new event TYPE, distinct from traditional management/data events, that provides visibility into API activity passing through a VPC endpoint for supported services — including calls made by AWS services on your behalf. VPC Flow Logs only see network metadata (IP/port), not which API was invoked.",
  },
  {
    tag: "Route 53 DNS Firewall Advanced",
    q: "A security team has configured Route 53 Resolver DNS Firewall with managed domain lists (malware, known botnets) but is still worried about malware that generates random domains via a Domain Generation Algorithm (DGA) or that uses DNS tunneling to exfiltrate data — techniques specifically designed to evade static domain lists. Which DNS Firewall capability specifically addresses this threat?",
    options: [
      "Increasing the TTL of DNS responses in the hosted zone",
      "DNS Firewall Advanced (advanced DNS threat protection), which analyzes the pattern of the queries themselves — instead of comparing against a fixed domain list — to detect DGA and DNS tunneling based on a configurable confidence threshold",
      "Enabling DNSSEC on the Route 53 hosted zone",
      "Migrating DNS queries to a third-party resolver outside the VPC",
    ],
    correct: 1,
    explain: "DNS Firewall's 'Foundational' rules block against lists of known domains (malicious, managed by AWS or Recorded Future). DNS Firewall Advanced adds a rule tier that analyzes the PATTERN of the query itself (length, entropy, structure) to detect techniques specifically designed to evade static lists, such as DGA and DNS tunneling, letting you tune a 'confidence_threshold' instead of relying solely on domain lists.",
  },
  {
    tag: "Amazon Detective finding groups",
    q: "An analyst has dozens of seemingly unrelated low/medium severity GuardDuty findings in Security Hub, and suspects several belong to the same attack campaign but doesn't have time to correlate them manually. Which Amazon Detective feature directly helps with this?",
    options: [
      "Detective automatically generates new GuardDuty findings that replace the originals",
      "Finding groups: Detective uses machine learning to automatically group related findings (that share resources, IAM roles, or source IPs) that together reveal the lifecycle of an attack, and includes natural-language summaries generated with generative AI",
      "Detective replaces Security Hub as the findings aggregation dashboard",
      "Detective can only analyze one finding at a time, with no grouping capability",
    ],
    correct: 1,
    explain: "Amazon Detective's finding groups use ML to identify which GuardDuty findings (and also Inspector findings) are related by sharing entities (the same IAM role, the same session, the same IP), grouping low-severity signals that in isolation might be ignored but together show a complete attack campaign — and it includes natural-language summaries generated with generative AI to accelerate investigation.",
  },
  {
    tag: "Macie automated sensitive data discovery",
    q: "An account has hundreds of S3 buckets holding petabytes of data. The team wants to maintain CONTINUOUS visibility into which buckets contain sensitive data without paying to fully scan every object on a recurring basis, which would be prohibitively expensive. Which Macie capability is specifically designed for this case?",
    options: [
      "A sensitive data discovery job scheduled to run daily over 100% of the objects",
      "Amazon Inspector, applied to the account's S3 buckets",
      "GuardDuty S3 Protection, which already includes content classification",
      "Automated sensitive data discovery: it evaluates the S3 inventory daily and analyzes a REPRESENTATIVE SAMPLE of objects (intelligent sampling) in each bucket to keep a sensitivity profile current, at a much lower cost than scanning 100% of the content",
    ],
    correct: 3,
    explain: "Automated sensitive data discovery is the Macie capability that evaluates the S3 inventory continuously (daily) and applies intelligent SAMPLING over a representative subset of objects per bucket, instead of scanning every object — keeping visibility of which buckets hold sensitive data current at a fraction of the cost of an exhaustive classification job. Traditional sensitive data discovery jobs (one-time or scheduled) still exist for thorough, targeted analysis when you need to examine 100% of a specific scope.",
  },
  {
    tag: "AWS Security Incident Response",
    q: "An organization wants a triage workflow to fire automatically whenever GuardDuty or Security Hub CSPM generates a critical finding, and wants 24/7 access to an AWS incident response team to collaborate on containment, without building that integration themselves from scratch. Which AWS service covers this use case?",
    options: [
      "AWS Trusted Advisor",
      "AWS Security Incident Response: automatically ingests and triages findings from GuardDuty and Security Hub CSPM (including third parties integrated via Security Hub), enables collaboration on containment, and gives direct access to the AWS Customer Incident Response Team (CIRT)",
      "Amazon Detective, by enabling a supposed 'incident response mode'",
      "AWS Config, via an automatic remediation",
    ],
    correct: 1,
    explain: "AWS Security Incident Response (GA December 2024) is a dedicated service that automatically ingests and triages findings from GuardDuty and Security Hub CSPM (including third-party integrations via Security Hub), offers collaboration tools for response, can take containment actions with your permission, and gives you 24/7 direct access to the AWS Customer Incident Response Team — this isn't a Trusted Advisor, Detective, or Config capability.",
  },
  {
    tag: "Security Lake rollup regions",
    q: "A company operates in three AWS regions and, for regulatory compliance reasons, needs Security Lake's security data from each region to also remain available locally, but also wants to consolidate a copy of all of it into a single region for centralized analysis. Which Security Lake concept enables this?",
    options: [
      "S3 cross-region replication, configured manually outside of Security Lake",
      "Security Lake can only operate in a single region per organization",
      "Rollup regions: you designate a region as a 'rollup' region that receives a copy of the data from one or more 'contributing regions', without removing the original data from its source regions",
      "AWS Config aggregator, redirected to consolidate Security Lake's data",
    ],
    correct: 2,
    explain: "Security Lake lets you designate one or more rollup regions that receive a COPY of the data from the specified contributing regions (the original data still exists in its source regions/buckets, satisfying data residency requirements), while also giving you a single integration point for centralized analysis tools — configurable via the console or the UpdateDataLake API.",
  },
  {
    tag: "CloudWatch cross-account observability",
    q: "The security team wants to view, from a single central monitoring account, the metrics, CloudWatch Logs, and X-Ray traces generated across dozens of workload accounts in the organization, WITHOUT copying or duplicating that data between accounts. What AWS mechanism enables this?",
    options: [
      "Copying each member account's log groups to the central account via CloudWatch Logs subscriptions",
      "CloudWatch cross-account observability via Observability Access Manager (OAM): links are configured between source accounts and a central monitoring account, which can query and visualize telemetry from the source accounts without the data being duplicated or leaving its source account",
      "Amazon Security Lake, which already automatically centralizes all CloudWatch metrics",
      "A CloudTrail organization trail configured to include CloudWatch metrics",
    ],
    correct: 1,
    explain: "OAM (Observability Access Manager) is the service underlying CloudWatch cross-account observability: through 'sinks' (in the monitoring account) and 'links' (from each source account), it lets a central account query and visualize metrics, logs, and traces from up to 100,000 source accounts WITHOUT moving or copying the data — it's queried in place, unlike a subscription-based solution built on CloudWatch Logs subscriptions, which does replicate the logs into another account.",
  },
  {
    tag: "AWS Config aggregator",
    q: "You want a single account to have a consolidated view of Config Rules compliance status and resource inventory across ALL accounts in your AWS Organization and all of their regions, without necessarily making that account the Security Hub delegated administrator. Which AWS Config resource do you use?",
    options: [
      "A CloudTrail organization trail pointed at that account",
      "A conformance pack, which by itself already centralizes visualization without needing an aggregator",
      "Amazon Security Lake, redirecting only AWS Config's data",
      "An organization-level AWS Config aggregator: it collects configuration and Config Rules compliance data from all member accounts (and regions) of the Organization into a single account, without needing to manually replicate Config Rules configuration in every account",
    ],
    correct: 3,
    explain: "A Config aggregator (in its organization variant) is a specific AWS Config resource that collects and consolidates, into a single account, the resource configuration state and Config Rules compliance of all member accounts and enabled regions in the Organization — a concept independent of the Security Hub/GuardDuty delegated administrator, even though they can coexist in the same security account. A conformance pack by itself deploys rules — it doesn't aggregate their visualization across accounts.",
  },
  {
    tag: "Security Hub vs Security Lake aggregation",
    q: "A security architect needs to explain the difference between 'Security Hub cross-region aggregation' and Amazon Security Lake's 'rollup regions', since both sound like 'centralizing data from multiple regions'. What is the correct distinction?",
    options: [
      "They are exactly the same mechanism with different names depending on the service",
      "Security Hub cross-region aggregation consolidates Security Hub FINDINGS (and those from the services feeding it) from multiple regions into an aggregation region for viewing in a single dashboard; Security Lake rollup regions consolidate copies of OCSF-normalized LOGS from multiple regions into a bucket in a destination region — they operate on different data and different layers",
      "Security Hub cross-region aggregation only works within a single account, while Security Lake rollup regions works across separate organizations",
      "Both features mandatorily require Security Lake to be enabled as a technical prerequisite",
    ],
    correct: 1,
    explain: "Although both address 'I want to see data from multiple regions in one place', they operate on different layers: Security Hub cross-region aggregation works with FINDINGS (the output of detection/evaluation) and replicates them to a designated aggregation region for the Security Hub dashboard; Security Lake rollup regions work with raw OCSF-normalized LOGS and replicate copies of those logs to a destination region for analysis. They are not interchangeable and neither technically depends on the other.",
  },
  {
    tag: "GuardDuty at organization scale",
    q: "A company with 180 accounts in AWS Organizations wants GuardDuty enabled everywhere, and any new account protected with no manual step. Which TWO are required?",
    options: [
      "Designate an account as the GuardDuty delegated administrator from the management account",
      "Turn on auto-enable so new organization accounts are onboarded automatically",
      "Create an IAM role in every member account allowing GuardDuty to read CloudTrail",
      "Enable GuardDuty manually in each account and invite them one by one from the central account",
    ],
    correct: [0, 1],
    explain: "GuardDuty is governed in Organizations through a <b>delegated administrator</b> plus <b>auto-enable</b>, which onboards new accounts with no action. GuardDuty ingests CloudTrail, VPC Flow Logs and DNS logs on its own via a service-linked role, so no roles or log setup are needed. The manual invitation flow exists but is exactly what this requirement rules out, and it misses future accounts.",
  },
  {
    tag: "CloudTrail: data events",
    q: "After an incident the team finds CloudTrail did not record WHO downloaded specific objects from an S3 bucket, though it did record the bucket's creation. Which TWO statements explain and fix this?",
    options: [
      "Management events log bucket-level operations but not operations on individual objects",
      "S3 data events must be enabled for the bucket, logging read operations such as GetObject",
      "CloudTrail can never log object access: only S3 server access logging can do it",
      "Simply increasing the existing trail's retention will surface the events retroactively",
    ],
    correct: [0, 1],
    explain: "CloudTrail separates <b>management events</b> (control plane: CreateBucket, PutBucketPolicy) from <b>data events</b> (data plane: GetObject, PutObject), and data events are off by default because of their cost and volume. S3 server access logging is an alternative, not the only route. Retention never manufactures events that were never captured: what wasn't logged doesn't exist.",
  },
  {
    tag: "Immutable logging account",
    q: "Audit requires that CloudTrail logs cannot be deleted or altered by an administrator of the account that produces them, not even with root credentials. Which TWO achieve this?",
    options: [
      "Deliver the logs to an S3 bucket in a separate, dedicated logging account with its own bucket policy",
      "Apply S3 Object Lock in compliance mode on the destination bucket",
      "Encrypt the bucket with SSE-S3 instead of SSE-KMS",
      "Enable bucket versioning and trust that administrators won't delete versions",
    ],
    correct: [0, 1],
    explain: "Account separation removes the source-account admin's power, and <b>Object Lock in compliance mode</b> blocks deletion even for root during the retention period (governance mode allows an exception with a special permission, which is why it wouldn't do here). The encryption type doesn't change who can delete. Versioning helps recovery, but an admin with permissions can delete versions: trust is not a control.",
  },
  {
    tag: "Security Hub multi-Region",
    q: "An organization operates in 5 Regions and wants to review all Security Hub findings from a single pane, in one account and Region. Which TWO are needed?",
    options: [
      "Designate a Security Hub delegated administrator for the organization",
      "Configure an aggregation Region that consolidates findings from the other Regions",
      "Manually replicate findings with a per-Region Lambda function",
      "Disable Security Hub in the secondary Regions to avoid duplicates",
    ],
    correct: [0, 1],
    explain: "Security Hub needs a <b>delegated administrator</b> for the multi-account view and <b>cross-Region aggregation</b> for the multi-Region view; they are two separate axes and both are required. Replicating with Lambda reinvents a native feature. Disabling Security Hub in the other Regions would remove the very findings you want to see: controls are evaluated where the resources live.",
  },
];
