var QUIZ_DATA = [
  {
    tag: "GuardDuty",
    q: "What data sources does Amazon GuardDuty analyze for behavior to detect threats, without you having to manually enable logging in each account?",
    options: [
      "CloudTrail (management and data events), VPC Flow Logs, DNS logs and EKS audit logs",
      "Only CloudTrail management events, since every other source has to be enabled separately",
      "The CloudWatch metrics of each resource, which GuardDuty reads through a read-only role",
      "The application logs you publish into a CloudWatch log group designated for GuardDuty",
    ],
    correct: 0,
    explain: "GuardDuty is 'serverless' in the sense that it internally consumes CloudTrail, VPC Flow Logs, and DNS query logs (and optionally EKS audit logs, EC2/ECS/EKS runtime monitoring, RDS login activity, S3 data events) WITHOUT you having to enable or separately manage them — you turn on the service and it's already analyzing. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty vs Macie vs Config",
    q: "You need to automatically discover which S3 buckets in your account contain credit card numbers or personally identifiable information (PII), without writing the detection rules yourself. Which service do you use?",
    options: [
      "Amazon GuardDuty, which profiles S3 access behavior and flags the buckets holding sensitive data",
      "Amazon Macie, which applies managed data identifiers and ML to classify S3 content",
      "AWS Config, whose managed rules inspect the contents of the objects in each bucket",
      "Amazon Inspector, which scans S3 objects the same way it scans container images",
    ],
    correct: 1,
    explain: "Macie specializes in DISCOVERING AND CLASSIFYING sensitive data in S3 (PII, credentials, financial data...) using machine learning and predefined (or custom) patterns. GuardDuty detects anomalous behavior/threats — it doesn't classify data content. <a href=\"https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Security Hub",
    q: "What is AWS Security Hub's main role relative to GuardDuty, Macie, and Inspector?",
    options: [
      "It replaces all three: once enabled you can turn GuardDuty, Macie and Inspector off",
      "It only evaluates EC2 resources, so S3 or IAM findings stay in each source service",
      "It aggregates and normalizes AWS and third-party findings, and runs compliance checks",
      "It splits and bills the cost of the security services across the organization accounts",
    ],
    correct: 2,
    explain: "Security Hub is the AGGREGATOR: it centralizes findings from multiple AWS and third-party detection services in one place, and additionally runs its own compliance controls against recognized security standards (CIS AWS Foundations, PCI-DSS, AWS Foundational Security Best Practices). <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Automating evaluations",
    q: "You want a set of AWS Config rules (e.g., 'every S3 bucket must have encryption enabled') to apply automatically to ALL accounts in an OU in your organization, centrally. What do you use?",
    options: [
      "Create the same Config rule account by account and keep the copies in sync by hand",
      "An SCP that denies s3:PutObject whenever the bucket has no encryption enabled",
      "Amazon Inspector, which evaluates the encryption configuration of every bucket",
      "AWS Config Conformance Packs deployed at the organization level onto the OU",
    ],
    correct: 3,
    explain: "Conformance Packs bundle a set of Config Rules (and optional remediation actions) as a single template that can be deployed centrally at the organization level, avoiding rule-by-rule configuration in each account — part of skill 1.1.5 on automating regular evaluations. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Organizational CloudTrail",
    q: "What advantage does configuring a CloudTrail 'organization trail' from the management account have over creating an independent trail in each member account?",
    options: [
      "It applies to all accounts, current and future, and members cannot disable it",
      "None functionally: only the creation point changes, cost and coverage are identical",
      "It records data events only; management events still need a per-account trail",
      "It covers only the management account, so each member still needs its own trail",
    ],
    correct: 0,
    explain: "An organization trail created from the management account (or a delegated administrator) is automatically replicated to all current AND future member accounts, without them being able to disable it, guaranteeing complete and immutable coverage — key for skill 1.2.2. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/creating-an-organizational-trail-in-the-console.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Dedicated logging account",
    q: "Why is it best practice to send security logs (CloudTrail, VPC Flow Logs...) to a dedicated logging ACCOUNT, separate from workload accounts?",
    options: [
      "CloudTrail technically requires a separate account to deliver into an S3 bucket",
      "It isolates the evidence from whoever compromises the workload account",
      "S3 storage is billed at half price once delivery crosses an account boundary",
      "It lets you deliver the logs unencrypted and avoid the cost of KMS keys",
    ],
    correct: 1,
    explain: "Separating logs into a dedicated account (with very restricted access, often the 'Log Archive account' in Control Tower) defends against the scenario where an attacker who compromises the workload account tries to delete or alter the evidence of their actions — the logs are no longer there for them to touch. <a href=\"https://docs.aws.amazon.com/prescriptive-guidance/latest/security-reference-architecture/log-archive.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Security Lake",
    q: "What problem does Amazon Security Lake specifically solve compared to simply centralizing logs in an S3 bucket?",
    options: [
      "None worth noting: it is a managed S3 bucket under a different product name",
      "It replaces CloudTrail as the source of the organization's API events",
      "It normalizes logs to the open OCSF schema and partitions them, with no ETL",
      "It only ingests GuardDuty findings, so everything else still needs its own bucket",
    ],
    correct: 2,
    explain: "Security Lake automates ingestion, normalization to OCSF, partitioning (by source/region/date), and lifecycle management of security logs from multiple accounts and sources (AWS and integrated third parties), eliminating the manual ETL work you'd need if you just centralized into a raw S3 bucket. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/what-is-security-lake.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Athena vs CloudWatch Logs Insights",
    q: "When is it more appropriate to use Amazon Athena instead of CloudWatch Logs Insights to analyze security logs?",
    options: [
      "Never: both query the same data and only the query syntax differs between them",
      "Athena can only query VPC Flow Logs; any other format requires OpenSearch",
      "CloudWatch Logs Insights cannot filter, it can only export the whole log group",
      "Athena for ad-hoc SQL over S3 history; Logs Insights for recent logs",
    ],
    correct: 3,
    explain: "Athena queries data in S3 with standard SQL (ideal for large historical volumes, like Security Lake's normalized data). CloudWatch Logs Insights uses its own query language optimized for recent logs already ingested into CloudWatch Logs — faster for immediate investigations, less suited to massive historical analysis. <a href=\"https://docs.aws.amazon.com/athena/latest/ug/when-should-i-use-ate.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Normalization and correlation",
    q: "Which AWS service is typically used to build visualization and correlation dashboards for security events from multiple sources (Security Lake, OpenSearch, CloudWatch)?",
    options: [
      "Amazon Managed Grafana, with panels over CloudWatch, OpenSearch and Athena",
      "AWS Config, whose compliance panel accepts external data sources like OpenSearch",
      "AWS Trusted Advisor, which builds dashboards out of the checks in its categories",
      "Amazon Inspector, which exposes its findings as multi-source correlation panels",
    ],
    correct: 0,
    explain: "Amazon Managed Grafana offers a managed Grafana service for building dashboards that correlate metrics and logs from multiple data sources (CloudWatch, OpenSearch, Athena/Security Lake, Prometheus...) without managing the Grafana infrastructure yourself — skill 1.2.5. <a href=\"https://docs.aws.amazon.com/grafana/latest/userguide/what-is-Amazon-Managed-Service-Grafana.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "VPC Flow Logs",
    q: "What information do VPC Flow Logs capture?",
    options: [
      "The full content of every packet, including the payload of the connection",
      "IP connection metadata (5-tuple, bytes, ACCEPT/REJECT) per ENI or VPC",
      "Only HTTP and HTTPS traffic, including the URL requested on each call",
      "Only the attempts rejected by security groups and the subnet network ACLs",
    ],
    correct: 1,
    explain: "VPC Flow Logs capture connection METADATA (5-tuple + bytes + action), similar to a phone call log: who called whom, how long it lasted, but NOT the content of the conversation. They're the primary source for detecting port scans, data exfiltration via anomalous volume, or communication with malicious IPs. <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Route 53 Resolver logs",
    q: "What visibility do Route 53 Resolver query logs specifically provide that VPC Flow Logs don't?",
    options: [
      "None: VPC Flow Logs already include the domain name behind each connection",
      "They only record the resolution failures (NXDOMAIN) returned by the resolver",
      "They record the preceding DNS query: which domain, who asked, what answer",
      "They only work if the queried domain is registered and hosted in Route 53",
    ],
    correct: 2,
    explain: "While VPC Flow Logs see the resulting IP connection, Resolver query logs see the DNS QUERY that came before it — essential for detecting malware resolving known C2 domains, or data exfiltration encoded in DNS subqueries (DNS tunneling), even before the IP connection is established. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Logging troubleshooting",
    q: "You notice CloudWatch Logs isn't receiving logs from an EC2 instance where the CloudWatch Agent is installed and running. What are the two most likely causes to check first?",
    options: [
      "The EC2 instance type chosen and the operating system version installed",
      "The size of the root EBS volume and the free disk space left on it",
      "The server time zone and the clock drift against the configured NTP source",
      "The agent configuration file and the instance profile IAM permissions",
    ],
    correct: 3,
    explain: "The two most common culprits when debugging 'the agent is running but no logs arrive' are: (1) an agent configuration file pointed at the wrong place (incorrect log paths, misreferenced log group), and (2) insufficient IAM permissions on the Instance Profile/execution role to write to CloudWatch Logs — exactly skill 1.3.2 on remediating 'CloudWatch Agent configuration' and 'missing logs'. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/troubleshooting-CloudWatch-Agent.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Logging troubleshooting",
    q: "A developer reports that invocations of their Lambda function aren't generating logs in CloudWatch, even though the function executes successfully. What's the most likely cause to check first?",
    options: [
      "The execution role is missing logs:CreateLogStream and PutLogEvents",
      "The function exceeds its memory limit and the runtime drops the log buffer",
      "The function is deployed in a region where CloudWatch Logs is unavailable",
      "The chosen runtime does not write to stdout, so Lambda collects no output",
    ],
    correct: 0,
    explain: "Lambda needs its execution role to have explicit permissions to write to CloudWatch Logs (normally via the AWSLambdaBasicExecutionRole managed policy). If they're missing, the function executes normally (the logging failure doesn't block execution) but simply nothing shows up in CloudWatch — a classic troubleshooting case for skill 1.3.1. <a href=\"https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon API Gateway logging",
    q: "What type of logging must be explicitly enabled in Amazon API Gateway to capture the body of requests and responses, useful for debugging authorization issues?",
    options: [
      "Default execution logging already includes the request and response body",
      "Data trace logging on the stage, which adds request/response detail",
      "AWS X-Ray, which records the body of each trace with no extra configuration",
      "The stage access logging, whose format always includes the full body",
    ],
    correct: 1,
    explain: "API Gateway distinguishes between 'execution logging' (execution metadata: errors, latency) and 'data trace logging' (full request/response detail, including headers and body). Data trace is enabled separately because it exposes potentially sensitive information in the logs — relevant to skill 1.3.1 on analyzing resource logging configuration. <a href=\"https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudFront logging",
    q: "What two logging modes does Amazon CloudFront offer for analyzing the requests reaching a distribution?",
    options: [
      "A single kind of access log, always delivered to an S3 bucket that you own",
      "Only real-time logs into Kinesis, with no deferred delivery option",
      "Standard logs delivered to S3 with delay and real-time logs to Kinesis",
      "No native logging: request records only come from a separate AWS WAF",
    ],
    correct: 2,
    explain: "Standard logs (access logs) are delivered to an S3 bucket with some delay and are free, ideal for historical/forensic analysis. Real-time logs are sent to Kinesis Data Streams within seconds, allowing you to alert on or react to traffic patterns almost immediately — the choice depends on whether you need speed (real-time) or cheap deferred analysis (standard). <a href=\"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/logging.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Aggregating findings across accounts",
    q: "To get a consolidated view of GuardDuty and Security Hub findings from ALL accounts in your organization without logging into each one, what pattern is used?",
    options: [
      "Export findings to CSV from each account and consolidate them in a spreadsheet",
      "An SCP forcing every member account to replicate its findings to the central account",
      "It is not possible: findings can only be read from the account that generates them",
      "Designate one account as the delegated administrator for GuardDuty and Security Hub",
    ],
    correct: 3,
    explain: "Both GuardDuty and Security Hub support the 'delegated administrator' model: a designated account (typically the security/logging account) automatically sees and manages findings from all member accounts in the Organization, without needing to log into each one individually. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_organizations.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Workload analysis",
    q: "Before designing a monitoring strategy for a new workload, what should you analyze first according to skill 1.1.1?",
    options: [
      "The monitoring requirements: which assets exist and which events matter",
      "Only the estimated monthly cost, which alone sets the applicable detection level",
      "The workload's name and tags, so the alarms can be grouped together later",
      "The CI/CD provider, which decides which detection services may be enabled",
    ],
    correct: 0,
    explain: "Skill 1.1.1 (analyzing workloads to determine monitoring requirements) is the foundation before choosing tools: without understanding what assets exist, which events matter, and what detection SLA is needed, any GuardDuty/Security Hub/alarm configuration will be generic instead of tailored to that workload's actual risk. <a href=\"https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/sec_detect_investigate_events_app_service_logging.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Health checks",
    q: "In the context of skill 1.1.2 (designing workload monitoring strategies by configuring health checks), what distinguishes a Route 53 health check from a basic CloudWatch alarm?",
    options: [
      "They are equivalent: a health check is a CloudWatch alarm under another name",
      "The health check actively probes the endpoint from several global locations",
      "Route 53 health checks only accept EC2 instances as the probe destination",
      "CloudWatch cannot alarm on an endpoint's health under any available metric",
    ],
    correct: 1,
    explain: "Route 53 health checks perform periodic ACTIVE probes against an endpoint from globally distributed locations, useful for deciding DNS failover. CloudWatch alarms are PASSIVE: they consume metrics already published (by the resource or by you) and trigger an action when they cross a threshold — both are pieces of a monitoring strategy, serving different purposes. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/welcome-health-checks.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "OCSF",
    q: "Why does Amazon Security Lake normalize logs to the OCSF format instead of storing them in each service's original format?",
    options: [
      "An SEC regulation requires it for the security logs stored in the cloud",
      "OCSF compresses the events and halves the cost of storing them in S3",
      "So a common schema correlates different sources with no custom parsers",
      "Athena can only query the S3 objects that are written using OCSF",
    ],
    correct: 2,
    explain: "The value of OCSF is INTEROPERABILITY: an authentication event from CloudTrail and one from a third-party firewall, both normalized to OCSF, share the same field structure — allowing you to correlate a 'failed login' across both sources with a single query, instead of writing separate parsing logic for each product. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/open-cybersecurity-schema-framework.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "A security analyst reviews Security Hub and sees a CRITICAL severity finding that GuardDuty had never issued at that level before, titled something like 'AttackSequence:IAM/CompromisedCredentials'. The finding groups together several individual events (privilege discovery, API manipulation, persistence) that occurred over a period of time. What GuardDuty feature generated this finding?",
    options: [
      "GuardDuty Malware Protection, which scans the EBS volumes of the instance involved",
      "AWS Config, which evaluates the configuration of the resources named in the finding",
      "Amazon Detective, which generates its own critical findings without GuardDuty",
      "GuardDuty Extended Threat Detection, which correlates events into a sequence",
    ],
    correct: 3,
    explain: "GuardDuty Extended Threat Detection (GA December 2024) analyzes patterns across multiple data sources and time periods to generate 'attack sequence findings' (AttackSequence: prefix) that represent a chain of steps taken by an attacker (discovery, movement, persistence, exfiltration) as a single CRITICAL-severity finding — a level GuardDuty never used before this feature. It differs from Detective, which helps you INVESTIGATE relationships between findings that already exist, not generate them. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-extended-threat-detection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for S3",
    q: "An application lets external users upload files directly to an S3 bucket before a pipeline processes them. The security team wants to automatically scan every new object for malware BEFORE the pipeline consumes it, without deploying or maintaining their own scanning infrastructure. Which native AWS solution meets this requirement?",
    options: [
      "GuardDuty Malware Protection for S3, which scans the newly uploaded objects",
      "Amazon Inspector, by enabling object scanning on the destination bucket",
      "Amazon Macie, with a classification job scheduled over that same bucket",
      "SSE-KMS encryption on the bucket, which rejects objects with a malicious signature",
    ],
    correct: 0,
    explain: "GuardDuty Malware Protection for S3 (GA June 2024) is a fully managed, agentless service that scans newly uploaded objects in selected S3 buckets, triggered by the s3:ObjectCreated event, and can tag the object or trigger automated remediation depending on configuration. Macie classifies sensitive CONTENT (PII) — it doesn't detect malware; Inspector evaluates EC2/ECR/Lambda vulnerabilities, not S3 objects; encryption doesn't analyze the file's content. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/gdu-malware-protection-s3.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "How does GuardDuty Malware Protection for EC2 (triggered after a finding on a potentially compromised instance) scan that instance's disk for malware without affecting the running production instance's performance?",
    options: [
      "It installs an agent in the operating system and scans the disk live",
      "It snapshots the EBS volumes and scans that copy in isolation, agentless",
      "It reboots the instance into recovery mode to scan the disk offline",
      "It requires stopping the instance and detaching the volumes before scanning",
    ],
    correct: 1,
    explain: "GuardDuty Malware Protection for EC2 is AGENTLESS: when triggered (automatically after certain findings, or on demand), it takes a snapshot of the EBS volumes on the suspicious instance/container and scans THAT snapshot in an AWS-managed scanning account, without installing anything on the original instance or affecting its availability or performance, and without needing to stop or reboot it. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty RDS Protection",
    q: "A company runs Aurora PostgreSQL clusters. They want to detect brute-force attempts against database credentials and access from unusual login patterns, without modifying the database engine or degrading its performance. Which GuardDuty feature addresses this?",
    options: [
      "GuardDuty Malware Protection for S3, applied to the Aurora cluster backups",
      "Amazon Inspector, scanning the Aurora PostgreSQL engine for vulnerabilities",
      "GuardDuty RDS Protection, which profiles login activity with ML models",
      "AWS Config, with a rule verifying that encryption at rest is enabled",
    ],
    correct: 2,
    explain: "GuardDuty RDS Protection monitors and profiles login activity for Aurora databases (MySQL- and PostgreSQL-compatible), RDS for PostgreSQL, and Aurora PostgreSQL Limitless Database, without requiring agents or engine changes, generating anomalous-credential findings (successful login from an unusual IP/pattern, or a spike in failed attempts indicative of brute forcing) with rich context about the affected database. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/rds-protection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty Lambda Protection",
    q: "A team suspects a Lambda function has been compromised and is being used to mine cryptocurrency or communicate with a Command and Control (C2) server, even in functions that are NOT configured inside a VPC. Which GuardDuty feature detects this behavior?",
    options: [
      "AWS X-Ray, by analyzing the outbound traces of each function invocation",
      "Amazon Inspector, scanning the function code and dependencies for malware",
      "AWS Config, evaluating whether the function is attached to a VPC and its subnets",
      "GuardDuty Lambda Protection, which analyzes the function's network activity",
    ],
    correct: 3,
    explain: "GuardDuty Lambda Protection analyzes the network activity logs generated every time an account's Lambda function is invoked — including functions WITHOUT VPC configuration — to detect outbound traffic to known malicious infrastructure (C2, cryptocurrency mining), applying smart filters so you're only charged for the subset of that network log data relevant to detection. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/lambda-protection.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty EKS Runtime Monitoring",
    q: "When you enable GuardDuty EKS Runtime Monitoring on an EKS cluster, how is the security agent deployed to gain OS-level visibility (process execution, file access, network connections) on each node?",
    options: [
      "As the aws-guardduty-agent add-on, an eBPF DaemonSet on every node",
      "As a sidecar container that GuardDuty injects into each pod of the cluster",
      "With no agent: the EKS audit logs GuardDuty already ingests are enough",
      "As a Lambda function that periodically polls the cluster's Kubernetes API",
    ],
    correct: 0,
    explain: "For EKS, the GuardDuty agent is distributed as the 'aws-guardduty-agent' EKS add-on and deployed as a DaemonSet (one instance of the agent per supported node in the cluster), built on eBPF to get kernel-level telemetry with low overhead. This contrasts with the ECS Fargate deployment, where the agent is injected as a sidecar container into each task, because Fargate exposes no persistent nodes to run a DaemonSet on. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/how-runtime-monitoring-works-eks.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty ECS/Fargate Runtime Monitoring",
    q: "An organization runs most of its workloads on Amazon ECS on Fargate (with no EC2 instances or nodes to manage). How does GuardDuty deploy the Runtime Monitoring agent in this case, given that Fargate exposes no persistent nodes to run a DaemonSet on?",
    options: [
      "Runtime Monitoring is not available on Fargate, only on ECS on EC2",
      "As an aws-guardduty-agent- sidecar container injected into each task",
      "The customer adds the agent to its own image and declares it in the Dockerfile",
      "As a CloudWatch Agent extension inside the application's own container",
    ],
    correct: 1,
    explain: "Unlike EKS (a DaemonSet per node), on ECS Fargate GuardDuty deploys the agent as an additional SIDECAR CONTAINER inside each task — visible as a container prefixed 'aws-guardduty-agent-' — automatically injected when automated agent management (ECS_FARGATE_AGENT_MANAGEMENT) is enabled, or via inclusion tags on the cluster, with no need to modify existing task definitions. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/runtime-monitoring.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Hub: risk prioritization",
    q: "In late 2025, AWS reorganized Security Hub: the compliance-checking service that had existed until then (CIS, PCI-DSS, AWS FSBP) was renamed 'Security Hub CSPM' and is now a sub-component of a broader 'new' Security Hub. What additional capability does this new Security Hub add on top of the original Security Hub CSPM?",
    options: [
      "It replaces GuardDuty and Inspector as the source of findings",
      "It drops ASFF and OCSF for a proprietary finding format",
      "Near real-time risk correlation and prioritization",
      "It adds a cost panel, with no change to the detection layer",
    ],
    correct: 2,
    explain: "The new Security Hub (general GA in late 2025) adds a risk analysis layer that automatically correlates signals from multiple services (Security Hub CSPM, Inspector, GuardDuty, Macie) to produce 'exposure findings' — business context on which combined findings represent the greatest real risk (e.g., public exposure + critical vulnerability + sensitive data), instead of requiring an analyst to manually correlate thousands of individual low-priority findings. It still needs GuardDuty/Inspector enabled as sources. <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudTrail network activity events",
    q: "Your organization uses VPC endpoints (AWS PrivateLink) so workloads can reach services like S3 or KMS without going out to the internet. You want to audit API activity that crosses those VPC endpoints, including activity generated by AWS services acting on your behalf, something standard CloudTrail (management/data events) doesn't always capture with the same level of detail. Which feature do you use?",
    options: [
      "VPC Flow Logs, which already record which API operation crossed the endpoint",
      "Amazon Detective, which rebuilds those calls from its behavior graph",
      "GuardDuty, by enabling the S3 data source over the buckets being accessed",
      "CloudTrail network activity events, an event type specific to VPC endpoints",
    ],
    correct: 3,
    explain: "CloudTrail network activity events for VPC endpoints (GA February 2025) is a new event TYPE, distinct from traditional management/data events, that provides visibility into API activity passing through a VPC endpoint for supported services — including calls made by AWS services on your behalf. VPC Flow Logs only see network metadata (IP/port), not which API was invoked. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-network-events-with-cloudtrail.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Route 53 DNS Firewall Advanced",
    q: "A security team has configured Route 53 Resolver DNS Firewall with managed domain lists (malware, known botnets) but is still worried about malware that generates random domains via a Domain Generation Algorithm (DGA) or that uses DNS tunneling to exfiltrate data — techniques specifically designed to evade static domain lists. Which DNS Firewall capability specifically addresses this threat?",
    options: [
      "DNS Firewall Advanced, which inspects the pattern of the DNS query itself",
      "Raising the TTL of the responses so the resolver caches the new domains",
      "Enabling DNSSEC on the hosted zone to validate the origin of the answers",
      "Redirecting the queries to a third-party resolver located outside the VPC",
    ],
    correct: 0,
    explain: "DNS Firewall's 'Foundational' rules block against lists of known domains (malicious, managed by AWS or Recorded Future). DNS Firewall Advanced adds a rule tier that analyzes the PATTERN of the query itself (length, entropy, structure) to detect techniques specifically designed to evade static lists, such as DGA and DNS tunneling, letting you tune a 'confidence_threshold' instead of relying solely on domain lists. <a href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/firewall-advanced.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Amazon Detective finding groups",
    q: "An analyst has dozens of seemingly unrelated low/medium severity GuardDuty findings in Security Hub, and suspects several belong to the same attack campaign but doesn't have time to correlate them manually. Which Amazon Detective feature directly helps with this?",
    options: [
      "Detective generates new GuardDuty findings that replace the original ones",
      "Finding groups, which use ML to group findings that share entities",
      "Detective replaces Security Hub as the findings aggregation dashboard",
      "Detective analyzes one finding at a time and has no automatic grouping",
    ],
    correct: 1,
    explain: "Amazon Detective's finding groups use ML to identify which GuardDuty findings (and also Inspector findings) are related by sharing entities (the same IAM role, the same session, the same IP), grouping low-severity signals that in isolation might be ignored but together show a complete attack campaign — and it includes natural-language summaries generated with generative AI to accelerate investigation. <a href=\"https://docs.aws.amazon.com/detective/latest/userguide/groups-about.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Macie automated sensitive data discovery",
    q: "An account has hundreds of S3 buckets holding petabytes of data. The team wants to maintain CONTINUOUS visibility into which buckets contain sensitive data without paying to fully scan every object on a recurring basis, which would be prohibitively expensive. Which Macie capability is specifically designed for this case?",
    options: [
      "A discovery job scheduled daily over 100% of the objects in the inventory",
      "Amazon Inspector, applied to the account's inventory of S3 buckets",
      "Automated sensitive data discovery, which samples representative objects",
      "GuardDuty S3 Protection, which classifies the content of each new object",
    ],
    correct: 2,
    explain: "Automated sensitive data discovery is the Macie capability that evaluates the S3 inventory continuously (daily) and applies intelligent SAMPLING over a representative subset of objects per bucket, instead of scanning every object — keeping visibility of which buckets hold sensitive data current at a fraction of the cost of an exhaustive classification job. Traditional sensitive data discovery jobs (one-time or scheduled) still exist for thorough, targeted analysis when you need to examine 100% of a specific scope. <a href=\"https://docs.aws.amazon.com/macie/latest/user/discovery-asdd.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Security Incident Response",
    q: "An organization wants a triage workflow to fire automatically whenever GuardDuty or Security Hub CSPM generates a critical finding, and wants 24/7 access to an AWS incident response team to collaborate on containment, without building that integration themselves from scratch. Which AWS service covers this use case?",
    options: [
      "AWS Trusted Advisor, with the checks in its security category",
      "AWS Config, with an automatic remediation attached to each rule",
      "Amazon Detective, by enabling its 24/7 incident response mode",
      "AWS Security Incident Response, which triages and escalates",
    ],
    correct: 3,
    explain: "AWS Security Incident Response (GA December 2024) is a dedicated service that automatically ingests and triages findings from GuardDuty and Security Hub CSPM (including third-party integrations via Security Hub), offers collaboration tools for response, can take containment actions with your permission, and gives you 24/7 direct access to the AWS Customer Incident Response Team — this isn't a Trusted Advisor, Detective, or Config capability. <a href=\"https://docs.aws.amazon.com/security-ir/latest/userguide/what-is.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Lake rollup regions",
    q: "A company operates in three AWS regions and, for regulatory compliance reasons, needs Security Lake's security data from each region to also remain available locally, but also wants to consolidate a copy of all of it into a single region for centralized analysis. Which Security Lake concept enables this?",
    options: [
      "Rollup regions: one region receives a copy from the contributing regions",
      "Security Lake only supports one active region per organization, with no copies",
      "S3 cross-region replication configured by hand outside of Security Lake",
      "An AWS Config aggregator, reused to consolidate those same data sets",
    ],
    correct: 0,
    explain: "Security Lake lets you designate one or more rollup regions that receive a COPY of the data from the specified contributing regions (the original data still exists in its source regions/buckets, satisfying data residency requirements), while also giving you a single integration point for centralized analysis tools — configurable via the console or the UpdateDataLake API. <a href=\"https://docs.aws.amazon.com/security-lake/latest/userguide/manage-regions.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudWatch cross-account observability",
    q: "The security team wants to view, from a single central monitoring account, the metrics, CloudWatch Logs, and X-Ray traces generated across dozens of workload accounts in the organization, WITHOUT copying or duplicating that data between accounts. What AWS mechanism enables this?",
    options: [
      "CloudWatch Logs subscriptions that copy the log groups into the central account",
      "CloudWatch cross-account observability via Observability Access Manager",
      "Amazon Security Lake, which ingests and centralizes the CloudWatch metrics",
      "A CloudTrail organization trail extended to include metrics and traces",
    ],
    correct: 1,
    explain: "OAM (Observability Access Manager) is the service underlying CloudWatch cross-account observability: through 'sinks' (in the monitoring account) and 'links' (from each source account), it lets a central account query and visualize metrics, logs, and traces from up to 100,000 source accounts WITHOUT moving or copying the data — it's queried in place, unlike a subscription-based solution built on CloudWatch Logs subscriptions, which does replicate the logs into another account. <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "AWS Config aggregator",
    q: "You want a single account to have a consolidated view of Config Rules compliance status and resource inventory across ALL accounts in your AWS Organization and all of their regions, without necessarily making that account the Security Hub delegated administrator. Which AWS Config resource do you use?",
    options: [
      "A CloudTrail organization trail delivered to that account's bucket",
      "A conformance pack, which already consolidates the view with no aggregator",
      "An organization-level AWS Config aggregator created in that account",
      "Amazon Security Lake, redirecting only the data coming from AWS Config",
    ],
    correct: 2,
    explain: "A Config aggregator (in its organization variant) is a specific AWS Config resource that collects and consolidates, into a single account, the resource configuration state and Config Rules compliance of all member accounts and enabled regions in the Organization — a concept independent of the Security Hub/GuardDuty delegated administrator, even though they can coexist in the same security account. A conformance pack by itself deploys rules — it doesn't aggregate their visualization across accounts. <a href=\"https://docs.aws.amazon.com/config/latest/developerguide/aggregate-data.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Hub vs Security Lake aggregation",
    q: "A security architect needs to explain the difference between 'Security Hub cross-region aggregation' and Amazon Security Lake's 'rollup regions', since both sound like 'centralizing data from multiple regions'. What is the correct distinction?",
    options: [
      "They are the same mechanism, merely renamed by the service implementing it",
      "Both require Amazon Security Lake to be enabled as a technical prerequisite",
      "The Security Hub one works within one account and the Security Lake one across orgs",
      "Security Hub consolidates findings; Security Lake rollup regions, OCSF logs",
    ],
    correct: 3,
    explain: "Although both address 'I want to see data from multiple regions in one place', they operate on different layers: Security Hub cross-region aggregation works with FINDINGS (the output of detection/evaluation) and replicates them to a designated aggregation region for the Security Hub dashboard; Security Lake rollup regions work with raw OCSF-normalized LOGS and replicate copies of those logs to a destination region for analysis. They are not interchangeable and neither technically depends on the other. <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/finding-aggregation.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "GuardDuty at organization scale",
    q: "A company with 180 accounts in AWS Organizations wants GuardDuty enabled everywhere, and any new account protected with no manual step. Which TWO are required?",
    options: [
      "Designate an account as the GuardDuty delegated administrator from the management account",
      "Create an IAM role in every member account letting GuardDuty read CloudTrail and flow logs",
      "Turn on auto-enable so new organization accounts are onboarded on their own",
      "Enable GuardDuty account by account and invite them one by one from the central account",
    ],
    correct: [0, 2],
    explain: "GuardDuty is governed in Organizations through a <b>delegated administrator</b> plus <b>auto-enable</b>, which onboards new accounts with no action. GuardDuty ingests CloudTrail, VPC Flow Logs and DNS logs on its own via a service-linked role, so no roles or log setup are needed. The manual invitation flow exists but is exactly what this requirement rules out, and it misses future accounts. <a href=\"https://docs.aws.amazon.com/guardduty/latest/ug/set-guardduty-auto-enable-preferences.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "CloudTrail: data events",
    q: "After an incident the team finds CloudTrail did not record WHO downloaded specific objects from an S3 bucket, though it did record the bucket's creation. Which TWO statements explain and fix this?",
    options: [
      "CloudTrail can never log object access: only S3 server access logging can do it",
      "Management events log operations on the bucket, not on individual objects",
      "Extending the existing trail's retention will surface the events retroactively",
      "S3 data events must be enabled on the bucket, logging reads such as GetObject",
    ],
    correct: [1, 3],
    explain: "CloudTrail separates <b>management events</b> (control plane: CreateBucket, PutBucketPolicy) from <b>data events</b> (data plane: GetObject, PutObject), and data events are off by default because of their cost and volume. S3 server access logging is an alternative, not the only route. Retention never manufactures events that were never captured: what wasn't logged doesn't exist. <a href=\"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Immutable logging account",
    q: "Audit requires that CloudTrail logs cannot be deleted or altered by an administrator of the account that produces them, not even with root credentials. Which TWO achieve this?",
    options: [
      "Deliver the logs to a bucket in a separate, dedicated logging account",
      "Encrypt the bucket with SSE-S3 instead of SSE-KMS to prevent object deletion",
      "Enable bucket versioning and trust that nobody will delete previous versions",
      "Apply S3 Object Lock in compliance mode on the destination bucket",
    ],
    correct: [0, 3],
    explain: "Account separation removes the source-account admin's power, and <b>Object Lock in compliance mode</b> blocks deletion even for root during the retention period (governance mode allows an exception with a special permission, which is why it wouldn't do here). The encryption type doesn't change who can delete. Versioning helps recovery, but an admin with permissions can delete versions: trust is not a control. <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
  {
    tag: "Security Hub multi-Region",
    q: "An organization operates in 5 Regions and wants to review all Security Hub findings from a single pane, in one account and Region. Which TWO are needed?",
    options: [
      "Replicate the findings with a Lambda function deployed in every Region",
      "Designate a Security Hub delegated administrator for the organization",
      "Configure an aggregation Region that consolidates findings from the others",
      "Disable Security Hub in the secondary Regions so findings are not duplicated",
    ],
    correct: [1, 2],
    explain: "Security Hub needs a <b>delegated administrator</b> for the multi-account view and <b>cross-Region aggregation</b> for the multi-Region view; they are two separate axes and both are required. Replicating with Lambda reinvents a native feature. Disabling Security Hub in the other Regions would remove the very findings you want to see: controls are evaluated where the resources live. <a href=\"https://docs.aws.amazon.com/securityhub/latest/userguide/finding-aggregation-enable.html\" target=\"_blank\" rel=\"noopener\">AWS docs ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["detection"] = QUIZ_DATA;
