// Banco de preguntas del módulo: buenas prácticas y prioridades (SC-100, dominio 1).
// Cada explicación termina en el enlace a la documentación oficial de Microsoft Learn.

var QUIZ_DATA = [
  {
    tag: "De dónde sale la prioridad",
    q: "Un cliente pide una estrategia de seguridad y aporta un informe con ochocientas vulnerabilidades. ¿Por dónde arranca el diseño?",
    options: [
      "Por las vulnerabilidades críticas del informe, que son las que un atacante explotaría antes",
      "Por un análisis de las amenazas más frecuentes en el sector al que pertenece el cliente",
      "Por identificar los procesos críticos del negocio y los activos de los que dependen",
      "Por comparar la postura actual con la de organizaciones parecidas en tamaño y sector",
    ],
    correct: 2,
    explain: "La estrategia no sale del catálogo de amenazas sino de <b>qué necesita el negocio que siga funcionando</b>. Primero los procesos críticos y sus activos; después qué amenazas ponen en riesgo <em>esos</em> activos, y de ahí la prioridad de los controles. Ordenar por severidad técnica trata igual una crítica en un entorno de pruebas y una media en el camino al sistema de facturación. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Quién fija el objetivo",
    q: "Al diseñar la protección de una aplicación de facturación, el equipo de seguridad propone una copia diaria nocturna. ¿Qué falta antes de aceptar ese diseño?",
    options: [
      "Conocer el RPO y el RTO que el negocio acepta para esa aplicación",
      "Comprobar que el almacenamiento de copias tiene cifrado con clave del cliente activado",
      "Verificar que la ventana nocturna no coincide con procesos por lotes de otras aplicaciones",
      "Decidir cuántas copias se conservan y durante cuánto tiempo antes de eliminarlas",
    ],
    correct: 0,
    explain: "Una copia diaria implica aceptar perder hasta <b>veinticuatro horas</b> de facturación, y eso no lo decide seguridad: lo decide el <b>negocio</b> con su <b>RPO</b>, igual que fija con el <b>RTO</b> cuánto tiempo puede estar parado. Sin esos dos números el diseño es una suposición. Cifrado, ventana y retención son decisiones posteriores, y todas dependen de la primera. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/disaster-recovery-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Copias que sobreviven al atacante",
    q: "Se rediseña el respaldo de un entorno crítico partiendo del supuesto de que el atacante conseguirá credenciales de administrador. ¿Qué DOS medidas incluye el diseño?",
    options: [
      "Aumentar la frecuencia de las copias de diaria a cada cuatro horas, para reducir la pérdida de dato",
      "Copias inmutables, con borrado temporal y eliminación protegida con autenticación multifactor",
      "Cifrado de las copias con una clave gestionada por el cliente y custodiada en Key Vault",
      "Separación de roles: quien administra la carga de trabajo no administra su almacén de copias",
    ],
    correct: [1, 3],
    explain: "El supuesto del enunciado es que el atacante <b>tiene permisos</b>, y contra eso la frecuencia y el cifrado no hacen nada: podría borrar las copias igualmente. Lo que las salva es que la plataforma <b>no permita borrarlas</b> —inmutabilidad, borrado temporal, eliminación con MFA— y que las credenciales de la carga <b>no sirvan</b> sobre el almacén. Cifrar protege la confidencialidad, que no es el riesgo aquí. <a href=\"https://learn.microsoft.com/en-us/azure/backup/backup-azure-security-feature\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Copias verdes que no restauran",
    q: "Un cliente enseña un panel con doce meses de copias correctas sin un solo fallo. ¿Qué preguntas antes de dar por buena su capacidad de recuperación?",
    options: [
      "Si las copias están replicadas en una segunda región geográficamente distante",
      "Si el almacén de copias tiene activado el cifrado con clave gestionada por el cliente",
      "Si la retención configurada cubre el periodo que exige la normativa del sector",
      "Cuándo se restauró por última vez y si se cumplió el RTO comprometido",
    ],
    correct: 3,
    explain: "Una copia verde solo demuestra que el proceso terminó, no que el dato sirva ni que el negocio vuelva a tiempo. La pregunta que separa un plan real de un panel bonito es <b>cuándo se restauró por última vez</b> y si esa restauración cumplió el <b>RTO</b>. Replicación, cifrado y retención son buenas propiedades de un respaldo que quizá nunca se haya probado. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/disaster-recovery-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Por dónde se empieza contra ransomware",
    q: "La dirección pide un plan de ransomware y quiere saber qué se aborda primero, con presupuesto para una sola línea de trabajo este trimestre. ¿Cuál eliges?",
    options: [
      "Desplegar EDR en todo el parque y activar la reducción de superficie de ataque en los clientes",
      "Asegurar la capacidad de recuperación: copias inmutables y aisladas, con restauración probada",
      "Endurecer el correo, que es por donde entra la mayoría de las campañas de este tipo",
      "Formar a toda la organización con campañas de simulación de phishing trimestrales",
    ],
    correct: 1,
    explain: "El orden de Microsoft es <b>recuperar, limitar el alcance y dificultar la entrada</b>, y es contraintuitivo a propósito. La recuperación va primera porque es lo único que garantiza que el negocio sobrevive <em>aunque la prevención falle</em>, y es lo que quita al atacante su palanca de negociación. EDR, correo y formación son las tres fases siguientes, no la primera. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase1\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que convierte el incidente en catástrofe",
    q: "Con la recuperación ya resuelta, el cliente pregunta qué línea de trabajo evita que un equipo comprometido acabe cifrando toda la organización. ¿Cuál es?",
    options: [
      "Segmentar la red en más zonas y filtrar el tráfico entre ellas con un cortafuegos interno",
      "Acortar el tiempo de detección con más reglas de análisis y guardias del SOC en horario ampliado",
      "Acceso privilegiado: PIM, estaciones dedicadas, LAPS y separación de planos de administración",
      "Aumentar la frecuencia de las copias para que el punto de restauración quede más próximo",
    ],
    correct: 2,
    explain: "Lo que convierte un equipo comprometido en una organización cifrada es que desde ese equipo se llegue a <b>credenciales de administración</b>. Por eso la segunda fase es el <b>acceso privilegiado</b>: activación temporal en PIM, estaciones dedicadas, contraseñas locales únicas con LAPS y separación de planos. La segmentación ayuda, la detección acorta el daño, y más copias no limitan el alcance. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Actualizar sin romper",
    q: "El equipo de plataforma quiere aplicar todas las actualizaciones de seguridad el mismo día en que se publican, en todo el parque de servidores. ¿Qué recomiendas?",
    options: [
      "Anillos de despliegue con un grupo piloto y fases, y una vía rápida para lo explotado activamente",
      "Aplicarlas todas de inmediato, ya que el riesgo de no parchear siempre supera al de una regresión",
      "Retrasarlas treinta días de forma sistemática para que otros detecten primero las regresiones",
      "Aplicar solo las críticas de inmediato y dejar el resto para la ventana trimestral de mantenimiento",
    ],
    correct: 0,
    explain: "El diseño maduro no elige entre velocidad y estabilidad: las combina con <b>anillos de despliegue</b> —piloto primero, producción por fases— y una <b>vía rápida documentada</b> para las vulnerabilidades que se están explotando de verdad. Aplicar todo a la vez arriesga una caída global; retrasar siempre treinta días deja abierto lo urgente; y dejar lo no crítico a un trimestre acumula deuda. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que no se puede parchear",
    q: "Un sistema heredado imprescindible tiene una vulnerabilidad conocida y el fabricante no publicará corrección. ¿Qué recoge el diseño?",
    options: [
      "Aceptar el riesgo y documentarlo, ya que no existe corrección disponible del fabricante",
      "Retirar el sistema de inmediato y sustituirlo por una alternativa con soporte vigente",
      "Aplicar la actualización de una versión posterior aunque no esté soportada por el fabricante",
      "Mitigación compensatoria —aislamiento y filtrado— con la retirada planificada y su plazo",
    ],
    correct: 3,
    explain: "«Imprescindible» descarta retirarlo hoy y «sin corrección» descarta parchearlo, pero aceptar el riesgo sin más no es un diseño. Lo que se espera es <b>mitigación compensatoria</b> —segmentar, filtrar, restringir quién llega, vigilarlo de cerca— acompañada de un <b>plan de retirada con fecha</b>, para que la excepción no se vuelva permanente. Instalar parches no soportados añade un riesgo distinto. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-posture-vulnerability-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Encontrar el hueco",
    q: "Un cliente ha ido comprando herramientas de seguridad sin un plan y quiere saber qué capacidades le siguen faltando. ¿Qué usas para responder?",
    options: [
      "El Microsoft Cloud Security Benchmark, comprobando control a control lo que no se cumple",
      "Las arquitecturas de referencia de ciberseguridad, para mapear capacidades y ver los huecos",
      "El Cloud Adoption Framework, siguiendo su recorrido de adopción desde la fase de estrategia",
      "El Well-Architected Framework, revisando cada carga de trabajo y sus compromisos de diseño",
    ],
    correct: 1,
    explain: "La pregunta es «<em>qué capacidades me faltan</em>», y ese es el mapa: el <b>MCRA</b> muestra el conjunto de capacidades de seguridad, cómo encajan y qué las cubre, de modo que lo que queda en blanco es el hueco. El <b>MCSB</b> mide si lo que hay está bien <em>configurado</em>, que es otra pregunta. El CAF ordena la adopción y el Well-Architected revisa una carga concreta. <a href=\"https://learn.microsoft.com/en-us/security/adoption/mcra\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Mapa o benchmark",
    q: "Ya definido el conjunto de capacidades, el cliente pide ahora una lista de controles concretos y medibles para saber si su nube está bien configurada. ¿Qué le das?",
    options: [
      "Las arquitecturas de referencia de ciberseguridad, que detallan cómo se integran los productos",
      "El marco de adopción de Zero Trust, con sus tres principios y sus seis pilares",
      "El Microsoft Cloud Security Benchmark, que Defender for Cloud evalúa de forma continua",
      "El modelo de responsabilidad compartida, para delimitar qué controla el proveedor y qué el cliente",
    ],
    correct: 2,
    explain: "Controles <b>concretos y medibles</b> es la definición del <b>MCSB</b>: está mapeado a CIS y NIST, viene asignado por defecto en Defender for Cloud y se evalúa solo, también sobre AWS y GCP conectados. El MCRA da el mapa de capacidades pero no una lista evaluable, Zero Trust da principios, y el modelo de responsabilidad compartida reparte quién hace qué. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El acceso ya es legítimo",
    q: "Un comercial que ha presentado su dimisión descarga la cartera completa de clientes a la que tiene acceso legítimo por su puesto. ¿Qué aborda este riesgo?",
    options: [
      "Exigir MFA resistente a phishing para acceder al sistema de gestión de clientes",
      "Retirar el acceso al sistema al recibir la dimisión, mediante un proceso de baja automatizado",
      "Gestión de riesgo interno, que puntúa el comportamiento del empleado",
      "Una política de acceso condicional que limite el acceso a las oficinas de la organización",
    ],
    correct: 2,
    explain: "Ningún control de acceso lo detiene, porque <b>el acceso es correcto</b>: es su trabajo. Lo que aborda esta amenaza es mirar <b>comportamiento</b> en vez de permisos, y eso es la <b>gestión de riesgo interno</b>, que combina señales —volumen inusual de descarga, dimisión presentada, movimiento a almacenamiento personal— para levantar un caso. Reforzar autenticación o ubicación contesta a una amenaza externa. <a href=\"https://learn.microsoft.com/en-us/purview/insider-risk-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Entrar por la puerta de confianza",
    q: "Tras un incidente sonado en el que un atacante comprometió una biblioteca muy usada, la dirección pregunta qué hace la organización frente a ese tipo de ataque. ¿Qué recoge el diseño?",
    options: [
      "Análisis de composición, procedencia y firma, con gobierno del acceso de terceros",
      "Un WAF con reglas gestionadas delante de todas las aplicaciones que usen bibliotecas de terceros",
      "Prohibir el uso de bibliotecas de código abierto en las aplicaciones críticas de la organización",
      "Aumentar la frecuencia del análisis de vulnerabilidades sobre las máquinas donde se ejecutan",
    ],
    correct: 0,
    explain: "La cadena de suministro entra por algo en lo que <b>ya confías</b>, así que la defensa va en la construcción: <b>análisis de composición</b> para saber qué se incorpora, <b>procedencia y firma</b> para saber que el artefacto es el que se compiló, y gobierno del acceso de proveedores y herramientas. Prohibir el código abierto no es realista, y el WAF y el análisis de máquinas actúan cuando el componente ya está dentro. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/sfi/protect-software-supply-chain\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La IA no es una excepción",
    q: "Un equipo despliega una carga de IA como prueba de concepto y pide quedar fuera del gobierno habitual «hasta que se decida si sigue adelante». ¿Qué respondes?",
    options: [
      "Que es razonable mientras no procese dato de producción, revisándolo cuando pase a serlo",
      "Que le aplican los controles del MCSB igual que a cualquier carga, más los suyos propios",
      "Que puede quedar fuera si se despliega en una suscripción aislada sin conexión con el resto",
      "Que hace falta un marco de gobierno específico para IA antes de poder aplicarle ningún control",
    ],
    correct: 1,
    explain: "El error de diseño típico es tratar la IA como un experimento fuera del gobierno. Una carga de IA es una carga: le aplican los <b>controles del MCSB</b> —identidad sin claves locales, endpoint privado, protección del dato, registro, postura— y <b>encima</b> los suyos propios, como los filtros de contenido y los escudos frente a inyección de instrucciones. No hace falta esperar a un marco nuevo: el que hay ya la cubre. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Controles propios de la IA",
    q: "Al aplicar el MCSB a una carga de IA generativa, ¿qué control no tiene equivalente en una carga tradicional y hay que añadir?",
    options: [
      "Autenticación con Entra ID e identidades administradas en lugar de claves de servicio",
      "Endpoint privado y acceso público deshabilitado sobre el recurso que hospeda el modelo",
      "Envío de las trazas del servicio al SIEM para correlacionarlas con el resto de la señal",
      "Filtros de contenido y escudos frente a la inyección de instrucciones, directa e indirecta",
    ],
    correct: 3,
    explain: "Las tres primeras son controles del benchmark que aplican igual a un servicio de IA que a una base de datos. Lo <b>específico</b> de la IA es que el contenido que el modelo lee puede acabar dirigiendo lo que hace: la <b>inyección de instrucciones</b>, que no la cubre ninguna medida de identidad ni de red y se aborda con los filtros y escudos del propio servicio. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Los tres principios",
    q: "Revisas un diseño donde la red interna se considera de confianza y, una vez dentro, los servicios se hablan entre sí sin autenticar. ¿Qué principio de Zero Trust se incumple?",
    options: [
      "Asumir la brecha: se segmenta y se verifica dando por hecho la intrusión",
      "Verificar explícitamente: falta exigir autenticación multifactor a los usuarios de esos servicios",
      "Mínimo privilegio: los servicios tienen más permisos de los que necesitan para su función",
      "Ninguno: el modelo permite confiar en la red interna si está correctamente segmentada",
    ],
    correct: 0,
    explain: "Tratar la red interna como zona de confianza es exactamente lo que niega <b>asumir la brecha</b>: se diseña dando por hecho que alguien ya está dentro, y por eso el tráfico entre servicios se autentica y se cifra igual que el que viene de fuera. Verificar explícitamente y mínimo privilegio son los otros dos principios y describen otros defectos. Y la cuarta opción es la premisa del modelo que Zero Trust vino a sustituir. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cómo se adopta",
    q: "La dirección aprueba «implantar Zero Trust» y pregunta qué producto hay que comprar y cuándo estará terminado. ¿Qué respondes?",
    options: [
      "Que se implanta con Entra ID y acceso condicional, y queda terminado al cubrir todas las aplicaciones",
      "Que basta con Microsoft Defender XDR, que aplica los tres principios sobre toda la señal del estado",
      "Que es un modelo que se adopta por pilares de forma continua, con el marco de adopción como guía",
      "Que primero hay que migrar por completo a la nube, porque el modelo no aplica a lo que está on-premises",
    ],
    correct: 2,
    explain: "Zero Trust no es un producto ni un proyecto con fecha de fin: es un <b>modelo</b> que se adopta por <b>pilares</b> —identidades, endpoints, aplicaciones, datos, infraestructura y redes—, y el <b>marco de adopción</b> existe justamente para dar el orden, los hitos y cómo medir el avance. El acceso condicional y Defender XDR son piezas importantes, no la implantación entera. Y el modelo aplica también a lo híbrido. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/adopt/zero-trust-adoption-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Antes de dar IA a todos",
    q: "Una organización quiere desplegar Copilot para Microsoft 365 a toda la plantilla el mes que viene. ¿Qué es lo primero del plan?",
    options: [
      "Formar a la plantilla en el uso responsable del asistente y publicar una política de uso aceptable",
      "Clasificar y etiquetar el contenido, y corregir el sobrecompartido de SharePoint y OneDrive",
      "Definir con negocio la lista de casos de uso aprobados y el retorno esperado de cada uno",
      "Desplegar a un grupo piloto y medir la calidad de las respuestas antes de ampliar el alcance",
    ],
    correct: 1,
    explain: "Un asistente <b>hereda los permisos del origen</b>: si el contenido está sobrecompartido, lo reparte más deprisa y ante más gente. Por eso el trabajo previo es de <b>gobierno del dato</b> —clasificar, etiquetar y arreglar permisos—, y todo lo demás viene después. Formación, casos de uso y piloto son partes legítimas del plan, pero ninguna evita que el primer día alguien lea lo que no debía. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La IA que ya se usa",
    q: "Al preparar la estrategia de adopción de IA se descubre que varios equipos ya usan herramientas de IA no aprobadas con documentos internos. ¿Qué recoge la estrategia?",
    options: [
      "Bloquear por categoría todas las herramientas de IA en el filtrado web hasta terminar el plan",
      "Una comunicación interna recordando que solo pueden usarse las herramientas aprobadas",
      "Aceptar el uso existente y auditarlo cuando la estrategia de adopción esté publicada",
      "Descubrir el uso real con Defender for Cloud Apps, y decidir con ese dato",
    ],
    correct: 3,
    explain: "La IA no aprobada es <b>shadow IT</b> y se trata igual: primero <b>descubrir</b> qué se usa y con qué volumen —eso lo da Defender for Cloud Apps a partir del tráfico—, y con ese dato decidir qué se sanciona, qué se sustituye por una alternativa corporativa y qué se bloquea. Bloquear a ciegas empuja el uso a canales sin visibilidad, y una comunicación no cambia el comportamiento por sí sola. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Organización o carga",
    q: "Un cliente pide revisar si el diseño de una aplicación concreta equilibra bien seguridad, fiabilidad y coste. ¿Qué marco aplicas?",
    options: [
      "El Cloud Adoption Framework, que cubre el recorrido completo de adopción de la nube",
      "El Microsoft Cloud Security Benchmark, que evalúa los controles de la carga de trabajo",
      "El Well-Architected Framework, que revisa una carga y hace explícitos sus compromisos",
      "Las arquitecturas de referencia de ciberseguridad, que muestran cómo encajan las capacidades",
    ],
    correct: 2,
    explain: "«Una aplicación concreta» y «equilibrar» son las dos pistas del <b>Well-Architected Framework</b>, que revisa una <b>carga de trabajo</b> a través de sus pilares y obliga a hacer explícitos los <b>compromisos</b>: reforzar seguridad casi siempre cuesta coste, rendimiento o comodidad operativa. El <b>CAF</b> mira la organización y su adopción, el MCSB mide configuración y el MCRA mapea capacidades. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El compromiso explícito",
    q: "En una revisión Well-Architected, el equipo propone endurecer una carga con controles que añaden latencia y coste. ¿Qué se espera del arquitecto?",
    options: [
      "Aplicar los controles igualmente, porque la seguridad tiene prioridad sobre los demás pilares",
      "Documentar el compromiso y llevarlo a decisión del propietario de la carga",
      "Descartar los controles que degraden el rendimiento y buscar alternativas sin ningún impacto",
      "Aplicar solo los controles que no tengan coste adicional y dejar el resto para el año siguiente",
    ],
    correct: 1,
    explain: "El Well-Architected no dice que la seguridad gane siempre: dice que los <b>compromisos existen</b> y que un diseño maduro <em>los hace explícitos</em> en vez de fingir que no están. El arquitecto mide el impacto en latencia y coste, lo pone junto al riesgo que se reduce y lleva la decisión a quien responde de la carga. Aplicar sin más, descartar sin más o filtrar por coste son tres formas de no decidir. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cada equipo a su aire",
    q: "En una organización con cuarenta equipos desplegando en Azure, cada uno configura la seguridad a su criterio y el resultado es dispar. ¿Qué recomiendas?",
    options: [
      "Una guía de buenas prácticas publicada por el equipo de seguridad, con revisión antes de cada despliegue",
      "Una auditoría mensual de las suscripciones con un informe de desviaciones para cada equipo",
      "Formación obligatoria en seguridad de Azure para todos los equipos de desarrollo de la organización",
      "Grupos de administración con iniciativas de Azure Policy y landing zones para lo nuevo",
    ],
    correct: 3,
    explain: "Un resultado dispar entre cuarenta equipos no se arregla pidiéndoles que se acuerden: se arregla poniendo las <b>barandillas en la plataforma</b>. Iniciativas de <b>Azure Policy</b> asignadas a <b>grupos de administración</b> aplican a todas las suscripciones, presentes y futuras, y las <b>landing zones</b> hacen que lo nuevo nazca conforme. La guía, la auditoría y la formación dependen de que cada equipo cumpla. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Quién responde de qué",
    q: "Tras un incidente, nadie sabe quién debía haber configurado el registro de una aplicación: ni el equipo de producto, ni plataforma, ni seguridad se dan por responsables. ¿Qué falta?",
    options: [
      "Un modelo de responsabilidades como el del CAF, con propietario por carga y funciones definidas",
      "Una política de Azure que active el registro de diagnóstico en todos los recursos de la organización",
      "Un espacio de trabajo de Log Analytics centralizado al que envíen todos los equipos sus registros",
      "Una cláusula en el procedimiento de gestión de incidentes que designe un responsable al abrirse cada caso",
    ],
    correct: 0,
    explain: "El defecto no es técnico sino de <b>gobierno</b>: no hay nadie a quien pedirle cuentas. El <b>CAF</b> define funciones de seguridad y un <b>propietario por carga de trabajo</b>, de modo que cada decisión tiene dueño antes del incidente. La política y el workspace resuelven este caso concreto y dejan intacto el problema, y designar responsable cuando ya ha pasado llega tarde por definición. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/teams-roles\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Por qué el grupo de administración",
    q: "Se quiere garantizar que toda suscripción de Azure, incluidas las que se creen el año que viene, tenga activados los planes de Defender y el registro centralizado. ¿Cómo se asegura?",
    options: [
      "Un procedimiento de alta de suscripción que el equipo de plataforma ejecute en cada creación",
      "Iniciativas de Azure Policy con DeployIfNotExists en el grupo de administración",
      "Una plantilla de infraestructura como código que cada equipo use al crear su suscripción nueva",
      "Una revisión trimestral de las suscripciones existentes con corrección de las que no cumplan",
    ],
    correct: 1,
    explain: "«Incluidas las que se creen el año que viene» es la pista del <b>grupo de administración</b>: una asignación ahí alcanza a las suscripciones que <em>aún no existen</em>, y con <b>DeployIfNotExists</b> la configuración se despliega sola en vez de solo auditarse. El procedimiento manual y la plantilla dependen de que alguien se acuerde, y la revisión trimestral corrige después de que el hueco haya existido tres meses. <a href=\"https://learn.microsoft.com/en-us/azure/governance/management-groups/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué separa una landing zone",
    q: "Al diseñar las landing zones, un equipo propone poner las suscripciones de identidad, conectividad y gestión junto a las de las aplicaciones para simplificar. ¿Qué señalas?",
    options: [
      "Que es razonable si todas quedan bajo el mismo grupo de administración con las mismas políticas",
      "Que es razonable siempre que cada aplicación tenga su propio grupo de recursos bien delimitado",
      "Plataforma y carga se separan: distinto ciclo, permisos y políticas",
      "Que solo importa si la organización supera un número determinado de suscripciones activas",
    ],
    correct: 2,
    explain: "El diseño de referencia separa las suscripciones de <b>plataforma</b> —identidad, gestión, conectividad— de las de <b>carga de trabajo</b> porque tienen ciclos de vida, responsables y necesidades de política distintos: quien despliega una aplicación no debe poder tocar la red del hub ni el almacén de registros. Mezclarlas rompe esa separación por comodidad, y los grupos de recursos no la sustituyen. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Una puerta al final",
    q: "En una organización, la seguridad revisa cada aplicación en una única puerta antes del paso a producción, y el equipo se queja de que siempre llega tarde y bloquea entregas. ¿Qué propones?",
    options: [
      "Repartir controles automáticos por el ciclo, en vez de una única puerta",
      "Adelantar la revisión de seguridad dos semanas para que dé tiempo a corregir lo que se encuentre",
      "Añadir más personas al equipo de seguridad para que la revisión final se resuelva más deprisa",
      "Permitir que las aplicaciones no críticas se salten la revisión y reservarla para las críticas",
    ],
    correct: 0,
    explain: "Una puerta al final concentra todos los hallazgos en el momento más caro para arreglarlos, y por eso siempre bloquea. <b>DevSecOps</b> reparte controles <b>automáticos</b> por el ciclo —modelado en diseño, análisis en el código y la pull request, dependencias en la compilación, política en el despliegue—, de modo que cada problema se encuentra donde es barato. Adelantar o reforzar la puerta no cambia su naturaleza. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/devsecops-controls\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Que el control cuente",
    q: "El análisis de seguridad del pipeline lleva meses generando avisos que nadie atiende, y las entregas siguen su curso. ¿Qué cambio del proceso lo corrige?",
    options: [
      "Enviar un resumen semanal de los avisos abiertos al responsable de cada equipo de desarrollo",
      "Aumentar la sensibilidad del análisis para que no se escape ningún hallazgo relevante",
      "Que el hallazgo por encima del umbral acordado rompa la construcción, con excepción documentada",
      "Trasladar los avisos a la herramienta de incidencias del equipo para que entren en su planificación",
    ],
    correct: 2,
    explain: "Un aviso que no detiene nada acaba siendo ruido, y el ruido no se lee. Lo que hace que el control cuente es que el hallazgo por encima del umbral <b>rompa la construcción</b>, con una vía de <b>excepción documentada y con dueño</b> para los casos justificados. Más sensibilidad genera más ruido, y el resumen semanal y el tablero de incidencias siguen dependiendo de que alguien priorice. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/devsecops-controls\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["best-practices"] = QUIZ_DATA;
