// Banco de preguntas del módulo: buenas prácticas y prioridades (SC-100, dominio 1).
// Cada explicación termina en el enlace a la documentación oficial de Microsoft Learn.

var QUIZ_DATA = [
  {
    tag: "De dónde sale la prioridad",
    q: "Un cliente pide una estrategia de seguridad y aporta un informe con ochocientas vulnerabilidades. ¿Por dónde arranca el diseño?",
    options: [
      "Por las vulnerabilidades críticas del informe, que son las que un atacante explotaría antes",
      "Por un análisis de las amenazas más frecuentes en el sector al que pertenece el cliente",
      "Por identificar los procesos críticos del negocio y los activos de los que dependen",
      "Por comparar la postura actual con la de organizaciones parecidas en tamaño y sector",
    ],
    correct: 2,
    explain: "La estrategia no sale del catálogo de amenazas sino de <b>qué necesita el negocio que siga funcionando</b>. Primero los procesos críticos y sus activos; después qué amenazas ponen en riesgo <em>esos</em> activos, y de ahí la prioridad de los controles. Ordenar por severidad técnica trata igual una crítica en un entorno de pruebas y una media en el camino al sistema de facturación. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Quién fija el objetivo",
    q: "Al diseñar la protección de una aplicación de facturación, el equipo de seguridad propone una copia diaria nocturna. ¿Qué falta antes de aceptar ese diseño?",
    options: [
      "Conocer el RPO y el RTO que el negocio acepta para esa aplicación",
      "Comprobar que el almacenamiento de copias tiene cifrado con clave del cliente activado",
      "Verificar que la ventana nocturna no coincide con procesos por lotes de otras aplicaciones",
      "Decidir cuántas copias se conservan y durante cuánto tiempo antes de eliminarlas",
    ],
    correct: 0,
    explain: "Una copia diaria implica aceptar perder hasta <b>veinticuatro horas</b> de facturación, y eso no lo decide seguridad: lo decide el <b>negocio</b> con su <b>RPO</b>, igual que fija con el <b>RTO</b> cuánto tiempo puede estar parado. Sin esos dos números el diseño es una suposición. Cifrado, ventana y retención son decisiones posteriores, y todas dependen de la primera. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Copias que sobreviven al atacante",
    q: "Se rediseña el respaldo de un entorno crítico partiendo del supuesto de que el atacante conseguirá credenciales de administrador. ¿Qué DOS medidas incluye el diseño?",
    options: [
      "Aumentar la frecuencia de las copias de diaria a cada cuatro horas, para reducir la pérdida de dato",
      "Copias inmutables, con borrado temporal y eliminación protegida con autenticación multifactor",
      "Cifrado de las copias con una clave gestionada por el cliente y custodiada en Key Vault",
      "Separación de roles: quien administra la carga de trabajo no administra su almacén de copias",
    ],
    correct: [1, 3],
    explain: "El supuesto del enunciado es que el atacante <b>tiene permisos</b>, y contra eso la frecuencia y el cifrado no hacen nada: podría borrar las copias igualmente. Lo que las salva es que la plataforma <b>no permita borrarlas</b> —inmutabilidad, borrado temporal, eliminación con MFA— y que las credenciales de la carga <b>no sirvan</b> sobre el almacén. Cifrar protege la confidencialidad, que no es el riesgo aquí. <a href=\"https://learn.microsoft.com/en-us/azure/backup/backup-azure-security-feature\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Copias verdes que no restauran",
    q: "Un cliente enseña un panel con doce meses de copias correctas sin un solo fallo. ¿Qué preguntas antes de dar por buena su capacidad de recuperación?",
    options: [
      "Si las copias están replicadas en una segunda región geográficamente distante",
      "Si el almacén de copias tiene activado el cifrado con clave gestionada por el cliente",
      "Si la retención configurada cubre el periodo que exige la normativa del sector",
      "Cuándo se restauró por última vez y si se cumplió el RTO comprometido",
    ],
    correct: 3,
    explain: "Una copia verde solo demuestra que el proceso terminó, no que el dato sirva ni que el negocio vuelva a tiempo. La pregunta que separa un plan real de un panel bonito es <b>cuándo se restauró por última vez</b> y si esa restauración cumplió el <b>RTO</b>. Replicación, cifrado y retención son buenas propiedades de un respaldo que quizá nunca se haya probado. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Por dónde se empieza contra ransomware",
    q: "La dirección pide un plan de ransomware y quiere saber qué se aborda primero, con presupuesto para una sola línea de trabajo este trimestre. ¿Cuál eliges?",
    options: [
      "Desplegar EDR en todo el parque y activar la reducción de superficie de ataque en los clientes",
      "Asegurar la capacidad de recuperación: copias inmutables y aisladas, con restauración probada",
      "Endurecer el correo, que es por donde entra la mayoría de las campañas de este tipo",
      "Formar a toda la organización con campañas de simulación de phishing trimestrales",
    ],
    correct: 1,
    explain: "El orden de Microsoft es <b>recuperar, limitar el alcance y dificultar la entrada</b>, y es contraintuitivo a propósito. La recuperación va primera porque es lo único que garantiza que el negocio sobrevive <em>aunque la prevención falle</em>, y es lo que quita al atacante su palanca de negociación. EDR, correo y formación son las tres fases siguientes, no la primera. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase1\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que convierte el incidente en catástrofe",
    q: "Con la recuperación ya resuelta, el cliente pregunta qué línea de trabajo evita que un equipo comprometido acabe cifrando toda la organización. ¿Cuál es?",
    options: [
      "Segmentar la red en más zonas y filtrar el tráfico entre ellas con un cortafuegos interno",
      "Acortar el tiempo de detección con más reglas de análisis y guardias del SOC en horario ampliado",
      "Acceso privilegiado: PIM, estaciones dedicadas, LAPS y separación de planos de administración",
      "Aumentar la frecuencia de las copias para que el punto de restauración quede más próximo",
    ],
    correct: 2,
    explain: "Lo que convierte un equipo comprometido en una organización cifrada es que desde ese equipo se llegue a <b>credenciales de administración</b>. Por eso la segunda fase es el <b>acceso privilegiado</b>: activación temporal en PIM, estaciones dedicadas, contraseñas locales únicas con LAPS y separación de planos. La segmentación ayuda, la detección acorta el daño, y más copias no limitan el alcance. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Actualizar sin romper",
    q: "El equipo de plataforma quiere aplicar todas las actualizaciones de seguridad el mismo día en que se publican, en todo el parque de servidores. ¿Qué recomiendas?",
    options: [
      "Anillos de despliegue con un grupo piloto y fases, y una vía rápida para lo explotado activamente",
      "Aplicarlas todas de inmediato, ya que el riesgo de no parchear siempre supera al de una regresión",
      "Retrasarlas treinta días de forma sistemática para que otros detecten primero las regresiones",
      "Aplicar solo las críticas de inmediato y dejar el resto para la ventana trimestral de mantenimiento",
    ],
    correct: 0,
    explain: "El diseño maduro no elige entre velocidad y estabilidad: las combina con <b>anillos de despliegue</b> —piloto primero, producción por fases— y una <b>vía rápida documentada</b> para las vulnerabilidades que se están explotando de verdad. Aplicar todo a la vez arriesga una caída global; retrasar siempre treinta días deja abierto lo urgente; y dejar lo no crítico a un trimestre acumula deuda. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que no se puede parchear",
    q: "Un sistema heredado imprescindible tiene una vulnerabilidad conocida y el fabricante no publicará corrección. ¿Qué recoge el diseño?",
    options: [
      "Aceptar el riesgo y documentarlo, ya que no existe corrección disponible del fabricante",
      "Retirar el sistema de inmediato y sustituirlo por una alternativa con soporte vigente",
      "Aplicar la actualización de una versión posterior aunque no esté soportada por el fabricante",
      "Mitigación compensatoria —aislamiento y filtrado— con la retirada planificada y su plazo",
    ],
    correct: 3,
    explain: "«Imprescindible» descarta retirarlo hoy y «sin corrección» descarta parchearlo, pero aceptar el riesgo sin más no es un diseño. Lo que se espera es <b>mitigación compensatoria</b> —segmentar, filtrar, restringir quién llega, vigilarlo de cerca— acompañada de un <b>plan de retirada con fecha</b>, para que la excepción no se vuelva permanente. Instalar parches no soportados añade un riesgo distinto. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-posture-vulnerability-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Encontrar el hueco",
    q: "Un cliente ha ido comprando herramientas de seguridad sin un plan y quiere saber qué capacidades le siguen faltando. ¿Qué usas para responder?",
    options: [
      "El Microsoft Cloud Security Benchmark, comprobando control a control lo que no se cumple",
      "Las arquitecturas de referencia de ciberseguridad, para mapear capacidades y ver los huecos",
      "El Cloud Adoption Framework, siguiendo su recorrido de adopción desde la fase de estrategia",
      "El Well-Architected Framework, revisando cada carga de trabajo y sus compromisos de diseño",
    ],
    correct: 1,
    explain: "La pregunta es «<em>qué capacidades me faltan</em>», y ese es el mapa: el <b>MCRA</b> muestra el conjunto de capacidades de seguridad, cómo encajan y qué las cubre, de modo que lo que queda en blanco es el hueco. El <b>MCSB</b> mide si lo que hay está bien <em>configurado</em>, que es otra pregunta. El CAF ordena la adopción y el Well-Architected revisa una carga concreta. <a href=\"https://learn.microsoft.com/en-us/security/adoption/mcra\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Mapa o benchmark",
    q: "Ya definido el conjunto de capacidades, el cliente pide ahora una lista de controles concretos y medibles para saber si su nube está bien configurada. ¿Qué le das?",
    options: [
      "Las arquitecturas de referencia de ciberseguridad, que detallan cómo se integran los productos",
      "El marco de adopción de Zero Trust, con sus tres principios y sus seis pilares",
      "El Microsoft Cloud Security Benchmark, que Defender for Cloud evalúa de forma continua",
      "El modelo de responsabilidad compartida, para delimitar qué controla el proveedor y qué el cliente",
    ],
    correct: 2,
    explain: "Controles <b>concretos y medibles</b> es la definición del <b>MCSB</b>: está mapeado a CIS y NIST, viene asignado por defecto en Defender for Cloud y se evalúa solo, también sobre AWS y GCP conectados. El MCRA da el mapa de capacidades pero no una lista evaluable, Zero Trust da principios, y el modelo de responsabilidad compartida reparte quién hace qué. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El acceso ya es legítimo",
    q: "Un comercial que ha presentado su dimisión descarga la cartera completa de clientes a la que tiene acceso legítimo por su puesto. ¿Qué aborda este riesgo?",
    options: [
      "Exigir MFA resistente a phishing para acceder al sistema de gestión de clientes",
      "Retirar el acceso al sistema al recibir la dimisión, mediante un proceso de baja automatizado",
      "Gestión de riesgo interno, que puntúa el comportamiento del empleado",
      "Una política de acceso condicional que limite el acceso a las oficinas de la organización",
    ],
    correct: 2,
    explain: "Ningún control de acceso lo detiene, porque <b>el acceso es correcto</b>: es su trabajo. Lo que aborda esta amenaza es mirar <b>comportamiento</b> en vez de permisos, y eso es la <b>gestión de riesgo interno</b>, que combina señales —volumen inusual de descarga, dimisión presentada, movimiento a almacenamiento personal— para levantar un caso. Reforzar autenticación o ubicación contesta a una amenaza externa. <a href=\"https://learn.microsoft.com/en-us/purview/insider-risk-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Entrar por la puerta de confianza",
    q: "Tras un incidente sonado en el que un atacante comprometió una biblioteca muy usada, la dirección pregunta qué hace la organización frente a ese tipo de ataque. ¿Qué recoge el diseño?",
    options: [
      "Análisis de composición, procedencia y firma, con gobierno del acceso de terceros",
      "Un WAF con reglas gestionadas delante de todas las aplicaciones que usen bibliotecas de terceros",
      "Prohibir el uso de bibliotecas de código abierto en las aplicaciones críticas de la organización",
      "Aumentar la frecuencia del análisis de vulnerabilidades sobre las máquinas donde se ejecutan",
    ],
    correct: 0,
    explain: "La cadena de suministro entra por algo en lo que <b>ya confías</b>, así que la defensa va en la construcción: <b>análisis de composición</b> para saber qué se incorpora, <b>procedencia y firma</b> para saber que el artefacto es el que se compiló, y gobierno del acceso de proveedores y herramientas. Prohibir el código abierto no es realista, y el WAF y el análisis de máquinas actúan cuando el componente ya está dentro. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/sfi/protect-software-supply-chain\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La IA no es una excepción",
    q: "Un equipo despliega una carga de IA como prueba de concepto y pide quedar fuera del gobierno habitual «hasta que se decida si sigue adelante». ¿Qué respondes?",
    options: [
      "Que es razonable mientras no procese dato de producción, revisándolo cuando pase a serlo",
      "Que le aplican los controles del MCSB igual que a cualquier carga, más los suyos propios",
      "Que puede quedar fuera si se despliega en una suscripción aislada sin conexión con el resto",
      "Que hace falta un marco de gobierno específico para IA antes de poder aplicarle ningún control",
    ],
    correct: 1,
    explain: "El error de diseño típico es tratar la IA como un experimento fuera del gobierno. Una carga de IA es una carga: le aplican los <b>controles del MCSB</b> —identidad sin claves locales, endpoint privado, protección del dato, registro, postura— y <b>encima</b> los suyos propios, como los filtros de contenido y los escudos frente a inyección de instrucciones. No hace falta esperar a un marco nuevo: el que hay ya la cubre. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Controles propios de la IA",
    q: "Al aplicar el MCSB a una carga de IA generativa, ¿qué control no tiene equivalente en una carga tradicional y hay que añadir?",
    options: [
      "Autenticación con Entra ID e identidades administradas en lugar de claves de servicio",
      "Endpoint privado y acceso público deshabilitado sobre el recurso que hospeda el modelo",
      "Envío de las trazas del servicio al SIEM para correlacionarlas con el resto de la señal",
      "Filtros de contenido y escudos frente a la inyección de instrucciones, directa e indirecta",
    ],
    correct: 3,
    explain: "Las tres primeras son controles del benchmark que aplican igual a un servicio de IA que a una base de datos. Lo <b>específico</b> de la IA es que el contenido que el modelo lee puede acabar dirigiendo lo que hace: la <b>inyección de instrucciones</b>, que no la cubre ninguna medida de identidad ni de red y se aborda con los filtros y escudos del propio servicio. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Los tres principios",
    q: "Revisas un diseño donde la red interna se considera de confianza y, una vez dentro, los servicios se hablan entre sí sin autenticar. ¿Qué principio de Zero Trust se incumple?",
    options: [
      "Asumir la brecha: se segmenta y se verifica dando por hecho la intrusión",
      "Verificar explícitamente: falta exigir autenticación multifactor a los usuarios de esos servicios",
      "Mínimo privilegio: los servicios tienen más permisos de los que necesitan para su función",
      "Ninguno: el modelo permite confiar en la red interna si está correctamente segmentada",
    ],
    correct: 0,
    explain: "Tratar la red interna como zona de confianza es exactamente lo que niega <b>asumir la brecha</b>: se diseña dando por hecho que alguien ya está dentro, y por eso el tráfico entre servicios se autentica y se cifra igual que el que viene de fuera. Verificar explícitamente y mínimo privilegio son los otros dos principios y describen otros defectos. Y la cuarta opción es la premisa del modelo que Zero Trust vino a sustituir. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cómo se adopta",
    q: "La dirección aprueba «implantar Zero Trust» y pregunta qué producto hay que comprar y cuándo estará terminado. ¿Qué respondes?",
    options: [
      "Que se implanta con Entra ID y acceso condicional, y queda terminado al cubrir todas las aplicaciones",
      "Que basta con Microsoft Defender XDR, que aplica los tres principios sobre toda la señal del estado",
      "Que es un modelo que se adopta por pilares de forma continua, con el marco de adopción como guía",
      "Que primero hay que migrar por completo a la nube, porque el modelo no aplica a lo que está on-premises",
    ],
    correct: 2,
    explain: "Zero Trust no es un producto ni un proyecto con fecha de fin: es un <b>modelo</b> que se adopta por <b>pilares</b> —identidades, endpoints, aplicaciones, datos, infraestructura y redes—, y el <b>marco de adopción</b> existe justamente para dar el orden, los hitos y cómo medir el avance. El acceso condicional y Defender XDR son piezas importantes, no la implantación entera. Y el modelo aplica también a lo híbrido. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/adopt/zero-trust-adoption-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Antes de dar IA a todos",
    q: "Una organización quiere desplegar Copilot para Microsoft 365 a toda la plantilla el mes que viene. ¿Qué es lo primero del plan?",
    options: [
      "Formar a la plantilla en el uso responsable del asistente y publicar una política de uso aceptable",
      "Clasificar y etiquetar el contenido, y corregir el sobrecompartido de SharePoint y OneDrive",
      "Definir con negocio la lista de casos de uso aprobados y el retorno esperado de cada uno",
      "Desplegar a un grupo piloto y medir la calidad de las respuestas antes de ampliar el alcance",
    ],
    correct: 1,
    explain: "Un asistente <b>hereda los permisos del origen</b>: si el contenido está sobrecompartido, lo reparte más deprisa y ante más gente. Por eso el trabajo previo es de <b>gobierno del dato</b> —clasificar, etiquetar y arreglar permisos—, y todo lo demás viene después. Formación, casos de uso y piloto son partes legítimas del plan, pero ninguna evita que el primer día alguien lea lo que no debía. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La IA que ya se usa",
    q: "Al preparar la estrategia de adopción de IA se descubre que varios equipos ya usan herramientas de IA no aprobadas con documentos internos. ¿Qué recoge la estrategia?",
    options: [
      "Bloquear por categoría todas las herramientas de IA en el filtrado web hasta terminar el plan",
      "Una comunicación interna recordando que solo pueden usarse las herramientas aprobadas",
      "Aceptar el uso existente y auditarlo cuando la estrategia de adopción esté publicada",
      "Descubrir el uso real con Defender for Cloud Apps, y decidir con ese dato",
    ],
    correct: 3,
    explain: "La IA no aprobada es <b>shadow IT</b> y se trata igual: primero <b>descubrir</b> qué se usa y con qué volumen —eso lo da Defender for Cloud Apps a partir del tráfico—, y con ese dato decidir qué se sanciona, qué se sustituye por una alternativa corporativa y qué se bloquea. Bloquear a ciegas empuja el uso a canales sin visibilidad, y una comunicación no cambia el comportamiento por sí sola. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Organización o carga",
    q: "Un cliente pide revisar si el diseño de una aplicación concreta equilibra bien seguridad, fiabilidad y coste. ¿Qué marco aplicas?",
    options: [
      "El Cloud Adoption Framework, que cubre el recorrido completo de adopción de la nube",
      "El Microsoft Cloud Security Benchmark, que evalúa los controles de la carga de trabajo",
      "El Well-Architected Framework, que revisa una carga y hace explícitos sus compromisos",
      "Las arquitecturas de referencia de ciberseguridad, que muestran cómo encajan las capacidades",
    ],
    correct: 2,
    explain: "«Una aplicación concreta» y «equilibrar» son las dos pistas del <b>Well-Architected Framework</b>, que revisa una <b>carga de trabajo</b> a través de sus pilares y obliga a hacer explícitos los <b>compromisos</b>: reforzar seguridad casi siempre cuesta coste, rendimiento o comodidad operativa. El <b>CAF</b> mira la organización y su adopción, el MCSB mide configuración y el MCRA mapea capacidades. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El compromiso explícito",
    q: "En una revisión Well-Architected, el equipo propone endurecer una carga con controles que añaden latencia y coste. ¿Qué se espera del arquitecto?",
    options: [
      "Aplicar los controles igualmente, porque la seguridad tiene prioridad sobre los demás pilares",
      "Documentar el compromiso y llevarlo a decisión del propietario de la carga",
      "Descartar los controles que degraden el rendimiento y buscar alternativas sin ningún impacto",
      "Aplicar solo los controles que no tengan coste adicional y dejar el resto para el año siguiente",
    ],
    correct: 1,
    explain: "El Well-Architected no dice que la seguridad gane siempre: dice que los <b>compromisos existen</b> y que un diseño maduro <em>los hace explícitos</em> en vez de fingir que no están. El arquitecto mide el impacto en latencia y coste, lo pone junto al riesgo que se reduce y lleva la decisión a quien responde de la carga. Aplicar sin más, descartar sin más o filtrar por coste son tres formas de no decidir. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cada equipo a su aire",
    q: "En una organización con cuarenta equipos desplegando en Azure, cada uno configura la seguridad a su criterio y el resultado es dispar. ¿Qué recomiendas?",
    options: [
      "Una guía de buenas prácticas publicada por el equipo de seguridad, con revisión antes de cada despliegue",
      "Una auditoría mensual de las suscripciones con un informe de desviaciones para cada equipo",
      "Formación obligatoria en seguridad de Azure para todos los equipos de desarrollo de la organización",
      "Grupos de administración con iniciativas de Azure Policy y landing zones para lo nuevo",
    ],
    correct: 3,
    explain: "Un resultado dispar entre cuarenta equipos no se arregla pidiéndoles que se acuerden: se arregla poniendo las <b>barandillas en la plataforma</b>. Iniciativas de <b>Azure Policy</b> asignadas a <b>grupos de administración</b> aplican a todas las suscripciones, presentes y futuras, y las <b>landing zones</b> hacen que lo nuevo nazca conforme. La guía, la auditoría y la formación dependen de que cada equipo cumpla. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Quién responde de qué",
    q: "Tras un incidente, nadie sabe quién debía haber configurado el registro de una aplicación: ni el equipo de producto, ni plataforma, ni seguridad se dan por responsables. ¿Qué falta?",
    options: [
      "Un modelo de responsabilidades como el del CAF, con propietario por carga y funciones definidas",
      "Una política de Azure que active el registro de diagnóstico en todos los recursos de la organización",
      "Un espacio de trabajo de Log Analytics centralizado al que envíen todos los equipos sus registros",
      "Una cláusula en el procedimiento de gestión de incidentes que designe un responsable al abrirse cada caso",
    ],
    correct: 0,
    explain: "El defecto no es técnico sino de <b>gobierno</b>: no hay nadie a quien pedirle cuentas. El <b>CAF</b> define funciones de seguridad y un <b>propietario por carga de trabajo</b>, de modo que cada decisión tiene dueño antes del incidente. La política y el workspace resuelven este caso concreto y dejan intacto el problema, y designar responsable cuando ya ha pasado llega tarde por definición. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/teams-roles\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Por qué el grupo de administración",
    q: "Se quiere garantizar que toda suscripción de Azure, incluidas las que se creen el año que viene, tenga activados los planes de Defender y el registro centralizado. ¿Cómo se asegura?",
    options: [
      "Un procedimiento de alta de suscripción que el equipo de plataforma ejecute en cada creación",
      "Iniciativas de Azure Policy con DeployIfNotExists en el grupo de administración",
      "Una plantilla de infraestructura como código que cada equipo use al crear su suscripción nueva",
      "Una revisión trimestral de las suscripciones existentes con corrección de las que no cumplan",
    ],
    correct: 1,
    explain: "«Incluidas las que se creen el año que viene» es la pista del <b>grupo de administración</b>: una asignación ahí alcanza a las suscripciones que <em>aún no existen</em>, y con <b>DeployIfNotExists</b> la configuración se despliega sola en vez de solo auditarse. El procedimiento manual y la plantilla dependen de que alguien se acuerde, y la revisión trimestral corrige después de que el hueco haya existido tres meses. <a href=\"https://learn.microsoft.com/en-us/azure/governance/management-groups/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué separa una landing zone",
    q: "Al diseñar las landing zones, un equipo propone poner las suscripciones de identidad, conectividad y gestión junto a las de las aplicaciones para simplificar. ¿Qué señalas?",
    options: [
      "Que es razonable si todas quedan bajo el mismo grupo de administración con las mismas políticas",
      "Que es razonable siempre que cada aplicación tenga su propio grupo de recursos bien delimitado",
      "Plataforma y carga se separan: distinto ciclo, permisos y políticas",
      "Que solo importa si la organización supera un número determinado de suscripciones activas",
    ],
    correct: 2,
    explain: "El diseño de referencia separa las suscripciones de <b>plataforma</b> —identidad, gestión, conectividad— de las de <b>carga de trabajo</b> porque tienen ciclos de vida, responsables y necesidades de política distintos: quien despliega una aplicación no debe poder tocar la red del hub ni el almacén de registros. Mezclarlas rompe esa separación por comodidad, y los grupos de recursos no la sustituyen. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Una puerta al final",
    q: "En una organización, la seguridad revisa cada aplicación en una única puerta antes del paso a producción, y el equipo se queja de que siempre llega tarde y bloquea entregas. ¿Qué propones?",
    options: [
      "Repartir controles automáticos por el ciclo, en vez de una única puerta",
      "Adelantar la revisión de seguridad dos semanas para que dé tiempo a corregir lo que se encuentre",
      "Añadir más personas al equipo de seguridad para que la revisión final se resuelva más deprisa",
      "Permitir que las aplicaciones no críticas se salten la revisión y reservarla para las críticas",
    ],
    correct: 0,
    explain: "Una puerta al final concentra todos los hallazgos en el momento más caro para arreglarlos, y por eso siempre bloquea. <b>DevSecOps</b> reparte controles <b>automáticos</b> por el ciclo —modelado en diseño, análisis en el código y la pull request, dependencias en la compilación, política en el despliegue—, de modo que cada problema se encuentra donde es barato. Adelantar o reforzar la puerta no cambia su naturaleza. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/develop/secure-devops-environments-zero-trust\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Que el control cuente",
    q: "El análisis de seguridad del pipeline lleva meses generando avisos que nadie atiende, y las entregas siguen su curso. ¿Qué cambio del proceso lo corrige?",
    options: [
      "Enviar un resumen semanal de los avisos abiertos al responsable de cada equipo de desarrollo",
      "Aumentar la sensibilidad del análisis para que no se escape ningún hallazgo relevante",
      "Que el hallazgo por encima del umbral acordado rompa la construcción, con excepción documentada",
      "Trasladar los avisos a la herramienta de incidencias del equipo para que entren en su planificación",
    ],
    correct: 2,
    explain: "Un aviso que no detiene nada acaba siendo ruido, y el ruido no se lee. Lo que hace que el control cuente es que el hallazgo por encima del umbral <b>rompa la construcción</b>, con una vía de <b>excepción documentada y con dueño</b> para los casos justificados. Más sensibilidad genera más ruido, y el resumen semanal y el tablero de incidencias siguen dependiendo de que alguien priorice. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/develop/secure-devops-environments-zero-trust\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Qué se protege primero",
    q: "Dirección pide una estrategia de seguridad y el equipo técnico propone empezar por endurecer los sistemas con más vulnerabilidades detectadas. ¿Qué corriges del planteamiento?",
    options: [
      "Nada: el número de vulnerabilidades es la medida objetiva del riesgo y ordena bien el trabajo",
      "Que hay que empezar por los sistemas más antiguos, que suelen concentrar los defectos sin corregir",
      "Que la prioridad la marca el impacto en el negocio si el sistema cae o se filtra, no el recuento de defectos",
      "Que primero hay que completar el inventario de activos y solo después decidir en qué orden se actúa",
    ],
    correct: 2,
    explain: "Una estrategia de resiliencia empieza en el negocio, no en el escáner. Lo primero es identificar los <b>procesos críticos</b> —los que si paran cuestan dinero, reputación o vidas— y los activos de los que dependen, y a partir de ahí se decide dónde se invierte. Un sistema con cuarenta vulnerabilidades que no soporta nada importante va después de uno con dos que sostiene la facturación. Ordenar por recuento de defectos o por antigüedad optimiza una métrica técnica, no el riesgo. Y el inventario es un paso necesario, pero por sí solo no prioriza: la criticidad la aporta el negocio. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Restaurar no es recuperar",
    q: "Un cliente tiene copias diarias verificadas de todos sus sistemas y considera cubierto su plan de continuidad. En un simulacro tarda once días en volver a operar. ¿Qué faltaba en el diseño?",
    options: [
      "Faltaba probar la recuperación completa del servicio, con orden de dependencias y tiempos medidos",
      "Faltaba aumentar la frecuencia de las copias, ya que una copia diaria implica perder hasta veinticuatro horas de datos",
      "Faltaba cifrar las copias con clave del cliente para que la restauración pudiera hacerse en cualquier región",
      "Faltaba conservar las copias durante más tiempo, para poder volver a un punto anterior al inicio del incidente",
    ],
    correct: 0,
    explain: "Tener copias responde al objetivo de punto de recuperación —cuánto dato pierdo—, pero el simulacro fracasó en el objetivo de <b>tiempo</b> de recuperación: cuánto tardo en volver a operar. Y ese depende de cosas que una copia no resuelve: en qué orden se levantan los sistemas, si la identidad está disponible antes que las aplicaciones que dependen de ella, si hay capacidad donde restaurar, si alguien sabe ejecutar el procedimiento. Por eso el plan se <b>prueba entero</b> y se cronometra contra el objetivo declarado. Copiar más a menudo mejora el otro objetivo, no este; cifrar y retener más tampoco cambian el tiempo. <a href=\"https://learn.microsoft.com/en-us/azure/reliability/concept-business-continuity-high-availability-disaster-recovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Las dos prioridades del ransomware",
    q: "Dirección aprueba un presupuesto limitado contra ransomware y pide saber en qué dos frentes concentrarlo para reducir más el riesgo, según las recomendaciones de Microsoft.",
    options: [
      "Antivirus de última generación en todos los equipos y formación de concienciación para toda la plantilla",
      "Segmentación de la red interna y cifrado de todos los discos de las máquinas del estado",
      "Filtrado de correo reforzado y un ciclo de parcheo mensual obligatorio en servidores y clientes",
      "Copias que el atacante no pueda destruir y control del acceso privilegiado que le deja propagarse",
    ],
    correct: 3,
    explain: "Microsoft ordena el trabajo contra ransomware en torno a dos preguntas: <b>si me cifran, ¿puedo volver?</b> y <b>¿hasta dónde puede llegar el atacante?</b>. La primera se responde con copias protegidas del propio administrador —inmutables, con eliminación temporal, fuera del ámbito de quien administra producción— y con la recuperación probada. La segunda, acotando el acceso privilegiado que convierte un equipo comprometido en el dominio entero. Antivirus, formación, segmentación, filtrado y parcheo son controles útiles y aparecen después, pero ninguno decide si sobrevives al ataque una vez ocurre. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase1\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El parche que no se puede aplicar",
    q: "Un sistema industrial crítico corre sobre una versión sin soporte del sistema operativo. El fabricante no certifica ninguna versión posterior y sustituirlo llevará dos años. ¿Qué recomiendas mientras tanto?",
    options: [
      "Aplicar las actualizaciones de la versión posterior aunque el fabricante no las respalde, porque el riesgo de no parchear es mayor",
      "Mitigación compensatoria —aislar la red, filtrar el acceso y vigilar de cerca— con la retirada planificada y su fecha comprometida",
      "Aceptar y documentar el riesgo, ya que sin actualización del fabricante no existe ningún control que se pueda aplicar",
      "Retirar el sistema de inmediato y sustituirlo por una alternativa con soporte, aunque implique parar la producción",
    ],
    correct: 1,
    explain: "Cuando no se puede parchear, la respuesta no es rendirse ni romper el sistema: es <b>compensar y poner fecha</b>. Compensar significa reducir la exposición con lo que sí controlas —segmentar la red para que solo lo alcance quien debe, filtrar protocolos, restringir cuentas, aumentar la vigilancia sobre ese activo— y poner fecha significa que la mitigación es temporal y hay un plan de retirada aprobado, con presupuesto y responsable. Aplicar actualizaciones no soportadas puede romper el proceso y anular la garantía. Aceptar el riesgo sin controles es abdicar. Y parar producción hoy es desproporcionado frente a un plan de dos años. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Parchear sin parar el servicio",
    q: "El equipo de operaciones se resiste al parcheo mensual porque cada ciclo provoca incidencias en producción. Seguridad exige cumplir el plazo. ¿Qué diseño resuelve el conflicto?",
    options: [
      "Aplicar los parches directamente en producción fuera del horario laboral, aceptando el riesgo de una incidencia nocturna",
      "Reducir el parcheo a los boletines críticos, dejando el resto para la ventana de mantenimiento anual del sistema",
      "Anillos de despliegue: primero un grupo piloto, luego el resto por fases, con programación automática y capacidad de revertir",
      "Delegar la decisión de parchear a cada equipo propietario, que conoce mejor el impacto de cada actualización en su sistema",
    ],
    correct: 2,
    explain: "El conflicto es real y tiene una solución de diseño conocida: <b>desplegar por anillos</b>. Un grupo pequeño y representativo recibe primero las actualizaciones, se observa el resultado unos días y solo entonces avanzan al siguiente anillo, hasta cubrir el estado; la programación y el informe salen de la herramienta de actualizaciones y hay un camino de vuelta si algo falla. Así se cumple el plazo sin apostar toda la producción a un solo día. Parchear de noche no reduce el riesgo, lo mueve. Limitarse a los críticos deja acumularse lo demás. Y delegar sin marco es como se llegó a la situación actual. <a href=\"https://learn.microsoft.com/en-us/azure/update-manager/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Para qué sirve la arquitectura de referencia",
    q: "Un arquitecto usa las arquitecturas de referencia de ciberseguridad de Microsoft como si fueran un diseño a implantar tal cual, y propone desplegar todas las capacidades que aparecen en ellas.",
    options: [
      "Es correcto: las arquitecturas de referencia describen el estado objetivo y desplegarlas completas garantiza la cobertura",
      "Es correcto siempre que se despliegue por fases, empezando por las capacidades de identidad y terminando por las de datos",
      "Es incorrecto: las arquitecturas de referencia solo describen productos de Microsoft y no sirven en un estado con varios proveedores",
      "Es incorrecto: son un mapa de capacidades para situar lo que tienes y detectar huecos, no una lista de compra a ejecutar entera",
    ],
    correct: 3,
    explain: "Las arquitecturas de referencia sirven para <b>orientarse</b>: muestran qué capacidades existen, cómo se relacionan entre sí y qué producto cubre cada una, de modo que puedas colocar encima lo que ya tienes y ver dónde hay hueco, dónde hay solape y qué falta. Tratarlas como una lista de compra lleva a desplegar capacidades sin requisito detrás, con su coste y su operación. La decisión de qué implantar sale del riesgo del cliente, no del dibujo. Y no es cierto que solo valgan para estados de Microsoft: el mapa de capacidades es igual de útil para situar herramientas de terceros y detectar el solape. <a href=\"https://learn.microsoft.com/en-us/security/adoption/mcra\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El riesgo que entra por el proveedor",
    q: "El cliente ha reforzado identidad, endpoint y red, pero no ha mirado cómo llegan a producción los componentes de terceros ni qué acceso tienen sus proveedores de servicios gestionados.",
    options: [
      "Es el hueco de cadena de suministro: verificar el origen de los artefactos y acotar el acceso de los proveedores",
      "No es un hueco relevante mientras los controles de identidad y endpoint estén bien implantados en todo el estado",
      "Se cubre exigiendo a cada proveedor una certificación de seguridad vigente y renovándola una vez al año",
      "Se cubre analizando todos los artefactos con el antivirus del endpoint antes de desplegarlos en producción",
    ],
    correct: 0,
    explain: "Los tres vectores que el temario nombra —interno, externo y <b>cadena de suministro</b>— piden controles distintos, y el tercero se olvida con frecuencia porque no entra por donde miran los demás. Tiene dos caras: el <b>código y los artefactos</b> que llegan de fuera, que exigen verificar procedencia e integridad, firmar y controlar qué entra en la compilación; y el <b>acceso de los proveedores</b>, que suele ser privilegiado, permanente y poco vigilado, y que se acota con acceso temporal, aprobación y auditoría. Un certificado anual no es un control técnico y el antivirus no detecta una dependencia legítima con una puerta trasera introducida aguas arriba. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/sfi/protect-software-supply-chain\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Tres vectores, tres controles",
    q: "Un cliente propone cubrir el riesgo interno con las mismas herramientas que usa contra atacantes externos: filtrado perimetral, detección de intrusiones y bloqueo de dominios maliciosos.",
    options: [
      "Es suficiente, porque un usuario interno malintencionado acaba usando las mismas técnicas que un atacante externo",
      "Es suficiente si además se revisan mensualmente los registros de acceso de los usuarios con permisos elevados",
      "No es suficiente: el interno ya está dentro con acceso legítimo, así que el control mira comportamiento y contexto",
      "No es suficiente: hay que retirar los permisos de administración local a todos los usuarios del estado",
    ],
    correct: 2,
    explain: "La diferencia entre los vectores está en el <b>punto de partida</b>. El atacante externo tiene que entrar, así que se le detecta intentándolo: intrusión, credenciales robadas, explotación. El interno <b>ya está dentro</b> y usa accesos que le corresponden, de modo que ningún control de perímetro se activa: lo que delata no es la intrusión sino el <b>patrón</b> —volumen inusual, actividad fuera de horario, coincidencia con una salida de la empresa— y eso es gestión de riesgos internos con DLP y clasificación. Revisar registros a mano no escala, y retirar la administración local es un buen control, pero no cubre al usuario que abusa de lo que sí tiene concedido. <a href=\"https://learn.microsoft.com/en-us/purview/insider-risk-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Adoptar no es desplegar",
    q: "Un cliente lleva año y medio desplegando controles de Confianza cero y no consigue que el negocio perciba avance ni que se aprueben nuevas fases. Los controles técnicos funcionan bien.",
    options: [
      "Hay que acelerar el despliegue técnico para llegar antes al estado objetivo y que el resultado sea visible de una vez",
      "Falta la parte del marco que no es técnica: escenarios de negocio, patrocinio, objetivos medibles y comunicación del avance",
      "Hay que sustituir el marco por uno más sencillo, porque Confianza cero es demasiado amplio para una organización mediana",
      "Hay que empezar de nuevo por identidad, que es el pilar del que dependen todos los demás controles del modelo",
    ],
    correct: 1,
    explain: "El marco de adopción de Confianza cero es explícito en que la parte difícil no es técnica. Estructura el trabajo en <b>escenarios de negocio</b> —modernizar rápido y seguro, proteger frente al ransomware, cumplir la norma— y en cuatro fases que se repiten por escenario: definir la estrategia con patrocinio, planificar con objetivos medibles, ejecutar y <b>gobernar</b> comunicando el avance. Cuando falta eso, el despliegue técnico avanza pero nadie fuera del equipo entiende qué se ha ganado, y por eso no se aprueban más fases. Acelerar más de lo mismo no cambia esa percepción, y ni el marco es excesivo ni hay que rehacer lo hecho. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/adopt/zero-trust-adoption-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Antes de encender la IA",
    q: "Una organización quiere adoptar IA generativa en seis meses. El equipo de seguridad pregunta cuál es el primer trabajo, antes de elegir modelos o plataformas.",
    options: [
      "Elegir la plataforma y el modelo, ya que el resto de decisiones de seguridad dependen de esa elección técnica",
      "Definir los filtros de contenido y los escudos de peticiones que se aplicarán a todas las cargas de trabajo de IA",
      "Formar a la plantilla en el uso responsable, para que el riesgo principal —el mal uso por desconocimiento— quede cubierto",
      "Poner en orden el gobierno del dato: saber qué hay, cómo está clasificado y quién puede verlo, porque la IA hereda esa exposición",
    ],
    correct: 3,
    explain: "La adopción segura de IA empieza <b>antes de la IA</b>, en el dato. Una herramienta generativa que respeta permisos no crea exposición nueva: <b>revela la que ya existía</b>, porque encuentra en segundos lo que antes había que saber buscar. Por eso el primer trabajo es de gobierno del dato —descubrir, clasificar, etiquetar, corregir comparticiones abiertas y permisos heredados de más— y solo después se decide plataforma, filtros y formación, que son necesarios pero no sustituyen a lo anterior. Empezar por la elección técnica es construir sobre un suelo que nadie ha mirado. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La IA que ya usa la plantilla",
    q: "Antes de aprobar ninguna herramienta, el cliente descubre que buena parte de la plantilla ya pega texto de trabajo en servicios de IA públicos desde el navegador corporativo. ¿Por dónde empiezas?",
    options: [
      "Descubrir el uso real con el catálogo de aplicaciones en la nube, y ofrecer una alternativa aprobada",
      "Bloquear en el proxy todos los dominios de servicios de IA generativa hasta que exista una herramienta corporativa aprobada",
      "Publicar una política interna que prohíba el uso de servicios de IA no aprobados y comunicarla a toda la plantilla",
      "Configurar DLP de punto de conexión para bloquear cualquier pegado de texto en el navegador desde aplicaciones de empresa",
    ],
    correct: 0,
    explain: "Este es el patrón de la IA en la sombra, y se trata como cualquier otro uso no aprobado: primero <b>ver</b> —el descubrimiento de aplicaciones en la nube dice qué servicios se usan, quién y con qué volumen—, luego <b>ofrecer</b> una alternativa aprobada, porque la gente usa esas herramientas para trabajar y prohibirlas sin sustituto empuja el uso a los móviles personales, donde no ves nada. Con eso ya se puede gobernar: bloquear lo peor, permitir lo demás con DLP sobre el contenido sensible. Bloquear de entrada sin alternativa, publicar una política sin controles o bloquear todo pegado son respuestas que no resisten el primer mes. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/security-features\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que la zona de aterrizaje resuelve una vez",
    q: "Cada equipo del cliente crea sus suscripciones y configura por su cuenta red, identidad, registro y directivas. El resultado es que ninguna se parece a otra y auditar cuesta semanas.",
    options: [
      "Publicar una guía escrita de configuración y revisar en la reunión de arquitectura cada suscripción nueva antes de aprobarla",
      "Auditar trimestralmente todas las suscripciones con Azure Policy y abrir incidencias a cada equipo por lo que incumpla",
      "Zonas de aterrizaje: la plataforma entrega la suscripción ya con red, identidad, registro y directivas",
      "Crear una única suscripción compartida para todos los equipos, de modo que solo haya una configuración que mantener",
    ],
    correct: 2,
    explain: "La idea de la zona de aterrizaje es que las decisiones de plataforma se toman <b>una vez</b> y se entregan hechas. El equipo recibe una suscripción que ya nace con su lugar en la jerarquía de grupos de administración, sus directivas heredadas, su conectividad, sus roles y su envío de registros, así que la configuración correcta no depende de que cada uno la repita bien. Una guía escrita depende de que se lea y se siga; auditar después detecta el incumplimiento cuando ya está desplegado y genera fricción constante; y una suscripción compartida elimina la separación de entornos y de permisos que se necesita. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Seguridad que no frena la entrega",
    q: "Al introducir controles de seguridad en las canalizaciones, los equipos de desarrollo se quejan de que cada compilación tarda cuarenta minutos más y muchos hallazgos no son accionables.",
    options: [
      "Mantener todos los controles y aceptar el coste, porque la seguridad justifica cualquier impacto en el tiempo de entrega",
      "Ajustar dónde corre cada control y con qué umbral: lo rápido y de alta señal bloquea, lo lento corre aparte",
      "Mover todos los controles fuera de la canalización y ejecutarlos una vez por semana sobre la rama principal del repositorio",
      "Dejar todos los controles en modo informativo, de manera que nunca detengan una compilación y no molesten al equipo",
    ],
    correct: 1,
    explain: "Un control que el equipo aprende a ignorar no protege nada, y esa es la lección de DevSecOps que el examen busca. El diseño consiste en <b>colocar cada control donde compensa</b>: análisis de secretos y comprobaciones rápidas y de alta señal en la confirmación o la solicitud de cambios, donde bloquear es barato y el hallazgo es casi siempre real; análisis pesados y ruidosos en ejecuciones programadas que alimentan el trabajo pendiente sin frenar a nadie. Y el umbral de bloqueo se acuerda, con excepciones documentadas. Aceptar el coste sin más quema la relación, sacarlo todo fuera pierde la puerta, y dejarlo todo informativo es no tener control. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/develop/secure-devops-environments-zero-trust\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Seguridad frente a disponibilidad",
    q: "Una medida de seguridad reduciría de forma clara el riesgo de intrusión, pero introduce un punto único de fallo en un servicio con exigencia de disponibilidad continua. ¿Cómo se resuelve?",
    options: [
      "Prevalece la seguridad: el riesgo de intrusión es mayor que el de una caída, y la disponibilidad se recupera",
      "Se busca una alternativa que dé el mismo control sin el punto único, y si no existe decide el negocio",
      "Prevalece la disponibilidad: cualquier medida que pueda causar una caída queda descartada por definición",
      "Se implanta la medida en modo pasivo, de forma que registre lo que habría bloqueado pero no llegue a bloquear nunca",
    ],
    correct: 1,
    explain: "Los pilares del marco de buena arquitectura <b>compiten entre sí</b>, y la habilidad que se mide es reconocer el conflicto y resolverlo, no proclamar que uno gana siempre. Lo primero es buscar un diseño que dé el control sin la contrapartida: redundar el componente, degradar con elegancia, aplicar el control en otro punto. Si no existe, la decisión es del <b>negocio</b>, tomada con los dos riesgos sobre la mesa y por escrito. Declarar un ganador por defecto —en cualquiera de los dos sentidos— es no hacer arquitectura. Y dejarlo en pasivo permanente es aparentar un control que no existe. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dos objetivos, dos diseños",
    q: "Un servicio declara un objetivo de punto de recuperación de cinco minutos y un objetivo de tiempo de recuperación de ocho horas. El equipo pregunta qué implica cada número para el diseño.",
    options: [
      "Ambos se cubren con la misma decisión: copias cada cinco minutos conservadas durante ocho horas en el almacén",
      "El primero exige una segunda región activa y el segundo exige aumentar la retención de las copias existentes",
      "Ambos se refieren al mismo intervalo medido de formas distintas, así que basta con diseñar para el más exigente de los dos",
      "El primero exige replicación casi continua del dato; el segundo permite restaurar con calma, y son decisiones independientes",
    ],
    correct: 3,
    explain: "Son dos preguntas distintas y confundirlas produce diseños caros o insuficientes. El objetivo de <b>punto</b> de recuperación mide cuánto dato puedo perder, y cinco minutos obliga a replicación casi continua o a copias muy frecuentes. El objetivo de <b>tiempo</b> mide cuánto puedo tardar en volver a operar, y ocho horas es holgado: permite restaurar y levantar por orden sin necesidad de una segunda región caliente. Aquí la combinación es exigente en dato y relajada en tiempo, y el diseño lo refleja. Que los dos sean exigentes no es lo mismo, y no siempre lo son a la vez. <a href=\"https://learn.microsoft.com/en-us/azure/backup/backup-azure-security-feature\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Del portátil al dominio",
    q: "En un ejercicio, el atacante entra por el portátil de un usuario sin permisos especiales y en cuatro horas controla el dominio. Todos los sistemas estaban parcheados y con antivirus.",
    options: [
      "El problema es la ruta de escalada: credenciales privilegiadas reutilizadas y accesibles desde equipos de uso general",
      "El problema es el antivirus, que no detectó la carga inicial y debe sustituirse por una solución de detección y respuesta",
      "El problema es la segmentación de red, y basta con separar los servidores de los equipos de usuario en redes distintas",
      "El problema es que el usuario abrió el fichero, y se corrige con formación y simulaciones de phishing periódicas",
    ],
    correct: 0,
    explain: "Que todo estuviera parcheado demuestra justo lo que hay que entender: el ransomware moderno no escala por vulnerabilidades sino por <b>credenciales</b>. El atacante entra donde puede y busca en memoria y en disco credenciales privilegiadas que alguien usó ahí, o cuentas locales con la misma contraseña en todas partes, y va saltando. Por eso las contramedidas son el modelo por planos, las estaciones de trabajo dedicadas para administrar, contraseñas locales distintas por máquina y acceso privilegiado temporal. El antivirus y la formación reducen la probabilidad de la entrada inicial, no la escalada; y segmentar ayuda, pero no impide que una credencial válida abra la puerta. <a href=\"https://learn.microsoft.com/en-us/security/ransomware/protect-against-ransomware-phase2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Marco general o punto de referencia técnico",
    q: "Un cliente pregunta qué diferencia hay entre usar las arquitecturas de referencia de ciberseguridad y usar el punto de referencia de seguridad en la nube de Microsoft, y cuándo aplica cada uno.",
    options: [
      "Son lo mismo con distinto nombre: uno es la versión resumida del otro para presentaciones a dirección",
      "Las arquitecturas aplican a Microsoft 365 y el punto de referencia aplica a Azure, así que se usan según el producto",
      "Las arquitecturas sitúan capacidades y responsabilidades; el punto de referencia da controles evaluables",
      "El punto de referencia sustituye a las arquitecturas desde que Defender for Cloud lo asigna de forma predeterminada",
    ],
    correct: 2,
    explain: "Se usan en <b>momentos distintos del diseño</b>. Las arquitecturas de referencia son un mapa: qué capacidades existen, cómo encajan, quién responde de cada una; sirven para orientar la conversación y detectar huecos. El <b>punto de referencia</b> baja al control concreto: qué debe cumplir un recurso, cómo se comprueba y a qué controles de otras normas equivale, y por eso Defender for Cloud lo evalúa automáticamente. Uno no sustituye al otro: primero se decide qué capacidades hacen falta y después se exige el control técnico que las materializa. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La carga de IA es una carga más",
    q: "El equipo pregunta si una carga de trabajo de IA necesita controles de seguridad completamente nuevos o si aplican los mismos que al resto del estado de Azure.",
    options: [
      "Necesita controles completamente nuevos, porque los riesgos del modelo no tienen equivalente en las cargas tradicionales",
      "Aplican los mismos controles de identidad, red, cifrado y registro, y encima se añaden los propios del modelo y de sus datos",
      "Aplican únicamente los controles propios del modelo, ya que la plataforma gestionada cubre por completo el resto",
      "Aplican los mismos controles y ninguno más, porque un servicio de IA es un servicio de plataforma como cualquier otro",
    ],
    correct: 1,
    explain: "El punto de referencia trata una carga de IA como lo que es: un <b>servicio de plataforma</b> al que se le exige lo mismo que a los demás —identidad en lugar de claves, punto de conexión privado, cifrado con la clave que corresponda, registro y postura— y <b>además</b> los controles que solo tienen sentido aquí: filtros de contenido, defensa frente a instrucciones incrustadas, gobierno del dato que alimenta al modelo y de lo que el modelo genera. Ni se tira lo aprendido ni se ignora lo nuevo: se suman las dos capas, y esa es la respuesta que el examen busca. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/security-features\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Filtrar la entrada y la salida",
    q: "Una aplicación de IA de cara al público aplica filtros de contenido sobre lo que escribe el usuario. En una revisión se pregunta si eso basta para cubrir el riesgo de contenido inapropiado.",
    options: [
      "Basta: filtrando la entrada se impide que el modelo reciba nada que le lleve a generar contenido inapropiado",
      "Basta si además el mensaje de sistema instruye al modelo para que rechace ese tipo de peticiones de forma explícita",
      "No basta: hay que registrar todas las respuestas y revisarlas a posteriori para detectar lo que el filtro dejó pasar",
      "No basta: se filtran las dos direcciones, porque el modelo puede generar contenido a partir de algo inocuo",
    ],
    correct: 3,
    explain: "Filtrar solo la entrada supone que todo el riesgo viene de lo que pide el usuario, y no es así: un modelo puede producir contenido dañino, sesgado o confidencial a partir de una petición perfectamente normal, o a partir de contenido incrustado en un documento que se le da a leer. Por eso Seguridad de Contenido se aplica en <b>las dos direcciones</b>, sobre la petición y sobre la respuesta, antes de que la respuesta llegue al usuario. El mensaje de sistema ayuda pero es la capa que el ataque intenta rodear, y revisar registros a posteriori detecta lo que ya se publicó. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Los tres principios, uno a uno",
    q: "Un diseño exige MFA resistente a phishing y dispositivo conforme para todo acceso, cifra el tráfico y segmenta la red. El equipo afirma que cubre Confianza cero por completo.",
    options: [
      "Falta el mínimo privilegio: el diseño dice quién entra y desde dónde, pero no con cuántos permisos ni durante cuánto tiempo",
      "No falta nada: verificar la identidad y el dispositivo y cifrar el tráfico cubren los tres principios del modelo",
      "Falta la verificación explícita, porque no se está usando la ubicación de red como señal en la decisión de acceso",
      "Falta asumir la brecha, porque no se ha desplegado una solución de detección y respuesta en los servidores del estado",
    ],
    correct: 0,
    explain: "Repasar el diseño contra los <b>tres principios</b> uno a uno es el ejercicio que el examen pide. Verificar explícitamente: cubierto, se evalúan identidad y dispositivo en cada acceso. Asumir la brecha: cubierto en parte, hay segmentación y cifrado, que es la contención del daño. <b>Mínimo privilegio</b>: no aparece por ninguna parte —qué puede hacer el usuario una vez dentro, con qué rol, permanente o temporal, revisado por quién—, y es donde está el hueco. Ese es el patrón de estas preguntas: el principio que falta suele ser el que habla de permisos, porque los controles de entrada son los que primero se implantan. <a href=\"https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Quién responde de qué",
    q: "En un cliente, la seguridad de la nube \"la lleva el equipo de plataforma\" y nadie sabe quién decide sobre postura, quién responde a incidentes ni quién aprueba las excepciones de directiva.",
    options: [
      "Es un problema menor: mientras el equipo de plataforma tenga los permisos necesarios, las decisiones acaban tomándose igual",
      "Se resuelve creando un comité mensual de seguridad donde se acuerden entre todos las decisiones pendientes de la nube",
      "Es un hueco de gobierno: el marco define funciones y responsabilidades, y sin dueño no se decide",
      "Se resuelve contratando un servicio gestionado que asuma la seguridad completa del estado en la nube del cliente",
    ],
    correct: 2,
    explain: "El marco de adopción no es solo técnico: define <b>funciones y responsabilidades</b> porque un control sin dueño no se opera. Hay que nombrar quién gobierna la postura y decide el nivel de riesgo aceptable, quién opera la detección y responde a incidentes, quién administra la plataforma y quién aprueba excepciones y con qué caducidad. Sin eso, las recomendaciones se quedan abiertas y las excepciones se vuelven permanentes. Confiar en que \"acaban tomándose\" es como se llega a este estado; un comité mensual sin responsables asignados reparte la culpa en lugar del trabajo; y externalizar traslada la ejecución, no la responsabilidad de decidir. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/teams-roles\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Evaluar una estrategia existente",
    q: "Te piden evaluar la estrategia de seguridad de un cliente que ya lleva tres años en la nube. Tienen controles desplegados, un equipo formado y presupuesto. ¿Con qué criterio la evalúas?",
    options: [
      "Comparando su inventario de herramientas con el de otros clientes del mismo sector y tamaño, para detectar lo que les falta",
      "Contra el marco: estrategia con patrocinio, gobierno con responsables, controles alineados y medición",
      "Midiendo la puntuación de seguridad de sus inquilinos y suscripciones, que resume el estado de forma objetiva y comparable",
      "Revisando el número de incidentes de los últimos doce meses, que indica si los controles desplegados están funcionando",
    ],
    correct: 1,
    explain: "Evaluar una estrategia no es inventariar herramientas ni leer un número. El marco da la estructura: ¿existe una <b>estrategia</b> escrita, con patrocinio y objetivos del negocio detrás? ¿Hay <b>gobierno</b>, con responsables nombrados y excepciones con caducidad? ¿Los <b>controles</b> responden al riesgo real de este cliente o a lo que traía el catálogo? ¿Se <b>mide</b> el avance de forma que dirección lo entienda? Comparar con otros clientes ignora que el riesgo es distinto. La puntuación es una entrada, no la evaluación. Y contar incidentes mide también la suerte y la actividad del atacante. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La recomendación que el cliente puede sostener",
    q: "Un cliente pequeño, con dos personas en sistemas y sin equipo de seguridad, pide recomendaciones. La tentación es proponerle el mismo diseño que a una gran empresa con centro de operaciones propio.",
    options: [
      "Proponer el mismo diseño, porque el riesgo no depende del tamaño de la organización y las buenas prácticas son universales",
      "Proponer solo controles gratuitos, ya que un cliente pequeño no puede asumir el coste de ninguna licencia adicional",
      "Proponer el diseño completo y que el cliente decida qué partes implanta según el presupuesto que tenga disponible cada año",
      "Ajustar la recomendación a lo que ese cliente puede operar: preferir lo gestionado y lo automático",
    ],
    correct: 3,
    explain: "Una recomendación que el cliente no puede operar no reduce riesgo: produce alertas que nadie mira y controles que se desactivan al primer incidente. Recomendar bien exige tener en cuenta la <b>capacidad operativa</b>, y para una organización pequeña eso significa inclinarse por lo gestionado y lo automático —detección que responde sola, directivas que corrigen, valores seguros por defecto— antes que por herramientas potentes que dan por supuesto un centro de operaciones. No es rebajar la seguridad, es elegir la forma que sobrevive. Ni el tamaño es irrelevante, ni el criterio es el precio, ni descargar la decisión entera en el cliente es asesorar. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Recomendar con orden",
    q: "Presentas veinte recomendaciones de seguridad a un cliente que puede acometer cinco este año. Pide que le digas cuáles y por qué, no que elija él de una lista sin ordenar.",
    options: [
      "Las cinco que más reducen el riesgo de sus procesos críticos, explicando en cada una qué escenario concreto deja de ser posible",
      "Las cinco más baratas de implantar, para maximizar el número de recomendaciones cerradas con el presupuesto disponible",
      "Las cinco que exige la norma sectorial que le aplica, dejando el resto para cuando llegue una nueva obligación",
      "Las cinco que Defender for Cloud marca como críticas, que es el orden que la propia herramienta ya calcula",
    ],
    correct: 0,
    explain: "El valor del arquitecto está precisamente en el <b>orden y la justificación</b>, no en la lista. Priorizar bien significa cruzar lo que la herramienta señala con lo que este cliente no puede permitirse que ocurra, y explicar cada recomendación en términos de <b>qué escenario deja de ser posible</b> si se implanta: eso es lo que permite a dirección decidir y sostener el presupuesto. Ordenar por coste optimiza el recuento de tareas cerradas. Limitarse a la norma cubre la auditoría, no el riesgo. Y la gravedad de la herramienta ignora la criticidad del activo, que es justo lo que el cliente aporta y la herramienta no sabe. <a href=\"https://learn.microsoft.com/en-us/azure/well-architected/security/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dónde se pone la directiva",
    q: "Se aprueba una directiva que debe cumplirse en todas las suscripciones actuales y en las que se creen en adelante. El equipo propone asignarla suscripción por suscripción para tener control fino.",
    options: [
      "Es correcto: asignar en cada suscripción permite adaptar los parámetros de la directiva a la realidad de cada equipo",
      "Es un error: se asigna en el grupo de administración que corresponda y se hereda, incluidas las suscripciones futuras",
      "Es correcto siempre que exista un proceso documentado que obligue a asignarla también en cada suscripción nueva",
      "Es un error: hay que asignarla en el grupo raíz del inquilino, que es el único ámbito donde la herencia funciona",
    ],
    correct: 1,
    explain: "Es la base del gobierno de una zona de aterrizaje: la jerarquía de grupos de administración existe precisamente para esto: una asignación en un grupo <b>se hereda</b> hacia abajo y alcanza también a las suscripciones que aún no existen, así que la que se cree mañana nace ya conforme. Asignar una por una convierte cada suscripción nueva en una oportunidad de olvido, que es como aparecen los huecos de gobierno. Documentar un proceso manual no cambia eso, solo reparte la culpa. Y el ámbito no tiene que ser la raíz: se elige el grupo que abarca exactamente lo que la directiva debe cubrir, que puede ser producción, una unidad de negocio o una región. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La misma credencial en todas partes",
    q: "Una única entidad de servicio con permisos de colaborador en todas las suscripciones sirve a las canalizaciones de los doce equipos. Es cómoda de gestionar y nunca ha dado problemas.",
    options: [
      "Es aceptable mientras el secreto se custodie en el almacén de la organización y se rote de forma automática cada noventa días",
      "Es aceptable si se audita cada uso de esa entidad y se revisa el registro de despliegues una vez al mes con los equipos",
      "Cualquier canalización comprometida despliega en cualquier suscripción: una identidad por equipo y entorno, acotada a lo que despliega",
      "Es preferible sustituirla por una identidad administrada única, que elimina el secreto y mantiene la comodidad de gestión actual",
    ],
    correct: 2,
    explain: "El problema no es el secreto, es el <b>alcance</b>. Una sola identidad con colaborador en todo significa que un fallo en la canalización menos importante —una dependencia comprometida, una rama abierta por cualquiera, un registro que filtra una variable— entrega el estado entero. El diseño correcto separa por equipo y por entorno, con permisos acotados a lo que esa canalización despliega realmente, y a ser posible sin secreto, mediante federación de identidades de carga de trabajo. Custodiar y rotar mejor el secreto, o auditarlo, no reduce lo que consigue quien lo use; y una identidad administrada única mantiene exactamente el mismo alcance excesivo. <a href=\"https://learn.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["best-practices"] = QUIZ_DATA;
