// Question bank for the module: security solutions for infrastructure (SC-100, domain 3).
// Every explanation ends with a link to the official Microsoft Learn documentation.

var QUIZ_DATA = [
  {
    tag: "CSPM versus CWPP",
    q: "A customer has just connected their subscriptions to Defender for Cloud and sees a long list of recommendations but no alerts. They ask why the product \"doesn't detect anything\". What do you explain?",
    options: [
      "That alerts take up to 30 days to appear while the service learns the environment's normal behaviour",
      "That the free tier gives posture; detecting requires turning on the workload protection plans",
      "That the Azure Monitor agent has to be installed on every resource before any security alert is generated",
      "That recommendations and alerts are the same thing and the recommendations already are the service's alerts",
    ],
    correct: 1,
    explain: "Defender for Cloud is two things: <b>posture</b> (CSPM), which is on by default and evaluates configuration against the MCSB returning recommendations, and <b>workload protection</b> (CWPP), which is the set of paid plans per resource type and is what generates alerts. With no plan enabled there is no detection, however well configured everything is. And a recommendation says what <em>could</em> happen; an alert says what <em>is</em> happening. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/concept-cloud-security-posture-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The cloud's baseline",
    q: "Management asks for a security baseline common to Azure and to the connected AWS accounts, with minimal operational effort. What do you propose?",
    options: [
      "The Microsoft Cloud Security Benchmark, already assigned and evaluated against AWS and GCP too",
      "Writing your own Azure Policy initiative gathering the controls the organisation considers mandatory",
      "Adopting CIS as the standard and translating each of its controls into hand-written policy definitions",
      "Exporting the recommendations to a workbook and reviewing them quarterly with the platform teams",
    ],
    correct: 0,
    explain: "The <b>MCSB</b> is exactly that: the baseline Microsoft considers common to any cloud, already assigned by default in Defender for Cloud and applied to connected <b>AWS and GCP</b> accounts too. \"Minimal operational effort\" rules out writing it. Your own initiative, or CIS translated by hand, is work that is already done — and it has to be maintained. The quarterly workbook is not a control. <a href=\"https://learn.microsoft.com/en-us/security/benchmark/azure/introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What each score measures",
    q: "The security lead wants a metric telling them how much the tenant's configuration has improved in identity, email and managed devices. Which one is it?",
    options: [
      "The Defender for Cloud secure score, which aggregates the state of every resource in the subscriptions",
      "The MCSB compliance percentage in the Defender for Cloud regulatory compliance dashboard",
      "The number of open recommendations by severity in the Defender for Cloud resource inventory",
      "Microsoft Secure Score, in the Defender portal",
    ],
    correct: 3,
    explain: "These are two different scores with almost identical names. <b>Microsoft Secure Score</b>, in the Defender portal, measures the <b>tenant's</b> configuration: identity, email, apps and devices. The <b>Defender for Cloud secure score</b> measures the configuration of the <b>resources</b> in Azure, AWS and GCP. The stem names identity, email and devices, so it is the first one. And MCSB compliance measures conformance with a standard, not improvement. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Score or compliance",
    q: "An external auditor asks for evidence of the degree of PCI DSS compliance in the Azure subscriptions. The team proposes showing them the secure score trend. What do you recommend?",
    options: [
      "Showing the secure score alongside the list of open recommendations ordered by severity",
      "Exporting the resource inventory and annotating by hand which PCI DSS control each resource covers",
      "Adding PCI DSS as a standard and taking the regulatory compliance dashboard, control by control",
      "Showing the secure score, since a high value implies the PCI DSS controls are being met",
    ],
    correct: 2,
    explain: "The secure score is a <b>relative improvement</b> metric: it is not mapped to any regulation's controls and does not answer \"do we meet requirement 8.3?\". The <b>regulatory compliance dashboard</b> does: you add PCI DSS as a standard and it shows, control by control, what is met and what is not, with exportable evidence. Annotating by hand is neither repeatable nor verifiable. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/regulatory-compliance-dashboard\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Connector or Arc",
    q: "A customer has Azure subscriptions, two AWS accounts and forty servers in their own data centre, and wants unified security posture across all of it. Which TWO pieces does the design include?",
    options: [
      "The Defender for Cloud AWS connector, which evaluates the account's configuration agentlessly",
      "A Log Analytics workspace for each of the three environments, with its data collection rule",
      "Azure Arc over the data centre servers, so they exist as Azure resources",
      "A separate Azure subscription per environment, each with its own management group",
    ],
    correct: [0, 2],
    explain: "These are two distinct gaps and each has its piece. The AWS account comes in through the <b>multicloud connector</b>, which reads its configuration <em>without installing anything</em>. The data centre servers come in through <b>Azure Arc</b>, which projects them into the Azure control plane so Policy and the Defender plans can apply to them. Workspaces are a logging decision, not a posture one, and extra subscriptions add no visibility. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-multicloud-security-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Agentless posture",
    q: "The AWS team agrees to connect their accounts to Defender for Cloud, but sets one condition: no Microsoft software is installed on their instances. What can still be offered?",
    options: [
      "Nothing useful: with no agent on the instances, the connector cannot see the account's configuration",
      "Full posture for the account, because the connector reads configuration over the API with no agents",
      "Only the resource inventory, with no recommendations and no evaluation against the MCSB",
      "Only network-layer alerts, obtained from the source cloud's own flow logs",
    ],
    correct: 1,
    explain: "The <b>posture side is agentless</b>: the connector assumes a role in the account and reads configuration over the API, so the MCSB is evaluated in full and the recommendations appear without touching a single instance. What does need deployment is some of the workload protection plans, and that is a second conversation. Saying there is nothing without an agent throws away exactly what the connector brings. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-multicloud-security-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Which plan covers the risk",
    q: "Administrators need RDP and SSH against a group of virtual machines, but security will not accept the ports being permanently open. Which plan and which capability?",
    options: [
      "Defender for Servers P1, with Defender for Endpoint deployed on each machine in the group",
      "Defender for Resource Manager, which watches suspicious operations on the Azure control plane",
      "Defender for Servers P2, with just-in-time access to the management ports",
      "Defender CSPM, which recommends closing management ports exposed to the internet",
    ],
    correct: 2,
    explain: "<b>Just-in-time access</b> opens the port only for the requesting IP, for the approved period, and closes it again: that is exactly the requirement, and it lives in <b>Defender for Servers P2</b>. P1 brings EDR, which is a different thing. Defender for Resource Manager watches the control plane, not the ports. And Defender CSPM <em>recommends</em> closing them but gives no mechanism to open them when needed. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/just-in-time-access-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Choosing the plan from the risk described",
    q: "An application lets external customers upload files to a storage account. The worry is that they upload malicious content. What do you turn on?",
    options: [
      "Defender for Storage, with malware scanning on upload",
      "Defender for App Service, which detects suspicious code execution in the web application",
      "Defender CSPM, so it recommends disabling public access on the storage account",
      "Defender for Servers P2, with file integrity monitoring over the file system",
    ],
    correct: 0,
    explain: "The risk is in <em>what gets uploaded</em>, and that is covered by <b>Defender for Storage</b>, which scans the object at upload time and alerts — or lets you block — if it is malicious. Defender for App Service watches the application, not the stored content. Disabling public access is good posture but examines no files. And file integrity monitoring watches changes on a server file system, not customer uploads. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What Arc enables",
    q: "You need to enforce and audit a specific operating system configuration on Linux servers living in the customer's data centre, with the same tooling used in Azure. What makes that possible?",
    options: [
      "An equivalent group policy applied from the organisation's on-premises Active Directory",
      "A configuration script run by the deployment tool the systems team already uses",
      "Defender for Servers P1, which deploys Defender for Endpoint onto those Linux servers",
      "Azure Arc, which projects them as resources and enables Azure Policy with Machine Configuration",
    ],
    correct: 3,
    explain: "<b>Azure Arc</b> is what makes an outside server exist as an <em>Azure resource</em>; from there you apply <b>Azure Policy</b> with <b>Machine Configuration</b>, which audits and remediates operating system configuration exactly as on an Azure machine. Group policy does not reach Linux. The script leaves no auditable evidence. And Defender for Servers brings EDR, not configuration. <a href=\"https://learn.microsoft.com/en-us/azure/azure-arc/servers/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Arc is not a log connector",
    q: "After connecting the data centre servers with Arc, the SOC asks why their security events are not showing up in Sentinel. What is missing?",
    options: [
      "Re-registering the servers in Arc, this time from the subscription where the workspace lives",
      "Deploying the Azure Monitor agent with its data collection rule and connecting the source in Sentinel",
      "Enabling Defender CSPM on the subscription, which is what forwards events from connected resources",
      "Assigning an audit Azure Policy initiative over the management group containing the servers",
    ],
    correct: 1,
    explain: "Arc <b>governs</b> the resource; it does not carry its logs. For the events to reach the SIEM you need the <b>Azure Monitor agent</b> — which Arc can deploy as an extension — with its <b>data collection rule</b>, and the source connected in Sentinel. These are two separate decisions, and a stem asking to govern <em>and</em> correlate needs both pieces. <a href=\"https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What you didn't know you had",
    q: "After a merger, the customer suspects there are domains and web servers published in their name that no team claims. They want the inventory of what an attacker would see from the internet. What do you use?",
    options: [
      "The Defender for Cloud resource inventory, filtered by resources holding a public IP address",
      "An agentless vulnerability assessment across every machine in the connected subscriptions",
      "Microsoft Defender EASM, starting from seeds such as the organisation's domains and IP ranges",
      "The virtual network flow logs, looking for inbound connections from unknown addresses",
    ],
    correct: 2,
    explain: "The value of <b>Defender EASM</b> is precisely in what is not in your subscriptions: it starts from <b>seeds</b> — domains, IP ranges, organisation names — and recursively discovers hosts, subdomains, certificates and pages belonging to you, whether you know about them or not. Defender for Cloud only sees what you have connected, which is exactly what is missing here. And flow logs see traffic, not inventory. <a href=\"https://learn.microsoft.com/en-us/azure/external-attack-surface-management/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Inside or outside",
    q: "Presenting the design, someone proposes replacing Defender EASM with Defender for Cloud \"because it already gives posture and costs less\". What do you answer?",
    options: [
      "That it is reasonable, because Defender for Cloud also discovers external assets from the seeds you give it",
      "That they look at different things: Defender for Cloud sees what is connected, EASM sees what is published even if you don't know it",
      "That it is reasonable provided Defender CSPM is enabled, which extends discovery to internet-facing assets",
      "That it only makes sense if an external penetration testing service is also contracted periodically",
    ],
    correct: 1,
    explain: "This is the distinction the task is after: Defender for Cloud gives an <b>inside-out</b> view — what is in the connected subscriptions and accounts — and EASM an <b>outside-in</b> one, the attacker's, including the subdomain from a forgotten campaign or the test environment left published. Nothing that is not connected shows up in Defender for Cloud, and that is precisely the customer's problem. <a href=\"https://learn.microsoft.com/en-us/azure/external-attack-surface-management/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Prioritising for real",
    q: "The team is carrying thousands of open recommendations and closing them by severity, with no drop in exposure. What process change do you propose?",
    options: [
      "Close first the ones affecting most resources, so the total number drops faster",
      "Distribute the recommendations across the owning teams and set a monthly closure target",
      "Work the attack paths towards critical assets and fix their chokepoints",
      "Raise the severity threshold so only critical recommendations enter the list",
    ],
    correct: 2,
    explain: "Ten criticals on isolated machines matter less than one medium on the road to a domain controller. <b>Security Exposure Management</b> chains assets and weaknesses into <b>attack paths</b> and points at the places where several paths cross: fixing one cuts many at once. Counting affected resources, sharing out the list or raising the threshold change the number, not the exposure. <a href=\"https://learn.microsoft.com/en-us/security-exposure-management/work-attack-paths-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What is critical to the business",
    q: "The attack paths coming out don't match what the business considers important: test environments show up and the billing system doesn't. What is missing from the configuration?",
    options: [
      "Critical asset classification, so prioritisation weighs business impact",
      "More data connectors, so the graph includes sources that are not being read today",
      "A security initiative specific to the production environment, with its own progress metric",
      "Azure resource tags carrying the system name and the owning team for each workload",
    ],
    correct: 0,
    explain: "The engine knows what is exposed and what is reachable, but it does not know <em>what you care about</em> until you tell it. <b>Critical asset management</b> is where you mark — with built-in or custom classifications — which resources are business critical, and from there paths and prioritisation order themselves by real impact. Azure tags document, but they do not feed that prioritisation. <a href=\"https://learn.microsoft.com/en-us/security-exposure-management/critical-asset-management\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Servers on several platforms",
    q: "The server estate mixes Windows Server, several Linux distributions and machines in AWS. Security wants uniform detection and response across all of them. What do you propose?",
    options: [
      "A different EDR product per platform, chosen by whichever team administers each one",
      "Defender for Servers, which brings Defender for Endpoint to Windows and Linux, on Azure, Arc and AWS",
      "Sentinel analytics rules over the operating system logs each server already generates",
      "Hardening group policies on Windows and hand-reviewed bastion guides on Linux",
    ],
    correct: 1,
    explain: "<b>Defender for Servers</b> deploys <b>Defender for Endpoint</b> across Windows and Linux, and reaches Azure machines, Arc-connected ones and AWS and GCP machines through their connectors: that is what gives the uniformity the stem asks for. One EDR per platform multiplies consoles. Logs in Sentinel give detection, but no response on the machine. And hardening prevents, it does not detect. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-defender-for-servers-select-plan\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Credentials on the server",
    q: "An application on a virtual machine keeps the connection string for an Azure database in a configuration file. What does the design specify?",
    options: [
      "Encrypting the machine's disk with a customer-managed key, to protect that file",
      "Restricting the file's permissions to the service account and auditing who reads it with the audit policy",
      "Rotating the password every thirty days through an automation that rewrites the configuration file",
      "Using a managed identity for the machine and removing the credential from the file",
    ],
    correct: 3,
    explain: "The exam's order of preference: <b>managed identity</b> first, secret in Key Vault second, secret in configuration never. If the application authenticates with the machine's identity, there is no credential to protect, encrypt or rotate. The other three options guard a secret whose very existence was the problem. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Personal device, corporate data",
    q: "Sales staff read corporate email on their personal phones. The company cannot manage those devices, but needs to stop data leaking into personal apps. What do you design?",
    options: [
      "Enrolling the devices in Intune with a light compliance policy, for email only",
      "Blocking access from non-compliant devices with a conditional access policy",
      "App protection policies, which fence the data inside the managed application",
      "Publishing email through a virtual desktop they connect to from the personal phone",
    ],
    correct: 2,
    explain: "\"We cannot manage the device\" rules out enrolment, and it also rules out conditioning on compliance, which needs a managed device. <b>App protection policies</b> (MAM) protect the data <em>inside</em> the app — encryption, no copy-paste into personal apps, no saving locally — without touching the rest of the phone. The virtual desktop works, but it is a whole infrastructure for a problem that already has an answer. <a href=\"https://learn.microsoft.com/en-us/intune/intune-service/apps/app-protection-policy\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Device state as a signal",
    q: "You want only corporate machines with disk encryption on and antivirus up to date to reach the applications. How is it wired?",
    options: [
      "An Intune compliance policy and a conditional access policy requiring a compliant device",
      "An Azure Policy rule over the machines, blocking access for those that do not meet the requirements",
      "A list of the offices' IP addresses as a trusted location in conditional access",
      "A monthly review of the device inventory, withdrawing access from those that do not comply",
    ],
    correct: 0,
    explain: "Two pieces interlocking: <b>Intune</b> evaluates the machine against a <b>compliance policy</b> and stamps the result on the device identity; <b>conditional access</b> consumes that signal with the \"require device to be marked as compliant\" control. Azure Policy governs Azure resources, not client machines. The IP says where the machine is, not how it is. And a monthly review arrives late. <a href=\"https://learn.microsoft.com/en-us/intune/intune-service/protect/device-compliance-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "An IoT device's identity",
    q: "A manufacturer is about to deploy a hundred thousand sensors that will send telemetry to Azure. The current plan is to bake the same shared key into the firmware image. What do you recommend?",
    options: [
      "Keeping the shared key but rotating it every six months through a mass firmware update",
      "Per-device identity with an X.509 certificate or TPM, provisioned with the Device Provisioning Service",
      "A different key per manufacturing batch, so a compromise only affects that batch of sensors",
      "Encrypting the firmware so the shared key cannot easily be extracted from the device",
    ],
    correct: 1,
    explain: "One shared key across a hundred thousand devices is a single point of failure: whoever extracts one impersonates them all, and there is no way to <b>revoke just one</b>. The right design is a <b>per-device identity</b> — X.509 certificate or a key in a TPM — provisioned automatically with the <b>Device Provisioning Service</b>. Rotating, batching or encrypting the firmware shrink the problem's scale but do not change it. <a href=\"https://learn.microsoft.com/en-us/azure/iot-dps/about-iot-dps\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Office IoT",
    q: "The corporate network inventory leaves out cameras, printers and meeting-room controllers, and nobody knows whether they are patched. They take no agent. What do you recommend?",
    options: [
      "An authenticated vulnerability scan against each of those devices, using an administrator credential",
      "Segmenting them into an isolated network and considering them covered, since they hold no corporate data",
      "Enterprise IoT discovery, which uses the Defender for Endpoint sensors already deployed",
      "A Defender for IoT OT network sensor connected to a mirror port on the core switch",
    ],
    correct: 2,
    explain: "For <b>enterprise IoT</b> — cameras, printers, room devices on the corporate network — discovery goes through <b>Enterprise IoT</b>, which uses machines already running Defender for Endpoint as sensors, with nothing installed on the device. The OT sensor is the answer for the <em>industrial</em> network, not the office one. Segmenting helps, but gives neither inventory nor vulnerabilities. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/eiot-defender-for-endpoint\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Visibility on the plant floor",
    q: "A factory wants to detect threats on its industrial control network. The condition is firm: no software is installed on the PLCs and production is not interrupted. What do you propose?",
    options: [
      "Defender for Endpoint on the engineering workstations, as an observation point into the industrial network",
      "An active scan of the industrial network during the scheduled monthly maintenance window",
      "Shipping the historian and SCADA logs to Sentinel and writing your own analytics rules",
      "A Defender for IoT network sensor in passive mode, on a mirror port",
    ],
    correct: 3,
    explain: "In OT you install nothing and you do not probe: an active scan can knock over a PLC. <b>Defender for IoT</b> works with a <b>passive sensor</b> on a mirror port that understands the industrial protocols and from there produces inventory, vulnerabilities and anomalies <em>without emitting a single packet</em>. Engineering workstations are a partial blind spot, and SCADA logs do not see device-to-device traffic. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The right matrix",
    q: "The SOC is about to measure its detection coverage over the industrial environment it has just taken on. Which MITRE ATT&CK matrix is it evaluated against?",
    options: [
      "Against the ICS matrix, which captures the techniques specific to industrial control systems",
      "Against the Enterprise matrix, which is the reference one and covers any environment in an organisation",
      "Against the Mobile matrix, because of the handheld terminals the operators use on the plant floor",
      "Against all three at once, averaging the coverage percentage each one produces",
    ],
    correct: 0,
    explain: "ATT&CK has three matrices and they are not interchangeable: <b>Enterprise</b> for corporate systems and cloud, <b>Mobile</b> for iOS and Android, and <b>ICS</b> for industrial control systems, with techniques that exist nowhere else. An OT environment is evaluated against <b>ICS</b>. Averaging the three mixes frameworks measuring different universes and says nothing useful about the real gap. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Applying a baseline",
    q: "You want an operating system hardening baseline, applied and audited continuously, across Azure servers and others connected with Arc. With what?",
    options: [
      "With a hardened golden image, redeploying any machine that drifts from the configuration",
      "With Azure Policy and Machine Configuration, which audits and remediates configuration inside the server",
      "With Intune security baselines, assigned to the device group holding the servers",
      "With a Sentinel analytics rule alerting whenever a critical operating system setting changes",
    ],
    correct: 1,
    explain: "<b>Machine Configuration</b> is the Azure Policy extension that looks <em>inside</em> the operating system: it audits configuration against a baseline and, if allowed, remediates it, on Azure machines and on <b>Arc</b>-connected ones alike. The golden image sets the starting point but does not watch for drift. Intune is for clients. And an alert detects the change, it does not prevent it. <a href=\"https://learn.microsoft.com/en-us/azure/governance/machine-configuration/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Rollout order",
    q: "The new server baseline is going to be applied across an estate of eight hundred legacy machines, many of them still on the old configuration. How is it rolled out?",
    options: [
      "In remediation mode from day one, so the estate converges on the baseline as soon as possible",
      "Only on new machines, leaving the legacy ones with their configuration until they are retired",
      "In audit mode to measure the real drift, remediate in batches, and enforce afterwards",
      "With a permanent exception for the legacy machines, documented as accepted risk",
    ],
    correct: 2,
    explain: "It is the same pattern as in governance: <b>audit</b> to learn the real scope, <b>remediate</b> in batches with a change window, and <b>enforce</b> at the end so the drift cannot come back. Remediating eight hundred legacy machines at once is how production breaks. Applying it only to new machines, or accepting the risk forever, leaves the estate split in two indefinitely. <a href=\"https://learn.microsoft.com/en-us/azure/governance/machine-configuration/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "A repeated local password",
    q: "A penetration test shows that, from one compromised laptop, any other in the estate can be reached by replaying the local administrator hash. What cuts it?",
    options: [
      "Renaming the local administrator account on every machine to make it harder to locate",
      "Windows LAPS, with a different password per machine, rotated automatically and held in Entra ID",
      "A group policy setting a long, distinct password for each department in the company",
      "Permanently disabling the local administrator account on every machine in the estate",
    ],
    correct: 1,
    explain: "The problem is that the credential <b>is the same everywhere</b>. <b>Windows LAPS</b> makes it unique per machine, rotates it with no intervention and keeps the copy in <b>Entra ID</b> or AD DS with scoped, audited read: one compromised machine stops opening the others. Renaming does not stop hash replay. A password per department is still shared. And disabling it strands the machine that loses the domain. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where the password is kept",
    q: "Evaluating Windows LAPS for an estate of Entra-joined-only machines, the team asks where the password ends up and who can read it. What do you answer?",
    options: [
      "It stays encrypted on the machine itself, and is recovered by booting into recovery mode with a master key",
      "It stays in a per-machine Key Vault, with an access policy for each administrator in the estate",
      "It stays on the Entra ID device object, and reading it is granted by role and audited",
      "It stays in an encrypted file on the administrative share, with restricted NTFS permissions",
    ],
    correct: 2,
    explain: "LAPS backs the password up on the <b>device object</b> — in <b>Entra ID</b> for Entra-joined machines, or on the AD DS computer object in a domain — reading it is granted through a role, and every retrieval <b>is audited</b>. That trail is half the value of the control: not only is there a distinct password per machine, there is a record of who asked for it and when. <a href=\"https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "A SaaS baseline",
    q: "The organisation uses a couple of dozen third-party SaaS applications and wants to evaluate continuously whether they are securely configured. Which tool covers that surface?",
    options: [
      "Azure Policy, with an initiative gathering the expected settings for each of the applications",
      "The Defender for Cloud regulatory compliance dashboard, adding whichever standard applies to the sector",
      "The Defender for Cloud secure score, which covers resources and the applications connected to the tenant",
      "SaaS security posture management in Defender for Cloud Apps",
    ],
    correct: 3,
    explain: "Every surface has its tool and mixing them up is the typical mistake in this task. IaaS and PaaS: Defender for Cloud and Azure Policy. <b>Third-party SaaS</b>: <b>SaaS security posture management</b> in <b>Defender for Cloud Apps</b>, which connects to the application and evaluates its configuration. Azure Policy does not reach someone else's SaaS, and the Defender for Cloud secure score measures cloud resources, not those applications' settings. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/security-saas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Where the PaaS baseline is set",
    q: "You want no new PaaS service to be deployed with public access enabled, across all present and future subscriptions. How is it specified?",
    options: [
      "An Azure Policy initiative assigned at the management group, with a Deny effect",
      "A Defender for Cloud recommendation assigned to each subscription's owners, with a due date",
      "A governance rule notifying the responsible team every time a public resource appears",
      "A reviewed infrastructure-as-code template, published by the platform team as the standard",
    ],
    correct: 0,
    explain: "\"Present and future\" points at the <b>management group</b>, which is where an assignment reaches subscriptions that do not exist yet, and \"not be deployed\" points at <b>Deny</b>, the preventive control. Defender for Cloud recommendations and governance rules warn and track, but do not prevent. And a standard template only covers whoever uses it. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The IoT platform",
    q: "Reviewing an IoT workload, you see the IoT Hub accepts connections from the internet and that every device uses the same shared access policy on the hub. What do you prioritise?",
    options: [
      "Rotating the shared policy key and setting up a quarterly rotation schedule",
      "Turning on the hub's diagnostic logging and shipping it to Sentinel to detect anomalous connections",
      "A per-device credential with least privilege, and a private endpoint for the hub",
      "Encrypting the telemetry in the application before sending it, on top of the protocol's transport encryption",
    ],
    correct: 2,
    explain: "These are the design's two structural defects and they go together: a <b>per-device credential</b> with least privilege — so one can be revoked without touching the rest — and a <b>private endpoint</b> so the hub stops being published. Rotating the shared key keeps the single point of failure. Logging detects after the fact. And end-to-end encryption protects the data but does not fix who can connect. <a href=\"https://learn.microsoft.com/en-us/azure/iot/iot-overview-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Revoking a device",
    q: "A batch of devices is found to have been physically tampered with and their access to the platform has to be cut without affecting the rest of the deployment. What makes that possible?",
    options: [
      "Blocking at the firewall the IP addresses those tampered devices connect from",
      "Disabling or revoking each affected device's individual identity",
      "Rotating the hub's shared key and redistributing it to the rest of the estate through an update",
      "Changing the platform's endpoint and updating only the devices that are still trusted",
    ],
    correct: 1,
    explain: "This is where the earlier design decision pays off: with an <b>individual identity</b>, revoking means disabling those device registrations and nothing else notices. With a shared key you would have to rotate it and redistribute it to the whole estate — that is option three, and it explains why the common key is a bad idea. IPs change. And moving the endpoint means redoing the whole deployment. <a href=\"https://learn.microsoft.com/en-us/azure/iot/iot-overview-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Global or regional",
    q: "A web application is served from three regions, with failover between them, and needs application-layer filtering at the edge. What do you choose?",
    options: [
      "Application Gateway with WAF in each region, and DNS resolution weighted by client latency",
      "Azure Firewall Premium with TLS inspection in front of the web application servers",
      "Azure Front Door with WAF, which is global and routes to the nearest healthy origin",
      "A network security group per subnet, with rules allowing only ports 80 and 443",
    ],
    correct: 2,
    explain: "Both services carry a WAF and the difference is reach: <b>Front Door</b> is <b>global</b> — it comes in when there are several regions, worldwide latency or failover — and <b>Application Gateway</b> is <b>regional</b>, inside the virtual network, for when traffic must not leave it. Azure Firewall filters network and protocol, not HTTP requests. And a network security group opens ports: it does not look at content. <a href=\"https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/afds-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Bypassing the edge",
    q: "Front Door with WAF is deployed in front of an App Service application. A test shows the attacker reaches the App Service on its public address and bypasses the WAF. What is missing?",
    options: [
      "Locking the origin down so it only accepts traffic from the edge service, by private link or filtering",
      "Turning on prevention mode in the WAF, which until now had been working in detection mode only",
      "Adding Azure DDoS Protection over the virtual network where the web application is published",
      "Broadening the WAF's managed rule set so it also covers the traffic arriving directly",
    ],
    correct: 0,
    explain: "A WAF only protects the traffic that <b>goes through it</b>. If the origin still accepts requests from anyone, the edge is optional for the attacker. What closes the gap is <b>locking the origin down</b>: private link from Front Door, or filtering that only accepts traffic from the edge service. Changing the mode or the rules improves a WAF this path never even crosses. <a href=\"https://learn.microsoft.com/en-us/azure/frontdoor/origin-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "A control at each stage",
    q: "A customer wants to stop privileged containers and containers with known critical vulnerabilities from reaching production. Which TWO controls does the design include?",
    options: [
      "Runtime detection on the nodes, with Defender for Containers alerts",
      "Vulnerability scanning of images in the registry and in the build pipeline",
      "Admission control in the cluster with Azure Policy for Kubernetes, rejecting what is non-compliant",
      "Network policies between pods, so a compromised container cannot reach the others",
    ],
    correct: [1, 2],
    explain: "The stem says <em>\"stop them reaching\"</em>, so both controls are preventive and act at different stages: <b>image scanning</b> finds the vulnerability before it is published, and <b>admission control</b> rejects, in the cluster itself, the manifest asking for privileges. Runtime detection and network policies are good pieces of the design, but they act once the container is already inside. <a href=\"https://learn.microsoft.com/en-us/azure/governance/policy/concepts/policy-for-kubernetes\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Secrets in the container",
    q: "A containerised application needs a database connection string. The team passes it today as an environment variable in the manifest, which lives in the repository. What do you propose?",
    options: [
      "Moving the variable into a Kubernetes secret, which the cluster stores separately from the manifest",
      "Encrypting the manifest in the repository and decrypting it in the pipeline at deployment time",
      "Injecting the variable from the continuous integration system, so it is never written into the repository",
      "Authenticating with a workload identity, with no secret to pass",
    ],
    correct: 3,
    explain: "As on machines: the best outcome is that <b>there is no secret</b>. With a <b>workload identity</b> the pod gets a federated token from Entra ID and reaches the database with no credential stored anywhere. The other three improve <em>where</em> the secret is kept — and a Kubernetes secret is base64-encoded, not encrypted, by default — but the secret still exists. <a href=\"https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Who gets into the cluster",
    q: "In an AKS cluster, developers share a kubeconfig file holding cluster-admin credentials. You want per-person access that is revocable and auditable. What do you design?",
    options: [
      "A kubeconfig per person, generated with their own client certificate and renewed quarterly",
      "Entra ID integration and Azure RBAC for Kubernetes, with roles scoped per namespace",
      "A jump server from which developers run the commands against the cluster",
      "Kubernetes RBAC roles and bindings tied to service accounts in the cluster itself",
    ],
    correct: 1,
    explain: "<b>Entra ID integration</b> makes access to the API server use the person's identity, so MFA, conditional access and PIM apply to it and it is logged; <b>Azure RBAC for Kubernetes</b> additionally lets you assign roles by scope from Azure. Per-person certificates and in-cluster service accounts are credentials outside the directory: no central revocation and no risk signals. <a href=\"https://learn.microsoft.com/en-us/azure/aks/concepts-identity\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Exposing the control plane",
    q: "A production AKS cluster's API server answers on the internet. The team argues it is protected because it requires Entra ID authentication. What do you recommend?",
    options: [
      "Leaving it as is, since requiring Entra ID with MFA is enough to protect the API server",
      "Publishing the API server behind a WAF with managed rules for API calls",
      "A private cluster, or authorized IP ranges if outside access is unavoidable",
      "Rotating the cluster credentials every thirty days and auditing access to the API server",
    ],
    correct: 2,
    explain: "Authentication is necessary but it is not the only layer: a published control plane is still reachable by anyone, and with that comes enumeration and any flaw in the server itself. It is closed with a <b>private cluster</b> — the API server only has an internal endpoint — or, if it must be administered from outside, with <b>authorized IP ranges</b>. A WAF understands application HTTP, not the Kubernetes API. <a href=\"https://learn.microsoft.com/en-us/azure/aks/private-clusters\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Access to the AI service",
    q: "An internal application consumes an Azure OpenAI model using the resource key, kept in the application's configuration. What do you specify in the design?",
    options: [
      "Disabling key authentication and using Entra ID with the application's managed identity",
      "Storing the key in Key Vault and reading it at startup, with rotation every ninety days",
      "Restricting access to the resource by IP address, so the key only works from the application",
      "Rotating the resource key every time somebody on the development team changes project",
    ],
    correct: 0,
    explain: "An AI service is just another Azure resource and the same order of preference applies: <b>managed identity and Entra ID</b> ahead of any key, and disabling local authentication so the key stops being a way in. Key Vault and rotation better guard a secret that can stop existing altogether. IP filtering bounds where from, but the key is still a value that leaks. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/security-features\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The risk specific to AI",
    q: "An internal assistant answers questions by reading documents users upload. The worry is that a document might contain instructions redirecting the model's behaviour. What addresses it?",
    options: [
      "A private endpoint for the AI resource and public access disabled on the service",
      "Customer-managed keys over the storage holding the uploaded documents",
      "A conditional access policy requiring a compliant device to use the assistant",
      "Content filters and prompt shields against direct and indirect injection",
    ],
    correct: 3,
    explain: "What the stem describes is <b>indirect prompt injection</b>: content the model reads ends up directing what it does. No network, encryption or identity measure prevents it, because the attacker needs no access — it is enough that their document gets read. It is addressed with the service's own <b>content filters and prompt shields</b>, and by bounding what the model can do with the identity it is given. <a href=\"https://learn.microsoft.com/en-us/azure/ai-services/content-safety/concepts/jailbreak-detection\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Private endpoint or service endpoint",
    q: "The requirement says a storage account must only be reachable from the application's virtual network. The team proposes a service endpoint. What do you point out?",
    options: [
      "That a service endpoint works, provided a network security group is also opened towards the service",
      "That a service endpoint gives the resource no private address: it needs a private endpoint with public access disabled",
      "That a service endpoint works, because traffic stops going out to the internet and travels over the Azure backbone",
      "That neither meets the requirement and the data has to move to a file server of your own",
    ],
    correct: 1,
    explain: "A <b>service endpoint</b> keeps traffic on the Azure backbone and lets you filter by virtual network, but the resource <em>still has a public address</em>. A <b>private endpoint</b> gives it a <b>private</b> address inside your network and, with public access disabled, it stops being reachable from outside. When the requirement says \"only from the virtual network\", it is a private endpoint. <a href=\"https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Rules that don't age",
    q: "An environment's network security groups carry hundreds of rules with fixed IP addresses, and every deployment forces a review. What change do you propose?",
    options: [
      "Consolidating the rules into a single network security group applied to every subnet in the environment",
      "Replacing the network security groups with Azure Firewall rules centralised in the hub",
      "Application security groups, so the rules speak of roles rather than addresses",
      "Reserving static IP addresses for each workload, so the rules stop changing",
    ],
    correct: 2,
    explain: "<b>Application security groups</b> group interfaces by function — <em>web</em>, <em>app</em>, <em>database</em> — and rules are written between those groups: a new machine inherits its policy by joining the group, with no rule touched. Consolidating into one group hurts readability, the hub firewall does not replace filtering between subnets, and pinning addresses perpetuates the problem. <a href=\"https://learn.microsoft.com/en-us/azure/virtual-network/application-security-groups\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "The policy follows the user",
    q: "With hybrid work, laptop browsing no longer passes through the data centre proxy and web filtering only applies in the office. What do you propose?",
    options: [
      "Microsoft Entra Internet Access, with web filtering and conditional access applied wherever the user is",
      "Backhauling all internet traffic to the data centre over the VPN, so it passes through the proxy again",
      "A local proxy installed on each laptop, with the blocked category list distributed by Intune",
      "Azure Firewall Premium rules on the virtual network, applied to the users' outbound traffic",
    ],
    correct: 0,
    explain: "<b>Entra Internet Access</b> is the secure web gateway in the SSE family: the client forwards browsing to the Microsoft service, where <b>web filtering</b> is applied and — the thing that separates it from a classic proxy — the same <b>conditional access</b> that governs applications, with identity and device state as signals. The policy stops depending on where the traffic goes. Backhauling everything to the office is exactly what you are trying to avoid. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-internet-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Filtering by identity",
    q: "You want to allow one specific group access to a category of sites that is blocked for the rest of the organisation. What makes that possible in the SSE design?",
    options: [
      "An exception by source IP address, applied to the range that group works from",
      "A second traffic forwarding profile, assigned to the devices the people in that group use",
      "A filtering policy assigned per group, since the decision is made on the user's identity",
      "An application rule in Azure Firewall Premium allowing those fully qualified domain names",
    ],
    correct: 2,
    explain: "That the gateway knows <b>who</b> is browsing is the fundamental difference from a network proxy: the policy is assigned per <b>user or group</b> from the directory and travels with the person, regardless of device or network. An exception by IP ties the policy back to a place. And Azure Firewall filters virtual network traffic, not the browsing of a laptop at home. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-internet-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "A stolen token outside the network",
    q: "After a token theft, you want a session token to be useless unless the request arrives through the corporate infrastructure, without relying on IP address lists. What do you use?",
    options: [
      "A named location in conditional access grouping the public ranges of every office",
      "The compliant network condition in conditional access, with the Microsoft traffic profile",
      "Sign-in frequency reduced to one hour for every application in the tenant",
      "Tenant restrictions v2 over the managed devices in the corporate estate",
    ],
    correct: 1,
    explain: "The <b>compliant network</b> condition requires the request to arrive through the Global Secure Access service; the marker cannot be reproduced from outside, so an exfiltrated token is worthless on another network. It is stronger than a <b>named location</b> by IP, which is faked by any egress through the corporate network. Sign-in frequency shortens the window but does not close it, and tenant restrictions solve a different problem. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-compliant-network\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Signing in to another tenant",
    q: "Employees are found uploading corporate documents to other organisations' Microsoft 365 accounts from their company laptops. Which control prevents it?",
    options: [
      "A Purview data loss prevention policy over those machines' network channels",
      "Blocking third-party domains in Entra Internet Access web filtering for the whole organisation",
      "Cross-tenant access settings, restricting which external organisations can invite users",
      "Tenant restrictions v2, which block signing in to other tenants from the corporate device",
    ],
    correct: 3,
    explain: "<b>Tenant restrictions v2</b> do exactly that: from a managed device or network, you can only sign in to the tenants the organisation allows, so the outside account stops being an exit. Cross-tenant access settings govern collaboration <em>into and out of your own tenant</em>, not signing in to somebody else's. And blocking the Microsoft 365 domain would break legitimate use too. <a href=\"https://learn.microsoft.com/en-us/entra/external-id/tenant-restrictions-v2\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Replacing the VPN",
    q: "External vendors reach an internal application over VPN today, and once inside they can reach the whole network. You want to scope it to that one application. What do you propose?",
    options: [
      "Microsoft Entra Private Access, publishing the application with its own conditional access policy",
      "Keeping the VPN and segmenting the internal network so the vendors' range only reaches that application",
      "Publishing the application on the internet with Entra ID authentication and a source IP restriction",
      "A virtual desktop per vendor, from which the internal application is reached inside the network",
    ],
    correct: 0,
    explain: "<b>Entra Private Access</b> grants access <b>to an application</b>, not to a network: a connector installed alongside it opens the connection outbound, nothing is published, and each application is a resource with its own conditional access policy evaluated on every session. Segmenting the VPN shrinks the blast radius but still hands out network and still publishes the concentrator. Publishing the application exposes it to the internet. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "What gets published outward",
    q: "Comparing Entra Private Access with the existing VPN, management asks what specifically improves. Which TWO statements are correct?",
    options: [
      "That it encrypts traffic between client and application, which the current VPN does not always do",
      "That it reduces latency because traffic stops crossing the organisation's infrastructure",
      "That there is no published concentrator: the connector opens the connection outbound from inside",
      "That each application is evaluated with conditional access on every session, not just when the tunnel is built",
    ],
    correct: [2, 3],
    explain: "The two that carry the zero trust argument: <b>nothing is published</b> — the connector initiates the connection from inside out, so there is no exposed concentrator to attack — and the decision is made <b>per application and per session</b> with conditional access, instead of once when the tunnel is established. A VPN also encrypts, and latency depends on the deployment: neither is the security difference. <a href=\"https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["infrastructure"] = QUIZ_DATA;
