// Banco de preguntas del módulo: aplicaciones y datos (SC-100, dominio 4).
// Cada explicación termina en el enlace a la documentación oficial de Microsoft Learn.

var QUIZ_DATA = [
  {
    tag: "Qué mide Secure Score",
    q: "La dirección quiere una métrica única para seguir trimestralmente la mejora de la configuración de Microsoft 365. ¿Qué llevas y qué adviertes?",
    options: [
      "El porcentaje de dispositivos conformes en Intune, que refleja el estado real del parque gestionado",
      "El número de incidentes cerrados en el portal de Defender, que baja según mejora la configuración",
      "Microsoft Secure Score, advirtiendo que mide mejora de configuración y no conformidad con una norma",
      "El secure score de Defender for Cloud, que agrega la postura de todos los recursos de la organización",
    ],
    correct: 2,
    explain: "<b>Microsoft Secure Score</b>, en el portal de Defender, es exactamente eso: la configuración del tenant —identidad, correo, aplicaciones, dispositivos— con acciones priorizadas por impacto y esfuerzo. La advertencia importa porque es la confusión que persigue el examen: mide <em>mejora</em>, no <em>cumplimiento</em>. El de Defender for Cloud mide recursos de nube. Los incidentes cerrados miden operación. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Perseguir el cien por cien",
    q: "El equipo se ha marcado llegar al 100% de Microsoft Secure Score. Algunas acciones exigen deshabilitar funciones que el negocio usa a diario. ¿Qué recomiendas?",
    options: [
      "Aplicar todas las acciones y buscar alternativas de negocio para las funciones que dejen de estar disponibles",
      "Implementar lo que aporte valor real y marcar el resto como riesgo aceptado o resuelto por un tercero",
      "Bajar el objetivo a un porcentaje redondo que el equipo pueda alcanzar sin discutirlo con el negocio",
      "Sustituir el Secure Score por el panel de cumplimiento normativo, que sí tiene un objetivo alcanzable",
    ],
    correct: 1,
    explain: "El Secure Score es una herramienta de <b>priorización</b>, no una nota que haya que sacar. Cada acción se decide contra el riesgo y el impacto en el negocio, y las que no apliquen se marcan como <em>riesgo aceptado</em> o <em>resuelto por un tercero</em>, que es justo para lo que existen esos estados: el número queda por debajo del 100% y la postura es la correcta. Perseguir el 100% rompiendo el negocio es el error de bulto. <a href=\"https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Correo o SaaS",
    q: "Una campaña de phishing con enlaces que se activan después de la entrega está superando los controles actuales de correo. ¿Qué capacidad lo aborda?",
    options: [
      "Safe Links de Defender for Office 365, que reescribe y comprueba el destino en el momento del clic",
      "Una política de sesión de Defender for Cloud Apps sobre el acceso web al buzón de los usuarios",
      "Una regla de flujo de correo que ponga en cuarentena todo mensaje externo que contenga un enlace",
      "Formación con simulaciones de phishing dirigidas a los departamentos con más incidencias registradas",
    ],
    correct: 0,
    explain: "El detalle del enunciado es «se activan <em>después</em> de la entrega»: el enlace era inocuo cuando pasó el filtro. <b>Safe Links</b> lo reescribe y vuelve a comprobar el destino <b>en el momento del clic</b>, que es cuando el ataque existe. La cuarentena masiva de todo enlace externo rompe el correo. La formación reduce la tasa pero no comprueba destinos. Y Cloud Apps gobierna aplicaciones SaaS, no la entrega del correo. <a href=\"https://learn.microsoft.com/en-us/defender-office-365/safe-links-about\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Aplicaciones que nadie aprobó",
    q: "Seguridad sospecha que los equipos suben información a servicios de almacenamiento en la nube que nadie ha aprobado, y quiere primero saber cuáles y con qué volumen. ¿Por dónde se empieza?",
    options: [
      "Bloqueando por categoría todos los servicios de almacenamiento en la nube en el filtrado web corporativo",
      "Una política de prevención de pérdida de datos en el endpoint que impida copiar a servicios web",
      "Una encuesta a los responsables de cada equipo sobre las herramientas que utilizan en su día a día",
      "El descubrimiento de aplicaciones en la nube de Defender for Cloud Apps, sobre los registros de tráfico",
    ],
    correct: 3,
    explain: "Antes de decidir hay que <b>medir</b>, y el enunciado pide justo eso: cuáles y con qué volumen. El <b>descubrimiento de aplicaciones</b> de Defender for Cloud Apps analiza los registros de tráfico, identifica los servicios usados, los puntúa por riesgo y muestra volumen y usuarios, y de ahí sale qué se sanciona y qué se bloquea. Bloquear por categoría sin medir corta también lo legítimo, y la encuesta no ve lo que nadie declara. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La señal que engancha con el dato",
    q: "El requisito dice que solo se pueda abrir documentación interna de SharePoint desde equipos corporativos con cifrado de disco. ¿Qué cadena de piezas lo implementa?",
    options: [
      "Una directiva de retención de Purview sobre los sitios, combinada con permisos por grupo de seguridad",
      "Directiva de cumplimiento en Intune y acceso condicional que exija dispositivo conforme",
      "Una etiqueta de confidencialidad con cifrado aplicada a todos los documentos de esos sitios",
      "Una política de prevención de pérdida de datos que impida descargar desde equipos no gestionados",
    ],
    correct: 1,
    explain: "Son dos piezas encajadas y en este orden: <b>Intune</b> evalúa el cifrado de disco con una directiva de cumplimiento y marca el dispositivo como conforme, y el <b>acceso condicional</b> exige esa señal para la aplicación de SharePoint. La etiqueta protege el fichero pero no condiciona por dispositivo, la DLP vigila la salida del dato y la retención decide cuánto se guarda: ninguna de las tres mira el estado del equipo. <a href=\"https://learn.microsoft.com/en-us/intune/intune-service/protect/device-compliance-get-started\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Sin gestionar el dispositivo",
    q: "Una empresa colaboradora accede a Teams con sus propios portátiles, que la organización no puede administrar. Se quiere impedir que descarguen ficheros de los canales compartidos. ¿Qué se diseña?",
    options: [
      "Exigir en el acceso condicional que el dispositivo esté unido a Entra ID y marcado como conforme",
      "Inscribir esos portátiles en Intune con un perfil restringido solo para el uso de Teams",
      "Control de aplicaciones de acceso condicional con una política de sesión que bloquee la descarga",
      "Retirar el acceso a los canales compartidos y publicar los ficheros en un portal externo propio",
    ],
    correct: 2,
    explain: "«No podemos administrar el dispositivo» descarta exigir cumplimiento y descarta inscribirlo. El <b>control de aplicaciones de acceso condicional</b> pone la sesión en proxy inverso y aplica una <b>política de sesión</b> que permite ver y editar en línea pero bloquea la descarga: el dato no llega al equipo no gestionado. Montar un portal aparte resuelve, pero es rehacer la colaboración para un control que ya existe. <a href=\"https://learn.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Que la protección viaje",
    q: "Un contrato se envía por correo a un destinatario externo y la preocupación es que lo reenvíe a terceros. ¿Qué capacidad de Purview lo cubre?",
    options: [
      "Una etiqueta de confidencialidad con cifrado y derechos de uso que restrinjan el reenvío",
      "Una política de prevención de pérdida de datos que bloquee el envío del contrato al exterior",
      "Una directiva de retención de siete años sobre el buzón desde el que se envía el contrato",
      "Barreras de información entre el departamento que redacta el contrato y el resto de la organización",
    ],
    correct: 0,
    explain: "La restricción es sobre lo que pasa <em>después de que el fichero haya salido</em>, y eso solo lo cubre una <b>etiqueta de confidencialidad con cifrado</b>: los derechos de uso viajan dentro del propio fichero y se evalúan al abrirlo, esté donde esté. La <b>DLP</b> impediría el envío, que no es lo que se pide —el envío es legítimo—. Retención y barreras de información responden a otras preguntas. <a href=\"https://learn.microsoft.com/en-us/purview/sensitivity-labels\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dónde está el dato regulado",
    q: "Una norma obliga a saber en qué sitios de SharePoint hay números de tarjeta de pago y a impedir que salgan por correo. ¿Qué DOS capacidades de Purview cubren el requisito?",
    options: [
      "Los tipos de información confidencial, para descubrir y clasificar el dato allá donde esté",
      "Las barreras de información entre los equipos que trabajan con datos de pago y el resto",
      "La gestión de riesgo interno, para puntuar el comportamiento de quien maneja esos datos",
      "Una política de prevención de pérdida de datos con el canal de correo en modo bloqueo",
    ],
    correct: [0, 3],
    explain: "Dos verbos, dos capacidades: <b>saber dónde está</b> lo resuelven los <b>tipos de información confidencial</b>, que reconocen el patrón de tarjeta con su validación, y <b>que no salga</b> lo resuelve la <b>DLP</b> sobre el canal de correo. El riesgo interno mide comportamiento y las barreras separan comunicaciones: ninguna descubre el dato ni bloquea el canal. <a href=\"https://learn.microsoft.com/en-us/purview/sensitive-information-type-learn-about\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Copilot enseña de más",
    q: "Al pilotar Copilot para Microsoft 365, varios usuarios reciben resúmenes de documentos de otros departamentos. ¿Cuál es la causa y qué se hace?",
    options: [
      "Copilot indexa el tenant completo con permisos elevados; hay que restringir su ámbito a sitios concretos",
      "Copilot respeta los permisos: aflora sobrecompartido que hay que corregir en el origen",
      "El modelo ha memorizado contenido del tenant; hay que solicitar el reentrenamiento del modelo base",
      "Falta una política de acceso condicional específica para Copilot que limite qué usuarios pueden usarlo",
    ],
    correct: 1,
    explain: "Copilot <b>no crea acceso</b>: responde con lo que el usuario ya podía abrir. Que aparezcan documentos de otro departamento significa que ese usuario <em>ya</em> tenía permiso y nadie lo había notado. Se corrige en el origen —revisar sitios y enlaces «cualquiera», retirar el sobrecompartido, etiquetar—, no acotando el asistente. Y el dato del tenant no entrena los modelos base, así que no hay nada memorizado que reentrenar. <a href=\"https://learn.microsoft.com/en-us/copilot/microsoft-365/microsoft-365-copilot-privacy\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Auditar lo que se preguntó",
    q: "Cumplimiento pregunta si es posible saber qué preguntó un empleado concreto a Copilot y qué se le respondió, para una investigación interna. ¿Qué respondes?",
    options: [
      "Que no queda registro de las conversaciones, porque se procesan sin almacenarse en el tenant",
      "Que solo queda el recuento de interacciones por usuario, sin el contenido de la conversación",
      "Que las interacciones se registran en Purview Audit y admiten retención y eDiscovery",
      "Que hay que activar antes un registro de diagnóstico específico, sin efecto retroactivo",
    ],
    correct: 2,
    explain: "Las interacciones con Copilot son actividad del usuario en Microsoft 365 y quedan en <b>Purview Audit</b>, con lo que se pueden buscar, someter a <b>retención</b> y recoger en <b>eDiscovery</b> como cualquier otro contenido. Es justo el punto que el examen quiere que sepas afirmar: el asistente no es un agujero en el gobierno del dato, entra en las mismas herramientas. <a href=\"https://learn.microsoft.com/en-us/purview/audit-solutions-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Por dónde se empieza un portafolio",
    q: "Una organización con unas doscientas aplicaciones internas quiere mejorar su seguridad y pide por dónde empezar. ¿Qué propones?",
    options: [
      "Una prueba de intrusión sobre cada una de las aplicaciones, empezando por las más antiguas del catálogo",
      "Análisis estático del código de todos los repositorios, priorizando después por número de hallazgos",
      "Un WAF delante de todas ellas, para reducir el riesgo mientras se planifica el trabajo de fondo",
      "Inventariar y clasificar por criticidad y dato tratado, y priorizar el esfuerzo con ese criterio",
    ],
    correct: 3,
    explain: "Con doscientas aplicaciones el problema no es técnico, es de <b>asignación de esfuerzo</b>: sin saber cuáles son críticas y qué dato tocan, cualquier orden es arbitrario. Primero el <b>inventario y la clasificación</b>, y de ahí sale dónde valen la pena las pruebas de intrusión y el análisis. Poner un WAF a todo es un parche uniforme sobre riesgos que no son uniformes, y ordenar por número de hallazgos confunde ruido con riesgo. <a href=\"https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Lo que se usa sin registrar",
    q: "El inventario de aplicaciones lo mantiene el equipo de arquitectura a mano, y se sospecha que faltan tanto aplicaciones SaaS como APIs publicadas. ¿Qué añades al diseño?",
    options: [
      "Descubrimiento de Defender for Cloud Apps para el SaaS y Defender for APIs para lo publicado",
      "Un proceso de alta obligatoria en el que cada equipo declare sus aplicaciones cada trimestre",
      "Una regla de Azure Policy que impida desplegar recursos sin la etiqueta de aplicación correspondiente",
      "Un análisis de puertos periódico sobre los rangos de direcciones públicas de la organización",
    ],
    correct: 0,
    explain: "Un inventario mantenido a mano falla justo en lo que no se declara. Se completa con <b>descubrimiento automático</b> por cada superficie: <b>Defender for Cloud Apps</b> ve el SaaS que se usa de verdad a partir del tráfico, y <b>Defender for APIs</b> inventaría lo publicado en API Management. La declaración trimestral repite el problema, la etiqueta solo cubre lo desplegado en Azure y el análisis de puertos ve servicios, no aplicaciones. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cuándo se modela",
    q: "El equipo propone hacer el modelado de amenazas de una aplicación crítica justo antes de pasarla a producción, cuando ya está todo construido. ¿Qué señalas?",
    options: [
      "Que es el momento adecuado, porque solo entonces se conoce la implementación real y sus dependencias",
      "Que da igual el momento mientras se repita en cada versión mayor de la aplicación",
      "Que es una actividad de diseño: se hace sobre el diagrama y produce requisitos antes de construir",
      "Que puede sustituirse por una prueba de intrusión, que encuentra los mismos problemas ya construidos",
    ],
    correct: 2,
    explain: "El modelado es una <b>actividad de diseño</b>: se hace sobre el diagrama de flujo de datos y su salida son <em>requisitos de seguridad</em> que condicionan cómo se construye. Hacerlo al final convierte cada hallazgo en un rediseño caro. Y no lo sustituye una prueba de intrusión: esta encuentra defectos de implementación, no decisiones de arquitectura que ya no se pueden cambiar. <a href=\"https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Clasificar la amenaza",
    q: "En el modelado de una API aparece que un cliente autenticado podría llamar a un método reservado a administradores manipulando un parámetro. ¿Qué categoría de STRIDE es y qué la mitiga?",
    options: [
      "Tampering; se mitiga firmando la petición y comprobando su integridad en el servidor",
      "Elevación de privilegio; se mitiga con autorización en el servidor y validación de la entrada",
      "Divulgación de información; se mitiga cifrando la respuesta que devuelve ese método",
      "Suplantación; se mitiga exigiendo autenticación multifactor para llamar a la API",
    ],
    correct: 1,
    explain: "El cliente <em>ya está autenticado</em> y consigue hacer algo que su rol no permite: eso es <b>elevación de privilegio</b>, y se cierra comprobando la <b>autorización en el servidor</b> —nunca confiando en lo que manda el cliente— y validando la entrada. <em>Tampering</em> rompe la integridad del dato, la divulgación expone información que ya se podía leer, y la suplantación es hacerse pasar por otro: aquí no hace falta, la identidad es real. <a href=\"https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dónde colocar el control",
    q: "Se quiere impedir que lleguen a producción credenciales incrustadas en el código. ¿Dónde se coloca el control para que sea más efectivo?",
    options: [
      "En el IDE y en la pull request, para que el secreto no llegue a fusionarse en la rama principal",
      "En un análisis semanal del repositorio, con un aviso al autor de cada hallazgo detectado",
      "En tiempo de ejecución, con una alerta cuando la aplicación use una credencial no esperada",
      "En una revisión manual de código antes de cada despliegue a producción, hecha por el equipo de seguridad",
    ],
    correct: 0,
    explain: "Cuanto <b>más temprano</b> actúa el control, más barato es el arreglo y menos superficie queda: un secreto detectado en el IDE se corrige antes de existir en la historia del repositorio, y uno detectado en la <b>pull request</b> no llega a la rama principal. El análisis semanal y la revisión manual llegan cuando el secreto ya está escrito, y en un repositorio un secreto fusionado hay que darlo por comprometido y rotarlo. <a href=\"https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-secret-scanning\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Dependencias vulnerables",
    q: "Un análisis revela que muchas aplicaciones arrastran versiones antiguas de bibliotecas con vulnerabilidades conocidas. ¿Qué añade la estrategia de ciclo de vida?",
    options: [
      "Un WAF con reglas específicas para las vulnerabilidades detectadas en cada una de esas bibliotecas",
      "Prohibir por política el uso de bibliotecas de terceros en las aplicaciones críticas del portafolio",
      "Un inventario anual de dependencias, revisado por el equipo de arquitectura junto con los propietarios",
      "Análisis de composición en el pipeline, con actualización automatizada de las dependencias vulnerables",
    ],
    correct: 3,
    explain: "Las dependencias cambian a diario, así que el control tiene que estar donde se construye y ser continuo: <b>análisis de composición</b> en el pipeline que detecte la versión vulnerable y <b>actualización automatizada</b> que abra la corrección sola. El WAF mitiga algunas explotaciones pero no arregla la biblioteca. Prohibir terceros no es realista. Y un inventario anual va muy por detrás del ritmo de publicación de vulnerabilidades. <a href=\"https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-dependency-scanning\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La credencial del pipeline",
    q: "El pipeline de despliegue se autentica en Azure con el secreto de un registro de aplicación, guardado como variable secreta del sistema de integración continua. ¿Qué propones?",
    options: [
      "Mover el secreto a Key Vault y que el pipeline lo lea al arrancar, con rotación cada noventa días",
      "Federación de identidad de carga de trabajo, para que no haya secreto que guardar ni rotar",
      "Un certificado en lugar del secreto, con una caducidad larga para no interrumpir los despliegues",
      "Restringir por dirección IP el uso de ese registro de aplicación a los agentes de compilación",
    ],
    correct: 1,
    explain: "El patrón que el examen quiere ver sustituido es exactamente ese. Con <b>federación de identidad de carga de trabajo</b>, el pipeline presenta un token firmado por su propio proveedor y Entra ID lo cambia por acceso: <b>no hay secreto</b> que guardar, rotar ni robar. Leerlo de Key Vault sigue exigiendo una credencial para llegar a Key Vault. El certificado es otro secreto. Y el filtrado por IP no evita que la credencial se use desde donde toca. <a href=\"https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Proteger la cadena",
    q: "Se quiere impedir que un cambio llegue a producción sin revisión, incluso si quien lo hace tiene permisos de escritura en el repositorio. ¿Qué se especifica?",
    options: [
      "Retirar los permisos de escritura a todo el equipo salvo a los responsables técnicos de cada aplicación",
      "Una alerta al equipo de seguridad cada vez que se registra un cambio directo en la rama principal",
      "Ramas protegidas con revisión obligatoria y entornos de producción con aprobación previa",
      "Un análisis de seguridad obligatorio en el pipeline que falle si detecta cualquier hallazgo nuevo",
    ],
    correct: 2,
    explain: "Se resuelve en la plataforma, no quitando permisos ni vigilando después: <b>ramas protegidas</b> que impiden empujar directo y exigen aprobación en la pull request, y <b>entornos con aprobación</b> que detienen el despliegue a producción hasta que alguien lo autoriza. La alerta avisa cuando ya ocurrió, retirar permisos rompe el trabajo diario, y el análisis mira el contenido del cambio, no quién lo aprobó. <a href=\"https://learn.microsoft.com/en-us/azure/devops/pipelines/process/approvals\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Identidades de cliente",
    q: "Una aplicación nueva la usarán clientes finales que se registran por su cuenta, con inicio de sesión social y recuperación de contraseña. ¿Qué se especifica?",
    options: [
      "Microsoft Entra External ID, que gestiona identidades de cliente con registro y proveedores sociales",
      "Invitaciones B2B al tenant corporativo, una por cada cliente que se registre en la aplicación",
      "Usuarios creados en el tenant corporativo mediante un proceso automatizado de alta desde la aplicación",
      "Autenticación propia de la aplicación, con las contraseñas guardadas con hash y sal en su base de datos",
    ],
    correct: 0,
    explain: "Identidades de <b>cliente o consumidor</b> son un caso propio y tienen su producto: <b>Entra External ID</b>, con autoregistro, proveedores sociales, flujos personalizables y separación del directorio corporativo. B2B está pensado para socios, no para consumidores masivos. Meter clientes en el tenant corporativo mezcla dos poblaciones con políticas distintas. Y escribir la autenticación a mano es reintroducir un problema resuelto. <a href=\"https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Alcanzar la base sin salir",
    q: "Una aplicación en App Service accede a una base de datos de Azure SQL y el requisito dice que ese tráfico no debe atravesar internet en ningún momento. ¿Qué se especifica?",
    options: [
      "Reglas de cortafuegos en el servidor SQL que solo permitan las direcciones de salida del App Service",
      "Un endpoint de servicio en la subred del App Service hacia el servicio de Azure SQL",
      "Integración con la red virtual en el App Service y endpoint privado en el servidor SQL",
      "Una cadena de conexión que fuerce TLS 1.2 y verificación del certificado del servidor",
    ],
    correct: 2,
    explain: "Para que el tráfico <b>no salga</b>, hacen falta las dos mitades: la <b>integración con la red virtual</b> mete la salida del App Service en tu red, y el <b>endpoint privado</b> le da a SQL una dirección privada dentro de ella. Las reglas de cortafuegos filtran pero el tráfico sigue yendo por la dirección pública. El endpoint de servicio lo mantiene en la red troncal de Azure, pero no da dirección privada. Y TLS cifra el camino, no lo cambia. <a href=\"https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Sin secreto para la aplicación",
    q: "Una función de Azure lee de una cuenta de almacenamiento y escribe en Cosmos DB. Hoy usa las claves de ambos servicios en su configuración. ¿Qué especificas?",
    options: [
      "Mover las dos claves a Key Vault y referenciarlas desde la configuración de la función",
      "Una identidad administrada para la función, con roles de datos sobre cada servicio",
      "Rotar las dos claves mediante una automatización mensual que actualice la configuración de la función",
      "Un registro de aplicación con certificado, compartido por todas las funciones de la suscripción",
    ],
    correct: 1,
    explain: "El orden de preferencia del examen no cambia: <b>identidad administrada</b> por delante de cualquier secreto. La función se autentica como ella misma contra Entra ID y recibe roles de datos acotados a cada servicio: no hay clave que guardar, rotar ni filtrar. Key Vault mejora la custodia de un secreto que puede dejar de existir, y una identidad compartida entre funciones rompe el mínimo privilegio y la trazabilidad. <a href=\"https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Gobernar lo que no es una persona",
    q: "Una auditoría señala que hay decenas de registros de aplicación con permisos amplios, sin propietario claro y sin saber si se siguen usando. ¿Qué se añade al diseño?",
    options: [
      "Caducar todos los secretos a treinta días para que las aplicaciones sin uso dejen de funcionar solas",
      "Una etiqueta obligatoria con el nombre del equipo responsable en cada registro de aplicación",
      "Una alerta cada vez que un registro de aplicación solicite un permiso nuevo al directorio",
      "Gobierno de identidades de carga de trabajo: propietario, access reviews y acceso condicional",
    ],
    correct: 3,
    explain: "Las identidades de carga de trabajo se gobiernan igual que las de personas: <b>propietario</b> asignado, <b>access reviews</b> que recertifiquen si siguen haciendo falta y qué permisos conservan, y <b>acceso condicional</b> para acotar desde dónde se usan. Caducar todos los secretos a treinta días provoca una caída en cadena. La etiqueta documenta pero no recertifica. Y la alerta cubre lo nuevo, no las decenas que ya están. <a href=\"https://learn.microsoft.com/en-us/entra/id-governance/identity-governance-applications-prepare\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Una API sin puerta",
    q: "Cada equipo publica sus APIs directamente desde su App Service, con la autenticación resuelta de forma distinta en cada una. ¿Qué propones?",
    options: [
      "Documentar el estándar de autenticación y revisar en cada pull request que cada API lo implemente",
      "Un WAF delante de cada App Service, con el conjunto de reglas gestionado para APIs activado",
      "Publicar todo a través de API Management, con validación del token en la puerta y backend privado",
      "Una prueba de intrusión periódica sobre cada API publicada, priorizada por criticidad del servicio",
    ],
    correct: 2,
    explain: "El problema es que <em>cada API resuelve lo mismo a su manera</em>, y eso se corrige centralizando el control en una puerta: <b>API Management</b> valida el token de Entra ID, aplica limitación de tasa y cuota, transforma la respuesta y deja el <b>backend en red privada</b>, solo alcanzable desde ella. El estándar documentado depende de que cada equipo lo implemente bien, y el WAF filtra peticiones pero no unifica la autorización. <a href=\"https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Abuso de una API pública",
    q: "Una API pública de consulta está siendo raspada de forma masiva por un cliente autenticado, que agota la capacidad del backend. ¿Qué control lo aborda?",
    options: [
      "Políticas de limitación de tasa y cuota por suscriptor en API Management",
      "Revocar el acceso de ese cliente y bloquear en el cortafuegos sus direcciones de origen",
      "Escalar el backend automáticamente para absorber el volumen que genera ese cliente",
      "Un WAF con reglas gestionadas delante de la API, en modo de prevención",
    ],
    correct: 0,
    explain: "El cliente está <b>autenticado y autorizado</b>: no es un ataque que un WAF reconozca ni un origen que bloquear tenga sentido, es <em>uso abusivo del derecho que tiene</em>. Se acota con <b>limitación de tasa y cuota por suscriptor</b> en la puerta de enlace, que es donde se conoce quién llama. Escalar el backend paga el abuso. Y revocarlo corta un caso concreto sin evitar el siguiente. <a href=\"https://learn.microsoft.com/en-us/azure/api-management/api-management-sample-flexible-throttling\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Desplegar el WAF sin romper",
    q: "Se va a poner un WAF delante de una aplicación en producción con mucho tráfico y comportamiento poco documentado. ¿Cómo se despliega?",
    options: [
      "En modo prevención con el conjunto de reglas gestionado, revirtiendo si aparecen incidencias de usuarios",
      "En modo detección para medir los falsos positivos, afinar con exclusiones y pasar después a prevención",
      "En modo prevención pero solo con las reglas críticas, añadiendo el resto cuando se estabilice",
      "En modo detección de forma permanente, para no arriesgar nunca a bloquear tráfico legítimo",
    ],
    correct: 1,
    explain: "Es el mismo patrón de <em>medir, ajustar, exigir</em> que en Azure Policy. El <b>modo detección</b> registra lo que bloquearía sin bloquearlo, y sobre esos registros se identifican los falsos positivos y se escriben las <b>exclusiones</b> y reglas personalizadas; solo entonces se pasa a <b>prevención</b>. Empezar en prevención rompe producción, y quedarse en detección para siempre es tener un WAF que no protege. <a href=\"https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-tuning\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El WAF que se rodea",
    q: "Con el WAF ya en prevención sobre Application Gateway, una prueba demuestra que las peticiones que llegan directamente a las máquinas del backend no pasan por él. ¿Qué falta?",
    options: [
      "Ampliar el conjunto de reglas gestionado para que cubra también ese tipo de peticiones directas",
      "Activar el registro del WAF y enviar sus eventos a Sentinel para detectar el tráfico que lo rodea",
      "Poner un segundo WAF, esta vez en Front Door, delante del Application Gateway existente",
      "Que las máquinas del backend solo acepten tráfico de la subred del Application Gateway",
    ],
    correct: 3,
    explain: "Un WAF solo ve el tráfico que <b>lo atraviesa</b>. Si el backend acepta peticiones de cualquier origen, pasar por el WAF es opcional para el atacante. Se cierra en la red: <b>grupo de seguridad</b> que solo permita la subred del Application Gateway, y sin dirección pública en las máquinas. Más reglas o un segundo WAF no sirven en un camino que no los cruza, y el registro detecta después de que pase. <a href=\"https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Antes de proteger, saber",
    q: "Una organización quiere aplicar controles al dato personal que guarda, pero está repartido entre Azure Storage, bases de datos SQL y un servidor de ficheros propio. ¿Por dónde se empieza?",
    options: [
      "Aplicando cifrado con clave del cliente en los tres orígenes, para partir de una base común",
      "Migrando los tres orígenes a un único almacén sobre el que aplicar un conjunto de controles",
      "Analizando y clasificando los tres orígenes con Microsoft Purview, para saber qué hay y dónde",
      "Definiendo una directiva de retención común y aplicándola a los tres orígenes de datos",
    ],
    correct: 2,
    explain: "No se puede proteger lo que no se sabe que existe ni dónde está: el primer paso es siempre <b>descubrir y clasificar</b>. El <b>mapa de datos</b> de Purview analiza orígenes en Azure, en otras nubes y on-premises, y la clasificación reconoce el dato personal con tipos de información confidencial. El cifrado y la retención son controles que <em>se deciden después</em>, y migrarlo todo es un proyecto que no responde a la pregunta. <a href=\"https://learn.microsoft.com/en-us/purview/data-map-classification\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Precisión en la clasificación",
    q: "La clasificación marca como número de cliente muchas cadenas que no lo son, y el equipo de datos ya sufre el ruido. Existe una lista maestra de esos números. ¿Qué se usa?",
    options: [
      "Coincidencia exacta de datos, contrastando contra la lista maestra en vez de contra un patrón",
      "Un clasificador entrenable, alimentado con documentos de ejemplo que contengan esos números",
      "Un tipo de información confidencial personalizado con una expresión regular más estricta",
      "Bajar el nivel de confianza exigido para que solo se marquen las coincidencias más claras",
    ],
    correct: 0,
    explain: "Cuando existe la <b>lista real de valores</b>, la respuesta es <b>coincidencia exacta de datos</b>: se contrasta contra un índice de esos valores concretos, no contra un patrón, y los falsos positivos caen prácticamente a cero. Una expresión regular más estricta sigue siendo un patrón. El clasificador entrenable reconoce <em>tipos de documento</em>, no valores. Y bajar el umbral cambia el equilibrio, no la precisión. <a href=\"https://learn.microsoft.com/en-us/purview/sit-learn-about-exact-data-match-based-sits\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Por dónde empezar la mitigación",
    q: "Defender for Cloud devuelve cientos de recomendaciones sobre almacenamiento y bases de datos. ¿Con qué criterio se ordena el trabajo?",
    options: [
      "Por severidad de la recomendación, empezando por todas las críticas de cualquier recurso",
      "Por recursos con dato sensible y expuesto, cruzando clasificación con quién puede alcanzarlos",
      "Por antigüedad de la recomendación, para que ninguna se quede abierta indefinidamente",
      "Por equipo propietario, repartiendo el total en partes iguales para que todos avancen a la vez",
    ],
    correct: 1,
    explain: "La priorización de este dominio sale de cruzar dos ejes: <b>sensibilidad</b> —lo que dice la clasificación— y <b>exposición</b> —quién puede llegar—. Un almacén con dato regulado accesible públicamente va antes que una crítica sobre un recurso de pruebas vacío. Defender for Cloud lo apoya con el descubrimiento de dato sensible y las rutas de ataque que terminan en él. Severidad, antigüedad y reparto ordenan la lista, no el riesgo. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/data-security-posture-prepare\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "La amenaza sobre el dato",
    q: "Un análisis de riesgo del dato de una aplicación identifica cuatro escenarios. ¿Cuál se mitiga con copias de seguridad inmutables y no con controles de acceso?",
    options: [
      "Que un empleado con permiso de lectura descargue el conjunto completo de la base de datos",
      "Que una credencial filtrada permita a un tercero consultar el dato desde fuera de la organización",
      "Que un desarrollador acceda al dato de producción desde un entorno de pruebas mal aislado",
      "Que un atacante cifre o borre el dato y exija un pago para devolverlo",
    ],
    correct: 3,
    explain: "Los tres primeros son problemas de <b>confidencialidad</b> y se atacan con acceso, red y clasificación. El cuarto es de <b>disponibilidad e integridad</b>: contra ransomware, ningún control de acceso te devuelve el dato una vez cifrado. Lo que lo mitiga es una copia que el atacante no pueda alterar —<b>inmutabilidad</b>, retención bloqueada, separación de credenciales de la copia— y haberla probado restaurando. <a href=\"https://learn.microsoft.com/en-us/azure/storage/blobs/immutable-storage-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Los tres estados del dato",
    q: "Un requisito dice que ni el proveedor de nube debe poder acceder al dato mientras la aplicación lo procesa en memoria. ¿Qué lo cubre?",
    options: [
      "Claves gestionadas por el cliente en Key Vault, con rotación y registro de cada uso de la clave",
      "Cifrado de infraestructura, que añade una segunda capa de cifrado bajo la del servicio",
      "Computación confidencial, donde el dato solo se descifra dentro de un enclave del procesador",
      "Cifrado del disco de la máquina virtual con una clave custodiada en Key Vault Managed HSM",
    ],
    correct: 2,
    explain: "El examen distingue tres estados y este es el tercero, el que se olvida: <b>en uso</b>. Ninguna clave gestionada por el cliente lo cubre, porque el dato tiene que descifrarse para procesarse. La <b>computación confidencial</b> lo descifra solo dentro de un <b>enclave</b> aislado por hardware, fuera del alcance del hipervisor y del operador. Las otras tres opciones protegen el reposo, que aquí ya estaba resuelto. <a href=\"https://learn.microsoft.com/en-us/azure/confidential-computing/overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Poder revocar la clave",
    q: "Una norma exige que la organización pueda hacer el dato ilegible de forma inmediata y sin depender del proveedor. ¿Qué se especifica?",
    options: [
      "Claves gestionadas por el cliente, revocando el acceso del servicio a la clave",
      "Borrado temporal y control de versiones en el almacenamiento donde reside el dato",
      "Cifrado de infraestructura sobre el dato en reposo, además del cifrado del servicio",
      "Una directiva de retención que permita eliminar el contenido cuando se solicite",
    ],
    correct: 0,
    explain: "Poder <b>revocar</b> es lo que separa la clave del cliente de la de la plataforma: si la clave vive en tu <b>Key Vault</b> y le retiras el acceso al servicio, el dato deja de poder descifrarse al instante y sin intervención del proveedor. El cifrado de infraestructura añade una capa pero sigue siendo con clave de la plataforma. El borrado temporal y la retención hablan de conservar y eliminar, no de hacer ilegible. <a href=\"https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El corpus que lee la IA",
    q: "Un asistente interno responde consultando documentos de SharePoint. Preocupa que acabe exponiendo información a quien no debería verla. ¿Qué se hace primero?",
    options: [
      "Limitar el asistente a un conjunto reducido de sitios elegidos a mano por el equipo de plataforma",
      "Registrar todas las respuestas del asistente para revisar a posteriori las que expongan dato sensible",
      "Cifrar con clave del cliente el almacenamiento donde residen los documentos que consulta el asistente",
      "Clasificar y etiquetar el corpus, y corregir el sobrecompartido de los sitios que consulta",
    ],
    correct: 3,
    explain: "Un asistente hereda los permisos del origen: si el origen está sobrecompartido, el asistente <b>reparte ese sobrecompartido más deprisa</b>. El trabajo es sobre el dato —<b>clasificar, etiquetar y corregir permisos</b>—, no sobre el asistente. Acotarlo a mano no escala y deja el problema intacto para el resto. El registro detecta después. Y el cifrado en reposo no cambia quién tiene permiso de lectura. <a href=\"https://learn.microsoft.com/en-us/purview/ai-microsoft-purview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "El dato que sale en el prompt",
    q: "Al revisar el diseño de una aplicación con IA generativa, ves que la DLP cubre correo, Teams y endpoint, pero nadie ha mirado qué mandan los usuarios en las peticiones al modelo. ¿Qué señalas?",
    options: [
      "Que no aplica, porque la petición viaja cifrada con TLS hasta el servicio de IA de la organización",
      "Que es un canal de salida más y debe entrar en el alcance de la clasificación y de la DLP",
      "Que basta con la retención de las conversaciones, que permite revisarlas si surge una incidencia",
      "Que se resuelve con un aviso legal en la interfaz recordando al usuario qué no debe escribir",
    ],
    correct: 1,
    explain: "El <em>prompt</em> es dato que <b>sale de la organización hacia un servicio</b>, exactamente igual que un adjunto de correo, y por eso tiene que estar en el alcance de la clasificación y la <b>DLP</b>. Que viaje cifrado protege el transporte, no decide qué se manda. La retención permite mirarlo después, cuando ya salió. Y el aviso legal traslada la responsabilidad al usuario sin implementar ningún control. <a href=\"https://learn.microsoft.com/en-us/purview/dlp-learn-about-dlp\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Que el administrador no lo vea",
    q: "Una columna con números de identificación no debe ser legible ni siquiera para los administradores de la base de datos de Azure SQL. ¿Qué se especifica?",
    options: [
      "Enmascaramiento dinámico de datos sobre esa columna, con permiso de desenmascarado restringido",
      "Cifrado transparente con una clave gestionada por el cliente y custodiada en Key Vault",
      "Always Encrypted, que cifra en el cliente de modo que el motor nunca ve el valor en claro",
      "Seguridad a nivel de fila que impida a los administradores consultar las filas con esa columna",
    ],
    correct: 2,
    explain: "El <b>enmascaramiento dinámico</b> oculta el valor en la respuesta, pero el dato sigue en claro en la base y quien tenga permiso lo ve. El <b>cifrado transparente</b> protege los ficheros en reposo, no la consulta. Lo único que deja el valor ilegible <em>para el propio motor y sus administradores</em> es <b>Always Encrypted</b>: el cifrado y descifrado ocurren en el cliente, con una clave a la que la base no tiene acceso. <a href=\"https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Cada quien ve lo suyo",
    q: "Una tabla de Azure SQL contiene datos de todas las delegaciones y cada gestor solo debe consultar los de la suya, sin duplicar la tabla ni cambiar la aplicación. ¿Qué se usa?",
    options: [
      "Seguridad a nivel de fila, con un predicado que filtre según la identidad que ejecuta la consulta",
      "Una vista por delegación, con permisos concedidos al grupo de gestores de cada una de ellas",
      "Enmascaramiento dinámico sobre la columna de delegación para los usuarios no autorizados",
      "Etiquetas de confidencialidad de Purview aplicadas a las filas de cada una de las delegaciones",
    ],
    correct: 0,
    explain: "La <b>seguridad a nivel de fila</b> hace exactamente eso: un predicado en el motor filtra las filas según quién ejecuta la consulta, de forma transparente para la aplicación, que sigue consultando la misma tabla. Una vista por delegación funciona pero obliga a mantener tantas vistas como delegaciones y a cambiar la consulta. El enmascaramiento oculta columnas, no filas. Y las etiquetas clasifican, no filtran. <a href=\"https://learn.microsoft.com/en-us/sql/relational-databases/security/row-level-security\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Acceso delegado revocable",
    q: "Un proveedor necesita subir ficheros a un contenedor durante unos días. El equipo propone una SAS firmada con la clave de la cuenta. ¿Qué señalas?",
    options: [
      "Que es correcto siempre que la SAS se emita con una caducidad corta y permisos de solo escritura",
      "Que no se puede revocar sin rotar la clave de la cuenta: mejor una SAS de delegación de usuario",
      "Que hay que entregarle directamente la clave de la cuenta y rotarla cuando termine el trabajo",
      "Que debe accederse por endpoint privado, con lo que la SAS deja de ser necesaria",
    ],
    correct: 1,
    explain: "El problema de una SAS firmada con la clave de la cuenta es la <b>revocación</b>: si hay que cortarla antes de tiempo, hay que rotar la clave y tumbar a todo lo demás que la use. La <b>SAS de delegación de usuario</b> se firma con una credencial de Entra ID, hereda sus permisos y se revoca revocando esa delegación, sin tocar la cuenta. Entregar la clave es peor. Y el endpoint privado resuelve por dónde se llega, no quién puede. <a href=\"https://learn.microsoft.com/en-us/rest/api/storageservices/create-a-user-delegation-sas\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Que no se pueda borrar",
    q: "Una norma sectorial exige conservar cierta documentación cinco años sin posibilidad de modificarla ni eliminarla, ni siquiera por un administrador. ¿Qué DOS piezas incluye el diseño?",
    options: [
      "Una directiva de inmutabilidad basada en tiempo sobre el contenedor, con el periodo bloqueado",
      "Una regla de ciclo de vida que mueva el contenido a un nivel de acceso esporádico a los treinta días",
      "Roles de datos acotados, de modo que ninguna identidad tenga permiso de eliminación sobre ese contenedor",
      "Control de versiones activado en la cuenta, para conservar copia de cada modificación del contenido",
    ],
    correct: [0, 2],
    explain: "«Ni siquiera por un administrador» exige que el bloqueo esté en la <b>plataforma</b> y no en los permisos: una <b>directiva de inmutabilidad basada en tiempo</b> y, sobre todo, <b>bloqueada</b>, que impide borrar y sobrescribir durante el periodo aunque quien lo intente sea propietario. Se acompaña de <b>roles acotados</b>, porque el mínimo privilegio sigue aplicando. El ciclo de vida gestiona coste y el control de versiones guarda copias, pero no impide el borrado. <a href=\"https://learn.microsoft.com/en-us/azure/storage/blobs/immutable-time-based-retention-policy-overview\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detectar sobre el almacenamiento",
    q: "Sobre una cuenta de almacenamiento ya endurecida —sin acceso público, con endpoint privado y sin claves— se quiere detectar actividad anómala y contenido malicioso subido por clientes. ¿Qué se añade?",
    options: [
      "Registro de diagnóstico de la cuenta enviado a Sentinel, con reglas de análisis escritas por el SOC",
      "Defender CSPM, que evalúa la configuración de la cuenta y recomienda lo que falte por endurecer",
      "Defender for Storage, con análisis de malware en la subida y alertas de acceso anómalo",
      "Una directiva de inmutabilidad sobre los contenedores donde los clientes suben los ficheros",
    ],
    correct: 2,
    explain: "La cuenta ya está bien <b>configurada</b>: lo que falta es <b>detección</b>, y ahí entra <b>Defender for Storage</b>, con análisis de malware en el momento de la subida, alertas por acceso desde identidades o ubicaciones anómalas y detección de exfiltración. Defender CSPM mira configuración, que es lo que ya está resuelto. Los registros en Sentinel obligan a escribir esas detecciones a mano. Y la inmutabilidad protege contra borrado. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
  {
    tag: "Detectar sobre la base de datos",
    q: "Tras un incidente en el sector, la dirección pide poder detectar intentos de inyección SQL y patrones de acceso anómalos sobre las bases de datos de Azure SQL. ¿Qué se activa?",
    options: [
      "Auditoría de la base de datos hacia un espacio de trabajo de Log Analytics, con retención de un año",
      "Seguridad a nivel de fila y enmascaramiento dinámico sobre las tablas con datos de clientes",
      "Un WAF en modo prevención delante de la aplicación que consulta esas bases de datos",
      "Defender for Databases, que alerta de inyección SQL y de accesos anómalos",
    ],
    correct: 3,
    explain: "<b>Defender for Databases</b> es el plan de detección para este servicio: trae escritas las detecciones de inyección SQL, fuerza bruta y patrones de acceso inusuales, y añade evaluación de vulnerabilidades de la configuración. La auditoría deja el rastro pero no alerta sola. El WAF filtra en la aplicación y no ve lo que llega por otros caminos. Y la seguridad a nivel de fila controla acceso, no detecta ataques. <a href=\"https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-databases-introduction\" target=\"_blank\" rel=\"noopener\">Microsoft Learn ↗</a>",
  },
];

// Registrado para el simulacro de examen, que carga los bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["apps-data"] = QUIZ_DATA;
