var QUIZ_DATA = [
  {
    tag: "GuardDuty",
    q: "¿Sobre qué fuentes de datos analiza Amazon GuardDuty el comportamiento para detectar amenazas, sin que tengas que activar logging manualmente en cada cuenta?",
    options: [
      "CloudTrail (eventos de gestión y de datos), VPC Flow Logs, DNS logs, y opcionalmente EKS audit logs y runtime monitoring",
      "Solo CloudTrail",
      "Solo métricas de CloudWatch",
      "Solo logs de aplicación que tú le envíes manualmente",
    ],
    correct: 0,
    explain: "GuardDuty es 'serverless' en el sentido de que consume internamente CloudTrail, VPC Flow Logs y DNS query logs (y opcionalmente EKS audit logs, runtime monitoring de EC2/ECS/EKS, RDS login activity, S3 data events) SIN que tú tengas que activarlos ni gestionarlos por separado — se activa el servicio y ya está analizando.",
  },
  {
    tag: "GuardDuty vs Macie vs Config",
    q: "Necesitas descubrir automáticamente qué buckets S3 de tu cuenta contienen números de tarjetas de crédito o información personal identificable (PII), sin escribir tú las reglas de detección. ¿Qué servicio usas?",
    options: [
      "Amazon GuardDuty",
      "Amazon Macie: usa machine learning y patrones gestionados para descubrir y clasificar automáticamente datos sensibles en S3",
      "AWS Config",
      "Amazon Inspector",
    ],
    correct: 1,
    explain: "Macie está especializado en DESCUBRIMIENTO Y CLASIFICACIÓN de datos sensibles en S3 (PII, credenciales, financieros...) usando machine learning y patrones predefinidos (o personalizados). GuardDuty detecta comportamiento anómalo/amenazas, no clasifica contenido de datos.",
  },
  {
    tag: "AWS Security Hub",
    q: "¿Cuál es el rol principal de AWS Security Hub frente a GuardDuty, Macie e Inspector?",
    options: [
      "Sustituye a los tres, haciendo innecesario tenerlos activados",
      "Solo funciona con recursos EC2",
      "Agrega y normaliza los findings de GuardDuty, Macie, Inspector y otros (incluidos productos de terceros) en un panel centralizado, y además ejecuta sus propios checks de compliance contra estándares (CIS, PCI-DSS, AWS FSBP)",
      "Es un servicio de facturación de seguridad",
    ],
    correct: 2,
    explain: "Security Hub es el AGREGADOR: centraliza findings de múltiples servicios de detección de AWS y de terceros en un solo lugar, y adicionalmente ejecuta sus propios controles de compliance frente a estándares de seguridad reconocidos (CIS AWS Foundations, PCI-DSS, AWS Foundational Security Best Practices).",
  },
  {
    tag: "Automatización de evaluaciones",
    q: "Quieres que un conjunto de reglas de AWS Config (ej. 'todo bucket S3 debe tener cifrado activado') se aplique automáticamente a TODAS las cuentas de una OU en tu organización, de forma centralizada. ¿Qué usas?",
    options: [
      "Config Rules individuales en cada cuenta, replicadas manualmente",
      "Una SCP con el mismo efecto",
      "Amazon Inspector",
      "AWS Config Conformance Packs desplegados a nivel de organización",
    ],
    correct: 3,
    explain: "Los Conformance Packs empaquetan un conjunto de Config Rules (y acciones de remediación opcionales) como una única plantilla desplegable de forma centralizada a nivel de organización, evitando configurar regla por regla en cada cuenta — parte del skill 1.1.5 sobre automatizar evaluaciones regulares.",
  },
  {
    tag: "CloudTrail organizacional",
    q: "¿Qué ventaja tiene configurar un CloudTrail 'organization trail' desde la cuenta de gestión, frente a crear un trail independiente en cada cuenta miembro?",
    options: [
      "El organization trail se aplica automáticamente a TODAS las cuentas (actuales y futuras) de la organización, no puede ser desactivado ni modificado por las cuentas miembro, y centraliza los logs en un único bucket S3",
      "Ninguna, el coste y la cobertura son idénticos",
      "El organization trail no registra eventos de gestión, solo de datos",
      "Solo puede tener un trail organizacional activo en toda la cuenta de gestión",
    ],
    correct: 0,
    explain: "Un organization trail creado desde la cuenta de gestión (o un delegated administrator) se replica automáticamente a todas las cuentas miembro presentes Y futuras, sin que estas puedan desactivarlo, garantizando cobertura completa e inmutable — clave para el skill 1.2.2.",
  },
  {
    tag: "Cuenta de logging dedicada",
    q: "¿Por qué la mejor práctica es enviar los logs de seguridad (CloudTrail, VPC Flow Logs...) a una CUENTA dedicada de logging, separada de las cuentas de carga de trabajo?",
    options: [
      "Es un requisito técnico obligatorio de CloudTrail",
      "Aísla los logs de un posible compromiso de la cuenta de carga de trabajo",
      "Reduce el coste de almacenamiento a la mitad",
      "Permite evitar el uso de KMS",
    ],
    correct: 1,
    explain: "Separar los logs en una cuenta dedicada (con acceso muy restringido, a menudo el 'Log Archive account' de Control Tower) es una defensa contra el escenario donde un atacante que compromete la cuenta de carga de trabajo intenta borrar o alterar la evidencia de sus acciones — los logs ya no están ahí para que los toque.",
  },
  {
    tag: "Amazon Security Lake",
    q: "¿Qué problema resuelve específicamente Amazon Security Lake frente a simplemente centralizar logs en un bucket S3?",
    options: [
      "Ninguno, es solo un bucket S3 con otro nombre",
      "Reemplaza completamente a CloudTrail",
      "Normaliza automáticamente los logs de múltiples fuentes de AWS (y de terceros compatibles) al esquema abierto OCSF, organizándolos en un data lake particionado y optimizado para consulta, sin que tengas que escribir transformaciones ETL",
      "Solo acepta logs de GuardDuty",
    ],
    correct: 2,
    explain: "Security Lake automatiza la ingesta, normalización a OCSF, particionado (por fuente/región/fecha) y gestión del ciclo de vida de logs de seguridad de múltiples cuentas y fuentes (AWS y terceros integrados), eliminando el trabajo manual de ETL que necesitarías si solo centralizaras en un bucket S3 crudo.",
  },
  {
    tag: "Athena vs CloudWatch Logs Insights",
    q: "¿Cuándo es más apropiado usar Amazon Athena en vez de CloudWatch Logs Insights para analizar logs de seguridad?",
    options: [
      "Nunca, son intercambiables en todos los casos",
      "Athena solo puede consultar logs de VPC Flow Logs",
      "CloudWatch Logs Insights no soporta ningún tipo de filtrado",
      "Athena es mejor para consultas SQL ad-hoc sobre grandes volúmenes de datos históricos almacenados en S3 (ej. un data lake de Security Lake); CloudWatch Logs Insights es mejor para consultas rápidas sobre logs recientes que ya están en un log group de CloudWatch",
    ],
    correct: 3,
    explain: "Athena consulta datos en S3 con SQL estándar (ideal para grandes volúmenes históricos, como los datos normalizados de Security Lake). CloudWatch Logs Insights usa su propio lenguaje de consulta optimizado para logs recientes ya ingeridos en CloudWatch Logs — más rápido para investigaciones inmediatas, menos apropiado para análisis histórico masivo.",
  },
  {
    tag: "Normalización y correlación",
    q: "¿Qué servicio de AWS se usa típicamente para construir dashboards de visualización y correlación de eventos de seguridad a partir de múltiples fuentes (Security Lake, OpenSearch, CloudWatch)?",
    options: [
      "Amazon Managed Grafana",
      "AWS Config",
      "AWS Trusted Advisor",
      "Amazon Inspector",
    ],
    correct: 0,
    explain: "Amazon Managed Grafana ofrece un servicio gestionado de Grafana para construir dashboards que correlacionen métricas y logs de múltiples fuentes de datos (CloudWatch, OpenSearch, Athena/Security Lake, Prometheus...) sin gestionar la infraestructura de Grafana tú mismo — skill 1.2.5.",
  },
  {
    tag: "VPC Flow Logs",
    q: "¿Qué información capturan los VPC Flow Logs?",
    options: [
      "El contenido completo (payload) de cada paquete de red",
      "Metadatos de las conexiones IP (origen, destino, puertos, protocolo, bytes, acción ACCEPT/REJECT) a nivel de ENI, subnet o VPC",
      "Solo el tráfico HTTP/HTTPS",
      "Solo los intentos de conexión bloqueados por Security Groups",
    ],
    correct: 1,
    explain: "VPC Flow Logs capturan METADATOS de las conexiones (5-tupla + bytes + acción), similar a un registro de llamadas telefónicas: quién llamó a quién, cuánto duró, pero NO el contenido de la conversación. Son la fuente principal para detectar escaneos de puertos, exfiltración de datos por volumen anómalo, o comunicación con IPs maliciosas.",
  },
  {
    tag: "Route 53 Resolver logs",
    q: "¿Qué visibilidad aportan específicamente los Route 53 Resolver query logs que los VPC Flow Logs no dan?",
    options: [
      "Ninguna, son redundantes",
      "Solo registran fallos de resolución DNS",
      "Capturan las consultas DNS realizadas desde recursos dentro de la VPC (qué dominio se resolvió, respuesta, quién preguntó)",
      "Solo funcionan si se usa Route 53 como registrador del dominio",
    ],
    correct: 2,
    explain: "Mientras VPC Flow Logs ven la conexión IP resultante, los Resolver query logs ven la CONSULTA DNS previa — esencial para detectar malware que resuelve dominios de C2 conocidos, o exfiltración de datos codificados en subconsultas DNS (DNS tunneling), incluso antes de que se establezca la conexión IP.",
  },
  {
    tag: "Troubleshooting de logging",
    q: "Notas que CloudWatch Logs no está recibiendo logs de una instancia EC2 donde el agente CloudWatch (CloudWatch Agent) está instalado y corriendo. ¿Cuáles son las dos causas más probables a revisar primero?",
    options: [
      "El tipo de instancia EC2 elegido y la versión del sistema operativo",
      "El tamaño del volumen EBS",
      "La zona horaria del servidor",
      "El archivo de configuración del agente (qué logs/rutas está configurado a enviar) y los permisos IAM del Instance Profile (falta el permiso logs:PutLogEvents o similar)",
    ],
    correct: 3,
    explain: "Los dos culpables más comunes al depurar 'el agente corre pero no llegan logs' son: (1) un archivo de configuración del agente mal apuntado (rutas de log incorrectas, log group mal referenciado) y (2) permisos IAM insuficientes en el Instance Profile/execution role para escribir en CloudWatch Logs — exactamente el skill 1.3.2 de remediar 'CloudWatch Agent configuration' y 'missing logs'.",
  },
  {
    tag: "Troubleshooting de logging",
    q: "Un desarrollador reporta que las invocaciones de su función Lambda no generan logs en CloudWatch, aunque la función se ejecuta correctamente. ¿Cuál es la causa más probable a revisar primero?",
    options: [
      "El execution role de la función Lambda no tiene el permiso logs:CreateLogStream / logs:PutLogEvents (parte de la managed policy AWSLambdaBasicExecutionRole)",
      "La función Lambda excede el límite de memoria",
      "La región donde se despliega la función",
      "El runtime de Lambda usado",
    ],
    correct: 0,
    explain: "Lambda necesita que su execution role tenga permisos explícitos para escribir en CloudWatch Logs (normalmente vía la managed policy AWSLambdaBasicExecutionRole). Si faltan, la función se ejecuta con normalidad (el fallo de logging no bloquea la ejecución) pero simplemente no aparece nada en CloudWatch — un caso clásico de troubleshooting del skill 1.3.1.",
  },
  {
    tag: "Amazon API Gateway logging",
    q: "¿Qué tipo de logging hay que activar explícitamente en Amazon API Gateway para capturar el cuerpo (body) de las peticiones y respuestas, útil para depurar problemas de autorización?",
    options: [
      "Execution logging por defecto ya lo incluye siempre",
      "Data trace logging (a nivel de stage), que además de los logs de ejecución estándar registra el detalle de request/response",
      "AWS X-Ray automáticamente sin configuración",
      "No es posible capturar el body en ningún caso",
    ],
    correct: 1,
    explain: "API Gateway distingue entre 'execution logging' (metadatos de la ejecución: errores, latencia) y 'data trace logging' (detalle completo de request/response, incluyendo headers y body). El data trace se activa aparte porque expone información potencialmente sensible en los logs — relevante para el skill 1.3.1 sobre analizar la configuración de logging de recursos.",
  },
  {
    tag: "CloudFront logging",
    q: "¿Qué dos modalidades de logging ofrece Amazon CloudFront para analizar las peticiones que llegan a una distribución?",
    options: [
      "Solo un tipo de log, sin opciones",
      "Solo logs en tiempo real, sin opción de logs diferidos",
      "Standard logging (logs de acceso entregados a S3 con cierto retraso) y Real-time logs (enviados a Kinesis Data Streams con latencia de segundos, para alertar casi en tiempo real)",
      "CloudFront no soporta logging nativo, hay que usar un WAF aparte",
    ],
    correct: 2,
    explain: "Standard logs (access logs) se entregan a un bucket S3 con cierto retraso y son gratuitos, ideales para análisis histórico/forense. Real-time logs se envían a Kinesis Data Streams en segundos, permitiendo alertar o reaccionar casi inmediatamente a patrones de tráfico — la elección depende de si necesitas velocidad (real-time) o análisis diferido barato (standard).",
  },
  {
    tag: "Aggregar findings multi-cuenta",
    q: "Para tener una vista consolidada de los findings de GuardDuty y Security Hub de TODAS las cuentas de tu organización sin iniciar sesión en cada una, ¿qué patrón se usa?",
    options: [
      "Copiar manualmente los findings a una hoja de cálculo",
      "Usar SCPs para forzar la consolidación",
      "No es posible consolidar findings entre cuentas",
      "Designar una cuenta como 'delegated administrator' de GuardDuty y Security Hub, que agrega automáticamente los findings de todas las cuentas miembro de la organización en un panel único",
    ],
    correct: 3,
    explain: "Tanto GuardDuty como Security Hub soportan el modelo de 'delegated administrator': una cuenta designada (normalmente la de seguridad/logging) ve y gestiona automáticamente los findings de todas las cuentas miembro de la Organization, sin necesidad de iniciar sesión en cada una individualmente.",
  },
  {
    tag: "Análisis de workloads",
    q: "Antes de diseñar una estrategia de monitorización para una nueva carga de trabajo, ¿qué debes analizar primero según el skill 1.1.1?",
    options: [
      "Los requisitos de monitorización de la carga de trabajo",
      "El coste mensual estimado de la carga de trabajo únicamente",
      "El nombre que se le va a dar a la carga de trabajo",
      "El proveedor de CI/CD que se usará",
    ],
    correct: 0,
    explain: "El skill 1.1.1 (analizar workloads para determinar requisitos de monitorización) es la base antes de elegir herramientas: sin entender qué activos hay, qué eventos importan y qué SLA de detección se necesita, cualquier configuración de GuardDuty/Security Hub/alarmas será genérica en vez de ajustada al riesgo real de esa carga de trabajo.",
  },
  {
    tag: "Health checks",
    q: "En el contexto del skill 1.1.2 (diseñar estrategias de monitorización de workloads configurando health checks), ¿qué diferencia a un health check de Route 53 de una alarma de CloudWatch básica?",
    options: [
      "Son exactamente lo mismo",
      "Un Route 53 health check verifica activamente la disponibilidad de un endpoint desde múltiples ubicaciones globales (y puede desencadenar failover DNS), mientras que una alarma de CloudWatch reacciona pasivamente a métricas que el propio recurso ya está publicando",
      "Los health checks de Route 53 solo funcionan con instancias EC2",
      "CloudWatch no puede alarmar sobre la salud de un endpoint",
    ],
    correct: 1,
    explain: "Route 53 health checks hacen sondeos ACTIVOS periódicos a un endpoint desde ubicaciones distribuidas globalmente, útiles para decidir failover de DNS. Las alarmas de CloudWatch son PASIVAS: consumen métricas ya publicadas (por el recurso o por ti) y disparan una acción cuando cruzan un umbral — ambos son piezas de una estrategia de monitorización, con propósitos distintos.",
  },
  {
    tag: "OCSF",
    q: "¿Por qué Amazon Security Lake normaliza los logs al formato OCSF en vez de guardarlos en su formato original de cada servicio?",
    options: [
      "Por requisito legal de la SEC",
      "OCSF reduce el tamaño de los logs a la mitad automáticamente",
      "Para que herramientas de análisis y SIEMs de terceros puedan consultar y correlacionar eventos de fuentes completamente distintas (CloudTrail, GuardDuty, firewalls de terceros...) usando un esquema común, sin escribir un parser distinto para cada formato propietario",
      "Es un requisito técnico de S3 para poder consultar con Athena",
    ],
    correct: 2,
    explain: "El valor de OCSF es la INTEROPERABILIDAD: un evento de autenticación de CloudTrail y uno de un firewall de terceros, ambos normalizados a OCSF, comparten la misma estructura de campos — permitiendo correlacionar 'inicio de sesión fallido' en ambas fuentes con una sola consulta, en vez de escribir lógica de parsing distinta para cada producto.",
  },
  {
    tag: "GuardDuty Extended Threat Detection",
    q: "Un analista de seguridad revisa Security Hub y ve un finding de severidad CRÍTICA que GuardDuty nunca había emitido antes con ese nivel, titulado algo como 'AttackSequence:IAM/CompromisedCredentials'. El finding agrupa varios eventos individuales (descubrimiento de privilegios, manipulación de API, persistencia) ocurridos en un periodo de tiempo. ¿Qué característica de GuardDuty generó este finding?",
    options: [
      "GuardDuty Malware Protection, que escanea volúmenes EBS en busca de malware",
      "AWS Config, que evalúa el estado de configuración de los recursos implicados",
      "Amazon Detective, que genera automáticamente hallazgos sin necesidad de GuardDuty",
      "GuardDuty Extended Threat Detection, que usa IA/ML para correlacionar múltiples findings individuales de baja/media severidad en una sola secuencia de ataque (attack sequence) de severidad crítica, mapeada a tácticas MITRE ATT&CK",
    ],
    correct: 3,
    explain: "GuardDuty Extended Threat Detection (GA diciembre 2024) analiza patrones a través de múltiples fuentes y periodos de tiempo para generar 'attack sequence findings' (prefijo AttackSequence:) que representan una cadena de pasos de un atacante (descubrimiento, movimiento, persistencia, exfiltración) como un único hallazgo de severidad CRÍTICA — un nivel que GuardDuty no usaba antes de esta función. Se diferencia de Detective, que ayuda a INVESTIGAR relaciones entre findings ya generados, no a generarlos.",
  },
  {
    tag: "GuardDuty Malware Protection for S3",
    q: "Una aplicación permite a usuarios externos subir archivos directamente a un bucket S3 antes de que un pipeline los procese. El equipo de seguridad quiere escanear automáticamente cada objeto nuevo en busca de malware ANTES de que el pipeline lo consuma, sin desplegar ni mantener su propia infraestructura de escaneo. ¿Qué solución nativa de AWS cumple este requisito?",
    options: [
      "GuardDuty Malware Protection for S3",
      "Activar Amazon Inspector sobre el bucket S3",
      "Configurar Macie con un job de clasificación en el bucket",
      "Habilitar cifrado SSE-KMS en el bucket, que bloquea automáticamente archivos maliciosos",
    ],
    correct: 0,
    explain: "GuardDuty Malware Protection for S3 (GA junio 2024) escanea de forma gestionada y sin agentes los objetos nuevos subidos a buckets S3 seleccionados, disparándose ante el evento s3:ObjectCreated, y puede etiquetar el objeto o dispararte una remediación automática según se configure. Macie clasifica CONTENIDO sensible (PII), no detecta malware; Inspector evalúa vulnerabilidades de EC2/ECR/Lambda, no objetos S3; el cifrado no analiza el contenido del archivo.",
  },
  {
    tag: "GuardDuty Malware Protection for EC2",
    q: "¿Cómo escanea GuardDuty Malware Protection for EC2 (activado tras un finding de una instancia potencialmente comprometida) el disco de esa instancia en busca de malware, sin afectar al rendimiento de la instancia en producción?",
    options: [
      "Instala un agente dentro del sistema operativo de la instancia en ejecución y escanea en caliente",
      "Toma un snapshot de los volúmenes EBS adjuntos a la instancia sospechosa y escanea ese snapshot de forma aislada y agentless, sin tocar la instancia original en ejecución",
      "Reinicia la instancia en modo de recuperación para escanear el disco offline",
      "Requiere detener la instancia antes de poder escanear cualquier volumen",
    ],
    correct: 1,
    explain: "GuardDuty Malware Protection for EC2 es AGENTLESS: cuando se dispara (automáticamente tras ciertos findings o bajo demanda), toma un snapshot de los volúmenes EBS de la instancia/contenedor sospechoso y escanea ESE snapshot en una cuenta de escaneo gestionada por AWS, sin instalar nada en la instancia original ni afectar su disponibilidad o rendimiento, y sin necesidad de detenerla ni reiniciarla.",
  },
  {
    tag: "GuardDuty RDS Protection",
    q: "Una empresa usa clústeres Aurora PostgreSQL. Quieren detectar intentos de fuerza bruta contra las credenciales de la base de datos y accesos desde patrones de login inusuales, sin modificar el motor de la base de datos ni degradar su rendimiento. ¿Qué función de GuardDuty resuelve esto?",
    options: [
      "GuardDuty Malware Protection for S3",
      "Amazon Inspector, escaneando vulnerabilidades del motor Aurora",
      "GuardDuty RDS Protection: perfila y monitoriza la actividad de login (éxitos y fallos) en bases de datos Aurora/RDS mediante modelos de ML, generando findings como CredentialAccess:RDS/AnomalousBehavior.SuccessfulLogin o .FailedLogin, sin requerir cambios en la base de datos",
      "AWS Config, evaluando si el cifrado en reposo está activado",
    ],
    correct: 2,
    explain: "GuardDuty RDS Protection monitoriza y perfila la actividad de login de las bases de datos Aurora (MySQL y PostgreSQL compatible), RDS for PostgreSQL y Aurora PostgreSQL Limitless Database, sin necesidad de agentes ni cambios en el motor, generando findings de credenciales anómalas (login exitoso desde IP/patrón inusual, o pico de intentos fallidos indicativo de fuerza bruta) con contexto enriquecido sobre la base de datos afectada.",
  },
  {
    tag: "GuardDuty Lambda Protection",
    q: "Un equipo sospecha que una función Lambda ha sido comprometida y está siendo usada para minar criptomonedas o comunicarse con un servidor de Comando y Control (C2), incluso en funciones que NO están configuradas dentro de una VPC. ¿Qué función de GuardDuty detecta este comportamiento?",
    options: [
      "AWS X-Ray, analizando las trazas de las invocaciones",
      "Amazon Inspector, escaneando el código de la función en busca de malware",
      "AWS Config, evaluando la configuración de red de la función",
      "GuardDuty Lambda Protection, que monitoriza los logs de actividad de red generados por TODAS las funciones Lambda de la cuenta (estén o no configuradas con VPC) para detectar comunicación con IPs/dominios maliciosos conocidos o patrones de minado de criptomonedas",
    ],
    correct: 3,
    explain: "GuardDuty Lambda Protection analiza los logs de actividad de red generados cada vez que se invoca una función Lambda de la cuenta —incluidas las funciones SIN configuración de VPC— para detectar tráfico saliente hacia infraestructura maliciosa conocida (C2, minería de criptomonedas), aplicando filtros inteligentes para cobrar solo por el subconjunto de esos logs de red relevante para la detección.",
  },
  {
    tag: "GuardDuty EKS Runtime Monitoring",
    q: "Al activar GuardDuty EKS Runtime Monitoring en un clúster EKS, ¿cómo se despliega el agente de seguridad para obtener visibilidad a nivel de sistema operativo (ejecución de procesos, acceso a ficheros, conexiones de red) en cada nodo?",
    options: [
      "Como el EKS add-on 'aws-guardduty-agent', desplegado como un DaemonSet basado en eBPF que se ejecuta en cada nodo compatible del clúster",
      "Como un sidecar container inyectado en cada pod",
      "No requiere ningún agente, analiza únicamente los audit logs de EKS",
      "Como una función Lambda que se ejecuta periódicamente contra la API de Kubernetes",
    ],
    correct: 0,
    explain: "Para EKS, el agente de GuardDuty se distribuye como el EKS add-on 'aws-guardduty-agent' y se despliega como un DaemonSet (una instancia del agente por cada nodo compatible del clúster), construido sobre eBPF para obtener telemetría del kernel con bajo overhead. Esto contrasta con el despliegue en ECS Fargate, donde el agente se inyecta como sidecar container en cada task, porque Fargate no expone nodos persistentes donde correr un DaemonSet.",
  },
  {
    tag: "GuardDuty ECS/Fargate Runtime Monitoring",
    q: "Una organización ejecuta la mayoría de sus cargas de trabajo en Amazon ECS sobre Fargate (sin gestionar instancias EC2 ni nodos). ¿Cómo despliega GuardDuty el agente de Runtime Monitoring en este caso, dado que Fargate no expone nodos persistentes donde correr un DaemonSet?",
    options: [
      "No es posible usar Runtime Monitoring en Fargate, solo en ECS sobre EC2",
      "GuardDuty inyecta automáticamente un contenedor sidecar (con prefijo 'aws-guardduty-agent-') dentro de cada ECS task de Fargate al activar la gestión automatizada del agente, sin que tengas que modificar manualmente las definiciones de tarea",
      "Requiere que el cliente construya su propia imagen de contenedor con el agente incluido manualmente en cada Dockerfile",
      "Se despliega como una extensión de CloudWatch Agent dentro del propio contenedor de la aplicación",
    ],
    correct: 1,
    explain: "A diferencia de EKS (DaemonSet por nodo), en ECS Fargate GuardDuty despliega el agente como un CONTENEDOR SIDECAR adicional dentro de cada task —visible como un contenedor con prefijo 'aws-guardduty-agent-'— inyectado automáticamente cuando se activa la gestión automatizada del agente (ECS_FARGATE_AGENT_MANAGEMENT) o mediante tags de inclusión en el clúster, sin necesidad de modificar las definiciones de tarea existentes.",
  },
  {
    tag: "Security Hub: risk prioritization",
    q: "Desde finales de 2025, AWS reorganizó Security Hub: el servicio de checks de compliance que existía hasta entonces (CIS, PCI-DSS, AWS FSBP) pasó a llamarse 'Security Hub CSPM' y ahora es un subcomponente de un 'nuevo' Security Hub más amplio. ¿Qué capacidad adicional aporta este nuevo Security Hub sobre el Security Hub CSPM original?",
    options: [
      "Sustituye la necesidad de tener GuardDuty o Inspector activados",
      "Elimina el uso de ASFF/OCSF como formato de findings",
      "Correlación y priorización de riesgo casi en tiempo real",
      "Solo añade un dashboard de costes de seguridad, sin cambios funcionales",
    ],
    correct: 2,
    explain: "El nuevo Security Hub (GA general a finales de 2025) añade una capa de análisis de riesgo que correlaciona automáticamente señales de múltiples servicios (Security Hub CSPM, Inspector, GuardDuty, Macie) para producir 'exposure findings' — contexto de negocio sobre qué hallazgos combinados representan el mayor riesgo real (ej. exposición pública + vulnerabilidad crítica + datos sensibles), en vez de exigir que un analista correlacione manualmente miles de findings individuales de baja prioridad. Sigue necesitando que GuardDuty/Inspector estén activados como fuentes.",
  },
  {
    tag: "CloudTrail network activity events",
    q: "Tu organización usa VPC endpoints (AWS PrivateLink) para que las cargas de trabajo accedan a servicios como S3 o KMS sin salir a Internet. Quieres auditar la actividad de API que atraviesa esos VPC endpoints, incluida la generada por servicios de AWS actuando en tu nombre, algo que el CloudTrail estándar (management/data events) no siempre refleja con el mismo detalle. ¿Qué función usas?",
    options: [
      "VPC Flow Logs, que ya capturan el detalle de la API invocada",
      "Amazon Detective, que reconstruye automáticamente esas llamadas",
      "GuardDuty, activando la fuente de datos S3",
      "CloudTrail network activity events for VPC endpoints",
    ],
    correct: 3,
    explain: "CloudTrail network activity events for VPC endpoints (GA febrero 2025) es un nuevo TIPO de evento, distinto de los management/data events tradicionales, que da visibilidad sobre la actividad de API que pasa a través de un VPC endpoint para los servicios soportados — incluyendo llamadas hechas por servicios de AWS en tu nombre. VPC Flow Logs solo ven metadatos de red (IP/puerto), no qué API se invocó.",
  },
  {
    tag: "Route 53 DNS Firewall Advanced",
    q: "Un equipo de seguridad ha configurado Route 53 Resolver DNS Firewall con listas de dominios gestionadas (malware, botnets conocidos) pero sigue preocupado por malware que genera dominios aleatorios mediante un Domain Generation Algorithm (DGA) o que usa DNS tunneling para exfiltrar datos — técnicas diseñadas para evadir listas estáticas de dominios. ¿Qué capacidad de DNS Firewall aborda específicamente esta amenaza?",
    options: [
      "DNS Firewall Advanced (protección avanzada contra amenazas DNS), que analiza el patrón de las propias consultas —en vez de comparar contra una lista fija de dominios— para detectar DGA y DNS tunneling en base a un umbral de confianza configurable",
      "Aumentar el TTL de las respuestas DNS en la zona alojada",
      "Activar DNSSEC en la zona hospedada de Route 53",
      "Migrar las consultas DNS a un resolver de terceros fuera de la VPC",
    ],
    correct: 0,
    explain: "Las reglas 'Foundational' de DNS Firewall bloquean contra listas de dominios conocidos (maliciosos, gestionadas por AWS o Recorded Future). DNS Firewall Advanced añade un tier de reglas que analiza el PATRÓN de la consulta (longitud, entropía, estructura) para detectar técnicas diseñadas precisamente para evadir listas estáticas, como DGA y DNS tunneling, permitiendo ajustar un 'confidence_threshold' en vez de depender solo de listas de dominios.",
  },
  {
    tag: "Amazon Detective finding groups",
    q: "Un analista tiene decenas de findings de GuardDuty de severidad baja/media aparentemente inconexos en Security Hub, y sospecha que varios pertenecen a la misma campaña de ataque pero no tiene tiempo de correlacionarlos manualmente. ¿Qué función de Amazon Detective le ayuda directamente con esto?",
    options: [
      "Detective genera automáticamente nuevos findings de GuardDuty que sustituyen a los originales",
      "Finding groups: Detective usa machine learning para agrupar automáticamente findings relacionados (que comparten recursos, roles IAM o IPs de origen) que en conjunto revelan el ciclo de vida de un ataque, e incluye resúmenes en lenguaje natural generados con IA generativa",
      "Detective reemplaza a Security Hub como panel de agregación de findings",
      "Detective solo puede analizar un finding a la vez, sin capacidad de agrupación",
    ],
    correct: 1,
    explain: "Los finding groups de Amazon Detective usan ML para identificar qué findings de GuardDuty (y también de Inspector) están relacionados por compartir entidades (mismo rol IAM, misma sesión, misma IP), agrupando señales de baja severidad que aisladas podrían ignorarse, pero que juntas muestran una campaña de ataque completa — e incluye resúmenes generados con IA generativa en lenguaje natural para acelerar la investigación.",
  },
  {
    tag: "Macie automated sensitive data discovery",
    q: "Una cuenta tiene cientos de buckets S3 con petabytes de datos. El equipo quiere mantener visibilidad CONTINUA de qué buckets contienen datos sensibles sin pagar por escanear cada objeto completo de forma recurrente, algo que sería prohibitivamente caro. ¿Qué capacidad de Macie está diseñada específicamente para este caso?",
    options: [
      "Un sensitive data discovery job programado para ejecutarse diariamente sobre el 100% de los objetos",
      "Amazon Inspector, aplicado a los buckets S3 de la cuenta",
      "Automated sensitive data discovery",
      "GuardDuty S3 Protection, que ya incluye clasificación de contenido",
    ],
    correct: 2,
    explain: "Automated sensitive data discovery es la capacidad de Macie que evalúa el inventario de S3 de forma continua (diaria) y aplica MUESTREO inteligente sobre un subconjunto representativo de objetos por bucket, en vez de escanear cada objeto — manteniendo visibilidad actualizada de qué buckets tienen datos sensibles a una fracción del coste de un job de clasificación exhaustivo. Los sensitive data discovery jobs tradicionales (puntuales o programados) siguen existiendo para análisis exhaustivo y dirigido cuando se necesita examinar el 100% de un alcance concreto.",
  },
  {
    tag: "AWS Security Incident Response",
    q: "Una organización quiere que, cuando GuardDuty o Security Hub CSPM generen un finding crítico, se dispare automáticamente un flujo de triage, y tener acceso 24/7 a un equipo de respuesta a incidentes de AWS para colaborar en la contención, sin construir ellos mismos esa integración desde cero. ¿Qué servicio de AWS cubre este caso de uso?",
    options: [
      "AWS Trusted Advisor",
      "AWS Config, mediante una remediación automática",
      "Amazon Detective, activando un supuesto 'modo incident response'",
      "AWS Security Incident Response",
    ],
    correct: 3,
    explain: "AWS Security Incident Response (GA diciembre 2024) es un servicio dedicado que ingesta y triagea automáticamente findings de GuardDuty y de Security Hub CSPM (incluyendo integraciones de terceros vía Security Hub), ofrece herramientas de colaboración para la respuesta, puede tomar acciones de contención con tu permiso, y da acceso directo 24/7 al AWS Customer Incident Response Team — no es una funcionalidad de Trusted Advisor, Detective ni Config.",
  },
  {
    tag: "Security Lake rollup regions",
    q: "Una empresa opera en tres regiones de AWS y, por motivos de cumplimiento normativo, necesita que los datos de seguridad de Security Lake de cada región permanezcan también disponibles localmente, pero además quiere consolidar una copia de todas ellas en una única región para análisis centralizado. ¿Qué concepto de Security Lake permite esto?",
    options: [
      "Rollup regions: se designa una región como 'rollup' que recibe una copia de los datos de una o varias 'contributing regions', sin eliminar los datos originales de sus regiones de origen",
      "Security Lake solo puede operar en una única región por organización",
      "Cross-region replication de S3, configurada manualmente al margen de Security Lake",
      "AWS Config aggregator, redirigido para consolidar los datos de Security Lake",
    ],
    correct: 0,
    explain: "Security Lake permite designar una o más rollup regions que reciben una COPIA de los datos de las contributing regions especificadas (los datos originales siguen existiendo en sus regiones/buckets de origen, cumpliendo requisitos de residencia de datos), dando además un único punto de integración para herramientas de análisis centralizadas — configurable vía consola o la API UpdateDataLake.",
  },
  {
    tag: "CloudWatch cross-account observability",
    q: "El equipo de seguridad quiere ver, desde una única cuenta central de monitorización, las métricas, logs de CloudWatch Logs y trazas de X-Ray generados en decenas de cuentas de carga de trabajo de la organización, SIN copiar ni duplicar esos datos entre cuentas. ¿Qué mecanismo de AWS permite esto?",
    options: [
      "Copiar los log groups de cada cuenta miembro mediante suscripciones de CloudWatch Logs hacia la cuenta central",
      "CloudWatch cross-account observability mediante Observability Access Manager (OAM)",
      "Amazon Security Lake, que ya centraliza automáticamente todas las métricas de CloudWatch",
      "Una organization trail de CloudTrail configurada para incluir métricas de CloudWatch",
    ],
    correct: 1,
    explain: "OAM (Observability Access Manager) es el servicio que sustenta CloudWatch cross-account observability: mediante 'sinks' (en la cuenta de monitorización) y 'links' (desde cada cuenta origen), permite que una cuenta central consulte y visualice métricas, logs y trazas de hasta 100.000 cuentas origen SIN mover ni copiar los datos — se consultan in situ, a diferencia de una solución basada en suscripciones de CloudWatch Logs, que sí replica los logs a otra cuenta.",
  },
  {
    tag: "AWS Config aggregator",
    q: "Quieres tener, desde una única cuenta, una vista consolidada del estado de cumplimiento de las Config Rules y del inventario de recursos de TODAS las cuentas de tu AWS Organization y de todas sus regiones, sin necesariamente convertir esa cuenta en delegated administrator de Security Hub. ¿Qué recurso de AWS Config usas?",
    options: [
      "Un organization trail de CloudTrail apuntando a esa cuenta",
      "Un conformance pack, que por sí solo ya centraliza la visualización sin necesidad de un aggregator",
      "Un AWS Config aggregator a nivel de organización",
      "Amazon Security Lake, redirigiendo únicamente los datos de AWS Config",
    ],
    correct: 2,
    explain: "Un Config aggregator (en su variante de organización) es un recurso específico de AWS Config que recopila y consolida en una única cuenta el estado de configuración de recursos y el cumplimiento de Config Rules de todas las cuentas miembro y regiones habilitadas de la Organization — es un concepto independiente del delegated administrator de Security Hub/GuardDuty, aunque puedan coexistir en la misma cuenta de seguridad. Un conformance pack por sí solo despliega reglas, no agrega su visualización entre cuentas.",
  },
  {
    tag: "Security Hub vs Security Lake aggregation",
    q: "Un arquitecto de seguridad necesita explicar la diferencia entre 'Security Hub cross-region aggregation' y las 'rollup regions' de Amazon Security Lake, ya que ambas suenan a 'centralizar datos de varias regiones'. ¿Cuál es la distinción correcta?",
    options: [
      "Son exactamente el mismo mecanismo con nombres distintos según el servicio",
      "Ambas funciones requieren obligatoriamente tener Security Lake activado como prerrequisito técnico",
      "Security Hub cross-region aggregation solo funciona dentro de una misma cuenta, mientras que Security Lake rollup regions funciona entre organizaciones distintas",
      "Security Hub cross-region aggregation consolida FINDINGS de Security Hub (y de los servicios que alimenta) de múltiples regiones en una región agregadora para verlos en un panel único; las rollup regions de Security Lake consolidan copias de los LOGS normalizados en OCSF de múltiples regiones en un bucket de una región de destino — operan sobre datos y capas distintas",
    ],
    correct: 3,
    explain: "Aunque ambas resuelven 'quiero ver datos de varias regiones en un solo sitio', operan sobre capas distintas: Security Hub cross-region aggregation trabaja con FINDINGS (el resultado de la detección/evaluación) y los replica hacia una región agregadora designada para el panel de Security Hub; Security Lake rollup regions trabaja con LOGS crudos normalizados a OCSF y replica copias de esos logs hacia una región de destino para análisis. No son intercambiables ni dependen técnicamente la una de la otra.",
  },
  {
    tag: "GuardDuty a escala de organización",
    q: "Una empresa con 180 cuentas en AWS Organizations quiere que GuardDuty esté activo en todas, y que cualquier cuenta nueva quede protegida sin intervención manual. ¿Qué DOS pasos son necesarios?",
    options: [
      "Designar una cuenta como delegated administrator de GuardDuty desde la management account",
      "Activar la opción de auto-enable para que las cuentas nuevas de la organización se incorporen solas",
      "Crear un rol de IAM en cada cuenta miembro que permita a GuardDuty leer CloudTrail",
      "Habilitar GuardDuty manualmente en cada cuenta e invitarlas una a una desde la cuenta central",
    ],
    correct: [0, 1],
    explain: "GuardDuty se gobierna en Organizations con un <b>delegated administrator</b> y la opción de <b>auto-enable</b>, que incorpora las cuentas nuevas sin tocar nada. GuardDuty consume CloudTrail, VPC Flow Logs y DNS logs por su cuenta mediante un service-linked role: no hay que crear roles ni habilitar esos logs. El flujo de invitaciones manuales existe, pero es justo lo que se quiere evitar y no cubre las cuentas futuras.",
  },
  {
    tag: "CloudTrail: eventos de datos",
    q: "Tras un incidente, el equipo descubre que CloudTrail no registró QUIÉN descargó objetos concretos de un bucket S3, aunque sí registró la creación del bucket. ¿Qué DOS afirmaciones explican y resuelven la situación?",
    options: [
      "Los management events registran operaciones sobre el bucket, pero no las operaciones sobre objetos individuales",
      "Hay que habilitar data events de S3 para el bucket y registrar operaciones de lectura como GetObject",
      "CloudTrail nunca puede registrar accesos a objetos: hay que usar exclusivamente S3 server access logging",
      "Basta con aumentar la retención del trail existente para que aparezcan los eventos retroactivamente",
    ],
    correct: [0, 1],
    explain: "CloudTrail separa <b>management events</b> (plano de control: CreateBucket, PutBucketPolicy) de <b>data events</b> (plano de datos: GetObject, PutObject), y los data events están desactivados por defecto porque tienen coste y volumen altos. S3 server access logging es una alternativa, no la única vía. Y la retención nunca genera eventos que no se capturaron: lo que no se registró no existe.",
  },
  {
    tag: "Cuenta de logging inmutable",
    q: "Auditoría exige que los logs de CloudTrail no puedan ser borrados ni alterados por un administrador de la cuenta que los genera, ni siquiera con credenciales root. ¿Qué DOS medidas lo consiguen?",
    options: [
      "Entregar los logs a un bucket S3 en una cuenta de logging dedicada y separada, con su propia bucket policy",
      "Aplicar S3 Object Lock en modo compliance sobre el bucket de destino",
      "Cifrar el bucket con SSE-S3 en lugar de SSE-KMS",
      "Activar el versionado del bucket y confiar en que los administradores no borren versiones",
    ],
    correct: [0, 1],
    explain: "La separación de cuentas quita el poder al administrador de la cuenta origen, y <b>Object Lock en modo compliance</b> impide el borrado incluso a root durante el periodo de retención (el modo governance sí admite excepción con un permiso especial, por eso no vale aquí). El tipo de cifrado no cambia quién puede borrar. El versionado ayuda a recuperar, pero un administrador con permisos puede borrar versiones: confiar no es un control.",
  },
  {
    tag: "Security Hub multi-Región",
    q: "Una organización opera en 5 Regiones y quiere revisar todos los findings de Security Hub desde un único panel, en una sola cuenta y Región. ¿Qué DOS elementos hacen falta?",
    options: [
      "Designar un delegated administrator de Security Hub en la organización",
      "Configurar una Región de agregación que consolide los findings de las demás Regiones",
      "Replicar manualmente los findings con una función Lambda por Región",
      "Desactivar Security Hub en las Regiones secundarias para evitar duplicados",
    ],
    correct: [0, 1],
    explain: "Security Hub necesita <b>delegated administrator</b> para la vista multi-cuenta y <b>cross-Region aggregation</b> para la vista multi-Región; son dos ejes distintos y hacen falta los dos. La replicación con Lambda es reinventar una función nativa. Y desactivar Security Hub en las otras Regiones eliminaría precisamente los findings que se quieren ver: los controles se evalúan donde están los recursos.",
  },
];

// Registrado para el simulacro de examen, que carga los seis bancos a la vez.
(window.QUIZ_BANK = window.QUIZ_BANK || {})["detection"] = QUIZ_DATA;
