const QUIZ_DATA = [
  {
    tag: "GuardDuty",
    q: "¿Sobre qué fuentes de datos analiza Amazon GuardDuty el comportamiento para detectar amenazas, sin que tengas que activar logging manualmente en cada cuenta?",
    options: [
      "Solo CloudTrail",
      "CloudTrail (eventos de gestión y de datos), VPC Flow Logs, DNS logs, y opcionalmente EKS audit logs y runtime monitoring — GuardDuty consume estas fuentes internamente sin que tengas que habilitarlas ni pagarlas tú por separado",
      "Solo métricas de CloudWatch",
      "Solo logs de aplicación que tú le envíes manualmente",
    ],
    correct: 1,
    explain: "GuardDuty es 'serverless' en el sentido de que consume internamente CloudTrail, VPC Flow Logs y DNS query logs (y opcionalmente EKS audit logs, runtime monitoring de EC2/ECS/EKS, RDS login activity, S3 data events) SIN que tú tengas que activarlos ni gestionarlos por separado — se activa el servicio y ya está analizando.",
  },
  {
    tag: "GuardDuty vs Macie vs Config",
    q: "Necesitas descubrir automáticamente qué buckets S3 de tu cuenta contienen números de tarjetas de crédito o información personal identificable (PII), sin escribir tú las reglas de detección. ¿Qué servicio usas?",
    options: [
      "Amazon GuardDuty",
      "Amazon Macie: usa machine learning y patrones gestionados para descubrir y clasificar automáticamente datos sensibles en S3",
      "AWS Config",
      "Amazon Inspector",
    ],
    correct: 1,
    explain: "Macie está especializado en DESCUBRIMIENTO Y CLASIFICACIÓN de datos sensibles en S3 (PII, credenciales, financieros...) usando machine learning y patrones predefinidos (o personalizados). GuardDuty detecta comportamiento anómalo/amenazas, no clasifica contenido de datos.",
  },
  {
    tag: "AWS Security Hub",
    q: "¿Cuál es el rol principal de AWS Security Hub frente a GuardDuty, Macie e Inspector?",
    options: [
      "Sustituye a los tres, haciendo innecesario tenerlos activados",
      "Agrega y normaliza los findings de GuardDuty, Macie, Inspector y otros (incluidos productos de terceros) en un panel centralizado, y además ejecuta sus propios checks de compliance contra estándares (CIS, PCI-DSS, AWS FSBP)",
      "Solo funciona con recursos EC2",
      "Es un servicio de facturación de seguridad",
    ],
    correct: 1,
    explain: "Security Hub es el AGREGADOR: centraliza findings de múltiples servicios de detección de AWS y de terceros en un solo lugar, y adicionalmente ejecuta sus propios controles de compliance frente a estándares de seguridad reconocidos (CIS AWS Foundations, PCI-DSS, AWS Foundational Security Best Practices).",
  },
  {
    tag: "Automatización de evaluaciones",
    q: "Quieres que un conjunto de reglas de AWS Config (ej. 'todo bucket S3 debe tener cifrado activado') se aplique automáticamente a TODAS las cuentas de una OU en tu organización, de forma centralizada. ¿Qué usas?",
    options: [
      "Config Rules individuales en cada cuenta, replicadas manualmente",
      "AWS Config Conformance Packs desplegados a nivel de organización — un paquete de reglas + remediaciones desplegado de forma centralizada a todas las cuentas de una OU",
      "Amazon Inspector",
      "Una SCP con el mismo efecto",
    ],
    correct: 1,
    explain: "Los Conformance Packs empaquetan un conjunto de Config Rules (y acciones de remediación opcionales) como una única plantilla desplegable de forma centralizada a nivel de organización, evitando configurar regla por regla en cada cuenta — parte del skill 1.1.5 sobre automatizar evaluaciones regulares.",
  },
  {
    tag: "CloudTrail organizacional",
    q: "¿Qué ventaja tiene configurar un CloudTrail 'organization trail' desde la cuenta de gestión, frente a crear un trail independiente en cada cuenta miembro?",
    options: [
      "Ninguna, el coste y la cobertura son idénticos",
      "El organization trail se aplica automáticamente a TODAS las cuentas (actuales y futuras) de la organización, no puede ser desactivado ni modificado por las cuentas miembro, y centraliza los logs en un único bucket S3",
      "El organization trail no registra eventos de gestión, solo de datos",
      "Solo puede tener un trail organizacional activo en toda la cuenta de gestión",
    ],
    correct: 1,
    explain: "Un organization trail creado desde la cuenta de gestión (o un delegated administrator) se replica automáticamente a todas las cuentas miembro presentes Y futuras, sin que estas puedan desactivarlo, garantizando cobertura completa e inmutable — clave para el skill 1.2.2.",
  },
  {
    tag: "Cuenta de logging dedicada",
    q: "¿Por qué la mejor práctica es enviar los logs de seguridad (CloudTrail, VPC Flow Logs...) a una CUENTA dedicada de logging, separada de las cuentas de carga de trabajo?",
    options: [
      "Es un requisito técnico obligatorio de CloudTrail",
      "Aísla los logs de un posible compromiso de la cuenta de carga de trabajo: si un atacante compromete la cuenta de producción, no puede alcanzar ni alterar los logs (que ya viven en otra cuenta con permisos mínimos y distintos)",
      "Reduce el coste de almacenamiento a la mitad",
      "Permite evitar el uso de KMS",
    ],
    correct: 1,
    explain: "Separar los logs en una cuenta dedicada (con acceso muy restringido, a menudo el 'Log Archive account' de Control Tower) es una defensa contra el escenario donde un atacante que compromete la cuenta de carga de trabajo intenta borrar o alterar la evidencia de sus acciones — los logs ya no están ahí para que los toque.",
  },
  {
    tag: "Amazon Security Lake",
    q: "¿Qué problema resuelve específicamente Amazon Security Lake frente a simplemente centralizar logs en un bucket S3?",
    options: [
      "Ninguno, es solo un bucket S3 con otro nombre",
      "Normaliza automáticamente los logs de múltiples fuentes de AWS (y de terceros compatibles) al esquema abierto OCSF, organizándolos en un data lake particionado y optimizado para consulta, sin que tengas que escribir transformaciones ETL",
      "Reemplaza completamente a CloudTrail",
      "Solo acepta logs de GuardDuty",
    ],
    correct: 1,
    explain: "Security Lake automatiza la ingesta, normalización a OCSF, particionado (por fuente/región/fecha) y gestión del ciclo de vida de logs de seguridad de múltiples cuentas y fuentes (AWS y terceros integrados), eliminando el trabajo manual de ETL que necesitarías si solo centralizaras en un bucket S3 crudo.",
  },
  {
    tag: "Athena vs CloudWatch Logs Insights",
    q: "¿Cuándo es más apropiado usar Amazon Athena en vez de CloudWatch Logs Insights para analizar logs de seguridad?",
    options: [
      "Nunca, son intercambiables en todos los casos",
      "Athena es mejor para consultas SQL ad-hoc sobre grandes volúmenes de datos históricos almacenados en S3 (ej. un data lake de Security Lake); CloudWatch Logs Insights es mejor para consultas rápidas sobre logs recientes que ya están en un log group de CloudWatch",
      "CloudWatch Logs Insights no soporta ningún tipo de filtrado",
      "Athena solo puede consultar logs de VPC Flow Logs",
    ],
    correct: 1,
    explain: "Athena consulta datos en S3 con SQL estándar (ideal para grandes volúmenes históricos, como los datos normalizados de Security Lake). CloudWatch Logs Insights usa su propio lenguaje de consulta optimizado para logs recientes ya ingeridos en CloudWatch Logs — más rápido para investigaciones inmediatas, menos apropiado para análisis histórico masivo.",
  },
  {
    tag: "Normalización y correlación",
    q: "¿Qué servicio de AWS se usa típicamente para construir dashboards de visualización y correlación de eventos de seguridad a partir de múltiples fuentes (Security Lake, OpenSearch, CloudWatch)?",
    options: [
      "Amazon Managed Grafana",
      "AWS Config",
      "AWS Trusted Advisor",
      "Amazon Inspector",
    ],
    correct: 0,
    explain: "Amazon Managed Grafana ofrece un servicio gestionado de Grafana para construir dashboards que correlacionen métricas y logs de múltiples fuentes de datos (CloudWatch, OpenSearch, Athena/Security Lake, Prometheus...) sin gestionar la infraestructura de Grafana tú mismo — skill 1.2.5.",
  },
  {
    tag: "VPC Flow Logs",
    q: "¿Qué información capturan los VPC Flow Logs?",
    options: [
      "El contenido completo (payload) de cada paquete de red",
      "Metadatos de las conexiones IP (origen, destino, puertos, protocolo, bytes, acción ACCEPT/REJECT) a nivel de ENI, subnet o VPC — NO el contenido/payload del tráfico",
      "Solo el tráfico HTTP/HTTPS",
      "Solo los intentos de conexión bloqueados por Security Groups",
    ],
    correct: 1,
    explain: "VPC Flow Logs capturan METADATOS de las conexiones (5-tupla + bytes + acción), similar a un registro de llamadas telefónicas: quién llamó a quién, cuánto duró, pero NO el contenido de la conversación. Son la fuente principal para detectar escaneos de puertos, exfiltración de datos por volumen anómalo, o comunicación con IPs maliciosas.",
  },
  {
    tag: "Route 53 Resolver logs",
    q: "¿Qué visibilidad aportan específicamente los Route 53 Resolver query logs que los VPC Flow Logs no dan?",
    options: [
      "Ninguna, son redundantes",
      "Capturan las consultas DNS realizadas desde recursos dentro de la VPC (qué dominio se resolvió, respuesta, quién preguntó) — clave para detectar comunicación con dominios de C2 (Command & Control) o técnicas de exfiltración vía DNS tunneling",
      "Solo registran fallos de resolución DNS",
      "Solo funcionan si se usa Route 53 como registrador del dominio",
    ],
    correct: 1,
    explain: "Mientras VPC Flow Logs ven la conexión IP resultante, los Resolver query logs ven la CONSULTA DNS previa — esencial para detectar malware que resuelve dominios de C2 conocidos, o exfiltración de datos codificados en subconsultas DNS (DNS tunneling), incluso antes de que se establezca la conexión IP.",
  },
  {
    tag: "Troubleshooting de logging",
    q: "Notas que CloudWatch Logs no está recibiendo logs de una instancia EC2 donde el agente CloudWatch (CloudWatch Agent) está instalado y corriendo. ¿Cuáles son las dos causas más probables a revisar primero?",
    options: [
      "El tipo de instancia EC2 elegido y la versión del sistema operativo",
      "El archivo de configuración del agente (qué logs/rutas está configurado a enviar) y los permisos IAM del Instance Profile (falta el permiso logs:PutLogEvents o similar)",
      "La zona horaria del servidor",
      "El tamaño del volumen EBS",
    ],
    correct: 1,
    explain: "Los dos culpables más comunes al depurar 'el agente corre pero no llegan logs' son: (1) un archivo de configuración del agente mal apuntado (rutas de log incorrectas, log group mal referenciado) y (2) permisos IAM insuficientes en el Instance Profile/execution role para escribir en CloudWatch Logs — exactamente el skill 1.3.2 de remediar 'CloudWatch Agent configuration' y 'missing logs'.",
  },
  {
    tag: "Troubleshooting de logging",
    q: "Un desarrollador reporta que las invocaciones de su función Lambda no generan logs en CloudWatch, aunque la función se ejecuta correctamente. ¿Cuál es la causa más probable a revisar primero?",
    options: [
      "La función Lambda excede el límite de memoria",
      "El execution role de la función Lambda no tiene el permiso logs:CreateLogStream / logs:PutLogEvents (parte de la managed policy AWSLambdaBasicExecutionRole)",
      "La región donde se despliega la función",
      "El runtime de Lambda usado",
    ],
    correct: 1,
    explain: "Lambda necesita que su execution role tenga permisos explícitos para escribir en CloudWatch Logs (normalmente vía la managed policy AWSLambdaBasicExecutionRole). Si faltan, la función se ejecuta con normalidad (el fallo de logging no bloquea la ejecución) pero simplemente no aparece nada en CloudWatch — un caso clásico de troubleshooting del skill 1.3.1.",
  },
  {
    tag: "Amazon API Gateway logging",
    q: "¿Qué tipo de logging hay que activar explícitamente en Amazon API Gateway para capturar el cuerpo (body) de las peticiones y respuestas, útil para depurar problemas de autorización?",
    options: [
      "Execution logging por defecto ya lo incluye siempre",
      "Data trace logging (a nivel de stage), que además de los logs de ejecución estándar registra el detalle de request/response — debe activarse explícitamente porque puede exponer datos sensibles",
      "AWS X-Ray automáticamente sin configuración",
      "No es posible capturar el body en ningún caso",
    ],
    correct: 1,
    explain: "API Gateway distingue entre 'execution logging' (metadatos de la ejecución: errores, latencia) y 'data trace logging' (detalle completo de request/response, incluyendo headers y body). El data trace se activa aparte porque expone información potencialmente sensible en los logs — relevante para el skill 1.3.1 sobre analizar la configuración de logging de recursos.",
  },
  {
    tag: "CloudFront logging",
    q: "¿Qué dos modalidades de logging ofrece Amazon CloudFront para analizar las peticiones que llegan a una distribución?",
    options: [
      "Solo un tipo de log, sin opciones",
      "Standard logging (logs de acceso entregados a S3 con cierto retraso) y Real-time logs (enviados a Kinesis Data Streams con latencia de segundos, para alertar casi en tiempo real)",
      "Solo logs en tiempo real, sin opción de logs diferidos",
      "CloudFront no soporta logging nativo, hay que usar un WAF aparte",
    ],
    correct: 1,
    explain: "Standard logs (access logs) se entregan a un bucket S3 con cierto retraso y son gratuitos, ideales para análisis histórico/forense. Real-time logs se envían a Kinesis Data Streams en segundos, permitiendo alertar o reaccionar casi inmediatamente a patrones de tráfico — la elección depende de si necesitas velocidad (real-time) o análisis diferido barato (standard).",
  },
  {
    tag: "Aggregar findings multi-cuenta",
    q: "Para tener una vista consolidada de los findings de GuardDuty y Security Hub de TODAS las cuentas de tu organización sin iniciar sesión en cada una, ¿qué patrón se usa?",
    options: [
      "Copiar manualmente los findings a una hoja de cálculo",
      "Designar una cuenta como 'delegated administrator' de GuardDuty y Security Hub, que agrega automáticamente los findings de todas las cuentas miembro de la organización en un panel único",
      "No es posible consolidar findings entre cuentas",
      "Usar SCPs para forzar la consolidación",
    ],
    correct: 1,
    explain: "Tanto GuardDuty como Security Hub soportan el modelo de 'delegated administrator': una cuenta designada (normalmente la de seguridad/logging) ve y gestiona automáticamente los findings de todas las cuentas miembro de la Organization, sin necesidad de iniciar sesión en cada una individualmente.",
  },
  {
    tag: "Análisis de workloads",
    q: "Antes de diseñar una estrategia de monitorización para una nueva carga de trabajo, ¿qué debes analizar primero según el skill 1.1.1?",
    options: [
      "El coste mensual estimado de la carga de trabajo únicamente",
      "Los requisitos de monitorización de la carga de trabajo: qué activos existen, qué eventos son críticos de detectar, qué nivel de latencia de alerta se necesita y qué compliance aplica",
      "El nombre que se le va a dar a la carga de trabajo",
      "El proveedor de CI/CD que se usará",
    ],
    correct: 1,
    explain: "El skill 1.1.1 (analizar workloads para determinar requisitos de monitorización) es la base antes de elegir herramientas: sin entender qué activos hay, qué eventos importan y qué SLA de detección se necesita, cualquier configuración de GuardDuty/Security Hub/alarmas será genérica en vez de ajustada al riesgo real de esa carga de trabajo.",
  },
  {
    tag: "Health checks",
    q: "En el contexto del skill 1.1.2 (diseñar estrategias de monitorización de workloads configurando health checks), ¿qué diferencia a un health check de Route 53 de una alarma de CloudWatch básica?",
    options: [
      "Son exactamente lo mismo",
      "Un Route 53 health check verifica activamente la disponibilidad de un endpoint desde múltiples ubicaciones globales (y puede desencadenar failover DNS), mientras que una alarma de CloudWatch reacciona pasivamente a métricas que el propio recurso ya está publicando",
      "Los health checks de Route 53 solo funcionan con instancias EC2",
      "CloudWatch no puede alarmar sobre la salud de un endpoint",
    ],
    correct: 1,
    explain: "Route 53 health checks hacen sondeos ACTIVOS periódicos a un endpoint desde ubicaciones distribuidas globalmente, útiles para decidir failover de DNS. Las alarmas de CloudWatch son PASIVAS: consumen métricas ya publicadas (por el recurso o por ti) y disparan una acción cuando cruzan un umbral — ambos son piezas de una estrategia de monitorización, con propósitos distintos.",
  },
  {
    tag: "OCSF",
    q: "¿Por qué Amazon Security Lake normaliza los logs al formato OCSF en vez de guardarlos en su formato original de cada servicio?",
    options: [
      "Por requisito legal de la SEC",
      "Para que herramientas de análisis y SIEMs de terceros puedan consultar y correlacionar eventos de fuentes completamente distintas (CloudTrail, GuardDuty, firewalls de terceros...) usando un esquema común, sin escribir un parser distinto para cada formato propietario",
      "OCSF reduce el tamaño de los logs a la mitad automáticamente",
      "Es un requisito técnico de S3 para poder consultar con Athena",
    ],
    correct: 1,
    explain: "El valor de OCSF es la INTEROPERABILIDAD: un evento de autenticación de CloudTrail y uno de un firewall de terceros, ambos normalizados a OCSF, comparten la misma estructura de campos — permitiendo correlacionar 'inicio de sesión fallido' en ambas fuentes con una sola consulta, en vez de escribir lógica de parsing distinta para cada producto.",
  },
];
